### ISSUE TITLE
Selectors: filter undefined values

### ISSUE THREAD

**Issue by dherges** [ngrx/platform#1002]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

I created a repro / example:
https://stackblitz.com/edit/angular-ngrx-effects-1rj88y

Let's look at the following selectors:

```ts

export const selectFoo = createFeatureSelector<State>('foo');

export const selectFooBar = createSelector(selectFoo, state => state.bar);

export const selectFooFoobar = createSelector(selectFoo, state => state.foobar);

export const selectProjectedValues = createSelector(
  selectFooBar,
  selectFooFoobar,
  (foo, foobar) => {
    if (foo && foobar) {
      return { foo, foobar };
    }

    // XX: Is it possible to filter this undefined value in the selector?
    return undefined;
  }
);
```

`selectProjectedValues` will emit an `undefined` value if `foo` or `foobar` have an undefined value.

Filtering the projected `undefined` value would need to happen in the subscribor, e.g.

```ts
store
  .select(selectProjectedValues)
  .pipe(filter(value => !!value))
```

## Expected behavior:

A projected value from  `foo` and `foobar` should be returned, if both states have a defined value. Let's pretend we have a `list` and an `activeItemId`, an active item will be emitted if both the list and the identifier are set. If one of them is undefined, there's no active item.

The question or feature request is: is it possible to filter the undefined value in terms of the `selectProjectedValues` API?

Meaning that `store.select(selectProjectedValues)` will never emit an undefined value.

## Minimal reproduction of the problem with instructions:

See above.

## Version of affected browser(s),operating system(s), npm, node and ngrx:

ngrx@5.2.0

**Comment by dherges** [comment]
One way could be to make selectors become pipeable operators :question: 

```ts
export const selectSomething = pipe(selectOne, selectTwo, map(() => ...), filter(/* .. 
))
```
???

**Comment by dummdidumm** [comment]
I don't think this is possible with the API, and also not wanted. Others may want undefined values to be emitted. Also the select method explicitely is there for emitting every update of the state. I think the way you show it with pipe(filter) is the way to go.

**Comment by dherges** [comment]
The expected behaviour is achieved by either:

```ts
store.pipe(
  map(state => selectProjectedValues(state)),
  filter(val => !!val)
)
```

or alternatively:

```ts
export const selectProjectedValuesFiltered = pipe(
  map(state => selectProjectedValues(state)),
  filter(val => !!val)
);

store.pipe(selectProjectedValuesFiltered)
```

With the current implementation, `store.select(something)` is an alias for `store.pipe(map(state => something(state))`.

---

This issue could also be a documentation request on "Composing a read model" / "Writing a selector API"

**Comment by gioragutt** [comment]
@dherges really love the suggestion.

Considering `select`s are often followed by pipes, why not make it possible to have the selectors `pipable` in the first place, to reduce possible boilerplate of applying the same `piping` after selects.

@brandonroberts is that even possible?

**Comment by dherges** [comment]
@brandonroberts I've started a little blog post series, pt. 1 on [read and write models](https://medium.com/spektrakel-blog/see-query-read-store-717ab9c84311)
