### ISSUE TITLE
`Actions` are undefined with Angular AOT when using barrel imports

### ISSUE THREAD

**Issue by macbem** [ngrx/platform#1009]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
This works both w/ and w/o AOT: 
```
EffectsModule.forRoot([
      EthereumEffects,
      ApiEffects,
      AuthEffects
    ]),
```

This works only without AOT: 
```
EffectsModule.forRoot([
      fromEthereum.EthereumEffects,
      fromApi.ApiEffects,
      fromAuth.AuthEffects
    ]),
```

`from*` are just files that re-export code from other modules, like `export * from './x'`.

## Expected behavior:
Method of importing files should not affect the end result.

I'm not sure if this is a ngrx issue, but I've encountered this in two separate projects so far.

**Comment by tdeschryver** [comment]
What version of ngrx and Angular are you using?
Can this be reproduced in a repo or in [StackBlitz](https://stackblitz.com/)?
