### ISSUE TITLE
RFC: RouterStore changes & enhancements

### ISSUE THREAD

**Issue by dummdidumm** [ngrx/platform#1010]
Related to #975 I'd like to propose some changes / enhancements to the RouterStore.

# Breaking Changes:
- The new default state serializer is that of (or similar to) the example app. It's all you ever need in 90% of the cases. Old defaultSanitizer can be used via flag (see API enhancements).

# API enhancements:
new forRoot properties:
`useEnhancedRouterState`  (boolean):  if true, use old default serializer. Defaults to false.
`routerStateSanitizer` (function): shortcut for `{ provide: RouterStateSerializer, useClass: CustomRouterStateSerializer }`. Defaults to default sanitizer.

# New actions in line with router navigation events
`ROUTER_REQUEST` - fired on NavigationStart
`ROUTER_NAVIGATED` - fired on NavigationEnd
`ROUTER_CANCEL` -> fired on NavigationCancel (same behavior as today)
`ROUTER_ERROR` -> fired on NavigationError (same behavior as today)

The `ROUTER_NAVIGATION` action could stay as is or be an alias for ROUTER_NAVIGATED and/or marked as deprecated to remove it in the next major release.

# Other enhancements / changes:
1. Setting the router reducer in StoreModule.forRoot is no longer necessary (but can still be done)
2. Define a base interface for the router state which all reducer implementations should follow. Right now there is no definition when writing your own and the RouterStore relies on a certain structure. That's a little brittle.
3. It should be possible to redirect/abort navigation inside the reducer without throwing errors
4. To achieve 3, the state is enhanced with a "request" property which contains the desired next route. Will be set on `ROUTER_REQUEST` actions and cleared on other actions. The RouterStore uses this to compare the request object of the state with that from the navigation it just did. If it changed, it will issue a redirect/cancel.

These are all just suggestions and not all of these (or any) need to be implemented. What do you think?

**Comment by brandonroberts** [comment]
I'm mostly in agreement with these changes. We're already using the an alternate default serializer.

1. Setting the router reducer is not required now. Its there for those that don't want to write their own reducer and just want to get router state data.
2. Is this something different than the `RouterReducerState<T>`?
3. Reducers are meant to be synchronous and with side-effects, so maybe this could be handled within an effect?

**Comment by dummdidumm** [comment]
1. true
2. Not different, but `RouterReducerState<T>` only defines `state` as `T`, but in the `StoreRouterConnectingModule`, `this.storeState[this.stateKey].state.url` is accessed. `url` is expected to exist, but someone could right a `state: T` without an `url` property.
3. I think I mixed something up here. The default routerReducer implementation does nothing of the likes, it's just some tests that do it like this. But ultimately, it's up to the user how he designs his customer router reducer (if he wants one).
