### ISSUE TITLE
Enhance action schematic to add an action to an existing actions file

### ISSUE THREAD

**Issue by gioragutt** [ngrx/platform#1016]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

running `ng g action Name` will create a new `name.actions.ts` file, with a stub action.

## Expected behavior:

add a new `--actions` flag, which will specify the name of the actions file.

f.e: Running `ng g action Logout --actions=./auth.actions.ts` will change 3 things - 
* Add the action name to the action types enum. f.e:
```typescript
export enum AuthActionTypes {
  Login = '[Auth] Login',
  ...,
  Logout = '[Auth] Logout', // appended via the schematic
};

* Create an Action class. f.e:
```typescript
export class Logout implements Action {
  readonly type = AuthActionTypes.Logout;
}
```

* Add the Action class to the actions union:
```typescript
export type AuthActions =
  | Login,
  ...,
  | Logout;  // appended via the schematic
```

## Other information:

Scaffolding the file structure is very important on its own, but having more micro-scaffolding is also important.

Having a ability to do what's listed above could reduce the steps needed to use an action to just 2:
* `ng g action <Name> --actions=<supply actions file>`
* optionally add constructor for payload

And from here, you can access the action with `fromAuth` or however the user wishes.

**Comment by vincecampanale** [comment]
Hey @brandonroberts, would you like some help with this?

**Comment by sandangel** [comment]
@gioragutt maybe this is what you want? 
https://github.com/ngrx/platform/issues/1075

**Comment by sandangel** [comment]
@gioragutt  yes ^^

**Comment by gioragutt** [comment]
@sandangel it's worth adding this to the docs

**Comment by sandangel** [comment]
@gioragutt unfortunately I have not received any feedback from @brandonroberts

**Comment by timdeschryver** [comment]
Closing this issue because this became obsolete with the introduction of `createAction`, introduced in NgRx 8.
