### ISSUE TITLE
Missing documentation for @ngrx/schematics@6.x

### ISSUE THREAD

**Issue by mrkvon** [ngrx/platform#1018]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## What is the current behavior?

The documentation of [schematics](https://github.com/ngrx/platform/tree/schematics-6/docs/schematics) is invalid for ngrx v6.x.
I.e. it doesn't show how to correctly wire `@ngrx/schematics` to `@angular/cli@v6.x`

## Expected behavior:

It should be possible to run `ng add @ngrx/schematics@6.0.0-beta.0` or follow a few simple steps in documentation and have `@ngrx/schematics` wired in angular project.

As a result i.e. `ng g entity ...` would work. Currently it errors:
```
Schematic "entity" not found in collection "@schematics/angular".
```

I expect it will appear in the docs eventually. However it would be incredibly useful to have an update there ASAP. So common folks can start using ngrx with angular-cli v6.x without frustration.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
`@angular/cli` v6.x
`@ngrx` v6.x

**Comment by jimbeck** [comment]
Were you able to figure out how to wire it up manually?

**Comment by brandonroberts** [comment]
The command for setting the default schematics has changed to:

```sh
ng config set cli.defaultCollection @ngrx/schematics
```

**Comment by mrkvon** [comment]
@brandonroberts Thank you, it works! (~~set~~)

Additionally, it seems the `ng generate` examples are out of date, too. i.e. former
```
ng g entity User
```
is now
```
ng g entity --name=User
```

**Comment by brandonroberts** [comment]
`ng generate` will be the same. After talking to the CLI team, I updated the schemas to work the same way as before. It will be updated in the next beta

**Comment by blove** [comment]
FWIW, the config command doesn't use get/set. So, the command to configure the Schematics in the updated angular.json is:

```
ng config cli.defaultCollection @ngrx/schematics
```

**Comment by brandonroberts** [comment]
Correct @blove. Anyone want to submit a PR to fix the command for setting the default?

**Comment by blove** [comment]
I'll submit a PR right now.
