### ISSUE TITLE
Add ng update support

### ISSUE THREAD

**Issue by tdeschryver** [ngrx/platform#1028]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
When running `ng update` the `ngrx/**` library is ignored.

## Expected behavior:
To have `ngrx/**` v6 installed when running `ng update` on a project that has a dependency to ngrx v5.2.

I've got a proposition, see [my commit here](https://github.com/tdeschryver/platform/commit/d472795535a5296633ffaf6dd3bda6468e0ea0a1).
To achieve this I've taken a look at rxjs and material because I didn't find any docs, but be aware that I haven't tried it out (yet) tho :sweat_smile:

**Comment by MattiJarvinen-BA** [comment]
Just curious, even though #1028 and #1032 are closed & merged project page doesn't list these as done.

**Comment by brandonroberts** [comment]
It doesn't automatically move them from to done, which I think is consistent with something like JIRA.
