### ISSUE TITLE
@ngrx/store/init firing before effects are listening

### ISSUE THREAD

**Issue by PhillipZada** [ngrx/platform#103]
Since the upgrade, INIT actions are no longer being pickup up via any effects.

I've also confirm that I'mm using the EffectsModule.forRoot([AppEffects])

Test Setup
![image](https://user-images.githubusercontent.com/12227583/28350066-d0d62dd8-6c89-11e7-8d4c-def7bc295b47.png)

**Comment by MikeRyanDev** [comment]
Ah, sorry! This is intentional but we forgot to mention it in the migration guide. You can refactor that action to look like this for the same behavior:

```ts
import { defer } from 'rxjs/observable/defer';

@Effect()
init$: Observable<Action> = defer(() => {
    console.log('ok');
    const username = '';
    const password = '';

    return of(new auth.LoginAction({ username, password });
  });
```

Will gladly accept a PR that adds a more thorough example to the migration guide!

**Comment by zygimantas** [comment]
Strange, if I use

```@Effect() public readonly initEffect = Observable.defer(() => Observable.of(new Action1()));```

then neither Action1, nor any other effect is executed. Probably I haven't migrated properly.

**Comment by gmickel** [comment]
I have the same issue as @zygimantas 

My project has a Init effect that uses defer(). After upgrading to ngrx v4 all actions after the Init effect are no longer run/working.

**Comment by zygimantas** [comment]
@brandonroberts @MikeRyanDev is that a bug and we should reopen this issue or "defer" is not the best way to do it?

**Comment by maxisam** [comment]
If I use defer and return another Observable<Action> directly, it doesn't work.

```
    @Effect() init$ = Observable.defer(() => {
        return Observable.of(this._RootActions.init());
    });

    @Effect() applicationInit$ = this._Actions$
        .ofType(RootActions.INIT)
        .switchMap((action: any) => this.initial());

```
So I double check how defer really works.  http://reactivex.io/documentation/operators/defer.html

> The Defer operator waits until an observer subscribes to it, and then it generates an Observable

I guess defer generate the Observable before next effect observer.

So if I change the sequence, everything works. (Just move `init$` to the bottom of the file.)

**Comment by zygimantas** [comment]
@maxisam I can confirm, that after moving the ```init$``` with ```defer``` to the bottom, ```applicationInit$```, BUT other actions, dispatched from component, using ```this.store.dispatch(new Action3());``` are not handled by effects.

**Comment by maxisam** [comment]
@zygimantas  I don't have the same problem you have.

**Comment by maxisam** [comment]
I think another workaround is dispatching a init action in app root module instead of using defer.

**Comment by zygimantas** [comment]
Nice tip @maxisam !

**Comment by southeastcon2017** [comment]
@maxisam can you give a quick sentence on how you do that? :)

**Comment by Kaffiend** [comment]
Does `startsWith` not work?

**Comment by Kaffiend** [comment]
From what i gather we are trying to accomplish the same thing, on app startup perform something. In my electron app i use the startWith in my init effect to read in the json config file.
```
    // Reads and initializes the client from local config file if exists.
    @Effect() public init$: Observable<fromClientConfig.All>
    = this.actions$.ofType(fromClientConfig.LOAD)
        .startWith(new fromClientConfig.LoadAction())
        .switchMap(() => this.configService.readConf())
        .map((conf) => new fromClientConfig.InitSuccessAction(conf))
        .catch(err => of(new fromClientConfig.InitFailedAction()));
```

**Comment by maxisam** [comment]
@southeastcon2017 dispatching a init action in your app root module? You just need to inject store into your app root component and dispatch an action for your effect to work.

**Comment by zygimantas** [comment]
Or you can do it in onNgInit in app.component.ts, like you do in any other component, if that feels more natural than writing code directly in the module class.

**Comment by dfmartin** [comment]
One thing that appears to work for me right now is to inject the store into my effects class. Then use it from within the defer to dispatch the event I need.

```cs
@Injectable()
export class AppEffects {
  @Effect({dispatch: false} appInit$: Observable<any> = defer(() => {
    console.log('appInit effect')
    this.store.dispatch({ type: 'application_start', payload: { /* some app data */ })
  })

  // some more effects

  constructor(private actions$: Actions, private store: Store<any> {}
}
```

**Comment by rpm911** [comment]
When I added defer to my effects class, the other effects stopped working.  I believe this is the same issue that @zygimantas had.  I tried moving the defer to the bottom of my effects class as suggested by @maxisam and that did not fix it.  Next I tried moving the defer to a separate effects class.  That also did not work **_until_** I made the new effects class the last one in the EffectsModule.forRoot() call.

Guys, this seems awfully fragile and as @maxisam said, this seems like a hack.

**Comment by michaelwaihenya** [comment]
What works for me is creating an action derived class returning type INIT and using startsWith. This is consistent with my other action classes.

import { INIT } from '@ngrx/store';
export class StoreInit implements Action {
    get type() {
        return INIT
    }
}

and then

    @Effect()
    initSession$: Observable<Action> = this.actions$
        .ofType(INIT)
        .startWith(new StoreInit())
        .switchMap(action => this.authService.afAuth.authState)
        .mergeMap(auth => [new SessionStartSuccess(auth ? auth.uid : null)])

**Comment by bbaki** [comment]
For us changing from `@ngrx/store/init` to `@ngrx/effects/init` worked.

**Comment by navrudh** [comment]
`import { ROOT_EFFECTS_INIT } from '@ngrx/effects'` works

**Comment by michelcve** [comment]
I agree with @rpm911 that the current solution is fragile at best. @MikeRyanDev is there a better solution than using defer()?

**Comment by simeyla** [comment]
Wow. This is not the kind of thread you want to read when getting started on @ngrx. 
Is there an official doc what we're supposed to actually do?

**Comment by juanmendes** [comment]
This was closed without a real solution? A bunch of hacks that only work in some cases? Effects/reducers on my app aren't being triggered at all. It'd be great if one of them maintainers did a write up of these common problems with a definitive explanation of these cases, now I have to try all these different approaches and hope one works for me. I'll blame it on myself for only upgrading ngrx > 4 in Nov 2018.

**Comment by jonrimmer** [comment]
The problem with `defer()` is that while it delays *creation* of the observable until it is subscribed, the created observable will still push its value immediately. This will happen while NgRx is still in the process of subscribing to the defined effects, and before later effects have been subscribed to. This is why people are getting different results depending on the order they have defined their effects.

What we really need to do is delay the push of the action instead. The way to do this using RxJS is with a scheduler. Therefore, I would suggest not using `defer()` and instead using the RxJS `asyncScheduler` to delay dispatch of the action to a later event loop task, so NgRx has a chance to finish initializing all the effects before the value is pushed:

```ts
import { asyncScheduler, of } from 'rxjs';

@Effect()
$init = of(new LoginAction({ username, password }), asyncScheduler);
```

**Comment by SebasG22** [comment]
@jonrimmer Thanks, works as expected.

**Comment by Alexei000** [comment]
In @ngrx/store 8.6.0 I was able to make work without any tricks (defer or asyncScheduler):

```
  init$ = createEffect(() => this.actions$.pipe(
			ofType(ROOT_EFFECTS_INIT),
			map(_ => {
				// side effect stuff here
			}),
			switchMap(_ => {
				return EMPTY;
			})
		));
```

This works only if this effect belongs to an Effects class registered in root. [Reference](https://ngrx.io/guide/effects/lifecycle).

**Comment by dmitriydementor** [comment]
@jonrimmer , I have the latest version of NgRx, but when I use

```typescript
@Effect()
$init = of(new notificationActions.loadNotifications(), asyncScheduler)
```

I get compile error `Only a void function can be called with the 'new' keyword.`

My action doesn't have payload:

```typescript
export const loadNotifications = createAction(
    NotificationActionTypes.LoadNotifications,
)
```

Maybe I'm missing something?

**Comment by brandonroberts** [comment]
@dmitriydementor you don't use `new` with an action creator. Just call the function.
