### ISSUE TITLE
Failing schematics generate container

### ISSUE THREAD

**Issue by mrkvon** [ngrx/platform#1030]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

Running `ng g container --name=FooContainer` in @angular/cli project with ngrx/schematics@6.0.0-beta.0 yields an error:
`Could not find an NgModule. Use the skip-import option to skip importing in NgModule.`

Running `ng g container --name=FooContainer --skip-import` leads to another error:
`File /src/app/foo-container/foo-container.component.ts does not exist.`

If an empty file for the given path is created beforehand, command passes, but file remains empty and nothing gets generated. 

## Expected behavior:

`ng g container --name=FooContainer` resp `ng g container FooContainer` creates the desired container seamlessly.

## Minimal reproduction of the problem with instructions:

1. Create a new angular-cli project
2. Install and init ngrx/schematics as described in ngrx/schematics docs
3. Run `ng g container --name=FooContainer`

## Version of affected browser(s),operating system(s), npm, node and ngrx:
npm v6.0.0
node v10.0.0
ngrx/schematics v6.0.0-beta.0
ngrx/* v6.0.0-beta.1
angular, angular-cli v6.x

**Comment by brandonroberts** [comment]
This has already been fixed in master and will go out with the next beta
