### ISSUE TITLE
Add schematics to generate boilerplate for angular router and ngrx/router-store

### ISSUE THREAD

**Issue by ylulloa** [ngrx/platform#1031]
https://www.youtube.com/watch?v=YsG44g6_Fo0

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
</code></pre>

**Comment by vincecampanale** [comment]
@brandonroberts Have you already started on this feature? I'd be interested in working on it.

**Comment by brandonroberts** [comment]
Some of this work is being handled under #920 with the `ng-add` schematics support. Maybe you and @vitaliy-bobrov can coordinate on this?
