### ISSUE TITLE
Store router is not navigating to the right param

### ISSUE THREAD

**Issue by embryologist** [ngrx/platform#1034]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
I followed the setup [here](https://github.com/ngrx/platform/blob/master/docs/router-store/README.md) and [here](https://github.com/ngrx/platform/blob/master/docs/router-store/api.md#navigation-actions) for the router store.

1. dispatching navigation using the following code results in wrong routing,

```
store.dispatch(new RouterActions.Go({
  path: ['/dbapp/registry/patientregistration/edit', { routeParam: 2222 }],
  query: { page: 1 },
  extras: { replaceUrl: false }
});
```
the resulting route is,

> 'dbapp/registry/patientregistration/edit;routeParam=2222'

## Expected behavior:
the correct route should be 

> 'dbapp/registry/patientregistration/edit/2222'

## Version of affected browser(s),operating system(s), npm, node and ngrx:
Angular CLI: 6.0.0
Node: 9.11.1
OS: darwin x64
Angular: 6.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, http, material, platform-browser
... platform-browser-dynamic, router

@ngrx/effects:  4.1.1,
@ngrx/router-store: ^4.1.1,
@ngrx/store: ^4.1.1,
## Other information:

**Comment by SerkanSipahi** [comment]
@embryologist did you try @ngrx/effects: v5.2.0 ?

**Comment by brandonroberts** [comment]
The example shown is for route parameters. Your URL is built from the items in the array. If you just want to provide an ID as part of the URL, you should add it as in item in the array,.

```
['/dbapp/registry/patientregistration/edit', 2222],
```
