### ISSUE TITLE
@ngrx not working with aot compilation

### ISSUE THREAD

**Issue by konradczarnecki** [ngrx/platform#1035]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

@ngrx/store is not working with aot compilation - the state is not created except for the router state from @ngrx/router-store. Everything works fine with jit or when running development server.

## Expected behavior:

@ngrx should work with both aot and jit.

## Minimal reproduction of the problem with instructions:

store.ts
<pre><code>
import { Action } from '@ngrx/store';
import { ActionReducer } from '@ngrx/store';

export const CHANGE_LANGUAGE = '[Change language]';

export class ChangeLanguageAction implements Action {

  readonly type = CHANGE_LANGUAGE;
  constructor(public lang: string) {}
}

export const languageReducer: ActionReducer&lt;string&gt; = (state: string = 'fr', action: ChangeLanguageAction): string => {

  switch (action.type) {

    case CHANGE_LANGUAGE:
      return action.lang;

    default:
      return state;
  }
};

export interface AppState {
  router: object;
  lang: string;
}

export const rootReducer: ActionReducerMap&lt;AppState&gt; = {
  router: undefined,
  lang: languageReducer
};
</code></pre>

app.module.ts
<pre><code>
import { HttpClientModule } from '@angular/common/http';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { BrowserModule } from '@angular/platform-browser';

import { StoreModule } from '@ngrx/store';
import { StoreRouterConnectingModule, routerReducer } from '@ngrx/router-store';
import { StoreDevtoolsModule } from '@ngrx/store-devtools';
import { rootReducer } from './store';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule.withServerTransition({ appId: 'dif-frontend' }),
    FormsModule,
    HttpClientModule,
    AppRoutingModule,
    StoreModule.forRoot({ ...rootReducer, router : routerReducer }),
    StoreRouterConnectingModule.forRoot(),
    StoreDevtoolsModule.instrument({maxAge: 25}),
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {
}

</code></pre>
## Version of affected browser(s),operating system(s), npm, node and ngrx:

Angular 6.0.0
ngrx 6.0.0-beta.1
rxjs 6.1.0
node 9.11
npm 5.6.0

**Comment by brandonroberts** [comment]
You should provide the root reducers to `StoreModule.forRoot` and define your router reducer in that map.
