### ISSUE TITLE
Initialize the store after APP_INITIALIZER

### ISSUE THREAD

**Issue by cmckni3** [ngrx/platform#1037]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

`StoreModule` inits when the application is bootstrapped.

## Expected behavior:

Allow the `StoreModule` to init after `APP_INITIALIZER`

## Version of affected browser(s),operating system(s), npm, node and ngrx:

ngrx: 4.0+

**Comment by cmckni3** [comment]
Thought I needed this for a vendor metareducer. Not necessary.

**Comment by nukec** [comment]
This is still not working.

**Comment by opankov-neocles** [comment]
@cmckni3 , how did you fix the problem? I need the same. I use service with is configured after APP_INITIALIZE used in meta reducers

**Comment by cmckni3** [comment]
@opankov-neocles I don't remember. 

Here's the providers I had

```
    providers: [
        {
            provide: APP_INITIALIZER,
            useFactory: initConfig,
            deps: [ConfigService],
            multi: true,
        },
        {
            provide: META_REDUCERS,
            useFactory: getMetaReducers,
        }
    ]
```
