### ISSUE TITLE
Schematics: Update default action/reducer/effect template to be less generic

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1040]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Other information:

Right now the templates for a generated action blueprint are very generic (e.g.) `[User] Action`. This should be updated to be less generic and more usable out of the box. We should extend this to the reducer and effects also when generating a feature.

```
export enum UserActionTypes {
  LoadUsers = '[User] Load Users'
}

export class LoadUsers implements Action {
  readonly type = UserActionTypes.LoadUsers;
}

export type UserActions = LoadUsers;
```

**Comment by brandonroberts** [comment]
cc: @thomasburleson

**Comment by ThomasBurleson** [comment]
Thanks @brandonroberts. I will work on this enhancement this weekend.

**Comment by ThomasBurleson** [comment]
@brandonroberts - darn. Now I have to check in the Nx Schematics if you have ALREADY done this work above. ;-)
