### ISSUE TITLE
@ngrx/schematics requires rxjs-compat, which update.angular.io asks us to remove once migrated to v6

### ISSUE THREAD

**Issue by alcfeoh** [ngrx/platform#1045]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
NgRx schematics requires rxjs-compat, otherwise the `ng generate store` schematics fails

## Expected behavior:
Angular 6 upgrade instructions ask developers to remove rxjs-compat once migration to RxJs 6 is completed. I cannot do so because @ngrx/schematic needs it.

## Minimal reproduction of the problem with instructions:
- Upgrade to Angular 6 and RxJs 6.1.0
- Install @ngrx/schematics 
- Run `ng generate store State --root --module app.module.ts --collection @ngrx/schematics`
- Error: 'ngrx-compat is required'

**Comment by brandonroberts** [comment]
Are you using the latest beta or 5.2?

**Comment by alcfeoh** [comment]
Using 5.2

**Comment by brandonroberts** [comment]
We will be releasing V6 very soon which only depends on RxJS 6.x. You can use the `6.0.0.beta-1` release or the nightly builds until then.

**Comment by alcfeoh** [comment]
Sounds good, thanks a lot! Is the final 6.0 going to be released before June?

**Comment by brandonroberts** [comment]
V6 has landed with full support for RxJS 6.
