### ISSUE TITLE
RFC: Use tree shakable providers angular v6, deprecate NgModule

### ISSUE THREAD

**Issue by sandangel** [ngrx/platform#1049]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

Tokens and services is provided through static method on StoreModule, EffectModule...

## Expected behavior:

Since ngrx does not provide any directives or components..., we should consider use function to provide services and tokens instead of NgModule and mark all service as `providedIn: 'root'` to take advantage of tree-shakable providers.

For now, we can provide a config function like `provideStoreForRoot(): Provider[]`, provideStoreForFeature() (naming matters, discuss in comments)
and user will use that function like this: `providers: provideStoreForRoot({...})`

Or even better we can provide only 1 function to config all Modules in AppModule like:

```typescript
@NgModule({
  providers: provideNgRxPlatform({store: {}, effects: [], devtools: {}, routerStore: {}})
})
export class AppModule {}
```

and function to config FeatureModule like:

```typescript
@NgModule({
  providers: provideNgRxForFeature({store: {}, effects: []})
})
export class FeatureModule {}
```

We then can deprecate StoreModule... and all Module will be removed in v7

## Other information:
I can prepare a PR if this proposal is accepted.

**Comment by brandonroberts** [comment]
NgModule's aren't going away any time soon, so we'll revisit this another time.
