### ISSUE TITLE
Effect gets called twice when using StoreDevtoolsModule.instrument()

### ISSUE THREAD

**Issue by Exocomp** [ngrx/platform#1054]
I'd appreciate if someone can guide me to what is causing this problem.  Whenever I use StoreDevtoolsModule.instrument() to use the redux dev tools, the effects are called twice for some reason.  I created a simple Angular project to demonstrate this.

Versions: I'm using version 5.2.0 of Angular and all the relevant ngrx packages.

In this example, I have a feature module called "module1", which gets loaded lazily.  Then "module1.component.ts" dispatches the GetName action.  In that action, I simply do a console.log to demonstrate that it gets called twice.

**app.module.ts**
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';
import { AppRoutingModule } from './app-routing.module';
import { StoreModule } from '@ngrx/store';
import { EffectsModule } from '@ngrx/effects';

import { StoreRouterConnectingModule } from '@ngrx/router-store';
import { StoreDevtoolsModule } from '@ngrx/store-devtools';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    StoreModule.forRoot({}),
    EffectsModule.forRoot([]),
    StoreRouterConnectingModule,
    StoreDevtoolsModule.instrument()
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**app-routing.module.ts**
```
// angular imports
import { NgModule } from '@angular/core';
import { Routes, RouterModule, PreloadAllModules } from '@angular/router';

const APP_ROUTES: Routes = [

    { path: 'module1', loadChildren: './module1/module1.module#Module1Module' },

];

@NgModule({
    imports: [
        RouterModule.forRoot(APP_ROUTES, {preloadingStrategy: PreloadAllModules})
    ],
    exports: [
        RouterModule
    ],
    providers: [
    ]
})
export class AppRoutingModule {

}
```

**module1.module.ts**
```
import { NgModule } from '@angular/core';

import { Module1Component } from './module1.component';
import { Module1RoutingModule } from './module1-routing.module';
import { StoreModule } from '@ngrx/store';
import { EffectsModule } from '@ngrx/effects';
import { module1Reducer } from './ngrx-store/module1.reducers';
import { Module1Effects } from './ngrx-store/module1.effects';

@NgModule({
    declarations: [
        Module1Component
    ],
    imports: [
        Module1RoutingModule,
        StoreModule.forFeature('module1', module1Reducer),
        EffectsModule.forFeature([Module1Effects])
    ],
    providers: [
    ]
})
export class Module1Module { }
```

**module1-routing.module.ts**
```
// angular imports
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

import { Module1Component } from './module1.component';

const APP_ROUTES: Routes = [
 
    { path: '', component: Module1Component, children: [
    ] }

];

@NgModule({
    imports: [
        RouterModule.forChild(APP_ROUTES)
    ],
    exports: [RouterModule],
    providers: [
    ]
})
export class Module1RoutingModule {

}
```

**module1.component.ts**
```
import { Component, OnInit } from '@angular/core';

import { Store, State } from '@ngrx/store';

import * as fromModule1 from './ngrx-store/module1.reducers';
import * as Module1Actions from './ngrx-store/module1.actions';

@Component({
  selector: 'app-module1',
  templateUrl: './module1.component.html',
  styleUrls: ['./module1.component.css']
})
export class Module1Component implements OnInit {

  constructor(private store: Store<fromModule1.FeatureState>) { 
    
  }

  ngOnInit() {
    this.store.dispatch(new Module1Actions.GetName());
  }

}
```

**module1.effects.ts**
```
import { Injectable, Inject, PLATFORM_ID } from '@angular/core';
import { Actions, Effect } from '@ngrx/effects';
import { Router } from '@angular/router';
import { isPlatformBrowser } from '@angular/common';

import 'rxjs/add/operator/do';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/switchMap';
import 'rxjs/add/operator/mergeMap';
import { fromPromise } from 'rxjs/observable/fromPromise';

import * as Module1Actions from './module1.actions';
import { environment } from '../../../environments/environment';
import { HttpHeaders, HttpClient } from '@angular/common/http';
import { State } from '@ngrx/store';
import * as fromModule1 from './module1.reducers';

@Injectable()
export class Module1Effects {
    constructor(private actions$: Actions,
        private router: Router,
        @Inject(PLATFORM_ID) private platformId: Object,
        private state: State<fromModule1.State>) { }

    // GET_NAME
    @Effect({dispatch: false})
    getName = this.actions$
        .ofType(Module1Actions.GET_NAME)
        .map(() => {
            console.log("test");  // <----- This gets printed twice in the console
            return "Mike"
        });
}
```

**Comment by brandonroberts** [comment]
An actual reproduction using stackblitz is necessary to resolve this issue. Support questions should be asked on stackoverflow or the [gitter channel](https://gitter.im/ngrx/platform).

**Comment by DaDave** [comment]
I had the same problem. Actions in effects had been called twice. 
It turns out that in imports (app.module) I imported StoreDevtoolsModule AFTER I imported StoreModule. 
After I switched StoreDevtoolsModule and StoreModule everything works fine.

**Comment by vincentjames501** [comment]
I'm running into this exact same thing on version 6.0.1. I'll try to see if I can find anything.

**Comment by vincentjames501** [comment]
@Exocomp , I figured out the problem based on your example which I put here:

https://stackblitz.com/edit/github-sbpnzu

The issue is in module1.effects.ts here:

```typescript
private state: State<fromModule1.State>
```

If you remove this, all is happy!

**Comment by mixalistzikas** [comment]
Yes... I agree... I have the same issue
    ` "@ngrx/effects": "^6.1.0",
      "@ngrx/store": "^6.1.0",
      "@ngrx/store-devtools": "^6.1.0",`

**Comment by brandonroberts** [comment]
Provide a reproduction in StackBlitz so we can take a look

**Comment by vincentjames501** [comment]
@brandonroberts , I already did that above :D

**Comment by F1oyd** [comment]
> https://stackblitz.com/edit/github-sbpnzu

**Comment by brandonroberts** [comment]
Ok, I see. Why are you injecting `State`?

**Comment by sswayney** [comment]
I was having the same issue. I used State instead of Store in one of my Effects. 
Thank you @brandonroberts

**Comment by mtuzinskiy** [comment]
@brandonroberts  Hi! I hope that you don't mean that we should avoid injecting State in all the app?  Only in Effects?  
It still looks like a bug to me (very annoying, as it takes a lot of time to figure out the cause), this issue needs to be reopened.

**Comment by LeVadim** [comment]
Hello!
Same issue here

**Comment by majo44** [comment]
Hello! I have same issue on 8.0.1, ng: 8.0.1, rxjs: 6.5.2
:(

**Comment by TheRisa** [comment]
I've found the same problem.
Avoiding the use of "this.state.getValue()" was the cleaner solution, but removing "import { StoreDevtoolsModule } from '@ngrx/store-devtools';" worked as well.
There may be a conflict between .getValue() and this dependency

**Comment by chikakow** [comment]
Hi this was happening to my dev enviroment with Angular core 8.2.2.  In my case, I was not injecting State and I also removed StoreDevToolsModule but it was still happening.  I just updated the code from v7 to v8 a couple of days ago and I still have lots of v7 style way of actions, reducers, and effects.  But this was only happening to the effect with a new v8 syntax createEffect(() => this.actions$.pipe...) . So I removed that style and just did regular this.actions$.pipe like v7 style.  Then it stopped firing twice and only fire once.  I feel like my case was v8 bug.

**Comment by BovineEnthusiast** [comment]
I've had a similar case to @chikakow. I changed just one of my effects to the old style:

```ts
uploadPhoto$(): Observable<Action> {
    return this.actions$.pipe(
...
```

from 

```ts
uploadPhoto$ = createEffect(() =>
    this.actions$.pipe(
```

and it only fires once now.

**Comment by BovineEnthusiast** [comment]
@brandonroberts I have this issue even when `StoreDevtoolsModule.instrument()` is disabled. I also just had the issue where an effect that doesn't dispatch anything didn't just fire twice but looped (and sent me 3000 emails 😨 ). Should I open a new issue? I'm pretty sure the effects are written correctly:

```ts
createAd$ = createEffect(() =>
    this.actions$.pipe(
      ofType(createAd),
      switchMap((payload) => {
        return this.adModelService.create(payload.ad).pipe(
          map((ad) =>
            createAdSuccess({
              adId: ad.id,
              loggedIn: payload.loggedIn,
              communityCode: payload.ad.classified.communityCode,
            }),
          ),
          catchError(() => of(createAdFailure())),
        )
      }),
    ),
  )

  createAdSuccess$ = createEffect(() =>
    this.actions$.pipe(
      ofType(createAdSuccess),
      tap((payload) => {
        if (payload.loggedIn) {
          this.router.navigate(['cm', payload.communityCode, 'ads', payload.adId, 'conf'], {
            queryParamsHandling: 'merge',
          })
        } else {
          // This is output many times in the console. The whole browser tab becomes unresponsive
          console.log('sending verification email')
          

          // We have a blank subscription here because Angular's HttpClient uses
          // observables and thus won't actually make the call unless there is a
          // subscription
          // this.adFormService
          //   .sendVerificationEmail(payload.adId)
          //   .pipe(first())
          //   .subscribe()
        }
      }),
    ),
  )
```

Should I open a new issue?

**Comment by manklu** [comment]
@BovineEnthusiast https://ngrx.io/guide/effects/lifecycle#non-dispatching-effects

**Comment by BovineEnthusiast** [comment]
Ahh @manklu thanks!

Here were my issues:

1. After upgrading to ngrx 8, I didn't remove the `@Effect()` decorators from the effects I've transitioned to `createEffect`.

2. I removed `{dispatch: false}` from the effects (now using `createEffect`) instead of placing them as the second argument, after the arrow function.

Everything works now.

**Comment by gaborszekely** [comment]
Can confirm, removing the @Effect() decorator from the new Angular 8 "createEffect()" syntax fixed the issue for me.

**Comment by Mutantmannen** [comment]
This must be a bug in v8. Have a new project written from scratch with Angular v 8.2.5 and ngrx v 8.3.0.

Using v8 createEffect(), no use of state nor @Effect() decorator.

Effect fires twice, regardles of StoreDevtoolsModule.instrument enabled or not.

**Comment by Mutantmannen** [comment]
`saveSalesRepresentative$ = createEffect(
    () =>
      this.actions$.pipe(
        ofType(SalesRepresentativesActions.salesRepresentativeUpdated),
        concatMap(action =>
          this.salesRepresentativesDataService.patch(
            action.update.id,
            action.update.changes
          )
        )
      ),
    { dispatch: false }
  );`

This is my effect. Call to dataservice fires twice nomatter how I do it. Tried all approces in this thread.

**Comment by timdeschryver** [comment]
@Mutantmannen can you create a new issue with a reproduction?

**Comment by lalosh** [comment]
For me I was shocked to find out the commenting the code for StoreDevToolsModule in app.module fixed the problem of two actions being dispatched instead of one
```js
    // StoreDevtoolsModule.instrument({
    //      maxAge: 25, // Retains last 25 states
    // }),
```
can anyone help find a fix, so we can keep using the dev tool?

**Comment by brandonroberts** [comment]
@lalosh open a new issue with a reproduction of the issue. Include the version of NgRx you're using.

**Comment by ikemtz** [comment]
So I w

> Can confirm, removing the `@Effect()` decorator from the new Angular 8 `createEffect()` syntax fixed the issue for me.

I was doing an NgRx migration and my effects were firing twice, but that's because I had neglected to remove the @Effect decorator.  I was able to reproduce this behavior using unit tests with Jest, and subsequently validate the fix.
Thanks!

**Comment by jssum** [comment]
Encounter the same issue, commenting the code for StoreDevToolsModule in app.module fixed the problem.

**Comment by manklu** [comment]
@jssum Either one of the solutions here fixes your problem or you should open a new issue with a reproduction.

**Comment by jssum** [comment]
I finally found the root caused of my issue - trigger twice when I using StoreDevToolsModule. 

I inject my service - AuthService in my Effects class.

`export class UserEffects {
    constructor(private auth: AuthService, private actions$: Actions, private router: Router) { }
.....
}`

But in my AuthService class, I use the state to get the value of the store, check my code below:
`
import { Injectable } from "@angular/core";
import { HttpClient, HttpHeaders } from "@angular/common/http";
import { map } from "rxjs/operators";
import { State } from "@ngrx/store";
import { UserState } from "../../state/user.state";
import { of } from "rxjs";


@Injectable({ providedIn: "root" })
export class AuthService {
    key = "auth.user";
    constructor(private http: HttpClient, private state: State<UserState>) {

    }


    login(userCode: string, password: string) {

        const headers = new HttpHeaders();
        headers.append("Content-Type", "application/x-www-form-urlencoded");
        headers.append("Access-Control-Allow-Origin", "/");

        return this.http.post<any>(`http://myAPI.com/token`, `grant_type=password&username=${userCode}&password=${password}`, { headers })
            .pipe(map(response => {

                let user: AuthInfo;
                if (response && response.access_token) {
                   user = {
                        userCode: response.userCode,
                        userName: response.username,
                        token: response.access_token,
                        expiresIn: response.expires_in,
                        tac: response.tac,
                        winAuth: (response.winAuth === "1"),
                        defaultDb: response.defaultDb,
                        internalUser: response.internalUser,

                        defaultOrgCode: response.defaultOrganisationCode,
                        defaultOrgName: response.defaultOrganisationName,
                        defaultOrgDbId: response.orgDbId,
                        defaultOrgFileCode: response.orgFileCode
                    };

                }
                sessionStorage.setItem(this.key, JSON.stringify(user));
                return user;
            }));

    }


    /**
     * Get Token from state
     */
    getToken(): string {

        return this.state.getValue().User.token;
    }
}


// tslint:disable-next-line: interface-name
export interface AuthInfo {
    userCode: string;
    userName: string;
    token: string;
    expiresIn: string;
    tac: boolean;
    winAuth: boolean;
    defaultDb: string;
    internalUser: string;
    defaultOrgCode: string;
    defaultOrgName: string;
    defaultOrgDbId: string;
    defaultOrgFileCode: string;

}`

**Comment by manklu** [comment]
@brandonroberts @timdeschryver Maybe the API documentation for State should contain a big warning not to use it, unless you know what you are doing.

**Comment by tomschreck** [comment]
I was experiencing a scenario where only 1 of my effects was firing multiple times, which lead me to this thread.  It turns out 2 of my actions had the exact same Type:

```
export const requestOccupationDetails = createAction
  (
    '[Occupation] Request Occupation Details',
    props<{ zipCode: string; subOccupationId: number; }>()
  );

export const occupationDetailsReceived = createAction
  (
    '[Occupation] Request Occupation Details',
    props<{ occupationDetails: OccupationDetail; }>()
  );

```

Clipboard inheritance was to blame for the error.  It was not immediately obvious what the issue was.    Hopefully this will help someone not paying attention to pasting...

**Comment by kamenminkov** [comment]
Can confirm that removing a `private store: Store<AppState>` from a component's constructor args (and making sure that no other components have it) fixes the issue - otherwise it manifested for me too with angular 9.0.0-rc.8 and ngrx 8.6.0.

**Comment by kevinbeal** [comment]
You'll also get effects firing twice if you subscribe it the effect subscription, like by composing effects out of other effects (rather than the actions they dispatch).

You can solve it by subscribing to the actions the effects dispatch, or you can also use `shareReplay()` or other similar "hot" observable solution.

**Comment by hsntngr** [comment]
In my case I was injecting effect class into my component, which was not specified that should provided in root. 

So it get solved when I remove the effect dependency. Specifiying the providing effect class in root level also worked

**Comment by darkedges** [comment]
for me I had 
```
constructor(
    private store: Store<AppState>,
    private state: State<AppState>
  ) { }
canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) {
const userid = this.state.getValue().framauthuiFeature.auth.user.email;
}
```
and 
```
 StoreDevtoolsModule.instrument({ maxAge: 25, logOnly: environment.production }),
```
which caused a Double effect call.
Remove `StoreDevtoolsModule` and it did not happen.
Remove refrences to `State` and it did not happen.

Rewsolved by removing all references to `State` so I guess there is something strange happening with `StoreDevtoolsModule` and `State` usage.

**Comment by mtuzinskiy** [comment]
It's funny to see that this annoying serious issue is ignored for years.  
This was the reason for me and my team to stop using NgRx overall, thank you! :clap:

**Comment by kevinbeal** [comment]
> It's funny to see that this annoying serious issue is ignored for years.
> This was the reason for me and my team to stop using NgRx overall and switch to simple Subject-based state management, thank you! 👏

There were like 6 reasons you could get this that were not issues with NGRX given immediately above your comment. Did you rule them out first?

**Comment by mtuzinskiy** [comment]
@kevinbeal  Yes.  
But, to be honest, I don't find these to be actually "reasons". They are more a steps to reproduce a **defect**.  
I want the DevTools just to work, without influencing the behavior of effects or any other part of the lib.  
Why in the world should I spend tremendous amount of time debugging this?  
Take as an example the "reason" posted by @darkedges . It's exactly how he says, something strange happening.  
I also observed how it was fixed for me at certain point, but then upgrading the NgRx version broke it again. And I just gave up.  
It's not the main reason why I decided to avoid NgRx, but it was one of the last drops. Sorry.

**Comment by VishalAkhouri** [comment]
I had the similar issue (effect being called twice) when I converted my effect from:
  `@Effect() public someEffect$: Observable<Action> = this.actions$.pipe(`

TO new syntax -

 `@Effect() public someEffect$: Observable<Action> = createEffect(() =>`

The reason for my issue as I did not remove the @Effect() decorator in the updated effect.

Correct usage should be:  `public someEffect$: Observable<Action> = createEffect(() =>`

**Comment by Stephanemw** [comment]
I understand retaining the legacy API for now to ease transition to the new APIs for downstream developers.

Unfortunately, this approach leads to scenarios detailed above which feel very much like a setting us up to shoot ourselves in the foot.

An initial FAQ entry would help.

Adding a runtime warning when situations where @Effect and createEffect are both used, or some of the other scenarios detailed above are breached would really help reduce developer puzzlement and frustration.

**Comment by timdeschryver** [comment]
We'll look into it.
For now, you can use [ngrx-tslint-rules](https://github.com/timdeschryver/ngrx-tslint-rules) or [eslint-plugin-ngrx](https://github.com/timdeschryver/eslint-plugin-ngrx). This will warn you if you use the decator.

**Comment by xindexer** [comment]
I'm using @ngrx/data and I was getting this issue as well, I did not have state referenced in the parent component, but I did have it in the children, I ended up removing this.state.getValue() functions from all of the components and the double tap stopped.

**Comment by soufianerafik** [comment]
I had the same issue too, everything was firing twice.

I fixed it by **commenting out** the StoreDevtoolsModule 


```javascript
  /*StoreDevtoolsModule.instrument({
      maxAge: 25,
      logOnly: environment.production,
    })*/
```

**Comment by sandeepsuvit** [comment]
For me the issue was with defining

`private state: State<AppState>` instead of `private state: Store<AppState>` when using the following configuration

```typescript

// Configure global states
const globalStates = [
  provideState(authFeatureKey, authReducer),
  // Register additional states here
];

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(AppRoutes),
    // NGRX Configuration
    provideStore(),
    ...globalStates,
    provideEffects(globalEffects),
    // Only for development
    provideStoreDevtools({
      maxAge: 25,
      logOnly: false,
    }),
  ],
};
```

Angular: 18 and Ngrx: 18
