### ISSUE TITLE
[feature] provide FeatureStore

### ISSUE THREAD

**Issue by amitport** [ngrx/platform#106]
Currently we can declare reducers in module hierarchy. We still always provide the root Store though. It would be nice if we could further separate individual modules, allowing them to request only the innermost FeatureStore (which is a view of the store for a specific feature).

(ngrx is great BTW)

**Comment by amitport** [comment]
The current way I'm doing this

`const ROOT_STORE = new InjectionToken<Store<MyAppState>>('rootStore');`

in root module:
`
 {provide: ROOT_STORE, useExisting: Store}
`

in child module:
`
{
      provide: Store,
      useFactory: (store: Store<MyAppState>) =>
        store.select(createFeatureSelector<MyFeatureState>('myFeature')),
      deps: [ROOT_STORE]
 }
`

(we refer to `MyAppState` and `ROOT_STORE` in child module for type safety, but could skip this and use string as a type token if we want complete separation)

**Comment by MikeRyanDev** [comment]
Your solution is how we would recommend going about this. We thought long and hard about whether or not we should scope instances of `Store` to feature state and ultimately came to the conclusion that - while powerful - it can be very confusing to track what instances of `Store` are received by which components. It also complicates deriving state from multiple features, a pattern that we see as being common in some of our own applications.
