### ISSUE TITLE
Schematics docs rename blueprint to schematic

### ISSUE THREAD

**Issue by tdeschryver** [ngrx/platform#1060]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## What is the current behavior?
Right now we're describing a schematic as a blueprint.

## Expected behavior:
I think this should be matched to the angular cli docs, where the renamed happened a couple of days ago.
Reference: [commit](https://github.com/angular/angular-cli/commit/03445633552c8161ad3c5fe46fd4fd83fe5d7766) and in the [docs](https://github.com/angular/angular-cli/wiki/generate)

## Other information:
If this issue gets accepted I can change the docs.
cc: @vincecampanale, is this something you want to do? (because you asked for a simple issue on the gitter channel)

**Comment by vincecampanale** [comment]
Woot! Alright, so it looks like all I'm doing is changing instances of "Blueprint(s)" in the `docs` directory (and possibly other places) to "Schematic(s)"?

**Comment by tdeschryver** [comment]
@vincecampanale yep that's it!
