### ISSUE TITLE
Compilation error for reducer with third argument. config.reducerFactory has been passed to StoreModule.forRoot to change combineReducer to be able to pass third argument into reducer.

### ISSUE THREAD

**Issue by raj0109** [ngrx/platform#1063]
Type Definition for reducer is:
export interface ActionReducer<T, V extends Action = Action> {
    (state: T | undefined, action: V): T;
}

which does not allow to customize combineReducer to have third argument in reducer as mentioned in below link:
https://redux.js.org/recipes/structuring-reducers/beyond-combinereducers

**Comment by tdeschryver** [comment]
Could you elaborate a bit more, because I'm not following...

**Comment by raj0109** [comment]
In our application, return value from one of the reducers not only depends on state from that reducer, and action, but also depends on the state from other reducer.
so we have customize the combineReducer function as such:


import {
    Action,
    ActionReducer,
    ActionReducerFactory,
    ActionReducerMap,
    MetaReducer
} from '@ngrx/store';

export function combineReducers<T, V extends Action = Action>(
    reducers: ActionReducerMap<T, V>,
    initialState?: Partial<T>
): ActionReducer<T, V>;
export function combineReducers(reducers: any, initialState: any = {}): ActionReducer<any, Action> {
    const reducerKeys = Object.keys(reducers);
    const finalReducers: any = {};

    for (let i = 0; i < reducerKeys.length; i++) {
        const key = reducerKeys[i];
        if (typeof reducers[key] === 'function') {
            finalReducers[key] = reducers[key];
        }
    }

    const finalReducerKeys = Object.keys(finalReducers);

    return function combination(state, action) {
        state = state === undefined ? initialState : state;
        let hasChanged = false;
        const nextState: any = {};
        for (let i = 0; i < finalReducerKeys.length; i++) {
            const key = finalReducerKeys[i];
            const reducer: any = finalReducers[key];
            const previousStateForKey = state[key];
            const nextStateForKey = reducer(previousStateForKey, action, state);

            nextState[key] = nextStateForKey;
            hasChanged = hasChanged || nextStateForKey !== previousStateForKey;
        }
        return hasChanged ? nextState : state;
    };
}


Line: const nextStateForKey = reducer(previousStateForKey, action, state);
third argument to reducer is whole state of store

I have a reducer which is like 
export function dataReducer(
    state: DataState = initialState,
    action: DataActionsUnion,
    appState
): DataState {
	// some bussiness logic
	return newState;
}

when I create the ActionReducerMap 

export const seRootReducers: ActionReducerMap = {
    data: dataReducer
};

ts compiler throws an error

TS2345: Argument of type '{ data: (state: DataState, action: DataActionsUnion, appState: any) => Data...' is not assignable to parameter of type 'ActionReducerMap<{ data: any; }, Action> | InjectionToken<ActionReducerMap<{ deviceData: an...'.
  Type '{ data: (state: DataState, action: DataActionsUnion, appState: any) => Data...' is not assignable to type 'InjectionToken<ActionReducerMap<{ data: any; }, Action>>'

it does not accept third argument.

Changing the ActionReducer definition solves the problem for us:
export interface ActionReducer<T, V extends Action = Action> {
(state: T | undefined, action: V, ...args): T;
}

**Comment by dummdidumm** [comment]
The interface defined by ngrx which you complain about is written to fit the implementation of ngrx' `combineReducers`. You wrote your own, so you need your own interface as well. I don't see ngrx at fault here. On the other hand, I don't see harm in enhancing the signature to add `...args: any[]`. You could add a PR and see if the owner is okay with it.
