### ISSUE TITLE
Actions are undefined with ng build --prod 

### ISSUE THREAD

**Issue by mitorski** [ngrx/platform#1065]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

<pre><code>

import {EntityState, createEntityAdapter} from '@ngrx/entity';
import {Action, createFeatureSelector} from '@ngrx/store';
import {Injectable} from '@angular/core';
import {Actions, Effect, ofType} from '@ngrx/effects';
import {HttpClient} from '@angular/common/http';
import {switchMap, map} from 'rxjs/operators';
import {Observable} from 'rxjs';
import {environment} from '../environments/environment';

export interface Subject {
  id: number;
  name: string;
  icon: string;
}

export enum SubjectActionTypes {
  Get = '[Subject] Get',
  Success = '[Subject] Success',
}

export class SubjectGet implements Action {
  readonly type = SubjectActionTypes.Get;
}

export class SubjectSuccess implements Action {
  readonly type = SubjectActionTypes.Success;
  constructor(public payload: Subject[]) {}
}

export type SubjectUnion
  = SubjectGet
  | SubjectSuccess;

export const SubjectAdapter = createEntityAdapter<Subject>();

export interface SubjectState extends EntityState<Subject> {}

const SubjectInitialState: SubjectState = SubjectAdapter.getInitialState();

export function SubjectReducer(
  state: SubjectState = SubjectInitialState,
  action: SubjectUnion
) {
  switch (action.type) {
    case SubjectActionTypes.Success:
      console.log('ACTION', action);
      return SubjectAdapter.addAll(action.payload, state);
    default: {
      return { ...state };
    }
  }

}

const SubjectStateGet = createFeatureSelector<SubjectState>('subjects');

export const {
  selectIds,
  selectEntities,
  selectAll,
  selectTotal
} = SubjectAdapter.getSelectors(SubjectStateGet);

@Injectable({providedIn: 'root'})
export class SubjectService {
  constructor(private http: HttpClient) {}
  get(): Observable<Subject[]> {
    return this.http.get(environment.api.subjects).pipe(map((result: {results: Subject[]}) => result.results));
  }
}

@Injectable()
export class SubjectEffect {

  constructor(private actions$: Actions, private service: SubjectService) {
    console.log(this.actions$);
  }

  @Effect()
  get$ = this.actions$
    .pipe(
      ofType(SubjectActionTypes.Get),
      switchMap(() => this.service
        .get()
        .pipe(
          map((subjects: Subject[]) => new SubjectSuccess(subjects))
        )
      )
    );
}

</code></pre>

## What is the current behavior?

With <pre>ng build --prod</pre> Actions are undefined so i have this error:

<pre>Uncaught TypeError: Cannot read property 'pipe' of undefined</pre>

## Expected behavior:

Actions will not be undefined. It's crash application on production, after we upgrade versions of ng, rxjs, and ngrx.

## Version of affected browser(s),operating system(s), npm, node and ngrx:

Just build this stack with --prod flag on build

<pre><code>

{
  "name": "frontend",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.0.0",
    "@angular/common": "^6.0.0",
    "@angular/compiler": "^6.0.0",
    "@angular/core": "^6.0.0",
    "@angular/forms": "^6.0.0",
    "@angular/http": "^6.0.0",
    "@angular/platform-browser": "^6.0.0",
    "@angular/platform-browser-dynamic": "^6.0.0",
    "@angular/pwa": "^0.6.0",
    "@angular/router": "^6.0.0",
    "@angular/service-worker": "^6.0.0",
    "@ngrx/effects": "^6.0.0-beta.2",
    "@ngrx/entity": "^6.0.0-beta.2",
    "@ngrx/router-store": "^6.0.0-beta.2",
    "@ngrx/store": "^6.0.0-beta.2",
    "@ngrx/store-devtools": "^6.0.0-beta.2",
    "@types/lodash": "^4.14.108",
    "angularfire2": "^5.0.0-rc.7",
    "bootstrap-4-grid": "^2.4.0",
    "core-js": "^2.5.4",
    "firebase": "^4.13.1",
    "lodash": "^4.17.10",
    "ngrx-actions": "^3.1.6",
    "ngrx-store-freeze": "^0.2.2",
    "rxjs": "^6.0.0",
    "rxjs-compat": "^6.1.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.0",
    "@angular/cli": "~6.0.0",
    "@angular/compiler-cli": "^6.0.0",
    "@angular/language-service": "^6.0.0",
    "@ngrx/schematics": "^5.2.0",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2"
  }
}

</code></pre>

**Comment by mitorski** [comment]
In same issue i found tip for upgrade ngrx to latest version ~ 6, so on 5.2 not working too. But, i make it work extract to separated file SubjectEffect. 

<pre><code>
import {EntityState, createEntityAdapter} from '@ngrx/entity';
import {Action, createFeatureSelector} from '@ngrx/store';
import {Injectable} from '@angular/core';
import {Actions, Effect, ofType} from '@ngrx/effects';
import {HttpClient} from '@angular/common/http';
import {switchMap, map} from 'rxjs/operators';
import {Observable} from 'rxjs';
import {environment} from '../environments/environment';

export interface Subject {
  id: number;
  name: string;
  icon: string;
}

export enum SubjectActionTypes {
  Get = '[Subject] Get',
  Success = '[Subject] Success',
}

export class SubjectGet implements Action {
  readonly type = SubjectActionTypes.Get;
}

export class SubjectSuccess implements Action {
  readonly type = SubjectActionTypes.Success;
  constructor(public payload: Subject[]) {}
}

export type SubjectUnion
  = SubjectGet
  | SubjectSuccess;

export const SubjectAdapter = createEntityAdapter<Subject>();

export interface SubjectState extends EntityState<Subject> {}

const SubjectInitialState: SubjectState = SubjectAdapter.getInitialState();

export function SubjectReducer(
  state: SubjectState = SubjectInitialState,
  action: SubjectUnion
) {
  switch (action.type) {
    case SubjectActionTypes.Success:
      console.log('ACTION', action);
      return SubjectAdapter.addAll(action.payload, state);
    default: {
      return { ...state };
    }
  }

}

const SubjectStateGet = createFeatureSelector<SubjectState>('subjects');

export const {
  selectIds,
  selectEntities,
  selectAll,
  selectTotal
} = SubjectAdapter.getSelectors(SubjectStateGet);

@Injectable({providedIn: 'root'})
export class SubjectService {
  constructor(private http: HttpClient) {}
  get(): Observable<Subject[]> {
    return this.http.get(environment.api.subjects).pipe(map((result: {results: Subject[]}) => result.results));
  }
}

</code></pre>

<pre><code>
import {Actions, Effect, ofType} from '@ngrx/effects';
import {Subject, SubjectActionTypes, SubjectService, SubjectSuccess} from '../adapters/Subject.adapter';
import {Injectable} from '@angular/core';
import {map, switchMap} from 'rxjs/internal/operators';

@Injectable()
export class SubjectEffect {

  constructor(private actions$: Actions, private service: SubjectService) {
    console.log(this.actions$);
  }

  @Effect()
  get$ = this.actions$
    .pipe(
      ofType(SubjectActionTypes.Get),
      switchMap(() => this.service
        .get()
        .pipe(
          map((subjects: Subject[]) => new SubjectSuccess(subjects))
        )
      )
    );
}

</code></pre>

In this way, all works fine after prod build.

For me that's ok, but the error exists after all. Can i help you with it?

**Comment by tdeschryver** [comment]
@mitorski if it's working it's all good. 
I thought the problem would be not splitting up the files, but I had problems with some of your types - so I couldn't test it to be sure.
You can close the issue if you now :smile:

**Comment by mitorski** [comment]
Obviously, for me topic it's close. But thinking about deeper, it's stranger that in some case this code work, and otherwise not. Close topic it's not solution for problem. In perfect world, this code sould be work so maybe we can try to find solution for it?:)

**Comment by 2RajShaikh** [comment]
Unfortunately I am facing this issue. When run using prod flag it throws error and if removed --prod flag it works.
