### ISSUE TITLE
RFC: auto generate Actions using schematics

### ISSUE THREAD

**Issue by sandangel** [ngrx/platform#1075]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

Actions is not boilerplate, but having to declare it manually feel odd.

## Expected behavior:

We can auto generate actions using schematics
User Input:
```typescript
export enum AuthActionTypes {
  MyAction = '[Feature.HomePage] Do My Action',
  MyAction1 = '[Feature.HomePage] Do My Action 1',
  MyAction2 = '[Feature.HomePage] Do My Action 2',
  MyAction3 = '[Feature.HomePage] Do My Action 3',
  MyAction4 = '[Feature.HomePage] Do My Action 4'
}
```
command:
```bash
ng generate @ngrx/schematics:action-helper 'projects/example/**/*.actions.ts'
# or
ng g @ngrx/schematics:ah 'projects/example/**/*.actions.ts'
```
output:

```typescript
import { Action } from '@ngrx/store';

export enum AuthActionTypes {
  MyAction = '[Feature.HomePage] Do My Action',
  MyAction1 = '[Feature.HomePage] Do My Action 1',
  MyAction2 = '[Feature.HomePage] Do My Action 2',
  MyAction3 = '[Feature.HomePage] Do My Action 3',
  MyAction4 = '[Feature.HomePage] Do My Action 4'
}

/**
 * Generated Actions
 */

export class MyAction implements Action {
  readonly type = AuthActionTypes.MyAction;
}

export class MyAction1 implements Action {
  readonly type = AuthActionTypes.MyAction1;
}

export class MyAction2 implements Action {
  readonly type = AuthActionTypes.MyAction2;
}

export class MyAction3 implements Action {
  readonly type = AuthActionTypes.MyAction3;
}

export class MyAction4 implements Action {
  readonly type = AuthActionTypes.MyAction4;
}

export type AuthActions = MyAction | MyAction1 | MyAction2 | MyAction3 | MyAction4;
```

Then user can define `constructor(public payload: any) {}` or import types they need for payload by themselves.

## Minimal reproduction of the problem with instructions:

I have done a quick prototype and you can try it out at [@ngrx-utils/schematics](https://github.com/ngrx-utils/ngrx-utils/tree/schematics)

http://www.giphy.com/gifs/NUajv0WeM9lBCHS0Xe
![may-20-2018 14-14-05](https://user-images.githubusercontent.com/22189661/40275920-1c70a0f4-5c38-11e8-9fe5-3b38895ef7eb.gif)

clone the schematics branch then run 

```bash
npm install
npx tsc -p projects/schematics/tsconfig-build.json -w
cd projects/schematics
npm link
cd ../..
npm link @ngrx-utils/schematics
ng g @ngrx-utils/schematics:ah 'projects/schematics/action-helper/**/*.actions.ts'
```

or 
- create an test.actions.ts file in your project
```typescript
export enum AuthActionTypes {
  MyAction = '[Feature.HomePage] Do My Action',
  MyAction1 = '[Feature.HomePage] Do My Action 1',
  MyAction2 = '[Feature.HomePage] Do My Action 2',
  MyAction3 = '[Feature.HomePage] Do My Action 3',
  MyAction4 = '[Feature.HomePage] Do My Action 4'
}
```
- run 
```bash
npm install -D @ngrx-utils/schematics@next prettier
ng g @ngrx-utils/schematics:ah 'path/to/test.actions.ts'
```

You can add more action to the enum type and run the command again, it will automatically update your action file accordingly.

![may-21-2018 20-20-06](https://user-images.githubusercontent.com/22189661/40305185-65683202-5d34-11e8-800d-8eb0ce8a94ad.gif)

This command will also collecting all action types to analyze and provide feedback when user declare not unique action. Try declaring 2 actions with same type and the command will show the error: 'Duplicated action types...'

![may-21-2018 20-23-21](https://user-images.githubusercontent.com/22189661/40305296-dbd047c2-5d34-11e8-9f68-9d48acf1f1b5.gif)

User can continously update the enum type and run command to only generate actions which is not declared yet. The command will then update the type alias as well as add new action class.

This command is forcing user to follow the naming best practice for enum type. It's only take the enum with 'ActionTypes' suffix. This also support multi enum in the same file.

## Other information:
If this look ok then I could prepare a PR as well as tests
cc: @brandonroberts

**Comment by sandangel** [comment]
@dummdidumm thanks for your reply. I think they are nice but I want to follow ngrx best practice and convention so we can do some analyzing on our code like the schematics above.

> ...analyze and provide feedback when user declare not unique action

**Comment by brandonroberts** [comment]
I'd like to hold off on this one. With V7, we are looking at how you can define the actions and unions to be less verbose.

**Comment by stm32p103** [comment]
I also feel clumsy when copy-pasting 'action string' everywhere...So I made [tiny utility to made it simple.](https://github.com/stm32p103/ngrx-utility)

With this utility, you can define actions like:
```
export class CounterActions {
    @ToAction()
    static increment(): any {
        console.log( 'increment action' );
    }

    @ToAction()
    static decrement(): any {
        console.log( 'decrement action' );
    }
    
    @ToAction()
    static preset( n: number ): any {
        console.log( 'preset action' );
        return n;
    }
}
```

And define reducer like:
```
//build reducer factory
const factory = new ReducerFactory<number>();

// add( action, ( state: T, payload? any ) => T );
factory.add( CounterActions.increment, ( count: number ) => count + 1 );
factory.add( CounterActions.decrement, ( count: number ) => count - 1 );
factory.add( CounterActions.preset,    ( count: number, preset: number ) => preset );

// define reducer
const counterReducer = factory.create( 0 );  // initial value = 0
```
Then dispatch action like:
```
increment() {
        this.store.dispatch( CounterActions.increment() );
}
```

I think it could be simple and not violates ngrx's philosophy. If you have interested in it, please try and leave some comments.

**Comment by timdeschryver** [comment]
Closing this issue because this became obsolete with the introduction of `createAction`, introduced in NgRx 8.
