### ISSUE TITLE
Is it a good idea to store, store observables into the store?

### ISSUE THREAD

**Issue by sanbornsen** [ngrx/platform#1076]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[x] A general question
</code></pre>

## The normal way

So normally my store looks like 
```
{
  ...
  comments: {
    "1": {
      id: '1',
      body: 'Comment - 1',
      creator: '3'
    },
    "2": {
      id: '2',
      body: 'Comment - 2',
      creator: '2'
    }
  },
  users: {
    "1": {
      id: '1',
      username: 'user-1'
    },
    "2": {
      id: '2',
      username: 'user-2'
    },
    "3": {
      id: '3',
      username: 'user-3'
    }
  }
  ...
}
```
Where the `creator` in `comments` are foreign key to the `user`. I store the data and combine them and resolve the user for each comment before rendering a comment with the creator.

## The insane way:

What if I do this instead? 
```
{
  ...
  comments: {
    "1": {
      id: '1',
      body: 'Comment - 1',
      creator: this.store.select('users').select('3')
    },
    "2": {
      id: '2',
      body: 'Comment - 2',
      creator: this.store.select('users').select('3')
    }
  },
  users: {
    "1": {
      id: '1',
      username: 'user-1'
    },
    "2": {
      id: '2',
      username: 'user-2'
    },
    "3": {
      id: '3',
      username: 'user-3'
    }
  }
  ...
}
```
and I do this in comments effect itself. Thus I am storing an entire store observable in to the store. 

## Is it a good idea?
Now I already have seen that `ngrx/store-devtools` is failing with this approach. What else may go wrong if I follow this? So, I am planning to store every relationship as an observable in the store.

**Comment by tdeschryver** [comment]
It is possible but that doesn't mean you should, and imho I don't recommend this.
Because your store isn't serializable now, thus also making the devtools not usable.

You should create selectors where you map the comments and users to a read model.
