### ISSUE TITLE
RFC: StackBlitz ngrx seed

### ISSUE THREAD

**Issue by tdeschryver** [ngrx/platform#1079]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## What is the current behavior?
The issue template currently has a link to an old plunkr template.

## Expected behavior:
If we create a StackBlitz ngxr seed, this would maybe lower the effort to create a repro for an issue.
Currently I've ported the plunkr template to StackBlitz which you can find at [https://stackblitz.com/edit/ngrx-seed](https://stackblitz.com/edit/ngrx-seed).

Thoughts?
Would this be enough, should something be added/removed?

**Comment by vincecampanale** [comment]
I think this is a great idea. Some thoughts:

I'm of two minds when it comes to the seed application structure. When I initially went to [https://stackblitz.com/edit/ngrx-seed](https://stackblitz.com/edit/ngrx-seed), I was looking for actions, effects, reducers, etc. in their own folders, as one would find them in most apps with NgRx. So my first feedback was that maybe we should divide them up like that to make it easier to navigate. That being said, the point of the seed is to be minimal and small, so having all the store stuff in one file makes sense. Maybe we call the directory something other than `reducers`? Would `store` work?

Also, we may want to include a `fakeAsync` util with timeouts and such to mock an HTTP request or something. Pairing that with a simple effect and some `Fail` and `Success` actions would make it easier to reproduce issues that involve asynchronous code, which I would imagine are fairly common.

**Comment by tdeschryver** [comment]
Seems like I forgot to save after I moved the actions to the actions folder :sweat_smile: - now it's there.

**Comment by tdeschryver** [comment]
Closing, because it's implemented in #1100 .
