### ISSUE TITLE
Angular 5 and AOT

### ISSUE THREAD

**Issue by ritox842** [ngrx/platform#1084]
[X ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request

Back in March 17 I've opened an [issue]((https://github.com/ngrx/store/issues/355)) related to angular 2 and AOT. 
The issue was related to the AOT build process, The build throw this error:

> Uncaught TypeError: Cannot read property 'information' of undefined
(When information is the name of my nested reducer).

I recently updated my rxjs to version 5.x and same for my angular version.
The build runs fine when not in AOT mode, But when it is the build fails with a similar message.

I understand that I need to avoid execution of functions in the build for it to works, and I did.. But probably I'm doing it wrong cause it still doesnt work.

This is my current code for the root reducer.

```
export const AppState = {
  app: appReducer,
  event: eventReducer,
  eventLog: eventLogReducer,
  bettingOptions: bettingOptionsReducer,
  eventData: eventDataReducer,
  statsByPeriod: statsByPeriodReducer,
  timeLine: timeLineReducer,
  betData: betDataReducer,
  eventBetsIDs: eventBetsIDsReducer,
  transactions: transactionsReducer,
  lobby: lobbyReducer,
  leagues: leagueReducer,
  genre: genreReducer,
  betSlips: betSlipsReducer,
  betOffers: betOffersReducer,
  createBet: createBetReducer,
  userProfile:
    {
      information: userInformationReducer,
      limits: limitsReducer,
      notifications: notificationsReducer
    }
  ,
  cashier: {
    balance: cashierReducer,
    payment: paymentReducer
  },
  myBets: myBetsReducer,
  usersData: usersDataReducer,
  social: {
    connections: connectionsReducer,
    groups: {
      userGroups: groupsReducer,
      config: groupConfigReducer
    },
  }
};

const finalReducers = {};

const combineReducers = (reducers) => {
  const reducerKeys = Object.keys(reducers);
  for (let i = 0; i < reducerKeys.length; i++) {
    const key = reducerKeys[i];
    if (typeof reducers[key] === 'function') {
      finalReducers[key] = reducers[key];
    }
    else {
      finalReducers[key] = combineReducersEnhanced(reducers[key]);
    }
  }
};

combineReducers(AppState);

export const rootReducer = finalReducers;

```

And in my App.module Import:
` StoreModule.forRoot(rootReducer)`

The [combineReducersEnhanced ](https://github.com/KwintenP/combine-reducers-enhanced)is 3rd party lib.

Any idea how to make the build work?

**Comment by tdeschryver** [comment]
Do you have or can you create a repository where this is reproduced?

**Comment by brandonroberts** [comment]
In order to do this, you need to inject the reducers as documented here https://github.com/ngrx/platform/blob/master/docs/store/api.md#injecting-reducers

If you need further support, use the [gitter channel](https://gitter.im/ngrx/platform)
