### ISSUE TITLE
ExampleApp Good Action Hygeine

### ISSUE THREAD

**Issue by ccadieux** [ngrx/platform#1089]
## I'm submitting a...
<pre><code>
[X] Feature request
</code></pre>

## What is the current behavior?

The Good Action Hygiene with Mike Ryan @MikeRyanDev 
https://www.youtube.com/watch?v=JmnsEvoy-gY
Talks about good action hygiene yet the example actions have examples like:
`[Layout] Open Sidenav`

A lot of people look to that app for best practices. Applying the idea Mike Ryan presented would help people write better ngrx apps.  

## Expected behavior:

Actions using `[SOURCE] EVENT`

**Comment by tdeschryver** [comment]
Thanks for the feedback, this is already planned for the next release (#861).
But this doesn't mean a PR is welcome :wink:
