### ISSUE TITLE
Schematics: Environments import path is off by one level when generating new store

### ISSUE THREAD

**Issue by markgoho** [ngrx/platform#1090]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
use schematics to generate a new store
`ng g store AppState --root --module app.module.ts --collection @ngrx/schematics`
in app.module.ts the environment file path is incorrect
`import { environment } from '../../environments/environment';`

## Expected behavior:

see the environment path file set to
`import { environment } from '../environments/environment';`

**Comment by tdeschryver** [comment]
Are you using the released version (6.0.1) or are you using the beta version?
Because I thought this was resolved in the released version.

**Comment by tdeschryver** [comment]
Oops, you're right.
I think I broke it with the reducer fix, sorry :sweat_smile:
