### ISSUE TITLE
Schematics: state name is not respected on store generation

### ISSUE THREAD

**Issue by markgoho** [ngrx/platform#1092]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

`ng g store Bob --root --module app` should create a reducer with Bob as the name for the state interface

## Expected behavior:
Regardless of the string you pass in, the reducer always shows
`export interface State`

**Comment by tdeschryver** [comment]
You can pass `--stateInterface Bob` to create the interface as `Bob`.
I'm not sure if this is intended or not, so we'll have to wait till someone can enlighten us 😄

**Comment by markgoho** [comment]
I wonder what the `State` part of the command does. In any case, it certainly gives the impression that string is going to be the name of your interface, until you see the additional `stateInterface` flag

**Comment by brandonroberts** [comment]
The name was required because the CLI required it before. It doesn't really serve a purpose other than that.  The `--stateInterface` option was added to override it for V6, but we could look at changing it for V7 to use the first argument as the state interface
