### ISSUE TITLE
[example-app] why useHash: true ?

### ISSUE THREAD

**Issue by dakipro** [ngrx/platform#1093]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ x ] Documentation issue or request
</code></pre>

## What is the current behavior?

All url's use has in the url, f.eks. http://localhost:4200/#/books

## Expected behavior:

by default url is http://localhost:4200/books

## Other information:
Just curious for the reasons, I personally like it without the hash :)

**Comment by dakipro** [comment]
I already did, and it says  https://angular.io/guide/router#which-strategy-is-best

> Almost all Angular projects should use the default HTML5 style. It produces URLs that are easier for users to understand. And it preserves the option to do server-side rendering later. 
> ...
> Stick with the default unless you have a compelling reason to resort to hash routes.

That is why I am asking why is the example app using hash routes, and why should one chose hash route over the HTML5 style (again, just curious)

**Comment by brandonroberts** [comment]
It's only because we're hosting the example app on github pages. I believe there is a way to support the default location strategy, but it was just easier to setup initially.

**Comment by dakipro** [comment]
Thank you, thought actually crossed my mind at one point :)
