### ISSUE TITLE
Typing is lost along with pipeable operators chain in effects

### ISSUE THREAD

**Issue by blackholegalaxy** [ngrx/platform#1096]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
The typing is incorrect and does not detect proper action type on effects.

```
@Effect()
  topbarItemClick$: Observable<Action> = this.actions$.pipe(
    ofType(fromLayoutActions.TOPBAR_ITEM_CLICK),    
    withLatestFrom(
      this.store.pipe(select(fromLayoutSelectors.getLayoutState))
    ),
    map(([action, state]) => ({ action, state })),
    distinctUntilChanged(),
    map(({ action, state }) => {
      return new fromLayoutActions.TopbarItemClickChanges(
        this.createTopbarItemClickPayload(state, action.payload)
      );
    })
  );
```

This effect actually works but IDE displays an error when hovering `action.payload`.

![image](https://user-images.githubusercontent.com/11064123/40514108-feef1b0a-5f75-11e8-9036-9f757d399656.png)

It seems the typing is wrongly inferred. It reads Action instead of the actual action type which is:

```
export class TopbarItemClick implements Action {
  readonly type = TOPBAR_ITEM_CLICK;
  constructor(public payload: ElementRef) { }
}
```

So the typing is somehow "lost" during pipeable operators.

Here is an interesting hover hint on a map right after ofType operator:

![image](https://user-images.githubusercontent.com/11064123/40514298-9b169616-5f76-11e8-92f9-8f396ba5be89.png)

More interestingly, if I try to type the action "manually" here is the result:

![image](https://user-images.githubusercontent.com/11064123/40514363-dec37d02-5f76-11e8-957d-e4ee66df0a08.png)

This is problematic because since Rxjs 6.0 we cannot use resultSelector methods of operators such as `withLatestFrom` or `combineLatest`. 

Before we were able to do:

```
ofType...
withLatestFrom(
        select(fromLayoutSelectors.getLayoutState),
        (
          action: fromLayoutActions.TopbarItemClick,
          state: fromLayout.LayoutState
        ) => ({ action, state })
      ),

```
and the typing was working as expected by "forcing it" at this level.

But now we must `map` after `withLatestFrom` resulting in an array argument, which cannot be typed:

```
ofType...,
withLatestFrom(select(fromLayoutSelectors.getLayoutState)),
map(([action, state]) => ({action, state })
```

## Expected behavior

Having proper action typing inferred properly

## Version of affected browser(s),operating system(s), npm, node and ngrx:

Rxjs/ngrx/angular 6. Webstorm and VSCode editors.

**Comment by tdeschryver** [comment]
You have to provide a type when using `ofType`, so the operator will become:
```
ofType<INSERT_YOUR_ACTION_HERE>(fromLayoutActions.TOPBAR_ITEM_CLICK)
```

**Comment by blackholegalaxy** [comment]
Completely missed that on the docs! Thanks :)
