### ISSUE TITLE
Example App: book-exists.guard map error

### ISSUE THREAD

**Issue by Bielik20** [ngrx/platform#1098]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
In book-exists.guard `hasBookInApi` method:
```ts
hasBookInApi(id: string): Observable<boolean> {
  return this.googleBooks.retrieveBook(id).pipe(
    map(bookEntity => new BookActions.Load(bookEntity)),
    tap((action: BookActions.Load) => this.store.dispatch(action)),
    map(book => !!book),
    catchError(() => {
      this.router.navigate(['/404']);
      return of(false);
    })
  );
}
```
The first `map` maps `Book` into `BookActions.Load`. The second `map` expects `Book` but it gets `BookActions.Load`. This way it always returns true.

## Expected behavior:
First `map` should be merged into `tap` so that second `map` could get `Book`.

**Comment by tdeschryver** [comment]
Not really... let me explain why.
If we take a look at the comments above the method it says:
```
/**
   * This method loads a book with the given ID from the API and caches
   * it in the store, returning `true` or `false` if it was found.
   */
```

So we're fetching the book first, creating a `BookActions.Load` action with the fetched book and storing it in our store. Because we've found the book we want activate the route, therefor we must return an `Observable(true)`, this is what `!!book` does for us.

Now if we're navigating to a book that doesn't exist in the api (for example `/#/books/6I6DaTsb7o4dd`) the api will return a 404, resulting in an error that we catch in `catchError`.

**Comment by Bielik20** [comment]
Hello, I am learning it right now and I appreciate the response. I understand what you are saying, still, I think the second map should be changed into something like that:
```
map(() => true)
```
The reasons are that:
1. It doesn't take a `Book` object, it takes a `BookAction.Load` so the name "book" is misleading.
2. The result of `!!book` is always true as at this point the `book` will always be an object so casting it to boolean always return true.

Is it correct, or am I missing something?

**Comment by tdeschryver** [comment]
Yep, you're right.
It would be perhaps a bit more readable when just returning true.

**Comment by ravishivt** [comment]
My suggestion is not to use `map` to convert the `bookEntity` to an action.  The following would be more clear IMO:

```ts
  return this.googleBooks.retrieveBook(id).pipe(
    tap(bookEntity => this.store.dispatch(new BookActions.Load(bookEntity))),
    map(bookEntity => !!bookEntity),
```
