### ISSUE TITLE
store-devtools frezz in chrome after updated to version 6.0.1

### ISSUE THREAD

**Issue by ofirrifo** [ngrx/platform#1109]
## Minimal reproduction of the bug/regression with instructions:
- update to
    "@ngrx/effects": "6.0.1",
    "@ngrx/router-store": "6.0.1",
    "@ngrx/store": "6.0.1",
    "@ngrx/store-devtools": "6.0.1"

- execute project
- open chrome in dev tools 
- select redux tab
now I cant do anything 

## Expected behavior:

should work as was in 5.0.1

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
 ngrx v6.0.1
angular v6.0.3
node v9.7.1
affected browser is chrome
OS: mac

## Other information:
I just update my project to work with the cli 6, angular 6 rxjs 6 and ngrx 6
evrthing work in my project but if I want to work with the store-devtools I can't

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by tdeschryver** [comment]
Hi, normally it should work tho 😅 (not tested on a mac tho)
Can you try if the [ngrx-seed](https://ngrx-seed.stackblitz.io/) works?
If it does work, there is probably something mis-configured, and would a repro be helpful.

**Comment by ofirrifo** [comment]
Hi, I check this ngrx-seed and it works as expected.
Is this ngrx-seed package.json use @ngrx/store-devtool V6.0.1 ?
can I clone this project from git? 
Thanks

**Comment by tdeschryver** [comment]
Yep, it has the latest versions.
Code can be found on (StackBlitz)[https://stackblitz.com/edit/ngrx-seed]

**Comment by tdeschryver** [comment]
@ofirrifo any updates on this?

**Comment by eemece2** [comment]
Hi @tdeschryver,
Make sure that this line:
   StoreDevtoolsModule.instrument( ... )
goes AFTER this line:
  StoreModule.forRoot(...)
I hope it helps you.

**Comment by ofirrifo** [comment]
Hi @eemece2 
I check and my  StoreDevtoolsModule.instrument(...) is after StoreModule.forRoot(...)
I still have the issue

```
@NgModule({
  declarations: [AppComponent, MainComponent, IfRoleAdminStubDirective],
  imports: [   
    StoreModule.forRoot(combinedReducers, { metaReducers: [logoutMetaReducer] }),
    StoreRouterConnectingModule,
    StoreModule.forFeature('settings', fromSettings.reducers),
    StoreModule.forFeature('integrations', fromIntegrations.reducers),
    StoreModule.forFeature('scope', fromScope.reducers),
    StoreModule.forFeature('configurations', fromConfiguration.reducer),
    SortablejsModule.forRoot({ animation: 150 }),
    EffectsModule.forFeature([ScopeEffects, GroupsEffects]),
    !environment.production
      ? StoreDevtoolsModule.instrument({
          maxAge: 10
        })
      : [],
    EffectsModule.forRoot([
     ...
    ])  
  ],
  providers: [
    { provide: RouterStateSerializer, useClass: CustomRouterStateSerializer }  
  ],
  bootstrap: [AppComponent]
})
```

**Comment by ofirrifo** [comment]
@tdeschryver  
the reason I can't do 'working' reproduction is the project I working on is a big project.
I even try to remove some of the StoreModule.forFeature(...) and just keep one of theme that way it works for few seconds and then it stop again.
I removed the router-store and the same issue
When I just downgrade the @ngrx/store-devtools to "5.0.1" everything work as should.

the problem is I don't get any exception and the redux chrome app just stop

**Comment by tdeschryver** [comment]
When I take a look at the [changelog](https://github.com/ngrx/platform/blob/master/CHANGELOG.md), I see some changes were made between 5.0.1 and 6.0.1. Could try installing v5.1.0 and v5.2.0 and see if the problem also occurs in any of these versions?

**Comment by ofirrifo** [comment]
Yes, I will check it and let you know. thanks

**Comment by tdeschryver** [comment]
That version introduced [2 bugfixes](https://github.com/ngrx/platform/blob/master/CHANGELOG.md#520-2018-03-07) on the devtools project, but I don't see how this would make the dev tools freeze.
The only thing that I can think of is that there must be something wrong with your state?
Are your actions and state serializable and are your reducers pure?

**Comment by ofirrifo** [comment]
Hi, @tdeschryver
- my reducers are pure 
- I will make sure that the state is serializable as well 

- is in case my state is not serializable should I see any console error?
- I try my self to understand what changed between store-devtools.umd.js (for v5.1.0) and the v6.0.1
  but I didn't find the main problem.
  can you point me to what method should I debug

Thanks

**Comment by tdeschryver** [comment]
To be honest I'm not sure why your devtools is freezing ...
I can only point out the changes introduced in 5.2 via the [changelog](https://github.com/ngrx/platform/blob/master/CHANGELOG.md#520-2018-03-07).

**Comment by dummdidumm** [comment]
Do you use action or state sanitizers? If yes, how do they look? What happens if you comment them out / make them very simple? (background: one of the bugfixes is around sanitizers)

**Comment by ofirrifo** [comment]
Hi @dummdidumm ,
I'm not sure what is the "sanitizers" in ngrx
I search for "sanitizers" text in my project and I didn't find something that related to it.
I do have a lot of actions and state but nothing special.

example of action I have
```
export class FetchActivities implements Action {
  readonly type = FETCH_ACTIVITIES;

  constructor(public payload?: any) {}
}
```

and then I have a reducer that return the new state.
I'm using the best practice of ngrx recommended.

in addition, I have RouterStateSerializer

```
import { Params, RouterStateSnapshot } from '@angular/router';
import { RouterStateSerializer } from '@ngrx/router-store';

/**
 * This interface represents the router state in the store
 */
export interface RouterStateUrl {
  url: string;
  queryParams: Params;
}

export interface RouterState {
  state: RouterStateUrl;
}

/**
 * This class serializes the router state to its store representation
 */
export class CustomRouterStateSerializer implements RouterStateSerializer<RouterStateUrl> {
  serialize(routerState: RouterStateSnapshot): RouterStateUrl {
    const { url } = routerState;
    const queryParams = routerState.root.queryParams;

    return { url, queryParams };
  }
}
```

and in the app.module
```
providers: [    { provide: RouterStateSerializer, useClass: CustomRouterStateSerializer }]
```

**Comment by ofirrifo** [comment]
I'm closing this bug since it seems after some latest update fixed the issue
