### ISSUE TITLE
Can't find Python executable "python"

### ISSUE THREAD

**Issue by mariadigiledge** [ngrx/platform#1119]
Error:
while installing npm install web3 it shows to install python but am writing program in javascript and after installing and adding python in system variable still it shows error.
Error:
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\LENOVO\AppData\Local\Programs\Python\Python36", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\maria\patcoin\patcoin\css\node_modules\scrypt
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN angular2-materialize@15.1.10 requires a peer of @angular/common@^4.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\LENOVO\AppData\Roaming\npm-cache\_logs\2018-06-10T12_00_32_304Z-debug.log
![capture](https://user-images.githubusercontent.com/39727684/41201573-2d196782-6cd8-11e8-9301-23eb25699e1f.PNG)

**Comment by tdeschryver** [comment]
I don't think this has anything to do with NgRx?
