### ISSUE TITLE
Generate reducer throw error

### ISSUE THREAD

**Issue by ofirrifo** [ngrx/platform#1120]
## Minimal reproduction of the bug/regression with instructions:
I'm trying to create a new reducer with the schematic command I get an error

- first I execute this npm command  `npm install @ngrx/schematics --save-dev`
- then I update the angular.json with this command `ng config cli.defaultCollection @ngrx/schematics`
- then I execute this command `ng generate r login`

I get this error:  newTree.optimize is not a function

## Expected behavior:
create a new reducer just like I create action (BTW 

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
"@ngrx/schematics": "^6.0.1",
 "@ngrx/effects": "6.0.1",
  "@ngrx/router-store": "6.0.1",
  "@ngrx/store": "6.0.1",

```
Angular CLI: 6.1.0-beta.2
Node: 9.7.1
OS: darwin x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.7.0-beta.2
@angular-devkit/build-angular      0.7.0-beta.2
@angular-devkit/build-ng-packagr   0.7.0-beta.2
@angular-devkit/build-optimizer    0.7.0-beta.2
@angular-devkit/build-webpack      0.7.0-beta.2
@angular-devkit/core               0.7.0-beta.2
@angular-devkit/schematics         0.7.0-beta.2
@angular/cdk                       6.2.1
@angular/cli                       6.1.0-beta.2
@angular/language-service          6.0.4
@angular/material                  6.2.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.1.0-beta.2
@schematics/angular                0.7.0-beta.2
@schematics/update                 0.7.0-beta.2
ng-packagr                         3.0.1
rxjs                               6.2.0
typescript                         2.7.2
webpack                            4.10.2

```

**Comment by tdeschryver** [comment]
This is because you're using the next version of the cli (and angular-devkit) which is currently in beta.
To use ngrx schematics right now in you're project you can 'downgrade' to the latest stable version, which is 6.0.x, until we make some changes on our end.

**Comment by mblackritter** [comment]
Just for the sake of completeness and also in case other users of Nrwl Nx hit this with 6.1.0-beta.2 while trying to fix the issue mentioned in [Nrwl/Nx - New workspaces should be created in their own directory](https://github.com/nrwl/nx/issues/549).

6.1.0-rc.0 seems to resolve both, creating subdirectories with Nx and `newTree.optimize is not a function`, which I got with 6.1.0-rc.2 when just running `ng new <project>`.

**Comment by mblackritter** [comment]
Just for the sake of completeness and also in case other users of Nrwl Nx hit this with 6.1.0-rc.2 (which has the `newTree.optimize is not a function` issue when used with Nx) while trying to fix the issue mentioned in [Nrwl/Nx - New workspaces should be created in their own directory](https://github.com/nrwl/nx/issues/549).

Going back to 6.1.0-rc.0 resolves `newTree.optimize is not a function`, which I got with 6.1.0-rc.2 and Nx when just running `ng new <project>`.
