### ISSUE TITLE
Can't use `@ngrx/entity` without installing `@ngrx/store`

### ISSUE THREAD

**Issue by gioragutt** [ngrx/platform#1122]
## Minimal reproduction of the bug/regression with instructions:

`npm install @ngrx/entity`

Follow the docs to get an `adapter`.

## Expected behavior:

I want to use `@ngrx/entity` without the `redux` part in the application.
I wrote the code to get an adapter, ran `ng serve`, and I get the following error:

```
ERROR in ./node_modules/@ngrx/entity/fesm5/entity.js
Module not found: Error: Can't resolve '@ngrx/store' in 'D:\Repositories\notes-app\node_modules\@ngrx\entity\fesm5'
```

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
I'm running `Windows 10`, Node `v8.11.1`,

```
"dependencies": {
    "@angular/animations": "^6.0.3",
    "@angular/cdk": "^6.2.0",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/material": "^6.2.1",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/router": "^6.0.3",
    "@ngrx/entity": "^6.0.1",
    "core-js": "^2.5.4",
    "rxjs": "^6.0.0",
    "uuid": "^3.2.1",
    "zone.js": "^0.8.26"
  }
```

## Other information:

I guess this might be some issue with unwanted dependencies, I just assumed, thinking of `entity`, that it can be used standalone.

**Comment by brandonroberts** [comment]
`@ngrx/store` is listed as a peerDependency for `@ngrx/entity`, which would have given a warning when it was installed.

**Comment by gioragutt** [comment]
@brandonroberts But why is there a dependency in the first place on store?

**Comment by tdeschryver** [comment]
@gioragutt because @ngrx/entity [ships](https://github.com/ngrx/platform/blob/master/modules/entity/src/state_selectors.ts) with default selectors, and thus needs `ngrx/store`.

**Comment by gioragutt** [comment]
Oh, okay👍 just have to mention that entity is awesome.

**Comment by gioragutt** [comment]
@brandonroberts how does separating all `selector` core code to `@ngrx/selector`, so that `entity` won't have all of `store` as a dependency?
That in turn will make people be able to use `selectors` regardless of the `store`. `entity` is just an example.
