### ISSUE TITLE
Example: Convert guards/services to implement Treeshakable providers

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1126]
## Other information:
If the service is eagerly loaded at the root, use the `providedIn` syntax and remove the `forRoot` implementation as needed.

## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
The effects don't need to be converted to trreeshakable providers. I was mainly referring to the auth and books services. In most cases `providedIn: 'root'` is sufficient, which can be used on eager and lazy services.

**Comment by maxisam** [comment]
Well, it might cause circular dependency issues then. Image if you needed to use services in effects.

It could be like effect -> service -> module (not root module but feature module) -> effect

**Comment by kouMatsumoto** [comment]
@maxisam 
Are you still dealing with this issue?
I'll do it instead if you stopped :smiley:

**Comment by maxisam** [comment]
no, I do. Please do it if you can. :)

**Comment by MatsumotoKou** [comment]
I try it, thankyou!
