### ISSUE TITLE
angular universal after import server state, @ngrx/store/update-reducers action wipes store

### ISSUE THREAD

**Issue by sangecz** [ngrx/platform#1132]
In angular universal project in ssr mode after successfully importing transferred state into store, next dispatched action `@ngrx/store/update-reducers` wipes the store. Actually there are multiple  `@ngrx/store/update-reducers` actions fired (>10). 

Inspecting in @ngrx/store-devtools (chrome extension) shows incorrectly that store after `@ngrx/store/update-reducers` is still filled with data but it's not true, I see that previously loaded data in cmp disappears after a quick moment (when this mentioned action fires).

It only happens in ssr mode, although multiple `@ngrx/store/update-reducers` are still present in @ngrx/store-devtools.

## Expected behavior:
To work same in ssr and in normal mode.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
angular 5.2.7
@ngrx/{store,effects,store-devtools,router-store} 5.2.0 
chrome 66

**Comment by tdeschryver** [comment]
Hi, this may sound stupid but do you have a default return in every reducer?

**Comment by sangecz** [comment]
yes, of course.
