### ISSUE TITLE
Change ActionReducer Action type to "any"

### ISSUE THREAD

**Issue by jdforsythe** [ngrx/platform#1134]
There's currently an arbitrary requirement that the "type" field of the Action parameter of an ActionReducer be a string.

This prevents using standard enums to define the event types. Instead, you have to define meaningless string. For example, this doesn't work (type mismatch):

```ts
export enum SelectedItemReducerEvents {
  SelectItem
}

export interface SelectedItemReducerPayload {
  type: SelectedItemReducerEvents;
  payload: Item;
}

export const selectedItemReducer: ActionReducer<Item, SelectedItemReducerPayload> = (
  state: Item = undefined,
  { type, payload }: ISelectedItemReducerPayload,
): Item => {}
```

## Workaround

If I put strings into the enum definition, the type mismatch is resolved:

```ts
export enum SelectedItemReducerEvents {
  SelectItem = 'SELECT_ITEM',
}
```

but these strings are useless and the requirement that the type be a string seems completely arbitrary.

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by tdeschryver** [comment]
Correct me if I'm wrong but having the `type` as a string is "one of the main parts" of redux - [docs](https://redux.js.org/recipes/reducing-boilerplate#actions).
It is serializable, it is used by the redux devtools to give us developers a good overview of what is happening inside our application.

Also in typescript enums are by default number based meaning that you lose the uniqueness of your actions. For example:

```
enum AAA {
  A,
  B,
  C
}

enum ZZZ {
  Z,
  Y,
  X
}

console.log(AAA.A === ZZZ.Z) // true
```
Thus, this could be the cause of strange behaviours in your reducers.
