### ISSUE TITLE
store.select function not working as expected

### ISSUE THREAD

**Issue by StephenPaul** [ngrx/platform#1135]
## Minimal reproduction of the bug/regression with instructions:

After upgrading my NGRX store to the latest version, I have been trying to configure my store so that production builds do not fail (because of AOT requirements). I followed this example:
https://github.com/ngrx/platform/issues/306#issuecomment-323829336

Having now done that, I am suddenly having issues selecting state from the store that is more than 1 level deep in the state tree.
For example:
this prints the complete state tree correctly
    `this.store.select(s => s).subscribe(s => console.log(s));`
whereas this prints 'undefined'
    `this.store.select(s => s.branch1).subscribe(s => console.log(s));`

Here is my example code:
https://stackblitz.com/edit/angular-fbmtou

## Expected behavior:

I expect to select from the state tree more than 1 level deep

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
NGRX: 6.0.1
Angular: 6.0.0
Node: 8.10.0
Chrome
Windows 10

**Comment by tdeschryver** [comment]
As you can see in the first print your state looks lik this:
```
{
  app: {
    branch1: {…},
    branch2: {…},
  }
}
```
This is because of the `getReducer` function:
```
export function getReducers() {
  return {
    app: reducers,
  };
}
```

Where it should be: 
```
export function getReducers() {
  return reducers;
}
```

Or you should select your branch as: `s=> s.app.branch1`
