### ISSUE TITLE
Property '0' is missing in type 'MemoizedSelector<object, State>'

### ISSUE THREAD

**Issue by tunecino** [ngrx/platform#1141]
## Minimal reproduction of the bug/regression with instructions:

I'm using Entity to store pagination:

```javascript
export interface Page {
  key: number;
  dataIds: number[];
  query: BrandQuery;
  meta: HeadersMeta;
}

export interface State extends EntityState<Page> {
  currentDataIds: number[];
  currentQuery: BrandQuery;
  currentMeta: HeadersMeta;
  loaded: boolean;
  loading: boolean;
}

export const adapter: EntityAdapter<Page> = createEntityAdapter<Page>({
  selectId: (page: Page) => page.key,
  sortComparer: false
});
```

And those are some of my selectors:

```javascript
export const getBrandsPaginationState = createSelector(
  getItemsRootState,
  state => state.brandsPagination
);

export const {
  selectIds: getBrandsPaginationIds,
  selectEntities: getBrandsPaginationEntities,
  selectAll: getBrandsAllPagination,
  selectTotal: getBrandsTotalPagination
} = fromPagination.adapter.getSelectors(getBrandsPaginationState);

export const getBrandsCurrentQuery = createSelector(
  getBrandsPaginationState,
  fromPagination.getCurrentQuery
);
```
That code works fine. It was written a while ago using older Typescript and NgRx versions. Now after upgrading to Angular 6 (NgRx 6.0.1 and Typescript 2.7.2) it also works fine, until I try to edit the name of any of the existing entities state properties or adding a new one like:

```javascript
export interface State extends EntityState<Page> {
  currentDataIds: number[];
  currentQuery: BrandQuery;
  currentMeta: HeadersMeta;
  isDirty: boolean; // <-- just adding this
  loaded: boolean;
  loading: boolean;
}
```
That breaks my selectors:

![screen shot 2018-06-21 at 14 58 04](https://user-images.githubusercontent.com/5133397/41723668-964061dc-7563-11e8-8c7d-5c44c82dd4c9.png)

And raises the following error:

```
ERROR in src/app/items/reducers/index.ts(205,3): error TS2345: Argument of type 'MemoizedSelector<object, State>' is not assignable to parameter oftype '[Selector<{}, State>, Selector<{}, {}>, Selector<{}, {}>, Selector<{}, {}>, Selector<{}, {}>, Sel...'.
  Property '0' is missing in type 'MemoizedSelector<object, State>'.
```
I have no idea what would cause it and I wasn't able to reproduce it (https://stackblitz.com/edit/ngrx-seed-zr6uv5). Any hint on where should I investigate next is welcome.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
Angular 6.0.5
NgRx 6.0.1
Typescript 2.7.2

## I would be willing to submit a PR to fix this issue

[x] Yes - If I can (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by tdeschryver** [comment]
I think this would resolve itself if you upgrade NgRx to 6.0.1 and Typescript to 27.2.
Any reasons you don't upgrade?

**Comment by tunecino** [comment]
Sorry. I copied versions from the wrong lock file. I just updated. I'm actually using NgRx 6.0.1 and
Typescript 2.7.2

**Comment by tunecino** [comment]
I have also tried with Typescript 2.9.2. Of corse I wasn't able to compile as Angular requires `>=2.7.2 and <2.8.0`versions but at least VSCode kept complaining about it by showing the same error.

**Comment by tunecino** [comment]
The fault was purely mine:

```javascript
export const getBrandsCurrentQuery = createSelector(
  getBrandsPaginationState,
  fromPagination.getCurrentQuery // <-- should be 'fromBrandPagination.getCurrentQuery'
);
```
I guess I've got confused between different states holding the exact same property names. Thank you and sorry for opening this.
