### ISSUE TITLE
AutoLogin/"Remember Me" feature for Auth Module

### ISSUE THREAD

**Issue by Calliostro** [ngrx/platform#1142]
What is the best way to implement an AutoLogin in the Auth module? I mean, if the authorization service saves a token in the local or session storage of the browser and the user reloads the page, that he is automatically logged in.

It would also be nice to have a redirect feature: When the user calls up a bookmark that then displays the login page, and then automatically navigates to the original page.

**Comment by tdeschryver** [comment]
Support questions should be asked on stackoverflow or the [gitter channel](https://gitter.im/ngrx/platform).

**Comment by Calliostro** [comment]
Sorry, I didn't mean to disturb here.

I understood my entry here more as a feature request, because I think that this is a common scenario for many applications.

**Comment by Calliostro** [comment]
My last words on this thread: Whoever is faced with the question of realizing an AutoLogin, have a look at http://brianflove.com/2017/04/10/angular-reactive-authentication/
