### ISSUE TITLE
Effect init does not finnish loading data in time before a route guard service gets called

### ISSUE THREAD

**Issue by axmad22** [ngrx/platform#1148]
This used to work but after Angulars update, occasionally the effects init method when refreshing a page fails to load the data  from the local db just in time before the route guard _canActivate_ method is called.
Is this a bug, or is there a way for the init function to block until it loads the data, so the guard can have something to check against

## Minimal reproduction of the bug/regression with instructions:
``` js
@Effect()
init$: Observable<Action> = defer(() =>
    // Loads the data from index db with a promise
   //  it works just the guard is called before it finish's loading
    from(DbLocal.readData('users'))
      .pipe(
        catchError(() => of({})),
        map(data => new UsersInit(data))
      )
  );
```
## Expected behavior:
Effect init function should finish loading the data before the guard check is reached 

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
NgRx version  6.0.1
angular-cli version 6.0.3
Node version v9.8.0
Chrome
Win 7

**Comment by tdeschryver** [comment]
Hi, I don't think this is a bug but without seeing your guard I'm not 100% sure.

In the guard you can "wait" till your data loaded by using the `filter` operator, as shown in the [book-exist.guard](https://github.com/ngrx/platform/blob/master/example-app/app/books/guards/book-exists.guard.ts) from the example-app.

I'm going to close the issue, if you don't agree feel free to re-open.
If you need help you can always @ me in the [gitter-channel](https://gitter.im/ngrx/platform).
