### ISSUE TITLE
Allow Selector to accept arguments besides state

### ISSUE THREAD

**Issue by tsugitta** [ngrx/platform#1152]
Thanks for this awesome library!

With [Reselect](https://github.com/reduxjs/reselect#accessing-react-props-in-selectors), we can call a selector with arguments like below (almost copied from Reselect's README):

```ts
import { createSelector } from 'reselect'

const getVisibilityFilter = (state, props) =>
  state.todoLists[props.listId].visibilityFilter

const getTodos = (state, props) =>
  state.todoLists[props.listId].todos

const getVisibleTodos = createSelector(
  [ getVisibilityFilter, getTodos ],
  (visibilityFilter, todos) => {
    switch (visibilityFilter) {
      case 'SHOW_COMPLETED':
        return todos.filter(todo => todo.completed)
      case 'SHOW_ACTIVE':
        return todos.filter(todo => !todo.completed)
      default:
        return todos
    }
  }
)

const todos = getVisibleTodos(state, props)
```

but ngrx's selector does not seem to have such a feature. It will be helpful for me if it's possible.

## Other information:

In the above example of Reselect, the props is not used in `createSelector`, but actually it also can be used like below:

```ts
import { createSelector } from 'reselect'

const shootingById = createSelector(
  [shootings,(state, shootingId) => shootingId],
  (shootings, shootingId) => head(shootings.filter(s => s._id === shootingId))
);

const shootings = shootingById(state, someId)
```

ref: https://github.com/reduxjs/reselect/issues/272#issuecomment-316754662 

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
Selectors can already be created using arrays. See https://github.com/ngrx/platform/blob/master/modules/store/spec/selector.spec.ts#L126

**Comment by tsugitta** [comment]
@brandonroberts 
The point I wanted to say is not passing multiple selectors to a `createSelector`, but passing arguments besides State (`props` in the example) to a selector created by `createSelector`.

**Comment by brandonroberts** [comment]
What's your proposed change?

**Comment by timdeschryver** [comment]
If this is something we want, I can provide a PR.

**Comment by brandonroberts** [comment]
Seems reasonable to me. Let @tsugitta put in the PR if they still want to work this change.

**Comment by tsugitta** [comment]
thanks, let me try to submit the PR.

**Comment by timdeschryver** [comment]
I got one ready tho 😅 
@tsugitta you can checkout the [commit](https://github.com/timdeschryver/platform/commit/a3662b74ebd41ce445569f99872ce22417543d98) if this is what you want you can let me know and I'll open a PR. If not you can submit a PR.

**Comment by tsugitta** [comment]
@timdeschryver 
seems great, please open a PR.

**Comment by Abhay-Joshi-Git** [comment]
Does [documentation of the selectors](https://ngrx.io/guide/store/selectors) reflect this change ? I tried to check there but couldn't find it out.

**Comment by timdeschryver** [comment]
It's documented at https://ngrx.io/guide/store/selectors#using-selectors-with-props @Abhay-Joshi-Git . Are the docs missing something?

**Comment by Abhay-Joshi-Git** [comment]
ok, thanks for sharing this.
