### ISSUE TITLE
repo: Add pull request template

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1166]
## I would be willing to submit a PR for the docs :heart:

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

Use Angular template for reference:  https://raw.githubusercontent.com/angular/angular/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by MatsumotoKou** [comment]
I hope that commit message guideline is also added to CONTRIBUTING.md of this project.
Because angular's PULL_REQUEST_TEMPLATE.md checks it.

https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md

**Comment by MatsumotoKou** [comment]
@brandonroberts 
May I submit a draft proposal :smiley:?

**Comment by kouMatsumoto** [comment]
@brandonroberts 
May I submit a draft proposal :smiley:?
