### ISSUE TITLE
Example of @ngrx/entity and HttpClient

### ISSUE THREAD

**Issue by dalu** [ngrx/platform#1167]
### On [StackOverflow](https://stackoverflow.com/questions/tagged/ngrx) using the `ngrx` tag

I'm not on Stackoverflow, I boycott them. It's a cesspool if circle jerking aholes.

### In our gitter support channel at https://gitter.im/ngrx/platform

Sure I could join that channel however EVERYONE having the same issue would have to join the channel and ask again and again and again and again and...
https://youtu.be/9VDvgL58h_Y?t=4m27s

---

Can you provide an example of @ngrx/entity and HttpClient?

I've watched 3 videos, read 2 blog posts, none explain how you actually sync with your database backend via HttpClient.
Let's assume you have a regular restful http api.
```
GET / = list all
GET /:id = find one
POST / = create
PUT /:id = update
DELETE /:id = remove one
DELETE / = remove all
```
Can you provide an example how to do this?

**Comment by galenp** [comment]
These are very unrelated concepts.

**Comment by ngnam** [comment]
```
getPizzas(): Observable<Pizza[]> {
    return this.http
      .get<Pizza[]>(`/api/pizzas`)
      .pipe(catchError((error: any) => Observable.throw(error.json())));
  }

  createPizza(payload: Pizza): Observable<Pizza> {
    return this.http
      .post<Pizza>(`/api/pizzas`, payload)
      .pipe(catchError((error: any) => Observable.throw(error.json())));
  }

  updatePizza(payload: Pizza): Observable<Pizza> {
    return this.http
      .put<Pizza>(`/api/pizzas/${payload.id}`, payload)
      .pipe(catchError((error: any) => Observable.throw(error.json())));
  }

  removePizza(payload: Pizza): Observable<Pizza> {
    return this.http
      .delete<any>(`/api/pizzas/${payload.id}`)
      .pipe(catchError((error: any) => Observable.throw(error.json())));
  }
```

 ```
@Effect()
  loadPizzas$ = this.actions$.ofType(pizzaActions.LOAD_PIZZAS).pipe(
    switchMap(() => {
      return this.pizzaService
        .getPizzas()
        .pipe(
          map(pizzas => new pizzaActions.LoadPizzasSuccess(pizzas)),
          catchError(error => of(new pizzaActions.LoadPizzasFail(error)))
        );
    })
  );
```

**Comment by galenp** [comment]
* use an ngrx effect to GET the data from your API and store it in your state (see above example)
* as your user trigger actions in your UI this will correspond to ngrx actions i.e createPizza, updatePizza
* since your UI components do not change the state of your application directly you use an ngrx reducer to update your apps local state. This is where this ngrx entity library comes in to make that job easier. Note: this is not for your backend sync.
* however as your local app state is updated with ngrx/entity you also have an ngrx effect that is triggered on the appropriate actions to call your server API. (the above code snippet is missing this).

Roughly something like below (i didn't syntax check it)
```
@Effect()
 addPizza$ = this.actions$.ofType(pizzaActions.ADD_PIZZA).pipe(
   switchMap((action) => {
     return this.pizzaService
       .createPizza(action.payload)
       .pipe(
         map(pizzas => new pizzaActions.AddPizzasSuccess(pizzas)),
         catchError(error => of(new pizzaActions.AddPizzasFail(error)))
       );
   })
 );
```

* if your use case is only a single user editing the data at one time then this is probably all you need. Since the user making the change has already had their app state updated. (They don't need a refresh from the server).

Btw there is plenty of material out there with thorough examples. 
[This is a good one;](https://blog.realworldfullstack.io)

**Comment by dalu** [comment]
Thanks for the reply. I know how to use Http, but a) I was asking for HttpClient (doesn't matter really) and b) I was asking for this in conjuction with @ngrx/entity. I mean where are you getting the data from, and where are you syncing to the server side?

Regarding link, I beg to differ, but thanks anyway. cloud cloud cloud hype hype buzzword in your link. Anything one can do wrong, setting on inflated price infrastructure where AI makes decisions if your service is worthy of being kept alive (https://medium.com/@serverpunch/why-you-should-not-use-google-cloud-75ea2aec00de).
There's a whole generation learning the wrong concept. It's sad really.

Ok what I was looking for, I'm writing my 2nd version of a server side endpoint generator. I provide it with the structs (and if it was an OO language they'd be classes, I use Go if you wondered) that represent the data model and it generates the repository code and the handlers (or controllers if you will) and the routes.
Additionally it generates angular services for now that are compatible to talk to those generated endpoints, very similar to what you've posted. But you're using a deprecated HttpModule module instead of HttpClientModule. Idk if you didn't care to answer why bother answering at all? Not trying to be rude but wondering.

So now I was looking for a standard way of using those services in a "reactive" (buzzword) way. I was about to roll my own when I stumbled upon your project, ngrx. And there I saw `@ngrx/entity`.
Well my idea was similar to yours. Having an in memory store of data that is first filled, then updated. It would return Observables one could subscribe to and putting or updating data in the store would fire http requests being sent out to sync with the backend. But there doesn't seem to be an interface for actually updating or even getting data.

So again my question:
Can you provide an example, I mean why do you have `@ngrx/entity` when it does nothing to sync with the backend? Isn't this rather overengineered? It does remind me of Java and its OO overhead (where the overhead is 90% of the code). Yes I am being serious and no I'm not trolling.
What I'm looking for is a standard way to represent or .. to integrate syncing with the backend.
Where does the backend fit in here? Where can I plug my e.g. ProfileService or BlogpostService or w/e?
Can you give an example of that? The blog is a nice diary but rather irrelevant.

**Comment by tdeschryver** [comment]
@ngrx/entity does not "sync" with the backend, meaning it don't call any http service.
What it does offer, are the basic CRUD operators to manage your entity collections client side.

**Comment by dalu** [comment]
Why do you evade the question?

**Comment by tdeschryver** [comment]
> I mean why do you have @ngrx/entity when it does nothing to sync with the backend? Isn't this rather overengineered?
I think I answered this question?

If you want an example you can take a look at example-app in the project.
[books.reducer](https://github.com/ngrx/platform/blob/master/example-app/app/books/reducers/books.reducer.ts)
[books.effects](https://github.com/ngrx/platform/blob/master/example-app/app/books/effects/book.effects.ts)
[google-books.service](https://github.com/ngrx/platform/blob/master/example-app/app/core/services/google-books.service.ts)

**Comment by dalu** [comment]
*sigh* Then what is entity for?
I mean... no disrespect, but do you understand what I'm trying to tell you?
Why have an entity api when it doesn't sync with the backend?
It's the very definition of what a service should do, only in your, ngrx, world.
So why not do 1+1=2.
Well anyhow I guess I'll have to roll my own after all.
Rethink your design because currently you're calling apples oranges and oranges do what apples do.
Why have an effect decorator when you have an entity library.
Idk if you're just not seeing the forest for the trees :)
And isn't entity there to reduce the effects boilerplate?

What is entity for then?

**Comment by dalu** [comment]
https://github.com/johnpapa/angular-ngrx-data/blob/master/docs/faq.md/#how-is-ngrx-data-different-from-ngrxentity

This pretty much answers it.
I'd still suggest you rethink your design because right now it's unintuitive and counter-productive.
The juice, the core of the operation is called a side-effect...
Well it doesn't really answer the issue, an example of ngrx/entity with HttpClient, but angular-ngrx-data might be what I'm looking for short of re-inventing the wheel
