### ISSUE TITLE
Combining rxjs state selections yields value inconsistencies

### ISSUE THREAD

**Issue by ericp96** [ngrx/platform#1168]
## Explanation:
Combining multiple selections on the store induces scenarios where state values passed into a combining function are inconsistent.

e.g. below sometimes returns false and it will emit more than once:
```
Observable.combineLatest(
    this.store.select(state => state.itemA),
    this.store.select(state => state.itemA),
).map(([a, stillA]) => a === stillA)
```

## StackBlitz:
https://stackblitz.com/edit/ngrx-seed-sazzq6

## Expected behavior:
In the example given you should only see one emission per state selection and the value should always be true.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
N/A

## Other information:
**This is not an explicit bug with ngrx, but a characteristic of rxjs being synchronous.  However this does pose several pitfalls for ngrx users.** 

Oftentimes it is necessary to derive values from the same piece of state in different selectors and combine their results only when necessary.

There are three issues with relying on eventual consistency:

1. Unintended states being passed into the combining function
2. Excessive invocation of code more than once.
3. Potential for excessive UI updates since each emission of a resulting observable will trigger change detection.  If not correctly batched then jank could occur.

## Proposals:
Please provide direction as to the best way to accomplish the selection of multiple pieces of state.  Libraries such as react-redux do this by forcing you to coerce all your results into a single combining function `mapStateToProps`, ngrx provides no direction which can lead to the pitfalls above.

Potential solutions:
1. Suggest the use of a combining selector when necessary,  Similar to `mapStateToProps`.
2. Create an additional select operator called `selectAll` that takes in a variadic number of selectors and returns an array with value in the corresponding position.  Similar to Observable.combineLatest

## I would be willing to submit a PR to fix this issue

[X] Yes
[ ] No

**Comment by tdeschryver** [comment]
You can fix this by adding a `debounceTime` as explained in [A glitch in combineLatest and how to fix it](https://blog.strongbrew.io/combine-latest-glitch/).

I don't know how others feel about a `mapStateToProps` tho.

**Comment by ericp96** [comment]
Thank you for the suggestion, I was able to circumvent the inconsistency as you had mentioned, but this seems like a convenience that ngrx should have.

I went ahead and rolled my own `selectAll` and the usage seems consistent with what I would expect:

```
this.store.pipe(
 selectAll(selector1, selector2, selector3),
 map(([val1, val2, val3]) => ...)
)
```

The gotcha here is that you end up one layer deeper than you would like to be when doing a `combineLatest`:

```
Observable.combineLatest(
  this.store.pipe(
   selectAll(selector1, selector2, selector3)
  ),
  secondObservable
).map(([[val1, val2, val3], obs2Va ]) => ...)
```

But it still feels like a nice extension point.  I would be interested in seeing what others think.

**Comment by brandonroberts** [comment]
RxJS issue aside, the efficient way to compose multiple pieces of state is to do it at the selector level before its passed to store.select. This provides memoization for each argument as shown [in the docs](https://github.com/ngrx/platform/blob/master/docs/store/selectors.md#using-selectors-for-multiple-pieces-of-state).

**Comment by tim1016** [comment]
Can you update the link "in the docs" ?

> RxJS issue aside, the efficient way to compose multiple pieces of state is to do it at the selector level before its passed to store.select. This provides memoization for each argument as shown [in the docs](https://github.com/ngrx/platform/blob/master/docs/store/selectors.md#using-selectors-for-multiple-pieces-of-state).

**Comment by tim1016** [comment]
Nevermind it is quite simple. I could do it .
