### ISSUE TITLE
Schematics: devkit dependencies necessary?

### ISSUE THREAD

**Issue by cmckni3** [ngrx/platform#1176]
Are the `angular-devkit` dependencies required in a project for `@ngrx/schematics`?

I didn't see anything mentioned in the [docs](https://github.com/ngrx/platform/tree/master/docs/schematics) but the schematic commands appear to work without adding the dependencies to the project.

## I would be willing to submit a PR for the docs :heart:

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
Yes, they are required, but are implicitly installed with the Angular CLI. We require a specific version to maintain a minimum version is installed, so that you don't try to use newer schematics with older versions of the CLI.

**Comment by cmckni3** [comment]
Strange was getting this in a new project.

```
warning " > @ngrx/schematics@6.0.1" has unmet peer dependency "@angular-devkit/core@^0.6.0".
warning " > @ngrx/schematics@6.0.1" has unmet peer dependency "@angular-devkit/schematics@^0.6.0".
```

**Comment by brandonroberts** [comment]
That's because the CLI is pinned to version `0.6.8` of those packages instead of `^0.6.0`. We may end explicitly pinning those versions as `dependencies` to avoid this issue or remove them altogether if they are stable enough to be implicitly included.
