### ISSUE TITLE
Add Bazel support for schematics tests

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1185]
## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

All other packages run tests through Bazel except for schematics. Setup is little more difficult due to referenced collection files. May be able to use https://github.com/angular/angular/tree/master/packages/elements/schematics for reference

**Comment by roopkt** [comment]
Hi @brandonroberts can I start working on this I want to create PR for this one please let me know.
