### ISSUE TITLE
actions holds in memory causing memory leaks 

### ISSUE THREAD

**Issue by Liork1** [ngrx/platform#1188]
Hi,

I'm using v5.0.0 in my app in my angular 5 application.
I see that every time I'm dispatching an action, the browser still holds refrence to the object and it causing a memory leak.

for example, the below action being dispatched 44 times during app cycle and it holds 44 refrences (attached screenshot)
**action**
```
export class ballOut implements ActionWithPayload<any> {
  readonly type = BINGO_GAME_BALL_OUT;
  constructor(public payload: any) {
    this.payload = {
      balls: payload.balls,
      bingoGameType: payload.bingoGameType
    }
  }
}
```
**usage:**
`this.store.dispatch(new BingoGameActions.ballOut({balls: calls, bingoGameType: BingoGameType.Current}));`

memory leaks:
![image](https://user-images.githubusercontent.com/12165229/42942896-f8f94958-8b69-11e8-9c07-11443330770c.png)

The question is relevant for all actions in my application.

Is there any known issues here? somthing I'm doing wrong? 
How can I free the memory?

Regards,
Lior

**Comment by timdeschryver** [comment]
Hi,

Are you using some meta-reducers (ngrx-store-freeze) or an external tool like the redux devtools?
These could be the reason the reference to the actions stays in memory.

**Comment by timdeschryver** [comment]
@Liork1 any updates on the question above?

**Comment by Liork1** [comment]
Hi @timdeschryver, sorry for not replying back.
removing the exact 2 meta-reducers you suggested "fixed" the problem.
Thank a lot!

**Comment by SzymonSliwinski** [comment]
I've faced with the same issue but I'm not using any meta-reducers and plugins to track store.
I've placed more info here https://stackoverflow.com/questions/76113632/angular-constantly-growing-store
