### ISSUE TITLE
EffectsModule.forRoot([]) required

### ISSUE THREAD

**Issue by gmeans** [ngrx/platform#119]
We are migrating an app we just started that only has effects within a feature module. We ran into errors after migrating the feature to use `EffectsModule.forFeature()` and solved it by placing  the following in the app module.

```
EffectsModule.forRoot([])
```

Not sure if this is a documentation thing, or something that can be enhanced within `.forFeature()` to be able to handle not having a parent `.forRoot()` call.

Thanks!

**Comment by MikeRyanDev** [comment]
Yeah, the `forRoot()` call is required as it sets up some root-level features. Will happily accept a PR that clarifies this in the documentation for Effects.
