### ISSUE TITLE
createFeatureSelector with two arguments

### ISSUE THREAD

**Issue by abritabroad** [ngrx/platform#1191]
## Minimal reproduction of the bug/regression with instructions:

I am trying to use createFeatureSelector with two type arguments as per the example-app:

/**
 * Layout Reducers
 */
export const getLayoutState = createFeatureSelector<State, fromLayout.State>(
  'layout'
);

The compiler wants 1 argument, not two.

https://stackblitz.com/edit/ngrx-feature-selector?file=src%2Fapp%2Freducers%2Findex.ts

## Expected behavior:

Accept two type arguments.

ngrx v6.0.1, Angular v6.0.9 and AngularCLI v6.0.8.

## Other information:

https://stackoverflow.com/questions/51432742/ngrx-createfeatureselector-with-two-type-arguments/51433977?noredirect=1#comment89857554_51433977

## I would be willing to submit a PR to fix this issue

[X] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Hi, this is a unreleased feature which will become available in the next release.
You can use the code below for now.
```
export const getLayoutState = createFeatureSelector<fromLayout.State>('layout');
```
