### ISSUE TITLE
RFC: Add optional namespace to Store so features can define which store to use

### ISSUE THREAD

**Issue by bniedermeyer** [ngrx/platform#1195]
Currently there is no effective way to bind a feature store to a root store. Adding an optional configuration value to define a namespace for a store can help to resolve which store should be used by a feature module when multiple stores are present. This won't be needed 99.9% of the time but would allow ngrx to be used in ways outside of traditional Angular applications without clashing with other stores. 

## Use Case
I am using a library that uses its own ngrx store to maintain its state. This store is a root store, not a feature store. In a simple Angular app this works fine as the app is too simple to necessitate maintaining its own store. 

I've run into problems when it comes to using the library in an application that also uses ngrx. When I add a feature store that uses the library I end up with my the feature being attached to the library's store instead of my application store. My current theory is this is happening due to Angular's DI hitting the library's store in the injector tree first since it's in the same module as the feature store. 

An ideal implementation for this would add the ability to "name" stores by defining a `namepace` in the `storeConfig`. Feature stores would then declare which store they are intended for or would default to using the unnamed store just like today. 

__Example:__
*Store module with namespace*
```typescript
/* lib.module.ts */
imports: [
	// the namespace value in the storeConfig means that any features that interact with 
	// this store must define the same namespace
	StoreModule.forRoot(reducers, {namespace: 'my-lib'})
]

/* lazy-loaded feature module in library*/
imports: [
	// namespace binds this feature store to the 'my-lib' store created above
	StoreModule.forFeature('my-feature', reducers, {namespace: 'my-lib'}) 
]
```  

*Application that uses ngrx and consumes the above library*
```typescript
/* app.module.ts */
imports: [
	MyLibrary, // library defined above with it's own store
	StoreModule.forRoot(reducers) // anything that does not have a namespace uses this store
]

/* Feature module in app */
imports: [
	StoreModule.forFeature('my-other-feature', reducers) // does not attach to 'my-lib' store
]
```

This would enable those who build libraries with ngrx to effectively declare what should be included in their store and prevent clashes with other applications that use ngrx. 

## Describe any alternatives/workarounds you're currently using
I have a working branch of the library in question that uses a feature store instead of maintaining its own root store with no issues. However, this requires that anyone who consumes the library setup ngrx in their app - which hopefully can be avoided so that those who don't use ngrx can also use the library.
 
## Other information:
As an implementation detail that can probably be worked out later if it's decided to implement this - working with the [Angular injector directly](https://angular.io/guide/dependency-injection#appendix-working-with-injectors-directly) may be the easiest way to achieve this functionality.

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Would need some guidance on the best place to start)
[ ] No

**Comment by timdeschryver** [comment]
I get why you would want this, but this would break the "1 store for an application" concept.
Therefor, this use case should be handled by the lib instead of NgRx in my opinion.

I'm curious how others feel about this tho!

**Comment by bniedermeyer** [comment]
I see your point. The key to why this might be ok in my opinion is that libraries with their own store wouldn't expose that store to end users so you still have a "1 store per application" concept. The users of the library interact with it though the api, which dispatches actions and interacts with its store in other ways behind the scenes. A user shouldn't be able to tell if your library is using ngrx or not.

I guess the main question at hand is do we want to force anyone creating a library using ngrx to force their users to also use (or in some cases learn) ngrx even if they don't need it in their app, or give the ability for libraries built with ngrx to be more widely used.

**Comment by manklu** [comment]
> the key to why this might be ok in my opinion is that libraries with their own store wouldn't expose that store to end users

How should time travel debugging work with multiple stores? At least it's more complicated.

> or in some cases learn

I think there isn't much to learn. Follow some simple instructions to setup the root store.

**Comment by bniedermeyer** [comment]
We ended up hooking our library in through a feature store and requiring any apps that consume it to also be powered by ngrx.
