### ISSUE TITLE
How to prevent action dispatch during time travel with router-store

### ISSUE THREAD

**Issue by codemasterover9000** [ngrx/platform#1196]
Hi,

I am rewriting an existing app to use ngrx. In the app there are components instantiated through route changes that load data in ngOnInit(). I replaced this with an action dispatch. Problem is that when using time travel in dev-tools with router-store the action get dispatched again through the actual init code of the component. 

I thought of using an effect and hooking into router events but I'm not sure if this is the right way to handle this.

So my question is how does one handle this case?

Thanks!

**Comment by dummdidumm** [comment]
Once #955 gets merged you can use "lock" to ignore all new actions, so time traveling will work without disturbance.
