### ISSUE TITLE
Failing to add feature state to an angular 6 library 

### ISSUE THREAD

**Issue by joelmuskwe** [ngrx/platform#1197]
Used the following steps below:
1. ng new my-demo
2. cd my-demo
3. yarn add @ngrx/{store,effects,entity,store-devtools,router-store,schematics}
4. ng config cli.defaultCollection @ngrx/schematics
5. ng g library demo-products
6. ng generate store State --project demo-products -m demo-products.module.ts

## Expected behavior:
Expecting to add a feature state to the demo-products library. but i am getting the following error:
Cannot read property 'getEnd' of undefined

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
ngrx - v6.0.1
angular - v6.0.3
node - v8.11.1

**Comment by brandonroberts** [comment]
What version of the CLI are you using?

**Comment by joelmuskwe** [comment]
i am using Angular CLI: 6.0.8

**Comment by brandonroberts** [comment]
Fixed via https://github.com/ngrx/platform/pull/1213
