### ISSUE TITLE
Effects: Document effects as functions

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1198]
## I would be willing to submit a PR for the docs :heart:

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

Effects can be defined in two ways but only one way is documented.

Property Assignment
```
@Effect()
this.effect$ = this.actions$.pipe(ofType('SOME_ACTION'));
```

Using a function that is called without arguments and returns the effect.
```
@Effect()
effect$() {
  return this.actions$.pipe(ofType('SOME_ACTION'));
}
```

Defining effects using a function allows you to use defaults that can be overridden during testing. This could be a useful pattern in providing test schedulers or custom values during testing.

```
@Effect()
effect$(waitTime = 3000, scheduler: Scheduler | undefined = undefined) {
  return this.actions$.pipe(ofType('SOME_ACTION')).pipe(delay(waitTime, scheduler));
}
```

**Comment by timdeschryver** [comment]
Should the example app also be updated using this approach instead of injecting these values?
[books.effects](https://github.com/ngrx/platform/blob/master/example-app/app/books/effects/book.effects.ts#L24).

**Comment by brandonroberts** [comment]
Yes, I think that's a good place to put an example
