### ISSUE TITLE
Suggestion: add a link to the new docs at the top of the migration guide

### ISSUE THREAD

**Issue by alexjlockwood** [ngrx/platform#120]
I have been struggling to migrate to v4 for a while and only just discovered that there are a bunch of new docs here: https://github.com/ngrx/platform/tree/master/docs/store

Probably my fault for missing it, but it might save you all some bug reports if you added the link to the top of the migration guide. :)

**Comment by MikeRyanDev** [comment]
Will gladly accept a PR for this.

**Comment by timdoes** [comment]
Me too :)

I was hunting down CHANGELOGs and then saw the migration link via this issue.

@alexjlockwood 
If you don't have time, I can create the PR

**Comment by alexjlockwood** [comment]
@timdoes Sure, feel free. I'm on my phone now so not as easy. :)
