### ISSUE TITLE
Schematics: Generating feature and importing it into feature module causes merge conflict

### ISSUE THREAD

**Issue by wolfhoundjesse** [ngrx/platform#1202]
## Minimal reproduction of the bug/regression with instructions:
Following the [example for generating a feature:](https://github.com/ngrx/platform/blob/master/docs/schematics/feature.md)

> ng generate module User --flat false
> ng generate feature user/User -m user.module.ts --group

## Expected behavior:

Generate a User feature set within a user folder and register it with the user.module.ts file in the same user folder.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
NgRx - v6.0.1
Angular -v 6.1.0
@angular/cli - v6.1.1
@angular-devkit/schematics - v 0.7.1
Node - v10.7.0
Arch Linux - 4.14.56-lts

## Other information:
The above results in an error: A merge conflicted on path "/src/app/user/user.module.ts".

The error is thrown from [@angular-devkit/schematics/src/tree/host-tree.ts](https://github.com/angular/angular-cli/blob/9582b84603182d43dbb9f0e6a8db600e83921f8a/packages/angular_devkit/schematics/src/tree/host-tree.ts), line 177:
`if (!creationConflictAllowed) {
              throw new MergeConflictException(path);
            }`

While neither the _reducer_ nor the _effect_ Rule supplies a `MergeStrategy`, both would be writing to the same file, _user.module.ts_ in this case. `chain` is supposed to allow each rule to complete before moving on to the next, so I'm not certain whether this is an NgRx issue or an @angular-devkit/schematics issue (or something else entirely).

If you pass a MergeStrategy in either the _reducer_ or _effect_ Rule as below, it works as expected.
`return chain([
      branchAndMerge(
        chain([addImportToNgModule(options), mergeWith(templateSource)]),
        MergeStrategy.AllowOverwriteConflict
      ),
    ])(host, context);`

That's no fix, though. ;-)

## I would be willing to submit a PR to fix this issue

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Does this also occur if you're using angular cli 6.0 ?

**Comment by wolfhoundjesse** [comment]
> npm uninstall @angular/cli
> npm cache verify
> npm install @angular/cli@">=6.0.0 < 6.1.0"
Resulted in a dependency warning, so I did the same thing for that package:
> npm uninstall @angular-devkit/core
> npm cache verify
> npm install @angular-devkit/core@^0.6.0

Now its @angular/cli - v6.0.8 and @angular-devkit/core -v0.6.8

Everything works now. Where would be a good place to learn how to find when the change took place? I went through the releases for the cli until I found the first commit after v0.6.8. I cloned the repository and switched to that commit and ran the build script, but I'm not entirely sure what the process would be from here. I'd like to get better at tracking things down if you can point me in the right direction.

**Comment by wolfhoundjesse** [comment]
I just noticed a warning that says @ngrx/schematics require @angular-devkit/core@^0.6.0. I am on 0.7.1. That explains why it worked when I downgraded everything. Now I'm getting the same error as the one in [this issue.](https://github.com/ngrx/platform/issues/1120)

I'll close this for now and see if it's resolved with the next release.

**Comment by timdeschryver** [comment]
@wolfhoundjesse in the [release notes](https://github.com/angular/angular-cli/releases), I did a search on `MergeStrategy` and there was a section 'Two notes about changes in Schematics in 0.7.0:' in the 6.1 release.
