### ISSUE TITLE
[Example App]: readme.md pointing stackblitz to an old commit

### ISSUE THREAD

**Issue by orizens** [ngrx/platform#1215]
## Other information:
the example app loaded in stackblitz is pointing to commit 61cbfe537f9df8cef3dd4a6ee0b8f483e49653f4 which is version 5.2 from March 2018. should be pointing to latest in master or otherwise to a later commit.
i.e, a pr that i opened and was merged, fixes an issue with loading images via https - https://github.com/ngrx/platform/pull/1107

## I would be willing to submit a PR for the docs :heart:

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
This is a known issue. Latest master fails to open in StackBlitz directly from GitHub because of schematics blueprint files. What I have in mind is to read the example-app files and use the [StackBlitz sdk](https://stackblitz.com/docs#generate-and-embed-new-projects) to open the example app.

**Comment by orizens** [comment]
thanks @brandonroberts i'll into it.
