### ISSUE TITLE
Selectors: createSelectorFactory should not have a MemoizeFn as argument

### ISSUE THREAD

**Issue by UserGalileo** [ngrx/platform#1217]
I'm opening this issue to go on with my last post on #1192.
Currently, `createSelectorFactory` accepts a `MemoizeFn` in order to handle the memoization process.
However, I find this approach problematic as the developer who wants to use `createSelectorFactory` needs to know what a `MemoizeFn` does, how it does it, who uses it and how.

It is difficult to think that anyone who wants to use selectors' public api could write a function such as **`defaultMemoize`**. It needs a projector function and it needs to call it, it needs to provide an object containing 2 functions, and calculate results in one of them. I feel this shouldn't be the responsibility of the developer, I think that a dev should only need to pass the comparers (for both arguments and result) to `createSelectorFactory`, and it should be the library that calls the projector function in case arguments/result are different. Everything should be as pure as possible, and as of now it isn't (for me, of course).

I'm saying this because after #1192 I wanted to help writing down docs for this part (which is really important, at least for me because I see large enterprise applications with hundreds of entities/selectors and I need createSelectorFactory more than ever) but I just can't figure out how to explain this process in a simple way. It is simple to explain why `createSelectorFactory` is needed, how `createSelector` uses it and what it does, but it's not simple to explain what the arguments are, why you should provide them to the function and how to write them (`MemoizeFn`, `AnyFn`, `defaultMemoize`, functions called with `apply()`, etc...).

For now, the only option I thought about was creating a memoizeFactory (sort of) which takes the `defaultMemoize` function and passes down the comparers, and then use this final function in `createSelectorFactory`. But this way, the dev doesn't touch anything inside `defaultMemoize`, so this mechanism is quite strange: would I ever need to write a `MemoizeFn` different from `defaultMemoize`? If yes, this can make sense (but nothing comes to mind to me), if not I think it should be removed from the public api and comparers should be the only thing passed down to `createSelectorFactory`.

Let me know what you think! :) Thanks guys.

## Describe any alternatives/workarounds you're currently using
As I said, a factory function for defaultMemoize.

## Other information:
None.

## If accepted, I would be willing to submit a PR for this feature
I would submit a PR for the docs part, for the actual code I have to think about it. The "selectors" part of the repo is quite new to me.

**Comment by alex-okrushko** [comment]
>  would I ever need to write a MemoizeFn different from defaultMemoize? If yes, this can make sense (but nothing comes to mind to me)

It could be that you'd want to provide different memoization strategy. E.g. `defaultMemoize` still remembers only the latest results, while one might need to cache all previous results.

**Comment by UserGalileo** [comment]
@alex-okrushko I see, thanks for the reply :)
At this point I think the issue could be closed, I didn't have that scenario in mind. Makes sense.
I think I could write down the docs for the `createSelectorFactory` / Memoization part, the only thing I have to figure out is where to put it because I think it'll be a bit complicated and I'm not sure if it fits in the selectors docs, since 99% of people won't use these techniques.
What do you think? Would another .md file be better just for this part?

**Comment by brandonroberts** [comment]
If you to create an "Advanced Topics" page that's fine.
