### ISSUE TITLE
where is go, replace, search, show, back, forward in @ngrx/router-store on v4?

### ISSUE THREAD

**Issue by junimohano** [ngrx/platform#122]
Where is the document for @ngrx/router-store for v4?
MIGRATION.md has no manuals..

import { go, replace, search, show, back, forward } from '@ngrx/router-store';
this one was working at v1 not v4.

I can not find any documentation anywhere.

**Comment by brandonroberts** [comment]
Duplicate of #107

**Comment by mikedanylov** [comment]
At least go, replace, back and forward can be easily replaced by Angular Router and `Location` 
https://angular.io/api/common/Location
