### ISSUE TITLE
RFC: reducers/actions as classes, no magic strings, reduced boilerplate

### ISSUE THREAD

**Issue by michael-lang** [ngrx/platform#1221]
## Feature Concept
Boilerplate is the biggest opportunity for improvement in applications using ngrx. Schematics are fine, but you still have to edit that code and add to it.  What if the entire way you defined actions and reducers didn't have any duplicate code in the first place?

Instead of writing action name constants, action classes to define the payload, and reducers to process the actions into the state, just write a single class with a function for each action.  The rest is done for you.

``` 
(book.store.ts)
export class BookActions extends FeatureActions<BookState> {
  @FeatureAction<BookState>()
   search(state: BookState, query: string) {
      return {...state, loading: true, error: ''}
  }
}
```

Your action name becomes: [ClassName] functionName
example: "[BookActions] search"

This replaces the need for a separate actions file and reducers file.  The 'FeatureAction' decorator is used by the library code to generate a reducer that you can register in a module.

`StoreModule.forFeature('books', booksReducer)`

The 'booksReducer' isn't magic, you create it with a few lines of code.  This code can be optimized over time to shorten it up, but at least it isn't a unioned type you have to keep remembering to add new actions to.

``` 
(book.store.ts)
export const bookActions = new BookActions();
const reducer = FeatureActions.createReducer(initialBookState, bookActions);
export function booksReducer(state: BookState, action: Action): BookState {
  return reducer(state, action);
} //reducer could be used in dev, but with AOT this function wrapper is needed.
```

You can dispatch actions with type safety easily using store.dispatch as usual...

```
  constructor(private store: Store<BookFeatureAppState>) { ... }
  search(query: string) {
    this.store.dispatch(bookActions.create(bookActions.search, query));
  }
```

if a string was not specified in this last snippet, the typescript compiler would tell you the types didn't match, since it knows all about the search function.  I know you get this with current action classes pattern as well, I'm more showing that you don't lose that with this new pattern.

Effects are enhanced also with a new pipeable operator to replace 'ofType' and the following 'map' call, with a single operator.

```
  @Effect()
  loadCollection$: Observable<Action> = this.actions$.pipe(
    ofAction(collectionActions.load),  // <-- new operator
    switchMap(() =>
      this.db.query('books').pipe(
        toArray(),
        map((books: Book[]) => collectionActions.create(collectionActions.loadSuccess, books)),
        catchError(error => of(collectionActions.create(collectionActions.loadFail, error)))
      )
    )
  );
```

This operator could easily be enhanced over time to allow specification of multiple actions with the same payload to use the same effect. Right now it only supports one.

## Other information:

I have created a new repo that includes the 'FeatureActions' base class, 'FeatureAction' decorator, and the 'ofAction' pipeable operator. The repo includes a proof of the concept using the sample book application from nrgx platform.

Sample app, including the library code to make it all work:
https://github.com/michael-lang/book-sample-ngrx

The new library code is only 134 lines of code, 20 of which is documentation comments. The amount of application store code needed is cut nearly in half. Selectors work the same, but actions and reducers are combined into one. Actions are still serializable and interoperate transparently with other reducers not using this new pattern.

## If accepted, I would be willing to submit a PR for this feature

[ x ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by michael-lang** [comment]
Here is another effect that actually uses the action payload.

```
@Effect()
  addBookToCollection$: Observable<Action> = this.actions$.pipe(
    ofAction(collectionActions.addBook),
    mergeMap(book =>
      this.db.insert('books', [book]).pipe(
        map(() => collectionActions.create(collectionActions.addBookSuccess, book)),
        catchError(() => of(collectionActions.create(collectionActions.addBookFail, book)))
      )
    )
  );
```

**Comment by brandonroberts** [comment]
@michael-lang thanks for the proposal! If this pattern works for you that's great, but we won't be adding this to the core API. Actions are meant to describe events, and shouldn't contain logic for updating state. That way you can handle actions across multiple effects and reducers. Maintaining type safety is also something we won't compromise on, and with the usage of decorators lends itself to that.

**Comment by michael-lang** [comment]
This issue has been closed for a while. I've waited to reopen until I used it more in production. Now that I have used it for a full-lifecycle, I'd like to revisit. Do you mind re-opening for a bit for some discussion, @MikeRyanDev, @brandonroberts, @robwormald ? I'd like to at least have a clearer picture of how it does not meet all of the project team's goals.

This code can be a bit misunderstood at first glance given that it does much of the work for you.  However, I believe it does meet all the goals of a Redux pattern.  Let me explain.

# Goals Recap:

Redux Goals (all met):
(1) The whole state of your app is stored in an object tree inside a single store.
(2) The only way to change the state tree is to emit an action, an object describing what happened.
(3) To specify how the actions transform the state tree, you write pure reducers.

Added Ngrx goals (all met):
(4) state should be fully serializable and deserialzable.
(5) type safety of actions, reducers, payloads

Added goals (all met):
(6) 100% interoperability with store, actions, effects, entities, etc... of core @ngrx/store and official extensions.
(7) reduced boilerplate

# Goal Detail

## Goal 1 - single store

You retrieve state using selectors as usual from the main Store.

## Goal 2 - change state tree via action emit

This goal appears to be broken at first glance, but in reality it works the same as before.  Here's the relevant code:

	const query = {term: 'value', someFlag: true}; //whatever you want, maybe just a string?
	this.store.dispatch(featureAction(bookActions.search, query));

It appears as if this is calling a function which can only be caught by itself, or that it may be invoking itself.  But this is not the case.  The 'featureActions' function takes it's parameters and creates an Action instance with action type set to a string value action name, in this case "[BookReducer] search". The bracketed portion of the name is controlled with an attribute value, and the rest is the name of the function; This still works with AOT prod builds. 'featureActions' takes the second parameter and places it into the payload of the Action instance.  The result is an Action instance such as:

	{
		type: '[BookReducer] search',
		payload: {term: 'value', someFlag: true}
	}

This payload itself is serializable and can be caught by any reducer. Also, if the payload was the wrong type the typescript compiler would tell the developer. The 'search' function that defines its  parameter type is enforced by the 'featureAction' function.

If store-devtools is enabled in the project, the action will be seen in the Redux debugger.  All actions can be reversed and replayed the same as any other action.

In short, the dispatch with featureAction defines an event, it does not invoke the function.  It does not specify which reducer function or switch processes the payload to update state or respond to events.

## Goal 3 - pure reducers

This solution still requires the developer to write pure functions that accept the prior state and the action payload. Although they do not have to specify action 'type' since that is specified as the function name. However, it does become a 'type' per goal 2 in the function that builds a reducer from the class containing these pure action functions.

	search(state: BookState, query: {term: string, someFlag: boolean}) {
		return {...state, criteria: query, loading: true, error: ''}
	}
	
The developer may also write other reducer functions that process multiple actions including this search action. I did not include it in the prior example, but it would be something like this:

	export function someReducer(state: BookState = initialState, action: Action) {
		switch(action.type) {
			case 'abc':
			case 'etc':
			case '[BookReducer] search':
				// action.payload still contains object: {term: 'value', someFlag: true}
				// some additional state changes not handled by the action method.
				return {...state, doneWithStuff: true};
		}
	}
	
The common case is that developers using featureReducer will compose them using the utility function that builds a single pure function from the class functions.  At that point they can also include other functions into the same or another reducer that act on any of those action events.

	export const bookActions = new BookActions();
	const reducer = FeatureActions.createReducer(initialBookState, bookActions);
	export function booksReducer(state: BookState, action: Action): BookState {
	  return reducer(state, action);
	}
	
[full book.store.ts](https://github.com/michael-lang/book-sample-ngrx/blob/master/src/app/books/store/book.store.ts)

## Goal 4 - serializable 

Up to the individual developer. This feature does not affect the action payload.

## Goal 5 - type safety

The store dispatch using 'featureAction(f1, payload)' requires the second argument type to match the payload type defined by the signature of the function specified in the first argument.

Decorators actually facilitate this. Try running the project and attempt to pass in the wrong payload and see what happens. When I use the wrong payload type, I get red squiggles immediately with a typescript compile error.

I'm not sure how usage of Decorators could break the type safety.  Can you elaborate?  

## Goal 6 - interoperability

Effects are not changed as part of this code. But we do add a new operator for convienience, 'ofAction'.  

We still have actions as events, and pure functions as reducers. Its done in a way to allow you to combine them into one, reducing code.  It fully supports defining additional actions the normal way and intermixing them in your project.

## Goal 7 -reduce boilerplate

1/2 the application code for typical/simple scenarios. If it can't handle some case, just mix traditional ngrx with featureReducers in any combination.
