### ISSUE TITLE
RFC: Compound Selectors

### ISSUE THREAD

**Issue by Bielik20** [ngrx/platform#1226]
I would like to be able to create compound selectors. Meaning a selector that can get a param for a selector from a different selector. I know how it sounds, so here is an example:

```ts
export const paramSelector = (id) => createSelector(
  someState,
  state => state[id]
);

export const selectedId = createSelector(
  someOtherState,
  state => state.id
);

export const compoundSelector = createSelector(
  selectedId,
  id => paramSelector(id),
  state => state
);

// or
export const compoundSelector = createSelector(
  selectedId,
  id => paramSelector(id),
  (id, state) => state
);
```

The idea is to have specialized parametrized selectors, and some higher level selectors consuming them. Imagine `paramSelector` is more complex. Sometimes you want to use `paramSelector` with specific parameters. Sometimes you don't want to provide params yourself, you want to get it somewhere from the store (eg. router state).

## Describe any alternatives/workarounds you're currently using

Alternative is to repeat the code to get the desired state:

```ts
export const notCompundSelector = createSelector(
  selectedId,
  someState,
  (id, state) => state[id]
);
```

## Other information:

First I wrote a question on [stackoverflow](https://stackoverflow.com/questions/51580288/ngrx-compound-selector). So here is the reference.

## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[X] No

**Comment by timdeschryver** [comment]
I'm closing this issue since it has been almost 3 months without any comments.
