### ISSUE TITLE
Effect cause entity adapter fn to be called until crash

### ISSUE THREAD

**Issue by savaryt** [ngrx/platform#1228]
## Minimal reproduction of the bug/regression with instructions:
Generate a project using schematics entity and effects.
Build a feature module

Component template
```html
      <button mat-mini-fab
              color="primary"
              (click)="add(item)">
        <mat-icon>add_shopping_cart</mat-icon>
      </button>
```

Component code
```ts
  add(item: Item) {
    const action = new AddItem({ item });
    this.store.dispatch(action);
    console.log('fn called')
  }
```

Effect code
```ts
  @Effect() add$ = this.actions$
    .pipe(ofType(ItemActionTypes.AddItem))
    .pipe(tap(console.log))
```

Generated entity code

```ts
    case ItemActionTypes.AddItem: {
      console.log('adapter called')
      return adapter.addOne(action.payload.item, state);
    }
```

Console output multiple call on the adapter addOne function when the effect is setup while it output 2 calls for the first action and one call for subsequent action when the effect isn't active.

Any idea of what could go wrong ?

**Comment by timdeschryver** [comment]
Your effect is causing an infinite loop, it keeps dispatching the `AddItem` action.
To prevent this you must tell the effect not to dispatch any actions with `{ dispatch; false }`.

```ts
 @Effect({ dispatch: false }) add$ = this.actions$
    .pipe(ofType(ItemActionTypes.AddItem))
    .pipe(tap(console.log))
```

See the [docs](https://github.com/ngrx/platform/blob/master/docs/effects/api.md#non-dispatching-effects) for more info.

**Comment by savaryt** [comment]
Oh, I believed effect where only listening to action unless specified, my bad.
Thanks for your comprehensive answer.
