### ISSUE TITLE
Effects: Write migration from V6 to V7 to handle compatibility changes

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1230]
## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

With https://github.com/ngrx/platform/issues/860 and the removal of instance operators, we'll need a way to migrate users usage of the existing `Actions` from `@ngrx/effects` to `Actions` from `@ngrx/effects/compat` and to the pipeable `ofType` operator where necessary.

This also covers migrating from `store.select()` to `store.pipe(select())`

**Comment by timdeschryver** [comment]
I've modified `rxjs-tslint` to our needs at [ngrx-tslint](https://github.com/timdeschryver/ngrx-tslint).
I would appreciate it if some would try it out and give their feedback, **be sure to commit your work before running it** 😅.

Usage:
- Fork the repo: `git clone https://github.com/timdeschryver/ngrx-tslint.git`
- Install deps: `npm install`
- Create a release: `npm run release`
- Create an npm pack: `cd dist && npm pack && cd ..` - this should create a file `ngrx-tslint-versionNumber.tgz`
- Use the created file to install the linter in your project: `npm install path-to-file --save-dev`
- Add the rules to your `tslint.json`
- Run the linter with the `--fix` flag: `ng lint projectName --fix`

```json
{
  "rulesDirectory": ["node_modules/ngrx-tslint"],
  "rules": {
    "ngrx-store-operators": true,
    "ngrx-effects-operators": true,
    "ngrx-chained-pipes": true
  }
}
```

If you need help, feel free to ping me.
