### ISSUE TITLE
Overriding  One to One relationships with EntityAdapter

### ISSUE THREAD

**Issue by Lahrachtdi** [ngrx/platform#1231]
How to override relationships using EntityAdapter methods (addOne, updateOne, ...) 
when we have a One to One relationship between two entities, like 'Bus' and 'Driver'.

If I add a new bus with an already affected driver, this driver will be affected to both buses rather than be affected to the newly created bus and be removed from the other bus.

this how I handle that temporary:

```
export function fixeRelations<V>(FKeys: string[], entities: { [id: number]: V }, entity: V) {
    for (let key in entities) {
        if (!entities.hasOwnProperty(key))
            continue;
        FKeys.map(FKey => {
            if (entity[FKey] === entities[key][FKey])
                entities[key][FKey] = null
        });
    }

    return entities;
}
```

**Comment by timdeschryver** [comment]
We already have an issue open to add relationships into entities #859.
