### ISSUE TITLE
Error when trying to generate an action

### ISSUE THREAD

**Issue by duffbuster** [ngrx/platform#1232]
## Minimal reproduction of the bug/regression with instructions:

`ng generate action TestAction`

Nothing happens, the message `Cannot read property 'entries' of undefined` is displayed.

<img width="502" alt="screen shot 2018-08-06 at 1 12 17 pm" src="https://user-images.githubusercontent.com/1220827/43730765-6aceef56-997a-11e8-8d9a-6a4d40890584.png">

## Expected behavior:

An action is generated.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

`@angular/cli@6.1.2`
`@ngrx/schematics@6.1.0`

## Other information:

My global `@angular/cli` version is the same.

## I would be willing to submit a PR to fix this issue

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by duffbuster** [comment]
Note: I took the steps outlined here: https://stackoverflow.com/questions/51645370/cannot-read-property-entries-of-undefined-angular-cli, but nothing changed.

**Comment by brandonroberts** [comment]
Can you provide a repo that reproduces this error?

**Comment by duffbuster** [comment]
@brandonroberts https://github.com/duffbuster/angular-cli-test

`ng -v`:
```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.1.2
Node: 10.4.0
OS: darwin x64
Angular: 6.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.4.2
@angular/cli                      6.1.2
@angular/material                 6.4.2
@ngtools/webpack                  6.0.8
@schematics/angular               0.7.2
@schematics/update                0.7.2
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.8.3
```

**Comment by brandonroberts** [comment]
Why are you specifying versions of `@angular-devkit/core` and `@angular-devkit/schematics`? The CLI uses `0.7.x` versions of those libraries. You can also upgrade the NgRx 6.1, which doesn't include the `0.6.x` peer dependencies anymore.

**Comment by duffbuster** [comment]
@brandonroberts the repo I provided is an Angular CLI project that I started a couple of months ago. All I did to produce this issue was upgrade all of the packages (`yarn upgrade`). Looks like the 0.6.8 version of `@angular-devkit` could be the cause here.

**Comment by duffbuster** [comment]
@brandonroberts the issue is resolved once I upgrade all of the devkit dependencies.
