### ISSUE TITLE
Run effects that have {dispatch: false} during dev tools time travel.

### ISSUE THREAD

**Issue by codemasterover9000** [ngrx/platform#1235]
Hi,

Would it be possible to allow effects that dont result in state modification to run during time travel? In my case I use such an effect to show a snackbar.

Thanks!

**Comment by timdeschryver** [comment]
If I'm not mistaken, effects are ignored for a reason right now (e.g. we don't want to fetch/save the data again).
I think if we want effects to be "replayed", #955 should first be merged.
If the devtools is "locked' it wouldn't dispatch the actions and otherwise it would, at least that's how I'm seeing it.

**Comment by codemasterover9000** [comment]
The implementation of #955 would still mean effects won't run in any case if I understand correctly? As we still don't want the side effects to actually run (remote calls etc)? #955 only prevents action dispatch. 

I'm also using the action stream as an event system to display messages in my app. This won't work during time travel atm. Maybe this is bad design on my part but I'm not sure how to implement it differently.

**Comment by timdeschryver** [comment]
Yea you're correct it won't solve this problem. But it would allow to use the "lock" functionality to prevent effects to be invoked. In other words, if it isn't locked we could invoke effects; if it's locked we could prevent this. But again, that's how I'm seeing it 😅

**Comment by brandonroberts** [comment]
Time traveling is for state, and not effects. If you want to trigger an effect this way, you're effect should be listening for a piece of state to change.
