### ISSUE TITLE
Update documentation with new usage of ofType operator

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1239]
## I would be willing to submit a PR for the docs :heart:

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

Documentation will need to be updated to support #1183

**Comment by hlovdal** [comment]
Any progress on this issue?

**Comment by timdeschryver** [comment]
@hlovdal I believe we haven't picked this one up yet.
Are you struggling with something and need some help?

**Comment by whyboris** [comment]
It looks like the `breaking changes` section under version 7 has incorrect information:
https://github.com/ngrx/platform/blob/master/CHANGELOG.md#700-beta0-2018-11-03

`import { ofType } from '@ngrx/store';`
should be
`import { ofType } from '@ngrx/effects';`

Right?

**Comment by timdeschryver** [comment]
@whyboris you're right.
This is due to the commit message, I'm not sure if we safely edit this commit message.

PS: see [the docs](https://next.ngrx.io/guide/migration/v7) where it is correct

**Comment by whyboris** [comment]
Thank you @timdeschryver - I also found this good resource:
https://github.com/ngrx/platform/tree/master/docs/effects#example

**Comment by brandonroberts** [comment]
I believe this is covered
