### ISSUE TITLE
Component displays no data

### ISSUE THREAD

**Issue by dalu** [ngrx/platform#1248]
https://github.com/dalu/ngrx-sucks

HomeComponent doesn't receive data.

Where do you initalize loading from http api?

Your example app doesn't show so many things. And again all resources are behind a paywall or don't explain anything.

The ... browser plugin shows that the store is populated with data. Why is there no data displayed?

**Comment by timdeschryver** [comment]
Support questions should be asked on [stackoverflow (with a ngrx tag)](https://stackoverflow.com/questions/tagged/ngrx) or the [gitter channel](https://gitter.im/ngrx/platform).
