### ISSUE TITLE
Adding router state and reducer crashes Redux Devtools

### ISSUE THREAD

**Issue by hqp6684** [ngrx/platform#125]
I've migrated my project to use ngrx v4, Chrome/Firefox Redux Devtools extension was fine until I added router state and reducer to the app as instructed by https://github.com/ngrx/platform/blob/master/MIGRATION.md#ngrxrouter-store

I used the [example-app](https://github.com/ngrx/platform/tree/master/example-app) and was able to reproduce the problem

```
export const reducers: ActionReducerMap<State> = {
  layout: fromLayout.reducer,
  router: routerReducer
};

// console.log all actions
export function logger(reducer: ActionReducer<State>): ActionReducer<any, any> {
  return function(state: State, action: any): State {
    console.log('state', state);
    console.log('action', action);

    return reducer(state, action);
  };
}
...
...
...

export const getShowSidenav = createSelector(
  getLayoutState,
  fromLayout.getShowSidenav
);
```

**Comment by brandonroberts** [comment]
Duplicate of #97
