### ISSUE TITLE
updateOne convert object into a string

### ISSUE THREAD

**Issue by egiev** [ngrx/platform#1251]
## Expected behavior:
It should not convert the object into a string

I have a service that return a data from the API
example response:
```javascript
{
  "_id":"D704206235673",
  "name":"D704206235673",
  "group":[],
  "location":[0,0],
  "connectionStatus":false,
  "isInactive":false,
  "createdDate":"2018-08-15T07:13:20.771Z",
  "updatedDate":"2018-08-15T07:13:20.771Z",
  "__v":0,
  "lastReadingDateTime":"2018-08-15T07:25:39.745Z",
  "metadata":{}
}
```
When I pass the response data as payload to **updateOne** method the **metadata** property in the **Collection** turns into a string

Action:
```javascript
export const UpdateInfo implements Action {
  readonly type = '[Device] Update'
  constructor(public payload: Update<Device>)  {}
}
```

Reducer:
```javascript
{
  ...adapter.updateOne(action.payload, state)
}
```

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
Angular 5.0.0
NgRx 4.1.1
## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ x] No

**Comment by timdeschryver** [comment]
Do you got a reproduction?

**Comment by egiev** [comment]
What do you mean by reproduction ?
Sorry, I'm a new to NgRx and I'm a little bit confuse about the behavior of updateOne method.

**Comment by kouMatsumoto** [comment]
I don't think it might be the issue of NgRx.
updateOne method doesn't modify the specific property. it just replace the object reference with new one.

**Comment by egiev** [comment]
Nope. I think this is an issue with NgRx Entity

Here's my action payload. As you can see the metadata property is an object
![screenshot_20180816_101540](https://user-images.githubusercontent.com/12962304/44183621-502d7200-a13e-11e8-806f-c0f99cb81af8.png)

And then this is the output of the collection. The metadata is in string type.
![screenshot_20180816_102528](https://user-images.githubusercontent.com/12962304/44183736-bf0acb00-a13e-11e8-9483-d8ca3c54329a.png)

**Comment by timdeschryver** [comment]
With a reproduction I mean a project ([StackBlitz](https://stackblitz.com/edit/ngrx-seed), GitHub) where this kind of behavior can be seen.

**Comment by timdeschryver** [comment]
I think this is already resolved, I couldn't [reproduce](https://stackblitz.com/edit/ngrx-seed-bkbp3r)
it anyway...
