### ISSUE TITLE
How Ngrx could be scaled to fit large systems ?

### ISSUE THREAD

**Issue by Elsiranas** [ngrx/platform#1252]
## Suppose that we have the next scenario :
An enterprise system

- the system deals with **6** types of products :

1. Frames 
2. Accessories 
3.  Contact Lenses
4.  Finish Lenses
5.  RX Lab Lenses 
6.  Services 

- Each one of those products has a different architecture with a different number of data expected 
for example :

1. Frames will have at least 300 thousand item
2. All lenses together would be over 700 thousand item at least

- Then we are talking about **1 million item** would be exist

### How NGRX will fit this scenario ?

- **Is that** makes sense to have all of these 1 million item in my store ?
```
 * dispatch(getAllFrames)
 * dispatch(getAllAccessories)
 * dispatch(getAllContactLenses)
 * dispatch(getAllFinishLenses)
 * dispatch(getAllLabLenses)
 * dispatch(getAllServices)
```
- We have already implemented the pattern from [here](https://github.com/UltimateAngular/ngrx-store-effects-app)

**Comment by timdeschryver** [comment]
I agree with @dummdidumm , you could test it out and see how the performance is.
Also, in the [Redux docs](https://redux.js.org/faq/performance), there is a performance section which personally I find well written.
