### ISSUE TITLE
Multiple feature modules requires unique action names

### ISSUE THREAD

**Issue by Exocomp** [ngrx/platform#1253]
I'm using the latest available version 6.1.0 with Angular 6.0.3.

I looked around and could not find an answer to this.  The issue I'm having is when I use multiple feature modules that have the same action name - when I trigger an action in one feature module it changes the state in the other feature module as well.  

For ex.

1) 

Feature Module 1 has action:  SetName
Feature Module 2 has action:  SetName

2)

Trigger Module 1 SetName, for ex:

`this.store.dispatch(new Module1Actions.SetName('Mike'));`

3) Check the state in Redux DevTools, name for Module1 and Module2 are updated to the same value set in the previous step.

**Comment by dummdidumm** [comment]
Use a prefix for all actions in that module and/or use case

**Comment by timdeschryver** [comment]
Exactly what @dummdidumm says. The actions are being passed to all reducers, meaning if you use the same action type it will trigger both changes. To solve this use a prefix, e.g. `[Feat1 DetailsPage] SetName` and `[Feat2 OverviewPage] SetName`.

**Comment by Exocomp** [comment]
@dummdidumm 
@timdeschryver

Thanks for the help!

If I understand correctly using a prefix would be a manual process for each action.  It would be nice to have a global prefix you can register to each feature module that will add the prefix to each action automatically - just a thought.

**Comment by timdeschryver** [comment]
While it may seem like a good idea, I think it isn't. 
This would prevent [good action hygiene](https://www.youtube.com/watch?v=JmnsEvoy-gY).

**Comment by Exocomp** [comment]
@timdeschryver thanks for that link. I just watched that video and learned a few things which I will apply to my project.

The way I was thinking about it regarding automatically applying a prefix by feature module could be thought of as an additional to what was described in the video. For example, if your actions are like `[Feat1 DetailsPage] SetName, Feat2 OverviewPage] SetName`, the feature prefix of the action could simply be appended from what is registered once since it is going to be the same always for that feature module.
