### ISSUE TITLE
Devtools: Use different action when recomputing state history

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1255]
## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

Currently, when store-devtools is enabled and feature stores are loaded, it uses the same `@ngrx/store/update-reducers` action to recompute the state history. This is confusing because users think its changing state, when its just a pass-through action to update the reducer map. Update this to a new action that is more descriptive and accurate of what's happening.

**Comment by tja4472** [comment]
https://github.com/ngrx/platform/blob/d2992c9ae0424405be838d5fe971092849d48326/modules/store-devtools/src/reducer.ts#L501,L505

```ts
          // Recompute state history with latest reducer and update action
          computedStates = computedStates.map(cmp => ({
            ...cmp,
            state: reducer(cmp.state, liftedAction),
          }));
```

Is this a case of replacing `liftedAction` with RECOMPUTE_STATE_ACTION?

```ts
const RECOMPUTE_STATE = '@ngrx/AAAAA/recomput-state' as '@ngrx/AAAAA/recomput-state';
const RECOMPUTE_STATE_ACTION = { type: RECOMPUTE_STATE };
```

**Comment by brandonroberts** [comment]
@tja4472 yes, that's correct
