### ISSUE TITLE
NGRX reloads the page

### ISSUE THREAD

**Issue by abnerey** [ngrx/platform#1256]
Good night.

I've been working on a ngrx test, but, when I dispatch an action to the Store, the entire page gets reload, I tried to see what's going on, but I don't realize where is my code broken; I did this test following the example in the @ngrx/store readme and I can't figure out how and why is ngrx related to the page reload, it doesn't has any sense.

Please, help me

**Comment by abnerey** [comment]
Common, Angular is a SPA framework, why does ngrx reload the page? It should be impossible

**Comment by brandonroberts** [comment]
`@ngrx/store` is not causing your page to reload. Provide an reproduction of your issue in the [gitter support channel](https://gitter.im/ngrx/platform) so you can get some assistance.
