### ISSUE TITLE
Guard doesn't retrieve store data

### ISSUE THREAD

**Issue by ChAraya** [ngrx/platform#1259]
i have a problem protecting my routes using the store, when ever i tried to select some variable from the store its undefined and my page doesn't load because of that.

The store is working good, here some pictures.

Initial State
<img width="1631" alt="screen shot 2018-08-18 at 8 40 25 pm" src="https://user-images.githubusercontent.com/19436477/44304030-2e431380-a327-11e8-91aa-9700198e1f3a.png">

State loaded
<img width="1631" alt="screen shot 2018-08-18 at 8 40 42 pm" src="https://user-images.githubusercontent.com/19436477/44304034-3a2ed580-a327-11e8-8389-90e92e148bde.png">

Console output

<img width="1629" alt="screen shot 2018-08-18 at 8 40 51 pm" src="https://user-images.githubusercontent.com/19436477/44304047-6c403780-a327-11e8-9ca8-dcc1c681218f.png">

and here some portion of the code

home.guard.ts

```
...
@Injectable()
export class HomeGuard implements CanActivate {
  constructor(private store: Store<fromStore.State>) {}

  canActivate(route: ActivatedRouteSnapshot): Observable<boolean> {
    return this.checkStore().pipe(
      switchMap(() => of(true)),
      catchError(() => of(false))
    );
  }

  checkStore() {
    return this.store.select(fromStore.selectProjectsLoaded).pipe(
      tap(loaded => {
        //HERE IS WHERE THE LOADED IS UNDEFINED AND THE PAGE DOESNT LOAD
        console.log('data ' + loaded);
        if (!loaded) {
          this.store.dispatch(new fromStore.LoadProject());
        }
      }),
      filter(loaded => loaded),
      take(1)
    );
  }
}
```

home.selector.ts

```
...
export const selectProjectsLoaded = createSelector(
  fromFeature.getProjectState,
  fromReducer.getProjectLoaded
);
...
```

homer.reducer.ts

```
...
export interface State extends EntityState<Project> {
  loaded: boolean;
  loading: boolean;
}

export const initialState: State = adapter.getInitialState({
  loaded: false,
  loading: false
});
...
export const getProjectLoaded = (state: State) => state.loaded;
...
```

home.module.ts
```
...
@NgModule({
  imports: [
    CommonModule,
    RouterModule.forChild(routes),
    StoreModule.forFeature('campaigns', reducers),
    EffectsModule.forFeature(effects)
  ],
  providers: [...fromServices.services, ...fromGuards.guards],
  declarations: [...fromContainers.containers],
  exports: [...fromContainers.containers],
  
})
...
```

its the guard called before the store is init?

what can i do ?

**Comment by timdeschryver** [comment]
Support questions should be asked on [StackOverflow (with a NgRx tag)](https://stackoverflow.com/questions/tagged/ngrx) or the [gitter channel](https://gitter.im/ngrx/platform).
If you can reproduce it with a [StackBlitz project](https://stackblitz.com/edit/ngrx-seed) or a GitHub repo, I'll be happy to take a look.

**Comment by ChAraya** [comment]
ok, thanks.

i did it here is the link https://stackoverflow.com/questions/51918201/guard-doesnt-retrieve-data-from-store-ngrx
