### ISSUE TITLE
On update how to merge state

### ISSUE THREAD

**Issue by BDominik** [ngrx/platform#1260]
When I'm updating the state, and is there any option to merge the state?
e.g.
my state interface looks like this
{
name: string;
balance: number;
price;
}
and when I'm updating with updateOne I want to pass just like this.
{
id: 1,
changes: { balance: 4 }
}
in this current case the whole object is overrided by the balance: 4
is any option to use merge? Or should I get the state and merge it before calling the updateOne method?
thank for the help

**Comment by timdeschryver** [comment]
This [example](https://stackblitz.com/edit/ngrx-seed-5u4xbw) behaves correctly.
