### ISSUE TITLE
Router-Store: Add custom serializer to config object

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1262]
## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

Currently you have to use the provider object syntax to override the default router state serializer. This can be easier by exposing a `serializer` option in the configuration with the custom serializer class. If none is provided, use the default.

**Comment by dummdidumm** [comment]
#1010 related

**Comment by timdeschryver** [comment]
Can I take this one? Or are you already working on it?

**Comment by dummdidumm** [comment]
I have PR in the making implementing this and the other enhancement suggestions. I will request the merge soon.

**Comment by cyberbeast** [comment]
Is this available in ngrx/router-store ^6.1.0?

**Comment by timdeschryver** [comment]
This isn't available in 6.1. You could install ngrx from the nightly builds, these builds have the latest features.

**Comment by cyberbeast** [comment]
@timdeschryver Thank you for that information. I'll check that out.
