### ISSUE TITLE
Router-Store: Provide configuration for pre/post router navigation action

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1263]
## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

Currently, router-store dispatches a `ROUTER_NAVIGATION` action as a pre-activation hook which is run before guards and resolvers. We should provide an option to let this be configured to run as a `post-activation` hook that is run after guards and resolvers.

Also add an action that is dispatched when the navigation cycle ends successfully and the current route is active.

**Comment by dummdidumm** [comment]
#1010 related

**Comment by dummdidumm** [comment]
Looking at the angular router docs, there is not much in between "after guards and resolvers" and before "navigation end". There is `ActivationEnd` but that can be fired multiple times, resulting in multiple dispatched actions, same for `ChildActivationEnd`. After those two events, there is only NavigationEnd. So `ROUTER_NAVIGATION` will be dispatched at the same time like a possible `ROUTER_NAVIGATED`

**Comment by brandonroberts** [comment]
Fixed via https://github.com/ngrx/platform/pull/1267
