### ISSUE TITLE
In the example app, redundant code

### ISSUE THREAD

**Issue by UncleJimmy** [ngrx/platform#1264]
In the example app, on file `platform/example-app/app/books/reducers/books.reducer.ts`, on line 58, what's the benefits to have `selectedBookId: state.selectedBookId,`, since it's just setting the same value to the state. Will it break anything if we remove this?

The same on line 72.

Thanks.

**Comment by timdeschryver** [comment]
You're right, this doesn't do anything.
In fact this can be written as ` return adapter.addMany(action.payload, state);`.
Do you want to create a PR for this?

**Comment by UncleJimmy** [comment]
@timdeschryver Just created a PR for this, it's #1268 :)
