### ISSUE TITLE
Schematics: Reducer spec test description incorrect

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1265]
## Minimal reproduction of the bug/regression with instructions:

ng generate @ngrx/schematics:reducer Test

The test generated:

```
describe(Test Reducer', () => {
  describe('unknown action', () => {
    it('should return the initial state', () => {
      const action = {} as any;

      const result = reducer(initialState, action);

      expect(result).toBe(initialState);
    });
  });
});
```

## Expected behavior:

The test description should say it returns the previous state

```
describe(Test Reducer', () => {
  describe('an unknown action', () => {
    it('should return the previous state', () => {
      const action = {} as any;

      const result = reducer(initialState, action);

      expect(result).toBe(initialState);
    });
  });
});
```

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by kouMatsumoto** [comment]
I would like to submit this pull request 😃
