### ISSUE TITLE
Issue after upgrade to Ngrx4

### ISSUE THREAD

**Issue by PVSajith** [ngrx/platform#127]
I am getting compile error after upgrading from ngrx2 to 4.  Following the migration [guide](https://github.com/ngrx/platform/blob/master/MIGRATION.md)

Error:
node_modules/@ngrx/store/src/models.d.ts (6,52): ',' expected.

angular cli  and typescript version used:
"angular/cli": "1.0.1",
"typescript": "~2.2.0"

Any help appreciated. Thanks

**Comment by brandonroberts** [comment]
You need to upgrade your `@angular/cli` to `~1.2.0`, and typescript to at least `~2.4.1`
