### ISSUE TITLE
Example: Update app name for devtools

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1270]
## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

Rename `NgRx Book Store Devtools` to `NgRx Book Store App` or something easier to pick out of the list.

**Comment by kouMatsumoto** [comment]
I'll submit a pull reqest :smile:

**Comment by brandonroberts** [comment]
You're not a first-timer 😂

**Comment by MatsumotoKou** [comment]
sorry, I missed `Good First Issue` label 😣

**Comment by brandonroberts** [comment]
No problem 👍

**Comment by timdeschryver** [comment]
Don't force him to create a new account 😄

**Comment by brandonroberts** [comment]
Burner GitHub accounts 😂
