### ISSUE TITLE
Example: Refactor actions to follow Good Action Hygiene

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1272]
## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

https://www.youtube.com/watch?v=JmnsEvoy-gY

**Comment by kanafghan** [comment]
@brandonroberts I can do a PR for the `books` feature if it is not being done by someone else?

**Comment by timdeschryver** [comment]
Hi @kanafghan thanks that you're willing to contribute but someone already open a PR for this #1280 .

**Comment by timdeschryver** [comment]
You're absolutely right! 
So there are still a few actions that you could tackle 😉

**Comment by timdeschryver** [comment]
@kanafghan if you do take this up, you could mention it here so others would know.

**Comment by kanafghan** [comment]
@timdeschryver yes, I'm working on the PR for the `books` feature.
