### ISSUE TITLE
Issues using store.pipe(select(...)):  Argument of type 'Observable<{}>' is not assignable to parameter of type 'OperatorFunction<any, any>'.

### ISSUE THREAD

**Issue by jrista** [ngrx/platform#1273]
I am having some trouble getting the `select` operator working in a store.pipe. I keep getting the following syntax error, both within my editors (webstorm or vscode) as well as when actually building with `ng build` (I note this as many times, the editors will show syntax errors that otherwise build just fine.)

![Visual Syntax Error](https://i.imgur.com/PNyP91E.png)

As can be seen in the image above, the syntax error appears to actually come from the `select` operator itself, rather than the selector passed into the operator, however I suspect the underlying operator is playing a role in the issue here.

I want to also note that if I use the legacy select function on the store, I do not have this syntax error:

![Visual Syntax Success](https://i.imgur.com/9mTveCZ.png)

I have noted that there are some differences in the parameter types for the select **operator** vs. the select **function**. I have resorted to using the select **function** thus far, however seeing as those functions are deprecated, I would like to get the select **operator** working. 

## Minimal reproduction of the bug/regression with instructions:

The state is standard entity structured state, with `entities` and `ids`. My selector is as follows:

```javascript
export const allAppointmentImports = createSelector(
    entityState,
    (state: IAppointmentImportState): AppointmentImport[] => state.ids.map(id => state.entities[id])
);
```

Nothing special here, pretty standard selector. (I am not able to use @ngrx/entity in this particular app, hence the manual implementation.) 

Selection is quite standard as well:

```javascript
this.apptImports$ = this.store.pipe(select(allAppointmentImports));
```

## Expected behavior:

I would expect my completely standard selector to function properly with the select operator, as it does with the select function. I am unsure why there is a difference in behavior between the two, however I see no reason why either should not work as well as the other. 

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

➜ npx ng -v

         _                      _                 ____ _     ___
        / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
       / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
      / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
     /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                    |___/
    

Angular CLI: 6.0.8
Node: 8.11.2
OS: darwin x64
Angular: 6.0.6
... common, compiler, compiler-cli, core, forms, http
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.8.3
    

        "@ngrx/core": "^1.2.0",
        "@ngrx/effects": "^6.0.0",
        "@ngrx/entity": "^6.0.0",
        "@ngrx/router-store": "^6.0.0",
        "@ngrx/store": "^6.0.0",
        "@ngrx/store-devtools": "^6.0.0",

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Can you try removing `@ngrx/core`? 
Also how does your import look like (from RxJS)?

**Comment by jrista** [comment]
@timdeschryver Well, it looks like it was @ngrx/core. Not entirely sure how or why that was in there, or why the `select` operator was coming from /core rather than /store. Removing core and updating the import does seem to have resolved the issue.

Thanks!

**Comment by timdeschryver** [comment]
Awesome!
