### ISSUE TITLE
StoreModule.forRoot method doesn't contain 'name' argument

### ISSUE THREAD

**Issue by giolf** [ngrx/platform#1276]
I don't get the point why only `StoreModule.forFeature` method allow to provide a name.
```
StoreModule.forFeature('featureModuleName', reducers)
```

why this is not allowed ? 
```
StoreModule.forFeature('rootModuleName', reducers)
```
why i can't provide a name for my root module ?

**Comment by timdeschryver** [comment]
In `forRoot` we're defining our root reducer (and store state). 
The `featureName` in `forFeature` is used to add the feature's reducers to the root reducer.
For example we start with:

```ts
{
   auth: authReducer,
   router: routerReducer,
}
```


When our books module is loaded we want to add this to our root reducer so it becomes:

```ts
{
   auth: authReducer,
   router: routerReducer,
   books: booksReducer,
}
```
