### ISSUE TITLE
Question: can reducers be in the actions themselves?

### ISSUE THREAD

**Issue by Jiehong** [ngrx/platform#1279]
Hello,

I'm using Angular 6.1.1 with Ngrx 6.1.0.

Looking at the documentation, reducers are using switches, but I wanted to try to use a more object oriented way to deal with that, so I tried the following example (it doesn't work very well, idk why), and I wanted to know if this style has any issues with ngrx and why it's not used more often:

```typescript
import {Action} from '@ngrx/store';

export interface State {
  a: boolean;
  b: string;
}

const initialState: State = {
  a: false,
  b: 'hello'
};

interface ActionWithReducer<T> extends Action {
  reduce(state: T): T;
}

export enum ActionTypes {
  Action1 = 'Action 1',
  Action2 = 'Action 2',
}

export class MyAction1 implements ActionWithReducer<State> {
  readonly type = ActionTypes.Action1;

  reduce(state: State): State {
    return {...state, a: true};
  }
}

export class MyAction2 implements ActionWithReducer<State> {
  readonly type = ActionTypes.Action2;

  reduce(state: State): State {
    return {...state, b: 'new value'};
  }
}

export type MyActions = MyAction1 | MyAction2;

export function reducer(
  state: State = initialState,
  action: MyActions
): State {
  if (Object.values(ActionTypes).includes(action.type)) {
    return action.reduce(state);
  }
  return state;
}

```

This would allow to avoid a big switch in the reducer when more actions are defined.

Weirdly, I didn't see this way online very much.

Any technical reason against doing this?

**Comment by brandonroberts** [comment]
Technically no, but its bad practice. Actions should not contain logic, as they are only to describe unique events that can trigger _one or more_ state changes or effects.

**Comment by Jiehong** [comment]
Thanks!
