### ISSUE TITLE
Interface Action should be generic.

### ISSUE THREAD

**Issue by ovangle** [ngrx/platform#128]
This issue is a resubmission (and improvement)  of the proposal `https://github.com/ngrx/store/issues/297`: _`Action` to be made generic_.

----- 

## New `Action<T>` Interfaces

`ActionType` represents the interface that is statically implemented by an action. 

It guarantees that `Action` must be constructable using a single parameter, and be declared as part of an `NgModule`.  

    interface ActionType<T> {
      /**
       * The `NgModule` that this action is declared as part of.
       */
      ngModule: Type<T>;
      /**
       * The action is carrying information of type `payload`
       */
      new (payload: T): Action<T>;
    }

     /**
      * Represents an instruction that the reducer will apply to the module/global state.
      */
     interface Action<T> {
        readonly payload: T;
     }

The following declarations would all be a conforming Actions:

```
class VoidAction implements Action<null> {
   static ngModule: AppModule;
   constructor(public readonly payload: null) {}
}

class IncrementAction implements Action<number> {
   static ngModule: MathModule;
   constructor(public readonly payload: number) {}
}

class ComplexAction implements Action<ComplexInterface> {
    constructor (public readonly payload: ComplexInterface) {}
```

## Some utility functions

It needs to be possible to obtain a value which corresponds to the old `action.type`. 

    /** 
     * This function can be used wherever there was previously a call to `action.type`, 
     * which is expected to return a string.
     */
    export function actionTypeToString(action: Action<T>): string {
        let type = actionType(action);
        function stringify(type: Type<T>) { return type.constructor.name; }
        return `${stringify(actionType.module)} (${stringify(type)})`;
    }

    export function actionType(action: Action<T>): ActionType<T> {
        return Object.getPrototypeOf(action).constructor;
    }

See [this attached gist](https://gist.github.com/ovangle/699f6a45423b8a67360be1b98a77da76) for an example of using the improved interface for `Action`, and how the example (despite being a stupid example) feels more "angular"y, since it uses the static type of an object as a token...
        
----

## Simple inline actions

By making the interface for `Action` rely upon the runtime type of the action for use in reducers, it removes the possibility for calls like the following:

   ```
   store.dispatch({type: 'some-quick-and-dirty-string', payload: Math.PI});
   ```

However, we can workaround this by enforcing a simple rule throughout the code:

    ```
    action has a property 'type' and the value is a string? Use it. Else, try use the runtime type.
    ```

Thus, for example, the function `actionTypeToString` would actually be

     export function actionTypeToString(action: Action<T>): string {
        if (typeof action.type === "string") {
            return action.type;
        } else {
           ... (see above)
        }
    }

## Void actions

The syntax for declaring a conforming `Action<Void>` (no payload) is a little clunky, and could be improved by changing the `ActionType` and `Action` interfaces to make the `payload` parameter optional. There are a number of common use cases (eg. a `delete resource` action) which would make this improvement justified.

**Comment by jinder** [comment]
@ovangle why must there be a single payload property?

**Comment by ovangle** [comment]
Because my intuitive idea of `Action` is "Procedure (typeString) with arguments (payload) that represents an update of the global state". Now I may be completely off the mark, but that's the way I've always seen it be used in practice.

Having a single "payload" property on every `Action` allows you to codify (and thus typecheck) the notion that the payload represents the "arguments". If you change the `ActionType` interface so that there is no single payload property

    interface ActionType<T> {
       new (...args: any[]): Action<T>;
    }

Then you lose any connection between `T` and `Action<T>`, and the `T` parameter actually just becomes a useless appendage on the interface.

**Comment by RicardoVaranda** [comment]
After upgrading to ngrx 4 my application is spamming me with 
```Property 'payload' does not exist on type 'Action'.``` 

Pointed at https://github.com/ngrx/platform/blob/master/modules/store/src/models.ts#L1

Did you guys have this issue also, not really sure how to fix this.

**Comment by ovangle** [comment]
There is no `payload` parameter on the `Action` interface (see [here](https://github.com/ngrx/platform/blob/master/modules/store/src/models.ts#L1)) -- that is correct and I'm arguing that it should be added.

So the fix (at the moment) is to coerce the type of all your calls to payload:

    (action as any).payload

And to add a 👍 to this issue.

**Comment by chrissena** [comment]
Am I missing something? 

In ngrx4 you can already just create an interface (e.g. `MyActionInterface`) that implements the provided `Action ` interface with any extra properties you like called whatever you like, payload etc..(as long as it has the compulsory type property).

Your actions can all then just implement this interface. When creating effects the `Actions` stream is already generic (with default type parameter of `Action`). You can use..

` constructor(private actions$: Actions<MyActionInterface>){}`

and 
```
@Effect()
   public sideEffect$: Observable<MyActionInterface> = this.actions$
        .ofType('ACTION_I_NEED')
        .map(a:ActionINeedType => ....
```
as usual and not have to worry about coercion etc. Just use `MyActionInterface` everywhere you would have used the `Action` interface (e.g. reducer parameter definition).

I'm using this now and it works a treat.

**Comment by MikeRyanDev** [comment]
The only part of the action interface that you must implement is the `type`. When we had `payload` on the interface marked as `any` this introduced type safety issues, especially when interacting with the `Actions` stream in @ngrx/effects. We won't be making any changes to this interface at this time.

If you want a parameterized version, you can create your own:

```ts
export interface ActionWithPayload<T> extends Action {
  payload: T;
}
```

And if you need an unsafe version to help with transition you can create that, too:

```ts
export interface UnsafeAction implements Action {
  payload?: any;
}
```

**Comment by jinder** [comment]
@ovangle I think your proposal makes the assumption that their should be a payload property on the object.  My actions do not have a single payload property, and I'm not sure ngrx should enforce it.

**Comment by ovangle** [comment]
@MikeRyanDev @jinder 

That's disappointing but understandable. I know the redux community had a similar discussion about standardising the shape of `Action` and I know the conclusion that they came to, but I think in ngrx there is a far stronger case to be made for imposing additional structure (because typescript). 

I wish I could motivate you both to try out the changes I proposed locally and _then_ come to a decision about whether the change is worth it, but I can't. 

That said, the generic `Actions` does remedy a lot of the problems which motivated the proposal in the first place, so...

**Comment by ovangle** [comment]
## Some notes on my mental model of a library like ngrx/redux.

A library like ngrx is a von neumann machine emulator. At it's most basic, it consists of:

- The application state, or memory of the machine.
- The actions, or instruction set of the machine
- The reducer, or CPU of the machine.

Each operation of the reducer on the memory applies a patch to the application state, contained in it's payload. But instead of an instruction set of basic math, memory access, jumps etc., the instructions of our machine can apply patches of structured data, into memory which is also structured data.

In order to clearly demonstrate the idea of ngrx as a von neumann machine emulator, I've implemented a turing machine:

```
class Tape {
   // The TERMINATE condition for our machine is moving the head to an invalid position
   static isTerminated(tape) { return tape.head < 0; }
   // Read the symbol at HEAD
   static read(tape) { return tape.contents[tape.head]; }
   // Get the head position
   static position(tape) { return tape.head; }

   readonly head: number;
   readonly contents: Array<number>;
   constructor(head, contents) {}
}

class Reset implements VoidAction {}
class Write implements Action<{value?: number}> {
  constructor(public payload: {value?: number}) {}
}
class Move implements Action<{offset: number}> {
  constructor(public payload: {offset: number}) {}
}

function turingReducer(tape: Tape, action: Action<any>) {
   switch (actionType(action)) {
       case Reset:
           return new Tape(0, []);
       case Write:
           contents = tape.contents.splice();
           contents[tape.head] = (<Write>action).payload.value;
           return new Tape(tape.head, contents);
      case Move:
           return new Tape(tape.head + (<Move>action).payload.offset, contents);
      default:
           return tape;
   }
}

function fibonacci(store) {
    return doWhileAsync(
       store => !Tape.isTerminated(store),
      function (store) {
          // Write the next fibonacci number at the head tape
          async function nextFibonacci() {
             store.dispatch(new Move({offset: -2});
             let fib_a = await store.select(Tape.read).first().toPromise();
             store.dispatch(new Move({offset: 1});
             let fib_b = await store.select(Tape.read).first().toPromise();
             store.dispatch(new Move({offset: 1});
             store.dispatch(new Write({value: fib_a + fib_b});
             // Move to the position of the next write
             store.dispatch(new Move({offset: 1});
          }
        
          store.dispatch(new Reset());
          store.dispatch(new Write({value: 0});
          store.dispatch(new Move({value: 1});
          store.dispatch(new Write({value: 1});
          store.dispatch(new Move({value: 1});
          
          return nextFibonacci();
    });
}
```

Note that the reduction to a turing machine is equivalent to the one used in the standard proof for turing completeness of a von neumann machine. `Effect`s are the IO of the machine, but I've omitted the implementation, because it's irrelevant.

## Why _the hell_ am I telling you this?!?

You wrote the library, I expect you have a clearer idea of what your library _is_ than I do. But sometimes it's important to be explicit about these things, to make sure we're all on the same page. That way if I have some grave misunderstanding about what the library is, you can correct me up front and we can both move on. 

## Von neumann instructions

All instructions share a similar scheme:

    load                  $1 0x0234123
    ----                   --------------
     Instruction       payload

The CPU reads a stream of instructions and each instruction patches the memory state. It's just that in our machine, the memory is arbitrary structured javascript data, and our instructions can be any semantically meaningful verb.

## So, what does this look like in the type system?

Well, using the current `Action` interface, it looks like

    interface Action {
       type: string;                 // instruction
       [key: string]: any;        // patch to apply to the global state.
                                            // This is hidden in the current interface, because it is 
                                            // (rightly) assumed that all actions are javascript objects
    }

## Why this is fine in redux

Redux is javascript. All that a dynamic language cares about is that the data is structured, it doesn't care if the objects it exposes are useful. So for javascript, `Object.keys(action)` is a perfectly reasonable way of accessing the structure of the payload

## Why this is a problem in ngrx

Ngrx is typescript. Users expect to be able to use the type information exposed by an object in order to make inferences about the object. Now that we can actually _use_ the interface we've defined, we'd like to know the type of our patch.

      type patch = { [key: string]: any};

Oh, the patch is completely untyped. Can't use that for anything :/

## How ngrx can do better.

By explicitly including the `payload` of the instruction in the interface for `Action`, 

     interface Action<T> {
        type: string;
        payload: T;
    }

then we can actually _read_ the payload.

### @jinder

There's no reason you can't add getters/setters to your Actions so that they keep whatever arbitrary key/values you like to add to them:

     class SomeCoolAction<SomeCoolInterface> {
        constructor(public payload: SomeCoolInterface);

        get interestingProperty() { return this.payload.interestingProperty; }
     }

The only difference is that in your new actions, you've still got an _explicitly typed_ exposed `payload`to reflect on.

## Not all instructions have a payload

No, they don't. But there's also no semantic difference between an instruction with a `null` payload and an instruction with no payload, so our model is still accurate in this case.

## Why typing `Actions<T>` isn't a solution.

Defining `Actions<T>` in `Effects` is a good change, it declares that **all the `Actions` used here share a common interface**. There's no reason to remove it, it's a good change.

However, it only provides a common base interface to use within the `Effect`s module, it provides no way to reflect on the type of the payload. If you look at the turing reduction above, even _that_ already has three different types of instruction payloads

- `void`
- `{offset: number}`
- `{value: number}`

## But what can accomplish by knowing the type of the patch?

The reducer is just a giant switch statement, and typescript doesn't infer that the type used in a case statement is the right restriction to the code inside the case (although conceivably in future such functionality could be added), so the answer is _not much_, when it comes to typing the reducer. The typecasts will always be necessary.

But everywhere else? Go ahead, use those types

## So that's why I wrote this proposal.

You're writing a typescript-first library, and you expect to distinguish yourselves from redux in some way. Allowing users to provide usable types to their instruction set payloads? That would be a great first step...

**Comment by jinder** [comment]
@ovangle (FYI, I don't work on NGRX, I just submitted a PR to fix an issue).  I was intrigued by this issue, because my actions don't have a payload property, and was wondering whether this was a good or bad decision on my part.

I still really don't see why NGRX needs to enforce the payload property.  If you want to use Action<T>, why not use it where you see fit?  Why does NGRX need to enforce this convention?  

Also, typecasts are not necessary in a reducer.  If you ensure that your action's type property is readonly, you can use [discriminated unions](https://basarat.gitbooks.io/typescript/content/docs/types/discriminated-unions.html) to get the correct type inference for your action types.

**Comment by ovangle** [comment]
> If you ensure that your action's type property is readonly, you can use discriminated unions to get the correct type inference for your actions.

Discriminated unions still just give a shared common base for your action types, the typecasts are still necessary (but typescript isn't going to complain if you don't provide them, because it thinks payload is "any". 

I'm still going to have to 

```typescript
function reducer(state: Tape, action: Move | Write | Reset) {
   switch (action.type) {
       case Move:
          // If there's no typecast here, typescript will complain with:
          // TS2339: Property 'value' does not exist on type '{ value: number; } | { offset: number; }'
          // Property 'value' does not exist on type '{ offset: number; }'.

          return new Tape(tape.head + (<Move>action).payload.offset, contents);
   }
}
```

This however, as I've noted, can't be improved upon if you correct the `Action` interface.

> because my actions don't have a payload property, and was wondering whether this was a good or bad decision on my part.

It's fine that your actions don't have a "payload" property. There's nothing bad about it, indeed that is exactly the redux model for how the payload should be included (cause redux don't care about dem types). The `Action` is considered a black box of key value pairs, and the only thing we know about it is the `type` key.

But I'm arguing that the library _should_ enforce a typed payload property. This doesn't change anything for you -- you just do a five minute refactor of your code to change the "black box" into a series of getters (probably in an abstract base class somewhere), like in the example I gave you above. Then everywhere else in your code you can ignore the existence of `payload` entirely.

And by exposing that small amount of type information (and by using typestrings only when interoperating with redux libs), you'll see the whole ngrx API become a whole lot simpler.

*Well, apart for the reducers. You will never be able restrict the type by entering a case statement.**

**Comment by karptonite** [comment]
@ovangle 
> Well, apart for the reducers. You will never be able restrict the type by entering a case statement.

I believe I have a counter example to that here: https://github.com/ngrx/platform/issues/132#issuecomment-317196727

**Comment by ovangle** [comment]
Well it seems that the whole strings -> type mapping was just an editor bug. Teaches me to open my mouth in public, I guess.

**Comment by ovangle** [comment]
Still, this issue is still closed and likely to remain closed now, so I'll shut the hell up and crawl back into my hole.

**Comment by ovangle** [comment]
So...

When nobody wants to agree with you, you're probably wrong. So, after updating my editor (because it was out of date and causing bugs) and upgrading to `immutable@4.0.0-rc.2` (which got rid of _a lot_ of the typecasts I was having to do), I refactored my code to get rid of all of the `payload`s.

And... it's good. I'm sorry for wasting your time with all this, although I'd gamble nobody has even bothered to read my essays (because it's painfully obvious that I'm an idiot), so it was only my time that has been wasted. I was so confident that I knew the answers to the old library's problems that I didn't spend the time actually figure out how you'd solved those problems in the new version, because it wasn't the way I suggested you'd solve them. I'm such a child sometime.

There's only one pain point I still have, and that's the multiple declarations of the type of an action:

```typescript
export const MY_ACTION_TYPE = '[feature area] my action'; // (1)
export class MyAction implements Action {   // (2)
   readonly type = MY_ACTION_TYPE; // (3)
   /* etc. */
}

export type Actions // (4)
    = MyAction;
```

You have to declare the action *four* times for it to be useful. That's horribly redundant. If I was to resubmit the proposal with _just_ the *use type tokens instead of strings* part (getting rid of all the crap about generics), would you be more receptive?

**Comment by jinder** [comment]
@ovangle I've found using ```readonly```, ```Readonly<>``` and ```ReadonlyArray<>``` is sufficient in my code to ensure immutability.  So you may not even need or want to use immutable.js.

**Comment by ovangle** [comment]
Thanks for that advice, but I use the immutable.js collection types everywhere, they're far more functional than their javascript counterparts. It's always the _first_ library I install when I start a new project.

There were some problems with the libraries type declarations because they wrote it for a much older typescript. But there aren't anymore because they have fixed them in 4.0.0.

**Comment by BennieCopeland** [comment]
@ovangle Can you go into detail on how the new library solves the problem? I'm still trying to figure it out, and there seems to be little documentation available. I've taken to casting my actions in the `case` blocks.

**Comment by jbonfante** [comment]
@ovangle I Read Them! (your essays) Being a fan of the payload myself, I was even rooting for you at time there, but casting when needed is definitely the way to go. And the pain points, redeem themselves when they save ya... that random chance or three.

**Comment by murpyslaw** [comment]
I got around this issue of a non-generic action by creating the following:
```
import { Action } from '@ngrx/store';

type GenericAction<T> = {
	[K in keyof T]: T[K]
}
export default interface Action<T> extends Action {
	payload: GenericAction<T>
}
```

It's much safer than an `any` typed payload, and seems pretty easy to implement. I'm probably missing something obvious though, it couldn't be THAT simple to do, could it?

**Comment by jiqsaw** [comment]
https://github.com/jiqsaw/ngrx-generic
