### ISSUE TITLE
migrate  tool to fix store.select is deprecated 

### ISSUE THREAD

**Issue by ofirrifo** [ngrx/platform#1282]
## Describe any alternatives/workarounds you're currently using
it seems that the select is deprecated and I have to use store.pipe(select())
I have a big project with more than 100 places I'm using store.select
currently I replace it manually in the code which takes a lot of time.

is it possible to create a tool just like the "rxjs-5-to-6-migrate" for this case?

Thanks
## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
Yes, that is being tracked here https://github.com/ngrx/platform/issues/1230
