### ISSUE TITLE
Example: Add tsconfig paths to cleanup relative imports

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1284]
## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

Add an `@example-app` path to the `tsconfig.app.json` and clean up the relative imports. Respond with a comment if you are willing to take this one.

**Comment by mgred** [comment]
@brandonroberts I'm willing to take this

**Comment by mgred** [comment]
Hey guys
PR is opened: #1312 

Path is added to `tsconfig.app.json`
```json
...
"@example-app/*": ["./src/app/*"]
...
```

My editor (vim + tsserver) didn't get it, since it is looking for `tsconfig.json` in a parent directory of the current file, therefore a path was also added to `tsconfig.json` in the root folder of the repo.

**Comment by mgred** [comment]
Production build is failling. Can be reproduced:

```bash
yarn run example:build:prod
```

This is because for some reason I add the `rootDir` property to the [`tsconfig.app.json`](https://github.com/ngrx/platform/pull/1312/files#diff-5ce09dd9c6c63d4c17383cbe83ef6902) in the example app. I removed it and fixed the path alias and it worked for me locally.

**Comment by mgred** [comment]
Executed:
```bash
for module in auth books core material reducers shared; do \
    ag --vimgrep "'(.*)[./]\/$module\/" projects/example-app/src/app | cut -d ':' -f 1 | uniq | xargs -L1 sed -i -E "s|'(.*)[./]\/$module\/|'\@example-app\/$module\/|"; 
done
```
This replaced most of the relative paths. Unit tests and production build worked
