### ISSUE TITLE
@ngrx/entity Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by mxchange** [ngrx/platform#1285]
I can't figure out the cause of this error:

`Cannot read property 'Symbol(Symbol.iterator)' of undefined`
![screenarea_2018-08-24_16-00-21](https://user-images.githubusercontent.com/24876534/44588750-da1cb100-a7b6-11e8-8074-163dc51d1cd4.png)

I'm unable to find the exact source file for this line of code, and do not know what is causing this, other than it happens after `.addAll` or `addMany` is getting called.

**Comment by timdeschryver** [comment]
Support questions should be asked on [StackOverflow (with a NgRx tag)](https://stackoverflow.com/questions/tagged/ngrx) or the [gitter channel](https://gitter.im/ngrx/platform).

Make sure to add more information (mainly your code) in order to this problem.

**Comment by DigiBanks99** [comment]
I got the same error. The problem was that my state did not have an ids field and this was due to me not setting up my initialState properly.
