### ISSUE TITLE
Router Store: Refactor router_store_module into separate files

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1298]
## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

The actions, reducer and module are all in one file.

**Comment by kouMatsumoto** [comment]
I'd like to submit pull request.

**Comment by brandonroberts** [comment]
Ok, wait until #1294 lands or branch from there to get started

**Comment by kouMatsumoto** [comment]
Certainly, thank you.

**Comment by timdeschryver** [comment]
Well that was fast 🔥 🔥 🔥
