### ISSUE TITLE
navigationActionTiming

### ISSUE THREAD

**Issue by zpydee** [ngrx/platform#1306]
### In our gitter support channel at https://gitter.im/ngrx/platform

HI, I've posted in Gitter, so please excuse the repetition.

I'm using 6.1.0 of router-store. I'm following the docs to set up `RouterStoreConnectingModule.forRoot({navigationActionTiming: NavigationActionTiming.PostActivation})` but it appears that the attr is missing in the `StoreRouterConfig` interface?

I see it on the master branch in the repo, but not in my local node_modules

Am I missing something?

**Comment by timdeschryver** [comment]
it's a new feature which will become available in the next release
if you want to use it now, you can install the nightly builds

**Comment by zpydee** [comment]
@timdeschryver nope, its not on the nightly builds either.

**Comment by timdeschryver** [comment]
I'll re-open the issue, and ask for @brandonroberts 's help on this.

**Comment by zpydee** [comment]
@brandonroberts it seems nightly builds (p[er my yarn.lock) are pointing at `6.0.1`, which also doesn't include this feature.

**Comment by brandonroberts** [comment]
The nightlies build are working correctly now: https://github.com/ngrx/router-store-builds

**Comment by zpydee** [comment]
hmmm, this feature breaks my app. gonna have to wade through my logic to se what it affects...
