### ISSUE TITLE
Example: Create barrels for actions and refactor imports

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1316]
## Other information:

Instead of importing actions directly from multiple files, create `index.ts` in the `actions` folders and export the actions from each file there. This is similar to what we do with the `reducers/index.ts` pattern where this is considered the "public api".

For example

```
import * as AuthActions from './auth.actions';
import * as AuthApiActions from './auth-api.actions';

export { AuthActions, AuthApiActions };
```

Usage

```
import { AuthActions, AuthApiActions } from '@example-app/auth/actions';

case AuthActions.AuthActionTypes.Logout:
```

Leave a comment if you will take this one.

**Comment by peterbsmith2** [comment]
sure. expect something before 5 PM eastern.
