### ISSUE TITLE
Request patch tag release

### ISSUE THREAD

**Issue by blackholegalaxy** [ngrx/platform#1321]
Hello there,

Some patchs have been pushed in master since latest releases. Some are needed in order to get buggy behaviors to be fixed.

Could you consider to release a patch version of ngrx modules?

Or do you have any way for us to use master branch for every single modules?

Thanks for considering this.

**Comment by timdeschryver** [comment]
You can install the packages from the nightly builds, e.g. `yarn add github:ngrx/store-builds`.
