### ISSUE TITLE
Lazy Loaded Module Fired Twice When Changing routes

### ISSUE THREAD

**Issue by blindsz** [ngrx/platform#1323]
Anyone stumbled upon an issue regarding Lazy Loaded Modules with ngrx-store? The issue is I have this two routes that is lazy loaded. Whenever I go to the second route and using this code "this.store.subscribe" in component.ts under ngOnInit function it will fire twice.

**APP.MODULE.TS**
const routes: Routes = [
  {
      path: 'courses',
      loadChildren: './routes/courses/courses.module#CoursesModule'
  },
  {
      path: 'teachers',
      loadChildren: './routes/teachers/teachers.module#TeachersModule'
  },
  {
      path: '',
      redirectTo: '',
      pathMatch: 'full'
    }
];

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    RouterModule.forRoot(routes),
    StoreModule.forRoot(reducers, { metaReducers }),
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

**Comment by timdeschryver** [comment]
Support questions should be asked on [stackoverflow (with a NgRx tag)](https://stackoverflow.com/questions/tagged/ngrx) or the [gitter channel](https://gitter.im/ngrx/platform).

Also it's hard to pinpoint the cause of this problem with only the shared code, a reproduction would be helpful.
