### ISSUE TITLE
Action switching

### ISSUE THREAD

**Issue by dsl400** [ngrx/platform#1328]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Feature request
[ *] Documentation issue or request
</code></pre>

## What is the current behavior?

console.log(action.type) inside any reducer function will log actions form all the application

## Expected behavior:

reducers should receive only own actions

**Comment by timdeschryver** [comment]
This is by design, an action **must** be "dispatched" to all reducers.

**Comment by dsl400** [comment]
this means that 100 reducers will switch test more than 6 cases per action ?

**Comment by timdeschryver** [comment]
Correct - [Won't calling “all my reducers” for each action be slow?](https://redux.js.org/faq/performance#performance-all-reducers)
