### ISSUE TITLE
ngrx action/state history

### ISSUE THREAD

**Issue by AngelKyriako** [ngrx/platform#134]
I am looking for a way to access the lastest [number]{state, action} pairs fired.

Is there a way to do this by either subscribing somewhere or via the store-devtools library ?

I am looking into using those data to POST them into the server when something crashes in the app or the user files a bug.

Any help mostly appreciated.

**Comment by bfricka** [comment]
This isn't really relevant to this project. Getting the last two values can be accomplished with `pairwise`:

```ts
getOnlineState(store$)
  .pairwise()
  .subscribe(([wasOnline, isOnline]) => {
    // Do something with last two
  });
```
