### ISSUE TITLE
How to reuse smart components (containers) with its own state?

### ISSUE THREAD

**Issue by DmitriyIvanko** [ngrx/platform#1343]
## How to reuse smart components (containers) with its own state?
As suggest @robwormald I reopen this issue: https://github.com/ngrx/store/issues/393

## Small example:
Imagine you have a complex smart component (container): book-collection.container.ts with its own state. In this state you keep current: pagination-model, sort-model, filter-model and etc. 
And what if you what reuse it? For example:
```
<div class="row">
    <div class="col-6">
        <app-book-collection></app-book-collection>
     </div>
    <div class="col-6">
        <app-book-collection></app-book-collection>
     </div>
</div>
```
All containers dispatch the same actions, and trigger the same reducer or effects. But they should keep it's own state: for example: on the left `<app-book-collection>` I change filter-model, but on the right `<app-book-collection>` I change sort-model. But any dispatched actions will affect on both containers!

I found many related questions on StackOverflow and ngrx/store:
1) https://stackoverflow.com/questions/49537571/independent-instances-of-the-same-ngrx-feature-module
2) https://github.com/ngrx/store/issues/278
3) https://github.com/ngrx/store/issues/393
4) https://github.com/ngrx/store/pull/269#issuecomment-283258747 

I researched a lot of docs. There are a lot of hacks with ids for every container. But I can't find a good solution for this. Can you explain the official solution? Thank you for any help.

**Comment by timdeschryver** [comment]
The only way to differentiate these collections is by id, like you said. Your example will become something like:
```html
<div class="row">
    <div class="col-6">
        <app-book-collection id="47"></app-book-collection>
     </div>
    <div class="col-6">
        <app-book-collection  id="3"></app-book-collection>
     </div>
</div>
```

Perhaps #858 will solve this use case in the future.

**Comment by DmitriyIvanko** [comment]
@timdeschryver Really thank you for your answer. Will be wait "Local State API for Component Local States" feature.
