### ISSUE TITLE
Router-store reducer does not compile with --strictFunctionTypes

### ISSUE THREAD

**Issue by rkirov** [ngrx/platform#1344]
## Minimal reproduction of the bug/regression with instructions:
The definition of routerReducer is written to accept a subtype of Action.

https://github.com/ngrx/platform/blob/master/modules/router-store/src/reducer.ts#L23

That is not correct as every action runs through every reducer (if I understand ngrx correctly that is still the case). TypeScript with --strictFunctionTypes errors when you write you your reducers with any type different from `reducer(state = defaultState, action: Action)`. 

## Expected behavior:

Router reducer should be written as:
```typescript
routerReducer(state = defaultState, action: Action) {
  const routerAction = action as RouterAction; 
}
```

The unsafe (but benign) type cast should live inside the reducer function.

## Other information:
General issue about --strictFunctionTypes - https://github.com/ngrx/platform/issues/951.

## I would be willing to submit a PR to fix this issue

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
You get a 👍 from me.
(And yes you're right, every actions runs through every reducer)

**Comment by brandonroberts** [comment]
👍

**Comment by alex-okrushko** [comment]
Thanks Rado!
