### ISSUE TITLE
Use another data as id in entity

### ISSUE THREAD

**Issue by blackholegalaxy** [ngrx/platform#1348]
Currently, @ngrx/entity seems to rely on the fact there is a data named `id` in the model to work.

It could be interesting to support, when creating the adapter for example, the fact to design another data as id. Do you have any way to achieve that?

**Comment by timdeschryver** [comment]
This is already possible with `selectId` - [docs](https://github.com/ngrx/platform/blob/master/docs/entity/adapter.md#createentityadapter)
