### ISSUE TITLE
Docs for router-store has wrong config

### ISSUE THREAD

**Issue by wszgrcy** [ngrx/platform#1349]
## Other information:
code in `platform/docs/router-store/api.md`

```ts
interface StoreRouterConfig {
  stateKey?: string;
  serializer?: new (...args: any[]) => RouterStateSerializer;
  navigationActionTiming?: NavigationActionTiming;
}
```
but in `"@ngrx/router-store": "^6.1.0",`
```ts
export interface StoreRouterConfig {
    stateKey?: string;
}
export declare type StoreRouterConfigFunction = () => StoreRouterConfig;
```
How to config router with new version?
I have  not used before
## I would be willing to submit a PR for the docs :heart:

[x ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
This will become available in the next version.
To use it now you can install ngrx from the nightly builds.

**Comment by carlos-stage** [comment]
I think it is confusing, as it is not present on main package but referenced on the main documentation. At least an explanation pointing that to use it ngrx router nightly builds is needed, could avoid misunderstandings.
