### ISSUE TITLE
Route params not being set to store for secondary outlets

### ISSUE THREAD

**Issue by markgoho** [ngrx/platform#1351]
## Minimal reproduction of the bug/regression with instructions:
Route params aren't being set for secondary outlets.

https://stackblitz.com/edit/ngrx-seed-3k3rpz

## Expected behavior:
Route params _should_ be set for secondary outlets.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
NgRx, 6.1.0
Angular, 6.1.9
Node, 10

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by markgoho** [comment]
I'm guessing this has something to do with the boilerplate code for the custom serializer.

**Comment by timdeschryver** [comment]
As @kouMatsumoto has mentioned, you'll have to create your a [Custom Router State Serializer](https://github.com/ngrx/platform/blob/master/docs/router-store/api.md#custom-router-state-serializer).
