### ISSUE TITLE
Schematics:feature generates incorrect code for Effects

### ISSUE THREAD

**Issue by krzysztof-grzybek** [ngrx/platform#1356]
## Minimal reproduction of the bug/regression with instructions:
The following command:
`ng generate @ngrx/schematics:feature customName`
generates effects file:
```
import { Injectable } from '@angular/core';
import { Actions, Effect, ofType } from '@ngrx/effects';
import { CustomNameActionTypes } from './custom-name.actions';

@Injectable()
export class CustomNameEffects {

  @Effect()
  loadFoos$ = this.actions$.pipe(ofType(CustomNameActionTypes.LoadCustomNames));

  constructor(private actions$: Actions) {}
}
```

## Expected behavior:

I think that instead of `loadFoos$` it should be `loadCustomNames$`:

```
import { Injectable } from '@angular/core';
import { Actions, Effect, ofType } from '@ngrx/effects';
import { CustomNameActionTypes } from './custom-name.actions';

@Injectable()
export class CustomNameEffects {

  @Effect()
  loadCustomNames$ = this.actions$.pipe(ofType(CustomNameActionTypes.LoadCustomNames));

  constructor(private actions$: Actions) {}
}


```

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
"@ngrx/schematics": "^6.1.0",
"@angular/core": "^6.1.0",
node: 10.9.0
## I would be willing to submit a PR to fix this issue

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by krzysztof-grzybek** [comment]
Sure! I'll do it today or tomorrow at the latest.

**Comment by timdeschryver** [comment]
Thanks @krzysztof-grzybek!

**Comment by dummdidumm** [comment]
Since the PR was merged, this can be closed, right?

**Comment by brandonroberts** [comment]
Fixed via https://github.com/ngrx/platform/pull/1357
