### ISSUE TITLE
@nrgx/effects issue

### ISSUE THREAD

**Issue by Cosmocat** [ngrx/platform#136]
Hello,

I'm getting this error when trying to import EffectsModule in app.module.ts

No provider for Actions! ; Zone: <root> ; Task: Promise.then ; Value: Error: No provider for Actions!

here is how import looks like: EffectsModule.forRoot([MyEffects])

Can anyone help?

**Comment by maxisam** [comment]
do you put your action in the providers in @NgModule?

**Comment by maxisam** [comment]
I meant your own action class not Actions from '@ngrx/effects'

**Comment by DavidStrausz** [comment]
@Cosmocat We had the exact same error in our project after upgrading/refactoring it for NGRX4. In our case it was a faulty import from ngrx/effects. This is the commit that fixed it for us:
```
- import { Actions, Effect } from '@ngrx/Effects';
+ import { Actions, Effect } from '@ngrx/effects';
```
So you should probably look for some typo somewhere.

**Comment by Cosmocat** [comment]
Thx, I got it working using @adammartin1981  approach.
