### ISSUE TITLE
CustomSerializer error alert

### ISSUE THREAD

**Issue by docaohuynh** [ngrx/platform#1360]
Hi team!
I have config customserializer but it show error below
```
[ts]
Argument of type '{ serializer: typeof CustomSerializer; }' is not assignable to parameter of type 'StoreRouterConfig | StoreRouterConfigFunction'.
  Object literal may only specify known properties, and 'serializer' does not exist in type 'StoreRouterConfig | StoreRouterConfigFunction'.
```
How do I solve it? Tks

My Version:
Angular 6.1
Ngrx 6.1.0

**Comment by timdeschryver** [comment]
Support questions should be asked on [stackoverflow (with a ngrx tag)](https://stackoverflow.com/questions/tagged/ngrx) or the [gitter channel](https://gitter.im/ngrx/platform).

Also make sure you're looking at the [documentation for v6.1](https://github.com/ngrx/platform/tree/6.1.0).
