### ISSUE TITLE
DefaultRouterStateSerializer: path property missing in routeConfig

### ISSUE THREAD

**Issue by JanCejka** [ngrx/platform#1363]
## Minimal reproduction of the bug/regression with instructions:

Example: https://stackblitz.com/edit/ngrx-seed-nl8b8q?file=src%2Fapp%2Fapp-routing.module.ts

Routing effect based on: https://github.com/vsavkin/state_management_ngrx4

## Expected behavior:

routerConfig should contain path / pathMatch (if it exists in original routerConfig) to allow easy identification of Router rule that was used to match used route. This way of matching is used in above mentioned example.

In example above, if routes in `app-routing.module.ts` are defined as shown in example, it's not possible to distinguish in `effects/routing.effects.ts`, function `handleNavigation` what rule in router definition was used (`data/:id` or `test/:id`) since path / pathMatch keys are missing. This has worked before since routeConfig from ActivatedRouteSnapshot was used directly and it contains these keys.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

NgRx: 6.1.0
Angular: 6.1.1
Node: 8.9.4

## Other information:
Current behaviour is caused by: https://github.com/TypescriptID/platform/pull/102/commits/7917a276fa199b19d6d8f2e3d2fa1708e3481c2b

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

**Comment by timdeschryver** [comment]
What exactly are we looking at here?
