### ISSUE TITLE
Somehow warn developers about erring or completing @Effect Observables

### ISSUE THREAD

**Issue by michahell** [ngrx/platform#1364]
I think it is under-documented that, because `@Effect`s are also `Observable`s, they stop emitting values after erring or being completed.
I see waiting for something that never happens effectively as silently failing. As this happens more often when working with Observables, developers are used to it, but it could be expected that `@Effect`s work differently.

 It would be quite helpful to have a list of operators which are dangerous to use in `@Effect`s, ie, operators that complete observables, such as `first()` and `empty()`, and using the `catchError()` operator in the 'main' Effect observable (as opposed to within `switchMap`, `concatMap`, `map` etc).

I suggest that either:
- `@Effect`s when they error ór complete, provide a warning regarding them being completed.
- documentation is updated to reflect that developers have to be careful with certain operators (see list idea above) in `@Effect`s.

related SO posts:

- https://stackoverflow.com/questions/44180361/ngrx-effect-does-not-run-the-second-time
- https://stackoverflow.com/questions/45523127/observable-with-rx-broken-after-error
- https://stackoverflow.com/questions/47896171/is-it-possible-to-throw-errors-inside-ngrx-effects-without-completing-the-observ
- https://stackoverflow.com/questions/45556674/ngrx-effect-only-triggers-once-angular-4

**Comment by michahell** [comment]
Yes, showing how to handle errors in an Effect would be a great start, or better said, how *not* to handle errors :)

**Comment by timdeschryver** [comment]
I'll close this issue in favor of https://github.com/ngrx/platform/issues/1336 .
