### ISSUE TITLE
Schematic "State" not found in collection "@ngrx/schematics".

### ISSUE THREAD

**Issue by xxluke** [ngrx/platform#1365]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## What is the current behavior?
Terminal output
> Error: Schematic "State" not found in collection "@ngrx/schematics".

## Expected behavior:
Generation of a new state.

## Minimal reproduction of the problem with instructions:
From the [docs](https://github.com/ngrx/platform/blob/master/docs/schematics/README.md):

> Generate the initial state management and register it within the app.module.ts
> `ng generate @ngrx/schematics:store State --root --module app.module.ts`
> > Note that `@ngrx/schematics:store` is only needed when the default collection isn't set to `@ngrx/schematics`

So I believe I can skip the `@ngrx/schematics:store` part because my angular.json looks like this:
```json
  "schematics": {
    "@ngrx/schematics:component": {
      "styleext": "scss"
    }
  },
  "cli": {
    "defaultCollection": "@ngrx/schematics"
  }
```
but then the above error occurs.

It works when I use the full command.

## Versions
Angular 6.1, ngrx 6.1

**Comment by kouMatsumoto** [comment]
Use `ng generate store State --root --module app.module.ts` but `ng generate State --root --module app.module.ts`.
You can skip `@ngrx/schematics:` part.

**Comment by timdeschryver** [comment]
What @kouMatsumoto is correct, it should be `ng generate store State --root --module app.module.ts`. 

Could you send in a PR in order to get this right @xxluke ?
