### ISSUE TITLE
Geting rid of action type?

### ISSUE THREAD

**Issue by bOmBeLq** [ngrx/platform#1372]
Since actions are objects we should be able to identify actions solelly basing on action instance type not the type field. Doing this would reduce code boilerplate a little.
So where is the type field used?
1. ofType operator
1. reducers switch function
1. Am I missing anything?
-------------
1. ofType operator would be easilly replaced with ofInstance operator:
```
export const ofInstance = (instance) => <T>(source: Observable<T>) =>
	source.pipe(filter((value) => value instanceof instance));
```
2. Reducers are the harder part. We could replace the switch with if, else statements but I wouldn't like it:
```
export function reducer(state = initialState, action: SomeActions): GlobalTasksState {
	if (action instanceof SomeAction) {
		// ... modify state
	}
	else if (action instanceof OtherAction) {
		// ... modify state
	}
	else {
		// .....
	}
}
```

But I don't like it. Instead I think we should create some abstraction which would allow to register multiple reducers. Something like:
```
const multiReducer = new MultiReducer();

multiReducer.add(someReducerFunction, SomeAction);
multiReducer.add(someReducerFunction2, [SomeAction, SomeOtherAction]);

// default reducer (this could actually be coded by default in the MultiReducer since by default the reducer will return simply copy of actualy state)
multiReducer.setDefault(someReducerFunction3);

export const reducer = multiReducer;

```
We could also consider some reducerBuilder. 

```
export const reducer = reducerBuilder()
.add(someReducerFunction, SomeAction)
.add(someReducerFunction2, [SomeAction, SomeOtherAction])
.setDefault(someReducerFunction3)
.getReducer();
```

[*] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
Thanks for the idea @bOmBeLq. We won't be removing the action type. See https://github.com/ngrx/platform/issues/1345 for reference
