### ISSUE TITLE
@Effect is ignored when defined in an abstract class

### ISSUE THREAD

**Issue by timosadchiy** [ngrx/platform#1374]
First of all, thank you for the ngrx! It's abslutely awesome!

## Minimal reproduction of the bug/regression with instructions:
Effects are ignored when defined in an abstract class that is extended by an injectable.
Example: https://stackblitz.com/edit/ngrx-seed-dupnes?file=src%2Fapp%2Feffects%2Feffects.ts

## Expected behavior:
Effects defined in an abstract class should fire the same way as effects defined in an injectable extending that class.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

NgRx: 6.1.0
Angular: 7.0.0
Node: 10.7.0

## Other information:
With the NgRx 6.0.1 (same angular and node) effects defined in abstract classes fire as expected in my local project. However, when I tried to reproduce the expected behaviour with NgRx 6.0.1 in stackblitz, it still didn't work. 

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

**Comment by timdeschryver** [comment]
Thanks @jfrazx!
