### ISSUE TITLE
docs: Rewrite guides

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1383]
General

- [ ] Architecture

@ngrx/store

- [x] Overview
- [x] Actions
- [x] Reducers
- [ ] Selectors
- [ ] Testing

@ngrx/effects

- [x] Overview
- [x] Effects
- [ ] Testing

## Other information:

Tracking these under a single issue rather than separate issues for each one.

**Comment by damienwebdev** [comment]
@brandonroberts do you need help with this one? We're refactoring our tests over in graycoreio/daffodil and one of our packages depends heavily on ngrx. I'd imagine with the new `MockStore`, you need docs covering this new feature and it's usage.

I'd be happy to chip in here if that would be useful.

**Comment by brandonroberts** [comment]
@damienwebdev Yes, that would be great!

**Comment by simonh1000** [comment]
Could I suggest that you add an installation guide for the library as a whole, with schematics etc. I'm relying upon stuff on the internet but never know whether that is best practise

**Comment by nasreddineskandrani** [comment]
@damienwebdev are you going to add doc for MockStore? 

I'll open a PR to update the example-app with MockStore as stated in this comment
https://github.com/ngrx/platform/pull/1027#issuecomment-434728683

**Comment by michahell** [comment]
To make sure that my request (making sure there is a part about `completing` and `erroring out` killing the observable, effectively) is not forgotten:
https://github.com/ngrx/platform/issues/1364

See also explanation in this article:
https://blog.angularindepth.com/5-tips-to-improve-user-experience-of-your-angular-app-with-ngrx-6e849ca99529

**Comment by brandonroberts** [comment]
Thanks @michahell. There is a specific section in the effects guide that covers this https://ngrx.io/guide/effects#handling-errors

**Comment by michahell** [comment]
ah nice, I see :) okay moot point then! great :)

**Comment by sgronblo** [comment]
Any plan to document `State` as part of this?

**Comment by brandonroberts** [comment]
@sgronblo what do you mean? Document the API?

**Comment by sgronblo** [comment]
Hmm, I must have not been looking close enough yesterday. I was able to find `State` now. At least in the API section. There doesn't seem to be any mention about it in the "normal" documentation pages on ngrx.io though.

**Comment by timdeschryver** [comment]
Do you mean [this page](https://github.com/ngrx/platform/blob/master/docs/store/api.md) @sgronblo ? If so, which part?

**Comment by sgronblo** [comment]
Not sure if this documentation feedback should go somewhere else, but here goes.

I was writing a service that needed to get a value from the Store. Realized that Store is an Observable and got worried that this could cause a problem where my service would not be able to get the required value from the Store until that value changes the next time. Lots of frantic googling finds a mix of different clues that ngrx also contains State which seems like it is same as Store except as a BehaviorSubject.

However, going to the actual ngrx.io site and trying to get a confirmation that my understanding is correct yields almost no information that State even exists. At least not in a way where it is easily found from the left menu on the document page. Eventually I found that State is in the API section here: https://ngrx.io/api/store/State but this page basically doesn't explain anything about whether there are any caveats to using it or whether I can just swap out the Store dependency to a State dependency and have everything work as expected.
