### ISSUE TITLE
The same store for multiple lazy loading modules

### ISSUE THREAD

**Issue by serrg1994** [ngrx/platform#139]
How can I use only one store for all my lazy loading modules. As I understand for every lazy loaded module I have different store and when I user shared module.

**Comment by karptonite** [comment]
You should be able to have those lazy loaded modules each import a SharedStoreModule, and add handle the shared store in that commonly loaded module.

**Comment by brandonroberts** [comment]
You don't have more than one store for lazy loaded modules. If you add `StoreModule.forRoot` to your `AppModule`, you will only have one instance of `Store` throughout your app.
