### ISSUE TITLE
@ngrx/router-store docs out of date

### ISSUE THREAD

**Issue by cmeyertons** [ngrx/platform#1390]
@ngrx/router-store
## Minimal reproduction of the bug/regression with instructions:

What is the recommended pathway for setting up a custom serializer?

```
@Injectable()
export class CustomSerializer implements RouterStateSerializer<RouterStateUrl> {
  public serialize(routerState: RouterStateSnapshot): RouterStateUrl {
    let route = routerState.root;

    while (route.firstChild) {
      route = route.firstChild;
    }

    const {
      url,
      root: { queryParams },
    } = routerState;
    const { params } = route;

    // Only return an object including the URL, params and query params
    // instead of the entire snapshot
    return { url, params, queryParams };
  }
}

@NgModule({
    declarations: [
        AppComponent,
    ],
    imports: [
        BrowserModule,
        BrowserAnimationsModule,
        FormsModule,
        HttpClientModule,
        HttpModule,
        RouterModule,
        PagesModule,
        SharedComponentsModule.forRoot(),
        StoreModule.forRoot({ ...reducers, router: routerReducer }),
        RouterModule.forRoot(routes),
        StoreRouterConnectingModule.forRoot({
            serializer: CustomSerializer
        }),
        !environment.production ? StoreDevtoolsModule.instrument() : [],
        EffectsModule.forRoot([ DataIntegrityEffects ]),
    ],
    providers: [GlobalState, GlobalService],
    bootstrap: [AppComponent]
})
```

![image](https://user-images.githubusercontent.com/19917677/47753059-55da2480-dc64-11e8-9f4e-8f9c79ada379.png)

**Comment by timdeschryver** [comment]
This is the documentation for features that aren't released yet, these will become available in the next version.

To read the documentation of your version, you can find a note in the [README](https://github.com/ngrx/platform/blob/master/README.md#packages).
> Note: The links below will take you to the master branch version of the docs. To view the docs corresponding to a specific release (which is probably what you want), the easiest way is to use git tags to browse a snapshot of the repo as it was for a release. One way to do this, is to use github's branches toggle (which is by default labeled "Branch: Master" and is located on the far left of the green "clone or download" button, above). Click the toggle, click the "tags" tab in the overlay pane, and select the tag for a release.

**Comment by cmeyertons** [comment]
ah that would explain it!  thanks @timdeschryver 

I ended up figuring it out from the source code and the way i did it matched the docs, whoop whoop.

You guys might want to call that out in the README and provide the instructions you just did to look at your specific release - may reduce false issues and save y'all time.

**Comment by timdeschryver** [comment]
It's mentioned in the "root" README. I suppose most people skips this part and immediately browses through `/docs/`, myself included 😅 .
Also this problem would resolve itself once ngrx.io launches.

**Comment by cmeyertons** [comment]
lol okay i'm just a serial skimmer, my bad!

ngrx.io sounds sweet, looking forward to it!
