### ISSUE TITLE
Angular dependencies could use a version bump to 7

### ISSUE THREAD

**Issue by snebjorn** [ngrx/platform#1391]
## Minimal reproduction of the bug/regression with instructions:
`ng update @ngrx/store` (also `npm up`) fails with incompatible angular 7 version.

It doesn't appear to have been fixed in ngRx v6.1.1 either.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
Angular 7, ngRx 6.1.0

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

**Comment by timdeschryver** [comment]
Hi, NgRx 6.1.1 has indeed Angular 6 dependencies, but should also work with Angular 7.
We're working on the Angular update in https://github.com/ngrx/platform/pull/1354.

**Comment by fr0** [comment]
Angular 7 has been out for two weeks, is there a reason RxJS isn't already updated for it?
