### ISSUE TITLE
Why schematics not follow example app?

### ISSUE THREAD

**Issue by wizardnet972** [ngrx/platform#1400]
In `ngrx/schematics`, does the prefix `Load` make any sense for action except loading things? for example, I want to create an action called `Login`, so if I generate through the schematics, it's output **Load**Login**s**.....
I also can see in the next version that @brandonroberts remove the prefix.. so this is the standard?

**Comment by brandonroberts** [comment]
I'm not exactly sure what you mean. Yes, the `Load` mostly makes sense for loading things, but this is also just scaffolding to get you started. We could add an option to disable prefixing from the generated action?
