### ISSUE TITLE
Can't time travel if router state key is not explicitly defined

### ISSUE THREAD

**Issue by alaboudi** [ngrx/platform#1404]
## Minimal reproduction of the bug/regression with instructions:
```
imports: [
...
StoreRouterConnectingModule.forRoot(), // does not work with time travel debugging
]
```
but
```
imports: [
...
StoreRouterConnectingModule.forRoot({stateKey: 'router'}), // works as expected
]
```

## Expected behavior:
time traveling should work by just calling `.forRoot()` with no config

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
Ngrx 6, Node 10.x.x, Angular 6, Chrome, Mac
## I would be willing to submit a PR to fix this issue

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Hi, how does your state and action reducer map look like?

**Comment by alaboudi** [comment]
@timdeschryver below is my state and action reducer map

```
export interface AppState {
  router: RouterReducerState;
}

export const appReducerMap: ActionReducerMap<AppState> = {
  router: routerReducer,
};

const metaReducers: MetaReducer<AppState>[] = !environment.production ? [storeFreeze] : [];
```

**Comment by brandonroberts** [comment]
In V6 you must still define the `stateKey` as `router`. In V7, `router` is the default.
