### ISSUE TITLE
Custom Router State Serializer

### ISSUE THREAD

**Issue by philmayfield** [ngrx/platform#1405]
## Other information:

The documentation example for this section has an error:
`serializer: RouterStateSerializer,` should be `serializer: CustomSerializer`

Could use to be a little more clear as to where the pieces go too 😃 

## I would be willing to submit a PR for the docs :heart:

[ x ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
Will you fix this while you're tweaking that text for the official docs site?

**Comment by philmayfield** [comment]
> Will you fix this while you're tweaking that text for the official docs site?

Sure no problem.
