### ISSUE TITLE
ngrx.io: Weird package.json "name" field

### ISSUE THREAD

**Issue by icepeng** [ngrx/platform#1408]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## What is the current behavior?
https://github.com/ngrx/platform/blob/ccc99e9f7818ff10829876224af38e9ee5874270/projects/ngrx.io/package.json#L2

## Expected behavior:
```
"name": "ngrx.io"
```

## Minimal reproduction of the problem with instructions:
:)

## Version of affected browser(s),operating system(s), npm, node and ngrx:
Latest ngrx.io application

**Comment by brandonroberts** [comment]
@icepeng would you like to submit a fix? :-)

**Comment by icepeng** [comment]
@brandonroberts I'd love to, but I'm confused about how to write the commit message following the contribution guide.

**Comment by brandonroberts** [comment]
No problem. Just title the commit message "docs: update docs app name in package.json"

**Comment by icepeng** [comment]
Thank you, I submitted a pull request.

**Comment by icepeng** [comment]
Since the changed file was `package.json`, I was not sure how to choose between "docs", "fix" and even "build" type.

**Comment by brandonroberts** [comment]
I see. To keep things simple for next time, just use `docs` as the prefix.
