### ISSUE TITLE
StoreModule.forFeature should accept injection token

### ISSUE THREAD

**Issue by karptonite** [ngrx/platform#141]
See issue #116. The problem with AOT and reducers that are created by factories also exists for reducers imported in feature modules. However, the forFeature method lacks the handling for injector tokens that are present in forRoot. It seems like a similar approach should be added to forFeature.

**Comment by juliekoubova** [comment]
hello, is is there any chance this would get released soon? it's kind of blocking me 😢

**Comment by karptonite** [comment]
I believe that this was added in 4.0.2: https://github.com/ngrx/platform/blob/master/modules/store/CHANGELOG.md#402-2017-08-02

**Comment by juliekoubova** [comment]
ok i should be able just "as any" my way until this gets released 😄 
https://github.com/ngrx/platform/commit/38b2f955e980c8f717a184e860fdda2db159018a
