### ISSUE TITLE
docs: Create community section

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1411]
## I would be willing to submit a PR for the docs :heart:

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

We have an awesome community of people creating great content, libraries, and talks. We need a place to promote and provide visibility.

**Comment by timdeschryver** [comment]
I should be able to get this one started if that would be OK.
I was thinking of adding a menu item in the header, between docs and GitHub.

**Comment by brandonroberts** [comment]
👍

**Comment by LMFinney** [comment]
A co-worker and I created this library to use Java-style enums to defined actions: [ngrx-enums](https://www.npmjs.com/package/ngrx-enums)

**Comment by timdeschryver** [comment]
Resources are added at https://github.com/ngrx/platform/pull/1418
