### ISSUE TITLE
support meta reducer factory for feature

### ISSUE THREAD

**Issue by itayod** [ngrx/platform#1414]
## If accepted, I would be willing to submit a PR for this feature

[x ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
Will you explain further what you're asking for?

**Comment by timdeschryver** [comment]
As a workaround you could use:

```
StoreModule.forFeature('featureFoo', reducers, {
  metaReducers: [logger],
}),
```

**Comment by itayod** [comment]
What I am trying to do is saving parts of the store to the server.
Therefor I wanted to create a configurable meta reducer, pass him the keys that we want to save from the store and inject it the angular http client service and use it in every feature store.
In order to do so I need to be able to create a meta reducer with factory and provide it the http service and the keys.

right now this is my work around: 
```
export function myMetaReducer(reducer: ActionReducer<any>): ActionReducer<any> {
  const keys = ['stuff.from.state', 'another.stuff.form.state', ...];
  return createMyGerenricReducer(key)(reducer);
}

...
StoreModule.forFeature('feature', reducers, {metaReducers: [myMetaReducer]}),



```

**Comment by itayod** [comment]
Thanks for the reply,

as you can see my solution is not perfect yet because I still can't use angular's http service and currently I am using the browser's fetch Api.

Either way I see why you think it could be impossible to bind the meta reducer to the right feature with the way it works right now... 

I will try look up to a solution in the code and make a PR if I find one :)

**Comment by itayod** [comment]
I think I made a working solution...
but I think I will need permissions in order to add my branch.

**Comment by timdeschryver** [comment]
@itayod you can't push your branch into the ngrx repo. 
You'll have to fork the ngrx repo, clone this repo, create a feature branch on your personal repo, push commits to this branch. For some help you can take a look at the [contributing](https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md) file.
