### ISSUE TITLE
Why "EntityAdapter" methods (e.g. addOne) do not require "id" for an argument?

### ISSUE THREAD

**Issue by YuKimura45z** [ngrx/platform#1430]
Now, "EntityAdapter" require "selectId" for option in the creation.
It find its id by calling "selectId" and then register to a dictionary called "entities" in "EntityState."

Why "EntityAdapter" methods (e.g. addOne) do not require "id" for an argument?
Let entities to hold their id is redundant.
It is striking problem because I'm using firebase firestore.

Thanks

**Comment by timdeschryver** [comment]
Hi, correct me if I'm wrong but I think this is mainly done for the following reasons:

- you only define the key property once, instead of in every CRUD action
- within the sorted state adapter, it's used to sort the entities after every CRUD action
