### ISSUE TITLE
Impossible to update config name with Universal other than static string

### ISSUE THREAD

**Issue by Kunepro** [ngrx/platform#1433]
## Minimal reproduction of the bug/regression with instructions:

In a project that uses both NgRx and Universal, starting the project with server side pre-rendering, I want the Store DevTools to have a random name to identify multiple opened instance.

In the module where I import the Store DevTools I use:
```
const simpleRandomId: string   = (Math.random() * 1000).toFixed(0);

@NgModule({
	imports:   [
		StoreModule.forRoot(storeState, { metaReducers }),
		EffectsModule.forRoot(storeEffects),
		StoreDevtoolsModule.instrument({ maxAge: 50, name: simpleRandomId })
	],
	providers: storeServices,
})
```

## Expected behavior:

When opening Redux DevTools I expect the name to be a random number, instead it's the default name: "NgRx Store DevTools".

The above works with normal ng serve, I tried several approach and none worked. Only static strings work.

Anything that would allow to change the name outside a decorator, inside a class, would fix this issue and would allow for more powerful/specific naming, like using window.location.host.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
"@ngrx/store": "^6.1.0",
"@ngrx/store-devtools": "^6.1.2",
"@angular/animations": "7.0.1",
"@angular/cdk": "^7.0.2",
"@angular/common": "7.0.1",
"@angular/compiler": "7.0.1",
"@angular/core": "7.0.1",
"@angular/forms": "7.0.1",
"@angular/http": "7.0.1",
"@angular/material": "^7.0.2",
"@angular/platform-browser": "7.0.1",
"@angular/platform-browser-dynamic": "7.0.1",
"@angular/platform-server": "^7.0.1",
"@angular/router": "7.0.1",

Node v10.11.0

Tested in Chrome Canary Version 72.0.3613.0 (Official Build) 

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ X ] No

**Comment by timdeschryver** [comment]
I think this is just how the compiler works, you can wrap the config within a function to prevent this.

```ts
export function createDevToolsConfig() {
  return {
    name: (Math.random() * 1000).toFixed(0),
    logOnly: environment.production,
  };
}

// and use it as:
StoreDevtoolsModule.instrument(createDevToolsConfig)
```
