### ISSUE TITLE
preloadingStrategy: PreloadAllModules dispatches @ngrx/store/update-reducers twice

### ISSUE THREAD

**Issue by alexesca** [ngrx/platform#1438]
## Minimal reproduction of the bug/regression with instructions:

I do not have a live example, but I will try to reproduce it with my own code.

1.  Here is my module with preloading: 
`export const routes: Routes = [
    { path: 'estimator', loadChildren: 'src/app/features/estimate/estimate.module#EstimateModule'},
    { path: 'new-lead', loadChildren: 'src/app/features/leads/new-leads.module#NewLeadsModule'},
];

@NgModule({
    imports: [
        RouterModule.forRoot(routes, {preloadingStrategy: PreloadAllModules, useHash: false}),
    ],
    exports: [RouterModule],
    providers: [RouterLink]
})
export class AppRoutingModule {}`

2. Here is my feature module 
`@NgModule({
    imports: [
        CommonModule,
        StoreModule.forFeature('estimateTemplateLoader', estimateReducers.reducer),
        StoreModule.forFeature('orders', orderReducers.reducer),
        StoreModule.forFeature('purchaseOrderEstimate', purchaseOrderReducer.reducer),
        StoreModule.forFeature('purchaseOrderSections', purchaseOrderSectionReducers.reducer),
        StoreModule.forFeature('workOrderEstimate', workOrderReducer.reducer),
        StoreModule.forFeature('workOrderSections', workOrderSectionReducers.reducer),
        StoreModule.forFeature('markupEstimate', markupReducer.reducer),
        ...
        EffectsModule.forFeature([
            EstimateTemplateLoaderEffects,
            ...
        ])
    ],
    declarations: [
        EstimateTemplateLoaderComponent,
        EstimatePanelMenuComponent,
        ...
    ],
    providers: [
        EstimateTemplateLoaderService,
...
    ]
})
export class EstimateModule {

}`

## Expected behavior:

This feature state gets dispatched twice _StoreModule.forFeature('markupEstimate', markupReducer.reducer),_. As a result, all subsequent actions get ignored by this reducer. It forces me to refresh the page from a different module. 

If I change `RouterModule.forRoot(routes, {preloadingStrategy: PreloadAllModules, useHash: false})` to `RouterModule.forRoot(routes, {useHash: false}),` it works again. If I add `PreloadAllModules` it breaks again.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
Angular CLI: 6.1.5
Node: 8.12.0
OS: win32 x64
Angular: 6.1.7
## Other information:
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.5
@angular-devkit/build-angular     0.7.5
@angular-devkit/build-optimizer   0.7.5
@angular-devkit/build-webpack     0.7.5
@angular-devkit/core              0.7.5
@angular-devkit/schematics        0.7.5
@angular/cli                      6.1.5
@ngtools/webpack                  6.1.5
@schematics/angular               0.7.5
@schematics/update                0.7.5
rxjs                              6.3.2
typescript                        2.7.2
webpack                           4.9.2

**Comment by timdeschryver** [comment]
Hi, I'm a bit confused with the issue description, could you elaborate a bit more on

> This feature state gets dispatched twice StoreModule.forFeature('markupEstimate', markupReducer.reducer),. As a result, all subsequent actions get ignored by this reducer. It forces me to refresh the page from a different module.

My wild guess is:

- You're using the NgRx Redux DevTools, this causes a second dispatch of `update-reducers`
- Somewhere inside an effect an error is thrown, which will complete the observable stream. Thus also all actions are ignored.

**Comment by alexesca** [comment]
We can close this issue. I did not realize I was setting the feature state from a different module two. Preloading strategy and Ngrx work just fin together.
