### ISSUE TITLE
RFC: Adding meta reducers with injection tokens

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#1441]
This RFC is based on the plugin system of NGXS, where you can import plugins (meta reducers). An example of this is the following:

```ts
@NgModule({
  imports: [
    NgxsModule.forRoot([]),
    NgxsLoggerPluginModule.forRoot()
  ]
})
export class AppModule {}
```

This was from what I have seen, well received by the people using NGXS. 
So I was thinking of adding this into NgRx, eg:

```ts
@NgModule({
      imports: [
        StoreModule.forRoot(
          {},
          {
            metaReducers: [logReducer],
          }
        ),
      ],
      providers: [
        {
          provide: META_REDUCERS,
          useValue: storeFreeze,
          multi: true,
        },
        {
          provide: META_REDUCERS,
          useValue: localStorageSync,
          multi: true,
        },
      ],
    });
```

## Describe any alternatives/workarounds you're currently using
Currently, it's possible to provide meta reducers by using the config option within `StoreModule.forRoot()` or to provide a meta reducer by overriding the `META_REDUCERS` token.

## Other information:
This change should be backward compatible, where you could still provide the meta reducers via the config, but as well via providers.

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
I like the idea of making it easier to register third-party meta reducers. One thing to think about is keeping the order intact because of the behavior difference in import priority with SomePluginModule versus SomePluginModule.forRoot(). If you spread these meta reducers out across feature modules, it could introduce inconsistency. Meta-reducers are composed from right to left.
