### ISSUE TITLE
Getting Executed 0 of 0 ERROR.

### ISSUE THREAD

**Issue by amitcdubey** [ngrx/platform#1442]
Test case not executed 
while am using my effects in side providers and effects = TestBed.get(sampledataeffects); ng test case not getting executed and also skipping all test,in console  getting Executed 0 of 0 ERROR.

if i remove the  sampledataeffects from provider and TestBed.get(sampledataeffects) then rest all test case work .

describe('My Effects', () => {
    let actions: Observable<any>;
    let effects: sampledataeffects;
    

  beforeEach(() => {
    TestBed.configureTestingModule({
       imports: [RouterTestingModule],
        providers: [ SampleDataService,
           provideMockActions(() => actions)
           ,{
        
           }
      ],
    });
    effects = TestBed.get(sampledataeffects);// here if i remove the sampledataeffects or comment the line rest all case would executed but in this condition getting Executed 0 of 0 ERROR.
same this happening while using sampledataeffects in side providers
  });

kindly help me ..

**Comment by timdeschryver** [comment]
Support questions should be asked on [stackoverflow (with a ngrx tag)](https://stackoverflow.com/questions/tagged/ngrx) or the [gitter channel](https://gitter.im/ngrx/platform).

Also, with the provided info it's hard to know what's going on - a working reproduction would help.
