### ISSUE TITLE
UpdateEffects during prod build not behaving as intended 

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#1447]
## Minimal reproduction of the bug/regression with instructions:

The following snippet works while working in dev mode, but fails in prod mode.
This is because constructor names are mangled by the CLI during a build, thus the check `action.effects.includes('SomeEffectsClass')` would always fail.

```ts
@Effect()
init = this.actions.pipe(
  ofType(UPDATE_EFFECTS),
  filter(action => action.effects.includes('SomeEffectsClass')),
  map(action => ...)
);
```

## Expected behavior:

In order to get this working we should dispatch the `UPDATE_EFFECTS` action with an array of effect instances instead of the constructor names. This could be compared to the Angular router events. The above code snippet would become:

```ts
@Effect()
init = this.actions.pipe(
  ofType(UPDATE_EFFECTS),
  filter(action => action.effects.some(x => x instanceof SomeEffectsClass)),
  map(action => ...)
);
```

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
NgRx 7.0.0-beta.0

## I would be willing to submit a PR to fix this issue

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
The downside of this would be that the action payload would be an effect resulting in a big payload. E.g. the `AuthEffects` from the example app would have a 125K lines payload.

**Comment by timdeschryver** [comment]
Another approach would be to use something as mentioned in https://github.com/ngrx/platform/issues/683#issuecomment-370300048:

```
EffectsModule.forFeature([
  Effect1,
  Effect2
], {
  initAction: { type: 'EffectsRegistedAction' }
})
```

**Comment by timdeschryver** [comment]
Or adding a `initAction` property in the effect self, which will be used to dispatch the init action:

```
@Injectable()
export class AuthEffects {
  initAction = 'MY_INIT_ACTION';
  
  ...
}
```

**Comment by brandonroberts** [comment]
We're going into lifecycle madness with all these hooks 😂 . Are there other options are there to reasonably getting the Effects class name in prod? I'm hesitant to introduce another stream for "Effects Events" as init would be the only one.
