### ISSUE TITLE
Cannot read property 'whitelist' of undefined in new version of redux devtools

### ISSUE THREAD

**Issue by zbarbuto** [ngrx/platform#1449]
*EDIT* So it's pretty clear that the issue here lies with redux-devtools-extension - specifically https://github.com/zalmoxisus/redux-devtools-extension/issues/588 - however I'm going to leave this open for now so it's visible to anyone who happens to be looking for the error in this repo until the plugin issue gets resolved. 

All of my applications that use `@ngrx/store-devtools` currently get this error on load using the latest version of redux devtools (2.16.0):

`Cannot read property 'whitelist' of undefined`.

I'm cross-linking with the issue in redux-devtools-extension as I'm unsure if the issue lies with ngrx or with the devtools themselves:

https://github.com/zalmoxisus/redux-devtools-extension/issues/589

FTR this is using the latest version of `@ngrx`:

```json
    "@ngrx/effects": "^6.0.0",
    "@ngrx/router-store": "^6.0.0",
    "@ngrx/store": "^6.0.0",
    "@ngrx/store-devtools": "^6.0.0",
```

**Comment by jhenrich** [comment]
Getting the same error suddenly

**Comment by timurkin** [comment]
It's because of https://github.com/zalmoxisus/redux-devtools-extension/issues/587

**Comment by tirlipinpon** [comment]
No matching version found for @ngrx/store-devtools@2.1.5

**Comment by timdeschryver** [comment]
@tirlipinpon you have to downgrade the browser extension (not `@ngrx/store-devtools`).

**Comment by timurkin** [comment]
@tirlipinpon check here: https://github.com/zalmoxisus/redux-devtools-extension/issues/588#issuecomment-442311474

**Comment by MattiJarvinen-BA** [comment]
Seems like last automatic chrome update broke it, here's the changelog:

https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/2.16

- Deprecating window.devToolsExtension 220
- ~~Proper support for Blacklisted actions and dynamic maxAge~~ (removed for now as it's not allowed to be called "while reducer is executing") 316
- Improve performance for Chrome devpanel 580
- Workaround for new Chrome limit on message size 582
- Fix Chart Monitor nodes reusing 269
- Fix losing options passed from option page
- Fix actionsBlacklist/Whitelist to be also string as per documentation
- Fix infinite recursion in enhancers 556
- Fix serialization 459

( numbers are redux-devtools-extension issue numbers )

**Comment by brandonroberts** [comment]
A fix has been released https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/2.16.2
