### ISSUE TITLE
Freeze chrome

### ISSUE THREAD

**Issue by DmitriyIvanko** [ngrx/platform#1456]
## Minimal reproduction of the bug/regression with instructions:
Next code freeze chrome:
@Effect() public breakMe$ = this.actions$.pipe();
No errors, no warnings;

## Expected behavior:
No freeze;

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
@ngrx/effects": "6.1.2"
@angular/core": "7.1.0",
Google Chrome: 70.0.3538.110
## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ +] No

**Comment by brandonroberts** [comment]
This is not a bug. https://github.com/ngrx/platform/blob/master/docs/effects/api.md#non-dispatching-effects

This should be added to the website though

**Comment by timdeschryver** [comment]
@brandonroberts would it be sufficient to copy the current docs until we've rewritten the effects documentation?

**Comment by brandonroberts** [comment]
@timdeschryver Yes, just copy them into sections in the overview page and we'll separate them into a different page later.

**Comment by timdeschryver** [comment]
I'll mark this as Acceptating PRs. If it isn't picked up next week, I can move it :)

For clarifications, we want the current API effect page at  https://github.com/ngrx/platform/blob/master/docs/effects/api.md to also exist on the ngrx.io website.

To do so, copy the file to https://github.com/ngrx/platform/tree/master/projects/ngrx.io/content/guide/effects and add a new navigation item inside https://github.com/ngrx/platform/blob/master/projects/ngrx.io/content/navigation.json.

**Comment by Teamop** [comment]
Just ran into this issue, so open a PR #1468 as @timdeschryver suggested.
