### ISSUE TITLE
Store.dispatch stops working when exception is thrown 

### ISSUE THREAD

**Issue by FelipeTaiarol** [ngrx/platform#1458]
## Minimal reproduction of the bug/regression with instructions:
Hit the plus button five times while you check the console. When the counter gets to number 5 the reducers will throw an exception. After that if you dispatch an action to the store it will not be sent to the reducers and the state will not change.

https://stackblitz.com/edit/ngrx-seed-nihcey

## Expected behavior:
How can I get the store back to a consistent behavior after an exception is thrown?

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
- Angular 6 . 
- NgRx 6 . 

## I would be willing to submit a PR to fix this issue
[X] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Throwing an error makes the reducer impure, because of this I would strongly discourage the use of it inside your reducers. 

That being said if you want to catch these errors, you could create a meta-reducer that wraps your reducers inside a `try catch` block.

If you need some guidance feel free to hop into the [gitter channel](https://gitter.im/ngrx/platform).

**Comment by FelipeTaiarol** [comment]
Well, if the reducers throw an exception for whatever reason the app completely stops to work, I'm trying to find a way to avoid that. 

It would be also nice to know whether the action I just dispatched caused the reducers to throw an exception or not. 

I'll check the meta-reducers, thanks.

**Comment by FelipeTaiarol** [comment]
I found a way to achieve what I wanted using a meta-reducer and an angular service. I'll add the [stackoverflow link](https://stackoverflow.com/questions/51774582/ngrx-store-dispatch-stops-working-after-reducer-throws-exception/53703462#53703462) here for people with the same problem in the future.
