### ISSUE TITLE
Docs: Add events to top bar navigation

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1463]
## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

Lot's of people give talks at meetups and conferences. The events page is currently buried in the footer. We should put events there from anyone talking about NgRx. This change moves Events into the top bar and updates the page with a list of upcoming events.

**Comment by timdeschryver** [comment]
The navigation can be modified at https://github.com/ngrx/platform/blob/master/projects/ngrx.io/content/navigation.json.
