### ISSUE TITLE
Central @ngrx/store for self-contained web components developed using angular elements

### ISSUE THREAD

**Issue by nisargjoshi16** [ngrx/platform#1466]
We are building enterprise level application where individual product team is building their app and bundling it as web component (using angular elements). All these apps are going to be hosted in shell container. This shell container will act as central store for all applications.

How can this apps as elements can communicate with store?

**Comment by timdeschryver** [comment]
I think this isn't supported yet.

**Comment by barryajones** [comment]
@nisargjoshi16 take a look at this medium article from the guys at [nrwl.io](https://blog.nrwl.io/5-reasons-to-use-angular-elements-390c9a629f89). It doesn't get into specific code samples but hopefully will answer some questions your team has.

**Comment by timdeschryver** [comment]
See #1621

**Comment by nisargjoshi16** [comment]
Thank you @timdeschryver . Good help.

**Comment by vugar005** [comment]
Hi guys, when we import StoreModule.forRoot in element and in Shell app. The elements store will override Shell Store state. How can we achivee independent state instance? See: https://github.com/ngrx/platform/issues/3308
