### ISSUE TITLE
Can StoreDevtoolsModule export provider INITIAL_OPTIONS for better consumption?

### ISSUE THREAD

**Issue by ttestman4** [ngrx/platform#1470]
StoreDevtoolsModule need way to inject option when the entire structure is part of reusable library for large scale project.  Please find the attached sample where, logOnly option needs to flow from application to library to pass to the StoreDevtoolModule.  My understanding is INITIAL_OPTIONS provider should be exported on the lines of META_REDUCERS

Reproduction project sample:
https://github.com/ttestman4/sampleapp1/blob/develop/projects/non-functional/src/lib/root-store/root-store.module.ts  Line #40

also deployed on https://ttestman4.github.io/sampleapp1/index.html

## Describe any alternatives/workarounds you're currently using
I do not find alternative.

## Other information:
This is low priority issue but vital for large scale application design.

## If accepted, I would be willing to submit a PR for this feature
[X] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
Seems reasonable to me if you're still willing to submit a PR.

**Comment by maartentibau** [comment]
@brandonroberts @timdeschryver @alex-okrushko is there still interest to add this? If so I might be able to have a look at this.

**Comment by brandonroberts** [comment]
@maartentibau yea, its still open for contribution.

**Comment by brandonroberts** [comment]
Closing for now. Will reopen if there is interest in the future
