### ISSUE TITLE
No import option in Redux DevTools

### ISSUE THREAD

**Issue by anth-git** [ngrx/platform#1473]
I can export state but there is no button to import it.

For react-redux application it is possible to import state, but not for Angular/@ngrx: 
http://zalmoxisus.github.io/examples/counter/

![import](https://user-images.githubusercontent.com/6680915/50078187-9aa32600-01e6-11e9-8516-a9738520c46a.png)

**Comment by timdeschryver** [comment]
Have you tried refreshing the page?
I'm currently seeing the import button on the example page:

![image](https://user-images.githubusercontent.com/28659384/50079282-7eed4f00-01e9-11e9-88b8-a2f9b9b66721.png)

**Comment by anth-git** [comment]
@timdeschryver I've reinstalled Redux DevTools and and it started working…
So, please close this issue.

**Comment by timdeschryver** [comment]
Glad you got it resolved!
