### ISSUE TITLE
Docs: Move example app into docs

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1482]
Create a page for the example app describing what it is and its important parts. Move the stanadlone application into the docs example applications. From there we can generate a live StackBlitz example.

## I would be willing to submit a PR for the docs :heart:

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by gabrielgeorge** [comment]
Hey @brandonroberts, I would love to help creating PR for docs

**Comment by SerkanSipahi** [comment]
I would like to create the description for the example app. I have some questions:  
1.) Where should be the description located? Maybe here: https://github.com/ngrx/platform/blob/master/projects/example-app/README.md
2.) Do you have any branch name convention? maybe pr/description-example-app ?

**Comment by brandonroberts** [comment]
Apologies for the delay. A description of the example app and what's in it would be a good start. I don't think we'll move it from where it is now. We'll take another look at the tooling in time so see if we can include snippets of it in the guide.

1. You can create an `example-app.md` in this folder https://github.com/ngrx/platform/tree/master/projects/ngrx.io/content/guide
2. No specific convention for branch names.
3. Add a link at the bottom of the `navigation.json` here to point to it https://github.com/ngrx/platform/tree/master/projects/ngrx.io/content/guide

**Comment by SerkanSipahi** [comment]
Perfect, hopefully this weekend i will start:)

**Comment by brandonroberts** [comment]
Not going to do this after all
