### ISSUE TITLE
Subscribe only to slice of array

### ISSUE THREAD

**Issue by naordah69** [ngrx/platform#1486]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## What is the current behavior?

Using selectors and entities, trying to subscribe only the slice of the entities array, but no matter what changed in the array the selector is firing (after upsertMany) even if the selected array didn't changed.

## Expected behavior:

Option to subscribe only to a slice of the entities array

## Minimal reproduction of the problem with instructions:

Selector:
Export const SelectUserAged18 = createSelector (
SelectAllUsers,
(Users:User[])=>Users.filter(user=>user.age===18)
)

Now if i add A user aged 15 , the selector still fires.
Even if updating a 15 years old user.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
7.0

**Comment by timdeschryver** [comment]
This is the intended behavior.
The selector gets executed when one of the input parameters change, if you create/update/delete a user this selector will get executed.

See the [docs](https://ngrx.io/guide/store/selectors):
> When using the createSelector and createFeatureSelector functions @ngrx/store keeps track of the latest arguments in which your selector function was invoked. Because selectors are pure functions, the last result can be returned when the arguments match without reinvoking your selector function. This can provide performance benefits, particularly with selectors that perform expensive computation. This practice is known as memoization.
