### ISSUE TITLE
Entity custom merge operator/statergy

### ISSUE THREAD

**Issue by abdulkareemnalband** [ngrx/platform#1491]
## Describe any alternatives/workarounds you're currently using
If we want to `update` entity with nested objects , first we have to fetch and merge existing with new entity, then we have to dispatch merged object to store for update.

it is easy to handle one entity with `updateOne` , but updating  many using `updateMany` it becomes too complicated

## Solution

Provide third property `mergeFunction` along with `selectId`  and `sortComparer` in  [`createEntityAdapter`](https://ngrx.io/api/entity/createEntityAdapter) parameter

whose signature is 
```ts
(currentValue:T|undefined , newValue:T ) => T;
```
it will be used while updating/upserting a value by adaptor

## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
I think that it is unlikely to add this functionality in ngrx. 
One of the best practices in a redux application is to keep your state normalized. If its only intention is to make mutations on nested objects easier, we fully discard this best practice.

That being said, NgRx 7 introduced the `adapter.map` function, which could make this easier, e.g.:

```ts
return adapter.map(
  entity => entity.id in payload.ids ? {...entity, foo: 'bar'} : entity, 
  state
);
```

Personally, I also recommend taking a look at [immer](https://github.com/mweststrate/immer) to people who find it inconvenient to use the spread syntax, or to people who really want to have their state nested.
