### ISSUE TITLE
Consider changing MockStore<T> source type to MockState<T>

### ISSUE THREAD

**Issue by eloiqs** [ngrx/platform#1495]
## Describe any alternatives/workarounds you're currently using

Hello!  I previously had developed my own MockStore. Without going to much into details, in addition to `setState`, I also had a method which allowed me to effectively test my container's subscriptions with marbles. In this method I subscribed to a given marbles observable and attached the next, complete and error callbacks to the store source. I have since then extracted this method into its own helper which can be used to schedule marbles on any given subjet.

The problem is that the official MockStore source subject takes its type from the base Observable instead of the MockState (which it is at runtime), and this prevents me from calling next, complete and error on it without getting typescript errors. I am currently circumventing this problem by casting the source like so `store.source as MockState<AppState>`.

## If accepted, I would be willing to submit a PR for this feature

[x ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
I'm not sure how your tests look like, but I would discourage using the store's `source` property.
Instead, use the `store` stream, or take a look at [jasmine marbles](https://github.com/synapse-wireless-labs/jasmine-marbles) - which you already did since you're mentioning marbles? but why would you need to access `next`, `complete` and `error`?

Is it in fact even possible to type `source`, because `source` is typed as `any` within RxJS?

**Comment by eloiqs** [comment]
> Is it in fact even possible to type `source`, because `source` is typed as `any` within RxJS?

Yes, I could effectively just create my own MockStore class, extending the official one, just for the purpose of redeclaring source as the `MockState<T>` type. This works:
```
class MyMockStore<T> extends MockStore<T> {
	source: MockState<T>;
}
```
The store observable source is `state$: StateObservable`, which happens to be `MockState<T>` in `MockStore<T>`
See: https://github.com/ngrx/platform/blob/6b7306081be367509a9ea996a840524975f30aba/modules/store/testing/src/mock_store.ts#L13-L25
https://github.com/ngrx/platform/blob/6b7306081be367509a9ea996a840524975f30aba/modules/store/src/store.ts#L11-L20

**Comment by eloiqs** [comment]
> I'm not sure how your tests look like, but I would discourage using the store's `source` property.

Isn't using `source.next()` directly, the same as calling `setState` since source _is_ state$?
https://github.com/ngrx/platform/blob/6b7306081be367509a9ea996a840524975f30aba/modules/store/testing/src/mock_store.ts#L27-L29

**Comment by eloiqs** [comment]
> Instead, use the `store` stream, or take a look at [jasmine marbles](https://github.com/synapse-wireless-labs/jasmine-marbles) - which you already did since you're mentioning marbles? but why would you need to access `next`, `complete` and `error`?

I am using https://github.com/cartant/rxjs-marbles and jest.

I like the way testing effects and services can be done with marbles, and I'd like to test containers the same way.
```
// NB: this code hasn't been tested

const state = helpers.hot("   -^-b- a", someValues);
const expected = helpers.cold("--x- 700ms y", { x: "some-value", y: "some-other-value" });

state.subscribe({
  next: val => store.source.next(val),
  error: err => store.source.error(err),
  complete: () => store.source.complete()
});

helpers.expect(container.someObservable$).toBeObservable(expected);
```

**Comment by timdeschryver** [comment]
What about making the `state` property public?

```ts
state.subscribe({
    next: val => mockState.next(val),
    error: err => mockState.error(err),
    complete: () => mockState.complete()
});
```

**Comment by eloiqs** [comment]
@timblakely Can you clarify a little bit? Do you mean making the `MockStore`'s `state$` property public? Your example's `mockState` variable is confusing me 😄 

If I understood correctly though, then yes, I _guess_ that making the state variable property public is better than playing with the observable's source.

I went ahead and changed my tests with what I thought you meant, and the tests still pass:
```
helpers.hot('^-a-b', values).subscribe({
  next: val => (store['state$'] as MockState<AppState>).next(val),
  error: err => (store['state$'] as MockState<AppState>).error(err),
  complete: () => (store['state$'] as MockState<AppState>).complete()
});
```

(The `store['state$']` notation is needed to circumvent illegal private property access.)

**Comment by eloiqs** [comment]
@timdeschryver Yes, I think you are right. I only added these callbacks because in theory it would be possible to model these events with marbles. But, yeah, in practice I don't think the store's state observable should ever be in one of those states 😄 .

**Comment by timdeschryver** [comment]
Then I would rather keep it as it is. 
In your case: instead of the source cast, you could use `store.setState(val)`.

**Comment by brandonroberts** [comment]
I agree with keeping it as is for now.
