### ISSUE TITLE
Could not resolve @angular/core relative to [object Object].

### ISSUE THREAD

**Issue by Teebo** [ngrx/platform#1496]
## Minimal reproduction of the bug/regression with instructions:

Run Angular v7.1.4 and @ngrx/store@6.1.0
## Expected behavior:
 Running `ng build --prod` to completely build project.

Build the Angular app for production
## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
Angular v7.1.4 
@ngrx/store@6.1.0
Node v10

`
    "@angular/animations": "7.1.4",
    "@angular/common": "7.1.4",
    "@angular/compiler": "7.1.4",
    "@angular/core": "7.1.4",
    "@angular/forms": "7.1.4",
    "@angular/http": "7.1.4",
    "@angular/platform-browser": "7.1.4",
    "@angular/platform-browser-dynamic": "7.1.4",
    "@angular/platform-server": "7.1.4",
    "@angular/pwa": "^0.11.4",
    "@angular/router": "7.1.4",
    "@angular/service-worker": "7.1.4",
    "@ngrx/store": "^6.1.0",
    "@ngrx/store-devtools": "^6.1.0",
    "@nguniversal/express-engine": "^7.0.2",
    "@nguniversal/module-map-ngfactory-loader": "^7.0.2",
`
## Other information:
I am getting an error related to Ngrx it is as follows
  `ERROR in ../@ngrx/store/store.ts(10,2): Error during template compile of 'Store'
  Could not resolve @angular/core relative to [object Object]..`

This error exists only when I am building for production.

I was using the `combineReducers` function and got an error regarding the restriction of running functions in decorators which in the case is the NgModule.
I then followed a link on how to resolve the issue by [injecting reducers](https://github.com/ngrx/platform/blob/master/docs/store/api.md#injecting-reducers)
When using the reducer injection approach I started getting the error.
I have reinstalled @ngrx/store@6.1.0, tried also install @ngrx/store@7.0.0 with v7 I get the same error and other errors about not finding the `@angular/core` and `rxjs`.
I have followed the thread on `@ngrx/store` and tried the suggested solutions but nothing seems to fix the issue.
Any assistance is much appreciated.

**Comment by timdeschryver** [comment]
Hi, could you create a reproduction? Based on the description provided it's hard to tell what goes wrong.

**Comment by Teebo** [comment]
Hi @timdeschryver I tried to research on how I can build an app on StackBlitz that can be build by ng build --prod, I am not sure how to do it, is it possible? How can I do the reproduction for production build, please assist.

**Comment by timdeschryver** [comment]
A github repo would be fine, so I can build it myself.

**Comment by Teebo** [comment]
Hi @timdeschryver after some attempts on reproducing the error with no success, I have found a solution to the issue by specifying in the `tsconfig.app.json` the path to the node_modules, the build with the `--prod` now works. The change I have made is as follows in the compiler options
  ```
 "compilerOptions": {
    "baseUrl": ".",
    "paths": { "@angular/*": ["../node_modules/@angular/*"] },
   }
```
Thanks, but I just wonder if this could maybe be fixed in `@ngrx/store`? Or it is something specific to a project since I could not reproduce it when I started a clean project with `ng new repo`?

**Comment by PhilippeRoy** [comment]
Hi @Teebo,

I had a similar issue. The issue was I had two node_module folders, one at the root and one nested. As well as package.json for the project at the root and another package.json nested for the library. I removed the nested node modules and let the nested package.json inherit the nodule_modules from the root and this resolved it.

Hope this helps.

**Comment by Teebo** [comment]
@PhilippeRoy thank you, I have noted that

**Comment by javiermrz** [comment]
@PhilippeRoy I have come across your answer and I've encountered the same problem. I have been searching about how to inherit from the nested `package.json` as you suggested, but have struggled to find any info at all. Could you please share a link to some info, or briefly explain how to do this so I go on the right direction? 

Thanks in advance.
