### ISSUE TITLE
@ngrx/router-store: Tranferring router state in an universal app fails due to circular references 

### ISSUE THREAD

**Issue by tomazy** [ngrx/platform#150]
Do you guys have any suggestions how to transfer the router state from server to browser in an angular universal app? I was able to do it with @ngrx/router-store@1.2.6, but in this version you keep RouterStateSnapshot in the state and this is not transferrable - JSON.stringify throws "TypeError: Converting circular structure to JSON". 

@ngrx/store@4.0.0
@ngrx/router-store@4.0.0

node v6.10.3
npm v5.0.3
yarn v0.27.5

**Comment by brandonroberts** [comment]
Related to #97
