### ISSUE TITLE
ofType not supporting verion 7

### ISSUE THREAD

**Issue by amitcdubey** [ngrx/platform#1507]
ngrx/effects verion 7 not supporting ofType !!!!!

**Comment by tja4472** [comment]
This has been removed.

https://github.com/ngrx/platform/blob/master/CHANGELOG.md#700-beta0-2018-11-03

> effects: Removes .ofType method on Actions. Instead use the provided 'ofType' rxjs operator.
BEFORE:

>this.actions.ofType('INCREMENT')
AFTER:

>import { ofType } from '@ngrx/store';
...
this.action.pipe(ofType('INCREMENT'))

**Comment by timdeschryver** [comment]
Like @tja4472 said, this is removed in NgRx 7.

Would you mind trying out [ngrx-tslint](https://github.com/timdeschryver/ngrx-tslint) and give some feedback? Be sure that you've committed your changes before running the command.

This is a migration tool that should update your `ofType` methods, I just haven't had the chance to test it out on a real project 😅.
