### ISSUE TITLE
Subscribe returns Object not AppState

### ISSUE THREAD

**Issue by smatthews1999** [ngrx/platform#151]
Having a heck of a time converting my app to the new version.... I have a simple reducer to return AppState type.

```
export function StateReducer
    (state: AppState = initialState, action: Action):AppState {
    let newState = Object.assign({}, state);
    switch (action.type) {
        case SET_LOGIN: {
            let auth = (<loginAction>action).payload;
            newState.authenticated = true;
            return newState;
        }
        default: {
            return state; // unmodified
        }
    }

```
I have it being registered in @NgModule as so...
```
 imports: [
    BrowserModule,
    FormsModule,
    StoreModule.forRoot({StateReducer}),
  ],
```
In my components I am subscribing as so....
```
 constructor(private store: Store<AppState>,) {
    store.subscribe((s) => {      
      this.appState = s;
    });
  }
```
What is puzzling is that when I recieve the state it is in the form of an Object, not my AppState type.
![image](https://user-images.githubusercontent.com/562964/28482036-9ddc4014-6e34-11e7-9f32-b555e5c6d279.png)
Can someone explain what I am doing wrong here?

**Comment by littleStudent** [comment]
I guess you need to use it like this?
```Javascript
StoreModule.forRoot({ state: StateReducer })
```

**Comment by loiane** [comment]
You might want to create a constant with all your reducers in the app level (or as @littleStudent demonstrated if you only have the StateReducer in the app root level):

```
export const reducers = {
  routerReducer: routerReducer,
  app: StateReducer
  // other app level reducers
};
```
In your module:

```StoreModule.forRoot(reducers)```

In your component, you need to select part of the state you are interested in. For example:

```store.select('app').subscribe(info => // do something);```

or 

```
store.select('app')
.map((state: AppState) => state.authenticated)
.subscribe(authenticated => // do something);
```

**Comment by Kaffiend** [comment]
To expand on what @loiane mentioned above you can utilize the `ActionReducerMap`
*Root State*
```
import { ActionReducerMap } from '@ngrx/store';

export interface AppState {
  clientConfig: fromClientConfig.ClientConfigState;
  router: fromRouter.RouterReducerState;
  home: fromHome.HomeState;
  user: fromLogin.LoginState;
}

export const reducers: ActionReducerMap<AppState> = {
  clientConfig: fromClientConfig.clientConfigReducer,
  router: fromRouter.routerReducer,
  home: fromHome.homeReducer,
  user: fromLogin.loginReducer
};
```
and compose your slices of state
*Root Reducer*
```
export const developmentReducerFactory: ActionReducerFactory<AppState, Action> = compose(logger, combineReducers);
export const productionReducerFactory: ActionReducerFactory<AppState, Action> = undefined;

export const selectUser = createFeatureSelector<fromLogin.LoginState>('user');
export const selectUserLoggedIn = createSelector(selectUser, (state: fromLogin.LoginState) => state.loggedIn);

export const selectRouter = createFeatureSelector<fromRouter.RouterReducerState>('router');
export const selectRouterUrl = createSelector(selectRouter, (state) => state.state.url);

export const selectClientConfig = (state: AppState) => state.clientConfig;

export function rootReducer(state: any, action: any) {
  if (ENV !== 'development') {
    return productionReducerFactory(state, action);
  } else {
    return developmentReducerFactory(state, action);
  }
```
create selectors for the slices of state you need to subscribe to.
you can use the `reducerFactory` in your module as well
*module*
```
StoreModule.forRoot(reducers, {
      reducerFactory: rootReducer
    }),
```
Then you can subscribe to them in your components like so
```

    constructor(
        private store: Store<LoginState>,
        private loginSocket: LoginSocketService
    ) {
        this.baseUserState = store.select(fromRoot.selectUser);
    }
```

**Comment by smatthews1999** [comment]
@littleStudent 
Unfortunately doing that does nothing but give the state object a new name....
![image](https://user-images.githubusercontent.com/562964/28490475-eaaf01a0-6ea8-11e7-826b-928866d504fe.png)

@loiane 
I only have one reducer because that's all I need.  In any case when I try to "select" a reducer I get a compile error.
![image](https://user-images.githubusercontent.com/562964/28490568-3748c08a-6eab-11e7-93a8-9c8deef2c264.png)

This compile error also exists in this form....
![image](https://user-images.githubusercontent.com/562964/28490587-cf2e3e02-6eab-11e7-8ed7-4cda31ccb509.png)

@Kaffiend 
I appreciate the suggestions, and eventually I will try to learn those additional features, but right now I am struggling with basic functionality that used to work just awesome.  At this point I am probably going to roll back to 2.x as it served my needs.  Either that or find another redux store.  I am afraid this product has become exponentially more complicated, and sacrificed basic functionality, and the simple use case scenario.

**Comment by robwormald** [comment]
@smatthews1999 this is works as intended - generally `AppState` is defined as an interface, which has no runtime representation - they are designed to describe the *shape* of the object returned. This doesn't have anything to do with NgRx specifically - unless you explicitly *instantiate* an instance of the class and return it, you're dealing with plain old objects everywhere. 

Example in the typescript playground of this - notice that the interface drops away in the compiled version. http://www.typescriptlang.org/play/index.html#src=class%20FooType%20%7B%0D%0A%20%20%20%20foo%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20IFoo%20%7B%0D%0A%20%20%20%20foo%3A%20string%3B%0D%0A%7D%0D%0A%0D%0A%2F%2Finterface%20usage%0D%0Alet%20a%3A%20IFoo%20%3D%20%7B%20foo%3A%20'bar'%20%7D%0D%0A%0D%0Aa.foo%20%3D%20'blaz'%0D%0Aa.bar%20%2F%2Ferror%2C%20not%20the%20correct%20shape%0D%0A%0D%0A%2F%2Fclass%20usage%20-%20must%20be%20instantiated!%0D%0Alet%20b%20%3D%20new%20FooType()%3B%0D%0Ab.foo%20%3D%20'blaz'

**Comment by bsricharan** [comment]
i think we spoke more on this issue than the actual problem is 
 imports: [
    BrowserModule,
    FormsModule,
    StoreModule.forRoot({StateReducer}),
  ],

remove the {} around the state reducer that will remove the issue just do StoreModule.forRoot(StateReducer),

**Comment by timdeschryver** [comment]
@vikasmanghani using `any` is the way to go for now.
We're tracking the issue in https://github.com/ngrx/platform/issues/951.
