### ISSUE TITLE
Custom Serializer params with nested routes

### ISSUE THREAD

**Issue by AlejandroPeralTaboada** [ngrx/platform#1510]
## Other information:

Using the NgRx Router-Store with the provided custom serializer in the doc:
https://ngrx.io/guide/router-store/configuration#custom-router-state-serializer

I realised the url params are only saved for the last route.

Given this router configuration:

```
const routes: Routes = [
	{
		path: ':id',
		component: ParentComponent,
		children: [
			{ path: 'edit', component: EditComponent }
		]
	}
];
```
If EditComponent does something like
```
export class EditComponent implements OnInit {
    editItem$: Observable<EditItem>;
    constructor(private itemService: ItemService,private store: Store<State>) {}
    
    ngOnInit() {
	this.editItem$ = this.store.select(getUrlParams).pipe(
            filter(params => params.id),
	    switchMap(params =>this.itemService.getItem(params.id))
	);
    }
}
```

Where getUrlParams is

```
export const selectRouterState = createFeatureSelector<fromRouter.RouterReducerState<RouterStateUrl>>('routerReducer');
export const getUrlParams = createSelector(	selectRouterState,	s => s.state.params);
```
It will never reach the switch map because the serializer is taking only the params from the child route witch is  just 'edit' therefore the variable params is empty

Changing the CustomSerializer.ts to this I think solves the problem 

```
import { Params, RouterStateSnapshot, ActivatedRouteSnapshot } from '@angular/router';
import { RouterStateSerializer } from '@ngrx/router-store';
 
export interface RouterStateUrl {
  url: string;
  params: Params;
  queryParams: Params;
}
 
export class CustomSerializer implements fromRouter.RouterStateSerializer<RouterStateUrl> {	 
    serialize(routerState: RouterStateSnapshot): RouterStateUrl {
        const { url } = routerState;
        const { queryParams } = routerState.root;
        let state: ActivatedRouteSnapshot = routerState.root;
        let params = {...state.params};
        while (state.firstChild) {
            state = state.firstChild;
            params = { ...params, ...state.params };
        }
	return { url, queryParams, params };
    }
}
```
The change is Inside the while loop, it adds the founded params on each children to the params variable.
Would you mind checking if I'm right about it?

Thanks
## I would be willing to submit a PR for the docs :heart:

[ X ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
The snippet seems right.

I think you have to watch out when you use the same parameter names in a URL, if Angular supports this. I haven't tried this but I assume the last would override the first ones e.g. `customers/:id/orders/:id` where the `orderId` would override the `customerId`.
