### ISSUE TITLE
.next is not working 

### ISSUE THREAD

**Issue by amitcdubey** [ngrx/platform#1514]
.next is not working after updating ngrx and angular

**Comment by timdeschryver** [comment]
Some more context is needed here.
- What's the previous and current version
- Where are you calling `next`?
- What are you doing?
- ...

**Comment by amitcdubey** [comment]
am working on effects unit test case while am using 


it('should work also', () => {
    actions = new ReplaySubject(1);
 
    actions.next(SomeAction);
 
    effects.someSource$.subscribe(result => {
      expect(result).toEqual(AnotherAction);
    });
  });
});

here .next is not working ,

is there any other way to write this ?

**Comment by timdeschryver** [comment]
This is explained in our [docs](https://ngrx.io/guide/effects/testing#testing).

**Comment by amitcdubey** [comment]
as per doc while am creating effects test am getting below error 

Property 'next' does not exist on type 'Observable<any>'.
Could you please let me know why this is happening .

my Angular version is 7 and also ngrx 7

**Comment by EnricoVogt** [comment]
As I understand it, you have the possibility to do the tests via jasmine-marbles ( it('should work' ) or manually ( it('should work also' ). it seems like you prefer the manual way, then you have to change the Type of the action variable in your test from `let actions: Observable<any>` to `let actions: ReplaySubject<any>`. Please correct me if im wrong.

**Comment by amitcdubey** [comment]
am doing this by jasmine-marbles only but its not working ,getting below error 
Property 'next' does not exist on type 'Observable'.

am not understanding the explanation of docs.below code as per doc 

  it('should work also', () => {
    actions = new ReplaySubject(1);
 
    actions.next(SomeAction);
 
    effects.someSource$.subscribe(result => {
      expect(result).toEqual(AnotherAction);
    });
  });
});

but while am using am getting error !!!!!

**Comment by timdeschryver** [comment]
You'll have to cast `actions` as a `ReplaySubject`


```ts
(actions as ReplaySubject<Action>).next(SomeAction);
```
