### ISSUE TITLE
Schematics: add common success/failure actions to feature schematic

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1529]
When a feature schematic is run, we scaffold out `[Something] Load Something`. In lots of cases you end up with, `[Something] Load Something`, `[Something] Load Something Success`, `[Something] Load Something Failure`.

We should provide some type of option that adds the success/error actions to the action/reducer/effect when generating a feature. The piece that's unknown is what to put in the *Map for the effect.

```ts
@Injectable()
export class SomethingEffect {
  @Effect()
  this.loadSomething$ = this.actions$.pipe(
    oftype('SomeAction'),
    (concat/exhaust/blah)Map(() => 
      (/** some observable to be replaced here */).pipe(
        map(() => new LoadSomethingSuccess()),
        catchError(() => of(new LoadSomethingFailure))
      )
    )
  )
}
```

**Comment by wesleygrimes** [comment]
If you're accepting PRs, I will give this one a shot.
