### ISSUE TITLE
Content overflows in docs home page in mobile screen

### ISSUE THREAD

**Issue by omarperezm** [ngrx/platform#1536]
It's just a little style-related issue and I'm sure it doesn't happen in every mobile screen size/resolution. In my case, I'm experiencing this behaviour in a 5 inches screen with a 960 x 540 pixels resolution. Some of the text overflows to the right. This is only while the viewport is vertically, not in landscape.

**Comment by timdeschryver** [comment]
Hi, I think you've created the issue in the wrong repo, that's why I'm closing this issue.
