### ISSUE TITLE
Schematics: Add ng-add support with prompt for making our schematics default

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1538]
`ng add @ngrx/schematics`

Requirements:

- [ ] Should prompt the user to set `@ngrx/schematics` as the default collection. If the user accepts, it should do the equivalent of https://ngrx.io/guide/schematics#default-schematics-collection
- [ ] Docs
- [ ] Tests

**Comment by itayod** [comment]
@brandonroberts if you'r accepting pr I can give it a try :)

**Comment by schuchard** [comment]
Hey @brandonroberts, we're taking a look at this as well at Briebug. Curious how you test schematics in the repo outside of unit tests? Do you have any patterns for locally testing? I like to use a sandbox approach to develop and test with https://www.kevinschuchard.com/blog/2018-11-20-schematic-sandbox/

Thanks

**Comment by timdeschryver** [comment]
I haven't used the sandbox approach but it seems nice!
I've used [verdaccio](https://github.com/verdaccio/verdaccio) in the past to host a private npm registry.

**Comment by timdeschryver** [comment]
To avoid working on this issue with multiple devs simultaneously, perhaps it would be better to assign someone to this issue?

**Comment by schuchard** [comment]
I agree. @itayod claimed it first so I'm happy to step back or provided assistance if needed.

**Comment by brandonroberts** [comment]
@schuchard its pretty manual right now. I've mostly used the nightly builds and test projects to validate, but something more automated such as sandboxing would be helpful. Its kinda meta, but I think a standalone library to do integration testing would be nice. This is similar to what you're doing already.

You use a clean CLI project
Run your schematic against it
Use the schematics CLI to read files from your CLI project and validate it was applied correctly.
