### ISSUE TITLE
Action types, too many references.

### ISSUE THREAD

**Issue by argygkou** [ngrx/platform#1540]
hi, I'm building a large application for my company with many actions etc. After a while actions types have too many references resulting VS code to struggle fetching them quickly and to stuck every time I open *.action.ts file. Here is an example

![test-action](https://user-images.githubusercontent.com/22211468/52214932-9bc60a80-289b-11e9-8204-beae69221496.jpg)

Is this my fault, or it has something to do with vscode, or typescript, or ngrx???

**Comment by timdeschryver** [comment]
This isn't no one's fault, it refers to the `type` property from the `Action` interface.
In your application, this `type` property is used 1530 times.
