### ISSUE TITLE
RFC: Add CorrelationId Utilities to ngrx/effects

### ISSUE THREAD

**Issue by dummdidumm** [ngrx/platform#1541]
Currently, `@ngrx/effects` does not have any support for the correlation id pattern. It would be great if there were utilities that help streamline the code.

## Scenario

Inside our app, it's often necessary to dispatch an action, wait for another action in response and then continue with follow-up logic.

Example:
1. Dispatch actionA
2. Wait for actionB
3. Continue and decide what to do based on actionB

Because our app needs to rely on generic stores, it's not feasible to implement each flow with special actions which can be easily filtered for, so we have correlationIds. This is a known pattern, but we have to implement the things around it on our own.

## Proposed solution

It would be great if there utilities inside the `@ngrx/effects` package:

#### A method that makes it easy adding a correlationId to an action

```ts
const myAction = {type: 'MY_ACTION'};
const actionWithCorrelationId = withCorrelationId(myAction);
// => {type: 'MY_ACTION', _ngrx_correlation_id: 'some correlation id'}
```

#### A custom pipe operator that waits for correlated actions

```ts
filterActionsWithCorrelationId(actionWithCorrelationId: {type: string; _ngrx_correlation_id: string}, actionTypesToWaitFor: string[]});
```

#### An additional @Effect-property that adds correlationId of incoming action to outcoming actions

```ts
@Effect({withCorrelationId: true})
someEffect$ = this.actions$.pipe(
   filter(action => action.type === 'SOME_ACTION'), // action has _ngrx_correlationId="abc" set
   map(() => ({type: 'SOME_OUTGOING_ACTION'})) // outgoing action also has _ngrx_correlationId="abc" set
);
```

Alternatively, you could also decide to always add the correlationId, so there is no property required.

Edit: I'm not sure this is possible to implement, the effects library somehow has to know not only what comes out of the stream but also what goes into it.

#### Usage of all combined would be something like this:
```ts
@Effect()
doSth$ = this.actions$.pipe(
   filter(action => action.type === 'ACTION_A'),
   switchMap(() => {
      const outgoingAction = withCorrelationId({type: 'SOME_ACTION'});
      const responseAction$ = this.actions$.pipe(
         filterActionsWithCorrelationId(outgoingAction, ['SOME_RESPONSE_ACTION']),
         map(responseAction => {
               // responseAction is SOME_RESPONSE_ACTION
        })
     );

     return merge(of(outgoingAction), responseAction$));
  })
);

@Effect({withCorrelationId: true})
someEffect$ = this.actions$.pipe(
   filter(action => action.type === 'SOME_ACTION'),
   map(() => ({type: 'SOME_RESPONSE_ACTION'}))
);
```

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
Closing as we won't be adding this to effects

**Comment by montella1507** [comment]
Why? IT IS Common usecase.

**Comment by bradacina** [comment]
@brandonroberts  It would be nice to know if you would be adding this to a separate library? or what's the plan around it?

**Comment by montella1507** [comment]
in my opinion, you should have been able to create this functionality with something like :

// custom action creator
createActionWithCorrelationId(...) {  return createAction(.../add props and corrId/.. } 

// custom effect creator
createCorrelatedEffect() {  .. it has to take correlatino ID from input to observable stream and add it to output actions.. }

submitData$ = createCorrelatedEffect(() =>
        this.actions$.pipe(
             ofType(actionCreatedByActionWithCorrelationIDCreator),
             ....,
           // effect has to take this output (wrap observable) and add correlation ID.
            map(x=> OutputActionWithCorrelationId())
        ));

**Comment by timdeschryver** [comment]
FWIW, I implemented correlation at [ngrx-etc](https://github.com/timdeschryver/ngrx-etc/blob/master/tests/correlate/correlate-effect.spec.ts).
You can see if this fits your needs, be aware that this is untested code (that's why it isn't documented)

**Comment by montella1507** [comment]
> FWIW, I implemented correlation at [ngrx-etc](https://github.com/timdeschryver/ngrx-etc/blob/master/tests/correlate/correlate-effect.spec.ts).
> You can see if this fits your needs, be aware that this is untested code (that's why it isn't documented)

Unfortunately action created with this Is not handled correctly in standard effect :/ not catched.
