### ISSUE TITLE
Schematics: add support for generating new workspace/application/lib with initial setup

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1544]
Make it easier to scaffold out a new workspace/project/library

Generates a new workspace/application/library
Includes all ngrx dependencies
Sets up Store/Effects/Store Devtools/Router Store

Also supports generating a new application with the above. Should be broken down into new schematics.

`workspace` - new workspace from scratch (May have to include global install of `@ngrx/schematics`)

```
ng new my-ngrx-project --collection=@ngrx/schematics
```

`application` - adding a new application project

```
ng generate @ngrx/schematics:application my-ngrx-app
```

`lib` - adding a new library that includes NgRx

```
ng generate @ngrx/schematics:library my-ngrx-lib
```

**Comment by santoshyadav198613** [comment]
Hi @brandonroberts ,

Can i help here, i am already learning schematics, will be helpful for me.

**Comment by brandonroberts** [comment]
I think we'll table this for now
