### ISSUE TITLE
ERROR TypeError: Cannot read property 'firstname' of undefined

### ISSUE THREAD

**Issue by kammanageswararao** [ngrx/platform#1547]
Component.ts:

  public nagesh($scope) {
    const employees = [{ firstname: 'kamma', lastname: 'nageswararao', gender: 'Male', salary: 57000 },
    { firstname: 'ram', lastname: 'Daniel', gender: 'Male', salary: 87000 },
    { firstname: 'Arun', name: 'A', gender: 'Male', salary: 95000 },
    {
      firstname: 'kumar', lastname: 'balara', gender: 'Male', salary: 95000
    }
    ];
    $scope.employees = employees;

  }

component.html:

<div id="id1" style="width: 300px; height: 200px;">
  <table>
    <thead>
      <tr>
        <th>firstName</th>
        <th>lastname</th>
        <th>gender</th>
        <th>salary</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>kamma</td>
        <td>kamma</td>
        <td>kamma</td>
        <td>kamma</td>
      </tr>
      <tr ng-repeat="let employee of Employees | async">
    
        <td>{{employee.firstname}}</td>
        <td>{{employee.lastname}}</td>
        <td>{{employee.gender}}</td>
        <td>{{employee.salary}}</td>
      </tr>
    </tbody>
  </table>
</div>

Problem:-
ERROR TypeError: Cannot read property 'firstname' of undefined
 at Object.eval [as updateRenderer] (EnterknowntvlrnumberComponent.html:35

**Comment by timdeschryver** [comment]
Hi, I'm going to close this issue because I think this isn't NgRx related.
It seems more like an AngularJS question, please feel free to re-open if I'm wrong.

**Comment by Oscar-Everest** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/63425337/81184586-76e1ab00-8fa8-11ea-8ac0-f23c8a6c52aa.png)
![Screenshot (4)](https://user-images.githubusercontent.com/63425337/81184596-79440500-8fa8-11ea-9f79-4bb498e7fec0.png)


i have this error message while creating firebase authentication
