### ISSUE TITLE
ngrx.io add gitter.im chat addon?

### ISSUE THREAD

**Issue by MattiJarvinen** [ngrx/platform#1548]
[Scala exercises](https://www.scala-exercises.org/std_lib/asserts) got this nice chat addon in their study material, I was wondering if adding similar functionality to the documentation site would add any value?

![image](https://user-images.githubusercontent.com/12794435/52533634-3b254a80-2d3f-11e9-82cf-bcdb74d82b02.png)

I do get that the gitter link is in the footer but maybe it should be more visible throughout the site.

Added link to the https://sidecar.gitter.im/

**Comment by brandonroberts** [comment]
Maybe. I don't know how many people from the chatroom would access it from the docs page as opposed to just having a "Chat" link in the top bar.

**Comment by brandonroberts** [comment]
Closing this for now.
