### ISSUE TITLE
.pipe is not a function

### ISSUE THREAD

**Issue by ngohungphuc** [ngrx/platform#1549]
I have this error
>  _this.userInfoService.getUserInfo(...).pipe is not a function

What I trying to achieved is I 2 page 1 user list page 1 user detail. When load list users save list of user in store then if I go to detail page I don't need to make api call if user list already exist in store else I will make API call

Service
```typescript
 getUserInfo(userId: string): Observable<any> {
        let val;
        this.userListStore.select(getUsers).subscribe(res => {
            res.length > 0
                ? (val = res.find(u => u.id === userId))
                : (val = this.http
                      .get(`api/users/${userId}`)
                      .map(resp => resp.json()));
        });

        return val;
    }
```

Effect 
```typescript
@Effect()
    getUserInfo$: Observable<Action> = this.actions$.pipe(
        ofType<userInfoAction.GetUser>(
            userInfoAction.UserInfoActionTypes.GetUser
        ),
        mergeMap(action =>
            this.userInfoService.getUserInfo(action.payload).pipe(
                // If successful, dispatch success action with result
                map(
                    (userInfo: IUser) =>
                        new userInfoAction.GetUserSuccess(userInfo)
                ),
                // If request fails, dispatch failed action
                catchError(() =>
                    of({ type: userInfoAction.UserInfoActionTypes.Fail })
                )
            )
        )
    );
```
I will get error at  this.userInfoService.getUserInfo(action.payload).pipe(

Is there anything I have done wrong ?
Thanks you

**Comment by timdeschryver** [comment]
The service should return an observable (in most of the cases the http request stream).

See the [example-app](https://github.com/ngrx/platform/blob/master/projects/example-app/src/app/core/services/google-books.service.ts#L17) for an example.

**Comment by ngohungphuc** [comment]
Hi @timdeschryver so what you suggest about scenario I need to get data from the store. That it's not a http request 
Thank you

**Comment by timdeschryver** [comment]
I would not integrate the store into services, imho they should just make requests to a web api.

For your case I would prefer to solve it via ngrx/effects - see [Start using ngrx/effects for this](https://blog.angularindepth.com/start-using-ngrx-effects-for-this-e0b2bd9da165), there should be an example in there.

**Comment by zoechi** [comment]
I run into this error because I used `*ngrxLet="foo$ | async as foo" but `| async` is implied already with `ngrxLet`
