### ISSUE TITLE
Build: add package for ngrx/data

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1554]
Create initial package and setup to produce nightly builds of `@ngrx/data` from John Papa and Ward Bell as an official package.

Source: https://github.com/johnpapa/angular-ngrx-data

Checklist

- [ ] Add build setup to modules folder
- [x] Setup github repo for night builds
- [ ] Create doc for installation and usage

**Comment by wardbell** [comment]
Let's DO IT

**Comment by johnpapa** [comment]
let's get this party started!

**Comment by johnpapa** [comment]
Is there an update on this or estimated time to be merged?

**Comment by timdeschryver** [comment]
I had some time and started the migration at https://github.com/ngrx/platform/tree/ngrx-data.
Seems like the CI got some problems while running the tests 😅

**Comment by mfrieling** [comment]
How long will it probably take after the release of Angular 8 until this will be solved and ngrx-data 8 be released?

**Comment by brandonroberts** [comment]
`@ngrx/data` will be released as part of version 8. The plan is to release the first beta soon so developers can test it out installed as a primary package.

**Comment by kichnan** [comment]
Can't wait for this to be available! I've been using [angular-ngrx-data](https://github.com/johnpapa/angular-ngrx-data) (in Production!) for more than 8 months now. Saves a LOT of boiler plate code and brings a lot of consistency in development practices too. A few issues/hurdles here n there but overall, pretty AWESOME!

Thank you @johnpapa and @wardbell for this, again!
