### ISSUE TITLE
Example: add cypress testing for example app

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1556]
We've already talked about this, but had no official issue to track.

**Comment by timdeschryver** [comment]
Current status: Cypress tests are available at [/wip/example-cypress](https://github.com/ngrx/platform/tree/wip/example-cypress) but the bazel build is failing because the build files aren't formatted - https://circleci.com/gh/ngrx/platform/5064.

**Comment by brandonroberts** [comment]
I'll take another look over the weekend

**Comment by brandonroberts** [comment]
You should be unblocked now. I rebased the branch on master, added a fix, and force pushed the changes.
