### ISSUE TITLE
Single createSelector function doesn't get state passed in.

### ISSUE THREAD

**Issue by michalvankodev** [ngrx/platform#1558]
Hello,
This took me some time to find but I've ran into this issue.
When I have only simple selector
```
const somethingSelector = createSelector(
  (state: StoreState) => {
    return {
      state.something
    };
  }
);
```
It will not get the state passed in.

I've found that this PR: #1515 has introduced this issue.
Not very sure why the function is not called with state as an argument but it broke my application immediately.

## Expected behavior:
Nothing should be broken by a not-breaking release.
Use of createSelector without any previous selectors is broken.

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ X] No. I think reverting the previous PR should be done. And a proper fix for the issue it was intented to fix

**Comment by timdeschryver** [comment]
I think this was an undesired outcome, made by implementing selector with props (more specifically to allow the [createSelector with only a props selector](https://github.com/ngrx/platform/blob/master/modules/store/spec/selector.spec.ts#L242).
If you take a look at an example from v6.0.x, the state within the selector is also 
`undefined` - [repro](https://stackblitz.com/edit/ngrx-seed-za3pw9?file=src%2Fapp%2Freducers%2Findex.ts).

The PR #1515 reverts this change, but was indeed a breaking change.

**Comment by timdeschryver** [comment]
With the knowledge gained, I think it wasn't a great idea to allow these selectors with props working directly with the projection function without the need of a selector.

Concrete this means that the following won't be possible anymore

```ts
const getTodosById = createSelector(
  (state: TodoAppSchema, id: number) => {
    return state.todos.find(p => p.id === id);
  }
);
```

But would need to be written as:
```ts
const getTodosById = createSelector(
  (state: TodoAppSchema) => state,
  (state: TodoAppSchema, id: number) => {
    return state.todos.find(p => p.id === id);
  }
);

// or 

const getTodosById = createSelector(
  (state: TodoAppSchema) => state.todos,
  (todos: Todo[], id: number) => {
    return todos.find(p => p.id === id);
  }
);

```

This would also be in line with the reduxjs/reselect library which has as [API](https://github.com/reduxjs/reselect#api)
`createSelector(...inputSelectors | [inputSelectors], resultFunc)`.

This would be a **breaking change** that we could add for v8. 

Would this be OK for you @brandonroberts ?

**Comment by brandonroberts** [comment]
@timdeschryver I'm fine with the breaking change to make the usage more consistent.

**Comment by timdeschryver** [comment]
👍 I will submit a PR
