### ISSUE TITLE
ngrx/effects 7.2.0 does not work with rxjs-compat

### ISSUE THREAD

**Issue by dolanmiu** [ngrx/platform#1562]
When I upgraded my version of ngrx/effects to `7.2.0`, it broke my project.

I use rxjs-compat to use the traditional way of using observables

Namely the 'ofType' broke:

```
 Property 'ofType' does not exist on type 'Actions<Action>'.
```
<img width="889" alt="screenshot 2019-02-17 at 19 42 16" src="https://user-images.githubusercontent.com/2917613/52918192-5fa79680-32ec-11e9-8e0b-f690491f20f9.png">

**Comment by brandonroberts** [comment]
See the [V7 migration guide](https://ngrx.io/guide/migration/v7) about the removal of the ofType instance operator.

**Comment by dolanmiu** [comment]
I use the previous way of using obervables with rxjs, not the `pipe` way e.g.

```
this.source$.map().filter().do() etc.
```

`rxjs` has kindly made an `rxjs-compat` library to address this issue.

Will ngrx introduce a `ngrx-compat` in future?

**Comment by tallmorgan** [comment]
A monkey patch might look like:
```typescript
Actions.prototype.ofType = function () {
    return this.pipe(ofType(...arguments));
}
```
Of course, actually updating each instance is a better solution for typing and tree shaking reasons.

**Comment by dolanmiu** [comment]
@tallmorgan Yes tree-shaking would be a bonus, but I am developing an electron desktop app, and tree-shaking and bundle size isn't really a concern. 

Dot-chaining is far superior in terms of readability and syntactical conciseness. I really want `ngrx-compat` to be a real thing
