### ISSUE TITLE
Schematics: implement E2E testing

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1563]
Original discussion: https://github.com/ngrx/platform/issues/1538#issuecomment-463356946

We don't currently have an automated way to "sandbox" test our schematics. This effort would create an integration test suite that installs and runs our schematics against a clean Angular project to verify they are applied correctly.

**Comment by brandonroberts** [comment]
cc @schuchard

**Comment by schuchard** [comment]
I'll put some time into this when I can. I think having a sandbox to test and develop against would be very helpful.

**Comment by sumitparakh** [comment]
Hi @brandonroberts . Is this issue still relevant? I would like to work on it.

**Comment by schuchard** [comment]
Interesting timing, i just published a [monorepo](https://github.com/schuchard/ng-tools) that has some sandbox testing. I still haven't found a clean solution to testing multiple schematics across multiple packages that seems maintainable. So far it's just a collection of shell scripts. Maybe that's OK? Would be nice to have some sort of config file that orchestrates everything together but maybe a shell script with the test configuration is sufficient?

**Comment by brandonroberts** [comment]
Closing this one for now
