### ISSUE TITLE
Schematics: use defaultProject if project is not provided

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1564]
Currently we use the first project in the list if the project is not provided.

https://github.com/ngrx/platform/blob/master/modules/schematics-core/utility/project.ts#L16

Instead, we should use the workspace `defaultProject` property as a first choice, then fallback to the first project.

**Comment by santoshyadav198613** [comment]
Hey @brandonroberts ,

should i take this as well, just opened the PR for earlier changes.

**Comment by timdeschryver** [comment]
Sure, go for it @santoshyadav198613 .
But as Brandon already has mentioned, submit them as separate PRs.

**Comment by santoshyadav198613** [comment]
HI @timdeschryver and @brandonroberts ,

Can you let me know how i can run code coverage on my local i am using windows, every time i run i get

----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                |
----------|----------|----------|----------|----------|----------------|

**Comment by timdeschryver** [comment]
I'm also on a Windows, and I do see the coverage with `yarn test`.
Which script are you running?

**Comment by santoshyadav198613** [comment]
> I'm also on a Windows, and I do see the coverage with `yarn test`.
> Which script are you running?

I am using the same command , i am getting below message when i run it, does this pending step has something to do with it?

Pending:

1) integration spec should support preventing navigation
  Temporarily disabled with xit

407 specs, 0 failures, 1 pending spec
Finished in 108.42 seconds

----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                |
----------|----------|----------|----------|----------|----------------|
