### ISSUE TITLE
Schematics: rename template files to avoid compilation

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1566]
Our schematics template files end with `.ts`, which you have to explicitly ignore or they will be compiled.
Renaming them to `.ts.template` follows the convention used in the Angular schematics.

For reference: https://github.com/angular/angular-bazel-example/issues/286

**Comment by santoshyadav198613** [comment]
Can i take this.

**Comment by timdeschryver** [comment]
You sure can @santoshyadav198613 !

**Comment by santoshyadav198613** [comment]
Hi @timdeschryver ,

I can see some test cases referring to /src/app/foo/foo.actions.ts but such file does not exists in code, due to which some tests are getting failed, can you guide me to if i am missing something.

**Comment by santoshyadav198613** [comment]
Hi @timdeschryver / @brandonroberts ,
Can you review once, all check are success, i have used the new method to handle the templates.
