### ISSUE TITLE
Entity: Loosen type restrictions on selectId and sortComparer

### ISSUE THREAD

**Issue by karptonite** [ngrx/platform#1568]
The types  for `createEntityAdapter` are currently defined as
```typescript
export function createEntityAdapter<T>(
  options: {
    selectId?: IdSelector<T>;
    sortComparer?: false | Comparer<T>;
  } = {}
): EntityAdapter<T>
```

This is somewhat restrictive for the types on selectId and sortComparer. It means that if you have something like:
```typescript
interface CompoundId {
  type: string;
  id: string;
}
interface Foo extends CompoundId {
  // ...
}
interface Bar extends CompoundId {
  // ...
}
```
where CompoundId requires both type and id to identify an item, you can't (I think) make a general `selectId` function that works on any type that extends `CompoundId`. You'd need a separate `selectId` function for Foo, Bar, etc.

I believe we could fix this by tweaking the type in createEntityAdapter. it could look, instead, like:
```typescript
export function createEntityAdapter<T extends U & V, U, V>(
  options: {
    selectId?: IdSelector<U>;
    sortComparer?: false | Comparer<V>;
  } = {}
): EntityAdapter<T>
```
I'm not certain that that is the best way to handle something like this, but I think it should work.

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
I'm not sure if this is something we would want to add.

If we do implement this, we also would have to add a `isKeyTheSame()` (with probably a better suited name) method. Because `{ id: '47', type: 'foo' } === { id: '47', type: 'bar' }` always results to `false`.

**Comment by karptonite** [comment]
@timdeschryver I'm not sure I understand your objection. The only change I'm talking about is changing the type signature of `createEntityAdapter`. The example was only motivational, and the intention was that `selectId` would continue to return a string or number, as usual, with the implementation left to the user. for example selectId for a `CompoundId` might return, for example,
`type + '_' + id`. 

But the only change I'm proposing is to allow the entity type for the entity adapter to extend some base interface that is then used by the user-provided `selectId`. Is that more clear?

**Comment by timdeschryver** [comment]
Sorry, I misunderstood you.

I think the following does what you're asking?

```ts
function selectId<T extends CompoundId>(entity: T) {
    return entity.type + '_' + entity.id;
}

const adapter = createEntityAdapter<BookModel>({
   selectId,
});

onst adapter2 = createEntityAdapter<PageModel>({
    selectId,
});
```

**Comment by karptonite** [comment]
Yes, you are right, something like that will work as well. But, to me, it wasn't an obvious solution. Do you think that explicitly changing the types in `createEntityAdapter` makes sense, or is it better for this to be on the user to write selectId to have a generic type?

**Comment by timdeschryver** [comment]
Yes, I think you should always type the `createEntityAdapter`. Otherwise, it would lead to compilation errors?


```
export interface State extends EntityState<Book> {
  selectedBookId: string | null;
}
export const adapter = createEntityAdapter<Book>({
  selectId: book => book.id,
  sortComparer: false,
});

// this gives the error `Property 'id' does not exist on type '{}'`
export const adapter = createEntityAdapter({
  selectId: book => book.id,
  sortComparer: false,
});
```

**Comment by karptonite** [comment]
@timdeschryver I'm not suggesting that users shouldn't type the `createEntityAdapter`. I'm suggesting that the types allow for the primary type to extend other types that are used by `selectId` and `sortComparer`. While the user can accomplish the same thing by using a generic type for their `selectId`, if we used the proposed signature above, then the user `selectId` function could look like:
```
interface BookModel extends CompoundId{}
interface PageModel extends CompoundId{}

function selectId(entity: CompoundId) {
    return entity.type + '_' + entity.id;
}

const adapter = createEntityAdapter<BookModel>({
   selectId,
});

onst adapter2 = createEntityAdapter<PageModel>({
    selectId,
});

**Comment by timdeschryver** [comment]
Yes, I think the generic `selectId` is the best solution, we can re-evaluate later if needed.
