### ISSUE TITLE
How to share state between two reducers 

### ISSUE THREAD

**Issue by amitcdubey** [ngrx/platform#1572]
Hi am working on ngrx,and currently am trying to share state between two reducers ,one is my login reducers and other is userdetails ,while am using login reducers its working fine but after login when am using userdetails reducers am not getting any state ,all the time am getting blank in tree,kindly let me know how to share state between two reducers

**Comment by timdeschryver** [comment]
Make sure every reducer is returning state (the `default` case in the `switch` statement), you can take a look at the [docs](https://ngrx.io/guide/store/reducers#creating-the-reducer-function) or our [example-app](https://github.com/ngrx/platform/tree/master/projects/example-app) for some examples.

For more information, you can always join our [gitter channel](https://gitter.im/ngrx/platform) or ask a question on [stackoverflow (with a ngrx tag)](https://stackoverflow.com/questions/tagged/ngrx).

If this isn't the case feel free to re-open this issue.
