### ISSUE TITLE
docs(Schematics): add --api

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#1574]
## Other information:
Add the new `api` flag introduced in #1530 to the docs at https://ngrx.io/guide/schematics/feature.

## I would be willing to submit a PR for the docs :heart:

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by deli6z** [comment]
Hi. I am probably writing in the wrong place anyhow - I am using the store for about two years and wanted to give back. I am new to open source world. I went over the contribution guidelines - just need some simple task/bug to start off. You guys need help ?

**Comment by timdeschryver** [comment]
Hi @deli6z, great to hear that!
You can take a look at some specific tags as [Good first issue](https://github.com/ngrx/platform/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22Good+First+Issue%22) and [Accepting PRs](https://github.com/ngrx/platform/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc++label%3A%22Accepting+PRs%22+) - if you want to pick up something leave a comment in the issue 😄 

You can also join our [gitter chat](https://gitter.im/ngrx/store) to answer some questions asked over there, of ask a question yourself.

**Comment by feeloor** [comment]
Hi! 
I'd like to take a shot at this. Assuming no one else have started working on this?

**Comment by timdeschryver** [comment]
@feeloor Awesome! Feel free to take this one 😄
