### ISSUE TITLE
variable typing not correct in example

### ISSUE THREAD

**Issue by LordMidi** [ngrx/platform#1581]
https://github.com/ngrx/platform/blob/master/docs/effects/testing.md - first code example

line 12
`let actions: Observable<any>;` - typed Observable

line 34
`actions = hot('--a-', { a: action });` - typed TestHotObservable

line 41
`actions = new ReplaySubject(1);` - typed ReplaySubject

using these three types doesn't work - at least for correct TypeScript linting.

**Comment by brandonroberts** [comment]
There's a PR to fix the this #1571

**Comment by LordMidi** [comment]
Haha Nice. The same guy I talked to an Stackoverflow abot this problem. Thanks
