### ISSUE TITLE
createFeatureSelector should return root store or feature state?

### ISSUE THREAD

**Issue by wizardnet972** [ngrx/platform#1587]
I think there is a confusion in example app or maybe possible bug..

according to the comment the `createFeatureSelector` should return only the piece of state from the store right? And in practice the `createFeatureSelector` return the `Store` object.

[index.ts](https://stackblitz.com/edit/ngrx-example-app-1-talkz4?file=example-app%2Fapp%2Fbooks%2Freducers%2Findex.ts):

```
/**
 * The createFeatureSelector function selects a piece of state from the root of the state object.
 * This is used for selecting feature states that are loaded eagerly or lazily.
 */
export const getBooksState = createFeatureSelector<BooksState>('books');
```

```
export const getBookEntitiesState = createSelector(
  getBooksState,
  (state) => {
    // debugger;
    console.log({ state });
    return state;
  },
  state => state.books
);
```
![image](https://user-images.githubusercontent.com/4997825/53571402-8037e200-3b71-11e9-91e1-46b61352b2bb.png)

cc @brandonroberts

**Comment by timdeschryver** [comment]
The `createSelector` example in your example is behaving as intended.
The 2nd parameter (`state => state`) is just a second selector, it isn't relying on the output of the first one (`getBooksState`) and thus receives the full state object.

The `getBookEntitiesStat` select is composed of multiple selectors:
- the first gets as input the full state and retrieves the `books` from the state
- the second one (`state => state`) retrieves the full state and returns the full state 

The last argument of the selector is the projector function which receives the output from all of the selectors, in this case `bookState` and `fullState`.

(If you're using VSCode for example and you hover of the `state` argument, you'll see it will be typed as the full state)

If something isn't clear, feel free to reach out.
