### ISSUE TITLE
example-app: vscode reports Typescript problems

### ISSUE THREAD

**Issue by tja4472** [ngrx/platform#1592]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

![image](https://user-images.githubusercontent.com/18631456/53634823-2a1b7b00-3c13-11e9-9646-0bbf54d2192f.png)

## Expected behavior:

No problems

## Other information:
Could add tsconfig.json to example-app folder.
```json
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "strict": false,
    "baseUrl": ".",
    "paths": {
      "@ngrx/effects": ["../../modules/effects"],
      "@ngrx/store": ["../../modules/store"],
      "@ngrx/store-devtools": ["../../modules/store-devtools"],
      "@ngrx/router-store": ["../../modules/router-store"],
      "@ngrx/entity": ["../../modules/entity"],
      "@ngrx/schematics": ["../../modules/schematics"],
      "@example-app/*": ["./src/app/*"],
      "ngrx-store-freeze": ["../../projects/ngrx-store-freeze"]
    }
  }
}

```

**Comment by timdeschryver** [comment]
Thanks for filling the issue, would you want to submit a PR @tja4472 ?
(We already got a `tsconfig.app.json` for the `example-app`.)

**Comment by tja4472** [comment]
Will do.

We can't just copy `tsconfig.app.json` as the excluded files causes problems with the `*.spec.ts` files within vscode.
