### ISSUE TITLE
Allow to prepend item

### ISSUE THREAD

**Issue by tbnovaes** [ngrx/platform#1599]
It would be good to have a way to add an item to the top of the array, instead of the end.

## Describe any alternatives/workarounds you're currently using
using sortComparer to sort it by the property you want on the top

## Other information:

The workaround works fine when you want to sort by some property that follows a sequence (name, id, created_at, updated_at, etc)

However, using as example stripe api, when you query a list of payment sources, the first item on the list is considered the `default` payment method. Each type of payment method follows a different id logic, and they do not provide a `created_at`... therefore, there is no way for me to have new payment methods on top by sorting the list. So the only way to have the last item user added on top as expected, is by reloading the entire list.

**Comment by timdeschryver** [comment]
I'm not sure if this would be for the best.
What about adding a sort property on the items that are retrieved?

**Comment by timdeschryver** [comment]
Closing this issue, it shouldn't matter how the items are stored in the store state.
For more complex sorting, you can use a selector.
