### ISSUE TITLE
RFC: add blog section to ngrx.io

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1601]
Instead of posting to Medium, we could integrate a section for blog posts into the ngrx.io app.

Pros:

- Infrastructure is already in place to generate pages from markdown
- Integrated code examples we could generate StackBlitz examples from
- More control over content analytics
- Allows for contributors/guest posts as PRs
- Take advantage of GitHub for peer reviews

Cons:

- We have to release the entire app to release a blog post or update
- Releasing in between major versions might be painful
- Specific syntax for writing in markdown files
- Custom code for blog section

A spike could be useful to see how much effort this would be.

**Comment by timdeschryver** [comment]
Would losing Medium's platform to reach people (who have subscribed to NgRx) also be considered a con?

**Comment by brandonroberts** [comment]
Maybe so.There are 300+ people subscribed right now

**Comment by thiagogjt** [comment]
Could the documentation have a life cycle of its own?

**Comment by wesleygrimes** [comment]
I love the idea of moving off of Medium. What are your thoughts on making this another repo like @ngrx/blog? We could then decouple the blog posts, which will have frequent edits and updates, from the release of ngrx.

We still gain some of the benefits you mention like peer reviews via PR, and guest posts via PRs. 

We could then clone a extremely trimmed down version of the docs app and use that as the code base.

**Comment by wesleygrimes** [comment]
To quell @timdeschryver concern of losing subscribers on Medium, you could still cross post to Medium, and even Dev.To as they have import capabilities. Probably a way to automate this via REST api calls. You would just need to set the `canonical_url` to point back to the ngrx.io site so that Google properly indexes searches.

**Comment by brandonroberts** [comment]
Staying with medium for now
