### ISSUE TITLE
Docs: Add Angular Checklist link and description to resources page

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1602]
## Describe any alternatives/workarounds you're currently using

Angular Checklist has a good checklist of items when building with NgRx.
Add an entry under `Example Projects` in the resources file with the following format:

```json
          "angular-checklist": {
            "title": "",
            "desc": "",
            "url": "",
            "rev": true
          }
```

The resources file to update is here.

https://github.com/ngrx/platform/blob/master/projects/ngrx.io/content/marketing/resources.json

**Comment by timdeschryver** [comment]
The URL to point to is https://angular-checklist.io/, right?

**Comment by santoshyadav198613** [comment]
Will do it guys.

**Comment by brandonroberts** [comment]
Yep. @santoshyadav198613 let someone else take this one. You're not a first timer anymore 😄
