### ISSUE TITLE
Docs: add contributors page

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1608]
Powered By The Community ™️  

We should create a page that list our community of contributors. We should be able to get this data from GitHub to generate data for the page. Maybe break down contributors per major release?

**Comment by timdeschryver** [comment]
Yes! 😄

**Comment by timdeschryver** [comment]
There is a tool `all-contributors` that can generate contributors in the README.
Yesterday I discovered that there's also a bot for this, so for example if one would create a PR and is a new contributor we can say `please add username for docs` and it will create a new PR with an entry for the new contributor. It will also keep track of the users in a separate file, that we could use to generate this page on ngrx.io.

For more info see https://allcontributors.org/, an example can be found at https://github.com/testing-library/dom-testing-library#contributors and the [generated file](https://github.com/testing-library/dom-testing-library/blob/master/.all-contributorsrc).

I don't know if this is something we would want to use here, dropping it here just in case.
