### ISSUE TITLE
Schematics: Remove deprecated defaultProject

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1614]
## Describe any alternatives/workarounds you're currently using

More context here https://github.com/angular/angular-cli/pull/12394, but `defaultProject` is being deprecated as the CLI will use the current working directory to determine where to generate files.

**Comment by santoshyadav198613** [comment]
Hey @brandonroberts ,

Is this is the same change wee added last week, let me know i can roll it back, and what project to take by default.

**Comment by brandonroberts** [comment]
Yes, we will revert that change. I'll see about further impact, so don't change anything else yet.

**Comment by brandonroberts** [comment]
Closing as this is still supported
