### ISSUE TITLE
Docs: Update events page with upcoming events

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1615]
Past events are listed in upcoming events. Some upcoming events are missing also

- Angular Connect
- Angular Denver
- Component.tech
- NG-MY
- ngRome
- ngVikings
- NG-MY
- Open Source 101
- Refactr.Tech

Other people speaking about NgRx at some event are welcome to add theirs also.

**Comment by santoshyadav198613** [comment]
Hi @brandonroberts ,
Let me know i can take it.

**Comment by itayod** [comment]
[Angular Up](https://angular-up.com/)

**Comment by itayod** [comment]
[Angular Up](https://angular-up.com/)

**Comment by itayod** [comment]
[Angular Up](https://angular-up.com/)
