### ISSUE TITLE
Please consider adding Angular-Bootstrap-Boilerplate to /resources

### ISSUE THREAD

**Issue by filipkappa** [ngrx/platform#1618]
Please consider adding the [Angular Bootstrap Boilerplate](https://github.com/mdbootstrap/Angular-Bootstrap-Boilerplate) to https://ngrx.io/resources
It's an open sourced Angular CRUD application starter with NgRx state management and Firebase backend.

**Comment by brandonroberts** [comment]
If someone wants to submit a PR, the file is here https://github.com/ngrx/platform/blob/master/projects/ngrx.io/content/marketing/resources.json
