### ISSUE TITLE
Docs: Add recipe for NgRx and server-side rendering

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1622]
We will have an official serialization and hydration API, but we still need a guide for the current setup as described in https://github.com/ngrx/platform/issues/101

Requirements:

- A guide that shows how to set it up.
- A downloadable live example under `projects/ngrx.io/examples` that is referenced in the guide.

**Comment by santoshyadav198613** [comment]
Hey @brandonroberts ,
I can start with this, can you tell me how should i get started,if you can guide me to any examples or demo.

**Comment by santoshyadav198613** [comment]
Will take this next.

**Comment by santoshyadav198613** [comment]
Hi @timdeschryver , @brandonroberts ,

I have created a SSR app with NgRx support its very simple App where you can see multiple routes with the same state.

https://github.com/santoshyadav198613/NgRxSSRDemo

**Comment by kanafghan** [comment]
I have done NgRx and SSR in a project before by following the technics discussed in #101. I would love to help @santoshyadav198613, @brandonroberts with the PR.

I guess that by

> A downloadable live example ...

you mean a Stackblitz app like those under `projectx/ngrx.io/content/examples`, right @brandonroberts ?

**Comment by MichaliEverson** [comment]
what about varies devices to mobile devices as tablet nd Smart Phone to Windows PC 
or even studio MAC
