### ISSUE TITLE
Issue with pre-compiled module 

### ISSUE THREAD

**Issue by chirag-vashisht** [ngrx/platform#1624]
I am working a pre-compiled module that has a feature state with angular 7.2.0 and ngrx version 7.3.0. But I keep getting following error when I imported the module into another repository.

> main.ts:14 Error: StaticInjectorError(AppModule)[InjectionToken @ngrx/store Feature Reducers -> Injector]: 
>   StaticInjectorError(Platform: core)[InjectionToken @ngrx/store Feature Reducers -> Injector]: 
>     NullInjectorError: No provider for Injector!
>     at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (core.js:8894)
>     at resolveToken (core.js:9139)
>     at tryResolveToken (core.js:9083)
>     at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:8980)
>     at resolveToken (core.js:9139)
>     at tryResolveToken (core.js:9083)
>     at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:8980)
>     at resolveNgModuleDep (core.js:21119)
>     at _callFactory (core.js:21187)
>     at _createProviderInstance (core.js:21139)

Below is the code for compiled module
```
@NgModule({
  declarations: [LoginComponent],
  imports: [
    CommonModule,
    SocialLoginModule,
    StoreModule.forFeature('authentication', FEATURE_REDUCER_TOKEN),
    EffectsModule.forFeature([AuthEffects]),
  ],
  providers: [
    {
      provide: AuthServiceConfig,
      useFactory: provideConfig
    },
    {
      provide: FEATURE_REDUCER_TOKEN,
      useFactory: authReducersFactory,
    },
  ],
  exports: [LoginComponent]
})
export class AuthenticationModule {

  /**
   * Create singleton injection
   * @static
   * @returns {ModuleWithProviders}
   * @memberof AuthenticationModule
   */
  public static forRoot(): ModuleWithProviders {
    return {
      ngModule: AuthenticationModule,
      providers: [
        {
          provide: AuthServiceConfig,
          useFactory: provideConfig
        },
        {
          provide: FEATURE_REDUCER_TOKEN,
          useFactory: authReducersFactory,
        }
      ]
    };
  }
}
export const authReducers: ActionReducerMap<IAuthState> = {
    login: loginReducer,
};

export const FEATURE_REDUCER_TOKEN = new InjectionToken<
  ActionReducerMap<IAuthState>
>('Feature Reducers');

export function authReducersFactory(): ActionReducerMap<IAuthState> {
    return authReducers;
}


@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    StoreModule.forRoot(REDUCER_TOKEN),
    EffectsModule.forRoot([]),
    AppRoutingModule,
    MssCommonModule.forRoot(),
    AuthenticationModule.forRoot()
  ],
  providers: [
    {
      provide: REDUCER_TOKEN,
      useFactory: getRootReducers,
    }
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
Could someone help me here?

**Comment by brandonroberts** [comment]
A GitHub repo with a small reproduction of the issue would help us diagnosis if its a problem on our end. We haven't changed any behavior about registering reducers with a token.

**Comment by chirag-vashisht** [comment]
Thanks for your time, I think the issue was with angular build, I set `preserveSymlinks` to `true`. And it started working.

**Comment by timdeschryver** [comment]
👍 As this is resolved, I will close the issue.
