### ISSUE TITLE
Sharing one state for multiple reducers

### ISSUE THREAD

**Issue by vasyliv** [ngrx/platform#1629]
## Minimal reproduction of the bug/regression with instructions:
https://github.com/vasyliv/ngrx-demo
go to repo
`npm run start`
click on button **get 1 item** (you will get 1 item per one click)
click on the link within an item from the list
go to the status page
change the status click submit
click on button **get 1 item** (you won't get 1 item per one click)

the problem is that reducer (`itemReducer`) from global store overrides by reducer (`itemStatusReducer`) from the feature store.
Why I created two separate reducers instead one, the reason is that in really big projects isn't a good way to create a big reducer that handles about 200 cases, instead of it I would like to have a lot of small reducers that belong each separate module (hello lazy loading) in this case we will have a lot of small reducers that much easy to manage and they will load exactly when they need.

## Expected behavior:
reducers won't override each other

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
latest, Windows 10
 
## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
I can't seem to run your example on stackblitz, but you have to provide an initial state (different from `undefined` and `null`) in the `itemStatusReducer`.

**Comment by vasyliv** [comment]
@timdeschryver I've created the example on the stackblitz https://stackblitz.com/edit/angular-kgfaa6, however I guess the problem doesn't relate to state, the problem is that itemReducer doesn't work after initializing itemStatusReducer, it looks like itemReducer overrides after initialization itemStatusReducer feature module.

**Comment by timdeschryver** [comment]
I see. 
What you're trying to do isn't possible, you can only have one reducer for each sub-state, e.g.

```ts
{
	customers: customersReducer,
	orders: ordersReducer	
}
```

You can't have two reducers for a single sub-state.

**Comment by vasyliv** [comment]
@timdeschryver thank you!
