### ISSUE TITLE
combineLatest not working with store.select

### ISSUE THREAD

**Issue by viqashussain** [ngrx/platform#1631]
## Minimal reproduction of the bug/regression with instructions:

https://stackblitz.com/edit/angular-3n5gfm

Add a new footballer to the list (name and club). The list should update with the new filtered list of footballers, but it only updates when you change the filter drop down list. 

## Expected behavior:

footballers$ in items-list.component.ts to be updated when the state in the store changes. 

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

Angular: 7.2.5
NgRx: 7.3.0

## Other information:

N/A

## I would be willing to submit a PR to fix this issue

[x ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
The problem is that the state is modified in an impure way, so it keeps the same reference. Because the check if the state is modified or not is a quick reference check `===`, the change doesn't trigger a state modification.

In your example, you should use the following the add a footballer

```ts
return {
  ...state,
  footballers: [...state.footballers, action.payload]
};
```

**Comment by viqashussain** [comment]
Of course, you need to make a deep copy, not a shallow one! Thank you so much!!!

**Comment by timdeschryver** [comment]
Glad we could help 😄
