### ISSUE TITLE
Example: Change search filter for E2E tests

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1636]
We have implemented visual testing, which works as designed, but the Google Books search doesn't return the same results consistently. We are currently searching for books containing `The Alchemist`. This should be updated to something more specific so we get more stable results.

**Comment by brandonroberts** [comment]
The line to change is here https://github.com/ngrx/platform/blob/master/projects/example-app-cypress/integration/round-trip.spec.ts#L40

**Comment by jtcrowson** [comment]
What do you mean that the Google Dooks search doesn't return the same results consistently?  Ordering is different?  Do we want a search that only yields one result?

**Comment by timdeschryver** [comment]
I think the biggest problem would be location? 

The API is documented at:
https://developers.google.com/books/docs/v1/reference/volumes/list

**Comment by brandonroberts** [comment]
Just something more predictable. May just need an additional `orderBy` filter so the most recent ones are always shown for that search, which should change less frequently.
