### ISSUE TITLE
Example: Move E2E test suite into example-app folder

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1638]
File structure is changing for Angular CLI V8 so that the e2e tests are no longer a separate project. Example app should be updated to reflect this.

https://github.com/angular/angular-cli/commit/026ae8cefc450038ff87338066fe9929570dfb6f

**Comment by kanafghan** [comment]
I would like to take this one @brandonroberts :-)

**Comment by brandonroberts** [comment]
Thanks @kanafghan. We don't need to do this one anymore because we're using cypress for E2E testing (which is currently disabled). If you want to look re-enabling the E2E tests that would help.

I filed an issue here #1879
