### ISSUE TITLE
Property 'forRoot' does not exist on type 'typeof EffectsModule'

### ISSUE THREAD

**Issue by JanisOzolins** [ngrx/platform#1644]
I'm trying to wire up effects to my app (Angular CLI: 7.3.6, Node: 10.10.0OS: Angular: 7.2.10).

But when trying to add `EffectsModule.forRoot([ MyEffects ])` to my app.module.ts file, I keep getting the `Property 'forRoot' does not exist on type 'typeof EffectsModule'`

Any ideas what might be causing this?

**Comment by timdeschryver** [comment]
You should upgrade the ngrx packages (and possibly remove @ngrx/core).

See https://github.com/ngrx/platform/issues/784.
