### ISSUE TITLE
replaceReducer has been deprecated

### ISSUE THREAD

**Issue by huineng** [ngrx/platform#165]
There's no documentation (as far as i've looked), nor migration guide update, as to why replaceReducer has been removed.  Can it be explained why it was removed and how to use it in release 4 

use case ... in angular 4.x
initial reducer SiteStore is loaded at bootstrap
reducer SiteStore and StoreReducer (from module) are combined and lazy loaded and replace A 

```
export const appReducers: any = {
    coverage: StoreReducer,
    siteStore: SiteStore,
};
constructor(private store: Store<any>) {
        this.store.replaceReducer(combineReducers(appReducers));
    }
```

thanks

**Comment by karptonite** [comment]
If I understand this properly, I think that you can achieve this same functionality now by providing with `StoreModule.forFeature()` , as described here: https://github.com/ngrx/platform/blob/master/docs/store/api.md#feature-module-state-composition

**Comment by abhi40308** [comment]
Link does not work anymore
