### ISSUE TITLE
docs(Schematics): example in "Default Schematics Collection" section is not working

### ISSUE THREAD

**Issue by musou1500** [ngrx/platform#1650]
I tried config bellow(it is [documented here](https://ngrx.io/guide/schematics#default-schematics-collection)), but `ng g container` generates component with **css** file.

```json
"schematics": {
  "@ngrx/schematics:component": {
    "styleext": "scss"
  }
}
```

I tried `@ngrx/schematics:container` instead, it works.
Should I fix the document?

## I would be willing to submit a PR for the docs :heart:

[ x ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by adrianfaciu** [comment]
Not sure I understand the problem, you have a config for `component` but generate a `container`.

Make sure you have NgRx set as the default collection:
`ng config cli.defaultCollection @ngrx/schematics`
This should add this property to angular.json:
`"defaultCollection": "@ngrx/schematics"`

Having this, you can generate a component and it will use the settings specified under NgRx in schematics.

**Comment by timdeschryver** [comment]
As @adrianfaciu pointed out, you're generating a container.
Have you tried the following?


```diff
"schematics": {
  "@ngrx/schematics:component": {
    "styleext": "scss"
  },
++"@ngrx/schematics:container": {
++  "styleext": "scss"
++}
}
```

**Comment by musou1500** [comment]
@adrianfaciu 
> Not sure I understand the problem, you have a config for component but generate a container.

I apologize that I had misunderstood the document. I had thought the config is also applied when generating a container....
I confirmed that `ng g component` generates component with scss properly. documented config is correct.

@timdeschryver 
thank you. I tried it. 
> I tried @ngrx/schematics:container instead, it works.

I understood documented config is correct. 
Do you have plan to document how to generate a **container** with scss?

**Comment by timdeschryver** [comment]
Awesome! 👍 

We can definitely add it to the docs.
Do you want to submit a Pull Request with these changes?

**Comment by musou1500** [comment]
@timdeschryver 
Yes. I want to submit a Pull Request.
I am thinking that where to document it....
How about the adding the descriptions to "Examples" section in "Container" page ?

**Comment by timdeschryver** [comment]
Yea, I think it can have its place there.
Let's wait on some feedback of @brandonroberts before you start 😄

**Comment by brandonroberts** [comment]
Go for it 👍
