### ISSUE TITLE
Errors occurring in effects are not caught right

### ISSUE THREAD

**Issue by maimArt** [ngrx/platform#1651]
## I would be willing to submit a PR for the docs :heart:

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

In the documentation of how to implement effects, you prefer to catch the error within the inner pipe:

```javascript
@Effect()
  loadMovies$ = this.actions$
    .pipe(
      ofType('[Movies Page] Load Movies'),
      mergeMap(() => this.moviesService.getAll()
        .pipe(
          map(movies => ({ type: '[Movies API] Movies Loaded Success', payload: movies })),
          catchError(() => of({ type: '[Movies API] Movies Loaded Error' }))
        ))
      )
    );
```

If it is used like this, you just catch errors occurring during mapping the movies to a new 'Loaded Success' action within the inner pipe, not errors occurring while requesting the service in the outer pipe.

The errors we really want to catch, are those occurring while requesting the service, so it should be implemented like this:

```javascript
@Effect()
  loadMovies$ = this.actions$
    .pipe(
      ofType('[Movies Page] Load Movies'),
      mergeMap(() => this.moviesService.getAll()
        .pipe(
          map(movies => ({ type: '[Movies API] Movies Loaded Success', payload: movies }))          
        )),
      catchError(() => of({ type: '[Movies API] Movies Loaded Error' }))
      )
    );
```

**Comment by timdeschryver** [comment]
This isn't true. You want to catch the errors caused by `this.moviesService.getAll()`.
If you don't catch the errors on the inner pipe the whole stream will be destroyed. This means that if you would dispatch another `Load` action, `getAll` won't be executed because the Effect itself is destroyed.

**Comment by maimArt** [comment]
Sorry, but you are wrong. Please at least bother to write a simple unit test for the code of the current documentation where the service throws an error. You will see.

**Comment by timdeschryver** [comment]
This is exactly what the snippet in the docs is doing @maimArt, it catches thrown errors of the service.

See https://stackblitz.com/edit/ngrx-effects-catcherror-inner-stream for an example.

**Comment by alex-okrushko** [comment]
@maimArt `catchError` in the inner pipe is there **not** to catch error of action mapping, but to catch errors from the inner **Observable** generated by the service call **before** that observable is flattened into the main stream of actions with `mergeMap`(the outer pipe).
