### ISSUE TITLE
Feature: Add @Reducer decorator similar to @Effect

### ISSUE THREAD

**Issue by ssljivic** [ngrx/platform#166]
It would be nice to be able to do a state composition the same way effects are defined using `@Effect` decorator, e.g. using `@Reducer` decorator. Beside other benefits, we can get rid of switch statement in reducers, which is by its own a huge improvement.

**Comment by Bretto** [comment]
We added our own: https://github.com/ngrx/store/issues/444

**Comment by brandonroberts** [comment]
This is something you could implement on your own, but we don't have any plans to add a decorator for reducers at this time.

**Comment by amcdnl** [comment]
Checkout https://github.com/amcdnl/ngrx-actions
