### ISSUE TITLE
Docs: Add Spartacus to resources page

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1661]
## Describe any alternatives/workarounds you're currently using

Spartacus is a storefront app built with Angular and NgRx.
https://github.com/SAP/cloud-commerce-spartacus-storefront
Add an entry under `Example Projects` in the resources file with the following format:

```json
          "sap-spartacus": {
            "title": "",
            "desc": "",
            "url": "",
            "rev": true
          }
```

The resources file to update is here.

https://github.com/ngrx/platform/blob/master/projects/ngrx.io/content/marketing/resources.json

**Comment by musou1500** [comment]
I want to working on this. Is it OK to create a Pull request?

**Comment by brandonroberts** [comment]
This one is specifically for first-time contributors.

**Comment by musou1500** [comment]
Certainly. Thank you.

**Comment by osnoser1** [comment]
Hi, can I take this?

**Comment by dkosasih** [comment]
@osnoser1 let me know if you are taking it so there will be no double work, I was planning to work on this some time this week.

**Comment by timdeschryver** [comment]
Sure @osnoser1 , it's all yours.

Sorry @dkosasih, but as already mentioned there are a few issues open 😄
