### ISSUE TITLE
subscribe to dispatcher when a action is being dispatched.

### ISSUE THREAD

**Issue by tomNjerry** [ngrx/platform#1669]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
</code></pre>

**Comment by timdeschryver** [comment]
What is the underlying case you want to solve with this?
I think this is something we don't want to add, see #877.
