### ISSUE TITLE
Schematics: Add schematics for action creators

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1670]
Follow up to #1480 

1. Adds an `actionCreators` option to the `action`, `feature`, `entity` schematics that uses the new action creator functions instead of classes
2. The actionCreators flag will use a different set of files for scaffolding. This keeps our current structure with `files` intact.
3. Adds tests to verify the behavior of the previously mentioned schematics

**Comment by timdeschryver** [comment]
What about making `actionCreators` the default (and make it our recommended way)?
We already have refactored the example app and are currently busy updating the docs.

**Comment by brandonroberts** [comment]
I'd rather it be opt-in for 8 and the default for 9.

**Comment by jtcrowson** [comment]
Happy to pick this up if it's still up for grabs.

**Comment by timdeschryver** [comment]
If I'm not mistaken, I think @brandonroberts has started on this.

**Comment by brandonroberts** [comment]
Yep, I have a branch here. https://github.com/ngrx/platform/tree/schematics-action-creators

If you want to take it, that's fine with me. It will need to land after #1725
