### ISSUE TITLE
"Const enum" for action generation

### ISSUE THREAD

**Issue by DmitriyIvanko** [ngrx/platform#1677]
It is better to generate "const enum MyActionTypes" instead of "enum MyActionTypes" (for default settings). This will reduce the size of the bundle.

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ + ] No

**Comment by erhise** [comment]
I think the release of version 8 will make this request obsolete (https://next.ngrx.io/guide/store/actions#creating-action-unions)

**Comment by brandonroberts** [comment]
Yes, with the creator functions, action type enums are longer needed. This won't change for the existing action classes.
