### ISSUE TITLE
Example: enable immutability checks

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#1683]
With #1613 merged, we have to enable the `strictImmutability` check by providing `runtimeChecks` at https://github.com/ngrx/platform/blob/master/projects/example-app/src/app/app.module.ts#L38

This will act as a replacement of ngrx-store-freeze, which is already removed from the example-app.

If you start with this issue, please leave a comment.

**Comment by King-i** [comment]
i can do this if you want?
