### ISSUE TITLE
Example: Clean up barrel imports

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1684]
In multiple places we have individual imports for components, containers, effects.

- Create an `index.ts` file in each grouping folder, for example (components/index.ts)
- Export modules from files in the grouping in the `index.ts` file, for example (export * from './login-page.component')
- Update imports in the application to use the barrel imports

**Comment by King-i** [comment]
i can pick this up?

**Comment by brandonroberts** [comment]
Sure

**Comment by jtcrowson** [comment]
@King-i are you still picking this up?

**Comment by alex-okrushko** [comment]
Can we revisit barrel imports? What value do they add in the example app?

**Comment by mikezks** [comment]
Some kind of connected to this issue:

What is your opinion on generating an index.ts file with schematics that exports a fromFeature namespace. This would lead to a better IDE experience in components, directives, services, modules that need to import reducers, actions, selectors, state.

I can provide an example repo if you like this idea.

**Comment by timdeschryver** [comment]
The auth module has been refactored in #1808, you can use this a reference to refactor the books module.

**Comment by alex-okrushko** [comment]
![giphy](https://user-images.githubusercontent.com/2830407/57253566-031b6400-701d-11e9-9633-c253bb45419b.gif)

**Comment by jasonhodges** [comment]
Is there anyone currently assigned this task? If not, I'd love the opportunity to jump in and help

**Comment by timdeschryver** [comment]
You can go ahead and take this one @jasonhodges, or are you currently working on this @King-i ?

**Comment by jasonhodges** [comment]
> You can go ahead and take this one @jasonhodges, or are you currently working on this @King-i ?

Thanks @timdeschryver 
Anything that needs to be done to mark this as claimed?

**Comment by timdeschryver** [comment]
No, we already have the community watch as label so we're all good. Maybe just wait 2-3 days before working on this, giving @King-i the opportunity the time to answer.

**Comment by jasonhodges** [comment]
> No, we already have the community watch as label so we're all good. Maybe just wait 2-3 days before working on this, giving @King-i the opportunity to answer.
No reply. I should be able to get started on this tomorrow.

**Comment by jasonhodges** [comment]
@brandonroberts @timdeschryver are there still other sections I can clean up barrel imports for? Thanks

**Comment by brandonroberts** [comment]
@jasonhodges I think the only one left is the `core` folder

**Comment by jasonhodges** [comment]
> @jasonhodges I think the only one left is the `core` folder

Ok, I’ll take it 👍🏽
