### ISSUE TITLE
ngrx/router-store go, forward, back navigation in 4.X?

### ISSUE THREAD

**Issue by pjmagee** [ngrx/platform#169]
The migration guide doesnt show the alternative or best way to map actions to router navigation actions in @Effects. 

```
.ofType(Action.EXAMPLE_ACTION)
.map(payload => go(['home']))
```

Is there now a new recommended approach since actions like *go* have been removed?

**Comment by linkvt** [comment]
It is now intended that you should use the angular `Router` directly, see here: https://github.com/ngrx/platform/issues/107#issuecomment-316370493

**Comment by brandonroberts** [comment]
Duplicate of #107
