### ISSUE TITLE
Missing comma in docs

### ISSUE THREAD

**Issue by jsonod** [ngrx/platform#1690]
1. Open https://ngrx.io/guide/store/selectors
2. Scroll to the bottom
3. Inside code snippet: select-last-state-transition.ts, at line 10
4. `} [] as {foo: number; bar: string}[])`
   should be
    `}, [] as {foo: number; bar: string}[])`
## I would be willing to submit a PR for the docs :heart:

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Do you want to submit a PR with a fix? 😄

**Comment by jsonod** [comment]
No problem.
