### ISSUE TITLE
Example Output in docs for Schematics

### ISSUE THREAD

**Issue by peterbsmith2** [ngrx/platform#1693]
It would be helpful to see the sample output of generate commands that are defined in ngrx schematics, right on ngrx.io

Other information:
I would be willing to submit a PR for the docs

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
How much sample output are you wanting to see? Generating a feature, or an entity would still be pretty verbose. We discussed this previously in https://github.com/ngrx/platform/issues/758, but we didn't have a dedicated place for docs then.

**Comment by peterbsmith2** [comment]
I think the full thing, perhaps in an expandable in case verbosity issues are about space on a page.   
  
I would say that there is a benefit to those people who are already using ngrx regularly. Its an enticement to them to see what would otherwise be manually written by hand. In that context verbosity could even be an asset.  
  
It also may drive adoption if it were clear what the benefit of the commands is before running them.

**Comment by brandonroberts** [comment]
Sounds reasonable to me

**Comment by peterbsmith2** [comment]
I'm going to be less than fast on this one, though I am starting planning over the weekend.

**Comment by brandonroberts** [comment]
No rush
