### ISSUE TITLE
example:cypress:open requires agreeing to Applitiools Terms & Conditions??

### ISSUE THREAD

**Issue by tja4472** [ngrx/platform#1697]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

Am unable to run example:cypress:open script as I have not agreed to Applitiools Terms & Conditions
```
Error: APPLITOOLS_API_KEY env variable is missing. It is required to define this variable when running Cypress for Applitools visual tests to run successfully.
```

## Expected behavior:

To be able to run script without registering with Third Parties

**Comment by brandonroberts** [comment]
Applitools is what we're using for now. You shouldn't need to run the E2E tests unless you're changing something visually to the example app. We will revisit this once we diagnose the flakyness.
