### ISSUE TITLE
Support in offline documentations

### ISSUE THREAD

**Issue by Hermel** [ngrx/platform#1698]
I would like to run a clone of the NGRX docs on a local pc (that has no internet access), is it possible to get support for such procedure?
Thanks.

**Comment by santoshyadav198613** [comment]
Hi @Hermel ,
The ngrx.io portal is available as PWA, you can get it installed and you do not need internet access after that.

**Comment by Hermel** [comment]
@santoshyadav198613 
Could you please explain in more detail how can I make it happen? Maybe with the code or the commands I should run?

**Comment by santoshyadav198613** [comment]
Hi @Hermel ,

1. On Desktop open chrome click on 3 dots icon, you will see an option Install NgRX.
2. On Mobile devices once you open ngrx.io you will get an option to Add NgRx.io to Home Screen.

Once it is done, the documentation will work offline as well.

Let me know if it helps.

**Comment by Hermel** [comment]
@santoshyadav198613 I tried to install and run the app but it didn't work when I switched the internet off. It works only with working internet connection.

Also, when "installing" NGRX via chrome - is it possible to copy the installation to another machine? I would like to download the offline docs at one computer (the one with internet connection) and run it at the other one that has no internet connection.
Thanks a lot for your help so far 🥇

**Comment by santoshyadav198613** [comment]
Hi @Hermel,

I tested it as well, looks like few resources are not available when offline, @brandonroberts I will look into this, if you have any pointers please share.

Regards, 
Santosh

**Comment by timdeschryver** [comment]
I haven't tested this, but you should be able to clone this repository, `cd` into `projects/ngrx.io` and follow the [CI steps](https://github.com/ngrx/platform/blob/master/.circleci/config.yml#L121) in order to build the website.

Or maybe the easiest way would be to just download the build version of the website at https://github.com/ngrx/ngrx-io-builds

**Comment by santoshyadav198613** [comment]
> I haven't tested this, but you should be able to clone this repository, `cd` into `projects/ngrx.io` and follow the [CI steps](https://github.com/ngrx/platform/blob/master/.circleci/config.yml#L121) in order to build the website.
> 
> Or maybe the easiest way would be to just download the build version of the website at https://github.com/ngrx/ngrx-io-builds

Yes this is another way, but if we are providing the site as PWA and most if the contents are static, it should work offline.

**Comment by timdeschryver** [comment]
Yea, but the problem is that the computer he wants to use doesn't have an internet connection. Thus he can't visit the page and install the PWA.

**Comment by santoshyadav198613** [comment]
May be he wants to download it for the one time using internet @Hermel am i right?

**Comment by Hermel** [comment]
Hey,
I'll clarify the request more -
I would like to download the pwa/runnable version of the docs in computer A (which has a working internet connection) and transfer it by DOK to computer B which has no internet connection at all. Therefore it is not possible to download one time with internet connection as @santoshyadav198613 suggested

**Comment by santoshyadav198613** [comment]
Ok @Hermel ,

In that case the below option works fine. tested locally only issue you may get is the bootstrap css url which will not be loaded on other machine, i would suggest make some changes in index.html by downloading the bootstrap and referring the same from your local folder. Than you can copy it on other machine and it will work.

Or maybe the easiest way would be to just download the build version of the website at https://github.com/ngrx/ngrx-io-builds

**Comment by brandonroberts** [comment]
I think this issue would be better discussed in the chat room https://gitter.im/ngrx/platform
