### ISSUE TITLE
Docs: create example from stackblitz fork in tutorial

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1702]
Currently we link to a forked StackBlitz here https://stackblitz.com/fork/ngrx-start. This should be placed under the ngrx.io/content/examples folder so we can modify it and send the user to a generated stackblitz link.

- Download the example from StackBlitz
- Extract the folder contents into the ngrx.io/content/examples/ngrx-start folder
- Create an empty `example-config.json` file
- Create a `stackblitz.json` file similar to the one in the `store` folder
- Replace link in tutorial with live example component

```html
<live-example name="ngrx-start"></live-example>
```

**Comment by santoshyadav198613** [comment]
Hi @brandonroberts ,
can i take this up.

**Comment by brandonroberts** [comment]
Sure!

**Comment by santoshyadav198613** [comment]
Hi @brandonroberts,
PR open for review.
