### ISSUE TITLE
Docs: update example dependencies to version 8

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1703]
The dependencies for the generated examples need to be updated with the upcoming release. The `package.json` file is located in the `projects/ngrx.io/tools/examples/shared` folder. 

- [ ] Update the Angular dependencies to latest 
- [ ] Update the NgRx dependences to latest
- [ ] Run yarn in the `shared` folder to update the `yarn.lock` file

**Comment by jtcrowson** [comment]
Should we wait until 8.0 is released?  Or use the beta version?

**Comment by brandonroberts** [comment]
Beta is fine. We'll do another pass once 8.0 goes final

**Comment by jtcrowson** [comment]
Cool, I'll update with Angular 8.0.0-beta.11 and NgRx 7.4.0
