### ISSUE TITLE
Docs: V7 update guide needs to mention minimum dependencies

### ISSUE THREAD

**Issue by dollyshah-02** [ngrx/platform#1705]
### In our gitter support channel at https://gitter.im/ngrx/platform

ERROR in node_modules/@ngrx/store/src/models.d.ts(31,43): error TS1005: ';' expected. node_modules/@ngrx/store/src/models.d.ts(31,67): error TS1005: ',' expected.

**Comment by go2theG** [comment]
I had the same when using Angular 6 with ngrx/store 7.

Downgrade ngrx/store to Version 6. Or upgrade Angular to version 7.

**Comment by brandonroberts** [comment]
@go2theG is correct. If you are using V7, you must upgrade to Angular V7. V6 works with Angular 6 and 7, but you'll get a peer dependency warning with Angular 7.

Would either one of you like to submit a PR to add the minimum dependencies to the V7 update guide similar to what's in the V6 update guide?

**Comment by dollyshah-02** [comment]
It is working fine after upgrading my angular version..Thank you guys.
