### ISSUE TITLE
Docs: Add section to Effects overview about using state with effects

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1714]
A section on using state with effects would be useful.

- Include an explanation that Effects in general, should only rely on the Action and associated metadata for handling the Effect.
- When you need to use state, use a flattening operator into another Observable so that the selector isn't immediately fired
- Include an example

Based on conversation from https://github.com/ngrx/platform/issues/1713

**Comment by jtcrowson** [comment]
I can take this.  Should we just increase the scope of the documentation created in #1708?

**Comment by brandonroberts** [comment]
Just create a new PR instead. That one has already been merged

**Comment by jtcrowson** [comment]
Will do.  I'll add this documentation in the same section of the Effects -> Testing.

**Comment by brandonroberts** [comment]
It should go in the overview guide and possibly link to the testing section
