### ISSUE TITLE
devtools doesn't work

### ISSUE THREAD

**Issue by genu** [ngrx/platform#1717]
## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by LuukMoret** [comment]
It is not working for me either when using `createAction()`, did you manage to solve this?

**Comment by alex-okrushko** [comment]
@LuukMoret example-app that is packaged with NgRx is using `createAction`. I just double checked and devtools show all the action in both JiT and AoT modes.
What's exactly not working?

**Comment by LuukMoret** [comment]
I refactored a small part of my application from Actions with Enums and classes to the createAction function with ngrx 7.4. The Redux DevTools plugin is saying "No Store found". When I revert these changes the DevTools plugin is working again. I think the example app is based on the master branch and not 7.4, not sure if this has anything to do with it.

I'll try to find any other difference between the example app and my application to see where the problem might be coming from

**Comment by LuukMoret** [comment]
Nevermind, I found the problem. In one of my map functions inside an effect I just referenced the actionCreator instead of actually invoking it!
