### ISSUE TITLE
Router-store initialization remove all data from the store.

### ISSUE THREAD

**Issue by izmaylovdev** [ngrx/platform#1722]
## Minimal reproduction of the bug/regression with instructions:
"@ngrx/router-store/request" action removes all data from store
![image](https://user-images.githubusercontent.com/14952947/55877208-24b23880-5ba2-11e9-8548-1b72d6273753.png)

## Expected behavior:
All data not related to the router will remain untouched.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
    "@agm/core": "^1.0.0-beta.5",
    "@angular/animations": "^7.2.12",
    "@angular/cdk": "^7.3.7",
    "@angular/common": "^7.2.12",
    "@angular/compiler": "^7.2.12",
    "@angular/core": "^7.2.12",
    "@angular/forms": "^7.2.12",
    "@angular/http": "^7.2.12",
    "@angular/material": "^7.3.7",
    "@angular/platform-browser": "^7.2.12",
    "@angular/platform-browser-dynamic": "^7.2.12",
    "@angular/platform-server": "^7.2.12",
    "@angular/router": "^7.2.12",
    "@ngrx/effects": "^7.4.0",
    "@ngrx/router-store": "^7.4.0",
    "@ngrx/store": "^7.4.0",
    "@ngrx/store-devtools": "^7.4.0"

**Comment by brandonroberts** [comment]
Router Store on its own does not alter state. Please provide a reproduction of the issue

**Comment by izmaylovdev** [comment]
Found mistake in my code... sorry for disturb...

**Comment by brandonroberts** [comment]
👍
