### ISSUE TITLE
How to use data store in route resolver

### ISSUE THREAD

**Issue by rezord** [ngrx/platform#1729]
How can I use the NGRX store in route resolver? I have a route resolver and before it loads an Id from service and then it calls several API calls and adds them as observable with fork-join. But know I need to wait for the result of the store and then call these APIs.

I have the following code in my resolver and it works fine but the only problem is in the component I should subscribe for this data and when the component loads the data still is not available.

return this.store.select(getSelectedCompanyId).pipe(take(1)).toPromise().then(companyId => {
      observables.push(this.storeDataService.getDate().pipe(map(data => CurrentDate = data)));
      observables.push(this.authService.getPriorityStatus().pipe(map(data => PriorityStatuses = data)));
      return observableForkJoin(observables).pipe(map(data => {
        return {
          PriorityStatuses: PriorityStatuses,
          CurrentDate: CurrentDate          
        };
      }));
    });
  }

**Comment by timdeschryver** [comment]
See Todd Motto's post [https://ultimatecourses.com/blog/preloading-ngrx-store-route-guards](https://ultimatecourses.com/blog/preloading-ngrx-store-route-guards).

Support questions should be asked on [stackoverflow (with a ngrx tag)](https://stackoverflow.com/questions/tagged/ngrx) or the [gitter channel](https://gitter.im/ngrx/platform).
