### ISSUE TITLE
Docs: example-app stackblitz link is broken in README

### ISSUE THREAD

**Issue by jtcrowson** [ngrx/platform#1730]
## Minimal reproduction of the bug/regression with instructions:

The stackblitz link in the [example-app README](https://github.com/ngrx/platform/blob/master/projects/example-app/README.md) leads to a 404 page.

Broken link: https://ngrx.github.io/platform/stackblitz.html

## Expected behavior:

Should lead to the example-app in stackblitz.

## I would be willing to submit a PR to fix this issue

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
I think this might be my fault when I accidentally deleted the `gh-pages` branch.
@brandonroberts I can't set the github pages branch in the project settings, I think this should be resolved if you could enable it 😄

**Comment by alex-okrushko** [comment]
It's working now
