### ISSUE TITLE
Set delay to Effects

### ISSUE THREAD

**Issue by dejooo13** [ngrx/platform#1731]
Hello, i have a question how could i make some delay for GetShop effect because i need token for http request to be valid? Dunno if there is any other way of doing it.. Thanks in advance
`@Effect()
  Login: Observable<any> = this.actions
    .ofType(AuthenticationActionTypes.LOGIN)
    .pipe(
      map((action: Login) => action.payload),
      mergeMap(payload => {
        return this.authenticationService.login(payload.email, payload.password)
        .pipe(
          concatMap((user) => {
            return [
              new LoginSuccess({token: user.token}),
              new GetShop(user)
            ];
          }),
          catchError((error) => {
            return of(new LoginFailure({ error: error }));
          }));
    }));

  @Effect({ dispatch: false })
  GetShop: Observable<any> = this.actions.pipe(
    ofType(ShopSettupActionTypes.GET_SHOP),
    switchMap((payload) => {
      return this.formDataService.getShop()
      .pipe(tap((user) => {
        console.log(user);
      }));
    })
  );`

**Comment by timdeschryver** [comment]
Support questions should be asked on [stackoverflow (with a ngrx tag)](https://stackoverflow.com/questions/tagged/ngrx) or the [gitter channel](https://gitter.im/ngrx/platform).
