### ISSUE TITLE
Docs: Add instructions for using ng add for schematics

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1739]
Similar to what we have on the installation page for the other libraries:

- Document that you can use `ng add @ngrx/schematics`
- It prompts you to make them your default
- The changes that occur after the schematics are run

**Comment by santoshyadav198613** [comment]
Hi @brandonroberts ,
Taking this up.

**Comment by santoshyadav198613** [comment]
Hi @brandonroberts ,
Open for review, hope i made the change to correct file.
