### ISSUE TITLE
Example: Reorganize into feature folders for state management

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1741]
Related to #861 

Currently, the example app is structured where the entire state management infrastructure is included in each particular feature folder. The proposed change is to restructure the state management parts into separate feature folders under `src/app/shared/state` instead of `src/app/reducers`. The rationale being that `reducers` are an implementation detail of how you manage state changes and not the state itself. This would be clearer to glance at and what the main purpose of NgRx is for, being shared state. It would also make it more clear that the 

Example File Structure

```bash
├── src
│   ├── auth
│   │   ├── actions
│   │   │   ├── auth.actions.ts
│   │   │   ├── index.ts
│   │   ├── auth.effects.ts
│   │   ├── auth.module.ts
│   ├── shared
│   │   ├── state
│   │   │   ├── auth.reducer.ts
│   │   │   ├── index.ts
```

**Comment by jtcrowson** [comment]
I agree it would be clearer that shared state is the main purpose, but it might be less clear that some state (books) can and should be lazy-loaded along with a given feature module.

**Comment by alex-okrushko** [comment]
```
│   │   ├── actions
│   │   │   ├── auth.actions.ts
│   │   │   ├── index.ts
```
Any reason why actions are put into their own folder? Why not flatten them and drop the `index.ts`:
```
│   ├── auth
│   │   ├── auth.actions.ts
│   │   ├── auth.effects.ts
│   │   ├── auth.module.ts
```
Or even drop the prefixes altogether  (we see the folder name in the file path):
```
│   ├── auth
│   │   ├── actions.ts
│   │   ├── effects.ts
│   │   ├── module.ts
```
That's what I already do in my project 😛

**Comment by timdeschryver** [comment]
Would an effect also qualify as shared? Could it be compared with a reducer, as it also listens to all dispatched actions?

**Comment by fxck** [comment]
> ```
> │   │   ├── actions
> │   │   │   ├── auth.actions.ts
> │   │   │   ├── index.ts
> ```
> Any reason why actions are put into their own folder? Why not flatten them and drop the `index.ts`:
> 
> ```
> │   ├── auth
> │   │   ├── auth.actions.ts
> │   │   ├── auth.effects.ts
> │   │   ├── auth.module.ts
> ```
> Or even drop the prefixes altogether (we see the folder name in the file path):
> 
> ```
> │   ├── auth
> │   │   ├── actions.ts
> │   │   ├── effects.ts
> │   │   ├── module.ts
> ```
> That's what I already do in my project 😛

I would stick with prefixes, makes it easier to search. And I also use a flat structure, as long as there is only a single file for a type, I nest it where there are more.

ie.

```
│   ├── users
│   │   ├── actions
│   │   │   ├── user-list.action.ts
│   │   │   ├── user-detail.action.ts
│   │   ├── users.effects.ts
│   │   ├── users.module.ts
```

**Comment by alex-okrushko** [comment]
> I would stick with prefixes, makes it easier to search.

I think searching for `auth/actions` is as easy as `auth.actions`, at the same type imports look nicer:

`import * actions from 'path/to/auth/actions'`
vs
`import * actions from 'path/to/auth/auth.actions'`

**Comment by brandonroberts** [comment]
Will take a look at a new example app at some point.
