### ISSUE TITLE
Docs: Add overview page for @ngrx/data

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1749]
Similar to our other pages, `@ngrx/data` needs general doc pages.

What `@ngrx/data` is, why you might want to use it
Key concepts
Initial Usage

All this information can be ported from https://github.com/johnpapa/angular-ngrx-data

Create a new folder under `projects/ngrx.io/content/guide` named `data`.
Create an `index.md` for the overview page.
Add a section in the `projects/ngrx.io/content/navigation.json` for `Data` below the `Entity` section.

**Comment by jtcrowson** [comment]
I can pick this up

**Comment by brandonroberts** [comment]
👍
