### ISSUE TITLE
Docs: Add installation page for @ngrx/data

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1750]
Follow-up to #1749 

How to install it using 

- ng add
- npm install
- yarn add

No schematics yet.

Create a new folder under `projects/ngrx.io/content/guide` named `data`.
Create an `installation.md` for the installation page.

**Comment by jtcrowson** [comment]
I can grab this!

**Comment by jtcrowson** [comment]
Done, just waiting on merge of #1767
