### ISSUE TITLE
How do you add a store to a library if you are following Angular 6+ structure of creating libs?

### ISSUE THREAD

**Issue by frontr-uk** [ngrx/platform#1760]
How do you add a store to a library if you are following Angular 6+ structure of creating libs?

I've tried for example `ng generate @ngrx/schematics:store Organisation --feature --module ../../projects/exui-organisation/src/lib/exui-organisation.module.ts`

**Comment by brandonroberts** [comment]
Provide the `project` and relative path to the module

```
ng generate @ngrx/schematics:store Organisation --feature --project exui-organisation --module exui-organisation.module.ts
```
