### ISSUE TITLE
Docs: Add section to Store testing guide on using mock selectors

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1761]
Follow-up to #1688 

You can mock selectors along with mocking the store for a fully isolated unit test.

- Document supported selectors
- Add examples to `projects/ngrx.io/content/examples/testing-store` to use in guide

Here is a StackBlitz example for testing with NgRx https://stackblitz.com/edit/ngrx-testing-template

**Comment by damienwebdev** [comment]
@brandonroberts I can tackle this, but I need a little more information to cover what I think will be a common case I described in #1778.

**Comment by jtcrowson** [comment]
@damienwebdev are you interested in pairing on this?  I could document the supported selectors and you could follow with the example in #1778 when you get it figured out?

**Comment by damienwebdev** [comment]
@jtcrowson yea, for sure. I already have a working example, so I'm good to add it to whatever docs you start. Let me know how you want to address merging them together. I figure I can just branch off your starting point when you submit your PR.

**Comment by jtcrowson** [comment]
@damienwebdev sounds good to me!
