### ISSUE TITLE
docs: remove ngrx-data and ngrx-store-freeze from resouces

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#1768]
## Other information:

Remove `angular-ngrx-data` and `ngrx-store-freeze` from the resources page at https://ngrx.io/resources because these are now built into ngrx.

The data from the resources pages comes from https://github.com/ngrx/platform/blob/master/projects/ngrx.io/content/marketing/resources.json

Put a comment here if you're willing to pick this one up.

**Comment by monsij** [comment]
Interested! @timdeschryver

**Comment by timdeschryver** [comment]
It's all yours @monsij 😄

**Comment by monsij** [comment]
The issue title has a typo btw :-) --: resources
