### ISSUE TITLE
Schematics: Missing type for Union

### ISSUE THREAD

**Issue by mikezks** [ngrx/platform#1774]
## Minimal reproduction of the bug/regression with instructions:

Using `ng g @ngrx/schematics:feature +state/app --group -c` to generate a feature state with new `createAction()` results in following code:

`export Union = typeof all;`

## Expected behavior:

Should be:

`export type Union = typeof all;`

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

`"@ngrx/schematics": "8.0.0-beta.0"`

## I would be willing to submit a PR to fix this issue

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Before picking this up, do we want to use `union` to export the actions or are we simply going to export the action creators?

**Comment by mikezks** [comment]
Good point, the new ``createReducer()`` does not need to have the action union type definition.

Maybe it would avoid possible errors to use the union type in the reducer function as well.

See https://github.com/ngrx/platform/pull/1746 discussion about the state type.

**Comment by brandonroberts** [comment]
This adds reducers with `createReducers` and doesn't include any unions as we don't explicitly need them. https://github.com/ngrx/platform/pull/1785

**Comment by timdeschryver** [comment]
This is resolved via #1785.
