### ISSUE TITLE
How to Include Store Enhancers?

### ISSUE THREAD

**Issue by bradyshutt** [ngrx/platform#178]
I'm trying to apply a "store enhancer" to my Redux store that will manage the responsive state of my app ([redux-responsive](https://github.com/AlecAivazis/redux-responsive)). 

It looks like the way to do this in plain Redux is to just include the enhancer in the call to createStore: `createStore(reducer, [preloadedState], [enhancer])`. 

However, setting up the ngrx store asks us to use provideStore: `StoreModule.provideStore(reducer: any, initialState?: any)`, which does not accept any enhancers. 

Can store enhancers be applied to the ngrx store? If so, how?

**Comment by karptonite** [comment]
I think you may be looking for meta-reducers, although I haven't tried to use any enhancers myself:
https://github.com/ngrx/platform/blob/master/docs/store/api.md#meta-reducers

**Comment by bradyshutt** [comment]
Thanks, I think I just got tripped up by the different nomenclature. You're right, it seems like a "Store Enhancer" is essentially just a meta-reducer.

**Comment by bradyshutt** [comment]
After looking into this more, I no longer think these are the same thing.

I think the ngrx router-store is an example of a store enhancer, and it seems to mirror the behavior of the [redux-responsive](https://github.com/AlecAivazis/redux-responsive) repo I mentioned above. Internally, `redux-responsive` wants to set up media query listeners to the browser window, listening for changes to the "responsive state", and then dispatch actions to the store when changes are detected. 

Store enhancers seem to be a way to add additional functionality to the store. But since the store creation process is handled internally by ngrx (ie, `StoreModule.forRoot(reducers, <initial_state>`), it seems like the only way to add these store enhancers to the ngrx store is to create a `Store<feature_enhancement>ConnectingModule` class that imports `Store`, and sets up the appropriate bindings, just like the ngrx-router does.
