### ISSUE TITLE
Router Store: Store confirmed state (state on NavigationEnd) explicitly

### ISSUE THREAD

**Issue by MaximSagan** [ngrx/platform#1784]
We should be able to differentiate tentative router state (state on RoutesRecognized, that can be reverted in the case of NavigationCancel/NavigationError) and confirmed state (state on NavigationEnd, that we can be sure will not changed until we have a new navigation cycle).

The reason this is beneficial is that there are cases where we need to deal with both the tentative router state and the confirmed router state at the same time.

### Example scenario
- The current view of the "product listing page" depends on a specific route param (e.g. a product ID) that is coming from router state, e.g. "/product-listing/{categoryId}"
- A link on the page points via URL to another page with route guards enabled. These route guards trigger a modal/lightbox. This modal contains components that depend on route params from the requested (tentative) route, e.g. "/my-products/{productId}"
- While this lightbox is open, the product listing page must maintain its state.

Therefore, we must have access to both the tentative state (for the lightbox) and the "confirmed state" (for the currently displayed product listing page underneath the lightbox).

## Describe any alternatives/workarounds you're currently using

Use a separate slice of state (one not managed by NGRX Router Store) to store listen for the ROUTER_NAVIGATED action and store the confirmed router state.

## Other information:

#816 is certainly tangentially related, and was supposedly fixed by #1267. However, this fix only introduces a flag that allows you to delay the state update from RoutesRecognized to NavigationEnd, an either-or situation (update early or update late). Clearly, in the above-described scenario, this does not suffice, as if we delay the state update to NavigationEnd, the modal used for the route guard will not be able to access any data related to the requested route.

## If accepted, I would be willing to submit a PR for this feature

[X] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
We may revisit this at some point, but closing for now.
