### ISSUE TITLE
Build: Update TypeScript to 3.4.x and RxJS to 6.5.x

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1788]
Update the versions for the dependencies so we'll be using the latest that the Angular framework uses upon release.

- Update necessary `package.json` files for the repo and examples
- Update Bazel [dependency versions](https://github.com/ngrx/platform/blob/master/tools/defaults.bzl#L10)
- Update the [migration guide](https://github.com/ngrx/platform/blob/master/projects/ngrx.io/content/guide/migration/v8.md) for v8 with the new versions
- Fix any necessary changes for TS 3.4.x

**Comment by santoshyadav198613** [comment]
Hi @brandonroberts ,

Should i give it a try.

**Comment by santoshyadav198613** [comment]
Hi @brandonroberts ,
Should i also remove "core-js": "^2.5.4", as Angular Cli 8 does not depends on it anymore.

**Comment by brandonroberts** [comment]
Not yet. We'll update that in a separate pass once CLI goes final
