### ISSUE TITLE
Docs: Add link to blog in nav bar and update footer link

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1790]
Make blog link more prominent in top bar

- Add link to nav bar to https://blog.ngrx.io
- Update link in footer to point to https://blog.ngrx.io instead of https://medium.com/@ngrx

**Comment by jtcrowson** [comment]
Got it 👍

**Comment by Edouardbozon** [comment]
Oops I made a PR at the same time :confused:

**Comment by brandonroberts** [comment]
💣
