### ISSUE TITLE
....@ngrx/entity: The entity passed to the selectId implementation returned undefined. You should probably provide your own selectId implementation. The entity that was passed:

### ISSUE THREAD

**Issue by amitcdubey** [ngrx/platform#1794]
this is my model

export interface SampledataModel {
uuidValue?: string;
id?: number;
name?: string;
surname?: string;
age?: number;
mail?: string;
size?: number;
page?: number;
searchTerms?: any;
sort?: any[];

}

my reducer

export interface SampleDataState extends EntityState<SampledataModel> {
selectedSampleId?: number;
loaded: boolean;
loading: boolean;
textMessage: string;
}
export const adapter: EntityAdapter<SampledataModel> = createEntityAdapter<
SampledataModel

({
selectId: (sampleid: SampledataModel) => sampleid.id,
sortComparer: false,
});

export const initialState: SampleDataState = adapter.getInitialState({
selectedSampleId: undefined,
loaded: false,
loading: false,
textMessage: undefined,
});

export function reducer(
state: SampleDataState = initialState,
action: SampleDataAction,
): SampleDataState {
switch (action.type) {
case SampleDataActionTypes.SET_CURRENT_CONTACT_ID: {
return {
...state,
selectedSampleId: action.payload.id,
};
}
case SampleDataActionTypes.LOAD_DATA_SUCCESS: {
return adapter.addAll(action.payload.sampledataModel, state);
}
case SampleDataActionTypes.LOAD_DATA: {
return adapter.addOne(action.payload, {
...state,
selectedSampleId: action.payload.id,
});
}
default: {
return state;
}
}
}
export const getSelectedUserId: any = (state: SampleDataState) =>
state.selectedSampleId;

**Comment by brandonroberts** [comment]
Support questions should be asked in the [gitter chatroom](https://gitter.im/ngrx/platform)

**Comment by amitcdubey** [comment]
i posted but no one answering me there thatsy i posted here ,since 2 days am trying but now able to understand that what is happening in my code

**Comment by rip222** [comment]
> i posted but no one answering me there thatsy i posted here ,since 2 days am trying but now able to understand that what is happening in my code

so why did you get that warning? what was the cause?
