### ISSUE TITLE
@ngrx/router-store, migration to 4.x: how do I call a route change in an effect?

### ISSUE THREAD

**Issue by samueledirito** [ngrx/platform#180]
Before there was a go action I use this way:

```
import { go } from '@ngrx/router-store';
...
@Effect()
logoutSuccess$: Observable<Action> = this.actions$
  .ofType(authentication.LOGOUT_SUCCESS)
  .map(_ =>
    go('/login')
  );
```

There's no "go" action anymore in new releases and the examples are not showing anything similar to this. Is still possible?
Thank you!

**Comment by littleStudent** [comment]
https://github.com/ngrx/platform/issues/107
> There isn't a replacement for those actions in V4 and that's for consistency. You should use the router navigation syntax as normal. If you're using the actions in effects, you would inject the Router and use it to navigate rather than dispatching an action that tells the router to navigate.

**Comment by pjmagee** [comment]
The migration guide should probably have mentioned this but it doesnt.

**Comment by samueledirito** [comment]
This is the solution I adopt:
```
    .do(_ => this.router.navigate['/login']);
```
but the app stop working, freezing the browser. Looking at the stacktrace, it seems that the call to "do" method starts a loop. I'm sure to do something wrong, but maybe could be a bug in library.
Do you have any example code?

**Comment by pjmagee** [comment]
Your action LOGOUT_SUCCESS is being sent and then received again. You could potentially add 

`@Effect({ dispatch: false })` to this effect.

**Comment by samueledirito** [comment]
Ok, amazing answer! Thank you very much, I'm really happy to see my app working after all these refactorings!!! :D
