### ISSUE TITLE
Inconsistency between documentation, code, angular schematic and example app

### ISSUE THREAD

**Issue by dakipro** [ngrx/platform#1800]
First I must say I very much appreciate hard work everyone is contributing to the library, I really love the concept of it and try to use it where it makes sense. 
I also like that effort is being put into reducing the setup code, f.eks. using the "createAction" to reduce the amount of code needed for initial setup and maintaining. https://github.com/ngrx/platform/blob/87b895aa56e79485f75779204ab47fb2a6158bc5/projects/example-app/src/app/books/actions/book.actions.ts#L4

I also noticed that there is possibility to use "createReducer" here https://github.com/ngrx/platform/blob/8f2cb7bb8605c34ee023498cb48d88f7e3891211/projects/example-app/src/app/books/reducers/search.reducer.ts#L21

However, the "createReducer" doesn't seem to be inside the 7.4 version of the store, I guess that "ReducerManager" is some sort of replacement/alternative?
None of these is mentioned in the documentation. Angular schematic still creates files the "usual" way. 

I've been using the ngrx on and off now for a year or so, and documentation was always the biggest issue for me adopting it properly. That and amount of code for achieving simple things, but I am glad that helper functions like "createAction" are coming. 

For someone beginning with ngrx/redux, the documentation on ngrx.io is ok (search would be nice) but it can only be used as a introduction to the concept, for real life usage the only place to find relevant info is the example-app, but right now it doesn't seem to be aligned with the documentation or the platform itself. 

Perhaps example-app is ahead of its time in the master branch? Or should I be looking at some other branch? Or am I missing something obvious?

**Comment by timdeschryver** [comment]
Hi, we're currently working on version 8 of NgRx, with the first beta just released last week.

The example-app is built in the `master` branch, which contains the code for the new features like the `createReducer` function. 

We're also busy updating our docs, the version on ngrx.io are the docs for NgRx version 7.4.0 (which had the `createAction`). You can take a look at https://next.ngrx.io to access the docs for the beta version.

**Comment by dakipro** [comment]
Thank you for your answer @timdeschryver , I somehow assumed that the master branch was actually stable (7.4).
