### ISSUE TITLE
Split alternative implementations to alternative example app / documentation

### ISSUE THREAD

**Issue by montella1507** [ngrx/platform#1804]
Due to version 8.0 and alternative implementations of reducers , actions and effects (createReducer, createAction, createEffect) there may be two versions of example-app + 2 versions of documentation:

Reasons:
- if is is alternative syntax (as it is explained in pull requests etc), there should be 2 example apps / documentations
- it may be difficult for newbies in functional programming / new typescript users
- it is less descriptive, especially for reducers containing non-primitive logic (branching, cykles...) 
- keep it as alternative please - lightweight, more functional way

Let your developers choose the way that is most suitable for their case.

Still want o let you know, version 8.0 seems to be very promising to me,  common boilerplate for store is sometimes non-ignorable problem for developers to adopt unidirectional data-flow,  redux pattern, etc.. , so they have now the way how to eliminate big chunk of it.  

Very appreciated.

**Comment by brandonroberts** [comment]
Thanks for the feedback @montella1507 .The example app contains best practices and is what we generally recommend. There are other alternatives provided by the community that offer different types of example apps. The choice is still up to the developers on which is most suitable for them. The documentation will highlight the differences between the previous and current approaches, but maintaining two versions is not a viable option.

**Comment by montella1507** [comment]
@brandonroberts  are you sere you are all to mark that as best practice already? I have seen your 7-15days old discussions and i have realized you are still not sure it will be better?
