### ISSUE TITLE
Docs: Add guide on adding NgRx to an existing app

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1807]
Have seen this asked more than a few times. We need a guide that takes a relatively small app (maybe similar to the new Angular tutorial 😉) that is just using services, and walk through introducing NgRx into the app, and migrating the state from the services to the Store.

**Comment by jtcrowson** [comment]
I can take this. @brandonroberts Under which directory would you like it added?

**Comment by brandonroberts** [comment]
Under `guide/store/recipes` will work.

**Comment by andrewevans0102** [comment]
I talked to @brandonroberts today on twitter, and he was good with me taking this one over.  I'm going to work on this and should have a PR ready in the near future.

**Comment by Armenvardanyan95** [comment]
I am willing to write this guide if the previous effort has been discontinued

**Comment by jtcrowson** [comment]
> I am willing to write this guide if the previous effort has been discontinued

Feel free!

**Comment by JeromeWirth** [comment]
To become more familar with NgRx, i recently added NgRx to the Angular Getting Started Tutorial Project (https://angular.io/start/start-data). If i add some explaining it could make a good tutorial. I'm willing to create a PR for it, if nobody works on it right now.

**Comment by timdeschryver** [comment]
Since this issue has been opem for quite some time.
