### ISSUE TITLE
Filter effects based on route

### ISSUE THREAD

**Issue by alexxxxOG** [ngrx/platform#1811]
I have the following scenario: 

I want some of the effects to trigger only when that module/component is active. Is there any more global way for a set of effects (specifically related to a feature module) not to trigger based on some logic (eg. the current route)?

Thanks.

**Comment by timdeschryver** [comment]
Hi, I think what you're looking for is [OnRunEffects](https://ngrx.io/guide/effects/lifecycle#onruneffects).

If you have a question about it feel free to join our [gitter channel](https://gitter.im/ngrx/platform).
