### ISSUE TITLE
Usage of incorrect @params tag

### ISSUE THREAD

**Issue by santoshyadav198613** [ngrx/platform#1812]
Few tags are incorrect like one below jsdoc has @param, not @params tag
https://github.com/ngrx/platform/blob/master/modules/data/src/dispatchers/entity-commands.ts#L75
## I would be willing to submit a PR for the docs :heart:

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Thanks for noticing this @santoshyadav198613 , feel free to create a PR with the needed changes.
