### ISSUE TITLE
Dependencies on Material and Angular? 

### ISSUE THREAD

**Issue by montella1507** [ngrx/platform#1813]
Why does NGRX 8.0 beta depend on @angular/material and concrete version of angular?   I think only one thing needed may be router?

https://github.com/ngrx/platform/blob/master/package.json#L89

I have got we have dependencies on angular, but why Material, why to force user to update 80% of libraries with new NGRX?

**Comment by goenning** [comment]
That package.json is used by this repository for many things, including the example-app, which uses Full Angular and Material

The package.json you’re probably looking for is this one https://github.com/ngrx/platform/blob/master/modules/store/package.json which doesn’t have any dependency 

NPM registry is also not reporting any dependency for version 8 https://www.npmjs.com/package/@ngrx/store/v/8.0.0-beta.1

**Comment by montella1507** [comment]
Thank you very much!
