### ISSUE TITLE
Remove @angular/http dep

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#1821]
The `@angular/http` package has been deprecated.
From what I can see we're not depending on it, thus this can be removed?

**Comment by santoshyadav198613** [comment]
@timdeschryver let me try this one.

**Comment by santoshyadav198613** [comment]
Hi @timdeschryver ,
We need to wait I think till Angular 8 or update to angular 8.0 rc  as platform-server still depends on @angular/http.

https://github.com/angular/angular/blob/8.0.0-beta.10/packages/platform-server/package.json#L20

**Comment by timdeschryver** [comment]
The RC version has removed the dep - https://github.com/angular/angular/blob/8.0.0-rc.2/packages/platform-server/package.json

**Comment by santoshyadav198613** [comment]
Ok, I as not sure, but in that case, we need to update everything to rc.

**Comment by brandonroberts** [comment]
Fixed via #1795
