### ISSUE TITLE
Add test runs against g3 for each PR

### ISSUE THREAD

**Issue by alex-okrushko** [ngrx/platform#1828]
Similar to how Angular PRs are validated against g3 we could add tests runs for NgRx. That would make my life somewhat easier when merging master syncs and would validate PR against huge codebase that's using NgRx during review time.

### If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
Do you know much time this will add to our CI turnaround?

**Comment by alex-okrushko** [comment]
Not sure. Internally to run all the tests it takes about 2 hours to get on a train and then about an hour (maybe more) to ride it with all the tests.
We can look at the post-submit option - if it's available.
Or at non-blocking operation.
