### ISSUE TITLE
Example: Add examples of effects not based on the Actions stream

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1830]
Add more Observable based effects to show that Effects aren't restricted to listening to the `Actions` stream in order to return new actions. Some ideas:

- A session timeout effect that is trigger when the user is idle for some amount of time. If the timeout expires, it dispatches an action to log out the user that is handled in `AuthEffects`
- Listening to router events to update the page title on successful navigation. This would include adding page titles to the route configuration.

Open to other ideas about how to show this.

**Comment by adrianfaciu** [comment]
I can look into adding the examples for the ideas mentioned above.
