### ISSUE TITLE
createFeatureSelector -> undefined / beta 8-1 / angular 7

### ISSUE THREAD

**Issue by adrienpsl** [ngrx/platform#1835]
Hello,
I need some help with  __createFeatureSelector__ 
 
1. I copy the entire feature Auth repo from the exemple-app, 
2. Import lazy this module, with the path 'auth'
3. When I go to http://localhost:4200/auth/login I get :
    core.js:15724 ERROR TypeError: Cannot read property 'status' of undefined
    at index.ts:31

``` export const selectAuthState = createFeatureSelector<State, AuthState>("auth"); ```
return undefined, but my store (check with reduxDevTools) is filled with the authStore . 

this does not occur if I import the module in AppModule

Is this a compatibility problem with the beta 8 and Angular 7 ?

Here a repo with the reproduction:
https://github.com/adrienpsl/bug-lazy-loading-ngrx-sample-project
I didn't succeed to upload the all repo on Stackblitz. 

__thanks by advance ! :)__

**Comment by timdeschryver** [comment]
I believe this is indeed a compatibility problem.
Have you tried upgrading Angular?

**Comment by brandonroberts** [comment]
Below are the valid combinations.

- NgRx version 8, and Angular version 8
- NgRx version 7, and Angular version 8

**Comment by adrienpsl** [comment]
ok, I will upgrade my Angular version !
thanks !

**Comment by rosstimothy** [comment]
Am seeing something similar with 
   -  "@ngrx/store": "^8.0.1",
   -  "@angular/common": "^8.0.2",

I have a lazy loaded module, and createFeatureSelector for that module is returning undefined. If I import the module directly into app.module everything works fine.

**Comment by timdeschryver** [comment]
@rosstimothy could you create a reproduction for the problem, so we can investigate it?
