### ISSUE TITLE
Warning during compiling doc portal

### ISSUE THREAD

**Issue by santoshyadavdev** [ngrx/platform#1840]
## Minimal reproduction of the bug/regression with instructions:

Run yarn serve-and-sync you will notice below warning

WARNING in ./src/app/custom-elements/code/pretty-printer.service.ts 16:12-50
System.import() is deprecated and will be removed soon. Use import() instead.
For more info visit https://webpack.js.org/guides/code-splitting/
i ｢wdm｣: Compiled with warnings.

## Expected behavior:

Should compile without warning

## I would be willing to submit a PR to fix this issue

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
Going to leave this as is
