### ISSUE TITLE
Update doc portal to Angular 8

### ISSUE THREAD

**Issue by santoshyadav198613** [ngrx/platform#1843]
## Other information:

Doc portal is on Angular 7, let's update to Angular 8.

## I would be willing to submit a PR for the docs :heart:

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
Good idea. We'll hold off on this until after 8 goes final, as it will be part of a larger change to sunc up the infrastructure stuff.

**Comment by santoshyadav198613** [comment]
I will start this by next week.

**Comment by brandonroberts** [comment]
Don't start this one yet

**Comment by santoshyadav198613** [comment]
cool.

**Comment by Stephenradams** [comment]
Hi, is this still open? @santoshyadav198613 are you still planning on working on this? It seems like a good first PR, I would be interested in looking at this if you haven't started it?

**Comment by brandonroberts** [comment]
Don't start on this. We are evaluating whether to reboot the docs app with a simpler infrastructure for easier maintenance.

**Comment by brandonroberts** [comment]
Closed via https://github.com/ngrx/platform/pull/2391. I updated it while updating the dependencies for the next release. We are still evaluating docs app options.
