### ISSUE TITLE
Resubscribe to the Effects stream after unhandled error

### ISSUE THREAD

**Issue by alex-okrushko** [ngrx/platform#1851]
Based of https://github.com/ngrx/platform/issues/1224#issuecomment-489773880

We would have the `mapToAction` operator to make it harder to miss errors, however it would be beneficial to still re-subscribe to the Effect if the unhandled error did go throw. 

New behavior is helpful in 90% of the use cases, however, there are some where it might be surprising, for example if the stream has `startWith` operator it would be called again. For such corner cases we should provide the lever to turn it off, for example with additional `{resubscribeOnError: false}`, which would be part of the same config object as `{dispatch: boolean}`.

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Resolved by #1881
