### ISSUE TITLE
Update code samples

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#1853]
## Other information:

The code samples in the docs are using a switch-case reducer and are creating union types for the actions. We should update the docs to use `createReducer` and to only export the actions. Otherwise it could be confusing because there would be a mismatch between the docs and the example app.

![image](https://user-images.githubusercontent.com/28659384/57627761-e3de8280-7598-11e9-8646-31b52b9d8203.png)

## I would be willing to submit a PR for the docs :heart:

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by santoshyadav198613** [comment]
Leave upto me.

**Comment by santoshyadav198613** [comment]
Hi @timdeschryver ,
One question, sample apps use an older version of typescript, zone, and rxjs, as we need to update all ngrx packages to beta for this change, should I update of the packages, we are already using Angular Beta, should I update to rc?

**Comment by timdeschryver** [comment]
@santoshyadav198613 aren't the examples  using the latest version of NgRx (v8-beta.1)? If that's the case, you don't have to update the packages.

**Comment by santoshyadav198613** [comment]
Please ignore, I got confused with packages in doc portal.

**Comment by santoshyadav198613** [comment]
Stackblit for reference: https://yrgvpdlbmkn.angular.stackblitz.io
