### ISSUE TITLE
Router Store: Expose some selectors for selecting router info

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1854]
We already have a reducer to add router state on navigations, but don't provide any selectors to get the data out. We should provide a minimum set of selectors out of the box to get:

- query params
- route params
- route data
- url

The initial idea is that this would be a function that returns selectors for the items mentioned above, similar to `getSelectors()` in Entity.

**Comment by jtcrowson** [comment]
I can take it

**Comment by santoshyadav198613** [comment]
Hi @jtcrowson ,
Should I take it, I am done with my existing PRs.

**Comment by brandonroberts** [comment]
@jasonhodges is working this one already

**Comment by santoshyadav198613** [comment]
Hi @brandonroberts ,
He updated the comments, so just wanted to check with him.
