### ISSUE TITLE
Add search functionality for api similar to Angular

### ISSUE THREAD

**Issue by santoshyadav198613** [ngrx/platform#1860]
## Describe any alternatives/workarounds you're currently using

Looking into code samples.

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by wesleygrimes** [comment]
@santoshyadav198613 Just clarifying... You are requesting the ability to search the docs similar to how you can search on https://angular.io with the searchbox in the upper-right hand corner of the page?

**Comment by santoshyadav198613** [comment]
Yes @wesgrimes, if you think it makes sense, I will start working on it, once I close my existing PR.

**Comment by itayod** [comment]
@santoshyadav198613 consider use algolia its a nice search engine and its free for open sources
