### ISSUE TITLE
Inconsistent/missing docs on sources of effects

### ISSUE THREAD

**Issue by zakhenry** [ngrx/platform#1863]
## I would be willing to submit a PR for the docs :heart:

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

Hello, I've been thinking for a while about what valid sources of effects can be, and recently this topic has brought up opposing views within my team. Consulting the docs, I find conflicting information. The question is *Should effects always be triggered by an action, or is is valid to have effect sources be store selectors?*

The [next](https://next.ngrx.io/) documentation has the following statement:
> Note: Event streams are not limited to dispatched actions, but can be any observable that produces new actions, such as observables from the Angular Router, observables created from browser events, and other observable streams.

however, later examples in the same page, namely in the [incorporating state](https://next.ngrx.io/guide/effects#incorporating-state) section has examples that are exclusively triggered by actions, additionally with the statement
> However, there may be cases when the required metadata is only accessible from state. When state is needed, the RxJS withLatestFrom operator can be used to provide it.

If it is valid (or not) to have effects be directly driven by store selectors, this should be explicit, and examples given. Here's a made up example of where the problem lies, and why there is two separate implementation options.

---

Imagine a scenario in the @ngrx/platform example application where there is a requirement to implement an effect which updates the page title (what is shown in the browser tab) to display a combination of the user state and the selected book state. For arguments sake, let's say an example of the display string might be `Selected: War & Peace | Logged in as Zak` or `Browsing Books | Guest user`.

To get this string, we'd first create a selector
```ts
export const getPageTitle = createSelector(getSelectedBook, getUser, (book, user) => {
  return book ? `Selected: ${book.volumeInfo.title}` : 'Browsing Books' + ' | ' + user ? `Logged in as ${user.name}` : 'Guest user';
});
```

Lets assume there is a `PageTitleService` with the following interface
```ts
export class PageTitleService {
  setTitle(title: string): void;
}
```

Now we create an effect class, with two implementation options

```ts

export class PageTitleEffects {

  optionOne$ = createEffect(() => this.store.pipe(
    select(getPageTitle),
    tap(title => this.pageTitleService.setTitle(title))
  ), { dispatch: false });


  optionTwo$ = createEffect(() => this.actions$.pipe(
    ofType(
      ViewBookPageActions.selectBook,
      AuthApiActions.loginSuccess,
      AuthActions.logout,
    ),
    concatMap(action => of(action).pipe(
      withLatestFrom(this.store.pipe(select(getPageTitle))),
      tap(([action, title]) => this.pageTitleService.setTitle(title))
    )),
  ), { dispatch: false });
  
  constructor(private store: Store<any>,
              private actions$: Actions,
              private pageTitleService: PageTitleService) {}

}
```

---

Now, a discussion of the two options

### `optionsOne$`
\+ simpler
\+ store is the the source of truth
\+ any transition in state will cause the page title to correctly reflect the state
? effect doesn't care what caused the change of state
\+ extension to the business requirement of what is displayed _only_ occurs in the selector

### `optionTwo$`
\- more verbose
\+ it is clear what causes the page title to change (it can explicitly only be one of the three actions)
\- if a new action is introduced say `ViewBookPageActions.deselectBook` and the developer forgets to add it to the list of triggering actions, the page title will show the most recently selected book
\- changes to the requirements of display must occur in both the effect and selector
? feels more ngrx-y

---

I'm clearly biased towards `optionOne$`, however I'd like to start a healthy discussion about the options to clarify if I am missing something critically flawed in this option, or if this is the right way to do it, or if there is a third option that is yet to be discovered. 

Either way, I think the documentation should cover this use case, as it applies to a large number of different use cases from page titles, to notifications, to bindings to webgl frameworks, to analytics tracking/events etc etc.

**Comment by tyroneneill** [comment]
In agreement with `optionOne$`, definitely interested in drumming up healthy debate around this, anyone with more than a todo application must be having to have the same (sometimes internal) debate. 

It seems reasonable to react directly to changes to the store rather than to the actions that are used to derive the new state, it is also safer given the following example: 

`
    1. user dispatches ChangeTitleAction.
    2. reducer receives ChangeTitleAction and ignores (because it is invalid).
    3. effect receives ChangeTitleAction and acts upon it.
`

**Comment by timdeschryver** [comment]
FWIW, @adrianfaciu created a [PR](https://github.com/ngrx/platform/pull/1845/files) with examples for effects based on other streams.

I think having a recipe / examples about this topic in the docs might be helpful 👍

**Comment by timdeschryver** [comment]
I'm going to close this issue because it has been inactive, and we've added examples to the example app.
If someone wants to create docs for this, feel free to do so.
