### ISSUE TITLE
Docs: home page isn't responsive on some mobile screens

### ISSUE THREAD

**Issue by NachoVazquez** [ngrx/platform#1866]
## Other information:

Texts are cropped and aligned to the right at the home page of the documentation app for some mobile screens.

Reported on:

- Huawei P20 Lite
- iPhone XS Max
- Samsung Galaxy S5 (Chrome Dev Tools)
- iPhone5 (Chrome Dev Tools)
- iPhone6/7/8 (Chrome Dev Tools)

There is a similar issue that was closed: #1536

## I would be willing to submit a PR for the docs :heart:

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by wesleygrimes** [comment]
We will help you with the PR once you submit. Just reference this issue when you create it.
