### ISSUE TITLE
ERROR in node_modules/@ngrx/store/src/models.d.ts(30,58): error TS2304: Cannot find name 'unknown'.

### ISSUE THREAD

**Issue by somnathsaha** [ngrx/platform#1867]
Getting below error,
ERROR in node_modules/@ngrx/store/src/models.d.ts(30,58): error TS2304: Cannot find name 'unknown'.
node_modules/@ngrx/store/src/models.d.ts(30,82): error TS2370: A rest parameter must be of an array type.
node_modules/@ngrx/store/src/models.d.ts(31,52): error TS2370: A rest parameter must be of an array type.
node_modules/@ngrx/store/src/models.d.ts(31,73): error TS2304: Cannot find name 'unknown'.
node_modules/@ngrx/store/src/action_creator.d.ts(11,124): error TS2344: Type 'ParametersType<C>' does not satisfy the constraint 'any[]'.
  Type '{}' is not assignable to type 'any[]'.
    Type '{}' is not assignable to type 'any[]'.
      Property 'includes' is missing in type '{}'.
--------------------------------------------------------------------------
ng version and other dependencies are as below,

Angular CLI: 7.3.8
Node: 10.15.2
OS: win32 x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.13.9
@angular-devkit/build-angular      0.13.9
@angular-devkit/build-ng-packagr   0.13.9
@angular-devkit/build-optimizer    0.12.4
@angular-devkit/build-webpack      0.13.9
@angular-devkit/core               7.3.9
@angular-devkit/schematics         7.3.8
@angular/cli                       7.3.8
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.3.9
@schematics/angular                7.3.8
@schematics/update                 0.13.8
ng-packagr                         4.7.1
rxjs                               6.5.1
typescript                         2.9.2
webpack                            4.29.0

**Comment by timdeschryver** [comment]
What's the version of NgRx?

**Comment by somnathsaha** [comment]
This is the package.json,

{
  "name": "@com-delta-idp/idp-flight-status",
  "version": "0.1.0-0",
  "scripts": {
    "ng": "ng",
    "init": "npm prune && npm install",
    "start-local": "ng serve --configuration=local",
    "start-local-node": "node --max_old_space_size=8000 ./node_modules/@angular/cli/bin/ng serve --configuration=local",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "css-lint": "bundle exec scss-lint --config .scss-lint.yml",
    "build:client-and-server-bundles": "ng build --prod && ng run flight-status:server:production",
    "build:ssr": "npm run build:client-and-server-bundles && npm run webpack:server && npm run build-content",
    "webpack:server": "webpack --config webpack.server.config.js --progress --colors",
    "serve:ssr": "node --inspect dist/server",
    "start-ssr": "npm run build:ssr && npm run serve:ssr",
    "release": "standard-version",
    "version": "npm run release -- --prerelease && git add package.json && git commit -m \"[ci-skip] new version\" --no-verify && git push",
    "version-temp": "npm run release -- --prerelease && git diff --quiet && git diff --staged --quiet || git commit -amn 'new version' && git push  && cd ..",
    "build-prod": "npm run build:properties && npm run build:ssr",
    "build:properties": "node scripts/generate-properties.js",
    "build-content": "node ./scripts/post-build.js",
    "copy-theme": "bash scripts/pre-build.sh",
    "test-app-build": "ng lint flight-status && ng test flight-status --source-map --watch false --code-coverage --configuration=build",
    "test-app": "ng lint flight-status && ng test flight-status --source-map --watch false --code-coverage",
    "clean": "rm -rf dist",
    "build-aem": "ng build --prod --base-href=/content/dam/delta-applications/flight-status/version_jenkins --output-path=flight-status-package/jcr_root/content/dam/delta-applications/flight-status/version_jenkins",
    "aem-package": "cd flight-status-package && zip -r ../flight-status-package.zip ./* && cd ..",
    "audit": "npm audit --registry=https://registry.npmjs.org",
    "lighthouse": "node_modules/lighthouse/lighthouse-cli/index.js http://dvl4.delta.com/content/dam/delta-applications/flight-status/version_jenkins --output-path=./lighthouse-report.html --chrome-flags='--no-sandbox --headless' --emulated-form-factor=none --disable-device-emulation --throttling-method=provided --onlyCategories=performance --only-categories=seo --only-categories=accessibility --only-categories=best-practices"
  },
  "publishConfig": {
    "repository": "https://nexus.delta.com/repository/npm-hosted/"
  },
  "repository": {
    "type": "git",
    "url": "git@git.delta.com:idp/idp-flight-status.git"
  },
  "contributors": [
    "Yadav Himanshu <yadav.himanshu@tcs.com>",
    "Mortimer, Jonathan M <jonathan.mark@delta.com>",
    "Saha, Somnath <somnath.saha@delta.com>"
  ],
  "standard-version": {
    "skip": {
      "changelog": true,
      "commit": true,
      "tag": true
    }
  },
  "dependencies": {
    "@angular-devkit/build-optimizer": "^0.12.2",
    "@angular/animations": "6.1.10",
    "@angular/common": "6.1.10",
    "@angular/compiler": "6.1.10",
    "@angular/core": "6.1.10",
    "@angular/forms": "6.1.10",
    "@angular/http": "6.1.10",
    "@angular/platform-browser": "6.1.10",
    "@angular/platform-browser-dynamic": "6.1.10",
    "@angular/platform-server": "^6.1.6",
    "@angular/router": "6.1.10",
    "@com-delta-idp/idp-components": "6.5.16",
    "@com-delta-mts/angular-logger": "0.0.22",
    "@com-delta-mts/application": "^1.0.7",
    "@com-delta-mts/express": "^1.0.52",
    "@ngrx/effects": "^7.4.0",
    "@ngrx/store": "^7.4.0",
    "@nguniversal/common": "6.1.0",
    "@nguniversal/express-engine": "^6.1.0",
    "@nguniversal/module-map-ngfactory-loader": "^6.1.0",
    "classlist.js": "1.1.20150312",
    "core-js": "^2.5.4",
    "domino": "2.1.0",
    "enquire-js": "^0.2.1",
    "express-device": "0.4.2",
    "express-request-proxy": "^2.0.0",
    "express-useragent": "1.0.12",
    "font-awesome": "^4.7.0",
    "moment": "^2.24.0",
    "moment-timezone": "^0.5.25",
    "multer": "^1.3.0",
    "ng-busy": "^7.0.0",
    "ngx-bootstrap": "^2.0.2",
    "ngx-responsive": "^7.0.1",
    "picturefill": "^3.0.3",
    "picturefill-background": "^1.0.2",
    "rxjs": "6.5.1",
    "rxjs-compat": "6.5.1",
    "serve-static": "^1.13.2",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.13.1",
    "@angular-devkit/build-ng-packagr": "~0.13.0",
    "@angular/cli": "7.3.8",
    "@angular/compiler-cli": "6.1.10",
    "@angular/language-service": "6.1.10",
    "@angular/platform-server": "6.1.10",
    "@ngrx/schematics": "^6.1.2",
    "@ngrx/store-devtools": "^6.1.2",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.5.0",
    "cors": "^2.8.5",
    "ejs": "^2.6.1",
    "express": "4.16.3",
    "express-request-proxy": "^2.2.2",
    "express-session": "^1.15.6",
    "husky": "^1.3.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.5",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-spec-reporter": "0.0.32",
    "lighthouse": "^4.1.0",
    "multer": "^1.4.1",
    "ng-packagr": "^4.2.0",
    "node-sass": "^4.11.0",
    "nodemon": "1.18.7",
    "properties-reader": "0.0.16",
    "protractor": "~5.4.0",
    "shelljs": "^0.8.2",
    "standard-version": "^4.4.0",
    "ts-loader": "4.2.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~2.9.2",
    "webpack-cli": "3.1.0"
  }
}

**Comment by timdeschryver** [comment]
If you're using NgRx v7.x, you should use Angular v7.x
