### ISSUE TITLE
Move MockStore tests to a separate file

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#1873]
Currently the `MockStore` tests are added to the `Store` tests, this makes them harder to find. That's why we want to extract the `MockStore` tests at https://github.com/ngrx/platform/blob/master/modules/store/spec/store.spec.ts#L450 to their own file.

**Comment by timdeschryver** [comment]
This one is picked up by @deli6z.

**Comment by alex-okrushko** [comment]
Did n't realize this issue was opened - I moved the tests as part of https://github.com/ngrx/platform/pull/1878

**Comment by deli6z** [comment]
@alex-okrushko stole my chance to shine.

**Comment by brandonroberts** [comment]
Fixed via #1878

**Comment by alex-okrushko** [comment]
> @alex-okrushko stole my chance to shine.

@deli6z there's plenty more! :)
