### ISSUE TITLE
[@ngrx/data] Set HttpClient options

### ISSUE THREAD

**Issue by norato** [ngrx/platform#1876]
The default option for response in HttpClient is **body**, if I need to map the full response do we have some config to it?
In a case that we receive the total elements at the response headers, how can I get it using the @ngrx/data?

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
You can create your own custom [data service](https://next.ngrx.io/guide/data/entity-dataservice), which will allow you to do so if I'm not mistaken.
