### ISSUE TITLE
splitting up strictImmutability into separate store/action checks

### ISSUE THREAD

**Issue by ludicast** [ngrx/platform#1890]
## Describe any alternatives/workarounds you're currently using

Not mutating store anyway.

## Other information:

In cases where an action has a mutable payload, setting strictImmutability throws an error when the payload mutates.  This is by design, and an overall good thing.

Here is an example where the Increment class has a payload that mutates after a timeout:

https://stackblitz.com/edit/ngrx-seed-3ytt7p 

For cases where developers cannot control the creation/dispatch of an action I would propose (like with serialization), adding strictStoreImmutability and strictActionImmutability (both of which strictImmutability would use in maintaining its current behavior).

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Thanks for opening this issue.
If you don't mind I would like to assign this to myself, as we want to create the meta reducers slightly different.
