### ISSUE TITLE
Store: add migration to move users off ngrx-store-freeze

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1896]
The majority of our users are probably using `ngrx-store-freeze` to guard against state mutations. We have built-in run-time checks in version 8 to guard against those. This migration would

- Check to see if they are using `ngrx-store-freeze`
  - Remove `ngrx-store-freeze` from imports and the meta-reducers array
  - Remove `ngrx-store-freeze` from their `package.json` dependencies.
- Update StoreModule.forRoot() to enable the `strictStateImmutability` and `strictActionImmutability` run-time checks.

**Comment by santoshyadav198613** [comment]
Hi @brandonroberts ,
Taking this next.

**Comment by brandonroberts** [comment]
@santoshyadav198613 hold off on doing anything with this one yet

**Comment by santoshyadav198613** [comment]
Cool, let me know once we want to proceed.

**Comment by timdeschryver** [comment]
We discussed this internally and I already started to work on this feature in #1901. I'm sorry @santoshyadav198613.

**Comment by santoshyadav198613** [comment]
> We discussed this internally and I already started to work on this feature in #1901. I'm sorry @santoshyadav198613.

No problem.
