### ISSUE TITLE
Add support for Angular 8

### ISSUE THREAD

**Issue by paustint** [ngrx/platform#1899]
## Describe any alternatives/workarounds you're currently using
Waiting to upgrade my project.

## Other information:
Now that Angular 8 is final, all `@ngrx` libraries need to be updated to ensure that the peer dependency uses `@angular/core` 8.0.0.

https://github.com/angular/angular/blob/master/CHANGELOG.md

![image](https://user-images.githubusercontent.com/5461649/58600548-52326e80-8242-11e9-82e2-2513cf524cd2.png)

## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

**Comment by brandonroberts** [comment]
Betas for NgRx version 8 are already out until final release is ready

**Comment by stumbino** [comment]
Can I get a link or package.json example of the dependencies for version 8? Thanks!

**Comment by timdeschryver** [comment]
These are visible at https://next.ngrx.io/guide/migration/v8
