### ISSUE TITLE
RFC: Hold back on releasing mapToAction

### ISSUE THREAD

**Issue by MikeRyanDev** [ngrx/platform#1907]
I've been playing with `mapToAction` since it landed and I have some concerns about the ergonomics of this utility function:
1. It doesn't meaningfully reduce lines-of-code (some effects may increase in size)
2. It abstracts over too many parts of rxjs. I don't think it should be selecting a merge operator for you. As designed, it makes it awkward to use an unusual merging operator like `groupBy`
3. On the flip side, I think it should handle mapping results into actions without the user having to import the `map` operator.

That is a pretty brief description of some of my concerns about `mapToAction`. What I would like to suggest is that we hold off on releasing it in v8.0.0 and save it for v8.1.0. It may be fine as-is but I want to spend a little more time on the design of this function before it becomes part of our stable API.

[X] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by alex-okrushko** [comment]
For anyone following this issue - after having a team discussion we decided to rename the operator to `act` (similar to what @cartant named it) and not promote it for the time being (until `8.1.0`+) and review it one more time.
