### ISSUE TITLE
Docs: Add status badges for CircleCI and NPM to README

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1909]
Could be useful to have in the [README.md](https://github.com/ngrx/platform) along with the gitter and commitizen badges
For reference: https://raw.githubusercontent.com/angular/angular/master/README.md

**Comment by timdeschryver** [comment]
@deli6z do you want to pick this one up?

**Comment by Edouardbozon** [comment]
Hi, can I take this ?

**Comment by deli6z** [comment]
@timdeschryver I am on it!

**Comment by timdeschryver** [comment]
Let's assign this to @deli6z as it's hes first contribution 🙂
