### ISSUE TITLE
How to register single reducer using StoreModule.forFeature with ngrx 8.0.0 beta

### ISSUE THREAD

**Issue by xinlongli2018** [ngrx/platform#1915]
Hi,

in my feature module, im using the createReducer method to create my reducer as follow:

**export const reducer = createReducer(
  new InitState(),
  on(loadData, state => {
    return {
      ...state,
      isLoading: true
    };
  })
);**

but when i register the above reducer in the module class as following:

  **StoreModule.forFeature('my-module', reducer),**

im getting the following error when compiling the project:

**ERROR myModule.module.ts(38,47): Error during template compile of 'MyModuleModule'
  Function calls are not supported in decorators but 'createReducer' was called in 'reducer'
    'reducer' calls 'createReducer' at myreducer.reducer.ts(14,24).**

Do you know what might go wrong? or how do i register single reducer, because all the examples i have seen are using combineReducers with multiple reducers, and i wonder if for just one reducer, how do we do it?

Thank you much!

**Comment by alex-okrushko** [comment]
You have two options:
- register reducers with `InjectionToken`: https://github.com/ngrx/platform/blob/d81ddeb3938cb5768cf76a815c956a78de4df057/projects/example-app/src/app/reducers/index.ts#L37-L44

- wrap with function
https://github.com/ngrx/platform/pull/1746#issuecomment-483779662

**Comment by xinlongli2018** [comment]
thanks second option works! and Is wrapping the single reducer in a function a long term solution, or will createReducer() just work in the production version of ngrx 8.x?  and when do we expect the production version of ngrx 8.x to be released?

**Comment by timdeschryver** [comment]
> and Is wrapping the single reducer in a function a long term solution, or will createReducer() just work in the production version of ngrx 8.x?

No sadly not, this is how the AOT compiler works.

> when do we expect the production version of ngrx 8.x to be released?

We're laying the last stones for the ngrx 8 release.
Besides that we've hit a problem with `prod` builds https://github.com/ngrx/platform/issues/1905

**Comment by xinlongli2018** [comment]
@timdeschryver, ok thank you for the update! so far i really like the ngrx library

**Comment by varghesep** [comment]
Wrapping the ```createReducer``` in a function is not working for me.

```
export function productsReducer(state, action) {
  return createReducer(
    initialState,
    on(ProductActions.AddProduct, (state, { product }) => adapter.addOne(product, state)),
    on(ProductActions.UpsertProduct, (state, { product }) => adapter.upsertOne(product, state)),
  );
}
```
It gives me an error ```entiry map can't be executed on undefined```.

**Comment by alex-okrushko** [comment]
@varghesep updated the comment.

**Comment by amirSohel007** [comment]
I have reducer folder which contain multiple reducer file
![image](https://user-images.githubusercontent.com/32379866/103326842-2e678800-4a78-11eb-9556-c1f6ed2d88d9.png)

each fle contain code in this way 
![image](https://user-images.githubusercontent.com/32379866/103326856-43dcb200-4a78-11eb-971e-9d3755183e25.png)


now my requirement is, I want to merge all the reducers without creating multiple instances, must be only a single name that contains all reducers

**Comment by alex-okrushko** [comment]
@amirSohel007 
you are probably looking for https://ngrx.io/api/store/combineReducers

**Comment by amirSohel007** [comment]
@alex-okrushko this above approach will not work

**Comment by Neewd** [comment]
> @alex-okrushko this above approach will not work

Sorry to up the topic, but did you find any solution or workaround for your problem?
