### ISSUE TITLE
having an observable in the featureEntity break ngrx

### ISSUE THREAD

**Issue by popoleeMaster** [ngrx/platform#1916]
**I'm submitting a...**

[ ] Regression
[X] Bug report 
[] Feature request
[ ] Documentation issue or request
(I think it is a bug cause at least it shouldn't crash)

**Information**
I have a ngrx store where I store a list of object from a class `Line`.

in the class `Line` there is the following 

      export class Line {
           lineId: string
           points: Points[]
      }

and in the point there is 

      private coordinateChangeEmitter = new ReplaySubject<void>();
      coordinateChange$: Observable<void>;
      constructor() {
        this.coordinateChange$ = this.coordinateChangeEmitter.asObservable();
      }

that is used by the line and some component to update the position of UI elements... when we     `this.toy.point[0].coordinateChange$.subscribe(() => {});` for exemple, we get the position change updates

at some point, I want to save my toys again and his list of point so I do the follow

    const ADD_POINT= (state: State, action: featureAction.AddPoint) => {
      const line= {...state.entities[action.payload.lineId]};
      line.points= [...line.points, ...[action.payload.points]];
      return featureAdapter.updateOne({
        id: action.payload.lineId,
        changes: line.points,
      }, state);
    };

I have to do this cause if I only update the array, there is no change detection on ngrx.

the problem I face is, when some component subscribed to the observable, redux updates than break with the following 

> TypeError: Converting circular structure to JSON
>     --> starting at object with constructor 'Object'
>     |     property '_subscriptions' -> object with constructor 'Array'
>     |     index 0 -> object with constructor 'Object'
>     --- property '_parent' closes the circle

 now this is a json error but there should be some guard to prevent it from crashing 

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/94A9k.png

**Comment by brandonroberts** [comment]
This is not a bug. You should be using plain JavaScript objects in your state. Storing an observable in your state that has circular references should be avoided.
