### ISSUE TITLE
Can we bump the number of actions in createReducer?

### ISSUE THREAD

**Issue by bryanrideshark** [ngrx/platform#1918]
Can we bump the number of generics in `createReducer` to be higher?

Some reducers can get bigger than 10 actions.

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

**Comment by jtcrowson** [comment]
Can you provide an example where it limits you?  From looking at the code `/modules/store/src/reducer_creator.ts` line 182, it doesn't look like there is any limitation to the number of actions a createReducer can handle.

**Comment by timdeschryver** [comment]
Correct, it will support an unlimited amount of `on`'s but you lose the type safety.

**Comment by julianobrasil** [comment]
@timdeschryver, I've just opened a new issue asking for the type safety thing. Well, I'm not aborting it. Even if I use one `createReducer` per `action` to keep the type safety, I lost code editor autocompletion as the action payload seems to be `any` from the editor's point of view (VSCode). The issue I've just opened: #1949

**Comment by timdeschryver** [comment]
Should we bump up the number, and if so how many do we see fit?

**Comment by dkosasih** [comment]
@timdeschryver, I stumbled upon this thread. let me know if I can work on this

**Comment by timdeschryver** [comment]
I don't have a strong opinion on this.
Thoughts @brandonroberts / @alex-okrushko ?

**Comment by brandonroberts** [comment]
I think 10 is an acceptable number for now. We can revisit if it becomes more common or provide some guidance in the API docs on what to do if you have more than 10
