### ISSUE TITLE
Ability to compose an array of selectors in createSelector 

### ISSUE THREAD

**Issue by avatsaev** [ngrx/platform#192]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## What is the current behavior?
Currently we can only pass selector functions to createSelector arguments

## Expected behavior:

It would be useful to be able to pass an array of selectors to an argument of createSelector, which will return two values for the next selector in the composition

## Minimal reproduction of the problem with instructions:

From: https://github.com/reactjs/reselect#composing-selectors

```
const getKeyword = (state) => state.keyword

const getVisibleTodosFilteredByKeyword = createSelector(
  [ getVisibleTodos, getKeyword ],
  (visibleTodos, keyword) => visibleTodos.filter(
    todo => todo.text.includes(keyword)
  )
)
```

Most selectors take in one argument (usually the state), but in some cases a selector can take 2 or more arguments, composing an array of selectors can help to form the number arguments for the next selector.

:heartpulse: ngrx? Please consider supporting our collective: 👉  [donate](https://opencollective.com/ngrx/donate)

**Comment by tdeschryver** [comment]
Maybe a dumb question, but do you accept a PR for this? Asking because this issue doesn't have the label 'Accepting PRs'.

**Comment by brandonroberts** [comment]
Sure, we'll take a PR for this
