### ISSUE TITLE
The version selection dropdown on ngrx.io is not user friendly

### ISSUE THREAD

**Issue by dsebastien** [ngrx/platform#1926]
Hello,

I'm not sure if this has been mentioned before, but it took me some time to notice the documentation version selection dropdown in the docs section of the NGRX Website.

Also, after selecting a version in the dropdown, we end back on the homepage, but there is no clear indication that we are now seeing a different version of the documentation.

Now that I get it I get it... But I suppose others might be facing the same issue.

In my case I was looking for the v8 docs.

## I would be willing to submit a PR for the docs :heart:

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

**Comment by jtcrowson** [comment]
Version is displayed in the URL:
next: https://next.ngrx.io/
stable: https://ngrx.io/
v7: https://v7.ngrx.io/

It's possible that your browser cached the old version of https://ngrx.io/, I know mine did.  When I navigated to https://ngrx.io/ today, I got version 7.4, and by using the dropdown and selecting next, I got version 8, which is https://ngrx.io/.  But after that, navigating to https://ngrx.io/ has been correctly delivering version 8.

As far as the dropdown itself goes, ngrx.io was essentially forked from angular.io, which has the same dropdown.

**Comment by deli6z** [comment]
I think @dsebastien saying that it would be good to see the current version information on the homepage. Once user is changing the version it brings you back to homepage where URL is the only indication your selection worked - so the question is whether that is enough?

**Comment by brandonroberts** [comment]
I think a straightforward fix would be to redirect to the `/docs` page when changing from stable or next here instead of the homepage. https://github.com/ngrx/platform/blob/master/projects/ngrx.io/src/app/app.component.ts#L178

That way, once you navigate, the side menu is displayed with the current version you are looking at.

**Comment by deli6z** [comment]
I can try to fix that if that is ok?

**Comment by brandonroberts** [comment]
Sure. Some docs tests maybe need to be updated also.

**Comment by deli6z** [comment]
alright sign me up, may ask more questions.

**Comment by brandonroberts** [comment]
Cool! Just let us know and we'll assist.

**Comment by dsebastien** [comment]
Great, thank you guys. Keep up the great work!
