### ISSUE TITLE
Incorrect ngrx/data module on ngrx.io/guide

### ISSUE THREAD

**Issue by pegaltier** [ngrx/platform#1930]
You can see on the link below there is still the old module 'NgRxDataModule' used but it should be replaced by the new one 'EntityDataModule'

https://ngrx.io/guide/data/entity-metadata

## I would be willing to submit a PR for the docs :heart:

[X] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Good catch and thanks for opening the issue.
Do you want to pick this one up @pegaltier ?

**Comment by pegaltier** [comment]
@timdeschryver Yes I would like to pick this one but i have no idea where the doc is located. Can you help me? Thanks!

**Comment by timdeschryver** [comment]
You can take a look at our new contributing page at https://ngrx.io/contributing.

To answer your question, the docs are made so you can click on the pencil on the website to go straight to editing mode of the docs 🙂

![image](https://user-images.githubusercontent.com/28659384/59150657-fd071180-8a26-11e9-87de-0d926a1edf4c.png)

Feel free to ping us if you need some guidance, we're here to help.

**Comment by pegaltier** [comment]
@timdeschryver thanks for your help! I did it! I hope it's correct!

**Comment by timdeschryver** [comment]
@pegaltier Yes that's it! 

I left a comment in the PR because there is another import 🙈

**Comment by pegaltier** [comment]
@timdeschryver Good find! it's done so it should be fine now!
