### ISSUE TITLE
Update live demo (stackblitz) to last release on ngrx.io/guide

### ISSUE THREAD

**Issue by pegaltier** [ngrx/platform#1931]
Currently the stackblitz live demo given on the ngrx.io/guide uses the beta version. It should be updated with the official release. See link below:

https://ngrx.io/guide/store#tutorial

**Comment by timdeschryver** [comment]
If someone wants to grab this, you can change the versions at

https://github.com/ngrx/platform/blob/master/projects/ngrx.io/tools/examples/shared/package.json
and
https://github.com/ngrx/platform/blob/master/projects/ngrx.io/tools/examples/shared/boilerplate/cli/package.json

**Comment by deli6z** [comment]
I guess I could grab this one.

**Comment by deli6z** [comment]
@timdeschryver stackblitz has the right versions now, am I missing something?

**Comment by jtcrowson** [comment]
@deli6z you'll need to update both package.json to use the new NgRx version.   Those generate the stackblitz dependencies.

**Comment by deli6z** [comment]
@timdeschryver just so I understand can you please point me to the script which picks these jsons up when generating the stackblitz code. Thanks.
