### ISSUE TITLE
Default router serialization is not compatible with immutability check

### ISSUE THREAD

**Issue by jonr-elsewhen** [ngrx/platform#1937]
## Minimal reproduction of the bug/regression with instructions:

The "strictStateImmutability" runtime check is enabled by default in NgRx 8. This check is not compatible with `@ngrx/router-store`, because the default router state cannot be safely made immutable: https://github.com/ngrx/platform/issues/1104#issuecomment-479945199

1. Create a Angular project without routing enabled.
2. Add `@ngrx/store`
3. Add `@ngrx/router`

Browse the app. You will get the following in the console:

```
Attempting to configure '__source' with descriptor '{"value":"StaticContentPipe","configurable":true}' on object 'InjectionToken STATIC_CONTENT_CONTEXT' and got error, giving up: TypeError: Cannot redefine property: __source
```

## Expected behavior:

The "strictStateImmutability" check should skip freezing the router store by default.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

NgRx: 8
Angular: 8

## I would be willing to submit a PR to fix this issue

[x] Yes
[ ] No

**Comment by timdeschryver** [comment]
To make router-store serializable you will have to use [`RouterState.Minimal`](https://next.ngrx.io/guide/router-store/configuration).
