### ISSUE TITLE
Documentation for How to Unit Test Selectors using passed in properties

### ISSUE THREAD

**Issue by Rlcolli4** [ngrx/platform#1938]
I was reviewing your documentation on unit testing slices of the store (https://ngrx.io/guide/store/testing) and realized that there was no documentation for taking a selector that has the added `properties` parameter (IE `getFilteredItems = createSelector(getItemsState, (state: fromFeatures.ItemsState, props: any)`. Currently, attempting to unit test this with current documentation causes the "state" variable to alway be null/undefined even if the value is passed in in the test (IE `expect([...fromSelectors.getFilteredItems(initialState,{searchTerm: "string"})]).toBe([]);`). While I need this fixed (a separate issue) I feel that this should be properly documented as the current method does not work.

**Comment by timdeschryver** [comment]
Because selectors are functions, you can invoke the selector just like a normal function.

[StackBlitz demo](https://stackblitz.com/edit/jasmine-testing-nk1pnv?file=test/jasmine-setup.ts)
```
describe('selector with props', () => {
  it('should be able to pass props', () => {
    const actual = selector({counter: 3}, {multiplier: 10}) 
    expect(actual).toBe(30);
  });
});
```
