### ISSUE TITLE
Docs: Explain what should the DataService server respond for ngrx/data to work properly

### ISSUE THREAD

**Issue by jsgoupil** [ngrx/platform#1939]
The documentation is lacking how should the DataServer, responding to ngrx/data, actually respond in order for the client to work properly. You talk a little bit about DELETE returning a 404, but you don't talk about what should be returned for add(), delete(), getAll().

For instance, should add() return the whole instance added or just the ID? Looking at the code, it seems that the ID might be sufficient.

For the `getWithQuery`, you should mention how you will send the query to the server... QueryString? POST?, etc.

**Comment by JiaLiPassion** [comment]
I would like to add the documentation and the sample code, basically you can get those information from the `typescript d.ts`.

```typescript
export interface EntityCollectionDataService<T> {
    readonly name: string;
    add(entity: T): Observable<T>;
    delete(id: number | string): Observable<number | string>;
    getAll(): Observable<T[]>;
    getById(id: any): Observable<T>;
    getWithQuery(params: QueryParams | string): Observable<T[]>;
    update(update: Update<T>): Observable<T>;
    upsert(entity: T): Observable<T>;
}
```
- for the methods return `Observable<T>`, the data server should return the whole entity, of course you can return only the `id` and in your customized EntityCollectionService, you can merge the `id` with the existing entity in memory. 
- for the method return `Observable<string | number>`, server at least need to return the `id`, and of course you can return the whole entity, and in your customized EntityCollectionService, you just return the extracted id.
