### ISSUE TITLE
How to get params from router state

### ISSUE THREAD

**Issue by oleosjo** [ngrx/platform#194]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request
</code></pre>

How do I get params from the route state? I'm trying to create a selector with reselect, but the params are always empty.

<pre><code>
export const routerState = (state: AppState) => state.router;

export const selectedUser = createSelector(routerState, usersById, (router, users) => {
  const userId = router.state.root.firstChild.params['id'];
  if (users) {
    return users[userId];
  } else {
    return <User>{};
  }
});
</code></pre>

**Comment by bradyshutt** [comment]
I'm pretty sure what you're looking for should be _somewhere_ in that `router.state` object. Try logging it to the console if you haven't already, and dig around for it there. I suspect it's another level down (ie, `router.state.root.firstChild.firstChild.params['id']`), but it'll depend on how you've set up your routes.

**Comment by oleosjo** [comment]
Yeah, thanks. I'm sure it's in there somewhere. I decided to just track selected ids myself and have components update the state. It doesn't seem worth it to try to find it in the object.
