### ISSUE TITLE
HttpClient with "pipe" sends multiple GET requests even if the first one did not fail

### ISSUE THREAD

**Issue by usarskyy** [ngrx/platform#1940]
## Minimal reproduction of the bug/regression with instructions:

My Angular 8 app is hosted on http://localhost:4200/
My API is hosted on http://localhost:6002/

I am trying to send a HTTP GET request from Angular app to API. Before GET request is issued, browser sends preflight OPTIONS request to get CORS policy.

The problem is that when I add "retry" to my "pipe", I start getting multiple API requests. By some reason NgRx treats preflight OPTIONS request as failed GET request and makes a retry.

![2019_06_12_10_38_26_Oebb EvuZd_C_Users_l028705_Documents_SOURCE_evuzd_Oebb EvuZd_ _Oebb Evuzd](https://user-images.githubusercontent.com/1206777/59341967-2797e980-8d09-11e9-89db-a722fa2ef6be.png)

![2019_06_12_10_37_26_DevTools_localhost_4200_anmeldung_returnUrl_2Fzugliste](https://user-images.githubusercontent.com/1206777/59341975-2a92da00-8d09-11e9-99ac-f924c716c325.png)

## Expected behavior:

I expect that NgRx sends only one single GET request.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

Win7 SP1
Chromium 68.0.3440.106
NgRx 8.0.0-rc.1
Angular 8.0.0

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

**Comment by dummdidumm** [comment]
The HttpClient is from Angular. I don't think this issue has anything to do with Ngrx.

**Comment by usarskyy** [comment]
From my point of view, the problem is in "retry". It should not be executed because the first request was successful.

**Comment by dummdidumm** [comment]
`retry` is also not part of `ngrx`. It's a function from the library `rxjs`.

**Comment by usarskyy** [comment]
So, who can decide if this is ngrx or rxjs issue? I can also create an issue there

**Comment by brandonroberts** [comment]
This is not an issue with NgRx or RxJS specifically. With CORS being a browser-based security restriction, your best option is to proxy your API requests through the CLI so everything is served from the same port. See https://angular.io/guide/build#proxying-to-a-backend-server

**Comment by usarskyy** [comment]
Ok, it looks like this is Angular's fault https://github.com/angular/angular/issues/20879

Thank you for your help! This ticket can be closed.

**Comment by usarskyy** [comment]
Brandon, unfortunately this is not always possible. API is often hosted on "api." subdomain and this is completely OK.
CORS is browser specific functionality, you are right. But exactly in this case this is Angular's bug.
BTW, since Angular 1.* had absolutely no problems with CORS, as well as other frameworks, means that this is purely software bug and not browser's.

**Comment by brandonroberts** [comment]
👍

**Comment by johannesMatevosyan** [comment]
It is not related with NgRx, it's a [**retry** operator](https://www.learnrxjs.io/learn-rxjs/operators/error_handling/retry) from RxJs.  Retry()  operators does not treat initial request as the first try. Therefore the request will be repeated (count + 1) times.
