### ISSUE TITLE
Docs Suggestion: Add examples of multi-entity stores

### ISSUE THREAD

**Issue by mwamufiya** [ngrx/platform#1947]
## Other information:
In getting familiar with the ngrx ecosystem, I found that examples of how to use the store with multiple entities challenging. 
I eventually landed here ->  [https://stackoverflow.com/questions/48621298/angular-ngrx-multiple-entities-in-one-entityadapter-possible](url)

this helped me a great deal to understand how a store can work with multiple entities. 

Just a suggestion

thank you. 
## I would be willing to submit a PR for the docs :heart:

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

**Comment by timdeschryver** [comment]
Personally, I'm not sure if I would recommend handling multiple entities in a single reducer.
A reducer should be scoped to one entity, imho.

**Comment by brandonroberts** [comment]
I agree with @timdeschryver, managing multiple entities within a single reducer will be hard to maintain.

**Comment by GitHubish** [comment]
Hello @brandonroberts, having found myself in the same situation I wanted to be able to use several entity states in the same store and I encountered many blocking problems. If this is a recommendation from the NGRX team, I would tend to suggest that it be mentioned in the documentation that it is not preferable to do so. What do you think? 

My case was the following I have a store representing the detail of a product in which I had several collections to manage. So my choice went to EntityState for its simplicity, ease of use and readability. According to your last comment, I segmented this "object" into several stores/reducers. Is this the right solution according to you?

Thank you in advance
