### ISSUE TITLE
RFC: schematics should toggle immutability checks on by default 

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#1950]
When using the schematics to create a `root` store, I think it would be a good practice to turn the immutability checks on.

```ts
runtimeChecks: {
        strictStateImmutability: true,
        strictActionImmutability: true,
},
```

And what about the serializability checks?

## Describe any alternatives/workarounds you're currently using

Now the user needs to add it manually.

**Comment by brandonroberts** [comment]
Good idea

**Comment by itayod** [comment]
@timdeschryver @brandonroberts I am available for this one.

**Comment by timdeschryver** [comment]
Go for it @itayod
