### ISSUE TITLE
@ngrx/entity Migration to 8 "Detected unserializable action"

### ISSUE THREAD

**Issue by RomainWeb** [ngrx/platform#1951]
Hi team,

I have migrated to version 8 but i have trouble with a serialization. I dispatch an object with date property and i have this error. i searched on PR and issues but i didn't found some solutions.

**Error**
`ERROR Error: Detected unserializable action at "notification.date_created"
    at throwIfUnserializable (http://localhost:4200/vendor.js:168370:19)
    at http://localhost:4200/vendor.js:168303:13
    at http://localhost:4200/vendor.js:168253:27
    at http://localhost:4200/vendor.js:167529:20
    at computeNextEntry (http://localhost:4200/vendor.js:166435:21)
    at recomputeStates (http://localhost:4200/vendor.js:166488:15)
    at http://localhost:4200/vendor.js:166836:26
    at ScanSubscriber.StoreDevtools.liftedAction$.pipe.Object.state [as accumulator] (http://localhost:4200/vendor.js:166888:38)
    at ScanSubscriber._tryNext (http://localhost:4200/vendor.js:190716:27)
    at ScanSubscriber._next (http://localhost:4200/vendor.js:190709:25)`

**package.json**
`"@ngrx/effects": "^8.0.1",
    "@ngrx/entity": "^8.0.1",
    "@ngrx/store": "^8.0.1",`

**Action**
`export const addNotification = createAction(
  '[Notification] Add Notification',
  props<{ notification: AppNotification }>()
)`

**Reducer**
`on(fromActions.addNotification, (state, {notification}) => {
    return adapter.addOne(notification, state);
  }),`

**Model**
`export interface AppNotification {
  uuid: string;
  description: string;
  date_created: Date;
  type: string;
  icon: string;
  is_read: boolean;
}`

Can someone help me ?

**Comment by timdeschryver** [comment]
A `Date` is not serializable: https://ngrx.io/guide/store/configuration/runtime-checks#strictstateserializability

**Comment by RomainWeb** [comment]
oh thx for information and your quick answer

**Comment by SerkanSipahi** [comment]
@RomainWeb you can dispatch moment (https://momentjs.com/) date object. This works well :)

**Comment by stemda** [comment]
I'm facing the same issue. Unfortunately, using moment like you suggested @SerkanSipahi didn't solve the problem for me. Did I get you wrong?

start_date: Moment {_isAMomentObject: true, _i: Array(3), _isUTC: false, _pf: {…}, _locale: Locale, …}

**Comment by Zonnex** [comment]
+1, date nor moment works

**Comment by kevinbeal** [comment]
`Date` is serialize-able in other contexts (e.g. as JSON and `toString`). For what reason does NGRX impose additional limits on an object's ability to be serialized?

Maybe there are some properties which are computed and return different values at different times? That would make more sense here, but the restriction is also being set on any instance of a class (it seems).

**Comment by huineng** [comment]
I got on question..  when i'm using angular (8) and don't compile with aot i have this error, when i do compile with aot, i don't have these errors. So these checks only work when not using aot.

**Comment by manklu** [comment]
@huineng AFAIK they are only active in dev mode.

**Comment by timdeschryver** [comment]
Correct, the runtime checks are disabled in a production build.

**Comment by SerkanSipahi** [comment]
@stemda im using ngrx v8 and have no trouble when dispatching a moment object! @timdeschryver any thoughts?

**Comment by pcurrivan** [comment]
Huh? A Date is not serializable?  Serialize with toJSON, deserialize with the constructor.  Is there a reason we can't have NgRx automatically (de)serialize Dates and other objects so we don't have to manually do these conversions all throughout our app?

**Comment by amithegde** [comment]
please fix this, it's kind of let down!

**Comment by JAspeling** [comment]
It's strange, I have a simple object like this

```ts
export class ClientRegistration {
    name: string;
    email: string;
    contact: string;
    additionalContact: string;
    password: string;

    constructor(init?: Partial<ClientRegistration>) {
        Object.assign(this, init);
    }
}
```

and using this object in my action - 

```ts
export const registerClient = createAction(
    '[Register Client] Signup',
    props<{ registration: ClientRegistration }>()
);
```

But it says it's unserializable? This is a perfectly serializable object...?
