### ISSUE TITLE
docs: Clean Up Integration Testing Examples

### ISSUE THREAD

**Issue by jtcrowson** [ngrx/platform#1952]
Now that we have updated the documentation with using MockStore + mock selectors, we should revisit the existing testing examples (prior to v6) that have been moved to "Integration Testing" to more accurately represent an integration test.  It looks like the [v6 testing docs](https://github.com/ngrx/platform/blob/6.1.2/docs/store/testing.md) were just moved into this section without updating them.

I propose updating the documentation accordingly:
- In the store/testing integration testing section, do not have an example that dispatches a `load_____Success` action.  These actions are dispatched by an Effect. In this example, a true integration test would import the EffectsModule and mock the Effect's downstream dependencies.  But since this section is only concerned about Store Integration, the example should not be of an app that uses effects, and the component test should only dispatch actions that the component can.
- Add an effects/testing integration testing section, which shows importing the StoreModule and EffectsModule and mocks the Effect's downstream dependencies.

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
👍 I agree the testing docs can be enhanced.
I've been keeping a "to document" list to test effects but hadn't have the time to start writing it.

**Comment by jtcrowson** [comment]
Cool, after discussing with @timdeschryver offline, I'll be working with him on revamping the integration testing sections.
