### ISSUE TITLE
Example: Update book search failure action with only error message

### ISSUE THREAD

**Issue by znikola** [ngrx/platform#1953]
## Minimal reproduction of the bug/regression with instructions:

strictActionSerializability throws error in case of an @angular/common/http/HttpErrorResponse

The goal is to cause an http error.
Modifying `searchBooks()` in `google-books.service.ts` in the ngrx's `example-app` is enough:

```ts
searchBooks(queryTitle: string): Observable<Book[]> {
    return this.http
      .get<{ items: Book[] }>('xxx') // 'xxx' endpoint doesn't exist, which will cause an error
      .pipe(map(books => books.items || []));
  }
```

## Expected behavior:

Since the `xxx` endpoint doesn't exist, the `search$` effect in `book.effects.ts` will catch the error, but since it's not serializable, the `strictActionSerializability` flag will kick in and throw an error.

<img width="1437" alt="Screen Shot 2019-06-17 at 15 00 52" src="https://user-images.githubusercontent.com/11561723/59629406-c0b36f80-9110-11e9-9d0a-9c52d40a9863.png">

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

the newest ngrx, since version 8.

## Other information:

The reason why this is failing is because `'normalizedNames`, `lazyInit`, `lazyUpdate` properties from `HttpHeaders` are of type `Map` or `function`.

I guess this is actually a desired behaviour, and `strictActionSerializability` works as expected (since the Angular's error response object is not serializable), but my concern is how to handle these errors?

## I would be willing to submit a PR to fix this issue

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
This is the desired result. To address your concern, you shouldn't store the error in the store. 

For example, you could only use the message:

```
 of(BooksApiActions.searchFailure({ errorMsg: err.message }))
```

**Comment by znikola** [comment]
That's certainly possible, but I think there's should be a similar solution for this case, as it's similar to the router state problem which has been solved with `RouterState.Minimal` config.

**Comment by timdeschryver** [comment]
I'm not sure if this would be in the same alley as `RouterState.Minimal`, we have the router state in our hands which is not the case if you would like to store an `Error` in to the store.

**Comment by evgenyfedorenko** [comment]
@timdeschryver what should be done in this one? I can take it if nobody is working on it already.

**Comment by znikola** [comment]
Since ngrx is forcing objects provided to actions to be serializable, my proposal would to at least implement and expose a utility method that will make these angular's objects serializable.

**Comment by timdeschryver** [comment]
@evgenyfedorenko see https://github.com/ngrx/platform/issues/1953#issuecomment-502824730, the change would be to store the error message, not the error object.

@znikola this isn't an Angular object, it's the JavaScript `Error` object. Imho it's up to you to decide what you want to store.

**Comment by znikola** [comment]
I believe it's an instance of Angular's `HttpErrorResponse` coming from `@angular/common/http` package.
