### ISSUE TITLE
Allow runtime checks to ignore 3rd party dependencies

### ISSUE THREAD

**Issue by joe-mills** [ngrx/platform#1959]
I use the ng-oidc-client npm package in my project and it violates the strictActionSerializability rule.  This is good to know and I can submit a request on their github repo but in the meantime I don't want the runtime error being thrown for that library.  Can we disable checks for dependencies or selectively ignore?

## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ x] No

**Comment by timdeschryver** [comment]
Personally I think this change wouldn't have a lot of benefit, in contrary... 
If one of the actions is not serializable, you won't have the benefit of having serializable actions. This change would only verify that your own actions are valid, but it misses the whole point of having serializable actions. I would rather know that all my actions are serializable or not, and not make assumptions which ones are and which ones aren't.

This is my personal view, I'm happy to hear other opinions.

**Comment by joe-mills** [comment]
I agree that you need to know the problems exist, even in a dependency, and the checks have really helped a lot with my own architecture but this is not something I can fix immediately myself.  

So should I turn the runtime checks off until the maintainer updates their project or I have time to replace it with something else?

**Comment by timdeschryver** [comment]
Yes that would be my advice.
