### ISSUE TITLE
Share the Entity Change Tracking of NgRx-Data so it can be used with "regular" NgRx-Entity Entities

### ISSUE THREAD

**Issue by jimbarrett33** [ngrx/platform#1961]
## Describe any alternatives/workarounds you're currently using
Without using NgRx-Data the changes in an NgRx Entity collection need to be tracked manually - very similarly to what NgRx-Data does (and what ORMs do on the server).

## Other information:
Not sure if it would be difficult to share the Entity Change Tracking code of NgRx-Data with "regular" NgRx-Entity entities but it seems like this would be something very useful. I couldn't find it but if there IS a way to non-manually track changes to an NgRx-Entity please let me know.

## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No
[x] Maybe

**Comment by brandonroberts** [comment]
We will revisit this at some point, but closing for now.
