### ISSUE TITLE
Http interceptor finalize, when all (side)Effects are done, anyway to check on HTTP request only 

### ISSUE THREAD

**Issue by rickvandermey** [ngrx/platform#1964]
I would like to check wether an HTTP request is being processed or done. I'm using the following setup:

```
@Injectable()
export class AppHttpInterceptor implements HttpInterceptor {
	constructor(private store: Store<StateInterface>) {}

	intercept(
		request: HttpRequest<any>,
		next: HttpHandler,
	): Observable<HttpEvent<any>> {
		this.store.dispatch(new SetRequestStatus({ isMakingRequest: true }));
		return next
			.handle(request)
			.pipe(
				finalize(() =>
					this.store.dispatch(
						new SetRequestStatus({ isMakingRequest: false }),
					),
				),
			);
	}
}
```

```
@Effect()
createPayment$: Observable<any> = this.actions$.pipe(
	ofType(cartConfigActions.CREATE_PAYMENT),
	switchMap(
		([_action]: any) => {
			return this.paymentService.createPayment()
				.pipe(
					map(response => { <-- expect finalize() of HTTP interceptor
						return new cartConfigActions.CreatePaymentSuccess({
							redirect: response.data.redirect,
						});
					}),
					catchError(error => {
						console.log(error);
					}),
				);
		},
	),
);

@Effect()
handleCreatePaymentSuccess$: Observable<
	{} | routerActions.Go
> = this.actions$.pipe(
	ofType(cartConfigActions.CREATE_PAYMENT_SUCCESS),
	switchMap((action: any) => {
		return Observable.create(
			RouteHelper.redirectToExternalUrl(action.payload.redirect),
		); <-- output of finalize() of HTTP interceptor
	}),
);
```

this works, but the finalize completes when `RouteHelper.redirectToExternalUrl` has been dispatched, I would expect it would finalize when the `createPayment` service has a response. Is there another way to check this.

(above is a cleaner version, not sure if it actually is correct, if the full code is needed, i can provide it)

**Comment by brandonroberts** [comment]
Support questions should be asked in our [gitter channel](https://gitter.im/ngrx/platform)

**Comment by adrianbenjuya** [comment]
@rickvandermey Hi, did you find a solution? I'm facing a very similar problem with an interceptor that handles 401 errors and retries the requests after refreshing the token. When more than one unauthorized request is queued the effect makes the interceptor reach the `finalize` callback, therefore the requests won't retry

**Comment by adrianbenjuya** [comment]
Great thanks, anyway, my concern is a little bit deeper, is this the common behavior for effects? is it a bug?, I'm afraid I could come with it in another situation.

**Comment by adrianbenjuya** [comment]
@rickvandermey I've got an answer from Gitter, it's not a bug, you just need to replace `switchMap` for a non blocking map operator like `concatMap` or `mergeMap`

**Comment by chan-dev** [comment]
@rickvandermey this fixed the bug on mine. I was using `exhaustMap` instead of `switchMap` and it's basically blocking the effect, and switching to `mergeMap` definitely fixed it.
