### ISSUE TITLE
Schematics: deprecated usage of Type<T> or InjectionToken<T>

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#1968]
The schematics are currently generating deprecated versions of `TestBed.get`

```
deprecated from v8.0.0 use Type<T> or InjectionToken<T> This does not use the 
deprecated jsdoc tag on purpose because it renders all overloads as deprecated in
TSLint due to https://github.com/palantir/tslint/issues/4522.
```

## Other information:

For example:

```
TestBed.get(CustomersEffects);
```

Should become:

```
TestBed.get<CustomersEffects>(CustomersEffects);
```

## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by itayod** [comment]
@timdeschryver may I take this?

**Comment by brandonroberts** [comment]
It's yours
