### ISSUE TITLE
How to integrate Redux.Middleware?

### ISSUE THREAD

**Issue by naivefun** [ngrx/platform#197]
Is there a way to add standard `Redux.Middleware`? For example: `redux-logger`.

**Comment by naivefun** [comment]
Seems ngrx is not Redux based

**Comment by huskywhale** [comment]
@brandonroberts ^ doesnt support ngrx 4

**Comment by brandonroberts** [comment]
@huskywhale it is. See https://github.com/ngrx/platform/issues/170#issuecomment-318031101

**Comment by bradyshutt** [comment]
I don't think @naivefun was asking how to implement a store logger in ngrx, it seems like he was asking if ngrx supports adding standard [Redux Middleware](https://github.com/reactjs/redux/blob/master/docs/Glossary.md#middleware). He gave `redux-logger` as an example, but there's a [large list of other examples](https://github.com/xgrommx/awesome-redux#react---a-javascript-library-for-building-user-interfaces) that he could have gave.

I am also curious.

**Comment by brandonroberts** [comment]
`@ngrx/effects` is analogous to redux middleware in ngrx. You perform "side effects" and also provide additional sources of events through actions dispatched to the `Store`.
