### ISSUE TITLE
Store: runtime checks token typo 

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#1972]
## Minimal reproduction of the bug/regression with instructions:

There is a typo at:

https://github.com/ngrx/platform/blob/master/modules/store/src/tokens.ts#L76

It should be:

```
export const _ACTIVE_RUNTIME_CHECKS = new InjectionToken<RuntimeChecks>(
  '@ngrx/store Internal Runtime Checks'
);
```

**Comment by jtcrowson** [comment]
Nice and easy!  I got it.
