### ISSUE TITLE
docs: testing changes with overridden selector and setResult

### ISSUE THREAD

**Issue by minijus** [ngrx/platform#1978]
It feels that there is documentation missing for a case on testing change in selector value using overridden selector.

In a given scenario below the selection from `store` for ready state only receives `false` (initial value of overridden selector), but never receives `true` (the updated value from `setResult`).

There is a small repo with reproduction of scenario: https://github.com/minijus/ngrx-set-result/blob/master/src/app/service/app.service.spec.ts

```ts
export class AppService {
  constructor(private store: Store<AppState>) {}
  isReady() {
    return this.store
      .select(selectAppReady)
      .pipe(find(ready => !!ready))
      .toPromise();
  }
}
```

```ts
describe('AppService', () => {
  let service: AppService;
  let store: MockStore<AppState>;
  let appReady: MemoizedSelector<AppState, boolean>;

  beforeEach(() => {
    TestBed.configureTestingModule({ providers: [provideMockStore()] });

    store = TestBed.get(Store);
    appReady = store.overrideSelector(selectAppReady, false);

    service = TestBed.get(AppService);
  });

  describe('#isReady', () => {
    it('should resolve once app state becomes ready', fakeAsync(() => {
      setTimeout(() => {
        appReady.setResult(true);
      }, 1000);

      const spy = jasmine.createSpy();
      service.isReady().then(spy);

      expect(spy).not.toHaveBeenCalled();

      tick(1001);

      expect(spy).toHaveBeenCalled();
    }));
  });
});
```

## I would be willing to submit a PR for the docs :heart:

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by pburkindine** [comment]
More generally, setResult should cause the observable to emit.  As it stands we cannot make any use of the MockStore for long-lived streams in components, for example.

**Comment by minijus** [comment]
> More generally, setResult should cause the observable to emit. As it stands we cannot make any use of the MockStore for long-lived streams in components, for example.

Exactly, `setResult` could internally re-apply current state on store. Maybe by calling setState on store instance internally.

**Comment by timdeschryver** [comment]
See https://github.com/ngrx/platform/issues/2000#issuecomment-509331815

**Comment by garrappachc** [comment]
The `MockStore.setState()` method doesn't do anything as far as mocked selectors are concerned.

**Comment by timdeschryver** [comment]
In `8.4.0` we release `MockStore.refreshState()` to solve this issue.

Closing in favor of #2154 (to add it to our docs)
