### ISSUE TITLE
Http error when lazy loading effects with universal

### ISSUE THREAD

**Issue by Owain94** [ngrx/platform#198]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## What is the current behavior?

When I run my app using universal with lazy loading I get the following error.

https://gist.github.com/Owain94/7eb45555c5d1616c70e85c71576f8c4f

This only happens on the server app when using lazy loading, it works fine in the browser.

## Minimal reproduction of the problem with instructions:
Angular universal app with ngrx and a effect file that loads data from an API.

Made a quick repo over here
https://github.com/Owain94/ngrx-error/

## Version of affected browser(s),operating system(s), npm, node and ngrx:
MacOS High Sierra version 10.13
Chrome, Safari (haven't tested in others but I assume it's browser independent)
npm --version 5.3.0
yarn --version 0.24.6
node --version v8.1.4

"@ngrx/effects": "4.0.1",
"@ngrx/router-store": "4.0.0",
"@ngrx/store": "4.0.0",
"@ngrx/store-devtools": "4.0.0",

:heartpulse: ngrx? Please consider supporting our collective: 👉  [donate](https://opencollective.com/ngrx/donate)

**Comment by Owain94** [comment]
Added a repo

**Comment by brandonroberts** [comment]
I don't see how this is an issue with ngrx. The error states that `XMLHttpRequest is not defined`. Does HttpClient work universal?
