### ISSUE TITLE
Immutability check reducer is not compatible with IE11

### ISSUE THREAD

**Issue by jonr-elsewhen** [ngrx/platform#1991]
## Minimal reproduction of the bug/regression with instructions:

Can't include a repro as StackBlitz does not work in IE11.

Trying to run an app that uses NgRx in 11 in non-prod mode produces the following error:

```
ERROR TypeError: Accessing the 'caller' property of a function or arguments object is not allowed in strict mode
```

It occurs here: https://github.com/ngrx/platform/blob/c59c21150293ad2c9ee5b03782b4fda7ce9f15c7/modules/store/src/meta-reducers/immutability_reducer.ts#L23

Seems to be the same issue as this: https://github.com/substack/deep-freeze/issues/6

## Expected behavior:

Using NgRx in dev mode in IE11 should work.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

Angular 8
NgRx 8
Internet Explorer 11

## I would be willing to submit a PR to fix this issue

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Can you reproduce it with the ngrx example-app located in this project? 
If I open up the example app, I can't reproduce this behavior.

**Comment by jonr-elsewhen** [comment]
The underlying issue was that one of the objects in our store had a function property. You can reproduce it in the example app by adding a function to the initial state of some some reducer.

See the PR I submitted for more info. This bug also showed up in ngrx-store-freeze: https://github.com/brandonroberts/ngrx-store-freeze/issues/7
