### ISSUE TITLE
Effects: add minimal setup option for schematics

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1994]
Adds a `minimal` flag when using `ng-add` or `@ngrx/schematics` for effects. 

- Only applies when `--root` flag is used
- Registers an empty array with `EffectsModule.forRoot()`
- No generated effects file

**Comment by santoshyadav198613** [comment]
Can I take it @brandonroberts .

**Comment by brandonroberts** [comment]
@santoshyadav198613 I'm working this one already. Just opened an issue for tracking

**Comment by santoshyadav198613** [comment]
Ok thanks.

**Comment by brandonroberts** [comment]
Fixed via https://github.com/ngrx/platform/pull/1998
