### ISSUE TITLE
Schematics: Add and import feature key for reducer state

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1996]
Currently, when we register a feature, we tie to it the reducer using a string, such as:

`StoreModule.forFeature('users', fromUsers.reducer)`

This would add an exported "feature key" to the reducer file and import it to prevent typos.

In the reducer file:

```ts
export const usersFeatureKey = 'users';
```

Where the feature is registered

```ts
import * as fromUsers from './users.reducer';

@NgModule({
  imports: [
    StoreModule.forFeature(fromUsers.usersFeatureKey, fromUsers.reducer)
  ]
})
```

Where the top-level selector is used

```ts
export const selectUsersState = createFeatureSelector<AppState, UsersState>(fromUsers.usersFeatureKey)
```

I'd propose updating the docs, and example app to use this convention also.

**Comment by jtcrowson** [comment]
I can take this.  I noticed Schematics is labelled, do we want the schematics updated, along with the docs and example app?

**Comment by brandonroberts** [comment]
Yes, all of those should be updated

**Comment by jtcrowson** [comment]
@brandonroberts do you have any setup steps for testing the schematics against a sample project in development?  I've tried some of the steps provided on angular.io but can't seem to get the link to work correctly.

**Comment by jtcrowson** [comment]
Also, should the State interface take advantage of this as well?

```ts
export const authFeatureKey = 'auth'; 

export interface AuthState {
  status: fromAuth.State;
  loginPage: fromLoginPage.State;
}

export interface State extends fromRoot.State {
  [authFeatureKey]: AuthState; // <--- Here
}
```

**Comment by brandonroberts** [comment]
@jtcrowson i don't have any automated steps at the moment. If you can't link the built schematic, just build the package and copy into your `node_modules`. And yes to the state interface, as we're already importing everything from the reducer.

**Comment by jtcrowson** [comment]
@brandonroberts Excuse my inexperience with the schematics library, how do I build?  Then in my sample app, just `npm install $BUILT_LIBRARY` and then `ng generate @ngrx/schematics:store State`?

**Comment by brandonroberts** [comment]
You build schematics using `yarn bazel build //modules/schematics/...`. The built package will be in `dist/bin/modules/schematics/npm_package`

**Comment by jtcrowson** [comment]
I couldn't get the build to work, might be due to my proxy settings.

@brandonroberts just to be sure: **If the feature is not registered, we do not need to generate the feature key, right?**

**Example:**
For the schematics with a module flag (is registered): 
`ng generate reducer User --module app.module.ts`

In reducer file:
```ts
export const usersFeatureKey = 'users';
```
in module file:
```ts
import * as fromUsers from './users.reducer';

@NgModule({
  imports: [
    StoreModule.forFeature(fromUsers.usersFeatureKey, fromUsers.reducer)
  ]
})
```

For the schematics **without** a module flag (is not registered): 
`ng generate reducer User`

In reducer file:
```ts
// no featureKey needed since the feature is not registered
```
in module file:
```ts
@NgModule({
  imports: [
    // not registered because no module flag
  ]
})
```

**Comment by jtcrowson** [comment]
I'm going to submit the PR under that assumption.  The goal is to limit the hardcoded strings, and adding the featureKey only when module is passed for the reducer and entity schematics accomplishes that.

**Comment by brandonroberts** [comment]
I think the feature key should be added either way.  When you eventually register the reducer you should use the key instead of the string.

**Comment by jtcrowson** [comment]
My thought was that in the cases you weren't used the module flag, you weren't planning on registering it.  But I can see it either way, I'll go ahead and add that back in.
