### ISSUE TITLE
Effects should use APP_INITIALIZER instead of APP_BOOTSTRAP_LISTENER

### ISSUE THREAD

**Issue by robwormald** [ngrx/platform#20]
tldr, if you don't actually bootstrap a component, effects doesn't start up. This popped up for an internal team at Google using ngUpgrade, but might also show up if you use `ngDoBootstrap` to start up an angular *app* (instance of a root ngModule) before actually starting UI.

cc @MikeRyanDev @brandonroberts

**Comment by brandonroberts** [comment]
Closed via https://github.com/ngrx/platform/pull/24
