### ISSUE TITLE
build error.

### ISSUE THREAD

**Issue by ycpaladin** [ngrx/platform#200]
sorry, my english is not so good.. 

i got an error as below  when building. 

.../node_modules/@ngrx/store/src/store.d.ts (13,5): Class 'Observable<T>' defines instance member property 'select', but extended class 'Store<T>' defines it as instance member function.

Version:
ngrx/store: 4.0
angular: 4.3.1
typescript:2.4.2
rxjs:5.1.0

the project address is https://github.com/ycpaladin/angular4--ngrx-store

below is the place appear error .

![image](https://user-images.githubusercontent.com/3337028/28680739-cc2fbadc-7329-11e7-82e8-a69b89d66814.png)

**Comment by brandonroberts** [comment]
You need to upgrade to RxJS 5.4.2

**Comment by ycpaladin** [comment]
@brandonroberts  

I hava upgrade to Rxjx 5.4.2. but still appear error.

![image](https://user-images.githubusercontent.com/3337028/28698922-0dde2258-7379-11e7-9e93-2758e27d36ce.png)

**Comment by krjordan** [comment]
@ycpaladin Don't think this will fix your error, but it looks like the `rxjs/Observable.js` warning can be solved by importing `Observable` from `rxjs/Observable` instead of `rxjs/observable`.

**Comment by brandonroberts** [comment]
@ycpaladin Ok. I took a look at your repo and you need to remove `@ngrx/core` from your `package.json` and update the `view-book-page.component.ts` by removing `import '@ngrx/core/add/operator/select';` and updating lines 24-26

```ts
        this.actionsSubscription = route.params
            .map(p => new book.SelectAction(p['id']))
            .subscribe(store);
```

**Comment by ycpaladin** [comment]
@krjordan  The module @**ngrx/core** in my project causing the error.  

@brandonroberts Thanks!  It is working well.

Thanks for your reply!
