### ISSUE TITLE
Store: provideMockStore(), frozen initialState with a Date object

### ISSUE THREAD

**Issue by molily** [ngrx/platform#2003]
## Minimal reproduction of the bug/regression with instructions:

- Set up a component spec that uses `provideMockStore()`.
- Pass an initialState that has a frozen Date object (e.g. `Object.freeze(new Date())`).
- Run spec
- Angular fails while compiling the test module with this exception:

Failed: Cannot add property __anonymousType, object is not extensible
at <Jasmine>
at identifierName (@angular/compiler/fesm2015/compiler.js:2716:1)
at JitEmitterVisitor._emitReferenceToExternal (@angular/compiler/fesm2015/compiler.js:6046:1)
at JitEmitterVisitor.visitExternalExpr (@angular/compiler/fesm2015/compiler.js:6016:1)
at ExternalExpr.visitExpression (@angular/compiler/fesm2015/compiler.js:1276:1)
at @angular/compiler/fesm2015/compiler.js:5683:1
at JitEmitterVisitor.visitAllObjects (@angular/compiler/fesm2015/compiler.js:5714:1)
at JitEmitterVisitor.visitLiteralMapExpr (@angular/compiler/fesm2015/compiler.js:5681:1)
at LiteralMapExpr.visitExpression (@angular/compiler/fesm2015/compiler.js:1457:1)
at @angular/compiler/fesm2015/compiler.js:5695:1
at JitEmitterVisitor.visitAllObjects (@angular/compiler/fesm2015/compiler.js:5714:1)

Example repository:

https://github.com/molily/ngrx-immutability-test

Failing spec:

https://github.com/molily/ngrx-immutability-test/blob/master/src/app/test1.component.spec.ts

This is where the error happens in the compiler:

![Screenshot 2019-07-09 at 13 46 59](https://user-images.githubusercontent.com/51251/60885710-812ffd00-a250-11e9-96ae-2b52b6848bff.png)

While compiling the test module and its component:

![Screenshot 2019-07-09 at 13 47 19](https://user-images.githubusercontent.com/51251/60885736-92790980-a250-11e9-99ea-fe5d8e961ece.png)

EmitterVisitorContext:

![Screenshot 2019-07-09 at 13 48 28](https://user-images.githubusercontent.com/51251/60885750-9b69db00-a250-11e9-9efd-6808800e437f.png)

## Expected behavior:

Spec passes. The fact that the date is frozen should not affect the spec.

When I’m using a full `StoreModule.forRoot()`, it works fine. This spec is green: https://github.com/molily/ngrx-immutability-test/blob/master/src/app/test2.component.spec.ts

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

@angular/compiler: 8.1.0
@ngrx/store: 8.0.1
https://github.com/molily/ngrx-immutability-test/blob/master/package.json

Node 10.15.3, MacOS

## Other information:

I know this is a *very* specific bug yet it happens in my app where all my test fixtures are deeply frozen. I’m doing this so no spec or component/reducer/service etc. under test meddles with the fixtures.

For some reason, the Angular compiler takes the initialState and adds the internal property __anonymousType to its properties. I’m lacking the knowledge of Angular internals to understand what is going on here. I’m not even sure if there is anything wrong in NgRx or whether this is merely a bug or shortcoming in the Angular JIT compiler. Angular seems to resolve the INITIAL_STATE injection token and then iterates over the initialState value, mutating it. Is there a way to prevent this? Thanks.

## I would be willing to submit a PR to fix this issue

[X] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
The issue that you're encountering is due to the angular compiler - https://github.com/angular/angular/blob/master/packages/compiler/src/compile_metadata.ts#L43

The value of `new Date()` is `'Tue Jul 09 2019 19:49:49 GMT+0200 (Central European Summer Time)'`. Because it has a `)` in it, the compiler threats this as a function. 

I'm not sure if it's smart to make `new Date()` your root state.
