### ISSUE TITLE
@ngrx/store: StoreConfig interface missing from exports.

### ISSUE THREAD

**Issue by bhalash** [ngrx/platform#2007]
## Minimal reproduction of the bug/regression with instructions:
This does not require StackBlitz. It appears to be a simple case of either a missing export or incorrect documentation.

## Expected behavior:
In the guide, [Using Dependency Injection -> Injecting Feature Config](https://ngrx.io/guide/store/recipes/injecting#injecting-feature-config) states that you should import `StoreConfig`:

```typescript
import { StoreModule, StoreConfig } from '@ngrx/store';
```

Looking at the source I find that [store_module.ts](https://github.com/ngrx/platform/blob/60633b770e27f6d984abc91a802df5ea9902d80a/modules/store/src/store_module.ts#L89-L93) declares the interface, but [index.ts](https://github.com/ngrx/platform/blob/60633b770e27f6d984abc91a802df5ea9902d80a/modules/store/src/index.ts#L51-L58) in the same folder does not re-export `StoreConfig`.

![Screenshot 2019-07-11 at 12 57 39](https://user-images.githubusercontent.com/1775913/61049093-7fdf0b80-a3db-11e9-9c03-e8cb467256f1.png)

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

* NgRx: `8.1.0`
* Angular: `8.1.0`

## I would be willing to submit a PR to fix this issue

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
Good catch. Go for it

**Comment by timdeschryver** [comment]
While we're at it we also should export `RootStoreConfig`

**Comment by bhalash** [comment]
Done and done, PR open.
