### ISSUE TITLE
Dispatching events within a guard leads to loop in router-store

### ISSUE THREAD

**Issue by PerfectPixel** [ngrx/platform#201]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## What is the current behavior?
Dispatching an action synchronously in a guard leads to a loop.

## Expected behavior:
No loop.

## Minimal reproduction of the problem with instructions:

https://plnkr.co/edit/MNtybtGWdLg2e2dQu3EJ?p=preview

Watch the Console, while you click the link. **NOTE: this causes a loop and will lag out your browser!**

<img width="1233" alt="screen shot 2017-07-27 at 19 05 37" src="https://user-images.githubusercontent.com/2388847/28683027-566231ec-72ff-11e7-9875-3e1cfb64a434.png">

## Analysis
Dispatching the action will lead to [this part](https://github.com/ngrx/platform/blob/master/modules/router-store/src/router_store_module.ts#L191) of the router store that will check if a navigation is necessary. However, `this.router.url` will point to the old route, while `this.storeState['routerReducer'].state.url` will point to the new route. Therefore, routing is cancelled and the same route is activated again, the guard is triggered again and then you have a loop.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
NPM 5.3
Browser: all
OS: all
node 6 LTS
ngrx 4.0.x

**Comment by chrisbenseler** [comment]
Same is happening for me. An action with type: ROUTER_CANCEL is being dispatched, then the infinite loop begins.

**Comment by csutorasr** [comment]
I had some problems with it. I resolved as I wrote it in the Issue #68.

However it should be nice to know which guard caused the cancellation to handle the redirecting properly.

**Comment by PerfectPixel** [comment]
@csutorasr this issue has nothing to do with guards cancelling anything as the guard just returns true.

**Comment by wesselvdv** [comment]
Anyone have a workaround for this issue?

**Comment by PerfectPixel** [comment]
I kicked out `router-store` as it was not used very often in my project. The other "solution" I found was wrapping the dispatch in a timeout.

Both are not very solid solutions...

**Comment by skkonstantin** [comment]
+

**Comment by PerfectPixel** [comment]
There is another effect that is caused by the same mechanism:
If you have a `canDeactivate` guard and cancel route deactivation, then `router-store` will try to route you again.

**Comment by brandonroberts** [comment]
A workaround for this issue is to change the name of the router slice to something other than `routerReducer`. Router store only attempts to navigate when the state changes if the `routerReducer` key is present in the state and the URL doesn't match what's in the state.

**Comment by brandonroberts** [comment]
Fixed via #355
