### ISSUE TITLE
Angular 7 navigationTrigger support with the @ngrx/route

### ISSUE THREAD

**Issue by udi101** [ngrx/platform#2010]
## Other information:
I need to get the navigationTrigger of the last route that was activated. When I register to the router.events I get this data from the NavigationStart events. The ngrx/router-store doesn't trigger an action on browser navigations (back, forward) and the navigationTrigger is not a part of the route state.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
NgRx :7
Angular: 7

## If accepted, I would be willing to submit a PR for this feature
[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
We add the Angular router event in the payload:

```
{
   type: "@ngrx/router-store/request"
   payload: {
     event: {
       id: 3
       navigationTrigger: "imperative"
       restoredState: null
       url: "/"
     }
     ....
   }
}
```


If I use the back button the trigger is also correct:

```
id: 4
navigationTrigger: "popstate"
restoredState: {navigationId: 2}
url: "/login"
```




Could you elaborate a bit more, because it seems to just work.
This is NgRx 8 with Angular 8 tho.
