### ISSUE TITLE
Cannot find module '@ngrx/store/testing'

### ISSUE THREAD

**Issue by diego-unanue-globant** [ngrx/platform#2011]
I have installed ngrx and I want to use '@ngrx/store/testing' but when I try to import:

import { provideMockStore, MockStore } from '@ngrx/store/testing'
ir says module not found.

I tried to do a npm install @ngrx/store/testing but it says "as it does not contain a package.json file."

**Comment by itayod** [comment]
@diego-unanue-globant have you tried to install `@ngrx/store`?

**Comment by jtcrowson** [comment]
Also double check that your installed `@ngrx/store` version is 7.0.0 or above (check `package-lock.json`).  `@ngrx/store/testing` ships inside `@ngrx/store`, but the sub-package was introduced in version 7.0.0.

**Comment by timdeschryver** [comment]
The testing package is included with `@ngrx/store`.
 
As @itayod said, you should install `@ngrx/store`.
`@ngrx/store/testing` was added in NgRx 7, so make sure you have this version (or a later version) installed, as @jtcrowson mentioned.
