### ISSUE TITLE
"Cannot read property 'tree' of undefined" when using "resultMemoize" after updating to 8.1.0

### ISSUE THREAD

**Issue by mrucelum** [ngrx/platform#2013]
## Minimal reproduction of the bug/regression with instructions:

Just open: https://stackblitz.com/edit/angular-qmbwzq and see this error in the console:

``` ERROR Error: Cannot read property 'tree' of undefined ```

The issues seems to be in this part in tree.reducer.ts

```
export const getListValueInformation = (identifier: string) => {
  return createSelectorFactory<any, { name: string }>(simpleObjMemoize)(listValueInformation(identifier));
}
```

If I remove the memoizer, everything works fine (the app works anyways btw, so this errors seems to be not affecting any functionality - at least in my real app). 

So this works fine:
```
export const getListValueInformation = (identifier: string) => {
  return listValueInformation(identifier);
}
```

This error only appeared after I upgraded from ngrx 6.x to ngrx 8.x.
(See also https://stackblitz.com/edit/angular-ilj1pj with ngrx 6.1.2 -> no error!)

Tbh, I am not 100% sure if I maybe just did something wrong there (I read there something of a breaking change about selectors, but as far as I understood this, it should not be directly related to this issue). 

## Expected behavior:

No error.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

Angular 8.x
NgRx 8.1.0

Happens for me at least in Chrome (75.0.3770.100), FF (68.0) and Edge (44.17763.1.0) on Windows 10. I am pretty sure that this is not related to specific browser and/or OS.

## I would be willing to submit a PR to fix this issue

I would if someone could tell me how to fix it. :)

[ x ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
A selector should always have a projector function, in your case it would be:

```
export const getListValueInformation = (identifier: string) => {
  return createSelectorFactory<any, { name: string }>(simpleObjMemoize)(
    listValueInformation(identifier), 
    // this line is added
    s => s 
  );
}
```

**Comment by mrucelum** [comment]
Ah damn... of course! Thank you - and sorry for bothering you with this... :/
