### ISSUE TITLE
Effect devtools

### ISSUE THREAD

**Issue by Odonno** [ngrx/platform#2015]
## Describe any alternatives/workarounds you're currently using

None

## Other information:

The goal would be to provide a devtools/visualizer for @ngrx/effects in the relatively same way we do with state/reducers by the useful @ngrx/store-devtools package.

Indeed, I think that being able to visualize effects in realtime can help developers a lot by:

* visualizing the behavior of a single effect (how each operator combined together work)
* help finding bugs in our applications (by checking the global behavior of effects based on actions dispatched)

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
I think this isn't something that we're looking to create (for now?).
Nicholas Jamieson is working on a RxJS devtools, which is what you're looking for if I'm not mistaken - https://twitter.com/ncjamieson/status/1159095787319463936?s=20
