### ISSUE TITLE
strictStateImmutability + RouterState.Full incompatible with each other

### ISSUE THREAD

**Issue by luchsamapparat** [ngrx/platform#2016]
Enabling `strictStateImmutability` together with `RouterState.Full` as router state serialization leads to errors that are very hard to track down (see angular/angular#31523, ngrx/platform#1937), so the [runtime check documentation](https://ngrx.io/guide/store/configuration/runtime-checks) should probably include a warning that those to configurations are not compatible with each other.

And for future (major) releases the `Minimal` router serialization should maybe be the default...?

## I would be willing to submit a PR for the docs :heart:

[X] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
This is not the first time I see this question, so I agree that it would good to add a warning here.

Do you want to pick this one up @luchsamapparat ?

**Comment by luchsamapparat** [comment]
I'll create a PR on Friday 👍

**Comment by wawyed** [comment]
Sorry to bring up an old post but I'm using the [MinimalRouterStateSerializer](https://ngrx.io/api/router-store/MinimalRouterStateSerializer) but I'm still getting CannotFreeze error from strictStateImmutability. Is this a regresion?
