### ISSUE TITLE
schematics should not ignore sourceRoot

### ISSUE THREAD

**Issue by ben-henoida** [ngrx/platform#2018]
## Minimal reproduction of the bug/regression with instructions:

https://github.com/ben-henoida/ngrx-generate-sourceRoot-bug

1. ng new app
2. cd app
3. ng add @ngrx/store
4. move src to src/main/webapp and update sourceRoot in angular.json
5. ng add @ngrx/store-devtools
6. ng add @ngrx/schematics
7. ng generate store State

==> reducers are created under src/app

## Expected behavior:

should create reducers in src/main/webapp/app (using sourceRoot in angular.json)

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

Angular CLI: 8.1.1
Node: 10.16.0
OS: win32 x64
Angular: 8.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.1
@angular-devkit/build-angular     0.801.1
@angular-devkit/build-optimizer   0.801.1
@angular-devkit/build-webpack     0.801.1
@angular-devkit/core              8.1.1
@angular-devkit/schematics        8.1.1
@ngtools/webpack                  8.1.1
@schematics/angular               8.1.1
@schematics/update                0.801.1
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.35.2

    "@ngrx/schematics": "^8.1.0",
    "@ngrx/store": "^8.1.0",
    "@ngrx/store-devtools": "^8.1.0",

## I would be willing to submit a PR to fix this issue

YES

**Comment by brandonroberts** [comment]
Usage of source root was deprecated in the CLI, which is why we moved away from it.

**Comment by ben-henoida** [comment]
Thank you for your reply.
Angular does not mentionned it being deprecated... (cf https://angular.io/guide/workspace-config)
Can you clarify ?
Is there a way to use @ngrx/schematics if we use a source path different from 'src/app' ?

**Comment by Zarepheth** [comment]
I'm having the same problem, but with a different path.
How do we work around the use of a non-default source path?

**Comment by Zarepheth** [comment]
By using a relative path, I can specify the `--module` location.
```
ng generate store State --root --module /../../mySourceRoot/path/to/app.module.ts
```
Unfortunately, this doesn't work for the `--statePath` option when specifying the desired location of the generated files.
