### ISSUE TITLE
UglifyJSPlugin stopped working with upgrade to 4.0

### ISSUE THREAD

**Issue by etatuev** [ngrx/platform#202]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## What is the current behavior?
I'm getting following error with prod build when using UglifyJsPlugin in webpack after moving to 4.0
```
ERROR in vendor.24c6ee9cd306388aea71.js from UglifyJs
Unexpected token: name (ActionsSubject) [vendor.24c6ee9cd306388aea71.js:115622,6]
```

## Expected behavior:
Minification should just work.

## Minimal reproduction of the problem with instructions:
Application with ngrx 4.0, webpack with embedded UglifyJSPlugin

## Version of affected browser(s),operating system(s), npm, node and ngrx:
node: 6.11.0
npm: 5.3.0
"@ngrx/effects": "^4.0.1",
"@ngrx/store": "^4.0.0",
"@ngrx/store-devtools": "^4.0.0",

## Other information:
"typescript": "2.4.2",
"webpack": "^3.4.1",
"awesome-typescript-loader": "^3.2.2",

```
ts-config:
{
    "include": [
        "src/**/*",
    ],
    "exclude": [
        "node_modules",
        "dist"
    ],
    "compileOnSave": true,
    "compilerOptions": {
        "allowJs": true,
        "target": "es5",
        "module": "commonjs", // esnext
        "moduleResolution": "node",
        "sourceMap": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "lib": [
            "es2017.object",
            "es2015",
            "dom"
        ],
        "noEmitHelpers": true,
        "importHelpers": true,
        "strict": true,
        "strictNullChecks": false,
        "skipLibCheck": true,
        "suppressImplicitAnyIndexErrors": true,
        "typeRoots": [
            "node_modules/@types"
        ],
        "outDir": "dist/tsc"
    },
    "awesomeTypescriptLoaderOptions": {
        "forkChecker": true,
        "useWebpackText": true
    }
}
```

:heartpulse: ngrx? Please consider supporting our collective: 👉  [donate](https://opencollective.com/ngrx/donate)

**Comment by alexander-heimbuch** [comment]
We are also struggling with angular CLI prod builds since upgrading to ngrx 4. It's working without problems in development but prod throws this on runtime:
```
vendor.bundle.js:78017 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'group' of undefined
TypeError: Cannot read property 'group' of undefined
    at ErrorReporter.webpackJsonp.../../../../@ngrx/effects/@ngrx/effects.es5.js.ErrorReporter.report
```

**Comment by brandonroberts** [comment]
Please provide a reproduction of this issue in a repository

**Comment by etatuev** [comment]
@brandonroberts 
Problem is that @ngrx/store/src/actions_subject.js file in npm package has ES6 class in output. It's break IE and UglifyJS. My current workaround is to add Babel to pre-transpile @ngrx.

**Comment by brandonroberts** [comment]
You shouldn't have to do that though. What's your tsconfig look like?

**Comment by etatuev** [comment]
If it's just my misunderstanding of build process - it will be excellent, I'm quite new in modern front-end development :)

Here is it:

```
{
    "include": [
        "src/**/*",
        "plugins/**/*"
    ],
    "exclude": [
        "node_modules",
        "dist"
    ],
    "compileOnSave": true,
    "compilerOptions": {
        "allowJs": true,
        "target": "es5",
        "module": "esnext",
        "moduleResolution": "node",
        "sourceMap": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "lib": [
            "es2017.object",
            "es2015",
            "dom"
        ],
        "noEmitHelpers": true,
        "importHelpers": true,
        "strict": true,
        "strictNullChecks": false,
        "skipLibCheck": true,
        "suppressImplicitAnyIndexErrors": true,
        "typeRoots": [
            "node_modules/@types"
        ],
        "outDir": "dist/tsc"
    },
    "awesomeTypescriptLoaderOptions": {
        "forkChecker": true,
        "useWebpackText": true
    }
}
```
