### ISSUE TITLE
defaultDataServiceConfig  configurations example 

### ISSUE THREAD

**Issue by harmnot** [ngrx/platform#2027]
I want to set the url DefaultDataServiceConfig on NgRx/data, but the documentation not clear
can u all give example ? because when I getData the api hit the localhost which my localhost angular e.g http://localhost:4200/api/myentity 
my server is on port 3000 tho, but I saw that I could change it with this documentation :
https://ngrx.io/api/data/DefaultDataServiceConfig
but still not clear

**Comment by evgenyfedorenko** [comment]
@timdeschryver should we take this one?

**Comment by guyng** [comment]
@evgenyfedorenko Yeah i aswell need a custom port and i can't find any documentation how/where should i config it

**Comment by guyng** [comment]
@timdeschryver .

**Comment by timdeschryver** [comment]
We're always looking for documentation improvements.
Feel free to take this one @evgenyfedorenko 👍

**Comment by evgenyfedorenko** [comment]
Alright, on it.

**Comment by evgenyfedorenko** [comment]
@timdeschryver is it actually possible to set a different url for API endpoint when using @ngrx/data? B/c right now it seems like DefaultDataServiceConfig::root only accepts relative path.

**Comment by EnricoVogt** [comment]
This seems related to #2071

**Comment by evgenyfedorenko** [comment]
@timdeschryver still need to hear your opinion.

**Comment by timdeschryver** [comment]
Sorry, I missed this @evgenyfedorenko .

Seems like this is resolved in https://github.com/ngrx/platform/pull/2075 right?

**Comment by evgenyfedorenko** [comment]
on nice, let's close this one then?
