### ISSUE TITLE
How to handle a long running effect?

### ISSUE THREAD

**Issue by varghesep** [ngrx/platform#2034]
This is not a defect, but a question only.

An effect in my application takes 2 to 3 minutes to complete, and it can further be more slower in the future due to the data in the datasore is growing. Right now a ```http``` request is made and wait for that call to be succeeded and then a success action is sent. The reducer catches that action and navigate to a ```home``` page. during that time of starting and navigation, the screen is almost frozen. Instead of a frozen screen, I want the app to be routed to the ```home``` page and when the effet is successful, show a notification and update the home page with latest stats from the ```ngrx store```. How can I do that in an effect?

**Comment by timdeschryver** [comment]
Support questions should be asked on [stackoverflow (with a ngrx tag)](https://stackoverflow.com/questions/tagged/ngrx) or the [gitter channel](https://gitter.im/ngrx/platform).

Maybe web workers? - [Running in Parallel: NgRx with WebAssembly, Web Workers and Worklets by Vitalii Bobrov](https://www.youtube.com/watch?v=AJsDy_45Yuc)
