### ISSUE TITLE
Attempting to configure '__@ngrx/effects_create__' with descriptor '{"value":{"dispatch":true,"resubscribeOnError":false}}' on object 'undefined' and got error, giving up: TypeError: Object.defineProperty called on non-object

### ISSUE THREAD

**Issue by techyaura** [ngrx/platform#2036]
## Minimal reproduction of the bug/regression with instructions:
1. Open app 
2. Home page leads to login page
3. Enter email & password
4. Click on login.
Observed result : -
On Dispatching the login action, corresponding effect is not executing.

## Expected behavior:
Should able to call the effect when dispatch the login action.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
"@ngrx/effects": "^8.1.0",
"@ngrx/router-store": "^8.1.0",
"@ngrx/store": "^8.1.0",
"@ngrx/store-devtools": "^8.1.0",
"@angular/animations": "~8.1.2",
"@angular/common": "~8.1.2",
"@angular/compiler": "~8.1.2",
"@angular/core": "~8.1.2",
"@angular/forms": "~8.1.2",
"@angular/platform-browser": "~8.1.2",
"@angular/platform-browser-dynamic": "~8.1.2",
"@angular/router": "~8.1.2",
_NODEJS- v10.16.0_

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by jtcrowson** [comment]
@techyaura Would you mind editing this issue to provide a summarized title and detailed reproduction steps?  I'm having a hard time interpreting the issue with it's current structure.  Thanks!

**Comment by techyaura** [comment]
Sure @jtcrowson.

**Comment by techyaura** [comment]
Hi @jtcrowson ,

I have updated the issue & here is the repo URL. If you need some more info from my side, Please let me know.

Thanks

**Comment by timdeschryver** [comment]
I don't want to sound harsh but please don't type everything as `any`, because this is the problem of why you haven't "caught" the mistakes. 

- if you dispatch the action from the component, don't use `loginSuccess`, but use `login`
- return the actions stream in the effect: `return this.actions$.pipe(...)`
- don't return the dispatch in the effects, but return the success action:  `return loginSuccess(userResponse)`

**Comment by techyaura** [comment]
Thanks a lot @timdeschryver. You saved me.

> I know this sound harsh but please don't type everything as any, because this is the problem of why you haven't "caught" the mistakes.

Definitely Just from now. I will try to make out my best when using types.

> if you dispatch the action from the component, don't use loginSuccess, but use login

Here i had used the login only but `loginsuccess` tried for testing only.

> return the actions stream in the effect: return this.actions$.pipe(...)

That's was the thing `return`, which let me to take my head on the wall for the whole night. Thanks again for this quick response.

> don't return the dispatch in the effects, but return the success action: return loginSuccess(userResponse)

Sure, will not going happen from today.

_**Thanks a lot for your valuable time.**_ :)
