### ISSUE TITLE
Production build fails with initial configuration.

### ISSUE THREAD

**Issue by Adam-Michalski** [ngrx/platform#2038]
Production build fails with initial configuration.

[Get Started StackBlitz Example](https://stackblitz.com/edit/angular-ngrx-8-fail)

Download sources, install packages `npm i` and build with `ng build --prod`

```
ng build --prod

Date: 2019-07-31T11:36:32.903Z
Hash: b143f63947732859cca6
Time: 3646ms
chunk {0} runtime.ec2944dd8b20ec099bf3.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} main.9868d9b237c3a48c54da.js (main) 128 bytes [initial] [rendered]
chunk {2} polyfills.85f47f0bf59079cbc23a.js (polyfills) 130 bytes [initial] [rendered]
chunk {3} styles.5413946c31efe8ce9712.css (styles) 0 bytes [initial] [rendered]

ERROR in src\app\app.module.ts(16,34): Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'createReducer' was called in 'counterReducer'
    'counterReducer' calls 'createReducer' at src\app\counter.reducer.ts(6,31).
```
## Expected behavior:

Build without errors

## Assumptions

I have found few issues pointing to: 

[Docs](https://github.com/ngrx/platform/blob/master/docs/store/api.md#injecting-reducers)

But is this Token Injection only solution and there is no mention about that if you don't use Injection you can't run application in production.

I assume it's JIT connected issue.

I have fixed this error by only closing `appReducers` in `InjectionToken`:

```
import { InjectionToken } from '@angular/core';
import { ActionReducerMap } from '@ngrx/store';
import { serviceUiDynamicConfigReducer } from '../ngrx/reducers/service-ui.reducers';

export const appReducers = {
  serviceUiConfig: serviceUiDynamicConfigReducer,
};

export const REDUCER_TOKEN = new InjectionToken<ActionReducerMap<any>>('Registered Reducers', {
  factory: () => {
    // return reducers synchronously
    return appReducers;
  },
});

```
And then using this by     `StoreModule.forRoot(REDUCER_TOKEN)` in  AppModule

But is this redundant code?

## Other information:

    "@ngrx/store": "8.1.0",
    "@angular/core": "7.2.15",

**Comment by timdeschryver** [comment]
This is not redundant, but needed in order to be able to compile in AOT.

Instead of creating injection tokens, you can also wrap your reducer inside a "function reducer":

```
export  function reducer(state, action){
  return counterReducer(state, action)
}
```

The appmodule would use this reducer, as:

```
   StoreModule.forRoot({count: reducer})
```
