### ISSUE TITLE
Code unclear in demo app (book.effects.ts)

### ISSUE THREAD

**Issue by colinskow** [ngrx/platform#2039]
I am a bit perplexed by this line in the demo code. I've never seen this type of syntax before. It looks a bit like a curried function, but I see nothing about it in the `createEffect` documentation.

`() => ({ debounce = 300, scheduler = asyncScheduler } = {}) =>`

https://github.com/ngrx/platform/blob/master/projects/example-app/src/app/books/effects/book.effects.ts#L35

Perhaps this could be explained in a comment in the code to help others. Is this simply to define constants for debounce and scheduler?

**Comment by manklu** [comment]
It's a destructuring operation: https://basarat.gitbooks.io/typescript/content/docs/destructuring.html

>  Is this simply to define constants for debounce and scheduler?
Yep

**Comment by timdeschryver** [comment]
This is touched on in our docs of testing effects.

https://ngrx.io/guide/effects/testing#effects-with-parameters

**Comment by colinskow** [comment]
Thanks @manklu I didn't know it was possible to set default values inside object destructuring. It is indeed a curried function.
