### ISSUE TITLE
When --strict feature selector does not compile

### ISSUE THREAD

**Issue by alvipeo** [ngrx/platform#2041]
I have an angular 8.2.0 app with ngrx 8.2.0 and I enabled `--strict` option for typescript (3.5.3).
My app has a feature module (lazy loading) and I use the standard technique to extend AppState and creating selectors:

**app.state** (global):
```
export interface AppState {
  [fromAppRouter.routerFeatureKey]: fromRouter.RouterReducerState;
  [fromWip.featureKey]: fromWip.WipState;
  [fromAuth.authFeatureKey]: fromAuth.AuthState;
  [fromLang.layoutFeatureKey]: fromLang.LangState;
  error: IlgError | null;
}
...
```

and **feature state** (pageBlock.reducer.ts):

```
import * as root from "src/app/state";
import { PageBlockInfo } from "../models";

export const pagesFeatureKey = "pages";

export interface PageBlockState extends EntityState<PageBlockInfo> {}

export interface AppState extends root.AppState {
  [pagesFeatureKey]: PageBlockState;
}

export const pageBlocksAdapter: EntityAdapter<PageBlockInfo> = createEntityAdapter<PageBlockInfo>({
  selectId: pb => pb.pageBlockId,
  sortComparer: sortByName
});

export const initialPageBlocksState: PageBlockState = pageBlocksAdapter.getInitialState({
  // additional entity state properties
});

const pageBlockReducer = createReducer(
  initialPageBlocksState,
...
);

export function reducerPageBlock(state: PageBlockState | undefined, action: Action) {
  return pageBlockReducer(state, action);
}

export const getPageBlocksState = createFeatureSelector<AppState, PageBlockState>(pagesFeatureKey);

export const getSelectedPageBlockId = createSelector(
  getPageBlocksState,
  root.selectPageBlockId,
  (pageBlockState: PageBlockState, selectedPageBlockId) => {
    return selectedPageBlockId;
  }
);

export const {
  selectIds: getPageBlockIds,
  selectEntities: getPageBlockEntities,
  selectAll: getPageBlocks,
  selectTotal: getBlocksCount
} = pageBlocksAdapter.getSelectors(getPageBlocksState);

export const getSelectedPageBlock = createSelector(
  getPageBlockEntities,
  getSelectedPageBlockId,
  (entities, selectedId) => (!!selectedId ? entities[selectedId] : undefined)
);
```

and here's **the usage of the selector** in my component:
```
@Component({
  selector: "ilg-pageblock-edit",
  template: `
    <ilg-pageblock-form [pageBlock]="selectedPageBlock$ | async"></ilg-pageblock-form>
  `
})
export class IlgPageBlockEditComponent implements OnInit {
  selectedPageBlock$: Observable<PageBlockInfo | undefined> = this.store.pipe(
    select(getSelectedPageBlock)   // **============> ERROR**
  );

  constructor(private store: Store<AppState>) {}

  ngOnInit() {}
}
```
**Notice the ERROR** which is the following:
> TS2345: Argument of type '(source$: Observable<AppState>) => Observable<PageBlockInfo | undefined>' is not assignable to parameter of type 'OperatorFunction<AppState, PageBlockInfo | undefined>'.
Types of parameters 'source$' and 'source' are incompatible.
    Type 'import("E:/.../node_modules/rxjs/internal/Observable").Observable<import("E:.../app/state/index").AppState>' is not assignable to type 'import("E:/.../node_modules/rxjs/internal/Observable").Observable<import("E:/.../app/pages/state/page-block.reducer").AppState>'.
      Property '[pagesFeatureKey]' is missing in type 'import("E:/.../app/state/index").AppState' but required in type 'import("E:/.../app/pages/state/page-block.reducer").AppState'.

My understanding is this is because we extend global AppState in a feature module but TypeScript has no idea about it. Is that correct? Can we workaround it somehow? Or is there my mistake somewhere maybe?

Thank you!

**Comment by alvipeo** [comment]
btw, you can get away with this config:
```
// "strict": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "strictBindCallApply": true,
    "strictNullChecks": true,
    // "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
```
so the only unresolved option is **_strictFunctionTypes_**.

**Comment by timdeschryver** [comment]
Can you reproduce this in a github repo?

**Comment by alvipeo** [comment]
yes, today or tomorrow

**Comment by Ketec** [comment]
Seems I got something similar:
```

Argument type MonoTypeOperatorFunction is not assignable to parameter type OperatorFunction
  Type unknown is not assignable to type ICategory[]
    Type unknown is not assignable to type Array unknown icategory icategory
```

when using `pipe(take(1))` on store select.

**Comment by alvipeo** [comment]
sorry, it took me so long... there's a big project going on.

anyway, here's the app and the repo - [https://github.com/alvipeo/typestrict](url)

**Comment by timdeschryver** [comment]
The problem here isn't the selector, but how the selector is used.

Import the `AppState` from `../state/event-details.reducer` (`import { getSelectedEvent, AppState } from "../state/event-details.reducer";` to be complete) in `event-details-impl.service` and you will be able to build the project.

**Comment by alvipeo** [comment]
oh, thank you! stupid me... )
