### ISSUE TITLE
StoreModule.forFeature description is repeated in the docs. 

### ISSUE THREAD

**Issue by iamkdev** [ngrx/platform#2042]
![ngrx io_api_store_StoreModule](https://user-images.githubusercontent.com/1850968/62409411-4c675980-b5f4-11e9-8cdc-4728636ab6da.png)

## Other information:
Go to https://ngrx.io/api/store/StoreModule
Check the description for forFeature, which seems repeated. I think it can be removed.

## I would be willing to submit a PR for the docs :heart:
I can, but didn't find the file within ngrx repo.

[ x ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by jtcrowson** [comment]
Yes, they are similar, but the reducer parameter in the first function is noted to be of type `ActionReducerMap | InjectionToken`, and the reducer parameter in the second function is noted to be of type `ActionReducer | InjectionToken`.

**Comment by timdeschryver** [comment]
See @jtcrowson answer.
