### ISSUE TITLE
Component: Problem with extending onChanges  hook

### ISSUE THREAD

**Issue by BioPhoton** [ngrx/platform#2049]
## Minimal reproduction of the bug/regression with instructions:

Normally live cycle hooks are extended by overwriting the Component_Definitions 

```typescript
   originalHook = component.constructor[NG_COMPONENT_DEF][hookName];

 target[hook] = function(args) {
      // custom stuff here
      originalHook && originalHook.call(component, args);
    };
```

Unfortunately, the `onChanges` feature is different than the rest and it is not possible to extend it in a normal way. The `onChanges` feature is created over [wrapOnChanges](https://github.com/angular/angular/blob/e688e02ee442658c754d813e84a9908baf874520/packages/core/src/render3/features/ng_onchanges_feature.ts#L58) that encapsulates the `this`

So the current hack is to extend the components `ngOnChanges` method which gets called inside of the `NG_COMPONENT_DEF` 's `onChanges` function.

```typescript
 originalHook = component['ngOnChanges'];

 component['ngOnChanges'] = function(args) {
      // custom stuff here
      originalHook && originalHook.call(component, args);
    };
```

See details [here](https://github.com/ngrx/platform/pull/2046/commits/4b43786db30b4ef71ff1bcbeadcc62a435175f50)

## Expected behavior:

I believe ivy should provide a more extendable way for it's lifecycle hooks as well as a consistent implementation of all hooks.

However, I'm not sure if this is by design or a miss conception. 

## I would be willing to submit a PR to fix this issue

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by dummdidumm** [comment]
On a broader note: Calling it like `originalHook && originalHook.call(component, args);` is wrong, it should be `originalHook && originalHook.call(this, args);`. This also wrong in the current state of the ngrx-components-branch.

**Comment by BioPhoton** [comment]
Thanks @dummdidumm!

ATM the state service which handles the primitive functionality of observables like set or connect streams and subscription handling can hook into un composable functions.

When ivy features land we can implement proper behavior.

Find the current status of release candidates functionality here: https://github.com/ngrx/platform/pull/2046
