### ISSUE TITLE
Router doesnt update itself

### ISSUE THREAD

**Issue by mkbryla** [ngrx/platform#205]
After upgrade from ngrx2 to 4 when I try to observe actions on ROUTER_NAVIGATION it fires up but the router its not active... its url is just "/" but page changes its url address and router does not notice that change. Did you change some order? On previous version it worked. Do you have any idea why it doesnt work now?

<pre><code>
@Injectable()
export class AccommodationListEffects {
  constructor(private actions$: Actions, private http: HttpService, private router: Router,
              private roomsApi: RoomsApiService, private route: ActivatedRoute,
              private utils: UtilsService) {
                console.log('init');
              }

  @Effect()
  public trigger$: Observable<any> = this.actions$
  .ofType(ROUTER_NAVIGATION)
    .do(console.log)
  .map((state) => {
    if (this.router.isActive(`${MarketConfig.href()}/list`, false)) {
      return {
        type: accommodationListActions.ActionTypes.FETCH_START
      };
    }
    console.log('NOT ACAS')
    return {
      type: 'NO_ACTION'
    };
  });
</code></pre>

**Comment by valdestrijus** [comment]
I used Location for checking current routes in Effects like this:

```

@Injectable()
export class AccommodationListEffects {
  constructor(private actions$: Actions, private http: HttpService, private location: Location,
              private roomsApi: RoomsApiService, private route: ActivatedRoute,
              private utils: UtilsService) {
                console.log('init');
              }

  @Effect()
  public trigger$: Observable = this.actions$
  .ofType(ROUTER_NAVIGATION)
    .do(console.log)
  .map((state) => {
    if (this.location.isCurrentPathEqualTo(`${MarketConfig.href()}/list`)) {
      return {
        type: accommodationListActions.ActionTypes.FETCH_START
      };
    }
    console.log('NOT ACAS')
    return {
      type: 'NO_ACTION'
    };
  });

```

**Comment by mkbryla** [comment]
Thanks! I will try that tomorrow and give an update if that works for me too
