### ISSUE TITLE
RFC: Component: Evaluation of using angular's internal `ɵdetectChanges` method

### ISSUE THREAD

**Issue by BioPhoton** [ngrx/platform#2050]
## Minimal reproduction of the bug/regression with instructions:

At the moment the `puah$` pipe relies on `detectChanges` or `markForCheck` from the `ChangeDetectorRef` [injected over the pipes constructor](https://github.com/ngrx/platform/blob/ngrx-component-setup/modules/component/src/push%24/push%24.pipe.ts#L34)

Here my question:
I have a [detectChanges](https://github.com/ngrx/platform/blob/ngrx-component-setup/modules/component/src/push%24/operators/detectChanges.ts) operator that is used to fire eighter `markForCheck` or if the related ivy bug is fixed `detectChanges`. I will replace the internal logic later no.
This operator takes the components/decorators/pipes `ChangeDetectorRef`. 

```typescript
export function detectChanges(
  cdr: ChangeDetectorRef
): UnaryFunction<Observable<unknown>, Observable<unknown>> {
  return pipe(tap(_ => cdr.detectChanges()));
}
```

## Expected behavior:

Would it make sense to create a detectChanges operator that receives `this` and calls the internal angular `detectChanges` function?

Does it have any downsides in performance?

```typescript
import { ɵdetectChanges as detectChanges } from '@angular/core';

export function detectChanges(
  comp: ComponentInstance
): UnaryFunction<Observable<unknown>, Observable<unknown>> {
  return pipe(tap(_ => detectChanges(comp)));
}
```

## I would be willing to submit a PR to fix this issue

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by BioPhoton** [comment]
Now this situation is implemented as:

```typescript
import {
  ChangeDetectorRef,
  NgZone,
  ɵdetectChanges as detectChanges,
  ɵmarkDirty as markDirty,
} from '@angular/core';
import { AsyncPipe } from '@angular/common';

import { isIvy } from './ivy-check';
import { isZoneLess } from './zone-check';

export function getChangeDetectionHandler(
  ngZone: NgZone,
  cdRef: ChangeDetectorRef
): <T>(component?: T) => void {
  // @TODO test it properly!!!
  if (isIvy(AsyncPipe)) {
    return isZoneLess(ngZone) ? detectChanges : markDirty;
  } else {
    return isZoneLess(ngZone)
      ? cdRef.detectChanges.bind(cdRef)
      : cdRef.markForCheck.bind(cdRef);
  }
}
```

see PR: https://github.com/ngrx/platform/pull/2046

**Comment by manklu** [comment]
@BioPhoton AFAIK ɵdetectChanges and ɵmarkDirty are considered as part of the private API and are subject to change without notice.
