### ISSUE TITLE
Store: Proposal: Add Higher Order Component decorator

### ISSUE THREAD

**Issue by itayod** [ngrx/platform#2053]
## Summary

Since in most of the cases, each `containerComponent` has its own `reducer` function and `actions` file we could create a `store` for a specific container component. We can do achieve that with by adding a Higher Order Component decorator, with store configuration for "container components", which will create a store for the specific component.

## Advantages

Creating Hoc for components could bring some very nice benefits:

* Connect state object to the component instance
* An ability to add property decorator for `selectors`, by reflecting the metadata.
* An ability to unregister state onDestroy.
* Creating life cycle hooks for Component.
* Reduce a lot of the user's boilerplate.
* Control the user's selectors which will allow us to release the memoized data. 

## Disadvantages

* The component should be unique since the state key is unique (or we could maybe find a way to overcome it?).

## If accepted, I would be willing to submit a PR for this feature

[ X] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
Thanks for the proposal @itayod! We are looking at ways of accomplishing this with Ivy, so I'd like us to take a step back and not just think "How can I do this with a decorator".

**Comment by itayod** [comment]
Thanks, @brandonroberts,
Sure, the Ivy release is the reason I opened this issue :)

I have recently played with HOC's in Ivy 

For example, I created an [auto-unsubscribe](https://ivy.ng-run.com/edit/2jqY7nJ528JJD1uxduZS?open=app%2Fchild%2Fchild.component.ts&layout=1&aot=false
) 

Anyway, I am happy to hear that you are working on a way to accomplish that :)

**Comment by brandonroberts** [comment]
Component Store will satisfy most of the requirements here. Closing this one

**Comment by itayod** [comment]
> Component Store will satisfy most of the requirements here. Closing this one

True 😄
