### ISSUE TITLE
Props not passed to createAction for setScores Action

### ISSUE THREAD

**Issue by chriswininger** [ngrx/platform#2054]
## Other information:
On the `https://ngrx.io/guide/store/reducers` page there is an example which appears to be missing some necessary code.

setScores is defined as:

```
export const setScores = createAction('[Scoreboard Page] Set Scores');
```

Then the reducer for this action has the following definition:

```
 on(ScoreboardPageActions.setScores, (state, { game }) => ({ home: game.home, away: game.away }))
);
```

As is typescript is confused by `{ game }`. The problem appears to be resolved, by supply createAction with props

```
export const setScores = createAction('[Scoreboard Page] Set Scores', props<{ game: State }>());
```

I would be willing to create a pr against the docs, but I am not sure where the source for `https://ngrx.io/guide/store/reducers` is. I looked in ngrx/platform at the docs directory, but these appear to be for an older version of ngrx.

Does this change make sense? Are there any existing issues reported against this that I missed? Could someone point me to the source for https://ngrx.io/guide/store/reducer?

## I would be willing to submit a PR for the docs :heart:

[ X] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Great catch!
For our docs, you can edit them via the pencil icon on the top of the page:

![image](https://user-images.githubusercontent.com/28659384/62726577-df026100-ba17-11e9-9322-43293131b0f9.png)

You can edit the docs for this issue at https://github.com/ngrx/platform/blob/master/projects/ngrx.io/content/guide/store/reducers.md

Do you want to create a Pull Request for this? 
To get up and running you can take a look at our [contributing page](https://ngrx.io/contributing). Feel free to ask questions along the way.
