### ISSUE TITLE
Auxiliary verb missing on Getting Started page

### ISSUE THREAD

**Issue by anno1985** [ngrx/platform#2056]
An auxiliary verb (`is`) seems to be missing on the Getting Started page about [here](https://ngrx.io/guide/store#key-concepts):

> State `is` accessed with the Store, an observable of state and an observer of actions.

(All other items in the list use the simple present, so having the simple past here makes me anticipate another verb in the sentence, which never appears, and thus trips me up while reading. On its own, the sentence makes a perfectly good list item...)

## Other information:

I would have raised a PR but I'm not sure what repo I'd have to clone. [This one](https://github.com/ngrx/platform/blob/master/docs/store/README.md) seems to be the wrong one...
> The documentation below is for NgRx versions 6.x and older.

Anyway, I was mainly curious to find out where the current docs are stored on git... :)

## I would be willing to submit a PR for the docs :heart:

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
You can edit our docs via the pencil icon on the top of the page:

![image](https://user-images.githubusercontent.com/28659384/62726577-df026100-ba17-11e9-9322-43293131b0f9.png)

There is also a guide to contribute on our [contributing page](https://ngrx.io/contributing).
