### ISSUE TITLE
Update and upsert functions are not taking into account removed properties

### ISSUE THREAD

**Issue by maxime1992** [ngrx/platform#2061]
## Minimal reproduction of the bug/regression with instructions:

I have an object that has some optional fields.
Let say that the interface looks like the following:

```ts
interface MyObject {
  propA: string;
  propB?: string;
}
```

If at a given point in time the object is set in the store with both properties and I want to remove the optional one later, I can (using update or upsert).

CF this line: https://github.com/ngrx/platform/blob/4e4c50f1a010a7f51e190950b9b465f1f289b79f/modules/entity/src/unsorted_state_adapter.ts#L100

The repro doesn't need a full ngrx repro, following should be enough:

```ts
Object.assign(
  {},
  { propA: 'a original', propB: 'B original' },
  { propA: 'a updated and optional B is not needed anymore!' } // note that I'm trying to remove propB here!
);
```

Output:

```
{ propA: "a updated and optional B is not needed anymore!", propB: "B original" }
```

## Expected behavior:

Output should be:

```
{ propA: "a updated and optional B is not needed anymore!" }
```

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

Ngrx `8.2.0`

## I would be willing to submit a PR to fix this issue

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

I could work on a PR if I'm not the only one considering the current behavior as a bug :)

**Comment by manklu** [comment]
see https://github.com/ngrx/platform/issues/1604

**Comment by manklu** [comment]
@maxime1992 Issue https://github.com/ngrx/platform/issues/1604 contains the answer for upsert, work as designed.

**Comment by maxime1992** [comment]
Indeed. Feels like passing an option to the method might be a good think rather than having to set all the fields to remove to null or undefined though.

**Comment by timdeschryver** [comment]
Closing in favor of #2369
