### ISSUE TITLE
strict serializability check for actions should happen *after* the action creator is ran

### ISSUE THREAD

**Issue by kevinbeal** [ngrx/platform#2063]
I'm using the `createAction` overload which allows for a function as the second parameter. In that function, I'm making a currently unserializable object serializable. This is too late however as the check happens before this function is ran.

If this function is not supposed to be used to normalize, format, modify in some way data before it's sent to the reducer, then what is it for?

## Describe any alternatives/workarounds you're currently using

I'm doing this logic before I do the dispatch.

## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

**Comment by agugan** [comment]
Hi @kevinbeal 
Do you currently have a stackblitz demo that reproduces this?Or if not can you post one?

**Comment by timdeschryver** [comment]
The serializability check happens when the action is dispatched to the store, not when you call `createAction`. 

My guess is that the action is not serializable, feel free to re-open the issue with a reproduction/the dispatched action.
