### ISSUE TITLE
MyCounterComponent is missing in app.module.ts

### ISSUE THREAD

**Issue by Hernan12345** [ngrx/platform#2064]
MyCounterComponent should be imported like this?? (see below)
declarations: [AppComponent, MyCounterComponent],

**Comment by jordanpowell88** [comment]
@Hernan12345 Unless I am misunderstanding your issue it appears to already be there.

<img width="732" alt="Screen Shot 2019-08-15 at 6 28 16 AM" src="https://user-images.githubusercontent.com/3605268/63089462-f1076680-bf25-11e9-971e-394ef1a2c265.png">

**Comment by timdeschryver** [comment]
It's unclear what the question is, but it seems as @jordanpowell88 already provided an answer. 
Please feel free to re-open the issue, but with more information if the answer provided wasn't what you were looking fore.
