### ISSUE TITLE
RFC: Effects: Dispatch multiple actions at OnInitEffects lifecycle

### ISSUE THREAD

**Issue by talohana** [ngrx/platform#2068]
## Describe any alternatives/workarounds you're currently using
In case I need to dispatch multiple actions at `OnEffectsInit`, I create a general `initAction`,
create an effect with `ofType(initAction)` and dispatch the multiple actions I need with `mergeMapTo`.

For example:

```
  const init = createAction('[My Feature] Init');
  const subscribeToUsers = createAction('[My Feature] Subscribe to users');
  const subscribeToPosts = createAction('[My Feature] Subscribe to posts');

  @Injectable()
  export class MyFeatureEffects implements OnInitEffects {
    init$ = createEffect(() => 
      this.actions$.pipe(
        ofType(init),
        mergeMapTo([subscribeToUsers(), subscribeToPosts()])
      )
    )

    subscribeToUsers$ = createEffect(() => 
      this.actions$.pipe(
        ofType(subscribeToUsers)
        .
        .
      )
    )

    subscribeToPosts$ = createEffect(() => 
      this.actions$.pipe(
        ofType(subscribeToPosts)
        .
        .
      )
    )

    ngrxOnInitEffects(): Action {
      return init();
    }

    constructor(private actions$: Actions) {}
  }
```

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Dispatching multiple actions at once is considered an anti-pattern. 

> Actions express unique events that happen throughout your application

The action dispatched would be a `Feature B Loaded`, and multiple effects can listen for this action to process a side effect.

**Comment by luchsamapparat** [comment]
@timdeschryver could you provide an explanation for why this is regarded as an anti-pattern?

It's basically prevents the Splitter pattern from the *Enterprise Integration Patterns* book (https://blog.nrwl.io/ngrx-patterns-and-techniques-f46126e2b1e5#cdd3) - so I'm not quite convinced that this should be seen as an anti-pattern.

**Comment by Edouardbozon** [comment]
@luchsamapparat [here is a talk](https://www.youtube.com/watch?v=JmnsEvoy-gY) from Mike Ryan that provides explanations about why this is an anti-pattern.
