### ISSUE TITLE
@ngrx/data docs- Clarify what the 'root' parameter means in DefaultDataServiceConfig class docs

### ISSUE THREAD

**Issue by mxdmedia** [ngrx/platform#2071]
IMO, the DefaultDataServiceConfig class docs are not very clear.  In particular, I spent way too much time trying to figure out how to hit an API that was not local.  The 'root' parameter is listed as:

> root path of the web api (default: 'api')

As there is no indication here regarding the domain and port, I was under the assumption that this value was simply the root path portion of the URL- i.e.- the common path *after* the address and port.  I spent more time than I'd like to admit trying to figure out where to change the domain and port, only to discover that it should all be set in this parameter.

This could be cleared up with an example or two.  Perhaps a description like:

> root path of the web api.  e.g.: 'api' or 'https://api-domain.com:8000/api/v1' (default: 'api')

Additionally, using a remote API is a very common use-case.  It would be nice to have a brief description on how to do so in the Overview/Getting Started sections (rather than just a line that says "you can override the default behavior of '/api' with no hint as to where to look).

## I would be willing to submit a PR for the docs :heart:

[X] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
If you want, you can create a PR @mxdmedia
