### ISSUE TITLE
How to we update additional entity properties?

### ISSUE THREAD

**Issue by sagunpandey** [ngrx/platform#2079]
## I would be willing to submit a PR for the docs :heart:

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

I have a reducer where I am updating an entity state by using addAll(). While adding I need to set some other custom entity properties too. I tried checking the [docs](https://ngrx.io/guide/entity/adapter) but couldn't find anything on it. I could have created a second action for just setting those custom properties I guess. But I was wondering if there is a way to set those properties while using adapter methods.

**Comment by manklu** [comment]
@sagunpandey
I would say it depends on what updates you need. Setting some attributes to (nearly) fixed values or complex logic?

And who is the source of the action? GUI? An Effect? Other?

**Comment by timdeschryver** [comment]
We have this on a recipe's page: [Additional state properties](https://ngrx.io/guide/entity/recipes/additional-state-properties).

Feel free to re-open this issue if it's missing something.

**Comment by NavruzbekNoraliev** [comment]
on(OrderActions.retActive, (state, { data }) => {
     return adapter.addAll(data, state)
  }),
is not updating my state 
i'm using ngrx8, ngrx-entity

**Comment by NavruzbekNoraliev** [comment]
![image](https://user-images.githubusercontent.com/44977644/64036447-a6fcc280-cb6c-11e9-9c3b-4f3623f2cb3b.png)

**Comment by roddc** [comment]
Hi @timdeschryver, my entity has a additional state called history which basically just a history of the original data, so I can use it to retrieve all old data. But I want to update the history when the original data got updated. How do I update the history state in  adapter.updateOne while updating the original data?
