### ISSUE TITLE
Bug: @ngrx/effects { dispatch: false } does not work when running unit tests

### ISSUE THREAD

**Issue by wilgert** [ngrx/platform#2080]
## Minimal reproduction of the bug/regression with instructions:
Because the bug only occurs when running unit tests we have created a GitHub repo instead of a StackBlitz.

https://github.com/NavaraBV/ngrx-dispatch-false-bug

## Expected behavior:
`{ dispatch: false }` stops the effect from emitting any actions when running unit tests using `provideMockActions`.

## Actual behavior:
When running unit tests `{ dispatch: false }` lets the Action go through. But when running the same code in production `{ dispatch: false }` works correctly.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
@angular/{core,common,compiler,platform-browser}: 8.2.2
@ngrx/{store,entity,effects}: 8.2.0
nodejs: 10.16.0
OS: OS X 10.14.6
Browser: Chrome 76.0.3809.100

## I would be willing to submit a PR to fix this issue

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
An effect will always emit a next value. 
The difference is that `dispatch: false`, does not dispatch the emitted action.

https://github.com/ngrx/platform/blob/master/modules/effects/src/effects_resolver.ts#L37

**Comment by wilgert** [comment]
I believe this is still a bug. I pushed an update to the reproduction repo. It now logs the value that was emitted in the subscriber. You can clearly see that what was emitted is in fact the Action.

<img width="437" alt="Screenshot 2019-08-25 at 08 15 54" src="https://user-images.githubusercontent.com/503813/63646293-9e416200-c710-11e9-9fa8-e043575dd0d7.png">
<img width="274" alt="Screenshot 2019-08-25 at 08 16 07" src="https://user-images.githubusercontent.com/503813/63646292-9da8cb80-c710-11e9-8c43-6c40ae613123.png">

**Comment by timdeschryver** [comment]
Yes, the effect will always emit a value (an action, or another object).
The difference is that `dispatch: false` does not dispatch the emitted value, whereas `dispatch: true` will dispatch the value (an action, or another object).

**Comment by timdeschryver** [comment]
To clarify, dispatch false does not change the effect's stream. It only prevents the emitted value to be dispatched.

**Comment by wilgert** [comment]
Ah I get it, so my test is wrong. How can I design a test that catches when
{ dispatch: false } is removed?

**Comment by gr4vitonn** [comment]
I ran into the same issue.

One of the devs put { dispatch: false } on an effect which is supposed to dispatch the returned action.
The unit test can't prevent that, since the effect stream is not changed by { dispatch: false }, so in this case we can also expect what the returned action is.

The mistake was catched during manual testing, but I thinkit would be good to be able to catch such a mistake at unit test level.
