### ISSUE TITLE
example app does not work on StackBlitz

### ISSUE THREAD

**Issue by walrus95** [ngrx/platform#2088]
## Minimal reproduction of the bug/regression with instructions:

I click the link under, "try the example-app on StackBlitz." I don't see the example app run on StackBlitz.

## Expected behavior:

The example app runs on StackBlitz after clicking the link.

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

**Comment by manklu** [comment]
Works for me.
