### ISSUE TITLE
ng update errors have no line numbers

### ISSUE THREAD

**Issue by pcurrivan** [ngrx/platform#2093]
Currently an error during automatic migration looks like this:

>     ** Executing migrations for package '@ngrx/store' **
>     Cannot read property 'filter' of undefined

Not very helpful.  It should be more like this error message from @angular/core:

>     ** Executing migrations for package '@angular/core' **
>             ------ Static Query Migration ------
>             With Angular version 8, developers need to
>             explicitly specify the timing of ViewChild and
>             ContentChild queries. Read more about this here:
>             https://v8.angular.io/guide/static-query-migration
>             
>             The template migration strategy uses the Angular compiler internally and therefore projects that no longer build successfully after the update cannot use the template migration strategy. Please ensure there are no AOT compilation errors.
>             
>             Could not setup migration strategy for "src/tsconfig.app.json". The following error has been reported:
>             
>             Error: error TS100: Error during template compile of 'AppModule'
>               Function expressions are not supported in decorators in 'ɵ0'
>                 'ɵ0' contains the error at src/app/app.module.ts(29,21)
>                   Consider changing the function expression into an exported function.
>             
>             
>             Migration can be rerun with: "ng update @angular/core --from 7 --to 8 --migrate-only"
>             
>             ------------------------------------------------
>

**Comment by timdeschryver** [comment]
It's a different error, the Angular error is an error on "your side" that you can fix to be able to run the migration correctly.

The `Cannot read property 'filter' of undefined` is a problem on "our side", and I believe I found the culprit.

Do you import the store somewhere in your project as follows 

```ts
import * as store from '@ngrx/store';
```

If so, you can fix this issue by import the store imports via named imports until we release a fix, for example:

```ts
import { StoreModule } from '@ngrx/store';
```
