### ISSUE TITLE
Error when using META_REDUCERS token to inject meta-reducers

### ISSUE THREAD

**Issue by cmdickson** [ngrx/platform#2094]
## Minimal reproduction of the bug/regression with instructions:
When attempting to inject meta reducers using the `META_REDUCERS` injection token as described here:
https://ngrx.io/guide/store/recipes/injecting#injecting-meta-reducers

The application fails to initialize and the following error appears in the console:
```
Error: fn is not a function
```

Based on seed: https://stackblitz.com/edit/ngrx-seed-ptkzce
Minimal reproduction: https://stackblitz.com/edit/angular-bhv4yc

## Expected behavior:
Application loads without errors and the meta reducers defined by factory for the `META_REDUCERS` injection token are used by the application store.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
Angular: ^8.0.0
NgRx: ^8.0.0
Browser: Chrome 75
OS: MacOS 10.14.1

**Comment by timdeschryver** [comment]
The docs are a bit wrong here, with the change that it's become a `multi` token,
we expect the factory function to return a reducer, see https://stackblitz.com/edit/angular-ifqdmm?file=src/app/app.module.ts
