### ISSUE TITLE
ngrx/data Hot to add custom selector?

### ISSUE THREAD

**Issue by de-juve** [ngrx/platform#2097]
I have additional field "selectedId" in entityMetadata->additionalCollectionState
How to add selector for get selectedEntity? Like 
`const selectEntity = createSelector(selectEntities, selectSelectedId, (entities, id) => entities && id ? entities[id] : null)`?

**Comment by timdeschryver** [comment]
That seems good to me, have you tried it?

Support questions should be asked on [stackoverflow (with a ngrx tag)](https://stackoverflow.com/questions/tagged/ngrx) or the [gitter channel](https://gitter.im/ngrx/platform).
