### ISSUE TITLE
unused count parameter of selectLastStateTransitions

### ISSUE THREAD

**Issue by walrus95** [ngrx/platform#2102]
## Other information:

I visit the docs located at https://ngrx.io/guide/store/selectors

Under "Advanced Example: Select the last {n} state transitions" there is a function called selectLastStateTransitions in the select-last-state-transition.ts file.

The count parameter is not being used. It looks like the concept of the number three is just hard-coded into the function. 

The same problem is in the linked [StackBlitz project ](https://stackblitz.com/edit/angular-ngrx-effects-1rj88y?file=app%2Fstore%2Ffoo.ts)

## I would be willing to submit a PR for the docs :heart:

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

https://youtu.be/GW7uBlzrt2w

**Comment by mj-meyer** [comment]
Can I grab this? Haven't contributed to open source yet... so would love to break the ice. Will submit a PR tomorrow morning if that's alright?

**Comment by mj-meyer** [comment]
I'm not sure how the stackblitz example is updated?

**Comment by timdeschryver** [comment]
The stackblitz is created by the contributor who provided the docs.
To make it maintainable we should move the code to the [examples](https://github.com/ngrx/platform/tree/master/projects/ngrx.io/content/examples), but I think we can just remove the link to the stackblitz for now.

**Comment by manklu** [comment]
@mj-meyer You can fork the stackblitz sample and then modify it

**Comment by mj-meyer** [comment]
@timdeschryver so I didn't remove the stackblitz example on my PR. Should I remove it before we continue?

**Comment by timdeschryver** [comment]
See my comment on the PR.
