### ISSUE TITLE
Detected unserializable action at "payload.routerState.root.paramMap"

### ISSUE THREAD

**Issue by bjornharvold** [ngrx/platform#2113]
## Reproduction
[ngrx-seed.zip](https://github.com/ngrx/platform/files/3593356/ngrx-seed.zip)
StackBlitz didn't want to fork for me so attaching a zip ball

Very simple way to replicate error:
1. Add ngrx-router to AppModule
2. Add runtimeChecks to StoreModule
```
runtimeChecks: {
        strictStateImmutability: true,
        strictActionImmutability: true,
        strictStateSerializability: true,
        strictActionSerializability: true
      }
```
Error displays in console

## Expected behavior:
No errors

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
NGRX: 8.3.0
Angular 8.2.5

Cheers on a great framework!

**Comment by brandonroberts** [comment]
See about using the `RouterState.Minimal` option if you don't need the extra properties https://ngrx.io/guide/router-store/configuration#routerstateminimal
