### ISSUE TITLE
New warning about unprovided feature state wrecks unit test output

### ISSUE THREAD

**Issue by Halt001** [ngrx/platform#2116]
We have unit tests where we use the state without mocking. With the new warning about undefined feature state, that is given while it shouldn't in case of the router state, our unit test are now littered with this warning. Also it shows up in the debugger console when we run the app.

Warning:  

> The feature name "router" does not exist in the state, therefore createFeatureSelector cannot access it.  Be sure it is imported in a loaded module using StoreModule.forRoot('router', ...) or StoreModule.forFeature('router', ...).  If the default state is intended to be undefined, as is the case with router state, this development-only warning message can be ignored.

Also see the discussion here: [Issue 1897](https://github.com/ngrx/platform/issues/1897)

![image](https://user-images.githubusercontent.com/9273697/64756488-72571680-d52f-11e9-9cc9-982e835f7cf3.png)

## Expected behavior:
I think it is bad practice to give warnings that should be ignored in some cases. This leads to warning/error fatigue. Also unit tests that have hundreds or even thousands of warnings quickly lose their usefulness.

So please find a way to not warn when there is nothing to warn about, like in the case of the router state. Or add the ability to suppress the warnings for a user provided key, or even remove this warning completely as it does seem to do more harm than good.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
NgRx 8.3
Ng 8.2.5

**Comment by jtcrowson** [comment]
Could you push up a basic code sample where this is happening?  I can try to work around this, possibly by excluding tests, possibly by excluding router state.

**Comment by Halt001** [comment]
Working on it. May take some time as I can't share our code and it isn't obvious to me when the warning is triggered.

**Comment by jtcrowson** [comment]
I appreciate your help, thanks!

**Comment by Halt001** [comment]
Sorry for the delay. I've created a repo with an app that generates the warning multiple times after running the unit tests with `npm test`.

Also when running the app with `npm start` you can observe the warning in the browsers debugger console.

[The repo](https://github.com/Halt001/ngrx-warning)

**Comment by timdeschryver** [comment]
I haven't taken an in-depth but it I believe you should also import the router and router-store. In your component you're using a router selector, but no (router) state is provided.

**Comment by Halt001** [comment]
I've added actual routing to the app. It now doesn't display the warning in the browser debugger console anymore (but our production app does) but the example still shows the warnings in the unit tests. Hope this may save you some work.

**Comment by meanstack-perficient** [comment]
actually this error produces the undefined message stated above
yes I am receiving the type error

and takes out the ngrx store itself

so this breaks ngrx feature state (just a spinner) in my case

i remodeled my feature state and selectors... blue in the face

cant shake it

can someone escalate this, reopen or provide workaround

/vendor.js:197218 The feature name "feature" does not exist in the state, therefore createFeatureSelector cannot access it. Be sure it is imported in a loaded module using StoreModule.forRoot('feature', ...) or StoreModule.forFeature('feature', ...). If the default state is intended to be undefined, as is the case with router state, this development-only warning message can be ignored.

ERROR TypeError: Cannot read property 'spinner' of undefined

**Comment by meanstack-perficient** [comment]
feature-state.ts
```
export const FEATURE_PROPERTY_KEY = 'feature'

export const reducers: ActionReducerMap<FeatureState, any> = {
    spinner: spinnerReducer,
    user: userReducer,
    users: usersReducer,
}

export interface FeatureState {
    spinner: SpinnerState
    user: UserState
    users: UsersState
}

export interface FeatureStateContainer extends RootState {
    feature: FeatureState
}

```
feature-selector.ts
```
export const selectFeatureState = createFeatureSelector<FeatureStateContainer, FeatureState>(
    FEATURE_PROPERTY_KEY
)

export const selectFeature = createSelector(
    selectFeatureState,
    (state: FeatureState) => state
)
```

feature-module.ts
```
        // ngrx
        StoreModule.forFeature('feature', reducers),
        EffectsModule.forFeature([
            SpinnerEffects,
            UserEffects,
            UsersEffects,
            SettingsEffects
        ]),
```

any clarification/assistance for workaround appreciated

**Comment by meanstack-perficient** [comment]
Im not seeing any pattern enforcement in loading modules and scenarios for CORE or FEATURE or CORE/FEATURE modules... as they pertain to AppModule

then factor in ionic tabs which pushes things out another dimenison

and we have opened the door to race conditions like the wild wild west

My boot spinner hangs more than shows/hides in my AppComponent due to refactoring

im seeing alot of race conditions

**Comment by manklu** [comment]
@meanstack-perficient

Your Problem has nothing to do with this ticket. This ticket is about suppressing the warning when it is known that the state is not yet initialized.

> any clarification/assistance for workaround appreciated

Initialize your feature state.

> /vendor.js:197218 The feature name "feature" does not exist in the state, therefore createFeatureSelector cannot access it. Be sure it is imported in a loaded module using StoreModule.forRoot('feature', ...) or StoreModule.forFeature('feature', ...). If the default state is intended to be undefined, as is the case with router state, this development-only warning message can be ignored.

Not initialized when creating the feature selector.

> ERROR TypeError: Cannot read property 'spinner' of undefined

Still not initialized when used for the first time.

**Comment by jtcrowson** [comment]
@timdeschryver what do we want to do here?  The point of this was to save headaches, not create them.  Only approach I've found was to string match on the state key for router.

**Comment by meanstack-perficient** [comment]
well the error is telling me something is wrong...better than none
Im pushing this framework to the max

for instance if you forget to add an index route ' ' in one of your router modules you will get this

`typeerror cannot read property ‘split’ of undefined at defaultUrlMatcher `

which doent tell much about what to do or where to go except guess that url/router might be the cause... that one held me up three days deep into router modules

so if this ngrx error is omitted or stifled what would I see then?

**Comment by timdeschryver** [comment]
@jtcrowson I have mixed feelings here, the same you are expressing.

I don't see any solution neither, besides doing a string match.

I'd like to know if it's only the router store that's causing these warnings.
We haven't upgraded to 8.3.0 yet at work, but I'll try to push this to next week - just to see the behavior here.

**Comment by meanstack-perficient** [comment]
From my perspective

My router store is functioning and running fine
and
this message it has to do with any store in general

and I eluded to race conditions associated with the way developers are cobbling together their lazy loaded and eager loaded modules as they are setting up at bootstrap according to their route tree

I am ironing out my router tree now

in some cases ngrx is ok and gets past the anomalous setup of modules beit eager/lazy
and the message appears

in other cases the message appears identifying the anomalous setup of modules beit eager/lazy

and the reference error occurs

**Comment by meanstack-perficient** [comment]
try lazyloading everything in your appmodule and that will flush it out
with a few ngrx stores
core/feature/shared/biz

**Comment by timdeschryver** [comment]
Thanks for the info @meanstack-perficient

**Comment by aquark** [comment]
We're having a similar issue with many user-defined feature modules where the state is intentionally `undefined` until some event changes the state. We can work around the issue by initializing the state to `null` instead of `undefined`, but would rather not. I don't suppose there's a way to use `hasOwnProperty` to check if a key is present in the store, whether or not its value is `undefined`?

**Comment by timdeschryver** [comment]
I like that idea @aquark 👍!
From what I can think atm, that would fix these problems and it will also provide a helpful message.
Thoughts @jtcrowson ?

**Comment by Gunyon** [comment]
try to select the router slice of state with a simple function 

`export const selectRouter = (state: State) => state.router;`

because createFeatureSelector, hence the name, is used for selecting a slice of state added
in a FEATURE module 

`StoreModule.forFeature('feature1', reducers)`

in this case you should use createFeatureSelector

```
export const selectFeature1 = createFeatureSelector<
  State, Feature1State<any>
>('feature1');
```
