### ISSUE TITLE
How to use isDevMode() core function for metaReducers

### ISSUE THREAD

**Issue by harishajdarevic** [ngrx/platform#2117]
Hello,

This is my app.module.ts

```
@NgModule({
  imports: [
    BrowserModule,
    .....
    StoreModule.forRoot(reducers, { metaReducers }), // error is here
    ......
```

And for metaReducer I've part of code:

```
import {isDevMode} from '@angular/core';

export const metaReducer: MetaReducer<IAppState>[] = isDevMode()
  ? [storeFreeze]
  : [];
```

During AOT build I'm getting the following error:

>  Error during template compile of 'AppModule'
>   Function calls are not supported in decorators but 'isDevMode' was called.

I tried to wrap isDevMode() into another function etc but nothing works. 

I don't want to use environment.production flag from environment files, because I want to be able dynamically to change this and to have hardcoded in an environment file and that's why I'm using isDevMode().

Thanks

**Comment by Edouardbozon** [comment]
Something like this should work: 

```ts
export function getMetaReducers(): MetaReducer<fromRoot.State>[] {
  return isDevMode() ? [storeFreeze] : [];
}
 
@NgModule({
  providers: [
    {
      provide: META_REDUCERS,
      useFactory: getMetaReducers,
      multi: true,
    },
  ],
})
export class AppModule {}
```

However `ngrx-store-freeze` package is deprecated in favor of [runtime checks](https://ngrx.io/guide/store/configuration/runtime-checks) that already do this logic for you.

**Comment by timdeschryver** [comment]
See @Edouardbozon 's answer.
