### ISSUE TITLE
Access createAction props type

### ISSUE THREAD

**Issue by WojciechSlyp** [ngrx/platform#2118]
Hi, 

I recently migrated from using class based Actions to `createAction` approach.
I use facade pattern and to reduce imports and overall complexity, I use the following a lot:
```
class FacadeService {
  someAction(payload: Actions.SomeAction['payload']) {
    this.store.dispatch(new Actions.SomeAction['payload']);
  }
}
```

How would I go about accessing payload (or rather `props`) type without declaring additional interfaces / types etc from actions created with `createAction`?

**Comment by timdeschryver** [comment]
We see this is an anti-pattern, we encourage [good action hygiene](https://www.youtube.com/watch?v=JmnsEvoy-gY).

Therefor we encourage to use a generic dispatch in the facade.

**Comment by manklu** [comment]
@WojciechSlyp If you really need the payload type of an action, you can use the following:

```typescript
import { createAction, props, ActionCreator } from '@ngrx/store';

export const login = createAction(
  '[Login Page] Login',
  props<{ username: string; password: string }>()
);

type ExtractActionPayloadType<Type> = (Type extends ActionCreator<any, infer V> ? V : never) extends (p: infer T) => infer T & any ? T : never

type actionPayload = ExtractActionPayloadType<typeof login>
```
http://www.typescriptlang.org/docs/handbook/advanced-types.html

**Comment by WojciechSlyp** [comment]
> We see this is an anti-pattern, we encourage [good action hygiene](https://www.youtube.com/watch?v=JmnsEvoy-gY).
> 
> Therefor we encourage to use a generic dispatch in the facade.

You're actually very right. Thanks for this!

**Comment by DenisSlaschilinDevPro** [comment]
@manklu I see you are good in TypeScript typings. Maybe you can help with the related question:
https://stackoverflow.com/questions/58028504/correct-type-declaration-for-method-with-ngrx-actioncreator-as-parameter
