### ISSUE TITLE
this.actions$.ofType(login_types_1.LOGIN_USER) throws undefined is not a constructor in unit tests

### ISSUE THREAD

**Issue by MikeSaprykin** [ngrx/platform#212]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## What is the current behavior?

Tried to write unit tests on basic Effects class, using the latest version of @ngrx/effects using [this tutorial](https://github.com/ngrx/platform/blob/master/docs/effects/testing.md) and faced issue: 

`TypeError: undefined is not a constructor (evaluating 'this.actions$
                    .ofType(login_types_1.LOGIN_USER)')` 

Here is a repo with reproduced issue: https://github.com/MikeSaprykin/ngrx-effects-ofType-tests-bug

> Sidenote: this Effects class is used in feature module.

## Expected behavior:

All tests pass, as described in the tutorial.

## Minimal reproduction of the problem with instructions:

Effects File
```typescript
@Injectable()
export class LoginEffects {

  constructor(public actions$: Actions) {}

  @Effect()
  logInAction$: Observable<ActionWithPayload<any>> = this.actions$
    .ofType(LOGIN_USER)
    .map(action => action);
}
```

Tests file

```typescript
describe("My Effects", () => {
  let effects: LoginEffects;
  let actions: any;

  const TEST_LOGIN_ACTION = { type: "LOGIN_USER" };

    beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [
        RouterTestingModule
      ],
      providers: [
        LoginEffects,
        provideMockActions(() => actions),
      ],
    });

    effects = TestBed.get(LoginEffects);
  });


  it("should work", () => {
    actions = hot("--a-", { a: TEST_LOGIN_ACTION });

    const expected = cold("--b", TEST_LOGIN_ACTION);

    expect(effects.logInAction$).toBeObservable(expected);
  });

  it("should work also", () => {
    actions = new ReplaySubject(1);

    actions.next(TEST_LOGIN_ACTION);

    effects.logInAction$.subscribe(result => {
      expect(result).toEqual(TEST_LOGIN_ACTION);
    });
  });
});
```

Login Module
```typescript
@NgModule({
  imports: [
    CommonModule,
    routing,
    StoreModule.forFeature('login', reducer),
    EffectsModule.forFeature([LoginEffects]),
  ],
  declarations: [
    LoginComponent,
    LoginFormComponent
  ],
})
export class LoginModule { }
```
## Version of affected browser(s),operating system(s), npm, node and ngrx:
angular/cli: 1.2.4
npm: 5.3.0
node: 8.0.0
os: darwin x64

ngrx/effects: ^4.0.1,
ngrx/router-store: ^4.0.0,
ngrx/store-devtools: ^4.0.0,

**Comment by brandonroberts** [comment]
See https://github.com/ngrx/platform/issues/173
