### ISSUE TITLE
Conditional import Store dev tools for the same envioronment which can build with AOT true or false

### ISSUE THREAD

**Issue by harishajdarevic** [ngrx/platform#2122]
I've already different build environments for my angular application.

What I'm looking for is how to implement conditional import of StoreDevTools based on that are we in development mode or not.

The important thing is to notice that for the same environment we want to able to serve it in development mode and have StoreDevTools included in that case and on the other hand to be able to build/deploy the app for the same environment and to be in production mode.

How we are achieving that?

Very simple using following commands:

Staring application for **configuration:** test1, **aot:**, false, **prod:**, false...
> ng serve --port 3000 --configuration=test1 --aot=false --prod=false --optimization=false --progress=false

And in an application I'm able to check are we in dev mode or not simply calling isDevMode() angular/@core functionality. 

When I want to deploy the application for the same config I made build using:
**configuration:** test1, **aot:**, true, **prod:**, true...
> ng build --configuration=test1 --aot=true --prod=true --optimization=true 

The main problem is because I wasn't able to use isDevMode() method in app.module.ts and do like this:

> isDevMode() ? StoreDevtoolsModule.instrument({ maxAge: 50 }) : [],

**Comment by timdeschryver** [comment]
AFAIK this isn't possible due to the fact how Angular compiles.
The easiest way to accomplish this is to add a [target-specific file replacement](https://angular.io/guide/build#configure-target-specific-file-replacements).

See https://ngrx.io/guide/store-devtools/recipes/exclude for an example.

**Comment by harishajdarevic** [comment]
@timdeschryver Unfortunately it is not possible to achieve following that link. 

As I said above I want to be able to use one environment file for both production/development and determine in which mode are we by calling isDevMode().

So basically if I do it by following the link that you pasted I will still need to have production property into environment file which is not what I want.

**Comment by timdeschryver** [comment]
Then I think the only way would be to override the `REDUX_DEVTOOLS_EXTENSION` token - https://github.com/ngrx/platform/blob/master/modules/store-devtools/src/instrument.ts#L72 but I'm not sure if I can recommend it ...
