### ISSUE TITLE
@ngrx/data : documenting selectors

### ISSUE THREAD

**Issue by peterbsmith2** [ngrx/platform#2124]
###  Other information:
My Scenario:  
  
Existing large codebase with multiple entities  

Currently combining multiple pieces of state with selectors like:
```ts
export const selectedCatsWithOwners = createSelector(
  selectAllCats,
  selectOwnersEntities,
  (cats, ownerEntities) => cats.map(c => ({
    ...c,
    owner: ownerEntities[c.owner]
  }))
);
```

I'd like to use @ngrx/data with Owners and keep everything else the same.  That means replacing the existing `selectOwnersEntities` selector (provided by @ngrx/entity) with similar from @ngrx/data.

So I found the elegant solution provided by @ngrx/data:

```ts
export const ownerSelectors = new EntitySelectorsFactory().create<Owner>('Owner');

export const selectedCatsWithOwners = createSelector(
  selectAllCats,
  ownerSelectors.selectEntities,
  (cats, ownerEntities) => cats.map(c => ({
    ...c,
    owner: ownerEntities[c.owner]
  }))
);
```

That said, `new EntitySelectorsFactory().create<Owner>('Owner');` is not documented anywhere. And I think it should be.

## I would be willing to submit a PR for the docs :heart:

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by SerkanSipahi** [comment]
Thank you for your contribution. Im also working to improve the documentation of ngrx/data. If you want we can work together on this branch https://github.com/ngrx/platform/pull/2086

I guess it is easer for @wardbell to code-review everything at once.
