### ISSUE TITLE
@ngrx/data: documenting customizing reducers

### ISSUE THREAD

**Issue by peterbsmith2** [ngrx/platform#2126]
## Other information:
I have am trying to replace @ngrx/entity with @ngrx/data for a `Owner` entity. On @ngrx/data I need to include a `selectedId` property on state to keep reference to which Id of that entity is selected in the app. My `entity-metadata.ts` looks like:  

```ts
const entityMetadata: EntityMetadataMap = {
  Owner: {
    additionalCollectionState: {
      selectedId: null
    }
  }
};
```
The [ngrx/data docs on Entity Reducer architecture](https://ngrx.io/guide/data/entity-reducer) are inaccurate. There are multiple references to `EntityReducerFactory` in the docs, which does not exist in the API.  
  
I read through the code to understand more. There are `EntityCacheReducerFactory` and `EntityCollectionReducerFactory`. I have the following notes:

- [line 8](https://github.com/ngrx/platform/blame/4b883af778617052f741fb0f9ede6a3a2b72450f/projects/ngrx.io/content/guide/data/entity-reducer.md#L8) appears to reference `EntityCacheReducerFactory`.

- [line 38](https://github.com/ngrx/platform/blame/4b883af778617052f741fb0f9ede6a3a2b72450f/projects/ngrx.io/content/guide/data/entity-reducer.md#L38) may reference `EntityCollectionReducerFactory` 

- [line 48](https://github.com/ngrx/platform/blame/4b883af778617052f741fb0f9ede6a3a2b72450f/projects/ngrx.io/content/guide/data/entity-reducer.md#L48) and line [line 51](https://github.com/ngrx/platform/blame/4b883af778617052f741fb0f9ede6a3a2b72450f/projects/ngrx.io/content/guide/data/entity-reducer.md#L51) appear to reference `EntityCollectionReducerRegistry`
 
- [line 94](https://github.com/ngrx/platform/blame/4b883af778617052f741fb0f9ede6a3a2b72450f/projects/ngrx.io/content/guide/data/entity-reducer.md#L94) and [line 112](https://github.com/ngrx/platform/blame/4b883af778617052f741fb0f9ede6a3a2b72450f/projects/ngrx.io/content/guide/data/entity-reducer.md#L112) appear to reference `EntityCacheReducerFactory`.

- [line 250](https://github.com/ngrx/platform/blame/4b883af778617052f741fb0f9ede6a3a2b72450f/projects/ngrx.io/content/guide/data/entity-reducer.md#L112) appears to reference `EntityCollectionReducerRegistry`

## I would be willing to submit a PR for the docs :heart:

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by peterbsmith2** [comment]
I opened PR #2127 to make the appropriate updates.

**Comment by SerkanSipahi** [comment]
Thank you for your contribution. Im also working to improve the documentation of ngrx/data. If you want we can work together on this branch https://github.com/ngrx/platform/pull/2086

I guess it is easer for @wardbell to code-review everything at once.

**Comment by danielhdz56** [comment]
@peterbsmith2 or @SerkanSipahi I can't seem to follow the documentation and was hoping you could shed some light on the following:

how to modify a reducer so that when passing a key to `getByKey` the value for selectedId gets updated. 

```
const entityMetadata: EntityMetadataMap = {
  Owner: {
    additionalCollectionState: {
      selectedId: null
    }
  }
};

const pluralNames = {  };


// do i have to add entityCacheMetaReducers or entityCollectionMetaReducers? (if so, how do i do that)
export const entityConfig: EntityDataModuleConfig = {
  entityMetadata,
  pluralNames,
};


```

**Comment by wardbell** [comment]
This should be more clearly documented.

Before I tell you how to do it, I'd like to suggest that you keep this information outside of NgRx Data. At least that's what I do. I fallback on regular NgRx. My apps have a mix of NgRx Data for entity data management and regular NgRx for session data (data that goes away when the app closes) such as the currently selected customer.  I have a "Session" model for that kind of thing and I write it in vanilla NgRx.

BUT, let's suppose you wanted to keep the `selectedId` in the entity collection AND you wanted to maintain it as part of one of the existing actions such as `getByKey`.

Thanks to PR #2127 the instructions have been corrected!
