### ISSUE TITLE
RFC: Migrations support for updating class type actions to use 'createAction' syntax

### ISSUE THREAD

**Issue by evgenyfedorenko** [ngrx/platform#2137]
I've updated the ngrx to v8 finally and it was a lot of monotonous work. I wonder if adding support for automatic actions syntax upgrade via schematics would be something worth pursuing - given that is it actually feasible. Reducers and effect I feel like would be even harder to update.

Thoughts?

## If accepted, I would be willing to submit a PR for this feature

[X] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
I was thinking about it, but from what I could see at the time it really wasn't straightforward to do. You can see a lot of different flavors of actions in the wild.
To be able to fully make use of reducers (with type-safety) you more or less need the actions migrated first.
I'm open for suggestions tho.

**Comment by evgenyfedorenko** [comment]
I was thinking to add this functionality as a part of 'ng update' command. What flavors of actions you are talking about except those which are created this way?

export const SOME_ACTION_TYPE = 'SOME_ACTION_TYPE';
export class SomeAction implements Action {
  readonly type = SOME_ACTION_TYPE;
}
export type All = SomeAction;

**Comment by timdeschryver** [comment]
That's an easy action but it becomes tricky if you add a payload, constructor, some logic, enums, static readonly types, etc.

**Comment by brandonroberts** [comment]
I think if we want to achieve this, it should only support certain scenarios. Using creators should be an addition, not a refactoring task for your existing codebase. I would suggest supporting the idiomatic approach of converting "standard usage " of enums, action classes, and unions. The constructor would be ported over as is to props, enclosed in a `payload` object if that's what previously existed.

If developers have rolled their own flavor of the approach, they will have to migrate by hand if they want to.

**Comment by brandonroberts** [comment]
This would not be part of `ng update`, but a migration you can generate.

**Comment by evgenyfedorenko** [comment]
@brandonroberts 

> Using creators should be an addition, not a refactoring task for your existing codebase.

Here you mean migrations script should not refactor all actions to new use new creator syntax? Sorry, not clear what would be the purpose of this effort then.
> This would not be part of ng update, but a migration you can generate.

As far as I understood migrations are run as a part of 'ng update' command. Not true? I was planning to create another migration and that would be executed via 'ng update' (based on my prior schematics debugging experience)

**Comment by brandonroberts** [comment]
I'm saying the new syntax is opt-in. You don't _have_ to refactor your entire codebase if you want to use the new syntax.

It's not part of `ng update` because it's not a breaking change that requires you to change your existing code.

**Comment by evgenyfedorenko** [comment]
ok I see, what schematics command would be used then to run this refactoring if they decide they need it?

**Comment by evgenyfedorenko** [comment]
The reason I assumed migrations are run as a part of ng update is b/c of this
```
  "ng-update": {
    "packageGroup": "NG_UPDATE_PACKAGE_GROUP",
    "migrations": "NG_UPDATE_MIGRATIONS"
  },
```

**Comment by brandonroberts** [comment]
It would something like `ng g create-action-migration` and `ng g create-reducer-migration` if we're doing it in a multi-stage approach.

**Comment by timdeschryver** [comment]
I believe it would be something similar to https://github.com/ngrx/platform/pull/2136

**Comment by evgenyfedorenko** [comment]
thanks @brandonroberts and @timdeschryver. createEffect is already done, great!
Will take a look.

**Comment by evgenyfedorenko** [comment]
@timdeschryver I've messed with your 'create-effect-migration' quite a bit and wanted to start working on createAction one. I am not familiar with the way I can run the built schematics locally. For example once I add new schematics how do I test it in ngrx context ? Thanks!

**Comment by timdeschryver** [comment]
I always start with the unit tests, these will cover 90% of all the cases.
After this step you can build the repo with `npm run build` (this requires bazel). The build output of the schematics will be found in `.\dist\bin\modules\schematics\npm_package`.
Now you should be able to install the package with `npm install path/to/npm_package` and run the schematics local.

**Comment by brandonroberts** [comment]
Going to close this for now as it will be the default in version 9
