### ISSUE TITLE
Feature Request: Something similar to a sNgRx Tour of Heroes step by step tutorial.

### ISSUE THREAD

**Issue by ChuckIrvine** [ngrx/platform#2138]
I am having trouble understanding NgRx sufficiently to convert my existing Angular app to use NgRx. I've looked around for sample apps and tutorials but so far none have been effective in getting me over the hump. What would really be helpful is something similar to the official Angular Tour of Heroes tutorial that uses NgRx. I feel confident that lots of folks would really like to see something like this as part of the NgRx docs set.

Thanks!

**Comment by brandonroberts** [comment]
Thanks for the suggestion Chuck! We are looking at additional ways to make the on-boarding process easier for new developers.

**Comment by ChuckIrvine** [comment]
I have a fairly large Angular app. (www.izedor.com). Managing state has become a living hell, so I'm sure I'll benefit from NgRx. Finding a good example that is well done and up-to-date has proved to be impossible. I'm struggling through it and making some progress. It bet one of you NgRx guru's could put together an NgRx Tour of Heroes in no time. (https://angular.io/tutorial). Thanks

**Comment by ChuckIrvine** [comment]
I thought I would refine my suggestion for future reference. 

The suggestion is to clone the finished tutorial referenced at (https://angular.io/tutorial). Then modify it to use NgRx. This would be a good tutorial since lots of Angular developers are likely to be familiar with the Tour of Heroes tutorial.

**Comment by brandonroberts** [comment]
If you want to see a version of Angular tutorial using NgRx, check out https://github.com/nrwl/ngrx-workshop-app

**Comment by ChuckIrvine** [comment]
Well, it turns out that lots of folks have converted the Tour of Heroes tutorial to use NgRx. This one is the best that I have found: https://github.com/webmasterdevlin/heroes-ngrx. The heroes component uses NgRx 7 and the villains uses NgRx 8.
