### ISSUE TITLE
Schematics: Generate selectors file as part of feature schematic

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#2140]
It's common practice to have a separate `{feature-name}.selectors.ts` file alongside your actions, reducers, etc. The `feature` schematic would add a flag to generate this file and it's tests in addition to the current set, and eventually become the default.

We could optionally do this for the `entity` schematic also.

At a minimum, the selectors file would:

- Import the usual `createSelector` functions
- Import the reducer exports
- Include a selector that uses `createFeatureSelector` to select that feature key

**Comment by timdeschryver** [comment]
If no-one is currently working on this or is planning to work on this feature, I could grab this up.
