### ISSUE TITLE
Selector keeps calling not stop.

### ISSUE THREAD

**Issue by hmendezm** [ngrx/platform#2141]
## Minimal reproduction of the bug/regression with instructions:

The selector have logic that returns a value that is not the state value. The state value is using for reproducing an extra value. In this case, I cast the object to a specific class.

## Expected behavior:
I have the following selector
```
export const selectMapBounds = createSelector(
  getConfigState,
  config => {
  // Do some logic
    const mapBounds = value from logic;
    return mapBounds; 


  } 
);

```
The selector is in looping and never finished so the app crash. However, if I have  the selector below the app calls once the selector
```
export const selectMapBounds = createSelector(
  getConfigState,
  config => {
    return config .mapBounds; 
  } 
);

```

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
    "@ngrx/effects": "^8.3.0",
    "@ngrx/entity": "^8.3.0",
    "@ngrx/store": "^8.3.0",
     "@angular/core": "^7.2.15",
## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
Support issues should be asked in the [gitter channel](https://gitter.im/ngrx/platform).
