### ISSUE TITLE
SSE (SERVER SENT EVENTS) support

### ISSUE THREAD

**Issue by ceyhunn** [ngrx/platform#2147]
## Describe any alternatives/workarounds you're currently using
I can't find any implemention for sse with ngrx. Please add this feature.
## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
This is something NgRx that isn't baked into the platform.

But you can leverage `@ngrx/effects` to listen to the websocket and dispatch actions to the NgRx Store.

You can take a look at an example [here](https://github.com/avatsaev/angular-contacts-app-example/blob/master/src/app/views/contacts/store/contacts-effects.ts#L91-L104).
