### ISSUE TITLE
[@ngrx/data] Consider Making PersistenceResultHandler Return an Observable<Action>

### ISSUE THREAD

**Issue by mwootendev** [ngrx/platform#2152]
At present, the current implementation assumes that there will be a single response from a data service and it will result in a single Action. I would like to be able to support situations where more than one response can be returned (such as from a WebSocket connection or a polling HTTP service) and more than one Action may result from the response. For instance, when loading from Firebase, the query response can contain ADD, UPDATE, and DELETE operations. 

The `PersistenceResultHandler` interface's `handleSuccess()` method is responsible for converting the EntityAction into a function that emits another Action based on the data. Ideally, I would like this to result in multiple Actions as an Observable. 

Would it be possible to change the signature from 

```javascript
 abstract handleSuccess(originalAction: EntityAction): (data: any) => Action;
``` 

to 

```javascript
 abstract handleSuccess(originalAction: EntityAction): (data: any) => Observable<Action>;
```
or
```javascript
 abstract handleSuccess(originalAction: EntityAction): (data: any) => Action | Observable<Action>; 
```
## Describe any alternatives/workarounds you're currently using

I have not found a suitable alternative. It may be possible with a custom Effect, but the current @ngrx/data documentation is unclean on how to achieve this. 

## Other information:

This would also necessitate a change to `EntityEffects.persist` to change the `map` operation to a `mergeMap`. 

I have a working local copy, but I am having issues with adding a new test case for the scenario where multiple actions are emitted.

## If accepted, I would be willing to submit a PR for this feature

[X] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by JiaLiPassion** [comment]
@mwootendev, I am not sure I understand your motivation to change the `persistentResultHandler` to return `Observable`, could you show some sample code to explain it ? Thanks!

**Comment by mwootendev** [comment]
The specific case I am looking at is mapping @angular/fire FireStore stateChanges to a LOAD operation. The call to the FireStore will return an array of `DocumentChangeAction` results. 

```javascript
export interface DocumentChangeAction<T> {
    type: "added" | "removed" | "modified";
    payload: DocumentChange<T>;
}
```

That single data service response can be mapped to individual `EntityOp.ADD_ONE`, `EntityOp.REMOVE_ONE`, and `EntityOp.UPDATE_ONE` operations. The issue is that PerisistenceResultHandler must map the entire array to a single Action type.

**Comment by timdeschryver** [comment]
So it the change wouldn't be to allow an `Observable<Action>` but an array of actions as in `Action[]` ?

**Comment by mwootendev** [comment]
@timdeschryver I tend to think of the approaches as pretty much equal. I had imagined the `Action` -> `Observable<Action>` solution because then `EntityEffects` could just change the RXJS `map` operation to a `mergeMap`.

**Comment by brandonroberts** [comment]
We will revisit this at some point. Closing for now
