### ISSUE TITLE
router-store: firstchild of undefined with custom serializer

### ISSUE THREAD

**Issue by sheikalthaf** [ngrx/platform#2153]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
![image](https://user-images.githubusercontent.com/22526247/66332471-7883bb80-e952-11e9-9c56-e17867be10d2.png)

above is my route state with custom serializer (same as described in the doc).

![image](https://user-images.githubusercontent.com/22526247/66332599-b7b20c80-e952-11e9-927b-6be67c1c36cb.png)

when i try to use `selectRouteData` it throws error 

https://github.com/ngrx/platform/blob/ecf7a26dba588429cfd185ae77237df4a790eeb6/modules/router-store/src/router_selectors.ts#L15

this is due to selectRouterState will get the object in the state

https://github.com/ngrx/platform/blob/ecf7a26dba588429cfd185ae77237df4a790eeb6/modules/router-store/src/router_selectors.ts#L19

so the `router` variable in the above line will be undefined so the while loop breaks

## Expected behavior:
If anything I'm missing please correct me. Any solution please

## Version of affected browser(s),operating system(s), npm, node and ngrx:
ngrx: 8.2.0

**Comment by timdeschryver** [comment]
The router selectors only work for the built-in serializer as mentioned in the [docs](https://ngrx.io/guide/router-store/selectors).

**Comment by sheikalthaf** [comment]
@timdeschryver thanks for clarification
