### ISSUE TITLE
@ngrx/entity adaptor created selectors cause internal exception in a lazy loaded module

### ISSUE THREAD

**Issue by owen26** [ngrx/platform#2156]
## Minimal reproduction of the bug/regression with instructions:

https://stackblitz.com/edit/angular-nrqkr4

Visit `LazyB` before `LazyA` causes the exception.

I'm aware it's a bad practice to have lazy-loaded module access states in another lazy-loaded module. But the library shouldn't stop people using bad practice by throwing an internal error on it with no choice to do a workaround.

## Expected behavior:

If lazy module is not initialised, those selectors should perform a null/undefined check against the state.

Additionally, perhaps show a `console.warn()` let people know a possible bad practice.

In fact `@ngrx/store` (not `@ngrx/entity`) does throw a warning message like the following:

```
The feature name "foobar" does not exist in the state, therefore createFeatureSelector cannot access it.
```

But `@ngrx/entity` causes a fatal error.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

Angular 8.2.9
Ngrx 8.3.0

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

**Comment by zakhenry** [comment]
👍, but I'm not actually convinced it is bad practice. A lazy module might actually want to access data from another lazy module _if it has been loaded_.

I'd expect the correct behavior be that selector just returns null for unloaded parts of the state.

**Comment by brandonroberts** [comment]
This is already handled by `createFeatureSelector`, which is what you should use when composing feature selectors for `@ngrx/entity`

**Comment by zakhenry** [comment]
@brandonroberts the example does use `createFeatureSelector`?

**Comment by brandonroberts** [comment]
It does. I don't think we should return a null value for something that isn't defined in this case.

**Comment by zakhenry** [comment]
@brandonroberts the problem still remains that a lazy loaded module will cause an error to be thrown from within `createFeatureSelector`.

Would it be correct to wrap this to guard against the error? Something along the lines of 

```ts
function createLazyFeatureSelector<T>(stateSlice: string, initialState: T) {

  return (state) => {
    if (!(stateSlice in state)) {
      return { ...state, [stateSlice]: initialState };
    }

    return createFeatureSelector<T>(stateSlice)(state);
  }

}
```

**Comment by timdeschryver** [comment]
I'm not in favor of adding a guard here. If state is accessed, it should be there.

If we would add a guard here, there should be more guards in NgRx (I believe) but also in the application itself. Every part of the application that touches something of this state would need to be wrapped with a guard, I don't see added value here.

That being said you can create a custom `createFeatureSelector`, e.g. `createLazyFeatureSelector` and use it in your application.

**Comment by zakhenry** [comment]
Thanks @timdeschryver the use of `createLazyFeatureSelector` is the strategy we opted for.
