### ISSUE TITLE
@ngrx/data - Passing QueryParams in getByKey

### ISSUE THREAD

**Issue by sergey-karlo** [ngrx/platform#2159]
Sometimes it's necessary to pass additional Passing QueryParams in getByKey.
It's impossible to make workaround using getWithQuery, because it has different route (plural route).

## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[X] No

**Comment by jordanpowell88** [comment]
@sergey-karlo Can you provide some more context to your issue? What is it you are trying to accomplish exactly?

**Comment by kadung** [comment]
@jordanpowell88 I think I have same problem with @sergey-karlo.
When I try to call getgetAll() method then the request API is domain/posts 
But I use getByKey(1) method then  the request API is domain/post/1 (I think it should be domain/posts/1)

You take a look at https://stackblitz.com/edit/angular-bbgfje

**Comment by sergey-karlo** [comment]
@jordanpowell88 my case is I have entity with several large (BLOB like) properties. Usually I don't need that large property values when I query data from server, but in some cases I do. So I would use some additional QueryParams in getByKey to specify whether I need the BLOB values or not

**Comment by exeleon** [comment]
@jordanpowell88 @sergey-karlo 
I think this would be a desirable option. My API accepts query params to expand the result (ex: include relational models from DB). As a workaround I am doing this:
```
getByIdWithQuery(id: string | number, options: QueryParams) {
    const queryParams = Object.keys(options).map(key => `${key}=${options[key]}`).join('&');
    return super.getByKey(`/${id}?${queryParams}`);
}
```

**Comment by brandonroberts** [comment]
Closing as a duplicate of #1934
