### ISSUE TITLE
[Bug] No provider for Store! in V4.0.0

### ISSUE THREAD

**Issue by luchillo17** [ngrx/platform#216]
## I'm submitting a...

<pre><code>
[x] Bug report  
</code></pre>

## What is the current behavior?

![image](https://user-images.githubusercontent.com/9698639/28750912-6f0ba3a6-74bf-11e7-91a3-5393284cac38.png)

## Expected behavior:
To not throw error.

## Minimal reproduction of the problem with instructions:
Clone: https://github.com/luchillo17/yuxi-global-angular-test/tree/develop
Specific commit: 24cb2eef953e38c96f91dda92da1f91cea0425e5

Then run with `npm run start` and open in browser, error should show in console.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
Chrome: 60.0.3112.78 (Official Build) (64-bit)
Ubuntu: 17.04
npm: 5.3.0
node: v7.10.1
ngrx: 4.0.0

**Comment by ronzeidman** [comment]
this line:
https://github.com/luchillo17/yuxi-global-angular-test/blob/develop/src/app/app.component.ts#L2
```ts
import {Store} from '@ngrx/store/src';
```
should be:
```ts
import {Store} from '@ngrx/store';
```

**Comment by luchillo17** [comment]
Omg, i'm dumb, i should look more at how the VSCode auto import plugin gives me paths, sorry for making an issue for that.

**Comment by maxisam** [comment]
@luchillo17 don't be too hard on yourself. I got the same shit here too. And spent 8+ hours for this. Your issue saved my day. 

Mine is `@ngrx/store/store`

**Comment by luchillo17** [comment]
Yeah but mine was because of laziness to make VSCode import for me.

**Comment by maxisam** [comment]
@luchillo17 well, same here. I used typescript built-in feature with VSCode. I think this might be a bug just not sure it should be in typescript or ngrx store.

**Comment by brandonroberts** [comment]
Its not a bug with ngrx store. If you add an `NgModule` without defining it and use VSCode imports, it will give you options like `@angular/core/core`

**Comment by maxisam** [comment]
@brandonroberts I thought about that too. I guess both typescript and typescript hero, a vs code extension, make the same error.
