### ISSUE TITLE
Cannot override mockstore selector during testing

### ISSUE THREAD

**Issue by peterreisz** [ngrx/platform#2171]
Once a select stream is created it cannot be overwritten during tests with the `mockStore.overrideSelector`

## Minimal reproduction of the bug/regression with instructions:

I have the following component:

```ts
@Component({
  template: `{{ myValue$ | async }}`
})
class MyComponent {
  myValue$ = this.store.select(mySelector);
  // ... other observables

  constructor(private store: Store<any>) {}

  onSomeEvent(): void {
    this.store.dispatch(myAction());
  }
  // ... other event handlers
}
```

Which I would like to test:

```ts
describe('MyComponent', () => {
  let store: MockStore<any>;

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [
        MyComponent,
        ...
      ],
      providers: [
        provideMockStore({
          selectors: [{ selector: mySelector, value: 'foo' }],
        })
      ],
    }).compileComponents();
  }));

  beforeEach(() => {
    store = TestBed.get(Store);
    fixture = TestBed.createComponent(MyComponent);
    fixture.detectChanges();
  });

  it('should render bar insteadof foo', () => {
    store.overrideSelector(mySelector, 'bar');
    fixture.detectChanges();
    expect(fixture.debugElement.nativeElement.textContent).toBe('bar');
  });

}
```

## Expected behavior:

The above test should pass, the `mockStore.overrideSelector` should update the select stream.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

NgRx: 8.4.0

## Other information:

The [mockstore implementation](https://github.com/ngrx/platform/blob/master/modules/store/testing/src/mock_store.ts#L114) is now creating the stream, but it does not store any reference of the subject. Mockstore should the reference of the stream and next a new value into it in case of `overrideSelector` called.

There is a similar issue, but that does not solve the use case defined above: #2121

## I would be willing to submit a PR to fix this issue

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by manklu** [comment]
IMHO the documentation contains all that's needed to support your use case.

https://next.ngrx.io/guide/store/testing#using-mock-selectors

**Comment by timdeschryver** [comment]
You can use the new `mockStore.refreshState()` method, which isn't documented yet (https://github.com/ngrx/platform/issues/2154).

You can take  a look at https://github.com/ngrx/platform/pull/2148 for an example.

**Comment by peterreisz** [comment]
@manklu @timdeschryver 

`store.pipe(select(mySelector))` can be mocked during tests, but you have no tests mocking `store.select(mySelector)`. If you be kind and look at [the code I've linked](https://github.com/ngrx/platform/blob/master/modules/store/testing/src/mock_store.ts#L114) you can see, it's directly returning a new Subject which won't be refeshed with `mockStore.refresState()`

**Comment by timdeschryver** [comment]
@peterreisz could create a reproducable example with it?
We have a test to verify `store.select` should work - https://github.com/ngrx/platform/blob/master/modules/store/testing/spec/mock_store.spec.ts#L336-L345

**Comment by peterreisz** [comment]
@timdeschryver I've just got back to this issue and it's working now, thanks for the help.
Meanwhile I've found a connected minor issue: #2244

**Comment by ChuckkNorris** [comment]
@peterreisz I know it's been a while, but do you know what the issue was?
I just ran into the same issue where we can set a selector in the `provideMockStore({selectors})` method, but it's not getting overridden when using `store.overrideSelector()`

**Comment by ChuckkNorris** [comment]
Think I just found the issue and it was because of the `beforeEach(async () => ...)` combined with the `beforeEach(() => ...`.
e.g. Just moved all the fixture/component setup code in the OP's example into a single beforeEach call.

**Comment by Babeetlebum** [comment]
@ChuckkNorris I had the same issue, I added `.refreshState()` and it ended up working. I don't really like how it looks but at least it works
```typescript
// in Testbed
provideMockStore({selectors: { selector: mySelector, value: mockResult1 }})
// in beforeEach
TestBed.inject(MockStore).overrideSelector(mySelector, mockResult2);
TestBed.inject(MockStore).refreshState();
fixture.detectChanges();
// the test
```

**Comment by tortuc** [comment]
> `mockStore.refreshState`

Did you test it? It's not working.

**Comment by tortuc** [comment]
@timdeschryver 
overrideSelecor() is not working in it().
```
it('should not render if allowReferral is false', () => {
   store.overrideSelector(
      getPlayer,
      {
        ...initialState.player,
        firstName: 'Tortu',
        lastName: 'C',
        featureFlags: {
          allowCrypto: false,
          allowReferral: false,
        }
      },
    );

    store.refreshState();
    expect(component.fullName).toBeUndefined();
  })
```
