### ISSUE TITLE
[devtools] time travel duplicates actions

### ISSUE THREAD

**Issue by Hagith** [ngrx/platform#2173]
## Minimal reproduction of the bug/regression with instructions:

- Start official [example-app](https://github.com/ngrx/platform/tree/master/projects/example-app)
- Navigate through application
- Use time travel in Redux DevTools extension

Bug screencast: https://youtu.be/6TycwZjqxcs

## Expected behavior:

Time traveling should not dispatch new/duplicated actions.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

- NgRx [latest master](https://github.com/ngrx/platform/commit/0d597833c284a07d1f78d2ddf122f65ce60c7821)
- Angular 8.0.0
- Node v10.16.3
- Linux Fedora 30
- Google Chrome 77.0.3865.120
- Redux DevTools extension 2.17.0

## I would be willing to submit a PR to fix this issue

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by dummdidumm** [comment]
I'm not really sure if this is intended behaviour or not. I guess these are actions triggered from effects. Either way, as a workaround you can click on "lock changes" to prevent such things.

**Comment by timdeschryver** [comment]
This is indeed the effects that dispatch the actions.
If I remember correctly we mentioned you should lock the changes, as @dummdidumm said.
