### ISSUE TITLE
[@ngrx/store/testing] overrideSelector with props

### ISSUE THREAD

**Issue by mistic100** [ngrx/platform#2176]
Currently we can override selectors in the MockStore with the `overrideSelector` method. This method treats `MemoizedSelector` and `MemoizedSelectorWithProps` exactly the same way : by providing an hardcoded return value.

It would be really is usefull to be able to provide a callback for `MemoizedSelectorWithProps` in order to return different values depending on the props.

## Describe any alternatives/workarounds you're currently using

None

## Other information:

I am testing a router guard that can check multiple access rights, accessed via a selector, and I want to test when the user has some rights but not all.

## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

**Comment by fpl1976** [comment]
+1

**Comment by minijus** [comment]
Is anyone looking into this already?
I have same issue and would be willing to submit a PR.

**Comment by louie-succio** [comment]
Is there any update on this?

**Comment by minijus** [comment]
@louie-succio it works fine overriding MemoizedSelectorWithProps statically - the mock value can't be conditional based on passed prop.

The scenario that is not possible to mock today would be similar to this:
```ts
it('should allow conditionally mocking of store.select with a memoized selector with Prop using provideMockStore', () => {
  const expectedValue = 300;

  const selectorWithPropMocked = createSelector(
    () => initialState,
    (state: typeof initialState, add: number) => state.counter1 + add
  );

  // This override should be applied when prop is 1
  mockStore.overrideSelector(selectorWithPropMocked, 100);

  // This override should be applied when prop is 2
  mockStore.overrideSelector(selectorWithPropMocked, 200);

  // Idea for mocking #1:
  // mockStore.overrideSelector(selectorWithPropMocked, 1, 100);
  // mockStore.overrideSelector(selectorWithPropMocked, 2, 200);

  // Idea for mocking #2:
  // mockStore.overrideSelector(selectorWithPropMocked, (prop) => {
  //   switch (prop) {
  //     case 1:
  //       return 100;
  //     case 2:
  //       return 200;
  //   }
  // });

  combineLatest([
    mockStore.select(selectorWithPropMocked, 1),
    mockStore.select(selectorWithPropMocked, 2),
  ]).subscribe((result) => expect(result).toBe(expectedValue));
});
```

**Comment by bbonczek** [comment]
Is there any update on this?

**Comment by mmulhearn** [comment]
@minijus it seems you know exactly what we're looking for.  are you working to get this in?

**Comment by timdeschryver** [comment]
I just wanted to mention that there's a chance that selector with props will be deprecated (and removed later).
https://github.com/ngrx/platform/issues/2980

**Comment by brandonroberts** [comment]
Closing as we've deprecated selectors with props
