### ISSUE TITLE
data: document default http request structure

### ISSUE THREAD

**Issue by dalu** [ngrx/platform#2177]
## Other information:

I found https://slides.com/jiali/deck-5#/18 however it doesn't seem right.
PUT is idempotent, which effectively means it needs an url parameter, as well as does DELETE.

How is one supposed to write a compatible http api when it's not documented?

## I would be willing to submit a PR for the docs :heart:

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

**Comment by timdeschryver** [comment]
I just verified that it does have a query param:

```
PUT http://localhost:4200/api/hero/3 
DELETE http://localhost:4200/api/hero/5 
```

**Comment by dalu** [comment]
thank you and sorry for no PR, my head is exploding in multiple dimensions rn

**Comment by timdeschryver** [comment]
No problem @dalu , thanks for raising an issue - this change will be helpful for others
