### ISSUE TITLE
Request for bugfix release to fix effects testing

### ISSUE THREAD

**Issue by linkvt** [ngrx/platform#218]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
</code></pre>

## What is the current behavior?
Testing Effects with `provideMockActions` is broken since the platform release. A workaround is simple and is also used in the [example app](https://github.com/ngrx/platform/blob/master/example-app/app/books/effects/collection.spec.ts#L11-L23).
A fix for this was merged almost two weeks ago: https://github.com/ngrx/platform/commit/bfdb83bfc51a895c548395189033763f56573e6d

## Expected behavior:
I don't want to be pushy, but I would really appreciate a bugfix release - that said without knowing whether there are any internal/unknown blockers. If there are any blockers (like the update of the example app), I will gladly help.
I noticed it, because I kept my migration PR open since I encountered the problem.

If no release is planned, I will just merge the PR and open an issue at my side to remove the workaround when the fix is released - so not really a problem, just wanted to inform you in case the release was forgotten.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
@ngrx/effects at 4.0.1

**Comment by brandonroberts** [comment]
Closed via https://github.com/ngrx/platform/commit/f969676c56b29bd585bf263ce4131d1b4c84d25d
