### ISSUE TITLE
[@ngrx/entity] Use ReadonlyArray<T> instead of mutable arrays

### ISSUE THREAD

**Issue by dmytro-gokun** [ngrx/platform#2181]
For example, EntityStateAdapter<T> has methods like:

```
addMany<S extends EntityState<T>>(entities: T[], state: S): S;
addAll<S extends EntityState<T>>(entities: T[], state: S): S;
```

Would not it make sense to change these to:

```
addMany<S extends EntityState<T>>(entities: ReadonlyArray<T>, state: S): S;
addAll<S extends EntityState<T>>(entities: ReadonlyArray<T>, state: S): S;
```

This looks like a backward-compatible change which support immutable/functional style.

Same for EntitySelectors:

```
    selectIds: (state: V) => string[] | number[];
    selectAll: (state: V) => T[];
```

should become:

```
    selectIds: (state: V) => ReadonlyArray<string> | ReadonlyArray<number>;
    selectAll: (state: V) => ReadonlyArray<T>;
```

This is a breaking change though.

Thoughts?

**Comment by timdeschryver** [comment]
If we would use the `ReadOnly` types we should take a broader look, e.g. also add it to reducers and selectors.
This can also help for #1824.

**Comment by dmytro-gokun** [comment]
@timdeschryver You are right, this should not be limited to @ngrx/entity only. The reason i've labeled the issue in that way was that EntityStateAdapter methods were we I run into warning while refactoring one of my projects to use ReadonlyArray-s. Practically, that was the only source of warnings. That, however, might be different for different projects.

In any case, if ReadonlyArray-s are to be used within @ngrx, i think it needs to starts somewhere. And the easieast places to start would be those which would not create breaking changes. EntityStateAdapter seems to be just like that.

**Comment by brandonroberts** [comment]
We will revisit this at some point. Closing for now

**Comment by dev054** [comment]
Hey @brandonroberts any chance to revisit it before v11? Thanks.
