### ISSUE TITLE
Improve typings of createEffect, help debugging

### ISSUE THREAD

**Issue by alex-okrushko** [ngrx/platform#2192]
## Describe any alternatives/workarounds you're currently using

Currently it's very hard to debug any issues (wrong type, missing imports or anything else really) that are happening within `createEffect` callback.

e.g.
<img width="714" alt="Screen Shot 2019-10-29 at 5 36 29 PM" src="https://user-images.githubusercontent.com/2830407/67825970-6c969f80-faa1-11e9-9dd9-fb7b2de46235.png">

Here we have the missing import for `switchMap`, for example, yet Typescript doesn't help us pinpoint what the issue is.

I think we should change the signature of `createEffect` to further improve it.
I'll take this opportunity to add `{[CREATE_EFFECT_METADATA_KEY]: EffectConfig}` type as well, since that's what all effects have anyway. That should improve types within effects in other functions, such as `getCreateEffectMetadata` and so on.

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by alex-okrushko** [comment]
After looking into and making a number of other improvements, I don't see you this could be solved, for a few reasons:
- we chain operators from observable without enclosing it with `{return obs}`.
- we still want to be strict on what it returns (has to be `Observable<Action>`).

Based on that, here are the workarounds:
- temporarily add `{dispatch: false}`. The type becomes less string and other errors are surfaced.
- put obs inside `{return this.actions$.pipe(...)}` - then the body of the function is checked for errors first.

I'd recommend the second approach, because it's less error prone. Forgetting to remove `{dispatch: false}` may result in hours of debugging why action is not dispatched from effect.

```ts
effect$ = createEffect(() => {
  return this.actions$.pipe(
    ...
  );
});
```

**Comment by brandonroberts** [comment]
I think the second option is an easy win. We can update the schematics to do this also.

**Comment by alex-okrushko** [comment]
Yes, I agree. Schematics and snippets 🙂

**Comment by timdeschryver** [comment]
I was excited for this change, as I've had also looked into it and came to the same conclusion.

This is an error that I see frequently and I didn't know how to make it more clear on what the actual problem is. Thanks for providing a workaround 👍

**Comment by brandonroberts** [comment]
I think we've updated the stuff on our end to fix this.

**Comment by AdditionAddict** [comment]
@brandonroberts should the docs be updated? I'm still getting a lot of traffic to my [stackoverflow answer](https://stackoverflow.com/a/57612215/4711754) on this

**Comment by brandonroberts** [comment]
Yes, if there are any examples that aren't unwrapped, they should be updated

**Comment by MrCardenas10** [comment]
See your method getCollection and validate if you have of that form: 

getCollection(): Observable<name of interface that you use or type any> {
   return ...
}
