### ISSUE TITLE
Cannot reference reducer by FeatureKey when using AOT

### ISSUE THREAD

**Issue by petrikas** [ngrx/platform#2193]
## Minimal reproduction of the bug/regression with instructions:
https://stackblitz.com/edit/ngrx-seed-pgzkpn

`ng serve --aot`
or
`ng build --aot`

throws

```
ERROR in src\app\app.module.ts(21,25): Error during template compile of 'AppModule'
  Expression form not supported in 'reducers'
    'reducers' contains the error at src\app\reducers\index.ts(19,3).
```
## Expected behavior:
It should be possible to reference raducers by using featureKeys using the AOT compiler.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

NGRX 8.0.0
Angular 7.0.0
Node 10.16.0
OS Windows
Browsers N/A

package.json
```
{
  "name": "ngrx-seed",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "@angular-devkit/core": "8.0.1",
    "@angular-devkit/schematics": "8.0.1",
    "@angular/common": "8.0.0",
    "@angular/compiler": "8.0.0",
    "@angular/core": "8.0.0",
    "@angular/forms": "8.0.0",
    "@angular/platform-browser": "8.0.0",
    "@angular/platform-browser-dynamic": "8.0.0",
    "@angular/router": "8.0.0",
    "@ngrx/effects": "8.0.0-rc.0",
    "@ngrx/entity": "8.0.0-rc.0",
    "@ngrx/router-store": "8.0.0-rc.0",
    "@ngrx/schematics": "8.0.0-rc.0",
    "@ngrx/store": "8.0.0-rc.0",
    "@ngrx/store-devtools": "8.0.0-rc.0",
    "core-js": "2.5.4",
    "rxjs": "6.5.2",
    "tslib": "1.9.3",
    "zone.js": "0.9.1"
  },
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.10.0",
    "@angular/cli": "~7.0.2",
    "@angular/compiler-cli": "~7.0.0",
    "@angular/language-service": "~7.0.0",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.1"
  }
}
```

Also, tested with 
NGRX 8.4.0
Angular 8.2.11
Node 10.16.0
OS Windows
Browsers N/A

## Other information:

This bug occurs when i use `counterFeatureKey` to reference the slice of state in the ActionReducerMap with AOT enabled.

Currently, it is possible to workaround the issue by "hardcoding" the feature name or compile without AOT.

Instead of
```
export const reducers: ActionReducerMap<State> = {
  router: routerReducer,
  [counterFeatureKey]: counterReducer,  
};
```
Use
```
export const reducers: ActionReducerMap<State> = {
  router: routerReducer,
  counter: counterReducer,  
};
```

## I would be willing to submit a PR to fix this issue

[ x ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

P.S. If necessary I can build a sample using the latest version and syntax.

**Comment by alex-okrushko** [comment]
@petrikas Please add features with `StoreModule.forFeature(counterFeatureKey, counterReducer)`;

**Comment by petrikas** [comment]
@alex-okrushko but how do I add multiple reducers then?

**Comment by alex-okrushko** [comment]
Instead of `counterReducer` you can provide another function that returns `combineReducers` call: https://github.com/ngrx/platform/blob/master/projects/example-app/src/app/books/reducers/index.ts#L27

**Comment by petrikas** [comment]
@alex-okrushko Thank you for your help.

**Comment by jpduckwo** [comment]
The schematics generates reducers using ActionReducerMap however this doesn't compile with AOT unless you change this to a combineReducers function like

e.g. change:
```
export const reducers: ActionReducerMap<State> = {
  [fromRooms.roomsFeatureKey]: fromRooms.reducer,
  [fromRoomsWatcher.roomsWatcherFeatureKey]: fromRoomsWatcher.reducer,
};
```
TO
```
export function reducers(state: State | undefined, action: Action) {
  return combineReducers({
      [fromRooms.roomsFeatureKey]: fromRooms.reducer,
      [fromRoomsWatcher.roomsWatcherFeatureKey]: fromRoomsWatcher.reducer,
  })(state, action);
}
```
@alex-okrushko Should schematics be updated to generate reducers/index.ts files like this maybe? I can raise a new issue if you think it should.
