### ISSUE TITLE
 NgRx store returning undefined on APP_INITIALIZER

### ISSUE THREAD

**Issue by paubereng** [ngrx/platform#2196]
I have a init service called with `APP_INITIALIZER`. This service call some endpoints that I need before runing app.
When I build the app without `--prod` flag, works fine, but with flag store returns undefined.
Some idea what happens? Thanks.

**Comment by brandonroberts** [comment]
Support questions should be asked in the [gitter channel](https://gitter.im/ngrx/platform)
