### ISSUE TITLE
feat(router): router actions as ActionCreators

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#2206]
If we're using the creator functions for reducers and effects we aren't able to use the router actions.
I'm suggesting that we'd also create these router actions as `ActionCreators`, for example:

```ts
export const routerRequestAction = createAction(ROUTER_REQUEST, props<{ payload: RouterRequestPayload<BaseRouterStoreState> }>())
```

## Describe any alternatives/workarounds you're currently using

We can create the `ActionCreators` in our project.

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by maartentibau** [comment]
OK, I will have a look on this tonight (if I don't forget), but I'm happy to help out on this one!

**Comment by Jefiozie** [comment]
Hi @timdeschryver and @maartentibau, did one of you guys already worked on this? 
I would like to help or pick up this ticket, however, I'm not exactly sure what I need to do. 

My understanding of this ticket is that we would like to have migrated the default actions based on the new `createAction` ticket. Is this correct?

**Comment by timdeschryver** [comment]
I'm not working on this.

We want to have both options (action type enum and action creator), familiar to https://github.com/ngrx/platform/pull/2219.

**Comment by Jefiozie** [comment]
Okay, if @maartentibau doesn't mind I can have a look at this issue. ☺️

**Comment by maartentibau** [comment]
@Jefiozie I don't mind if you have a look. I didn't really have a lot of time to look at it. But I'm certainly willing to help out if need be.

Sadly ... the time I can spend on OSS is very very limited these days, but since I'm using the creator methods now on a very frequent base I thought I could help out. But again... finding the time to do it is the hardest part.

So sure... feel free to start on it, thx m8!!

**Comment by Jefiozie** [comment]
So I  added a draft PR, should we update the docs (https://ngrx.io/guide/router-store/actions) as well?

**Comment by timdeschryver** [comment]
I think we should, we're going to make the creator functions the default in v9.x so I think it will be helpful to add it to the docs.

I think we should update the docs with the emphasis on the creator function, and add a note that the action types can still be used.
Similar to actions/reducers/effects in the [current docs](https://ngrx.io/guide/effects#writing-effects):

![image](https://user-images.githubusercontent.com/28659384/69273095-10262c00-0bd8-11ea-858f-0b1516c3deb2.png)

**Comment by Jefiozie** [comment]
I missed your comment for some reason, I will make some changes to the docs in upcoming days. Did you have some time to see if the PR is what you expected?
