### ISSUE TITLE
Store reset on route change

### ISSUE THREAD

**Issue by hems03** [ngrx/platform#221]
My routing module for a part of my app is protected by a authentication guard that uses a state in the ngrx store. 

Here is the guard's canActivate function

`canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<boolean> {
        
        return this.authSub.map(role => {
            console.log("ROLE: "+role)
            if (role != UKNOWN) {
                return true
            }
            this.router.navigate(['/login'], { queryParams: { returnUrl: state.url } });
            return false
        })`
In my initial state, the role is set to UKNOWN, but on route changes, ngrxinit is being called and the store is being reset. As a result, I'm being redirected to the login page every time. Any ideas on how to debug this or what could be wrong?

**Comment by arjun289** [comment]
I am facing an issue where when I hover a time-stamp for any action dispatched its updating the time to current time. This is really weird along with on router change my previous dispatched actions are preserved. I think my store is reset too time and again. @hems03 @brandonroberts @karptonite @vsavkin

**Comment by brandonroberts** [comment]
A reproduction of this issue would help. Here is a plunker template: http://plnkr.co/edit/tpl:757r6L

**Comment by hems03** [comment]
the initial plunker template doesn't work. It is stuck on  'loading' when I run it.

**Comment by brandonroberts** [comment]
I froze the plunker to the latest version. Try reloading it
