### ISSUE TITLE
Blog: Write blog post for version 9 release

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#2214]
For future reference. Will be published at https://medium.com/ngrx

**Comment by maxipaolucci** [comment]
When is the release date?

**Comment by AdditionAddict** [comment]
@maxipaolucci expected soonish, waiting on #2231 - see Projects tab

**Comment by brandonroberts** [comment]
https://medium.com/ngrx/announcing-ngrx-version-9-immutability-out-of-the-box-customizable-effects-and-more-e4cf71be1a5b
