### ISSUE TITLE
Docs: update example dependencies to version 9

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#2215]
The dependencies for the generated examples need to be updated with the upcoming release. The `package.json` file is located in the `projects/ngrx.io/tools/examples/shared` folder. 

- [ ] Update the Angular dependencies to latest 
- [ ] Update the NgRx dependences to latest
- [ ] Run yarn in the `shared` folder to update the `yarn.lock` file

**Comment by jordanpowell88** [comment]
@brandonroberts Thanks for clarifying v9. I read this yesterday and was a little confused. I can work on this

**Comment by brandonroberts** [comment]
Fixed via #2360
