### ISSUE TITLE
generate ROOT_EFFECTS_INIT through createAction

### ISSUE THREAD

**Issue by maxisam** [ngrx/platform#2218]
Currently ROOT_EFFECTS_INIT is defined from
https://github.com/ngrx/platform/blob/2bac73cb33c5e05874e4dd7962c6d75496d009b8/modules/effects/src/effects_root_module.ts#L12

However, it doesn't work with `createReducer` or `createEffect`

Should we create this action through createAction?

**Comment by timdeschryver** [comment]
Can be done, the same way as pointed out in https://github.com/ngrx/platform/issues/2206

**Comment by timdeschryver** [comment]
Do you want to create a PR with these changes @maxisam ?

**Comment by maxisam** [comment]
@timdeschryver I just tried to make a pull request but I don't know where I messed up
