### ISSUE TITLE
Action Payload Object by Reference

### ISSUE THREAD

**Issue by kuwas** [ngrx/platform#222]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## What is the current behavior?

Objects passed by reference to an action payload will update the store, but not trigger subscription emissions.

## Expected behavior:

Objects passed by reference should either not update the store, or update the store and trigger the subscription emissions.

## Minimal reproduction of the problem with instructions:

In my example, since the object is empty at the start, it works the first time, but once the key is existing in the object and only the value changes, it will still update the store value, but no longer trigger subscription emissions. As a workaround I just clone the object before passing it into the payload to avoid passing by reference.

```
public temporary = {};

public onChange(key: string, value: string): void {
  this.temporary[key] = value;
  this.store.dispatch(new Action(this.temporary)); // adding clone(this.temporary) will work
}
```

```
<input (change)="onChange('asdf', $event.target.value)" type="text" />
```

## Version of affected browser(s),operating system(s), npm, node and ngrx:
Node 8.2.1
NPM 5.3.0
ngrx 4.0.0

## Other information:
I know this is bit of an edge case, but I'm basically using multiple inputs to construct a "filter" object and sending it to the store. Please close this issue if this behavior is by design.

**Comment by littleStudent** [comment]
I think this is by design.
It is your responsibility in the reducer to return a new object instead of modifying the state.
This means that you can control when a subscription to the store is triggered with new values.

**Comment by karptonite** [comment]
Can we see your reducer? If you are storing the `temporary` object directly in the reducer, that is the problem, I think, since the store data should be immutable.

**Comment by kuwas** [comment]
@karptonite 
Yeah the reducer returns the payload directly `return action.payload`. I had a feeling this might be by design for immutability, I'll close this then.
