### ISSUE TITLE
HttpClientModule should come with @ngrx/data

### ISSUE THREAD

**Issue by jhcao23** [ngrx/platform#2220]
## Minimal reproduction of the bug/regression with instructions:
A basic cli series:
```
ng new app && cd app && ng add @ngrx/store && ng add @ngrx/store-devtools && ng add @ngrx/effects && yarn add @ngrx/effects && yarn add @ngrx/router-store && ng add @ngrx/entity && ng add @ngrx/data && ng add @ngrx/schematics
```
## Expected behavior:

It should run!

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
ng: 8.2.13
ngrx: 8.4.0
node: 12.12.0
os: macOS Catalina

## Actual Result: 
the main page has nothing and the `<app-root></app-root>` doesn't compile.

## Workaround: 
Add `HttpClientModule` to `app.module.ts` solves the problem OR, remove `EntityDataModule` from this file.

**Comment by brandonroberts** [comment]
`HttpClientModule` is an implicit dependency that may not be included in the module where you import the `EntityDataModule`. We can add a note to the docs that `@ngrx/data` assumes you already have it imported into your application. Would you like to submit a PR for this?

**Comment by jhcao23** [comment]
I'm not good at schematics so I only updated the docs on the main page of the @ngrx/data section.
I created a [PR 2238](https://github.com/ngrx/platform/pull/2238).
Thanks!
