### ISSUE TITLE
Docs: Observable is missing the type in Effects overview

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#2221]
The `Observable` is missing the type from the Effects example https://ngrx.io/guide/effects#comparison-with-component-based-side-effects

The code snippet is correct, but the `<` and `>` need to be changed to the equivalent HTML entities.

The file to edit is here: https://github.com/ngrx/platform/blob/master/projects/ngrx.io/content/guide/effects/index.md

**Comment by jordanpowell88** [comment]
Sorry for the long mess here, my forked branch got all jacked up. Should be good now
