### ISSUE TITLE
RFC: Change behavior of ofType in Effects to be more consistent when combining observables

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#2222]
There are two predominant things you do when listening to an action after using the `ofType` operator:

```ts
actions.pipe(
  ofType('SOME_ACTION')
  someMap(action => doSomething(action))
)
```
and
```ts
actions.pipe(
  ofType('SOME_ACTION'),
  withLatestFrom(store.select(someThing)),
  someMap(([action, latest]) => doSomething(action, latest))
)
```

These have two different behaviors as far as effects are concerned. The first one doesn't do anything until the action is dispatched, which is what it should do.

The second one immediately subscribes to the `withLatestFrom` whether the action is dispatched yet or not. If that state used by the selector is not initialized yet, you could get an error you're not expecting. In order to make it "lazy" you end up having to nest it within a flattening observable operator.

```ts
actions.pipe(
  ofType('SOME_ACTION'),
  someMap(action =>
    of(action).pipe(
      withLatestFrom(store.select(someThing)),
      someMap(([action, latest]) => doSomething(action, latest))
    )
)
```

We document this here: https://ngrx.io/guide/effects#incorporating-state

I think the behavior should be the same in either case, where the selector should not be triggered until the action is dispatched without having to nest it inside another flattening observable operator.

One idea would be to add a `.pipe` after the `filter` inside the `ofType` operator to map it to a new observable of the action to mimic the second scenario. There are probably other options also, and I haven't measured the impact of this change yet either.

**Comment by AdditionAddict** [comment]
I referenced this in [a stackoverflow answer](https://stackoverflow.com/questions/60282687) as I personally found the above explanation better than the docs. 

With regards to the RFC, I think this is needed. Whilst you would guess `ofType` is a filter the behaviour above is still surprising and not what you would expect and try first.

**Comment by jqsjqs** [comment]
I agree. The official docs weren't clear on this and needs this type of explanation. Good job @brandonroberts (and thanks).

**Comment by sod** [comment]
We [wrote a custom operator for that](https://gist.github.com/sod/a34fc7705b396f61d0ef00713b807209), that boils down to

```typescript
export function mergeTakeOne<SOURCE, MERGE extends ObservableInput<any>>(
    ...toBeMerged$: MERGE[]
): OperatorFunction<SOURCE, [SOURCE, ...ObservedValueOf<MERGE>[]]> {
    return mergeMap((source) =>
        combineLatest(toBeMerged$).pipe(
            take(1),
            map((source2): any => [source, ...source2]),
        ),
    );
}
```

used just like `withLatestFrom`, only that it subscribes once it's needed.

**Comment by ngfelixl** [comment]
I am sorry that I did not found this discussion and opened #2703.

In my opinion it would be really nice to have something like a `withLatestFromStore` operator provided by the effects package that combines the `concatMap` and the `withLatestFrom`. I've seen and I see many people just using `withLatestFrom`. For myself, I use NgRX almost every day and only knew about the performance issues about a month ago or so. Having an operator in place that prevents the devs from having to use the nested observables would be very beneficial. Therefore it would be great to have a `withLatestFromStore` operator in place that is usable like

```typescript
createEffect(() => this.actions$.pipe(
  ofType(getSelectedBookDetails),
  withLatestFromStore(this.store.select(getSelectedBookId)),
  switchMap(([action, selectedBookId]) => this.bookService.getDetails(selectedBookId).pipe(
    map(...),
    catchError(...)
  )
);
```

or without having the store explicitly injected

```typescript
createEffect(() => this.actions$.pipe(
  ofType(getSelectedBookDetails),
  withLatestFromStore(getSelectedBookId),
  switchMap(([action, selectedBookId]) => this.bookService.getDetails(selectedBookId).pipe(
    map(...),
    catchError(...)
  )
);
```

If the operator name contains the `withLatestFrom` string could help the dev understand how to use it. He or she can assume that it is similar to the corresponding RxJS operator. At least the first thing I would try as an output would be the array like function parameter `[action, selectedBookId]` if I am not familiar with it.

**Comment by david-shortman** [comment]
@ngfelixl The key distinction to note is that `withLatestFromStore`, as an operator, will not be able to reference an injectable `Store`, so it can't internally do `this.store.select` on each provided selector.

For instance you, could have this instead:

```typescript
createEffect(() => this.actions$.pipe(
  ofType(getSelectedBookDetails),
  delayedWithLatestFrom(() => [this.store.select(getSelectedBookId)]),
  switchMap(([action, selectedBookId]) => this.bookService.getDetails(selectedBookId).pipe(
    map(...),
    catchError(...)
  )
);
```

**Comment by david-shortman** [comment]
At that point, I wonder if the use case would extend far enough to be included in RxJS instead. I'm sure there are other instances where it is desirable to delay evaluation of the params to an operator like `withLatestFrom`.

**Comment by david-shortman** [comment]
Created an issue in RxJS land to see where such an operator would better belong https://github.com/ReactiveX/rxjs/issues/5845

**Comment by david-shortman** [comment]
Here's the operator I ended up writing. Gonna figure out how to open a PR:

```typescript
import { Observable, of, OperatorFunction } from 'rxjs';
import { concatMap, withLatestFrom } from 'rxjs/operators';

type TypeOfObservable<T> = T extends Observable<infer U> ? U : never;

/*
 * RxJS operator that lazily evaluates the input Observables.
 *
 * Useful when there is a performance cost for evaluating a function which produces
 * an input observable, like in the case of NgRx's `store.select` method.
 */
export const lazyWithLatestFrom = <T extends Observable<unknown>[], V>(o: () => [...T]) =>
  concatMap(value => of(value).pipe(withLatestFrom(...o()))) as OperatorFunction<
    V,
    [V, ...{ [i in keyof T]: TypeOfObservable<T[i]> }]
  >;
```

Jest proof:
```typescript
import { of } from 'rxjs';
import { lazyWithLatestFrom } from './lazy-with-latest-from.operator';
import { skipWhile, tap, withLatestFrom } from 'rxjs/operators';
import { hot } from 'jasmine-marbles';

describe('lazyWithLatestFrom', () => {
  it('should evaluate the array of observables only when the source emits a value', () => {
    // given
    let evaluated = false;
    const toBeLazilyEvaluated = () => {
      evaluated = true;
      return of(4);
    };

    // when
    const numbers$ = hot('abc', { a: 1, b: 2, c: 3 }).pipe(
      skipWhile(number => number < 3),
      tap(() => expect(evaluated).toBe(false)),
      withLatestFrom(() => [toBeLazilyEvaluated()])
    );

    // then
    expect(evaluated).toBe(false);
    expect(numbers$).toBeObservable(hot('--d', { d: [3, 4] }));
    expect(evaluated).toBe(true);
  });
});
```

**Comment by jeetparikh** [comment]
Another question around this is once the withLatestFrom subscribes it's always listening. If a pipe and put a `.tap` to it I can see it logging all the time when that particular state slice changes. What I am interested in just the latest value of that state slice when THAT action triggers. And this is what I had originally intended too. Isn't this a performance hit if it's always listening? Any tips @brandonroberts  or anyone . Thanks

**Comment by david-shortman** [comment]
> Another question around this is once the withLatestFrom subscribes it's always listening. If a pipe and put a `.tap` to it I can see it logging all the time when that particular state slice changes. What I am interested in just the latest value of that state slice when THAT action triggers. And this is what I had originally intended too. Isn't this a performance hit if it's always listening? Any tips @brandonroberts or anyone . Thanks

Answered this question in the discussion in this PR https://github.com/ngrx/platform/pull/2799#issuecomment-738473327

**Comment by MichaliEverson** [comment]
a verbal conversation is or could be a verbal contract of confidentiality
as well as a need to know basis meta/manifest form is the same as a thought
what could be or is jus as so a wish

**Comment by david-shortman** [comment]
> a verbal conversation is or could be a verbal contract of confidentiality as well as a need to know basis meta/manifest form is the same as a thought what could be or is jus as so a wish
> […](#)

I think you replied to the wrong email, friend

**Comment by niklas-wortmann** [comment]
just adding my 2 cents to this discussion. I usually just do 
```ts
actions.pipe(
  ofType('SOME_ACTION'),
  withLatestFrom(store.select(someThing)),
  someMap(([action, latest]) => doSomething(action, latest))
)
```

My problem with having the `withLatest` in `someMap` operator is that it will create a new subscription to that observable on every emission. This works fine with ngrx selects which emits synchronously on subscribe, but this won't behave as expected if the observable emits asynchronous. The problem is actually displayed in the marble diagram of rxjs
![image](https://user-images.githubusercontent.com/6104311/102198228-bf8b0c00-3e87-11eb-9001-459ce9d68509.png)
If you would pass an observable that emits asynchronously by wrapping it in `someMap` you will likely lose the triggered action.
This might be just one of my concerns, so ignore me if this does not apply :D

**Comment by david-shortman** [comment]
@niklas-wortmann You are right that if you delay when withLatestFrom in invoked, some Ovservables will not have a value readily available like is the case with store.select.

This is another good reason why the PR for concatLatestFrom is against NgRx and not proposed as an RxHs operator- it fits this use case well, but could get people into trouble in other scenarios if they don't understand the mechanics of their Observables and the operator.
