### ISSUE TITLE
Schematics: update Effect schematics to unwrap and return actions stream

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#2226]
A follow-up to #2192 

Today we generate effects that use an arrow function with an implicit return to return the observable stream:

```ts
effect = createEffect(() => this.actions$.pipe(switchMap(() => {})))
```

This is prone to be harder to debug in the case of missing imported operators in the observable pipeline. Unwrapping the function and returning the actions/observable stream will give the developer better debugging information as to what's wrong inside the function.

```ts
effect = createEffect(() => {
  return this.actions$.pipe(switchMap(() => {}));
})
```

The schematics for generating Effects should be updated to unwrap and return the observable stream of actions. The files are here:

https://github.com/ngrx/platform/tree/master/modules/schematics/src/effect/files/__name%40dasherize%40if-flat__

**Comment by maxisam** [comment]
I was just trying to do the same thing.

https://gist.github.com/maxisam/12da6721d2ed6ea9dc30ffe4fef0eb78

My case is a bit different because I have my own action creator before. So anyone wanna try it need to modify it first.

**Comment by hehaijin** [comment]
May I work on this issue?

**Comment by brandonroberts** [comment]
@hehaijin Sure. Let us know if you need any assistance
