### ISSUE TITLE
Schematics: generate selectors by default when generating state features

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#2227]
We introduced generated selectors with 8.5.0. They should be generated by default

**Comment by Jefiozie** [comment]
I can have a look at this however is it not already enabled [here](https://github.com/ngrx/platform/blob/master/modules/schematics/src/feature/index.ts#L48)

**Comment by timdeschryver** [comment]
I think you're right @Jefiozie

**Comment by Jefiozie** [comment]
Okay, if @brandonroberts also agree on this we can close the ticket. 😊

**Comment by Jefiozie** [comment]
Pinging @brandonroberts to see if this is resolved, if not I will have a look at it 😁

**Comment by brandonroberts** [comment]
This one is already done.
