### ISSUE TITLE
Docs: Missing "props" import on scoreboard-page.actions.ts example

### ISSUE THREAD

**Issue by acb14js** [ngrx/platform#2233]
I think there is a missing import in the scoreboard-page.actions.ts example from the Reducers tutorial page (https://ngrx.io/guide/store/reducers)

I think the imports should change from:

`import { createAction } from '@ngrx/store';`
To this:
`import { createAction, props } from '@ngrx/store';`

Because the props method is used on the line 
`export const setScores = createAction('[Scoreboard Page] Set Scores', props<{game: Game}>());`

**Comment by timdeschryver** [comment]
You're totally right @abinp !

Feel free to create a PR with the proposed change 👍

**Comment by jordanpowell88** [comment]
If @acb14js  doesn't want to I can

**Comment by timdeschryver** [comment]
Let's give @acb14js the time to answer @jordanpowell88

**Comment by acb14js** [comment]
@timdeschryver just added the pull request

**Comment by timdeschryver** [comment]
@acb14js I think you still have to create the pull request at https://github.com/ngrx/platform/pulls by clicking on "New pull request" (green button at the top right).

**Comment by acb14js** [comment]
@timdeschryver Thanks for your patience, Its my first time creating a pull request. I think I've setup the pull request correctly now.

**Comment by timdeschryver** [comment]
Super! Thanks @acb14js
