### ISSUE TITLE
Remove Angular & @ngrx/store Dependency from @ngrx/entity

### ISSUE THREAD

**Issue by alaboudi** [ngrx/platform#2237]
I really like ngrx's entity module that I decided to use it with my react application. Unfortunately, it is coupled with Angular and ngrx/store. I think it would be a great idea to remove these dependencies and have it as a standalone package that is consumable by any application that wants to manage entity collections. What do you think?

**Comment by brandonroberts** [comment]
Thanks @alaboudi. We don't have any plans to remove these dependencies from `@ngrx/entity`.
