### ISSUE TITLE
Property/method 'let' has been removed from Store?

### ISSUE THREAD

**Issue by chrisbenseler** [ngrx/platform#224]
I have upgraded my att to @ngrx/store to 4.0.0 and it seems that the let() method (property) from Store has been removed.
Is this correct? I didn't found it in the changelog.

The error:

> Property 'let' does not exist on type 'Store<any>'

If so, what is the proper way to deal with this? Can I use the .select() method?

My package.json:

> "@ngrx/core": "^1.2.0",
> "@ngrx/effects": "^4.0.0",
> "@ngrx/router-store": "^4.0.0",
> "@ngrx/store": "^4.0.0",

**Comment by brandonroberts** [comment]
The `let` operator is not specific to `@ngrx/store`. You just need to import it. You can use the `.select` method also

```ts
import 'rxjs/add/operator/let';
```
