### ISSUE TITLE
Platform: Update usage of TestBed.get to TestBed.inject

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#2240]
`TestBed.inject` replaces `TestBed.get<Type>`. We need to clean up:

- [ ] Library code
- [ ] Docs
- [ ] Schematics

Blocked by #2234

**Comment by sumitparakh** [comment]
Hey, I wanna do this.

**Comment by brandonroberts** [comment]
@sumitparakh It's yours. Let us know if you need any assistance

**Comment by sumitparakh** [comment]
Hi @brandonroberts , This update requires angular 9 and i see that currently ngrx is not upgraded to Angular 9.. 

Is there any other issue regarding Angular upgrade or should i upgrade to Angular 9 in this PR itself?

**Comment by santoshyadav198613** [comment]
Angular 9 update is in progress @timdeschryver is already on it.

**Comment by sumitparakh** [comment]
Alright. So I'll wait for that update and then continue with this PR
