### ISSUE TITLE
Schematics: add support for exported createReducer and Ivy

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#2241]
With Ivy, we can use the reducers generated by `createReducer` directly. 

```
export const reducer = createReducer(...);

StoreModule.forRoot({ myState: reducer });
```

We should add support for this in the docs and schematics:

- [ ] Note that the exported reducer is required for View Engine in the docs
- [x] Add support to schematics to export the generated reducer and not include the exported function.
- [ ] Update the AOT metadata errors link to https://angular.io/guide/aot-metadata-errors#function-calls-are-not-supported

We will keep the existing exported reducer by default, unless there is some way to detect Ivy within our schematics.

**Comment by brandonroberts** [comment]
Example detection from the Angular schematics https://github.com/angular/angular-cli/blob/524bff6f43f4cf94c9c6e8c26efd514e52ec7455/packages/schematics/angular/migrations/update-9/utils.ts#L111

**Comment by brandonroberts** [comment]
Closed via #2440

**Comment by JohannesHoppe** [comment]
As you all know, this new syntax cannot be used with the old View Engine. Unfortunately the old engine is still is the basis for extracting messages using the command "ng xi18n". One solution is to use a different extration tooling. see https://github.com/angular/angular-cli/issues/17319#issuecomment-626936585

**Comment by Maximaximum** [comment]
Why has this issue been closed if only 1 of 3 tasks have actually been resolved? In particular, the docs still need to be updated

**Comment by Maximaximum** [comment]
@timdeschryver I've created a PR to update the docs. Could you please check it out?

**Comment by Maximaximum** [comment]
FWIW, yet another PR would be needed to update https://ngrx.io/guide/store page as well

**Comment by Maximaximum** [comment]
And https://ngrx.io/guide/store/reducers too :)
