### ISSUE TITLE
Schematics: use `skipTests` instead of `spec` 

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#2242]
With the new version of the Angular CLI, the `spec` option from the schematics has been removed. Instead, a `skipTests` option has been added.

We would like to keep our schematics in line with the Angular CLI schematics.

This change includes:

- [ ] Modifying the schematic options
- [ ] Update the schematics code
- [ ] Uppdate the docs

For ref: angular/angular-cli@e92c46a

**Comment by Jefiozie** [comment]
I would like to work on it, if that is fine by you @timdeschryver

**Comment by timdeschryver** [comment]
Sure, go ahead @Jefiozie.
Feel free to ping us if needed.

**Comment by Jefiozie** [comment]
@timdeschryver thanks, I also see a change around style. Do you want me to change this I'm this issue/PR?

**Comment by timdeschryver** [comment]
Seems like I'm too late to answer 😅

**Comment by Jefiozie** [comment]
haha, yeah I thought it would be fine so made the PR 👍

**Comment by timdeschryver** [comment]
Yes, ofcourse - thanks!
