### ISSUE TITLE
Effect in library - TS4029 Public property .. of exported class has or is using name 'CreateEffectMetadata' from external module

### ISSUE THREAD

**Issue by jorgjanke** [ngrx/platform#2243]
ERROR: projects/my-lib/src/lib/animal.effects.ts(13,3): 
**error TS4029: Public property 'loadAnimals$' of exported class has or is using name 'CreateEffectMetadata' from external module** "/Users/jorg/Documents/Test/vLatest/node_modules/@ngrx/effects/src/effect_creator" but cannot be named.

## Minimal reproduction of the bug/regression with instructions:

ng generate library MyLib --prefix ml
ng generate feature Animal --project MyLib -m MyLibModule --api --creators
ng build MyLib

## Expected behavior:
No error

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
8.5

## Other information:
```
Angular CLI: 8.3.18
Node: 12.4.0
OS: darwin x64
Angular: 8.2.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.18
@angular-devkit/build-angular      0.803.18
@angular-devkit/build-ng-packagr   0.803.18
@angular-devkit/build-optimizer    0.803.18
@angular-devkit/build-webpack      0.803.18
@angular-devkit/core               8.3.18
@angular-devkit/schematics         8.3.18
@angular/cli                       8.3.18
@angular/pwa                       0.803.18
@ngtools/webpack                   8.3.18
@schematics/angular                8.3.18
@schematics/update                 0.803.18
ng-packagr                         5.7.1
rxjs                               6.4.0
typescript                         3.5.3
webpack                            4.39.2
```

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No (no clue where to look)

**Comment by timdeschryver** [comment]
Is it possible to share the repo @jorgjanke ?

**Comment by alex-okrushko** [comment]
I might've not added `CreateEffectMetadata` to the exported public api.
