### ISSUE TITLE
Mockstore selector override with undefined value

### ISSUE THREAD

**Issue by peterreisz** [ngrx/platform#2244]
## Minimal reproduction of the bug/regression with instructions:

```ts
interface MyFeatureState {
  myProp?: string;
}

const selectMyFeature = createFeatureSelector<MyFeatureState>('my-feature');

const selectMyProp = createSelector(selectMyFeature,
  (state: MyFeatureState) => state.myProp);

TestBed.configureTestingModule({
  providers: [provideMockStore()],
}).compileComponents();

const store: MockStore<any> = TestBed.get(Store);
const mockSelector = store.overrideSelector(selectMyProp, undefined);

mockSelector.setResult(undefined);
store.refreshState();

store.select(selectMyProp).subscribe(val => expect(val).toBe(undefined))
```

## Expected behavior:

User should be able to override selector result with `undefined` too, at this moment [`undefined`](https://github.com/ngrx/platform/blob/2bac73cb33c5e05874e4dd7962c6d75496d009b8/modules/store/src/selector.ts#L84) value is indicating that the selector result is not overwritten, thus mockstore will try to run all the selector logic.

This would be useful in case of a deep state contains an optional value and the user do not want to define the whole state tree in the parameter of the `provideMockStore` method. As a workaround `setResult` can be called with `null as any`, but projects can ban null keyword via a tslint rule, thus it might requires additional lint ignore comment too.

NgRx should use a different variable for indicating is the selector value overwritten.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

NgRx: 8.4.0

## I would be willing to submit a PR to fix this issue

[X] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by Maximaximum** [comment]
Wow, I had to spend a couple of hours in order to find this issue and realize that `overrideSelector()` does not properly handle the `undefined` value. Indeed, this is a huge problem and has to be fixed

**Comment by alex-okrushko** [comment]
Yeah, I knew about this issue, and still spent a few hours debugging... 🤦‍♂️
