### ISSUE TITLE
routerReducer doesn't handle ROUTER_NAVIGATED action

### ISSUE THREAD

**Issue by dmitry-urenev** [ngrx/platform#2246]
Hey guys, during refactoring of one project in our company I noticed that `routerReducer` doesn't handle `ROUTER_NAVIGATED` action:

https://github.com/ngrx/platform/blob/90d06020d794034d326f01dbecef440be62cf7ce/modules/router-store/src/reducer.ts#L18-L36

I don't think that it is so on purpose. In our app we are interested in the router state only when navigation is finished - when we pass all guards and resolvers. 

## So the expected behavior would be:

to see **the latest** serialized router state when navigation is finished: 

```ts
switch (routerAction.type) { 
     .....
     case ROUTER_NAVIGATED: 
       return { 
         state: routerAction.payload.routerState, 
         navigationId: routerAction.payload.event.id, 
       }; 
```

Right now we do it in some custom reducer, but that makes then `ngrx/router-store` module completely useless for us. Maybe you could improve that, shouldn't be a big deal. 

Thanks in advance! 

## Versions of NgRx, Angular:
```
"@angular/core": "^8.2.0",
"@ngrx/router-store": "^8.0.0",
"@ngrx/store": "^8.0.0",
```

**Comment by brandonroberts** [comment]
I think what you're looking for is https://ngrx.io/api/router-store/StoreRouterConfig#navigationActionTiming
