### ISSUE TITLE
Schematics: replace `styleExt` with `style`

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#2248]
With the new version of the Angular CLI, the `styleExt` option from the schematics has been removed. Instead, a `style` option has been added.

We would like to keep our schematics in line with the Angular CLI schematics.

This change includes:

- [ ] Modifying the schematic options
- [ ] Update the schematics code
- [ ] Uppdate the docs

For ref: angular/angular-cli@e92c46a

**Comment by Jefiozie** [comment]
@timdeschryver  going to do this one as well if you don't mind.
