### ISSUE TITLE
Store: Use minimal option by default for ng add

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#2250]
Change minimal to be `true` by default, so only the `StoreModule.forRoot({})` is added to the AppModule.

The option is here: https://github.com/ngrx/platform/blob/master/modules/store/schematics/ng-add/schema.json#L41

**Comment by Jefiozie** [comment]
Hey @brandonroberts, I would like to pick this one up. Next to changing the property do you expect anything else?

**Comment by brandonroberts** [comment]
The docs on the installation page may need updating also
