### ISSUE TITLE
ngrx reducer

### ISSUE THREAD

**Issue by JakobKadosh** [ngrx/platform#2256]
Trying to build state management with multiple states.
in the app.state.ts :
import { ActionReducerMap } from '@ngrx/store';
import * as bookStore from './state managment'

export interface AppState{
    user:bookStore.UserState;
    book:bookStore.BookState;
    wishlist:bookStore.WishlistState;
}

export const initialState:AppState={
    user:bookStore.userInitState,
    book:bookStore.bookInitState,
    wishlist:bookStore.wishlistInitState
}

export const reducer:ActionReducerMap<AppState>={  // HERE I GET ERROR!!! see message below 
    book:bookStore.reducer
};

export const getMyBook=(s:bookStore.BookState)=>s.book;
export const getMyUser=(s:bookStore.UserState)=>s.user;
export const getMyWishlist=(s:bookStore.WishlistState)=>s.wishlist;
ERROR MESSAGE: 
Type '{ book: (state: any, action: bookActions) => any; }' is missing the following properties from type 'ActionReducerMap<AppState, Action>': user, wishlistts(2739)

**Comment by timdeschryver** [comment]
Support questions should be asked on [stackoverflow (with a ngrx tag)](https://stackoverflow.com/questions/tagged/ngrx) or the [gitter channel](https://gitter.im/ngrx/platform).
