### ISSUE TITLE
RC.1/IVY - export 'EffectsFeatureModule' (imported as 'i2') was not found in @ngrx/effects

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#2260]
Copied from https://github.com/angular/angular/issues/33701

# 🐞 bug report

### Affected Package

  

After upgrading to RC1 and turning on IVY I get tons of errors from  the @ngrx/effects module.

```
"export 'EffectsFeatureModule' (imported as 'i2') was not found in '@ngrx/effects'
"export 'EffectsFeatureModule' (imported as 'i2') was not found in '@ngrx/effects'
```
... and so on.. 

Turning off IVY everything works without an issue.

This is from a production app running NG8 currently in production.
It uses @ngrx/store and effects module.

I've never had these issues with the .next-x and rc.0 versions.

### Is this a regression?

I think so

 Yes, the previous version in which this bug was not present was: ....

I believe so.
 I've never seen this issue before and I've tested all .next versions and rc.0

### Description

ng serve yields lots off errors like:

```
ERROR in ./src/app/store/bizz-store/bizz-store.module.ts 19:79-102
"export 'EffectsFeatureModule' (imported as 'i1') was not found in '@ngrx/effects'
ERROR in ./src/app/modules/lazy-shared/lazy-shared.module.ts 136:26-50
"export 'EffectsFeatureModule' (imported as 'i16') was not found in '@ngrx/effects'
ERROR in ./src/app/feature-modules/dashboard/dashboard.module.ts 58:520-544
"export 'EffectsFeatureModule' (imported as 'i16') was not found in '@ngrx/effects'
ERROR in ./src/app/store/iticket-store/iticket-store.module.ts 22:105-128
"export 'EffectsFeatureModule' (imported as 'i2') was not found in '@ngrx/effects'
ERROR in ./src/app/feature-modules/login/store/login-store.module.ts 24:103-126
"export 'EffectsFeatureModule' (imported as 'i2') was not found in '@ngrx/effects'
ERROR in ./src/app/feature-modules/gdpr/gdpr.module.ts 40:149-172
"export 'EffectsFeatureModule' (imported as 'i3') was not found in '@ngrx/effects'
ERROR in ./src/app/modules/licenseplate-checker/licenseplate-checker-module.ts 25:162-185
"export 'EffectsFeatureModule' (imported as 'i3') was not found in '@ngrx/effects'
ERROR in ./src/app/feature-modules/feedback/feedback.module.ts 38:185-208
"export 'EffectsFeatureModule' (imported as 'i3') was not found in '@ngrx/effects'
ERROR in ./src/app/feature-modules/weather/weather.module.ts 38:182-205
"export 'EffectsFeatureModule' (imported as 'i3') was not found in '@ngrx/effects'
ERROR in ./src/app/feature-modules/receipt/receipt.module.ts 39:170-193
"export 'EffectsFeatureModule' (imported as 'i4') was not found in '@ngrx/effects'
```

## 🔬 Minimal Reproduction

Unfortunately I cannot share my repo but if nobody has seen this issue before I'll try and do a minimal version. 

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.0.0-rc.1
Node: 12.2.0
OS: darwin x64
Angular: 9.0.0-rc.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-rc.1
@angular-devkit/build-angular      0.900.0-rc.1
@angular-devkit/build-optimizer    0.900.0-rc.1
@angular-devkit/build-webpack      0.900.0-rc.1
@angular-devkit/core               9.0.0-rc.1
@angular-devkit/schematics         9.0.0-rc.1
@angular/cdk                       9.0.0-rc.0
@angular/material                  9.0.0-rc.0
@angular/material-moment-adapter   9.0.0-rc.0
@ngtools/webpack                   9.0.0-rc.1
@schematics/angular                9.0.0-rc.1
@schematics/update                 0.900.0-rc.1
rxjs                               7.0.0-alpha.0
typescript                         3.6.4
webpack                            4.41.2

</code></pre>

**Anything else relevant?**

**Comment by brandonroberts** [comment]
Waiting for a reproduction, or more context about the environment.

**Comment by JoostK** [comment]
Hi folks, I have a fix here: https://github.com/angular/angular/pull/33875

Thanks @brandonroberts and others who helped with providing reproductions!

**Comment by JoostK** [comment]
Another update: angular/angular#33875 was just merged and should be available in a release later this week.

**Comment by timdeschryver** [comment]
Thanks @JoostK 👍
