### ISSUE TITLE
Style guide is missing

### ISSUE THREAD

**Issue by Fry-kun** [ngrx/platform#2261]
https://ngrx.io/guide/style-guide doesn't have any info

## I would be willing to submit a PR for the docs :heart:

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
The style guide is not active yet

**Comment by Danebrouwer97** [comment]
I just landed on the same issue.
Would it be possible to remove the link from the site until it's active?

Google crawling ngrx.io still finds Style Guide even though it doesn't necessarily have anything. 
IMO; it seems pointless to have the page while there's no information.
