### ISSUE TITLE
Effects documentation should explicitly state that decorated @Effect members must be public

### ISSUE THREAD

**Issue by zakhenry** [ngrx/platform#2262]
Recent changes to the `@Effect` decorator has now forced effect members to be public on the class, causing a very confusing error:

```ts
export class DemoEffects {

	@Effect()
	private someEffect$ = NEVER;

}
```

will result in a TS error:

```
ERROR in src/app/../demo.effects.ts:3:4 - error TS2345: Argument of type '"someEffect$"' is not assignable to parameter of type 'never'.

32   @Effect()
      ~~~~~~~~

error Command failed with exit code 1.

```
The fix is to simply omit the `private` keyword, or make it `public`.

If there is more than one effect in the class, you get a different error, which is equally confusing:

```ts
export class DemoEffects {
  @Effect()
  private someEffect$ = NEVER;

  @Effect()
  public someOtherEffect$ = NEVER;
}
```
Gives error:
```
ERROR in ERROR in src/app/../demo.effects.ts:3:4 - error TS2345: Argument of type '"someEffect$"' is not assignable to parameter of type '"someOtherEffect$"'.

32   @Effect()
      ~~~~~~~~

error Command failed with exit code 1.

```

The docs don't use `public`/`protected`/`private` keywords at all, but many orgs enforce this selection with lint rules, and it is unexpected that making an effect member private would cause a typescript error.

Even if this does not need to be added to the docs, I hope this issue helps someone else :)

## I would be willing to submit a PR for the docs :heart:

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
@alex-okrushko should we partially revert the commit to allow private members, because this seems like a breaking change. We can re-add add this as a breaking change for v9, or leave it as previously because it doesn't add anything(?) for the dev creating an effect.

The cause is `K extends EffectPropertyKey<T>`:
https://github.com/ngrx/platform/blob/master/modules/effects/src/effect_decorator.ts#L14

**Comment by alex-okrushko** [comment]
> The docs don't use public/protected/private keywords at all, but many orgs enforce this selection with lint rules

In TS, everything is `public` by default, and explicit keyword is not necessary (https://www.typescriptlang.org/docs/handbook/classes.html#public-by-default). Personally, I think enforcing this with lint is strange.

>  it is unexpected that making an effect member private would cause a typescript error.

Technically, these props are used outside of the Effect Classes and `private` means that they should be only used within the class, so making them `private` doesn't make sense to me. If anything, we should be only adding `readonly` to the properties.

**Comment by brandonroberts** [comment]
Do we still need to do anything here?

**Comment by alex-okrushko** [comment]
@zakhenry  Would you consider this resolved?

**Comment by zakhenry** [comment]
@alex-okrushko I think possibly this issue itself may serve as a good enough search result in case anyone else hits the issue. I’m happy to close for now, but it would be helpful if anyone else in future that hits this issue would comment so we can see that the docs need clarity.

On the topic of lint enforcement of explicit publicity declaration, I understand that public is the default, which is precisely the reason to enforce making a conscious choice with linting. We default to private to keep the api surface as small as possible, which is a long term maintenance boon.

In this case it isn’t really clear that the properties are accessed from outside the class, because the semantics of how decorators work aren’t completely obvious to developers

**Comment by alex-okrushko** [comment]
@zakhenry Thanks. If you keep them private, how would you test them? Only through e2e?

**Comment by zakhenry** [comment]
@alex-okrushko yep in this particular case it was a mistake in an effect that was only tested e2e. It should have been public anyway

**Comment by CrazyFlasher** [comment]
This is bad, that I couldn't mark private property with decorator.
What if I would like to inject this property, but shouldn't give possibility to access it like public?
```ts
export const inject = <T>(target:T, key: keyof T) =>
{
  console.log("opa! ", target, key);
}

class Mock
{
  @inject
  private a:number = 1;

  constructor()
  {
    console.log(this.a);
  }
}

new Mock();
```
