### ISSUE TITLE
Can't use export default for reducers (AOT issue)

### ISSUE THREAD

**Issue by DenisValcke** [ngrx/platform#2279]
## Minimal reproduction of the bug/regression with instructions:
I have create a reducer following most documentation:
```typescript
const projectsReducer = createReducer(
	initialState,
	// get a single project | /projects/{id}
	on(getProject, (state) => ({ ...state, isLoading: true})),
	on(getProjectSucces, (state, { project }) => adapter.addOne(project, { ...state, isLoading: false })),
	on(getProjectFailed, (state, { error }) => ({ ...state, error, isLoading: false })),
	// get a range of projects | /projects
	on(getProjects, (state) => ({ ...state, isLoading: true})),
	on(getProjectsSucces, (state, { projects }) => {
		const items = propOr([], 'items', projects);
		const meta = omit('items', projects);

		return adapter.addMany(items, { ...state, meta, isLoading: false });
	}),
	on(getProjectsFailed, (state, { error }) => ({ ...state, error, isLoading: false }))
);

export default function (state: IProjectsState, action: Action) {
	console.log('reducer');
	return projectsReducer(state, action);
}
```

But if I do the above, in production, the AOT compiler can't handle the export default and will leave the store with an empty object instead of an initial-state. This causes the selectors that the adapter generates to break.

If I change the from export default to a named export:
```typescript
const reducer = createReducer(
	initialState,
	// get a single project | /projects/{id}
	on(getProject, (state) => ({ ...state, isLoading: true})),
	on(getProjectSucces, (state, { project }) => adapter.addOne(project, { ...state, isLoading: false })),
	on(getProjectFailed, (state, { error }) => ({ ...state, error, isLoading: false })),
	// get a range of projects | /projects
	on(getProjects, (state) => ({ ...state, isLoading: true})),
	on(getProjectsSucces, (state, { projects }) => {
		const items = propOr([], 'items', projects);
		const meta = omit('items', projects);

		return adapter.addMany(items, { ...state, meta, isLoading: false });
	}),
	on(getProjectsFailed, (state, { error }) => ({ ...state, error, isLoading: false }))
);

export function projectsReducer (state: IProjectsState, action: Action) {
	return reducer(state, action);
}
```
Like above, the problem stops and the code works as expected.

## Expected behaviour
Either a export default shouldn't break my production code or this should be documented.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
I'm using Angular 8.2.9 with ngrx 8.5.1.

## Other information:
I consider this to be a bug. When developing locally, there is no problem but when my production build is on the server, I get very vague errors leaving me with a mess to debug.

You can recreate this issue by doing the same as I did and running Angular locally with: `ng serve --prod --optimization=false`.

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

**Comment by timdeschryver** [comment]
This is due to the Angular AOT compiler.
I'm not sure, but this might be resolved with the ngcc compiler and Ivy.

**Comment by DenisValcke** [comment]
I understand, yet it might be a good idea to highlight this in the docs because this one is very hard to figure out tbh. 😅
