### ISSUE TITLE
Save different state of same child component 

### ISSUE THREAD

**Issue by webTheGiant** [ngrx/platform#2282]
`Hello` everybody,
I work on a simple component (container or parent component) with two same child component, I need to save different state of them. I read something to use metadata but I don't know if it is the best or right way to make it.
Can you help me to solve it
An example of project:

```
<div class="container">
 <a style="font-size: 22px" [routerLink]="['/sibling']" > Sibling</a>
  <div class="parent-block">
    <app-child id="1" #elem></app-child>
    <h1>
      PARENT Component
    </h1>
    <app-child id="2" #elem></app-child>
  </div>
</div>
```

**Comment by timdeschryver** [comment]
You will have to create a reference to each child component in the store: e.g.

```
{
	apps: {
  		1: {...},
		2: {...},
	}
}
```

Support questions should be asked on [stackoverflow (with a ngrx tag)](https://stackoverflow.com/questions/tagged/ngrx) or the [gitter channel](https://gitter.im/ngrx/platform).
