### ISSUE TITLE
e not a function / e.lift not a function when building for prod

### ISSUE THREAD

**Issue by bjornharvold** [ngrx/platform#2285]
## Minimal reproduction of the bug/regression with instructions:

Repo that shows the error.
https://github.com/bjornharvold/ngrx-prod-issue

- Verify that it works with "ng serve" by running ./runDeveloper.sh
- Verify that it does not work when building to prod with ./buildDeveloperProd.sh. (run static assets on some server)

## Expected behavior:
Have spent the whole day trying to figure out why ngrx is not working when building a production bundle. I have a working SPA w ngrx working in production but I cannot deploy an update because the new version doesn't work and I cannot figure out what it is. 

I've stripped down the project and put it in the repo above. Please advise.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
Angular CLI: 8.3.20
Node: 12.13.1
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.20
@angular-devkit/build-angular      0.803.20
@angular-devkit/build-ng-packagr   0.803.20
@angular-devkit/build-optimizer    0.803.20
@angular-devkit/build-webpack      0.803.20
@angular-devkit/core               8.3.20
@angular-devkit/schematics         8.3.20
@angular/cdk                       8.2.3
@angular/cli                       8.3.20
@angular/flex-layout               8.0.0-beta.27
@angular/material                  8.2.3
@angular/pwa                       0.803.20
@ngtools/webpack                   8.3.20
@schematics/angular                8.3.20
@schematics/update                 0.803.20
ng-packagr                         5.7.1
rxjs                               6.5.3
typescript                         3.5.3
webpack                            4.39.2
ngrx 8.5.2

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

<img width="392" alt="Screen Shot 2019-12-02 at 9 22 10 PM" src="https://user-images.githubusercontent.com/641791/69966864-d47d5180-1549-11ea-85d8-78779ada3931.png">

**Comment by arangelp** [comment]
Hi, my platform in production is experiencing the same issue.  Could it be a dependency of a library that changed?

**Comment by erodriguezh** [comment]
Confirming the issue

**Comment by timdeschryver** [comment]
Is there a dependency that is updated recently?

**Comment by timdeschryver** [comment]
Seems related to `ofType`, leave these out and it does work ... not sure why.

**Comment by markhus-aurelius** [comment]
Also having the same issue with our prod build. Looks like an action string is triggering the 'not a function' error 
![Screen Shot 2019-12-02 at 3 11 50 PM](https://user-images.githubusercontent.com/11519613/70001969-93c21e80-15c3-11ea-8a17-2338905deff6.png)

**Comment by brandonroberts** [comment]
This was a bug in an upstream package that has been fixed. Pin the `terser` package to `4.4.0` or `4.4.2` as a workaround.

https://github.com/angular/angular/pull/34179

**Comment by bjornharvold** [comment]
@brandonroberts Great detective work!! My eyes were burning last night after having tried to resolve this one. How did you figure this one out? Yes, @timdeschryver - the only dep update was Angular CLI 8.3.20.

**Comment by brandonroberts** [comment]
😉 Whenever I see errors that point back to build optimizer, its usually an upstream issue with the CLI, as we haven't changed the way we package and distribute the libraries. I reached out to the CLI team, and they pointed me to the cause.
