### ISSUE TITLE
Data: Cannot find NO_TRACK actions

### ISSUE THREAD

**Issue by Nosfistis** [ngrx/platform#2288]
I am trying to update the local store after manually performing a nested object update. Thus, change tracking should be disabled for that action, since the object is persisted remotely already.

Docs [mention](https://ngrx.io/guide/data/entity-change-tracker#enabling-and-disabling-change-tracking) that I can use one of the `NO_TRACK` variations of `EntityOp`, but these are not listed in the enum. Furthermore, I cannot find any code mention of those actions. Are they removed?

## I would be willing to submit a PR for the docs :heart:

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
@wardbell I first thought this was forgotten in the migration, but I can't find the `NO_TRACK` actions in the `ngrx-data` repo either.
Could you help to clarify this?

**Comment by wardbell** [comment]
Yikes. That documentation is incorrect and I'm not sure how this error escaped into the wild.

**That's not correct at all. I must update the documentation.**.

You control how (or whether) the changes are tracked by supplying the optional `mergeStrategy` among the `EntityOptions` that you can pass in the action payload.

>If you don't specify a `mergeStrategy`, Ngrx Data uses the default for that operation.

If you were dispatching an action with `EntityDispatcher` and you didn't want that action to be change-tracked, the code might look something like this:
```
    const hero: Hero = { id: 42, name: 'Francis' };
    dispatcher.addOneToCache(hero, {
      mergeStrategy: MergeStrategy.IgnoreChanges,
    });
```

That's the kind of thing you'd should be able to do with a helpful `EntityCollectionService` facade such as a `HeroService`
```
    const hero: Hero = { id: 42, name: 'Francis' };

    // BUG: doesn't work
    heroService.addOneToCache(hero, {
      mergeStrategy: MergeStrategy.IgnoreChanges,
    });
```

Apparently I neglected to extend the methods of `EntityCollectionService` to take the optional `EntityActionOptions`. Currently `EntityCollectionService.addOneToCache` is implemented as
```
  addOneToCache(entity: T): void {
    this.dispatcher.addOneToCache(entity);
  }
```

It should be
```
  addOneToCache(entity: T, options?: EntityActionOptions): void {
    this.dispatcher.addOneToCache(entity, options);
  }
```
I'll fix that at the same time that I fix the documentation.

Meanwhile, you can access the `dispatcher` directly from an `EntityCollectionService` and dispatch your action with options.

Sorry for the mistakes in documentation and the oversight on `EntityCollectionService` methods.

P.S: If you prepare the action directly with `EntityActionFactory`, it might look like
```
    const hero: Hero = { id: 42, name: 'Francis' };

    const payload: EntityActionPayload = {
      entityName: 'Hero',
      entityOp: EntityOp.ADD_ONE,
      data: hero,
      mergeStrategy: MergeStrategy.OverwriteChanges,
      // .. other options ..
    };

    const action = factory.create(payload);
```
