### ISSUE TITLE
docs: add link to Diagram PSD

### ISSUE THREAD

**Issue by jordanpowell88** [ngrx/platform#2293]
## Other information:

Their has been several requests to share the PSD I created for the Lifecycle diagram used on the getting started page https://ngrx.io/guide/store. 

Not sure where we want to add this link? Issue #2287 suggested we create a "Press Kit" link on the ngrx.io website. Anyone have thoughts where it could go? Maybe under the contribution page? or something maybe even a little more public facing?

## I would be willing to submit a PR for the docs :heart:

[X] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
I think it can be added to the resources list in the footer of ngrx.io (see angular.io for an example)?
