### ISSUE TITLE
ngrx/data: best way to have multiple api roots?

### ISSUE THREAD

**Issue by autozoom** [ngrx/platform#2298]
Hello,
I would need to target different api endpoint roots from different angular modules.

For example 
http://server:port/user-api  from User module
http://server:port/admin-api from Admin module
http://server:port/checkout-api from Cart module
and so on.

From what I see, the api root called by ngrx/data can be changed but only globally, by means of DefaultDataServiceConfig in app.module

How can I have different api roots in different Angular modules?

At the moment I am using a CustomizeHttpUrlGenerator to change the urls based on a naming convention of mine, but I guess if there's a better way.

Thanks

**Comment by zee85** [comment]
I currently have the same set-up where each micro service is available via a different host and port. I put off implementing an api gateway until now. I think using an api gateway makes much more sense than adding custom code to handle mapping each api to a different host/port. Not to mention you will eventually need to consider managing all those services and an api gateway is prefect for that. I'm using .NET Core. For .NET Core Ocelot is the goto package to create an api gateway but I'm sure one exists for every major language / framework.

**Comment by zee85** [comment]
I've been looking through the source code to facilitate this easier without having the api gateway in place. It looks like you can easily register your own instance of the data service. The data service constructor accepts the config which includes the api end-points. So each data service can have a separate url but it requires registering the service manually probably with a factory function.

https://ngrx.io/guide/data/entity-dataservice

**Comment by zee85** [comment]
This what worked for me.

Create custom data service.

`import { Injectable, Inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { DefaultDataService, HttpUrlGenerator, Logger } from '@ngrx/data';

import { ADS_SETTINGS } from '../ads.tokens';
import { AdListItem, AdsSettings } from '../models/ads.models';

@Injectable({
  providedIn: 'root'
})
export class AdListItemDataService extends DefaultDataService<AdListItem> {
  constructor(@Inject(ADS_SETTINGS) adsettings: AdsSettings,http: HttpClient, httpUrlGenerator: HttpUrlGenerator, logger: Logger) {
    super('AdListItem', http, httpUrlGenerator);
    this.entityUrl = this.entitiesUrl = `${adsettings.endpointUrl}/ads`;
  }
}`

Register data service in module.

`@NgModule({
  declarations: [AdDetailComponent, CreateAdComponent, AdMasterComponent, AdSearchBarComponent, AdBrowserComponent, AdDetailTabComponent, AdGalleryTabComponent ],
  imports: [
    CommonModule,
    HttpClientModule,
    ReactiveFormsModule,
    RouterModule.forChild(routes),
    // StoreModule.forFeature(fromAds.ADS_FEATURE_KEY, fromAds.reducer),
    // EffectsModule.forFeature([AdsEffects]),
    MaterialModule,
    FlexLayoutModule,
    NgxDropzoneModule,
    TaxonomyModule
  ],
  providers: [
    // AdsFacade
  ]
})
export class AdsModule {
  constructor(eds: EntityDefinitionService, entityDataService: EntityDataService, adDataService: AdDataService, adListItemDataService: AdListItemDataService) {
    eds.registerMetadataMap(entityMetadata);
    entityDataService.registerService('Ad', adDataService);
    entityDataService.registerService('AdListItem', adListItemDataService);
  }
}`

**Comment by autozoom** [comment]
thanks a lot I will try it

**Comment by timdeschryver** [comment]
Answered in https://github.com/ngrx/platform/issues/2298#issuecomment-569862941

**Comment by vdelamarre** [comment]
Hi.
I do not find the comment that explain the way to do it.

Is there a documentation anywhere ?

Thanks
