### ISSUE TITLE
DOCS: @ngrx/data Reducer example

### ISSUE THREAD

**Issue by sapabg** [ngrx/platform#2302]
Can you please, please, please provide an example for a reducer for @ngrx/data.
https://ngrx.io/guide/data/entity-reducer

How and where do I initialize the EntityCacheReducerFactory when the constructor requires entityCollectionCreator: EntityCollectionCreator, entityCollectionReducerRegistry: EntityCollectionReducerRegistry, logger: Logger

It is all a blur for me...

**Comment by AdditionAddict** [comment]
@sapabg can you give a concrete example of what you are trying to achieve in order to focus the mind?

**Comment by sapabg** [comment]
> @sapabg can you give a concrete example of what you are trying to achieve in order to focus the mind?

Well I basically want to modify the rest of the store on an action completion. 
Let's say I have a @ngrx/data/query-by-key/success action triggered, how do I make a reducer that updates a different part of the store not the entityCache?
I don't really remember what exactly I needed it for a month ago...

**Comment by brandonroberts** [comment]
Support questions should be asked in the [gitter channel](https://gitter.im/ngrx/platform)
