### ISSUE TITLE
Effects: resubscribeOnError for "broken" effect results in infinite loop and ends with "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by alex-okrushko** [ngrx/platform#2303]
## Minimal reproduction of the bug/regression with instructions:

This one ended up being very hard to debug. (Resulted from the recent merge to Google attempt).

There is a test that imports a Module that imports many other Modules. Some of them import `EffectsModule.forFeature(...)`.
The author of the test tried hard to substitute all the Effects Classes with empty objects, so that effects are not running (with many `{provide: FooEffects, useValue: {}}`), however missed one. 
That one missed effect was producing an error immediately (due to the fact that it was using `store.select(selector)` and it was erroring within a `selector`)
Anyhow, the effect was immediately resubscribing and resubscribing, eventually ending up with _"RangeError: Maximum call stack size exceeded"_ error.

Nothing in the stacktrace was pointing to the resubscribing effect (and led to significant debugging time).

## Expected behavior:

Maybe after a number of failed attempts we should actually fail the effect? 100? And make it configurable. 
I wonder if that would still be better that a potentially frozen prod app.

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
I was thinking the same thing the other day but for the "loop of death", where the same action is continuously dispatched. I wondered if this could be a desired behavior in some cases, so a 👍 for making it configurable.

Would this also cover the "loop of death"?

Instead of `{provide: FooEffects, useValue: {}}` what about a `MockEffects` feature? I was fiddling with this idea the other day - https://github.com/ngrx/platform/compare/master...provide-mock-effects

**Comment by alex-okrushko** [comment]
> Instead of {provide: FooEffects, useValue: {}} what about a MockEffects feature?
I was thinking about it as well 😃
We need a carefully thought-out solution though - looking back at MockStore - it's wasn't a smooth merge with a number of changes in behavior. People tend to adopt them quickly, so any changes in them lead to a long refactoring.

How about starting a doc? 😎

**Comment by zakhenry** [comment]
@timdeschryver @alex-okrushko hah this isthe class of error that I hit, and attempted to resolve in #2294

**Comment by timdeschryver** [comment]
To not mix the maximum number of retries and the mock effects, I will create a separate issue for it so it's not forgotten (with a doc later).
