### ISSUE TITLE
DOCS: In no way match the example application

### ISSUE THREAD

**Issue by then3rdman** [ngrx/platform#2304]
It seems that documentation is from a previous iterations of NgRx. Whilst they do work and get you a working application, they are not even close to the demo application. Is this intentional? The readme of the demo app states "showcasing common patterns and best practices." Is the documentation on the main site intentionally different?

For example the demo app uses action and reducer creator functions, but the main documentation doesn't even make mention that these exist. 

Essentially just wondering how intentional this is? Is the docs update in the pipe line or is it something that would require some volunteers?

**Comment by alex-okrushko** [comment]
> For example the demo app uses action and reducer creator functions, but the main documentation doesn't even make mention that these exist

Hi @then3rdman 
They are documented, for example here: https://ngrx.io/guide/store/actions

Which documentation are you referring to?

**Comment by then3rdman** [comment]
> > For example the demo app uses action and reducer creator functions, but the main documentation doesn't even make mention that these exist
> 
> Hi @then3rdman
> They are documented, for example here: https://ngrx.io/guide/store/actions
> 
> Which documentation are you referring to?

Seems I just missed large amounts of the docs... Guess I'm the idiot.
