### ISSUE TITLE
ngrx/data: immutability of store broken after calling upsertOneInCache() of EntityCollectionService

### ISSUE THREAD

**Issue by Martinn2** [ngrx/platform#2307]
## Minimal reproduction of the bug/regression with instructions:

Repro can be found here: https://github.com/Martinn2/ngRxUpserInCacheIssue

## Expected behavior:

After calling upsertOneInCache() and then loading data from backend (using getByKey()), store immutability should not be broken

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
node: v12.13.1
NgRx: 8.6.0
Angular: 8.2.14

## Other information:

Run npm run server to start test express server.

Run ng serve for a dev server. Navigate to http://localhost:4200/.

When data is loaded from express server as many times as needed, no errors occur. However once changes are added using upsertOneInCache method and then loaded from server again, an error destroying immutability of store occures and can be seen in console.

If strictStateImmutability is set to false everything works.

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ x] No

**Comment by santoshyadav198613** [comment]
I will get it checked @timdeschryver .

**Comment by AdditionAddict** [comment]
@santoshyadav198613 `entity-change-tracker-base.ts` in general looks suspicious (`undoMany` is definitely buggy - PR #2352 opened), and `trackUpsertMany` is used in this case. All the methods in `entity-change-tracker-base.ts` return `collection` directly. Should these be returning `{ ...collection }` (assuming user deep clones entity)?
