### ISSUE TITLE
Pass NavigationStart event to Custom Router State Serializer

### ISSUE THREAD

**Issue by chrisguttandin** [ngrx/platform#2308]
I think it would be helpful if the actual navigation event would be passed to a Custom Router State Serializer of the router-store module. The [NavigationStart](https://angular.io/api/router/NavigationStart) event has for example a [navigationTrigger](https://angular.io/api/router/NavigationStart#navigationTrigger) property which is not available in the [RouterStateSnapshot](https://angular.io/api/router/RouterStateSnapshot).

## Describe any alternatives/workarounds you're currently using
I'm currently using my own custom router store. 

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by tehZeno** [comment]
@chrisguttandin  info on your custom router store? (kind of in need of this feature)

**Comment by chrisguttandin** [comment]
Hi @tehZeno, it's just a property on my state object which I update on each NavigationStart event.

Hi @timdeschryver, do you think it makes sense when I start a pull request for this. Or is this something you would rather not like to add to the library?

**Comment by brandonroberts** [comment]
Closing for now as something we won't be adding.
