### ISSUE TITLE
RFC:  a `MockEffects` provider during test setup

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#2316]
## Describe any alternatives/workarounds you're currently using

Manually mock effect instances

## Other information:

TODO (created the issue to not forget about it)

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

A WIP can be found at https://github.com/ngrx/platform/compare/master...provide-mock-effects

**Comment by brandonroberts** [comment]
Would you ever use `provideMockActions()` and `provideMockEffects()` together?

**Comment by timdeschryver** [comment]
> TODO (created the issue to not forget about it)

Yea... that didn't work 😅

The problem I've seen with this is when you would import a module (with effects) into the TestBed.
This was causing effects to be triggered either through actions or other sources.

Imho importing a module into the TestBed is a bad practice, so I'm going to close this issue.
We refactored the test setup instead.

Feel free to re-open if you see any value in it, and I will work in it.
