### ISSUE TITLE
ngrx/data: how to pass dynamic config to EntityDataModule.forRoot()?

### ISSUE THREAD

**Issue by autozoom** [ngrx/platform#2318]
Hello,
I would need to pass a dynamic configuration to `EntityDataModule.forRoot`.

Instead of being forced to declared `entityMetadata` and `pluralNames` statically I need to calculate them from a common, and statically declared, object.
Something like:

```
export const moduleEntityMap: ModuleEntityMap[] = [
    {
        httpContext: 'lookup',
        entities: {
            AreaBisogno: { plural: 'AreeBisogno', metadata: {} },
            DestinatarioTariffa: { plural: 'DestinatariTariffe', metadata: {} },
            [...]
        },
    },
    {
        httpContext: 'admin-sgq',
        entities: {
            Tariffe: { plural: 'Tariffe', metadata: {} },
            Nodo: { plural: 'Nodi', metadata: {} },
            [...]
        },
    },
];
```

From this I can calculate the `EntityDataModuleConfig` instance need by `EntityDataModule.forRoot`.
Nothing fancy, no services or http requests, just trying to aggregate everything in one config object of mine.
I've been trying to achieve this but with no luck.
I cannot use the forRoot pattern because there's no `ModuleWithProviders` counterpart that allows to dynamically declare the imports array.

I've then tried to put my logic into a pure .js file, inject it directly into the index.html file and save the resulting calculated `EntityDataModuleConfig` instance to the `window` object, something like:

```
entityConfig = extractConfig(myConfig);
window.entityConfig  = entityConfig;
```

and then read it from my module:
```
@NgModule({
imports: [EntityDataModule.forRoot(window['entityConfig'])]
...
```
but I always get a null as the forRoot parameter, don't really know why.

Is there a way to pass something that is not statically declared to `EntityDataModule.forRoot`?
That is, can I execute some code before declaring the imports array of my module?

This seems a fairly common requirement but I cannot find a way.

Thanks a lot.

**Comment by timdeschryver** [comment]
What about the following?

```
function extractConfig(config) {...}
const entityConfig = extractConfig(myConfig);

@NgModule({
imports: [EntityDataModule.forRoot(entityConfig )]
```

**Comment by autozoom** [comment]
> const entityConfig = extractConfig(myConfig);

Unfortunately this code will not execute before the @NgModule annotation, this is the whole point of the problem.

**Comment by timdeschryver** [comment]
And what if it's been done in `main.ts` and stored as a global variable, before the execution of `platformBrowserDynamic.bootstrapModule()`

**Comment by autozoom** [comment]
> 
> 
> And what if it's been done in `main.ts` and stored as a global variable, before the execution of `platformBrowserDynamic.bootstrapModule()`

That is what I've done, as explained.
Do you have a better idea for where to store it globally?

**Comment by timdeschryver** [comment]
🤦‍♂️  ofcourse, you're right. 


I'm still not sure why `EntityDataModule.forRoot(extractConfig(myConfig))` won't work tho. Besides that, I'm out of ideas.

**Comment by ve2m** [comment]
Can you please provide an example to reproduce your problem? I just tried it locally and it worked fine.

**Comment by autozoom** [comment]
I am very sorry but I forgot to mention that the issue only arises when you build for production, using AOT compilation.
I cannot provide an example on stackblitz as it only uses JIT compilation.

Could you please try and compile you example with --prod and see if it stops working?


> 
> 
> Can you please provide an example to reproduce your problem? I just tried it locally and it worked fine.

**Comment by brandonroberts** [comment]
This is a better question for the [gitter channel](https://gitter.im/ngrx/platform)
