### ISSUE TITLE
make createAction unique value to avoid duplication of actions

### ISSUE THREAD

**Issue by born2net** [ngrx/platform#2321]
I often find myself copying pasting actions before editing the new action name.
if by mistake I forgot to rename the action param I end up with two actions and actions should always be unique. I did this as a workaround to avoid issues:

```
export const actionEnterpriseUpdateApps = createAction(uniqueActionName('Enterprise API', 'update apps tx'), props<IEnterpriseApps>());

export function uniqueActionName(segment, name) {
  return `[${segment.toUpperCase()}] ${name.toLowerCase()} ${_.uniqueId('action_')}`;
}
```
but would be great if ```createAction``` would just append a unique value to the string as no two actions should ever be same when defined.

this will also give an opportunisticway to  standardize the name of action, as in lower case and upper case etc.

Thanks,

Sean.

**Comment by timdeschryver** [comment]
I consider adding a unique string a bad practice, imho.

- an action should describe a unique event in the application
- it would be hard to debug


You can try [ngrx-tslint-rules](https://github.com/timdeschryver/ngrx-tslint-rules#rules) which has a TSLint rule that checks if an action name is unique.

But now that I'm thinking of it.

Should we add a check inside `createAction` that checks if action names are unique (we won't be able to use `isDevMode()`)?

**Comment by born2net** [comment]
my 2 cents is that Actions should be appended with uniqueness

**Comment by alex-okrushko** [comment]
I agree with @timdeschryver - Actions should be describing unique events and thus have unique string names.

But you can easily create your own action creator if you choose.

```ts
function uniqueAction<P extends object>(
    segment: string, name: string, props?: Props<P>&NotAllowedCheck<P>) {
  const actionName = `[${segment.toUpperCase()}] ${name.toLowerCase()} ${
      new Date().toString()}`;
  if (props) {
    return createAction(actionName, props);
  }
  return createAction(actionName);
}
```

> Should we add a check inside createAction that checks if action names are unique (we won't be able to use isDevMode())?

I don't think we'll be able to check within createAction, but we could add some unique property to each Action and then within a store keep a map of actionName -> uniqueId and if we run into the same actionName and different ids that have some error.

But TBH, not sure it's worth the effort.

**Comment by timdeschryver** [comment]
See @alex-okrushko 's snippet.
We can revisit this later if needed.

**Comment by Deitsch** [comment]
What is the equivalent to this for the new @ngrx/eslint-plugin?

**Comment by Armenvardanyan95** [comment]
@Deitsch instead of the eslint plugin, you can use the runtime check called `strictActionUniqueness`, like this:

```typescript
@NgModule({
    imports: [StoreModule.forRoot(yourFeatures, {
      runtimeChecks: {
        strictActionUniqueness: true,
      }
    }
  )]
})
export class AppModule
```

You can do this similarly if you use standalone with `provideStore`, it also has runtime cheks

> Note this will check the uniqueness in _runtime_, but still will generate a meaningful error and show the action that caused it
