### ISSUE TITLE
Inconsistent dispatch synchronization

### ISSUE THREAD

**Issue by ersimont** [ngrx/platform#2322]
## Minimal reproduction of the bug/regression with instructions:

Here is a jasmine test demonstrating the inconsistency. Run this, where `backingStore` is just a `Store` object.

```ts
it("gets consistent values when subscribing", () => {
  backingStore.addReducer("testKey", (state: any, action: any) => ({
    ...state,
    counter: action.counter,
  }));

  function setAndGet(counter: number) {
    backingStore.dispatch({ type: "set", counter });
    backingStore.pipe(take(1)).subscribe((state) => {
      expect(state.testKey.counter).toBe(counter);
    });
  }

  setAndGet(1); // <------------------------------------------------ passes

  backingStore.pipe(take(1)).subscribe(() => {
    setAndGet(2); // <---------------------------------------------- passes
  });

  backingStore
    .pipe(
      skip(1),
      take(1),
    )
    .subscribe(() => {
      setAndGet(4); // <--------------------------------------------- fails
    });
  backingStore.dispatch({ type: "set", counter: 3 });
});
```

## Expected behavior:

I expect `setAndGet` to either always pass or always fail. Having the behavior depend on when it is called leads to surprising and hard to find bugs. Personally, I thought it would always pass.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

NgRx: 8.3.0
Angular: 8.2.4
Node: n/a
browser: n/a

## Other information:

It seems that `dispatch` will trigger reducers synchronously in most cases. But if called within a subscriber that is reacting to a state change, it is queued up to run later.

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[X] No

**Comment by eric-simonton-sama** [comment]
We've been using `@ngrx/store` for quite a while on my team (wrapped with [`ng-app-state`](https://github.com/simontonsoftware/ng-app-state)), so I'm surprised that we're just now running into this. We just hit another snag that traces back to this (sometimes) asynchronous behavior.

I'm eager to hear any thoughts about this from the ngrx team before I start thinking about rearchitecting or workarounds.

**Comment by timdeschryver** [comment]
Correct, correct me if I'm wrong but what you're seeing is because we're [using a queueScheduler](https://github.com/ngrx/platform/blob/master/modules/store/src/state.ts#L32).

We also have [a spec](https://github.com/ngrx/platform/blob/master/modules/store/spec/edge.spec.ts) for this specific behavior.

I expect this to be the desired result, but I'm not 100% sure.

**Comment by eric-simonton-sama** [comment]
Thank you for looking at this.

I'm not familiar enough with ngrx internals to know if the `queueScheduler` explains the behavior, I'm sorry to say. I could try to experiment with that tomorrow if it would be helpful.

The intent of that spec you linked seems to be to ensure one can dispatch an event while handling another event. It does not seem to specifically test that it synchronous at times, and other times asynchronous. Is there a reason that would be desired?

**Comment by BioPhoton** [comment]
Hi @ersimont 

I started to analyze the code. As some things are not at the top of my head now you have to insert some console.logs to check which of my assumptions are correct and then go on with the given process of analyzing.

Here something that you can use as a starter document. I hope it helps!


Your code with line numbers:
```typescript 
1.  backingStore.addReducer("testKey", (state: any, action: any) => ({
2.     ...state,
3.     counter: action.counter,
4.  }));
5.  
6.  function setAndGet(counter: number) {
7.      backingStore.dispatch({ type: "set", counter });
8.      backingStore.pipe(take(1)).subscribe((state) => {
9.          expect(state.testKey.counter).toBe(counter);
10.    });
11. }
12.
13.  setAndGet(1); // <------------------------------------------------ passes
14.
15.  backingStore.pipe(take(1)).subscribe(() => {
16.    setAndGet(2); // <---------------------------------------------- passes
17.  });
18.
19.  backingStore
20.    .pipe(
21.      skip(1),
22.      take(1),
23.    )
24.    .subscribe(() => {
25.      setAndGet(4); // <--------------------------------------------- fails
26.    });
27.  backingStore.dispatch({ type: "set", counter: 3 });
```


Order of execution:
0. `StateObservable`, `ActionsSubject`, `ReducerManager` get instantiated.
  0.1.`ActionsSubject` dispatches `{ type: INIT }` action.
   0.2. `ReducerManager` emit initial state
   0.3. Services `Store`,  gets initiated
   0.4. new Store<R> gets created out of `ReducerManager`
https://github.com/ngrx/platform/blob/59a9e6c77f627fcd75f8d00dfc9e6b7f05314989/modules/store/src/store.ts#L78
  0.5. Reducer reemits last value

1. Function hoisting. The `setAndGet` is now reachable and sits at the top of the file.
 ```typescript
6.  function setAndGet(counter: number) {
7.      backingStore.dispatch({ type: "set", counter });
8.      backingStore.pipe(take(1)).subscribe((state) => {
9.          expect(state.testKey.counter).toBe(counter);
10.    });
11. }
```

2. `backingStore` gets Reducer added

 ```typescript
1.  backingStore.addReducer("testKey", (state: any, action: any) => ({
2.     ...state,
3.     counter: action.counter,
4.  }));
```
3. `setAndGet` is called with param `1`. This executes synchronously.
```typescript
13.  setAndGet(1); // <------------------------------------------------ passes
```
4. `dispatch` is called. This executes synchronously.
 ```typescript
7.      backingStore.dispatch({ type: "set", 1});
```
5. The `ActionsSubject` dispatches it's value.  This executes synchronously.

https://github.com/ngrx/platform/blob/59a9e6c77f627fcd75f8d00dfc9e6b7f05314989/modules/store/src/store.ts#L84-L86

6. This sends an action to the State instance of Store.
https://github.com/ngrx/platform/blob/59a9e6c77f627fcd75f8d00dfc9e6b7f05314989/modules/store/src/state.ts#L32-L34
There it gets queued over a macro task (setInterval).
https://github.com/ReactiveX/rxjs/blob/master/src/internal/scheduler/QueueScheduler.ts#L3
https://github.com/ReactiveX/rxjs/blob/master/src/internal/scheduler/AsyncScheduler.ts#L58
https://github.com/ReactiveX/rxjs/blob/master/src/internal/scheduler/AsyncAction.ts#L73

The macro task stack for the `State` instance `ActionsSubject` looks like that:
1.1. process action  `{ type: "set", `1}`

7. `backingStore.pipe(take(1)).subscribe` is called. This happens synchronously.
 ```typescript
8.      backingStore.pipe(take(1)).subscribe((state) => {
9.           // observer callback here
10.    });
```

8.  `backingStore.pipe(take(1)).subscribe` is called again.  This happens synchrounously.
  
 ```typescript
15.  backingStore.pipe(take(1)).subscribe(() => {
16.     // observer callback here
17.  });
```

9.  `backingStore.pipe(  skip(1),take(1)).subscribe` is called. 
This happens synchronously.

 ```typescript
19.  backingStore
20.    .pipe(
21.      skip(1),
22.      take(1),
23.    )
24.    .subscribe(() => {
25.       // observer callback here
26.    });
```
10. `dispatch` is called. This sends an action to the `State` instance;

 ```typescript
27.  backingStore.dispatch({ type: "set", counter: 3 });
```

The macrotask stack for the `State` instance `ActionsSubject` looks like that:
1.2. process action  `{ type: "set", counter: 3 }`
1.1.  process action  `{ type: "set", `1}`


All synchronous code is processed.

---

11. Macrotask 1.1 gets processed. `State` updates and emits `{counter: 1}` as new state
12. The call back from line 9. executes. This happens synchronously. 
```typescript
9.  expect({counter: 1}).toBe(1);  // <---------------- passes
```
13. The call back from line 16. executes.  This happens synchronously.

```typescript
16.    setAndGet(2); 
```

17. `setAndGet` is called with param `2`. This executes synchronously.
18. `dispatch` is called. This executes synchronously.
 ```typescript
7.      backingStore.dispatch({ type: "set", 2});
```
19. The `ActionsSubject` dispatches it's value.  This executes synchronously.
20. This sends an action to the State instance of Store which queues it as a macro task.
The macrotask stack for the `State` instance `ActionsSubject` looks like that:
2.1.  process action  `{ type: "set", `2}`
1.2. process action  `{ type: "set", counter: 3 }`


21. `backingStore.pipe(take(1)).subscribe` is called. This happens synchronously.
 ```typescript
8.      backingStore.pipe(take(1)).subscribe((state) => {
9.           // observer callback here
10.    });
```
22. The store emits it's last emitted value =>  ` {counter : 1}`
Then it completes.
 ```typescript
    backingStore.pipe(take(1)).subscribe(
    // observer callback here
   );
```

**Comment by BioPhoton** [comment]
Furthermore, here a demo to understand the scheduling behavior:
https://stackblitz.com/edit/rxjs-notification-reentrance

**Comment by ersimont** [comment]
Thank you for looking at this. You came up with slightly different behavior than I remember. Specifically, I didn't think any macro tasks were being scheduled. Trying to google around about `queueScheduler`, it seems it doesn't try to use the macro task. I suspect it is the root of the behavior I'm seeing, but documentation seems sparse so that's harder to verify.

@timdeschryver How do you see this proceeding? Do you think there's anything to fix/change here w/ ngrx? Or maybe an option to specify whether to use a scheduler, or something?

**Comment by brandonroberts** [comment]
I think we will keep the behavior as is for now

**Comment by BioPhoton** [comment]
> I think we will keep the behavior as is for now

Yes definitely! The queue scheduler thing is kinda avoiding an antipattern, but I created the local state thing without it and the 3rd person using i ran into the problem.

IMHO the current behavior and the usage of queueScheduler is perfect.

**Comment by eric-simonton-sama** [comment]
I'm interested to hear what y'all's thoughts are on the issue it is causing me. An unforunate, necessary evil to avoid worse problems if you change it? Or is what I'm observing actually desirable in itself for some reason?
