### ISSUE TITLE
[Bug] @ngrx/data additionalCollectionState selectors not allowed by typings

### ISSUE THREAD

**Issue by luchillo17** [ngrx/platform#2324]
## Expected behavior:

Typings should allow to call the custom selectors created for additionalCollectionState props in EntityMetadata.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
Ngrx: 8.6.0
Angular: 8.3.2
Node: 12.12.0
Browser: Any
OS: Windows (presumably any, typings issue)

## Other information:
Here's my custom additionalCollectionState:
![image](https://user-images.githubusercontent.com/9698639/72703646-1e36f100-3b24-11ea-97d3-3fabbd05ade9.png)

Here's what should be possible but typings scream at me:
![image](https://user-images.githubusercontent.com/9698639/72703736-5fc79c00-3b24-11ea-9561-d4a30f630b1e.png)

Selectors in question should be generated in this lines:
https://github.com/ngrx/platform/blob/master/modules/data/src/selectors/entity-selectors.ts#L208-L229
https://github.com/ngrx/platform/blob/master/modules/data/src/selectors/entity-selectors%24.ts#L111-L123
https://github.com/ngrx/platform/blob/master/modules/data/src/entity-services/entity-collection-service-base.ts#L48-L60

## I would be willing to submit a PR to fix this issue

* [x] Yes (Assistance is provided if you need help submitting a pull request)
* [ ] No

**Comment by luchillo17** [comment]
Ping @brandonroberts @alex-okrushko mind if i do a PR for this? not that hard to allow random named selectors in there, though it would use `Observable<any> | Store<any>` and dev would have to cast it to get the specific type of that property.

**Comment by luchillo17** [comment]
Funny thing is `CollectionSelectors<T>` does have what it needs to allow the selectors themselves, but `EntitySelectors$<T>` is the one missing one alike:
![image](https://user-images.githubusercontent.com/9698639/72859225-09c43700-3c91-11ea-9c66-a7aa1fb42303.png)

**Comment by brandonroberts** [comment]
@luchillo17 seems reasonable to me.

**Comment by wardbell** [comment]
LGTM

**Comment by luchillo17** [comment]
Should we close it or once we get a release?

**Comment by brandonroberts** [comment]
We'll close it, and it will go with the next release. Thanks luchillo17!
