### ISSUE TITLE
Rename entity addAll to replaceAll

### ISSUE THREAD

**Issue by elvisun** [ngrx/platform#2330]
## Describe any alternatives/workarounds you're currently using
This is what `addAll` documentation says:
```
addAll: Replace current collection with provided collection
```
Then this really should be called `replaceAll` so people know their existing entities are being removed.

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by elvisun** [comment]
@alex-okrushko

**Comment by alex-okrushko** [comment]
Yeah, we had a case where `addAll` was used by accident instead of `addMany` and that lead to hours of debugging 😵

**Comment by alex-okrushko** [comment]
Maybe alias `replaceAll` to `addAll` and depreciate it?
`removeAll` can also be renamed to `clearAll`, but it's less error-prone, I think.

**Comment by PsychoPflanze** [comment]
I don't know, i like `addAll` 😢 . Or at least don't use `replaceAll` but `setAll` instead, makes it easier to write 👍

**Comment by timdeschryver** [comment]
👍 for `setAll` if we're going to rename this.

**Comment by alex-okrushko** [comment]
@brandonroberts @MikeRyanDev any thoughts on this? It wasn't the first time 🕵️‍♀️

**Comment by brandonroberts** [comment]
Sounds good to me. Let's introduce the new one, and deprecate the old one.
