### ISSUE TITLE
Fix loadCollection action in example app to fit good actions hygiene 

### ISSUE THREAD

**Issue by Liovareg** [ngrx/platform#2334]
## Context
We are discussing implementing Good Actions Hygiene from @MikeRyanDev in our project and found one place in example app that seems does not fit this pattern.

Here is the place: https://github.com/ngrx/platform/blob/master/projects/example-app/src/app/books/containers/collection-page.component.ts#L43

It's a common practice to dispatch some action in component's onInit. So, from actions-like-events standpoint type should be something like "[Collection Page] Initialization" (event from component, no idea how store will handle this event), but in example it sounds more like a command: "[Collection Page] Load Collection" (command to store what to do).

## Proposal
So, proposal is to fix loadCollection action to be collectionPageInitialization (or Init ?) with type "[Collection Page] Initialization".

Is that a right naming in such cases? 

Would be happy to add pr.

## If accepted, I would be willing to submit a PR for this feature

[X] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
I think `[Collection Page] Enter` would fit there
