### ISSUE TITLE
[@ngrx/data] - wrong type of filter$

### ISSUE THREAD

**Issue by b-shanovskyi-andersen** [ngrx/platform#2337]
## Minimal reproduction of the bug/regression with instructions:

In EntityCollectionServiceBase:

```
/** Observable of the filter pattern applied by the entity collection's filter function */
filter$: Observable<string> | Store<string>;
```

But filter can have `any` type:
```
/**
  * Set the pattern that the collection's filter applies
  * when using the `filteredEntities` selector.
  */
setFilter(pattern: any): void;
```

## Expected behavior:

```
filter$: Observable<any> | Store<any>;
```

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[X] No

**Comment by santoshyadav198613** [comment]
Hi @timdeschryver/ @brandonroberts  ,
I will work on it.
