### ISSUE TITLE
Data: testing and helpers

### ISSUE THREAD

**Issue by Nosfistis** [ngrx/platform#2340]
While there is a nice effort to simplify and assist testing of components using store, via `store/testing` package, I think that the data package also has significant effort and difficulty to mock, especially for unit tests.

It would certainly be nice to have a testing module, accepting some entity metadata and providing mock entity services, with spies/Subjects replacing normal properties.

Currently the easiest approach I have found is having a setup similar to
https://github.com/ngrx/platform/blob/3a9ad636099169afffcd78defe3b9ed98e4a8f8d/modules/data/spec/entity-services/entity-collection-service.spec.ts#L458

but I was thinking of a shallower level of mocking.

## I would be willing to submit a PR for the docs :heart:

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

**Comment by ianjamieson** [comment]
In case it helps anyone I have a (non working0 StackBlitz setup to attempt to be able  to test my CustomDataService (I wanted to build an integration test that would mock my Backend service but then use the EntityData module and resolvers

https://stackblitz.com/edit/ngrxdata-testing-not-working-pxfmkb?file=src/main.ts
