### ISSUE TITLE
Need a separate local storage by angular base url 

### ISSUE THREAD

**Issue by kushal-azilen** [ngrx/platform#2344]
![image](https://user-images.githubusercontent.com/30619709/73590219-efe2e980-4505-11ea-8411-02bab271a8a2.png)

**Comment by timdeschryver** [comment]
NgRx does nothing with localstorage.
Open up a question on stackoverflow or the gitter channel with more information and a reproduction, so we can help you.

Support questions should be asked on [stackoverflow (with a ngrx tag)](https://stackoverflow.com/questions/tagged/ngrx) or the [gitter channel](https://gitter.im/ngrx/platform).
