### ISSUE TITLE
Is there any way to stop auto sorting by id?

### ISSUE THREAD

**Issue by sharozmirza** [ngrx/platform#2358]
My model has an `id` field and the adapter is sorting the HTTP response array by id automatically. I would like to know how I can stop it.

Here is my adapter:
`const adapter: EntityAdapter<SampleModel> = createEntityAdapter<SampleModel>();`

and here is the reducer:
```
adapter.addMany(action.payload.samples, {
                ...initialSamplesState,
                totalCount: action.payload.totalCount,
                listLoading: false,
                lastQuery: action.payload.page,
                showInitWaitingMessage: false
            });
```

**Comment by brandonroberts** [comment]
@sharozmirza the default adapter behavior is to leave the list unsorted. If you need further support, see the [gitter channel](https://gitter.im/ngrx/platform)
