### ISSUE TITLE
Navigation without pushing a new state into history

### ISSUE THREAD

**Issue by aamir1995** [ngrx/platform#236]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[*] Support request
</code></pre>

**How to Navigate without pushing a new state into history or What is the equivalent of `show` in `ngrx 4x`?**

**Comment by brandonroberts** [comment]
The [migration docs](https://github.com/ngrx/platform/blob/master/MIGRATION.md#navigation-actions) have an example of how to do this. Just add `skipLocationChange: true` to the `extras` object

**Comment by aamir1995** [comment]
@brandonroberts Thanks.
