### ISSUE TITLE
MockStore selectors resulting in warning logs

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#2363]
## Minimal reproduction of the bug/regression with instructions:

Currently all the tests that use a mockstore with mocked selectors, [will log the warning that the state does not exists](https://github.com/ngrx/platform/blob/master/modules/store/src/selector.ts#L618).

This is normal because when we define a mocks store, we don't define the state object.

## Expected behavior:

It should not be logged while running tests.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

Angular 9
NgRx 9-beta.1

## Other information:

AFAIK, it isn't possible to detect when we run in a test environment.
But we could set a property on the state (`__ngrxMockEnvironment__`), and the `createFeatureSelector` could use this property to check if it the warning has to logged or not.

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by evgenyfedorenko** [comment]
I can take this one.

**Comment by evgenyfedorenko** [comment]
@timdeschryver can you please give me the example of the test which produces that warning?

**Comment by timdeschryver** [comment]
@evgenyfedorenko the example tests log them, run

```
yarn test:example
```
