### ISSUE TITLE
[Ivy] @ngrx/store-devtools included in bundle in production mode

### ISSUE THREAD

**Issue by DmitriyIvanko** [ngrx/platform#2372]
## Minimal reproduction of the bug/regression with instructions:
import { StoreDevtoolsModule } from '@ngrx/store-devtools';

import { environment } from 'environments';

const STORE_DEV_TOOL_MAX_AGE = 25;

@NgModule({
  imports: [
   // other imports
    StoreDevtoolsModule.instrument({
      logOnly: environment.production,
      maxAge: STORE_DEV_TOOL_MAX_AGE,
    }),
  ],
})
export class AppModule { }

![image](https://user-images.githubusercontent.com/18007391/74342970-62cc4a00-4dbb-11ea-8406-c92f7a2ec3fb.png)

## Expected behavior:
Not included in bundle in production mode;

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

    "@ngrx/effects": "^8.6.0",
    "@ngrx/entity": "^8.6.0",
    "@ngrx/store": "^8.6.0",
    "@ngrx/store-devtools": "^8.6.0",

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.1
Node: 12.14.1
OS: win32 x64

Angular: 9.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              8.0.0
@angular-devkit/schematics        8.0.0
@angular/cli                      9.0.1
@ngtools/webpack                  9.0.1
@schematics/angular               8.0.0
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

**Comment by timdeschryver** [comment]
See the [docs](https://ngrx.io/guide/store-devtools/recipes/exclude) on how to exclude devtools from a production build.
