### ISSUE TITLE
AngularInDepth link in ngrx/resources is broken

### ISSUE THREAD

**Issue by cjkumaresh** [ngrx/platform#2377]
The **AngularInDepth** link in [https://ngrx.io/resources](https://ngrx.io/resources) is broken. It should be updated to this new link [https://admin.indepth.dev/tag/ngrx/](https://admin.indepth.dev/tag/ngrx/)
## I would be willing to submit a PR for the docs :heart:

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by santoshyadav198613** [comment]
Hi @cjkumaresh, 

It should be https://indepth.dev/tag/ngrx/, just wait for sometime, I will get it checked with team why this URL gives 404. So you can get it changed.

**Comment by cjkumaresh** [comment]
@santoshyadav198613 Sure

**Comment by santoshyadav198613** [comment]
Hi @cjkumaresh, 
The URL is https://indepth.dev/ngrx/.
Thanks for bringing this up, if you are interested you can change the URL in Angular repo as well.
