### ISSUE TITLE
@ngrx/store mutating object from selector mutates the store

### ISSUE THREAD

**Issue by talohana** [ngrx/platform#2382]
## Minimal reproduction of the bug/regression with instructions:
Reproduction in [this stackblitz](https://stackblitz.com/edit/ngrx-8-playground-uzkppa?file=src%2Fapp%2Fapp.component.ts)

In `ngOnInit` I select a slice from the store, mutates it and after 1 second logging the mutated state.

## Expected behavior:
Correct me if i'm wrong, but I expected the store or the selector return some kind of cloned data, so mutations outside of the `reducer` function won't affect the state.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
angular: 9.0.0
@ngrx/store: 8.6.0

## I would be willing to submit a PR to fix this issue

[X] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by cjkumaresh** [comment]
@talohana Can you enable the runtime checks in root module and confirm ? [runtime checks](https://ngrx.io/guide/store/configuration/runtime-checks) 

e.g.
`StoreModule.forRoot(reducers, {
      runtimeChecks: {
        strictStateImmutability: true,
        strictActionImmutability: true
      }
    }),`

**Comment by talohana** [comment]
> @talohana Can you enable the runtime checks in root module and confirm ? [runtime checks](https://ngrx.io/guide/store/configuration/runtime-checks)
> 
> e.g.
> `StoreModule.forRoot(reducers, { runtimeChecks: { strictStateImmutability: true, strictActionImmutability: true } }),`

Yup that solves it, somehow I forgot about this option..
Thank you!
