### ISSUE TITLE
Bringing in Temp Solution for Store-Freeze

### ISSUE THREAD

**Issue by PhillipZada** [ngrx/platform#240]
Hey,

I was trying to get store-freeze working in a dev environment thought it might be handy to bring it into this project as standard middle-ware as it is widely used. 

The solution I have below caters for the current router problem and ignores said feature state until the router state issues are resolved. And is based on ngrx-store-freeze and redux-freeze code.

Please let me know your thoughts and would be happy to submit as a pull request, otherwise I can also create it in its own repo and publish to npm.

```
import { ActionReducer } from '@ngrx/store';
import * as deepFreeze from 'deep-freeze-strict';

/**
 * Middleware that prevents state and action payload from being mutated anywhere in the app.
 */
export function storeFreeze<T>(reducer: ActionReducer<T>): ActionReducer<T, any> {
    return function (state: T, action: any): T {

        freezeState(state);

        if (!action.type.startsWith('ROUTER')
            && action.payload
            && isFreezable(action.payload)) {
            deepFreeze(action.payload);
        }

        const nextState = reducer(state, action);
        freezeState(nextState);
        return nextState;

    };
}

function freezeState(state) {
    if (isFreezable(state)) {

        // Allow us to still use store freeze but ignore the router state
        for (const prop in state) {
            if (prop !== 'router') {
                deepFreeze(state[prop]);
            }
        }

    }
}

function isFreezable(value) {
    return value !== null && typeof value === 'object';
}

```

**Comment by PhillipZada** [comment]
Also forgot to ask what are your opinions on freezing the payload? i.e. 

```

        if (!action.type.startsWith('ROUTER')
            && action.payload
            && isFreezable(action.payload)) {
            deepFreeze(action.payload);
        }

```

I've found that if I freeze the payload then it becomes harder to build the state in the reducer.

**Comment by DorianGrey** [comment]
For reference - the update issue in the ngrx-store-freeze repository: https://github.com/codewareio/ngrx-store-freeze/issues/17

**Comment by PhillipZada** [comment]
Thanks @DorianGrey, there didn't seem to be any activity in that repo for a while so I thought to bring it in house.

**Comment by DorianGrey** [comment]
Already discussed a solution like this:
https://github.com/codewareio/ngrx-store-freeze/issues/17#issuecomment-317528883
However, the downside is that it does not allow to configure a custom name (here: `router`) for the router reducer in the state. I've attempted to make this configurable somehow, but wasn't able to get it working with AoT (the infamous `Function calls are not allowed` thing...).

**Comment by DorianGrey** [comment]
I can confirm that ngrx-store-freeze works fine in case a `RouterStateSerializer` is used (possible with `@ngrx/router-store` >= 4.0.3).
Just tested this one:
```
export class CustomRouterStateSerializer
  implements RouterStateSerializer<CustomRouterStateInfo> {
  serialize(routerState: RouterStateSnapshot): CustomRouterStateInfo {
    const url = routerState.url;
    return {
      url,
      params: routerState.root ? routerState.root.params : {},
      queryParams: routerState.root ? routerState.root.queryParams : {}
    };
  }
}
```
Things seem to work as expected.
