### ISSUE TITLE
RFC @ngrx/data - general route guards / resolvers

### ISSUE THREAD

**Issue by AdditionAddict** [ngrx/platform#2415]
NgRx Data maintains a `loaded` state for each entity and provides a `EntityServices` that can load a `CollectionService` based on a string of the `entityName`. This provides the basics for general route guards / resolvers.

Is there interest in adding general routing guards / resolvers as a feature to ngrx data?

## Describe any alternatives/workarounds you're currently using

It's a bit basic but as an example I'm using the following routing canActivate guard which prevents loading route until `loaded` state is true calling `service.getAll()` if not. 

Used as 
```
    canActivate: [
      EntityLoadedService.forEntities(["GeneralEmployee", "Mould", "Project"])
    ]
```
```
import { Injectable } from "@angular/core";
import { Observable, forkJoin } from "rxjs";
import { tap, filter, take, map } from "rxjs/operators";
import { EntityServices } from "@ngrx/data";

/**
 * 
 * Based on https://stackoverflow.com/a/44285913/4711754
 * 
 * `forEntities`
 *    Generates a guard class based on passed
 *    entities string array
 */
@Injectable({ providedIn: "root" })
export class EntityLoadedService {
  /** keep guards to use in provided */
  public static guards = [];

  static forEntities(entities: string | string[]) {
    /** Create guard class based on entity name(s)  */
    @Injectable({ providedIn: "root" })
    class EntityLoadedGuard {
      constructor(private entityServices: EntityServices) { }

      canActivate(): Observable<boolean> {
        if (Array.isArray(entities)) {
          const loadedArray: Observable<boolean>[] = entities.map(entityName =>
            this.entityLoaded(entityName)
          );

          return forkJoin(loadedArray).pipe(
            // check every entity loaded
            map(loadedArray => loadedArray.every(v => v))
          );
        }
        return this.entityLoaded(entities as string);
      }

      /**
       * Gets the entity collection service
       * Checks if entity is loaded
       * Calls getAll if not
       * Filters stream until it emits true
       * @param entityName
       */
      entityLoaded(entityName: string): Observable<boolean> {
        /** Load service based on {entityName} */
        const service = this.entityServices.getEntityCollectionService(
          entityName
        );

        return service.loaded$.pipe(
          tap((loaded: boolean) => {
            if (!loaded) {
              console.log(`💂‍♂️💂‍♂️ ${entityName} Guard - QUERY_ALL`);
              service.getAll();
            }
          }),
          filter(loaded => loaded),
          take(1)
        );
      }
    }

    EntityLoadedService.guards.push(EntityLoadedGuard);
    return EntityLoadedGuard;
  }
}
```
## If accepted, I would be willing to submit a PR for this feature

[ x ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by AdditionAddict** [comment]
Closed for lack of interest, like to reopen

**Comment by alex-okrushko** [comment]
@AdditionAddict thanks for feature suggestion. Many of the core contributors are not using `data` in their day-to-day work (we were building project with _raw_ NgRx for a long time), so it's harder to relate and evaluate if this actually a feature that solves problems for `data` users.
As I see it, the best way to check for interest would be to tag @wardbell and maybe @SerkanSipahi with @JiaLiPassion who are known users.

**Comment by wardbell** [comment]
Hi @AdditionAddict 

You raise an interesting question. Now I really DO use Ngrx Data in my daily work and I have guards that are like the one you describe. So I feel the need that you are expressing.

But I'm not convinced that we have an abstraction that works for everyone. It might be OK for the happy path, when the data for all source load successfully.

Where this breaks down, for me, is _What happens when the load fails?_  What should you do? How should you communicate with the user? How long should I wait before giving up? Where would I navigate to if it fails?  Wouldn't that depend upon why it fails? Not the same if failed because not authorized or simply lost connection.

I think that we're not ready to abstract this. Maybe you can convince me otherwise? I'm listening.

**Comment by hoang-innomizetech** [comment]
Between entity collection and entity item, what if the user fetches the single entity but not fetch the list. For example, they enter the URL and go to the edit/view page and then come back to the list (option). Should we fetch the collection or not?

**Comment by AdditionAddict** [comment]
> 
> 
> Between entity collection and entity item, what if the user fetches the single entity but not fetch the list. For example, they enter the URL and go to the edit/view page and then come back to the list (option). Should we fetch the collection or not?

@hoang-innomizetech 

You don't fetch collection you use guard / resolver that checks `id` is in the cache, similar to following:
```
@Injectable({
  providedIn: "root"
})
export class GetIdGuard<T> implements CanActivate {
  constructor(private service: SomeService) {}

  canActivate(route: ActivatedRouteSnapshot) {
    return this.checkStore().pipe(
      switchMap(() => {
        const id = route.params.id;
        return this.hasItem(id);
      })
    );
  }

  hasItem(id: string): Observable<boolean> {
    return this.service.entityMap$.pipe(
      map((entities: { [key: string]: T}) => !!entities[id]),
      take(1)
    );
  }

  checkStore(): Observable<boolean> {
    return this.service.loaded$.pipe(
      tap((loaded: boolean) => {
        if (!loaded) {
          this.service.getAll();
        }
      }),
      filter(loaded => loaded),
      take(1)
    );
  }
}
```

**Comment by hoang-innomizetech** [comment]
@AdditionAddict Actually, I am not a fan of using resolver for the collection container component. So if we have a way to custom the effect for a given EntityOp that would be great.

By the way, in relation to my previous concern about how to define and add custom actions (or Entity Op). Do you have any guidelines or ideas? Right now I am stuck on the EntityOp, it isn't extendable.
