### ISSUE TITLE
example-app - is removeBookFailure reducer correct?

### ISSUE THREAD

**Issue by AdditionAddict** [ngrx/platform#2417]
Basically this SO post https://stackoverflow.com/questions/60417722/ngrx-handle-api-failure

Should line below be removed given it has no effect / should `removeBook` optimistically remove the book?
Happy to create PR whichever way

```
on(
    CollectionApiActions.addBookSuccess,
    CollectionApiActions.removeBookFailure, <-------------------
    (state, { book }) => {
      if (state.ids.indexOf(book.id) > -1) {
        return state;
      }
      return {
        ...state,
        ids: [...state.ids, book.id],
      };
    }
  ),
```

## If accepted, I would be willing to submit a PR for this feature

[ x ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
This does seem weird.

I expect it to revert the removal of a book if the API call failed.
What is missing from the example app is the removal of the book in the collection when the `removeBook` action is dispatched.

The same counts for the `addBook` and `addBookFailure`  actions.
