### ISSUE TITLE
Entities updateOne documentation inaccurate?

### ISSUE THREAD

**Issue by kameelyan** [ngrx/platform#2431]
Attempt to use entities, I had an updateOne method call that was extremely simple and followed the documentation almost to a T:

https://ngrx.io/guide/entity/adapter
adapter.updateOne(user, state)

However, I found that it wasn't updating my data. After some searching, I found some examples where users were passing an object with "id" and "changes". Updated my code, and viola! It started working. 

Is the documentation wrong here?

## I would be willing to submit a PR for the docs :heart:
[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x ] No

**Comment by AdditionAddict** [comment]
@kameelyan what version are you using? The api changed between versions

**Comment by kameelyan** [comment]
@AdditionAddict 8.6

**Comment by timdeschryver** [comment]
@kameelyan what do you do to make your code work? 
And how can we make the docs better, so that it will be clear for the next person.

**Comment by AdditionAddict** [comment]
@kameelyan sorry, I was thinking of `upsertOne` (whose api has changed). Yes, api for `updateOne` is an `Update<t>` supporting partial updates.

Docs are correct...if you look at the props type for the `updateUser` action it's `props<{ user: Update<User> }`.

Should this be `props<{ update: Update<User> }` to make this clearer?

**Comment by kameelyan** [comment]
Thanks @AdditionAddict, I see that now!

 I think this could be made more clear @timdeschryver by either changing the property name "user" in the reducer, or by adding a comment. Right now it looks like the reducer variable user for upsertUser is the same as updateUser if you just look at the reducer first, not looking at any of the actions.

My personal use case was that I was familiar enough with ngrx to look at the documentation of just the reducer, see a pattern emerge and make some assumptions (which were wrong of course).

Definitely appreciate the quick response!
