### ISSUE TITLE
Docs: Missing v8 from https://ngrx.io/docs

### ISSUE THREAD

**Issue by jonstelly** [ngrx/platform#2435]
The [documentation site](https://ngrx.io/docs) has a version selection dropdown that has (v4, v5, v6, v7, v9, next).  v8 is missing from the list.

## I would be willing to submit a PR for the docs :heart:

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

**Comment by timdeschryver** [comment]
Thanks for raising this issue @jonstelly !
