### ISSUE TITLE
Docs: Use async method when testing effects without TestBed

### ISSUE THREAD

**Issue by MrCube42** [ngrx/platform#2449]
# Background
I decided to test my effects without using the Angular TestBed because this should be faster then using the entire TestBed when I only want to test the effect in isolation (https://ngrx.io/guide/effects/testing#setup-without-testbed). I am using [Jest](https://jestjs.io) as test runner.

# Repro-Steps
Consider this simplified, generic approach I used.
```ts
  it('should get data on success', () => {
    // Arrange.
    const sampleData = { ... }
    const serviceMock = {
      getMyData: jest.fn().mockReturnValue(of(sampleData)),
    };

    const actions$ = new Actions(
      of(loadData({ id: 42 })),
    );

    const effects = new MyEffects(actions$, serviceMock);

    // Act.
    effects.loadData$.subscribe(action => {
      // Assert.
      expect(action).toEqual(
        loadDataSuccess({ data: sampleData }),
      );
    });
  }));
```

# What's the problem?
Unfortunately the test is green, however the coverage showed me that it is not executed properly. This is due to two problems:
- The jest.fn() call does not execute anything and is wrong. This is an error from my side.
- However, in this case we want to **see that an error occurs and the test should fail**.

# How to fix it? What do change?
If the test itself was run inside of `async`, then we would know that actually the service's `getMyData` has never been called because of the wrong implementation of the mock.

The [docs ](https://ngrx.io/guide/effects/testing#setup-without-testbed) may propose to wrap the async test into the `async` method call like this:

```ts
  it('should get data on success', async(() => { ...
```

# Side Note
The test itself can than be fixed by don't mocking out the call by jest, but letting it go through.

Instead of using this:
```ts
getMyData: jest.fn().mockReturnValue(of(sampleData)),
```

We must use this:
```ts
getMyData: jest.fn(() => of(sampleData)),
```

## I would be willing to submit a PR for the docs :heart:

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
@MrCube42 what are you proposing in terms of docs, as we don't have any Jest-specific examples in the testing guide.

**Comment by MrCube42** [comment]
**To summarize, my proposal is**: Adding the `async()` wrapper from `@angular/core/testing` to the test example `my.effects.spec.ts` in the docs because of the asynchronous nature of this effects test.

---

I tried to reproduce the scenario with standard Jasmine/Karma setup of Angular.
Consider the following test:

```ts
it('should get data on success', () => {
  // Arrange.
  const sampleData = ['foo', 'bar'];
  spyOn(serviceMock, 'getMyData'); // <- This is en error. Missed to provide a mock implementation

  const actions$ = new Actions(of(loadData({ id: 42 })));

  const effects = new DataEffects(actions$, serviceMock);

  // Act.
  effects.loadData$.subscribe((action) => {
    // Assert.
    expect(action).toEqual(loadDataSuccess({ data: sampleData }));
  });
});
```

In this case, the test is green and the error due to the missing mock implementation of the `getMyData` function is shown in the console:
![image](https://user-images.githubusercontent.com/1512210/79042204-eb1d6e80-7bf5-11ea-8a9c-fe14d81057ef.png)

Only looking at the console or the code coverage reveals that there is an error in the test itself.

However, if we would wrap the test function in an **async**hronous test zone, we would receive the error during the test run and the test would actually fail:

`it('should get data on success', async(() => { ... }))`
![image](https://user-images.githubusercontent.com/1512210/79042251-42234380-7bf6-11ea-8fae-5ee36f0ac2a8.png)

In the end, this would be more fail safe. I am not 100% sure, but I suppose the test would formally be more correct if it is wrapped into the async zone because of the existing subscription.
