### ISSUE TITLE
Navigation missing link to Selector Schematic 

### ISSUE THREAD

**Issue by REDDJF** [ngrx/platform#2454]
[Selector schematics doc ](https://github.com/ngrx/platform/blob/master/projects/ngrx.io/content/guide/schematics/selector.md) is missed off of the [nav](https://github.com/ngrx/platform/blob/master/projects/ngrx.io/content/navigation.json) 

## I would be willing to submit a PR for the docs :heart:

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Thanks for creating this issue @REDDJF 
Feel free to open a PR if you want

**Comment by Dilski** [comment]
@timdeschryver Here we go: #2459 
Hope i've interpreted the contributing guidelines properly ^^
