### ISSUE TITLE
ngrx data not compiling in ng 7.2.0 project

### ISSUE THREAD

**Issue by sergeysatori** [ngrx/platform#2464]
## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
```
 "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "@ngrx/data": "^9.0.0",
    "@ngrx/effects": "^7.4.0",
    "@ngrx/entity": "^9.0.0",
    "@ngrx/store": "^7.4.0",
    "@ngrx/store-devtools": "^9.0.0",
   ```
## Other information:
```

node_modules/@ngrx/data/src/selectors/entity-selectors.d.ts(77,163): error TS2694: Namespace '"...../node_modules/@ngrx/store/store"' has no exported member 'DefaultProjectorFn'.

```
## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ x] No

**Comment by timdeschryver** [comment]
It's best to keep the `@ngrx` packages on the same version (same counts for Angular).
Data has been migrated to an ngrx package in NgRx version 8, for earlier versions of data see https://github.com/johnpapa/angular-ngrx-data.
