### ISSUE TITLE
navigationActionTiming Alternatives

### ISSUE THREAD

**Issue by Hanawa02** [ngrx/platform#2465]
Right now the only possibilities for the navigationActionTiming is pre guards/resolver, or post guards/resolvers, in my application we cant use PostNavigation strategy because of offline functionalities, but for the canDeactivate guards the ideal is the PostNavigation, since some form data is lost when the navigation is done before the canDeactivate guards.

I would like to request an intermediate possibility, maybe 
PreNavigation
PostCanActivateGuardsNavigation
PostCanDeactivateGuardsNavigation
PostGuardsNavigation
PostResolversNavigation
PostNavigation 

or some additional configuration to the route itself, indicating what should be executed before navigating to/from the route.

I am still trying to find a okay workarounds for this

## If accepted, I would be willing to submit a PR for this feature
I didn't investigate the code fully to be able to implement the feature myself, but I could try if allowed.
[x] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

**Comment by brandonroberts** [comment]
Thanks @Hanawa02, I think listening to router events and populating the store within a separate reducer with what you need would be an option here, as opposed to providing too many options for when the navigation action is dispatched.

**Comment by brandonroberts** [comment]
Closing as non-actionable for now
