### ISSUE TITLE
Angular app cannot load when disable sideEffects

### ISSUE THREAD

**Issue by hoang-innomizetech** [ngrx/platform#2466]
We have applied the tree shaking feature of webpack by adding _sideEffects: false_ to the package.json file. After bundling the AOT build, the Angular app cannot load, it just display a blank page without any error. Does anyone encounter this issue and find out solutions to fix it?

Steps to replicate:
1. Generate latest angular app `ng new my-ivy-app`
2. Add @ngrx/store module and configure store `ng add @ngrx/store`
3. Build AOT build `ng build --prod`
4. Use http-server /dist -> now the app just display a blank page.

**Comment by timdeschryver** [comment]
Could you create a reproduction for this?
It seems to be working just fine here.

Also make sure you're in the dist folder, `./dist/project-name`.

**Comment by hoang-innomizetech** [comment]
@timdeschryver Sorry, this seems an issue of Angular itself, so I am closing this issue. Thank you for your attention.
