### ISSUE TITLE
No provider for MockStore

### ISSUE THREAD

**Issue by SpellChucker** [ngrx/platform#2468]
## Other information:

I am trying to setup testing using the store for one of my components and it seems that the `provideMockStore` function is not actually providing the `MockStore`. I have to also include `MockStore` in my providers.

I am unsure if this is expected (as the docs do not show this) or if I am implementing testing incorrectly.

The error I am getting is this:

```
Failed: R3InjectorError(CompilerModule)[MockStore -> MockStore]: 
NullInjectorError: No provider for MockStore!
```

However, if I add `MockStore` to the `providers` array, it works fine.

```
...
    TestBed.configureTestingModule({
      declarations: [
        LoginPage
      ],
      providers: [
        MockStore,
        provideMockStore()
      ]
    });
...
```

## I would be willing to submit a PR for the docs :heart:

[X] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Hi, what version of NgRx are you using?
This should be fixed in NgRx v9.

**Comment by SpellChucker** [comment]
You're right, thank you. Closing!
