### ISSUE TITLE
Ngrx/Data Trying to make a call similar to localhost/Access/UserPermissions/{appid}/{employeeId}

### ISSUE THREAD

**Issue by Godrules500** [ngrx/platform#2469]
How can I make a similar to localhost/Access/UserPermissions/{appid}/{employeeId} with ngrx/data?  GetAll won't let me modify the route
GetByKey expects one item to be returned so I get a "select id not implemented"
GetWithQuery expects a query selector.

So how can I make a call passing multiple parameters in the route?

**Comment by timdeschryver** [comment]
Support questions should be asked on [stackoverflow (with a ngrx tag)](https://stackoverflow.com/questions/tagged/ngrx) or the [gitter channel](https://gitter.im/ngrx/platform).

**Comment by Godrules500** [comment]
I did on both yesterday and haven't received an answer so I figured I would reach out here. I'll wait to see if it gets answered.

Thanks!
