### ISSUE TITLE
Change TestBed.inject(CollectionEffects) to TestBed.get(CollectionEffects)

### ISSUE THREAD

**Issue by epaitz** [ngrx/platform#2470]
https://github.com/ngrx/platform/blob/e30cbe2b9a89df85408432a98c19438f1b5d01e9/projects/example-app/src/app/books/effects/collection.effects.spec.ts#L54

I am very new to NgRx and I have been reading up on testing. Not that it matters but shouldn't

`TestBed.inject(CollectionEffects) `

 ...really be...

`TestBed.get(CollectionEffects)`

The CollectionEffects is already injected into the TestBed on line 30. Also I do not think you need to inject the Actions on line 55 either. I am not 100% sure about that but it works in my tests (different project) without that. 

Again I am very new to NgRX so I could be wrong but I wanted to just ask. This might have something to do with an Angular change?

**Comment by timdeschryver** [comment]
[TestBed.inject](https://angular.io/guide/testing#testbedinject) is used in Angular to get the instance of an injected service, in this example to retrieve the instance of `CollectionEffects`.

In Angular 9 `TestBed.get` got deprecated and got replaced with `TestBed.inject`
