### ISSUE TITLE
Using NgRx Data for non-CRUD operations

### ISSUE THREAD

**Issue by amina-ahmed** [ngrx/platform#2472]
Hi,

Could you guide me on how to use NgRx Data for non-CRUD operations like:

1.  Implementing and storing navigation between different pages?

2. Adding more methods to an entity service like sorting?

**Comment by brandonroberts** [comment]
Thanks @amina-ahmed, but these questions are better asked on the [gitter channel](https://gitter.im/ngrx/platform)
