### ISSUE TITLE
ng add @ngrx/store -> Unexpected token / in JSON at position 173

### ISSUE THREAD

**Issue by PooSham** [ngrx/platform#2478]
## Minimal reproduction of the bug/regression with instructions:

When I run `ng add @ngrx/store`, I get the following error: 

> Unexpected token / in JSON at position 173

and StoreModule is not added to my imports in the app module.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

Here's the output from `ng version` 

> Angular CLI: 9.0.1
> Node: 10.16.2
> OS: win32 x64
> 
> Angular: 9.0.0
> ... animations, cdk, common, compiler, compiler-cli, core, forms
> ... language-service, localize, platform-browser
> ... platform-browser-dynamic, router
> Ivy Workspace: Yes
> 
> Package                           Version
> -----------------------------------------------------------
> @angular-devkit/architect         0.900.1
> @angular-devkit/build-angular     0.900.1
> @angular-devkit/build-optimizer   0.900.1
> @angular-devkit/build-webpack     0.900.1
> @angular-devkit/core              9.0.1
> @angular-devkit/schematics        9.0.1
> @angular/cli                      9.0.1
> @ngtools/webpack                  9.0.1
> @schematics/angular               9.0.1
> @schematics/update                0.900.1
> rxjs                              6.5.3
> typescript                        3.6.4
> webpack                           4.39.1

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ X ] No

**Comment by timdeschryver** [comment]
I hope https://github.com/ngrx/platform/pull/2455 fixes this issue. 
When a new version is released, I will give it a spin and see what happens.

**Comment by timdeschryver** [comment]
@PooSham we just release v9.1 and this issue seems resolved.
If this is not the case, fee free to reopen this issue.

**Comment by PooSham** [comment]
I still get this issue in v9.1
