### ISSUE TITLE
RFC: Add more information to Redux Devtools from Effects

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#2485]
## Other information:

Effects are very opaque when it comes to seeing how they fit into the reactive cycle when building apps with NgRx. In most cases

- You have to trust that they "just work" when you dispatch an action
- Developers often get the timing of Effects wrong, in that they are handled _after_  state has already reduced, and then dispatch a new action.
- Developers can't easily see in the Redux DevTools what Effect dispatched a particular action

We have all this information at runtime, but are not currently surfacing it. This feature would dispatch a new action named `@ngrx/effects/dispatch` that contains:

- The name of the Effects class
- The effects property that produced the output action
- The output action that was dispatched

An example dispatched action:

```
{
  type: '@ngrx/effects/dispatch',
  effectsName: 'AuthEffects',
  effect: 'login$',
  outputAction: {
    type: '[Auth/API] Login Success',
    userId: 1
  }
}
```

This would provide a clearer log of how actions dispatched from Effects are integrated into the reactive cycle, where they originated from, and would not trigger any state changes. Effects with `dispatch: false` would not be included.

This _might_ be a breaking change for tests, as it introduces a new action being dispatched before the action from the Effect is dispatched, so it could be introduced as an opt-in option initially.

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by david-shortman** [comment]
While I like the idea of giving devs an optional tool to use, I do this dispatching actions unnecessarily is inadvisable especially considering how it affects tests. Further, following good action hygiene, developers "should" be writing actions which have a single source, and named with that source in the action name (i.e. "[myEffect] Some Action").

To me, promoting good action hygiene in the docs would be a better first direction to go before introducing a new debug action dispatching mechanism.

**Comment by loverde** [comment]
This project has an approach that wraps the effects and adds some of this information to the action. 
https://github.com/Bobrovskih/ngrx-log-initiator

It basically wraps effects before registering them with NGRX, so if NGRX had a configuration option to provide a function to wrap effects as they are registered then this code be one possible implementation of that function.
