### ISSUE TITLE
No documentation for the on function in Website

### ISSUE THREAD

**Issue by inunotaisho26** [ngrx/platform#2487]
There is no documentation for the `on` function within the NgRx website. I'm not sure if this is intentional or not, but newbies need that documentation. No matter how small, inconsequential or stupid it may sound. The `on` function is very easy to use, but I need to know precisely what it does.

**Comment by timdeschryver** [comment]
The docs for `on` can be found at https://ngrx.io/api/store/On.

**Comment by inunotaisho26** [comment]
@timdeschryver The [scoreboard.reducer.ts](https://ngrx.io/guide/store/reducers) example in the reducers page does not take the user to the documentation you shared with me.
