### ISSUE TITLE
@ngrx/component max call stack error with getter accessor property 

### ISSUE THREAD

**Issue by cgatian** [ngrx/platform#2488]
Exposing a public observable through a getter accessor property causes a max call stack error. If I change to a public property, the code works as intended. 

Accessing an observable through a getter accessor property seems to be the issue.

Use `ngrxLet` or `ngrxPush` in a simple hello world app.
* Disable ZoneJS
* Import `ReactiveComponentModule`
* Use `ngrxLet` with an observable

```html
<ng-container *ngrxLet="count$ as n">
  counter {{ n }}
</ng-container>
<button (click)="increment()">Increment</button>
```
```typescript
export class HelloWorldComponent {
  private countSubject = new BehaviorSubject<number>(0);

  get count$() {
    return this.countSubject.asObservable();
  }

  increment() {
    this.countSubject.next(this.countSubject.value + 1);
  }
}
```
Code works with async pipe and zone.

```
hostReportError.js:2 Uncaught RangeError: Maximum call stack size exceeded
    at TapSubscriber._next (tap.js:43)
    at TapSubscriber.next (Subscriber.js:49)
    at MapSubscriber._next (map.js:35)
    at MapSubscriber.next (Subscriber.js:49)
    at DistinctUntilChangedSubscriber._next (distinctUntilChanged.js:50)
    at DistinctUntilChangedSubscriber.next (Subscriber.js:49)
    at Subject.next (Subject.js:39)
    at Object.next (component.js:226)
    at LetDirective.set ngrxLet [as ngrxLet] (component.js:624)
    at setInputsForProperty (core.js:13652)
```

## Expected behavior:
Using the accessor property should not throw an error

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
Angular CLI: 9.1.1
Node: 13.12.0
OS: win32 x64

Angular: 9.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.1
@angular-devkit/build-angular     0.901.1
@angular-devkit/build-optimizer   0.901.1
@angular-devkit/build-webpack     0.901.1
@angular-devkit/core              9.1.1
@angular-devkit/schematics        9.1.1
@ngtools/webpack                  9.1.1
@schematics/angular               9.1.1
@schematics/update                0.901.1
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
## I would be willing to submit a PR to fix this issue

[X] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by cgatian** [comment]
I could be wrong, but because `asObservable()` returns a new reference the `distinctUntilChanged` [calls in `CdAware`](https://github.com/ngrx/platform/blob/master/modules/component/src/core/cd-aware.abstract.ts#L62) fail to notice that its actually the same observable. To fix I think we could perform a comparison on the `source` property within the observable.

**Comment by cgatian** [comment]
I believe this is functioning as intended, but may be worth noting in the docs.

Async pipe works because it never invokes a change detection on the component. `ngrxPush`/`ngrxLet`  do invoke changes which cause the template checks to run. If you use a function to return an observable (without memoizing that return value) you get into this situation.

**Comment by timdeschryver** [comment]
@BioPhoton do you got any ideas here? 🙂

**Comment by BioPhoton** [comment]
@cgatian Thanks for the input.
I'll consider it!

**Comment by criskrzysiu** [comment]
in't the rpbolem that in CdAware You actually never unsuscribe from observables? So here he is pushing new ones, and all of them are being 'taped'
You need to use switchMap inside cdaware I think,  I will check it out later.

**Comment by BioPhoton** [comment]
Hi @cgatian 

Your problem occurs most likely because `.asObservable` is creating a new instance of an observable. 
See: https://github.com/ReactiveX/rxjs/blob/master/src/internal/Subject.ts#L140

The lines:
```typescript
 get count$() {
    return this.countSubject.asObservable();
  }
```
As above we do not store the created instance of the observable returned by `asObservable` we return a new instance of Observable every time the function is called.

You can think of the following:
```typescript
private readonly _count$ = this.countSubject.asObservable();
 get count$() {
    return this._count$;
  }
```

But to give to a full understanding of the problem let me elaborate more.

The concept of the `async` pipe is the same in `ngrxPush` and `ngrxLet` and works as follow:
1. receive an observable and check if it is new. 
   1. If
       1. do nothing
   2. else
        1. reset the view value & re-render the view
        2. subscribe to the newly passed observable
            1. for every new value  reset the view value  & re-render the view

In you this, the passed observable was always new. This caused the following process to go in an endless loop:
1. receive an observable and check if it is new. 
    ii. else
        a. reset the view value & rerender the view
        b. subscribe to the newly passed observable
            1. for every new value  reset the view value  & re-render the view => go to 1.

I will see if I can find a way to detect such special cases and open a new issue if I can suggest something.

If I can help you further please let me know! 

Otherwise, I would not consider closing this issue as from
the perspective of the component package it is working correctly and handles new observables that are passed.

@brandonroberts 
May give feedback on my suggestion.

**Comment by cgatian** [comment]
@BioPhoton thank you for the deep explanation. It should help someone in the future. I think in general my practice of making accessors for observables is a bit of an anti-pattern. 

I do ask the team to consider adding a warning in documentation to make sure consumers avoid doing this. The gotcha for me was the async pipe worked fine.
