### ISSUE TITLE
docs(store): add docs for using `FEATURE_REDUCERS` token with ReducerManager

### ISSUE THREAD

**Issue by damienwebdev** [ngrx/platform#2495]
I'm trying to work out a solution to #1734 and I have a pretty decent solution that I'd like to document for `@ngrx`. Unfortunately, I'm currently facing some issues surrounding accessing `FEATURE_REDUCERS` across root, child, and lazy-loaded injector hierarchies. 

Specifically, I'm trying to merge an application developer's feature reducers into an existing reducer via the `ReducerManager`.

In my feature module, I'm trying to follow a similar pattern to the `@ngrx/store` StoreModule.forFeature() where I merge the reducers together into the feature via a custom-defined `reduceReducers`.

Currently, my key issue is that no matter what I try, `FEATURE_REDUCERS` is always an empty array.

## I would be willing to submit a PR for the docs :heart:

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
It's a bit unclear to me what you're trying to do and what is going wrong.
Got some code you can share?
