### ISSUE TITLE
window.ngrx.store is empty object when using umd files of ver. 8 and above

### ISSUE THREAD

**Issue by ramesh-yadav** [ngrx/platform#2496]
## Minimal reproduction of the bug/regression with instructions:

I am using this (https://www.angulararchitects.io/aktuelles/6-steps-to-your-angular-based-microfrontend-shell/) approach to create Microfrontends. 

When I use UMD files of @ngrx/store 8 and above window.ngrx.store is empty object. With Ver. 7 it is working fine.

## Expected behavior:

window.ngrx.store should not give empty object and return object same like Ver 7.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
NgRx: 9.1
Angular: 9.1
Node: 10.16.1
OS: MacOS Mojave

**Comment by brandonroberts** [comment]
Check with the latest release or the next beta
