### ISSUE TITLE
ETA on when ngrx 4.x should be available on npm?

### ISSUE THREAD

**Issue by petercn** [ngrx/platform#25]
Just wondering if there's an ETA / roadmap on when ngrx 4.x is targeted to be available on npm?

**Comment by MattMorrisDev** [comment]
Here's an estimate from a month ago: https://github.com/ngrx/store/pull/269#issuecomment-293628437

You can also try the nightly builds already. If you're using the angular-cli, they *should* be releasing a beta version today with typescript 2.3 support, so there shouldn't be any major barriers for most people to try it after that's released.

**Comment by jd-carroll** [comment]
The angular-cli now supports typescript 2.3, any update on when this might be released?

**Comment by bbaia** [comment]
You can use nightly build for now, setting your `package.json` like this:
```javascript
"@ngrx/effects": "github:ngrx/effects-builds",
"@ngrx/router-store": "github:ngrx/router-store-builds",
"@ngrx/store": "github:ngrx/store-builds",
"@ngrx/store-devtools": "github:ngrx/store-devtools-builds",
```

**Comment by robwormald** [comment]
Target is July 1

**Comment by ygrene-austin** [comment]
Where is the Gittip/ buy you guys a coffee button? @robwormald

**Comment by MattiJarvinen-BA** [comment]
@robwormald You guys still on target? 🏆

**Comment by ciesielskico** [comment]
How's the ETA now that the example app has been merged?

**Comment by robwormald** [comment]
Now 😇

**Comment by petercn** [comment]
Great work guys! :-)
