### ISSUE TITLE
What context of using NgRX

### ISSUE THREAD

**Issue by jt4000** [ngrx/platform#2505]
Hello, 

I'm newbie in ngrx and I wonder what context have you used ngrx to your website and why?

Thank you!

**Comment by brandonroberts** [comment]
Hello @jt4000, good to see you're looking at using NgRx. GitHub is mainly for bugs, and feature requests. These types of questions are better asked on the [gitter channel](https://gitter.im/ngrx/platform) or on social media if you use it.
