### ISSUE TITLE
Missing Documentation for new Entity module

### ISSUE THREAD

**Issue by petercn** [ngrx/platform#251]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ x ] Documentation issue or request
[ ] Support request
</code></pre>

## What is the current behavior?
Entity module is not documented

## Expected behavior:
Documentation should be present describing the purpose of the entity module

## Minimal reproduction of the problem with instructions:
Visit ngrx/platform main readme and note that the entity module's purpose is not mentioned

## Version of affected browser(s),operating system(s), npm, node and ngrx:
ngrx 4+

**Comment by MikeRyanDev** [comment]
This is intentional. We'll release documentation and examples when we are ready to release the package.

Thanks!

**Comment by petercn** [comment]
Thanks for the prompt reply @MikeRyanDev :-)
