### ISSUE TITLE
When using RouterState.Full in router-store: "Cannot assign to read only property 'tView' of object '[object Object]'"

### ISSUE THREAD

**Issue by adrdilauro** [ngrx/platform#2510]
## Minimal reproduction of the bug/regression with instructions:

Initialising `@ngrx/router-store` in the following way causes an exception

```typescript
StoreRouterConnectingModule.forRoot({
  routerState: RouterState.Full,
})
```

The error is the following

```
ERROR Error: Uncaught (in promise): TypeError: Cannot assign to read only property 'tView' of object '[object Object]'
    at getOrCreateTComponentView (core.js:7625)
    at createRootComponentView (core.js:18912)
    ...
```

The error I am seeing seems to be related to https://github.com/ngrx/platform/issues/2109, which was apparently fixed in https://github.com/ngrx/platform/pull/2351, but had a recrudescence in https://github.com/ngrx/platform/issues/2404.

I inspected the source code, and found out that, at line https://github.com/ngrx/platform/blob/master/modules/router-store/src/router_store_module.ts#L172, `DefaultRouterStateSerializer` is used instead of `MinimalRouterStateSerializer` by default, when you specify that you want to use `RouterState.Full`. 

Following the discussion in https://github.com/ngrx/platform/issues/2404, I suspect that the cause of the error is that, at line https://github.com/ngrx/platform/blob/master/modules/router-store/src/serializers/default_serializer.ts#L30 of the default serialiser, you are including in the serialised data the component that is attached to the route: such component is not an `@ngrx` component, thus it doesn't get included in the fix done in PR https://github.com/ngrx/platform/pull/2351.

Explicitly forcing `MinimalRouterStateSerializer` is a workaround that avoids the exception, like this:

```typescript
StoreRouterConnectingModule.forRoot({
  routerState: RouterState.Full,
  serializer: MinimalRouterStateSerializer,
})
```

Finally, I am seeing this error regardless of the presence of strict checks.

## Expected behavior:

I should be able to configure `RouterState.Full` in `StoreRouterConnectingModule.forRoot()` without having to add `MinimalRouterStateSerializer`.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

- `@ngrx/store`: 9.0.0
- `@ngrx/router-store`: 9.1.0
- `@angular/core`: 9.0.6
- `node`: 12.13.0

## I would be willing to submit a PR to fix this issue

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Can you try this with the latest `@ngrx/store` and `@ngrx/router-store` version (v9.1.1) please?

**Comment by adrdilauro** [comment]
@timdeschryver with that version I get the following error:

<img width="1171" alt="Screen Shot 2020-05-07 at 16 51 50" src="https://user-images.githubusercontent.com/1175837/81316174-268b4b80-9083-11ea-9346-c23029effd26.png">

**Comment by timdeschryver** [comment]
Thanks @adrdilauro.

This is the desired result, as it's also noted in our [docs](https://ngrx.io/guide/router-store/configuration).
IIRC we did this because this configuration was the default in previous versions.
Do you remember something about this @brandonroberts ?

We could make the `MinimalSerializer` also the default for the `RouterState.Full` option, but I'm not sure why this would be helpful. If you're using `RouterState.Full`, my guess is that you want the full router event stored and added to the action.

**Comment by brandonroberts** [comment]
Yea, we had to do it that way because of the navigationId/event information I believe. This should not be an issue with the latest release. If it is re-open the issue.

**Comment by Frankitch** [comment]
I stumbled upon this issue.
As stated in the docs I set the runtime check `strictStateSerializability` to `false` (default) but I also had to set `strictStateImmutability` to `false` to make it work...
