### ISSUE TITLE
RFC: simplifying immutable updates; reduced boilerplate

### ISSUE THREAD

**Issue by ysoulaim** [ngrx/platform#2518]
## Target Issue

Manipulating the state within reducers can be complex and may require quite a lot of boilerplate, and the produced code is not necessarily readable.

Let's consider a simple example:
```
const initialState = {
	loader: { pending: false, error: null },
};

export const itemsReducer = createReducer(
	on(getItemsAction, (state) => ({
		...state,
		loader: { ...state.loader, pending: true }
	})),
);
```

The complexity is more apparent for deep states; updating a deep state in an immutable way requires destructuring each level of the state tree. For instance, in the above example, we have `...state` then `...state.loader`, and this can go deeper depending on the state shape.

## Feature Concept

The code presented above can be simplified by introducing the [immer](https://github.com/immerjs/immer) library, which allows to produce the next immutable state tree by simply mutating the current one.
```
export const itemsReducer = createReducer(
	on(getItemsAction, (state) => 
		produce(state, (draft) => { draft.loader.pending = true; })
	),
);
```

However, introducing the `produce(state, (draft) => {})` layer at each change of state can quickly become annoying. 

As it is done in the [Redux Toolkit](https://github.com/reduxjs/redux-toolkit/blob/master/src/createReducer.ts), it would be pleasant to have an internal option allowing to choose between the two possibilities, depending on the need. Eventually a `createMutableReducer` method, or simply a `mutableOn` which can be used as follows:
```
const itemsReducer = createMutableReducer(
	initialState,

	on(getItemsAction, (state) => {
		state.loader.pending = true;
	})
);
```
Or `mutableOn`, which can coexist with `on`:
```
const itemsReducer = createReducer(
	initialState,

	mutableOn(getItemsAction, (state) => {
		state.loader.pending = true;
	})

	on(getItemsSuccessAction, (state, { payload }) => ({
		...state,
		loader: { ...state.loader, pending: false }
		items: payload.items
	})),
);
```

## Other information:

The two utility functions proposed above are already implemented in the library [NgRx-etc](https://github.com/timdeschryver/ngrx-etc) which we can integrate if the feature is accepted.

## If accepted, I would be willing to submit a PR for this feature

[X] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
Thanks @ysoulaim, but we're keeping the core as it is, and if you want to use Immer, or some other immutable library, you can.
