### ISSUE TITLE
schematics:feature --skipTest flag generates actions.spec.ts

### ISSUE THREAD

**Issue by aszechlicki** [ngrx/platform#2521]
## Minimal reproduction of the bug/regression with instructions:
ng g @ngrx/schematics:feature TestFeature --flat false -r index.ts --skipTest true

result:
**CREATE src/app/reducers/test-f.actions.spec.ts (198 bytes)**
CREATE src/app/reducers/test-f.actions.ts (123 bytes)
CREATE src/app/reducers/test-f.reducer.ts (328 bytes)
CREATE src/app/reducers/test-f.effects.ts (580 bytes)
CREATE src/app/reducers/test-f.selectors.ts (220 bytes)

## Expected behavior:
No *.spec.ts files are generated

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
Angular: 9.1.6
ngrx/core: 9.1.2
ngrx/schematics: 9.1.2

## Other information:
I believe i tracked it down:
file _platform/modules/schematics/src/feature/index.ts_ calls actions schematic:
```
schematic('action', {  
        flat: options.flat,  
        group: options.group,  
        name: options.name,  
        path: options.path,  
        project: options.project,  
        skipTest: true,
        api: options.api,  
        creators: options.creators,  
      })
```
thats first issue - value provided in options is ignored, and hardcoded true is passed instead

and then in _platform/modules/schematics/src/action/schema.ts_ parameter name is:  
`skipTests?: boolean;` (see the typo?)

## I would be willing to submit a PR to fix this issue

[*] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
Good catch @aszechlicki. If you need help on the PR, just let us know.
