### ISSUE TITLE
Angular App with WebComponent; WebComponent-Init destroy state in DevTools

### ISSUE THREAD

**Issue by TechnicalFreak** [ngrx/platform#2523]
Project 1: AngularApp with ngrx (own rootStore)
Project 2: AngularApp using Angular/Elements with ngrx (also own rootStore)

WebComponent from Project2 is running in Project 1.

The Web-Component is introduced dynamically in app.html from Project 1 by button-click. It's the same behavior, when hard-coding the web-component.

With button-click the state of the web-component is loading. The problem is, that the initialState is written in the state of the Project1-Store. Until there is no Action raised in project1, the store contains the intialState of the web-component. In the store of the web-component the initialState is missing.

After 2 days I found a solution but it's not nice. 
The store of the web-component is working correctly only if I'm using the EffectsModule in the web-component-project. With the action "@ngrx/effects/init the state is written correctly. Before the effects-init action raises a "@@Init" Action with state undefined. This is a bug?!

The store of Project 1 is only working correctly if I'm calling "this.devtools.refresh();" in "ngAfterViewChecked" in the app.component.ts. Otherwise the store contains the initialState of the web-component.

**Comment by brandonroberts** [comment]
This question should be asked in the [gitter channel](https://gitter.im/ngrx/platform)
