### ISSUE TITLE
After updating project from Angular 8 to Angular 9 this error occurs store.js:328 Uncaught TypeError: this.dispatcher.next is not a function

### ISSUE THREAD

**Issue by SzymonPawlak** [ngrx/platform#2526]
## Minimal reproduction of the bug/regression with instructions:
It is really hard to figure out what have to be done to reproduce that.

After updating angular 8 to version 9 after running application locally (ng serve) i have this error:
![Screenshot_3](https://user-images.githubusercontent.com/8612345/81823884-1b2d9980-9535-11ea-9880-fe122383c2b9.png)
```
store.js:328 Uncaught TypeError: this.dispatcher.next is not a function
    at ReducerManager.push.../../node_modules/@ngrx/store/fesm5/store.js.ReducerManager.updateReducers (store.js:328)
    at ReducerManager.push.../../node_modules/@ngrx/store/fesm5/store.js.ReducerManager.addReducers (store.js:314)
    at ReducerManager.push.../../node_modules/@ngrx/store/fesm5/store.js.ReducerManager.addFeatures (store.js:300)
    at new StoreFeatureModule (store.js:881)
    at _createClass (core.js:22159)
    at _createProviderInstance (core.js:22121)
    at initNgModule (core.js:22051)
    at new NgModuleRef_ (core.js:22691)
    at createNgModuleRef (core.js:22680)
    at Object.debugCreateNgModuleRef [as createNgModuleRef] (core.js:32086)
```

## Expected behavior:
After run ng serve should working without errors

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
Angular: 9.1.6
@ngrx/effects": "9.1.2",
@ngrx/router-store": "9.1.2",
@ngrx/store": "9.1.2",
@ngrx/store-devtools": "9.1.2",
Node: v10.16.3
Windows 10
All browsers

**Comment by timdeschryver** [comment]
Did you try it with a clean install?

**Comment by SzymonPawlak** [comment]
@timdeschryver many times

**Comment by timdeschryver** [comment]
Can you create a reproduction for this issue?

**Comment by SzymonPawlak** [comment]
@timdeschryver i will try to reproduce this using stackblitz, but this is quite complicate project - so it will be hard to reproduce this without showing client code

**Comment by SzymonPawlak** [comment]
Right now i separate one project from nrwl workspace (all projects have the same issue) and a run it on angular workspace i have a little more information in console, but still during debugging for me is really hard to understand this issue 

![image](https://user-images.githubusercontent.com/8612345/82800720-6f614380-9e7c-11ea-856e-2e3a4c024b46.png)

**Comment by SzymonPawlak** [comment]
I found root of issue 

`import { ModuleWithProviders, NgModule } from '@angular/core';
import { EffectsModule } from '@ngrx/effects';
import { StoreModule } from '@ngrx/store';
import { StoreDevtoolsModule } from '@ngrx/store-devtools';

import { devtoolsExtensionProvider, metaReducersProvider } from './providers';
import { EffectsService, StateService } from './services';

@NgModule({
    imports: [StoreModule.forRoot({}), EffectsModule.forRoot([]), StoreDevtoolsModule.instrument()],
    exports: [StoreModule, EffectsModule],
    providers: [EffectsService, StateService, devtoolsExtensionProvider, metaReducersProvider]
})
export class NgrxRootModule {}

@NgModule()
export class NgrxModule {
    static forRoot(): ModuleWithProviders<NgrxRootModule> {
        return {
            ngModule: NgrxRootModule
        };
    }
}
`

this is my NgrxRoot Module, when i deleted `StoreDevtoolsModule.instrument()` everything works well, but frankly speaking i have no idea why

**Comment by brandonroberts** [comment]
Maybe check of some your custom providers. Marking as resolved
