### ISSUE TITLE
router-state gets deleted after navigation completes

### ISSUE THREAD

**Issue by mvasyukov** [ngrx/platform#2527]
I am using Angular 9.1.6 with ngrx 9.1.2.
The following problem was encountered, when the setup for the router-store was reused from an angular 7 project:

- `@ngrx/router-store/navigation` action adds the routerState to my application state. Everything fine up until here.
![TestcaseDevelopment](https://user-images.githubusercontent.com/60703222/82020445-5f31b300-9689-11ea-82ae-22aec05d71fb.jpg)
- However the `@ngrx/router-store/navigated` action removes the store after the navigation is finished.
![TestcaseDevelopment](https://user-images.githubusercontent.com/60703222/82020632-be8fc300-9689-11ea-8295-e49b305e5f8d.jpg)

This means I am not further able to access my router params. 
Did I miss something when moving from angular7 -> 9?

I have provided my dependencies as well as the router setup and the imports in app.module

<details>
<summary> Dependencies </summary>

    "@angular/animations": "~9.1.6",
    "@angular/cdk": "^9.2.3",
    "@angular/common": "~9.1.6",
    "@angular/compiler": "~9.1.6",
    "@angular/core": "~9.1.6",
    "@angular/forms": "~9.1.6",
    "@angular/material": "^9.2.3",
    "@angular/platform-browser": "~9.1.6",
    "@angular/platform-browser-dynamic": "~9.1.6",
    "@angular/router": "~9.1.6",
    "@ngrx/effects": "^9.1.2",
    "@ngrx/entity": "^9.1.2",
    "@ngrx/router-store": "^9.1.2",
    "@ngrx/store": "^9.1.2",
    "@ngrx/store-devtools": "^9.1.2",
    "core-js": "^3.6.5",
    "jwt-decode": "^2.2.0",
    "moment": "^2.25.3",
    "ngrx-store-freeze": "^0.2.4",
    "ngrx-store-localstorage": "^9.0.0",
    "ngx-mat-select-search": "^2.2.0",
    "rxjs": "~6.5.5",
    "tslib": "^1.9.0",
    "zone.js": "~0.10.3"

</details>

<details>
<summary> Reducer </summary>

```

export const reducers: ActionReducerMap<TestCaseDevelopmentAppState> = {
  router: fromRouter.routerReducer,
};

export const metaReducers: Array<MetaReducer<TestCaseDevelopmentAppState>> = !environment.production
  ? [purgeOnLogout, storeFreeze, localStorageSyncReducer]
  : [purgeOnLogout, localStorageSyncReducer];


export interface TestCaseDevelopmentAppState {
  router: fromRouter.RouterReducerState<RouterStateUrl>;
  asyncState?: AsyncState;
}

export interface RouterStateUrl {
  url: string;
  params: Params;
  queryParams: Params;
  firstUrlSegment: string | null;
}

export class CustomRouterStateSerializer
  implements RouterStateSerializer<RouterStateUrl> {
  serialize(routerState: RouterStateSnapshot): RouterStateUrl {
    let route = routerState.root;

    // first url segment is used in navbar to determine which section button is active
    let firstUrlSegment = null;
    if (
      route.firstChild &&
      route.firstChild.url &&
      route.firstChild.url.length > 0
    ) {
      firstUrlSegment = route.firstChild.url[0].path;
    }

    let params = {};

    while (route.firstChild) {
      params = { ...params, ...route.params };
      route = route.firstChild;
    }
    params = { ...params, ...route.params };

    const {
      url,
      root: { queryParams },
    } = routerState;

    let storeReadyUrl = url;
    if (url.indexOf('?') > -1) {
      storeReadyUrl = url.substring(0, url.indexOf('?'));
    }

    // Only return an object including the URL, params and query params
    // instead of the entire snapshot
    return { url: storeReadyUrl, params, queryParams, firstUrlSegment };
  }
}
```

</details>

<details>

<summary> App Module </summary>

```
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AsyncStateModule,
    HttpClientModule,
    NavigationModule,
    AuthModule.forRoot(),
    SettingsModule.forRoot(),
    EffectsModule.forRoot([RouterEffects]),
    StoreModule.forRoot(reducers, { metaReducers }),
    StoreDevtoolsModule.instrument(),
    StoreRouterConnectingModule.forRoot({
      stateKey: 'router',
    }),
    BrowserAnimationsModule,
    RouterModule.forRoot(routes, { preloadingStrategy: PreloadAllModules })
  ],
  providers: [
    { provide: RouterStateSerializer, useClass: CustomRouterStateSerializer },
    { provide: API_BASE, useValue: getApiBase(environment) },
    { provide: APP_NAME, useValue: environment.app_name },
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

</details>

**Comment by JoshMcDaniel** [comment]
What was the solution to the issue? I'm having this problem now and can't figure out why.
