### ISSUE TITLE
Make it possible to change the variable name for EntityMetadataMap on @ngrx/data

### ISSUE THREAD

**Issue by amithegde** [ngrx/platform#2529]
I am looking at [this sample](https://stackblitz.com/edit/ngrx-data-tutorial?file=src%2Fapp%2Fstore%2Fentity-metadata.ts) which defines a variable `entityMetadata` to create entity metadata map for using @ngrx/data. If I change that variable name to something else such as `appEntityMetadata` as shown on the [docs here](https://ngrx.io/guide/data/entity-metadata) it shows following error:

>Error: Uncaught (in promise): Error: No EntityDefinition for entity type "Hero".
>Error: No EntityDefinition for entity type "Hero".

I noticed this with an example I am trying and little research pointed me to [this SO question](https://stackoverflow.com/questions/58731183/using-ngrx-data-getting-no-entitydefinition-for-entity-type-x) which mentioned the variable name issue. Is this something that can be fixed in the future? Or is there a specific purpose for this?

## Expected behavior:

User should be able to define this variable with whatever name.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
NgRx 8, Angular 8.

**Comment by timdeschryver** [comment]
You can rename the variable, but you will have to use the `appEntityMetadata` property while providing the config.

```ts
const foo: EntityMetadataMap = {
  Hero: {},
  Villain: {}
};

export const entityConfig = {
  entityMetadata: appEntityMetadata ,
  pluralNames
};
```
