### ISSUE TITLE
ngrx store how to reset state when user logout?

### ISSUE THREAD

**Issue by node-rookie** [ngrx/platform#253]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

**Comment by brandonroberts** [comment]
If you want to do this for the entire state. Use a meta-reducer that listens for a particular action and resets the state as undefined

**Comment by valdestrijus** [comment]
Maybe example would be helpful. I am doing it like this. I am redefining state as undefined it is not a mutation.
`
import {
    ActionReducerMap,
    createSelector,
    createFeatureSelector,
    ActionReducer,
} from '@ngrx/store';
import { environment } from '../../../environments/environment';

import { storeFreeze } from 'ngrx-store-freeze';
import { storeLogger } from 'ngrx-store-logger';

import * as fromConfig from './config';
import * as fromAuth from './auth';

export interface State {
    config: fromConfig.State;
    auth: fromAuth.State;
}

export const reducers: ActionReducerMap<State> = {
    config: fromConfig.reducer,
    auth: fromAuth.reducer
};

function storeStateGuard(reducer) {
    return function (state, action) {
        if (action.type === '[Auth] Logout success') {
            state = undefined;
        }

        return reducer(state, action);
    }
}

export const metaReducers: ActionReducer<any, any>[] = environment.debug
    ? [
        storeStateGuard,
        storeLogger({
            filter: {
                blacklist: ['@ngrx/store/update-reducers', 'Do Nothing']
            }
        })
    ]
    : [storeStateGuard];

...selectors

`
