### ISSUE TITLE
Warning about deep imports

### ISSUE THREAD

**Issue by GregOnNet** [ngrx/platform#2532]
## Describe any alternatives/workarounds you're currently using

The library [NgRx Ducks]() uses the types `FunctionWithParametersType` and `TypedAction` of NgRx to build its API to be compatible with the NgRx ecosystem.

```ts
import {
  FunctionWithParametersType,
  TypedAction
} from '@ngrx/store/src/models';
```

To use the types I need to use a deep import into NgRx's source: `@ngrx/store/src/models`.
Currently, if NgRx Ducks is used the Angular CLI throws a warning about deep imports.

```bash
$ ng serve
Warning: Entry point '@ngrx-ducks/core' contains deep imports into '~/../ngrx-ducks-example-ivy/node_modules/@ngrx/store/src/models'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
```

Can the types be exposed as public API allowing other libraries to reuse the types?

### Reproduction

```
git clone https://github.com/co-IT/ngrx-ducks-example-ivy
cd ngrx-ducks-example-ivy
yarn
npm start 
# see warning in console output
```
## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by alex-okrushko** [comment]
Hey @GregOnNet ,

`FuntionWithParametersType` is a simple function type. I checked the sources for NgRx Ducks, and it appears to be used in one place (+ the test).

You should be able to replace
```typescript
export declare type ActionLoaded<
  TType extends string,
  TPayload
> = FunctionWithParametersType<
  [TPayload],
  {
    payload: TPayload;
  } & TypedAction<TType>
> &
  TypedAction<TType>;
```

with 

```typescript
export declare type ActionLoaded<
  TType extends string,
  TPayload
> = ActionCreator<
  TType,
  Creator<TPayload[], { payload: TPayload; type: TType }>
>;
```
or 

```typescript
export declare type ActionLoaded<
  TType extends string,
  TPayload
> = ActionCreator<
  TType,
  (payload: TPayload) => { payload: TPayload; type: TType }
>;
```
both `Creator` and `ActionCreator` are part of the public API.
