### ISSUE TITLE
INITIAL_STATE injection token with new createReducer function

### ISSUE THREAD

**Issue by knoefel** [ngrx/platform#2534]
I want to set the initial state of a feature module with the `INITIAL_STATE` token, because i need to inject and use a service before setting the initial state. This is how implemented it following the docs:

```
@NgModule({
    ...
    imports: [
        SharedModule,
        DashboardRoutingModule,
        StoreModule.forFeature(fromDashboard.dashboardFeatureKey, fromDashboard.reducer, INITIAL_STATE)
    ],
    providers: [
        { provide: INITIAL_STATE, useFactory: getInitialState, deps: [ServiceA] }
    ]
})
export class DashboardModule {}
```

```
const getInitialState = (aService: ServiceA) => {
    return aService.getState();
};
```

This is working fine and the `getInitialState` function is called - although the return value is ignored and isn't set as the initial state value. Aside from that it isn't clear, what is to set as the first parameter for the createReducer function:

```
createReducer<any, Action>(initialState: any, ...ons: On<any>[]): ActionReducer<any, Action>
```

I tried to set it to `undefined`, but then my selectors got also `undefined` as the state value.

Am i missing something obvious? I can't find anything about that use case in the docs.

**Comment by timdeschryver** [comment]
The `INITIAL_STATE` token is only used to set the initial state of the root module.
You could use the [`OnInitEffect`](https://ngrx.io/guide/effects/lifecycle#oniniteffects) lifecycle or the `@ngrx/store/update-reducers` action to dispatch a "set action" to set the state of the feature module in a reducer.
