### ISSUE TITLE
@ngrx/entity add mapOne method

### ISSUE THREAD

**Issue by awonihlgard** [ngrx/platform#2538]
Similiar to `setOne` and `updateOne`, it would be useful with a `mapOne` for cases where you want to update a single entity but the new value depends on the old. Example:

```js
return adapter.mapOne(id, entity => {
    ...entity,
    counter: entity.counter + 1
}, state);
```

The naming of `map` would then be a bit inconsistent, but that might be fine. For full consistency the naming would `mapOne` and `mapAll` (`mapMany` could also be added for completeness).

## Describe any alternatives/workarounds you're currently using

The same thing can be accomplished by accessing the old entity with `state.entities`, but it becomes a bit more verbose if you also want to check for existence:

```js
const entity = state.entities[id];
if (entity) {
    return state.updateOne({
        id,
        changes: {
            counter: entity.counter + 1
        }
    })
} else {
    return state;
}
```

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
What about using the `map` method for it, it looks as follows:

```ts
const withUpdates = adapter.map(
      entity =>
        entity.id=== action.id
          ? {...entity, counter: entity.count +1}
          : entity,
      state
    );
```

**Comment by awonihlgard** [comment]
Yes, the performance concern is why I gave `updateOne` as an alternative. Even if using `map` is fine in most cases it feels inelegant to iterate every entity when you only want to update one.

**Comment by timdeschryver** [comment]
IIRC this is not the first time that this feature came up to discussion.
What do you think about adding this to @ngrx/entity @brandonroberts, if @awonihlgard wants to create a PR for it?

If we want to forward with this, how would it behave if no entity is found for the key? Should it just ignore it, or invoke the `map` with an `undefined` entity?

**Comment by criskrzysiu** [comment]
I would say It should pass without an error  and no change should be made
to state. Also, should update methods start to check that entity is
provided with different id than the one passed as an argument?

W dniu wt., 16.06.2020 o 13:01 Tim Deschryver <notifications@github.com>
napisał(a):
