### ISSUE TITLE
idea for lazy effects

### ISSUE THREAD

**Issue by sod** [ngrx/platform#2541]
I'd like to have a way to define effects to be bootstrapped on demand.

We rewrote our shop with angular + ngrx. So everything now works with redux. We are super pleased with the experience and don't look back.

We accumulated quite some effects (as of now, 136 `createEffect(...)`). We have a few bound to lazy chunks, but most of them are part of the global state, so initialized upfront.

Profiling the page shows this flame chart:
![image](https://user-images.githubusercontent.com/905328/83154765-cecf8580-a100-11ea-8873-2b83c74a01e1.png)
Where the block in the red square is first dependency injecting all effect classes and then registering them with ngrx. Even though only a handful of those effects are needed on initial load to get the page up and running. Many are required only when the user interacts with the page.

I already started tinkering with a more lazy/on-demand effects approach. Maybe something like this:

A `createLazyEffect` function, that could look like this: https://gist.github.com/sod/7c59bf435e43c192f589815997bce76c

And using it could look like:

```typescript
import {createLazyEffect} from './create-lazy-effect';
import {createAction} from '@ngrx/store';
import {Injectable} from '@angular/core';
import {tap} from 'rxjs/operators';

@Injectable({providedIn: 'root'})
export class MyService {
    public addSmiley(text: string): string {
        return text + ' :)';
    }
}

export const myAction = createAction('[Demo] My Action');
export const myEffect = createLazyEffect({
    actions: [myAction],
    dependencies: [MyService],
    dispatch: false,
    effect: (action$, myService) => action$.pipe(tap(() => console.log(myService.addSmiley('My Action happened')))),
});

@NgModule({
    imports: [
        EffectsModule.forFeature([myEffect]),
    ],
})
export class MyFeatureModule {}
```

Now the effects module should wait with bootstrapping this effect until one of the defined actions emits.

Of course it would be amazing if the dependency injection could be a bit more elegant. But I couldn't think of a better syntax yet. (Would be nice if angulars `@Injectable` could work on functions.)

May there a chance to have something like this in ngrx? Any ideas for a better syntax?

**Comment by sod** [comment]
I just read through the [component-store RFC](https://github.com/ngrx/platform/issues/2489) and code. It seems like that could already solve the issue partially, as thoase stores can be picked on component level instead of module level. Pretty nice.

**Comment by sod** [comment]
I'm gonna try that component-store when it's ready.

**Comment by timdeschryver** [comment]
@sod As you've mentioned, component story will help here.
For now, another option would be to register the effect when it's needed via the `addEffect` method, see the [docs](https://ngrx.io/api/effects/EffectSources) for more info.
