### ISSUE TITLE
Docs: Reorganize sections on homepage/sidenav for packages

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#2564]
## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by jordanpowell88** [comment]
I'd be happy to tackle this @brandonroberts Can you be a little more specific on how you want everything grouped?

**Comment by brandonroberts** [comment]
Sure. We have three main areas.

- State: composed of all the existing libraries that deal with state management
- Data: incldues NgRx Data
- View: includes Component today, and potentially Router in the future

So the sidenav would group the packages according to these areas, and the docs would be updated to describe NgRx as a framework to handle these different areas. If you want to take the nav part that would be great. I'm working on the homepage text.
