### ISSUE TITLE
Root actions not handled by feature reducer

### ISSUE THREAD

**Issue by karlhaas** [ngrx/platform#257]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## What is the current behavior?
When dispatching an action on the Root-Store, the action is not handled by feature reducers. In our case we have some global actions which could be relevant for feature reducers as well. Currently when we dispatch such an action via the root store (provided via StoreModule.forRoot), then the feature reducers are not called.

## Expected behavior:
When dispatching an action via the root store, feature reducers are called.

## Minimal reproduction of the problem with instructions:

- Add feature reducer
- Dispatch action on root reducer
- Feature reducer not called

## Version of affected browser(s),operating system(s), npm, node and ngrx:
Angular 4.3.3
NGRX builds

**Comment by brandonroberts** [comment]
Will you provide a small reproduction of this issue?

**Comment by karlhaas** [comment]
arrggg. While trying to find the AOT bug, I probably moved StoreModule.forRoot into the import array of our CoreModule. I guess the Store has been created several times which caused the issue. After moving back to forRoot it works ...
Sorry @brandonroberts
