### ISSUE TITLE
Schematics: add schematic for component store

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#2570]
Add a new schematic to generate:

A service that extends ComponentStore
A spec file if requested
Maybe an inlined interface for the default type

## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by ilyaryabchinski** [comment]
Wanted to grab this, but didn't find the way how to run schematics locally(not from node_modules) 😢

**Comment by santoshyadavdev** [comment]
Hey @ilyaryabchinski if you want to start I can help.

**Comment by ilyaryabchinski** [comment]
Hey @santoshyadavdev! would be nice

So I am trying to run schematics directly from the repo, but get an error. What am I doing wrong?

![image](https://user-images.githubusercontent.com/20639767/88219810-c9a73680-cc6a-11ea-8f9b-70a66dca520f.png)

**Comment by santoshyadavdev** [comment]
It's easy to write test for schematics and verify rather than trying to run it locally. You can see any existing test case. You can share the repo with me to check as well.

**Comment by timdeschryver** [comment]
As @santoshyadavdev pointed out, the easiest way to test a schematic is via unit tests.
What I do if I want to test them out in a project is to build to project and use `npx` to to run the schematic.
The [angular docs](https://angular.io/guide/schematics-for-libraries#running-your-library-schematic) have a section that can help you with it (via `npm link`).
I hope this helps you a bit, if not feel free to ping us 🙂

**Comment by rovshenn** [comment]
I am planning to look into this as there seem to be no open PR :) I have had some schematics experience

**Comment by rovshenn** [comment]
@brandonroberts @timdeschryver and @alex-okrushko 
I am wondering what the template for the auto generated component store service should contain. 
Where do you want to discuss it guys?

**Comment by rovshenn** [comment]
I am wondering if the component store should be provided for a specific component or a modal or shall we give both selections and let the user narrow down?

**Comment by rovshenn** [comment]
I will base my work based off of schematics for effects, as both effects and component store are services

**Comment by rovshenn** [comment]
@timdeschryver @brandonroberts @alex-okrushko :) any thoughts on above?

**Comment by brandonroberts** [comment]
Yes I think providing a path to a component should be an option.

**Comment by va-stefanek** [comment]
@brandonroberts Would you prefer to have a path to module and component as an option or one of them (component)? In case of component should we also inject component store to the constructor? Do we allow to not specify neither of them and generate component store with `providedIn: 'root'`?
