### ISSUE TITLE
ngrx 9: Typescript error when return EMPTY from createEffect

### ISSUE THREAD

**Issue by DzmVasileusky** [ngrx/platform#2577]
In previous versions of NGRX we could return EMPTY observable constant from rxjs createEffect method of ngrx/effects. 
Currently it cause typechecking error

## Minimal reproduction of the bug/regression with instructions:
https://stackblitz.com/edit/ngrx-seed-jo6t62?file=src%2Fapp%2Fdemo.effects.ts

## Expected behavior:
No error when createEffect's source function returns EMPTY from rxjs

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
NgRx 9.2.0
Angular 8/9.*.*

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

**Comment by alex-okrushko** [comment]
Thanks for the report @DzmVasileusky 

Technically `Observable<never>` would never emit an Action, so that means that this effect shouldn't expect to dispatch it, so that means that it should have a corresponding config of `{dispatch: false}`.

https://stackblitz.com/edit/ngrx-seed-enzi7k?file=src/app/demo.effects.ts

I'd considered this to be a type improvement, which would catch a bug if one by accident always returns EMPTY.

Should there be a case when the Action could be produced, there would be no error:
https://stackblitz.com/edit/ngrx-seed-7zrdoj?file=src/app/demo.effects.ts

Hopefully this makes sense.

**Comment by timdeschryver** [comment]
Thanks @alex-okrushko , if that's the case I don't consider this being a bug - and working as intended.

**Comment by annacieplicka** [comment]
what if I want to do sth like this?
`  setValidateFieldError$ = createEffect(() => this.actions$.pipe(
    ofType(validateField),
    mergeMap(({ fieldName, fieldValue, additionalData }) => this.ValidationService.validate(fieldName, fieldValue, additionalData)
      .pipe(
        map(() => EMPTY),
        catchError((err) => {
          if (err.status === 400) return of(setValidateFieldError({ fieldName }));
          return EMPTY;
        })
      )
    ),
  ));
`

 map(() => EMPTY), causes an error

**Comment by nawlbergs** [comment]
This is in the [docs for effects](https://ngrx.io/guide/effects):
```js
loadMovies$ = createEffect(() => this.actions$.pipe(
    ofType('[Movies Page] Load Movies'),
    mergeMap(() => this.moviesService.getAll()
      .pipe(
        map(movies => ({ type: '[Movies API] Movies Loaded Success', payload: movies })),
        catchError(() => EMPTY)
      ))
    )
  );
```
Throws errors for me... what am I suppose to return if I don't want to trigger another action?
```js
  loginSuccess$ = createEffect(() => this.actions$.pipe(
    ofType(fromManualLogin.LoginSuccess),
    mergeMap((action: fromManualLogin.LoginSuccess) => {
      this.redirectionManager.redirectToPortal();
      return EMPTY; // <--- ERROR TS2322: Type 'Observable<never>' is not assignable to type 'never'.
    }),
  ));
```

**Comment by timdeschryver** [comment]
@nawlbergs That's why we have an ESLint rule for this 

https://ngrx.io/guide/eslint-plugin/rules/prefer-effect-callback-in-block-statement

**Comment by alex-okrushko** [comment]
@nawlbergs some IDEs will should it correctly (e.g. Webstorm), however VS Code does not.
That's why I suggest to use `createEffect(() => { return this.actions$.pipe(....)});`, basically to have a function body there.

See https://github.com/ngrx/platform/issues/2192
