### ISSUE TITLE
Entity docs can't be found as the chunk is missing

### ISSUE THREAD

**Issue by aravindfz** [ngrx/platform#2582]
![image](https://user-images.githubusercontent.com/22231525/84688183-c5615e00-aef3-11ea-8538-50f6ae1a8e2e.png)

## Other information:

Seems like a build issue that the chunk is not found in the server

## I would be willing to submit a PR for the docs :heart:

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Thanks for bringing this to our attention @aravindfz.
Strangely, I'm able to navigate to the page, have you tried a (hard) refresh?

**Comment by alex-okrushko** [comment]
Works fine for me too. 🤷‍♂️

**Comment by timdeschryver** [comment]
Feel free to reopen the issue if it doesn't work for you @aravindfz

**Comment by aravindfz** [comment]
@timdeschryver  - I think it is fixed 🎉  thank you
