### ISSUE TITLE
Share store/actions between 2 angular apps

### ISSUE THREAD

**Issue by Lata702** [ngrx/platform#2583]
Hello All!
> 
> I am here because I need some support on something I need to do.
> 
> I am working on a project using NG4 + ngrx/store. We are integrating NG4 modules into existing webapp and so we are bootstrapping several modules in dynamic tags:
> 
> ```
> platformBrowserDynamic().bootstrapModule(App1Module)); // bootstrap AppModule in '<app1>'
> platformBrowserDynamic().bootstrapModule(App2Module); // bootstrap AppModule in '<app2>'
> ```
> 
> App1 and App2 are basically 2 features (Search and display results for example). They are not in the same tree and not in the same app. They can't communicate through Angular.
> 
> I would like to be able to share store between 1 and 2.
> 
> Is it possible?
> Do I need to have 2 states?
> Do I need to pass actions from 1 to 2?
> Do you have any advise, hint, how it is possible to achieve that?
> 
> 
> 
> Many thanks!
> 
> LATA

**Comment by brandonroberts** [comment]
Hello @Lata702, if you need support, the best place is our [gitter channel](https://github.com/ngrx/platform)

**Comment by Lata702** [comment]
> Hello @Lata702, if you need support, the best place is our [gitter channel](https://github.com/ngrx/platform)

i have two angular apps
