### ISSUE TITLE
Ngrx/store for sharing state between  angular apps

### ISSUE THREAD

**Issue by Lata702** [ngrx/platform#2589]
Hi everyone,

I want to share user details from angular project1 to angular project2 using ngrx/store .
how can i do please help me with sample example.

thanks in advance..!

**Comment by timdeschryver** [comment]
Opening a same issue when the first one gets closed won't help @Lata702 (#2583)
We try to keep issues that's causing bugs here, for support, the best place is on [stackoverflow (with a ngrx tag)](https://stackoverflow.com/questions/tagged/ngrx) or the [gitter channel](https://gitter.im/ngrx/platform
