### ISSUE TITLE
Docs: Document runAfterBootstrap for bootstrapping effects with APP_INITIALIZER or provide recommended approach

### ISSUE THREAD

**Issue by bmarti44** [ngrx/platform#2591]
We had a lot of trouble implementing effects that rely on an APP_INITIALIZER to load config into a service. It seems @brandonroberts has provided a solution at the end of the following PR, but the API is not well documented.

https://github.com/ngrx/platform/issues/931 

At the end of the PR, there is still some confusion on how to implement (to be fair, there is a solution there though, but I also did miss it).

We spoke with @MikeRyanDev about using effects with APP_INITIALIZER, and he pointed us towards the `runAfterBootstrap` API

https://github.com/ngrx/effects/blob/master/src/effects.module.ts#L31

After using this API, everything works great! Having this documented better (or providing a recommendation/approach that the ngrx team approves of) would help a lot with the headache people are having getting APP_INITIALIZERS and effects working (our team struggled with this for a few months).

## I would be willing to submit a PR for the docs :heart:

[X ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
I agree that this should be documented for those who want some effects to wait until bootstrap. We removed the API previously because it caused users to miss actions that were dispatched too early.

**Comment by Huarru** [comment]
@bmarti44 @brandonroberts I am still unclear how do you use runAfterBootstrap API? This is not available in the latest NGRX effects? Could either of you help explain how you resolved the issue with the APP_INITIALIZER  and NGRX effects?

**Comment by vladtheimpala** [comment]
We get a lot of trouble on my app regarding root effects instantiated before APP_INITIALIZER. @brandonroberts is there and what is the recommended way to solve my issue ? thanks for support
