### ISSUE TITLE
Quick question: EffectsTestingModule?

### ISSUE THREAD

**Issue by NathanWalker** [ngrx/platform#26]
Perhaps I am missing something obvious (likely so!), but is the `EffectsTestingModule` and testing barrel just not currently being published with the nightly builds?
https://github.com/ngrx/effects-builds

I have been loving the 4.x api and was trying to test some effects but realized the `@ngrx/effects/testing` bundle does not exist in these builds?

Forgive me if I'm missing something incredibly obvious!

**Comment by MikeRyanDev** [comment]
They are not yet published. We working on a refreshed Effects api in #24 and will likely revisit testing after that lands.

**Comment by NathanWalker** [comment]
Thank you!

**Comment by msandeeprao38** [comment]
I spent a whole day on this issue and later read this thread. Lesson learned, go through the issue list ASAP.
