### ISSUE TITLE
The docs state "@ngrx/store ships with five (5) built-in runtime checks:", but then the example shows 6:

### ISSUE THREAD

**Issue by TheParad0X** [ngrx/platform#2615]
## Minimal reproduction of the bug/regression with instructions:

The docs state "@ngrx/store ships with five (5) built-in runtime checks:", but then the example shows six (6):

```
StoreModule.forRoot(reducers, {
      runtimeChecks: {
        strictStateImmutability: true,
        strictActionImmutability: true,
        strictStateSerializability: true,
        strictActionSerializability: true,
        strictActionWithinNgZone: true,
        strictActionTypeUniqueness: true,
      },
    }),
```

**Comment by timdeschryver** [comment]
Do you want to update the docs @TheParad0X ?
I think we can just remove the number.

**Comment by TheParad0X** [comment]
@timdeschryver my first PR ever on Github.
https://github.com/ngrx/platform/pull/2618
