### ISSUE TITLE
Selector with optional prop returns incorrect memoized result

### ISSUE THREAD

**Issue by JohnKis** [ngrx/platform#2625]
## Minimal reproduction of the bug/regression with instructions:
- Create a selector that accepts optional multiplier. E.g.:
```ts
export const getCount = createSelector(
  getCounterState,
  (counter, props) => props ? counter * props : counter
);
```
- Use the selector once without properties
```ts
this.counter = this.store.pipe(select(fromRoot.getCount));
```
- Use the selector again with a property
```ts
this.counterTimesTwo = this.store.pipe(select(fromRoot.getCount, 2));
```
- Subscribe to both observables
- Observe that both observables last emitted value is the multiplied value.

Interestingly, if I add an explicit `null` prop to the first select (e.g.: `this.counter = this.store.pipe(select(fromRoot.getCount, null));`), the issue doesn't happen

[Stackblitz example](https://stackblitz.com/edit/ngrx-seed-nmqbpb)

## Expected behavior:
The last emitted value of `this.counter` should be the un-multiplied value and the last emitted value of `this.counterTimesTwo` should be the multiplied value.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
- NGRX version: 9.2.0
- Angular version: 10.0.4
- Node version: v10.16.3
- Operating system: macOS Catalina 10.15.5

## Other information:
I know that I could probably use a selector facade the solve this issue, but as I understand it, it shouldn't be required.

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

**Comment by timdeschryver** [comment]
When you're using selectors with props you should create a factory function for the selector. This to make 2 instances of the selector, otherwise it will re-use the same instance of the selector. See the [updated example](https://stackblitz.com/edit/ngrx-seed-2iv74m?file=src%2Fapp%2Fapp.component.ts).

See the ["Using selectors with props" docs](https://ngrx.io/guide/store/selectors#using-selectors-with-props) for more info

**Comment by JohnKis** [comment]
I understand that I can use a factory function to solve this issue. One problem with this though is that on every use, a new selector instance will be created regardless whether the props are the same or not.

**Comment by JohnKis** [comment]
The aforementioned problem can be solved via converting the selector to a factory function that caches selector instances based on the props. See the [updated example](https://stackblitz.com/edit/ngrx-seed-icwpha).

It's a bit more boilerplate yet again, but it can be useful to keep memory usage down if the same selector is invoked the same props at different places in the app.
