### ISSUE TITLE
@ngrx/store: warn on duplicate action names.

### ISSUE THREAD

**Issue by henness17** [ngrx/platform#2626]
## Describe any alternatives/workarounds you're currently using
Right now, the developer has to find the root problem of the bugs that come of duplicate action names.

It would be nice to get a console warning when NgRx detects duplicate action names.

## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ X] No

**Comment by timdeschryver** [comment]
We introduced this in the last version of NgrRx.
It's currently an opt-in runtime check, see the [docs](https://ngrx.io/guide/store/configuration/runtime-checks#strictactiontypeuniqueness) for more info.

**Comment by henness17** [comment]
Thank you.
