### ISSUE TITLE
Getting 'Immer' (enablees5()) error when deployed in MFE

### ISSUE THREAD

**Issue by raju1488** [ngrx/platform#2634]
Hi,

  I am getting ERROR Error: [Immer] The plugin for 'ES5' has not been loaded into Immer. To enable the plugin, import and call `enableES5()` when initializing your application.when deployed as Micro Frontend application(Angular 7) and browsed through Internet explorer.Is there any workaround or polyfills to be installed. 
        "@ngrx/effects": "^9.1.2",
        "@ngrx/store": "^9.1.2",
        "@ngrx/store-devtools": "^9.1.2",

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

**Comment by timdeschryver** [comment]
Why do you think this is an issue in the NgRx repository?
This repository doesn't have a dependency on NgRx.

I'm going to close this issue, if it's "our fault" please provide more info.

See https://github.com/immerjs/immer/issues/610, perhaps it can help.
