### ISSUE TITLE
OnIdentifyEffects does not work with Angular 10

### ISSUE THREAD

**Issue by aram-m** [ngrx/platform#2639]
I'm getting  No suitable injection token for parameter 'effectIdentifier' of class 'SomethingEffects'.
just try to add this doc example in some effect
```
class EffectWithIdentifier implements OnIdentifyEffects {
 constructor(private effectIdentifier: string) {}

 ngrxOnIdentifyEffects() {
   return this.effectIdentifier;
 }
```
## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

` "@angular/animations": "~10.0.2",
    "@angular/cdk": "^10.0.1",
    "@angular/common": "~10.0.2",
    "@angular/compiler": "~10.0.2",
    "@angular/core": "~10.0.2",
    "@angular/fire": "^6.0.0",
    "@angular/forms": "~10.0.2",
    "@angular/material": "^10.0.1",
    "@angular/material-moment-adapter": "^10.0.1",
    "@angular/platform-browser": "~10.0.2",
    "@angular/platform-browser-dynamic": "~10.0.2",
    "@angular/router": "~10.0.2",
    "@ngrx/effects": "^9.1.2",
    "@ngrx/entity": "^9.1.2",
    "@ngrx/router-store": "^9.1.2",
    "@ngrx/schematics": "^9.1.2",
    "@ngrx/store": "^9.1.2",
    "@ngrx/store-devtools": "^9.1.2",`

Thanks for NGRX <3

**Comment by timdeschryver** [comment]
Did this work on previous versions of Angular?
The problem is that you will have to provide something for `effectIdentifier`. The example in the docs came from the need of creating and registering the effect manually (and not via `forRoot` or `forFeature`), see https://github.com/ngrx/platform/issues/1443 for more context.

**Comment by aram-m** [comment]
@timdeschryver my bad closing the issue, thanks!!
