### ISSUE TITLE
Angular libraries that rely on @ngrx/component can't be compiled when Ivy is disabled

### ISSUE THREAD

**Issue by cherurg** [ngrx/platform#2643]
Angular libraries that rely on `@ngrx/component` can't be compiled when Ivy is disabled. `ng build lib` leads to error:

```

ERROR: Unexpected value 'undefined' exported by the module 'ReactiveComponentModule in /Users/karpovad/recogizer/sandbox/ngrx-component-store/node_modules/@ngrx/component/ngrx-component.d.ts'
Unexpected value 'undefined' declared by the module 'ReactiveComponentModule in /Users/karpovad/recogizer/sandbox/ngrx-component-store/node_modules/@ngrx/component/ngrx-component.d.ts'
Can't bind to 'ngrxLet' since it isn't a known property of 'ng-container'.
1. If 'ngrxLet' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
    <ng-container [ERROR ->]*ngrxLet="data$ as data">
      <p>lib works! {{ data }}</p>
    </ng-container>
")
Property binding ngrxLet not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("
    [ERROR ->]<ng-container *ngrxLet="data$ as data">
      <p>lib works! {{ data }}</p>
    </ng-container>
")

An unhandled exception occurred: Unexpected value 'undefined' exported by the module 'ReactiveComponentModule in /Users/karpovad/recogizer/sandbox/ngrx-component-store/node_modules/@ngrx/component/ngrx-component.d.ts'
Unexpected value 'undefined' declared by the module 'ReactiveComponentModule in /Users/karpovad/recogizer/sandbox/ngrx-component-store/node_modules/@ngrx/component/ngrx-component.d.ts'
Can't bind to 'ngrxLet' since it isn't a known property of 'ng-container'.
1. If 'ngrxLet' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
    <ng-container [ERROR ->]*ngrxLet="data$ as data">
      <p>lib works! {{ data }}</p>
    </ng-container>
")
Property binding ngrxLet not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("
    [ERROR ->]<ng-container *ngrxLet="data$ as data">
      <p>lib works! {{ data }}</p>
    </ng-container>
")

```

## Minimal reproduction of the bug/regression with instructions:

I've prepared a simple repository with Readme file that describes details https://github.com/cherurg/ngrx-component-compilation-bug

## Expected behavior:

Compilation of libraries that rely on `@ngrx/component` should work when Ivy is disabled. Ivy still isn't recommended in Angular 10 libraries. It would be great if it works with Angular 9 too however I understand that `@ngrx/component` states Angular 10 as peer dependency. 

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

@ngrx/component 10.0.0-beta.1
Angular 9, 10 (didn't try earlier versions)
MacOS 10.15.3
Node v12.16.2

## Other information:

As a super urgent workaround for this problem, I forked `@ngrx/component` internally with the same code but I removed all barrel files (`index.ts`). When I use the fork as a dependency of Angular library, then compilation via `ng build lib` works as expected for me.

The structure of the forked `@ngrx/component`:

```
.
├── lib
│   ├── core
│   │   ├── cd-aware
│   │   │   ├── cd-aware_creator.ts
│   │   │   └── creator_render.ts
│   │   └── utils
│   │       └── has-zone.ts
│   ├── let
│   │   └── let.directive.ts
│   ├── push
│   │   └── push.pipe.ts
│   └── reactive-component.module.ts
└── public-api.ts

```

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

**Comment by cherurg** [comment]
Thank you for `@ngrx/component-store`! I find it a very powerful abstraction. For sure, `@ngrx/component` is a great addition to the store

**Comment by criskrzysiu** [comment]
Now that I see Your error I think we have something similar in our project with angular 9 libraries. So maybe it's actually an angular 9+ problem?

**Comment by brandonroberts** [comment]
I would say the first step would be to remove the barrels we have in the ngrx/component package, and export the symbols directlly.
