### ISSUE TITLE
Updating entity record

### ISSUE THREAD

**Issue by abnemo** [ngrx/platform#2644]
Hello everybody,

I already tried trying to ask for help on StackOverflow and gitter, but without success.
I am trying to understand, why does getByKey() method updating the existing entity only partially and not by replacing the whole object, even if the new object misses some attributes. 
For example, when the client is receiving an item changed event from the backend, because someone removed the value of an object's property. In this case, the backend I have to work with would remove undefined properties from the object in the response.
Is there any possibility to update the whole entity?

Thank you for your help!

**Comment by timdeschryver** [comment]
You can use `setOne`.
https://ngrx.io/guide/entity/adapter#adapter-collection-methods
