### ISSUE TITLE
@ngrx/router-store is not in the npm registry

### ISSUE THREAD

**Issue by ShahnavazKazi** [ngrx/platform#2649]
npm install for @ngrx/router-store is failing. It's not installing the latest or specific version and instead gives below error:

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@ngrx%2frouter-store - Not found
npm ERR! 404
npm ERR! 404  '@ngrx/router-store@9.0.0' is not in the npm registry.

## Minimal reproduction of the bug/regression with instructions:

npm i @ngrx/router-store@9.0.0 --save
npm i @ngrx/router-store

## Expected behavior:

Package should get installed.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

Angular 7.0.0.0
Node > 10.16

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by jannikfr** [comment]
Same for @ngrx/store and @ngrx/effects.

**Comment by caohothang** [comment]
same....

**Comment by santoshyadavdev** [comment]
this is due to npm is down.
