### ISSUE TITLE
Not Found - GET https://registry.npmjs.org/@ngrx%2fstore - Not found

### ISSUE THREAD

**Issue by mihailstefanov** [ngrx/platform#2650]
npm i @nrgx/store            
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@nrgx%2fstore - Not found
npm ERR! 404 
npm ERR! 404  '@nrgx/store@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mihail/.npm/_logs/2020-08-06T11_27_18_512Z-debug.log

**Comment by cgmferrier** [comment]
@mihailstefanov seems to work again now for me

**Comment by nwcas** [comment]
Happening with other packages so probably npm doing server work.

**Comment by mihailstefanov** [comment]
I see, so let's close it for now, even I still get error. May be depends on the region.

**Comment by MarcScheib** [comment]
Check https://status.npmjs.org/ for server issues.
