### ISSUE TITLE
Add tokens and functions used in providers array in public_api

### ISSUE THREAD

**Issue by Grayfox12** [ngrx/platform#2655]
I have a problem when taking out a feature module in the angular library. I cant use StoreModule.forFeature() and EffectsModule.forFeature(), cause compiler  said "not use functions in decorators". And i cant do static injection through providers syntax, because some tokens, like _STORE_FEATURES, are private. Import from src folder lead to error " in the target entry-point has missing dependencies".

## Describe any alternatives/workarounds you're currently using
Now I have to use dirty trick like 
```
import {
    combineReducers,
    FEATURE_REDUCERS,
    STORE_FEATURES,
    StoreFeatureModule,
    ɵngrx_modules_store_store_bh as _actionTypeUniquenessCheck,
    ɵngrx_modules_store_store_m as _FEATURE_REDUCERS,
    ɵngrx_modules_store_store_n as _FEATURE_CONFIGS,
    ɵngrx_modules_store_store_o as _STORE_FEATURES,
    ɵngrx_modules_store_store_p as _FEATURE_REDUCERS_TOKEN,
    ɵngrx_modules_store_store_s as _ACTIVE_RUNTIME_CHECKS,
    ɵngrx_modules_store_store_t as _ACTION_TYPE_UNIQUENESS_CHECK,
    ɵngrx_modules_store_store_v as _createFeatureStore,
    ɵngrx_modules_store_store_w as _createFeatureReducers
} from "@ngrx/store";
import {
    EffectsFeatureModule,
    USER_PROVIDED_EFFECTS,
    ɵngrx_modules_effects_effects_b as createEffects,
    ɵngrx_modules_effects_effects_g as _FEATURE_EFFECTS,
    ɵngrx_modules_effects_effects_h as FEATURE_EFFECTS
} from "@ngrx/effects";
```
token (_STORE_FEATURES) and functions(_createFeatureStore,_createFeatureReducers) critically needed, because _STORE_FEATURES inject in constructor of StoreFeatureModule, and functions create providers.
## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
Can you provide some more concrete examples of what you're trying to do here? We don't want to expose those tokens, as they are meant for internal use.

**Comment by Grayfox12** [comment]
I want to separate feature module from project at angular library module with ng-packagr. So i have typical store folder structure with state, effects, actions, reducers and selectors. Describe feature module like this
```
@NgModule({
    imports: [
        StoreModule.forFeature('feature', {someValue: someValueReducer}),
        EffectsModule.forFeature([...]),
        ...
    ],
    declarations: [],
    ...
})
export class FeatureModule {}
```

my ngpackagr look like this
```
{
    "$schema": "ng-packagr/ng-package.schema.json",
    "lib": {
      "entryFile": "public_api.ts"
    }
  }
```
and in angular.json config object
```
{
        "root": "src",
        "projectType": "library",
        "architect": {
            "build": {
            "builder": "@angular-devkit/build-ng-packagr:build",
            "options": {
                "project": "src/.../ng-package.json",
                "tsConfig": "src/.../tsconfig.lib.json"
            }
            }
        }
      },
```
When you try to run ng build in this project you get error:
```
 Function calls are not supported in decorators but 'forFeature' was called in 
```
As i know, all you can do is change the description of feature module like this
```
@NgModule({
    imports: [
        StoreFeatureModule,
        EffectsFeatureModule
        ...
    ],
    providers:[],
    declarations: [],
    ...
})
export class FeatureModule {}
```
and repeat the steps from forFeature function in the providers part. Most of tokens from this part i can init by myself, but this ones token (_STORE_FEATURES) and functions(_createFeatureStore,_createFeatureReducers) you use it in the future.

**Comment by brandonroberts** [comment]
Just some additional context here, but that's correct that you can't use `createReducer` directly in `StoreModule.forFeature()` when building with View Engine. In order to make this compatible, you need to wrap it in an exported function.

```ts
const _someValueReducer = createReducer(initialState);

export function someValueReducer(state: State | undefined, action: Action) {
  return _someValueReducer(state, action);
} 
```

That should allow you to build and ship the library without exporting all these tokens publicly.

**Comment by Grayfox12** [comment]
if I understand correctly the module will then look like this
```
@NgModule({
    imports: [
        StoreModule.forFeature('feature',someValueReducer),
        EffectsModule.forFeature([...]),
        ...
    ],
    declarations: [],
    ...
})
export class FeatureModule {}
```
but compiler got a error not on function in forFeature function. It got error on call forFeature function directly.
And if you comment line with StoreModule or move line with EffectsModule before StoreModule you got a error:
```
ERROR: Error during template compile of 'FeatureModule '
  Function calls are not supported in decorators but 'EffectsModule' was called.

An unhandled exception occurred: Error during template compile of 'FeatureModule '
  Function calls are not supported in decorators but 'EffectsModule' was called.
```
And there is no function in EffectsModule.forFeature(). it take array of classes

**Comment by Grayfox12** [comment]
Hey, any thoughts about my exapmle?

**Comment by brandonroberts** [comment]
I'm still on the stance that those tokens should remain internal to the package. If you can provide a reproduction in a GitHub repo, or reproductions steps from a new project we could take a further look. There are other libraries providing there own slice of state and effects, so I'd like to know what the difference is in this case.

**Comment by Grayfox12** [comment]
https://github.com/ngrx/platform/files/5056131/sample.zip
I attached little sample project correspond to my library

**Comment by brandonroberts** [comment]
Will you create a GitHub repo with the files in the zip file?

**Comment by Grayfox12** [comment]
I'm sorry, I misinterpreted your request. 
https://github.com/Grayfox12/ngrx-sample-lib
it's part of library, so there is many subfolders

**Comment by Grayfox12** [comment]
Hey, any thoughts about https://github.com/Grayfox12/ngrx-sample-lib?

**Comment by brandonroberts** [comment]
Linking https://github.com/ngrx/platform/issues/2768#issuecomment-720145943 for reference as it may be an upstream issue
