### ISSUE TITLE
EntityStateAdapter is not documented in API

### ISSUE THREAD

**Issue by abdulkareemnalband** [ngrx/platform#2664]
Search for `EntityStateAdapter` in ngrx.io , we don't get any results

**Comment by brandonroberts** [comment]
Thanks @abdulkareemnalband. Its `EntityAdapter` https://ngrx.io/guide/entity/adapter

**Comment by abdulkareemnalband** [comment]
@brandonroberts Yes it is documented in guide , but not in https://ngrx.io/api

**Comment by alex-okrushko** [comment]
@abdulkareemnalband it's there too

https://ngrx.io/api/entity/EntityAdapter

**Comment by abdulkareemnalband** [comment]
@alex-okrushko  but it does not include methods defined in  `EntityStateAdapter` like `addMany`

**Comment by timdeschryver** [comment]
@abdulkareemnalband those can be found at https://ngrx.io/api/data/EntityCollectionReducerMethods

**Comment by abdulkareemnalband** [comment]
@timdeschryver  I'm not sure but it looks like that is related to `@ngrx/data` , not `@ngrx/entity` package

**Comment by timdeschryver** [comment]
Oh shoot, you're right 😅

**Comment by timdeschryver** [comment]
It [isn't exported](https://github.com/ngrx/platform/blob/master/modules/entity/src/index.ts) and that's why it isn't visible in the docs.

**Comment by abdulkareemnalband** [comment]
If `EntityStateAdapter` is internal and `EntityAdapter` is public API , 
I think it those methods can be documented here https://ngrx.io/api/entity/EntityAdapter
