### ISSUE TITLE
RouterStateSerializer not found in @ngrx/router-store v4.0.2

### ISSUE THREAD

**Issue by joswalt** [ngrx/platform#267]
I'm submitting a bug report. The example-app shows that RouterStateSerializer is an export from @ngrx/router-store. I even searched the UMD file for the router-store and could not find any reference to RouterStateSerializer.

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## What is the current behavior?
Module '"E:/_Dev/TestApp/node_modules/@ngrx/router-store/router-store
"' has no exported member 'RouterStateSerializer'.

## Expected behavior:
RouterStateSerializer should be found as an export.

## Minimal reproduction of the problem with instructions:
Installed following versions:
@ngrx/store - v4.0.2
@ngrx/effects - 4.0.2
@ngrx/router-store - 4.0.2
@ngrx/store-devtools - 4.0.0

**Comment by denismorozov** [comment]
RouterStateSerializer is not in 4.0.2.
It's in master if you choose to go for the nightly build: `yarn add github:ngrx/router-store-builds`

**Comment by brandonroberts** [comment]
This will be included in the next release
