### ISSUE TITLE
Pass NavigationError to the ROUTER_ERROR action payload as object

### ISSUE THREAD

**Issue by aidanxyz** [ngrx/platform#2672]
When `ROUTER_ERROR` is dispatched, the `event` property of the payload contains only `id ` and `url`. With `RouterState.Full` the error is provided [as a string](https://github.com/ngrx/platform/blob/de02aa73c9fe4d5ac404992c75afd7a77fa3f767/modules/router-store/src/router_store_module.ts#L305) which makes it useless if I want to extract details from the error.
What is the reason we can't have it in the payload as an object? The `Router.events` provides it as is, for instance.

**Comment by brandonroberts** [comment]
The error object is not immutable so it will cause the checks to fail. If you want the full error, you can extract it from the router events.
