### ISSUE TITLE
REQUEST FOR DOCUMENT FAILED.

### ISSUE THREAD

**Issue by LYSSION** [ngrx/platform#2676]
We are unable to retrieve the "**api/store/On**" page at this time. Please check your connection and try again later.

**Comment by almamlaka** [comment]
![image](https://github.com/ngrx/platform/assets/59602921/21877c30-9d72-49f2-8bc0-f8d67a428597)

website documentation is not working.

**Comment by Exac** [comment]
Still broken as of January 2026.

<img width="2506" height="1388" alt="Image" src="https://github.com/user-attachments/assets/889630c9-ac27-451f-9d01-2ef3c2433e39" />

**Comment by brandonroberts** [comment]
> Still broken as of January 2026.
> 
> <img width="2506" height="1388" alt="Image" src="https://github.com/user-attachments/assets/889630c9-ac27-451f-9d01-2ef3c2433e39" />

You need to do a hard refresh on the docs. We've deployed a new docs site.
