### ISSUE TITLE
How do we calculate span of an effect globally

### ISSUE THREAD

**Issue by ssrm** [ngrx/platform#2677]
Hey, can someone tell me is there any we can calculate total time taken by an effect globally (not on every effect).

**Comment by alex-okrushko** [comment]
Hi @ssrm. Not sure I understand the question - effects function for the entire lifespan of the application (unless they are lazyloaded, unhandled errors, manually shut down or something similar)

Btw, issue tracker is not the best place for questions. We have:
* [Stackoverflow](https://stackoverflow.com/questions/tagged/ngrx)
* [Discord server](https://discord.gg/gCEj4zC)
* [Gitter](https://gitter.im/ngrx/platform)
