### ISSUE TITLE
@ngrx/router-store selectRouteData returns always empty

### ISSUE THREAD

**Issue by greg-md** [ngrx/platform#2680]
## Minimal reproduction of the bug/regression with instructions:

Reproduced: https://stackblitz.com/edit/ngrx-seed-s6jcdy?file=src%2Fapp%2Ftest.component.ts

I've followed all the steps from the https://ngrx.io/guide/router-store, but `selectRouteData` doesn't return data from routes resolvers. Am I missing something that is not documented?

```ts
  constructor(
    private route: ActivatedRoute,
    private store: Store<AppState>
  ) {}

  readonly center$ = this.store.select(selectRouteData).pipe(
    tap(data => {
      console.log('selectRouteData', data, this.route.snapshot);
    }),
  );
```

But data exists in the `ActivatedRoute` snapshot.

<img width="737" alt="Screen Shot 2020-08-21 at 12 03 30" src="https://user-images.githubusercontent.com/10551984/90873273-914c6280-e3a6-11ea-92ad-d5d6ce5b4cb0.png">

## Expected behavior:

`selectRouteData` should return data from activated route.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

Latest versions.

**Comment by greg-md** [comment]
@timdeschryver is there an active template for ngrx version 10 in stackblitz? I couldn't find one. Basically I did everything from the docs.

1. Installed `StoreRouterConnectingModule` is app module;
```ts
StoreModule.forRoot(appReducers),
StoreRouterConnectingModule.forRoot(),
```
2. Added `routerReducer` in the app reducers.
```ts
import { ActionReducerMap } from '@ngrx/store';
import { routerReducer, RouterReducerState } from '@ngrx/router-store';

export type AppState = {
  router: RouterReducerState<any>;
};

export const appReducers: ActionReducerMap<AppState> = {
  router: routerReducer,
};
```
3. Exported router selectors:
```ts
export const selectRouter = createFeatureSelector<AppState, RouterReducerState>('router');

export const {
  selectRouteData,      // select the current route data
} = getSelectors(selectRouter);
```
4. Then tried to select route data:
```ts
readonly data$ = this.store.select(selectRouteData);
```

And, it's always empty.

**Comment by timdeschryver** [comment]
@greg-md  there is this one, https://stackblitz.com/edit/ngrx-seed?file=src/app/app.component.ts.

**Comment by greg-md** [comment]
@timdeschryver Thanks! Here it is: https://stackblitz.com/edit/ngrx-seed-s6jcdy?file=src%2Fapp%2Ftest.component.ts

**Comment by timdeschryver** [comment]
So the problem are resolvers. 

```ts
const routes: Routes = [
  {
    path: '',
    component: TestComponent,
    // 👇 this doesn't selected
    resolve: {
      test: TestResolver,
    },
    // 👇 this gets selected
    data: {
      id: 1
    }
  },
];
```

**Comment by greg-md** [comment]
@timdeschryver right. I think they should be included as well in `selectRouteData`

**Comment by timdeschryver** [comment]
I'm not very familiar with it, but it seems that Angular doesn't expose the data from the resolved in the router events. So if Angular doesn't expose it, I don't know if we can...

![image](https://user-images.githubusercontent.com/28659384/91045888-d3300f80-e617-11ea-97f5-76356db4408f.png)

**Comment by timdeschryver** [comment]
@greg-md do you know how we could include the `data` in the payload?

**Comment by bramvandervoet** [comment]
related to #358

**Comment by bramvandervoet** [comment]
navigationActionTiming: NavigationActionTiming.PostActivation

Adding this config seems to help but not sure regarding the remarks by Brandon in 358.
