### ISSUE TITLE
Component: Using ng add command fails with missing schematics error

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#2683]
## Minimal reproduction of the bug/regression with instructions:

1. Generate a new project
2. Run `ng add @ngrx/component`
3. Notice the error

`
The package that you are trying to add does not support schematics. You can try using a different version of the package or contact the package author to add ng-add support.
`

The `schematics` entry is missing from the `package.json`. An example can be found here `https://github.com/ngrx/platform/blob/master/modules/store/package.json#L27`

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by Jefiozie** [comment]
If is fine by you @brandonroberts I will make a PR for this

**Comment by brandonroberts** [comment]
Go for it
