### ISSUE TITLE
Is there way @ngrx/component-store can be viewed on Redux DevTools

### ISSUE THREAD

**Issue by dean-g** [ngrx/platform#2692]
I have both ngrx store as well as component store. my component store is not available on redux dev tool. 

Is there way @ngrx/component-store can be viewed on Redux DevTools
 https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en ? 

Please advise.

**Comment by katesky** [comment]
Hi, I remember from the presentation of the component-store that it will not be part of the DevTool, because Actions are not part of the indirection of the Component Store therefor it's not used by DevTools. 
You can see the detailed explanation here: https://ngrx.io/guide/component-store/comparison

**Comment by brandonroberts** [comment]
As @katesky said, there won't be built in support.

**Comment by dean-g** [comment]
@katesky @brandonroberts Do you have any suggestion towards debugging the individual stores ?

**Comment by alex-okrushko** [comment]
@dean-g 
Generally breakpoints should work fine - since there's no actions, and the state is more localized it should be easier to set them up.
`tap(console.log)` is another quick way.

Also @cartant is [working on the debugging tools for RxJS](https://www.youtube.com/watch?v=GG77Lsi-yaE) in general - once that dev extension is released it should be possible to track the moving pieces within ComponentStore(s) as well.

**Comment by dean-g** [comment]
thanks @alex-okrushko.

**Comment by AshMcConnell** [comment]
If all you want is to view the component state then you can hook it up to a global store pretty quickly.  Diffs also work

Here is what I did: -
- Create an action to update component state, it takes a component name and the updated state
- Create a reducer with an empty object as its initial state that sets the state based on the componentName
- Create a helper object that takes an observable / component name and the global store - this turns adding a new component into the global state a 1 liner.  i.e. `linkToGlobalState(this.vm$, 'Result Panels', this.store);` where `vm` is the viewModel and `store` is the store that is injected into the component store
- Added the componentStateReducer into the App Module imports like so: - 
```
StoreModule.forRoot({ componentState: componentStateReducer}),
StoreDevtoolsModule.instrument({
   maxAge: 25, // Retains last 25 states
   logOnly: true, // Restrict extension to log-only mode
}),
```

Here is the majority of the code needed, I'm fairly new to ngrx/store and component store, so I'm sure it could be more elegant 😄 .  That isEqual in there might be quite severe on performance with big states, but here it is, I hope some of you find it useful  👍 

```
import {createAction, createReducer, on, props, Store} from '@ngrx/store';
import {isEqual} from 'lodash';
import {Observable} from 'rxjs';
import {distinctUntilChanged} from 'rxjs/operators';

export const updateComponentState = createAction(
    '[Component Store] Update Action',
    props<{ componentName, componentState }>()
);

export const initialState: any = {};

export const componentStateReducer = createReducer(
    initialState,
    on(updateComponentState, (state, {componentName, componentState}) => {
        return ({[componentName]: {...componentState}});
    })
);

export const linkToGlobalState = (componentState$: Observable<any>, componentName: string, globalStore: Store) => {
    componentState$.pipe(
        distinctUntilChanged((prev, next) => isEqual(prev, next))
    ).subscribe(componentState => {
        globalStore.dispatch(updateComponentState({componentName, componentState}));
    });
};
```

**Comment by xianshenglu** [comment]
So, I guess dynamically adding a component store to the global state, so we can still enable the functionality of redux like devtool, time travel, bug tracking?

**Comment by MykolaDiachok** [comment]
> If all you want is to view the component state then you can hook it up to a global store pretty quickly. Diffs also work
> 
> Here is what I did: -
> 
> * Create an action to update component state, it takes a component name and the updated state
> * Create a reducer with an empty object as its initial state that sets the state based on the componentName
> * Create a helper object that takes an observable / component name and the global store - this turns adding a new component into the global state a 1 liner.  i.e. `linkToGlobalState(this.vm$, 'Result Panels', this.store);` where `vm` is the viewModel and `store` is the ngrx/store that is injected into the component store
> * Added the componentStateReducer into the App Module imports like so: -
> 
> ```
> StoreModule.forRoot({ componentState: componentStateReducer}),
> StoreDevtoolsModule.instrument({
>    maxAge: 25, // Retains last 25 states
>    logOnly: true, // Restrict extension to log-only mode
> }),
> ```
> 
> Here is the majority of the code needed, I'm fairly new to ngrx/store and component store, so I'm sure it could be more elegant 😄 . That isEqual in there might be quite severe on performance with big states, but here it is, I hope some of you find it useful 👍
> 
> ```
> import {createAction, createReducer, on, props, Store} from '@ngrx/store';
> import {isEqual} from 'lodash';
> import {Observable} from 'rxjs';
> import {distinctUntilChanged} from 'rxjs/operators';
> 
> export const updateComponentState = createAction(
>     '[Component Store] Update Action',
>     props<{ componentName, componentState }>()
> );
> 
> export const initialState: any = {};
> 
> export const componentStateReducer = createReducer(
>     initialState,
>     on(updateComponentState, (state, {componentName, componentState}) => {
>         return ({[componentName]: {...componentState}});
>     })
> );
> 
> export const linkToGlobalState = (componentState$: Observable<any>, componentName: string, globalStore: Store) => {
>     componentState$.pipe(
>         distinctUntilChanged((prev, next) => isEqual(prev, next))
>     ).subscribe(componentState => {
>         globalStore.dispatch(updateComponentState({componentName, componentState}));
>     });
> };
> ```
> 
> ![image](https://user-images.githubusercontent.com/497941/119888674-90e08980-bf2d-11eb-8c3e-7d438ac43956.png)

so for auto work, only need to add this
`@Injectable()
export class DashboardStore extends ComponentStore<DashboardState> {
  constructor(private globalStore: Store) {
    super(initialState);
    linkToGlobalState(this.state$, 'DashboardStore', this.globalStore);
  }`
