### ISSUE TITLE
RouteNavigationPayload is not serialization-compliant

### ISSUE THREAD

**Issue by s-ve** [ngrx/platform#27]
Currently, [RouteNavigationPayload](https://github.com/ngrx/platform/blob/0beb87c2f76216756d9cdb938eda3afb1db23375/modules/router-store/src/router_store_module.ts#L14-L17) stores a reference to a `RouterStateSnapshot` instance.

`RouterStateSnapshot` is likely to contain circular references (e.g. child routes have pointers to their parent) and thus it prevents navigation actions to be properly encoded as a JSON string.

As mentioned [in this thread](https://github.com/reactjs/redux/issues/437), unserializable actions are not advised as they can lead to compatibility issues with some redux libraries/tools.

Do you plan to address this issue in the future by converting navigation actions into "serialization-compliant" objects  ?

**Comment by Matmo10** [comment]
See https://github.com/ngrx/platform/pull/12

**Comment by s-ve** [comment]
Closing this since it's already being discussed in #12
