### ISSUE TITLE
Reducing number of lines in index.ts file with selectors.

### ISSUE THREAD

**Issue by bbonczek** [ngrx/platform#2706]
Hi,

We're working on a medium size application, that we expect to live for quite a long time. We've been following the same architecture as in the example library app. This is how our state currently looks like:

![image](https://user-images.githubusercontent.com/11254976/92449899-fd0e3800-f1ba-11ea-82cb-76dd841a992b.png)

The **profile** branch is the heart of our application where most of the things happen. The **profile** reducer is equivalent of ```example-app/src/app/books/reducers/index.ts``` in the example application in ngrx repository. It contains reducers for each of our pages (Identity, Temperature, Status....) and reducers that consist of logic universal for 'page-based' profile reducers (layout, turingSocket, cipObjects).

The problem that we have with such an approach is that our profile reducer file (index.ts with selectors) becomes huge very quickly. It gets hard to maintain it. Below there is a short sample of how this file looks like (note that it is currently 840 lines long).

![image](https://user-images.githubusercontent.com/11254976/92451066-896d2a80-f1bc-11ea-9497-08681b3d55d3.png)

It seems that the length of this file is partially caused by the necessary (are they necessary though?) repetitions like:
```
export const getTorqueLimitFormValid = createSelector(
    getAutotuneModalPageState,
    fromAutotuneModalPage.getTorqueFormValidity,
);
```

This selector is already declared in autotuneModalPage reducer:
![image](https://user-images.githubusercontent.com/11254976/92453905-267d9280-f1c0-11ea-84cb-1d3036345e17.png)

The only reason for repeating it here is wrapping it with ```createSelector```.

**Are there some general patterns when using ngrx, that allow you to avoid reducer to become so bloated? Have we missed something in terms of architecture that would allow us to reduce the size of reducer file? Do we need to wrap each of our selectors into the 'createSelector' function? If so, could documentation be updated to reflect some kind of 'recipes' or 'good practices' that would allow you to get that?**

## Other information:
* each of our selectors is used either in component or in effect.
* ngrx dependencies that we're currently using:
```
"@ngrx/effects": "^9.1.2",
"@ngrx/entity": "^9.1.2",
"@ngrx/router-store": "^9.1.2",
"@ngrx/store": "^9.1.2",
"@ngrx/store-devtools": "^9.1.2",
```

## I would be willing to submit a PR for the docs :heart:

[:heavy_check_mark:] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Hi, we (thanks @sassypianist98) are currently revamping the live examples.
You can take a look at #2696 and notice that we introduce `*.selector.ts` files, and remove the `index.ts` file.
I hope this is an answer to your question, if not, feel free to reopen this issue.

**Comment by bbonczek** [comment]
Hi, thanks for the response, it seems like such an approach may help indeed. I have one more question regarding your example, but since it is not really related to this issue I'll ask it in pull request [#2696](https://github.com/ngrx/platform/pull/2696).
