### ISSUE TITLE
Refactor docs from `store.pipe(select(...))` to `store.select(...)`

### ISSUE THREAD

**Issue by alex-okrushko** [ngrx/platform#2710]
I'm suggesting to use `store.select` as the recommended way to select from the Store.
This question is frequently asked - which way to use, and if I'm recommending `store.select` then why the docs have it otherwise?

The reasons why I suggest `store.select` are:
- it's easier to mock for tests with a simple mock object
- it's shorter to write
- having a pipe `select` encourages further addition of other operators. That logic might be better handled in selector itself.

`store.select` was initially deprecated, and then un-deprecated - see some history here: https://github.com/ngrx/platform/pull/1361#issuecomment-430082234

## I would be willing to submit a PR for the docs :heart:

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by wesleygrimes** [comment]
Yes, agreed

**Comment by timdeschryver** [comment]
Because everyone agrees, what about also deprecate the pipeable `select`?
