### ISSUE TITLE
Change detection is not triggered with ngrxPush

### ISSUE THREAD

**Issue by friedrich-ulrich** [ngrx/platform#2712]
## Minimal reproduction of the bug/regression with instructions:

We set up a small sample project https://github.com/friedrich-ulrich/ngrx-test-v10

The component button should update its content with the timer observerable, but does not.

As soon as you add the additional line in the comment block in post.component.html the change detection gets trigger even for the ngrxPush-pipe above.

## Expected behavior:

The content should update with ngrxPush alone.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

ngrx : 10.0.0
Angular: 10.1.1
node: 12.18.3
npm: 6.14.6
OS: Windows 10

**Comment by timdeschryver** [comment]
Hi, does this work with the `async` pipe?
Also, I don't see a comment block in [post.component.html](https://github.com/friedrich-ulrich/ngrx-test-v10/blob/master/src/app/post/post.component.html).

**Comment by friedrich-ulrich** [comment]
Hi. Nope. It doesn't work with the async pipe either.
Sorry. I forgot to commit. Now it's there.

**Comment by friedrich-ulrich** [comment]
I added the async variant as a branch. https://github.com/friedrich-ulrich/ngrx-test-v10/tree/async

**Comment by friedrich-ulrich** [comment]
One important detail: zone.js is disabled.

**Comment by va-stefanek** [comment]
Interesting is fact, that I have copied ReactiveComponentModule from NgRx repository to your example, and import it instead of one installed via npm and everything work's fine

**Comment by friedrich-ulrich** [comment]
After updating to angular 10.2.0 the issue was gone. I assume the angular team fixed it somewhere in core.
