### ISSUE TITLE
MockStore: Need to be able to mock selectors with parameters

### ISSUE THREAD

**Issue by cold-gin** [ngrx/platform#2717]
I have the same problem as this ticket, which is closed as "will not fix":

https://github.com/ngrx/platform/issues/2249

It seems that mocking selectors that take parameters would be a very important capability to have for the @ngrx/store test harness. Is there a reason this issue will not be addressed?

Thanks

**Comment by dianabarsan** [comment]
I'm equally curious about this answer. 

You support creating selectors with props: https://ngrx.io/guide/store/selectors#using-selectors-with-props but not mocking them?

**Comment by MichaliEverson** [comment]
Boundries

(KiwiBox)
