### ISSUE TITLE
Typing the schematic-core for reuse in other libraries

### ISSUE THREAD

**Issue by baumblatt** [ngrx/platform#2718]
Hello  @brandonroberts ,

In the version 10.0.0 of `@ngrx/schematics` the module `schematics-core` are shipped without types (*.d.ts) files. 

I know that this a copy from angular cli repo, but there is several customizations that fits with NgRx very well.

I 'm using this to build a schematic project with a few variants and several unrelated features, fell free to take a look at [angular-mat-baum](https://github.com/baumblatt/angular-mat-baum)

## Describe any alternatives/workarounds you're currently using
Copy and paste the entire code.

## Other information:
N/A
@
## If accepted, I would be willing to submit a PR for this feature

[ x ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Hi @baumandm , schematics-core isn't intended to be used this way.
For now, it's considered as an internal library.

If we want to publish it, it would be as its own package (`@ngrx/core-schematics` for example).
I can't find the issue, but IIRC we opened an issue to create a first-class package for `core-schematics` but no one worked on this.

I think that would be great if we would take the time now and publish the core-schematics package if you want to contribute to it.

Thoughts?

**Comment by brandonroberts** [comment]
Re-open if you're still interested in landing this. Otherwise, I'd recommend looking at something like the Nx Devkit for making your own schematics
