### ISSUE TITLE
ngrx schematics disappeared after updating on angular 10.1.2

### ISSUE THREAD

**Issue by dima11221122** [ngrx/platform#2719]
## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
- `@angular/common`: `~10.1.2`,
-  `@angular/compiler`: `~10.1.2`,
-  `@angular/core`: `~10.1.2`,
-  `@angular-devkit/build-angular`: `~0.1001.2`,
- `@ngrx/schematics`: `^10.0.0`,
## Other information:
After upgrade from angular 10.0.14 to angular 10.1.2 ngrx schematics disappeared from the list of available schematics. Reinstalling of node_modules doesn't help

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Thanks for bringing this to our attention @dima11221122 .

What do you mean with "disappeared from the list of available schematics", what command did you run?
