### ISSUE TITLE
Add support for `autoPause` option

### ISSUE THREAD

**Issue by felixschorer** [ngrx/platform#2722]
We've recently introduced NgRx into one of our applications. As our state object grows very large in our integration environment, we needed to deactivate the NgRx devtools. This was necessary as the overhead of sending the state to devtools brought the application to a crawl. The performance hit is caused by serializing the state object to JSON. This is done by the Redux Devtools Extension itself.

The Redux Devtools Extension has a feature to automatically pause recording the state when the devtools are closed. This reduces the overhead to zero as long as the devtools are closed.
[This feature can be activated by setting `autoPause: true` in the options object.](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#autopause)

It is currently not possible to set `autoPause: true` using the `StoreDevtoolsModule`.

## Describe any alternatives/workarounds you're currently using
N/A. Disabling the devtools is currently the only option.

## Other information:
It is not possible to reduce the size of our state object.

## If accepted, I would be willing to submit a PR for this feature

[ x ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Do you want to [create a Pull Request](http://makeapullrequest.com/) for this @felixschorer ?

**Comment by felixschorer** [comment]
@timdeschryver I've created a task for that in our issue tracker.

**Comment by timdeschryver** [comment]
Fyi @felixschorer, you can also use the blocklist for now to exclude those bigger actions.

https://ngrx.io/guide/store-devtools/config#actionssafelist--actionsblocklist
