### ISSUE TITLE
dispatching the same action from multiple components

### ISSUE THREAD

**Issue by learnuser521** [ngrx/platform#273]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## What is the current behavior?
I get the below error when I try to dispatch the same action from more than one component(not dispatching the action at the same time from multiple components ) - 

Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '.....'. Current value: '.....'.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
node : 6.9.5
ngrx : 4.0.2

**Comment by brandonroberts** [comment]
Please provide a reproduction using the following plunker template http://plnkr.co/edit/tpl:757r6L?p=preview or a github repo.

**Comment by learnuser521** [comment]
this was not a bug with ngrx, I thought it is since I was getting the "ExpressionChangedAfterItHasBeenCheckedError" when I dispatched the same action from multiple components.

https://github.com/angular/angular/issues/14748#issuecomment-307291715
https://blog.angularindepth.com/everything-you-need-to-know-about-the-expressionchangedafterithasbeencheckederror-error-e3fd9ce7dbb4

the above helped me resolve the error I was facing.

**Comment by brandonroberts** [comment]
👍

**Comment by ValentinBossi** [comment]
hi
i can provide a reproduction: https://stackblitz.com/edit/stackblitz-starters-lowehc (its a node project. so make sure `npm install` in the "ngrx-dis-exp" directory + `ng serve`)
steps for reproduction:

1. click on "Menu"
2. click on "Order 1"
3. check the console for `ExpressionChangedAfterItHasBeenCheckedError`

i really would not expect this error cause its the nature of an observable to change its value over time. in general i would say i see this setup/steps/process as a valid implementation which should work.
thank you for the help!
