### ISSUE TITLE
@ngrx/data - Allow getWithQuery() to replace the whole state instead of merging into it

### ISSUE THREAD

**Issue by JustDoItSascha** [ngrx/platform#2730]
When using `getWithQuery()` there are situations where I want to replace the whole state instead of extending it. For example if I have a table with filters or pagination and I use getWithQuery to send the new query params to the server. Then the response should replace the whole state, otherwise I can't filter which entries belong to the currently activated filters.

## Describe any alternatives/workarounds you're currently using

I couldn't find any good workaround for this. At first I thought the option `readonly mergeStrategy?: MergeStrategy;` does what I wanted to do, but no. This is just confusing because of the naming.

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by Nvveen** [comment]
I would like to second this. In a more general sense, it's pretty hard to figure out how to replace the cache, or even not use it entirely in the store (the latter I still haven't figured out yet). I'm using @ngrx/data for its removing boilerplate concerning actions, reducers, and selectors, not necessarily client-side caching.

**Comment by timdeschryver** [comment]
I'm no ngrx/data expert but have you tried the following?
 https://ngrx.io/guide/data/entity-actions#entitycache-level-actions

If that's not the case, I think you could (should?) write custom reducers https://ngrx.io/guide/data/entity-reducer#customizing-entity-reducer-behavior

**Comment by JustDoItSascha** [comment]
@timdeschryver Yeah, it's possible to write own reducers, but I also have to write own Effects and if I write everything by myself there is no point in using ngrx/data at all. Especially for a feature which is very common and adds only one option and maybe 2-3 lines of codes. Because the actions are already there. I only have no possibility to say the `getWithQuery` method what it should do.

**Comment by timdeschryver** [comment]
If it can be added to ngrx/data, I think you can create a PR for it and we can discuss there (or here).

**Comment by Nvveen** [comment]
Another possible solution is to inject a custom EntityChangeTracker that just overwrites the state. What would be nice to have in that case is to derive EntityChangeTrackerBase, but there's a possible obstacle with the merging query upserts, because they use the private function `mergeServerUpserts`, whereas the rest of the functions are part of the interface and are public. Were this function to be made protected, one can overwrite any caching behaviour in that change tracker without redefining the rest, and it all it would require is changing the keyword from private to protected.

**Comment by mattbodman** [comment]
I would also love to see this feature added.  I can't think of a use case for the default behaviour.  I alway want to replace the cache with the query results, but maybe that's just me.  In the meantime, as a quick and dirty way around it, I call `clearCache()` on the EntityService, right before the query results are added.

**Comment by brandonroberts** [comment]
If someone wants to create a PR for this that provides some flexibility, that would be good.
