### ISSUE TITLE
@ngrx/data missing forFeature method for lazy loading

### ISSUE THREAD

**Issue by wizardnet972** [ngrx/platform#2732]
I starting to use `@ngrx/data`.

according to docs I need to import `EntityDataModule.forRoot(entityConfig)` in the app.module file to make it work.

but my projects is divide by domain-packages. like: `products`, `reports`, `companies`..  (each of them, loaded during lazy loading). also each of them has `StoreModule.forFeature(..)`.

since `EntityDataModule` has only `forRoot`, it force me to import the modules not in lazy loading way. 

Is there any workaround solution here?

**Comment by timdeschryver** [comment]
We have documented this under https://ngrx.io/guide/data/entity-metadata#register-metadata


```
@NgModule({...})
class LazyModule {
  constructor(eds: EntityDefinitionService) {
    eds.registerMetadataMap(this.lazyMetadataMap);
  }
  ...
}
```

**Comment by allout58** [comment]
The documentation clearly states (maybe updated since this defect) that this will not work for Lazy Loaded modules as a provider is already set and consumed
