### ISSUE TITLE
Inconsistent calls to reducer if calling actions from within an action stream

### ISSUE THREAD

**Issue by v-c-git** [ngrx/platform#2734]
Hi, 

Recently I noticed some strange (to me at least) behavior with ngrx. Frankly, I m not sure if it's a bug or my misunderstanding of how action stream works, but definitely feels odd.

 In general - when an action is submitted in "vanilla redux" redux calls the reducer synchronously and the line after dispatch action will be blocked until after reducer returns. This works as well when I call Ngrx effects from, say a web component. But the moment I try to dispatch an action from within an action stream by either a subscription inside a component or via effect it appears that the call to store.dispatch becomes asynchroneous and the next line of code gets called immediately. 

For example, assuming a reducer prints out 'in reducer' in console this code below when executed from outside of an effect of actions subscription: 

console.log('before dispatch')
store.dispatch(someAction);
console.log('after dispatch');

would print the following

before dispatch
in reducer
after dispatch

However, if the same code were to be executed within an action stream the result would be: 

before dispatch
after dispatch 
in reducer

This is very different from regular calls and could cause issues if for example the reducer was supposed to clear the state before proceeding with the code below action dispatch. 

To make this simpler to follow I created a stackblitz repo here : 

https://stackblitz.com/edit/angular-ivy-eorfi3?file=src/app/ngrx.ts

In this project there are 4 different ways of calling actions and subscribing and the first two work fine whereas the second group returns a "stale object" because dispatch appears to be occuring asyncrhoneously and goes to the next line of code before updating the reducer. 

Does anyone have any ideas or explanation regarding this. Thanks !

**Comment by timdeschryver** [comment]
This is intended because [the state uses](https://github.com/ngrx/platform/blob/10.0.1/modules/store/src/state.ts#L33_ the RxJS [`queueScheduler`](https://rxjs.dev/api/index/const/queueScheduler).

For more info see [this test](https://github.com/ngrx/platform/blob/master/modules/store/spec/edge.spec.ts).
