### ISSUE TITLE
Add milestone or project for NgRx 11

### ISSUE THREAD

**Issue by criskrzysiu** [ngrx/platform#2738]
Would it be possible to add milestone or project for NgRx 11 so it would be clear what is being worked on for next version? 
Also some kind of issue with plan for next release would be great as an alternative.

**Comment by alex-okrushko** [comment]
@criskrzysiu That' s good point  👍
We are actively discussing it with the team.

**Comment by GuateDevIO** [comment]
It would be nice if we can get something about this topic (Ngrx Entity - Nested/Relational data and Normalization) in the coming version of NgRx https://github.com/ngrx/platform/issues/1707

**Comment by jfalmoguera** [comment]
It would be great to have support for the logging of the updatter and effects invocations with the new ComponentStore libray. Once you are used to view actions logs into the console and into the redux dev-tools, personally I feel missing without them.

**Comment by david-shortman** [comment]
This is probably closed by https://github.com/ngrx/platform/commit/c96ed39e45665adf7819b8cce4a2ec288b51ec49

**Comment by peterhe2000** [comment]
@david-shortman @brandonroberts 
Thank you for looking into this thread. 
May i know which task resolve https://github.com/ngrx/platform/issues/1707?
It got most of thumb up in this thread. 
Hope to see there is a documentation about it.
