### ISSUE TITLE
ng g store error

### ISSUE THREAD

**Issue by hansschenker** [ngrx/platform#2739]
command: ng g @ngrx/schematics:store state/AppState
error: newTree.optimize is not a function

Angular cli:
Angular CLI: 10.1.7
Node: 12.10.0
OS: win32 x64

Angular: 10.1.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.7
@angular-devkit/build-angular   0.1001.7
@angular-devkit/core            10.1.7
@angular-devkit/schematics      10.1.7
@angular/cli                    10.1.7
@schematics/angular             10.1.7
@schematics/update              0.1001.7
rxjs                            6.6.3
typescript                      4.0.3

Angular cli for Angular component works:
-----------------------------------------------------------------------------------
command:  ng g c page-not-found -m app
CREATE src/app/page-not-found/page-not-found.component.html (29 bytes)
CREATE src/app/page-not-found/page-not-found.component.ts (306 bytes)
CREATE src/app/page-not-found/page-not-found.component.scss (0 bytes)
UPDATE src/app/app.module.ts (577 bytes)

**Comment by timdeschryver** [comment]
What version of ngrx schematics are you using?

**Comment by hansschenker** [comment]
hi Tim,

thank's for the message!

ngrx/schematics version:
> npm view @ngrx/schematics version
10.0.1

kind regards
Hans
calling from Switzerland

Am Do., 15. Okt. 2020 um 16:51 Uhr schrieb Tim Deschryver <
notifications@github.com>:

**Comment by timdeschryver** [comment]
@hansschenker do you got a reproduction of this? Seems like to be working fine for me

```json
{
  "name": "reproduction",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~10.1.6",
    "@angular/common": "~10.1.6",
    "@angular/compiler": "~10.1.6",
    "@angular/core": "~10.1.6",
    "@angular/forms": "~10.1.6",
    "@angular/platform-browser": "~10.1.6",
    "@angular/platform-browser-dynamic": "~10.1.6",
    "@angular/router": "~10.1.6",
    "@ngrx/schematics": "^10.0.1",
    "@testing-library/angular": "^10.1.1",
    "rxjs": "~6.5.5",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1001.7",
    "@angular/cli": "~10.1.7",
    "@angular/compiler-cli": "~10.1.6",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~3.3.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "4.0.3"
  }
}
```

**Comment by hansschenker** [comment]
Hi Tim,

I installed @ngrx/schematics again and the I did not get the error again!

Thank's a lot for your help!
regards
Hans

Am Do., 15. Okt. 2020 um 19:18 Uhr schrieb Tim Deschryver <
notifications@github.com>:
