### ISSUE TITLE
pending observable in login form improperly evaluated

### ISSUE THREAD

**Issue by helzgate** [ngrx/platform#274]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## What is the current behavior?
Login form doesn't disable after submit

## Other information:
in [this file](https://github.com/ngrx/platform/blob/master/example-app/app/auth/components/login-form.component.ts), there needs to be an else clause wrapped around line 76, otherwise `this.form.enable()` is always true.

**Comment by brandonroberts** [comment]
Thanks for the PR 😉
