### ISSUE TITLE
Store: add ability to create the Store/MockStore outside of the TestBed

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#2745]
Currently you have to use the TestBed  `provideMockStore()` to get an instance of the `MockStore`. This would declare static providers when using `provideMockStore()` so it can be used with `Injector.create()`

## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by amartinelli12** [comment]
I managed to achieve this in my project by the following:
```
import { ActionsSubject } from '@ngrx/store';
import { MockState, MockStore } from '@ngrx/store/testing';

// import local application state model
// import local application state object

const actionSubject$: ActionSubject = new ActionsSubject();
const reducerManager$: ReducerManager = new ReducerManager(null, null, null, () => null); // this could be improved
const mockState$: MockState<LocalApplicationStateModel> = new MockState();

export const MOCK_STORE$: MockStore<LocalApplicationStateModel> = new MockStore(
    mockState$,
    actionSubject$,
    reducerSubject$,
    LOCAL_APPLICATION_STATE_OBJECT
);
```

**Comment by alex-okrushko** [comment]
Hey @amartinelli12 

Checkout the PR from @markostanimirovic that's attached here: https://github.com/ngrx/platform/pull/2759
It's good 🙂
