### ISSUE TITLE
Add custom operation to @ngrx/data

### ISSUE THREAD

**Issue by wizardnet972** [ngrx/platform#2747]
## Describe any alternatives/workarounds you're currently using

**Motivation:**
Sometimes in the real world I have many operations to do on the entity, beside than add, update, delete etc. 
Those operations belong to the entity (such add to favorite, lock and other logics I do on the entity). and these can be done in the server side only. 

the server is always need to return response with the entity (changed) and then I need to merge/add to the collection.

Today I can do it by create an action, effect and reducer even though I using `@ngrx/data`. I know that `@ngrx/data` is not solution for every problem in ngrx.
But no matter which operation is the flow is the same. dispatch an action -> server -> merge the response with the collection.

**This is can be in-the-box of ngrx/data** and not to do a custom services or override/extends ngrx logic.

ngrx/data does that:
 getAll -> GET -> response entity -> add to store collection.

And I propose something like that:

 (the function) (the action) (the data) (the HTTPmethod)  (THE URL of the opration) -> ngrx normal flow -> ngrx normal flow
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 custom('CUSTOM_ACTION', { data: { ... }, type: 'POST', url: '/product/lock' }) -> POST -> response entity -> add to store collection.

Just need to add (by convention) another case to [callDataService function](https://github.com/ngrx/platform/blob/4598fe0271/modules/data/src/effects/entity-effects.ts#L110) same as update operation.

## Other information:
If you need more information I will be happy to answer

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
Seems like a reasonable change to me. Can you provide some sample code about the changes?

**Comment by brandonroberts** [comment]
Reopen when you're still interested in landing this
