### ISSUE TITLE
Class 'Observable<T>' defines instance member property 'select', but extended class 'Store<T>' defines it as instance member function.

### ISSUE THREAD

**Issue by darshu514** [ngrx/platform#275]
This is my package.json
{
  "name": "testproject",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --proxy-config proxy.conf.json",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.2.4",
    "@angular/cdk": "^2.0.0-beta.8",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/material": "^2.0.0-beta.8",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-beta.1",
    "@ng-idle/core": "^2.0.0-beta.12",
    "@ng-idle/keepalive": "^2.0.0-beta.12",
    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^4.0.2",
    "@ngrx/store": "^4.0.2",
    "@ngtools/webpack": "^1.6.0",
    "angular2-modal": "^3.0.2",
    "angular2-tag-input": "^1.2.3",
    "core-js": "^2.5.0",
    "dragula": "^3.7.2",
    "enhanced-resolve": "^3.4.1",
    "file-saver": "^1.3.3",
    "immutable": "^3.8.1",
    "moment": "^2.18.1",
    "mydatepicker": "^2.0.27",
    "mydaterangepicker": "^4.1.9",
    "ng2-auto-complete": "^0.12.0",
    "ng2-dragula": "^1.5.0",
    "ng2-interceptors": "^1.3.0-1",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.3.0",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.1.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
}

**Comment by brandonroberts** [comment]
See the migration guide, remove `@ngrx/core` from your application: https://github.com/ngrx/platform/blob/master/MIGRATION.md

**Comment by darshu514** [comment]
tried removing @ngrx/core, still getting the same error: Class 'Observable<T>' defines instance member property 'select', but extended class 'Store<T>' defines it as instance member function
