### ISSUE TITLE
ngrx/component ngrxLet - AOT object undefined error when accessing property with strict null checks

### ISSUE THREAD

**Issue by mekodes** [ngrx/platform#2755]
## Minimal reproduction of the bug/regression with instructions:

1. Download project at https://stackblitz.com/edit/angular-ivy-ftrrpm?file=src%2Fapp%2Fapp.component.ts
2. npm install
3. ng build

The build reports the following error
```
ERROR in src/app/app.component.ts:7:46 - error TS2532: Object is possibly 'undefined'.

7   <p *ngrxLet="foo$; let f">Hello foo$ '{{ f.bar }}'</p>
                                               ~~~
```

## Expected behavior:

Typing/context should be aware that the object is defined when AOT compiling with strict null checks enabled. `f` object should be defined so `bar` can be accessed without forced non-null assertion.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

- NgRx: 10.0.1
- Angular: 10.1.6
- Node: 13.8.0

## Other information:

Temporary workaround is to add non-null assertion: e.g. `{{f!.bar}}`

**Comment by timdeschryver** [comment]
@mekodes you can create a Pull Request for this if you want.

**Comment by yringler** [comment]
@brandonroberts , when will there be another release of [@ngrx/component](https://www.npmjs.com/package/@ngrx/component)? Just ran into this bug, would love to not have to specify a git url in my packge.json
