### ISSUE TITLE
Router Store: Add selector to retrieve param from anywhere in route tree

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#2758]
If you have a route parameter in the route tree, it could be at different levels in the hierarchy based on how the parameter is used.

Example:

```ts
[
  {
    path: 'myRoute',
    children: [
      {
        path: ':accountId',
        component: AnotherComponent,
      }
    ]
  },
  { path: ':accountId', component: MyComponent }
]
```

This selector would traverse the route tree, and return the first occurrence of the route param, instead of the bottom-most route in the tree.

Selector projector
```ts
let route = router.state.root;
let param = null;
while (route.firstChild) {
  route = route.firstChild;
  if (route.params[paramName]) {
    param = route.params[paramName];
    break;
  }
}
return param;
```

This would allow you to reuse the selector and not have to worry about where the parameter is.

## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by alex-okrushko** [comment]
Are we talking about duplicated route params here?
