### ISSUE TITLE
Cannot read property 'group' of undefined

### ISSUE THREAD

**Issue by pgrm** [ngrx/platform#276]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## What is the current behavior?

I've found the error `Cannot read property 'group' of undefined` logged in my sentry errors. The error is thrown from this line of code: https://github.com/ngrx/platform/blob/015107f88dc1713a33f7a7596791513985fd8e35/modules/effects/src/error_reporter.ts#L9

That means that `this.console` should be undefined.

The stack trace is coming from https://github.com/ngrx/platform/blob/48a2381c212d5dd3fa2b9435776c1aaa60734235/modules/effects/src/effect_sources.ts#L37 and inside here from https://github.com/ngrx/platform/blob/48a2381c212d5dd3fa2b9435776c1aaa60734235/modules/effects/src/effect_notification.ts#L19 

I'm importing `EffectsModule.forRoot(...)` exactly once in my application, in my main module, so I don't quite understand how `this.console` could be undefined.

## Expected behavior:

Not getting that error, instead seeing the log output

## Minimal reproduction of the problem with instructions:

Unfortunately I don't quite understand how to get into that part of code, and therefore couldn't reproduce it.

## Version of affected browser(s),operating system(s), npm, node and ngrx:

- Browser: Chrome 60.0.3112
- OS: Windows 10

**Comment by phmello** [comment]
I'm getting this error when serving --aot
