### ISSUE TITLE
Component-Store/read code sample bugs

### ISSUE THREAD

**Issue by sameera** [ngrx/platform#2769]
URL: https://ngrx.io/guide/component-store/read
Under **Combining Selectors**, `movie.store.ts` line 16-20 has a few bugs:

Current:
```
  readonly userPreferredMovies$ = this.select(
    movies$,
    userPreferredMovieIds$,
    (movies, ids) => movies.filter(id => ids.includes(id)),
  );
```

Corrected:
```
    readonly userPreferredMovies$ = this.select(
        this.movies$,
        this.userPreferredMovieIds$,
        (movies, ids) => movies.filter(movie => ids.includes(movie.id))
    );
```

## I would be willing to submit a PR for the docs :heart:

[ x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Thanks for creating this issue @sameera .
Feel free to create a Pull Request with the corrected version 👍
