### ISSUE TITLE
Calling feature selector from root selector doesn't trigger Angular change detection

### ISSUE THREAD

**Issue by VilleKuhlman** [ngrx/platform#2773]
In my Angular application I'm creating observable by calling a root selector that calls a feature selector.

Here I'm setting the observable in my application's root component:

`this.loaded$ = store.pipe(select(fromRoot.selectLoaded));`

This is the root reducer's (app.reducer.ts) selector that calls a separate feature selector:

```
export const selectLoaded = createSelector(
    fromUI.selectLoaded,
    loaded => loaded
  );
```

This is from the feature reducer's (UI.reducer.ts) selector that selects the actual feature state:

```
  export const selectUIState = createFeatureSelector<State, UIState>('UI');
  
  export const selectContactState = createSelector(
    selectUIState,
    state => state.contact
  );

  export const selectLoaded = createSelector(
    selectContactState,
    fromContact.loaded
  );
```

I have tested that observable itself is working fine: it is emitting values correctly.

What isn't working: the emitted values are not triggering Angular change detection in the root component.

Is this happening because I'm telling about the Feature State only in my Feature module, where the root component does not exist?

This is from the feature module:

` StoreModule.forFeature(fromUI.UIFeatureKey, fromUI.reducers)`

How can I subscribe to a feature state from root component?

**Comment by timdeschryver** [comment]
AFAIK this should work.
Can you create a reproduction so we can take a look please?
