### ISSUE TITLE
[ngrx/data] Easier api endpoints configuration

### ISSUE THREAD

**Issue by memee** [ngrx/platform#2781]
In my experience most of REST API's I worked with had the same endpoint for getting all resources and posting a new one so GET `/resources` and POST `/resources`. ngrx/data uses singular name for posting, putting and getting single one. It would make life a lot easier if it could be configurable `usePluralNameEndpoint` or sth similar.

## Describe any alternatives/workarounds you're currently using

`defaultDataServiceConfig` with `entityHttpResourceUrls` which is not well documented.

## If accepted, I would be willing to submit a PR for this feature

- [ ] Yes (Assistance is provided if you need help submitting a pull request)
- [x] No

**Comment by MichaliEverson** [comment]
its like clear the cookies when you leave the site kinna deal yo

**Comment by folivi** [comment]
Great point!

Do you have any workaround? I'm thinking of handling this with an interceptor. Is there a better way to do it?

thank you

**Comment by memee** [comment]
@folivi with custom `HttpUrlGenerator` that extends from `DefaultHttpUrlGenerator`. I found it in docs.

**Comment by donohoea** [comment]
[https://ngrx.io/guide/data/extension-points#replace-the-httpurlgenerator](https://ngrx.io/guide/data/extension-points#replace-the-httpurlgenerator ) for future reference.
