### ISSUE TITLE
Add patchState method to the ComponentStore 

### ISSUE THREAD

**Issue by markostanimirovic** [ngrx/platform#2786]
Add `patchState` method to get rid of unnecessary `state` spreading and replace:

```typescript
// case 1
this.moviesStore.setState(state => ({
  ...state,
  movies,
}));

// case 2
this.moviesStore.setState(state => ({
  ...state,
  movies: [...state.movies, movie],
}));
```

with:

```typescript
// case 1
this.moviesStore.patchState({ movies });

// case 2
this.moviesStore.patchState(state => ({
  movies: [...state.movies, movie],
}));
```

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by alex-okrushko** [comment]
@markostanimirovic 
Ok, let's look into it. 🙂
