### ISSUE TITLE
build: Update TS dep to match Angular v11

### ISSUE THREAD

**Issue by alex-okrushko** [ngrx/platform#2787]
Angular v11 has TS 4.0 and Rx `6.5`.

Our RxJS version is already up to date, so let's update to TS `^4.0.5`

## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by jordanpowell88** [comment]
I can take this one @alex-okrushko

**Comment by timdeschryver** [comment]
Oh, I guess this is included in #2794 😅
