### ISSUE TITLE
Quick Start Guide

### ISSUE THREAD

**Issue by lawrencebass1992** [ngrx/platform#279]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
</code></pre>

## What is the current behavior?
'npm run example:start' command throws error on systems not using Yarn.

## Expected behavior:
Provide optional command for starting example-app for those not using Yarn. Successfully got the project running using 'npm run build && npm run cli -- serve' instead of provided shortcut command.

**Comment by brandonroberts** [comment]
Can you provide some details about your environment? Node/npm versions, etc ..

**Comment by lawrencebass1992** [comment]
Was using node: v8.2.1 and npm: v5.3.0
