### ISSUE TITLE
Unclear how to overwrite pluralizer in lazy loaded modules

### ISSUE THREAD

**Issue by stefanmo** [ngrx/platform#2790]
## Other information:
Following instructions [here](https://github.com/ngrx/platform/issues/2732) and [here](https://ngrx.io/guide/data/entity-metadata#register-metadata) I have managed to make my data service load data from server. However I need to override the pluralizer as well and yet I cannot get it to function.

What I have now: in the data service constructor I register resource urls.

```typescript
@Injectable()
export class CustomDataService extends DefaultDataService<Custom> {
  constructor(
    httpClient: HttpClient,
    httpUrlGenerator: HttpUrlGenerator,
    @Inject(BASE_API) root: string
  ) {
    httpUrlGenerator.registerHttpResourceUrls({
      Custom: {
        collectionResourceUrl: `${root}custom/`,
        entityResourceUrl: `${root}custom/`,
      },
    });
    super("Custom", httpClient, httpUrlGenerator, { root });
  }
}
```

As you can see I also inject the base api url with a token, however I have to create the resource urls by adding the root as well.

I have also tried creating my own pluralizer that extends Pluralizer and set it on the module providers however it does not work:

```typescript


@Injectable()
class CustomPluralizer extends DefaultPluralizer {
  constructor() {
    super([{ Custom: "custom" }]);
  }
}

@NgModule({
  imports: [CommonModule],
  providers: [
    CustomDataService,
    {
      provide: Pluralizer,
      useClass: CustomPluralizer, 
    },
  ],
})
export class DataAccessCustomModule {
```

Also, following the example for the metadata, I have tried injecting the pluralizer in the module constructor and registering the plural names in the constructor and this doesn't work either:
```typescript

    pluralizer: Pluralizer
  ) {
    if (pluralizer instanceof DefaultSerializer) {
      pluralizer.registerPluralNames({Custom: 'custom'})
    }
```

So is there any way to override the pluralizer?

## I would be willing to submit a PR for the docs :heart:

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

**Comment by donohoea** [comment]
@stefanmo Not something I've ever tried and certainly not documented but I think something like your last approach should work:

```javascript
@NgModule({...})
class LazyModule {
  constructor(eds: EntityDefinitionService, pluralizer: Pluralizer) {
    eds.registerMetadataMap(this.lazyMetadataMap);
    pluralizer.registerPluralNames({Custom: 'custom'});
  }
  ...
}
```
I wonder if your 'if (pluralizer instanceof DefaultSerializer)' is the issue? Not sure what DefaultSerializer is or why the pluralizer would be an instance of it.
