### ISSUE TITLE
Could you please provide a working, current example app with @ngrx/router-store 4.x

### ISSUE THREAD

**Issue by KlausEichinger** [ngrx/platform#280]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request
</code></pre>

## What is the current behavior?
Can't get the navigation to run with store.dispatch …

## Expected behavior:
Would like to see / understand the code of a working example

## Other information:
My app runs perfect via angular/router with router.navigate and [routerLink]. But I want to lift it to the ngrx  level

**Comment by brandonroberts** [comment]
Router Store 4.x does not provide actions to navigate. You can implement yourself. Usage example is the in migration guide https://github.com/ngrx/platform/blob/master/MIGRATION.md#navigation-actions
