### ISSUE TITLE
addReducer/removeReducer available in documentation since v9 but actually not implemented in 10.1.0

### ISSUE THREAD

**Issue by jcimoch** [ngrx/platform#2804]
Here we can see https://v9.ngrx.io/api/store/testing/MockStore  addReducer method
```ts
  addReducer<State, Actions extends Action = Action>(key: string, reducer: ActionReducer<State, Actions>)
```
But even in the latest version (not to mention v9 from docs) it is still not available https://github.com/ngrx/platform/blob/10.1.0/modules/store/testing/src/mock_store.ts#L115 

```ts

  addReducer() {
    /* noop */
  }

  removeReducer() {
    /* noop */
  }

```

My question is when it will be implemented or removed from the docs as it is making confusion, I wanted to migrate to version 9 for that feature but it is not there yet. Or am I'm missing something here?

**Comment by timdeschryver** [comment]
AFAIK it wasn't (and isn't) our intention to implement those methods for `MockStore`.
I tried to remove it from the docs, but then it uses the methods from the base class `Store`.
Perhaps someone with more knowledge knows how to do it (if it's possible...).

What I tried, was to mark those methods as internal

```ts
  /**
   * @internal
   */
  addReducer() {
    /* noop */
  }

  /**
   * @internal
   */
  removeReducer() {
    /* noop */
  }
```

**Comment by jcimoch** [comment]
So maybe side question then, How would you propose to test complex effects which behaviour depends on what action was dispatched initially or in the middle of the processing?. Right now I mock whole store with utilities provided by ngrx, but writing logic to handle different selectors overrides for different scenarios gets cumbersome. 

Previously when using jasmine-marbles I used to just pipe tap operator to the stream with store.dispatch(action). So my test was acting more like integration one rather than unit. This approach has some benefits, for example as soon as behaviour of depended reducers will change, the effect test would also fail. However using testScheduler this approach doesn't allways work as resulted state from reducer might be applied after effect state selector usage.

Do you have some advices on that topic? Docs examples are created for simple effects, the situation gets complicated with much more advanced ones.
My intention was to use addReducer with mockStore to only pass real reducer implementation that are involved within effect logic to not write own conditions and provide different selectors overrides.

**Comment by brandonroberts** [comment]
@jcimoch I think you would use something more like an integration test at that point, where you're not using the mock store, and using `StoreModule.forRoot()` in the TestBed to register reducers
