### ISSUE TITLE
@ngrx/schematics  match Angular 11

### ISSUE THREAD

**Issue by qqaimh** [ngrx/platform#2805]
Environment:
"@angular/common": "~11.0.3",
"@angular/compiler": "~11.0.3",
"@angular/core": "~11.0.3",
"@ngrx/schematics": "^10.1.0",

Execute : ng config cli.defaultCollection @ngrx/schematics

Error: 
Schema validation failed with the following errors:
  Data path ".projects['mype'].prefix" should match format "html-selector".

**Comment by timdeschryver** [comment]
Hi, I tried to reproduce this but I couldn't.
Can you help me with a reproduction please?

```bash
ng new schematics-test
cd .\schematics-test\
yarn add @ngrx/schematics
ng config cli.defaultCollection @ngrx/schematics

ng --version
Angular CLI: 11.0.3
Node: 12.16.2
OS: win32 x64

Angular: 11.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.3
@angular-devkit/build-angular   0.1100.3
@angular-devkit/core            11.0.3
@angular-devkit/schematics      11.0.3
@schematics/angular             11.0.3
@schematics/update              0.1100.3
rxjs                            6.6.3
typescript                      4.0.5
```

**Comment by qqaimh** [comment]
> Hi, I tried to reproduce this but I couldn't.
> Can you help me with a reproduction please?
> 
> ```shell
> ng new schematics-test
> cd .\schematics-test\
> yarn add @ngrx/schematics
> ng config cli.defaultCollection @ngrx/schematics
> 
> ng --version
> Angular CLI: 11.0.3
> Node: 12.16.2
> OS: win32 x64
> 
> Angular: 11.0.3
> ... animations, cli, common, compiler, compiler-cli, core, forms
> ... platform-browser, platform-browser-dynamic, router
> Ivy Workspace: Yes
> 
> Package                         Version
> ---------------------------------------------------------
> @angular-devkit/architect       0.1100.3
> @angular-devkit/build-angular   0.1100.3
> @angular-devkit/core            11.0.3
> @angular-devkit/schematics      11.0.3
> @schematics/angular             11.0.3
> @schematics/update              0.1100.3
> rxjs                            6.6.3
> typescript                      4.0.5
> ```

https://github.com/qqaimh/my-pe9

**Comment by timdeschryver** [comment]
It seems like this is an "issue" on the angular cli part.
It doesn't handle empty prefixes correctly, either remove it or give the project a prefix at https://github.com/qqaimh/my-pe9/blob/master/angular.json#L18.

**Comment by v1d3rm3** [comment]
@timdeschryver 

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: sh-form@0.0.0
npm ERR! Found: @angular/core@11.0.3
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"~11.0.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"^10.0.0" from @ngrx/store@10.0.1
npm ERR! node_modules/@ngrx/store
npm ERR!   @ngrx/store@"10.0.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See C:\Users\victo\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\victo\AppData\Local\npm-cache\_logs\2020-12-07T23_06_53_312Z-debug.lo
```
