### ISSUE TITLE
Crash Chrome on strictStateImmutability false

### ISSUE THREAD

**Issue by TomySmit** [ngrx/platform#2806]
Crash Chrome on strictStateImmutability false
Increase full RAM on computer 

Version Chrome 87
"@ngrx/store": "^10.0.1"
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

**Comment by MichaliEverson** [comment]
defragmentation as well as doubles unsure if u have the option when u edit
a doc/pic to save an original file
