### ISSUE TITLE
Props documentation page broken

### ISSUE THREAD

**Issue by RoboZoom** [ngrx/platform#2808]
Hi,

The `props()` API page leads to a broken link: https://ngrx.io/api/store/props

The page even resuggests the broken page as an alternative.

## I would be willing to submit a PR for the docs :heart:

[ X ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

Note: I'm happy to help with technical writing if this API page needs to be generated, but I likely will need help/supervision to ensure I include the right content.  Most likely however, is not that the content needs to be generated, but that there exists a bug in the documentation library that a team dev would most likely be more effective at finding than me.

**Comment by timdeschryver** [comment]
It seems like for some reason that the generated JSON content is invalid - see https://ngrx.io/generated/docs/api/store/Props.json

**Comment by jordanpowell88** [comment]
@timdeschryver Where/How are these api JSON files generated from? I'm willing to look into why the "contents" value is invalid

**Comment by timdeschryver** [comment]
@jordanpowell88 good question 😅 
I actually don't know it myself, it's part of the [dgeni](https://github.com/angular/dgeni) processor

**Comment by jordanpowell88** [comment]
Well that makes me feel like less of an idiot! 😂 Let me know if you find out and I'll take a look at this

**Comment by RoboZoom** [comment]
I tried to take a look at this, but I don't think we non-team members have access to some of the content that would enable us to debug.  I tried tracing the source of the json file, as defined here: https://github.com/ngrx/platform/blob/143289164b1e94bafe9570c4002a009a04ab659c/projects/ngrx.io/src/app/documents/document.service.ts#L58

The content path should be `generated/docs` but it looks like that isn't included in the .git repository.

**Comment by ngfelixl** [comment]
@RoboZoom try running `yarn docs` inside the `projects/ngrx.io` directory. It will generate this folder for you based on the source code.

**Comment by timdeschryver** [comment]
It seems like this is the same issue as #2854 
The docs clash because of  the `props` method and `Props` interface.
AFAIK, the only fix would be to rename one of the two...
