### ISSUE TITLE
Selectors, how to use them, poor documentation

### ISSUE THREAD

**Issue by FriOne** [ngrx/platform#281]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report
[ ] Feature request
[x] Documentation issue or request
[x] Support request
</code></pre>

I want to create selectors for my feature module/store and l looked at [selectors documentation](https://github.com/ngrx/platform/blob/master/docs/store/selectors.md) and it has very poor description of how it should be used I guess.
createSelector type definition is this:
```ts
export declare function createSelector<State, S1, Result>(s1: Selector<State, S1>, projector: (S1: S1) => Result): MemoizedSelector<State, Result>;
```
And `select` method typings is this:
```ts
select<K>(mapFn: (state: T) => K): Store<K>;
```
So it provide possibility to show what type of "response" will be in `map` calls.
But I can't understand how to use it, what is `<State, S1, Result>` and S1 here?
Could somebody clarify how to use it? I guess nobody wants to import a feature inner state and selector at once.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
ngrx: 4

**Comment by brandonroberts** [comment]
There are also samples of how to use selectors in the example app: https://github.com/ngrx/platform/blob/master/example-app/app/books/reducers/index.ts

**Comment by FriOne** [comment]
@brandonroberts So why `<State, S1, Result>` is in code? How to use this generics? As you can see example app doesn't have an examle.

**Comment by brandonroberts** [comment]
The `<State, S1, Result>` is in the code for type hinting by the TypeScript compiler. You provide a state `State`, a selector function `S1` and return a result `Result` of that selector function. The types provide you with the signatures that the `createSelector` function will accept. 

From the example app:

```ts
export const getBookEntitiesState <- Result = createSelector(
  getBooksState, <- State
  (state: BooksState) => state.books <- S1
);
``

**Comment by FriOne** [comment]
@brandonroberts Thanks for explanation!
