### ISSUE TITLE
Document tapResponse 

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#2811]
## Other information:

The `tapResponse` operator was introduced with #2763 but it's missing documentation.
I think it would be great if we had some example usage in our docs 🙂

## I would be willing to submit a PR for the docs :heart:

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by alex-okrushko** [comment]
Missed this. Thanks for catching, Tim!
