### ISSUE TITLE
Error when updating component-store via ng update schematic - An unhandled exception occurred: Cannot find module '@ngrx/component-store/./migrations/migration.json'

### ISSUE THREAD

**Issue by wingy3181** [ngrx/platform#2819]
## Minimal reproduction of the bug/regression with instructions:

Don't have the time right now to setup an example but will do so later and add a comment to this issue later but had a look at the source and i think i found the issue. See "Other information"

- Current project setup
   - @ngrx/component-store@10.0.0 
- Attempted to update to latest via schematic: `ng update @ngrx/store`
- I get the following error message:
```
An unhandled exception occurred: Cannot find module '@ngrx/component-store/./migrations/migration.json'
Require stack:
....
```
- Can see in `node_modules` it is indeed missing that folder/file for component store
![image](https://user-images.githubusercontent.com/1212576/101836032-c87e9380-3b90-11eb-9be2-6ef7fc842c4f.png)

## Expected behavior:

Should update @ngrx/component-store successfully

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

Ngrx: 10
Angular: 11.0.4
Node: 12
OS: OSX Big Sur

## Other information:

I believe the following file is missing the `assets` attribute like the other modules
- https://github.com/ngrx/platform/blob/master/modules/component-store/ng-package.json

Also `component` module has the same issue (https://github.com/ngrx/platform/blob/master/modules/component/ng-package.json)

## I would be willing to submit a PR to fix this issue

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
I think you're right, do you want to create a Pull Request for this?

**Comment by wingy3181** [comment]
@timdeschryver done
=)
See https://github.com/ngrx/platform/pull/2822
