### ISSUE TITLE
@ngrx/store won't install with Angular 11

### ISSUE THREAD

**Issue by manoharnikkam** [ngrx/platform#2831]
## Minimal reproduction of the bug/regression with instructions:
![image](https://user-images.githubusercontent.com/8573069/102674041-2f381a00-415a-11eb-9bef-4cf47673bbe8.png)

## Expected behavior:
npm install @ngrx/store should install 

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
{
  "name": "nx-workspace",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "nx": "nx",
    "server": "json-server db.json --watch",
    "startSsl": "concurrently \"npm run server\" \"nx serve  --ssl --ssl-cert localhost.crt --ssl-key localhost.key\"",
    "start": "concurrently \"npm run server\" \"nx serve\"",
    "nxserve": "nx serve",
    "build": "nx build",
    "test": "nx test",
    "lint": "nx workspace-lint && nx lint",
    "e2e": "nx e2e",
    "affected:apps": "nx affected:apps",
    "affected:libs": "nx affected:libs",
    "affected:build": "nx affected:build",
    "affected:e2e": "nx affected:e2e",
    "affected:test": "nx affected:test",
    "affected:lint": "nx affected:lint",
    "affected:dep-graph": "nx affected:dep-graph",
    "affected": "nx affected",
    "format": "nx format:write",
    "format:write": "nx format:write",
    "format:check": "nx format:check",
    "update": "nx migrate latest",
    "workspace-generator": "nx workspace-generator",
    "dep-graph": "nx dep-graph",
    "help": "nx help",
    "postinstall": "ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points"
  },
  "private": true,
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1100.1",
    "@angular-eslint/eslint-plugin": "0.8.0-beta.1",
    "@angular-eslint/eslint-plugin-template": "0.8.0-beta.1",
    "@angular-eslint/template-parser": "0.8.0-beta.1",
    "@angular/compiler-cli": "^11.0.0",
    "@angular/language-service": "^11.0.0",
    "@nrwl/angular": "^11.0.9",
    "@nrwl/cli": "11.0.9",
    "@nrwl/cypress": "11.0.9",
    "@nrwl/eslint-plugin-nx": "11.0.9",
    "@nrwl/jest": "11.0.9",
    "@nrwl/tao": "11.0.9",
    "@nrwl/workspace": "11.0.9",
    "@types/jest": "26.0.8",
    "@types/node": "12.12.38",
    "@typescript-eslint/eslint-plugin": "4.3.0",
    "@typescript-eslint/parser": "4.3.0",
    "codelyzer": "^6.0.0",
    "concurrently": "^5.3.0",
    "cypress": "^5.5.0",
    "dotenv": "6.2.0",
    "eslint": "7.10.0",
    "eslint-config-prettier": "6.0.0",
    "eslint-plugin-cypress": "^2.10.3",
    "jest": "26.2.2",
    "jest-preset-angular": "8.3.1",
    "json-server": "^0.16.3",
    "prettier": "2.1.2",
    "ts-jest": "26.4.0",
    "ts-node": "~9.1.1",
    "tslint": "~6.1.0",
    "typescript": "~4.0.3"
  },
  "dependencies": {
    "@angular/animations": "^11.0.5",
    "@angular/cdk": "^11.0.3",
    "@angular/common": "^11.0.0",
    "@angular/compiler": "^11.0.0",
    "@angular/core": "^11.0.0",
    "@angular/flex-layout": "^11.0.0-beta.33",
    "@angular/forms": "^11.0.0",
    "@angular/material": "^11.0.3",
    "@angular/platform-browser": "^11.0.0",
    "@angular/platform-browser-dynamic": "^11.0.0",
    "@angular/router": "^11.0.0",
    "rxjs": "^6.5.5",
    "tslib": "^2.0.0",
    "zone.js": "^0.10.2"
  }
}

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
This is known behavior of the Angular CLI. Use the `@latest` until v11 is out. For context 

https://github.com/ngrx/platform/issues/2604

**Comment by manoharnikkam** [comment]
Thank you @brandonroberts for the quick response. I tried installing with @latest. Unfortunately that did not work. Am I missing some setup? Appreciate any help. 
![image](https://user-images.githubusercontent.com/8573069/102674365-5a6f3900-415b-11eb-9474-466982908316.png)

Here is the extract from log
0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'install',
0 verbose cli   '@ngrx/store@latest'
0 verbose cli ]
1 info using npm@7.0.15
2 info using node@v15.4.0
3 timing config:load:defaults Completed in 0ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/Users/manohar/Projects/Learning/nx-workspace/.npmrc Completed in 1ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/Users/manohar/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 6ms
19 verbose npm-session f49d2fd9c7f8aa18
20 timing npm:load Completed in 13ms
21 timing arborist:ctor Completed in 0ms
22 timing idealTree:init Completed in 675ms
23 http fetch GET 304 https://registry.npmjs.org/@ngrx%2fstore 985ms (from cache)
24 timing idealTree:userRequests Completed in 992ms
25 silly idealTree buildDeps
26 silly fetch manifest @ngrx/store@10.1.1
27 http fetch GET 304 https://registry.npmjs.org/@ngrx%2fstore 71ms (from cache)
28 silly fetch manifest @angular/core@^11.0.0
29 http fetch GET 304 https://registry.npmjs.org/@angular%2fcore 50ms (from cache)
30 silly fetch manifest rxjs@^6.5.5
31 http fetch GET 304 https://registry.npmjs.org/rxjs 55ms (from cache)
32 silly fetch manifest zone.js@^0.10.2
33 http fetch GET 304 https://registry.npmjs.org/zone.js 45ms (from cache)
34 timing idealTree Completed in 1904ms
35 timing command:install Completed in 1905ms
36 verbose stack Error: unable to resolve dependency tree
36 verbose stack     at Arborist.[failPeerConflict] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1045:25)
36 verbose stack     at Arborist.[loadPeerSet] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1025:36)
36 verbose stack     at async Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:781:11)
36 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:209:7)
36 verbose stack     at async Promise.all (index 1)
36 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:122:5)
36 verbose stack     at async install (/usr/local/lib/node_modules/npm/lib/install.js:39:3)
37 verbose cwd /Users/manohar/Projects/Learning/nx-workspace
38 verbose Darwin 20.2.0
39 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@ngrx/store@latest"
40 verbose node v15.4.0
41 verbose npm  v7.0.15
42 error code ERESOLVE
43 error ERESOLVE unable to resolve dependency tree
44 error
45 error While resolving: [1mnx-workspace[22m@[1m0.0.0[22m
45 error Found: [1m@angular/core[22m@[1m11.0.5[22m[2m[22m
45 error [2mnode_modules/@angular/core[22m
45 error   [1m@angular/core[22m@"[1m^11.0.0[22m" from the root project
45 error
45 error Could not resolve dependency:
45 error [35mpeer[39m [1m@angular/core[22m@"[1m^10.0.0[22m" from [1m@ngrx/store[22m@[1m10.1.1[22m[2m[22m
45 error [2mnode_modules/@ngrx/store[22m
45 error   [1m@ngrx/store[22m@"[1m10.1.1[22m" from the root project
45 error
45 error Fix the upstream dependency conflict, or retry
45 error this command with --force, or --legacy-peer-deps
45 error to accept an incorrect (and potentially broken) dependency resolution.
45 error
45 error See /Users/manohar/.npm/eresolve-report.txt for a full report.
46 verbose exit 1
[2020-12-19T00_02_34_402Z-debug.log](https://github.com/ngrx/platform/files/5718594/2020-12-19T00_02_34_402Z-debug.log)

**Comment by grestrepo** [comment]
Hi, I had the same error, I fixed it like this: 
**npm install @ngrx/store@latest --legacy-peer-deps**

**Comment by finti3295** [comment]
Thank you @grestrepo , it is working

**Comment by omarboulbaze** [comment]
> 

This fixed the issue for me

**Comment by pkobakov** [comment]
for me as well . Thank you very mouch

**Comment by Onamuhledivad** [comment]
Worked for me, thanks
