### ISSUE TITLE
Is there a solution to export store not using Chrome Dev Tool?

### ISSUE THREAD

**Issue by dsmb13** [ngrx/platform#2837]
I have an Angular app (v.10 with ngrx ) and I would like to export all state not using the Chrome dev tools but I would like to do it by clicking on a button inside my app.
Is there a solution and an example to do it?
Can someone help me, please?

thanks :)

#ngrx #angular #redux #devtools

**Comment by timdeschryver** [comment]
Hi, support questions should be asked on [stackoverflow (with a ngrx tag)](https://stackoverflow.com/questions/tagged/ngrx) or you can join our [discord server](https://discord.com/invite/gCEj4zC) and ask your question there.

**Comment by dsmb13** [comment]
> Hi, support questions should be asked on [stackoverflow (with a ngrx tag)](https://stackoverflow.com/questions/tagged/ngrx) or you can join our [discord server](https://discord.com/invite/gCEj4zC) and ask your question there.

thank you so much @timdeschryver :D
