### ISSUE TITLE
ComponentStore: Support global debounce setting

### ISSUE THREAD

**Issue by jaufgang** [ngrx/platform#2847]
The `debounce`  option for component-store selectors is awesome.  It would be really convenient if a team could set `{debounce: true}` as a global default for all selectors in a project.  

Setting this should obviously still support creating non-debounced selectors by setting `{debounce:false}` to individual selectors.

**Comment by alex-okrushko** [comment]
Thanks @jaufgang 
I thought about it a lot, and I actually had `debounce: true` by default at the beginning (I actually didn't even have an option to turn it off), but that was backfiring.

See the description of this PR for more details, and explanation why it's `debounce: false` by default now: https://github.com/ngrx/platform/pull/2606#issue-444311075

**Comment by Harpush** [comment]
@alex-okrushko Saw this issue after looking for a way to set it globally. I understand why its not default. But I think allowing it as an injection token for those who know what they are doing is still correct. It can even work well as it is a constructor argument with `@Inject` allowing to pass it by calling super in the constructor for specific store configuration.
