### ISSUE TITLE
Consider adding a data property to SerializedRouterStateSnapshot

### ISSUE THREAD

**Issue by epaitz** [ngrx/platform#2848]
I usually define the data property of an Angular route like the following.

```
const routes: Routes = [
    {
        path: 'home',
        component: HomeComponent,
        data: {
            label: 'Home'
        }
    }
]
```

Then I have a router selector like the following.

```
export const selectRouterState = (state: AppState) => state.router;

export const selectRouteDataLabel = createSelector(
    selectRouterState,
    (state: RouterReducerState) => {
        return state?.state?.['data'].label;
    }
);
```

Since the [SerializedRouterStateSnapshot ](https://ngrx.io/api/router-store/SerializedRouterStateSnapshot)does not contain a data property I have to use the string literal to access the data property. Another alternative would be to cast the state as any like the following.

```
export const selectRouteData = createSelector(
    selectRouterState,
    (state: RouterReducerState) => {
        return (state?.state as any)?.data;
    }
);
```
Both of these two approaches work at runtime but using the string literal comes up as a lint warning and casting as any IMHO adds noise to the code. The lint rule can be  disable/enable for this line of code or globally which will work too but adding the data property seems like the best solution. 

Please let me know if there is something I have overlooked.

Thanks

**Comment by timdeschryver** [comment]
`data` should be available on `root` and on the route's children (`childen` and `firstChild`).
In your example:

```ts
state.state.root.data
```

**Comment by epaitz** [comment]
Thanks for the fast reply. There does appear to be a data property on root but at runtime root its undefined and the data property is on the state object one level up. Here is my selector.

```
export const selectRouteDataLabel = createSelector(
    selectRouterState,
    (state: RouterReducerState) => {
        console.log(state);
        console.log(JSON.stringify(state, null , '\t'))
        return state?.state?.['data'].label;
    }
);
```

Here is a screen grab of my console log output. I do not see a root property. 

![image](https://user-images.githubusercontent.com/30181382/103385171-44e90000-4ac7-11eb-918e-321ad73b5d42.png)

Here is the output from the JSON.stringify().

```
{
  "state": {
    "url": "/map/bookmarks",
    "params": {},
    "queryParams": {},
    "data": {
      "label": "Bookmarks",
      "icon": "bookmarks"
    }
  },
  "navigationId": 1
}
```
