### ISSUE TITLE
Proposal: Better Typescript Typing with `createFeatureSelector`

### ISSUE THREAD

**Issue by isc30** [ngrx/platform#2849]
The current declaration looks like the following:

```ts
export declare function createFeatureSelector<T, V>(featureName: keyof T): MemoizedSelector<T, V>;
```

which allows arbitrary types to be set as for the `V` parameter.

### Proposal:
```ts
export declare function createFeatureSelector<T>(featureName: keyof T): MemoizedSelector<T, T[typeof featureName]>;
```

this version ensures that the proper value type is returned for the given object key, and removes the need of manually specifying `V`

**Comment by alex-okrushko** [comment]
`createFeatureSelector` has also another signature:

```ts
export function createFeatureSelector<T>(featureName: string): MemoizedSelector<object, T>;
```

I use it exclusively, without creating a "fake" object that would contain the key.

**Comment by isc30** [comment]
yes, but that allows you to use any type there which is "ok" if you don't know the type of the store.
When you do, IMO it's better to let the compiler error if you mess up the type in the `<T, V>` case)

**Comment by alex-okrushko** [comment]
Longer answer:

`createFeatureSelector` is typically used with `forFeature`, which should **not** be aware about the shape for the rest of the store (they are even lazy-loaded in many cases). As such, they only care/know about the shape that they'll be patching to the global store, e.g.:

```ts
interface NewFeatureState {
  product: Product;
  selectedId: number;
}
```

This state is patched by a specific KEY, e.g., `const MY_NEW_FEATURE_KEY = 'product';`.

In the Module:
```ts
@NgModule({
  imports: [
     StoreModule.forFeature(MY_NEW_FEATURE_KEY, productReducer),
 ],
})
export class MyNewFeatureModule {}
```

and then in the selectors file:
```ts
// Infers NeFeatureState type
const productsFeatureState = createFeatureSelector<NewFeatureState>(MY_NEW_FEATURE_KEY);

// 👇 everything is type-safe
export const selectProduct = createSelector(
  productsFeatureState,
  state => state.product,
);

export const selectId = createSelector(
    productsFeatureState,
    state => state.selectedId,
);

export const selectProductName = createSelector(
  selectProduct,
  product => product.name
);
```

Then all of this call be used in the type-safe way in the components:
```ts
@Component({...})
export class NewProductName {
  // infers `string` type
  readonly productName$ = this.store.select(selectProductName);
 
  // notice the unspecified generic       👇 because it's not needed 
  constructor(private readonly store: Store) {}
}
```

Hope it's a bit clearer now 🙂

**Comment by alex-okrushko** [comment]
I'm very pro-strictest-type possible. 🙂

btw, if you want to combine selectors from different "features" - this is still possible:

```ts
// 👇 selector from another "Feature"
import {selectCurrentId} from '@routing/selectors';

...

// Combines data from multiple features
export const currentProduct = createSelector(
   selectProducts,
   selectCurrentId,
   (products, id) => products.find(p => p.id === id),
);
```

**Comment by ValentinBossi** [comment]
@alex-okrushko 
> btw, if you want to combine selectors from different "features" - this is still possible:

in the ngrx example-app its not possible to combine selectors from "auth" and "books" feature.
for example `createSelector(selectUser, selectCollectionBookIds, (a,b)=>{})`
or how to do that? i think this is a very common question and as far as i can see there is no topic about that in the docs.

**Comment by david-shortman** [comment]
@ValentinBossi The example you provide is exactly how you can create a selector from two selectors selecting from different features:

```typescript
export const selectUserAndCollectionBookIds = createSelector(
    selectUser,
    selectCollectionBookIds,
    (user, collectionBookIds) => [user, collectionBookIds]
);
```

Of course, you can create any kind of value that can be thought of. I just provided an unimaginative example of combining them in a tuple.

**Comment by david-shortman** [comment]
The docs also provide an example of this on the Selectors page under the section [Using selectors for multiple pieces of state](https://ngrx.io/guide/store/selectors#using-selectors-for-multiple-pieces-of-state):

```typescript
export const selectVisibleBooks = createSelector(
  selectUser,
  selectAllBooks,
  (selectedUser: User, allBooks: Book[]) => {
    if (selectedUser && allBooks) {
      return allBooks.filter((book: Book) => book.userId === selectedUser.id);
    } else {
      return allBooks;
    }
  }
);
```

**Comment by david-shortman** [comment]
Although, in the example, it shows the selectors being from the same `AppState`. There isn't an explicit example where selectors which select from `object` (no provided "AppState" generic to `createFeatureSelector)...

**Comment by ValentinBossi** [comment]
i know i can compose selectors, but the example i showed does not work.
if you clone this repo and add that example you will see you will get an error.
why is that? @david-shortman  @alex-okrushko

**Comment by david-shortman** [comment]
What error are you seeing? I get no errors, and a proper type for my example selector:

![Screen Shot 2021-07-09 at 07 27 53](https://user-images.githubusercontent.com/25187726/125071444-45221380-e087-11eb-90b8-98a238206fa8.png)

**Comment by ValentinBossi** [comment]
https://stackblitz.com/edit/xdjo9p--run?embed=1&file=projects/example-app/src/app/books/reducers/index.ts

**Comment by david-shortman** [comment]
It appears the example is woefully out-of-date. It's on NgRx 7.4.0, released March 28, 2019. The current version is 12.2.0.

**Comment by ValentinBossi** [comment]
true.
i found the code change why it was not working before in the example-app. not long ago, april 2021.
![image](https://user-images.githubusercontent.com/19373754/125191883-f326ec80-e244-11eb-9a85-e373be8e723d.png)
and exactly this code change did also made my team member to get the selector composition problem solved. and we are now discussing if its better to use
```
export declare function createFeatureSelector<T>(featureName: string): MemoizedSelector<object, T>;
/// or 
export declare function createFeatureSelector<T, V>(featureName: keyof T): MemoizedSelector<T, V>;
```
i said lets use `<T,V>` its safer cause when we have lazy modules, it could be that there is no feature key and the selector will receive `undefined` `.<T,V>` shows you if the key is for sure available. (for example [current master] in the books module books state extends root state which has the layout key and composing a selector with layout and book selector will work also with `<T,V>` signature, cause the layout key is for sure available)

could it be the rule of thumb to use only `<T>` if you're sure the composed selectors selects only earger state?
maybe i messed up things but it would help to know whats right resp. best practice.

**Comment by ValentinBossi** [comment]
this eager/lazy note is also pointed out by alex-okrushko, when i get this quote correctly...

> createFeatureSelector is typically used with forFeature, which should not be aware about the shape for the rest of the store (they are even lazy-loaded in many cases). As such, they only care/know about the shape that they'll be patching to the global store, e.g.:
