### ISSUE TITLE
ComponentStore:  Updaters should enforce type of returned value

### ISSUE THREAD

**Issue by jaufgang** [ngrx/platform#2851]
## Minimal reproduction of the bug/regression with instructions:

```ts
interface AppComponentState {
  foo: boolean;
  bar: boolean;
}

@Component({
  selector: "my-app",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
  providers: [ComponentStore]
})
export class AppComponent {
  // this should throw an error because updaterFn does not return type AppComponentState
  updateCount = this.store.updater<number>((state, count) => ({
    ...state,
    count
  }));

  constructor(public store: ComponentStore<AppComponentState>) {
    this.store.setState({ foo: true, bar: false });

    this.updateCount(interval(500).pipe(take(10)));
  }
}
```
for live version, see: see: https://stackblitz.com/edit/ngrx-component-store-updaters-iyxsat?file=src%2Fapp%2Fapp.component.ts

## Expected behavior:

Should throw an error for the updateCount updater declaration because updaterFn does not return type AppComponentState (ie: property `count` is not declared in AppComponentState)

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

@ngrx/component-store@10.1.1

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by va-stefanek** [comment]
I am not sure but I think it might be like a typescript limitation https://stackoverflow.com/questions/64263271/typescript-validate-excess-keys-on-value-returned-from-function

**Comment by timdeschryver** [comment]
As @va-stefanek pointed out, this is something out of our control (AFAIK).
You could resolve this if you type the return type:

```ts
//                                                                                            👇 add a return type
updateCount = this.store.updater<number>((state, count): AppComponentState => ({
  ...state,
//  👇 this does now throw.
  count
}));
```

**Comment by timdeschryver** [comment]
This is now available as a [rule](https://github.com/timdeschryver/eslint-plugin-ngrx/blob/main/docs/rules/updater-explicit-return-type.md) the NgRx ESlint plugin.
