### ISSUE TITLE
Custom RouterStateSerializer is called with both the original and the custom serialized version

### ISSUE THREAD

**Issue by DorianGrey** [ngrx/platform#286]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## What is the current behavior?

I've just upgraded `ngrx-router-store` to 4.0.3 to be able to provide a custom `RouterStateSerializer` to get both the dev-tools and `ngrx-store-freeze` working again. While debugging, I've recognized that this serializer is not only called with the router snapshot, but with the serialized version it generated before as well.
I'm not sure if this is a bug w.r.t. the typings (i.e. it should be `RouterStateSnapshot | T` instead of just `RouterStateSnapshot`) or a technical issue.
[Here](https://github.com/DorianGrey/ng-webpack-template/blob/ngrx-4-update/src/app/app.store.ts#L98) is my current implementation, including a workaround to simply return the casted input instead of creating new data.

## Expected behavior:

I would expect that either:
- The typings reflect that the value provided to `serialize` may be the custom state version.
- The serializer will never be called with the custom serialized version.

## Minimal reproduction of the problem with instructions:

Minimal version: http://plnkr.co/edit/hlQKrHTDTqOrGasMkO4H
Just switch between the routes - two calls will be listed for each switch, one for the original snapshot and one for the serialized version. Calls are printed with `console.warn`.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
- OS: Ubuntu 16.04
- node: 6.11.1
- npm: 5.3.0 / yarn 0.27.5
- ngrx: 4.0.3

## Other information:
./.

**Comment by brandonroberts** [comment]
That is a bug, fix is here #287
