### ISSUE TITLE
docs: link to ngrx ultimate courses is broken

### ISSUE THREAD

**Issue by ngfelixl** [ngrx/platform#2860]
The link on the [ressources page](https://ngrx.io/resources) to Todd Mottos Ultimate Angular NgRX workshop is broken. It points to https://ultimatecourses.com/angular/ngrx-store-effects but should point to https://ultimatecourses.com/learn/ngrx-store-effects.

## I would be willing to submit a PR for the docs :heart:

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
@ngfelixl feel free to create a PR from your branch.
Thanks in advance!
