### ISSUE TITLE
refactor(ngrx.io): combineLatest is deprecated

### ISSUE THREAD

**Issue by ngfelixl** [ngrx/platform#2861]
This is more like a refactoring request for the docs. While working on another issue, I've seen that there are some `combineLatest` used in a deprecated way. I would be happy to help bringing them up to date with the parameter as tupel and the map operator.

Affected in the following files:
- integration.spec.ts, line 148 and 275
- limitations.md, line 80
- app.component.ts, line 168, 208 and 218
- api-list.component.ts, line 71
- toc.component.ts, line 55
- navigation.service.ts, line 113

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
LGTM, thanks again @ngfelixl - feel free to also create a PR for this.
Could you also break the commit in two? One for the docs (`limitations.md`), the rest can be committed under `ngrx.io`.
