### ISSUE TITLE
Using non-parametrized selector inside parametrized may result in multiple calls

### ISSUE THREAD

**Issue by Akxe** [ngrx/platform#2862]
## Minimal reproduction of the bug/regression with instructions:

```ts
interface Store {
  elements: unknown[];
}

export const offerState = createFeatureSelector<Store>('store');

const listAsSet = createSelector(
	state => state.list,
	carriers => new Set(carriers),
);

const elementSelectorFactory = () => createSelector(
	listAsSet,
	(set, { element }) => set.has(element),
);
```

## Expected behavior:

I would expect it to behave like the fix below.

```ts
interface Store {
  elements: unknown[];
}

export const offerState = createFeatureSelector<Store>('store');

const listAsSet = createSelector(
	state => state.list,
	carriers => new Set(carriers),
);

const elementSelectorFactory = () => createSelector(
	state => listAsSet(state),  // This will fix it, but this is nor documented, nor user friendly...
	(set, { element }) => set.has(element),
);
```

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

NgRx: 10.1.2

## Other information:

In my opinion, the selector should be aware if it uses the `props` in its `projection` function. Only if it uses `props` they should get passed to it. [`Function.length`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/length) might help here.

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] Once agreed upon solution, it might be finicky...
[ ] No

**Comment by Akxe** [comment]
I can see 3 possible solutions:
1) Remove params from `createSelector`, instead create a `createSelectorWithParams` function, that would require params accept. This could also be used to mitigate the factory that needs to be created around the selector called with multiple different props.
2) Relly on `projectionFn.lenght` vs `arguments.lenght - 1`, to decide, if selector uses the props.
3) `projection` and `projectionWithProps` as the last parameter of `createSelector`. They would give the selector a hint on wherever or not pass parameters to the given selector.

**Comment by timdeschryver** [comment]
Thanks for creating this issue @Akxe , the issue here is that the props are passed down to all selectors.
Because of this `listAsSet` will be invoked multiple times, once for each time a `listAsSet` selector is initialized. 

If this is not the behavior that you want, I would suggest passing the props to the selector via a factory method:

```ts
const elementSelectorFactory = (element) => createSelector(
	listAsSet,
	(set) => set.has(element),
);
```

**Comment by Akxe** [comment]
@timdeschryver I know why it happens, i debugged the code quite a bit. I would suggest filling docs on this matter.

Why is this factory a standard? There is whole mechanism for props, but you can never use them, because of this problem...

**Comment by markostanimirovic** [comment]
+1 to think about removing `createSelector` overloads with props, because it can be replaced with factory function.
Also, without props, `createSelector` arguments can be switched to variadic tuples to accept any number of input selectors :)

**Comment by Akxe** [comment]
@markostanimirovic To allow any number of input selectors I would suggest accepting an object as the first argument. Just like `combineLatest` does [from v7](https://github.com/ReactiveX/rxjs/issues/5022#issuecomment-756543136). The key benefit of this switch/addition is, that it is less error-prone.

```ts
createSelector({
  a: aSelector,
  b: bSelector,
}, ({a, b}) => `${a} ${b}`);
```

It is almost the same, but the object notation is very well supported in TS, unlike variadic tuples, it is there only since 4.x.x. Thought it might not be a problem for angular since your support is tied to the Angular version that supports TS 4.0.0

-----

How about removing props from `createSelector`, but having them in `createSelectorWithProps`?

**Comment by timdeschryver** [comment]
I agree that `createSelector` (with props) needs some extra work. 
It's a bit late to add it to a v11 release, but we should discuss this for a future release.

What we can do now, is polishing up the docs around selectors with props (e.g. mention that used selectors will be executed and document that you can pass in arguments via the factory method to prevent the described issue).

**Comment by markostanimirovic** [comment]
> @markostanimirovic To allow any number of input selectors I would suggest accepting an object as the first argument. Just like `combineLatest` does [from v7](https://github.com/ReactiveX/rxjs/issues/5022#issuecomment-756543136).
> 
> ```ts
> createSelector({
>   a: aSelector,
>   b: bSelector,
> }, ({a, b}) => `${a} ${b}`);
> ```

@Akxe 
Current signature of `createSelector` looks better to me, especially when you have only one selector:

- Sequence (current):
`createSelector(selectA, a => a + 1);`

- Object:
`createSelector({ a: selectA }, ({ a }) => a + 1);`

> The key benefit of this switch/addition is, that it is less error-prone.

Can you give me an example where current `createSelector` signature is error prone?

> It is almost the same, but the object notation is very well supported in TS, unlike variadic tuples, it is there only since 4.x.x. Thought it might not be a problem for angular since your support is tied to the Angular version that supports TS 4.0.0

Yes, NgRx now supports TS 4 and strong typing for any number of input selectors can be done with variadic tuples 🙂

**Comment by Akxe** [comment]
If you ever combine 5+ operators it gets messy if you want to add or remove one. Even more if you want to organize them.

**Comment by brandonroberts** [comment]
Closing this as we've deprecated selectors with props

**Comment by yalunqin** [comment]
I'm trying to understand the advantage of factory selector over selector with props and came to this thread. @Akxe @timdeschryver what is the issue in the example code? Which function is called multiple times? How is the factory called in the component?

**Comment by timdeschryver** [comment]
@yalunqin  see #2980

**Comment by yalunqin** [comment]
@timdeschryver I read through that thread already. That's how I found this thread because this is linked from there. 

"One of the big benefits of using selectors is that a selector is memoized, but with selectors with props it's very easy to "break" this. Most of the problems/questions I see is because selector with props aren't used correctly, resulting in selectors that are executed multiple times. This isn't something a user might expect, and arises some confusion. Even when they're used correctly, shared "child selectors" will be invoked for each time that child selector is used in a selector with props (#2862).
​"

I'd appreciate it if this could be elaborated more. My team has been using selector with props throughout our code base and haven't encountered any performance issue.

**Comment by timdeschryver** [comment]
@simply-alliv please take a look at the demo in the RFC. 
There you can see how many times a selector is invoked.
