### ISSUE TITLE
Same code giving error with CreateEffect and working well with @Effect

### ISSUE THREAD

**Issue by alfmos** [ngrx/platform#2865]
I have received an error for days in a CreateEffect, and I wasn't able to understand what the error is.
Then I removed CreateEffect and addedd @Effect() and everything works fine now.
I'm not sure 100% it is a bug, but reasonably if the compiler emits an error this error should be present also at runtime.
Here the code:
```
export interface ServerAuthData{
  AccessToken: string;
  RefreshToken: string;
  Utente: Utente;
}
export interface AuthState {
  isAuthenticated: boolean;
  errorMessage: string;
  accessToken: string;
  refreshToken: string;
  utente: Utente;
}
  
export const authLogin = createAction( 
    '[Auth] Login',    
    props<{ username: string,password: string }>()  
    );  
export const authLoginSuccess = createAction('[Auth] LoginSuccess',  
    props<{serverAuthData: ServerAuthData}>()  
    );  
```
Reducer:
```
  on(authLoginSuccess, (state,{serverAuthData}) => (
    { ...state,
      isAuthenticated: true,
      utente: serverAuthData.Utente,
      accessToken: serverAuthData.AccessToken,
      refreshToken: serverAuthData.RefreshToken,
      erroMessage: "",
    }))
);
```
and finally effect:
```
@Injectable()
export class AuthEffects {
  login$ = 
  createEffect(() =>
      this.actions$.pipe(
        ofType(authLogin),
        switchMap((action) =>
          this.authService.login(action.username,action.password).pipe(
            map((serverAuthData) =>  authLoginSuccess({serverAuthData})),
            catchError((error: any) => of(this.authService.loginFailure(error))),
          )
        )
      )
  );

```
This is the service I call:
```
login(username: string,password: string) {
    var formData: any = new FormData();
    formData.append("username", username);
    formData.append("password", password);
    console.log("Chiamo il server");
    return this.http.post<ServerAuthData>(this.loginUrl, formData);
  }
```
I receive an error:

> Type 'Observable<void | ({ serverAuthData: ServerAuthData; } & TypedAction<"[Auth] LoginSuccess">)>' is not assignable to type 'EffectResult'.
> Type 'Observable<void | ({ serverAuthData: ServerAuthData; } & TypedAction<"[Auth] LoginSuccess">)>' is not assignable to type 'Observable'.
> Type 'void | ({ serverAuthData: ServerAuthData; } & TypedAction<"[Auth] LoginSuccess">)' is not assignable to type 'Action'.
> Type 'void' is not assignable to type 'Action'.
> 

Changing CreateEffect and using @Effect() make the effect working perfectly
```
  //login$ = 
  //createEffect(() => 
  @Effect()
     login$= this.actions$.pipe(
        ofType(authLogin),
        switchMap((action) =>
          this.authService.login(action.username,action.password).pipe(
            tap((serverAuthData) => console.log('Dopo login. Ricevuto:' + serverAuthData)),
            map(serverAuthData =>  authLoginSuccess({serverAuthData})),
            catchError((error: any) => of(this.authService.loginFailure(error))),
          )
        )
      );
  //);
```
## Steps to reproduce the bug:
It's not so simple to reproduce the bug as it calls a webservice, and I think a possible cause of the error is the service returns a typed http.post.
If someone is interested in investigating the issue, I can help giving sources and an access to the webservice

## Expected behavior:

I would expect CreateEffect not giving an error

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
    "@angular-extensions/elements": "~10.1.1",
    "@angular-extensions/model": "^10.0.1",
    "@angular/animations": "~10.2.3",
    "@angular/cdk": "^10.2.7",
    "@angular/common": "~10.2.3",
    "@angular/compiler": "~10.2.3",
    "@angular/core": "~10.2.3",
    "@angular/flex-layout": "^11.0.0-beta.33",
    "@angular/forms": "~10.2.3",
    "@angular/material": "~10.2.7",
    "@angular/platform-browser": "~10.2.3",
    "@angular/platform-browser-dynamic": "~10.2.3",
    "@angular/router": "~10.2.3",
    "@fortawesome/angular-fontawesome": "^0.7.0",
    "@fortawesome/fontawesome-free": "^5.15.1",
    "@fortawesome/fontawesome-svg-core": "^1.2.32",
    "@fortawesome/free-brands-svg-icons": "^5.15.1",
    "@fortawesome/free-solid-svg-icons": "^5.15.1",
    "@ngrx/effects": "~10.0.1",
    "@ngrx/entity": "~10.0.1",
    "@ngrx/router-store": "~10.0.1",
    "@ngrx/store": "~10.0.1",
    "@ngrx/store-devtools": "~10.0.1",
    "@ngx-translate/core": "^13.0.0",
    "@ngx-translate/http-loader": "^6.0.0",
    "bootstrap": "^4.5.3",
    "browser-detect": "^0.2.28",
    "rxjs": "~6.6.3",
    "tslib": "^2.0.3",
    "uuid": "^8.3.1",
    "zone.js": "~0.11.3"

**Comment by markostanimirovic** [comment]
@alfmos 
The return type of `authService.loginFailure()` method seems to be `void`. You must return an action instead.

It works with `@Effect()` because decorators are not type safe. So, you need to pass the action here:
`catchError(error => of(loginFailure({ error }) /* <- action */))`

**Comment by alfmos** [comment]
@markostanimirovic 
Thanks for your response. I suppose these are the quirks of functional programming. I got the error on this.Actions$.pipe, of course, and focused on the success part, and I didn't realize it was loginError being void.
I'm still new to Angular and ngrx.

**Comment by markostanimirovic** [comment]
@alfmos
You're welcome :)

For additional questions, you can join on [Discord](https://discord.gg/FWRNtraC).

**Comment by alfmos** [comment]
@markostanimirovic 
Thanks, Marko, I did.
