### ISSUE TITLE
Proposal: feat(effects): ngrx effects flow diagram generation tool

### ISSUE THREAD

**Issue by ngfelixl** [ngrx/platform#2867]
It would be nice if there was a tool which automatically generates flow diagram for the effects and their related actions in an application. Maybe similar to the @nrwl/nx dep-graph. This would especially be handy if an application is more complex and if there are sequences of effects. Also for developers starting with an existing angular+ngrx project they would get a nice overview of how the application works.

Here is a simple "hand" drawn version created with google draw. It's just an example to give you an idea what I approximately mean.

![ngrx-effects-flow (2)](https://user-images.githubusercontent.com/24190530/104025656-40a69c00-51c5-11eb-83ea-4dd0951fcd12.png)

Another idea is to make these items clickable/hoverable so that they show a tooltip with further information. E.g. the reducer function itself if hovering the green hexagons, or the payload if hovering the actions, or the related services and if the effect is using a nested observable, and involved services.

## Describe any alternatives/workarounds you're currently using

As far as I know there aren't any tools for visualising the flow. Procedure is navigating through the sourcecode.

## If accepted, I would be willing to submit a PR for this feature

[x] Yes, but I think it is too much for me alone. A collaboration would be great.
[ ] No

**Comment by brandonroberts** [comment]
I would like to see something like this also at some point. There is one option that's pretty close to what you are looking for now.

ngrx-vis https://github.com/co-IT/ngrx-vis

There's also another one that only supports the older syntax

https://github.com/google/ngrx-visualizer

**Comment by brandonroberts** [comment]
Closing as we don't have any immediate plans for this, but leaving as reference

**Comment by a-p-z** [comment]
Hi, I recently implemented a tool that does more or less what you need. It is similar to the already linked ngrx-vis and ngrx-visualizer.
Here is the link https://github.com/a-p-z/ngrx-graphviz
