### ISSUE TITLE
ngrx/data example app

### ISSUE THREAD

**Issue by Pingear** [ngrx/platform#2868]
Please, add a reference example using ngrx/data, just like https://github.com/ngrx/platform/tree/master/projects/example-app, but using all ngrx/data functions.
Having an example of reference use, you can understand the general principle and best practices, and refer to the documentation only for specific clarifications. The documentation, as it is, does not provide a general understanding of use for beginners. It provides background information that is needed by those who already know how to use your library.

**Comment by yharaskrik** [comment]
Hey @Pingear I am actually working on one right now for some talks I am giving. I will post it here later if the NgRx doesn't get to something first.

**Comment by mgiannelli** [comment]
Hi @Pingear you can find an example of application with ngrx/data here: https://github.com/johnpapa/heroes-angular

**Comment by Pingear** [comment]
@mgiannelli 
Hi) Yes, I've seen this example, but it's a bit poor. I also watched John Papa presentation. 
This is not part of the documentation anyway, and I had to search many examples on the Internet to understand this topic. Therefore, I suggested that the developers add an example that exposes all the functionality of ngrx / data exactly as they expect it to be worth using.
Thanks any way)

**Comment by Pingear** [comment]
@yharaskrik 
It would be really cool if you offer a pull request)

**Comment by timdeschryver** [comment]
I think we could create an example app if someone wants to add it to this repo.
I know there's an example app at the original [angular-ngrx-data](https://github.com/johnpapa/angular-ngrx-data/tree/master/src) repo.

**Comment by yharaskrik** [comment]
Hey @timdeschryver I can clean up my example repo and simplify it a lot and include!

**Comment by yharaskrik** [comment]
Hey @timdeschryver I am working on the example app right now but just wanted to let you know that when i pulled the repo and ran yarn install and then generated the example app the tsconfig.json got removed and the package.json/lock file were updates with angular language service and stuff, then the generated app was trying to reference tsconfig.base.json.

I am assuming that Nx caused that as they migrated away from tsconfig.json. I have switched it back but that might trip others up.

**Comment by yharaskrik** [comment]
Done and done, let me know if that is sufficient or if there are other concepts we would like to include! (Also there is 0 styling because CSS and I are not friends.)

**Comment by Pingear** [comment]
@yharaskrik 
This is a very poor example that can not give anything useful, except for connecting ngrx/data, which is already well described in the documentation.
Look at an example - https://github.com/ngrx/platform/tree/master/projects/example-app
This example is at least a little like a real project. There is authorization, transition between pages, checking whether an article exists in the cache before asking the api. Any beginner can apply this project as a prototype for his project. This is where examples are useful.
And your project is just a piece of code that tells us only that ngrx/data can be connected. I emphasize that your example does not give anything to a person who is trying to understand technology.
 
You had a chance to help thousands of newbies easily integrate technology into their project, and instead you offer them this! Why(

**Comment by Pingear** [comment]
@yharaskrik 
This is a very poor example that can not give anything useful, except for connecting ngrx/data, which is already well described in the documentation.
Look at an example - https://github.com/ngrx/platform/tree/master/projects/example-app
This example is at least a little like a real project. There is authorization, transition between pages, checking whether an article exists in the cache before asking the api. Any beginner can apply this project as a prototype for his project. This is where examples are useful.
Unfortunately, your example does not give anything to a person who is trying to understand technology(

**Comment by yharaskrik** [comment]
@Pingear Although that message did not contribute in a positive way to my day or the NgRx project in anyway, I would like to know exactly what you think is missing from the example app and I will try and take some time out of my day or my free time to make it more clear.

I am always open to constructive criticism but not to unjustified and mean criticism such that you provided. This is an open source project that myself and others help contribute to, I am not even a maintainer of the repo, if you are unhappy with what is being provided to you free of charge and built by many who contribute their valuable time you have two options:

1. Do not use it and find an alternative
2. Provide feedback that is helpful and respectful

I hope your day is goes alright and that you consider being more respectful next time you provide feedback to an open source contributor, it does not take much.

**Comment by Pingear** [comment]
@yharaskrik 
Yes, at first I wrote that you had a chance to be useful for beginners, and instead you launched a very insipid project, of which there are an infinite number of on the Internet. Then I decided that you might be offended and corrected my message. You are offended anyway, it's not nice to see it (

I wrote this because I was very tormented by dealing with the documentation. The example I gave in the last post helped me a lot. I was hoping to see the same on this topic.
I don't need it now, I have studied everything.
But I was offended that you closed this issue with such a useless example.

Open source software - you and I are the same community members, so please don't attack me, since my opinion about your action is categorical.
I am sure that you perfectly understood what you are doing, and that your example will not provide the necessary information for beginners. But you pushed it anyway.
If you want, I can help you with a new example, I can once again apologize for having offended you. But please, let's not deviate from the purpose of this issue, namely to help new community members learn this technology easily )
