### ISSUE TITLE
Type 'unknown' is not assignable to type 'RouterReducerState<SerializedRouterStateSnapshot>

### ISSUE THREAD

**Issue by cswww** [ngrx/platform#2882]
`Error: src/app/app.module.ts:31:26 - error TS2322: Type '<T extends BaseRouterStoreState = SerializedRouterStateSnapshot>(state: RouterReducerState<T> | undefined, action: Action) => RouterReducerState<...>' is not assignable to type 'ActionReducer<unknown, Action>'.
  Types of parameters 'state' and 'state' are incompatible.
    Type 'unknown' is not assignable to type 'RouterReducerState<SerializedRouterStateSnapshot> | undefined'.
      Type 'unknown' is not assignable to type 'RouterReducerState<SerializedRouterStateSnapshot>'.

31     StoreModule.forRoot({router: routerReducer, count: counterReducer, movies: movieReducer, }),
                            ~~~~~~



`



`
    StoreModule.forRoot({router: routerReducer, count: counterReducer, movies: movieReducer, }),`

An error occurred when routerReducer and counterReducer are referenced together

No error will be reported if routerReducer is used alone

**Comment by cswww** [comment]
@ngrx/router-store version 10.1.2

**Comment by timdeschryver** [comment]
Hi, can you create a reproduction please @cswww

**Comment by cswww** [comment]
Sorry, I don't quite understand “create a reproduction”

**Comment by cswww** [comment]
StoreModule.forRoot({router: routerReducer}),     One can run

StoreModule.forRoot({router: routerReducer, count: counterReducer, movies: movieReducer, }),  More than one will report an error

**Comment by cswww** [comment]
StoreModule.forRoot({count: counterReducer, movies: movieReducer, }),   Remove router is ok
