### ISSUE TITLE
Gauging For Interest: Updating `selectRouterParam` and `selectQueryParam` to be selectors with props.

### ISSUE THREAD

**Issue by ZackDeRose** [ngrx/platform#2884]
## Other information:

https://github.com/ngrx/platform/blob/master/modules/router-store/src/router_selectors.ts#L34

Looks like the `selectRouterParam` and `selectQueryParam` are exported as selector factory functions, as opposed to `SelectorWithProp`s.

Would it be worthwhile to change these to be `SelectorWithProp`s and introduce the breaking change? 

Alternatively, we could introduce new `SelectorWithProps` with different name and export them from router-store.

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Personally, I like that these selectors are factory functions. This makes them easier to combine with other selectors.
Also, I think I usually use selector factories over selectors with props because it's easier to prevent mistakes.

**Comment by brandonroberts** [comment]
Closing this one as we've deprecated selectors with props in favor of factory selectors.
