### ISSUE TITLE
ngrxPush pipe returns undefined, type is not correct

### ISSUE THREAD

**Issue by samuelfernandez** [ngrx/platform#2888]
## Minimal reproduction of the bug/regression with instructions:

https://stackblitz.com/edit/angular-ivy-9bbbxq?file=src/app/app.component.html

## Expected behavior:

Right now the typing of the pipe is:
https://github.com/ngrx/platform/blob/master/modules/component/src/push/push.pipe.ts#L82

```ts
transform<T>(potentialObservable: ObservableInput<T>): T;
```

However, if the source doesn't emit on subscription, the first returned value will be `undefined`.

A more strict and real typing would be:

```ts
transform<T>(potentialObservable: ObservableInput<T>): T | undefined;
```

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

`@angular: ^11.0.8`
`@ngrx/component: ^10.1.2`

## I would be willing to submit a PR to fix this issue

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Seems like a good change to me.
Seems like the Angular [async pipe](https://github.com/angular/angular/blob/master/packages/common/src/pipes/async_pipe.ts#L98-L101) uses `null` instead of `undefined` tho, perhaps we should try to keep the same signature/behavior ?

**Comment by samuelfernandez** [comment]
Angular team acknowledges that `undefined` would be a better option, but they can't make the change because it would be too breaking.

- https://github.com/angular/angular/issues/16982#issuecomment-688987110
- https://github.com/angular/angular/pull/39785#issuecomment-731418991

Since this is new in ngrx and there shouldn't be so many compatibility concerns as with Angular, I'd say to go with `undefined` instead of with `null`. If this becomes too opinionated we could define a configuration token with the default empty value.

Besides those comments form the Angular issues, I personally would prefer it for an additional reason. The pipe is used mainly at inputs, and having as empty value `undefined` would allow to simply use an optional property input:

```html
<my-comp [value]="value$ | ngrxPush">
```

```ts
@Input() value?: string;

// Instead of
@Input() value: string | null;
```

**Comment by timdeschryver** [comment]
Thanks for the clarification @samuelfernandez 
Feel free to create a Pull Request.

**Comment by samuelfernandez** [comment]
PR created, ready to be reviewed
