### ISSUE TITLE
refactor(store-devtools): empty() rxjs function is used in a deprecated way

### ISSUE THREAD

**Issue by ngfelixl** [ngrx/platform#2891]
In the store devtools there is a deprecated usage of the RxJS `empty` function in the file `modules/store-devtools/src/extension.ts`. It should be replaced by the `EMPTY` object.

## Minimal reproduction of the bug/regression with instructions:

In the import statements and in the following reference there is the `empty` function used 

https://github.com/ngrx/platform/blob/17f076ccc0f0c0769bc363da72dbf3a3eb73d91b/modules/store-devtools/src/extension.ts#L163

## Expected behavior:

It should use the `EMPTY` object from `rxjs`.

## I would be willing to submit a PR to fix this issue

As discussed on discord I submit this as a "Good First Issue".

**Comment by krishnaanaril** [comment]
@brandonroberts @ngfelixl Are you working on this? If not, I'll submit my PR.

**Comment by ngfelixl** [comment]
It would be great if you would create a PR 😃
