### ISSUE TITLE
Webpage api does not work for items which share case

### ISSUE THREAD

**Issue by bdirito** [ngrx/platform#2896]
dupe of #2676 (though that was closed without resolution or comment)

## Minimal reproduction of the bug/regression with instructions:
It looks like apis for which there exist two api targets differing only in capitialization fail on both requests. One will give a 'Page not found' error. The other will give a 'Request for document failed'

https://ngrx.io/api/store/On 
 => page not found
https://ngrx.io/api/store/on
 => request for document failed

https://ngrx.io/api/store/Props
 => request for document failed
https://ngrx.io/api/store/props
  => page not found

All links are the links as found on https://ngrx.io/api

--
Tested on chrome 87 on linux;

**Comment by spikeynick** [comment]
I get the same results using those urls in Safari

**Comment by timdeschryver** [comment]
This is reslvedd with #2889, this will become available with the next release.
