### ISSUE TITLE
Overriding default getByKey(key: any) method doesn't work

### ISSUE THREAD

**Issue by CodeLiftSleep** [ngrx/platform#2898]
## Expected behavior:

```
@Injectable()
export class SummaryDataService extends DefaultDataService<Summary>{
   constructor(http: Httplient,
   httpUrlGenerator: HttpUrlGenerator,
   private summaryService: SumaryService,
   private router:Router) {
       super('Summary', http, httpUrlGenerator)
   }

//this override works fine
   getAll(): Obervable<any> {
      let state = this.router.getCurrentNavigation().extras.state;
      return this.summaryService.getSummaryData(state.summaryId)
       .pipe(
         map((res: string) => JSON.parse(res))
     );
//this override does not work at all and still uses the default dataconfiguration
    getByKey(key: any): Observable<any> {
       let state = this.router.getCurrentNavigation().extras.state;
       return this.summaryService.getSummaryData(state.summaryId)
        .pipe(
           map((res:string) => JSON.parse(res))
        );
    }
  }
}

```

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
Angular 10.0
ngRx: 10.1.2
Node: 12.17.0

All browsers/ windows 10
## Other information:
Theoretically it doesn't matter if I call the getAll() or getByKey() method since I am calling another service that hits a C# controller that makes the call to the backend and returns the data, but this work properly and I shouldn't have to use this workaround to get it to function.

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
It would be great if you could submit a Pull Request with a fix @CodeLiftSleep

**Comment by Anil-sk** [comment]
I second this, the override for getByKey is not working at all

**Comment by markostanimirovic** [comment]
@CodeLiftSleep @Anil-sk 

Method `getByKey` doesn't exist in `DefaultDataService` class. You are probably looking for `getById` method: https://github.com/ngrx/platform/blob/master/modules/data/src/dataservices/default-data.service.ts#L86

**Comment by brandonroberts** [comment]
Thanks @markostanimirovic
