### ISSUE TITLE
Why component-store has its own debounce implementation

### ISSUE THREAD

**Issue by preda7or** [ngrx/platform#2911]
I was wondering what is the difference between the component-store's debounce and rxjs's built-in debounceTime, and why ngrx is not using the latter.

## Other information:

I would expect having something like debounceTime(0, asapScheduler) would result in the same behavior. (Though I didn't do a thorough testing)

## I would be willing to submit a PR for the docs :heart:

[ X] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by alex-okrushko** [comment]
Hi @preda7or 

Here's the explanation: https://indepth.dev/posts/1372/ngrx-component-store-debouncing#alternative-implementation

**Comment by preda7or** [comment]
Ah the timer... I didn't see that coming. Thx!

**Comment by alex-okrushko** [comment]
Thanks for the question @preda7or 
I didn't think about that initially as well. That's why I ran it by @cartant - someone who know RxJS inside out 🙂
