### ISSUE TITLE
Feature substate service

### ISSUE THREAD

**Issue by preda7or** [ngrx/platform#2912]
I ran into use cases when I needed the complex features of store (e.g. a complex component/page that has deep state object on which sub nested components rely on) but also wanted to be able to make multiple of this substate (e.g for multiple instance of this container or to mitigate complicated state setup/cleanup).

The idea is to have instances of substate which can be interacted with the same way as the global store, without the actions, reducers and selector used in this substate knowing about this "encapsulation".

## Describe any alternatives/workarounds you're currently using

My implementation currently is to provide a "substore" class, that extends the store class but  also responsible to:
- generate a uuid for the current substate
- pluck the substate from the store observable (so selectors are executed on the current substate)
- patche dispatched actions to include the uuid meta information (e.g. as a symbol)
- Register feature reducer if not existing yet
- Inject a reducer level that filters out actions based on their uuid meta info.

## Other information:

I already have a working implementation without tests. I would like to know if there is interest in this feature before putting more effort into it to create a PR.

## If accepted, I would be willing to submit a PR for this feature

[X] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
I feel like we got this covered with [Component Store](https://ngrx.io/guide/component-store).
