### ISSUE TITLE
Confusion about archived repositories

### ISSUE THREAD

**Issue by tobmaster** [ngrx/platform#2914]
## Other information:

Some people still land on https://github.com/ngrx/router-store for example when looking for solutions for ngrx and routing. There is no hint in the readme why its archived and for non experienced ngrx newbies it is not clear its part of the platform, giving the impression its a discontinued project. 

Maybe a big hint like: "The work on router-store is continued in..." would already do the trick.

Thank you

**Comment by david-shortman** [comment]
The top of the readme for that repo reads as follows:

<img width="934" alt="Screen Shot 2021-02-20 at 01 54 41" src="https://user-images.githubusercontent.com/25187726/108586794-a5a1f580-731e-11eb-9a1a-d6cbdf391280.png">

**Comment by timdeschryver** [comment]
I agree with @david-shortman here
