### ISSUE TITLE
ngrx effects inject abstract service

### ISSUE THREAD

**Issue by stefan0s** [ngrx/platform#2915]
Hello,

I am working on a module that is using ngrx. The module is lazy loaded so both Store and Effects Module is loaded forFeature. My custom service is loaded in the main Component as: 
`
@Component({
   selector: 'my-component',
   templateUrl: './my.component.html',
   styleUrls: ['./my.component.scss'],
   providers: [{ provide: MyAbstractService, useClass: MyDefaultService }]
})
`
I also need to use effects that within the effect need to call an abstract service without injecting that service in the app.module. My Effects look like that, but i am getting No Provider for MyAbstractService.

`@Injectable()
export class MyEffects {
   @Effect()
   public loadCollection$ = this.actions$.pipe(
      ofType<any>(collection.LoadAction),
      switchMap(() => {
         return this._myService.viewData$;
      })
   );

   constructor(private actions$: Actions, private _myService: MyAbstractService) {}
}`

How can i properly inject that service to my Effects?

**Comment by timdeschryver** [comment]
AFAIK you can't, the Effect exists in the application scope and is not bound to a component.
If you want effects to live in the lifecycle of a component, you should take a look at [Component Store](https://ngrx.io/guide/component-store)
