### ISSUE TITLE
schematics: NgRx 11 ng upgrade

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#2917]
This one is reported on Discord.
Running `ng upgrade @ngrx/schemarics` throws the following error.

```
An unhandled exception occurred: Cannot find module \node_modules\@ngrx\schematics\src\index.js'. Please verify that the package.json has a valid "main" entry
```

The `package.json` references an index file that does not exists

```
  "main": "src/index.js",
  "typings": "src/index.d.ts",
```

**Comment by dlq84** [comment]
Same error as me, the file src/index.js doesn't even exist.
