### ISSUE TITLE
StoreDevtoolsModule is affecting the change detection for selectors

### ISSUE THREAD

**Issue by TheParad0X** [ngrx/platform#2918]
I came across an interesting behaviour in my app:

I used this way to disable the DevTools in production mode:

```
@NgModule({
  imports: [
   ...
    StoreModule.forRoot(appReducers, {
      metaReducers
    }),
    ...
    environment.devMode ?
        StoreDevtoolsModule.instrument({
        name: 'MyStore',
	maxAge: 100,
    }) : [],
  ],
  ...
  })
```

This led to a **different change detection behavior in Dev and Prod mode**. Consider this state and its selectors:

```
export interface MyState{
  timerValue: number; // Is updated every second
}

export const selectMyState = createFeatureSelector<MyState>('myState');
export const selectTimerValue = createSelector(
  selectMyState,
  (myState) => myState.timerValue);
```

And its usage in a template:
```
<ng-container *ngIf="store.select(selectUpdateTimer) | async as timerValue">
    {{ timerValue }}
</ng-container>
```

In **Dev Mode**, I would see the timer value change every second - the async pipe (and its internal markForCheck()) are enough to trigger the change detection.

In **Prod Mode** however, the timer value would not change every second, unless I triggered the change detection by opening a menu or so, and the I would see the actual current value of the timer. So I had to subscribe to my selector in the TS file and call detectChanges() every time it fires. This solved the problem.

**My question: Why does the presence of StoreDevtoolsModule affect the change detection ?**

Angular 11.1.1, Ngrx 10.1.2, Rxjs 6.6.3

**Comment by timdeschryver** [comment]
As discussed on our NgRx discord server, a reproducion will be helpful.

**Comment by TheParad0X** [comment]
Unfortunately, I was not able to reproduce it with a simple new project. There must be something different in within my rather complex project. So I guess this can be closed.
