### ISSUE TITLE
Listen router events using ComponentStore

### ISSUE THREAD

**Issue by dev054** [ngrx/platform#2920]
To listen router events using `@ngrx/store` and perform operations we could do something like this:

```
readonly test$ = createEffect(
  () =>
    this.actions$.pipe(
      ofType(routerNavigatedAction),
      tap(({ payload }) => ...),
    ),
  { dispatch: false },
)
```

Is it possible to achieve the same functionality using `@ngrx/component-store`? If so, can it be documented? Or perhaps, a more abrangent docs on how to listen global store using `@ngrx/component-store`?

## I would be willing to submit a PR for the docs :heart:

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
An effect is ComponentStore is essentially the same. Efffects are just subscribers to streams. Here is an example.

https://stackblitz.com/edit/ngrx-component-store-router?file=src%2Fapp%2Fcomponent-router.store.ts
