### ISSUE TITLE
How to provide DefaultDataService without creating Custom Data Service?

### ISSUE THREAD

**Issue by MariaLazarenko** [ngrx/platform#2925]
I have a lazy loaded module and I don't need any custom data services. The DefaultDataService is enough for me. But I can't find out how to provide it. I've found in Documentation only how to provide custom services.

I have the following configuration and I'm getting an error `NullInjectorError: No provider for DefaultDataService!`

Then I tried to add DefaultDataService to providers in App module `providers: [DefaultDataService]` but got an error `Can't resolve all parameters for DefaultDataService: (?, ?, ?, ?).`

app.module.ts

```
    @NgModule({
      declarations: [AppComponent],
      imports: [
        BrowserModule,
        AppRoutingModule,
        StoreModule.forRoot({
          auth: authReducer,
        }),
        EffectsModule.forRoot([AuthEffects]),
        EntityDataModule.forRoot({}),
        StoreDevtoolsModule.instrument({
          maxAge: 25, // Retains last 25 states
          logOnly: environment.production, // Restrict extension to log-only mode
        }),
        HttpClientModule,
        TranslateModule.forRoot({
          loader: {
            provide: TranslateLoader,
            useFactory: createTranslateLoader,
            deps: [HttpClient],
          },
          defaultLanguage: 'ru',
        }),
        BrowserAnimationsModule,
        CoreModule,
        NgbModule,
      ],
      providers: [],
      bootstrap: [AppComponent],
    })
    export class AppModule {}
```

teacher.module.ts (lazy loaded module)

```
    const modules = [
      CommonModule,
      TeacherRoutingModule
    ];
    
    const components = [
      TeacherComponent,
      TeacherApplicationComponent
    ];
    
    @NgModule({
      declarations: [...components],
      imports: [...modules],
    })
    export class TeacherModule {
    
      constructor(private eds: EntityDefinitionService) {
        this.eds.registerMetadataMap({
          Teacher: {}
        });
      }
```

So I don't have any idea how to provide this DefaultDataService without creating custom services.

**Comment by timdeschryver** [comment]
Hi, support questions should be asked on our [discord server](https://discord.com/invite/ngrx) or [stackoverflow (with a ngrx tag)](https://stackoverflow.com/questions/tagged/ngrx).
