### ISSUE TITLE
Types of property 'isOptimistic' are incompatible. Type 'boolean' is not assignable to type 'true' in EntityCollectionServiceBase after upgrade from @ngrx/data v10.1.2 to v11.0.0

### ISSUE THREAD

**Issue by Rob4226** [ngrx/platform#2928]
Hi,
I just upgraded @ngrx/data from v10.1.2 to v11.0.0 but now in my class that overrides `EntityCollectionServiceBase` I get a TypeScript compile error:
> Types of property 'isOptimistic' are incompatible. Type 'boolean' is not assignable to type 'true'.

I think it has something to do with #2899 and #2906.

Here is my code:
```typescript
export class UUIDEntityCollectionServiceBase<
  T extends UUIDEntity
> extends EntityCollectionServiceBase<T> {
  constructor(
    public entityName: string,
    private _dataService: UUIDBasedEntityCollectionDataService<T>,
    private _log: LogService,
    serviceElementsFactory: EntityCollectionServiceElementsFactory
  ) {
    super(entityName, serviceElementsFactory);
  }

  /**
   * Overriding the default `EntityCollectionServiceBase#add()` method so I can
   * add a random uuid as the id of the entity being added and automatically
   * update the `dateAdded` and `dateUpdated` fields.
   * @param entity The new entity to be added.
   * @param options Optional options for the entity.
   */
  add(entity: T, options?: EntityActionOptions): Observable<T> {
    entity = {
      ...entity,
      id: this._dataService.generateValidEntityId(),
      dateAdded: Date.now(),
      dateUpdated: Date.now(),
    };
    return super.add(entity, options); // *HERE options has the error: Types of property 'isOptimistic' are incompatible. Type 'boolean' is not assignable to type 'true'.
  }
}
```

Just as a test to try to get the signatures right, I replaced my overridden code for `add()` with the `add()` function code directly from the ngrx/data[ source code](https://github.com/ngrx/platform/pull/2906) I get another error:
> Types of parameters 'options' and 'options' are incompatible.
      Type 'EntityActionOptions & { isOptimistic: false; }' is not assignable to type 'Pick<EntityActionOptions, "correlationId" | "mergeStrategy" | "tag" | "error" | "skip"> & { isOptimistic: true; }'.
        Type 'EntityActionOptions & { isOptimistic: false; }' is not assignable to type '{ isOptimistic: true; }'.
          Types of property 'isOptimistic' are incompatible.
            Type 'false' is not assignable to type 'true'.ts(2416)
```typescript
// ...
// Both `add()` functions are unerlined with the above error.
add(
    entity: Partial<T>,
    options: Omit<EntityActionOptions, 'isOptimistic'> & { isOptimistic: true }
): Observable<T>;
add(entity: T, options?: EntityActionOptions): Observable<T> {
    return this.dispatcher.add(entity, options);
    // return super.add(entity, options); // same error as above line
}
// ...
```

All I want to do is pass along the optional argument `options` to the parent function like I did in v10.1.2.  How do I clear the error? Thank you!!
```typescript
// ...
return super.add(entity, options); // *HERE options has the error: Types of property 'isOptimistic' are incompatible. Type 'boolean' is not assignable to type 'true'.
// ...
```

**Comment by brandonroberts** [comment]
@yharaskrik any ideas here? I think we introduced a fix for this already

**Comment by yharaskrik** [comment]
Oh Hmm good question. What we did was type function such that if isOptimistic is false then it takes Partial<T>, there must be a conflict somewhere, maybe it doesn't work when explicitly passing true since true is the default? I don't think I actually ever tried that case... I'll see if I can find some time today to check out the typings!

**Comment by yharaskrik** [comment]
@brandonroberts I loosened up the typings on the add function. @Rob4226 I pasted your code into the data-example-app to ensure your passthrough function worked as expected, it seemed too.

**Comment by brandonroberts** [comment]
Thanks @yharaskrik!

**Comment by yharaskrik** [comment]
No problem! Hopefully this doesn't cause any other problems but it shouldn't as the original signature is very open. 🤷‍♂️

**Comment by Rob4226** [comment]
@yharaskrik @brandonroberts Thanks for your help guys!!

**Comment by yharaskrik** [comment]
You are welcome!

**Comment by Emilius449** [comment]
hi, 
I just upgraded @ngrx/data from v11 to v12.1.0 and i got the same issue on entity-collection-service-base

 add(entity: Partial<T>, options: EntityActionOptions & {
        isOptimistic: false;
    }): Observable<T>;
