### ISSUE TITLE
Uncaught ReferenceError: Store is not defined

### ISSUE THREAD

**Issue by MursalovAltun** [ngrx/platform#2933]
## Minimal reproduction of the bug/regression with instructions:

After update to v11 angular & ngrx the application throws Store is not defined exception on production build

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
Ngrx: 11.0.1
Angular: 11.1.0

**Comment by timdeschryver** [comment]
This will be hard to debug without a reproduction.
Please, attach a reproduction.

**Comment by MursalovAltun** [comment]
> This will be hard to debug without a reproduction.
> Please, attach a reproduction.

Sorry it's more related to angular builder than ngrx. Has been fixed updating angular to 11.2.1

**Comment by timdeschryver** [comment]
Thanks for the update @MursalovAltun , I'm closing this issue.
