### ISSUE TITLE
[router-store] Navigation error message is lost when using RouterState.Minimal

### ISSUE THREAD

**Issue by mistic100** [ngrx/platform#2934]
I realised that the "ROUTER_ERROR" action does not contains the original error message/stack emitted by Angular.

I didn't tracked this completly but I think it is because of these lines that strips the event properties when using RouterState.Minimal.

https://github.com/ngrx/platform/blob/86a5662adacffc563c18c9d26d691d2d1ac0f8f0/modules/router-store/src/router_store_module.ts#L327-L330

It could be a good idea, in case of a navigation error, to always include the full error, otherwise this action is pointless when wanting to globally handle different errors (loading chunk error, guard error, etc).

**Comment by timdeschryver** [comment]
This is by design.
The error contains properties that are not serializable.

**Comment by mistic100** [comment]
`name` (type string) and `message` (type string) are not serializable ? 😕

**Comment by timdeschryver** [comment]
[NavigationError](https://angular.io/api/router/NavigationError) is a class, these are not serializable.
You can create a [custom serializer](https://ngrx.io/guide/router-store/configuration#custom-router-state-serializer) that contains the data that's needed for your use case.

**Comment by mistic100** [comment]
If I am not wrong a custom serializer wil not allow to customize the payload use in `dispatchRouterAction` it is all or nothing.

My point is the serializer is called "Minimal" not "Strip EverythingThatCouldBeUseful", I don't see how it is a problem to pass useful information to error actions when using a Minimal serializer (obviously by extrating serializable data from the NavigationError class)
