### ISSUE TITLE
Migrate to ESLint

### ISSUE THREAD

**Issue by david-shortman** [ngrx/platform#2938]
## Describe any alternatives/workarounds you're currently using
- N/A

## Other information:
We all know TSLint is EOL, so migration to ESLint is inevitable.

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Let's wait on https://github.com/nrwl/nx/pull/4328 :)
