### ISSUE TITLE
Component Store other use cases

### ISSUE THREAD

**Issue by fgoulet** [ngrx/platform#2942]
I really like the Component Store. I'm looking forward to use it with the other envisioned use cases:

Use Case 2: Complex Common Component State
Use Case 3: Complex Independent Component Store
Use Case 4: Application-wide Singleton Service

Any estimated time frame for the official documentation (or even just a draft) to be available ?

In the meantime, does anybody has code to share (pseudocode, prototype, experimentation...) that could help me getting started implementing those use cases in my application ?

Thank you !

**Comment by alex-okrushko** [comment]
The documenting for these cases have been on my plate for some time now. I'll see what I can do about it.

In the meantime, you can watch the use cases here: https://youtu.be/v5WSUE1_YHM

At around 40 mins.
