### ISSUE TITLE
Missing instructions to quick start the ngrx/data experience

### ISSUE THREAD

**Issue by BenLune** [ngrx/platform#2943]
Hi there,
Thank you so much for this great stuff !
I use ngrx since 3 years on many projects and wanted to give a try to ngrx/data. I spent a few hours on this link : 
https://ngrx.io/guide/data

The informations given seems to be ok to start quickly, but it doesn't work if you follow the steps.

In the app.module.ts description the Effects array is empty, so nothing is triggered when we call getAll on the created DataService, you should add this :
EffectsModule.forRoot([EntityEffects])

I think it would help people boarding on ngrx/data.

Best regards,
Benoît

**Comment by timdeschryver** [comment]
I'm not familiar with data, but is that really needed? I thought data does this for you.
The examples I see, don't need to do this.
