### ISSUE TITLE
Type '(a: string, b?: boolean) => Ngrx/store - action - Error message: ` ... is not assignable to type '"empty objects are not allowed in action creators"`

### ISSUE THREAD

**Issue by Lertis** [ngrx/platform#2947]
I have got an error when did migration from v10 to v11 of NGRX.

Here is my action
![image](https://user-images.githubusercontent.com/24374130/109271800-ae139800-7818-11eb-8c26-0d4bef9e21b3.png)
And error:
![image](https://user-images.githubusercontent.com/24374130/109271839-bd92e100-7818-11eb-86d4-60e3ab3a8634.png)

I did something link (a: string, b: boolean = false) and the error disappeared for me, but another occurs: Type boolean trivially inferred from a boolean literal, remove type annotation
![image](https://user-images.githubusercontent.com/24374130/109271748-9d632200-7818-11eb-9ea5-21aacc9200a1.png)

Any ideas on how to provide a default value for function-based action?

https://stackblitz.com/edit/angular-action-func?file=src%2Fapp%2Fapp.component.ts

**Comment by david-shortman** [comment]
A workaround would be

```typescript
const c = (a: string, b = false) => ({ a, b });
const myAction = createAction("ACTION", c);
```

It's weird that the type inference fails and the `NotAllowedCheck` thinks the return value type has no keys in your example, but if the creator function is declared separately, it works fine.

**Comment by david-shortman** [comment]
Here's a reproduction of the type error being thrown in a TS playground: https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAYwgOwM7wEoFEDiBJAZQBUtsARAfQEEBhIvAeQDkKiBNABSwIC44BvOAG0AhghgBLFEQCeYYH3RQJyAOYBdPsgCuAWwBGwKHAC+cALwCTAbgBQt0JFiIU6OCKhQRM1FSjAmCBgqABsQiAB3YAATAFlUVQtbODgAcg8vH3d-OGQg9zDImLgVd3EpZER-ERhoVFS7GDlgOD9M339A4MKo6Is4JvkIADNs9r8AoNDw3vjVOwdwaHgkNHhB4A4oCHlYGTxULumiuISklNSNuDBt3aaS1Fz8kR7i0rFJFCrgGrqG2yusnkWx2RiaByOrz6lg2IwGzRBd32hymULmC0cyxcazgwF0YCaDH0ACtgOIOpNujMYnNzmk8QSZHAICSyTBHh4Wnl4C9qX13uUvghqrUoPVGs04Fh8YTWeSJpC+f1YaMGbLSfLOqi+ej7JjnFcAGLaZCC5AQ7UnAA8yTgRAANLasJ5oLFgKhUCJVC1QDBgMhoo8lCpVLYAHz9Ii4kB+gOPY2mz6VAD8UpdUDdHq9LT4RDsAHoAFSF5KF1pwYYms0DAAWNTg-hg2igaHclRZGvgpRgNZaqDr8mZox7LQABlQzaOSsg-VBhmJgAA6FI0FDDCSqZvFbSoENwUfCn5+idJ0eL0v5xZOdaSmgi6A2lIcaOxwNtmRCdT9ETID-qR0pBgL7+m+HZsv0YHiOG-QJmaADqEg9hwHgiLowCzqgQLAFaHD2nAGBhhiSwGpKionDQvYIAA1laUa+iBjyQTAEaWHRMYMe+n62qmbTeBSZG9LaubAXGAjwvIfA-kyJjcXaCK3GCyICTEQlwFRwAyHCbGvo8yDAAAbkYsnSoyRKdvxlqCSkfAmlReQRMgCwpEWJZwGWBDAGOd5HtAZ4XleWJXCeFTeb8UCPnaIlvsGaj9DFqgAXANBRY8oWiv0aXQNBljJQAZHJ8jRMFKC0YRerEV2M5GPOCAtMVyCZVAiKoKVAi2hQIioHwqQ3Ds4rtWAuZ2DJAUkYOsFJghSEoWhGFYThKVwLZ9nIJ+eFAZY+kQBI0QsXAAAUtqLsdHiqF1cAcLYACUFgRhgRHXtOs41XV1b8LaGyKDAyhqMN9j5vmcDRGSIScgMEBwLoIjqSU8C9UiAC0-jIKhe6esMwCjfAwMIKDOQqM9C4FTE9W0Yt8URvRon1W1KTVNEKAhEyn12n9tiVomFRA8A656fN2kcRTh0pCzDq2oeYV8I1118PVjWte9dPoc2lRmWyi7A7zmwKXs+0S6KeGXM0qR4YrKRwPpLzaAo4nAIlKQRMoMAiPoIQ2-OISoHbtomFdbP6vAHPVvrwCkwLolCx9zS5jLrRmvLDoHTd5gRlhRVmqVZUBxWVZJt8NShxn4fRd9IZ4c+VOgXKzHC7buaJas66qLL8f3k1twtRwEb5cp0QUWSNFd7Hctt7ReH7fD53Pj3lkxP31E4WGycRtPxPp0mmd2NnQd5yHpO2sXQal2oiUV+xolSWttpAZXjHV+Gteiw3bdS6PuH4d3cC9-PNEEbHE0VCmjWZCXhZpGEws0HC604D5TTmHMMn84FFyzhVHOnMhQikLhvQ+cB4p4WSrfJKbcwyP2jnaBua4NzJj4IIDq50eod1SKYOAAAfJKw9W4+XCkQCMZtsD4GIKQLAlBaD0GYKwTg3AhAbC-JYfa-DCAkHINQOgjAWDsC4AQaRzQvwsLYQABhugAajgAARiciUUY+0VTYibhYcwlhUg7wqKkG6ZslZNhbNzLWWFrHNHHsdRcp1zqX3UMvA67jzaBMbhufagTglXXtubDYSTfZ+x9uLVwPJHiWBiYkVMeTFx0LgN1NUMh-gpFQBERCCAawHU6m420KQECdRaKkMpqQeBNPNo2FW3iVDAF8SkpOt0Im21MFddJ5tECtLSJPTp3SPF9M1gMoZ-iDqTz4ExcJ+1InTMCZPJJ0yUmLImVM82msRDaBCDALp0yRY1m2BEXIwBnnOm2FAfaqQACqelwBsmKIU1xdgUgyRGqsNwDN3QzjgtAKi-Q95mi+R8Fx48RBfR+glOA+h+gey9jswQIg8I4rSXYKFqAYVwq+agCAs0awhmBbYcllKoBUWpbS9C9K1AmwGFAa26T7AQpWP0fa6LcHHyxTiyweLgAEvcMSiZdghVwAiHCnJ+djxIvSGaHlCB0mqtZagdldKGX6rVcazlDK8LfX5dYIAA

**Comment by Lertis** [comment]
@david-shortman Yeah, I was thinking about this approach. Another - is to manage the default value in the reducer. For v.11 a new rule added into createAction function.
![image](https://user-images.githubusercontent.com/24374130/109306528-f5fde380-7847-11eb-9d08-ab8f60765fa2.png)

Thanks for the reply!

**Comment by david-shortman** [comment]
The rule you're referencing is valid, but doesn't apply to the creator you're supplying. Somehow TS is inferring the return type of the creator function incorrectly such that it thinks it has no keys, and thus it fails the `NotAllowedCheck`.
Workaround is fine but we should address this bug either here or open with TS if it's not our fault.

**Comment by Lertis** [comment]
@david-shortman totally right. If not SonarLint extension's rule as ```flag: boolean = false``` is not needed type annotation.- I would face something like that.
