### ISSUE TITLE
ngRx data does not complete properly in resolve, must use workaround to manually setLoaded to true

### ISSUE THREAD

**Issue by CodeLiftSleep** [ngrx/platform#2950]
## Minimal reproduction of the bug/regression with instructions:

https://stackblitz.com/edit/ngrx-seed-ff5gd8
**need to have a server and cannot use stackblitz to import express...have it set up you would need to install a server locally to get it to work

The issue is that we manually have to call setLoaded(true) to get the resolve to complete and we shouldn't have to.  Without using the bolded line of code below in the subscribe:
**next: () => this.myResolveEntityService.setLoaded(true)**
, the resolve never completes because looking in Devtools at the entity state in the entityCache for this item, "loaded" is still false even though all the data is present.

```
import { Injectable } from "@angular/core";
import {
  ActivatedRouteSnapshot,
  Resolve,
  Router,
  RouterStateSnapshot
} from "@angular/router";
import { Observable } from "rxjs";
import { filter, take, tap } from "rxjs/operators";
import { MyResolveEntityService } from "./myResolveEntityService";

@Injectable({ providedIn: "root" })
export class MyResolve implements Resolve<boolean> {
  constructor(
    private myresolveEntityService: MyResolveEntityService,
    private router: Router
  ) {}
  resolve(
    route: ActivatedRouteSnapshot,
    state: RouterStateSnapshot
  ): Observable<boolean> {
    return this.myresolveEntityService.loaded$.pipe(
      tap((loaded: boolean) => {
        if (!loaded) {
          this.myresolveEntityService.getAll().subscribe( ()=> {
              next: () => this.myResolveEntityService.setLoaded(true) //<---- this is required currently to complete the resolve!!!
          });
        }
      }),
      filter(loaded => !!loaded),
      take(1)
    );
  }
}
```

## Expected behavior:

Resolve completes once EntityService loads data and entityService.loaded$ returns true WITHOUT the need for manual intervention and additional code in the subscribe.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s): 
Angular 11.1.0
ngRx 10.1.2
Node: 12.17.0

All browsers, Windows 10
## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
Support questions should be asked in the [gitter channel](https://gitter.im/ngrx/platform) or the [Discord](https://discord.gg/ngrx)
