### ISSUE TITLE
StackBlitz Book example not current

### ISSUE THREAD

**Issue by mousedownmike** [ngrx/platform#2953]
The README.md file in `projects/example-app` provides a link to a [StackBlitz](https://ngrx.github.io/platform/stackblitz.html):
```md
... Try it on [StackBlitz](https://ngrx.github.io/platform/stackblitz.html).
```

The code loaded in that StackBlitz instance appears to be old.  I'm new to this but it appears that `ngrx-store-freeze` is no longer necessary.  However, in the StackBlitz code, it is both imported and used in the example.  This is different than what I see in the example app found in the repository.

```typescript
import { storeFreeze } from 'ngrx-store-freeze';
//...
export const metaReducers: MetaReducer<State>[] = !environment.production
  ? [logger, storeFreeze]
  : [];
```
## Other information:

I'm happy to help but I believe this is probably a build related issue.  I'm not very familiar with how StackBlitz source is populated.

## I would be willing to submit a PR for the docs :heart:

[X] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
Fixed via https://github.com/ngrx/platform/pull/2969
