### ISSUE TITLE
NGRX is not working with Angular 11

### ISSUE THREAD

**Issue by psahni** [ngrx/platform#2956]
#### In my package.json

```
"@ngrx/core": "1.2.0",
"@ngrx/store": "^11.0.1",
"@ngrx/store-devtools": "11.0.1",
```

### 
- Dispatch events are not working
- I update the value in store 
- ```
#### In Code
```
this.store.dispatch({
      type: USER_BUSY,
      payload: {
        busy
      }
});
```

```
this.myService.getReducer().subscribe((user) => {
   console.log('Subscription called')
}));
```

The subscription never called.

Please help

**Comment by spierala** [comment]
Hi, what is `this.myService.getReducer()` doing? Is it returning an Observable?
In NgRx you subscribe (in most cases) on selected state observables: `store.select(someSelector).subscribe()`

Are you refering maybe to an old example like this?:
https://v7.ngrx.io/guide/store/recipes/injecting
If I look at that example, I think that getReducers should return a map of Reducers. But it won't be an Observable.
Subscribe callback will never be called.

**Comment by timdeschryver** [comment]
Please remove `@ngrx/core` and try again.
If that doesn't solve it, can you add a reproduction and reopen this issue please?

**Comment by psahni** [comment]
@timdeschryver  @spierala 
Thank you very much your responses.
It works for me now.
I just kept ngrx/store, and removed the other two
```
"@ngrx/store": "^11.0.1",
```
@spierala - the getreducer function returns the observable as mentioned by you. Thank you.
Your kind of people keeps the community alive.
