### ISSUE TITLE
https://v10.ngrx.io/ is down

### ISSUE THREAD

**Issue by shajanjp** [ngrx/platform#2960]
https://v10.ngrx.io/ is not accessible.

**Comment by mousedownmike** [comment]
The site is accessible but it is presenting a firebase.com certificate.  Most browsers will make it difficult to access.

**Comment by brandonroberts** [comment]
@shajanjp it should be available and will have the correct certificate when firebase finishes setting it up

**Comment by shajanjp** [comment]
Thank you, @mousedownmike @brandonroberts. I was just letting you guys know. I was not sure where to report this too.

**Comment by david-shortman** [comment]
It's alive 🧟‍♂️!
