### ISSUE TITLE
Feature Request: Allow MockStore.overrideSelector to accept an Observable as its second argument

### ISSUE THREAD

**Issue by rmorrise** [ngrx/platform#2962]
Hi! ngrx is great!

Coming over from the older unsupported ```angular-redux/store``` framework, one thing I miss is their ability to provide an Observable as a mock response for ```store.select``` calls.

It would be so useful if I could use ```overrideSelector``` with an Observable. This would make it easy to use with Jasmine marbles, for example, when testing Effects or Components/Service methods that listen to the store:

```
      // set up marble diagram for the test using Jasmine marbles
      const promptFlag$ = hot('ff-t-f-t', {f: false, t: true});
      const dataToBeSaved$ = hot('---a---b', {a: {}, b: {}});

      // specify that calls to ```store.select``` should return the marble diagram Observables when the specified selector is sent
      store.overrideSelector(selectShowPromptFlag, promptFlag$);
      store.overrideSelector(selectShowPromptFlag, dataToBeSaved$);
```

If necessary, this could be a new method:
```
      store.overrideSelectorWithObservable(selectShowPromptFlag, promptFlag$);    
```

## Describe any alternatives/workarounds you're currently using

Here is the workaround I'm currently working on. I think this does the same thing but looks a lot uglier:
```
      store.select = createSpy('select').and.callFake((selector) => {
        if (selector === selectShowPromptFlag) {
          return promptFlag$;
        } else if (selector === selectDataToBeSaved) {
          return dataToBeSaved$;
        } else {
          fail('Unexpected selector');
          return;
        }
      });
```

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by david-shortman** [comment]
I have the same desire from the enterprise app I work on.

This small workaround we use would probably map to to some kind of real implementation here as well:

```typescript
// in beforeEach
selectOverrides = new Map<MemoizedSelector<unknown, unknown>, unknown>();
spyOn(store, 'select').and.callFake(selector => selectOverrides.get(selector) ?? fail('Unexpected selector'));

// in some some test
selectOverrides.set(someSelector, cold('ab', { a: 1, b: 2 }));
```

**Comment by david-shortman** [comment]
Since `overrideSelector` suggests that the _selector function_ return value is being overriden, maybe the appropriate name for this functionality would be `overrideSelect`, which overrides the observable returned when selecting the selector.

**Comment by rmorrise** [comment]
> I have the same desire from the enterprise app I work on.
> 
> This small workaround would probably map to to some kind of real implementation here as well:
> 
> ```ts
> // in beforeEach
> selectOverrides = new Map<MemoizedSelector<unknown, unknown>, unknown>();
> spyOn(store, 'select').and.callFake(selector => selectOverrides.get(selector) ?? fail('Unexpected selector'));
> 
> // in some some test
> selectOverrides.set(someSelector, cold('ab', { a: 1, b: 2 }));
> ```

Thanks for the sample code!

One thing I was wondering about is, is there any reason why the mock implementation has to implement the MemoizedSelector interface? Why not just use Observable? I didn't really understand the purpose of MemoizedSelector

**Comment by david-shortman** [comment]
The `Map` type takes the following generics: `Map<TypeOfKey, TypeOfValue>`.

So `selectOverrides` is a `Map` where the keys are `MemoizedSelector`s and the values are `unknown`.

I suppose for this example, since we only want `selectOverrides` to return observables when we retrieve an override, we could type it as `Map<MemoizedSelector<unknown, unknown>, Observable<unknown>>` instead.

**Comment by david-shortman** [comment]
To clarify, selectors themselves are _not_ observables. They are merely functions which NgRx does some special magic to memoize.

Instead, observables are _produced_ by calling `store.select` on a selector function reference.

Then, the keys of `selectOverrides` are selector functions, and the values are the Observables `store.select(someSelector)` should return.

**Comment by rmorrise** [comment]
> To clarify, selectors themselves are _not_ observables. They are merely functions which NgRx does some special magic to memoize.
> 
> Instead, observables are _produced_ by calling `store.select` on a selector function reference. This gives us the selector's value over time.
> 
> Then, the keys of `selectOverrides` are selector functions, and the values are the Observables `store.select(someSelector)` should return.

You're right, sorry, I misread your code.
Earlier, I was trying to figure out the return type of overrideSelector:
```
overrideSelector<
    Selector extends Memoized<Result>,
    Value extends Result,
    Result = Selector extends MemoizedSelector<any, infer T>
      ? T
      : Selector extends MemoizedSelectorWithProps<any, any, infer U>
      ? U
      : Value
  >(
    selector: Selector | string,
    value: Value
  ): OnlyMemoized<typeof selector, Result>
```

It looks like it returns ```OnlyMemoized``` where I would have expected ```Observable```

**Comment by david-shortman** [comment]
started an implementation of `overrideSelect`: https://github.com/ngrx/platform/compare/master...david-shortman:mock-select

**Comment by brandonroberts** [comment]
As I mentioned in the PR, we won't be introducing this change. Mocking the select function and passing an observable based on the selector is a solid alternative.
