### ISSUE TITLE
NgRx Data: Cannot inject entity services to a service

### ISSUE THREAD

**Issue by SanteriMagister** [ngrx/platform#2964]
### In our gitter support channel at https://gitter.im/ngrx/platform

Neither
`
public constructor(private readonly objectEntityService: ObjectEntityService) {}
`

nor

`
public constructor(entityServices: EntityServices) {
        entityServices.getEntityCollectionService("Object");
}
`

works inside a service. Injecting to a component works fine. The app compiles but I get a blank web page when it's served. Tested on Angular 11.0.6 and 11.2.3.

**Comment by timdeschryver** [comment]
Hi, support questions should be asked on [stackoverflow (with a ngrx tag)](https://stackoverflow.com/questions/tagged/ngrx) or you can join our [discord server](https://discord.com/invite/gCEj4zC) and ask your question there.
If you ask the question on these channels, adding a reproduction will help us to debug the problem.
