### ISSUE TITLE
Inferred generic type of reducers Number/String/Boolean instead of number/string/boolean

### ISSUE THREAD

**Issue by lephyrus** [ngrx/platform#2966]
When the state is a `number`, `string` or `boolean`, and the reducer function uses no parameters (`() => newState`), the generic type of the action reducer is wrongly inferred to be `Number`, `String` or `Boolean`.

This leads to Typescript errors either in `createReducer()` itself (depending on the order or the action reducers) or later on.

This was not an issue in `@ngrx/store` v10 - I hit this as I've upgraded to v11.

## Minimal reproduction of the bug/regression with instructions:

Reproduction in the [Typescript playground](https://www.typescriptlang.org/play?noUnusedLocals=true&noUnusedParameters=true&ts=4.2.3#code/JYWwDg9gTgLgBAbzgQQMY2BAdgGhezLAJQFMATAV1RKj1ShIEMYS0Ns6HmTTLra4HOGCgQwAZzgBfOADNRIOAHIAAlgDmUAB4B6cTGgklAbgBQp1Nn1xgWYBkYAbAMoxuALjhYKIAEY04AF44AAYzCyt4cRIYNkIguHomFjjsAAolaJglPBExcQAeJAA3JwoST28-AKkAPjSASgazSyxrBizUrASk7i6MjpilZvMSLUhYRMi5RmBHW3VeKgDg3pYl-jTTOBs7Bxc3FhxtwSw0zoIhNIB9fW48ErKSaQag2rhSx3KG4530wdil1wcEab129mATlc3B+phGpjGE3grWsAHdoABrBYbFaJLjrcjLKBbHa2CFQw4kX6nNIArp4UGBd5k-bQliwv5nC7sYE3O5HRAfJ4vMGfb7HeGI6DI6aIkjochdHFQTxKwn8ApVfwCLrvYLoqBYjTKsxSyYo+CMdAUJxqvg0VVA5UFAByPm1eF1CQNRsW6poxiAA).

```ts
import { Action, ActionReducer, createAction, createReducer, on, props } from '@ngrx/store';

const initialState: number = 0;

const setAction = createAction('set', props<{ value: number }>());
const resetAction = createAction('reset');

export const failingReducer = createReducer(
  initialState,
  on(setAction, (_state, { value }) => value),  // Typescript error
  on(resetAction, () => initialState),
);

export const workingReducer = createReducer(
  initialState,
  on(resetAction, () => initialState),
  on(setAction, (_state, { value }) => value),
);

export const expectedActionReducer: ActionReducer<number, Action> = workingReducer;  // Typescript error
export const actualActionReducer: ActionReducer<Number, Action> = workingReducer;
```

## Expected behavior:

If the state is `number`, `string`, or `boolean`, reducers' inferred generic type should be the same, even if there is a "reset-style" action reducer.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

NgRx: 11.0.1
Typescript: 4.1.5 / 4.2.3

## Other information:

The workaround is to add the state argument to the reducer function even though it is not needed:

```ts
export const reducer = createReducer(
  initialState,
  on(setAction, (_state, { value }) => value),
  on(resetAction, (_state) => initialState),
);

// works!
export const expectedActionReducer: ActionReducer<number, Action> = reducer;
```

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[X] No

**Comment by parloti** [comment]
Now I can no longer use on() with a generic state. Apparently, problem with type inference.

[Play](https://www.typescriptlang.org/play?noUnusedLocals=true&noUnusedParameters=true&ts=4.2.3#code/MYewdgzgLgBMBOBTAhlE8YF4ZgK4Bt8ZkIZcwBrMEAdzGNIEFgoBLcAYSVXQG4AofgDNyLdvQQooiAOKIwieK2AAlRABNcwRQB4AKgGUoqRDEQAPaWHWkQAIwBWiFgD4AFKzCs2yfEZMAXDCGxtIAlEHMbOBqmtrw+v7SLjAA3vwwcODQMEhxilhw3NKxWopuGZkwnt6svkmIADSVmeBukjzwjTBu0CbdyGLgYVgp6VVVAPQAVNMtE9MwjPAA5rgAtvKwIEIwUACeAA6mAOS9oYhBIf3EQ2BB9k4sMABkaXtHlzDQSmArvDAAL4jTApa7SE7VUjUWAkCCsFZgZB2fCmNAwQ7IeDITbSDA7D7HGAnADyYFK8USF26AG0ouIuFJ0Dofp4Vt1GZ0dMgwPsaQBdbqPZxQFwufkuE4AOnmVUWek+xPBiEhrGhIFhEHhiORqL2IEJp2VZks8hsMGFzwA-O8aQAFar0CiIfYE5X8q4Ne38gGAmCei7S2WZeWKk6WqCq9Wa7VIlFog0HIknY0WKzmiMwG2pGD2x0wZ2u3bugMmb2+-3BBrStwAJgAzAAWACsYWDMGmk2DSCguHg9D60hgAgmwMqYQElR7ffoeTK8AEgMEkxms1mMAAsjV1r4cCt4OYO2vO-xPHihINTPTwGkk19WX9eEv1M58FjTGfFBftMFPupr2A+gmumpAPisKRpmaTB3Gk3DqOA+D7IaVxPvwL7AG+SCGjAABiojRGAADq3gABZ2liOKIHiEAKscOgOpB1ikOQVC0GAArdCohQAG4gKw6gpNgbhSiJWIrBAQR2iCKQqAI6GYWiiqcmgCQMaaTHELyAqFDyfKCjAXGMRmjgioUEaCbh+HiMRUBkRRuKKDRnz0ZxLhya+77YQBynMnowFQd8UC-CshRgRy-kaT5GDYFFFkcK8v7HP+dz6G5aEeVhd5LHctGIDojAWYwEXmt5xTMp4QgFHo3QVQUHApDaai9v2uU6PVCXjFUd4ofwfpBAo3GKAIn7wN+phkhSugNByZXwKQRmkHBCFIaVTLwAKYzzOcgQwNNtwEZEOXOVFEA0ng6x2IoEoRLtFzFbYJnWmk7a5g6ngFi6BINB6t1lnaPrzH1v3SIu-BZQAopY2IsABuUQG1s3zep5pLWAiHZQRUUbYUnWZDSADSLr5oWBInT9J0Ey6-L3RjDKzTotUYHoDXBJWA1Db1w1gOel4GRo85wzoe0nTTqPo6tnTY7juT8-EQQTbLU3UjAJ1pRMd4STAkNBYMUCw588Oq6DI1jbTMSKwk1UwAAajTAGFABm0TNt0hXDAAA+ZDWIgQieBoAx3EE1s3XooPyZ5IhgDBHQlBbQvdEVC1m-Q2COxUmQ1D4fgXEEBjdCJUrZEEk3wILefJ1jEoCuOh0ESX8dLGl4dYZHMHgELysi0nYsrXclfuJUBdiZrNIFzH6Cayd3RznLMAK-kCTC4j4o13zC9l53y8CCux6LAAtAfh9HwfR5rl2QA)
