### ISSUE TITLE
Ngrx Effects How to get the payload of the previous action

### ISSUE THREAD

**Issue by noahsalvadordenjo** [ngrx/platform#2972]
If you've the following effect 
```
  testEffects$ = createEffect(() => this.actions$.pipe(
    ofType(RDX_TEST_INC_VALUE),
    switchMap(ac => instance.get('/api/test/kam').then(res => {
      return {
        type: RDX_TEST_INC_VALUE_SUCCESS,
      }
    }).catch((err: AxiosError) => {
      return {
        type: RDX_TEST_INC_VALUE_ERROR,
      }
    }))
  ))
 ```
How do we return the payload of ```RDX_TEST_INC_VALUE``` with ```RDX_TEXT_INC_VALUE_SUCCESS```?

**Comment by timdeschryver** [comment]
Hi, support questions should be asked on [stackoverflow (with a ngrx tag)](https://stackoverflow.com/questions/tagged/ngrx) or you can join our [discord server](https://discord.com/invite/ngrx) and ask your question there.
