### ISSUE TITLE
NgRx Store: Add `createChildSelectors` function

### ISSUE THREAD

**Issue by markostanimirovic** [ngrx/platform#2974]
## Description

`createChildSelectors` function creates memoized and strongly typed child selectors based on the parent selector. There are two signatures:

**First:**

```ts
export const selectUserState = createFeatureSelector<fromUsers.State>('users');

export const {
  selectUsers,
  selectLoading,
  selectPagination,
} = createChildSelectors(selectUserState, fromUsers.initialState);
```

**Second:**

```ts
export const {
  selectUsers,
  selectLoading,
  selectPagination,
} = createChildSelectors(selectUserState, ['users', 'loading', 'pagination']);
```

Full description is available here: https://github.com/markostanimirovic/ngrx-child-selectors

## Other information:

This feature can be implemented when we upgrade TypeScript version to 4.1 or higher.

## If accepted, I would be willing to submit a PR for this feature

[x] Yes ❤️
[ ] No

**Comment by timdeschryver** [comment]
Gets a 👍 from me.

**Comment by brandonroberts** [comment]
I think we should look at maybe unifying this into something similar to `createSlice` in Redux Toolkit where you get the reducer key, reducer, the feature selector, and those child selectors for a given slice of state.

**Comment by markostanimirovic** [comment]
Hey @brandonroberts,

Did you mean something like this?

```ts
const {
  selectMusiciansState // 👈 feature selector
  selectMusicians,
  selectLoading,
  selectPagination
} = createSliceSelectors('musicians', initialState);
```

**Comment by brandonroberts** [comment]
Something more like

```ts
export const {
  reducer(maybe),
  featureKey,<- musicians
  featureSelector, <- createFeatureSelector('musicians')
  selectLoading,
  selectCurrentMusicianId,
 ...
} = createFeature<State>({
  name: 'musicians'
})
```

**Comment by markostanimirovic** [comment]
Looks good 👍 

I will be happy to create a PR if you and the other team members agree :)

Btw, I would also add `createChildSelectors` function, because it can be used within `createFeature` function, but also independently, to create nested selectors for any selector.

**Comment by david-shortman** [comment]
![image](https://user-images.githubusercontent.com/25187726/118848939-3ac07600-b89d-11eb-9fd0-e038e6a1789b.jpeg)
