### ISSUE TITLE
entity/EntityAdapter.getSelectors() links to the wrong EntitySelector

### ISSUE THREAD

**Issue by bdirito** [ngrx/platform#2978]
https://ngrx.io/api/entity/EntityAdapter

 `EntityAdapter.getSelectors()` documents its return value (the actual hyperlink when clicking EntitySelectors) as `*data*/EntitySelectors<T>`. We would want `entity/EntitySelectors<T, V>`.  `entity/EntitySelectors<T, V>` is not documented on the website. From `@ngrx/entity/src/models.d.ts` `EntitySelectors<T, V>` is described as 

```
export interface EntitySelectors<T, V> {
    selectIds: (state: V) => string[] | number[];
    selectEntities: (state: V) => Dictionary<T>;
    selectAll: (state: V) => T[];
    selectTotal: (state: V) => number;
}
```

Note that *those* types are also wrong as via https://github.com/ngrx/platform/issues/2751.

**Comment by brandonroberts** [comment]
Closing as duplicate
