### ISSUE TITLE
Support generic state

### ISSUE THREAD

**Issue by parloti** [ngrx/platform#2982]
Since this change [pull/2967](https://github.com/ngrx/platform/pull/2967/files#diff-b5b61b5c88ce4368769a58df0918602484c6c507e6a6dfad51e4746e470caf26) Typescript can't compile my reducer based on generic state.

The following error is being generated:
_Argument of type '(state: TState, action: object & { type: string; }) => TState' is not assignable to parameter of type 'OnReducer<TState, [ActionCreator<string, Creator<any[], object>>]>'.
 Type 'TState' is not assignable to type 'TState extends object ? { [P in keyof TState]: TState[P]; } : TState'.
 Type 'object' is not assignable to type 'TState extends object ? { [P in keyof TState]: TState[P]; } : TState'.(2345)_
 
## Minimal reproduction of the bug/regression with instructions:
Reproduction in the [Typescript playground](https://www.typescriptlang.org/play?noUnusedLocals=true&noUnusedParameters=true&ts=4.2.3#code/JYWwDg9gTgLgBAbzgQQMY2BAdgYSgUwEMZoAaFdTLAJXwBMBXVfKc1A4-Wx51ubAL5wAZlAgg4AcgACWAOZQAHgHoAziQKSA3ACgdqbOrjsiGuAF44WBgBsbcQqrgMsAaywQA7lgdO0GbDxTaF0dfEVIWBEXSmxjDhh8AHF8LBZgVG4mFgAeABUAZRhOOHDErDonCAAjACt8dAA+AApgLGAMQhsizgAuOELixIBKfv8qLN58nsTGxB04Y0N4Ah4WC3jTLnpsqGaFxbg2juAumfxSA8XsZpNiMjhm9U5yQlisYYs5hCvD5QAqf6-Q7-FBQOQMECpeAQYRwGAATzA+CkTyG+H6gxeDne-Rq9XQcAAZIh4UiMXB1FA2nItHABJ9zHMsYlJEcnB54I5VMA5FhCNUbCiSHAwIQoIQoYkoPw4YjkVIAPI0HZTFkXOAAbXGgQS0ByVJp5CC9ygOUIWARmoAuuR8Q0YI1GtbGpIAHTAxagvLkqTqtnADkQLmqHl8gVC+EQMkKyTq0qKcqVfh1B1wAD8pM1AAUjj5XPgEbCBudrZjzjnrXShOX0e7PXBvb7JPb0AGgyGw-zBcLo-KUXHzgmk1VU4TM0gc3m4AWi3D1WWS+jK9W4LXOO7mgAmADMABYAKzDBv-ZSeggwBhQHzPRJwXSHenHxbDUKLC9XnyrXa6ARAA).

## Describe any alternatives/workarounds you're currently using
I am currently casting the state returned by the reducer to 'any'.

## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[X ] No

**Comment by HaanJeroen** [comment]
same here! would be nice to get a solution

**Comment by sommcz** [comment]
same here.. the way i only found is to cast reducer return type manually.
