### ISSUE TITLE
Multiple Stores with Webcomponents; Ngrx-Devtools not working as expected

### ISSUE THREAD

**Issue by TechnicalFreak** [ngrx/platform#2986]
My solution contains 2 Projects.
1. Angular Shell-Application
2. Angular Webcomponent, displayed in the Shell-Application

Both apps contain its own Ngrx-Store.

A clean separation of the 2 Stores in the Ngrx-Devtools is not possible for me.

For example, the Initial-State of the Shell-App is displayed in the Webcomponent store in Devtools.

I tried 2 ways, but both without success:
1. Both apps using their root-store.
2. Both apps using an empty root-store. The real state is in a feature-store. I wanted to avoid conflicts in multiple root-states.

**Comment by brandonroberts** [comment]
Support questions should be asked in the gitter channel or the Discord

**Comment by zizifn** [comment]
Not trying to be rude here, but why ngrx prefer gitter for questions, gitter and discord may blocked by the company proxy and maybe not be searchable.

**Comment by brandonroberts** [comment]
@zizifn no worries. That may be true, but issues are for bugs(reproducible) and feature requests. You'll get better support from people in those places.
