### ISSUE TITLE
my-counter.component.css is missing

### ISSUE THREAD

**Issue by ilyasOne** [ngrx/platform#2989]
In the documentation at **https://ngrx.io/guide/store** latest step in example walkthrough.

**my-counter.component.css** was not created before use, this should be created first.

**Comment by brandonroberts** [comment]
Thanks @ilyasOne. Would you like to put a PR in?

**Comment by EnricoVogt** [comment]
Is a dedicated file needed? For the example, i would suggest to use `styles` option instead of `styleUrls` or omitting this option completely

**Comment by AlmaniaM** [comment]
If no one is working on this I can submit a PR? Should the CSS file be removed entirely since it doesn't have any styles?

**Comment by brandonroberts** [comment]
@AlmaniaM sure, if no css is being used you can just remove that from the decorator metadata.
