### ISSUE TITLE
Clarify/improve existing behavior in component-store initState method

### ISSUE THREAD

**Issue by eLeontev** [ngrx/platform#2991]
## Description:
Displaying of `${this.constructor.name} has not been initialized yet. Please make sure it is initialized before updating/getting.` looks incorrect for multiple component-stores and possible for store + component-store integration in some cases.

Usually call of some store action in subscriber callback is bad practice, but in some cases it could be chain of calls where subscription from one store triggers initialization of another component-store.

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ * ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
Initialized component-store actions throw the same error: `${this.constructor.name} has not been initialized yet. Please make sure it is initialized before updating/getting.`

## Expected behavior:
Actions of initialized store should work as expected.
Error should not be displayed.

## Minimal reproduction of the problem with instructions:
native issue reproduction
```typescript
class Store extends ComponentStore<{ shouldInitDerivedStore: boolean }> {
    constructor() {
        super({ shouldInitDerivedStore: false });
    }

    initDerivedStore = this.updater((state) => ({
        shouldInitDerivedStore: !state.shouldInitDerivedStore,
    }));
}

class DerivedStore extends ComponentStore<{ anyField: boolean }> {
    constructor() {
        super({ anyField: false });
    }

    anyAction = this.updater(() => ({ anyField: true }));
}

const store = new Store();
const initDerivedStoreCallback = () => {
    const derivedStore = new DerivedStore();
    derivedStore.anyAction(); // `DerivedStore has not been initialized yet. Please make sure it is initialized before updating/getting.`
};

store.state$
    .pipe(filter(({ shouldInitDerivedStore }) => shouldInitDerivedStore))
    .subscribe(initDerivedStoreCallback);

store.initDerivedStore();
```

## Other information:
For practice usage in angular world:
Angular supports performance improvements like `changeDetectionStrategy: OnPush`. It means user need to handle view synchronisation manually in case if changes comes outside of angular word (any action which does not trigger change detection). 
For these cases angular provides two options to update view: 
- `marckForCheck` marks all components tree modified to the root entry to validate them on the next change detection call
- `detectChanges` runs change detection directly for the affected component. 
Usage of both methods depends on the used libraries and performance criteria.

If we have two components with different store instances we could not make them dependent if parent component trigger `detectChanges` inside the callback. In other words children component with its own store instance cannot be created from the subscription result of the parent component like next:
```typescript
// in parent component
store.select(shouldDisplayChildSelector).subscribe((shouldDisplayChild) => {
  this.shouldDisplayChild = shouldDisplayChild;
  this.ref.detectChanges(); // this call means initialisation of child component performs before `queueScheduler` of rxjs will call all its actions
})
```

```html
<!--parent component-->
<child-component-with-own-store *ngIf="shouldDisplayChild"><child-component-with-own-store />
```

## Reason:
Looks like it is regression after this PR https://github.com/ngrx/platform/pull/2606 

## Possible solutions if expected behaviour will be confirmed
1. Simple way: refactor this method: https://github.com/ngrx/platform/blob/master/modules/component-store/src/component-store.ts#L149
![image](https://user-images.githubusercontent.com/15786916/114058559-3ebfa800-989c-11eb-9e24-f600a3791ac2.png)

to this way
```typescript
   /**
     * Reason: staying isInitialized flag inside callback looks like code issue
     *
     * Description: staying the flag in the callback means we need to perform side effects (actions queue) before to init the store
     * even if user has already initialized it
     *
     * Fix details: once user init state in constructor or #setState the store will be initialized
     */
    private initState(state: T): void {
        this.isInitialized = true; // the fix

        scheduled([state], queueScheduler).subscribe((s) => {
            this.stateSubject$.next(s);
        });
    }
```

2. Complex way: stop use **singleton** queueScheduler in each component-stores instance  and replace to multiple instances:
```typescript
class ComponentStore {
  constructor() {
    this.queueScheduler = new queueScheduler()
  }
}
```

## workarounds for angular:
1. if the reason is `detectChanges` call and it's correct for the application to postpone to call changeDetection. Simple replace its call to `markForCheck`
2. if the reason in subscriber. You can try to use https://rxjs.dev/api/operators/observeOn (looks like a hack)
```
this.observable$
  .pipe(observeOn(queueScheduler)) // this postpone to call subscribe till all actions in queue will be called (#initState/#setState are placed in this scheduler)
  .subscriber(callback)
```
3. as a hack solution - add any delay

**Comment by eLeontev** [comment]
I could prepare the fix PR if the expected behavior will be confirmed.

**Comment by ghostlytalamaur** [comment]
It would be great to use new instance of queueScheduler per component store. It will solve problem with recursive updates. Also it solves problem when store is created inside queueScheduler executing task and store might be uninitialized after instantiating altough initialState is passed through constructor.

**Comment by evantrimboli** [comment]
I'm facing a similar issue, during component initialization I conditionally load some data based on whether there's a parameter in the route. I want to set the loading state in my store, however by the time I make that call, the store is yet to be initialized. The code looks something like this:

```typescript
interface Data {
    readonly loading: boolean
}

class MyStore extends ComponentStore<Data> {
    constructor() {
        super({
            loading: false
        })
    }

    loadId(id) {
       // Can't set state here, not initialized.
        this.setState({
            loading: true
        })
        // Remote call here
        return of({})
    }
}

@Component({
  selector: 'app-my-component',
  providers: [MyStore],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class MyComponent {
  constructor(
    route: ActivatedRoute,
    private readonly store: GatewayFormStore
  ) {
    const loader$ = route.params.pipe(
      map((p) => ({
        routeId: getRouteId('foo', p)
      })),
      switchMap(({ routeId }) => {
        if (route !== null) {
          return this.store.loadId(routeId);
        } else {
          return of(false);
        }
      }),
      shareReplay(1)
    );
  // Other stuff
  }
}
```

Would appreciate any advice.

**Comment by NachmanBerkowitz** [comment]
I am having a similar issue. My component store is initialized in the constructor, yet I get a not-initialized error. I only get this error if I start the app on the view that has the component store (i.e. refresh the browser on that view), not if I navigate there from within the app. Most probably because there is a lot qued on app initialization.

**Comment by Klapik** [comment]
Any news?

**Comment by monkeycatdog** [comment]
I have the same issue
Seems like the initialisations is async. weird.

**Comment by rovshenn** [comment]
Same issue here, using component store in a modal, requires us to provide the store in root, which raises above error.

**Comment by yurakhomitsky** [comment]
> I'm facing a similar issue, during component initialization I conditionally load some data based on whether there's a parameter in the route. I want to set the loading state in my store, however by the time I make that call, the store is yet to be initialized. The code looks something like this:
> 
> ```ts
> interface Data {
>     readonly loading: boolean
> }
> 
> class MyStore extends ComponentStore<Data> {
>     constructor() {
>         super({
>             loading: false
>         })
>     }
> 
>     loadId(id) {
>        // Can't set state here, not initialized.
>         this.setState({
>             loading: true
>         })
>         // Remote call here
>         return of({})
>     }
> }
> 
> @Component({
>   selector: 'app-my-component',
>   providers: [MyStore],
>   changeDetection: ChangeDetectionStrategy.OnPush
> })
> export class MyComponent {
>   constructor(
>     route: ActivatedRoute,
>     private readonly store: MyStore
>   ) {
>     const loader$ = route.params.pipe(
>       map((p) => ({
>         routeId: getRouteId('foo', p)
>       })),
>       switchMap(({ routeId }) => {
>         if (route !== null) {
>           return this.store.loadById(routeId);
>         } else {
>           return of(false);
>         }
>       }),
>       shareReplay(1)
>     );
>   // Other stuff
>   }
> }
> ```
> 
> Would appreciate any advice.

Having the same issue in the `tap` setLoadingStatus

```
	private getEquipment$ = this.effect((wellId$: Observable<number>) => {
		return wellId$.pipe(
			tap(() => this.setLoadingStatus()),
			switchMap((wellId: number) =>
				this.dataService.getWellEquipment(wellId).pipe(
					tapResponse(
						(equipment: WellEquipment[]) => {
							this.setStatusByResponse(equipment);
							this.setEquipment(equipment);
						},
						() => {
							this.setErrorStatus();
						}
					)
				)
			)
		);
	});
```


```
	private setLoadingStatus(): void {
		this.patchState({ status: ActionStatusEnum.LOADING });
	}
```

**Comment by yurakhomitsky** [comment]
> I am having a similar issue. My component store is initialized in the constructor, yet I get a not-initialized error. I only get this error if I start the app on the view that has the component store (i.e. refresh the browser on that view), not if I navigate there from within the app. Most probably because there is a lot qued on app initialization.

I was getting the same issue

I fixed it like this
![image](https://user-images.githubusercontent.com/54478076/177549530-f9bd0851-9c84-4021-8891-eb3c724d5bba.png)
