### ISSUE TITLE
How to mock Store in v4?

### ISSUE THREAD

**Issue by ShadowManu** [ngrx/platform#300]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
</code></pre>

## What is the current behavior?
There are testing instructions regarding the Store Service in tests.

## Expected behavior:

How do you tests components/service that use the `Store<State>` service? Do you mock it? Use the real one? I would like to have some guidance on best practices here.

## Minimal reproduction of the problem with instructions:
Couldn't find related tests in the example app

## Version of affected browser(s),operating system(s), npm, node and ngrx:
ngrx v4+

**Comment by brandonroberts** [comment]
There is an example of testing components that use the Store in the docs. Tests in the example app will be added, but the pattern is the same.

https://github.com/ngrx/platform/blob/master/docs/store/testing.md

**Comment by richflee** [comment]
@brandonroberts this didn't work for me. 

`Error: <spyOn> : dispatch() method does not exist` when I attempt to run the tests.
