### ISSUE TITLE
component store - error in tapResponse success handler gotcha

### ISSUE THREAD

**Issue by piotrpalek** [ngrx/platform#3006]
Hey, I've recently started using component-store, and I'm wondering if it's just me not getting rxjs right, but I think it would be good to document this, or maybe change the implementation a little bit?

So the issue is that when you throw an error form inside the success handler of `tapResponse`, that error gets swallowed due to `catchError` that's used inside of `tapResponse`, which caused a little bit of head scratching for myself.

You can see it in action here: https://stackblitz.com/edit/tap-vs-tapresponse-error

Maybe it's just me, but this can cause some stupid bugs to be harder to debug then necessary.

## I would be willing to submit a PR for the docs :heart:

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

**Comment by timdeschryver** [comment]
Could you elaborate a bit more on your use case?
Because this is why `tapResponse` was added, to catch and react to errors.

> Handles the response in ComponentStore effects in a safe way, without additional boilerplate. It enforces that the error case is handled and that the effect would still be running should an error occur.

**Comment by piotrpalek** [comment]
Yes, the issue is though that you can't react to errors, because they are catched by `catchError` and not re-thrown / logged anywhere, they just dissapear. So when I make any error inside of the success handler of `tapResponse`, I don't even know I've made an error, because it's silenced.

**Comment by alex-okrushko** [comment]
`as any` is silencing the compile-time error, as you know.

`tapResponse` shouldn't be producing errors - it's mean to call some side-effects that shouldn't produce runtime errors, like calling `updaters`.

**Comment by piotrpalek** [comment]
gotcha, well I sometimes find errors in there, since `tapResponse` can invoke any side-effects they sometimes do error, for me at least :) But since it's something expected I'm fine with that, I was just wondering if I'm using it wrong. I can always do a "custom" tapResponse which has a `console.error` in the `catchError` or something like that, thanks for the info!
