### ISSUE TITLE
StoreModule.forRoot and forFeature initialState typing not OK when providing metaReducers

### ISSUE THREAD

**Issue by spierala** [ngrx/platform#3007]
## Minimal reproduction of the bug/regression with instructions:

Use the following StackBlitz example to create a reproduction: https://stackblitz.com/edit/angular-ngrx-store-module-for-root?file=src/app/app.module.ts

The example code does not show (the expected) type errors when meta reducers are provided.
When the metaReducers are removed, then the type errors become visible.

## Expected behavior:
ForRoot initialState type should match the provided reducers map keys.
ForFeature initial state type  should match the provided reducers state type.
Type errors should show up accordingly, also if metaReducers are provided. 

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
NgRx 11.1.1, Ng11

**Comment by timdeschryver** [comment]
@spierala have you tried to add the State type to the metareducer?


```ts
interface State {
  counter1: CounterState;
  counter2: CounterState;
}

function someMetaReducer(reducer): ActionReducer<State>  {
  return (state, action) => {
    return reducer(state, action);
  };
}
```

In order to infer the types correctly, we have to add a type to something.
Because the same generic is used for the root state, initial state, and metareducers we need to define a "truth" otherwise TypeScript won't know which type to use.

We could also remove the state generic from the metareducers, as the metareducer receives the global state... 🤔

**Comment by spierala** [comment]
@timdeschryver Adding a return type to the metaReducers helps indeed.
See updated example here: https://stackblitz.com/edit/angular-ngrx-store-module-for-root-typed-meta?file=src%2Fapp%2Fapp.module.ts

Also `StoreModule.forRoot<State>` would help.

Personally I think that the matching between initialState and the reducer structure is more important than the metaReducer type. On the other hand I think that the root reducer will drop "wrong" initialState properties anyway when it processes an action.

**Comment by timdeschryver** [comment]
> Personally I think that the matching between initialState and the reducer structure is more important than the metaReducer type

Yea, I feel the same way - that's why I was thinking not to use the State interface here.

> On the other hand I think that the root reducer will drop "wrong" initialState properties anyway when it processes an action.

This isn't true, TypeScript doesn't drop properties (or doesn't throw like in some other languages), the "wrong" properties will still be there in the state.

**Comment by spierala** [comment]
> This isn't true, TypeScript doesn't drop properties (or doesn't throw like in some other languages), the "wrong" properties will still be there in the state.
I mean the combined root reducer creates a new state object based on the reducer keys and therefore would drop inititalState props which do not have a corresponding reducer key. See `combineReducers`:
https://github.com/ngrx/platform/blob/master/modules/store/src/utils.ts#L63-L77

But "wrong" initialState props will remain when provided with StoreModule.forFeature
