### ISSUE TITLE
`@ngrx/component-store`: Add `select` signature that accepts the state key

### ISSUE THREAD

**Issue by markostanimirovic** [ngrx/platform#3008]
## Description

We could add another `select` signature that accepts the state key, similar to the `select` method of the global NgRx store :)

Before:

```ts
books$ = this.select(state => state.books);
loading$ = this.select(state => state.loading);
```

After:

```ts
books$ = this.select('books');
loading$ = this.select('loading');
```

## If accepted, I would be willing to submit a PR for this feature

[x] Yes
[ ] No

**Comment by brandonroberts** [comment]
Something something type safety, but pretty sure @alex-okrushko is gonna veto this :-)

**Comment by alex-okrushko** [comment]
Yes, really not a fan of selecting by property key names. 🙃
