### ISSUE TITLE
Make the array of strings an optional parameter when using the typed version of ofType in effects.

### ISSUE THREAD

**Issue by ncrawlins** [ngrx/platform#301]
## I'm submitting a...

<pre><code>
[X ] Feature request
</code></pre>

## What is the current behavior?

you have to explicitly put in type identifier strings in the typed ofType utility function.
`actions$.ofType<MyActionClass>()` does not let any actions through.

## Expected behavior:
This is a small quibble and I don't know enough about generics and how much the are just there for IDE type checking and how much they actually affect compilation and runtime to know if it's possible, but if I specify this
`actions$.ofType<MyActionClass>()`
I feel like it should filter that to all actions that are of the type MyActionClass regardless of what their type field is set to.  You should only have to pass an array of strings in if you want to restrict to a subset of MyActionClass objects.

I follow the basic structure of your example app and this becomes useful in cases where I have an feature action file that has
`export const Actions = ActionClass1 | ActionClass2 | ... | ActionClassN`

then in the effects, if I wanted to do something for every action from that feature, i can just use
`actions$.ofType<fromFeature.Actions>()`
and I don't have to spell out the type strings of every one of those actions. And if I add a new action to that feature and that exported Action Union, I don't have to remember to go to the effect and add in the new constant string type, it just works.

Maybe this sort of conflicts with the original name of the function, but whatever you want to call it, it feels like `ofType<MyAction>('MY_ACTION')` is redundant and just makes it harder to maintain.

**Comment by yngvebn** [comment]
I would suspect that the Generic argument is only there for typecasting convenience. Afaik there are no way of doing typechecking in Javascript, and this is also the reason for the required `type: string` property on the action-classes. If what you suggest was possible, there would be no use for the type-constant on the Action interface.

**Comment by brandonroberts** [comment]
Since types aren't present at compile time, you still need to provide a type to filter on. Closing as non-actionable. Another option would be to create an array of your Action types and use the spread syntax in the `ofType` function.

```ts
export const ACTION_1 = 'Some Action';
export const ACTION_2 = 'Another Action';

export const ActionTypes = [ACTION_1, ACTION_2];
```

and 

```ts
actions$.ofType(...fromFeature.ActionTypes)
```
