### ISSUE TITLE
ngrx.io prevent all search engine to index it

### ISSUE THREAD

**Issue by mix5003** [ngrx/platform#3010]
i not sure why current [robots.txt](https://ngrx.io/robots.txt) dose use from [stable](https://github.com/ngrx/platform/blob/master/projects/ngrx.io/src/extra-files/stable/robots.txt) folder.

and it prevent all search engine from index it.

**Comment by mix5003** [comment]
today i found that robots.txt now use from stable. but i can not see any commit relate to this.
i not sure but i think it relate to circle ci.
if you use [deploy-docs-stable](https://github.com/ngrx/platform/blob/045c4c3dc940c93f8fced1def1b11a046c55687c/.circleci/config.yml#L278) it will copy robots.txt from stable to replace it.
but if use [deploy](https://github.com/ngrx/platform/blob/045c4c3dc940c93f8fced1def1b11a046c55687c/.circleci/config.yml#L295) it will not

**Comment by timdeschryver** [comment]
Hi, thanks for reporting this!

I suppose the difference is that we manually deploy the docs from time to time.
While deploy-docs-stable does it correctly (and was triggered with the v12 release).
(deploy is to publish our packages to npm, not the docs).

cc @brandonroberts

**Comment by mix5003** [comment]
@timdeschryver but in deploy:builds it has a task that name `Deploy docs` too. i am nut sure is it relate or not.
because it just update another git repo. can you take a look with it?

https://github.com/ngrx/platform/blob/3b565b47493a3a86681690893d89d28b25b949ac/build/deploy-build.ts#L7
https://github.com/ngrx/platform/blob/3b565b47493a3a86681690893d89d28b25b949ac/build/tasks.ts#L57-L64

**Comment by gethari** [comment]
why are we preventing the search engine from indexing the site ? How do we get proper SEO then ? I'm just wondering how is the SEO performance here as the site is built on `Angular` ?  Asking because I want to have a similar docs site but worried about the SEO & performance

**Comment by prewk** [comment]
Yeah, every time I search for ngrx docs I end up on v9.ngrx.io.

**Comment by brandonroberts** [comment]
The `https://v9.ngrx.io/robots.txt` file should prevent that version from being indexed

**Comment by prewk** [comment]
I guess Google just doesn't care 🤷

**Comment by mix5003** [comment]
i think v9 is not on google index anymore (i try to search "site:v9.ngrx.io" in google but it only found few url)

but [v7](https://v7.ngrx.io/) and [v8](https://v7.ngrx.io/) still live in google (because these 2 site no robots.txt)

and main domain docs still bad in SEO term. 
for example when you goto this page directly https://ngrx.io/guide/store
(or you can try by `curl -I 'https://ngrx.io/guide/store'` or use this [link](https://search.google.com/test/rich-results?url=https%3A%2F%2Fngrx.io%2Fguide%2Fstore) )
this page return 404 http response but render correctly. 
for user it can use normally
but for search engine it mean noindex
so that page can not be index in google 

that why when i search for docs it will show only v7 and v8 domain 

from http response i found that you it serve by Netlify.
i think you should config this to make that page serve by http status 200
https://docs.netlify.com/integrations/frameworks/angular/#redirects

**Comment by mix5003** [comment]
@timdeschryver  @brandonroberts base on comment above should i open new issue? if docs in main domain serve 404 http response and make google not index it. i think it pain to search current document
