### ISSUE TITLE
Type StoreRootModule does not have 'ɵmod' property.

### ISSUE THREAD

**Issue by Ruslancic** [ngrx/platform#3019]
## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

```
Angular CLI: 12.0.0
Node: 14.16.1
Package Manager: npm 6.14.12
OS: win32 x64

Angular: 12.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0
@angular-devkit/build-angular   12.0.0
@angular-devkit/core            12.0.0
@angular-devkit/schematics      12.0.0
@angular/flex-layout            11.0.0-beta.33
@schematics/angular             12.0.0
rxjs                            6.6.7
typescript                      4.2.4
```

## Other information:

After Upgrading NGRX-STORE with ng update i have recieving this error, and white page!
This is a screenshot: https://i.postimg.cc/v8CDLJTX/screenshot-93.png

**Comment by timdeschryver** [comment]
Have you tried removing the `node_modules` and installing the dependencies again?
If that doesn't fix it, could you create a reproduction please.

**Comment by Ruslancic** [comment]
> Have you tried removing the `node_modules` and installing the dependencies again?
> If that doesn't fix it, could you create a reproduction please.

I followed your advice, removed node_modules, and now i have no errors.

**Comment by timdeschryver** [comment]
Great, thanks for getting back to us @Ruslancic !
