### ISSUE TITLE
Inconsistent formatting of action class names in the example-app

### ISSUE THREAD

**Issue by bradyshutt** [ngrx/platform#302]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
</code></pre>

## What is the current behavior?

In [/example-app/app/books/actions/book.ts](https://github.com/ngrx/platform/blob/master/example-app/app/books/actions/book.ts) action class names are formatted like "_\<ActionName\>_**Action**". ie:

> `SearchAction`
> `SearchCompleteAction`
> `this.store.dispatch(new book.SearchAction(query));`

etc. 

In [platform/example-app/app/auth/actions/auth.ts](https://github.com/ngrx/platform/blob/master/example-app/app/auth/actions/auth.ts), action class names are formatted like "_\<ActionName\>_". ie:

> `Login`
> `LoginSuccess`
> `this.store.dispatch(new Auth.Login($event));`

etc.

## Expected behavior:

Action class names should have a consistent format (either always having Action appended to the end, or never). Especially as it's an example app, which I am (and I'm sure many others are) using as a model of sorts.

## Minimal reproduction of the problem with instructions:

n/a
## Version of affected browser(s),operating system(s), npm, node and ngrx:
n/a

**Comment by brandonroberts** [comment]
Agreed. The example app has evolved over time and not all changes have been consistent across the app.

**Comment by karptonite** [comment]
If we look to standardize this, I suggest with consider using something like `toAuth` as the convention for importing actions. It works nicely with `fromAuth` for the selectors, and it leaves the `auth` namespace open for the model of Auth itself, a conflict I had run into as an issue before I started using the `to` convention in my own code.

**Comment by brandonroberts** [comment]
We're not trying to standardize on naming conventions, because they are subjective. I don't feel strongly about wildcard imports versus direct imports. I don't feel it's something to get hung up on.

**Comment by bradyshutt** [comment]
Regarding the action class names in the example app (and in general), is `LoginSuccess` or `LoginSuccessAction` to be preferred?

**Comment by brandonroberts** [comment]
`LoginSuccess`
