### ISSUE TITLE
Angular Universal store completion guidance

### ISSUE THREAD

**Issue by callumelgrant** [ngrx/platform#3021]
Hi there, I have been trying find guidance on how to destroy the NGRX store state in Angular Universal, at the moment in an app I'm working on we call the store complete method https://ngrx.io/api/store/Store#complete but this is undocumented and I'm not sure if it's even doing what we think it does (clear out the store). In Universal should we be doing anything when a render is complete or is everything using ngOnDestroy hooks?

Thanks in advance.

## I would be willing to submit a PR for the docs :heart:

[x] Yes (Assistance is provided if you need help submitting a pull request)
[] No

**Comment by timdeschryver** [comment]
AFAIK, we don't have a built-in way to "destroy/clear" the store.
Why do you want to clear the store?

**Comment by callumelgrant** [comment]
Hi @timdeschryver I think it was added in when trying to track down memory leaks in Angular Universal - from looking at the source code it seems like NGRX uses the ngOnDestroy hooks so we don't need to intervene to make sure the store doesn't leak memory in node.js.

**Comment by brandonroberts** [comment]
If the app is torn down, the store should be torn down with it using the destroy hooks.
