### ISSUE TITLE
Provide `setMany` adapter for `@ngrx/entity`

### ISSUE THREAD

**Issue by samuelfernandez** [ngrx/platform#3026]
`setAll` replaces the whole collection. If an entity is not provided there, it will be removed. However, the feature request for a new `setMany` would act like:

* Replacing (not updating) the elements being provided, like setOne
* Keep other entities that are not updated

Copying from the docs:

> To prevent partial updates either explicitly set all the fields, setting non-used fields with value undefined, or use the setOne or setAll adapter methods.

Even though there is `updateMany`/`upsertMany`, those do a partial update. The requested `setMany` would do a replacement.

## Describe any alternatives/workarounds you're currently using

Custom entity adapter extension or a loop on `setOne`.

## Other information:

We have a scenario where we want to set only a subset of entities, so `setAll` wouldn't work. This would align with `remove`, `update` and `upsert`.

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Hey, we already have a `setAll` method (https://ngrx.io/guide/entity/adapter#adapter-collection-methods).
In earlier versions of NgRx, this method was be named `addAll`.

**Comment by timdeschryver** [comment]
Now, that's a whole other story 😅
I think that would complete the entity api, as we have a `xxOne` and `xxMany` for the other methods.
Feel free to create Pull Request if you'd want to.

**Comment by samuelfernandez** [comment]
@timdeschryver thanks for allowing this move forward! 😄 I've submitted a PR, please let me know if there is anything left
