### ISSUE TITLE
NgRx Effects making a second network call on state change.

### ISSUE THREAD

**Issue by then3rdman** [ngrx/platform#3028]
Facing a strange behaviour i have not ever run into before. I am not asking for the solution to the problem as i understand that I would need to provide a reproduction. Just want some direction as to what could cause this.

For all api calls I am following the standard action -> action-success / action-fail as below
```ts
  invite$ = createEffect(() =>
    this.actions$.pipe(
      ofType(WorkforceActions.invite),
      switchMap((action) => {
        return this.employeeService.registerNewEmployee(action.invite).pipe(
          map(() => WorkforceActions.inviteSuccess()),
          catchError((error) => of(WorkforceActions.inviteFailure({ error })))
        );
      })
    )
  );
```
This work perfectly fine as expected. However if i log out of the application and log back in, the log in process triggers a heap of parallel requests as designed, but it also repeats what ever the previous api request was with the exact same data. 

No action is dispatched to trigger the effect, only the resulting action. Above i see the invite failure action. I have even debugged and broke on the function that makes the api call and it is skipped. 

Obviously this can be explained but I can't work out what is going on. Any help or direction would be greatly appreciated!

**Comment by timdeschryver** [comment]
Hi, support questions should be asked on [stackoverflow (with a ngrx tag)](https://stackoverflow.com/questions/tagged/ngrx) or you can join our [discord server](https://discord.com/invite/ngrx).
