### ISSUE TITLE
The payload property has been removed from the Action interface?

### ISSUE THREAD

**Issue by TheBolmanator** [ngrx/platform#303]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request
</code></pre>

## What is the current behavior?
Current "BEFORE"
  @Effect() someEffect$: Observable<Action> = this.actions$.ofType(UserActions.LOGIN)
    .map(action => action.payload)
    .map(() => new AnotherAction())
Current "AFTER"
  @Effect() someEffect$: Observable<Action> = this.actions$.ofType(UserActions.LOGIN)
    .map((action: UserActions.Login) => action.payload)
    .map(() => new AnotherAction())
## Expected behavior:

I am sorry this may be more of a question in the end, but it is unclear to me how the 'payload' property has been impacted from the example provided. 

Many thanks for the great work, I am putting together a slide pack to share with my Meetup group and would like to fully understand this change for the slides.

**Comment by brandonroberts** [comment]
The explanation is included here https://github.com/ngrx/platform/issues/128#issuecomment-316680916 which we could include in the migration guide as the reason for the change.
