### ISSUE TITLE
ng add @ngrx/store@latest fails with "Specified module path /src/app/app does not exist" error

### ISSUE THREAD

**Issue by sanket-bhalerao** [ngrx/platform#3037]
## Minimal reproduction of the bug/regression with instructions:
1. create an angular project using "ng new demo"
2. rename the "src" directory to "ui" or any other name 
3. change the config to accommodate these changes.
4. try to execute "ng add @ngrx/store@latest" 

## Expected behavior:
the package should get added and ngrx store config should get added.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
angular version : 12
ngrx: 12

## Other information:
![image](https://user-images.githubusercontent.com/9264813/120984475-4f0adb00-c798-11eb-92a3-b2cb8d5d6b9e.png)
## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ x] No

**Comment by timdeschryver** [comment]
You can specify the path to the module while using the ng add command.
See the [docs](https://ngrx.io/guide/store/install#optional-ng-add-flags) for more info.
