### ISSUE TITLE
Getting linting warning for unused import

### ISSUE THREAD

**Issue by MurhafSousli** [ngrx/platform#304]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[X] Support request
</code></pre>

## What is the current behavior?
Linting warning
![tslint](https://user-images.githubusercontent.com/6850223/29494116-4c85da9e-859b-11e7-8a18-fc2aae32ec1d.png)

## Expected behavior:

Should not give the linting warning

## Minimal reproduction:
```ts
import { IonicPage } from 'ionic-angular';
import { Component } from '@angular/core';
import { Store } from '@ngrx/store';
import { Authenticate, RegisterForm } from '../models/user';

import * as Auth from '../actions/auth';
import * as fromAuth from '../reducers';

@IonicPage()
@Component({
  selector: 'page-auth',
  templateUrl: 'auth.html',
})

export class AuthPage {

  /** default active tab */
  selectedTab = 'Login';

  constructor(private store: Store<fromAuth.AuthState>) {
  }

  onLogin(e: Authenticate) {
    this.store.dispatch(new Auth.Login(e));
  }

  onRegister(e: RegisterForm) {
    this.store.dispatch(new Auth.Register(e));
  }

}
```

## Version of affected browser(s),operating system(s), npm, node and ngrx:
Ubuntu 17.04, Node v8.4.0, npm 5.3.0, ngrx v4.0.2
## Other information:

Is there a way to fix this without disabling the `no-unused-variable` rule? 

Thanks.

**Comment by brandonroberts** [comment]
Sure, you can import the actions individually instead of using the wildcard import.
