### ISSUE TITLE
12.1.0 has a breaking change

### ISSUE THREAD

**Issue by e-oz** [ngrx/platform#3041]
https://github.com/ngrx/platform/compare/12.0.0...12.1.0#diff-c1a8d221f6e4e46115140017a7c4c52d888ee837a50f065738bfcdfdf774e973L150

`options` are not more optional, it's a breaking change 😢
Please mention it in the release notes.
And, maybe, it should bump the major version number.

**Comment by timdeschryver** [comment]
This wasn't intended, do you want to create a Pull Request with a fix?
