### ISSUE TITLE
warning "SchematicsNgRxCreateEffectMigration" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.

### ISSUE THREAD

**Issue by ofirrifo** [ngrx/platform#3048]
## Minimal reproduction of the bug/regression with instructions:
after I'm execute this command ` ng generate @ngrx/schematics:create-effect-migration`
Im getting this warning:
```
"SchematicsNgRxCreateEffectMigration" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
```

I'm not sure what I need to do.

## Expected behavior:
- not to see this warning and if I need to change something please give more details such where to change.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
angular 12
NGRX 12 
NODE 14

**Comment by timdeschryver** [comment]
Hi, this is just a warning and doesn't affect the schematic or the created files.
We already fixed this in #3034, which will be included in our next release.
