### ISSUE TITLE
Make ReducerManager more extensible

### ISSUE THREAD

**Issue by GregOnNet** [ngrx/platform#3049]
## Describe any alternatives/workarounds you're currently using

In order to register reducers dynamically, I extend `ReducerManager` to enhance reducers being already registered.
(see [Example](https://github.com/co-IT/ngrx-ducks/blob/main/packages/core/src/store-facade/reducer-manager-opened.ts#L14))

## Problem

The current solution is hacky because INITIAL_REDUCERS is a private member. (see [Source](https://github.com/ngrx/platform/blob/master/modules/store/src/reducer_manager.ts#L32))
Making INITIAL_REDUCERS **protected** would allow inheriting classes to work with INITIAL_REDUCERS.

```diff
@Injectable()
export class ReducerManager
  extends BehaviorSubject<ActionReducer<any, any>>
  implements OnDestroy {
  constructor(
    private dispatcher: ReducerManagerDispatcher,
    @Inject(INITIAL_STATE) private initialState: any,
-    @Inject(INITIAL_REDUCERS) private reducers: ActionReducerMap<any, any>,
+    @Inject(INITIAL_REDUCERS) protected reducers: ActionReducerMap<any, any>,
    @Inject(REDUCER_FACTORY)
    private reducerFactory: ActionReducerFactory<any, any>
  ) {
    super(reducerFactory(reducers, initialState));
  }

```
 

## Other information:

[NgRx Ducks](https://co-it-eu-open-source.gitbook.io/ngrx-ducks/) will be able to register reducer-Functions automatically in the Store. This reduces the amount of infrastructural code that is needed to set up reducers.
Therefore, NgRx Ducks needs to access INITIAL_REDUCERS.

```ts
// Example

 @StoreFacade({ registerInStore: ['counterSlice', 'counter', initialState] })
export class CounterFacade {}
```
## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Why do you need access to the reducers, to read them?
Because we currently had the add and remove methods.

I'm not a big fan of making the property protected, maybe a getter would be better here if we want to expose it.

**Comment by GregOnNet** [comment]
> Why do you need access to the reducers, to read them?

Hi, NgRx Ducks reads the existing features of the store.

```ts
// store
{
  featureA: reducerFn,
  featureB: reducerFn
}
```

The @StoreFacade-Decorator is capable of merging the generated reducer into an existing feature (instrumenting combineReducers).
This is the reason why I need to know about the most recent state of INITIAL_REDUCERS.

Please let me know if there is a cleaner way to access them.

> I'm not a big fan of making the property protected, maybe a getter would be better here if we want to expose it.

A getter would also do. 👍

**Comment by timdeschryver** [comment]
@GregOnNet feel free to create a PR to expose the reducers with a getter.
