### ISSUE TITLE
Inconsistent readonly usage

### ISSUE THREAD

**Issue by peterreisz** [ngrx/platform#3050]
## Minimal reproduction of the bug/regression with instructions:

Here we have readonly modifier before the `ActionCreator[]`:

https://github.com/ngrx/platform/blob/7515e366e68b808c7e51a45404f3974da0731100/modules/store/src/reducer_creator.ts#L24-L26

But here we don't:

https://github.com/ngrx/platform/blob/7515e366e68b808c7e51a45404f3974da0731100/modules/store/src/reducer_creator.ts#L105-L108

## Expected behavior:

Be consistent, use readonly in both places.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

ngrx store version: 12.1.0

## Other information:

In my project I have several reducer function extracted to a variable and a linter rule demands that I specify the type for them.
If I want to satisfy the linter, the inconsistent readonly usage results non compiling code.

## I would be willing to submit a PR to fix this issue

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
This seems like a reasonable change, feel free to create a Pull Request.
