### ISSUE TITLE
SaveEntitiesCanceled action has the wrong type

### ISSUE THREAD

**Issue by preda7or** [ngrx/platform#3065]
https://github.com/ngrx/platform/blob/bf2bd1a626b5c98d3eb78c8ab672ba57c6db6ab9/modules/data/src/actions/entity-cache-action.ts#L169

Two actions should not have the same type, but SaveEntitiesCancel and SaveEntitiesCancel do.

**Comment by timdeschryver** [comment]
Oh, great catch!
Feel free to open a Pull Request to modify the type to `SAVE_ENTITIES_CANCELED`.
