### ISSUE TITLE
Update all examples of selectors to appear in .selectors.ts files instead of index.ts

### ISSUE THREAD

**Issue by david-shortman** [ngrx/platform#3067]
## Other information:

Placing selectors in `index.ts`:

- discourages the creation of tests
- makes it harder to search for the filename containing selectors

It is a better practice to place selectors in their own file and to encourage them to be paired with a .selectors.spec.ts file.

## I would be willing to submit a PR for the docs :heart:

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
This is a preference, and putting selectors in the `index.ts` is fine also.
