### ISSUE TITLE
Expand the Example-App or Examples to show more use cases - REST API or Similar

### ISSUE THREAD

**Issue by michaeljohnbennett** [ngrx/platform#307]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[X] Documentation issue or request
[ ] Support request
</code></pre>

## What is the current behavior?
Their is a good example-app that models a server query then store locally. But not all use cases are like this, sometimes a more REST API based CRUD model would be a good fit for many people using or trying to use this package.

## Expected behavior:
Would it be possible to give a more comprehensive example that might use a more CRUD based API for books? 

Even some best practices or patterns to achieve: 

- how to load or clear down stores based on user authentication (e.g. `As a USER I want to see only my selected books from API`) and refresh from the API
- how to sync from an API
- how best to write back to the API based on SaveActions for example.
- how and when to sync state back, per Action or manually?

It took me a while to kind of map these features but I'm not sure it's the best way to do things. It would be good to get some advice from the Dev's on how they use this package in the real world.

I'm sorry if this isn't really relevant to the development process but it took me a few weeks to really understand and get things working properly through the learning curve, package issues and dependencies and working with REST API I had initially.

## Other information:
Keep up the great work and looking forward to seeing further features/developments in the future.

**Comment by brandonroberts** [comment]
This issue has been discussed at length before here https://github.com/ngrx/example-app/issues/94. The example app isn't meant to be a comprehensive example of complex scenarios.
