### ISSUE TITLE
return `null` from partial updater for `ComponentStore`

### ISSUE THREAD

**Issue by owl-from-hogvarts** [ngrx/platform#3073]
There is no statment about returning `null` or `undefined` from partial updater in `ComponentStore` documentation.

## Other information:
with `@ts-ignore` i can return `null` or `undefined` value from updater and as expected update of state is aborted i.e. state doesn't update, store and selectors does not emit new value.

But i don't know is it safe to do such thing as that is undocumented?

## I would be willing to submit a PR for the docs :heart:

[x] Yes (Assistance is provided if you need help submitting a pull request)
[  ] No

**Comment by timdeschryver** [comment]
The types of the `updater` methods require that the returned value need to be the shape of the component store's interface.

If a `null` or `undefined` value is returned, then you should see the following error message (if that's not the case feel free to re-open this issue).

```
Argument of type '() => null' is not assignable to parameter of type 'Partial<State> | Observable<Partial<State>> | ((state: State) => Partial<State>)'.
  Type '() => null' is not assignable to type '(state: State) => Partial<State>'.
    Type 'null' is not assignable to type 'Partial<State>'.ts(2345)
```

If you then use `@ts-ignore`, I would say that you're shooting yourself in the foot.
ESLint (and TSLint) prevent the usage of `@ts-ignore` for a reason.

**Comment by owl-from-hogvarts** [comment]
Thanks for reply.

Sorry, my english is quite poor)

I mean what will store do when updater return:
1. partial state with values which are already in store 
2. empty opject (`{}`)

These thing are not documented in `componentStore`.

**Comment by owl-from-hogvarts** [comment]
@timdeschryver Pls check my previous comment) Thanks in advance.
