### ISSUE TITLE
Incorrect change tracking of entity updates where ID got changed

### ISSUE THREAD

**Issue by preda7or** [ngrx/platform#3108]
## Minimal reproduction of the bug/regression with instructions:

- Execute entity update where the `changes` contains a different id than the updated id
- Try to undo the update
- Profit

https://ngrx-seed-lejy6r.stackblitz.io

## Expected behavior:

- change tracking should work even with updates where the id changes
(use case: entities are files, id is the path, renaming the file changes the path)

- changeState should track entities under their update ID
- undo should be able to remove updated entity and upsert original entity after ID was updated

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

Ngrx 10.0.0

## I would be willing to submit a PR to fix this issue

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Have you tried this in NgRx v12?

**Comment by preda7or** [comment]
Update the stackblitz to 12.3.0, still the same:
https://stackblitz.com/edit/ngrx-seed-lejy6r

**Comment by timdeschryver** [comment]
If I understand correctly, you're updating the `id` of an entity.
I find that a weird thing to do, and I'm not sure if this should be supported by NgRx Data.
In the example you give, I would expect a specific id field to be used instead of the path of the file.

**Comment by preda7or** [comment]
Yes, this is bit of an edge case, as people do not often change the id,
but in my case (and in case of all file systems) the file path works very well as an id.
I saw that the update response may override the id too, so I was thinking why couldn't the update itself do that already (I mean with correct change tracking).

(ps. if I used UIDs on the backend I need to access a database, with the path I can go directly to the disk, or in parallel to the disk and the database)

**Comment by timdeschryver** [comment]
Closing this issue because it's an edge case, and I consider that IDs can't be changed.
We might re-evaluate this when it pops up again.

**Comment by DmitryEfimenko** [comment]
@timdeschryver  here it pops up again. Updating ids is a standard behavior for optimistic updates - when entity is added with a temporary id before the API call is complete, and updated with the actual id when API call succeeds and returns it
