### ISSUE TITLE
EffectsSubscription remove??

### ISSUE THREAD

**Issue by mailok** [ngrx/platform#311]
please, how to cancel a effect?? when import {EffectsSubscription} from "@ngrx/effects" it gives me an error, because do not existe in de package, my versión is  "4.0.2".
Exists another way to cancel a effect? I need stop the action launched by the effect

**Comment by brandonroberts** [comment]
See controlling effects: https://github.com/ngrx/platform/blob/master/docs/effects/api.md#onruneffects

**Comment by mailok** [comment]
I was reading, but I'm not clear how to use it OnRunEffects. you could put a much clearer example?

**Comment by brandonroberts** [comment]
Sure. Are you wanting to stop effects from running or only dispatch an action from an effect under certain criteria. If its the latter, you just need to use the `filter` operator on your effect. If you don't want the effect to dispatch any actions, use `dispatch: false` in the decorator.

```ts
@Effect({ dispatch: false })
```

**Comment by alsoicode** [comment]
I could also use a more detailed example for OnRunEffects.

I have effects for feature modules that are lazy loaded only when the user is authenticated. When the user logs out, I would like to turn the effects off until the log in again.

Is something like that possible? or perhaps in a different manner than OnRunEffects?
