### ISSUE TITLE
More explanation on reducers DI?

### ISSUE THREAD

**Issue by moniuch** [ngrx/platform#3112]
## I would be willing to submit a PR for the docs :heart:

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

With some previous intermediate experience in ngrx.io, I find this page:
https://ngrx.io/guide/store/recipes/injecting

not really helpful in explaining *WHY* one would use DI for registering reducers, as opposed to the commonly known technique `StoreModule.forRoot({ ... })`

Could someone expand on the technique, its advantages or situations where it must be used, and make this page less succinct? Thanks.

**Comment by timdeschryver** [comment]
You can use it to dynamically create a root or feature reducer.
I haven't used it in my projects, but I believe a use case would to be to an add or remove a reducer based on the application's configuration, or based on the authenticated user.
