### ISSUE TITLE
Doc page about ngrx vs SSR

### ISSUE THREAD

**Issue by moniuch** [ngrx/platform#3113]
## I would be willing to submit a PR for the docs :heart:

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

I would personally find it very useful to see a page about ngrx vs SSR.

It might not be super obvious to all what sort of considerations (and if there are any) need to be made when using an ngrx app with SSR. An explanation on the state hydration, maybe some time-based operators in effects that need to be avoided? I am wild guessing here, because I don't have enough experience with SSR, but I feel like this area is totally omitted and it would be helpful to have a word on it.

**Comment by timdeschryver** [comment]
I think this can be closed in favor of https://github.com/ngrx/platform/discussions/3078.
Feel free to re-open if that's not the case.

**Comment by moniuch** [comment]
@timdeschryver While #3078 indeed mentions SSR, what I had in mind was a primer, recipe-like doc page describing the flow, building blocks, limitations, etc. of using ngrx store with SSR. Not sure if this ticket should be seen as duplicate. I believe this sort of manual could help even before the aforementioned API gets created. Usually API documentation doesn't really help to understand the concept behind it, esp. for beginners.
