### ISSUE TITLE
ngrxPush not working with strictTemplate checks

### ISSUE THREAD

**Issue by ocsurfnut** [ngrx/platform#3114]
## Minimal reproduction of the bug/regression with instructions:

Use the ` | ngrxPush` pipe with an observable typed differently than the `@Input()`.

## Expected behavior:

Error `Type 'X' is not assignable to type 'Y'.`

## Actual behavior:

No type error in IDE or from `ng build`.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

Versions 11 and 12, not OS-specific.

## Other information:

Copying the `ngrxPush` source code locally and experimenting, I've isolated it to [this line](https://github.com/ngrx/platform/blob/master/modules/component/src/push/push.pipe.ts#L57).  If `export class PushPipe<S> ...` is changed to `export class PushPipe<S = any> ...`, the type checking starts working.

Working from there, I confirmed that _any_ pipe class with a generic argument is skipped in strict template checking.  I created a [Stackblitz](https://stackblitz.com/edit/angular-ivy-1f1mfz?devtoolsheight=33&file=src/app/pipes/generic.pipe.ts) to demonstrate the base issue, which seems specific to Angular, not NgRx.  However, I couldn't find any related issues with Angular or otherwise.

Without understanding the need for this generic parameter, I'm not sure if this change is desirable.  I noticed the [Angular async pipe](https://github.com/angular/angular/blob/master/packages/common/src/pipes/async_pipe.ts#L83) simply types the internal value as `any`, and does not use a generic on the class.

## I would be willing to submit a PR to fix this issue

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by markostanimirovic** [comment]
Generic parameter [here](https://github.com/ngrx/platform/blob/master/modules/component/src/push/push.pipe.ts#L57) seems like a surplus to me too.

[Reproduction with `ngrxPush`](https://stackblitz.com/edit/angular-ivy-ytb3lo?file=src/app/app.component.ts)
