### ISSUE TITLE
Eagerly initialize the State service

### ISSUE THREAD

**Issue by shlomiassaf** [ngrx/platform#312]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## What is the current behavior?
The `State` service is not initialized until it is being used.
This might lead to unexpected  results and unexpected values in the state.

## Expected behavior:
`State` service should be initialized in the DI within the `StoreModule.forRoot()` 

In my application I have a `CoreModule` and a `RootModule`

`StoreModule.forRoot()` and `CoreModule` are set in the `RootModule`.

The state contains a list of items that are populated in the app bootstrap.

A user can see a list of items when opening a popup. The popup component is defined in the `CoreModule`. The page uses the `State` service to get the list of items.

When opening the page I see a blank list since they are not in the state (though they are there in the dev tool)

Adding the following provider to the `RootModule` solves the isssue
```ts
  { provide: APP_INITIALIZER, 
    useFactory: () => () => {}, 
    multi: true,
    deps: [  State  ] }
```
This will force eager init of the `State` before `CoreModule` requests it.

I can assume that when not doing eager init the `CoreModule` get's a different instance or maybe its related to the new ability to have a new state in feature modules (although I have no feature modules with a feature store)

**This started once I updated `store@4.0.0` to `store@4.0.3`**

To apply it from the library, the provider above need to be added to the providers in `forRoot`

**Comment by brandonroberts** [comment]
I don't think this warrants changing the behavior for the service. The workaround for eagerly instantiating the `State` service is simple enough. Closing as non-actionable for now.
