### ISSUE TITLE
Documentation does not reflect angular strict mode by default

### ISSUE THREAD

**Issue by xchimera** [ngrx/platform#3125]
## Other information:

The documentation does not reflect strict mode. As an example in the Entity/Adapter documentation, the selectCurrentUser selector would give a null type error as userId is nullable.

## I would be willing to submit a PR for the docs :heart:

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by xchimera** [comment]
In the reducer.ts file, it has a nullable selectedUserId. I have copied the State directly from https://ngrx.io/guide/entity/adapter:

```
export interface State extends EntityState<User> {
  // additional entities state properties
  selectedUserId: string | null;
}
```

And in the index.ts, the following selectors is created:

```
export const selectCurrentUserId = createSelector(
  selectUserState,
  fromUser.getSelectedUserId
);

export const selectCurrentUser = createSelector(
  selectUserEntities,
  selectCurrentUserId,
  (userEntities, userId) => userEntities[userId]
);
```
where selectCurrentUserId can be nullable, unless i am missing something.

I made a user feature by almost copy pasting from the docs, and got an error that userId was nullable.

**Comment by timdeschryver** [comment]
Oh yikes, it seems like I had the cached version of the docs.
Thanks for the extra info.

After giving it a second look, it seems like you're completely right.
Feel free to create a PR to get this resolved.

**Comment by gauravsoni119** [comment]
I would also like to contribute if no one is working on this. I think the fix should be updating the docs to have (_userId && userEntities[userId]_),
```
export const selectCurrentUser = createSelector(
  selectUserEntities,
  selectCurrentUserId,
  (userEntities, userId) => userId && userEntities[userId]
);
```
