### ISSUE TITLE
Store Walkthrough missing types

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#3128]
This one comes from a [StackOverflow question](https://stackoverflow.com/questions/68914356/what-does-props-book-mean-in-ngrx-angular). It seems like our [walkthrough](https://ngrx.io/guide/store/walkthrough) is missing some type definitions for some [book actions](https://github.com/ngrx/platform/blob/master/projects/ngrx.io/content/examples/testing-store/src/app/state/books.actions.ts).

This should become

```ts
export const addBook = createAction(
  '[Book List] Add Book',
  props<{ bookId:number }>()
);

export const removeBook = createAction(
  '[Book Collection] Remove Book',
  props<{ bookId:number }>()
);

export const retrievedBookList = createAction(
  '[Book List/API] Retrieve Books Success',
  props<{ book:Book }>()
);
```

Because the book property name of the `retrievedBookList` action is now lowercase, all references to it should also be updated.

## I would be willing to submit a PR for the docs :heart:

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by mauromattos00** [comment]
Hi @timdeschryver! Can I get this one, please?

**Comment by timdeschryver** [comment]
@mauromattos00 sure, thanks for the PR!
