### ISSUE TITLE
[Question] Store Dev Tools + Router Store

### ISSUE THREAD

**Issue by gperdomor** [ngrx/platform#313]
According to [migration guide](https://github.com/ngrx/platform/blob/master/MIGRATION.md):

> NOTE: store-devtools currently causes severe performance problems when used with router-store. We are working to fix this, but for now, avoid using them together

That was properly solved? Their issue (https://github.com/ngrx/platform/issues/97) is closed, but mi chrome console it freezes sometimes

**Comment by brandonroberts** [comment]
You can use a custom serializer for the router state https://github.com/ngrx/platform/blob/master/docs/router-store/api.md#custom-router-state-serializer

**Comment by bufke** [comment]
Is using the custom serializer the long term fix for the issue or is it a temp workaround?

**Comment by brandonroberts** [comment]
The `RouterStateSnapshot` isn't going to change, so only picking the parts of it you need would be more efficient. That note should be changed to point to the custom serializer.
