### ISSUE TITLE
Update the stackblitz link on issue template

### ISSUE THREAD

**Issue by rafaelss95** [ngrx/platform#3132]
Stackblitz on [issue template](https://github.com/ngrx/platform/blob/master/.github/ISSUE_TEMPLATE/bug-report.md) is a bit outdated. It uses the version 10 and doesn't use `createAction` and `createReducer` yet, for example.

## I would be willing to submit a PR for the docs :heart:

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Should be upgraded now, thanks for letting us know 👍

**Comment by rafaelss95** [comment]
@timdeschryver Thanks! Would it be asking too much to enable strict mode + Ivy by default? 😍

**Comment by timdeschryver** [comment]
@rafaelss95 there you go 😉
