### ISSUE TITLE
distinctUntilChanged() usage in ngrxLet

### ISSUE THREAD

**Issue by e-oz** [ngrx/platform#3135]
Just want to highlight the fact that `distinctUntilChanged()` only compares objects by reference, so if something has been changed inside - it will not be emitted.

https://github.com/ngrx/platform/blob/83bb8a9e4c6492470e5a13e0a93949f0a1acbe79/modules/component/src/core/cd-aware/cd-aware_creator.ts#L73

**Comment by e-oz** [comment]
Ok, but I think it will be good to note this somewhere in the docs :) People will try to use it as a drop-in replacement of the “ngIf={} as ctx” trick.

**Comment by timdeschryver** [comment]
Sorry, it was unclear what you meant with the issue.
Feel free to open a Pull Request to mention that `ngrxLet` uses `distinctUntilChanged`.
