### ISSUE TITLE
NgRx Version 12.4.0 no method *.addAll available anymore on AdapterEntity

### ISSUE THREAD

**Issue by kwhjvdkamp** [ngrx/platform#3137]
### In our gitter support channel at https://gitter.im/ngrx/platform

Learning NgRx seems, as many leading figures are trying to let me believe in, it seems pretty straight forward to learn. Many people are copying the same sample over and over again on several media channels, e.g. However, as mentioned already by others (at least one on Morioh) there seems to be a culprit! I noticed it too! For some reason on newer versions of NgRx (probably higher than 8.6.0) on version 12.4.0 the method .addAll on the AdapterEntity is removed. 
There is no information available (at least I could not find it) why, when and for what reason, this method has been removed. Moreover , there seems to be no workaround available or suggestion how to add a whole collection is a different way. This sample, trackable on several social media by search terms 'Angular: Build a CRUD Application With NgRx' needs to be marked as outdated and pretty worthless, unless experiences people out of the NgRx community should direct how to overcome this hurdle. 
It not my goal to bring up an issue, but much more I need a tip (support) how to continue. It also might help others....

**Comment by kwhjvdkamp** [comment]
...searching for information in previous versions of NgRx. Deep down in the NgRx branch Version 10.1.x I found this piece of comment 
  **/** @deprecated addAll has been renamed. Use setAll instead. */

**Comment by timdeschryver** [comment]
All of our migrations are added to the [migrations on ngrx.io](https://ngrx.io/guide/migration/v11#removed-addall-in-favor-of-setall).

**Comment by kwhjvdkamp** [comment]
...I missed that piece of info, thanks

**Comment by kwhjvdkamp** [comment]
...I missed those docs! Thanks Tim!
