### ISSUE TITLE
router selectors - strict type

### ISSUE THREAD

**Issue by TomaszCz** [ngrx/platform#3140]
When using 
```
export const {
  selectCurrentRoute, // select the current route
  selectFragment, // select the current route fragment
  selectQueryParams, // select the current route query params
  selectQueryParam, // factory function to select a query param
  selectRouteParams, // select the current route params
  selectRouteParam, // factory function to select a route param
  selectRouteData, // select the current route data
  selectUrl, // select the current url
} = getSelectors(selectRouter);
```
taken directly from:
https://ngrx.io/guide/router-store/selectors

I am getting an error for object-destructuring rule ( I am still on tslint )

## Describe any alternatives/workarounds you're currently using
My workaround is to disable the type for this line:
// tslint:disable-next-line:typedef

## If accepted, I would be willing to submit a PR for this feature

[X] Yes (Assistance is provided if you need help submitting a pull request)
[] No

**Comment by timdeschryver** [comment]
I'm going to close this issue, because this is a popular pattern (and is also used across our docs).
As a fix, you can do

```ts
export const {
  ...
}: ReturnType<typeof getSelectors> = getSelectors();
```

**Comment by TomaszCz** [comment]
Thank you! It works
