### ISSUE TITLE
Async pipe for store subscriptions with better typing

### ISSUE THREAD

**Issue by samuelfernandez** [ngrx/platform#3142]
Both Angular's async pipe and ngrxPush are designed for generic observable subscriptions. Since it is possible that the source observable doesn't emit on subscription, both provide an initial default value according to its type definition:

- `async`: default `null` (`transform<T>(obs: Observable<T>): T | null`)
- `ngrxPush`: default `undefined` (`transform<T>(obs: Observable<T>): T | undefined`)

When using strict null checks, both force to handle that default value downstream.

However, when the source of observable is the store, it acts as a `BehaviorSubject`, which emits on subscription. That default value is never emitted, so the pipe could simply be typed as `transform<T>(obs: Observable<T>): T`. This can simplify a lot strict checks removing the need for cumbersome downstream null checks when the source doesn't have that typing.

A new pipe `storeAsync` specific to this use case would be useful. It could have a runtime check to ensure that the observable truly emits on subscription. 

To provide even a simpler API, the pipe could accept a selector, and pipe it to the Store. This would simplify a lot smart components, so instead of this:

```html
<!-- input1: number | undefined -->
<!-- input2: string | undefined -->
<app-presentational 
[input1]="obs1$ | ngrxPush"
[input2]="obs2$ | ngrxPush">
```

```ts 
obs1$: Observable<number> = this.store.select(selector1);
obs2$: Observable<string> = this.store.select(selector2);
```

We could simply do this:

```html
<!-- input1: number -->
<!-- input2: string -->
<app-presentational 
[input1]="selector1 | storeAsync"
[input2]="selector2 | storeAsync">
```

```ts 
selector1 = selector1;
selector2 = selector2;
```

## Describe any alternatives/workarounds you're currently using

- Use `!` operator in the template, which has other problems when source observable has a valid null or undefined type.
- Handle unnecessary downstream null checks just because of bad typings

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
Thanks @samuelfernandez. We've discussed this previously and decided it's not something we want to add to the core, as you still have to inject the Store to dispatch actions, and to potentially combine external observables, which adds more complexity to figuring out where things are coming from.
