### ISSUE TITLE
link to StoreDevtoolsConfig leads to a pornographic ad site

### ISSUE THREAD

**Issue by iuliust** [ngrx/platform#3143]
Hi,
I was looking for [StoreDevtoolsConfig's documentation in the API section of the site](https://ngrx.io/api/store-devtools/StoreDevtoolsConfig), and as its documentation doesn't help a lot, I clicked on the link that was supposed to lead me to more in-depth doc about that interface. Unfortunately, `extension.remotedev.io` domain's ownership was not renewed and the link now leads to a rather terrible site.

Try it yourself (NSFW) : [http://extension.remotedev.io/docs/API/Arguments.html](http://extension.remotedev.io/docs/API/Arguments.html)

Have a good day, ngrx is awesome.
A quick note to cheer you up after this blunder :
I'm using ngrx in my enterprise to build software that will be used for heart surgery. Tonight, when going asleep, you may feel proud of doing something that is used to actually save lives !

**Comment by markostanimirovic** [comment]
> Unfortunately, `extension.remotedev.io` domain's ownership was not renewed and the link now leads to a rather terrible site.

😂 🤦‍♂️

Thanks for reporting this! Do you want to create a PR with fixed links?

**Comment by brandonroberts** [comment]
Yikes. Thanks @iuliust. We may need to file this upstream also

**Comment by iuliust** [comment]
Sure.
@markostanimirovic What should be the updated link ?

**Comment by brandonroberts** [comment]
@iuliust let's just remove it for now

**Comment by nicearma** [comment]
You can find the problem here 
zalmoxisus/redux-devtools-extension#810

and the official repo (I found two)
(from the store chrome) https://github.com/reduxjs/redux-devtools/tree/master/extension
(from the store firefox) https://github.com/zalmoxisus/redux-devtools-extension
