### ISSUE TITLE
RFC:  Add default type to Store<T>

### ISSUE THREAD

**Issue by jinder** [ngrx/platform#315]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

I'd like to suggest updating the Store definition from ```Store<T>``` to ```Store<T={}>```.  As you can now have feature effects/reducers/selectors, there's really no need to pass an AppState type to the Store.  Would be nice to make this optional if your use of the Store doesn't rely on inline lambdas for selectors.

**Comment by brandonroberts** [comment]
We want to encourage type safety, so this is not a change we would add.

**Comment by jinder** [comment]
@brandonroberts Completely agree which is why I'm suggesting ```T={}``` rather than ```T=any```.  It means that if you wish to use lambda selector, you need to specify a type.  If you're using a feature selector you have the same type safety you have at the moment.   

Please re-consider.
