### ISSUE TITLE
loading/error as default state in component store

### ISSUE THREAD

**Issue by tomalaforge** [ngrx/platform#3152]
Hello ngrx team. 

Please find below, one small feature request which can be a nice addon to the component store. 

In componentStore, you often have to deal with loading indicator and error status, and you end up adding it in many of your componentState. 
Would it be nice to have it already set in the store, and automatically handle in the store effect function ? 

I have done a small stackblitz application to show you what I mean and how we can implement it. 
https://stackblitz.com/edit/angular-ivy-ggm1tl?file=src/app/component-store.ts

Waiting for your feedback

Thanks

**Comment by markostanimirovic** [comment]
Moving this issue to Discussions (💡 Ideas category).
