### ISSUE TITLE
book-list walkthrough error in books.reducer.ts

### ISSUE THREAD

**Issue by nowconsulting** [ngrx/platform#3153]
Hi,

I am new to NgRx.  I was going through the Walkthrough section of the NgRx web site, and I am getting a compile error when following the sample code.  So my application does not build.  Looking at the code in your StackBlitz implementation, I see the same bug I am getting.  However, the StackBlitz version runs without any problem.  I even downloaded the ZIP file with the code an tried to build locally.  Still no luck

So I am at a loss.  I am wondering if the StackBlitz implementation is running different code from what I see in the source code windows.

The issue is in the **books.reducer.ts** file.  The **on(retrieveBookList** has an error in its definition.  I am including graphics from StackBlitz and my local environment
![StackBlitz](https://user-images.githubusercontent.com/23481789/134975632-5b020083-c342-4a68-b833-daf9af282684.PNG)
![MyCode](https://user-images.githubusercontent.com/23481789/134975659-8aaad3d4-7af9-4696-a17c-e632f4291520.PNG)
 which shows the error I am describing.

Please look into this and correct it.

Thank you in advance.

**Comment by timdeschryver** [comment]
We're sorry for this inconvenience, the correct version is  fixed in [this PR](https://github.com/ngrx/platform/pull/3151) but it needs to be released.
