### ISSUE TITLE
createSelector - how to assign correct type

### ISSUE THREAD

**Issue by TomaszCz** [ngrx/platform#3163]
Hi! 

Entire NGRX library is very well written, sometimes quite complex piece of art. I really enjoy using it everyday.

I searched docs and also looked up https://github.com/ngrx/platform/blob/master/modules/store/src/selector.ts#L125 but i cannot see the answer. I would like to correctly enforce strict typing on my selectors, so that when my interfaces changes, i get a compilation error. In particular my current problem is attached below:

![image](https://user-images.githubusercontent.com/20865719/135731345-4fc2c709-9b9d-4431-af14-cbfeeb594e13.png)

My source code:
```
export interface UsualInterface {
    value: boolean;
  }

  export function isAvailable1(): UsualInterface {
    return {
      someIncorrectKey: true, // this error is visible in vscode
      value: false,
    };
  }

  export function selector1(): MemoizedSelector<
    AppState,
    UsualInterface,
    DefaultProjectorFn<UsualInterface>
  > {
    return createSelector(mapState, (state: MapState) => {
      return {
        someIncorrectKey: true, // silent error ...
        value: false,
      };
    });
  }

  export const selector2 = createSelector(mapState, (state: MapState) => {
    return {
      someIncorrectKey: true, // silent error ...
      value: false,
    };
  });

  export const selector3 = createSelector<AppState, MapState, UsualInterface>(
    mapState,
    (state: MapState) => {
      return {
        someIncorrectKey: true, // error ...
        value: false,
      };
    }
  );

  export const selector4 = createSelector<AppState, MapState, UsualInterface>(
    mapState,
    (state: MapState) => {
      const myCustomObject: UsualInterface = {
        someIncorrectKey: true, // my workaround ...
        value: false,
      };

      return myCustomObject;
    }
  );
```

I see no online examples where people would actually add any kind of type in 'createSelector' function. ( like in your docs https://ngrx.io/guide/store/selectors ). But imagine having a tslint rule - expected call-signature: 'XXX' to have a typedef (typedef) -- applied to selectors, what would you write there? Currently any object match and i need to wrap my object to const before returning otherwise if the interface change, i am left with really nasty bugs.

Apologize if such question was already asked - I failed to find anything similar. 
I will appreciate any help.

**Comment by alex-okrushko** [comment]
Hi @TomaszCz 

We keep GitHub issues for reporting problems with code. Questions are better to be asked at discord.gg/ngrx

You can enforce the type by specifying the return type of the projector function:

```typescript
export const selector = createSelector(mapState, (state: MapState): UsualInterface => {
    return {
      someIncorrectKey: true, // error 
      value: false,
    };
  });
```

When return the object you can have even more concise form:

```typescript
export const selector = createSelector(mapState, (state: MapState): UsualInterface => ({
      someIncorrectKey: true, // error 
      value: false,
  }));
```

Please ask further questions at the discord.
