### ISSUE TITLE
component-store: select with multiple properties fires even when unrelated properties are changed

### ISSUE THREAD

**Issue by jwedel** [ngrx/platform#3168]
## Minimal reproduction of the bug/regression with instructions:

*Note: Stackblitz is giving me some errors, so I'm pasting an example jest test*

```
import { ComponentStore } from '@ngrx/component-store';
import { Observable } from 'rxjs';

describe('test', () => {
  interface State {
    foo: string;
    bar: string;
    baz: string;
  }

  class FooBarStore extends ComponentStore<State> {
    constructor() {
      super({
        foo: '',
        bar: '',
        baz: '',
      });
    }

    readonly foo$: Observable<string> = this.select(({ foo }) => {
      return foo;
    });

    readonly bar$: Observable<string> = this.select(({ bar }) => {
      return bar;
    });

    readonly baz$: Observable<string> = this.select(({ baz }) => {
      return baz;
    });

    readonly combined$ = this.select(({ foo, baz }) => ({ foo, baz }));
    readonly combined2$ = this.select(this.foo$, this.baz$, (foo, baz) => ({ foo, baz }));

    public updateFoo(foo: string) {
      this.patchState({ foo });
    }

    public updateBar(bar: string) {
      this.patchState({ bar });
    }
  }

  it('spec name', () => {
    const store = new FooBarStore();
    store.bar$.subscribe((bar) => console.log('subscribe bar: ' + bar));
    store.foo$.subscribe((foo) => console.log('subscribe foo: ' + foo));
    store.combined$.subscribe(({ foo, baz }) =>
      console.log(`subscribe combined: foo=${foo}, baz=${baz}`)
    );
    store.combined2$.subscribe(({ foo, baz }) =>
      console.log(`subscribe combined2: foo=${foo}, baz=${baz}`)
    );
    console.log('Calling updateFoo');
    store.updateFoo('newFoo');
    console.log('Calling updateBar');
    store.updateBar('newBar');
  });
});
```

Both combined selects select on `foo` and `baz`. When foo is updated, both subscribe blocks are executed. When bar is updated, `combined$` subscribe is fired, `combined2$` is not.

## Expected behavior:

When bar is updated, `combined$` and  `combined2$` are not fired.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

- `"@ngrx/component-store": "^10.1.2"` <- This was the most recent version that worked with angular 8
- `"@angular/core": "^8.2.0",`  <- We cant update Angular due to some legacy code currently.
- No browser, works even in jest runner but also in Chrome
- Node v12.22.5

## I would be willing to submit a PR to fix this issue

[X] Yes (If that means "in general", but I don't know what the problem is)
[ ] No

**Comment by markostanimirovic** [comment]
Reported behavior is actually expected. `ComponentStore.select` uses `distinctUntilChanged` without comparator under the hood, which means that in case of `this.select(({ foo, bar }) => ({ foo, bar }))`, it compares returned objects by reference -> When the state is changed, it will always return new object `{ foo, bar }`, whose reference differs from the previous one.

You can do the following:

```ts
  readonly fooBar$ = this.select(({ foo, bar }) => ({ foo, bar })).pipe(
    distinctUntilChanged(
      (previous, current) =>
        previous.foo === current.foo && previous.bar === current.bar
    )
  );
```

or:

```ts
  readonly fooBar$ = this.state$.pipe(
    map(({ foo, bar }) => ({ foo, bar })),
    distinctUntilChanged(
      (previous, current) =>
        previous.foo === current.foo && previous.bar === current.bar
    )
  );
```

However, I suggest this as the preferred way:

```ts
  readonly foo$ = this.select(s => s.foo);
  readonly bar$ = this.select(s => s.bar);
  readonly fooBar$ = this.select(
    this.foo$,
    this.bar$,
    (foo, bar) => ({ foo, bar })
  );
```

cc @alex-okrushko
