### ISSUE TITLE
Make it possible to use MockStore's overrideSelector method against selectors given by entityAdapter.getSelectors()

### ISSUE THREAD

**Issue by dil-btarkovacs** [ngrx/platform#3172]
Currently **if** a selector (`booksSelector` in this example) is created in the following way (using entityAdapter's `getSelectors` method):
``` lang-ts
export const booksAdapter = createEntityAdapter<Book>();
const { selectAll, selectTotal } = booksAdapter.getSelectors((state: BooksFeature) => state.books);
export const booksSelector = selectAll;
```
**then** it's impossible to use the overrideSelector method in a unit test, eg.:
``` lang-ts
let store = spectator.inject(MockStore);
let mockBooksSelector = store.overrideSelector(booksSelector, testBooks);
//...
mockBooksSelector.setResult(otherTestBooks)
```
Because the `overrideSelector` expects a `Selector` as its first parameter.

I think this makes us writing unnecessary workarounds in unit tests.
3 solutions seem possible:
1: Extend the the acceptable types of the first parameter of `MockStore`'s `overrideSelector`.
2: Extend the MockStore with an `overrideTypelessSelector` method that is similar to  the original `overrideSelector` but it accepts these kind of selectors as first param.
3: Modify the `EntityAdapter`'s `getSelectors` method to return with selectors that implement `Selector` or `MemoizedSelector`.

## Describe any alternatives/workarounds you're currently using
Currently I can't test the connection only between a state selector and a linked variable.
One of the (unwanted) workarounds is that we can change the state through the MockStore (or the entityAdapter) to trigger a change in the desired selector's value.
Another solution is to wrap the selectAll into a MemoizedSelector with createSelector.
Aaaaand the best workaround is:
```
export const booksSelector = createSelector(
    selectBooksState,
    (books) => Object.values(books.entities)
);
```
:D

## Other information:
Same problem is detailed on stackoverflow: https://stackoverflow.com/questions/69519000/in-unit-test-how-to-override-an-ngrx-selector-which-is-created-by-entityadapter

If accepted, I would be willing to submit a PR for this feature
(I mean I can try)

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by markostanimirovic** [comment]
closed by #4074
