### ISSUE TITLE
NGRX Schematics does not Support Angular JSON Standalone Configuration

### ISSUE THREAD

**Issue by kurtisblaine** [ngrx/platform#3174]
## Minimal reproduction of the bug/regression with instructions:
1. Use standalone configs for each project in monorepo.

{
  "version": 2,
  "projects": {
    "test-app": "apps/test-app/",
  }
}

2. Run @ngrx/schematics:store with these arguments.
{
        name: app,
        statePath: 'state',
        module: '/app.module.ts',
        root: true,
        path: `/apps/test-app/src/app`,
        stateInterface: 'AppState',
}

3. 
![image](https://user-images.githubusercontent.com/26177969/137521320-990d74ed-d89d-431e-8e12-b4ec2a0cc53b.png)

## Expected behavior:

Should fetch the project.json file from the path specified in the angular.json and generate the store feature.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

NgRx: 
     "@ngrx/component": "^12.2.0",
    "@ngrx/component-store": "12.4.0",
    "@ngrx/effects": "12.4.0",
    "@ngrx/entity": "12.4.0",
    "@ngrx/router-store": "12.4.0",
    "@ngrx/store": "12.4.0",

Angular:
    "@angular/animations": "12.1.0",
    "@angular/cdk": "12.1.0",
    "@angular/common": "12.1.0",
    "@angular/compiler": "12.1.0",
    "@angular/core": "12.1.0",
    "@angular/forms": "12.1.0",
    "@angular/localize": "12.1.0",
    "@angular/material": "12.1.0",
    "@angular/material-moment-adapter": "12.1.0",
    "@angular/platform-browser": "12.1.0",
    "@angular/platform-browser-dynamic": "12.1.0",
    "@angular/platform-server": "12.1.0",
    "@angular/router": "12.1.0",
    "@angular/service-worker": "12.1.0",

Node:
   v14.17.5

OS: 
   Windows 10

## I would be willing to submit a PR to fix this issue

[X ] Yes, but might not like the way I fix it.
[ ] No

**Comment by kurtisblaine** [comment]
Here is the pull request: https://github.com/ngrx/platform/pull/3175. Not supplying the app name to the schematic and instead supplying the path will work.

**Comment by brandonroberts** [comment]
This was an Nx configuration issue
