### ISSUE TITLE
Deprecate the `RootState` generic of `createFeatureSelector`

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#3179]
## Describe any alternatives/workarounds you're currently using

Deprecate the `State` generic of `createFeatureSelector`  because it's causing type issues with `Store`.
For this, we can also add an automatic migration.

BEFORE:

```ts
createFeatureSelector<State, FeatureA>('featureA');
```

AFTER:

```ts
createFeatureSelector<FeatureA>('featureA');
```

## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by santoshyadavdev** [comment]
Hey @timdeschryver is this open, can I take this one .

**Comment by sod** [comment]
Doesn't this make the generic of `Store` useless, because it's not validated anymore anyway?

**Comment by HamzaMeski** [comment]
fantastic
