### ISSUE TITLE
[ng/ngrx 12.x] StoreModule.forRoot Exception: StoreModule.forRoot in lazy module (other than app.module.ts) throws StoreModule.forRoot called twice exception

### ISSUE THREAD

**Issue by momoadeli** [ngrx/platform#3181]
## Minimal reproduction of the bug/regression with instructions:
BUG in ng/ngrx 12.x:  https://stackblitz.com/edit/angular-ivy-oes5ve?file=README.md (throws StoreModule.forRoot called twice exception)
WORKS in ng/ngrx 8x: https://stackblitz.com/edit/ngrx-lazy-loading-wa21lc?file=README.md

## Expected behavior:
should load store and feature in LazyModule just like it did in ng/ngrx 8x.

should load store and feature in LazyModule just like it did in ng/ngrx 8x.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

ng 12.x
ngrx 12.x
node v14.17.3
npm 6.14.13

## Other information:

This works in 8x versions. See statckblitz: https://stackblitz.com/edit/ngrx-lazy-loading-wa21lc?file=README.md

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

 i have no idea where the bug is.

**Comment by momoadeli** [comment]
@brandonroberts I don't understand which two checks? I have only ONE forRoot call. Please advise

**Comment by brandonroberts** [comment]
In your version 12 StackBlitz you have StoreModule.forRoot in the AppModule and in the LazyLoadedModule. This will try to load the providers twice, resulting in the error.

If you remove it from the AppModule it should work as you expect.

If you need further assistance, join the Discord https://discord.gg/ngrx
