### ISSUE TITLE
How to use the nightly versions ?

### ISSUE THREAD

**Issue by mlakhara** [ngrx/platform#32]
I have been using the 2.x branch of store, effects, and router-store for a while now and want to upgrade to the 4.x versions. However, I don't see any instructions on how to use the nightly build for the packages under ngrx/platform. It would be great if you could point me in  a direction and would really appreciate your help .

**Comment by axtho** [comment]
There are two things that are important for you:

1. The [docs](https://github.com/ngrx/platform/tree/master/docs) for each module
2. The [migration guide](https://github.com/ngrx/platform/blob/master/MIGRATION.md)

You will need a little fumbling about to get it to work. But it is possible.

Just be aware that there are two open issues (#30, #31) for implementing v4 (I have tried it myself, but found that it was yet too error prone - maybe I missed stuff, or there are things not fully tested yet).

**Comment by vecernik** [comment]
would you add some examples regarding a store default state into a migration guide, please?

**Comment by mlakhara** [comment]
@axtho I was more concerned about getting the package installed. I couldn't get it from npm. Only 2.x versions is available there it seems.

**Comment by axtho** [comment]
It says in the docs how to pull nightly builds. Check it out there

**Comment by mlakhara** [comment]
@axtho : Sorry, I had visited the docs long ago before sometime. Thanks for pointing this to me.
