### ISSUE TITLE
ComponentStore: Deep partial update

### ISSUE THREAD

**Issue by artfulsage** [ngrx/platform#3204]
## Other information:

Hey! What do you think about providing a possibility for deep partial update? I think it's a kinda common case when you have some nested props inside the state, e.g. a list state with a paginator state and some other query params. And it's very possible that you will update these nested props separately, e.g. page number, page size and so on. But now it's not possible.

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
This feature is not planned at the moment, we can revisit this in the future.
