### ISSUE TITLE
ComponentStore: Method for getting default initial state

### ISSUE THREAD

**Issue by artfulsage** [ngrx/platform#3205]
## Other information:

Hey! What do you think about providing a method for getting default initial state which can be used with lazy initialization? Here is the case. Suppose we have some state which can be updated via URL params, but we can't be sure if there are all required params in the URL. And it would be wrong to set the state with some default value before patching it with these URL params because it will trigger some undesired logic. So the idea is to provide some method which can be used during patching if the state hasn't been initialized yet.

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by markostanimirovic** [comment]
Hey @artfulsage 

What do you mean by lazy getting of initial state?

Can you please provide an example (with code)?

**Comment by artfulsage** [comment]
@markostanimirovic first of all I'm sure any changes made were reasonable. And I don't pretend on the right solution and I can be wrong, but still looking at the code I wonder if we can call some user provided function which will return the default state instead of throwing a `new Error(this.notInitializedErrorMessage)` and then execute the rest code.

**Comment by timdeschryver** [comment]
We want the component store to behave consistently, and that's why the initial state is required upon initialization.
If we remove that constraint, other parts (e.g. selectors) will become harder and it could introduce bugs that are harder to detect.

> Suppose we have some state which can be updated via URL params, but we can't be sure if there are all required params in the URL

I could have misinterpreted the issue, but you can access the route data in the component and set the initial state accordingly.

**Comment by artfulsage** [comment]
@timdeschryver yeah, I guess, these changes can bring some complexity. But still I think that patching shouldn't lead to errors if initiating hasn't been done yet. I think patching could be frozen for a while in that case. But I understand that for the usage in components it's not relevant in most cases, and so let it stays as it is. Please close this issue if you agree. And also thank all of you for your feedback @bryantlikes @markostanimirovic
