### ISSUE TITLE
[docs][ngrx.io] Walkthrough code sample not working

### ISSUE THREAD

**Issue by anton-marchenko** [ngrx/platform#3209]
Walkthrough example not working with Angilar 12 + strict templates + typescript 4.3.5 + strict mode.

@ngrx/store ~12.4.0 or 12.5.1 (both of them)

I am getting errors with Walkthrough example.

File `src/app/state/books.selectors.ts`

![image](https://user-images.githubusercontent.com/45929621/139008951-664a80d5-70c6-4e98-83e9-0a0181243614.png)

```
No overload matches this call.
  The last overload gave the following error.
    Argument of type '(state: AppState) => readonly Book[]' is not assignable to parameter of type '[SelectorWithProps<unknown, unknown, Book[]>, SelectorWithProps<unknown, unknown, unknown>, SelectorWithProps<unknown, unknown, unknown>, SelectorWithProps<unknown, unknown, unknown>, SelectorWithProps<...>, SelectorWithProps<...>, SelectorWithProps<...>, SelectorWithProps<...>]'.ts(2769)
selector.d.ts(177, 25): The last overload is declared here.
(parameter) state: AppState
```

![image](https://user-images.githubusercontent.com/45929621/139008980-faa24084-9753-42ef-9d00-50dde18e4ac5.png)

```
No overload matches this call.
  Overload 1 of 32, '(s1: Selector<AppState, Book[]>, s2: Selector<AppState, string[]>, projector: (s1: Book[], s2: string[]) => (Book | undefined)[]): MemoizedSelector<...>', gave the following error.
    Argument of type 'MemoizedSelector<object, readonly string[], DefaultProjectorFn<readonly string[]>>' is not assignable to parameter of type 'Selector<AppState, string[]>'.
      The type 'readonly string[]' is 'readonly' and cannot be assigned to the mutable type 'string[]'.
  Overload 2 of 32, '(s1: SelectorWithProps<AppState, unknown, Book[]>, s2: SelectorWithProps<AppState, unknown, string[]>, projector: (s1: Book[], s2: string[], props: unknown) => (Book | undefined)[]): MemoizedSelectorWithProps<...>', gave the following error.
    Argument of type 'MemoizedSelector<object, readonly string[], DefaultProjectorFn<readonly string[]>>' is not assignable to parameter of type 'SelectorWithProps<AppState, unknown, string[]>'.
      The type 'readonly string[]' is 'readonly' and cannot be assigned to the mutable type 'string[]'.ts(2769)
const selectCollectionState: MemoizedSelector<object, readonly string[], DefaultProjectorFn<readonly string[]>>
```

I suppose arrays must be ReadonlyArray. I've solved this errors:

```
export const selectBooks = createSelector(
  (state: AppState) => state.books,
  (books: ReadonlyArray<Book>) => books,
);

export const selectCollectionState =
  createFeatureSelector<ReadonlyArray<string>>('collection');

export const selectBookCollection = createSelector(
  selectBooks,
  selectCollectionState,
  (books: ReadonlyArray<Book>, collection: ReadonlyArray<string>) => {
    return collection.map((id) => books.find((book) => book.id === id));
  },
);
```

And another error (I've fixed it in my [pet-project](https://github.com/anton-marchenko/am.ngrx-test/commit/2cceae0c09ea08ef4928610f328caab5ab81c938)) is inside template (file src/app/app.component.html):

![image](https://user-images.githubusercontent.com/45929621/139009420-51d089f6-215e-4d89-9b89-e6ad2e0f67c5.png)

 Another error in the last section (13) file `src/app/app.component.ts`

![image](https://user-images.githubusercontent.com/45929621/139009223-3d7d777e-9425-46dd-986f-0cf0722918ab.png)

```
Argument of type 'MemoizedSelector<AppState, readonly Book[], DefaultProjectorFn<readonly Book[]>>' is not assignable to parameter of type '(state: object) => readonly Book[]'.
  Types of parameters 'state' and 'state' are incompatible.
    Type '{}' is missing the following properties from type 'AppState': books, collectionts(2345)
(alias) const selectBooks: MemoizedSelector<AppState, readonly Book[], DefaultProjectorFn<readonly Book[]>>
import selectBooks
```

```
No overload matches this call.
  Overload 1 of 9, '(mapFn: (state: object) => (Book | undefined)[]): Observable<(Book | undefined)[]>', gave the following error.
    Argument of type 'MemoizedSelector<AppState, (Book | undefined)[], DefaultProjectorFn<(Book | undefined)[]>>' is not assignable to parameter of type '(state: object) => (Book | undefined)[]'.
      Types of parameters 'state' and 'state' are incompatible.
        Type 'object' is not assignable to type 'AppState'.
  Overload 2 of 9, '(key: never): Observable<never>', gave the following error.
    Argument of type 'MemoizedSelector<AppState, (Book | undefined)[], DefaultProjectorFn<(Book | undefined)[]>>' is not assignable to parameter of type 'never'.ts(2769)
(alias) const selectBookCollection: MemoizedSelector<AppState, (Book | undefined)[], DefaultProjectorFn<(Book | undefined)[]>>
import selectBookCollection
```

I've solved it in my [pet-project](https://github.com/anton-marchenko/am.ngrx-test/commit/06ef2b4ffeba2e0df579ffa51b3cb39206aa70a4)

## Code for reproducing

There is my project with described errors:

https://github.com/anton-marchenko/am.ngrx-test

## I would be willing to submit a PR for the docs :heart:

- Yes (Assistance is provided if you need help submitting a pull request)

So, I am ready[ to update your documentation](https://github.com/ngrx/platform/pull/3210) for fixing this issue.)

**Comment by Pingear** [comment]
Hey)
As far as I can see, this code looks different from the website. - https://github.com/ngrx/platform/blob/master/projects/ngrx.io/content/examples/store-walkthrough/src/app/state/books.selectors.ts 
However, this code does not generate such errors. Is there a reason why there is a code on the site that generates an error in my IDE?

**Comment by anton-marchenko** [comment]
@Pingear 
Hi

I had same issue with code above and I fixed this code recently but seems like the updated code is not in the web site yet. Maybe ngrx-team will update it in next release (I don't know clearly)

**Comment by timdeschryver** [comment]
These changes aren't released yet.

**Comment by brandonroberts** [comment]
Updated docs have been deployed
