### ISSUE TITLE
Wrong typing from ngrxLet - incorrectly unwrapped generic type parameter?

### ISSUE THREAD

**Issue by montella1507** [ngrx/platform#3212]
Directive  ngIf (and ngutils/ngLet) support creating object to eliminate tons of ng-containers (one ng-container for one observable).

ngIf / ngLet directives work:
`<ng-container *ngIf="{ a: a$ | ngrxPush } as context">`

ngrxLet - compilation error: 
`<ng-container *ngrxLet="{ a: a$ | ngrxPush } as context">`
`<ng-container *ngrxLet="{ a: a$ | async } as context">`

```
 Type '{ a: any; }' is not assignable to type 'ObservableInput<any> | null | undefine
d'.
```

I thought ngrxLet should be drop-in replacement (aka better ngIf). So this may be supported?

**Comment by markostanimirovic** [comment]
@montella1507 

`*ngrxLet` expects [`ObservableInput`](https://github.com/ReactiveX/rxjs/blob/master/src/internal/types.ts#L90) as input, so error that you reported in first comment is expected. You can use `*ngIf` for that.

Regarding your second comment: it seems that your IDE cannot correctly infer the unwrapped type. Check [this example](https://stackblitz.com/edit/ngrx-let-strict-templates?file=src%2Fapp%2Fapp.component.html) where `*ngrxLet` works fine with `"strictTemplates": "true"`.

**Comment by montella1507** [comment]
@markostanimirovic  you were right. 

https://youtrack.jetbrains.com/issue/WEB-52068

Thank you.
