### ISSUE TITLE
RFC: feat(store) Deprecate select operator

### ISSUE THREAD

**Issue by damianbeles** [ngrx/platform#3213]
Can we deprecate `select()` operator?

Let's say we have the following state:
```javascript
state: { apple: { thrownApples: number }, pear: { thrownPears: number } }
```

And we have two ways of selecting the apple feature:
```javascript
apple1$ = this.store.select(fromApple.getThrownApples).pipe(tap(() => console.log('triggered storeSelect apple')));
apple2$ = this.store.pipe(tap(() => console.log('triggered storePipeSelect apple')), select(fromApple.getThrownApples));
```

We subscribe to them in:
```javascript
ngOnInit(): void {
  this.apple1$.subscribe();
  this.apple2$.subscribe();
}
```

Imagine we have two actions, `throwApple`, `throwPear`, each one increasing the state number for that fruit.

We'll make two functions for testing when those `console.log()` are printed:
```javascript
throwApple(): void {
  this.store.dispatch(appleActions.throwApple());
}

throwPear(): void {
  this.store.dispatch(pearActions.throwPear());
}
```

Now:
- throwing apples provides the following output:
```
triggered storeSelect apple
triggered storePipeSelect apple
```
because we modified the apple feature state (we increased `thrownApples` by 1).
- throwing pears provides the following output:
```
triggered storePipeSelect apple
```
even tho we changed just the pear feature (we increased `thrownPears` by 1).

## Describe any alternatives/workarounds you're currently using

`this.store.select()`

## Other information:
As far as my understanding of NgRx is for now:
- `apple1$` way of `this.store.select()` uses / calls `select` just once at initialization.
- `apple2$` way of `this.store.pipe(select())` uses / calls `select` each time the state is modified, not only for the feature state it is selecting.

If my understanding it's correct, there may be cases where instead of calling `select` once, it will be called even 1.000 times (each time state changes).

Isn't this a performance concern since there are many function calls when it can be just one?

There is this discussion from #1361 which recommends `this.store.select()` over `this.store.pipe(select())` and also the docs are written with `this.store.select()`.

[Stackblitz](https://stackblitz.com/edit/angular-ivy-rfyqwb?devtoolsheight=33&file=src/app/app.component.ts)

## If accepted, I would be willing to submit a PR for this feature

[x]  Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
This is not on our roadmap to remove. Using `store.pipe(tap())` before `select()` works as intended as you'll get every state update. We do recommend using `store.select())` but we will keep things backwards compatible for existing apps.
