### ISSUE TITLE
metaReducers don't work in forFeature module when using createFeature

### ISSUE THREAD

**Issue by evanfuture** [ngrx/platform#3216]
## Minimal reproduction of the bug/regression with instructions:

https://stackblitz.com/edit/ngrx-seed-rh3wya?devtoolsheight=33&file=src/app/app.module.ts

## Expected behavior:

When using `createFeature`, metaReducers stop working.

```
// THIS IS WHAT I EXPECT TO WORK
StoreModule.forFeature(counterFeature, {
    metaReducers: counterMetaReducers,
}),

 // THIS IS WHAT ACTUALLY WORKS
StoreModule.forFeature(counterFeature.name, counterFeature.reducer, {
    metaReducers: counterMetaReducers,
}),
```

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
Angular 12.x
NgRx 12.4.x

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ x ] No
(I might, but I can't promise anything)

**Comment by timdeschryver** [comment]
I think this is how we intended it to work, but I could be wrong though.
If that's the case, then we should fix the argument types of `forFeature()`.

**Comment by brandonroberts** [comment]
Yea, that's the case. If you need to add additional config, use the expanded form
