### ISSUE TITLE
Component Store typings lose inference on tap operator

### ISSUE THREAD

**Issue by kylecannon** [ngrx/platform#3217]
## Minimal reproduction of the bug/regression with instructions:

https://stackblitz.com/edit/angular-ivy-eg5tt2?file=src%2Fapp%2Ftest-store.service.ts

Open up stackblitz, go to `src/app/test-store.service.ts` to see examples where Obervable types return as `Observable<unknown>`

## Expected behavior:

Typings should work.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
Tried on `@ngrx/component-store` 12.5.1 and both on RxJS 6.6.x and RxJS 7.4.0

**Comment by markostanimirovic** [comment]
@kylecannon 

I noticed this issue before, but only in non-strict TS mode 👀 

The type is correctly inferred in strict mode: [example](https://stackblitz.com/edit/angular-ivy-xnjfhh?file=src/app/test-store.service.ts).

**Comment by kylecannon** [comment]
@markostanimirovic I have strict mode in the project that I am facing this issue with. Here is from my tsconfig.base.json:
```
        "strict": true,
        "strictPropertyInitialization": false,
        "strictFunctionTypes": false
```

Also, opening your stackblitz url i am given the following error:

![Screen Shot 2021-11-01 at 7 58 08 PM](https://user-images.githubusercontent.com/867978/139779677-3cce5a01-9f90-409a-ab30-c33ab47683de.png)

Removing the xyz, I do see that it's still showing as unknown

![Screen Shot 2021-11-01 at 7 59 39 PM](https://user-images.githubusercontent.com/867978/139779916-20cf91b6-0542-4f16-a18b-fb31d29d6ffc.png)

![Screen Shot 2021-11-01 at 8 00 23 PM](https://user-images.githubusercontent.com/867978/139779972-08e92b6c-8c50-4512-b1bf-71ec2a1c8685.png)

**Comment by markostanimirovic** [comment]
@kylecannon 

> Also, opening your stackblitz url i am given the following error:
> 
> ![Screen Shot 2021-11-01 at 7 58 08 PM](https://user-images.githubusercontent.com/867978/139779677-3cce5a01-9f90-409a-ab30-c33ab47683de.png)
>
> Also, opening your stackblitz url i am given the following error:

Yes, the error indicates that `r` is typed as expected: `Omit<State, "user"> & { username: string; }` (line 47).

> Removing the xyz, I do see that it's still showing as unknown
> 
> ![Screen Shot 2021-11-01 at 7 59 39 PM](https://user-images.githubusercontent.com/867978/139779916-20cf91b6-0542-4f16-a18b-fb31d29d6ffc.png)
> 
> ![Screen Shot 2021-11-01 at 8 00 23 PM](https://user-images.githubusercontent.com/867978/139779972-08e92b6c-8c50-4512-b1bf-71ec2a1c8685.png)
> 
> link: https://stackblitz.com/edit/angular-ivy-dayrax?file=src%2Fapp%2Ftest-store.service.ts

This seems like IntelliSense issue. Because if the `r` is of type `unknown`, then the previous compilation error will be different.

Btw, I checked with your configuration:

```json
  "strict": true,
  "strictPropertyInitialization": false,
  "strictFunctionTypes": false
```

The type of `r` becomes `unknown` when `strictFunctionTypes` is set to `false`.

If you remove `"strictFuctionTypes": false` flag or set `strictFunctionTypes` to `true`, then the type will be correctly inferred:

![strict-function-types](https://user-images.githubusercontent.com/17877290/139827291-8b3814b5-b7a5-4fe4-a84d-e45a980fa413.PNG)

**Comment by kylecannon** [comment]
@markostanimirovic,

Thank you for your help and the investigation effort on your end. This does appear to fix the issue. Are there plans to try and address this or should we try to add this to the ngrx docs? Once again, thank you so much.

**Comment by timdeschryver** [comment]
I think this (setting `strictFuctionTypes` to `false`) is very specific.
We'll keep our eyes and ears open, if it happens again we can add it to the docs.
For now, I'm closing this issue.
Thanks @markostanimirovic for the investigation.

**Comment by spierala** [comment]
There is something special with the `tap` operator.
I do not see the issue with e.g. `map` or `switchMap`...
