### ISSUE TITLE
Fix typo in `createFeature` docs

### ISSUE THREAD

**Issue by markostanimirovic** [ngrx/platform#3220]
There is one typo in `createFeature` docs:

![create-feature-api](https://user-images.githubusercontent.com/17877290/139851314-e8c69f95-356b-43f9-bc8f-b759f53dc2f1.PNG)

Underlined text "a the selector" should be replaced with "and a selector".

**Comment by snutij** [comment]
Hi, @markostanimirovic I can handle it if it's OK for you :+1:

**Comment by markostanimirovic** [comment]
sure @snutij 👍
