### ISSUE TITLE
@ngrx example application not working in strictmode

### ISSUE THREAD

**Issue by Pingear** [ngrx/platform#3222]
Hey)
In the example https://github.com/ngrx/platform/tree/master/projects/example-app
I'm getting errors like - Type 'boolean | null 'is not assignable to type' boolean '. Type 'null' is not assignable to type 'boolean'
I understand that this is due to strictmode, but I cannot figure out how to get rid of them.
Is there an updated version of this example that works correctly with strictmode?
By the way, the example https://ngrx.github.io/platform/stackblitz.html differs from https://github.com/ngrx/platform/tree/master/projects/example-app.

<img width="550" alt="Screenshot 2021-11-04 at 01 55 46" src="https://user-images.githubusercontent.com/16469484/140235055-3362b4e5-929f-44c2-bddc-7852c6ea551b.png">

<img width="835" alt="Screenshot 2021-11-04 at 01 56 58" src="https://user-images.githubusercontent.com/16469484/140235076-512de4d7-12e4-43e7-8db1-e8111892f92e.png">

**Comment by timdeschryver** [comment]
Thanks for opening this issue @Pingear .

See the [Angular docs](https://angular.io/guide/template-typecheck#strict-null-checks) for more info.
I think we should follow the docs and add a bang operator to the async pipe.

Do you want to create a Pull Request with these changes @Pingear ?

**Comment by Pingear** [comment]
Hi @timdeschryver !
Yes I can)
https://github.com/ngrx/platform/pull/3230

**Comment by Pingear** [comment]
@markostanimirovic
@timdeschryver 

Hey)
Unfortunately, I cannot resolve all conflicts on my own, so I am revoking my pull request. In the process of correcting, we had disagreements, the solutions of which I would like to shift onto the shoulders of the authors of the library)
I have collected all conflicting cases -

  1) https://github.com/ngrx/platform/blob/master/projects/example-app/src/app/auth/containers/login-page.component.ts
    a) Tag: bc-login-form
         Conflict property: [pending]="pending$ | async"
2) https://github.com/ngrx/platform/blob/master/projects/example-app/src/app/books/containers/collection-page.component.ts
    a) Tag: bc-book-preview-list
         Conflict property: [books]="books$ | async"
3) https://github.com/ngrx/platform/blob/master/projects/example-app/src/app/books/containers/find-book-page.component.ts
    a) Tag: bc-book-search
         Conflict property: [query]="searchQuery$ | async"
    b) Tag: bc-book-search
         Conflict property: [searching]="loading$ | async"
    c) Tag: bc-book-search
         Conflict property: [error]="error$ | async"
    d) Tag: bc-book-preview-list
         Conflict property: [books]="books$ | async"
4) https://github.com/ngrx/platform/blob/master/projects/example-app/src/app/books/containers/selected-book-page.component.ts
    a) Tag: bc-book-detail
         Conflict property: [book]="book$ | async"
    b) Tag: bc-book-detail
         Conflict property: [inCollection]="isSelectedBookInCollection$ | async"
5) https://github.com/ngrx/platform/blob/master/projects/example-app/src/app/books/components/book-search.component.ts
    The problem and its solution are described in this issue - https://github.com/angular/angular/issues/35958
    a) Tag: input
         Conflict property: (keyup)="search.emit($event.target.value)"
6) https://github.com/ngrx/platform/blob/master/projects/example-app/tsconfig.app.json
    Need to add the following - 
    "angularCompilerOptions": {
        "strictTemplates":  true,
        "strictInjectionParameters": true,
        "strictInputAccessModifiers": true
      },

**Comment by cedricduffournet** [comment]
@timdeschryver  can I take this one ? I already checked the review that has been made on this PR : https://github.com/ngrx/platform/pull/3230

**Comment by timdeschryver** [comment]
@cedricduffournet sorry for my late answer, but yes of course you can 👍
