### ISSUE TITLE
updateOne change state ids array sorting

### ISSUE THREAD

**Issue by mansourcodes** [ngrx/platform#3224]
## Minimal reproduction of the bug/regression with instructions:
I have an index of Invoices loaded from API to the NGRX Store, When the user enters a single Invoice it updates the full details from the API.

the Issue is that the index order changed when I user Ngrx updateOne I find that the ids array moves the entity to the front when updating it.

This issue is known and should be solved on older Ngrx version (v10): https://github.com/ngrx/platform/issues/571
we are using Ngrx version 12

Check screen shots on : **stackoverflow**
https://stackoverflow.com/questions/69894401/ngrx-updateone-change-ids-array-sorting

## Expected behavior:

Keeping the sort as it's.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

        "@angular/cdk": "^12.2.0",
        "@angular/common": "~12.2.0",
        "@angular/core": "~12.2.0",
        "@angular/forms": "~12.2.0",
        "@angular/material": "^12.2.0",
        "@angular/platform-browser": "~12.2.0",
        "@angular/platform-browser-dynamic": "~12.2.0",
        "@angular/router": "~12.2.0",
        "@angular/service-worker": "~12.2.0",

        "@ngrx/effects": "^12.5.1",
        "@ngrx/entity": "^12.5.1",
        "@ngrx/router-store": "^12.5.1",
        "@ngrx/store": "^12.5.1",
        "@ngrx/store-devtools": "^12.5.1",

## I would be willing to submit a PR to fix this issue

[ x ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by AdditionAddict** [comment]
Offending line is
https://github.com/ngrx/platform/blob/01dbce00ac6cf9287eed301b2aa3f801479bf8ed/modules/entity/src/sorted_state_adapter.ts#L124

**Comment by mansourcodes** [comment]
solved 

https://stackoverflow.com/questions/69894401/ngrx-updateone-change-ids-array-sorting/69895465#69895465
