### ISSUE TITLE
Wrong link on page Entity Adapter

### ISSUE THREAD

**Issue by Flachdachs** [ngrx/platform#3225]
On page https://ngrx.io/guide/entity/adapter in the section of `createEntityAdapter<T>`: 

In the description of `selectId` the word `method` is linked to an unrelated destination.

**Comment by timdeschryver** [comment]
Thanks for openening this issue Flachdachs, if you want feel free to update our docs at https://github.com/ngrx/platform/blob/master/projects/ngrx.io/content/guide/entity/adapter.md and remove the backticks around `method` - this should fix this issue.

**Comment by Flachdachs** [comment]
The process of changing two backticks is much simpler for someone who is already involved in the project than for others that have to do a whole chain of actions starting with a fork.

**Comment by snutij** [comment]
I can open a PR if it's ok for you @timdeschryver 👍

**Comment by timdeschryver** [comment]
It's all yours @snutij
