### ISSUE TITLE
Cannot read property 'start' of undefined at new EffectsRootModule

### ISSUE THREAD

**Issue by Vlad00b** [ngrx/platform#3226]
I have an ionic project for Angular 11.2.0. The project uses ngrx. I need to implement server side rendering. 
I use "@nguniversal / express-engine" for this. 
![image](https://user-images.githubusercontent.com/48056663/140810539-c5428704-c706-4b94-832b-27c93551a0e1.png)
When trying to import EffectsModule
![image](https://user-images.githubusercontent.com/48056663/140810827-f3aa5426-fec7-416f-bccb-7d2b488e7c97.png)
 I get this error
![image](https://user-images.githubusercontent.com/48056663/140810634-e63225dd-fe3d-4ff2-85d6-b3c6c1608aab.png)

**Comment by timdeschryver** [comment]
I noticed that the Angular and NgRx versions are different, have you tried to keep the Agular and NgRx versions compatible on v11 or v12?

**Comment by Vlad00b** [comment]
Yes, I used ngrx 11.1.1 with angular 11.2.0, but the error remained. 
It turned out to be much simpler. I just needed to provide the exact versions of the dependencies. Now my package.json looks like this and it working.
![image](https://user-images.githubusercontent.com/48056663/140994790-91dd99d6-3962-4a2e-882a-bebc5b3ef35d.png)
