### ISSUE TITLE
On ngrx/Schematics execution > Cannot read property 'Loose' of undefined

### ISSUE THREAD

**Issue by Sagato** [ngrx/platform#3233]
Hi,

when I add ngrx to my Angular 13 Project (13.0.0) I am unable to create via schematics:
`ng generate @ngrx/Schematics:entity user -m app.module.ts`

the error says: `Cannot read property 'Loose' of undefined`

What I already did to resolve:

Remove all packages, do a clean install. Delete Package-lock, did a clean Install.
Downgraded to Version 12.4.0 in order to see if the error persists.

I don't know how to resolve this issue.

package.json

{
  "name": "example",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "lint": "eslint .",
    "watch": "ng build --watch --configuration development",
    "test": "ng test",
    "e2e": "ng e2e",
    "cypress:open": "cypress open",
    "cypress:run": "cypress run"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~13.0.0",
    "@angular/cdk": "^13.0.0",
    "@angular/common": "~13.0.0",
    "@angular/compiler": "~13.0.0",
    "@angular/core": "~13.0.0",
    "@angular/forms": "~13.0.0",
    "@angular/material": "^13.0.0",
    "@angular/platform-browser": "~13.0.0",
    "@angular/platform-browser-dynamic": "~13.0.0",
    "@angular/router": "~13.0.0",
    "@auth0/auth0-angular": "^1.8.0",
    "@ngrx/effects": "^12.5.1",
    "@ngrx/entity": "^12.5.1",
    "@ngrx/store": "^12.5.1",
    "@ngrx/store-devtools": "^12.5.1",
    "ccxt": "^1.60.36",
    "rxjs": "~7.4.0",
    "socket.io-client": "^4.3.2",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.0.1",
    "@angular/cli": "~13.0.1",
    "@angular/compiler-cli": "~13.0.0",
    "@cypress/schematic": "^1.5.3",
    "@ngrx/schematics": "^12.5.1",
    "@types/jasmine": "~3.10.0",
    "@types/socket.io-client": "^3.0.0",
    "cypress": "latest",
    "jasmine-core": "~3.10.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "~4.4.3"
  }
}

Angular.json
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "example": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        },
        "@schematics/angular:application": {
          "strict": true
        }
      },
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/example",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "inlineStyleLanguage": "scss",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "./node_modules/@angular/material/prebuilt-themes/indigo-pink.css",
              "src/styles.scss",
              "src/styles/_layout.scss"
            ],
            "scripts": [
              "node_modules/ccxt/dist/ccxt.browser.js"
            ]
          },
          "configurations": {
            "production": {
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "500kb",
                  "maximumError": "1mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "2kb",
                  "maximumError": "4kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "outputHashing": "all"
            },
            "development": {
              "buildOptimizer": false,
              "optimization": false,
              "vendorChunk": true,
              "extractLicenses": false,
              "sourceMap": true,
              "namedChunks": true
            }
          },
          "defaultConfiguration": "production"
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "configurations": {
            "production": {
              "browserTarget": "example:build:production"
            },
            "development": {
              "browserTarget": "example:build:development"
            }
          },
          "defaultConfiguration": "development"
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "example:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.spec.json",
            "karmaConfig": "karma.conf.js",
            "inlineStyleLanguage": "scss",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "./node_modules/@angular/material/prebuilt-themes/indigo-pink.css",
              "src/styles.scss"
            ],
            "scripts": []
          }
        },
        "cypress-run": {
          "builder": "@cypress/schematic:cypress",
          "options": {
            "devServerTarget": "example:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "example:serve:production"
            }
          }
        },
        "cypress-open": {
          "builder": "@cypress/schematic:cypress",
          "options": {
            "watch": true,
            "headless": false
          }
        },
        "e2e": {
          "builder": "@cypress/schematic:cypress",
          "options": {
            "devServerTarget": "example:serve",
            "watch": true,
            "headless": false
          },
          "configurations": {
            "production": {
              "devServerTarget": "example:serve:production"
            }
          }
        },
        "lint": {
          "builder": "@angular-eslint/builder:lint",
          "options": {
            "lintFilePatterns": [
              "src/**/*.ts",
              "src/**/*.html"
            ]
          }
        }
      }
    }
  },
  "defaultProject": "example",
  "cli": {
    "defaultCollection": "@ngrx/schematics"
  }
}

**Comment by brandonroberts** [comment]
This is because there was a breaking change in the Angular Devkit that removed the JSON parser from schematics. This is fixed in NgRx 13. As a workaround you could try only bumping the @ngrx/schematics package to the 13.x RC.

**Comment by Sagato** [comment]
okay I see, thx for the fast reply. Is there any estimate on the release of NgRx 13? Greets

**Comment by JayAhn2** [comment]
After updating all ngrx dependency to `13.0.0-rc.0`, I got the below error.

```
? What should be the name of the reducer? food
? Should we add success and failure actions to the reducer? No
? Do you want to use the create function? Yes
Invalid JSON character: "/" at 0:0.
Done
```

**Comment by brandonroberts** [comment]
I got this error also when using just the reducer schematic. It seems that removing the comments from the `tsconfig.app.json` fixes the issue. This seems like a build issue, as when I checked the schematics, it still contained Ivy checks, which checks the `tsconfig.app.json`. This will be resolved in the v13 release build.

**Comment by ffadikhan** [comment]
@brandonroberts I am facing same issue **Cannot read property 'Loose' of undefined** when try to create reducer in cli.
Below is my `tsconfig.app.json` file.

`{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "types": []
  },
  "files": [
    "src/main.ts",
    "src/polyfills.ts"
  ],
  "include": [
    "src/**/*.d.ts"
  ]
}
`
I am using latest ngrx packages in angular `13.0.2`.
`"@ngrx/effects": "^12.5.1",
    "@ngrx/schematics": "^12.5.1",
    "@ngrx/store": "^12.5.1",
    "@ngrx/store-devtools": "^12.5.1",`
    
    I don't know how to resolve this issue.

**Comment by ffadikhan** [comment]
@Sagato and @JayAhn2 NGRX version 13 is now available and my issue has been fixed.
