### ISSUE TITLE
createFeatureSelector - featureName  is not type checked

### ISSUE THREAD

**Issue by gkamperis** [ngrx/platform#3242]
## Minimal reproduction of the bug/regression with instructions:

https://github.com/ngrx/platform/blob/4e9d52f252e965db06477d4591dccccda6fbff19/modules/store/src/selector.ts#L618

currently `createFeatureSelector` is defined as 

```
export function createFeatureSelector<T>(
  featureName: string
): MemoizedSelector<object, T>;
```

This allows for any random string to be passed as a `featureName` and TS cannot type-check for non existent fields

## Expected behavior:

I would expect that the function provides type-checking... perhaps as was the deprecated

```
export function createFeatureSelector<T, V>(
  featureName: keyof T    <<<<--------------
): MemoizedSelector<T, V>;
```

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
v12.5.0

**Comment by brandonroberts** [comment]
We recommend using the single interface for the top-level selector.

**Comment by gkamperis** [comment]
@brandonroberts thanks for the reply but I did not understand what the alternative is... 
is there a simple example you can point me to?
