### ISSUE TITLE
Docs: dns error with v12 documentation

### ISSUE THREAD

**Issue by cedricduffournet** [ngrx/platform#3244]
## Minimal reproduction of the bug/regression with instructions:
 - navigate to https://v12.ngrx.io

it seems that v12 subdmain has not been configurated

## Expected behavior:
Documentation should be displayed

## Other information:
Mayby related to this issue ? https://github.com/ngrx/platform/issues/3185

**Comment by timdeschryver** [comment]
It's working now, I think.
If it doesn't work, please at a comment to # #3185.

![image](https://user-images.githubusercontent.com/28659384/142625639-9d6a0451-09c7-4f55-8575-2caf30df1ec3.png)
