### ISSUE TITLE
*ngrxLet causes ASSERTION ERROR: Reached the max number of directives [Expected=> 1 != 1 <=Actual]

### ISSUE THREAD

**Issue by e-davidson** [ngrx/platform#3246]
The issue seems to be when the observable emits while angular is still constructing the template.

## Minimal reproduction of the bug/regression with instructions:

Here's an example to reproduce

https://github.com/e-davidson/angular-issue-reproduction-2021

## Expected behavior:

The component should render with no errors.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

NgRx 13, Angular 13, Node 14.17, OS wsl, browser chrome

## Other information:

I also submitted an issue to the angular team
https://github.com/angular/angular/issues/44231

If they do fix the issue this would still be a problem since createEmbeddedView will have been called an extra time when it shouldn't due to the recurssion.

I believe it can be easily fixed by not relying on the embeddedView to be null and instead have a field if it's the first time or not.

See here
https://github.com/ngrx/platform/blob/master/modules/component/src/let/let.directive.ts#L121

## I would be willing to submit a PR to fix this issue
Sure, I'd love to help if the team feels this is correct.

[x ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by markostanimirovic** [comment]
Good catch @e-davidson ! 👍  The proposed solution seems good to me.
