### ISSUE TITLE
Ngrx Data showing a weird error with Angular 12

### ISSUE THREAD

**Issue by boufenzi** [ngrx/platform#3247]
Hello guys, i'm having an error using ngrx Data that i don't understand. I followed the documentation of ngrx Data and everything works fine i'm getting data but in my html the result don't show and i'm having this error in the console : 
```
TypeError: E.reduce is not a function
    mergeServerUpserts http://localhost:4200/main.js:1
```
do someone knows why am i having this error ?

**Comment by markostanimirovic** [comment]
@boufenzi 

It's difficult to conclude what is happening in your app based on the console error you provided. Can you share your project on Github or create a reproduction via [StackBlitz](https://stackblitz.com/)?

**Comment by boufenzi** [comment]
Hello, thanks for your response. Here is my stackBlitz, i just followed what ngrx data documentation said and i'm having this weird error that i don't know where she's coming from https://github-pp6u2q.stackblitz.io
