### ISSUE TITLE
[Bug]: `package.json` of `@ngrx/store/testing` is incorrect

### ISSUE THREAD

**Issue by ahnpnl** [ngrx/platform#3248]
## Minimal reproduction of the bug/regression with instructions:

- Checkout https://github.com/ahnpnl/jest-preset-angular/tree/example-wrong-lib-format (branch **example-wrong-lib-format**)
- Run `yarn install` to install project dependencies
- Navigate to `e2e/partial-ivy-lib`
- Run `yarn install`
- Open `e2e/partial-ivy-lib/node_modules/@ngrx/store/testing/package.json`
- Observe that a few lines in this `package.json` points to non-existed files:
```
{
  "name": "@ngrx/store/testing",
  "typings": "ngrx-store-testing.d.ts",
  "main": "../bundles/core-testing.umd.js", // THIS IS NOT EXISTED !!!
  "module": "../fesm2015/ngrx-store-testing.mjs",
  "es2015": "../fesm2015/testing.js", // THIS IS NOT EXISTED !!!
  "esm5": "../esm5/testing/testing.js", // THIS IS NOT EXISTED !!!
  "esm2015": "../esm2015/testing/testing.js", // THIS IS NOT EXISTED !!!
  "fesm5": "../fesm5/testing.js", // THIS IS NOT EXISTED !!!
  "fesm2015": "../fesm2015/ngrx-store-testing.mjs",
  "es2020": "../fesm2020/ngrx-store-testing.mjs",
  "esm2020": "../esm2020/testing/ngrx-store-testing.mjs",
  "fesm2020": "../fesm2020/ngrx-store-testing.mjs",
  "sideEffects": false
}
```
- Open `e2e/partial-ivy-lib/node_modules/partial-ivy/testing/package.json`. Observe that those lines are not there. 

Because of those lines, it causes the issue https://github.com/thymikee/jest-preset-angular/issues/1195

## Expected behavior:

The content of `e2e/partial-ivy-lib/node_modules/@ngrx/store/testing/package.json` should be similar to `e2e/partial-ivy-lib/node_modules/partial-ivy/testing/package.json`, which is
```
{
  "name": "@ngrx/store/testing",
  "typings": "ngrx-store-testing.d.ts",
  "module": "../fesm2015/ngrx-store-testing.mjs",
  "fesm2015": "../fesm2015/ngrx-store-testing.mjs",
  "es2020": "../fesm2020/ngrx-store-testing.mjs",
  "esm2020": "../esm2020/testing/ngrx-store-testing.mjs",
  "fesm2020": "../fesm2020/ngrx-store-testing.mjs",
  "sideEffects": false
}
```

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):  

@ngrx/store version **13.0.1**

## Other information:

Once correcting the content for `package.json` like above, Jest won't throw error about "Cannot find module" anymore

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

**Comment by timdeschryver** [comment]
Thanks for the detailed report @ahnpnl
