### ISSUE TITLE
Offline capabilities

### ISSUE THREAD

**Issue by maxime1992** [ngrx/platform#325]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ x ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

As ngrx as moved to a mono repo, I'm duplicating a closed issue from the old repository: https://github.com/ngrx/store/issues/385

<hr>

I've been reading a lot of things lately about offline state management and I was wondering if that was possible with `Redux` (and `ngrx`).

I've found [ngrx roadmap](https://github.com/ngrx/ngrx.github.io/wiki/Roadmap) and saw something interesting : 
![image](https://cloud.githubusercontent.com/assets/4950209/24788403/a6f32b1e-1b6d-11e7-8e30-2a3b448a8620.png)

Then I also took a look into https://github.com/btroncone/ngrx-store-localstorage and it seems quite nice but also very simple and I don't think that it's going to handle retry, synchronisation, rollback, etc.

Luckily, I saw a brand new repo on Github which seems very promising : [Redux Offline](https://github.com/jevakallio/redux-offline). And I was wondering if it would be possible to integrate it with `ngrx` ? Because with `ngrx` we declare our store like that : 
![image](https://cloud.githubusercontent.com/assets/4950209/24788504/309d1492-1b6e-11e7-81c5-6cadc51aa5be.png)

And with `Redux Offline` there's a function `createOfflineStore` : 
![image](https://cloud.githubusercontent.com/assets/4950209/24788525/4be2f906-1b6e-11e7-82dc-b7cbeda2dc37.png)

Also, it seems that effects are handled by `Redux Offline` : 
![image](https://cloud.githubusercontent.com/assets/4950209/24788543/6b16642a-1b6e-11e7-822f-2b9391792c09.png)
and I'm not too sure how it stands with `ngrx/effects`.

There is obviously some work needed to make them work together (if it's possible in the first place) but it seems to be worth it and I'd love to have some feedback about that.

Angular claims to be for every paltforms 
![image](https://cloud.githubusercontent.com/assets/4950209/24788634/dd76aa34-1b6e-11e7-9cac-4c6c6eb032ad.png)

![image](https://cloud.githubusercontent.com/assets/4950209/24788649/f3b3c7fa-1b6e-11e7-802e-c339d316251b.png)

and it's trully a good think. But unless we use `Firebase` or something equivalent, it seems that the synchronization layer is going to be hard to handle (at least if we use redux/ngrx as state management and not directly a browser database, puchDb, etc).

As we're all hearing more and more about PWA awesomeness and how well Angular can be for mobiles (with code splitting, lazy loading, improved change detection, AOT for pre-compiled templates, etc) I think that the next big battle is going to be related to offline capabilities and how to handle the synchronization of the data.

If you have any idea that could hep me figure out how to do that (already ?) with `ngrx` or if you have any knowledge about that topic, please let me know :smile:.

PS : It might not be considered as an issue but this is way too opinionated to go on stackoverflow and needs some serious answer with I hope a lot of content and I don't think it's a good idea to post that on Gitter, that's why I opened it here.

**Comment by maxime1992** [comment]
![image](https://user-images.githubusercontent.com/4950209/29702740-cd8adf60-8972-11e7-84a8-1b8daf8bf7b2.png)

@MikeRyanDev is there any alpha work we can play with? :smile:

**Comment by brandonroberts** [comment]
No action exists on this at the moment. Will reopen once progress is made.

**Comment by RoopeHakulinen** [comment]
@brandonroberts @MikeRyanDev Would you be open for PR on this or is there already something designed for this or even undergoing development?

**Comment by MattiJarvinen-BA** [comment]
If you could post even WIP design goals and pseudo code about how it should work it would be very beneficial regarding community PRs. This is a missing feature that has pushed me into evaluating switching to angular-redux so I could use plain ol' redux-offline middleware instead.

**Comment by demisx** [comment]
Any update on this? We are very interested in offline.
