### ISSUE TITLE
Mismatch with ng 13 rxjs - dependency? 

### ISSUE THREAD

**Issue by kklocker** [ngrx/platform#3253]
I am slightly confused with the NgRx homepage, which states that the minimum version of RxJs should be 7.4.
![image](https://user-images.githubusercontent.com/25065744/143200005-fb119583-8b3f-4a17-a10b-99dd0741e83e.png)

I find this a bit weird, since angular13 relies on `rxjs ^6.6.7` and there has been introduced breaking changes in rxjs 6->7.4.
I guess my question/issue really is: When migrating to ng13 and ngrx13, should I  or should I not update rxjs to 7? 

Thanks. Hope this is clear.

## I would be willing to submit a PR for the docs :heart:

[ x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by markostanimirovic** [comment]
@kklocker 

> When migrating to ng13 and ngrx13, should I or should I not update rxjs to 7?

No, you can keep RxJS `6.5.3` or higher.

Angular `13.0` allows RxJS `^6.5.3` or `^7.4.0` as peer dependency, the same is for `@ngrx/store` ([package.json](https://github.com/ngrx/platform/blob/master/modules/store/package.json#L25)). Feel free to open the PR with the fix in migration guide :)
