### ISSUE TITLE
[@ngrx/schematics] Optionally generate entity pattern (introduce -e / --entity flag) when generating NgRx feature

### ISSUE THREAD

**Issue by tomastrajan** [ngrx/platform#3260]
Currently the `ng g feature path/to/feature/state/<state-name> -a -c --module path/to/feature` is great to scaffold whole state features in the consistent fashion across many features / projects.

The issue is that when used, the generated reducer is "vanilla" eg not implementing entity pattern.

It would be great to introduce additional `-e` or `--entity` flag which would

- generate reducer with all the boilerplate for entity pattern in place
- generate <state-name>.model.ts with stub interface (same as for `ng g entity`)
- adjust generated `on(...)` handlers to already use adapter as it can be expected that genrated load (and success) action will lead to `...adapter.setAll(<entity name>, state)` implementation in loadSuccess handler.

## Describe any alternatives/workarounds you're currently using
The entity pattern needs to be added manually into the generated reducer (or the entity reducer generated over the previously generated state feature)

## Other information:

Would be great as the `ng g feature ...` already is doing soo much good in terms of consistency of projects!

## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ x] No (sorry, extremely busy lately 😅)

**Comment by wgd3** [comment]
@brandonroberts I'd love to try tackling this! I'm working on a branch here: https://github.com/wgd3/platform/tree/issue-3260

Before I open a PR, I have one question - should this functionality support an entity with a name that's different from the feature name? Or just create an entity with the feature name, and let the user run `ng g entity` afterwards? I could see something like "I want a feature `ToDoList` with one entity named `ToDo` and another entity named `Category`"
