### ISSUE TITLE
Stackblitz links are outdated

### ISSUE THREAD

**Issue by cedricduffournet** [ngrx/platform#3261]
The following stackblitz links are outdated:
 - ~https://stackblitz.com/edit/ngrx-seed (contribution - v12)~
 - ~all examples in docs (v12)~ (closed by https://github.com/ngrx/platform/pull/3269)
 -  https://stackblitz.com/edit/ngrx-router-store-selectors (doc - v11)

**Comment by markostanimirovic** [comment]
@cedricduffournet

There is already an open issue for examples: https://github.com/ngrx/platform/issues/3186

**Comment by timdeschryver** [comment]
Does stackblitz work with Angular 13?

I'm getting the following error.
I also tried creating a new project (defaults to angular 12), and after upgrading it to v13 I also get this error.

```
Error in ~/src/main.ts
ngcc failed to run on @angular-devkit/schematics@13.0.4, @angular/core@13.0.3, @eslint/eslintrc@1.0.5, @angular/compiler@13.0.3, strip-ansi@6.0.1, eslint@8.4.0, ansi-regex@5.0.1, ajv-formats@2.1.1, @humanwhocodes/config-array@0.9.2, cli-spinners@2.6.1, eslint-scope@7.1.0, is-glob@4.0.3, normalize-path@3.0.0, @ngrx/store@13.0.1, @ngrx/router-store@13.0.1, globals@13.12.0, @ngrx/schematics@13.0.1, to-regex-range@5.0.1, eslint-visitor-keys@3.1.0, @angular-devkit/core@13.0.4, debug@4.3.3, @angular/animations@13.0.3, @angular/platform-browser@13.0.3, ajv@8.6.3, @angular/common@13.0.3, braces@3.0.2, deep-is@0.1.4, rxjs@7.4.0, binary-extensions@2.2.0, is-binary-path@2.1.0, glob@7.2.0, estraverse@5.3.0, @angular/router@13.0.3, signal-exit@3.0.6, readdirp@3.6.0, ajv@8.8.2, argparse@2.0.1, @ngrx/entity@13.0.1, picomatch@2.3.0, @humanwhocodes/object-schema@1.2.1, @ngrx/store-devtools@13.0.1, @ngrx/effects@13.0.1, fsevents@2.3.2, @angular/forms@13.0.3, espree@9.2.0, @angular/platform-browser-dynamic@13.0.3, flatted@3.2.4, fill-range@7.0.1, is-number@7.0.0, eslint-utils@3.0.0, anymatch@3.1.2, jsonc-parser@3.0.0, acorn@8.6.0, glob-parent@6.0.2, js-yaml@4.1.0, core-js@3.19.3, chokidar@3.5.2.
```

**Comment by cedricduffournet** [comment]
Code example in angular doc seems to use "WebContainer".  On stackblitz dashboard you can create `Node.js` project (this is a beta version).
I created an example with ngrx : https://stackblitz.com/edit/node-v7anuw

**Comment by timdeschryver** [comment]
Oh neat, thanks for the info @cedricduffournet, I did not know that 👍

**Comment by timdeschryver** [comment]
Fyi, I've updated the ngrx-seed to v13.
For the example app, we'll have to verify that a web container project supports TS paths.

**Comment by cedricduffournet** [comment]
@timdeschryver thank you for the ngrx-seed update.
I checked and web container supports paths configured in tsconfig.json (I think that's why this [issue](https://github.com/stackblitz/core/issues/220) has been closed). 
Quick example here : https://stackblitz.com/edit/node-l7ijlh?file=src%2Fmain.ts

**Comment by timdeschryver** [comment]
@cedricduffournet Good to know!
Do you want investigate this further so that our example app also targets a webcontainer project?
Seems like it's [documented](https://developer.stackblitz.com/docs/platform/project-config), and that the Angular team already ported over their examples in [this commit](https://github.com/angular/angular/commit/8020457ce213de2675daf58be2f972e8284a7670#diff-5908ae50532c86504771ece3576086e0e7161080af97560dd7c0cf2e39b1468d).

**Comment by cedricduffournet** [comment]
@timdeschryver yes of course !

**Comment by timdeschryver** [comment]
Thanks @cedricduffournet !
