### ISSUE TITLE
Documentation for factory selectors and how they can be nested to construct final desired state

### ISSUE THREAD

**Issue by mwamufiya** [ngrx/platform#3265]
having checked the ngrx SO, where there are a few outstanding questions on this topic with no answer, as well as a outstanding question in gitter on this topic. there seems to either be some missing documentation on this topic, of this feature is something that the community is using in an unintended way.

since selectors with props were deprecated & the recommended way of dealing with properties is through factory selectors, there doesn't appear to be documentation for how to call one factory selector from within another? to construct it's final output? 

For non factory selectors you are able to have nested calls to other selectors to help construct the output based on different slices of the state.

    export const selector2 = createSelector(
        selectFormState,
        ( state, FormState, props: { id: string} ) => {
           return state.notes.filter( note => note.parentId === props.id);
        }
    );
        
    //one (non factory selector) can call another (non factory selector) & pass the 'state' 
    // allowing developers to isolate selector logic in small chunks and combine them to create the desired result
    export const selector3 = createSelector(
        selectFormState,
       ( state: FormState, props: {id: string} ) => {
           // get notes by using an existing selector and passing the state & properties
           // the state is passed to the selector and it returns the expected result
           const notes = selector2({ storeName: state}, props)
           // do some more logic based on the nested call to a selector
           ...
       }
    );

with  factory selector, how do you go about calling one factory selector from within another :

    // factory Selector
    export const selector2 = (id: string) => createSelector(
        state
        ( state, FormState ) => {
           return state.notes.filter( note => note.parentId === id);
        }
    );
    // factory selector calling another factory selector
    export const selector3 = (id: string) => createSelector(
       state,
       ( state: FormState ) => {
           const items = [];
           state.items
              // return items that match the condition based on the "id" property
              .filter( item => item.parentId === id)
              // merge data from two different slices of the state using a factory selector for "note" in this case
              .map( item => {
                 // how is the `state` passed to the nested selector call below? 
                 return {
                    ...item,
                    notes: selector2( item.id)    // <-------------HERE
                 };
             })
       }
    );

## I would be willing to submit a PR for the docs 
If I understood how this can be done, yes.

[ x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by markostanimirovic** [comment]
@mwamufiya 

Factory selector from your example can be called as follows:

```ts
notes: selector2(item.id)({ featureName: state })
```

However, this is not the right way how selectors should be used. If you want to move the calculation logic from the selector's projector, you can do so by creating a plain TS function instead of calling another selector from the selector's projector.

Feel free to join our [Discord](https://discord.gg/8GRHc2Z3) server or [start new Q&A discussion](https://github.com/ngrx/platform/discussions) for further questions. 🙂
