### ISSUE TITLE
[@ngrx/schematics] Add Feature Selector and pass it to getSelectors when generating entity

### ISSUE THREAD

**Issue by PixelatedFigure** [ngrx/platform#3270]
## Minimal reproduction of the bug/regression with instructions:

When using ngrx schematics to generate an entity, you can provide a module to register the state as a feature in that module, and it generates a feature key to be added to an action reducer map, but one thing missing that developers must always do when generating this creates a feature selector and pass it to the "getSelectors" method at the bottom of the reducer file to ensure it returns the correct state (feature state) rather than the root app state.

## Expected behavior:

To create a feature selector and pass it to the "getSelectors" method.

## I would be willing to submit a PR to fix this issue

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
The preferred way to consume entity selectors is how it's added to the schematics.

```ts
export const {
  selectIds,
  selectEntities,
  selectAll,
  selectTotal,
} = adapter.getSelectors();
```

**Comment by PixelatedFigure** [comment]
Yes, this is what is generated by the schematics when generating an "entity"
But the purpose of this issue is to add a feature selector to the generated reducer and pass it to the adapter.getSelectors method as this is a feature state we're talking about that is registered within a feature module and is part of a root state, and we need a feature selector to specify the state we're using for those selectors that are provided by the entity adapter

**Comment by timdeschryver** [comment]
@PixelatedFigure Could you share what the expected output would be please?

**Comment by PixelatedFigure** [comment]
In the reducer file of a generated schematic using entity command "ng g entity"

```
export const aFeatureKey = 'a'
export interface State extends EntityState<A>{}
export const adapter: EntityAdapter<A> = createEntityAdapter<Group>();
export const initialState: State = adapter.getInitialState({});
export const reducer = createReducer(
....
);

**export const featureState = createFeatureSelector<State>(aFeatureKey);**
export const {
  selectIds,
  selectEntities,
  selectAll,
  selectTotal,
} = adapter.getSelectors(**featureState**);
```

**Comment by PixelatedFigure** [comment]
I believe this should be reopened and reconsidered, please check the provided pull request, the change is minimal and intuitive.
