### ISSUE TITLE
undefined Actions in createEffect

### ISSUE THREAD

**Issue by petrot** [ngrx/platform#3278]
## Minimal reproduction of the bug/regression with instructions:

We have featureStores with some featureEffects. The effects are defined based on the documentation:

```
myAction$ = createEffect(
    () =>
      this._actions$.pipe(
        ofType(myAction),
        tap(action => {
          [...]
        }),
      ),
    { dispatch: false },
  );
```

We don't know why, our code started to fail with the following error:
`TypeError: Cannot read properties of undefined (reading 'pipe')`

because `this._actions$` is undefined.

I found an [old issue](https://github.com/ngrx/platform/issues/1543). Based on that solution the error goes away, but the wffect not fired :/

```
myAction$ = () => createEffect(
    () =>
      this._actions$.pipe(
        ofType(myAction),
        tap(action => {
          [...]
        }),
      ),
    { dispatch: false },
  );
```

## Expected behavior:

Work with the old code style

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

NGRX: 13.0.2
TypeScript: 4.5.4

## Other information:

We use NX monorepo

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

**Comment by petrot** [comment]
Solved: we had to change our tsconfig:
wrong: `"target": "esnext"`
fixed: `"target": "es2015"`

**Comment by parloti** [comment]
Something like this also works.

```
export abstract class Wrapper {
  constructor(protected readonly actions$: Actions) {}
}
export class Effects extends Wrapper {
  constructor(actions$: Actions) {
    super(actions$);
  }
}
```
or
```
export class Effects extends class {
  constructor(protected readonly actions$: Actions) {}
} {
  constructor(
    actions$: Actions,
  ) {
    super(actions$);
  }
}
```
