### ISSUE TITLE
Wrong type either in the documentation or in the type definition

### ISSUE THREAD

**Issue by Laktik228** [ngrx/platform#3282]
Greetings! I have a following issue: In the docs its clearly said that the upsertOne or upsertMany entity adapter has a partial update support:

upsertOne: Add or Update one entity in the collection. Supports partial updates.
upsertMany: Add or Update multiple entities in the collection. Supports partial updates.

While in the code it seems that the type does not support it:
<img width="394" alt="Screenshot 2022-01-11 at 12 30 35" src="https://user-images.githubusercontent.com/22400584/148926414-fb5d3191-06f9-466b-8171-d9f49718b25f.png">

So the question is which one to believe - the docs or it's an error in the code?

Thank you for your attention!

P.S: I tried to update to ngrx 13, but it has this issue.

## I would be willing to submit a PR for the docs :heart:

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
The types are correct here, we want to enforce that a full-fledged object instance is passed to `upsert`. For more info see https://github.com/ngrx/platform/pull/912

Do you want to update the docs @Laktik228 ?

**Comment by Laktik228** [comment]
@timdeschryver I proposed the change
https://github.com/ngrx/platform/commit/b517d18a37acfd6242115a53c9806935fd3e5a8b
