### ISSUE TITLE
Problems with HttpClient requests

### ISSUE THREAD

**Issue by piacentero** [ngrx/platform#3283]
Hi.
I have a problem in an Angular project with all the http requests.
After I installed ngrx/store, ngrx/effects and ngrx/store-devtools every http request doesn't complete unless I force completion with take(1) operator.

I am currently using Angular v10.1.6, rxjs v6.6.0 and ngrx v10.1.2.

Thanks! (ˉ﹃ˉ)

**Comment by markostanimirovic** [comment]
Hi @piacentero 👋

We are trying to keep GitHub issues for bugs and feature requests. For questions, feel free to join our [Discord server](https://discord.com/invite/ngrx) or start a new [Q&A Discussion](https://github.com/ngrx/platform/discussions/new?category=q-a) on GitHub.

Regarding this question, it would be great if you can create a reproduction on [Stackblitz](https://stackblitz.com/edit/ngrx-seed) or at least attach code snippets. 🙂
