### ISSUE TITLE
Module with Featured store imported into 2 parent modules gets destroyed even only one parent module gets destroyed.

### ISSUE THREAD

**Issue by kellywoo** [ngrx/platform#3284]
## Minimal reproduction of the bug/regression with instructions:

I have  'GirlModule' and 'BoyModule' both import 'ChildModule'
Each has own featured store and the problem is if I destroy BoyModule, the store of ChildModule gets disappeared even GirlModule should be with childmodule store.
Here's the code and steps.

1. toggle to lazy-load BoyModule and check the string represents the store state. 
2. once removed BoyModule, try to update root store by clicking increment button.
3. check the string below..

https://stackblitz.com/edit/angular-fndqbu-f812vm?file=src/app/boy/boy.module.ts

![image](https://user-images.githubusercontent.com/25073979/148969093-c1729717-d761-4a82-9841-40ba93cbfac3.png)
![image](https://user-images.githubusercontent.com/25073979/148969138-9819fcd0-a4e9-4b4e-bf17-d9cc0d24fa99.png)

## Expected behavior:
Hope it can keep child featured store alive..
Is there anyway that I can keep child featured store alive?
Dynamically loaded module should be destroyed to release memory.. but can not now, because it crashes app .

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
![image](https://user-images.githubusercontent.com/25073979/148969784-b443fcc5-f594-43b1-b43c-cb6e0692fd2e.png)

**Comment by markostanimirovic** [comment]
@kellywoo 

The reported behavior is actually expected (see the source code [here](https://github.com/ngrx/platform/blob/master/modules/store/src/store_module.ts#L103)).

We could prevent the feature reducer from being removed by adding a flag to the configuration, like this:

```ts
StoreModule.forFeature('foo', fooReducer, { preserveOnDestroy: true });
```

Thoughts?

**Comment by kellywoo** [comment]
Thank you for your kind reply.
I was hoping there would be a way to count modules and if all count goes to zero, destroy store.....
but preserveOnDestroy sounds reasonable too.
Especially with associating effects & selectors..
That would be real helpful :) ❤️

**Comment by brandonroberts** [comment]
I think this is more of an edge case, that if you are dynamically creating and destroying modules, that you should load the store feature separately if you want it to outlive the lifecycle of the module.

**Comment by kellywoo** [comment]
I agree what you are saying in some points, but in a way, I disagree with the comment that this is out about outliving the lifecycle of the module.
This is about managing common resources, most big apps which runs on spa use dynamic-loading,
and I wonder how many people aware of this.
that's why I posted the issue here.

But I think it's true that this is an edge case, only few apps needing switching modules all the time.
Nonetheless I admire your jobs here and really appreciate your reply. 😃
