### ISSUE TITLE
ngrx.io: update footer year to 2022 🎄

### ISSUE THREAD

**Issue by markostanimirovic** [ngrx/platform#3288]
Update year in [footer.component.html](https://github.com/ngrx/platform/blob/master/projects/ngrx.io/src/app/layout/footer/footer.component.html#L20) file to 2022.

**Comment by SarveshLimaye** [comment]
@markostanimirovic can I work on this issue?

**Comment by timdeschryver** [comment]
Sorry @SarveshLimaye, this is already added in #3289
