### ISSUE TITLE
angular4 spa when navigate to another page, all action belong to this page dispatch again, bug?

### ISSUE THREAD

**Issue by node-rookie** [ngrx/platform#329]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

**Comment by node-rookie** [comment]
I found it's just action log again, not real run action, console log func setted in meta reducer, it's a bug or i need config something?

**Comment by brandonroberts** [comment]
Duplicate of #229
