### ISSUE TITLE
Map object is not supported in redux devtools

### ISSUE THREAD

**Issue by mejakm** [ngrx/platform#3293]
## Minimal reproduction of the bug/regression with instructions:

My state with a Map inside:

![image](https://user-images.githubusercontent.com/14975302/149959152-388d454f-27c5-4f7f-bbee-909815fae78b.png)

After dispatching the action and getting the response in my devtools it shows that my state is empty while in fact it's not.

![image](https://user-images.githubusercontent.com/14975302/149959375-1d36101a-1c57-4020-a77d-b3b1094ae840.png)

This is the console log after subscribing to my state slice:

![image](https://user-images.githubusercontent.com/14975302/149959503-51b31b3f-1d11-46e8-be11-d2060c7edfcf.png)

## Expected behavior:

It should show the real state 

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

NgRx: 13.0.1
Angular: 13.1.1
Browser: Chrome
OS: Windows

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
AFAIK The Redux DevTools only support types that can be JSON serialized/deserialized.
`Map` is serialized as a normal object (`{}`), hence this behavior.
That's also why we recommend to keep the state and the actions JSON serializable.

If you really want this fixed, creating an issue in the Redux DevTools repo would be better.
