### ISSUE TITLE
Example: Bump RxJS/jasmine-marbles in examples package.json files

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#3296]
jasmine-marbles should be 0.9.1 to go along with RxJS 7 for the generated examples.

https://github.com/ngrx/platform/blob/master/projects/ngrx.io/tools/examples/shared/boilerplate/cli/package.json
https://github.com/ngrx/platform/blob/master/projects/ngrx.io/tools/examples/shared/package.json

## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by gauravsoni119** [comment]
I would like to contribute. But I am not sure angular will allow using `rxjs@7` with `angular@12`. Probably there will be a bunch of warnings.

**Comment by brandonroberts** [comment]
The examples are updated to Angular v13, so RxJS 7 would work fine there.

**Comment by gauravsoni119** [comment]
I will create PR with `RXJS` 7 and `jasmine-marble` 0.9.1.

**Comment by gauravsoni119** [comment]
Should we need to bump up `RXJS` version in [ngrx.io](https://github.com/ngrx/platform/blob/master/projects/ngrx.io/package.json#L90) app as well?

**Comment by brandonroberts** [comment]
Shouldn't hurt to bump it also
