### ISSUE TITLE
feature schematics: Provide param to create a store-grouping subdirectory

### ISSUE THREAD

**Issue by moniuch** [ngrx/platform#3300]
I find it very cumbersome to achieve desired structure when creating a new feature using `@ngrx/schematics:feature`
I like my store to be enclosed in a directory named `_store`. Therefore my desired outcome of the schematics would be the following

```
lib
  admin
   src
    lib
      _store
        admin.actions.spec.ts
        admin.actions.ts
        admin.reducer.spec.ts
        admin.reducer.ts
        admin.effects.spec.ts
        admin.effects.ts
        admin.selectors.spec.ts
        admin.selectors.ts
      admin.module.ts
      admin-routing.module.ts      
      ...  
```

**Strategy 1:**
If I try it with `--path=libs/admin/src/lib` (ie. without targeting the subfolder), the module is found, dryRun runs clean, but I miss an option to specify the '_store' anywhere.

**Strategy 2:**
If I try it with `--path=libs/admin/src/lib/_store` (first I had to create this folder manually), dryRun spits errors at me, because it looks for the admin module inside this folder. Indeed, admin.module does not exist in this folder, this is only where I want all ngrx stuff to be grouped.

![image 2022-01-25 01-20-43](https://user-images.githubusercontent.com/681956/150887583-2f34b694-d0ec-46a6-be01-6f19463b7f47.png)

So my request would be to have a param that allows to specify the store grouping subdirectory?
I am not talking about the enclosing folders (like effects, selectors), but the main one. And make it bypass the underscore-to-hyphen replacements :)

## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

(I mean, I might, but I have never coded schematics before, so it might require too much of assistance and checkup).

**Comment by timdeschryver** [comment]
This should work, if that's not the case feel free to reopen.

```
npx ng generate  @ngrx/schematics:feature --path=src/app/feature/_store
? What should be the name of the feature? awesome
? Should we generate and wire success and failure actions? Yes
? Do you want to use the create functions? Yes
? What should be the prefix of the action, effect and reducer? load
? Do you want to @ngrx/entity to manage state? Yes
? To which module (path) should the effect be registered in? ../feature.module.ts
```
