### ISSUE TITLE
Replace deprecated `observable$.subscribe` usages

### ISSUE THREAD

**Issue by markostanimirovic** [ngrx/platform#3313]
The `observable$.subscribe(next, error, complete)` signature is deprecated in RxJS 7 and should be replaced with `observable$.subscribe({ next, error, complete })`.

## Other information:

Deprecated `subscribe` signature is used in the following files:

- [`entity-collection-service.spec`](https://github.com/ngrx/platform/blob/master/modules/data/spec/entity-services/entity-collection-service.spec.ts)
- [`entity-cache-effects.spec`](https://github.com/ngrx/platform/blob/master/modules/data/spec/effects/entity-cache-effects.spec.ts)
- [`entity-data-module.spec`](https://github.com/ngrx/platform/blob/master/modules/data/spec/entity-data.module.spec.ts)

**Comment by wiksien** [comment]
I will do that.

**Comment by RishiKumarRay** [comment]
do we have to run tests too?

**Comment by markostanimirovic** [comment]
Sorry @RishiKumarRay, PR for this issue is already created (#3314).

I'll let you know when I find another "good first issue". 🙂

**Comment by timdeschryver** [comment]
Maybe we should add the RxJS ESLint plugin (or just for a while), because it has fixers for some deprecations.

**Comment by matheo** [comment]
@timdeschryver by any chance the `eslint` autofix was implemented somewhere? TIA
