### ISSUE TITLE
Effect registered on the same observable 2 times throws an error in SSR (Node)

### ISSUE THREAD

**Issue by Platonn** [ngrx/platform#3316]
## Minimal reproduction of the bug/regression with instructions:
1. Register an effect on the observable `EMPTY`
   ```ts
   Injectable()
   export class TestEffect {
     effect$ = createEffect(() => EMPTY, { dispatch: false });  
   }
   ```
2. Run 2 requests to render an application in SSR. 
3. 💥 It will throw the following error in SSR on the 2nd SSR request:
<img width="710" alt="image" src="https://user-images.githubusercontent.com/4001059/154058964-c3c49a6f-427b-45a9-b3de-c14fa253e7df.png">

## Expected behavior:
No error thrown when registering the effect on the same observable more than once, when running in Node (SSR).

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
@ngrx/effects 13.0.2
@ngrx/store 13.0.2
@angular/core 13.2.0
@nguniversal/express-engine 13.0.2
Node 16.13.0
rxjs 6.6.0

## Other information:
**Reason of the error:**
When bootstrapping Angular app in SSR for the first request, the function `createEffect` assigns a special property `CREATE_EFFECT_METADATA_KEY` to the global static observable `EMPTY` (from `rxjs`).

When bootstrapping Angular app in SSR for the second request, the function `createEffect` attempts to assign this property to the already-mutated global static observable `EMPTY`, again.

In the browser assigning the same property twice into in the object doesn't cause an error, but in Node it seems to throw.

**More details:**
Ngrx mutates the observable passed to `createEffect()`, by assigning a special property to it:
https://github.com/ngrx/platform/blob/5f5b679520425b6210e9587e9ab2bad7922cb76c/modules/effects/src/effect_creator.ts#L68-L70 

The observable `EMPTY` is a global static object exposed by the `rxjs` library. Since it's a global, it's shared among many bootstraped angular apps in SSR when rendering for various requests.

The problem is not specifically related to the `EMPTY` observable, but in general to calling `createEffect` twice on the same observable.

**Proof that you can't assign a property twice in Node**
Run the following snippet in Node:
```js
const x = {};
Object.defineProperty(x, 'hello', { value: 'world' });
Object.defineProperty(x, 'hello', { value: 'new' });
```

<img width="346" alt="image" src="https://user-images.githubusercontent.com/4001059/154068048-029a61a5-bce8-4687-b5c7-20cd90578355.png">

**Personal opinion**
IMHO ngrx `createEffect()` should not tamper the taken observable.

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

**Comment by markostanimirovic** [comment]
@Platonn 

The same issue was opened some time ago: #3052

As a workaround, you can replace `createEffect(() => EMPTY)` with `createEffect(() => () => EMPTY)`.

**Comment by brandonroberts** [comment]
Closing as a duplicate
