### ISSUE TITLE
Type errors on all effects when returning an action (not a creator)

### ISSUE THREAD

**Issue by rfe-css** [ngrx/platform#3319]
![image](https://user-images.githubusercontent.com/42568214/154541309-5b30045a-f65a-40cc-b04c-2b02c115cdf6.png)

Argument type () => Observable<TypedAction<"[Insurance Page Container] Load Health Insurance">> is not assignable to parameter type () => (Observable<TypedAction<"[Insurance Page Container] Load Health Insurance">> & ConditionallyDisallowActionCreator<DispatchType<EffectConfig>, Observable<TypedAction<"[Insurance Page Container] Load Health Insurance">>>) 

Because `ActionCreator`:

![image](https://user-images.githubusercontent.com/42568214/154541461-153d49f3-f70f-4145-8d15-d9663dd54666.png)

Is both, a `Creator` and a `TypedAction`

![image](https://user-images.githubusercontent.com/42568214/154541707-123e6dae-ec9f-40e5-9aab-9d7ff3843567.png)

where the `TypedAction` should be allowed right?

So if I change the `ActionCreator` to `Creator`, it works as expected:

![image](https://user-images.githubusercontent.com/42568214/154542104-081d235b-49f4-4e76-973b-4e14fb11e5d2.png)

I guess it would be here?

https://github.com/ngrx/platform/blob/0bb49409413b784b1cc55c2b59e67ed760041aa5/modules/effects/src/effect_creator.ts#L17

**Comment by markostanimirovic** [comment]
@rfe-css 

Feel free to reopen this issue with provided reproduction.

For further questions, you can [join our Discord server](https://discord.com/invite/ngrx) or [start a Github discussion](https://github.com/ngrx/platform/discussions/new?category=q-a).

**Comment by rfe-css** [comment]
Stackblitz is here: https://stackblitz.com/edit/ngrx-seed-1smrme?file=src%2Fapp%2Freducers%2Fcounter.effects.ts

But I can't reproduce the error there.
So it must be related to Webstorm's Typescript Service.
It seems like a restart and or recompile of the Typescript Service solves the issue temporarily.
