### ISSUE TITLE
@ngrx/effects/effects"' has no exported member 'EffectsNotification'

### ISSUE THREAD

**Issue by pscanlon1** [ngrx/platform#332]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## What is the current behavior?

import { Actions, Effect, toPayload, OnRunEffects, EffectsNotification } from '@ngrx/effects';

node_modules/@ngrx/effects/effects"' has no exported member 'EffectsNotification'.'

## Expected behavior:

It is supposed to be exported

## Version of affected browser(s),operating system(s), npm, node and ngrx:
4.0.5

**Comment by brandonroberts** [comment]
Your import path is incorrect. It should be `@ngrx/effects`. Most likely you used VSCode to add the import path, but it doesn't add them correctly.

**Comment by brandonroberts** [comment]
The export is `EffectNotification`
