### ISSUE TITLE
Make Getting started guide compliant with ngrx eslint-plugin-ngrx recommended configuration

### ISSUE THREAD

**Issue by toureholder** [ngrx/platform#3325]
Code examples in the [Getting started](https://ngrx.io/guide/store) cause lint errors with ngrx eslint-plugin-ngrx recommended configuration. (It's worth noting that `yarn add @ngrx/store` enables the recommended configuration in the ESLint configuration file by default.)

These lines of code from the guide:

```ts
  // src/app/my-counter/my-counter.component.ts

  constructor(private store: Store<{ count: number }>) {
    this.count$ = store.select('count');
  }
```
surface the errors: 
- `Store` should not be typed, use `Store` (without generic) instead. [ngrx/no-typed-global-store](https://github.com/timdeschryver/eslint-plugin-ngrx/blob/main/docs/rules/no-typed-global-store.md)
- Using `string` or `props drilling` is forbidden. Use a selector instead. [ngrx/prefer-selector-in-select](https://github.com/timdeschryver/eslint-plugin-ngrx/tree/main/docs/rules/prefer-selector-in-select.md)

## I would be willing to submit a PR for the docs :heart:

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
Closed as won't fix. Reference https://github.com/ngrx/platform/pull/3326#issuecomment-1046308255

**Comment by defaultbranch** [comment]
@toureholder I agree with this issue, and also with the ESLint warning. From the "Getting Started Guide", it does not make sense to me that some magic signatures `{count: number}`, `{count: counterReducer}` and a magic string `'count'` are used, when working with a typesafe language.

Frustrating is that after setting the reader up with this poor code style, no clues are given how to get back to typesafe code.
