### ISSUE TITLE
Has no exported member 'ɵɵFactoryDeclaration

### ISSUE THREAD

**Issue by Raushan-Ranjan** [ngrx/platform#3329]
I had followed the same step as given in documentation. But still I am getting this issue.

"node_modules/@ngrx/store/src/actions_subject.d.ts:11:21 - error TS2694: Namespace '"C:/Users/raushan.ranjan/OneDrive - Zycus/Documents/work/start-test/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

     static ɵfac: i0.ɵɵFactoryDeclaration<ActionsSubject, never>"

This issue is still there since few months and no fix given since then.

Angular Fan !
<img width="658" alt="error" src="https://user-images.githubusercontent.com/64747207/155894654-8b246383-cb25-47b0-b4b1-e7fb2a25a626.png">

**Comment by brandonroberts** [comment]
Join the Discord for support https://discord.gg/ngrx. We'll need more information to help you

**Comment by smfukaya** [comment]
Did you manage to solve it? I'm having the same problem.

```
Error: node_modules/@ngrx/store/src/actions_subject.d.ts:11:21 - error TS2694: Namespace '"D:/devtools/cursos/angular-full-app/fitness-tracker/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

11     static ɵfac: i0.ɵɵFactoryDeclaration<ActionsSubject, never>;
```

package.json
```
{
  "name": "fitness-tracker",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^11.2.14",
    "@angular/cdk": "^12.2.0",
    "@angular/common": "~11.2.13",
    "@angular/compiler": "~11.2.13",
    "@angular/core": "~11.2.13",
    "@angular/fire": "^6.1.5",
    "@angular/flex-layout": "^12.0.0-beta.34",
    "@angular/forms": "~11.2.13",
    "@angular/material": "^11.2.13",
    "@angular/material-moment-adapter": "^12.2.0",
    "@angular/platform-browser": "~11.2.13",
    "@angular/platform-browser-dynamic": "~11.2.13",
    "@angular/router": "~11.2.13",
    "@ngrx/store": "^13.0.2",
    "firebase": "^7.0 || ^8.0",
    "hammerjs": "^2.0.8",
    "moment": "^2.29.1",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.3"
  },
  "devDependencies": {
    "@angular-devkit/architect": ">= 0.900 < 0.1300",
    "@angular-devkit/build-angular": "^0.1102.18",
    "@angular/cli": "~11.2.12",
    "@angular/compiler-cli": "~11.2.13",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "firebase-tools": "^8.0.0 || ^9.0.0",
    "fuzzy": "^0.1.3",
    "inquirer": "^6.2.2",
    "inquirer-autocomplete-prompt": "^1.0.1",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "jsonc-parser": "^3.0.0",
    "karma": "~6.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "open": "^7.0.3",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.1.5"
  }
}
```

**Comment by brandonroberts** [comment]
The version of NgRx shouldn't be higher than the version of Angular.

If you're on Angular version 11.x, you should be on NgRx package versions <= 11.x.

**Comment by smfukaya** [comment]
Thank you very much @brandonroberts! It's working now with @ngrx/store 11.1.1!

**Comment by codejq** [comment]
if you are angular 9 use the following and don't ask why but it will work

npm uninstall angular-froala-wysiwyg
npm i angular-froala-wysiwyg@4.0.15
npm uninstall ngx-print
npm i ngx-print@1.2.1
npm install querystring // Should be: "querystring": "0.2.1",
npm i webpack -dev-server@3.11.0
