### ISSUE TITLE
npm install @ngrx/store fails?

### ISSUE THREAD

**Issue by Janzelf** [ngrx/platform#333]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## What is the current behavior?

c:\ngprojects\platform>npm install @ngrx/store
@ngrx/platform@4.0.0 c:\ngprojects\platform
+-- @angular/cdk@2.0.0-beta.8
| `-- tslib@1.7.1
`-- UNMET PEER DEPENDENCY @ngrx/store@4.0.3

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN ngrx-store-freeze@0.1.9 requires a peer of @ngrx/store@^2.2.1 but none was installed.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
windows 10
c:\ngprojects\platform>npm -v
3.10.10

**Comment by brandonroberts** [comment]
There's no need to install `@ngrx/store` in the platform repo. Its mapped through the tsconfig.json
