### ISSUE TITLE
Make the usage of ErrorHandler optional in ReduxDevtools

### ISSUE THREAD

**Issue by phihochzwei** [ngrx/platform#3330]
Currently, when in DevMode I cannot provide my ErrorHandler (which also wants to access Store) since it will cause a CD with the redux devtools

![image](https://user-images.githubusercontent.com/10193885/156356270-7dd4da61-c727-46b8-bee5-baaf8f389c51.png)

It would be great if you could make the usage of the ErrorHandler optional so that this doesnt happen

## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Could you provide a reproduction please?
AFAIK, you should be able to inject to the Store into a custom errorhandler.

**Comment by markostanimirovic** [comment]
@phihochzwei 

Feel free to reopen this issue with provided reproduction.
