### ISSUE TITLE
[Feat] Add title to RouterStore selectors for Angular v14

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#3336]
## Describe any alternatives/workarounds you're currently using

In Angular v14, the Angular Router adds a `title` property to the route metadata that includes a page title/page title resolver. We should have a selector that returns this value. 

## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by santoshyadavdev** [comment]
I will take this once angular 14 is released 🙏

**Comment by timdeschryver** [comment]
@santoshyadavdev if you still want, the NgRx repo is updated to Angular 14

**Comment by santoshyadavdev** [comment]
Awesome will open the PR

**Comment by santoshyadavdev** [comment]
> @santoshyadavdev if you still want, the NgRx repo is updated to Angular 14

The PR is open now, let me know if any changes are needed
