### ISSUE TITLE
Live example app

### ISSUE THREAD

**Issue by tdeschryver** [ngrx/platform#334]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request
</code></pre>

## What is the current behavior?
The example app in the [README](https://github.com/ngrx/platform/blob/master/example-app/README.md) uses the code of the example app at [ngrx/example-app](https://github.com/ngrx/example-app).

## Expected behavior:
I think this should use the example app in this project (at [/example-app](https://github.com/ngrx/platform/tree/master/example-app))?

## Minimal reproduction of the problem with instructions:
N/A

## Version of affected browser(s),operating system(s), npm, node and ngrx:
N/A

## Other information:
Submitting this issue to give a heads up about the example app, perhaps this was forgotten with the release.

**Comment by brandonroberts** [comment]
Yes, we just need to generate a new build and update the github page
