### ISSUE TITLE
Store select with subscription

### ISSUE THREAD

**Issue by fbcarpinato** [ngrx/platform#335]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
</code></pre>

## What is the current behavior?

When i try to select a section of the store the subscription gets triggered only once, even if actions on that section are dispached.

## Expected behavior:

I should get data from the subscription every time i dispatch an action in the store

## Minimal reproduction of the problem with instructions:

> this.store.select((state: AppState) => state.authentication)
        .subscribe((test) => {
            // This is getting called once
            debugger;
        });

**Comment by stalniy** [comment]
your subscription will be called each time `state.authentication` is changed but not each time you dispatch an action in store

**Comment by fbcarpinato** [comment]
of course, in fact I am returning a new object every time, but nothing

**Comment by brandonroberts** [comment]
Please provide a minimal reproduction of this issue using a plunker template https://plnkr.co/edit/tpl:757r6L?p=preview
