### ISSUE TITLE
Jest does not find @ngrx/component-store module

### ISSUE THREAD

**Issue by vistiyos** [ngrx/platform#3350]
## Other information:

I'm integrating ComponentStore in my angular library project because we want to provide isolated state between components. Currently I'm facing problems trying to run the test. My test looks like this:

```
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { instance, mock } from 'ts-mockito';
import { ConfigurationComponent } from './configuration.component';
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { ReactiveFormsModule } from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';
import { ConfigurationStore } from "../../store/configuration.store";

describe('OutletConfigurationComponent', () => {
  let component: ConfigurationComponent;
  let fixture: ComponentFixture<ConfigurationComponent>;
  const store = mock(ConfigurationStore);

  beforeEach(async () => {
    await TestBed.overrideComponent(
     ConfigurationComponent,
      {
        set: {
          providers: [{ provide: ConfigurationStore, useFactory: () => instance(store) }]
        }
      }
    );

    await TestBed.configureTestingModule({
      declarations: [
        ConfigurationComponent,
      ],
      schemas: [CUSTOM_ELEMENTS_SCHEMA],
      imports: [
        ReactiveFormsModule,
        HttpClientModule,
      ]
    })
      .compileComponents();
  });

  beforeEach(() => {
    fixture = TestBed.createComponent(TestHostComponent);
    component = fixture.componentInstance;
  });

  it('should create', () => {
    fixture.detectChanges();
    expect(component).toBeTruthy();
  });
});
```

The error message I'm getting right now is the following:

`Cannot find module '@ngrx/component-store' from 'src/lib/store/configuration.store.ts'`

I have tried to add the route in jest.config.js file but I am still not able to run it. Am I missing anything here?

Any help would be really appreciated.

**Comment by brandonroberts** [comment]
Can you provide a GitHub repo that shows a minimal reproduction of the issue?

**Comment by etiennecrb** [comment]
Hello @vistiyos , 
I had the same issue with `@ngrx/component` and while trying to create a repo that show a minimal reproduction of the issue, I noticed that I was using `@ngrx/component` v13 but my app is still using Angular 12. Adjusting ngrx version to 12 fixed my problem.

**Comment by timdeschryver** [comment]
Thanks for the feedback @etiennecrb .
I'm closing this issue, if you have a reproduction feel free to reopen the issue.
