### ISSUE TITLE
Too many ways to do the same thing and lack of useful resources and examples. 

### ISSUE THREAD

**Issue by Milldrew** [ngrx/platform#3362]
Hello, 

NGRX has several ways to make a store and a reducer as well as actions etc. It also uses rxjs which is esoteric to angular. 

The documentation of ngrx is sparse. The learning materials outside of the documentation are mostly outdated. 

in redux you can make a reducer imperatively or you can use the redux/toolkit. And each method of creating an in memory store is distinguished and well documented. 

Please distinguish the different approaches to creating an in memory store with ngrx, and create a complete example. 

By comparison look here at the redux getting started pages.

https://redux.js.org/introduction/getting-started#other-resources

https://redux.js.org/introduction/learning-resources

https://redux.js.org/tutorials/fundamentals/part-1-overview

---------------------------------------------------------------
The best resource I could find for NGRX is from GDE Christoffer Noring.  ( This resource is outdated)
Architecting Angular Applications with Redux, RxJS, and NgRx

By Christoffer Noring

-----------------------------------------------------------------

I am going to take a look at the angular cookbook here soon. It doesn't need to be this difficult...

Andrew Miller

**Comment by david-shortman** [comment]
Does the page on reducers o the NgRx doc site not contain a complete example and explanation of declaring and implementing a reducer? https://ngrx.io/guide/store/reducers

It demonstrates the recommended way to create a reducer. In addition, it mentions that reducers can be implemented manually, but it is not the idiomatic or recommended approach.

**Comment by david-shortman** [comment]
Action creation and use are also detailed here: https://ngrx.io/guide/store/reducers

**Comment by david-shortman** [comment]
Like the official Angular docs, the NgRx docs do not focus at length on how to compose different types of Observables. Instead, the best source of truth and guidance for RxJs comes from rxjs.dev and learnrxjs.io.

**Comment by david-shortman** [comment]
The NgRx Resources page does look due for an update: https://ngrx.io/guide/store/reducers

I like the way the redux ones are constructed.

**Comment by brandonroberts** [comment]
Thanks @Milldrew
