### ISSUE TITLE
@ngrx/effects: Using a function to handle error in observable stream breaks typing

### ISSUE THREAD

**Issue by blackholegalaxy** [ngrx/platform#3363]
### Minimal reproduction of the bug/regression with instructions

https://stackblitz.com/edit/ngrx-seed-8b1zsk?file=src%2Fapp%2Feffects%2Fcounter.effect.ts

As you can see the typing is crazy when we use a method to render the catchError block. Writing directly the catchError block seems to write just fine.

Please note the usage of such method worked a long time ago when using @effect() decorator since it was somehow type lazy.

### Expected

We expect to be able to use a generic method to return catchError handlers (so we can reuse it accross several effects with similar exepected error action dispatch).

Maybe we are just ignorant on how to type this properly and avoid using TypedAction (which is not exported except in src) like this:

```
catchError((error: any): Observable<TypedAction<any> & any> => of(anyErrorAction({ error })));
```

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

@ngrx/effects > 7 as far as I could see
All browsers
All os

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by david-shortman** [comment]
This is an error caused by Typescript failing to correctly contextually infer one of the generic types of `catchError`. It does not relate to the implementation of effects.

This error can be replicated using only rxjs: https://codesandbox.io/s/broken-star-z4l859?file=/src/index.ts

**Comment by markostanimirovic** [comment]
Thanks @david-shortman!

@blackholegalaxy

To make the `handleError` method strongly typed, you can do the following:

```ts
private handleError<T>() {
  return catchError<T, Observable<ReturnType<typeof counterError>>>(
    () => of(counterError())
  );
}
```

**Comment by blackholegalaxy** [comment]
Thanks that should do the trick. Thanks for your help to you both.
