### ISSUE TITLE
@ngrx/component: fix typo in `PushPipe` docs

### ISSUE THREAD

**Issue by markostanimirovic** [ngrx/platform#3374]
### Information

"render_creator" should be replaced with "render" in the `PushPipe` description: [L30](https://github.com/ngrx/platform/blob/master/modules/component/src/push/push.pipe.ts#L30), [L39](https://github.com/ngrx/platform/blob/master/modules/component/src/push/push.pipe.ts#L39)

### Documentation page

https://ngrx.io/api/component/PushPipe#description

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by edytatar** [comment]
Can I pick this up?

**Comment by timdeschryver** [comment]
Go for it @edytatar

**Comment by edytatar** [comment]
@timdeschryver I have submitted a pull request.
