### ISSUE TITLE
How to handle web socket messages?

### ISSUE THREAD

**Issue by SebastianSchenk** [ngrx/platform#338]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[X] Support request
</code></pre>

The documentation says about effects:
> Provide new sources of actions to reduce state based on external interactions such as network requests, web socket messages and time-based events.

Now I'm wondering if this is really the best approach. Wouldn't it be enough to just listen for a web socket event and than just dispatch an action directly to the store? Why would I need an effect for that?

Maybe you could add some example in the documentation or example app, how to properly use ngrx with web sockets?

Thanks a lot!

**Comment by brandonroberts** [comment]
That's what effects do so you don't have to manually subscribe and dispatch events from the websocket. I believe @avatsaev was working on an example of using websockets with ngrx here https://github.com/avatsaev/angular-ngrx-socket-frontend
