### ISSUE TITLE
use `schematicCollections` instead of `defaultCollection`

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#3383]
### Information

In Angular 14, the `defaultCollection` is deprecated in favor of `schematicCollections`, which supports an array of schematics (instead of a single one).
We should update the NgRx schematics to add the ngrx schematics to the collection, instead of overwriting the `defaultCollection` option. 

See https://github.com/angular/angular-cli/pull/22860 for more info.

The code that does this is located at https://github.com/ngrx/platform/blob/master/modules/schematics/src/ng-add/index.ts.

### Describe any alternatives/workarounds you're currently using

If you want to pick this issue up, please add a comment below :)  

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by suke** [comment]
May I work on this issue?

**Comment by markostanimirovic** [comment]
@suke Sure!

**Comment by suke** [comment]
OK! I will work on it when Angular v14 is released!

**Comment by timdeschryver** [comment]
@suke We've updated the repo to use Angular 14, feel free to work on this.

**Comment by suke** [comment]
@timdeschryver I would like to discuss a specification.
Should I remove the properties in schema.json and automatically add  ngrx schematics  to the schematicCollections?

https://github.com/ngrx/platform/blob/master/modules/schematics/src/ng-add/schema.json#L6

**Comment by timdeschryver** [comment]
Yes, that's a good idea!
I think we could also log an error if `schematicCollections` is not defined within the workspace.

**Comment by suke** [comment]
> Yes, that's a good idea! I think we could also log an error if `schematicCollections` is not defined within the workspace.

If `schematicCollections ` is not defined, I can create them automatically, but would you prefer to log an error?

**Comment by timdeschryver** [comment]
I think throwing would be better, it probably means that the user didn't upgrade Angular.

**Comment by suke** [comment]
I understand.
I'll make it a spec to throw exception!
