### ISSUE TITLE
ComponentStore effect without parameters

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#3384]
### Information

A question that I frequently see on various channels, is how to implement an effect without parameters.
Because this seems to be the number one question, I propose to add an example to the docs.

### Documentation page

https://ngrx.io/guide/component-store/effect

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by LayZeeDK** [comment]
Building on the existing documentation example here. Might not be 100% accurate as I'm writing the code from memory.

# Using pipe
```ts
import { ComponentStore, tapResponse } from '@ngrx/component-store';
import { pipe, switchMap } from 'rxjs';

import { Movie } from './movie';
import { MoviesService } from './movies.service';

interface MoviesState {
  readonly movies: readonly Movie[];
}

@Injectable()
export class MoviesStore extends ComponentStore<MoviesState> {
  movies$: Observable<readonly Movie[]> = this.select(state => state.movies);

  constructor() {
    super(initialState);
    // Preload all movies
    this.#getAllMovies();
  }

  #getAllMovies = this.effect<void>(
    // Standalone observable chain. An Observable<void> will be attached by ComponentStore.
    pipe(
      switchMap(() => this.moviesService.fetchAllMovies().pipe(
        tapResponse(
          movies => this.#replaceMovies(movies),
          (error: HttpErrorResponse) => this.logError(error),
        )
      )
    )
  );
  
  #replaceMovies = this.updater<readonly Movie[]>((state, movies): MoviesState => ({
    ...state,
    movies,
  }));
}

const initialState: MoviesState = {
  movies: [],
};
```

# Using trigger$
```ts
import { ComponentStore, tapResponse } from '@ngrx/component-store';
import { pipe, switchMap } from 'rxjs';

import { Movie } from './movie';
import { MoviesService } from './movies.service';

interface MoviesState {
  readonly movies: readonly Movie[];
}

@Injectable()
export class MoviesStore extends ComponentStore<MoviesState> {
  movies$: Observable<readonly Movie[]> = this.select(state => state.movies);

  constructor() {
    super(initialState);
    // Preload all movies
    this.#getAllMovies();
  }

  #getAllMovies = this.effect<void>(
    // Can be named whatever. The name doesn't matter.
    trigger$ => trigger$.pipe(
      switchMap(() => this.moviesService.fetchAllMovies().pipe(
        tapResponse(
          movies => this.#replaceMovies(movies),
          (error: HttpErrorResponse) => this.logError(error),
        )
      )
    )
  );
  
  #replaceMovies = this.updater<readonly Movie[]>((state, movies): MoviesState => ({
    ...state,
    movies,
  }));
}

const initialState: MoviesState = {
  movies: [],
};
```

Credits to @nartc for the standalone `pipe` technique.

**Comment by LayZeeDK** [comment]
See [RFC: Add "ngrxOnInitStore" lifecycle method to ComponentStore (#3335)](https://github.com/ngrx/platform/discussions/3335) for a library hook proposal.

**Comment by LayZeeDK** [comment]
@timdeschryver I suggest you mention ComponentStore in the title of this issue to avoid confusion with NgRx Effects.

**Comment by e-oz** [comment]
I use this for effects without params:
```ts
someEffect$ = this.effect(_ => _.pipe(
```
and this for effects with params:
```ts
someEffect$ = this.effect<SomeType>(_ => _.pipe(
```

## Full examples

#### Without params:
```ts
  readonly createClass$ = this.effect(_ => _.pipe(
    withLatestFrom(this.select(s => s.model)),
    tap(([_, model]) => {
      // ... some code
    })
  ));
```
call:
```ts
  addClass() {
    this.store.createClass$();
  }
```

#### With param:
```ts
  readonly removeAttr$ = this.effect<string>(_ => _.pipe(
    withLatestFrom(this.editorStore.select(s => s.classForm)),
    exhaustMap(([attrKey, classForm]) => {
      //... some code
    })
  ));
```
call:
```ts
  removeAttr(attrKey: string) {
    this.store.removeAttr$(attrKey);
  }
```

**Comment by timdeschryver** [comment]
Thanks for summing up all the different ways @LayZeeDK and @e-oz .
Instead of mentioning all of them, I think that we should try to standardize one of these.
Does one of these have a clear benefit over the others, or is this more a matter of preference?

As a side note, I don't think the new hook will create a new technique, but it introduces a way to do something (in most of the cases invoke an effect with or without params) when the store and state are initialized.

**Comment by LayZeeDK** [comment]
> Instead of mentioning all of them, I think that we should try to standardize one of these.
> Does one of these have a clear benefit over the others, or is this more a matter of preference?

Personally, I see the biggest potential in the standalone pipe technique since it is extractable to a separate constant or ES module (file) which allows us to test the observable chain in isolation.

The standalone pipe also supports the point-free style, removing the need for an intermediary variable with an arbitrary name (`trigger$`/`source$`/`whatever$`).

**Comment by spierala** [comment]
I have a related question: Is the generic type for `effect` always required? 
Effects without parameters require then the generic type `void`?

I made a small example here: https://stackblitz.com/edit/angular-ivy-jsnxmn?file=src%2Fapp%2Fstate.service.ts

The typings of effect (https://github.com/ngrx/platform/blob/13.1.0/modules/component-store/src/component-store.ts#L279) give the impression that `void` should be the default... I do not understand why we have to write explicitly `effect<void>`.

Also the docs do not use a generic type for `effect`: https://ngrx.io/guide/component-store/effect
Although it seems to be required.

**Comment by LayZeeDK** [comment]
> I think the trigger$/source$ is the most natural way. Also, that approach is used in the docs already.

The standalone pipe technique additionally works well for parameterized effects. I agree that consistency is worth considering but maybe the current suggestion is not *the best*.

> Also the standalone pipe is not even needed if there is only one operator inside the pipe.

That's an interesting point. But how is it different than having `trigger$.pipe(singleOperation())`? `trigger$` isn't needed at all for most effects yet `.pipe` is also needed even for a single operation when using `trigger$`.

**Comment by LayZeeDK** [comment]
> I have a related question: Is the generic type for `effect` always required? Effects without parameters require then the generic type `void`?

If we leave out the generic, the default parameter type is `unknown`.

**Comment by nartc** [comment]
> The typings of effect (https://github.com/ngrx/platform/blob/13.1.0/modules/component-store/src/component-store.ts#L279) give the impression that void should be the default... I do not understand why we have to write explicitly effect<void>. 
> Also the docs do not use a generic type for effect: https://ngrx.io/guide/component-store/effect

If you use `trigger$`, then the type is inferred from the type of `trigger$`

```ts
this.effect((movieId$: Observable<string>) => movieId$.pipe());
```

Not sure why NgRx folks go with the route of typing with `Observable` rather than using the Generic. Using generic does not require you to import `Observable` symbol as well as faster/shorter to type.

With the standalone-pipe, there is nothing to infer so the Generic is required.

**Comment by LayZeeDK** [comment]
> you could do something like this with a single operation (e.g. mergeMap):

To me, `this.effect(mergeMap(v => doSomeStuff))` is closer to `this.effect(pipe(mergeMap(v => doSomeStuff)))` than `this.effect(trigger$ => trigger$.pipe(mergeMap(v => doSomeStuff)))`.

> In the last example the standalone pipe is useless, cause there is only one operator passed to the pipe.

Except for leaving room for additional operations, both `trigger$.pipe` and `pipe` are useless for single operations.

**Comment by timdeschryver** [comment]
I agree with @LayZeeDK.

The most common variant that I've used and seen is the snippet using the variable, e.g. `trigger$` in combination with a `pipe` to execute an effect.
I think that if you're familiar with the syntax, you can use just `pipe` or `xMap`, but the friendliest one is the one using `source$.pipe`.

```
  getAllMovies = this.effect<void>(
    // Can be named whatever, for example source$. The name doesn't matter.
    trigger$ => trigger$.pipe(
      switchMap(() => this.moviesService.fetchAllMovies().pipe(
        tapResponse(
          movies => this.#replaceMovies(movies),
          (error: unknown) => this.logError(error),
        )
      )
    )
  );
```

I'm ok with using a similar snippet like the one that was used to illustrate an example.

Thoughts?

**Comment by alvipeo** [comment]
This thread deserves a BLOG POST!

**Comment by tomalaforge** [comment]
@alvipeo I think I will write a blog post for this. I was thinking about it. 

@timdeschryver I can take that one. Are we going with the trigger$ => trigger$ ? 

Or we can maybe write two kind of solutions. I'm always using the standalone one which doesn't need to introduce a random name. But I get why people prefer the trigger$ one, it looks more like the rxjs pipe mental model.

**Comment by e-oz** [comment]
@tomalaforge without trigger$ you can't call an effect without params - TS complaints.

**Comment by tomalaforge** [comment]
@e-oz yes you can 

```typescript
  readonly updateTrackerContext = this.effect<number>(
    pipe(
      switchMap((trackerId) =>
        this.http.getTrackerContexts(trackerId).pipe(
          tapResponse(
            (contexts) => this.patchState({ contexts }),
            () => this.patchState({ contexts: undefined })
          )
        )
      )
    )
  );
```

**Comment by e-oz** [comment]
now try to call store.updateTrackerContent();

**Comment by timdeschryver** [comment]
Using `trigger$` is good for me @tomalaforge

**Comment by tomalaforge** [comment]
@timdeschryver can you assign me this Issue ?
