### ISSUE TITLE
Please un-deprecate `createFeatureSelector<GlobalState, SubState>()`

### ISSUE THREAD

**Issue by sod** [ngrx/platform#3385]
### Information

PR https://github.com/ngrx/platform/issues/3179 deprecated `createFeatureSelector<State, State['foo']>` and says to use `createFeatureSelector<State['foo']>` instead. But that breaks the typecheck between `Store` & selector. Then the generic on Store is kinda useless, as selectors aren't checking it anymore.

Given this example:

```ts
export interface State {
    foo: { name: string }
}

export const selectFoo = createFeatureSelector<State, State['foo']>('foo');
export const selectFooName = createSelector(selectFoo, (foo) => foo.name);

export class MyService {
    fooName$ = this.store.select(selectFooName);

    constructor(private store: Store<State>) {}
}
```

With `createFeatureSelector<State, State['foo']>('foo')` (deprecated in https://github.com/ngrx/platform/issues/3179), typescript validates if your `Store<State>` operates on the same store as your selector `selectFooName`. But with `createFeatureSelector<State['foo']>('foo')`, you can write `Store<{}>` and the selector wont complain, as there is no checking at all going on now.

I'm pretty sure PR https://github.com/ngrx/platform/issues/3179 was done out of frustration, given this sentence:
> because it's causing type issues with Store

to get a selector error going away. I guess whatever error @timdeschryver had, It could have been fixed without a change to ngrx and by doing this instead:

```ts
// replace this:
export const selectFoo = createFeatureSelector<State, State['foo']>('foo');

// with this:
export const selectFoo = createFeatureSelector<Pick<State, 'foo'>, State['foo']>('foo');
//                                             ^^^^^^^^^^^^^^^^^^
```

Use `Pick<State, 'foo'>`, to pick `foo` from the global `State`, so your selector wont ever ask your `Store<... Whatever ...>` to have the global `State` in its entirety, but instead only operate on the router key. This way you don't tie your selectors to the global state, but only on the subset they actually access.

### Describe any alternatives/workarounds you're currently using

Well, it was just `@deprecated`, but I fear the day it gets removed :(

### I would be willing to submit a PR to fix this issue

I'd remove the `@deprecated` on `createFeatureSelector<State, State['foo']>` and change all examples like:
```diff
- createFeatureSelector<State, State['foo']>('foo')
+ createFeatureSelector<Pick<State, 'foo'>, State['foo']>('foo')
```

To avoid frustration

**Comment by sod** [comment]
Optionally could also bake the `Pick` into the method signature to avoid more boilerplate, like this `selectKey` method:

```typescript
export function selectKey<STATE extends object, KEY extends keyof STATE>(key: KEY): 
    MemoizedSelector<Pick<STATE, KEY>, STATE[KEY]> {
    return /* replace with actual memoized implementation: */ ((state: Pick<STATE, KEY>): STATE[KEY] => state[key]) as any;
}

export const selectFoo = selectFoo<State, 'foo'>('foo');
```

**Comment by brandonroberts** [comment]
Thanks, @sod, but we think it's better to let the types flow through the createSelector without the additional root state than to type the Store with a generic, the generic exists for backward compatibility with existing apps.

**Comment by sod** [comment]
Will deprecate the generic on `Store<Generic>` as well? Or does that stay?

**Comment by sod** [comment]
If you think I talk nonsense, nvm mind then. Seems I'm incapable of explaining what my issue is. We just gonna override the types for us. Thank you for replying so fast 👍 .

**Comment by jon-armen** [comment]
@sod , I'm a little late to this discussion, but I understand your point.  I too was recently frustrated tracking down bugs caused by not strongly typing the root state.

**Comment by vectorjohn** [comment]
Same. The deprecation seems like a regression. It makes the selectors work over any type that definitely doesn't have the feature you're looking for and it'll just happily compile and run, then fail at runtime. 
Is there some way of using selectors that gets around this problem? I just don't understand the reasoning for the deprecation in the first place.
