### ISSUE TITLE
Effects: Add example of effects without actions

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#3387]
### Information

We have a note in the docs about how effects support observable streams other than an observable of actions. We should add a more concrete example to the docs like using router events observable, observable browser events, and more.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by banderberg** [comment]
Can you provide an example?  I read @timdeschryver 's [article](https://timdeschryver.dev/blog/start-using-ngrx-effects-for-this#external-sources) and the syntax does not work for me.  I get an error "function(): Observable<number>
Argument of type '() => Observable<number>' is not assignable to parameter of type '() => EffectResult<Action>'."

**Comment by Armenvardanyan95** [comment]
I can take this one, do you think this needs to go into the Effects doc itself?

**Comment by Armenvardanyan95** [comment]
Submitted a PR for this: #3408
