### ISSUE TITLE
[NGRX.IO] Style guide page not working/mpty

### ISSUE THREAD

**Issue by Marcel0024** [ngrx/platform#3388]
### Information

https://ngrx.io/guide/style-guide page has an empty response.

![image](https://user-images.githubusercontent.com/14852157/165086737-4d27fc81-3562-4da1-a44e-c5424592a953.png)

No errors in console screen or requests as far as i could see.

### Documentation page

https://ngrx.io/guide/style-guide

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by timdeschryver** [comment]
That empty page is normal, because there is [no content](https://github.com/ngrx/platform/blob/master/projects/ngrx.io/content/guide/style-guide.md) yet.

Was there a link in the docs that pointed to that page?
