### ISSUE TITLE
queryParams is fired twice (before component is destroyed)

### ISSUE THREAD

**Issue by sonukapoor** [ngrx/platform#3392]
### Minimal reproduction of the bug/regression with instructions

I have noticed that `queryParams` fires twice, once it receives an emission and the second time before the component is destroyed. 

Here is a reproducible to see the issue. 
https://stackblitz.com/edit/angular-ivy-2qhdju?file=src%2Fapp%2Fapp.module.ts

- The App component contains two router links. 
- One point to `foo` and the other points to `bar` with a query string.
- Click on the foo link you should see `foo component {}`
- Click on the bar link and you will see `foo component {a: "bar"}` and `FooComponent is destroyed`.

### Minimal reproduction of the bug/regression with instructions

The expectation is to not see the secondary `foo component {a: "bar"}`. When using the `ActivatedRoute` this does not happen. It only emits once. I have tried to use `NavigationActionTiming`, but that also causes two emissions (the console output is in reverse order), when routing from `bar` to `foo`.   

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

"@angular/animations": "^13.2.0",
"@angular/common": "^13.2.0",
"@angular/compiler": "^13.2.0",
"@angular/core": "^13.2.0",
"@angular/forms": "^13.2.0",
"@angular/platform-browser": "^13.2.0",
"@angular/platform-browser-dynamic": "^13.2.0",
"@angular/router": "^13.2.0",
"@ngrx/effects": "^13.1.0",
"@ngrx/router-store": "^13.1.0",
"@ngrx/store": "13.1.0",

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by timdeschryver** [comment]
This is the way it's intended to work.
For example, you need this information while using a selector in a guard.
As a workaround, you shouldn't manually subscribe to the selector in the constructor.
Instead, refactor the code so the selector is being subscribed to in the template (with the `async` pipe).

**Comment by sonukapoor** [comment]
@timdeschryver, what if I need to subscribe to do something else (like make an api call or open a modal)? I don't need the data in my template.

**Comment by timdeschryver** [comment]
It also works if you subscribe to the stream inside the `ngOnInit` hook.
