### ISSUE TITLE
Add a refCount config flag to select in component store

### ISSUE THREAD

**Issue by Harpush** [ngrx/platform#3393]
### Information

Currently component store select method always pass to `shareReplay` the flag `refCount` as true. That means that any async pipe to a selector inside ngIf will reevaluate the selector projector.
A specialized memoize can be implemented or even setting `refCount` to false by default (There is take until destroy so what's the point having it as true?).

### Describe any alternatives/workarounds you're currently using

Add a custom `shareReplay(1)` at the end of the selector.

### I would be willing to submit a PR to fix this issue

- [x] Yes
- [ ] No

**Comment by Harpush** [comment]
@alex-okrushko @brandonroberts Another possible solution (and maybe even with better performance) is introducing the same projector memoization from ngrx store createSelector to component store selectors. That way refCount as false become irrelevant.

**Comment by Harpush** [comment]
Any news concerning this?

**Comment by timdeschryver** [comment]
This feature is not planned at the moment, we can revisit this in the future.
