### ISSUE TITLE
 routerReducer should update the store on ROUTER_NAVIGATED action

### ISSUE THREAD

**Issue by ashwanikmar** [ngrx/platform#3400]
### Information

I think  routerReducer should update the store on ROUTER_NAVIGATED action as well. Because we can not get data from resolve guard.

Although, I can change the time of ROUTER_NAVIGATION action and after this, I can get data from the angular guard.

```
StoreRouterConnectingModule.forRoot({
  [navigationActionTiming](https://ngrx.io/api/router-store/StoreRouterConfig#navigationActionTiming): 
  [NavigationActionTiming.PostActivation](https://ngrx.io/api/router-store/NavigationActionTiming#PostActivation),
});
```
But, then I can not get transition from  ROUTER_NAVIGATION to ROUTER_NAVIGATED 

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by timdeschryver** [comment]
Hi @ashwanikmar what are you trying to do?
Without knowing a lot of your use case, I would argue that within an NgRx example you don't need the resolved data, instead you would store the data in the store, and read the stored state in the component.

**Comment by brandonroberts** [comment]
I agree with @timdeschryver on this about resolved data. Resolvers are render-blocking and should be used sparingly in my opinion.
