### ISSUE TITLE
your website doesn't navigate in chrome, brave

### ISSUE THREAD

**Issue by Coopersamjohn** [ngrx/platform#3404]
### Minimal reproduction of the bug/regression with instructions

Just go to the site and try to navigate. It will sometimes navigate but then return to home when clicking something else in the menu.

### Minimal reproduction of the bug/regression with instructions

actually navigating like a website should

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

Chrome, Brave

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by Coopersamjohn** [comment]
Its working today.

**Comment by timdeschryver** [comment]
Thanks for opening this issue @Coopersamjohn , it seems like this was an issue on Netlify's side.
https://www.netlifystatus.com/
