### ISSUE TITLE
add Docs for @ngrx-store  add payload in state

### ISSUE THREAD

**Issue by bobwatcherx** [ngrx/platform#3414]
### Information

I can't find a way to add a payload so that the initial state is added to the payload

example initial state= 5

this.store.dispatch({payload:2})

the state should now be 7

and other examples
initial state = "school"

payload = "new"
become now a "school new"

### Documentation page

https://ngrx.io/guide/store

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [X] No

**Comment by brandonroberts** [comment]
Action creators are the primary way to dispatch actions, with props used to define additional metadata. We don't encourage using a payload property

https://ngrx.io/guide/store/actions
