### ISSUE TITLE
@ngrx-store work on chrome , but not work in firefox

### ISSUE THREAD

**Issue by bobwatcherx** [ngrx/platform#3415]
### Minimal reproduction of the bug/regression with instructions

I tried this state management in chrome and it worked and I tried it on another browser, namely firefox, but when the dispatch function on the button is called, the value doesn't change

### Minimal reproduction of the bug/regression with instructions

I tried this state management in chrome and it worked and I tried it on another browser, namely firefox, but when the dispatch function on the button is called, the value doesn't change

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

  "@ngrx/devtools": "^1.4.0",
    "@ngrx/store": "^13.2.0",
    "@ngrx/store-devtools": "^13.2.0",

 "@angular/core": "~13.3.0",

OS:Arch linux
browser: chromium WORK , NOT WORK in firefox 99.0.1

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [X] No

**Comment by brandonroberts** [comment]
The `@ngrx/devtools` should not be used with the latest 13.x NgRx package. Also, try in incognito mode to see if you have any other extensions that may be causing an issue.
