### ISSUE TITLE
Docs: update example dependencies to latest Angular version

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#3419]
### Information

Docs: Update example dependencies to latest Angular version 14 release

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by cedricduffournet** [comment]
@timdeschryver I can work on this one

**Comment by timdeschryver** [comment]
@cedricduffournet thanks! I think we first need to upgrade the main packages first, when that's done I'll ping you here.

**Comment by brandonroberts** [comment]
@cedricduffournet the main packages are updated

**Comment by cedricduffournet** [comment]
@brandonroberts did the `14.0.0-beta.0` has been released ?

**Comment by cedricduffournet** [comment]
@timdeschryver so I think I have to wait for the release to update dependencies ?
