### ISSUE TITLE
store-devtools doesn't work when inspecting remote target 

### ISSUE THREAD

**Issue by NoNameProvided** [ngrx/platform#342]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## What is the current behavior?
Redux Devtools works with ngrx when running an app in browser, but doesn't work when trying 
 to debug on a remote device.

## Expected behavior:
Redux Devtools and @ngrx/store-devtools works the same way for remote debugging targets as for in-browser pages.

## Minimal reproduction of the problem with instructions:
1. Create a new ionic project
1. Install ngrx and the devtools
1. Configure it like
    ```ts
    StoreModule.forRoot(reducers()),
    StoreDevtoolsModule.instrument({ maxAge: 30 }),
    ```
1. Open the app in the browser with `ionic serve` and validate that the instance is selected
1. Run the app on a device with `ionic run android` and see that no instance is available

## Version of affected browser(s),operating system(s), npm, node and ngrx:

@ngrx/core: 1.2.0
@ngrx/store: "4.0.2
@ngrx/store-devtools: 4.0.0
Chrome: latest
NPM: 5.3.0
Node: v8.3.0
OS: MacOS Sierra 10.12.6

## Other information:

N/A

**Comment by brandonroberts** [comment]
There is a workaround for this issue from the 2.x version of store-devtools. https://github.com/ngrx/store-devtools/issues/36
