### ISSUE TITLE
Installation docs

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#3434]
### Information

All of the docs have installation instructions for `npm`, `yarn`, and `ng add`.
Currently, `ng-add` is added lastly and we have the following guide for it:

```md
If your project is using the Angular CLI 6+ then you can install 
the plugin to your project with the following `ng add` command
```

I would propose to move `ng-add` to the top because some `ng add` commands have some useful stuff included, and it's also a common command now. We can also rephrase the text, for example we can remove "If your project is using the Angular CLI 6+".

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by mauromattos00** [comment]
Hi @timdeschryver, I can work on this one if it's ok. 😀

**Comment by timdeschryver** [comment]
@mauromattos00 , I would like to hear @markostanimirovic and/or @brandonroberts opinion too before making this change 😅

**Comment by brandonroberts** [comment]
I think it's a good change 👍🏿

**Comment by timdeschryver** [comment]
@mauromattos00 there you go 😉
Feel free to take this.

**Comment by mauromattos00** [comment]
Also, would it be a good tweak to show the optional flags for `ng add` in a table?
I thought about something similar to the Angular docs.

What do you think @brandonroberts @timdeschryver @markostanimirovic?

![image](https://user-images.githubusercontent.com/13375865/170778620-4bf0267d-5923-48e6-a5dc-e71d171fb9e6.png)

### Angular docs

![image](https://user-images.githubusercontent.com/13375865/170778411-c416b61c-86a8-4a2c-a2cb-ddce55a9980e.png)

**Comment by brandonroberts** [comment]
Also a great idea 😄
