### ISSUE TITLE
Migrate `data-example-app` project to Angular strict mode

### ISSUE THREAD

**Issue by markostanimirovic** [ngrx/platform#3445]
1. Add `angularCompilerOptions` to `projects/data-example-app/tsconfig.app.json`:

```json
"angularCompilerOptions": {
  "strictTemplates": true,
  "strictInjectionParameters": true,
  "strictInputAccessModifiers": true
}
```

2. Fix compilation error in `projects/data-example-app/src/board/board.component.html`.

**Comment by mauromattos00** [comment]
Hi @markostanimirovic! Can I work on this?
