### ISSUE TITLE
component-store: Allow passing any selector (observable) to the get function

### ISSUE THREAD

**Issue by Harpush** [ngrx/platform#3459]
### Information

Currently component store `select` has two overloads - one for direct state select and second to combine selectors. Those selectors are memoized.
On the other hand - the `get` function only accepts a function for direct state select. The feature request is allowing passing a selector to it.
For example:
A selector I have:
```ts
public readonly test$ = this.select(state => state.items.map(item => item.id));
```
If I wanted the same result in `get` I would need to write the logic again and it will be calculated again and again:
```ts
this.get(state => state.items.map(item => item.id));
```
If I could pass a selector to `get` it would share the memoization and let me reuse the selector logic. It will even allow me to get any combined selector snapshot:
```ts
this.get(this.test$);
```

### Describe any alternatives/workarounds you're currently using

Writing a custom `get` function for this case... pretty straightforward. 

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Thanks @Harpush. The `get` function is meant to be a single-purpose snapshot of the state. I wouldn't recommend using snapshots of the state as a common practice. The `get` method is more for convenience internally to the component store.

**Comment by Harpush** [comment]
I agree. It's just that we sometimes need access to a selector result as snapshot and not just the state itself. Currently it will require to rewrite the selector logic. I never meant for it to be outside the component store.
