### ISSUE TITLE
New module to persist some part of the store - @ngrx/persistence

### ISSUE THREAD

**Issue by un33k** [ngrx/platform#346]
<pre><code>
[x ] Feature request
</code></pre>

## What is the current behavior?
To persist some part of the store, we can use an external module called [ngrx-store-localstorage](https://github.com/btroncone/ngrx-store-localstorage).

## Expected behavior:
Creating a new **@ngrx/persistence**.  Or perhaps moving in [ngrx-store-localstorage](https://github.com/btroncone/ngrx-store-localstorage) to **@ngrx/persistence**.

**Comment by brandonroberts** [comment]
Closing for now. `ngrx-store-localstorage` is still being actively maintained as serves as viable option.

**Comment by un33k** [comment]
@brandonroberts `actively maintained` is a relative term.  Ngrx provides 99% of what is required fantastically, add the last 1% as well if possible. Try to take 5.0.0-alpha.0 for a spin, & `ngrx-store-localstorage` insisted on 4.1.1.

**Comment by aasmm7x** [comment]
+1 to this be added to the ngrx project.

**Comment by Alexisvt** [comment]
+1 I think the same way! Persist is definitely something that We expect from ngrx out the box, some us are prohibited to add many third party libraries in projects.

**Comment by un33k** [comment]
@Alexisvt have a look at [ngxs](https://github.com/ngxs/store/tree/master/packages/storage-plugin) as an alternative.

**Comment by brandonroberts** [comment]
@siva636 This project is also still being actively maintained for free by developers in their free time.  I'm glad you found NGXS to be an easier alternative that fits your needs.

👍🏿
