### ISSUE TITLE
Incorrect reducer test result

### ISSUE THREAD

**Issue by rybsonPL** [ngrx/platform#3471]
### Information

In line 34 instead of ` expect(state).not.toBe(newState);` it should be ` expect(state).not.toBe(initialState);`

### Documentation page

https://ngrx.io/guide/store/testing#testing-reducers

### I would be willing to submit a PR to fix this issue

- [x] Yes
- [ ] No

**Comment by timdeschryver** [comment]
Hi @rybsonPL thanks for raising this issue.
You're right, and I would even suggest to remove that expectation.
Do you want to create a Pull Request for this?

**Comment by rybsonPL** [comment]
@timdeschryver  I will.

**Comment by rybsonPL** [comment]
Problem solved. https://github.com/ngrx/platform/pull/3474
