### ISSUE TITLE
adapter.getInitialState() - offer selectors for custom EntityState properties

### ISSUE THREAD

**Issue by moniuch** [ngrx/platform#3481]
### Information

I have just double-checked on Stackblitz with `@ngrx/entity@14.0.1` and seems like the following is a missing and valid feature to ask for. 

```ts
export const initialState: State = adapter.getInitialState({
  error: ''
});

export const {
  selectIds,
  selectEntities,
  selectAll,
  selectTotal,
  selectE|    // <-- could offer selectError
} = adapter.getSelectors();
```

Stackblitz screenshot:

![image 2022-07-08 20-41-09](https://user-images.githubusercontent.com/681956/178051609-a50b48a7-e4de-4e90-9c92-bd01e34f2c4a.png)

I assume it is also possible to infer and feed to template literals, as you guys doing TS magic ❤️ 

### Describe any alternatives/workarounds you're currently using

The only one that seems valid is to make a selector manually in a traditional way, and add it to export statement. The B-word.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by markostanimirovic** [comment]
Hi @moniuch,

You can use the `createFeature` function to get selectors for feature state properties. Together with `@ngrx/entity`, its usage would look like this:

```ts
// authors.reducer.ts

interface State extends EntityState<Author> {
  query: string;
  isLoading: boolean;
}

const adapter = createEntityAdapter<Author>();

const initialState: State = adapter.getInitialState({
  query: '',
  isLoading: false,
});

const reducer = createReducer(
  initialState,
  on(/* ... */),
  on(/* ... */)
);

const feature = createFeature({ name: 'authors', reducer });
const { selectAll, selectTotal } = adapter.getSelectors(feature.selectAuthorsState);

export const authorsFeature = { ...feature, selectAll, selectTotal };
```

---

```ts
import { authorsFeature } from './authors.reducer.ts';

const {
  selectAuthorsState,
  selectIds,
  selectEntities,
  selectAll,
  selectTotal,
  selectQuery,
  selectIsLoading,
} = authorsFeature;
```

**Comment by moniuch** [comment]
@markostanimirovic Thank you very much for providing such an elaborate answer! In fact I completely forgot about `createFeature`. Appreciated!
