### ISSUE TITLE
component-store: Add immutability check to updater

### ISSUE THREAD

**Issue by Harpush** [ngrx/platform#3486]
### Information

Ngrx store allows enforcing immutability in reducers by freezing the state after each reducer update in dev mode. This way you can't accidently mutate the state.

Component store updater is intended to be a reducer case (written in documentation) thus mutating is not intended. By adding the same freeze state in component store in dev mode this can be enforced.

In ngrx store there is a module to configure that. In component store it could be either as an optional constructor parameter or with global provider (will be accessed with the inject function to avoid passing it from services extending component store).

Only open question is where to freeze and whether setState and patchState are relevant too.

### Describe any alternatives/workarounds you're currently using

Either just remember to do it yourself with no runtime help or wrap updater with a custom method that does it.

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by Harpush** [comment]
Any news concerning this? Would help a lot.

**Comment by brandonroberts** [comment]
This feature is not planned at the moment

**Comment by timdeschryver** [comment]
Because it's not planned I'm closing this for now.
We can revisit this later.
