### ISSUE TITLE
Add extra source to the actions that wont affect the type

### ISSUE THREAD

**Issue by MotassemJa** [ngrx/platform#3501]
### Information

One rule of the good action hygine is not to reuse actions. The reason for this is clear, when we reuse actions, we wont be able to detect the source of this action, which makes debugging really harder.

However, there are some scenarios in which reusing actions is the cleanest approch (in my opinion). For example consider the following two cases:

**1. Handling api errors in a centralized effect.**
Currently, we handle failed api requests in the effects with the catchError operator, which returns a failure action, let's say: `UpdateUserFailure`.
To show an alert on each failed request, we need to either explicitly dispatch a `showAlert` action on each failure, or we should add all of the failure actions to the `ofType` section of the centralized error effect.
Both workarounds will break the good action hygine recommendations.

**2. Showing a global progress bar**
Let's say I want to show a progress bar to indicate that we have a long running task in the background (not only http requests). It would be much easier if we could dispatch an action before we start a certain effect, namely `showProgressBar`, and once the task has finished, we dispatch a `hideProgressBar` action.
This also breaks the good action hygine rule and makes debugging much harder.

### Describe any alternatives/workarounds you're currently using

What I would like to suggest is to add an optional parameter to both `createAction` and `dispatch` methods, where we can add some info the the actions, that wont affect the action type, but will be added when we check to inspector logs.

`this.store.dispatch(showAlert(), 'UpdateUserFailed');`

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Thanks @MotassemJa. We aren't looking to add additional data to actions as they are. You can wrap action creators and the dispatch to do this in userland code.

**Comment by eggbeard** [comment]
You might find this article useful:

https://indepth.dev/posts/1407/force-good-action-hygiene-and-write-less-actions-in-ngrx-with-the-prepared-events-pattern

**Comment by david-shortman** [comment]
Consider reacting to metadata in actions for common behavior like errors- https://dev.to/davidshortman/describe-your-ngrx-actions-more-to-write-less-code-1fij
