### ISSUE TITLE
Incorrect behavior of @ngrx/avoid-mapping-selectors lint rule

### ISSUE THREAD

**Issue by yurakhomitsky** [ngrx/platform#3511]
### Minimal reproduction of the bug/regression with instructions

![image](https://user-images.githubusercontent.com/54478076/182818233-5ea777af-5dc4-424d-82f8-5a9db4761e14.png)

### Minimal reproduction of the bug/regression with instructions

1. install ngrx-eslint-plugin: "@ngrx/eslint-plugin": "^14.0.2",
2. add to eslint config :			```extends: ['plugin:@ngrx/recommended'],```
3. Use this.store.select(selector).pipe(switchMap, map)
4. Note warning

Expected behavior there should not be a warning if there is an operator that changes the stream before the map

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

Ngrx: 13.1.0
Angular: 13.3.2
Node: 16.15.0

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by timdeschryver** [comment]
Could you elaborate this use case a bit more please?
In the snippet shown, the map that's giving the error isn't doing anything with the selector's result, so I would move it to the map  logic of the switchMap

**Comment by yurakhomitsky** [comment]
@timdeschryver, sorry for the lousy screenshot, here is another one.
In my case, the map logic could be moved to switchMap's map.

However what if the logic in the switchMap's map would be hard to read and I would want to  move  it to a separate `map`

I was thinking about whether it is possible to not show a warning if there is a switchMap/mergeMap before the map operator in the store selector pipe chain.

<img width="965" alt="image" src="https://user-images.githubusercontent.com/54478076/183087675-85f6ac5f-8529-499b-9446-290a39c3bffc.png">
