### ISSUE TITLE
Docs: Add page on createActionGroup

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#3514]
### Information

Add a documentation page explaining `createActionGroup` in NgRx Store and embed the YouTube video about it also.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by santoshyadavdev** [comment]
Can I take this.

**Comment by brandonroberts** [comment]
Check with @markostanimirovic to be sure he hasn't started it yet

**Comment by santoshyadavdev** [comment]
Cool @markostanimirovic let me know, if you are already doing it.

**Comment by markostanimirovic** [comment]
I haven't started it yet. You can take it @santoshyadavdev 🙂

**Comment by markostanimirovic** [comment]
Here is a list of resources that may be helpful for writing a page about `createActionGroup`:

- [API](https://ngrx.io/api/store/createActionGroup)
- [Creating Actions with NgRx Just Got Even Easier](https://youtu.be/rk83ZMqEDV4)
- [NgRx Action Group Creator](https://dev.to/ngrx/ngrx-action-group-creator-1deh)
- [The TypeScript Gluten Behind NgRx createActionGroup](https://liveloveapp.com/blog/2022-07-05-typescript-gluten-behind-ngrx-createactiongroup)

I'd put this page named "Action Groups" in the "Advanced" section of the `@ngrx/store` docs. We can also add a reference to this page on the [Actions](https://ngrx.io/guide/store/actions) page.
