### ISSUE TITLE
store-devtools trace tab not working

### ISSUE THREAD

**Issue by ogolan-ig** [ngrx/platform#3517]
### Information

hi, 
currently the trace tab displays the message: "To enable tracing action calls, you should set `trace` option to `true` for Redux DevTools enhancer. Refer to [this page](chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/window.html#) for more details"

i could not find any option like trace: boolean in the docs or typescript file. is there an option for tracing? if not will there be one in the future? im using angular v13.

thank you 

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by timdeschryver** [comment]
It must be added to our config [here](https://github.com/ngrx/platform/blob/master/modules/store-devtools/src/config.ts) and passed along to the devtools.

Feel free to create a PR for this.
