### ISSUE TITLE
createFeatureSelector' is deprecated

### ISSUE THREAD

**Issue by Felexonyango** [ngrx/platform#3520]
### Information
Hi am new to Ngrx an i have been trying to create A selector function only to realize that  CreateFeatureSelector is not working. Is there different ways to achieve this ? Thanks 

![Screenshot from 2022-08-09 13-03-12](https://user-images.githubusercontent.com/58067903/183622099-fe87cf83-d1d8-49dd-b54b-fb86813abbdf.png)

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by Felexonyango** [comment]
Any help on this

**Comment by timdeschryver** [comment]
Hi, we're trying to keep GitHub issues for bug reports and feature requests.
Support questions should be asked on the [NgRx Discord Server](https://discord.com/invite/ngrx), or on [stackoverflow (with a ngrx tag)](https://stackoverflow.com/questions/tagged/ngrx).


https://ngrx.io/guide/migration/v13#createfeatureselector
