### ISSUE TITLE
Remove `entryComponents` from example app

### ISSUE THREAD

**Issue by markostanimirovic** [ngrx/platform#3523]
### Information

`entryComponents` are not needed anymore and should be removed. In the example app, there is one use of `entryComponents` [here](https://github.com/ngrx/platform/blob/master/projects/example-app/src/app/auth/auth.module.ts#L36).

**Comment by mauromattos00** [comment]
I can do it if it's ok @markostanimirovic 🙂

**Comment by markostanimirovic** [comment]
Thank you @mauromattos00!
