### ISSUE TITLE
Store: Introduce Standalone API for NgRx Store

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#3526]
### Information

Introduce standalone APIs for registering the Store and pieces of state for the `@ngrx/store` package. This should allow developers to use Store in a "module-free" application.

Based on the discussion in #3399 we are looking at adding two new functions

`provideStore(reducerMap, rootConfig)` - Registers the root-level providers for the global Store, and initial setup
`provideState(reducerMap, featureConfig)` - Registers additional features in the global Store

Also under consideration of whether we should separate the runtime checks from the `provideStore()` function so they can be tree-shaken in production builds

```ts
providers: [
  provideStore(),
  provideRuntimeChecks(config)
]
```

Related discussion: https://github.com/ngrx/platform/discussions/3399

### Describe any alternatives/workarounds you're currently using

Using `importProvidersFrom` function:

```ts
// main.ts
bootstrapApplication(AppComponent, {
  providers: [importProvidersFrom(StoreModule.forRoot({}))]
});

// feature.routes.ts:
export const featureRoutes: Route[] = [
  {
    path: '',
    component: FeatureComponent,
    providers: [importProvidersFrom(StoreModule.forFeature('name', reducer))],
  },
];
```

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by yharaskrik** [comment]
@brandonroberts did you start this? 👀
