### ISSUE TITLE
StoreDevtools: Introduce Standalone API for NgRx StoreDevtools

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#3527]
### Information

Introduce standalone APIs for instrumenting the Store with the `@ngrx/store-devtools` package. This should allow developers to use StoreDevtools in a "module-free" application.

Based on the discussion in #3399

```ts
provideStoreDevtools(config)
```

This function will make use of the [ENVIRONMENT_INITIALIZER](https://angular.io/api/core/ENVIRONMENT_INITIALIZER) token to perform any init logic that was previously done in the NgModule constructor.

Registers the connection with the Redux Devtools Extension.

### Describe any alternatives/workarounds you're currently using

Using `importProvidersFrom` function:

```ts
// main.ts
bootstrapApplication(AppComponent, {
  providers: [importProvidersFrom(StoreDevtoolsModule.instrument())]
});
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by yharaskrik** [comment]
I got this one.

**Comment by poudelsagar725** [comment]
i got this one
