### ISSUE TITLE
RouterStore: Introduce Standalone API for NgRx RouterStore

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#3528]
### Information

Introduce standalone APIs for using the `@ngrx/router-store` package. This should allow developers to use RouterStore in a "module-free" application.

Based on the discussion in #3399

```ts
provideRouterStore(config)
```

This function will make use of the [ENVIRONMENT_INITIALIZER](https://angular.io/api/core/ENVIRONMENT_INITIALIZER) token to perform any init logic that was previously done in the NgModule constructor.

### Describe any alternatives/workarounds you're currently using

Using `importProvidersFrom` function:

```ts
// main.ts
bootstrapApplication(AppComponent, {
  providers: [importProvidersFrom(StoreRouterConnectingModule.forRoot())]
});
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by yharaskrik** [comment]
@brandonroberts how do we want to handle all of the private/init functions that are currently in the `StoreRouterConnectingModule`? Refactor them to plain functions and then use them in both places? Or should we leave the existing module as it is and then rewrite the logic so that it can be used in the environment initializer?

**Comment by yharaskrik** [comment]
OR I guess, make a `StoreRouterConnectingService` that is initialized using an environment initializer in both the provider function and the forRoot method that essentially takes all the init logic from the module and moves it into a service?

**Comment by brandonroberts** [comment]
> OR I guess, make a `StoreRouterConnectingService` that is initialized using an environment initializer in both the provider function and the forRoot method that essentially takes all the init logic from the module and moves it into a service?

This is what I was thinking, just move the NgModule class into a separate service and initialize it with the initializer, and just inject it into the constructor of the NgModule

**Comment by yharaskrik** [comment]
> > OR I guess, make a `StoreRouterConnectingService` that is initialized using an environment initializer in both the provider function and the forRoot method that essentially takes all the init logic from the module and moves it into a service?
> 
> This is what I was thinking, just move the NgModule class into a separate service and initialize it with the initializer, and just inject it into the constructor of the NgModule

Perfect! Already begun.

**Comment by yharaskrik** [comment]
Actually, should I use the same environment injection in both the provider function and ngModule? Or should the ngmodule `init` it by injecting into the constructor? (they should be equivalent?)

**Comment by brandonroberts** [comment]
Yea, they should be equivalent. Using the Environment Initializer token in both seems reasonable to me

**Comment by yharaskrik** [comment]
Inital PR done, I have some meetings for the rest of the day but will come back and update the documentation.
