### ISSUE TITLE
Data: Introduce Standalone API for NgRx Data

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#3529]
### Information

Introduce standalone APIs for using the `@ngrx/data` package. This should allow developers to use NgRx Data in a "module-free" application.

Based on the discussion in #3399

```ts
provideEntityData(config)
```

This function will make use of the [ENVIRONMENT_INITIALIZER](https://angular.io/api/core/ENVIRONMENT_INITIALIZER) token to perform any init logic that was previously done in the NgModule constructor.

### Describe any alternatives/workarounds you're currently using

Using `importProvidersFrom` function:

```ts
// main.ts
bootstrapApplication(AppComponent, {
  providers: [importProvidersFrom(EntityDataModule.forRoot(entityConfig))]
});
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by yharaskrik** [comment]
> I can take it 😊

Dangit santosh!

**Comment by santoshyadavdev** [comment]
> > I can take it 😊
> 
> Dangit santosh!

Take this one https://github.com/ngrx/platform/issues/3528

**Comment by yharaskrik** [comment]
> > > I can take it 😊
> > 
> > 
> > Dangit santosh!
> 
> Take this one #3528

Haha I was just working on it! Great minds think alike!
