### ISSUE TITLE
Creating nested stores for Subfeature (and so on)

### ISSUE THREAD

**Issue by mlakhara** [ngrx/platform#353]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request
</code></pre>

## What is the current behavior?
Lets us say that the app structure is like the following hierarchy of modules (lazy loaded)

    AppModule <--- Top level root module (store imported as StoreModule.forRoot() )
      ->ModuleA <- (Feature module, store imported as StoreModule.forFeature('moduleA',reducer)
          ->SubfeatureA (submodule of feature module, store imported as StoreModule.forFeature('subfeatureA', reducer))

Then the store is created in the following heirarchy:

    root
       moduleA
       subfeatureA

i.e. the subfeatureA store object is present at the same level instead of being nested in moduleA.
       
## Expected behavior:
subfeatureA should be nested inside the moduleA store.

If this is the intended behavior, then how to make the nesting work. Earlier I used composeReducers but have been waiting so long for the fractal store composition in the latest as I thought it would work out of the box.

**Comment by brandonroberts** [comment]
The state composition is still fractal even though not deeply nested. Using nested stores drastically increases the complexity of the store and it wasn't a tradeoff we were willing to implement. Feature modules imported into the AppModule don't created a nested structure either as they all share the same injector context.

**Comment by mlakhara** [comment]
The case for the nested structure is that I have components from lazy modules being injected at various levels for hierarchy. Sometimes multiple components of the same time might be present in an auxiliary route and primary route. In this case, the store state written by one component will be overwritten by another component.

**Comment by timblakely** [comment]
If you want to keep the flat/shallow structure, could we simply add a salt for multiply imported modules?

AppModule
  ModuleA
    SubfeatureA  <= in state as {"subfeatureA": {...}}
  ModuleB
    SubfeatureA  <= in state as {"subfeatureA_1": {...}}

Only createFeatureSelector() would need to know about the extra "_N" in the state; everything else wouldn't know the difference. Not sure how hard it would be for createFeatureSelector to be instantiated at module import time...?

**Comment by timblakely** [comment]
I think this might also cause issues when depending on third-party libraries that have name collisions in their state. If I depend on third party library A that declares a feature state of 'MyFeature'' and third party library B that declares an entirely separate feature state 'MyFeature', they'll collide in the base state.
