### ISSUE TITLE
Schematics Core: Add ability to add providers to bootstrapApplication function

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#3536]
### Information

Support adding providers to the bootstrapApplication function in preparation for NgRx APIs for Angular apps using standalone components for bootstrapping.

This will be added to the `ng-add` schematic for each library with a `--standalone` flag

Before:

```ts
bootstrapApplication(AppComponent)
```

After

```ts
bootstrapApplication (AppComponent, {
  providers: [
    provideStore(),
    provideStoreDevtools(),
    provideEffects(),
    // router-store, data, etc
  ]
})
```

### Describe any alternatives/workarounds you're currently using

Manual

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by DMezhenskyi** [comment]
Hey :) Is it something I could help you with?

**Comment by markostanimirovic** [comment]
Hey @DMezhenskyi 👋 

That would be great! Do you want to work on this feature? 😎

**Comment by brandonroberts** [comment]
Also wanted to note that in Angular v16, for standalone apps there will be a `src/app/app.config.ts` that will get updated also in addition to the `main.ts`. I'm not sure if there is a migration provided by the Angular team to introduce this file

**Comment by DMezhenskyi** [comment]
> Hey @DMezhenskyi 👋
> 
> That would be great! Do you want to work on this feature? 😎

Yeah, this is exactly what I would like to suggest :) My only concern is when you plan to deliver this feature because definitely I won't be able to work full-time on it. If it is not something urgent I would be happy to implement it. 

@brandonroberts Thank you for the info, Brandon :) I will keep it in mind.

**Comment by DMezhenskyi** [comment]
1 month... ok, I will try my best :)

**Comment by brandonroberts** [comment]
I think to keep the scope down we should only target using `ng add` with the file structure for standalone projects.

```ah
ng add @ngrx/store
```

Would modify the `src/app/app.config.ts` and add `provideStore()` to the `providers` array, along with generating an initial feature state if requested.

**Comment by DMezhenskyi** [comment]
Thank you all for your reviews, feedback and for accepting my PR 🙏

I think in my free time I could also help with other packages that need the support of the `--standalone` flag like effects, router-store, etc. My only question is if I have to create separate issues per package or how would it be better to organize that?

**Comment by brandonroberts** [comment]
Thanks for working on this! I fixed our issue with syncing the schematics-core across packages and updated the remaining packages except for NgRx Data to support standalone with ng add.

https://github.com/ngrx/platform/pull/3881

If you would review it that would help also 🙂

**Comment by DMezhenskyi** [comment]
Awesome! it was so fast :D Sure, I will be glad to review it.
