### ISSUE TITLE
Selector Release with Props

### ISSUE THREAD

**Issue by demike** [ngrx/platform#3538]
### Information

There is no way to selectively remove memoized selector results based on arguments.

Think of a big tree where a selector returns a node.   getNode(id: string)

In addition we can remove a specific node: removeNode(id: string)
In this case i would like to call `reset(id)` on the getNode selector, to just remove one memoized call (not all).

Imagine the selector would have to do more work than just doing a lookup, like transforming into  a different kind
of view model based on the original one. This would result in reevaluating the whole model even if the deleted node was
just a leaf node

### I would be willing to submit a PR to fix this issue

- [x] Yes
- [ ] No

**Comment by timdeschryver** [comment]
How do you see this being implemented?

A selector instance holds its own state, and by using props there will be multiple selector instances (one per invocation). 

This should work:

```ts
selector = selectById(1);
selector.release();
```

**Comment by demike** [comment]
@timdeschryver thanks for the clarification!
