### ISSUE TITLE
Add ability to generate actions with createActionGroup using schematics

### ISSUE THREAD

**Issue by billyjov** [ngrx/platform#3543]
### Information

We are currently be able to generate actions using schematics. 

https://ngrx.io/guide/schematics/action

The generated file contains all actions  like this: 

```ts
export const loadBooks = createAction(
  '[Books] Load Books'
);

export const loadBooksSuccess = createAction(
  '[Books] Load Books Success',
  props<{ books: Book[] }>()
);

export const loadBooksFailure = createAction(
  '[Books] Load Books Failure',
  props<{ error: any }>()
);
```

It will be helpful if the developer have the ability to group them using the new `createActionGroup` function to reach following result directly during file generation. 

```ts
export const BooksActions = createActionGroup({
  source: 'Books',
  events: {
    'Load Books': emptyProps(),
    'Load Books Success': props<{ books: Book[] }>(),
    'Load Books Failure': props<{ error: any }>(),
  }
})

```

## Proposal

`ng generate action ActionName --group` is already use to group actions within files an alternative can be 

- `ng generate action ActionName --compact`  or
- `ng generate action ActionName --action-group` or
- `ng generate action ActionName --minimal` or
...
any other proposal? Does this make sense? 

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Good idea. I'd like to take this a step further and make `createActionGroup` the default when using schematics to generate actions/features

**Comment by timdeschryver** [comment]
@brandonroberts I think that would be great, but maybe with that until we release v15?

**Comment by brandonroberts** [comment]
Yep, we can pick this back up after the last 14.x release

**Comment by timdeschryver** [comment]
@danielkleebinder that isn't possible.
`createActionGroup` requires a source, and the event description doesn't accept string values with `[` or `]`.

The actions should be combined per source, in your example this becomes `booksListPageActions` and `booksApiActions`. This still follows the best practices because actions are grouped, and are prefixed with the source of the group.

**Comment by danielkleebinder** [comment]
@timdeschryver I see, thank you for you response!

**Comment by jkyoutsey** [comment]
As a note, the keys in the events configuration violate default eslint rules:
/* eslint-disable @typescript-eslint/naming-convention */
It might be nice if the schematic block disabled this section.
```typescript
export const ThingActions = createActionGroup({
	source: 'Things',
	events: {
		/* eslint-disable @typescript-eslint/naming-convention */
		Load: emptyProps(),
		'Load Success': props<{ things: Thing[] }>(),
		'Load Failure': emptyProps(),
		/* eslint-enable @typescript-eslint/naming-convention */
	},
});
```
