### ISSUE TITLE
Provide adapter method to allow sorting from within reducer

### ISSUE THREAD

**Issue by moniuch** [ngrx/platform#3556]
### Information

I find it unclear how to dynamically change the adapter's sortComparer function in response to table header click in a component.

The example provided in docs:

```ts
export const adapter: EntityAdapter<User> = createEntityAdapter<User>({
  selectId: selectUserId,
  sortComparer: sortByName,
});
```

and lack of any adapter method to change the sorter afterwards (in response to an action) sounds like a limitation.

My suggestion would be to provide adapter with a method: `adapter.setSortComparer(fn: SortComparerFn)`

which could be then consumed by a reducer:

```ts
on(action.mySetSorting, (state, {sortCol, sortDir}) => adapter.setSortComparer(
  myCreateUserSortComparer(sortCol, sortDir)
))
```

```ts
const myCreateUserSortComparer = (sortingCol, sortingDir = 'ASC') => {
  return function entitySortComparerFactory (a: User, b: User) {
    // ... build custom sort comparer: numerical, lexical
   }
}
```

There would be probably much more involved TS typing than this, but I just want to suggest the usage part here for consideration.

With this in place, the adapter initialization could utilize it in the example.

### Describe any alternatives/workarounds you're currently using

none that I would be aware of
if there is one, please provide it in docs.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by markostanimirovic** [comment]
Hi @moniuch

Changing the sort comparer on the fly would lead to performance issues. See [this comment](https://github.com/ngrx/platform/issues/898#issuecomment-450151217).

You can use the selector to recalculate sorted entity collection when unsorted entity collection, sort column, or sort order changes:

```ts
export const selectSortedEntities = createSelector(
  selectUnsortedEntities,
  selectSortColumn,
  selectSortOrder,
  (entities, sortColumn, sortOrder) => /* sort entities here */
);
```

**Comment by moniuch** [comment]
@markostanimirovic Thanks for explaining, I appreciate that :) Somehow my brain got stuck at thinking about the adapter/reducer part rather than selectors. Could I ask you what is the purpose of this sortComparer then?
