### ISSUE TITLE
tapResponse still swallows Errors

### ISSUE THREAD

**Issue by alvipeo** [ngrx/platform#3558]
### Minimal reproduction of the bug/regression with instructions

We had [this issue](https://github.com/ngrx/platform/issues/3431) some time ago and it was fixed. But I updated my [stackblitz](https://stackblitz.com/edit/angular-ivy-pzhjks) example and it still doesn't work as expected I think. What am I missing?

### Minimal reproduction of the bug/regression with instructions

see stackblitz

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx: 14.3.0

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by sergidt** [comment]
It looks like the finalize operator is never called when service throws the error, can be a signal!!??
 
```typescript
readonly doTheProcessing = this.effect(
    (inputVals$: Observable<{ a: number; b: number }>) => {
      return inputVals$.pipe(
        tap(() => this.clearResult()),
        tap(() => this.setInProgress()),
        switchMap(({ a, b }) =>
          this.svc.doSomeProcessing(a, b).pipe(
            /* tapResponse(
              (result) => this.setResult(result),
              (err) => this.setError()
            ),*/
            finalize(() => this.clearInProgress())
          )
        )
      );
    }
  );

  private clearInProgress() {
    console.log('finalize');
    this.updater((state) => ({
      ...state,
      inProgress: false,
    }));
  }
```

the string 'finalize' is never shown

**Comment by alvipeo** [comment]
I don't want to point to any repo/product here. The guys do a GREAT job. But when it comes to real code, this is what makes it difficult.

In this case `finalize` shouldn't be called as `doSomeProcessing` itself throws. But expecting a service to throw errors is normal, and there must be a clean way of catching them. I just don't see it, which is why I ask.

**Comment by timdeschryver** [comment]
@alvipeo There's a difference here.
`tapResponse` catches errors that happen during the request, or while processing the response.

The problem in the stackblitz is that the service throws a JS error, this is something you should handle because it happens outside of the stream (before the stream is created).

If the throw is replaced with a `throwError` (rxjs) or when a request returns a non-successful error code the error is caught by `tapResponse`.

**Comment by alvipeo** [comment]
@timdeschryver thank you! that's what I thought but I think there might be a construct for this. I may be wrong. It's just if you wrap the `doSomeProcessing` with try-catch, it's going to be too cluttered I think.
