### ISSUE TITLE
ComponentStore - parameterless effect does not run

### ISSUE THREAD

**Issue by alvipeo** [ngrx/platform#3560]
### Minimal reproduction of the bug/regression with instructions

Here's the [stackblitz](https://stackblitz.com/edit/angular-ivy-sjvksu). Please see the working sample.

### Minimal reproduction of the bug/regression with instructions

Run stackblitz.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx: 14.3.0

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by alvipeo** [comment]
As a sidenote - can anyone explain to me why the effect runs just on load? I mean I did not invoke the effect anywhere, only selectors are defined. The only place where the effect is invoked is on `click`...

**Comment by timdeschryver** [comment]
@alvipeo the effect should still have a trigger.
It's this piece of code that gets invoked when it's been called.

It runs on load, because that's the initialization code to create the effect.

For more info see #3384

```ts
  readonly doVoidProcessing = this.effect((trigger$) => {
    return trigger$.pipe(
      switchMap(() => {
       this.patchState({ inProgress: true, errorMsg: undefined });
        return this.svc.doSomeProcessing(1, 2).pipe(
          tapResponse(
            (result) => this.setResult(result),
            (err) => this.setError('error occurred')
          ),
          finalize(() => this.clearInProgress())
        );
      })
    ) 
  });
```

**Comment by alvipeo** [comment]
@timdeschryver can somebody please write a blog post about it?

**Comment by alvipeo** [comment]
@timdeschryver so, if I have multiple effects they all run on load??? I don't get it...

**Comment by spierala** [comment]
Hi @alvipeo, all effects are wired up when the class is instantiated.

This line of code will run when the effect is wired up:
![image](https://user-images.githubusercontent.com/1272446/188919465-cf465c05-2f97-4411-879f-a35c7bb6078c.png)
But that line of code should not be at that place...

As Tim pointed out, you have to pass in the trigger$, also if there is no real parameter. 
All your effect logic should be inside trigger$.pipe().
trigger$ will emit as soon as you call the effect: `doVoidProcessing()`.
When trigger$ emits the code inside trigger$.pipe will run. 

Effects are wired up at the beginning, but won`t do anything until you call your effect.

**Comment by alvipeo** [comment]
Thank you. That must be added to the docs! Both:
- you have to pass in the trigger$, also if there is no real parameter
- All your effect logic should be inside trigger$.pipe()

It's also not very clear where is this `trigger$` coming from. I mean I still don't have a clear pic about what actually trigger is. I probably need to look at the sources for that.

**Comment by Harpush** [comment]
> Thank you. That must be added to the docs! Both:
> 
> * you have to pass in the trigger$, also if there is no real parameter
> * All your effect logic should be inside trigger$.pipe()
> 
> It's also not very clear where is this `trigger$` coming from. I mean I still don't have a clear pic about what actually trigger is. I probably need to look at the sources for that.

You can use the standalone pipe approach which won't have those possible problems

**Comment by alvipeo** [comment]
@Harpush link to docs/blog post?

**Comment by Harpush** [comment]
> @Harpush link to docs/blog post?

It's just a convention I usually use. @timdeschryver referenced an issue with that option there. It's almost impossible to do that mistake:
```ts
  readonly doVoidProcessing = this.effect<void>(
    pipe(
      tap(() => this.patchState({ inProgress: true, errorMsg: undefined })),
      switchMap(() =>
        this.svc.doSomeProcessing(1, 2).pipe(
          tapResponse(
            (result) => this.setResult(result),
            (err) => this.setError('error occurred')
          ),
          finalize(() => this.clearInProgress())
        )
      )
    )
  );
```

**Comment by alvipeo** [comment]
Oh, got it! yes, that's much cleaner in my opinion. No "miracles".
