### ISSUE TITLE
@ngrx/effects@14.3 not compatible with latest typescript 4.8

### ISSUE THREAD

**Issue by labeled** [ngrx/platform#3562]
### Minimal reproduction of the bug/regression with instructions

npm install typescript@latest
Attempt to build project

### Minimal reproduction of the bug/regression with instructions

Would expect no compilation errors

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx: 14.3.0
Angular: 14.6.5
Node: 16.7.0
Browser(s): Chrome
Operating system(s): Windows 10

### Other information

This is the error message I am seeing when building using the newest typescript. It looks like a simple fix is to change `getEffectDecoratorMetadata<T>` to `getEffectDecoratorMetadata<T extends {}>`
```
Error: node_modules/@ngrx/effects/src/effect_decorator.d.ts:7:84 - error TS2344: Type 'T' does not satisfy the constraint 'Object'.

7 export declare function getEffectDecoratorMetadata<T>(instance: T): EffectMetadata<T>[];
                                                                                     ~

  node_modules/@ngrx/effects/src/effect_decorator.d.ts:7:52
    7 export declare function getEffectDecoratorMetadata<T>(instance: T): EffectMetadata<T>[];
                                                         ~
    This type parameter might need an `extends Object` constraint.


Error: node_modules/@ngrx/effects/src/effects_metadata.d.ts:3:75 - error TS2344: Type 'T' does not satisfy the constraint 'Object'.

3 export declare function getSourceMetadata<T>(instance: T): EffectMetadata<T>[];
                                                                            ~

  node_modules/@ngrx/effects/src/effects_metadata.d.ts:3:43
    3 export declare function getSourceMetadata<T>(instance: T): EffectMetadata<T>[];
                                                ~
    This type parameter might need an `extends Object` constraint.


Error: node_modules/@ngrx/effects/src/models.d.ts:25:31 - error TS2344: Type 'T' does not satisfy the constraint 'Object'.

25     [key in EffectPropertyKey<T>]?: EffectConfig;
                                 ~

  node_modules/@ngrx/effects/src/models.d.ts:24:37
    24 export declare type EffectsMetadata<T> = {
                                           ~
    This type parameter might need an `extends Object` constraint.
```

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by SebastianPodgajny** [comment]
This is already fixed [here](https://github.com/ngrx/platform/pull/3548). Any information when we can expect ngrx with this fix to be released?

**Comment by timdeschryver** [comment]
[v14.3.1](https://github.com/ngrx/platform/compare/14.3.0...14.3.1) Is release 5 hours ago.
Could you retry and validate if it's working for you?
If that's not the case feel free to reopen this issue.

**Comment by drk-mtr** [comment]
The 14.3.1 update resolves this issue for me - thanks for the fast fix!
