### ISSUE TITLE
component-store: tap parameter loses type safety in effect if last operator

### ISSUE THREAD

**Issue by Harpush** [ngrx/platform#3563]
### Minimal reproduction of the bug/regression with instructions

It seems that because the effect trigger function return type is `Observable<unknown>` any operator without explicit return type will lose type safety (mono operator).

StackBlitz: https://stackblitz.com/edit/angular-ivy-26zukl?file=src/app/store.service.ts
Code sample:
```ts
  private test = this.effect<number>(
    pipe(
      tap(value => console.log(value)),
    )
  )
```
Hovering `value` will show `unknown` and not `number`. If another `tap` is added the first one works but the second one once again will show `value` as `unknown`. That won't be the case for `map` operator for example. 

### Minimal reproduction of the bug/regression with instructions

I am not sure if the solution is changing `effect` types or `tap` types or introducing some custom `tap` function or adding a custom ghost operator at the end of every effect.... anyway this is a very common way to write component store effects and it loses type safety altogether. 

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx: 14
Angular: 14

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by markostanimirovic** [comment]
Hi @Harpush

Take a look at [this comment](https://github.com/ngrx/platform/issues/3217#issuecomment-957298087). This happens in non-strict or partially strict TS mode - when `strictFuctionTypes` flag is `false`. It can be fixed by setting the `strictFunctionTypes` flag to `true` in `tsconfig.json`.

**Comment by Harpush** [comment]
> Hi @Harpush
> 
> The same issue was reported some time ago (#3217).
> 
> Take a look at [this comment](https://github.com/ngrx/platform/issues/3217#issuecomment-957298087). This happens in non-strict or partially strict TS mode - when `strictFuctionTypes` flag is `false`. It can be fixed by setting the `strictFunctionTypes` flag to `true` in `tsconfig.json`.

My bad - didn't see that issue. Anyway that really solved it. Maybe add docs about it?

**Comment by timdeschryver** [comment]
I think that's a good idea @Harpush .
The issue has popped up several times in the past :)

**Comment by david-shortman** [comment]
Is it worth individually calling out type issues in the docs? I wonder if instead the docs should recommend configuring a project tsconfig with the same strict rules under which the library is written. Any deviation may cause unexpected problems.

**Comment by timdeschryver** [comment]
I'm closing this issue because it's been a while.
I also assume most projects now have "strict" on.
