### ISSUE TITLE
Selectors: typed projector methods

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#3571]
### Information

This issue comes from a discussion https://github.com/ngrx/platform/discussions/3097

Currently when using the `selector.projector` method, we can pass it any argument(s) and it won't complain. With this change we want to make the projectors type-safe so that mistakes can be caught earlier. 

### Describe any alternatives/workarounds you're currently using

/

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by david-shortman** [comment]
Started a PR, feel free to assign
