### ISSUE TITLE
Migration: typed projector methods

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#3572]
### Information

This issue is dependent on #3571.
When #3571 is resolved, we want to add a migration so that we don't break any existing codebases.

@david-shortman proposed a migration plan at https://github.com/ngrx/platform/discussions/3097#discussioncomment-3540950, which we can implement. 

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by david-shortman** [comment]
This can be closed since we're only doing a breaking change
