### ISSUE TITLE
Error: 1 periodic timer(s) still in the queue when testing a store with fakeAsync

### ISSUE THREAD

**Issue by amakhrov** [ngrx/platform#3573]
### Which @ngrx/* package(s) are the source of the bug?

component-store

### Minimal reproduction of the bug/regression with instructions

```
it("doesn't work", fakeAsync(() => {
  new ComponentStore<{}>();
  expect(1).toEqual(1);
}));
```
Running this unit test produces
> Error: 1 periodic timer(s) still in the queue.

### Minimal reproduction of the bug/regression with instructions

The test above should pass.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx: 14.0.2
Angular: 14.2

### Other information

I believe it's a regression introduced with the lifecycle hooks. In particular, the run-time check in this PR: https://github.com/ngrx/platform/pull/3432/files#diff-dd156bfdaf294eb2eb0c9c87e1403ddd40190b88afa6ed8b443fb7cb1cd008f6R322

This check uses rxjs `asyncScheduler.schedule()`, which internally uses `setInterval` - a periodic task that offends `fakeAsync` :)
https://github.com/ReactiveX/rxjs/blob/6.x/src/internal/scheduler/AsyncAction.ts#L50

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by markostanimirovic** [comment]
Hi @amakhrov,

Replacing `asyncScheduler` with `asapScheduler` [here](https://github.com/ngrx/platform/blob/master/modules/component-store/src/component-store.ts#L325) (scheduling lifecycle hooks check to the microtask queue instead of macrotask) should solve this issue. Do you want to open the PR?

**Comment by amakhrov** [comment]
Yep, here is the PR: https://github.com/ngrx/platform/pull/3580
