### ISSUE TITLE
Update Router State in Store when using Resolve

### ISSUE THREAD

**Issue by pietmichal** [ngrx/platform#358]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## What is the current behavior?
When using `resolve` within `Route`, `data` property doesn't include the result of `resolve` in the store. 

## Expected behavior:
When using `resolve`, `data` property should be updated with the result from it.

## Minimal reproduction of the problem with instructions:
Example route:
```
      {
        path: ':userid',
        component: UserDetailComponent,
        canActivate: [UserIdGuard],
        resolve: { userName: UserNameResolve }
      }
```
`userName` doesn't exist in `data` property of `ActivatedRouteSnapshot` within the store.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
`@ngrx/router-store: 4.0.4`

## Other information:
I've noticed that even the serializer doesn't receive router state with updated `data` property.

**Comment by roopkt** [comment]
Hi @brandonroberts @MikeRyanDev 
I have fixed this issue by changing the hook to 

> afterPreactivation from beforePreactivation in StoreRouterConnectingModule  class

Can I create PR for this fix? However, I have question why we had hook on beforePreactivation if we change it to postPreactivation then effect will be fired after guards and resolves. Is it okay ? Will this impact the initial design in mind ?

**Comment by brandonroberts** [comment]
Hey @roopkt. The idea for the for the resolve action is to add an additional listener for the `ResolveEnd` action, similar to the existing `NavigationError` and `NavigationCancel` events, then dispatch the appropriate `NavigationResolve` action.

**Comment by roopkt** [comment]
Thanks! @brandonroberts  got it I will work on this.

**Comment by brandonroberts** [comment]
@roopkt after some thought I leaning towards not bringing this into the library. Using resolvers with ngrx is considered an anti-pattern, as you should use guards/effects to push data into the store.

**Comment by roopkt** [comment]
@brandonroberts  Thanks

**Comment by fredgate** [comment]
A question : I don't understand why use the guards instead resolvers to push data into store. The role of guards is to forbid access to a route, while role of resolver is to retrieve data needed for a route.
So the resolvers seem to be the best candidates for that.

**Comment by bbaia** [comment]
Relates to #816

**Comment by klinki** [comment]
I agree with @fredgate, using resolvers seems to be much better option to retrieve data. @brandonroberts  why is it considered anti-pattern (and not supported by library)?

I just hit this limitation and it gives me a lot of trouble :(
