### ISSUE TITLE
NgRX StoreDevtoolsModule.instrument() is broken refuses to log or function

### ISSUE THREAD

**Issue by kenatwex** [ngrx/platform#3582]
### Which @ngrx/* package(s) are the source of the bug?

router-store, store-devtools

### Minimal reproduction of the bug/regression with instructions

SUBJECT: NgRX StoreDevtoolsModule.instrument() is broken refuses to log or function

If someone tries to launch this repo and run nothing works

https://github.com/salimchemes/ngrx-router-state

Nothing will log in the console

not interested in any chrome redux extension... I want the original wonderful NgRX devtools router serializer on deck

Something is seriously wrong is this a hit job on NgRX ?
These comments speak for themself
>I've looked for the past few days for resources that go over troubleshooting redux dev tools with angular & ngRx and have no idea what to do anymore.

https://stackoverflow.com/questions/71226994/ngrx-angular-app-not-working-with-redux-devtools

WHO IS DESTROYING ANGULAR/NGRX ??????

Why does the best pattern on the planet have to be demoted to junk when the originators made a virtual masterpiece... human hands??? Im beside myself.

This is UNACCEPTABLE

WHO made the decision to funnel everything OUT of the console and into an extension in the browser in a different TAB?
When we had everything we needed to see right in front of us right in the console all color coded perfectly.
This is the kind of stuff that is everything Victor Savkins is not. A STEP DOWN INTO A TRENCH.
And it wont even work in the debugger ?

Someone seriously needs to be reviewed here and removed from the NgRX project and prevented from continued compounded damage.

This product has gone from elite world class and now in the dumps junk unusable.

Is anyone hearing this ? WHO IS DOING THIS STUFF ? PUT IT ALL BACK AND LEAVE IT ALONE

### Minimal reproduction of the bug/regression with instructions

launch this repo

it refuses to work... period

https://github.com/salimchemes/ngrx-router-state

Who in their right mind would trade state and logging right at your finger tips in the IDE console and the browser console for an extension that does nothing but offers fun elementary clicks and views across tabs its nothing but a stupid toy it has close to ZERO developmental value whatsoever.

This is pitiful

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.17.0
   OS   : darwin arm64
   yarn : 1.22.18
   
   nx : 14.7.5
   @nrwl/angular : 14.7.5
   @nrwl/cypress : 14.7.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.7.5
   @nrwl/eslint-plugin-nx : 14.7.5
   @nrwl/express : Not Found
   @nrwl/jest : 14.7.5
   @nrwl/js : 14.7.5
   @nrwl/linter : 14.7.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.7.5
   @nrwl/nx-cloud : 14.6.2
   @nrwl/nx-plugin : 14.7.5
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.7.5
   @nrwl/web : 14.7.5
   @nrwl/workspace : 14.7.5
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @fortawesome/angular-fontawesome: 0.10.2
   	 @ngrx/component-store: 14.2.0
   	 @ngrx/effects: 14.2.0
   	 @ngrx/entity: 14.2.0
   	 @ngrx/router-store: 14.2.0
   	 @ngrx/store: 14.2.0
   	 apollo-angular: 4.0.1
   	 @buildmotion/angular: 13.0.1
   	 @ngrx/schematics: 14.2.0
   	 @ngrx/store-devtools: 14.2.0
   	 @storybook/angular: 6.5.12

### Other information

NgRX has taken a walloping and barely usable now in the commercial field

the contention over classes vs creators

and now the devtools console log wont even function

this is one of the best products ever developed on planet earth

:"(

If they just left it alone at version 10,11 things would still be great

How do I get this to work now?

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
The repo you shared is for NgRx v9. Please add a relevant reproduction if you're going to share your frustration along with it
