### ISSUE TITLE
clear instructions for MemoizedSelectorWithProps deprecation

### ISSUE THREAD

**Issue by alex-vg** [ngrx/platform#3594]
### Information

The following line references an issue on github: https://github.com/ngrx/platform/blob/8eb400129ae5fe8d6f995986eb407b4393621c71/modules/store/src/selector.ts#L32

The docs should instead give clear instructions like the ones here: https://github.com/ngrx/platform/issues/2980#issuecomment-1263422402

### Documentation page

https://github.com/ngrx/platform/blob/8eb400129ae5fe8d6f995986eb407b4393621c71/modules/store/src/selector.ts#L32

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by timdeschryver** [comment]
Closing this because examples are added to the [migration guide](https://ngrx.io/guide/migration/v12#ngrxstore)
