### ISSUE TITLE
Type {...} does not satisfy the constraint 'extends Object'

### ISSUE THREAD

**Issue by vpallathu** [ngrx/platform#3603]
### Which @ngrx/* package(s) are the source of the bug?

store

### Minimal reproduction of the bug/regression with instructions

I started seeing the error in the actions list of my application. An example is below:

`export const LoadUser = createAction('[LoadUser] Load User', props<{ id: string }>());`

The error is `Type { id: string } does not satisfy the constraint 'extends Object'`

### Minimal reproduction of the bug/regression with instructions

The error leads to the type definition:

`export declare function createAction<T extends string, P extends object>(type: T, config: ActionCreatorProps<P> & NotAllowedCheck<P>): ActionCreator<T, (props: P & NotAllowedCheck<P>) => P & TypedAction<T>>;`

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx: 14.3.1
Angular: 14.2.3
Typescript: 4.8.3

### Other information

I think the issue is in `P extends object`

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by timdeschryver** [comment]
This seems to be working here, https://stackblitz.com/edit/ngrx-seed-vehcne?file=src%2Fapp%2Factions%2Fcounter.actions.ts.

Feel free to reopen when you have a reproduction.

**Comment by vpallathu** [comment]
The compiler does not generate any error. I'm using **ReSharper** plugin in **Visual Studio Community Edition 2020**.

This is what I see in the Visual Studio IDE:

![image](https://user-images.githubusercontent.com/72323243/195403394-9f0e6b44-8e6a-4e0b-b21a-c95afd7de335.png)

I also have opened a question in StackOverflow at https://stackoverflow.com/questions/74034777/type-does-not-satisfy-the-constraint-extends-object-error-in-typescript
