### ISSUE TITLE
TypeScript Error in IntelliJ when setting  StoreDevtoolsModule

### ISSUE THREAD

**Issue by xmlking** [ngrx/platform#361]
TypeScript show Error in IntelliJ 
please make `monitor` as optional in `StoreDevtoolsOptions` 
 
```
    StoreDevtoolsModule.instrument({
      maxAge: 25, //  Retains last 25 states
    }),
```

![image](https://user-images.githubusercontent.com/627951/30187951-ecdefebe-93e0-11e7-8e17-a0fccaf0875e.png)

**Comment by xmlking** [comment]
why this is closed ?

**Comment by deftomat** [comment]
@xmlking It looks like it is optional already (see [this](https://github.com/ngrx/platform/blob/47f4ca84c3951f9cfc003b3591f995742f7a6718/modules/store-devtools/src/instrument.ts#L89) and [this](https://github.com/ngrx/platform/blob/47f4ca84c3951f9cfc003b3591f995742f7a6718/modules/store-devtools/src/config.ts#L16)).

I'm using Webstorm 2017.2.3 and store-devtools@4.0.0 with no problem.

**Comment by xmlking** [comment]
I have to explicitly set `<StoreDevtoolsOptions>`  `type` to fix the IDE error mark.... 

```ts
    StoreDevtoolsModule.instrument(<StoreDevtoolsOptions>{
      maxAge: 25, //  Retains last 25 states
    }),
```
