### ISSUE TITLE
Effects: Remove Effect decorator

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#3617]
### Information

We deprecated this feature many versions ago, no longer have any usage of it with our largest consumers, and have a migration to automatically update any usage. This effort will:

- Remove the decorator from the `effects` package
- Simplify registration of effect metadata where possible
- Add relevant information to v15 migration guide

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by timdeschryver** [comment]
There are also a few eslint rules that work with `@effect`, I think that these can be removed as they no longer serve a purpose.

If no one is busy with this one, I can pick it up.
