### ISSUE TITLE
ngRx Effects fails when compiled with property renaming

### ISSUE THREAD

**Issue by KevinVillela** [ngrx/platform#362]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## What is the current behavior?
When compiled with the Closure Compiler and property_renaming=ON, you will get errors when injecting effects.

## Expected behavior:
ngRx works in compiled mode.

## Minimal reproduction of the problem with instructions:
Create any effect, compile the application with the Closure Compiler and property_renaming=ON, and start the application. The problem manifests [here](https://github.com/ngrx/platform/blob/81afd0d71c0aca6d051a88954e2fa4edbf9a9cf2/modules/effects/src/effects_resolver.ts#L20): `propertyName` in this case is the non-renamed version, so trying to get it in `sourceInstance` will return undefined. I'm not entirely sure why this is (maybe it's the way the metadata is gathered), but for whatever reason Closure does not rename that but does rename the actual effects class property. To work-around this, `export declare` an interface with all of the effects that you have, and have the effects class implement that interface. This will prevent Closure from renaming them. For example:

```
export declare interface SomeEffectsInterface { someEffect: Observable<{}>; }

@Injectable()
export class SomeEffectsClass implements SomeEffectsInterface {
  constructor(private readonly actions: Actions) {}

  @Effect()
  someEffect = this.actions.ofType(SOME_ACTION_TYPE).
                          .mapTo(new someOtherActionType());
``` 

## Version of affected browser(s),operating system(s), npm, node and ngrx:
ngrx/effects V4.05 (most recent), All browsers/OSes since the compiled JavaScript itself is bad.

**Comment by brandonroberts** [comment]
This is a known issue being tracked here: https://github.com/angular/tsickle/issues/577

**Comment by alex-okrushko** [comment]
Using [--export_local_property_definitions](https://gist.github.com/cramforce/bc76e77c1f16e979a436#file-closure-compiler-usage-L58) Closure flag and annotating each `@Effect` with `/** @export */ will keep the property in place.

**Comment by deli6z** [comment]
Should this one  be closed then @alex-okrushko ?

**Comment by alex-okrushko** [comment]
Yes, it should be closed.
