### ISSUE TITLE
Remove TSDoc comments about the AOT engine

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#3625]
### Information

Remove the notion and example of declaring reducers that are compatible with View Engine AOT.

This can be done by removing the following example:

https://github.com/ngrx/platform/blob/863673452c9964f1606089435194329c1c508c4a/modules/store/src/reducer_creator.ts#L115-L131

And also. by rewording the following notion:

https://github.com/ngrx/platform/blob/863673452c9964f1606089435194329c1c508c4a/modules/store/src/reducer_creator.ts#L98-L99

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by SilasParker** [comment]
Hi Tim, I'd like to take a shot at taking this on as a first issue

**Comment by timdeschryver** [comment]
Go for it @SilasParker !
Don't hesitate if you need some help.

**Comment by SilasParker** [comment]
Thanks @timdeschryver !

I'm having an issue opening a PR for this repo
`Permission to ngrx/platform.git denied to SilasParker.`

As far as I can tell it's because I need to be added as a collaborater. If this isn't the case and there's something else I need to do please let me know, thanks

**Comment by timdeschryver** [comment]
You first need to fork the NgRx repository, this creates a `silasparker/platform` repository.
It's here where you need to make changes and push your changes against.
When you've pushed the changes then you can create a Pull Request to `ngrx/platform`.

![image](https://user-images.githubusercontent.com/28659384/197194769-f66edf6d-354b-43b6-8f70-2f7d948acf29.png)

**Comment by timdeschryver** [comment]
This course by Kent C Dodds helped me when I started contributing, maybe that it can be of help for you too.
https://egghead.io/lessons/javascript-how-to-fork-and-clone-a-github-repository

**Comment by SilasParker** [comment]
Thanks so much! Think I've got it right this time round
Have opened the PR here https://github.com/ngrx/platform/pull/3627
Let me know if any further issues, I appreciate the help
