### ISSUE TITLE
spa, after i change route, all actions dispatched before dispatch again?

### ISSUE THREAD

**Issue by node-rookie** [ngrx/platform#363]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Version of affected browser(s),operating system(s), npm, node and ngrx:
chrome ngrx version: 5.0.3

**Comment by node-rookie** [comment]
i found it's @ngrx/store-devtools problem, after remove @ngrx/store-devtools import code, everything is ok, same as #229

**Comment by brandonroberts** [comment]
Closing as duplicate
