### ISSUE TITLE
Effects dispatching multiple actions don't reach reducer before other effects

### ISSUE THREAD

**Issue by jbardon** [ngrx/platform#3657]
### Which @ngrx/* package(s) are the source of the bug?

effects

### Minimal reproduction of the bug/regression with instructions

https://stackblitz.com/edit/ngrx-effect-multiple-actions?file=src%2Fapp%2Fstore.ts

### Minimal reproduction of the bug/regression with instructions

Hi,
I work on a codebase which have effects dispatching multiple actions. Usually, we expect actions dispatched to the store to reach the reducers first and then effects. Yet it's not the case when an effect dispatch multiple actions at once (see the attached Stackblitz with comments).

According to [no-multiple-actions-in-effects](https://github.com/timdeschryver/eslint-plugin-ngrx/blob/main/docs/rules/no-multiple-actions-in-effects.md) eslint rule this is a code smell to dispatch multiple actions in an effect. Unfortunately, I didn't manage to find a word about it in NgRx documentation. 

If it's a bug, it should be fixed to guarantee reducers are triggered **before** effects when a action is dispatched to the store. Otherwise it would be great to prevent this pattern with runtime error (if possible) or at least warn readers of effects documentation (some articles online advice the multiple actions pattern).

Have a nice day!

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx: 14.2
Angular: 14.2
Browser: all

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by jbardon** [comment]
After talking with a coworker, we might have figured out NgRx behavior when an effect emits multiple actions. 
* Actual behavior: take first action, dispatch to store (execute reducer), execute effects, do the same for next action in the list sequentially
* Expected: dispatch all actions at once to the store (execute reducers), execute effects, done

Can't say if the expected behavior makes sense since I don't know about NgRx internals.

**Comment by markostanimirovic** [comment]
Hi @jbardon,

You didn't pass the initial state to the reducer in provided StackBlitz reproduction. That was the issue:

```ts
export const stateReducer = createReducer<any>(
  // ⚠️ initial state is missing here

  on(actions.loadRequest, (state) => {
    console.log('reducer: loadRequest');
    return state;
  }),
  on(actions.loadRequestSuccess, (state) => {
    console.log('reducer: loadRequestSuccess');
    return state;
  }),
  on(actions.loadMoreRequest, (state) => {
    console.log('reducer: loadMoreRequest');
    return state;
  })
);
```

Please take a look at the fixed example: https://stackblitz.com/edit/ngrx-effect-multiple-actions-yqkhyy?file=src%2Fapp%2Fstore.ts

It works as intended - reducers are always executed before effects regardless of whether multiple actions are dispatched from the effect or not.

**Comment by jbardon** [comment]
Hey @markostanimirovic 
Indeed, I forgot the initial state. By looking at the fixed version it seems the issue is still there:

```
reducer: loadRequest
effect: loadRequest
reducer: loadMoreRequest
effect: loadMoreRequest
reducer: loadRequestSuccess
```

The expected order would be to have both `reducer: loadMoreRequest` and `reducer: loadRequestSuccess` executed before `effect: loadMoreRequest`. The outlier is the last reducer call which should be placed before the last effect call.

**Comment by timdeschryver** [comment]
@jbardon this is the expected behavior.
The first action is dispatched, and follows the flow (hits all reducers, then effects). Then, the second action is dispatched.

**Comment by jbardon** [comment]
@timdeschryver Thanks for the explanation. It makes sense but might not be straightforward for everyone.

Since an always hits reducers before effects. One would expect an effect which emits multiple actions to dispatch the two actions at the same time.

Don't you think it needs clarification, may on the doc? It can be a source of tricky sync bug for anyone who misunderstand this undocumented behavior.
