### ISSUE TITLE
Missing documentation on eslint-plugin

### ISSUE THREAD

**Issue by DaSchTour** [ngrx/platform#3658]
### Information

The documentation about the eslint-plugin is missing some information about how to actually add the recommended rules.

I tried to add the following to extends

- "plugin:@ngrx:recommended-requiring-type-checking"
- "plugin:@ngrx/eslint-plugin:recommended-requiring-type-checking"
- "@ngrx/eslint-plugin:recommended-requiring-type-checking"
- "@ngrx/eslint-plugin/recommended-requiring-type-checking"

till I found that probably "plugin:@ngrx/eslint-plugin/recommended-requiring-type-checking" works. At least it doesn't throw an error.

But it looks like "plugin:@ngrx/recommended-requiring-type-checking" also works.

It would be nice to have some examples on how to include this premade configurations.

### Documentation page

https://ngrx.io/guide/eslint-plugin

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by timdeschryver** [comment]
Hi @DaSchTour that would be valuable to add to the docs, thanks for bringing it up!

Simply added the rules is not enough.
The trick is to import the plugin via `plugins` or `extends`, then you can tweak the rules via the `rules`. 

For example:

```
{
      "plugins": ["@ngrx"],
      "rules": {
        "@ngrx/good-action-hygiene": "error",
      }
}
```

or

```
{
      "extends": ["@ngrx/recommended"],
      "rules": {
        "@ngrx/good-action-hygiene": "error",
      }
}
```


To use a preconfigured configuration, you can add it to `extends`:

```
{
      "extends": ["@ngrx/recommended-requiring-type-checking"],
      "rules": {}
}
```

Feel free to add this to the docs

**Comment by digeomel** [comment]
The OP is right, you need to prefix `plugin:` in the `extends` array, as such:
```
"extends": ["plugin:@ngrx/recommended"],
```
I did not find this in the docs.
