### ISSUE TITLE
Can't install @ngrx/entity via NPM or Yarn

### ISSUE THREAD

**Issue by exequiel09** [ngrx/platform#366]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## What is the current behavior?
Yarn and NPM returns error when installing `@ngrx/entity`

## Expected behavior:
It should be able to install `@ngrx/entity` via NPM or Yarn

## Minimal reproduction of the problem with instructions:

Try installing it with the command `npm install --save @ngrx/entity` or `yarn add @ngrx/entity`

## Version of affected browser(s),operating system(s), npm, node and ngrx:

Angular: 4.3.6
Node: 8.4.0
NPM: 5.4.1
OS: macOS 10.12.6

<img width="848" alt="screen shot 2017-09-10 at 1 44 42 pm" src="https://user-images.githubusercontent.com/1289472/30246553-32ba9316-9630-11e7-86dc-885fbf7510a1.png">

**Comment by exequiel09** [comment]
Managed to get around by issuing the command `yarn add https://github.com/ngrx/entity-builds.git`. Hopefully this will be available at NPM or Yarn.

**Comment by Lycidas0815** [comment]
+1 for npm. 
npm ERR! 404 Not found : @ngrx/entity

**Comment by code2nguyen** [comment]
@exequiel09 It doesn't work!

**Comment by MikeRyanDev** [comment]
This is because @ngrx/entity is not a released project yet. We are still landing the last remaining documentation bits. Once finished, we'll do a formal announcement and release.

**Comment by craigt1212** [comment]
Any time frames for the release on npm?

**Comment by petersgiles** [comment]
Should your example app use this if it hasn't been released yet?

**Comment by brandonroberts** [comment]
@petersgiles Yes. Its pretty close to release. Plus there are nightlies you can access now with full documentation.

**Comment by SergioArrighi** [comment]
Hi all,
how to install with NPM for the time being?
Regards

**Comment by tomrussell** [comment]
@SergioArrighi I added `"@ngrx/entity": "ngrx/entity-builds.git#d1a695dab0b045c42a02a1d4f54cce6dbe3e856c",` to my `package.json` file... hopefully this works for you

**Comment by Cazs03** [comment]
```
CollectionWebsiteComponent.html:4 ERROR TypeError: Cannot read property 'entities' of undefined
    at selectEntities (entity.es5.js:40)
    at store.es5.js:701
    at memoized (store.es5.js:669)
    at store.es5.js:705
    at memoized (store.es5.js:669)
    at store.es5.js:704
    at Array.map (<anonymous>)
    at store.es5.js:704
    at MapSubscriber.memoized [as project] (store.es5.js:669)
    at MapSubscriber.webpackJsonp.../../../../rxjs/operator/map.js.MapSubscriber._next (map.js:77)

<app-website-list [websites]="websites$ | async"></app-website-list>

```
Any idea?

**Comment by danielhdz56** [comment]
If anyone is still having issues with this, I recommend using the nightly builds.
`npm install github:ngrx/entity-builds`

**Comment by stankusl** [comment]
Anybody found a workaround?
