### ISSUE TITLE
RFC: Add ability to create functional effects

### ISSUE THREAD

**Issue by markostanimirovic** [ngrx/platform#3668]
### Which @ngrx/* package(s) are relevant/related to the feature request?

effects

### Information

Add the ability to create functional effects (without classes). Similar to functional guards, we would be able to use `inject` within the `createEffect` function:

```ts
// users.effects.ts

export const loadUsers = createEffect(
  (actions$ = inject(Actions), usersService = inject(UsersService)) => {
    return actions$.pipe(
      ofType(UsersPageActions.opened),
      exhaustMap(() => /* ... */)
    );
  },
  { functional: true }
);

export const displayErrorAlert = createEffect(
  () => {
    return inject(Actions).pipe(
      ofType(UsersApiActions.usersLoadedFailure),
      tap(({ error }) => alert(error.message))
    );
  },
  { functional: true, dispatch: false }
);
```

In order not to break the current behavior of the `createEffect` function, for functional effects we need to add `functional: true` in the effect config. They can be registered as follows:

```ts
import * as usersEffects from './users.effects.ts';

bootstrapApplication(AppComponent, {
  providers: [
    provideEffects(usersEffects),
  ],
});
```

### Testing

To test functional effects, we don't need `TestBed` to provide services if we inject all dependencies as effect factory parameters (see `loadUsers` effect above). Unit test for this effect can look like this:

```ts
it('loads users successfully', () => {
  usersEffects.loadUsers(actionsMock, usersServiceMock).subscribe((action) => {
    expect(serviceMock, 'getAll').toHaveBeenCalled();
    expect(action).toEqual(/* ... */);
  });
});
```

### This feature will not remove the ability to create effects within classes

We'll be still able to define effects within classes:

```ts
@Injectable()
export class UsersEffects {
  readonly displayErrorAlert = createEffect(() => {
    return this.actions$.pipe(
      ofType(UsersApiActions.usersLoadedFailure),
      tap(({ error }) => alert(error.message))
    );
  }, { dispatch: false });

  constructor(private readonly actions$: Actions) {}
}
```

and register them via `provideEffects` (or `EffectsModule.forRoot/forFeature`):

```ts
provideEffects(UsersEffects);
```

### I would be willing to submit a PR to fix this issue

- [x] Yes
- [ ] No

**Comment by manfredsteyer** [comment]
I love it for two reasons:
- It nicely fits to other trends in Angular like functional interceptors, guards, and resolvers
- For me, it also removes an ambiguity: In the past, we used to call two different things an effect: the service (class), and the property set up with `createEffect`

**Comment by Armenvardanyan95** [comment]
Is it possible to make the first argument for the callback function the injected `Actions` class instance by default? Something like

`const myEffect = createEffect(actions$ => actions$.pipe(/* etc) */)` 

Of course I think the users themselves will be able to do this manually, but would be nice to have.

Other than this. absolutely love the idea, removes boilerplate, removes ambiguity, also easier to explain in general I think

**Comment by Felexonyango** [comment]
This is cool ,I cant wait

**Comment by stefanoslig** [comment]
That's very nice! 
What about the effect's lifecycle hooks? I find them very useful in some projects! It will be possible to use them only in class effects?

**Comment by brandonroberts** [comment]
@stefanoslig yes that will still be possible. Being able to use effects in a class isn't changing at all.

**Comment by timdeschryver** [comment]
@phhien203 yes, that would be possible.

**Comment by phhien203** [comment]
Thank @timdeschryver

**Comment by markostanimirovic** [comment]
RFC description updated ☝️

**Comment by markostanimirovic** [comment]
> Is it possible to make the first argument for the callback function the injected `Actions` class instance by default? Something like
> 
> `const myEffect = createEffect(actions$ => actions$.pipe(/* etc) */)`

@Armenvardanyan95 

I'd rather not provide `Actions` by default because we'd need to provide them as well when testing effects that don't use actions. In my opinion, there is not much difference between:

```ts
(actions$ = inject(Actions)) => actions$.pipe(/* ... */)
// or
() => inject(Actions).pipe(/* ... */)
```

compared to:

```ts
(actions$) => actions$.pipe(/* ... */);
```

while the first option gives more flexibility.

**Comment by Armenvardanyan95** [comment]
@markostanimirovic I get you idea. How about a factory function that allows creating predefined effect creator functions? Like this:

```ts
const createUserEffects = createEffectFactory([Actions, UserService, SomeOtherService]);

const loadUsers = createUserEffects((actions, userService, someOtherService) => {
  return actions.pipe(
    ofType(someAction);
    // and so on
  );
})
```

Just feels kinda neater. In testing, we can still provide whatever mock values we want by calling it with mock args, can we? I think we should be able to do that

**Comment by liesahead** [comment]
> @markostanimirovic I get you idea. How about a factory function that allows creating predefined effect creator functions? Like this:
> 
> ```ts
> const createUserEffects = createEffectFactory([Actions, UserService, SomeOtherService]);
> 
> const loadUsers = createUserEffects((actions, userService, someOtherService) => {
>   return actions.pipe(
>     ofType(someAction);
>     // and so on
>   );
> })
> ```
> 
> Just feels kinda neater. In testing, we can still provide whatever mock values we want by calling it with mock args, can we? I think we should be able to do that

Reminds me of angularjs 🤕

**Comment by Armenvardanyan95** [comment]
@liesahead how come? We use factories in Angular and also in NgRx all the time. We have selector factory functions, for example. This is not a separate configuration, but a factory function to return a preconfigured effect creator

**Comment by liesahead** [comment]
> @liesahead how come? We use factories in Angular and also in NgRx all the time. We have selector factory functions, for example. This is not a separate configuration, but a factory function to return a preconfigured effect creator

But in each effect you would need to inject all services as function arguments `createUserEffects((actions, userService, someOtherService)` at least from what I see, this reminds me of angularjs. If you inject 10 services in your effect then it will be 10 arguments listed. Looks bulky.

**Comment by Armenvardanyan95** [comment]
@liesahead 
While I think what you mentioned is a bit limited (you usually use 1-2 services in 1 effects class from my experience), this still can be mitigated using an object instead of an array:

```typescript
const createUserEffects = createEffectFactory({actions$: Actions, userService: UserService, someOtherService: SomeOtherService});

const loadUsers = createUserEffects({actions, userService}) => { // use only the services you need for a particular effect
  return actions.pipe(
    ofType(someAction);
    // and so on
  );
})

**Comment by liesahead** [comment]
@Armenvardanyan95 , this one I like more 😄 anyway, if this doesn't replace current behavior (with services injection in the constructor) and comes as an additional feature then I think it might be a good idea for some people.

**Comment by achraf-elk** [comment]
my code coverage is nagging about uncovered branches regarding the injected dependecies, any clew how to mitigate that? 

![image](https://github.com/ngrx/platform/assets/128139969/9a451102-5feb-4c3c-8b18-bc48f3b0d598)
this is my tests: 

```
  describe('loadMecList', () => {
    it('should return loadMecListSuccess action, with the list, on success', () => {
      const mecList: Mec[] = [{} as Mec];
      const action = Actions.initCommandeManagement();
      actions$ = of(action);
      mecListServiceMock.loadMECsNonPagine.mockReturnValue(of(mecList));

      Effects.loadMecList$(actions$, mecListService).subscribe((resultAction) => {
        expect(mecListService.loadMECsNonPagine).toHaveBeenCalled();
        expect(resultAction).toEqual(
          Actions.loadMecListSuccess({
            mecList,
          }),
        );
      });
    });

    it('should return a CommandeCreationActions.loadFailure action, with an error, on failure', () => {
      const error = new HttpErrorResponse({});
      const action = Actions.initCommandeManagement();

      actions$ = of(action);
      mecListServiceMock.loadMECsNonPagine.mockReturnValue(throwError(error));

      Effects.loadMecList$(actions$, mecListService).subscribe((resultAction) => {
        expect(mecListService.loadMECsNonPagine).toHaveBeenCalled();
        expect(resultAction).toEqual(Actions.loadFailure({ error }));
      });
    });
  });
```

**Comment by marcschaller** [comment]
Yes, you can use the `runInInjectionContext` method of the `TestBed`:

```typescript
    it('should return loadMecListSuccess action, with the list, on success', () => {
      const mecList: Mec[] = [{} as Mec];
      const action = Actions.initCommandeManagement();
      actions$ = of(action);
      mecListServiceMock.loadMECsNonPagine.mockReturnValue(of(mecList));

      expect(TestBed.runInInjectionContext(Effects.loadMecList$)).subscribe((resultAction) => {
        expect(mecListService.loadMECsNonPagine).toHaveBeenCalled();
        expect(resultAction).toEqual(
          Actions.loadMecListSuccess({
            mecList,
          }),
        );
      });
    });
```

Note that you have to use the `provideMockActions` function provided by ngrx and a whole configured `TestBed` for this to work (as you don't pass your mocks directly to your effect).
