### ISSUE TITLE
Reusable feature module with unique state.

### ISSUE THREAD

**Issue by liesahead** [ngrx/platform#3672]
### Which @ngrx/* package(s) are relevant/related to the feature request?

store

### Information

It would be nice to have some setting like `shared: boolean` (true by default, like current behavior) when registering `StoreModule.forFeature`, so when I import some `CarSelectorModule` with its own actions/effects/reducer the state would be unique in every place where it's imported.

https://stackoverflow.com/questions/49537571/independent-instances-of-the-same-ngrx-feature-module

### Describe any alternatives/workarounds you're currently using

Either recreating and copy-paste logic (awful, lots of code to support and bundle size is growing too fast) or reusing with same state = bugs.

**Comment by Armenvardanyan95** [comment]
I may suggest using factory functions for creating reducers that do the same thing but with unique states + action group factory. For example, imagine you have a search functionality that can be in three different modules, like "users", "orders", "payments", and then create a reducer factory for this:

```typescript
function searchReducerFactory(module: string) {
  return createReducer<SearchState>(
    { search: null },
    on(fromSharedActions.loadSearchSuccess, (state, { search }) => ({
      results: search.results,
    })),
    // other handlers
  );
}

function createSearchActionsFactory(module: string) {
  return createActionGroup({
    source: module,
    actions: {
      loadSearch: createAction('Load Search'),
      loadSearchSuccess: createAction('Load Search Success'),
      loadSearchError: createAction('Load Search Error'),
    },
  });
}
```

Then use those factories to create different-but-same reducers and actions for different modules and register them there. This is a very high-level example, but that is how I would have done that

**Comment by liesahead** [comment]
@Armenvardanyan95 , thanks! Looks quite good, but I would also need a unique effects. And this becomes too complicated to manage without official way.

Our current decision is to reduce usage of `ngrx` in the project and in such components with `unique state` no state manager will be used or maybe some other.

**Comment by Armenvardanyan95** [comment]
@liesahead do the effects differ only with the service called? You can introduce an adapter service that will make the "same" call to different URLs depending on the kind of module you use them in, and have one single effect to handle those.  I've written an article about such dependency injection tricks (https://codeburst.io/angular-dependency-injection-tips-ddb24b8244be), scroll to the "Providing different services depending on the environment" section for more (no idea how to anchor link on Medium, sorry). It is about loading different services for different envs, but you can kinda extrapolate it for modules

**Comment by liesahead** [comment]
@Armenvardanyan95 , effects do not differ. What is needed in this case is a separate state. Effects, actions, reducers are the same. State is the only one that needs to be unique so the module could be fully re-usable. But, as I said, until this isn't supported officially, the easiest way to get rid of app state manager in such modules.

**Comment by timdeschryver** [comment]
This feature would add an additional complexity, and I think we don't want to add that now.
We could look into this when it becomes a feature that more peoples are asking for.
The current API should allow you to build something on top of it and create a reusable feature.

**Comment by liesahead** [comment]
Actually, we went with `ngrx-component-store` as it seems to cover our needs.

**Comment by timdeschryver** [comment]
Yea, component store seems to be a better fit here @liesahead . Thanks for the update!

**Comment by aenimaone** [comment]
So, if I have page (module/component) and, for example, use in two aux router outlet, its no way reuse ngrx feature now? And alternative is only component-store without dev tools from box? its very sadly. May be anybody know example of "feature fabric" or same so, that can help reuse logic?

**Comment by Armenvardanyan95** [comment]
@aenimaone as I mentioned in my previous comment, you still can go for a feature-factory, which is a pretty common low-risk pattern

**Comment by xianshenglu** [comment]
The global store used by ngrx fans brings a lot of duplications like 

`isUserListLoading`, `userList`, `selectedUserId`
`isProductListLoading`, `productList`, `selectedProductId`
......

Really painful.
