### ISSUE TITLE
New selector factory for route data

### ISSUE THREAD

**Issue by samuelfernandez** [ngrx/platform#3673]
### Which @ngrx/* package(s) are relevant/related to the feature request?

router-store

### Information

Right now the router seletors provide `selectRouteParam` and `selectQueryParam`, which are factory functions to resolve those types of params. This request is to do the same with route data, providing a selector factory for `selectRouteDataParam` or something similar.

### Describe any alternatives/workarounds you're currently using

Compose selectors

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Seems reasonable to me

**Comment by samuelfernandez** [comment]
> Seems reasonable to me

Thanks! Will submit a PR
