### ISSUE TITLE
Error while installing dependencies in Live Example

### ISSUE THREAD

**Issue by badnutz** [ngrx/platform#3674]
### Information

When I open the StackBlitz LiveExample for the store tutorial the example fails in the dependency installation step
![image](https://user-images.githubusercontent.com/4920326/203950893-47b2b368-117f-4456-971f-20b3a22ed2cc.png)

### Documentation page

https://ngrx.io/guide/store

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by timdeschryver** [comment]
Hi thanks for raising this issue.
We'll get this sorted when we upgrade the examples to v15.

**Comment by cedricduffournet** [comment]
I think this is more a stackblitz issue. Sometimes installation failed.

Anyway I submited a [PR](https://github.com/ngrx/platform/pull/3679) to upgrade the examples to V15
