### ISSUE TITLE
Docs: Update walkthrough to use createActionGroup

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#3681]
### Information

The walkthrough guide is more in-depth than the getting started. We should try to introduce `createActionGroup` as soon as possible.

https://ngrx.io/guide/store/walkthrough

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by cedricduffournet** [comment]
@brandonroberts i can take this one
