### ISSUE TITLE
Module '"@ngrx/effects"' has no exported member 'Effect'.

### ISSUE THREAD

**Issue by e2video** [ngrx/platform#3685]
### Which @ngrx/* package(s) are the source of the bug?

effects

### Minimal reproduction of the bug/regression with instructions

When imported  (import { Effect, ofType, Actions } from '@ngrx/effects';) 
Code shows me this message:
Module '"@ngrx/effects"' has no exported member 'Effect'.

Installed latest version on 11/29/2022:
"name": "@ngrx/effects",
  "version": "15.0.0",
  "description": "Side effect model for @ngrx/store",
  "repository": {
    "type": "git",
    "url": "https://github.com/ngrx/platform.git"
  }

### Minimal reproduction of the bug/regression with instructions

import { Effect, ofType, Actions } from '@ngrx/effects';

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

Angular CLI: 14.1.3
Node: 16.15.0
Package Manager: npm 8.15.0 
OS: darwin x64

Angular: 14.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1401.3
@angular-devkit/build-angular   14.1.3
@angular-devkit/core            14.1.3
@angular-devkit/schematics      14.1.3
@angular/cdk                    14.1.2
@angular/flex-layout            14.0.0-beta.40
@angular/material               14.1.2
@schematics/angular             14.1.3
rxjs                            6.6.7
typescript                      4.7.4

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by timdeschryver** [comment]
This is intended.
We removed `@Effect` in v15.

For more info see the migration guide.
https://ngrx.io/guide/migration/v15#removal-of-effect
