### ISSUE TITLE
schematics: ng-add wants to install 14.x in Angular 15.x project

### ISSUE THREAD

**Issue by fmalcher** [ngrx/platform#3691]
### Which @ngrx/* package(s) are the source of the bug?

schematics

### Minimal reproduction of the bug/regression with instructions

When adding `@ngrx/schematics` in an Angular 15 project, it will install `@ngrx/schematics@14.3.2`, even though `15.0.0` is available. Looks like a peerDeps issue.

### Minimal reproduction of the bug/regression with instructions

Create a new NG15 project and add `@ngrx/schematics`:

```
ng new testproject --routing --style=css
cd testproject
ng add @ngrx/schematics --default-collection
```

It will install 14.3.2 by default:

```
ℹ Using package manager: npm
✔ Found compatible package version: @ngrx/schematics@14.3.2.
✔ Package information loaded.

The package @ngrx/schematics@14.3.2 will be installed and executed.
```

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

```
Angular CLI: 15.0.2
Node: 18.12.1
Package Manager: npm 8.15.1
OS: darwin arm64

Angular: 15.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.2
@angular-devkit/build-angular   15.0.2
@angular-devkit/core            15.0.2
@angular-devkit/schematics      15.0.2
@schematics/angular             15.0.2
rxjs                            7.5.7
typescript                      4.8.4
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Interesting. The schematics package.json doesn't have any peer deps, so maybe it's Nx modifying it during the build.

**Comment by brandonroberts** [comment]
Looks like that's the case

https://unpkg.com/@ngrx/schematics@15.0.0/package.json

We'll have to update the schematics project config to not update the dependencies.

**Comment by brandonroberts** [comment]
@coly010 @leosvelperez this seems like an upstream bug as it shouldn't have picked up any v14 packages
