### ISSUE TITLE
Allows createActionGroup to preserve the case

### ISSUE THREAD

**Issue by hadrien-toma** [ngrx/platform#3693]
### Which @ngrx/* package(s) are relevant/related to the feature request?

store

### Information

I would like to be able to preserve the case of the event keys I put :grimacing: 

![image](https://user-images.githubusercontent.com/6162030/205476691-4298f739-6812-49bb-93ae-1d81f8feee73.png)

By the way: thank you very much for the improved APIs, I am totally fan! 

### Describe any alternatives/workarounds you're currently using

![image](https://user-images.githubusercontent.com/6162030/205476771-35eec5ee-050d-4a06-9b18-a1d61c05c250.png)

Unfortunately it will considerably increase any refactoring effort, I really like to have the name of my action being the name of its variable + (removing the spaces for the name of actions allows to have more characters visible in the Redux DevTools which helps a lot in case of long names).

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by hadrien-toma** [comment]
I also just noticed the `µ` character in the string `'µ My Super Specific Foo` is not the same as the one get with `mySuperSpecificActions.µMySuperSpecificFoo` but the one in the string is... the one I typed on my keyboard :grimacing:

**Comment by TJMaria** [comment]
I'm also postponing the use of action groups for this reason.
One of big downsides is that it makes it harder to find where certain actions are used in the code.

I think this is essential... ex. For a developer that is new to a project/codebase

**Comment by TJMaria** [comment]
For now i'm using a static class with utility functions as an alternative to createActionGroup
see https://github.com/ngrx/platform/pull/3736#issuecomment-1369785798

**Comment by martinkasa** [comment]
Find all references is not able to find action reference in createActionGroup in VS Code and vice versa. It is quite a big issue for navigating in a code. Maybe this PR solves that?

**Comment by TJMaria** [comment]
@martinkasa My workaround resolves that problem, with minimal extra code.
Hopefully the issue can be fixed in NgRx lib itself
