### ISSUE TITLE
Actions do not support collections

### ISSUE THREAD

**Issue by kenatwex** [ngrx/platform#3697]
### Which @ngrx/* package(s) are the source of the bug?

store

### Minimal reproduction of the bug/regression with instructions

I have no repo

### Minimal reproduction of the bug/regression with instructions

I would like to model an action like this

```
export const findSuccess = createAction(
	'[Cards/API] Find Success',
	props<{ cards: Card[] }>()
)
```

but the createAction api refuses to let me it imposes an OBJECT in the midst

not happy about PROPS being introduced like this unless Im missing something from the api

this code results int he same thing

```
export const findSuccess = createAction(
	'[Cards/API] Find Success',
	(cards: Card[]) => ({ cards })
);
```

an object continues to be imposed into the midst by the api

this api refuses to permit me to do anything otherwise

How can I get this Object out of my hair

Its ruining the NgRX cycles and doubling up Objects into everything

How can I model a collection in an action without being tripped up by this interwoven OBJECT
 

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.17.0
   OS   : darwin arm64
   yarn : 1.22.18
   
   nx : 15.1.1
   @nrwl/angular : 15.1.1
   @nrwl/cypress : 15.1.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.1.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.1.1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.1.1
   @nrwl/js : 15.1.1
   @nrwl/linter : 15.1.1
   @nrwl/nest : 15.1.1
   @nrwl/next : Not Found
   @nrwl/node : 15.1.1
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : 15.1.1
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.1.1
   @nrwl/schematics : 8.12.11
   @nrwl/storybook : 15.1.1
   @nrwl/web : 15.1.1
   @nrwl/webpack : 15.1.1
   @nrwl/workspace : 15.1.1
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @fortawesome/angular-fontawesome: 0.10.2
   	 @ngneat/transloco: 4.1.1
   	 @ngrx/component: 14.3.2
   	 @ngrx/component-store: 14.3.2
   	 @ngrx/effects: 14.3.2
   	 @ngrx/entity: 14.3.2
   	 @ngrx/router-store: 14.3.2
   	 @ngrx/store: 14.3.2
   	 @ngrx/store-devtools: 14.3.2
   	 apollo-angular: 4.1.0
   	 @buildmotion/angular: 13.0.1
   	 @ngrx/schematics: 14.3.2
   	 @ngrx/store-devtools: 14.3.2
   	 @storybook/angular: 6.5.13

### Other information

any assist is appreciated

I have been modeling NgRX for four years now

and this should not be holding me up

Our data remains unpredictable and we are chasing code in circles due to the imposed PROPS OBJECT

thanks for your help

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
This is by design. An action itself is a plain JavaScript object with a minimum of a `type` property. The props is an object that is merged into the object created internally. If you were to pass a collection directly, you wouldn't have a way of accessing it without a key.
