### ISSUE TITLE
Clarify docs for registering feature created with createFeature

### ISSUE THREAD

**Issue by pcurrivan** [ngrx/platform#3699]
### Information

It seems like the following should work, but selectors will apparently silently fail to function if you register the feature this way:
`StoreModule.forFeature(testFeature.name, [testFeature.reducer])`

I think it should be clearly stated in the docs that you must instead register like this:
`StoreModule.forFeature(testFeature)`

Maybe there could also be an error or warning if you try to use the first method?

### Documentation page

https://ngrx.io/guide/store/feature-creators

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by brandonroberts** [comment]
@pcurrivan where in the docs do you see the reducer being used in this way?

This works:

```ts
StoreModule.forFeature(testFeature.name, testFeature.reducer)
```

Your example is wrapping the reducer in an array, making it invalid

```ts
StoreModule.forFeature(testFeature.name, [testFeature.reducer])
```

**Comment by pcurrivan** [comment]
I'm not sure why I thought an array would work.  I guess I just saw the name of the argument "reducers" and assumed.  I didn't see it in the docs.  It would be nice if typescript would reject an array.
