### ISSUE TITLE
Misnamed key in configuration object for createEntityAdapter

### ISSUE THREAD

**Issue by karptonite** [ngrx/platform#370]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

This is a follow up for issues #367 and #369. While the documentation now indicates that the `sort` parameter is a compare function, it is still called `sort` In the configuration object, which could lead to confusion. It seems worth fixing the name before a beta of the entity package is actually released.

**Comment by brandonroberts** [comment]
I think `sort` is clearer, because you either disable it or you provide a custom comparer function used for sorting. What's your proposed name for the key?

**Comment by karptonite** [comment]
Good point. I agree that if you call it `compare` then setting to `false` to leave it unsorted is confusing. But it is already optional, so you could leave it unset if you were not sorting. Under what circumstances would you ever want to set it explicitly to `false`?  It seems that of you just had a `sortCompare` field, and sorted only if `sortCompare` is set, that may be clear for both usages.

**Comment by brandonroberts** [comment]
You wouldn't need to explicitly set it to false unless you have it wrapped in some sort of factory. I'm leaning towards leaving it as is for now.

**Comment by karptonite** [comment]
It is your call. I still think that calling the parameter `sort`, when what it takes is a custom comparer,  is not correct, especially when there is an actual name for what you are passing. It isn't a terrible thing, but what if, down the road, you want to add that `sort` boolean that you mentioned after all? If you leave it as it is, the parameter name is taken by something that isn't actually `sort`.

**Comment by brandonroberts** [comment]
Valid points. I think `sortComparer` is closer to describing what the key does. If its false, no sorting will be done, otherwise you provide a function that will be used for sorting.

**Comment by karptonite** [comment]
I agree that `sortComparer` is a good name.
