### ISSUE TITLE
Update environment files in example apps

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#3701]
### Information

We should update the example apps to the v15 "syntax".
This means that we can remove the environment files.

This needs to be done for:

- [] https://github.com/ngrx/platform/blob/master/projects/data-example-app/src/main.ts
- [] https://github.com/ngrx/platform/blob/master/projects/example-app/src/main.ts
- [] https://github.com/ngrx/platform/blob/master/projects/standalone-app/src/main.ts

### Documentation page

/

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by Villanuevand** [comment]
Hi @timdeschryver 
I would like to take this one!

**Comment by Villanuevand** [comment]
PR created at #3735
