### ISSUE TITLE
ComponentStore: Add documentation for using `ComponentStore.select` with observable dictionaries

### ISSUE THREAD

**Issue by markostanimirovic** [ngrx/platform#3704]
### Information

Using `ComponentStore.select` with observable dictionaries is introduced in [this PR](https://github.com/ngrx/platform/pull/3629). This feature should be also added to [ComponentStore documentation](https://ngrx.io/guide/component-store/read#combining-selectors).

Read more about this feature [here](https://dev.to/ngrx/announcing-ngrx-v15-standalone-apis-type-safe-projectors-component-and-componentstore-updates-and-more-l7#simplified-view-models-with-componentstore).

### Documentation page

https://ngrx.io/guide/component-store/read#combining-selectors

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by tomalaforge** [comment]
I can take this one
