### ISSUE TITLE
Store: Fix typo in `createSelectorFactory` documentation

### ISSUE THREAD

**Issue by markostanimirovic** [ngrx/platform#3705]
### Information

There is a typo in `createSelectorFactory` docs:

https://github.com/ngrx/platform/blob/10f1146e04d75339532ea55925365ba4736c9c8f/modules/store/src/selector.ts#L599

```diff
-* export const creactOrderDoesNotMatterSelector = createSelectorFactory(
+* export const createOrderDoesNotMatterSelector = createSelectorFactory(
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by TaylorAckley** [comment]
@markostanimirovic  I can take this one - note: experienced developer but first-time OS contributor - I apologize in advance if I don't get the etiquette or process right the first time.

**Comment by brandonroberts** [comment]
Let's go Taylor! No pressure, we'll help either way
