### ISSUE TITLE
Peer dependencies

### ISSUE THREAD

**Issue by Miedziaq** [ngrx/platform#3706]
### Which @ngrx/* package(s) are the source of the bug?

schematics

### Minimal reproduction of the bug/regression with instructions

you added 
"peerDependencies": {
    "@angular-devkit/schematics": "14.2.9",
    "@angular-devkit/core": "15.0.0"
  }
to the new ver ^15 of npm
this disallows to install angular 15:)

npm ERR! Could not resolve dependency:
npm ERR! peer @angular-devkit/schematics@"14.2.9" from @ngrx/schematics@15.0.0
npm ERR! node_modules/@ngrx/schematics
npm ERR!   dev @ngrx/schematics@"^15.0.0" from the root project

ngrx/schematics point to old 14 angular version

### Minimal reproduction of the bug/regression with instructions

you added 
"peerDependencies": {
    "@angular-devkit/schematics": "14.2.9",
    "@angular-devkit/core": "15.0.0"
  }
to the new ver ^15 of npm
this disallows to install angular 15:)

npm ERR! Could not resolve dependency:
npm ERR! peer @angular-devkit/schematics@"14.2.9" from @ngrx/schematics@15.0.0
npm ERR! node_modules/@ngrx/schematics
npm ERR!   dev @ngrx/schematics@"^15.0.0" from the root project

ngrx/schematics point to old 14 angular version

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

Ngrx 15
angular 15

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
This has been fixed already in https://github.com/ngrx/platform/pull/3692. We will have a release in a few days with the fix
