### ISSUE TITLE
"Getting Started Guide" conflicts with EsLint recommended-requiring-type-checking

### ISSUE THREAD

**Issue by defaultbranch** [ngrx/platform#3718]
### Information

**Actual**

The <https://ngrx.io/guide/store#tutorial> only demonstrates that NgRx somehow works, but as mentioned in #3325, the code style of the example is in conflict with EsLint `@ngrx/recommended-requiring-type-checking` and comes with type safety issues.

As it is, the 'Getting Started' does not help to get started in the right direction.

**Expected**

It would be helpful to have a starting example that is typesafe and accepted by EsLint.

### Documentation page

<https://ngrx.io/guide/store#tutorial>

### I would be willing to submit a PR to fix this issue

I could only provide the opinionated pattern <https://stackoverflow.com/a/74851371/14422199> for the tutorial.

**Comment by defaultbranch** [comment]
I have elaborated my problem in a SO post:

https://stackoverflow.com/questions/74850053/how-to-use-ngrx-in-a-composable-way-without-circular-code-dependencies-on-appst

**Comment by brandonroberts** [comment]
As with many Getting Started examples it's meant to teach you the concepts quickly, not to teach you how to build a production-grade app. We will revisit the getting started for clarity but we won't be making it more difficult to complete at this time.

**Comment by defaultbranch** [comment]
Thanks for the feedback, seems to be the same situation as 10 months ago (#3325) . NgRx is a great tool but it also comes with a steep learning curve... plus the many outdated 3rd-party introductions/guides/recipies being around. Well, that's probably the downside of a project being actively developed/enhanced ;-) The good thing is that the Guide is off because NgRx is being improved.
