### ISSUE TITLE
RFC: Add ability create extra selectors with `createFeature`

### ISSUE THREAD

**Issue by markostanimirovic** [ngrx/platform#3719]
### Which @ngrx/* package(s) are relevant/related to the feature request?

store

### Information

Add the ability to create extra selectors with the `createFeature` function.

This can be done by adding the optional `extraSelectors` property to the `FeatureConfig`. `extraSelectors` is a function that returns a dictionary of additional selectors. It accepts a dictionary of generated base selectors (feature selector + selector for each feature state property), so they can be used to create extra selectors as follows:

```ts
type CallState = 'init' | 'loading' | 'loaded' | { error: string };

interface State extends EntityState<Book> {
  callState: CallState;
}

const adapter = createEntityAdapter<Book>();
const initialState: State = adapter.getInitialState({
  callState: 'init',
});

export const booksFeature = createFeature({
  name: 'books',
  reducer: createReducer(initialState, /* case reducers */),
  extraSelectors: ({ selectBooksState, selectCallState }) => ({
    ...adapter.getSelectors(selectBooksState),
    selectIsLoading: createSelector(
      selectCallState,
      (callState) => callState === 'loading'
    ),
  }),
});
```

### Describe any alternatives/workarounds you're currently using

Currently, we can add extra selectors to the feature object in the following way:

```ts
type CallState = 'init' | 'loading' | 'loaded' | { error: string };

interface State extends EntityState<Book> {
  callState: CallState;
}

const adapter = createEntityAdapter<Book>();
const initialState: State = adapter.getInitialState({
  callState: 'init',
});

const feature = createFeature({
  name: 'books',
  reducer: createReducer(initialState, /* case reducers */),
});

export const booksFeature = {
  ...feature,
  ...adapter.getSelectors(feature.selectBooksState),
  selectIsLoading: createSelector(
    selectCallState,
    (callState) => callState === 'loading'
  ),
};
```

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
I like this, very flexible

**Comment by tomalaforge** [comment]
I don't get it. 

When I'm combining selector, i'm doing it inside my selector file and with the createSelector function. I prefer not to mix concern. 

Or I'm missing a point here.

**Comment by markostanimirovic** [comment]
@tomalaforge

We were thinking about the best way to include derived `@ngrx/entity` selectors in the NgRx feature. You can see the current/manual way how we can do that in the issue description. Another option is to export the entity adapter and use `getSelectors` in the `.selectors.ts` file to take `selectAll` and `selectTotal`, but using the adapter out of the reducer file is not the best solution IMO.

We also considered creating the `createEntityFeature` function, which would add `selectAll` and `selectTotal` selectors to the created feature. However, creating an additional feature function just to add derived entity selectors doesn't seem like a flexible solution, because we'll have the same issue if we want to add another group of derived selectors.

For example, a feature state contains the `callState` property and we want to also add `callState` selectors to that feature together with entity selectors. We also have the `getCallStateSelectors` function that is defined in the following way:

```ts
// call-state.ts
type CallState = 'init' | 'loading' | 'loaded' | { error: string };

interface CallStateSelectors<T> {
  selectIsLoading: MemoizedSelector<T, boolean>;
  selectIsLoaded: MemoizedSelector<T, boolean>;
  selectError: MemoizedSelector<T, string>;
}

export function getCallStateSelectors<T>(
  selectCallState: Selector<T, CallState>
): CallStateSelectors {
  return {
    selectIsLoading: createSelector(
      selectCallState,
      (callState) => callState === 'loading'
    ),
    /* ... */
  }
}
```

With this improvement, we'll be able to add `callState` selectors, derived entity selectors, or another group of "generic" derived selectors to any feature in a flexible way:

```ts
export const booksFeature = createFeature({
  name: 'books',
  reducer: createReducer(initialState, /* case reducers */),
  selectors: ({ selectBooksState, selectCallState }) => ({
    ...adapter.getSelectors(selectBooksState),
    ...getCallStateSelectors(selectCallState),
  }),
```

The `FeatureConfig.selectors` property would be optional, so there would be still the ability to define all derived selectors in a separate `selectors.ts` file.

**Comment by tomalaforge** [comment]
@markostanimirovic Thanks for the explanation. 

I think I need to practice and test `createFeature` more in depth to understand the value of this modification.

**Comment by Armenvardanyan95** [comment]
Absolutely love this approach, was going to ask if this is possible yet, but now I see this RFC. I was just having a separate selectors file for this, but now all can come down to having a `feature` file and actions/effects.
