### ISSUE TITLE
Unable to build example app

### ISSUE THREAD

**Issue by Jrubzjeknf** [ngrx/platform#372]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
ng build results in an error where it can't find the modules @ngrx/store, @ngrx/effects, @ngrx/router-store, @ngrx/store-devtools and @ngrx/entity.

<pre><code>$ ng build
Your global Angular CLI version (1.3.0) is greater than your local
version (1.2.1). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
Hash: 4a84aa82296b8d69c25c
Time: 25581ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 324 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 45.1 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 45.1 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 4.17 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in C:/Playground/ngrx/platform/example-app/app/shared/utils.ts (1,39): Cannot find module '@ngrx/router-store'.

ERROR in C:/Playground/ngrx/platform/node_modules/ngrx-store-freeze/dist/index.d.ts (1,31): Cannot find module '@ngrx/store'.

ERROR in C:/Playground/ngrx/platform/example-app/app/core/actions/layout.ts (1,24): Cannot find module '@ngrx/store'.

ERROR in C:/Playground/ngrx/platform/example-app/app/reducers/index.ts (7,8): Cannot find module '@ngrx/store'.

ERROR in C:/Playground/ngrx/platform/example-app/app/reducers/index.ts (10,29): Cannot find module '@ngrx/router-store'.

ERROR in C:/Playground/ngrx/platform/example-app/app/auth/actions/auth.ts (1,24): Cannot find module '@ngrx/store'.

ERROR in C:/Playground/ngrx/platform/example-app/app/auth/reducers/index.ts (1,55): Cannot find module '@ngrx/store'.

ERROR in C:/Playground/ngrx/platform/example-app/app/core/containers/app.ts (4,23): Cannot find module '@ngrx/store'.

ERROR in C:/Playground/ngrx/platform/example-app/app/auth/containers/login-page.component.ts (2,23): Cannot find module '@ngrx/store'.

ERROR in C:/Playground/ngrx/platform/example-app/app/auth/services/auth-guard.service.ts (5,23): Cannot find module '@ngrx/store'.

ERROR in C:/Playground/ngrx/platform/example-app/app/auth/effects/auth.effects.ts (8,33): Cannot find module '@ngrx/effects'.

ERROR in C:/Playground/ngrx/platform/example-app/app/auth/auth.module.ts (6,29): Cannot find module '@ngrx/store'.

ERROR in C:/Playground/ngrx/platform/example-app/app/auth/auth.module.ts (7,31): Cannot find module '@ngrx/effects'.

ERROR in C:/Playground/ngrx/platform/example-app/app/app.module.ts (8,29): Cannot find module '@ngrx/store'.

ERROR in C:/Playground/ngrx/platform/example-app/app/app.module.ts (9,31): Cannot find module '@ngrx/effects'.

ERROR in C:/Playground/ngrx/platform/example-app/app/app.module.ts (14,8): Cannot find module '@ngrx/router-store'.

ERROR in C:/Playground/ngrx/platform/example-app/app/app.module.ts (15,37): Cannot find module '@ngrx/store-devtools'.

ERROR in C:/Playground/ngrx/platform/example-app/app/books/actions/book.ts (1,24): Cannot find module '@ngrx/store'.

ERROR in C:/Playground/ngrx/platform/example-app/app/books/effects/book.ts (8,33): Cannot find module '@ngrx/effects'.

ERROR in C:/Playground/ngrx/platform/example-app/app/books/effects/book.ts (9,24): Cannot find module '@ngrx/store'.

ERROR in C:/Playground/ngrx/platform/example-app/app/books/actions/collection.ts (1,24): Cannot find module '@ngrx/store'.

ERROR in C:/Playground/ngrx/platform/example-app/app/books/effects/collection.ts (7,24): Cannot find module '@ngrx/store'.

ERROR in C:/Playground/ngrx/platform/example-app/app/books/effects/collection.ts (8,33): Cannot find module '@ngrx/effects'.

ERROR in C:/Playground/ngrx/platform/example-app/app/books/reducers/books.ts (1,32): Cannot find module '@ngrx/store'.

ERROR in C:/Playground/ngrx/platform/example-app/app/books/reducers/books.ts (2,65): Cannot find module '@ngrx/entity'.

ERROR in C:/Playground/ngrx/platform/example-app/app/books/reducers/index.ts (1,55): Cannot find module '@ngrx/store'.

ERROR in C:/Playground/ngrx/platform/example-app/app/books/guards/book-exists.ts (9,23): Cannot find module '@ngrx/store'.

ERROR in C:/Playground/ngrx/platform/example-app/app/books/containers/find-book-page.ts (3,23): Cannot find module '@ngrx/store'.

ERROR in C:/Playground/ngrx/platform/example-app/app/books/containers/view-book-page.ts (5,23): Cannot find module '@ngrx/store'.

ERROR in C:/Playground/ngrx/platform/example-app/app/books/containers/selected-book-page.ts (2,23): Cannot find module '@ngrx/store'.

ERROR in C:/Playground/ngrx/platform/example-app/app/books/containers/collection-page.ts (3,23): Cannot find module '@ngrx/store'.

ERROR in C:/Playground/ngrx/platform/example-app/app/books/books.module.ts (5,29): Cannot find module '@ngrx/store'.

ERROR in C:/Playground/ngrx/platform/example-app/app/books/books.module.ts (6,31): Cannot find module '@ngrx/effects'.

ERROR in Error encountered resolving symbol values statically. Could not resolve @ngrx/store relative to C:/Playground/ngrx/platform/example-app/app/app.module.ts., resolving symbol AppModule in
 C:/Playground/ngrx/platform/example-app/app/app.module.ts, resolving symbol AppModule in C:/Playground/ngrx/platform/example-app/app/app.module.ts, resolving symbol AppModule in C:/Playground/n
grx/platform/example-app/app/app.module.ts

ERROR in C:/Playground/ngrx/platform/example-app/app/app.module.ts (8,29): Cannot find module '@ngrx/store'.

ERROR in C:/Playground/ngrx/platform/example-app/app/app.module.ts (9,31): Cannot find module '@ngrx/effects'.

ERROR in C:/Playground/ngrx/platform/example-app/app/app.module.ts (14,8): Cannot find module '@ngrx/router-store'.

ERROR in C:/Playground/ngrx/platform/example-app/app/app.module.ts (15,37): Cannot find module '@ngrx/store-devtools'.

ERROR in C:/Playground/ngrx/platform/example-app/app/auth/auth.module.ts (6,29): Cannot find module '@ngrx/store'.

ERROR in C:/Playground/ngrx/platform/example-app/app/auth/auth.module.ts (7,31): Cannot find module '@ngrx/effects'.

ERROR in C:/Playground/ngrx/platform/example-app/app/reducers/index.ts (7,8): Cannot find module '@ngrx/store'.

ERROR in C:/Playground/ngrx/platform/example-app/app/reducers/index.ts (10,29): Cannot find module '@ngrx/router-store'.

ERROR in C:/Playground/ngrx/platform/example-app/app/shared/utils.ts (1,39): Cannot find module '@ngrx/router-store'.

ERROR in C:/Playground/ngrx/platform/example-app/app/core/containers/app.ts (4,23): Cannot find module '@ngrx/store'.

ERROR in ./example-app/app/app.module.ts
Module not found: Error: Can't resolve '@ngrx/store' in 'C:\Playground\ngrx\platform\example-app\app'
 @ ./example-app/app/app.module.ts 13:0-42
 @ ./example-app/main.ts
 @ multi ./example-app/main.ts

ERROR in ./example-app/app/auth/auth.module.ts
Module not found: Error: Can't resolve '@ngrx/store' in 'C:\Playground\ngrx\platform\example-app\app\auth'
 @ ./example-app/app/auth/auth.module.ts 12:0-42
 @ ./example-app/app/app.module.ts
 @ ./example-app/main.ts
 @ multi ./example-app/main.ts

ERROR in ./example-app/app/reducers/index.ts
Module not found: Error: Can't resolve '@ngrx/store' in 'C:\Playground\ngrx\platform\example-app\app\reducers'
 @ ./example-app/app/reducers/index.ts 1:0-69
 @ ./example-app/app/app.module.ts
 @ ./example-app/main.ts
 @ multi ./example-app/main.ts

ERROR in ./example-app/app/core/containers/app.ts
Module not found: Error: Can't resolve '@ngrx/store' in 'C:\Playground\ngrx\platform\example-app\app\core\containers'
 @ ./example-app/app/core/containers/app.ts 12:0-36
 @ ./example-app/app/app.module.ts
 @ ./example-app/main.ts
 @ multi ./example-app/main.ts

ERROR in ./example-app/app/app.module.ts
Module not found: Error: Can't resolve '@ngrx/effects' in 'C:\Playground\ngrx\platform\example-app\app'
 @ ./example-app/app/app.module.ts 14:0-46
 @ ./example-app/main.ts
 @ multi ./example-app/main.ts

ERROR in ./example-app/app/auth/auth.module.ts
Module not found: Error: Can't resolve '@ngrx/effects' in 'C:\Playground\ngrx\platform\example-app\app\auth'
 @ ./example-app/app/auth/auth.module.ts 13:0-46
 @ ./example-app/app/app.module.ts
 @ ./example-app/main.ts
 @ multi ./example-app/main.ts

ERROR in ./example-app/app/app.module.ts
Module not found: Error: Can't resolve '@ngrx/router-store' in 'C:\Playground\ngrx\platform\example-app\app'
 @ ./example-app/app/app.module.ts 16:0-89
 @ ./example-app/main.ts
 @ multi ./example-app/main.ts

ERROR in ./example-app/app/reducers/index.ts
Module not found: Error: Can't resolve '@ngrx/router-store' in 'C:\Playground\ngrx\platform\example-app\app\reducers'
 @ ./example-app/app/reducers/index.ts 3:0-49
 @ ./example-app/app/app.module.ts
 @ ./example-app/main.ts
 @ multi ./example-app/main.ts

ERROR in ./example-app/app/app.module.ts
Module not found: Error: Can't resolve '@ngrx/store-devtools' in 'C:\Playground\ngrx\platform\example-app\app'
 @ ./example-app/app/app.module.ts 17:0-59
 @ ./example-app/main.ts
 @ multi ./example-app/main.ts

ERROR in C:/Playground/ngrx/platform/example-app/app/auth/services/auth-guard.service.ts (5,23): Cannot find module '@ngrx/store'.

ERROR in ./example-app/app/auth/services/auth-guard.service.ts
Module not found: Error: Can't resolve '@ngrx/store' in 'C:\Playground\ngrx\platform\example-app\app\auth\services'
 @ ./example-app/app/auth/services/auth-guard.service.ts 13:0-36
 @ ./example-app/app/routes.ts
 @ ./example-app/app/app.module.ts
 @ ./example-app/main.ts
 @ multi ./example-app/main.ts

ERROR in C:/Playground/ngrx/platform/example-app/app/auth/containers/login-page.component.ts (2,23): Cannot find module '@ngrx/store'.

ERROR in ./example-app/app/auth/containers/login-page.component.ts
Module not found: Error: Can't resolve '@ngrx/store' in 'C:\Playground\ngrx\platform\example-app\app\auth\containers'
 @ ./example-app/app/auth/containers/login-page.component.ts 11:0-36
 @ ./example-app/app/auth/auth.module.ts
 @ ./example-app/app/app.module.ts
 @ ./example-app/main.ts
 @ multi ./example-app/main.ts

ERROR in C:/Playground/ngrx/platform/example-app/app/auth/effects/auth.effects.ts (8,33): Cannot find module '@ngrx/effects'.

ERROR in ./example-app/app/auth/effects/auth.effects.ts
Module not found: Error: Can't resolve '@ngrx/effects' in 'C:\Playground\ngrx\platform\example-app\app\auth\effects'
 @ ./example-app/app/auth/effects/auth.effects.ts 17:0-48
 @ ./example-app/app/auth/auth.module.ts
 @ ./example-app/app/app.module.ts
 @ ./example-app/main.ts
 @ multi ./example-app/main.ts

ERROR in C:/Playground/ngrx/platform/example-app/app/auth/reducers/index.ts (1,55): Cannot find module '@ngrx/store'.

ERROR in ./example-app/app/auth/reducers/index.ts
Module not found: Error: Can't resolve '@ngrx/store' in 'C:\Playground\ngrx\platform\example-app\app\auth\reducers'
 @ ./example-app/app/auth/reducers/index.ts 1:0-68
 @ ./example-app/app/auth/auth.module.ts
 @ ./example-app/app/app.module.ts
 @ ./example-app/main.ts
 @ multi ./example-app/main.ts

ERROR in C:/Playground/ngrx/platform/example-app/app/core/actions/layout.ts (1,24): Cannot find module '@ngrx/store'.

ERROR in C:/Playground/ngrx/platform/example-app/app/auth/actions/auth.ts (1,24): Cannot find module '@ngrx/store'.</code></pre>

## Expected behavior:
A succesful build.

## Minimal reproduction of the problem with instructions:
Pull the repo from github.
npm install
ng build

## Version of affected browser(s),operating system(s), npm, node and ngrx:
Windows 10
npm: 5.4.1
node: 6.10.3
Angular CLI: 1.3.0

## Other information:
I also tried without building without aot, but that doesn't make a difference.
Does anyone have an idea what might be the issue?

**Comment by pierre-hilt** [comment]
Hello, have you tried to build using npm run build?

**Comment by Jrubzjeknf** [comment]
@pierre-hilt yup, that did it. After an `npm run build` I can now use `ng build` and `ng serve`. Issue solved. :) Cheers!
