### ISSUE TITLE
Update createFeatureSelector in docs to use the non-deprecated signature

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#3724]
### Information

The docs about `createFeatureSelector` use a deprecated signature.
For example,

```ts
export const selectFeature = createFeatureSelector<AppState, FeatureState>(featureKey);
```

Should become

```ts
export const selectFeature = createFeatureSelector< FeatureState>(featureKey);
```

### Documentation page

https://ngrx.io/guide/store/selectors

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by briannarenni** [comment]
Hi, can I have this assigned to me? If the only changes needed are in the selectors.md file, I can open a PR right away.

**Comment by markostanimirovic** [comment]
Hi @briannarenni 👋 

Yes! Changes are needed in the `selectors.md` file.

**Comment by briannarenni** [comment]
> Hi @briannarenni 👋
> 
> Yes! Changes are needed in the `selectors.md` file.

Great, the changes are done! I was looking for a good first issue so happy to help.

Question before I submit a bad PR: I ran the `build`, `lint`, `start/docs`, and `test` commands, all passed. Am I missing anything needed? PR is able to merge as well.

**Comment by markostanimirovic** [comment]
@briannarenni

Sounds good! Feel free to create the PR. :)

**Comment by briannarenni** [comment]
Done: [PR 3275](https://github.com/ngrx/platform/pull/3599)
