### ISSUE TITLE
Lazy loading scenario

### ISSUE THREAD

**Issue by joelmuskwe** [ngrx/platform#373]
Hi i got a small question pertaining to ngrx i have two lazy loaded modules and i have a scenario where i have aonther third module named shared and i want these two modules to have access to the store that i want to put in the shared module. do you have any ideas how i can make this work.

**Comment by brandonroberts** [comment]
The `Store` isn't something you put in a shared module to include in your feature modules. You only need register the Store using `StoreModule.forRoot` in the root NgModule, and then the `Store` service is available globally. Then any modules whether loaded lazily or not will be able inject the `Store` and have access to the global state.
