### ISSUE TITLE
Module '"@angular/core"' has no exported member 'EnvironmentProviders'

### ISSUE THREAD

**Issue by ronaksonigara** [ngrx/platform#3734]
### Which @ngrx/* package(s) are the source of the bug?

store

### Minimal reproduction of the bug/regression with instructions

Got this error with getting started with ngrx

<img width="572" alt="image" src="https://user-images.githubusercontent.com/53657287/210175156-d352f3c0-a848-4131-9ddc-ee5eb20a1616.png">

<img width="392" alt="image" src="https://user-images.githubusercontent.com/53657287/210175182-5d2d2ed6-a0a9-4f17-88e4-2eea4359cf0a.png">

### Minimal reproduction of the bug/regression with instructions

Just followed the Getting started Tutorial

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx: 15.1.0
Angular: 14.2.10
Node: 14.18.3

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by ronaksonigara** [comment]
closing this issue as it worked,
i was installing the wrong version of ngrx

**Comment by Hemant-Lohni** [comment]
please tell which version of ngrx is compatible with ang 14

**Comment by ronaksonigara** [comment]
> please tell which version of ngrx is compatible with ang 14

ngrx version 14.x with angular version 14
