### ISSUE TITLE
RFC: Introduce object signature for `tapResponse` and provide ability to pass `finalize` callback

### ISSUE THREAD

**Issue by markostanimirovic** [ngrx/platform#3739]
### Which @ngrx/* package(s) are relevant/related to the feature request?

component-store

### Information

The `tapResponse` operator would accept the config (observer) object, where `next` and `error` callbacks will still be required properties:

```ts
tapResponse({
  next: (users) => this.patchState({ users }), // required
  error: (error: HttpErrorResponse) => this.logError(error), // required
  finalize: () => this.patchState({ isLoading: false }), // optional
  complete: () => console.log('complete') // optional
})
```

Similar to the `tap` operator, `finalize` callback will be executed on complete, error, or unsubscribe.

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by timdeschryver** [comment]
Would this also work with RxJS v6?

**Comment by markostanimirovic** [comment]
> Would this also work with RxJS v6?

Good point! We can make it compatible with RxJS 6 by using the `finalize` operator instead of the `finalize` prop from `TapObserver` introduced in v7.
