### ISSUE TITLE
StoreDevtoolsModule: Instrument only with extension for production mode?

### ISSUE THREAD

**Issue by maxime1992** [ngrx/platform#374]
## I'm submitting a...

<pre><code>
[ x ] Documentation issue or request
</code></pre>

## What is the current behavior?
In order to use the devtool, I have the following code:

```
!environment.production
      ? StoreDevtoolsModule.instrument({ maxAge: 50 })
      : [],
```

The thing is, I used to do `StoreDevtoolsModule.instrumentOnlyWithExtension()`

## Expected behavior:
I'd like to be able to use the redux devtools even in production IF the extension is present and launched.

How can I do that with ngrx V4 and the latest devtools?

**Comment by AhsanAyaz** [comment]
@maxime1992 I went through the forked code. 
I don't see `instrumentOnlyWithExtension` anymore in the code. 
@brandonroberts is there a possibility to bring that back?

**Comment by roopkt** [comment]
@brandonroberts should I work on this?

**Comment by maxime1992** [comment]
@roopkt have you tried something? :)

It's been two months and a half without any "official" answer and I think that if you know how to start on this it might be :ok_hand:

**Comment by roopkt** [comment]
Hi @maxime1992 ,
I started working on this and then stopped. 
Because, I am waiting for @brandonroberts to approve for starting a pull request.

**Comment by nickroberts** [comment]
Check the [migration guide](https://github.com/ngrx/platform/blob/master/MIGRATION.md#ngrxstore-devtools) on how to handle in production.

**Comment by brandonroberts** [comment]
@roopkt @maxime1992 we [removed this option](https://github.com/ngrx/platform/pull/57/files) previously because of injector issues with Angular. It also streamlined the code path for instrumenting. I'd be open to this being added back if its reliable.

**Comment by maxime1992** [comment]
@Lobaton2020 the recommended way is now documented here: https://ngrx.io/guide/store-devtools/recipes/exclude

I've been using this for a long time and it works perfectly too :)
