### ISSUE TITLE
use 'inject' in reducer

### ISSUE THREAD

**Issue by jiangyh1024** [ngrx/platform#3749]
### Which @ngrx/* package(s) are relevant/related to the feature request?

store

### Information

I'm using ng14.

when initializing the state, I wanna retrieve the data from localestorage which I encapsulated in a service called StorageService

<img width="734" alt="image" src="https://user-images.githubusercontent.com/34930870/211955588-521143e2-3679-4076-855b-58872e07d161.png">

I tried using

const storageService = inject(StorageService) --->  inject method is provided by Ng14

but it didn't work

### Describe any alternatives/workarounds you're currently using

<img width="800" alt="image" src="https://user-images.githubusercontent.com/34930870/211955851-a32988ea-c26b-4166-b01b-5cc4e3ac16a6.png">

this works, but it seems that is requires that the service has no other dependencies, otherwise we should specify deps

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by jiangyh1024** [comment]
oh ok. Thx for the explanation.

**Comment by Armenvardanyan95** [comment]
@jiangyh1024 you're welcome!
