### ISSUE TITLE
Dependency issue since v15.1

### ISSUE THREAD

**Issue by Wykks** [ngrx/platform#3750]
### Which @ngrx/* package(s) are the source of the bug?

effects

### Minimal reproduction of the bug/regression with instructions

Since v15.1.0, the package @ngrx/effects depends on @ngrx/store

Note: I'm using @ngrx/effects package just to have the "concatLatestFrom" operator
I prefer to use @ngrx/component-store instead of @ngrx/store and this operator is also usefull with component-store only.

### Minimal reproduction of the bug/regression with instructions

Install @ngrx/effects without @ngrx/store

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx: 15.1.0

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Not sure where this hard dependency is coming from. Its a peer dependency according to the `package.json` 

https://unpkg.com/@ngrx/effects@15.1.0/package.json

**Comment by markostanimirovic** [comment]
Hi @Wykks,

Take a look at this example: https://stackblitz.com/edit/angular-c2ybtn?file=src%2Fapp%2Fapp.component.ts,package.json

There is a compilation error with `@ngrx/effects` v15.1.0 or any other version when its APIs are used, but `@ngrx/store` is not installed. Therefore, `@ngrx/effects` doesn't have `@ngrx/store` as a hard dependency. Instead, it needs to be explicitly installed.

**Comment by Wykks** [comment]
Actually, the is an issue, with the correct version :) : https://stackblitz.com/edit/angular-c2ybtn-s77ysw?file=src/app/app.component.ts

**Comment by Wykks** [comment]
Still an issue with v15.3.0 https://stackblitz.com/edit/angular-c2ybtn-gyw4ut?file=package.json 
Can you re-open ? @markostanimirovic

**Comment by Wykks** [comment]
Solved with @ngrx/operators package 👍
