### ISSUE TITLE
eslint rule to warn against a parallel source of data

### ISSUE THREAD

**Issue by moniuch** [ngrx/platform#3751]
### Which @ngrx/* package(s) are relevant/related to the feature request?

eslint-plugin

### Information

I would propose that ngrx have an eslint rule to help users maintain the smart/dumb components paradigm in their codebases and prevent a component from getting data from other source(s).

I imagine this could be achieved by checking:

- for `store`: whether `Store` is injected (in constructor or via `inject()`) into a component that has `@Input`
- for `component-store`: whether the component class `extends ComponentStore`

### Describe any alternatives/workarounds you're currently using

While this does not guard against the problem in 100% (one could still get data from another injected service or token), it would prevent most of the cases. Also, the violation messages in IDE would have a great educational value for inexperienced users.

I have seen a lot of projects where no one had prevented introducing "a second source of truth" during a code review and the components then became hell to debug or refactor.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by timdeschryver** [comment]
Hi, thanks for raising this issue.
I'm going to close this one because I think that we can't provide a working rule that works in all scenarios (as mentioned in the issue description).
