### ISSUE TITLE
Error while loading rule '@ngrx/avoid-cyclic-effects': You have used a rule which requires parserServices to be generated. 

### ISSUE THREAD

**Issue by jerryorta-dev** [ngrx/platform#3757]
### Which @ngrx/* package(s) are the source of the bug?

`@ngrx/effects`

### Minimal reproduction of the bug/regression with instructions

The error occurs on every `*.effects.ts` file on a fresh install of `@ngrx/effects@15.0.0`. Here is the  [git commit](https://github.com/UIUXEngineering/ng-patterns/commit/6eceff3e6ff4e30bb5fc550b54716536b1f38109) in a public repo to fix the issue.

Steps I took to fix:

Make sure deps are added:

```
yarn upgrade @ngrx/eslint-plugin --latest
yarn add eslint-plugin-ngrx --dev
``` 

In the root `.eslintrc.json` file make sure the `ngrx` plugin is in the overrides node:

```
"overrides": [  
  {  
    ...
    "plugins": [..., "ngrx"],
    ...
```

In the projects `.eslintrc.json` file, make sure the parser config is added and is in the overrides node:

**Note: map the tsconfig from the root directory.**

```
"overrides": [  
  {  
    ...,
    "parserOptions": {  
      "project": ["libs/packages/firebase/tsconfig.lib.prod.json"],  
      "createDefaultProgram": true  
    },
    ...
```

### Minimal reproduction of the bug/regression with instructions

No error for `@ngrx/avoid-cyclic-effects`

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx: 15+
Angular: 15+
Nx: 15+

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by timdeschryver** [comment]
@jerryorta-dev it appears you're using `eslint-plugin-ngrx` which is deprecated in favor of `@ngrx/eslint-plugin`. You should remove the `eslint-plugin-ngrx` package and `ngrx` from the ESLint plugins.

Instead use the `@ngrx` plugin, or more preferably use the preset configurations, e.g. `@ngrx/all`.

This made me think that we have to improve the docs though.
For now, for more info see https://github.com/ngrx/platform/issues/3658
