### ISSUE TITLE
[@ngrx/data] Undo doesn't remove a property that was missing in the original state

### ISSUE THREAD

**Issue by amakhrov** [ngrx/platform#3766]
### Which @ngrx/* package(s) are the source of the bug?

data

### Minimal reproduction of the bug/regression with instructions

n/a

### Minimal reproduction of the bug/regression with instructions

TaskEntity:
```
{
  id: number,
  completedAt?: number // optional timestamp
}
```

Original entity in the state cache:
```
{
  id: 1
  // Note: completedAt timestamp is missing, since this task is not completed yet
}
```

The optimistic update operation brings it to the following state:
```
{
  id: 1,
  completedAt: <current timestamp>
}
```

If the ajax request fails, I issue the `UNDO_ONE` action, expecting it to return the entity to the original state.
What actually happens, is after the UNDO action, the entity still has its `completedAt` property.

I understand it's because it uses `upsert` under the hood, which merges two states, instead of replacing.

Note that a possible workaround is changing the original state from `{id: 1}` to `{id: 1, completedAt: undefined}`.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx: 14.3
ANgular: 14.2
Browser: Firefox
OS: MacOS

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by timdeschryver** [comment]
This is the intended behavior.
The workaround is to explicitly add the property as mentioned in the issue description.
