### ISSUE TITLE
Support `factory selectors` in the `extraSelectors` property of `createFeature()`

### ISSUE THREAD

**Issue by pablomaurer** [ngrx/platform#3768]
### Which @ngrx/* package(s) are relevant/related to the feature request?

store

### Information

Recently the great @markostanimirovic created the cool feature https://github.com/ngrx/platform/pull/3744 to support `extraSelectors` in the `createFeature()` function. But `extraSelectors` does not support `factory selectors` which is needed if the selector needs any `parameters`.

Would be really cool if `extraSelectors` would support `factory selectors`.

### Describe any alternatives/workarounds you're currently using

Just use `createFeature()` like before `extraSelectors` where available as documented in https://github.com/ngrx/platform/issues/3719

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by markostanimirovic** [comment]
Hey Pablo 👋 

I already fixed this issue in this PR: https://github.com/ngrx/platform/pull/3767

It will be published in the next NgRx version. 🚀

**Comment by pablomaurer** [comment]
You're too fast! 🚀 Thank you! ❤️
