### ISSUE TITLE
Short circuit selectors

### ISSUE THREAD

**Issue by ethanve** [ngrx/platform#377]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
If we have a selector for a property that doesn't exist then ngrx throws an error.
For example lets say we have the following object:

```
{ 
  a: {
    title: "Hello World"
 }
}
```
if we defined these selectors:
```
const selectResponse = createFeatureSelector('response');
const selectA = createSelector(selectResponse, (state) => state.a);
const selectTitle = createSelector(selectA, (state) => state.title);
```
Let's say for whatever reason the response is malformed with `a` as undefined:

```
{ 
  a: undefined
}
```

ngrx selectors will throw an error.

## Expected behavior:
What would be great if ngrx would short circuit the selector and return undefined, no matter the depth of the selection

**Comment by deftomat** [comment]
The same for me. I'm currently using this helper function: 
```
export function safe<I, O>(fn: Selector<I, O>) {
  return (data: I): O => {
    try {
      return fn(data);
    } catch (e) {
      if (e instanceof TypeError) return undefined;
      throw e;
    }
  };
}

interface Selector<I, O> {
  (state: I): O;
}
```

It can be used like this: 
```
const selectResponse = createFeatureSelector('response');
const selectA = createSelector(selectResponse, (state) => state.a);
const selectTitle = createSelector(selectA, safe((state) => state.title));
```

However, you must not forget to use it. 

Anyway, I agree, its is a selector, so maybe it should behave like this in default. So, when you will create a selector, you will get a memoized function which is safe when anything in a chain is undefined.

**Comment by brandonroberts** [comment]
I don't think its good practice to selectors to "eat" errors. It makes them harder to debug in the case that something is undefined due to user error or data being undefined. Creating helper functions works nicely here, but is not something that the library should impose.
