### ISSUE TITLE
Update year in the license to 2023 🎄 

### ISSUE THREAD

**Issue by markostanimirovic** [ngrx/platform#3771]
### Information

The year should be updated in the [`footer.component.html`](https://github.com/ngrx/platform/blob/master/projects/ngrx.io/src/app/layout/footer/footer.component.html#L20) and [`LICENCE`](https://github.com/ngrx/platform/blob/master/LICENSE#L3) files.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by Soumya-Kushwaha** [comment]
> ### Information
> The year should be updated in the [`footer.component.html`](https://github.com/ngrx/platform/blob/master/projects/ngrx.io/src/app/layout/footer/footer.component.html#L20) and [`LICENCE`](https://github.com/ngrx/platform/blob/master/LICENSE#L3) files.
> 
> ### Documentation page
> _No response_
> 
> ### I would be willing to submit a PR to fix this issue
> * [x]  Yes
> * [ ]  No
