### ISSUE TITLE
Default selectId function for EntityAdapter

### ISSUE THREAD

**Issue by code2nguyen** [ngrx/platform#378]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

I have several entities, and I use always id property for the primary key.  So, to create the EntityAdater I must repeat the code like:

```JS
export const myEntityAdapter: EntityAdapter<MyEntity> = createEntityAdapter<MyEntity>({
  selectId: (myEntity: MyEntity) => myEntity.id
});
```
## Expected behavior:

This could be greate if createEntityAdapter uses a default selectId method which will take <code>id</code> property of object as a primary key. So I just need call this function
 ```JS
export const myEntityAdapter: EntityAdapter<MyEntity> = createEntityAdapter<MyEntity>();
```

**Comment by brandonroberts** [comment]
Fixed via #405
