### ISSUE TITLE
ProvideMockStore doesn't provide initialState in standalone components

### ISSUE THREAD

**Issue by bobbyg603** [ngrx/platform#3780]
### Which @ngrx/* package(s) are the source of the bug?

store

### Minimal reproduction of the bug/regression with instructions

I've created a GitHub reproduction for this issue because I wasn't sure how to get StackBlitz to run tests. The example that demonstrates this issue is available [here](https://github.com/bobbyg603/ngrx-issue-3780).

1. Follow the [Getting Started Guide](https://ngrx.io/guide/store) to create a simple NgRx example
2. Convert MyCounterComponent to a standalone component and add a [Provider](https://github.com/bobbyg603/ngrx-bug/blob/c149b783cbd8c0a45cdb6230c998a9b5ac044bae/src/app/my-counter/my-counter.component.ts#L11) for `Store`
3. Run the app to verify everything is working
4. [Write a test](https://github.com/bobbyg603/ngrx-bug/blob/c149b783cbd8c0a45cdb6230c998a9b5ac044bae/src/app/my-counter/my-counter.component.spec.ts#L34-L40) for verifying the first value from `count$` is equal to some [initialState](https://github.com/bobbyg603/ngrx-bug/blob/c149b783cbd8c0a45cdb6230c998a9b5ac044bae/src/app/my-counter/my-counter.component.spec.ts#L20) provided via `provideMockStore`
5. Notice that `store.select` ignores the `initialialState` value provided to `provideMockStore` and `count$` emits undefined

### Minimal reproduction of the bug/regression with instructions

The store that's injected into the component under test should contain initialState.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx 15.0
Angular 15.1
Node 18
Chrome 110

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by markostanimirovic** [comment]
Hi @bobbyg603

You need to remove `Store` from the `MyCounterComponent` providers array and tests will succeed:

```diff
@Component({
  selector: 'app-my-counter',
  standalone: true,
  imports: [CommonModule],
-  providers: [Store],
  templateUrl: './my-counter.component.html',
  styleUrls: ['./my-counter.component.scss']
})
export class MyCounterComponent {
  count$: Observable<number>;
  /* ... */
```

You should not provide the global `Store` at the component level.

**Comment by bobbyg603** [comment]
> Hi @bobbyg603
> 
> You need to remove `Store` from the `MyCounterComponent` providers array and tests will succeed:
> 
> ```diff
> @Component({
>   selector: 'app-my-counter',
>   standalone: true,
>   imports: [CommonModule],
> -  providers: [Store],
>   templateUrl: './my-counter.component.html',
>   styleUrls: ['./my-counter.component.scss']
> })
> export class MyCounterComponent {
>   count$: Observable<number>;
>   /* ... */
> ```
> 
> You should not provide the global `Store` at the component level.

Thanks for your help! I haven't had a chance to try it yet, but I'll report back if something goes awry.
