### ISSUE TITLE
ESLint plugin wrongfully enforces a selector related rule on a feature created by `createFeature`  

### ISSUE THREAD

**Issue by Armenvardanyan95** [ngrx/platform#3786]
### Which @ngrx/* package(s) are the source of the bug?

eslint-plugin

### Minimal reproduction of the bug/regression with instructions

To reproduce this bug, create a feature using `createFeature` and add a selector with `extraSelectors`. The ESLint plugin will enforce the [prefix-selectors-with-select](https://ngrx.io/guide/eslint-plugin/rules/prefix-selectors-with-select) rule on the **feature** itself and throw an error/warning. For example:

```typescript
export const authFeature = createFeature({
  name: 'auth'.
  reducer: authReducer,
  extraSelectors: ({selectToken}) => ({
    selectIsAuthorized: createSelector(selectToken, token => !!token)
  }),
})
```

Here, the plugin will throw an error: `The selector should start with "select"`

### Minimal reproduction of the bug/regression with instructions

ESLint plugin should not treat features as it does selectors. When no `extraSelectors` are added, issue is not present

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

@ngrx/eslint-plugin: 15.2.1
Angular: 15.1.0
NodeJS: 18.12.1
Browser: N/A
Operating System: Windows

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by timdeschryver** [comment]
Do you want to create a pull request for this @Armenvardanyan95 ?
Otherwise I'll pick this up.

**Comment by Armenvardanyan95** [comment]
@timdeschryver I would love to, but I'm not very well versed in writing eslint plug-ins,  though with some guidance I might try if it isn't super urgent. Anything I can read on the topic?

**Comment by timdeschryver** [comment]
Sorry I don't got any good resource I think for this.
https://astexplorer.net/ is helpful to get to know the AST structure, but it doesn't help with writing rules.

**Comment by Armenvardanyan95** [comment]
@timdeschryver I see you already created a PR. Thanks for the resource - it is really useful!

**Comment by a-boertien** [comment]
Still happening for me on Angular 17.1.2 & ngrx 17.1.0

**Comment by timdeschryver** [comment]
@a-boertien can you share the `createFeature` method that causes this issue?

**Comment by a-boertien** [comment]
Sure:

`
export const niceFeature = createFeature({
	name: 'nice',
	reducer,
	extraSelectors: ({ selectNiceState }) => ({
		selectSelectedFoo: createSelector(
			selectNiceState,
			state => state.foo ?? null,
		),
		selectBar: createSelector(
			selectNiceState,
			state => state.bar,
		),
	}),
});
`

**Comment by timdeschryver** [comment]
I'm not able to reproduce this @a-boertien .
Can you also make sure that the NgRx eslint package that is installed also is on v17.1.x?
If you're comfortable with it, could you share the whole file?

**Comment by a-boertien** [comment]
@timdeschryver 
Whoops... our project was using eslint-plugin-ngrx (which we didn't realise was deprecated)
I've now migrated to @ngrx/eslint-plugin and all is good!
Thanks & sorry for the false alarm 🙇
