### ISSUE TITLE
Make the `@ngrx/component` declarables standalone

### ISSUE THREAD

**Issue by markostanimirovic** [ngrx/platform#3804]
### Which @ngrx/* package(s) are relevant/related to the feature request?

component

### Information

Make the `LetDirective` and `PushPipe` standalone and deprecate `LetModule` and `PushModule`.

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by adyngom** [comment]
@markostanimirovic how far along are you with this one and would it be a good candidate for a first issue to tackle? Cheers

**Comment by markostanimirovic** [comment]
@adyngom

I haven't started working on it yet. Do you want to take it?

**Comment by adyngom** [comment]
@markostanimirovic yes definitely want to take a stab at it.

**Comment by stefanoslig** [comment]
Hi @adyngom! I did some initial work on this issue. If you still want to work on it, feel free to check my PR. You can create yours and I can close mine. If not, I could finalize what I started 🙂

**Comment by markostanimirovic** [comment]
We plan to release this feature in v16. @adyngom let me know if you don't have time to work on this issue, and I'll take it.

**Comment by stefanoslig** [comment]
I did some initial work here: https://github.com/ngrx/platform/pull/3826

I closed this PR so @adyngom can work on this. If you don't have time I can also reopen the PR

**Comment by adyngom** [comment]
Hello @markostanimirovic @stefanoslig I'm honestly having trouble finding time and would not like to cause any delays. I'll try to contribute in other ways in the near future. So please move it forward and sorry about the hold up :(

**Comment by markostanimirovic** [comment]
No worries Ady, thanks for the update!
