### ISSUE TITLE
Dark theme for ngrx.io

### ISSUE THREAD

**Issue by aak-78** [ngrx/platform#3805]
### Information

Please add dark theme. for documentation web site. Please, please

### I would be willing to submit a PR to fix this issue

- [x] Yes
- [ ] No

**Comment by timdeschryver** [comment]
Feel free to pick this one up.
If you do, please drop your name here so we don't do double work.
As a reference, we can take a look at the Angular PR https://github.com/angular/angular/pull/41129

**Comment by GKarlos** [comment]
Hello again! It seems like no one else is working on this, so I'm willing to give it a try. I'll go through the PRs at https://github.com/angular/angular/pull/41129 before starting, so it may take some time.

**Comment by va-stefanek** [comment]
If no one is working on that I can take care of it.

**Comment by markostanimirovic** [comment]
Thanks @va-stefanek!

**Comment by vvolodin** [comment]
How do I switch to light theme?
