### ISSUE TITLE
https://ngrx.github.io/platform/stackblitz.html throws an error in AuthEffects

### ISSUE THREAD

**Issue by omegaula** [ngrx/platform#3809]
### Which @ngrx/* package(s) are the source of the bug?

effects

### Minimal reproduction of the bug/regression with instructions

1. Go to https://ngrx.github.io/platform/stackblitz.html
2. Observe that the demo page keeps showing "Loading..." forever
3. Observe this error in the dev tool console
```
zone.js:682 Unhandled Promise rejection: Cannot read properties of undefined (reading 'pipe') ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read properties of undefined (reading 'pipe')
    at <instance_members_initializer> (auth.effects.ts:28:28)
    at new AuthEffects (auth.effects.ts:37:16)
```

### Minimal reproduction of the bug/regression with instructions

The example should work

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

Whatever https://ngrx.github.io/platform/stackblitz.html does

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
The StackBlitz example is not maintained. If its linked somewhere we can update that. I'd recommend looking at the current example app
