### ISSUE TITLE
ngrx entity adapter misses sort when updating elements

### ISSUE THREAD

**Issue by daniel-zero** [ngrx/platform#3812]
### Which @ngrx/* package(s) are the source of the bug?

entity

### Minimal reproduction of the bug/regression with instructions

Create a new entity adapter with any custom interface. Use the custom selectId and sortComparer functions.

```ts
export interface CustomData {
customId: string;
orderId: number;
}

const sortByOrderId = (a: CustomData, b: CustomData): number => {
  return b. orderId r - a. orderId r;
};

export const watchlistAdapter = createEntityAdapter< CustomData >({
  selectId: (item) => item. customId,
  sortComparer: sortByOrderId,
});
```

Call any adapter helper function in a reducers to update an element.

The updated element will be always placed at the bottom of the entity list. It will be not sorted as described in the `sortByOrderId` function

### Minimal reproduction of the bug/regression with instructions

See regression description.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

Latest Version of NGRX and Angular v15.1

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Most likely this is due to your custom sort function. Feel free to add a reproduction as we have tests to verify the behavior is correct
