### ISSUE TITLE
Remove the deprecated createFeature signature

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#3814]
### Which @ngrx/* package(s) are relevant/related to the feature request?

store

### Information

Remove the deprecated createFeature signature.

This method was deprecated in https://github.com/ngrx/platform/issues/3737

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by apramendorfer** [comment]
I could open a PR for this one aswell 😃

**Comment by apramendorfer** [comment]
I haven't started so go ahead 👍

**Comment by timdeschryver** [comment]
Just as a heads-up, these PRs will remain open until we start with our RC for v16.
