### ISSUE TITLE
store/createFeature

### ISSUE THREAD

**Issue by michalgrzegorczyk-dev** [ngrx/platform#3817]
### Information

In the last example 'Creating Feature with Extra Selectors'

1. It should be      `...adapter.getSelectors(selectProductsState),` instead of `...adapter.getSelectors(selectBooksState),`
2. No idea what getCallStateSelectors is exactly so when I copy the code it does not work - please add source of getCallStateSelectors.

### Documentation page

https://ngrx.io/api/store/createFeature

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [x] No

**Comment by MAMCallejo** [comment]
Hey it's my first contributing and I would love to handle this one.

**Comment by MAMCallejo** [comment]
As to the `getCallStateSelectors ` I cannot find any other instances where this is used. Could you maybe give me some more context about it?

**Comment by MAMCallejo** [comment]
From my research, it seems the example code snippet was added on this [MR](https://github.com/ngrx/platform/pull/3744). Also, @markostanimirovic mentions on this [comment](https://github.com/ngrx/platform/issues/3719#issuecomment-1362732960) the existence of the `getCallStateSelectors` function. However, I cannot seem to find this function on the repository. Is it provided by an external dependency? Or maybe it was removed entirely?

**Comment by michalgrzegorczyk-dev** [comment]
Imo, we can add implementation of `getCallStateSelectors` ;) You can run this code on your local machine and you will see that this part is not working fully because of `extraSelectors` ;) It should work after copying this code :) 

```
const {
  name,
  reducer,
  // feature [selector](https://ngrx.io/api/store/testing/MockSelector#selector)
  selectProductsState,
  // feature [state](https://ngrx.io/api/store-devtools/StoreDevtools#state) properties selectors
  selectIds,
  selectEntities,
  selectCallState,
  // selectors returned by `adapter.getSelectors`
  selectAll,
  selectTotal,
  // selectors returned by `getCallStateSelectors`
  selectIsLoading,
  selectIsLoaded,
  selectError,
} = productsFeature;
```

**Comment by markostanimirovic** [comment]
The idea was to show how `createFeature.extraSelectors` can be used with `entityAdapter.getSelectors` or any other function that returns a dictionary of selectors. The `getCallStateSelectors` function was just used as an example. At the end of the example we can see what's the result of the `getCallStateSelectors` function:

```
  // selectors returned by `getCallStateSelectors`
  selectIsLoading,
  selectIsLoaded,
  selectError,
```

It's also shown what's the input argument of the `getCallStateSelectors` function.  Therefore, I think it's clear enough how this function should look based on its result and input argument.

I'd keep the examples from API docs concise and focus here on the `extraSelectors` feature, not on the implementation of helper functions. We already have a dedicated page for the `createFeature` function that contains more details and full examples: https://ngrx.io/guide/store/feature-creators
