### ISSUE TITLE
can effects .ofType() accept multiple actions

### ISSUE THREAD

**Issue by aavelyn** [ngrx/platform#383]
## I'm submitting a...
[x] Documentation issue or request

Is it possible to set up an Effect that accepts multiple .ofType inputs?
Basically I want to "listen" to several actions in one effect in order to return the same new action.

`this.actions$.ofType(fromHska.ActionTypes.COURSE_ADD_TODO || fromHska.ActionTypes.COURSE_ADD_TRACK)`

**Comment by brandonroberts** [comment]
Yes, you pass multiples as arguments to `ofType`

https://github.com/ngrx/platform/blob/master/docs/effects/api.md#oftype
