### ISSUE TITLE
ESLint plugin does not work correctly when the `inject` function is used

### ISSUE THREAD

**Issue by Armenvardanyan95** [ngrx/platform#3834]
### Which @ngrx/* package(s) are the source of the bug?

eslint-plugin

### Minimal reproduction of the bug/regression with instructions

For example, we want the linter to catch issues like subscribing to the store directly in components. It works correctly when the store is injected via a constructor, but fails to catch issues when the `inject` function is used

### Minimal reproduction of the bug/regression with instructions

Here the plugin will correctly catch a listing a issue:

```typescript
@Components({
  // metadata
})
export class MyComponent implements OnInit {
  constructor(private store: Store) {}

  ngOnInit() {
    this.store.select(selectSomething).subscribe(() => {
      // do something
    });
  }
}
```

But will fail to do so in the following case:

```typescript
@Components({
  // metadata
})
export class MyComponent implements OnInit {
  private store = inject(Store);

  ngOnInit() {
    this.store.select(selectSomething).subscribe(() => {
      // do something
    });
  }
}
```

It is possible the issue exists in the case of other plugin rules, but I have managed to find this one to fail 100% of the time.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx: 15.4.0
Angular: 15.1.0
Node: 18.10.0
Browsers: N/A
Operating systems: Windows 11

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by timdeschryver** [comment]
Good catch @Armenvardanyan95 .
Do do you want to help with this?

**Comment by Armenvardanyan95** [comment]
@timdeschryver I honestly want to, but I'm still quite far away from understanding how linting works under the hood. I actually dived into the source code, understood a bit, but that's it thus far. If you don't think this is super critical and wanna wait a week or so, I'm would love to try our, but obviously can't promise I will succeed
