### ISSUE TITLE
Clarifiy more on prefer-inline-action-props

### ISSUE THREAD

**Issue by JDillon522** [ngrx/platform#3837]
### Information

The eslint option `prefer-inline-action-props` makes sense but I think we need additional information on how to strongly type reducer functions or effect usages.

Example:

This is how I usually construct my actions and reducer:

```
// actions.ts
export interface IToggleToolsSidebar {
  open?: boolean;
}

export const toggleToolsSidebar = createAction(
  `${actionType} Toggle tools sidebar`,
  props<IToggleToolsSidebar>()
);

// reducer.ts
const handleToggleSidebar = (
  state: UiState,
  action: IToggleToolsSidebar
): UiState => {
  const newState = cloneDeep(state);
  newState.controlSidebarOpened =
    action.open !== undefined
      ? action.open
      : !newState.controlSidebarOpened;
  newState.controlSidebarLocked = false;

  return newState;
};
const reducer = createReducer(
  initialUiState,
  on(toggleToolsSidebar, handleToggleSidebar),
);
```

Its trivial for me to put the reducer function directly inside the `on` function but I think that gets really unwieldy later on. So in order to strongly type the `action` param in my `handleToggleSidebar` function I have to use an interface. 

Is it possible to strongly type my function to get the `props` from my action? If so I'd like to see the docs updated so that I can apply this eslint setting, otherwise I have to disable it.

### Documentation page

https://ngrx.io/guide/eslint-plugin/rules/prefer-inline-action-props

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by timdeschryver** [comment]
Hi, you can do the following to create a type.
Feel free to add it to the docs.

```ts
type toggleToolsSidebarProps = ReturnType<typeof toggleToolsSidebar>;
  

const handleToggleSidebar = (
  state: UiState,
  action: toggleToolsSidebarProps
): UiState => {
   ....
};

```

**Comment by JDillon522** [comment]
@timdeschryver that works perfectly. Thanks
