### ISSUE TITLE
Remove dev tools event listener from zone.js detection

### ISSUE THREAD

**Issue by thfsilvab** [ngrx/platform#3839]
### Which @ngrx/* package(s) are the source of the bug?

store-devtools

### Minimal reproduction of the bug/regression with instructions

- Add `StoreDevtoolsModule.instrument({})` to app.module.ts, just like in [the example](https://stackblitz.com/edit/ngrx-seed?file=src%2Fapp%2Fapp.module.ts)
- Install [Angular DevTools](https://chrome.google.com/webstore/detail/angular-devtools/ienfalfjdbdpebioblfackkekamfmbnh)
- Through Angular DevTools, start the profiler in the example
- The profiler will show a lot of change detection events caused by `Window.addEventListener:message`
- Remove `StoreDevtoolsModule.instrument({})`, repeat step 3, the change detection events won't show up anymore

### Minimal reproduction of the bug/regression with instructions

It's expected that the `StoreDevtools` doesn't trigger any change detection.
Change detection can be costly if any component do some kind of 'heavy work' like rendering multiple components with `ngForOf`, even if `StoreDevtools` logs only in development, it's still a big overhead for a development environment, depending on the size and complexity of the project.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx: 15.4.0
Angular: 15.2.3
Node: 16.16
Browser: Microsoft Edge 112.0.1722.34 (64-bit)
Operating system: Windows 10

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by thfsilvab** [comment]
Just saw there's already some guidance on this issue [documented in the code](https://github.com/ngrx/platform/blob/0ea2933d9af5f7c0ea82e2ae1e73d5388fa82728/projects/ngrx.io/src/polyfills.ts#L39):

```ts
/**
 * By default, zone.js will patch all possible macroTask and DomEvents
 * user can disable parts of macroTask/DomEvents patch by setting following flags
 * because those flags need to be set before `zone.js` being loaded, and webpack
 * will put import in the top of bundle, so user need to create a separate file
 * in this directory (for example: zone-flags.ts), and put the following flags
 * into that file, and then add the following code before importing zone.js.
 * import './zone-flags';
 *
 * The flags allowed in zone-flags.ts are listed here.
 *
 * The following flags will work for all browsers.
 *
 * (window as any).__Zone_disable_requestAnimationFrame = true; // disable patch requestAnimationFrame
 * (window as any).__Zone_disable_on_property = true; // disable patch onProperty such as onclick
 * (window as any).__zone_symbol__UNPATCHED_EVENTS = ['scroll', 'mousemove']; // disable patch specified eventNames
 *
 *  in IE/Edge developer tools, the addEventListener will also be wrapped by zone.js
 *  with the following flag, it will bypass `zone.js` patch for IE/Edge
 *
 *  (window as any).__Zone_enable_cross_context_check = true;
 *
 */
```

**Comment by brandonroberts** [comment]
Thanks @thfsilvab. I don't see in our code where we are using addEventListener directly for store-devtools.

What's the proposed fix?

**Comment by exequiel09** [comment]
This happens if the Redux Devtools is enabled when on load. You need to change the value of `Site Access` to `On Click`

![Screenshot 2023-06-26 at 1 58 38 PM](https://github.com/ngrx/platform/assets/1289472/c41a1483-f280-41b7-a41d-d2df62ea6702)
