### ISSUE TITLE
Store data dependency map

### ISSUE THREAD

**Issue by mfp22** [ngrx/platform#384]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
According to my understanding, there are 2 things to do when data is needed: Subscribe to an observable of the data in the store, and subscribe to an observable that puts the data in the store.

For example, when a smart component needs data, it selects it from the strore: `this.data$ = this.store.select(state => state.data);`. In addition, it must subscribe to some observable containing an `http` call. This observable will dispatch an action when the call is complete containing the response data, which a reducer will insert into the store. 

So there are two tasks for one idea: that the component needs the data.

## Expected behavior:
My proposal is to allow developers to define an object in the same shape as the state object, but instead of default values for state data, it would contain observables which if subscribed to, would fetch data from wherever and dispatch actions to insert the data into the store. 

Example:
`
const initialState: State = {
  users: []
}
`
<pre><code>
requireUsers$ = this.http.get(this.baseUrl + '/users')
  .map(res => res.json())
  .do(res => {
      this.store.dispatch({ type: 'RECEIVE_USERS', payload : res.users});
  })
  .share()

stateData = {
  users: this.requireUsers$
}
</code></pre>

Then, when a component selects data from the store `this.users$ = this.store.select(state => state.users)` and subscribes, behind the scences the observable which provides the data to the store is also subscribed to. So the question of when/if the data is in the store is completely removed from the consumer of the data. 

The pros/cons I see are these:
### Pros
- Separation of concerns
- When a component's data needs change, you only change what the component is selecting
- Page-level components don't need to anticipate data needs of every child smart component
- You can drop a smart component anywhere in an app, and the data it needs will still arrive. No implicit needs.
- Makes it easier to handle data dependency chains. Components can just subscribe to their data dependency, not their data dependency's data dependency (example: Get Firebase token from server, sign into Firebase, get data from Firebase. If the component just wants the data from Firebase it can just select it from the store and expect that it will show up, and none of its parent components need to care either). The reason this works is because inside `requireFirebaseData$` you might have `this.store.select(state => state.firebaseSignedIn)` which will channel `requireFirebaseSignIn$`, which will in turn channel `requireFirebaseToken$`.
- Requests get canceled when you navigate away from the component using the data and no other subscribers remain
- You don't need to know what other components are doing to avoid fetching data multiple times 
### Cons
- May be complicated to implement

There might be plenty of cons I haven't thought of. But right now it seems like this would be amazing to have.

**Comment by brandonroberts** [comment]
The issue I see with it is that this couples the components to your state, and couples your state to http requests that are dispatching actions. This is where `@ngrx/effects` plays very nicely and handles these transactions. The state's responsibility is not to fetch data for itself, but to provide an immutable structure for you to consume. The data doesn't _need_ to be refetched once in the store. Hope this helps. Thanks for the proposal!

**Comment by mfp22** [comment]
Thanks for the response!

The components don't necessarily need to be coupled to the state. You can still have a service that defines the selectors that the component uses so the component is agnostic to state. 

You have a point with the store not being responsible for its own data. Maybe my idea could be implemented as some kind of wrapper for the store, sort of like a smart store or something. To me the source of the data in the store is a concern that is closer to the store than it is to the consumer of the data in the store. So coupling the data source to the state is better than coupling the data source to the consumer of state. 

You would still use `@ngrx/effects` to handle actions dispatched from user events, but for supplying the store with some data fetched from the server, I like this proposal a lot.

About refetching data after its already in the store, that is not the behavior that I am proposing. In my example I thought `.share()` was enough to imply "This data is only fetched once."
