### ISSUE TITLE
EntityServerCommands.add does not allow optional id

### ISSUE THREAD

**Issue by Nosfistis** [ngrx/platform#3847]
### Which @ngrx/* package(s) are the source of the bug?

data

### Minimal reproduction of the bug/regression with instructions

1. Create an `EntityCollectionService`.
2. Inject it using `EntityServices.getEntityCollectionService()`.
3. Add a new entity using `add`.

The entity does not accept an optional `id` value, even if `isOptimistic` (the default) is set implicitly or explicitly.

### Minimal reproduction of the bug/regression with instructions

After #2870 the `id` is optional in `EntityCollectionServiceBase` if `isOptimistic` is set, but when getting an entity collection service through `EntityServices` the `EntityServerCommands` is used instead, which does not offer that type support.

https://github.com/ngrx/platform/blob/44827517ffb70f6d21a989f19d21341ce42e0ba6/modules/data/src/dispatchers/entity-commands.ts#L14

https://github.com/ngrx/platform/blob/44827517ffb70f6d21a989f19d21341ce42e0ba6/modules/data/src/entity-services/entity-collection-service-base.ts#L145-L152

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx: 15.3.0
Angular: 15.2.2
Node: 18.12.1

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by timdeschryver** [comment]
Feel free to create a PR for this @Nosfistis
