### ISSUE TITLE
USER_PROVIDED_EFFECTS not working after ngrx/effects@15.2.0 ? 

### ISSUE THREAD

**Issue by v-c-git** [ngrx/platform#3848]
### Which @ngrx/* package(s) are the source of the bug?

effects

### Minimal reproduction of the bug/regression with instructions

We use USER_PROVIDED_EFFECTS in combination with a function that returns injectable effect tokens from dynamically generated effects like so: 
..
 {
        provide: USER_PROVIDED_EFFECTS,
        useValue: getEffectTokens(),
        multi: true
      }

where getEffectTokens() returns an array like: 

export const getEffectTokens = () => [
  SOME_EFFECT_TOKEN,
   SOME_EFFECT_TOKEN2,
etc
];

And tokens are just NG injection tokens that use factory to create a class that derives from the base effect class in order to reduce boilerplate. 

### Minimal reproduction of the bug/regression with instructions

The code above worked fine for many releases until 15.2.0. Has something changed starting with that release that would affect USER_PROVIDED_EFFECTS ?

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NGRX: 15.2 and up
NG 15

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by v-c-git** [comment]
And here's the stackblitz: 

https://stackblitz.com/edit/angular-ivy-x2cbz5?file=src/app/app.module.ts

If you go there, let it run, then open console and you'll see output from InjectedEffect constructor. 

After that install ngrx/effects/15.2.0 or higher

Refresh - no more output from InjectedEffect constructor. It doesn't get called

**Comment by markostanimirovic** [comment]
This was a hidden feature before. 😅 

The [`USER_PROVIDED_EFFECTS` token](https://github.com/ngrx/platform/blob/master/modules/effects/src/tokens.ts#L11) expects an array of classes, not injection tokens. However, the compilation of the following code passes:

```ts
{ provide: USER_PROVIDED_EFFECTS, useValue: ['anything'] }
```
