### ISSUE TITLE
Any good doc on testing @ngrx/effects with Angular 4?

### ISSUE THREAD

**Issue by alexesca** [ngrx/platform#385]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[* ] Documentation issue or request
</code></pre>

## What is the current behavior?
I cannot find documentation on how to test @ngrx/effects

**Comment by brandonroberts** [comment]
Hey Alex,

There is a testing example in the docs: https://github.com/ngrx/platform/blob/master/docs/effects/testing.md

And multiple examples in the example app:
https://github.com/ngrx/platform/blob/master/example-app/app/books/effects/collection.spec.ts
https://github.com/ngrx/platform/blob/master/example-app/app/books/effects/book.spec.ts

If you have specific questions, our support channel is great for that: https://gitter.im/ngrx/platform
