### ISSUE TITLE
strong type State

### ISSUE THREAD

**Issue by shaman-apprentice** [ngrx/platform#3852]
### Which @ngrx/* package(s) are relevant/related to the feature request?

store

### Information

# Feature Request 

## Actual behaviour
As a developer I am interested in most strict possible type checking. When using [State](https://ngrx.io/api/store/State)'s `value` property or `getValue` method, the retrived type is any, as `State` class is defined as followed:

```js
class State<T> extends BehaviorSubject<any>
```

![ngrx getValue FR](https://user-images.githubusercontent.com/3596742/232759902-b17ef013-a118-4a58-af65-5a64008114a0.png)

## Desired new behaviour. 
State already requires a generic parameter. When we pass it through to BehaviorSubject, its `value` and `getValue` would also be strong typed.

```js
class State<T> extends BehaviorSubject<T>
```

### Some thoughts
In my opinion using `State`'s ` value` or `getValue`  are bad software design. But I am working with a legacy application and for the transition this is very handy in some parts of the software. 

When those imperative accessors are supported, I think they should be supported as well as possible, including strong typing.
 

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Thanks @shaman-apprentice. As you stated, we don't recommend using the State.getValue so I wouldn't promote or encourage usage of this.
