### ISSUE TITLE
@ngrx/updater-explicit-return-type not applied when inheritance

### ISSUE THREAD

**Issue by NicholaAlkhouri** [ngrx/platform#3868]
### Which @ngrx/* package(s) are the source of the bug?

eslint-plugin

### Minimal reproduction of the bug/regression with instructions

When the class is directly extends ComponentStore the linter detect the missing type successfully, however when not directly extends ComponentStore is the linter failed to detect the missing type.

### Minimal reproduction of the bug/regression with instructions

```typescript

interface someState {
  name: string;
}

@Injectable()
export class CompetitorsStore1 extends ComponentStore<someState> {
  // Here I get a warning from @ngrx/updater-explicit-return-type
  // `Updater` should have an explicit return type when using arrow functions:
  updateName = this.updater<string>((state, name: string) => ({
    ...state,
    name,
  }));
}

@Injectable()
export class CompetitorsStore2 extends CompetitorsStore1 {
  // Here I do not get a warning at all
  override updateName = this.updater<string>((state, name: string) => ({
    ...state,
    name,
  }));

  // Here I do not get a warning at all
  updateName2 = this.updater<string>((state, name: string) => ({
    ...state,
    name,
  }));
}
```

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx: 15.4.0
@ngrx/eslint-plugin: 15.4.0
Angular: 15.2.5
Node: 16.x

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [x] No

**Comment by timdeschryver** [comment]
Do you want to create a Pull Request for this one @NicholaAlkhouri ?

**Comment by NicholaAlkhouri** [comment]
> Do you want to create a Pull Request for this one @NicholaAlkhouri ?

sadly not, I am not very familiar with es-lint and the AST
