### ISSUE TITLE
v16/signals : Selector in pipe throws NG600 : 

### ISSUE THREAD

**Issue by JeanMeche** [ngrx/platform#3869]
Hi guys !  
Thanks for the work on your awesome lib!  I've an issue to report I've encountered while working on the upcoming v16 migration. 

I've narrowed down the error to the following issue : Having a selector in a pipe throws signals' `NG600`. 

See this [repro on stackblitz](https://stackblitz.com/edit/angular-next-8unlkk).  

A related subject has already been discussed on the angular repo : angular/angular#49967.

To me it seems a reasonable use case with ngrx. What's your thoughts about it ? 

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

* ngrx/store : 16.0.0-beta.0 
* angular/core : 16.0.0-rc.4

### I would be willing to submit a PR to fix this issue

- [X] Yes

**Comment by brandonroberts** [comment]
Hey Jean!

Much appreciated. We aren't explicitly using an `effect` or writing to a signal inside unless this is happening inside the framework/toSignal function. 

Using a selector inside a pipe shouldn't throw an error though.

What's the proposed fix?

**Comment by JeanMeche** [comment]
Hi Brandon, I don't have a fix to propose but I could if there were something to work on. 

I've narrowed it down even more : 

```
@Pipe({ name: 'test', standalone: true })
export class TestPipe implements PipeTransform {
  store = inject(Store);
  transform(s: number) {
    this.store.select('count');
    return s * 2;
  }
}
```

In the pipe triggers its that call to `select()` that triggers the error. The return value actually doesn't matter.

**Comment by JeanMeche** [comment]
Yep it's definitely related to `toSignal()`. 

Do you have any insights on why the `Store` constructor is called everytime `select()` is called ? 
That's the root issue.
