### ISSUE TITLE
docs: update action schematics overview

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#3873]
### Information

The action schematic docs still mention the use of enums and classes.

> Generates an action file that contains an enum of action types, an example action class and an exported type union of action classes.

We need to replace this and mention that `createActionGroup` is used to define the actions.

### Documentation page

https://ngrx.io/guide/schematics/action

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by GKarlos** [comment]
Hello there! If there isn't anyone already doing this, I'd like to start working on it. But as it's my first time, I may take some time opening the PR.

**Comment by brandonroberts** [comment]
Thanks @GKarlos, no problem. If you need some help or have some questions about contributing. Feels free to ask her or [on Discord](https://discord.gg/ngrx)

**Comment by GKarlos** [comment]
I hope I did everything right. While looking at the action's schema.json file, I noticed that the path option was missing on the document and that there is no skip-tests option, so that was also changed.
