### ISSUE TITLE
Migration README Error?

### ISSUE THREAD

**Issue by dolanmiu** [ngrx/platform#388]
I am reading: https://github.com/ngrx/platform/blob/master/MIGRATION.md

And there is this snippet. It says now, `payload` is no longer in the `Actions` interface, but from what I can see in the example below, it is still there? Am I being stupid, or is this an error in the document?

```ts
.map((action: UserActions.Login) => action.payload)
```

BEFORE:
```ts
import 'rxjs/add/operator/map';
import { Action } from '@ngrx/store';
import { Observable } from 'rxjs/Observable';
import { Effect, Actions } from '@ngrx/effects';

@Injectable()
export class MyEffects {
  @Effect() someEffect$: Observable<Action> = this.actions$.ofType(UserActions.LOGIN)
    .map(action => action.payload)
    .map(() => new AnotherAction())

  constructor(private actions$: Actions) {}
}
```

AFTER:
```ts
import 'rxjs/add/operator/map';
import { Action } from '@ngrx/store';
import { Observable } from 'rxjs/Observable';
import { Effect, Actions } from '@ngrx/effects';

@Injectable()
export class MyEffects {
  @Effect() someEffect$: Observable<Action> = this.actions$.ofType(UserActions.LOGIN)
    .map((action: UserActions.Login) => action.payload)
    .map(() => new AnotherAction())

  constructor(private actions$: Actions) {}
}
```

**Comment by brandonroberts** [comment]
This is not an error in the documentation. The example shows how you would previously would have mapped an action with a payload. Since the payload property has been removed, to use the same action in V4, you have to explicitly type the action to that includes a payload property.

**Comment by bnlambert** [comment]
`Since the payload property has been removed, to use the same action in V4, you have to explicitly type the action to that includes a payload property.`

Please Please!!! can you kind update the installation example at effects to reflect the above statement.
