### ISSUE TITLE
Question: Is it OK to place some logic in action too or action needs to be clean?

### ISSUE THREAD

**Issue by petrovic-ivan** [ngrx/platform#389]
Hi,

If I have some complex logic in effects is it OK to split logic and put in action?

Example I am retrieving some data in `effects` like this:

```
  @Effect()
  dataEffects$: Observable<Action> = this.action$
    .ofType(actions.LOAD)
    .switchMap(() => {
      return this.dataService.getData()
        .map((result) => new actions.LoadSuccess(result));
    });
```
In code above I am passing `result` as action'a payload and doing some logic in action:

```
export class LoadSuccess implements PayloadAction {
  readonly type = action.LoadSuccess;
  payload: string[];
  constructor(results: any) {
    let elements: string[] = [];
    const data1 = results.first.map(first => first.data1);
    const data2 = results.second.map(second => second.data2);
    elements = data1.concat(data2).sort();
    this.payload = elements;
  }
}
```

I know that I can do this in reducers but what is the best practice: **to keep actions clean (only type and payload) or do some logic when is necessary**?

**Comment by brandonroberts** [comment]
Best practice is to keep your actions clean and not to put logic in them. Use a utility function to transform the data before passing it to the action instead.
