### ISSUE TITLE
Dispatching action ends up with error 'Writing to signals is not allowed'

### ISSUE THREAD

**Issue by mi-po** [ngrx/platform#3892]
### Which @ngrx/* package(s) are the source of the bug?

store

### Minimal reproduction of the bug/regression with instructions

when using following pattern (dispatching action in tap operator) in **component** 

```typescript
  counter: Observable<number> = this.store
    .select(fromRoot.getCount)
    .pipe(
        tap(() => this.store.dispatch(counterActions.dummy()))
    );
```

it prints an error in console
`NG0600: Writing to signals is not allowed in a `computed` or an `effect` by default.`

StackBlitz example
https://stackblitz.com/edit/ngrx-seed-bpn7h3?file=src/app/app.component.ts

### Minimal reproduction of the bug/regression with instructions

there should be no error in console

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx: 16.0.0
Angular: 16.0.0
Node: 18

### Other information

when using same pattern in **guard**, there is **no error**

this code from example-app _book-exists.guard.ts_ runs without error

```typescript
  function hasBookInApi(id: string): Observable<boolean> {
    return googleBooks.retrieveBook(id).pipe(
      map((bookEntity) => BookActions.loadBook({ book: bookEntity })),
      tap((action) => store.dispatch(action)),
      map((book) => !!book),
      catchError(() => {
        router.navigate(['/404']);
        return of(false);
      })
    );
  }
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by markostanimirovic** [comment]
Hi @mi-po,

The same behavior can be reproduced without NgRx. Take a look: https://stackblitz.com/edit/ngrx-seed-jdlhj4?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

In v16, `Store` contains the `state` signal that is updated on every state update and it behaves as any other signal which means that we cannot update its value within the effect that doesn't contain `allowSignalWrites: true`.

In Angular 16, the compiled template code of each component is wrapped with `effect` that doesn't contain `allowSignalWrites: true`, so we should not update any signal during the template creation/update phase.

In the provided example, updating the `state` signal is triggered during the template initialization by the `async` pipe. As a quick fix, you can schedule `store.dispatch` to the micro/macrotask queue:

```ts
import { asapScheduler } from 'rxjs';

class CounterComponent {
  counter$ = this.store
    .select(fromRoot.getCount)
    .pipe(
      tap(() => {
        // or use Promise.resolve/setTimeout
        asapScheduler.schedule(() => this.store.dispatch(counterActions.dummy()));
      })
    );
}
```

However, I suggest you refactor your code by separating side effects from the state observables, and not use `async` pipe to trigger side effects. This change will also solve your issue. Example:

```ts
@Component({
  template: '<p>Count: {{ count$ | async }}</p>'
})
class CounterComponent implements OnInit {
  private readonly destroyRef = inject(DestroyRef);
  private readonly store = inject(Store);

  readonly count$ = this.store.select(selectCount);

  ngOnInit(): void {
    this.doSomethingOnCountChanges();
  }

  private performEffectOnCountChanges(): void {
    this.count$.pipe(
      takeUntilDestroyed({ destroyRef: this.destroyRef })
    ).subscribe(() => {
      this.store.dispatch(/* dispatch any action */);
    });
  }
}
```

Or even better, use `@ngrx/component-store` to handle side effects at the component level. 😎

**Comment by mi-po** [comment]
Hi @markostanimirovic ,
thank you for explanation and providing example how to fix it.
In your StackBlitz example you are using signals. I didn't mention it, but I don't use signals in my code and I'm not planning to use them in near future. So it was just confusing to get an error about writing to signals.

Btw, I use `@ngrx/component-store` for new components, and now I have to migrate also old ones.

**Comment by bridzius** [comment]
Is this logic (`tap` side-effects in `AsyncPiped` component code) statically analyzable? Would it be possible to add a rule to `@ngrx/eslint-plugin` to check for it? 
This can become quite a painful breaking change in large codebases, since the only way to currently find the issues is at runtime.

**Comment by hoi4** [comment]
I could fix this issue by using `ngrxLet` instead of the `async` pipe. 

I would love to better understand this. Could someone validate this assumption and maybe explain why `ngrxLet` works?

**Comment by Mooeeezzzz** [comment]
@markostanimirovic this error is not related to signal usage 
https://stackblitz.com/edit/angular-pai2do
<img width="1125" alt="Screenshot 2023-05-19 at 09 11 12" src="https://github.com/ngrx/platform/assets/48438016/71628566-60f7-44ce-abd1-64d0b3b3cbb8">

**Comment by montella1507** [comment]
"signals" will be easy, they said.

**Comment by matiasfs12** [comment]
This is also happening to me. I ´ve just upgraded few days ago everything to v16, (Angular and NgRx) in a really large application, we are NOT using Signals.

I´m still trying to figure out where the error comes from, but apparently comes after few NgRx Actions (Global Store) as @mi-po mentioned above.

I´ll let you guys know, seems like it is not breaking anything.

**Comment by matiasfs12** [comment]
> Is this logic (`tap` side-effects in `AsyncPiped` component code) statically analyzable? Would it be possible to add a rule to `@ngrx/eslint-plugin` to check for it? This can become quite a painful breaking change in large codebases, since the only way to currently find the issues is at runtime.

That would be a solution, in my application we are using frequently this pattern, which I´m kind of agree that is not the best pratice (observable + async pipe subscription + side effect dispatching an action), however, it should never throw an error at runtime with a description which only points out **"Writing to signals is not allowed in a `computed` or an `effect` by default"**, which it´s a different scenario and perhaps, same root issue, but I think we may all agree that is not accurate.

For the people wondering how it would be the most silly sample to reproduce the error, the following Stackblitz will be useful.

https://stackblitz.com/edit/angular-np1ley?file=src%2Fmain.ts

**Comment by brandonroberts** [comment]
This issue may resolve the issue we're seeing with the select/dispatch/async pipe combination. 

https://github.com/angular/angular/pull/50522

Will try it out after the PR lands

**Comment by matiasfs12** [comment]
Thanks to @eneajaho and @alxhub, this issue will be solved shortly.

https://twitter.com/Enea_Jahollari/status/1663910022894452742

**Comment by brandonroberts** [comment]
Angular v16.0.4 has been released, including the fix to resolve the original issue. We've also released NgRx 16.0.1, including the fix for the @ngrx/component package.

**Comment by blazekv** [comment]
I have similar issue in my project which was not resolved by mentioned fixes. 

In my case problem was custom pipe which dispatch action. I know it is probably not good idea at all to create pipe and dispatch action in it. But I did not find suitable solution for my case except this one. If someone will come here with similar problem. Look at your pipe and if there is some thing like this:


```
this.store
          .select()
          .subscribe(() => {
            this.store.dispatch();
          });
```


Get rid off it. And if it is not possible I fixed it according to fix in Angular. Just wrap it with untracked:


```
untracked(() => {
this.store
          .select()
          .subscribe(() => {
            this.store.dispatch();
          });
});
```

**Comment by montella1507** [comment]
> untracked(() => {

yes..@markostanimirovic mentioned using asapScheduler.schedule(()=> {}) but that breaks ngrx/effects and pipes...  Only last call will trigger effects...

**Comment by pfeileon** [comment]
Not sure if I should open a new issue, but just by adding the router store to my app, I got this issue in a component which doesn't even use the store.

What the component does is showing a mat table with expandable rows (anchor = fragment) and subscribing to the route's fragment to support anchor linking and auto-expanding a row. Deep linking to an anchored row causes the NG0600 error once, but apart from that everything works. Even routing away and back to the component, never causes this error again. But if you _don't_ deep link to an anchor first and start with the plain table (no row expanded), a clicked row never expands as the dynamic child can't be created: "Cannot add property __NG_ELEMENT_ID__, object is not extensible".

Simply removing `provideRouterStore()` from the providers fixes this issue.

**Comment by montella1507** [comment]
I think this has nothing to do... It is funny, because... you have found the author of this issue:

https://github.com/angular/angular/issues/44610

The problem is, angular is mutating component type...

**Comment by amakhrov** [comment]
The ticket is closed, but the issue (NG0600) keeps happening. The stack trace doesn't even show our app code - just angular and ngrx internals. Specifically, ngrx-router-store

**Comment by sod** [comment]
angular v19 will loosen the grip on writing to signals inside an effect via https://github.com/angular/angular/pull/56501 & https://github.com/angular/angular/pull/57874. So the error will probably disappear in the next major.

**Comment by montella1507** [comment]
Yes,. because angular team finally realized how bad idea it was. 

It has been throwing almost everywhere in regular application.. And developer could not do anything about it.

For the instance...

1) You had created angular component powered by signals, and it had implemented Control value accessor... setting signals value inside of writeValue =>>> 100% correct usecase for signals 

2) Your colleague called form.patchValue() inside of effect =>>>> 100% correct useage for effect()

=> It throwed error. 

This is what i was talking about the ENTIRE TIME. Bad design decisions.

**Comment by rainerhahnekamp** [comment]
@montella1507, I completely agree. I’m also not a fan of the “effect-bashing” mindset, like “never use an effect.”

Angular’s current approach is to provide utility methods like linkedSignal and resource for common use cases, positioning effect as a low-level function.

That said, I’d still love to see an explicit effect in the future—but removing the write protection is already a great first step.
