### ISSUE TITLE
docs: update example deps to Angular and NgRx 16

### ISSUE THREAD

**Issue by markostanimirovic** [ngrx/platform#3893]
### Information

Example dependencies should be updated to Angular and NgRx 16.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by stefanoslig** [comment]
Hello, @markostanimirovic . I could help with this one!

**Comment by timdeschryver** [comment]
Hey @stefanoslig not to rush you, but are you busy with this task?

**Comment by stefanoslig** [comment]
Hi @timdeschryver , thanks for the reminder. 
I will open an MR tomorrow or on Thursday if that's ok

**Comment by timdeschryver** [comment]
Yea sure, even if it's later that's still OK.
Thanks in advance @stefanoslig
