### ISSUE TITLE
adapter.getSelectors(feature) overload?

### ISSUE THREAD

**Issue by moniuch** [ngrx/platform#3898]
### Which @ngrx/* package(s) are relevant/related to the feature request?

entity

### Information

When I use `createFeature` alongside with `createEntityAdapter`, then in order to export selectors I am doing something like

```ts
const {
  selectAll,
  selectTotal,
} = adapter.getSelectors();

const {
  selectStatus,
  selectError,
  selectSelectedProductId, // extra selector
} = productsFeature;

export {
  selectAll,
  selectTotal,
  selectStatus,
  selectError,
  selectSelectedProductId,
}
```

Would it be a bad idea if `adapter.getSelectors` had the third overload and accept `feature` as param:

```ts
const {
  selectAll,
  selectTotal,
  selectStatus,
  selectError,
  selectSelectedProductId,
} = adapter.getSelectors(productsFeature);
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by markostanimirovic** [comment]
Hi @moniuch,

We can add derived entity selectors to the feature object in the following way:

```ts
export const productsFeature = createFeature({
  name: 'products',
  reducer: createReducer(initialState),
  extraSelectors: ({ selectProductsState }) =>
    adapter.getSelectors(selectProductsState)
});

// `productsFeature` will contain `selectAll` and `selectTotal`
productsFeature.selectAll
productsFeature.selectTotal
```

**Comment by moniuch** [comment]
@markostanimirovic Magnificent! Thank you!
