### ISSUE TITLE
[Type Error] Nightly build for @ngrx/store

### ISSUE THREAD

**Issue by cyr-x** [ngrx/platform#39]
The compiler is throwing an error due to wrong typings for `@ngrx/store` nightly builds.

This is the error message:
```
Class 'Observable<Readonly<T>>' defines instance member property 'select', but extended class 'Store<T>' defines it as instance member function
```
I'm using RxJs v5.4.0.

**Comment by robwormald** [comment]
Typescript version?

**Comment by cyr-x** [comment]
I'm using typescript version 2.3.4

**Comment by dancancro** [comment]
@cyr-x Have you solved this yet?

I'm getting this in [my project](https://github.com/dancancro/great-big-example-application/blob/talks/package.json#L66) too. I'm using typescript 2.3.4

With rxjs 5.4.2:
```
ERROR in [at-loader] ./node_modules/@ngrx/store/src/store.d.ts:13:5
    TS2425: Class 'Observable<Readonly<T>>' defines instance member property 'select', 
but extended class 'Store<T>' defines it as instance member function.
```
With rxjs 5.0.0-beta.6, I get the above error plus several new ones like this:
```
ERROR in [at-loader] ./src/main/webapp/app/core/store/id/id.functions.ts:62:5
    TS2322: Type 'Observable<{}>' is not assignable to type 'Observable<Action>'.
```

**Comment by antonyRoberts** [comment]
@dancancro and @cyr-x Make sure you guys have deleted the @ngrx/core from your node_modules and clean up any of your code that may have made calls to it

**Comment by MikeRyanDev** [comment]
Closed with #72

**Comment by gentlejoseph** [comment]
@MikeRyanDev How come its closed with #72?

**Comment by sandraandonov88** [comment]
@gentlejoseph I am getting the same error - were you able to resolve it? Thanks

**Comment by capdiem** [comment]
@gentlejoseph @sandraandonov88 npm uninstall @ngrx/core or yarn remove @ngrx/core

**Comment by softawarriors** [comment]
I was able to resolve the same exception as suggested to remove the @ngrx/core. I would like to understand the impact area.

**Comment by softawarriors** [comment]
Removing @ngrx/core from my module fixed the issue. Using Angular4 with
        "@ngrx/effects": "^4.1.1",
        "@ngrx/store": "^4.1.1",

This problem came when I am trying to use single store with multi child state, using InjectionToken. With single store and state no problem was found.
