### ISSUE TITLE
Mismatching documentation compared to code. 

### ISSUE THREAD

**Issue by AtozEvo** [ngrx/platform#3913]
### Information

When referencing on how to use Ngrx with a fully standalone Angular (16) app, I hit an issue where the referenced code does not compile. 

When trying to register a root state to my application using `provideState()`, the document asks for 

`provideState({ game: scoreboardReducer })`

Unfortunately, either due to my lack of studying/searching, this seem to be wrong. 

After looking through the API doc for `provideState` it shows that this function take in either
- 2 parameters, `featureName` and `reducers`
`provideState(featureName: string, reducers: any, config?: any)`
**or**
 - a `FeatureSlice`, which would be 
`provideState({name:string, reducer:ActionReducer<T,V>})`

Image Reference Below. 
**Documentation**
![image](https://github.com/ngrx/platform/assets/45632351/6eeaf40f-bacd-4b2b-be23-965e89be9f36)
**Code**
![image](https://github.com/ngrx/platform/assets/45632351/214313af-d747-4a64-8816-b3b5c29da18a)

### Documentation page

https://ngrx.io/guide/store/reducers#using-the-standalone-api

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by timdeschryver** [comment]
Good catch @AtozEvo , feel free to update this snippet.

**Comment by AtozEvo** [comment]
@timdeschryver I've created a PR for the changes made to the documentation. #3916
