### ISSUE TITLE
ngrx-store-freeze project in need of a good home, consider adoption?

### ISSUE THREAD

**Issue by kylecordes** [ngrx/platform#393]
[X] Feature request

The ngrx-store-freeze project is in need of a new maintainer - the original author is currently away from the Angular ecosystem:

https://github.com/codewareio/ngrx-store-freeze/issues/17#issuecomment-329259793

The “store freeze” functionality is incredibly useful for new NgRx users. store-freeze is only 13 lines of non-blank-non-comment code, perhaps the best 13 around in terms of developer experience improvement per line. It takes away the footgun aspect of immutability,in which one can very easily, accidentally have mutating data floating around in the system fundamentally designed around immutability.

Curiously, it looks like maybe this even happened to the core NgRx team, around router state, discussed in some of these: #327 #240 #104.  It can happen to anyone.

Keeping all that in mind, I suggest that the NgRx team offer to adopt ngrx-store-freeze (it could become `@ngrx/store-freeze` ?), keep it up-to-date with Store versions, include it in automated testing and feature planning, and so on. Of course the functionality could also be built in to Store itself, but even perhaps offering to adopt this existing project would help that user base find their way home even if something lands right in Store.

**Comment by brandonroberts** [comment]
Definitely agree with this proposal. We're looking at folding freeze and logging functionality into `Store`. In the interim, I'll reach out to the developer on the existing project and see where we can go from there.

**Comment by brandonroberts** [comment]
Just an update on this. The previous maintainer transferred ownership to me yesterday. I will take a look at what needs to be updated to get the package working correctly with the current version of NgRx. Then we'll look migrating its feature set into `Store` along with any additional features needed, but for the existing user base the package name will be the same.

**Comment by kylecordes** [comment]
@brandonroberts Great, this is wonderful to hear. Since you've now adopted it, should this issue be closed?

**Comment by brandonroberts** [comment]
Yep. I consider this issue done for now.
