### ISSUE TITLE
Angular 4 Production Build fails

### ISSUE THREAD

**Issue by meinschnaeppchen** [ngrx/platform#394]
I'm currently running ngrx version 4 and I'm unable to build an angular app with 'ng build --prod'.
The error that I get is:
ERROR in 27.a70594b6b91442ef8c30.chunk.js from UglifyJs
Unexpected token operator «=», expected punc «,» [node_modules/@ngrx/store/src/utils.js:6,0][27.a70594b6b91442ef8c30.chunk.js:650,48]

**Comment by brandonroberts** [comment]
Need more information on this one. A small reproduction would be great.

**Comment by bbaia** [comment]
Same pb here. See #428

**Comment by Bulan** [comment]
Had the same on the exact same file and row with CLI 1.4.1, upgraded to CLI 1.5 and now it works
