### ISSUE TITLE
@ngrx/eslint-plugin rules don't work when Store is injected using inject(Store) instead of constructor injection

### ISSUE THREAD

**Issue by tomastrajan** [ngrx/platform#3941]
### Which @ngrx/* package(s) are the source of the bug?

eslint-plugin

### Minimal reproduction of the bug/regression with instructions

@ngrx/eslint-plugin rules don't work when Store is injected using inject(Store) instead of constructor injection

### Minimal reproduction of the bug/regression with instructions

1. create a workspace, add ngrx and ngrx eslint plugin with `strict` preset
2. create a component
3. inject store using `private store = inject(Store);`
4. add ` view = this.store.select('view');`
5. run `ng lint`
6. there will be NO linting error in the output,
7. comment out `// private store = inject(Store);`
8. add `constructor(private store: Store) {}` instead
9. run `ng lint`
10. there will be correct   error  `Using string or props drilling is forbidden. Use a selector instead  @ngrx/prefer-selector-in-select` in the output

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

Angular CLI: 16.1.1
Node: 16.18.1
Package Manager: npm 8.19.2
OS: linux x64

Angular: 16.1.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.1
@angular-devkit/build-angular   16.1.1
@angular-devkit/core            16.1.1
@angular-devkit/schematics      16.1.1
@angular/cli                    16.1.1
@schematics/angular             16.1.1
rxjs                            7.8.1
typescript                      5.1.3
@ngrx/eslint-plugin : 16.0.1

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by brandonroberts** [comment]
I believe this has already been fixed in https://github.com/ngrx/platform/pull/3936

**Comment by tomastrajan** [comment]
Thank yo ufor a swift response@brandonroberts , any eta for release?

**Comment by brandonroberts** [comment]
Today, or tomorrow at the latest

**Comment by timdeschryver** [comment]
I'll close this one for now.
If this issue still persists after the release feel free to reopen.

**Comment by brandonroberts** [comment]
NgRx 16.1.0 has been released with the fix https://github.com/ngrx/platform/commit/ee00ed404386b8be252dd095b3f3a8a6f5b8c90f
