### ISSUE TITLE
eslint-plugin: lint rules using inject()

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#3943]
### Which @ngrx/* package(s) are relevant/related to the feature request?

eslint-plugin

### Information

Linter rules that use instances injected within the constructor should also work using `inject()`.
See #3936 for an example.

It could be that some implementations are already provided but we'll need to add tests for the other rules as well.

Drop your name here and mention which rule(s) you want to help with, if you want to help.

The list of rules that needs to be updates:

- [x] avoid-cyclic-effects ( @suke )
- [x] prefer-concat-latest-from ( @va-stefanek )
- [x] updater-explicit-return-type ( @suke )
- [x] no-dispatch-in-effects ( @va-stefanek )
- [x] avoid-combining-selectors ( @va-stefanek )
- [x] avoid-dispatching-multiple-actions-sequentially ( @va-stefanek )
- [x] avoid-mapping-selectors ( @va-stefanek )
- [x] no-multiple-global-stores ( @va-stefanek )
- [x] no-store-subscription
- [x] no-typed-global-store
- [x] prefer-action-creator-in-dispatch ( @suke )
- [x] prefer-selector-in-select ( @suke )
- [x] select-style ( @suke )
- [x] use-consistent-global-store-name ( @suke )

### Describe any alternatives/workarounds you're currently using

There is no workaround.

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by va-stefanek** [comment]
I can create no-dispatch-in-effects and prefer-concat-latest-from

**Comment by va-stefanek** [comment]
@timdeschryver let assign me to 
avoid-combining-selectors
avoid-dispatching-multiple-actions-sequentially
avoid-mapping-selectors
no-multiple-global-stores

**Comment by suke** [comment]
@timdeschryver please assign me `select-style`

**Comment by timdeschryver** [comment]
Thanks @suke

**Comment by suke** [comment]
@timdeschryver Please continue to assign
`prefer-action-creator-in-dispatch`
`prefer-selector-in-select`
`use-consistent-global-store-name`

**Comment by timdeschryver** [comment]
Done @suke ! Thanks in advance.

**Comment by suke** [comment]
@timdeschryver I will take on the remaining tasks!

**Comment by suke** [comment]
@timdeschryver I'm sorry. I have been busy lately and have not been able to work on it.
