### ISSUE TITLE
@ngrx/no-typed-global-store fails since 16.1.0

### ISSUE THREAD

**Issue by twittwer** [ngrx/platform#3950]
### Which @ngrx/* package(s) are the source of the bug?

eslint-plugin

### Minimal reproduction of the bug/regression with instructions

https://github.com/twittwer/ngrx-repro-eslint-no-typed-global-store

```ts
export class AppComponent {
  store = inject(Store); // <-- trigger for @ngrx/no-typed-global-store
}
```

### Minimal reproduction of the bug/regression with instructions

1. Run `npm i`
1. Run `npm run lint`
    ```
	> nx run app:lint

	Linting "app"...

	>  NX   Cannot read properties of undefined (reading 'typeAnnotation')

	   Occurred while linting C:\Users\tw\git\org\apps\app\src\app\app.component.ts:1
	   Rule: "@ngrx/no-typed-global-store"
	   Pass --verbose to see the stacktrace.
	```
1. Run `npm run downgrade` (`@ngrx/eslint-plugin@16.0.1`)
1. Run `npm run lint`
    - succeeds without error

> Run `npm run upgrade` (`@ngrx/eslint-plugin@16.1.0`) to restore the broken version

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

Angular: 16.1.4
NgRx: 16.1.0

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by DaSchTour** [comment]
Would it be possible to release this with a 16.1.1? I really would like to upgrade without disabling rules.
