### ISSUE TITLE
Rule @ngrx/prefix-selectors-with-select calculates endColumn wrong

### ISSUE THREAD

**Issue by johchur** [ngrx/platform#3956]
### Which @ngrx/* package(s) are the source of the bug?

eslint-plugin

### Minimal reproduction of the bug/regression with instructions

Run eslint with rule @ngrx/prefix-selectors-with-select on the following typescript file and output the result as json (-f json)

```
import {createFeatureSelector} from '@ngrx/store';

export interface FileListResponseState {
  loading: boolean;
}

const featureSelector = createFeatureSelector<FileListResponseState>("name");
```

### Minimal reproduction of the bug/regression with instructions

In the json the reported area should be line 7 column 7 to line 7 column 22.
Instead, the endColumn is calculated as 143. This corresponds to the endposition within the file.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx-EsLint-Plugin: 16.1.0

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by timdeschryver** [comment]
Hi, thanks for raising this issue.
