### ISSUE TITLE
How to migrate @Effect to createEffect if we are using version 14

### ISSUE THREAD

**Issue by navneetagrwl** [ngrx/platform#3957]
### Which @ngrx/* package(s) are the source of the bug?

effects

### Minimal reproduction of the bug/regression with instructions

How to migrate @Effect to createEffect if we are using version 14

### Minimal reproduction of the bug/regression with instructions

How to migrate @Effect to createEffect if we are using version 14

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NGRX - 14
angular -14

### Other information

How to migrate @Effect to createEffect if we are using version 14

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by wassim-ben-amor** [comment]
Hello @timdeschryver , after following the docs, by running `ng update @ngrx/store@13`, it only removes `Effect` import and replaces it with `createEffect`, but the @Effect lines are kept and the code remains the same

**Comment by navneetagrwl** [comment]
> Hello @timdeschryver , after following the docs, by running `ng update @ngrx/store@13`, it only removes `Effect` import and replaces it with `createEffect`, but the @effect lines are kept and the code remains the same

Did you got any solution?
