### ISSUE TITLE
@ngrx/store: Add docs for `Store.selectSignal`

### ISSUE THREAD

**Issue by markostanimirovic** [ngrx/platform#3968]
### Information

Add a guide for the `Store.selectSignal` method. A new section can be added to the [Selectors](https://ngrx.io/guide/store/selectors) page above the "Advanced Usage" section.

More info about `selectSignal`: https://dev.to/ngrx/announcing-ngrx-v16-integration-with-angular-signals-functional-effects-standalone-schematics-and-more-5gk6#ngrx-signals

### Documentation page

https://ngrx.io/guide/store/selectors

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by stefanoslig** [comment]
Hi Marko,

I could work on this one

**Comment by markostanimirovic** [comment]
Thanks @stefanoslig!

**Comment by michaelxvoelker** [comment]
Hey @stefanoslig. Basically the same question as for the `component-store`. I could take over if it's okay with you. 😊

**Comment by markostanimirovic** [comment]
Hi @stefanoslig,

Do you still plan to work on this issue?

**Comment by markostanimirovic** [comment]
Hey @michaelxvoelker,

Let me know if you're still interested in working on this issue.

**Comment by michaelxvoelker** [comment]
Hey @markostanimirovic. Yes. 🙂

**Comment by markostanimirovic** [comment]
Thanks @michaelxvoelker! 🙌 Feel free to create a PR.

**Comment by markostanimirovic** [comment]
Hey @michaelxvoelker 👋 

Still interested in working on this issue?

**Comment by va-stefanek** [comment]
If there will not be interest in that issue I can take care of it :)

**Comment by markostanimirovic** [comment]
Thanks @va-stefanek! Feel free to raise the PR.

**Comment by michaelxvoelker** [comment]
> Hey @michaelxvoelker 👋 
> 
> Still interested in working on this issue?

Thanks for the reminder. Unfortunately, I've been sick for weeks now and not able to contribute.

**Comment by markostanimirovic** [comment]
Get well soon Michael! 🤞

**Comment by va-stefanek** [comment]
@markostanimirovic will do it this week :)
