### ISSUE TITLE
@ngrx/component-store: Add docs for `ComponentStore.selectSignal`

### ISSUE THREAD

**Issue by markostanimirovic** [ngrx/platform#3969]
### Information

Add a guide for the `ComponentStore.selectSignal` method. A new section can be added to the ["Architecture/Read" page](https://ngrx.io/guide/component-store/read).

More info about `selectSignal`: https://dev.to/ngrx/announcing-ngrx-v16-integration-with-angular-signals-functional-effects-standalone-schematics-and-more-5gk6#ngrx-signals

### Documentation page

https://ngrx.io/guide/component-store/read

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by stefanoslig** [comment]
Hi Marko,

I could work on this one

**Comment by markostanimirovic** [comment]
Thanks @stefanoslig!

**Comment by michaelxvoelker** [comment]
Hi @stefanoslig. 👋 Are you working on it, or can I take it over? I already created a PR by copy-pasting the section in the mentioned article. I would also be happy to collaborate if you like. We can for instance change/adapt the added section. Let me know what you think. 🙌

**Comment by michaelxvoelker** [comment]
@markostanimirovic Please reassign the issue to me. Thanks.
