### ISSUE TITLE
"Cannot read properties of undefined (reading 'name') at isClassInstance" when importing effects from a library

### ISSUE THREAD

**Issue by mnlttt** [ngrx/platform#3972]
### Which @ngrx/* package(s) are the source of the bug?

effects

### Minimal reproduction of the bug/regression with instructions

1. Import into your app a library that exports a provider with effects;
2. Run your app.
3. ERROR TypeError: Cannot read properties of undefined (reading 'name')
    at isClassInstance (ngrx-effects.mjs:135:29)

### Minimal reproduction of the bug/regression with instructions

```diff
// node_modules/@ngrx/effects/fesm2022/ngrx-effects.mjs
function isClassInstance(obj) {
-     return (obj.constructor.name !== 'Object' && obj.constructor.name !== 'Function');
+     return (obj.constructor && obj.constructor.name !== 'Object' && obj.constructor.name !== 'Function');
}

function mergeEffects(sourceInstance, globalErrorHandler, effectsErrorHandler) {
-    const sourceName = getSourceForInstance(sourceInstance).constructor.name;
+    const sourceName = getSourceForInstance(sourceInstance)
+      ? getSourceForInstance(sourceInstance).constructor.name
+      : null;
```

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx: ^16.1.0
Angular: ^16.1.7
Node: 18.17.0

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by markostanimirovic** [comment]
Hi @mnlttt,

I couldn't reproduce this behavior. Can you provide reproduction via Stackblitz playground or GitHub repo?

**Comment by mnlttt** [comment]
@markostanimirovic I don't have a public published library I'm sorry, but I can give you more details about how to reproduce it:

Using Nx I built a buildable and publishable library where I had this:

```typescript
// my-effects.effects.ts
export const myEffect = createEffect(
  [...],
  { functional: true },
);
```

```typescript
import * as MyEffects from './my-effects.effects';

export const myStoreProvider: () => EnvironmentProviders = () =>
  makeEnvironmentProviders([
    provideEffects(MyEffects),
  ]);

export const myProvider = (): EnvironmentProviders =>
  makeEnvironmentProviders([
    myStoreProvider(),
  ]);
```

Then, in my App, I imported `myProvider` into app's providers.

```typescript
providers: [
  myProvider(),
],
```

BUT, if I remove `myStoreProvider()` from `myProvider`, and I import `myStoreProvider()` from my app, it works.
```typescript
export const myProvider = (): EnvironmentProviders =>
  makeEnvironmentProviders([
  ]);
```

```typescript
providers: [
  myProvider(),
  myStoreProvider(),
],
```

**Comment by markostanimirovic** [comment]
Thanks for more info! But as we mentioned in the bug report template, reproduction via GitHub repo/StackBlitz playground is required, especially for more complex scenarios.

Feel free to create an Nx repo that reproduces mentioned behavior, share the link here, and we'll take a look. Maybe the problem is not related to NgRx at all. It's weird that an object with effects (or any other object) doesn't have a `constructor`.

**Comment by mnlttt** [comment]
While I'll find the time to create a public repo, do you have any guesses why when importing effects directly from the app they're an esModule and everything works as expected
<img width="499" alt="CleanShot 2023-07-28 at 15 39 11@2x" src="https://github.com/ngrx/platform/assets/37709016/6ad6e76c-b53a-4aae-a7bb-a78b612f3c78">
but when imported from the installed library they're a plain object and it throws the error?
<img width="707" alt="CleanShot 2023-07-28 at 15 42 19@2x" src="https://github.com/ngrx/platform/assets/37709016/1c477dc7-1b58-4cfc-9b23-22c18120c41e">

I tested on a freshly created app too and it's the same.

**Comment by mnlttt** [comment]
@markostanimirovic there you go https://github.com/mnlttt/ngrx-app

It already conveniently has the library built, in the root. The lib is this https://github.com/mnlttt/ngrx-lib

I tried running the app on StackBlitz but I get this error:

>  NX   Missing Platform Dependency
>   The Nx CLI could not find or load the native binary for your supported platform (linux-x64)

https://stackblitz.com/github/mnlttt/ngrx-app/

**Comment by mnlttt** [comment]
Published the package on npmjs and made the app without Nx.

https://stackblitz.com/github/mnlttt/ngrx-app-vanilla?file=src%2Fmain.ts

IMPORTANT: add `import 'zone.js';` in `src/main.ts`.

**Comment by markostanimirovic** [comment]
Thanks @mnlttt! I'll take a look.

**Comment by avine** [comment]
I have the same issue.
After building and Angular library that use effets (class based or fonctional based effect), i have the same error in the console at line ngrx-effects.mjs:134.

**Comment by mnlttt** [comment]
Avoiding the `import/export * as` syntax solves the problem, but I think we all could agree that this solution isn’t the best considering that now we have to import every single effect one by one.

**Comment by markostanimirovic** [comment]
Agree 👍 

Btw, the issue exists because `import * as usersEffects` is transpiled to:

```ts
const usersEffects = Object.freeze({
  __proto__: null,
  // ... functional effects
})
```

**Comment by avine** [comment]
Here is my current solution:

```ts
import { inject } from '@angular/core';
import { Actions, createEffect, FunctionalEffect } from '@ngrx/effects';

// Do not export each effect
const myEffect$ = createEffect(
  (actions$ = inject(Actions)) => {
    return actions$.pipe(/* ... */);
  },
  { functional: true }
);

// Just add this
export const myFeatureEffects: Record<string, FunctionalEffect> = { myEffect$ };
```

Then, use your effects as usual:

```ts
import { myFeatureEffects } from './my-feature.effects.ts';

provideEffects(myFeatureEffects);
```

**Comment by marcindz88** [comment]
For those who still have to use version below 16.2.0 for some reason, you can use this as a quick fix:
```typescript
import * as MyEffects from './my-effects.effects';

export const myStoreProvider: () => EnvironmentProviders = () =>
  makeEnvironmentProviders([
    provideEffects({ ...MyEffects }),
  ]);
```
Spread operator creates a new object which does have proper constructor, and problem is resolved.
