### ISSUE TITLE
Entity dispatchers do not re-dispatch action on re-subscribe

### ISSUE THREAD

**Issue by Nosfistis** [ngrx/platform#3979]
### Which @ngrx/* package(s) are the source of the bug?

data

### Minimal reproduction of the bug/regression with instructions

The entity dispatcher methods dispatch the actions whenever they are called, and return a stream of the responses. However, this can be misleading when acting with RxJS, since the caller expects that the action will be dispatched when the returned (cold) observable is subscribed, and will be re-dispatched if and when the observable is re-subscribed later on, after completion.

Example use-case:
```Typescript
@Component({
  template: `
    <button type="button" (click)="clicked = false">Hide</button>
    <button type="button" (click)="clicked = true">Show</button>
    <div *ngIf="clicked">
      <div *ngIf="projects$ | async"></div>
    </div>
  `,
})
class MyComponent {

  readonly projects$ = this.entityServices.getEntityCollectionService(Project).getWithQuery({ all: true });
  clicked = true;

  constructor(readonly entityServices: EntityServices) {}
}
```

When the `projects$` observable is re-subscribed there will not be a new query dispatched. The only way to go around this is to use `defer()` to call the `getWithQuery` method again on subscribe.

### Minimal reproduction of the bug/regression with instructions

Should the returned observable be treated as hot instead? Perhaps the docs should mention that. Otherwise, the action should be dispatched every time the returned observable is subscribed.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx: 16.1.0
Angular: 16.1.5
Node: 18.17.0
Browsers: Chrome 117.0.5911.2
Operating system: Windows 11

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by timdeschryver** [comment]
Hi, this is the intended behavior.

Ideally, the `get` methods are used as "fire and forget" methods that dispatch actions to invoke a request. You don't have to subscribe on these methods in order to execute them.
On the other side, `selectors` (e.g. `entities$`) are used to render the entities.

Using `defer` is a valid workaround if you don't want to change your code.

**Comment by Nosfistis** [comment]
Hmmm, how would the intended way be to re-fetch data on subscription?

**Comment by timdeschryver** [comment]
AFAIK you can't.
But, for the example in this issue you can have a click handler that dispatches the action.

```ts
@Component({
  template: `
    <button type="button" (click)="hide()">Hide</button>
    <button type="button" (click)="show()">Show</button>
    <div *ngIf="hidden">
      <div *ngIf="projects$ | async"></div>
    </div>
  `,
})
class MyComponent {

  readonly projects$ = this.entityServices.getEntityCollectionService(Project).entities$;
  hidden= true;

  constructor(readonly entityServices: EntityServices) {}

  protected hide(): void {
    this.hidden = true;
  }

  protected show(): void {
   this.entityServices.getEntityCollectionService(Project).getWithQuery({ all: true });
   this.hidden = false;
  }
}
```ts

**Comment by Nosfistis** [comment]
Of course, it can be done in that way or using `defer`.

However, if this is the intended purpose, I think the methods should be more clear, at least in their documentation, that the action is not repeated.

**Comment by timdeschryver** [comment]
Do you want to create a PR for this @Nosfistis ?

**Comment by Nosfistis** [comment]
@timdeschryver regarding the documentation change?

**Comment by timdeschryver** [comment]
@Nosfistis yea for the documentation.

**Comment by Nosfistis** [comment]
Hi @timdeschryver I opened #4005
