### ISSUE TITLE
Incompatible type error when following docs

### ISSUE THREAD

**Issue by TheRedD0t** [ngrx/platform#398]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
</code></pre>

## What is the current behavior?
When following the docs for the [Entity Adapter/Adapter Collection Methods](https://github.com/ngrx/platform/blob/c31573f1c4d9cc02a90cd2033f68d83b17b74969/docs/entity/adapter.md#adapter-collection-methods), I get a `"Types of property 'id' are incompatible."` error at several points:

```
export const adapter: EntityAdapter<User> = createEntityAdapter<User>({
  selectId: (user: User) => user.id
});
```

and

```
[...]
case UserActions.UPDATE_USER: {
  return adapter.updateOne(action.payload.user, state);
}

case UserActions.UPDATE_USERS: {
  return adapter.updateMany(action.payload.users, state);
}
[...]
```

This seems to happen because the docs declare `user.id` as a `number`, but the code behind declares `id` everywhere as `string`.

## Expected behavior:
Types should be compatible when following the docs.

## Minimal reproduction of the problem with instructions:
Follow the docs  for the [Entity Adapter/Adapter Collection Methods](https://github.com/ngrx/platform/blob/c31573f1c4d9cc02a90cd2033f68d83b17b74969/docs/entity/adapter.md#adapter-collection-methods).

## Other information
**EDIT:** The interface `State` that extends `EntityState<User>` declares the `selectedUserId` property as a type of `number`, too. It may should be also changed to type `string` to prevent further issues.
```
export interface State extends EntityState<User> {
  // additional entities state properties
  selectedUserId: number | null;
}
```
____________________
Sorry for the sparse issue description, I don't have much time at the moment.

**Comment by Abrissirba** [comment]
I tried to follow the docs/example-app to add ngrx to an already existing app where we use number ids but got the same error as above. Is it considered bad practice to use a number as id in ngrx?

**Comment by brandonroberts** [comment]
Its not bad practice, but ids aren't always strictly numbers. If we restricted the type to a number, you couldn't use something like a hash, which is also a valid id.

**Comment by Abrissirba** [comment]
Ok, so why only accept string then? I think string | int or any would be better.

**Comment by brandonroberts** [comment]
TypeScript won't allow you to union string and number types. We'll add type overloads so you can provide either type.

**Comment by mbriggs** [comment]
the solution here introduced this when trying to use the selectIds adapter selector.

```
Error:(24, 28) TS2453:The type argument for type parameter 'S2' cannot be inferred from the usage. Consider specifying the type arguments explicitly.
  Type argument candidate 'number[]' is not a valid type argument because it is not a supertype of candidate 'string[]'.
    Type 'string' is not assignable to type 'number'.
```

this is an example which causes that to happen (not a full example, but the two selectors being composed are being pulled off of `adapter.getSelectors`)

```
export const getSurfaces = createSelector(
  getSurfaceEntities,
  getSurfaceIds,
  (e, i: string[])  => i.map(id => e[id])
);
```

**Comment by lelezeus88** [comment]
when you return just add "as any" and that kind of error should disappear.

**Comment by brandonroberts** [comment]
@mbriggs this should be resolved in the latest release
