### ISSUE TITLE
docs(effects): remove unneeded critical div

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#3985]
### Information

In https://github.com/ngrx/platform/pull/3854 we accidentally added a div, which makes all the content below it "critical".

![image](https://github.com/ngrx/platform/assets/28659384/39b3853f-fa13-4a46-a7bf-a60104001d48)

The following line should be removed

https://github.com/ngrx/platform/blob/f371d9e5b6c126fb33e51fa9f98c763d90453d33/projects/ngrx.io/content/guide/effects/index.md?plain=1#L373

### Documentation page

https://ngrx.io/guide/effects

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by KshitijTodkar48** [comment]
I want to fix this, can you assign this to me?
