### ISSUE TITLE
@ngrx/signals: Add `storage` sub-package

### ISSUE THREAD

**Issue by markostanimirovic** [ngrx/platform#3997]
### Information

Add the `@ngrx/signals/storage` sub-package that will contain the `withStorageSync` feature.

The initial implementation is available here: https://github.com/markostanimirovic/ngrx-signal-store-playground/blob/main/src/app/shared/storage-sync.feature.ts

### I would be willing to submit a PR to fix this issue

- [x] Yes
- [ ] No

**Comment by ducin** [comment]
@markostanimirovic would be happy to help here, if help is needed.

**Comment by gabrielguerrero** [comment]
@markostanimirovic  I also created an implementation for @ngrx-traits/signals, here https://github.com/gabrielguerrero/ngrx-traits/blob/main/libs/ngrx-traits/signals/src/lib/with-sync-to-web-storage/with-sync-to-web-storage.ts
in case anything will be useful, Im happy to help with this too. I also I did lots of other custom storage features , like withCalls that I think could be useful if they were subpackages that I will be happy to colaborate

**Comment by markostanimirovic** [comment]
I'm going to close this issue as it's not planned for now. It will be revisited later this year.

In the meantime, community plugins can be used for storage synchronization.

**Comment by muuvmuuv** [comment]
Will it become a new issue then or reopened? Wanted to implement something like that but its quiet hard since our storage factory is async (e.g. localforage would also be async).
