### ISSUE TITLE
combine, compose, createSelector?

### ISSUE THREAD

**Issue by axtho** [ngrx/platform#40]
Suppose I have a couple of reducers that all have a message in their state.
I want to create, in the meta reducer, a call that checks whether any of these states have a message that needs to be displayed.

I am doing it like this now:
```
export const getMessageP: any = createSelector(getPersonState, person.getMessagePerson);
export const getMessageS: any = createSelector(getSettingsState, settings.getMessageSettings);
export const getMessage:any =  createSelector(getMessageP, getMessageS,
    (msgP: any, msgS: any) => {
    return msgP || msgS;
});
```
That seems overly complicated. I checked the docs for combination of reducers, but the API is not well documented. Is there a better way to do something like that with v4?

ENV:
ngrx: nightly-builds
TS: 2.3.4
NG: 4.2.2
NPM 8

**Comment by MikeRyanDev** [comment]
You could write the last `getMessage` like this:

```ts
export const getMessage = (state: State) =>
  [
    getMessageP,
    getMessageS,
  ]
  .find(messageSelector => messageSelector(state));
```

**Comment by axtho** [comment]
Thanks! That looks good. I like that you can keep on adding to the array when new states have messages also.

What is `messageSelector`?  If I include this now it returns me a function:
```
function memoized() {
        if (!lastArguments) {
            lastResult = t.apply(null, arguments);
            lastArguments = arguments;
            return lastResult;
        }
        for (var /** @typ…
```

I am reading the messages from components like this:
```TS
this._store.select(app.getMessage)
            .takeWhile(() => this._alive)
            .subscribe((message: any) => {
                if (message) {
                    this._shout.out(message.text, message.type)
                        .afterDismissed()
                        .take(1)
                        .subscribe(() => this._store.dispatch(new ClearSettingsMessageAction()));
                }
            });
```
where message is an interface, that gets constructed from the reducer and passed along in the actions (UPDATE_XXX and CLEAR_MESSAGE - for each reducer that has messages):
```TS
export interface Message {
    type: string;
    text: string;
}
```

**Comment by agugan** [comment]
@axtho http://www.dongcoder.com/detail-365721.html  Take a look at this link. see whether it helps.
