### ISSUE TITLE
NullInjectorError: No provider for StoreRootModule! when using `provideStore(reducers)` and trying to register a feature store

### ISSUE THREAD

**Issue by mlc-mlapis** [ngrx/platform#4003]
### Which @ngrx/* package(s) are the source of the bug?

store

### Minimal reproduction of the bug/regression with instructions

https://stackblitz.com/edit/mlc-ngrx-sapi

When using the Angular standalone API to register a root store, `provideStore(reducers)`, then any try to register a feature store using any available syntax (`provideState(pageFeature)` in routes or just importing of a module with `StoreModule.forFeature(FEATURE_NAME, pageReducers)`) leads to the error message `NullInjectorError: No provider for StoreRootModule!`.

### Expected behavior

No error.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx: 16.2.0
Angular: 16.2.0
Browser: Chrome 115.0
OS: Windows 10

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by brandonroberts** [comment]
In order to use StoreModule.forFeature with a standalone setup, you must use StoreModule.forRoot in the providers array using `importProvidersFrom`.


```ts
providers: [
    importProvidersFrom(StoreModule.forRoot()),
    provideStore(reducers)
]
```

Same applies to EffectsModule.forFeature and EffectsModule.forRoot.

**Comment by mlc-mlapis** [comment]
@brandonroberts As I wrote already above, I also tried using `provideState(pageFeature)` in a route, but the problem happened exactly the same. So now, as it looks, there is no way how to register a feature store when you use `provideStore(reducers)`.

Also, it would be interesting to know the reason why you have to use `StoreModule.forRoot` and `StoreModule.forFeature` together from the point of Angular. Is it some conceptual problem?
