### ISSUE TITLE
Docs: Add documentation for opting out of Zone.js connection with StoreDevtools 

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#4008]
### Information

In https://github.com/ngrx/platform/issues/3839, we introduced a new option in StoreDevtools to connect to the Redux DevTools Extension outside the Zone to stop change detection from being triggered by the communication between the two.

```ts
provideStoreDevtools({
  connectOutsideZone: false,
})
```

This should be added to the examples on the overview page for Module and Standalone APIs.

https://github.com/ngrx/platform/blob/main/projects/ngrx.io/content/guide/store-devtools/index.md

<img width="1080" alt="image" src="https://github.com/ngrx/platform/assets/42211/fd50f88a-5279-4ac9-bcd8-1eb2b959f193">

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by va-stefanek** [comment]
I will take care of it
