### ISSUE TITLE
Fix typo on the Lifecycle page

### ISSUE THREAD

**Issue by markostanimirovic** [ngrx/platform#4010]
### Information

Type should be fixed [here](https://github.com/ngrx/platform/blob/main/projects/ngrx.io/content/guide/component-store/lifecycle.md?plain=1#L180): `ComoponentStore` => `ComponentStore`

### Documentation page

https://ngrx.io/guide/component-store/lifecycle

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by srinathsree66** [comment]
Hi, Is anyone working on it? If no, I want to try.

**Comment by srinathsree66** [comment]
Hi, Is anyone working on it? If no, I want to try.

**Comment by markostanimirovic** [comment]
Thanks @srinathsree66! Feel free to create a PR.
