### ISSUE TITLE
Make generated tests easier by using observer-spy instead of marbles

### ISSUE THREAD

**Issue by hgschwibbe** [ngrx/platform#4024]
### Which @ngrx/* package(s) are relevant/related to the feature request?

store

### Information

You can use marbles to test the timing behavior, but I don't know any developer who takes care of it. 
Instead everybody has to eat marble's complex syntax and fix all the timing errors after implementation changes.

Most of the developers are not interested in the timing behavior where something happens 10ms earlier, or later. 
Developers want to test the end result, sometimes some interim results of an observable.

Please make it easier and use observer spy for testing:
https://github.com/hirezio/observer-spy

### Describe any alternatives/workarounds you're currently using

I always replace the marble code by observer spy code after generating an NgRx feature store.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by rainerhahnekamp** [comment]
Whenever I write a unit test covering only an effect, the effect is quite complicated and I only use marbles for that. Usually, those are effects which combine multiple observables together, and I want to be very precise in my test.

I test simple effects only in combination with the complete store. That means together with selectors and the reducer. `fakeAsync` with `tick` is enough then.

So, I don't think that we should abandon marble in favour of observer-spy.

**Comment by timdeschryver** [comment]
We still encourage using marbles to test effects. 
The marble syntax is a concept of RxJS, and is used to test streams.
If you and your team wants to use observer-spy that's fine.

I'm closing this issue, but I also want to mention that I wasn't able to find a reference to a marble within the generated template files.
