### ISSUE TITLE
@ngrx/signals:  Provide Videos per Documentation Page

### ISSUE THREAD

**Issue by rainerhahnekamp** [ngrx/platform#4032]
### Which @ngrx/* package(s) are relevant/related to the feature request?

store

### Information

Every documentation page should have a short video clip summarising the content.

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by markostanimirovic** [comment]
Great idea! I think it would be better to open an issue per video/tutorial, but let's keep this issue for now as a reminder since we still don't know how many pages the `@ngrx/signals` docs will contain.

**Comment by rainerhahnekamp** [comment]
@markostanimirovic I think the documentation is done. Can we proceed with the videos?

**Comment by ducin** [comment]
@markostanimirovic I would be also willing to help here 💪

**Comment by markostanimirovic** [comment]
I'm going to close this issue as it's not planned for now. It will be revisited later this year.
