### ISSUE TITLE
@ngrx/signals: Add option to hide $update

### ISSUE THREAD

**Issue by rainerhahnekamp** [ngrx/platform#4034]
### Which @ngrx/* package(s) are relevant/related to the feature request?

store

### Information

There should be an option to hide the $update method from the outside. Otherwise components and services would have direct access to state. Logic would be spread over the code base and not kept in a central place.

I would like to add a PR but I think @markostanimirovic has already a working solution.

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by markostanimirovic** [comment]
Closing this issue because the `$update` method will be removed in this PR: https://github.com/ngrx/platform/pull/4037
