### ISSUE TITLE
How to Build an Android Version

### ISSUE THREAD

**Issue by mozgbrasil** [ngrx/platform#4035]
### Information

How to Build an Android Version

I would like to use this project as a model and distribute an application for Android, how to build an Android version, can you kindly help me

Is there a way to add this possibility to the project

Congratulations to all collaborators

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Thanks @mozgbrasil. Let's keep this as a discussion as it's not on our roadmap
