### ISSUE TITLE
Injecting ngUpgraded services into Effects classes leads to error on boot

### ISSUE THREAD

**Issue by pobrienms** [ngrx/platform#404]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

I'm submitting this as a new issue so that you're able to see the reproduction repository below.  Feel free to close this against the existing issue (316).

## What is the current behavior?

See https://github.com/ngrx/platform/issues/316
"effects v4 not compatible with ngUpgrade"

Error on boot:  "Unhandled Promise rejection: Trying to get the AngularJS injector before it being set." 

## Expected behavior:

There should be a mechanism for registering Effects classes with injectables that use the ngUpgraded $injector.

## Minimal reproduction of the problem with instructions:

Inject an ngUpgraded service into the constructor of an effects class

I've created a repo with a small reproduction here:
https://github.com/pobrienms/injectorRepro

See:
https://github.com/pobrienms/injectorRepro/commit/dba0dc613850b89a4271c118178a1a62b478130e

**Comment by brandonroberts** [comment]
This is not a bug with Effects, but more how ngUpgrade needs the app to be bootstrapped before you can access the AngularJS injector. You can workaround this issue by using the injector to get the `$rootScope` when needed. Here is an example repo https://github.com/brandonroberts/injectorRepro/commit/f811b96ae46af0db0cb15144627e75836db34466

**Comment by pobrienms** [comment]
Hey Brandon, Thanks for your response.  

The initial repro code was overly simplified to illustrate what I'm trying to get working.  I just used $rootScope as a stand in for any service upgraded from AngularJS.  My use case is that I have an Effect that uses startsWith() to trigger a http request when the Effect gets registered. I have an AngularJS service that wraps $http to log telemetry and set some app specific headers.  I haven't had the time to update this to ng4 yet and would like to use it in Effects until it can be replaced.  The following commit is closer to what I'm trying to accomplish:

https://github.com/pobrienms/injectorRepro/commit/9d012665155870475a8e0953071b1c65567aa3ab

In this case, the Effect still runs before AngularJS is bootstrapped and the "Trying to get the AngularJS injector before it being set." error remains.  

I'm fine with treating this as a feature request rather than a bug.  I was maintaining the categorization from the original issue (https://github.com/ngrx/platform/issues/316) when I filed this as a Bug Report.  

The suggestion that @michaelgerakis posted in the original issue should work.  It's just a little clunky to have to manage Effects registration in an imperative way.

**Comment by brandonroberts** [comment]
@pobrienms I see. You don't need to register the effects manually. The issue in this case is because the `startWith` operator doesn't respect the bootstrap process and fires as soon as the effect is registered. What I would do is remove the `startWith` operator and add an additional listener to your effect that listens for a "Bootstrapped" action type that is dispatched after the bootstrap in `ngDoBootstrap` method.

**Comment by brandonroberts** [comment]
@pobrienms any updates on this issue or can this be closed?

**Comment by pobrienms** [comment]
@brandonroberts thanks for your response.  Sorry for the delay in getting back to you.  Your proposed solution makes sense and should work in this case.  Thanks for your help!

**Comment by thekip** [comment]
Add my solution here, instead of using getters and injecting injector in effects, it's possible to use globally registered ajs injector via decorator: 

**@libs/inject-decorator.ts**
```ts
let _$injector: angular.auto.IInjectorService;

export function registerInjectDecoratorModule() {
  angular.module('inject-decorator', []).run(function registerInjectDecorator($injector) {
    _$injector = $injector;
  });
}

/**
 * Usage property dependency injector decorator
 *
 * Usage:
 *
 * import {inject} from '@libs/inject-decorator';
 *
 * class Foo {
 *    @inject() //property name the same as service name
 *    private someService: SomeService
 *
 *    @inject('barService') //explicit pass name of service to inject
 *    private bar: BarService
 * }
 */
export function inject(name?: string) {
  return function injectDecorator(target: any, key: string) {
    Object.defineProperty(target, key, {
       get: () => {
         const value = _$injector.get(name || key);
         Object.defineProperty(target, key, {
           value,
           writable: false,
           enumerable: false,
           configurable: false,
         });
         return value;
       },
      enumerable: false,
      configurable: true,
    });
  };
}
```
Then register module in ajs module to be able to get `$injector` service

**app.ts**
```ts
import { registerInjectDecoratorModule } from '@libs/inject-decorator';

registerInjectDecoratorModule();
const appModule = angular.module('app', [
  'inject-decorator', // should be before any other modules
  ...
]
```

Then you can use this decorator safely in Effects:

```ts
@Injectable()
export class MyEffects {
  @inject() private $rootScope: ng.IRootScopeService;

  @Effect()
  someEffect$ = this.action$.pipe(
    ofType('any'),
    tap(() => console.log('$rootScope',  this.$rootScope)),
    filter(() => false),
  )
}
```

**Comment by dopoto** [comment]
@thekip Great solution! Can you also please provide some sample code of unit tests for Effects using this solution?
