### ISSUE TITLE
loadWithQuery creates wrong action

### ISSUE THREAD

**Issue by x-etienne** [ngrx/platform#4045]
### Which @ngrx/* package(s) are the source of the bug?

data

### Minimal reproduction of the bug/regression with instructions

When I use "loadWithQuery" method the action created is "EntityOp.QUERY_MANY" i suspect this is wrong. Perhaps it need "EntityOp.QUERY_LOAD "

Look [here](https://github.com/ngrx/platform/blob/f2514baea9dd528a9f54f0623fe803b09b132c1e/modules/data/src/dispatchers/entity-dispatcher-base.ts#L332C87-L332C87)

thanks

### Expected behavior

When I call "loadWithQuery" I want the action "EntityOp.QUERY_LOAD "

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

 "@ngrx/data": "^16.2.0",

### I would be willing to submit a PR to fix this issue

- [x] Yes https://github.com/ngrx/platform/pull/4081
- [ ] No

**Comment by timdeschryver** [comment]
This is by design, https://github.com/ngrx/platform/blob/main/modules/data/spec/dispatchers/entity-dispatcher.spec.ts#L295-L304.
