### ISSUE TITLE
ng g store State --module app.module.ts --root --statePath store  Error: Unknown argument: statePath

### ISSUE THREAD

**Issue by huzurpolat** [ngrx/platform#4053]
### Which @ngrx/* package(s) are the source of the bug?

store

### Minimal reproduction of the bug/regression with instructions

ng generate store gives me an error
`ng g @ngrx/schematics:store AppState --module app.module.ts --root --statePath store
`
`Error: Unknown argument: statePath`

### Expected behavior

CLI generates a Store index.ts file in given folder

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

Angular: 16.2.0
Angular CLI: 16.2.0
Node: 20.5.1 (Unsupported)
Package Manager: npm 9.8.1
OS: darwin arm64
Browser: Chrome

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by markostanimirovic** [comment]
Have you tried with `--state-path`?

https://ngrx.io/guide/schematics/store

**Comment by huzurpolat** [comment]
Haha. it works.
THX @markostanimirovic 
I worked according to these instructions : https://v9.ngrx.io/guide/schematics/store
