### ISSUE TITLE
Store DevTools dispatcher doesn't successfully dispatch actions throught ActionsSubject

### ISSUE THREAD

**Issue by devkirr** [ngrx/platform#4055]
### Which @ngrx/* package(s) are the source of the bug?

store-devtools

### Minimal reproduction of the bug/regression with instructions

When using the devtools Dispatcher, the dispatched actions are catched by the Actions Injectable in Effects. But using the ActionSubject in component, I'm not able to see the manually dispatched actions.

### Expected behavior

I would expect the ActionSubject to behave like the Actions and listen to the manually dispatched actions.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx & DevTools => 15.4

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by rainerhahnekamp** [comment]
Do you maybe have a code example? Something we can use to reproduce it?

**Comment by timdeschryver** [comment]
This is by design.
If you want to listen to actions within a component, you can use `ScannedActionsSubject`.
This subject will also receive actions dispatched by the Redux DevTools.
