### ISSUE TITLE
How to reset/clear reducer initial state correctly: the user logs out, his data stored in the default value (reducer's initialState value) must be deleted from memory

### ISSUE THREAD

**Issue by DmitriyIvanko** [ngrx/platform#4058]
### Which @ngrx/* package(s) are the source of the bug?

store

### Minimal reproduction of the bug/regression with instructions

The problem relates to the function:
https://github.com/ngrx/platform/blob/4ed69da909dc74383559bccfb76539d85d301776/modules/store/src/reducer_creator.ts#L136C31-L136C43
How can I reset/clear initialState in the reducer?

Simple example
1) user 1 is logged into the application
2) Pressed F5
3) InitialState was set to values from the localStorage (initialState of user 1)
4) The user has left the application (all of his data should be erased, but they are saved in the initialState function as default value of that function)
5) User 2 logged in
6) Calling a method in the metareducer will return the values of old user 1:
```
export function clearStateMetaReducer(reducer: ActionReducer<AppState>): ActionReducer<AppState> {
  return function clearStateFn(state, action) {
    if (action.type === ClearGlobalStoreAction.type) {
      return reducer(undefined, { type: INIT });
    }
    return reducer(state, action);
  };
}

```

### Expected behavior

It will be possible to erase user 1 data in the reducer after logout

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

  "@ngrx/store": "16.0.0",

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by markostanimirovic** [comment]
Hi @DmitriyIvanko,

You can use GitHub Discussions, StackOverflow, or NgRx Discord for questions. [More info](https://github.com/ngrx/platform/blob/main/CONTRIBUTING.md#questions-and-requests-for-support)
