### ISSUE TITLE
StoreDevtoolsModule + CustomRouterStateSerializer not navigating after import

### ISSUE THREAD

**Issue by PhillipZada** [ngrx/platform#406]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
I've setup CustomRouterStateSerializer as found in the example-app in order to resolve the issue of the large router state slowing application performance when devtools is enabled. However when I import a state, the state of the Angular app isn't updating/redirecting as excepted and stays where it is. However if you remove the CustomRouterStateSerializer, it works fine but very slow.

## Expected behavior:
The app redirects to the exact state as exported.

## Minimal reproduction of the problem with instructions:
As per current behavior.
1. Implement a CustomRouterStateSerializer
```
export interface RouterStateUrl {
  url: string;
  queryParams: Params;
}

export class CustomRouterStateSerializer
  implements RouterStateSerializer<RouterStateUrl> {
  serialize(routerState: RouterStateSnapshot): RouterStateUrl {
    const { url } = routerState;
    const queryParams = routerState.root.queryParams;

    return { url, queryParams };
  }
}

```
2. Inject the provider into the module
```
{ provide: RouterStateSerializer, useClass: CustomRouterStateSerializer },
```
3. Open the dev tools, do some things to change the url
4. Export the state using the dev tools
5. Refresh the page to clear the state and start again
6. Import the state.json using the dev tools

## Version of affected browser(s),operating system(s), npm, node and ngrx:
Testing in Chrome, Firefox on Linux and Windows

**Comment by akaztp** [comment]
Does time travel work? I'm finding that it doesn't.

**Comment by akaztp** [comment]
Got it to work. 
@PhillipZada What is the name of the property where you store the router state?
It must be named ´routerReducer´ like in the [docs](https://github.com/ngrx/platform/blob/master/docs/router-store/api.md).

**Comment by PhillipZada** [comment]
Hey @akaztp, 

That worked, thanks for the assist 👍
