### ISSUE TITLE
External library issue: R3InjectorError(AppModule)[Store -> Store]

### ISSUE THREAD

**Issue by hwebb** [ngrx/platform#4060]
### Which @ngrx/* package(s) are the source of the bug?

effects, store

### Minimal reproduction of the bug/regression with instructions

The StoreModule is initialized within the application, and I aim to consume the state within the library since multiple projects will share the same component.

The setup functions correctly when the library resides in the same project. However, an error arises when the library is situated in an external folder:

```
ERROR NullInjectorError: R3InjectorError(AppModule)[Store -> Store]: 
  NullInjectorError: No provider for Store!
```

Interestingly, if I merely copy the compiled files from the dist folder and amend the tsconfig, it operates as expected. But, it fails to work from a distant folder.

Here's a snippet of the code from the App:
```
@Component({
  selector: 'app-root',
  template: `<lib-test></lib-test>`,
})
export class AppComponent {}

@NgModule({
  declarations: [AppComponent],
  imports: [StoreModule.forRoot({}), BrowserModule, TestComponent],
  providers: [],
  bootstrap: [AppComponent],
})
export class AppModule {}
```

On the Library:
```
@Component({
  selector: 'lib-test',
  standalone: true,
  template: `test`,
})
export class TestComponent {
  constructor(private store: Store) {}
}
```

My paths on tsconfig.json:
```
"paths": {
  "@angular/*": ["./node_modules/@angular/*"],
  // "test-lib": ["dist/test-lib"], // This works
  "test-lib": ["../test-library/dist/test-lib"], // This will not work (same compiled files)
}
```

### Expected behavior

I expect it to work the same way when the library is on the local project than on a separate shared library-dedicated project.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRX: ^16.2.0
Angular: ^16.2.0
Node: v18.15.0
Browser: Chrome
OS: WSL2

### Other information

I was able to kind of make it work with symlinks of the projects folder, but it's not really elegant!

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by markostanimirovic** [comment]
Are you sure that this issue is related to NgRx? If yes, you need to provide a reproduction via StackBlitz or GitHub repo.

**Comment by hwebb** [comment]
> Are you sure that this issue is related to NgRx? If yes, you need to provide a reproduction via StackBlitz or GitHub repo.

I don't see any other responsible code as it only happens to NgRX, everything else is working, The exact same code works when it's on the same project.

I have a test project that I can put on StackBlitz or GitHub repo, but as it consists of 2 different projects (lib + app) it may be challenging to make that work. I'll try to find a way.

**Comment by markostanimirovic** [comment]
I'm going to close this issue. Feel free to reopen it with provided reproduction.
