### ISSUE TITLE
Docs: follow-up polish for dark mode

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#4070]
This looks good to me, there might be some elements that can be tweaked as a follow up, e.g.

- code snippets 
- alerts/admonitions (see screenshot, in the dark theme it loses its background)

![image](https://github.com/ngrx/platform/assets/28659384/7548da16-1005-4697-9d24-8a6d3b7ae817)

_Originally posted by @timdeschryver in https://github.com/ngrx/platform/pull/4054#pullrequestreview-1674872135_

**Comment by va-stefanek** [comment]
I will continue with that one :)

**Comment by va-stefanek** [comment]
@timdeschryver 

1. For alerts we currently have exactly same color as Angular does. Let me know whether we for sure want to change it.
2. For code snippets it's hard to find proper orange color in the light mode which will pass accessibility rules, maybe you can propose some? https://webaim.org/resources/contrastchecker/

**Comment by timdeschryver** [comment]
@va-stefanek 

1. Ok that's fine for me
2. What about #D86703 ? It is a slight darker version from the original color #AF4B04, when making it too dark it doesn't play well with the other colors.

**Comment by va-stefanek** [comment]
Done, but this color still has contrast issue

<img width="311" alt="image" src="https://github.com/ngrx/platform/assets/67691339/1b4898b8-2656-4b27-b534-7a9133753f8d">
