### ISSUE TITLE
StoreDevtoolsConfig.logOnly = true seems to be ignored

### ISSUE THREAD

**Issue by heike2718** [ngrx/platform#4084]
### Which @ngrx/* package(s) are the source of the bug?

store-devtools

### Minimal reproduction of the bug/regression with instructions

In my app.config I use the StoreDevToolsProvider like this:

```
provideStoreDevtools({
      maxAge: 25,
      logOnly: environment.production
    });
```
since I do not want the Store be visible in the Browser in Production. 

Unexpectedly the Store is visible in Production. 

### Expected behavior

The content of the store should not be visible in the Chrome-Reduy-Plugin or other plugins that visualize the ngrx-Store.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

Nrgx: 16.0.1
Angular: 16.2.5

### Other information

Open the following link for example with Chrome with Redux extension and open the Redux-View in the development tools:

[mathe-jung-alt.de/mja-app/](https://mathe-jung-alt.de/mja-app/)
 

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by markostanimirovic** [comment]
With the `logOnly: true` option, the store is connected to the devtools extension in log-only mode. In other words, it disables modifications from the devtools extension.

Learn more about how to exclude store devtools from production [here](https://ngrx.io/guide/store-devtools/recipes/exclude).

**Comment by heike2718** [comment]
Thanks @markostanimirovic.

That was very helpful.
