### ISSUE TITLE
Docs: Fix dropdown in dark mode

### ISSUE THREAD

**Issue by markostanimirovic** [ngrx/platform#4089]
### Information

![Screenshot (17)](https://github.com/ngrx/platform/assets/17877290/e3b2ab14-b946-4a74-ae81-a785caf77a7a)

### Documentation page

https://ngrx.io/api

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by LayZeeDK** [comment]
Same issue for the version dropdown in the primary navigation drawer
![NgRx documentation version picker in dark mode](https://github.com/ngrx/platform/assets/6364586/815b6ae7-52ba-429b-a989-5a4bb0d34e37)
