### ISSUE TITLE
Store Devtools: Set default for connectOutsideZone to true

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#4093]
### Which @ngrx/* package(s) are relevant/related to the feature request?

store-devtools

### Information

We introduced the `connectOutsideZone` flag for Store Devtools to connect to the Redux Devtools outside the Angular zone to reduce the number of change detection calls being triggered.

It is currently set to `false` by default. This change would flip the flag to `true` by default and update the associated documentation to reflect that.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by timdeschryver** [comment]
I'll write a migration for this.
