### ISSUE TITLE
Missing tag for 16.3.0 version

### ISSUE THREAD

**Issue by eweap** [ngrx/platform#4096]
### Information

While npmjs.com shows a version for 16.3.0, the [github repository](https://github.com/ngrx/platform/tags) don't have a 16.3.0 tag

### Documentation page

https://www.npmjs.com/package/@ngrx/store/v/16.3.0?activeTab=readme

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Thanks. Fixed https://github.com/ngrx/platform/tree/16.3.0

**Comment by eweap** [comment]
wow, that's fast ⚡ ! thanks @brandonroberts
