### ISSUE TITLE
ngrx does not work with angular 17

### ISSUE THREAD

**Issue by pablogarzon1969** [ngrx/platform#4115]
### Which @ngrx/* package(s) are the source of the bug?

effects

### Minimal reproduction of the bug/regression with instructions

![angular17error](https://github.com/ngrx/platform/assets/32750488/8b83ed71-7bcc-4376-9a1c-04c9ce56871b)

### Expected behavior

installing ngrx in angular 17

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

Ngrx: 16.3.0
Angular: 17
Node: 20.9.0

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by brandonroberts** [comment]
NgRx does work with Angular v17. This is a peer dependencies issue. 

Use

```sh
npm install --legacy-peer-deps
```

NgRx v17 will be released soon-ish.

**Comment by entanglesoftware** [comment]
Hi @brandonroberts , Just wondering how much time would take to release? I just want to know so that i can make decisions. Keep up the great work Mate! Thanks

**Comment by MattiaMalandrone** [comment]
Yesterday we installed angular 17 on a project with ngrx 16.3.0 and it worked without issues 👍

**Comment by simonh1000** [comment]
Not sure why this is closed. Updating is not working for me nor - judging by the thumbs down above - for others

**Comment by andrew-cunliffe** [comment]
Still have to use --force or -legacy-peer-deps .... not ideal situation after 2 weeks and the Ops team are getting upset asking for a rollback all due to this....

**Comment by JeffryGonzalez** [comment]
> Still have to use --force or -legacy-peer-deps .... not ideal situation after 2 weeks and the Ops team are getting upset asking for a rollback all due to this....

You can put the setting in your local `.npmrc` for now. (https://docs.npmjs.com/cli/v7/using-npm/config#legacy-peer-deps) This was a change in NPM 7(?). The peer dependencies in NGRX 16 are for Angular 16 (`"@angular/core": "^16.0.0"`), I've updated several apps to Angular 17 with version 16 of the NGRX libraries no problem.  I'm grateful they are taking their time to get 17 "right".

**Comment by brandonroberts** [comment]
Thanks for your patience folks. NgRx 17.0.0 has been published to npm on `latest`.

Just a reminder that NgRx is maintained by our team **in addition to** our full-time jobs, so we prioritize what we can. As you and your companies depend on this for mission-critical apps, consider getting your company to sponsor the project, or contact us for further support opportunities.

https://github.com/sponsors/ngrx
https://ngrx.io/enterprise-support

**Comment by mlc-mlapis** [comment]
@brandonroberts Thanks a lot for your work. We all know that very well. Well, I hope so.
