### ISSUE TITLE
[Signal Store] Access the whole state object

### ISSUE THREAD

**Issue by jits** [ngrx/platform#4116]
### Which @ngrx/* package(s) are relevant/related to the feature request?

signals

### Information

Using `@ngrx/signals` 17.0.0-beta.0

It doesn't look like it's currently possible to access the whole state object from a `signalStore` instance as a single signal.

It would be useful to be able to do so, e.g. in cases where the state object is modelled as a state machine using type unions and a discriminated field.

I've noticed the autocompletion does allow you to do something like:

```ts
import { STATE_SIGNAL } from '@ngrx/signals/src/signal-state';
...
vm = this.#store[STATE_SIGNAL];
```

… which compiles fine, but at runtime there is an error:

```shell
✘ [ERROR] Could not resolve "@ngrx/signals/src/signal-state"

    src/app/login/feature/login-page.component.ts:3:29:
      3 │ import { STATE_SIGNAL } from '@ngrx/signals/src/signal-state';
        ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The path "./src/signal-state" is not exported by package "@ngrx/signals":

    node_modules/@ngrx/signals/package.json:55:13:
      55 │   "exports": {
         ╵              ^

  You can mark the path "@ngrx/signals/src/signal-state" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
```

Note: it would also be very useful to access this single signal in the `withMethods`, `withHooks` etc. A concrete use case is setting up an `effect` in `onInit` to log state changes in the whole state object.

### Describe any alternatives/workarounds you're currently using

No simple working alternatives found.

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by markostanimirovic** [comment]
Good point. The `STATE_SIGNAL` symbol will remain private. However, we can add the `getState(store)` function that returns the read-only state signal.

**Comment by jits** [comment]
@markostanimirovic – sounds good. I can work on a PR for this, unless you say otherwise.

**Comment by markostanimirovic** [comment]
Cool! Feel free to raise the PR.

**Comment by jits** [comment]
Thanks @markostanimirovic. I'm wondering if it makes more sense to return the `Signal` instance instead? This way it can be used in possibly many places (and for different purposes), e.g. in a template (and thus benefiting from finer-grained change detection) as well as in an `effect` elsewhere. I'm thinking of cases, for example, where you want to treat the whole state object as a view model to be used in a component. A contrived example:

```ts
@Component({
  ...
  template: `
    @if (vm().status == "authenticated") {
      <p>Hello {{ vm().user?.name }}</p>
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AComponent {
  #store = inject(AStore); // This is an instance of a signal store

  vm = getState(store);

  constructor() {
    effect(() => {
      if (this.vm().status === "error") {
        // Do something special here
      }
    });
  }
}

```

---

A separate thought: I wonder about the naming — `getState`. Since this could be used within `withMethods` and the hooks within `withHooks` the current naming convention (that I can make out) means we'd end up with something like `getState(state)` within those. Which doesn't sound right.

**Comment by markostanimirovic** [comment]
Regarding the view model with signals, it will be anti-pattern when angular introduces change detection at the view level in the upcoming versions. Therefore, it should not be used. Instead, we should use nested signals that SignalStore provides for each nested state slice.

===

>  Since this could be used within withMethods and the hooks within withHooks the current naming convention (that I can make out) means we'd end up with something like getState(state) within those. Which doesn't sound right.

The name of the `withHooks` or `withMethods` factory input argument should be `store`, not `state`:

```ts
const CounterStore = signalStore(
  withState({ count: 0 }),
  withMethods((store) => ({ /* ... */ })),
  withHooks({
    onInit(store) {
      const state = getState(store);
      console.log(state);
    },
  })
);
```

**Comment by jits** [comment]
@markostanimirovic — I'm with you now. Thanks for the clarifications. PR incoming.

**Comment by markostanimirovic** [comment]
**Important note for anyone who will read this discussion:**

There are use cases for the `getState` function, but in general, it should be **rarely** used. Using `getState` makes sense in the following cases:

- Synchronizing the SignalStore's state with local storage, so we need to grab all state slices together without knowing the state structure.
- Any kind of logging. For instance - implementing a Redux Devtools extension for SignalStore would require getting the entire state object.

**Comment by rosostolato** [comment]
I can't use the `getState` function from within the `withComputed` feature because it receives a slice of the store without the `[STATE_SIGNAL]` property. Is there any workaround?

**Comment by markostanimirovic** [comment]
Hi @rosostolato,

Can you provide a use case where `getState` should be used inside of `withComputed`? Maybe it should be solved differently.

**Comment by rosostolato** [comment]
@markostanimirovic

I'm building a redux library for ngrx signal store. I'm trying to reuse the main features to create my `withSelectors` feature, but I need to get the full state to provide it to the selectors. You can see the implementation on this commented code: https://github.com/rosostolato/ngrx-signals-redux/blob/master/projects/ngrx-signals-redux/src/lib/with-selectors.ts#L19-L37

My workaround is to follow the same implementation of the `withComputed` feature to receive the store reference.
