### ISSUE TITLE
[Signal Store] Using an interface for the state type causes a typing issue

### ISSUE THREAD

**Issue by jits** [ngrx/platform#4117]
### Which @ngrx/* package(s) are the source of the bug?

signals

### Minimal reproduction of the bug/regression with instructions

Using `@ngrx/signals` v17.0.0-beta.0 and `typescript` 5.2.2

Trying this code:

```ts
interface State {
  user: string | null;
}

export const userStore = signalStore(
  withState<State>({ user: null }),
);
```

… I get the TypeScript error:

```
No overload matches this call.
  The last overload gave the following error.
    Argument of type 'SignalStoreFeature<EmptyFeatureResult, EmptyFeatureResult & { state: State; }>' is not assignable to parameter of type 'SignalStoreConfig'.ts(2769)
signal-store.d.ts(20, 25): The last overload is declared here.
Type 'State' does not satisfy the constraint 'Record<string, unknown>'.
  Index signature for type 'string' is missing in type 'State'.ts(2344)
interface State
```

But when I change the interface to a type it works.

### Expected behavior

Interfaces should be allowed for the state type.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

`@ngrx/signals` v17.0.0-beta.0
`typescript` v5.2.2
`Angular` v17

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by markostanimirovic** [comment]
This is by design. Interfaces are not compatible with `Record<string, unknown>` (missing index signature).

Anyway, removing this restriction will be considered.

**Comment by npx** [comment]
It is very common to rather use Interfaces than types. It is also advised online, due to better error messages and extensibility. This restriction must be communicated clearly then, however, I would advise to lose that restriction, as a lot of libraries that are providing typing that you might want in your store (e.g. EntityState of @ngrx/entity) are based on interfaces.
While I see the efforts behind the "withEntities" creator function, I still feel this is rather limiting.

If the team stands by this decision, make sure to communicate it, as it also caught me by surprise, and feels a little odd.

**Comment by markostanimirovic** [comment]
> It is very common to rather use Interfaces than types. It is also advised online, due to better error messages and extensibility. This restriction must be communicated clearly then, however, I would advise to lose that restriction, as a lot of libraries that are providing typing that you might want in your store (e.g. EntityState of @ngrx/entity) are based on interfaces.

true 👍 

> While I see the efforts behind the "withEntities" creator function, I still feel this is rather limiting.

Can you provide more details on what seems limiting to you?

**Comment by npx** [comment]
Well, do not get me wrong. I love everything about the signal store, and I love its API. The limiting only seems to stem from the Interface problem. I love to use the EntityAdapter for any kind of collection, also in ComponentStores:

```

type EntityState<T> = {
  ids: string[] | number[];
  entities: Dictionary<T>;
};

type TodoListState = {
  id: string;
  title: string;
  loading: boolean;

  editing: string;
} & EntityState<TodoListItem>;

const todolist = createEntityAdapter<TodoListItem>();

const initialState: TodoListState = todolist.getInitialState({
  id: '',
  title: '',
  loading: true,
  editing: '',
});

const store = signalStore(withState(initialState));

```

`@ngrx/entity` is probably not the only package that provides you with datatypes that are interfaces that you might want to extend, or incorporate into your state.

The above feels a little awkward or clunky. Of course it is possible to use it as such:

```
type MyState = { entities: EntityState<Item> };

const initialState: MyState = { entities: adapter.getInitialState() };
```

While possible, it doesnt feel as natural as extending interfaces, which is what interfaces are really good at and mostly used for. 

Same, if you have some common utility interfaces like "HasLoadingState" or "HasErrorState".

I know that there will probably be packages extending the signal store (e.g. withEntities, withLoading, ...). However, I must say it feels odd to me to have to use types for this.
