### ISSUE TITLE
removeOne and removeMany Adapter Collection Methods missing in docs example

### ISSUE THREAD

**Issue by TheRedD0t** [ngrx/platform#412]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
</code></pre>

## What is the current behavior?
`DELETE_USER` and `DELETE_USERS` actions are described in `user.actions.ts` but never used in `user.reducer.ts`.

## Expected behavior:
They should be used in the reducer example as well.

## Minimal reproduction of the problem with instructions:
Just have a look at the [documentation](https://github.com/ngrx/platform/blob/master/docs/entity/adapter.md#adapter-collection-methods).

**Comment by brandonroberts** [comment]
Fixed via 793e262da953a917603c0a63a6815462d23bcb0d

**Comment by MikeRyanDev** [comment]
Closed in ddb2f97
