### ISSUE TITLE
Proposal for Scoped Utility Extensions in ngrx/signals

### ISSUE THREAD

**Issue by va-stefanek** [ngrx/platform#4125]
### Which @ngrx/* package(s) are relevant/related to the feature request?

signals

### Information

I believe it could be valuable to introduce a scope for certain utility extensions that may be widely used in conjunction with the `signalStore`.

Some potential utils:
**withDispatchers** -> extension will accept actions to dispatch and create in scope of the `signalStore` instance methods, accepting same payload as action and dispatch passed action.
**withQueryParam** -> extension will accept queryParams name and create signals if the param is present in route.

I think there will be even more proposals from community :) 

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by markostanimirovic** [comment]
I think the mentioned features are good candidates for community plugins!

Can you provide an example of how the usage of `withDispatchers` should look like?

**Comment by va-stefanek** [comment]
@markostanimirovic I have been thinking about something like that

```
const Store = signalStore(
        withMethods(() => inject(TOKEN)),
        withDispatchers({
          login: loginSuccess,
        }),
      );

      const store = TestBed.inject(Store);

      expect(store.baz()).toBe('baz');
      store.login({user: {name: 'test'}})
```

```
export function withDispatchers<
  Input extends SignalStoreFeatureResult,
  DispatchersKey extends string,
  ActionType extends string,
  C extends Creator = Creator
>(
  dispatchersMap: Record<DispatchersKey, ActionCreator<ActionType, C>>
): SignalStoreFeature<Input, EmptyFeatureResult & { dispatchers: Record<DispatchersKey, C> }> {
  return (store) => {
    const _ngrxStore = inject(Store);
    const dispatchers = Object.entries(dispatchersMap).reduce(
      (pv, [k, v]: [string, any]) => ({
        ...pv,
        [k]: (...args: C[]) => {
          // Dispatch the action using the action creator
          _ngrxStore.dispatch(v({ ...args }));
        },
      }),
      {} as Record<DispatchersKey, (...args: C[]) => void>
    );
    const dispatchersKeys = Object.keys(dispatchers);
    const signals = excludeKeys(store.signals, dispatchersKeys);
    const slices = excludeKeys(store.slices, dispatchersKeys);
    const methods = excludeKeys(store.methods, dispatchersKeys);

    return {
      ...store,
      slices,
      signals,
      methods,
      dispatchers: { ...store.dispatchers, ...dispatchers },
    } as InnerSignalStore<Record<string, unknown>, SignalsDictionary, MethodsDictionary, Record<DispatchersKey, C>>;
  };
}

```

**Comment by markostanimirovic** [comment]
> const Store = signalStore(
>     withMethods(() => inject(TOKEN)),
>     withDispatchers({
>         login: loginSuccess,
>     }),
> );
> 
> const store = TestBed.inject(Store);
> 
> expect(store.baz()).toBe('baz');
> store.login({
>     user: {
>         name: 'test'
>     }
> })

Can you provide more details on how `withDispatchers` should be used? 👀 For instance:

- What's returned by the `inject(TOKEN)`?
- What is `loginSuccess` in your example? Is it an action creator or something else?
- What should happen when `store.login` is called? How to define an updater/effect that listens to the dispatched action?

**Comment by va-stefanek** [comment]
I see that example could be misleading.  

The usage of withDispatchers assume you already have ngrx global state in your project. Util is just to simplify defining methods which responsibility is only dispatching actions handled in scope of the global state. 

**actions.ts**
 `export const loginSuccess = createAction(
  '[Auth/API] Login Success',
  props<{ user: User }>()
);`

`login.component.ts`
```
....
const store = inject(signalStore(
    withDispatchers({
      login: loginSuccess,
    }),
));

// Might be that we will not create that method and call directly store.login. It's only to example purpose
loginUser(user: User): void {
  store.login({...user})
}

```

**Comment by markostanimirovic** [comment]
As we discussed, there is no plan to add these features to the core package, but they are great candidates for community plugins!
