### ISSUE TITLE
DefaultDataService HttpOptions

### ISSUE THREAD

**Issue by Tom-Neo** [ngrx/platform#4126]
### Which @ngrx/* package(s) are the source of the bug?

data

### Minimal reproduction of the bug/regression with instructions

Use of DefaultDataService methods with parameter (options?: HttpOptions) dosn't work.

Example dont work;
super.getAll({httpParams: {fromObject: {language: 'en'}} })

this works:
super.execute('GET', this.entitiesUrl, null, { params: new HttpParams().set('language', 'en') })
or
super.getAll({ params: new HttpParams().set('language', language: 'en') } as any)

### Expected behavior

HttpOptions should correctly passed to the http client

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

"@ngrx/data": "^16.2.0",
"@angular/core": "^16.2.6",

### I would be willing to submit a PR to fix this issue

- [x] Yes
- [ ] No

**Comment by timdeschryver** [comment]
@Tom-Neo could you elaborate with "does work" and "doesn't work" please.
What's the expected result, and which result do you get instead?
Ideally, this is a runnable example.

Also, if this is a bug feel free to create a Pull Request with a fix.

**Comment by Tom-Neo** [comment]
I'm using a derivative of the DefaultDataService class and wanted to use the methods' parameter options.
The http options are not passed correctly or the type is not correct.
How to properly use options to pass HttpParams?
