### ISSUE TITLE
Incompatible types when following the docs

### ISSUE THREAD

**Issue by TheRedD0t** [ngrx/platform#413]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
</code></pre>

## What is the current behavior?
In the documentation, the `DeleteUser` and `DeleteUsers` actions take payload with content of type `User`.
`user.actions.ts`
```
export class DeleteUser implements Action {
  readonly type = DELETE_USER;

  constructor(public payload: { user: User }) {}
}

export class DeleteUsers implements Action {
  readonly type = DELETE_USERS;

  constructor(public payload: { users: User[] }) {}
}
```
But the Entity methods asks for parameter of type string and string[ ]
`models.d.ts`
```
[...]
removeOne<S extends EntityState<T>>(key: string, state: S): S;
removeMany<S extends EntityState<T>>(keys: string[], state: S): S;
[...]
```
This causes a error if you want to use the methods in the reducer.
`(Argument of type 'Users' is not assignable to parameter of type 'string'.)`
## Expected behavior:
The types should be compatible to each other.
## Minimal reproduction of the problem with instructions:
Just have a look at the [documentation](https://github.com/ngrx/platform/blob/master/docs/entity/adapter.md#adapter-collection-methods).
## Other information:
I guess the `string` which are taken by `removeOne` and `removeMany` are the ids of the user(s), so I know you can use `action.payload.user.id` for `removeOne` and code a little helperfunction for `removeMany`, that extracts the ids from the user array, but I'm not sure if this is considered as bad practice.

**Comment by brandonroberts** [comment]
Fixed via 793e262da953a917603c0a63a6815462d23bcb0d
