### ISSUE TITLE
Install in fresh v17 Angular project?

### ISSUE THREAD

**Issue by JimLynchCodes** [ngrx/platform#4132]
### Which @ngrx/* package(s) are the source of the bug?

store

### Minimal reproduction of the bug/regression with instructions

Hi, I have a package.json defining some Angular v17 dependecies:

```
"dependencies": {
    "@angular/animations": "^17.0.0",
    "@angular/common": "^17.0.2",
    "@angular/compiler": "^17.0.0",
    "@angular/core": "^17.0.2",
    "@angular/forms": "^17.0.2",
    "@angular/platform-browser": "^17.0.0",
    "@angular/platform-browser-dynamic": "^17.0.0",
    "@angular/router": "^17.0.0",

    ...
}
```

when I run `npm i @ngrx/store` it just fails though... is @ngrx/store not supported for Angular v17+?

> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR!
> npm ERR! While resolving: ng-v17-example@0.0.0
> npm ERR! Found: @angular/core@17.0.2
> npm ERR! node_modules/@angular/core
> npm ERR!   @angular/core@"^17.0.2" from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer @angular/core@"^16.0.0" from @ngrx/store@16.0.0
> npm ERR! node_modules/@ngrx/store
> npm ERR!   @ngrx/store@"*" from the root project
> npm ERR!
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR!
> npm ERR!

### Expected behavior

expecting it to figure out the necessary dependencies and install fine.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

command for this is what?

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [X] No

**Comment by markostanimirovic** [comment]
Take a look at: https://github.com/ngrx/platform/issues/4115
