### ISSUE TITLE
provideEffects([Effect]) does not work in ApplicationConfig

### ISSUE THREAD

**Issue by bh3605** [ngrx/platform#4142]
### Which @ngrx/* package(s) are the source of the bug?

effects

### Minimal reproduction of the bug/regression with instructions

```
import { HttpClient } from "@angular/common/http";
import { ApplicationConfig, inject } from "@angular/core";
import { createActionGroup, props, provideStore } from "@ngrx/store";
import { Actions, createEffect, ofType, provideEffects } from "@ngrx/effects";
import { exhaustMap, map } from "rxjs";
import { bootstrapApplication } from "@angular/platform-browser";
import { AppComponent } from "./app.component";

const effect = createEffect(
  (actions$ = inject(Actions), applicantsService = inject(HttpClient)) => {
    return actions$.pipe(
      ofType(MyActions.loadApplicant),
      exhaustMap((action) => {
        return applicantsService.get<string>("url").pipe(map(response => MyActions.loadApplicant({caseNumber: response})));
      })
    );
  }
);

export const MyActions = createActionGroup({
  source: "Applicant",
  events: {
    "Load Applicant": props<{ caseNumber: string }>(),
  }
})

export const appConfig: ApplicationConfig = {
  providers: [
    provideStore(),
    provideEffects([effect])
  ]
};

bootstrapApplication(AppComponent, appConfig);
```

The line with provideEffects() throws error
No overload matches this call.
  Overload 1 of 2, '(effects: (Type<unknown> | Record<string, FunctionalEffect>)[]): EnvironmentProviders', gave the following error.
    Type 'Observable<{ caseNumber: string; } & TypedAction<"[Applicant] Load Applicant">> & CreateEffectMetadata' is not assignable to type 'Type<unknown> | Record<string, FunctionalEffect>'.
      Type 'Observable<{ caseNumber: string; } & TypedAction<"[Applicant] Load Applicant">> & CreateEffectMetadata' is not assignable to type 'Record<string, FunctionalEffect>'.
        Index signature for type 'string' is missing in type 'Observable<{ caseNumber: string; } & TypedAction<"[Applicant] Load Applicant">> & CreateEffectMetadata'.
  Overload 2 of 2, '(...effects: (Type<unknown> | Record<string, FunctionalEffect>)[]): EnvironmentProviders', gave the following error.
    Type 'Observable<{ caseNumber: string; } & TypedAction<"[Applicant] Load Applicant">> & CreateEffectMetadata' is not assignable to type 'FunctionalEffect'.
      Type 'Observable<{ caseNumber: string; } & TypedAction<"[Applicant] Load Applicant">> & CreateEffectMetadata' is not assignable to type '() => Observable<unknown>'.
        Type 'Observable<{ caseNumber: string; } & TypedAction<"[Applicant] Load Applicant">> & CreateEffectMetadata' provides no match for the signature '(): Observable<unknown>'.

### Expected behavior

I can pass my Effect in the root configuration just as the tutorial states

https://ngrx.io/guide/effects#using-the-standalone-api

```
bootstrapApplication(AppComponent, {
  providers: [
    provideStore(),
    provideEffects(MoviesEffects, actorsEffects),
  ],
});
```

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx: 16.3
Angular: 16.2.7

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by markostanimirovic** [comment]
The `provideEffects` function expects a dictionary of effects as an input argument, not a single effect. Check the guide: https://ngrx.io/guide/effects#using-the-standalone-api (`import * as actorsEffects from './actors.effects'`).

If you want to provide a single (functional) effect, you can do that in the following way:

```ts
const effect = createEffect(() => { /* ... */ }, { functional: true });

provideEffects({ effect });
```
