### ISSUE TITLE
fix: 🐛   Route guards that expect state to change never complete

### ISSUE THREAD

**Issue by bjornharvold** [ngrx/platform#4149]
### Which @ngrx/* package(s) are the source of the bug?

store

### Minimal reproduction of the bug/regression with instructions

[Stackblitz](https://stackblitz.com/~/github.com/bjornharvold/ngrx-issue-4149)

### Expected behavior

With the new standalone provider paradigm, I feel lazy loading of state just took a step backwards [or at least made it more complicated].

We just finished migrating to Angular 17 and chose to go 100% in on "the standalone way of doing things" instead of having 2 ways of handling state (NgModule vs providers).

What we did not anticipate was that some of our route guards stopped working. And by "stopped working", the page suddenly wouldn't load if going directly to it.

Look at the Stackblitz and simple steps to reproduce below. Keep console open for some print statements:

1. Open app new window to properly see the url
2. Load the page
3. Click the lazy link. Router navigates to /lazy.
4. Refresh the '/lazy' page
5. You'll find the app hanging in an unresolved state waiting for the flag to become true

I'd say this is a regression as it works with the NgModule paradigm.

Temporary fix:
- Removed all guards and resolvers on lazy loaded routes that relied on Ngrx state.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

Angular: 17.0.4
Nx: 17.1.3
Ngrx: 17.0.0

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by bjornharvold** [comment]
This is not an Ngrx issue

**Comment by bjornharvold** [comment]
Actually, it is an Ngrx issue. Feature state should be available to AppComponent after createApplication or bootstrapApplication is called.

**Comment by bjornharvold** [comment]
Please ignore. This does not relate to ngrx.

🦸‍♂️

**Comment by brandonroberts** [comment]
Thanks @bjornharvold. We did not change anything intentionally to impact this behavior. This could be a difference in behavior on how the `ENVIRONMENT_INITIALIZER` works as opposed to using the NgModule constructor. Either way, this should still work the same way as before, and we'll at least see why that's not the case.

**Comment by bjornharvold** [comment]
Hi @brandonroberts 

Should we circle back to the Angular Team? One of the reasons it's hanging is the router feature called: withEnabledBlockingInitialNavigation(). But removing this also doesn't help, as it just fails immediately instead of waiting for the updated result.

**Comment by brandonroberts** [comment]
If you can reproduce it with a simple service + BehaviorSubject, I think that would help to narrow the issue down.

**Comment by bjornharvold** [comment]
I've updated the Stackblitz with a simplified version of this problem and filed it with Angular here: 

https://github.com/angular/angular/issues/53247
