### ISSUE TITLE
Select slices of state via @select annotation

### ISSUE THREAD

**Issue by Silthus** [ngrx/platform#416]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

Currently we need to define a selector for every select operation und use it inside our components.

## Expected behavior:

It would be great if we could inject selected slice of state into the components with an `@select` annotation, like it is done in `redux-angular`: https://github.com/angular-redux/store/blob/master/articles/select-pattern.md

**Comment by brandonroberts** [comment]
This has been discussed at length before, but besides decorators not having access to DI, we're not considering adding these to the API.

**Comment by fxck** [comment]
Too bad those lengthy discussions are now inaccessible with store issues section gone.

**Comment by MikeRyanDev** [comment]
@fxck 🥇

**Comment by Fallenstedt** [comment]
The enthusiasm about decorators here makes me question the lifespan of the effects decorator. https://github.com/ngrx/platform/blob/master/docs/effects/README.md

**Comment by sandangel** [comment]
I have created a simple Select decorator. You can look for more info here https://github.com/ngrx-utils/ngrx-utils
