### ISSUE TITLE
Add ESLint Plugin rule for createSelector usages with over 8 inputs

### ISSUE THREAD

**Issue by NathanLaing** [ngrx/platform#4164]
### Which @ngrx/* package(s) are relevant/related to the feature request?

eslint-plugin

### Information

Currently it seems like typing / autocomplete is lost in html (at least in WebStorm) when the number of inputs for a selector goes over 8.

I see increasing this limit has been proposed in the past https://github.com/ngrx/platform/issues/1192.

If the suggested better practice is to combine selectors where possible thus keeping the inputs under 8, it would be nice to have a linting rule for that.

Especially where going over the 8 loses you some IDE functionality.

Happy and willing to submit a PR but would have to check out repo and find my way around.

### Describe any alternatives/workarounds you're currently using

- Combining selectors to try keep the inputs under 8
- Living without autocomplete / typing

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by timdeschryver** [comment]
I like the idea @NathanLaing , if you want feel free to create a PR for this.
