### ISSUE TITLE
@ngrx/avoid-cyclic-effects is triggered in takeUntil(merge()) operator

### ISSUE THREAD

**Issue by egarkavy** [ngrx/platform#4168]
### Which @ngrx/* package(s) are the source of the bug?

eslint-plugin

### Minimal reproduction of the bug/regression with instructions

Having @ngrx/avoid-cyclic-effects rule, it successfully ignores this.actions$.pipe if it is directly specified in a takeUntil operator. But if it becomes a part of observable creation operator, like concat/merge... then this rule activates and prevents lint from successful completion.

```
 const requestData = createAction('Request');
 const requestDataSuccess = createAction('requestDataSuccess');

 @Injectable()
 export class Effects {
    private readonly actions$: Actions = inject(Actions);

    public readonly requestData$ = createEffect(() => {
    return this.actions$.pipe(
      ofType(requestData),
      switchMap(() => {
        return timer(500).pipe(
          map(() => {
            return requestDataSuccess();
          }),
          takeUntil(merge(timer(1000), this.actions$.pipe(ofType(requestData))))
        );
      })
    );
  });
}
```
![image](https://github.com/ngrx/platform/assets/22226318/7d2d929e-d313-46fc-837d-22fbb22002b2)

The only one way to avoid it to assign a property in effects which will represent an this.actions$.pipe(...) observable and use it in merge(). But I would like to avoid it if possible 

### Expected behavior

eslint should not complain in anything happening in takeUntil operator

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx: 17
Angular: 17
Node: 18
Windows OS

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by timdeschryver** [comment]
Thanks for reporting this (with a reproduction) @egarkavy !

**Comment by egarkavy** [comment]
@timdeschryver thank you for that light-speed response and action!
