### ISSUE TITLE
NGRX polling with Entity (State updates even when data hasn't changed)

### ISSUE THREAD

**Issue by Coconaut5** [ngrx/platform#4170]
### Which @ngrx/* package(s) are the source of the bug?

effects, entity, store

### Minimal reproduction of the bug/regression with instructions

Hi there, I apologize if this is not the right place to ask but I have not been able to find any response to my issue.

I have an application where i need to poll for http request to keep the state continously updated with our backend. 

I have an effect such as:

```
pollBooks$ = createEffect(() => {
		return this.actions$.pipe(
			ofType(pollBooksEffect),
			concatMap(() =>
				this.http.getBooks().pipe(
					map((dto) => {
							return setAllBooks({
								books: dto.books
							});
					}),
					repeat({ delay: 3000 }),
					takeUntil(
						this.ui.pollingActive$.pipe(
							filter((value) => !value.books)
						)
					)
				)
			)
		);
	});
```
	
a reducer case:
	
```
on(setAllBooks, (state, { books}) => {
		return adapter.setAll(books, { ...state, loading: false });
	}),
```
	
and a simple selector:
	
```
export const allBooks = createSelector(
	BooksEntityState,
	entityAdapter.selectAll
);

```
when i use the selector in my component:

`books$ = this.store.select(allBooks)`
		
I can see that it contionously emits values, triggers changeDetection and causes ui items to rerender even when the data hasn't changed at all. (The data doesnt move that much or that fast). 
		
First of all I wonder, what part has the responsiblity of making sure this doesnt happen? Is it the effect, reducer or selector? 
		Am I even supposed to handle this manually at all? Or ss there perhaps some issue with immutability?

Thankful for any help!
	

### Expected behavior

Store should not be updated or selector should not emit a new value if it is the same as previous.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx: 16.3.0
Angular: 16.2.12

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by markostanimirovic** [comment]
Hi @Coconaut5,

We're using GitHub issues for bugs and documentation/feature requests. For questions, you can use StackOverflow, GitHub discussions, or join our [Discord server](https://discord.gg/ngrx).
