### ISSUE TITLE
Signal store and signal state should have something like connectSignal and connectObservable to connect streams/signals to state

### ISSUE THREAD

**Issue by sokolej79** [ngrx/platform#4179]
### Which @ngrx/* package(s) are relevant/related to the feature request?

signals

### Information

Signal store and signal state should have some helper function utils like connectSignal  and connectObservable (or just connect for both)  to connect realtime data rx streams or signals to state.
Can be track router params,  streams,  http request...
Could also have something like  trigger() method for connect, to re-execute connected stream (below in second link ngx-signal-state, section Retriggering Observables).

Something like this two packages have:
https://ngxtension.netlify.app/utilities/signals/connect/
https://github.com/simplifiedcourses/ngx-signal-state/tree/master (under connect section)

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by rainerhahnekamp** [comment]
That is actually a built-in feature of `rxMethod`:

```typescript
    const Store = signalStore(
      withState({ date: new Date() }),
      withMethods((store) => ({
        updateTime: rxMethod<Date>(
          pipe(tap((date) => patchState(store, { date })))
        ),
      }))
    );

    const date$ = interval(1000).pipe(map(() => new Date()));
    const store = new Store();
    store.updateTime(date$);

    effect(() => {
      console.log(store.date());
    });
```

`rxMethod` would also be able to consume a signal instead of an Observable.

Was that what you were looking for?

**Comment by sokolej79** [comment]
Thanks for the reply.
I know this way how to currently connect observable or signal with Store,
I thought that these helper methods like connectToStore similar to withMethods would be a more transparent way.
I see that there is not much interest, so I am closing.
Thanks anyway.
