### ISSUE TITLE
@ngrx/signals: ability to use method inside rxMethod

### ISSUE THREAD

**Issue by pderiy** [ngrx/platform#4182]
### Which @ngrx/* package(s) are relevant/related to the feature request?

signals

### Information

It would be nice to have ability of calling methods from different methods.

Description:
- I have 3 methods: fetchIntegrations, pullProducts, pullInvoices
- After pulling products or invoices I'd like to refetch integrations

Current shortened component store implementation:

```
class IntegrationStore extends ComponentStore {
  readonly fetchIntegrations = this.effect((trigger$) =>
    trigger$.pipe(
      switchMap(() =>
        this.integrationsService.fetchList().pipe(
          tap(console.log),
        ),
      ),
    ),
  );

 readonly pullProducts = this.effect<{ integrationId: string }>((trigger$) =>
    trigger$.pipe(
      tap(() => this.patchState({ isLoading: true })),
      switchMap(({ integrationId }) =>
        this.integrationsService.pullProducts(integrationId).pipe(
          tapResponse(
            () => {
              this.fetchIntegrations();
              this.patchState({ isLoading: false, error: false });
            },
            () => this.patchState({ isLoading: false, error: true }),
          ),
        ),
      ),
    ),
  );

 readonly pullInvoices = this.effect<{ integrationId: string }>((trigger$) =>
    trigger$.pipe(
      tap(() => this.patchState({ isLoading: true })),
      switchMap(({ integrationId }) =>
        this.integrationsService.pullInvoices(integrationId).pipe(
          tapResponse(
            () => {
              this.fetchIntegrations();
              this.patchState({ isLoading: false, error: false });
            },
            () => this.patchState({ isLoading: false, error: true }),
          ),
        ),
      ),
    ),
  );
}
```

Expected signal store implementation:
```
const IntegrationStore = signalStore(
  withMethods((state, service = inject(Service)) => ({
    fetchIntegrations() {},
    pullProducts() {},
    pullIntegrations: rxMethod(
      pipe(
        switchMap(() =>
          service.fetch().pipe(
            tap(() => {
              this.fetchIntegrations();
            }),
          ),
        ),
      ),
    ),
  })),
);
```

### Describe any alternatives/workarounds you're currently using

I don't have a workaround at this moment. It just works with @ngrx/store and @ngrx/component-store.

So my question is do u have any plans or workaround to make this work?

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by markostanimirovic** [comment]
Hi @pderiy,

You can achieve the requested behavior as follows:

```ts
const IntegrationStore = signalStore(
  withMethods((state, service = inject(Service)) => {
    function fetchIntegrations() {}
    
    function pullProducts() {}
    
    const pullIntegrations = rxMethod<void>(
      switchMap(() =>
        service.fetch().pipe(
          tap(() => fetchIntegrations())
        ),
      ),
    );    

    return { fetchIntegrations, pullProducts, pullIntegrations };
  }),
);
```

Additionally, if some method should not be part of the public API, you can exclude it from the returned object.

---

We use issues for feature requests/bug reports. For any further questions, feel free to start the GitHub discussion or join our [Discord server](https://discord.gg/ngrx).

**Comment by pderiy** [comment]
@markostanimirovic makes sense
thank you :)

**Comment by nickregeda** [comment]
@pderiy 
To access the fetchIntegrations() method, you can simply declare another withMethods() under the existing one and implement the pullIntegrations() method inside it. In this case, your store will already have the fetchIntegrations() method and you can call it from the second withMethods().

**Comment by abhijit-chikane** [comment]
How to call another Rxmethod inside other Rxmethod?

**Comment by distante** [comment]
> Hi [@pderiy](https://github.com/pderiy),
> 
> You can achieve the requested behavior as follows:
> 
> const IntegrationStore = signalStore(
>   withMethods((state, service = inject(Service)) => {
>     function fetchIntegrations() {}
>     
>     function pullProducts() {}
>     
>     const pullIntegrations = rxMethod<void>(
>       switchMap(() =>
>         service.fetch().pipe(
>           tap(() => fetchIntegrations())
>         ),
>       ),
>     );    
> 
>     return { fetchIntegrations, pullProducts, pullIntegrations };
>   }),
> );
> Additionally, if some method should not be part of the public API, you can exclude it from the returned object.
> 
> We use issues for feature requests/bug reports. For any further questions, feel free to start the GitHub discussion or join our [Discord server](https://discord.gg/ngrx).


While this achieves this use case, it force us to manually export each function in the return and could carry errors like forget to export one function. And if a store has a lot of methods it is just ugly.
