### ISSUE TITLE
Router Navigate does not update router state data. selectRouteData returns {}

### ISSUE THREAD

**Issue by robertlario** [ngrx/platform#4185]
### Which @ngrx/* package(s) are the source of the bug?

router-store

### Minimal reproduction of the bug/regression with instructions

The state data is not being updated/recorded.

I would expect this call to store "Test" in the state.data field:

this.router.navigate(['/Universe'], { queryParams: {id : "00000000-0000-0000-0000-000000000000"},  state : { data: "Test"}}

Both are set as expected:
queryParams  =  {id :  "00000000-0000-0000-0000-000000000000")
 URL = "/Universe?id=00000000-0000-0000-0000-000000000000"

However data = {}

Here selectRouteData returns : {}

 this.store.select(selectRouteData)
            .subscribe(params => {

                console.log("selectRouteData" + params);
            })

### Expected behavior

state.data should be "Test" not {}

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

Angular CLI: 16.2.8
Node: 16.17.0
Package Manager: yarn 1.22.19
OS: win32 x64

Angular: 16.2.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.8
@angular-devkit/build-angular   16.2.8
@angular-devkit/core            16.2.8
@angular-devkit/schematics      16.2.8
@angular/cdk                    16.2.10
@angular/cli                    16.2.8
@angular/http                   7.2.16
@angular/localize               16.2.12
@angular/material               16.2.10
@schematics/angular             16.2.8
rxjs                            6.5.5
typescript                      5.1.6
zone.js                         0.13.3

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by timdeschryver** [comment]
The state within the store reflects the state from the Angular router.
As far as I know, the router's state isn't updated with the `state` passed with the `navigate` method. Instead, it's only available on the router's navigation event.

`selectRouteData` returns the Angular router's state, which will be the static `data` that's been configured for a route.

**Comment by robertlario** [comment]
This example is what informed me of this approach:
stackoverflow.com/questions/59031292/how-to-transfer-data-between-unrelated-pagesangular-8
"You have the three ways for transfer data." ->  "Using Router.navigate()"

Your response on "@ngrx/router-store selectRouteData returns always empty #2680" seems to be related to this issue. If I understand it correctly, would imply the following should work given:

Looking at the Class Router. The method "navigate(commands: any[], extras?: NavigationExtras): Promise<boolean>" has the parameter "extras" typed as "NavigationExtras" which extends "UrlCreationOptions" and "NavigationBehaviorOptions".

"NavigationBehaviorOptions" has a property "state" defined as:
    state?: {
        [k: string]: any;
    };

The documentation on "state" is :

/**
     * Developer-defined state that can be passed to any navigation.
     * Access this value through the `Navigation.extras` object
     * returned from the [Router.getCurrentNavigation()
     * method](api/router/Router#getcurrentnavigation) while a navigation is executing.
     *
     * After a navigation completes, the router writes an object containing this
     * value together with a `navigationId` to `history.state`.
     * The value is written when `location.go()` or `location.replaceState()`
     * is called before activating this route.
     *
     * Note that `history.state` does not pass an object equality test because
     * the router adds the `navigationId` on each navigation.
     *
     */

Perhaps I am misinterpreting this, but as I read it, this: 

this.router.navigate(['/Universe'], { queryParams: {id : "00000000-0000-0000-0000-000000000000"}, state : { data: "Test"}}

should set the state data to "Test" in the router store. And :

this.store.select(selectRouteData).subscribe(data=> {
            console.log("selectRouteData: " + data);
})

would display "selectRouteData: Test"

I appreciate your insight!

**Comment by timdeschryver** [comment]
@robertlario `state` is not stored in the router snapshot (NgRx router-state uses this to built its state), instead `state` only available using `getCurrentNavigation()` as you've pointed out.

The implementation of `selectRouteData` returns the configured data on a route.

For example: `selectRouteData` returns `{ "dataProperty": "From routes" }` for the following route:

```ts
const routes: Routes = [
  {
    path: '',
    component: TestComponent,
    data: {
      dataProperty: 'From routes',
    },
  },
];
```
