### ISSUE TITLE
Firebase ngrx by freezing firebase-cdk

### ISSUE THREAD

**Issue by HaidarVladyslav** [ngrx/platform#4187]
### Which @ngrx/* package(s) are the source of the bug?

store

### Minimal reproduction of the bug/regression with instructions

I have repo with this case and I think I described issue well, so you can check it. But in general - I can see a lot of errors in console and can't interact with firebase-cdk and ngrx-store correctly.

https://github.com/HaidarVladyslav/netflix-clone1/issues/1

### Expected behavior

Maybe we need some workaround for that, but for now I don't have any ideas. Maybe I'm wrong somewhere, so it would be good if you check and let me know. Thanks

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

node v18.15.0
OS: Windows

repo exists for you to check

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by timdeschryver** [comment]
It's the intended result that the NgRx store freezes actions and the state. This is to force immutability within the application, making sure that no state is updated outside of the reducers.

For help refer to the [NgRx Discord Server](https://discord.com/invite/ngrx).
