### ISSUE TITLE
Documentation Website

### ISSUE THREAD

**Issue by ShadowManu** [ngrx/platform#419]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## What is the current behavior?

To search for existing API and documentation, you have to search with the markdown documentation files. 

## Expected behavior:

To easily search for API's and documentation in a dedicated website for it

## Other information:
I really like the project. Our team has been refactoring some rxjs-based logics and services these 2 months with the store and its being a good journey so far. However, I think we can do better with the documentation and provide a website for the docs. Can it be considered? I'm all-in to help with that.

**Comment by brandonroberts** [comment]
Thanks! We have thought about putting a site together already, but haven't formalized any plans yet. We'll keep the community updated!

**Comment by ShadowManu** [comment]
Consider [compodoc](https://github.com/compodoc/compodoc) ;)

**Comment by ShadowManu** [comment]
Any place we can track (and contribute) to it?
