### ISSUE TITLE
signalStoreFeature: inject(MatDialog) not possible

### ISSUE THREAD

**Issue by leomayer** [ngrx/platform#4197]
### Which @ngrx/* package(s) are the source of the bug?

signals

### Minimal reproduction of the bug/regression with instructions

I would like to open within a method a MatDialog for further processing. I try the following code:
```
export function withSignalsDisplayDialog() {
  return signalStoreFeature(
    withMethods((state) => ({
      displayDialog(showDialog: boolean) {
        console.log('show dialog - 0');
        const dialog = inject(MatDialog);
        console.log('show dialog - 1');
        patchState(state, { showDialog });
        if (showDialog) {
          const dialogRef = dialog.open(CalDetailsDialogComponent, {... });
          dialogRef.afterClosed() .subscribe(() => patchState(state, { showDialog: false }));
        }      },     })),   ); }
```

### Expected behavior

Althoug I see `show dialog - 0`  I cannot see on the console `show dialog - 1`

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

Angular: 17.0.5
@ngrx/signals: "^17.0.1"
OS: Linux

### Other information

My setup could be found in 
https://github.com/leomayer/zen-calendar

in the file
src/app/calendar-container/cal-details-dialog

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by markostanimirovic** [comment]
Hi @leomayer,

Dependencies need to be injected out of the method body:

```ts
withMethods((store, dialog = inject(MatDialog)) => ({
  displayDialog() {
    dialog.open(/* ... */)
  }
}))
```

or:

```ts
withMethods((store) => {
  const dialog = inject(MatDialog);

  return {
    displayDialog() {
      dialog.open(/* ... */)
    },
  };
})
```

For any further question, feel free to join our [Discord Server](https://discord.gg/ngrx).

**Comment by leomayer** [comment]
@markostanimirovic : The first solution works, the second not - I get 
```
Uncaught Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`
```
Anyway - since I don't care about the difference and I have a running workaround: Thx a lot for your immediate response.

**Comment by markostanimirovic** [comment]
The first snippet is just a shorter version of the second one. In other words, they're equivalent.

Make sure that you copied the code correctly - `inject` needs to be called within the `withMethods` factory body, but out of the `displayDialog` method.
