### ISSUE TITLE
on() with union type causes ts2322

### ISSUE THREAD

**Issue by cheng93** [ngrx/platform#4198]
### Which @ngrx/* package(s) are the source of the bug?

store

### Minimal reproduction of the bug/regression with instructions

https://stackblitz.com/edit/fpk2lk?file=src%2Fapp%2Fstate%2Fbooks.reducer.ts

```ts
type Toggle = 'A' | 'B';

interface State {
  toggle: Toggle;
}

const iState: State = {
  toggle: 'A',
};

const reducer = createReducer(
  iState,
  on(BooksApiActions.retrievedBookList, (state) => ({
    ...state,
    toggle: state.toggle === 'A' ? 'B' : 'A',
  }))
);

// below works! can't figure out why the above doesn't
let state: State = {
  toggle: 'A',
};

state = {
  ...state,
  toggle: state.toggle === 'A' ? 'B' : 'A',
};
```

`error TS2322: Type 'string' is not assignable to type 'Toggle'.`

### Expected behavior

No error

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

errors with
ngrx 17 with typescript 5.2.2
ngrx 16 with typescript > 5.0.4 (i don't remember exact version, just it errored when updating previously)

worked fine
ngrx 16 with typescript 5.0.4

### Other information

My initial instinct was that it was a typescript error, but I tried to recreate but couldn't get the error (see bottom half of code snippet)

Seems like a niche issue that could be because of typings in ngrx?

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by timdeschryver** [comment]
This is a known TypeScript issue, to cover this we have the [explicit-return-type](https://ngrx.io/guide/eslint-plugin/rules/updater-explicit-return-type) ESLint rule.

The snippet becomeos:

```ts
const reducer = createReducer(
  iState,
  on(BooksApiActions.retrievedBookList, (state): State => ({
    ...state,
    toggle: state.toggle === 'A' ? 'B' : 'A',
  }))
);
```

**Comment by cheng93** [comment]
I suppose it would of been a nice to have for it to be implicit

related to #2412 I suppose, but that's been closed

**Comment by timdeschryver** [comment]
@cheng93 Yea, that would be ideal. Unfortunately this is currently not supported by TS.
https://github.com/ngrx/platform/issues/2412#issuecomment-616206318
