### ISSUE TITLE
Migrate @ngrx/db to monorepo

### ISSUE THREAD

**Issue by robwormald** [ngrx/platform#42]
- need to set up browser testing infrastructure
- needs moar integration tests
- decide if current Schema API is what we want to keep?

**Comment by Jefiozie** [comment]
@brandonroberts  I'm wondering if this will be migrated any time soon?  Maybe we can create some tasks to start the migration slowly or is there no intention to do this any more?
I can help a bit on this migration with some help of you.

**Comment by Jefiozie** [comment]
Cc @MikeRyanDev

**Comment by vipex** [comment]
Any update on this?

**Comment by MatsumotoKou** [comment]
I still desire this feature.
Has there been any progress?

**Comment by brandonroberts** [comment]
✌🏿
