### ISSUE TITLE
Property accessors

### ISSUE THREAD

**Issue by Shyam-Chen** [ngrx/platform#420]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

```ts
import { Action } from '@ngrx/store';

import { Counter } from './model';
import { INITIAL, INCREMENT, DECREMENT } from './constants';

export default (state: Counter = INITIAL, action: Action): Counter => {
  const { type } = action;

  switch (type) {
    case INCREMENT:
      return { ...state, value: state.value + 1 };
    case DECREMENT:
      return { ...state, value: state.value - 1 };
    default:
      return state;
  }
};
```

## Expected behavior:

```js
// Redux - Reducer
import { handleActions } from 'redux-actions';

import { INITIAL, INCREMENT, DECREMENT } from './constants';

export default handleActions({
  [INCREMENT](state) {
    return { ...state, value: state.value + 1 };
  },
  [DECREMENT](state) {
    return { ...state, value: state.value - 1 };
  }
}, INITIAL);
```

```js
// Vuex - Mutations
import { INCREMENT, DECREMENT } from './constants';

export default {
  [INCREMENT](state) {
    state.value++;
  },
  [DECREMENT](state) {
    state.value--;
  }
};
```

## Minimal reproduction of the problem with instructions:

Not very good to write.

## Version of affected browser(s),operating system(s), npm, node and ngrx:

Browser: Chrome
OS: macOS
Node: v8.5.0
Yarn: v1.0.2
NgRx: v4.0.3

## Other information:

❌

**Comment by brandonroberts** [comment]
There's nothing preventing you from using that library to create your reducers. You do lose the type safety in your reducer functions, and exporting `default` for your reducer does not work with AoT. Its not something we need to add to the existing API.
