### ISSUE TITLE
Entity: adapter.addOrUpdate

### ISSUE THREAD

**Issue by jobvanstiphout** [ngrx/platform#421]
## I'm submitting a...
<pre><code>
[ ] Regression
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
Sometimes when receiving a full entity from the server, you don't know if it already exists. At the moment you need to check for that manually and choose to update instead of add.
```ts
    case user.ADD_USER: {
      const changes = action.payload.user;
      const id = changes.id;

      if (state.ids.indexOf(id) > -1) {
        return adapter.updateOne({ id, changes }, state);
      }
      
      return adapter.addOne(changes, state);
    }
```

## Expected behavior:
The adapter provides a method that adds the entity when it does not exists, but merges (or replaces as it's not a partial entity) the entity into the existing one when it does exist.
```ts
    case user.ADD_USER: {
      return adapter.addOrUpdateOne(action.payload.user, state);
    }

    case user.ADD_USERS: {
      return adapter.addOrUpdateMany(action.payload.users, state);
    }
```

**Comment by Silthus** [comment]
This should be added for many entities as well: `addOrUpdateMany`.

**Comment by karptonite** [comment]
This is called "Upsert" in some databases. There could also be call for "Replace", which would Add or replace rather than than Add or merge; this would be important if, for example, an entity with an optional field has that field unset (and not returned by the server).

**Comment by dinvlad** [comment]
+1, though another possible workaround is to simply compose the reductions:
```typescript
case user.ADD_USER: {
  const changes = action.payload.user;
  const id = changes.id;
  state = adapter.addOne({ id, changes }, state); // safe
  return adapter.updateOne(changes, state);
}
```

**Comment by brandonroberts** [comment]
Adding `upsertOne` and `upsertMany` seems reasonable.

**Comment by dinvlad** [comment]
Btw, in https://github.com/ngrx/platform/blob/aa7172a7e65faca530c6d4fd1c5f14b3805d3deb/modules/entity/src/unsorted_state_adapter.ts#L71-L90 why do we call computationally expensive `indexOf` when `index` only `has` to be used if the id has changed (and the check for `index === -1` can be easily replaced with `!(update.id in state.entities)`)? It may be wise to move it inside `if (newKey !== update.id) {` to avoid possible quadratic time penalty when calling `updateOneMutably` from `updateManyMutably`.

Same goes for @jobvanstiphout's comment above - if we are to implement upsertOne, we need to make  sure not to unnecessarily call `indexOf`.

**Comment by dinvlad** [comment]
Also, calling `updateOneMutably` from `updateManyMutably`, especially in https://github.com/ngrx/platform/blob/aa7172a7e65faca530c6d4fd1c5f14b3805d3deb/modules/entity/src/sorted_state_adapter.ts#L98 leads to quadratic time on average. But we could easily do an `N log N` using a binary search given the fact that the "old" array is already sorted.

**Comment by MikeRyanDev** [comment]
@dinvlad Will gladly accept PRs that improve perf 👍

**Comment by dinvlad** [comment]
sounds good, I can take a look into it

**Comment by dinvlad** [comment]
I've updated methods to improve performance of collection methods. Let me know if you'd consider a PR for upserts too.

**Comment by brandonroberts** [comment]
Sure

**Comment by xipheCom** [comment]
I would suggest "upsert" instead of "addOrUpdate". First many db systems do so and seconds it sounds better to say "upsertMany" instead of "addOrUpdateMany". It is definitly a must have for the adapter!

**Comment by roopkt** [comment]
I agree with @xipheCom .

**Comment by dinvlad** [comment]
Sorry got a bit distracted, can draft it over the weekend

**Comment by xipheCom** [comment]
Any progress @dinvlad ?

**Comment by dinvlad** [comment]
Submitted a PR. Sorry for the delay.

I kept the signature for `upsert()` methods identical to that of `update()`. Otherwise (i.e. if one uses that of `add()`), we get a type error for the `id` because `string | number` determined by `selectId` is not assignable to `Update` id for some reason, even though `Update` id is defined for both `string` and `number`. I think we can fix that, if you prefer the signature of `add()`.

**Comment by dinvlad** [comment]
More specifically,
```
Type '{ id: string | number; changes: any; }' is not assignable to type 'Update<T>'.
    Type '{ id: string | number; changes: any; }' is not assignable to type 'UpdateNum<T>'.
      Types of property 'id' are incompatible.
        Type 'string | number' is not assignable to type 'number'.
          Type 'string' is not assignable to type 'number'. (2345)
```
So to use `add()` signature for upserts, we need to change the signature of `Update` to
```ts
export type Update<T> = {
  id: string | number;
  changes: Partial<T>;
};
```

**Comment by dinvlad** [comment]
But then we won't be able to change `id` with `upsert()`, so it's a double-edges sword...

**Comment by xipheCom** [comment]
we should use the signature of Update for Upsert. If we think in a Database System update and upsert have both a query. They are very similar. An Insert (or Add) function has another task.

Add: Add something
Update: Update something with some condition
Upsert: Update something with some condition, in case it does not exist add it.

I think you have done it right! Any idea of the team when the PR will be accepted?

**Comment by georgeF105** [comment]
Nice work on the PR @dinvlad. One issue I can see with keeping the `Upsert()` type the same is `Update` is that this will mean partial objects can be pushed to the cache. In a project I am working on we created an `Upsert()` type function with a signature similar to update but without the partial:
```
export type FullUpdate<T> = {
  id: string | number;
  changes: T:
}
```
Changing the signature to be the same as Add would a good alternative.

**Comment by dinvlad** [comment]
Hmm, one thing I've just realized is that the current PR (and test fixtures) don't take into account the situation when `selectId` is different from `entity => entity.id`. So in the current method for insertion, I just assign the `id` of the inserted entity to be `update.id`. But if the effective id is named differently (e.g. `selectId = entity => entity.name`, then this simple approach will fail. So in that case, the only signature that can work is the one for `add()`.

**Comment by dinvlad** [comment]
We can also use
```ts
function upsertManyMutably(updates: FullUpdate<T>[], state: R): boolean;
...
updated.push(update);
// else
added.push(update.changes); // now each change must be a full object containing the effective id.
```
or
```ts
function upsertManyMutably(entities: T[], state: R): boolean;
...
updated.push({
  id: selectId(entity),
  changes: entity,
})
// else
added.push(entity);
```

**Comment by mcblum** [comment]
@dinvlad Thank you for your work on this. I'm about to refactor a pretty giant redux mess and I'm wondering if a merge is on the horizon? Your point about needing to respect the defined `selectorId` is good, though, we're using that a lot to make it not the `entity.id` prop.
