### ISSUE TITLE
Type of idKey is not recognized correctly when using generics

### ISSUE THREAD

**Issue by Raul52** [ngrx/platform#4217]
### Which @ngrx/* package(s) are the source of the bug?

signals

### Minimal reproduction of the bug/regression with instructions

I am trying to create a signal store feature using generics and I stumbled upon a typing error when trying to use the idKey:
https://ngrx.io/guide/signals/signal-store/entity-management#customized-id-property

I have the following feature:

```typescript
export interface Entity {
    uuid: EntityId;
}

export function withEntityLoader<E extends Entity, F, S extends LoaderService<E, F>>(loaderServiceType: Type<S>, filter: F) {
    return signalStoreFeature(
    ......
        withMethods((store) => {
            const dataService = inject(loaderServiceType);

            return {
                load() {
                    rxMethod<void>(
                    ....................................................
                                    tapResponse({
                                        next: response => {
                                            patchState(store, setAllEntities(response.items, {idKey: 'uuid'}));
                                        },
                                    }),
                                ),
                            ),
                        ),
                    );
                },
            };
        }),
    );
}
```

I checked how the type definition is made internally and tried to reproduce it with as concise an example as I could.

context:

- `usingType()` function is used to mimick what any `set*` method would do if you accessed the config object.

[Current faulty behavior](https://www.typescriptlang.org/play?ssl=10&ssc=2&pln=8&pc=1#code/KYDwDg9gTgLgBDAnmYcCiA7GBLJBJAEzgF44BnGKbDAczgB84MBXAWwCNgoBuAKF9CRYCZKkw58BAApQIYMgB5xuRAD4ScAN684uuAG0A0nGpwA1sEQQAZuiwq4AQzJ2JiIwF04oGMAwEXZUk4AH44YwAuJmAANy4PKKD3Qw8+AF8+QWh4JBRXFUJDSyV7JHVSCytbJMIZOUUk9QAyckpqGj4BcGy4a2YMAGMcCAw4ZjJ2gBVRJVUACjBHKEdWRNLEQuK0VQBKLR04AZGyCAAbYAA6U4gaOYByAHFZCBg7nd40-izhPsHh0YA7rgABZoKCyKBKbwgXz+FyaZjMbAEKIUKi0NLzPbaPRjCa0aYoWb3RHIt4fIA)

### Expected behavior

The expected behavior is that `uuid` is recognized as a key with the correct type. 

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

"@ngrx/signals": "17.1.0"

### Other information

If you change the type of `EntityIdProps` to 

```typescript
export type EntityIdProps<Entity> = {
    [K in keyof Entity as K extends EntityId ? K : never]: Entity[K];
};
```
[Working playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcCiA7GBLJBJAEzgF44BnGKbDAczgB84MBXAWwCNgoBuAKF9CRYCZKkw58BAApQIYMgB5xuRAD4ScAN684uuAG0A0nGpwA1sEQQAZuiwq4AQzJxjoGMAwEXyyXAD8rnAAXEzAAG5cALqhvohGUXwAvnyC0PBIKHYSiISGlkr2SOqkFla2cYQycopx6gBk5JTUNHwC4Olw1swYAMY4EBhwzGQtACqiSqoAFGCOUI6ssUW5BPmIUwCUWjpwvYNkEAA2wAB0RxA00wDkAOKyEDDXm7xJ-GnC3X0DQwDuuAALNBQWRQJRwdyebxaZjMbAEUIUKi0JIzbbaPTDUa0CYoKY3WHw56vIA)

Then you will have the correct typing.

Seems like the type is not correctly resolved when using the indexed property accessor via generics which extends a known type.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by markostanimirovic** [comment]
@Raul52 

```ts
export type EntityIdProps<Entity> = {
    [K in keyof Entity as K extends EntityId ? K : never]: Entity[K];
};
```

👆  By applying the changes that you proposed, the `EntityIdProps` type will always return all props because `K extends EntityId` will always be true (except when some key is a symbol).

---

The idea with:

```ts
export type EntityIdProps<Entity> = {
    [K in keyof Entity as Entity[K] extends EntityId ? K : never]: Entity[K];
};
```

is to exclude all properties whose **values** are not `string | number` (not keys), because they cannot be used as identifiers.

---

But anyway, thanks for reporting this! Let's try to find some workaround.

**Comment by Raul52** [comment]
@markostanimirovic I created a complete test case and you are right, my proposed solution was wrong.

[test-case](https://www.typescriptlang.org/play?ssl=22&ssc=2&pln=1&pc=1#code/KYDwDg9gTgLgBDAnmYcCiA7GBLJBJAEzgF44BnGKbDAczgB84MBXAWwCNgoBuAKF9CRYCZKkw58BAApQIYMgB5xuRAD4ScAN684uuAG0A0nGpwA1sEQQAZuiwq4AQzJxjoGMAwEXyyXAD8rnAAXEzAAG5cALqhvohGUXwAvnyC0PBIKHYSiISGlkr2SOqkFla2cYQycopx6gBk5JTUNHwC4Olw1swYAMY4EBhwzGQtACqiSqoAFGCOUI6ssUW5BPmIUwCUWjpwvYNkEAA2wAB0RxA0s-OLm7xJ-GnCmagAQs7AE1mk2rpzC6wAMrNWihChUWh8P43VgAOTYnCgoRYHC4ULg-0Wrwgx2AjgwoXYOJO+OSjw6wm6fQGQwA7rgABZoKCyKBKODuTzeODvMifUQzba-PQjcaTNAzADkmKBIJoks26N0otoX2AU2m0ph8NRUAVSuGo1V4qlMuxuPx+vuQA)

Will also actively check for a solution given the intention.

**Comment by markostanimirovic** [comment]
I opened an issue in the TS repo: https://github.com/microsoft/TypeScript/issues/57318

As a workaround, you can use conditional type: [example](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcCiA7GBLJBJAEzgF44BnGKbDAczgB84MBXAWwCNgoBuAKF9CRYCZKkw58BAApQIYMgB5xuRAD4ScAN684uuAG0A0nGpwA1sEQQAZuiwq4AQzJ2JiIwF04oGMAwEXZUk4AH44YwAuJmAANy4PKKD3Qw8+AF8+QWh4JBRXFUJDSyV7JHVSCytbJMIZOUUk9QAyckpqGj4BcGy4a2YMAGMcCAw4ZjJ2gBVRJVUACjBHKEdWRNLEQuK0VQBKLR04AZGyCAAbYAA6U4gaOYByAHFZCBg7nd40-izhPsHh0YA7rgABZoKCyKBKbwgXz+FyaZjMbAEKIUKi0NLzPbaPRjCa0aYoKE+PwBLRjJEo1rouhpULoOBRDCxLjzO6I5FvD68IA)

**Comment by markostanimirovic** [comment]
https://github.com/microsoft/TypeScript/issues/48992
