### ISSUE TITLE
Component store Support for ACTIONS

### ISSUE THREAD

**Issue by vaidehi-cell** [ngrx/platform#4227]
### Which @ngrx/* package(s) are relevant/related to the feature request?

component-store

### Information

- My first question is why does component-store not support actions? (not custom actions, actions like in global-store)
- My second question is that I want to update a component variable (not in store) when certain service action occurs, how do I do that using component store without actions?
- If I use Actions in component store, can it cause any problem (memory leakage, data leakage etc.) ?
Any guidance will be highly appreciated! :)

### Describe any alternatives/workarounds you're currently using

Currently we are using Actions in Component Store.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by joaomarcosjova** [comment]
The `@ngrx/component-store` package provides a state management solution specifically designed for managing local component state within Angular applications. It's optimized for managing component-level state without the need for creating a full-fledged NgRx store.

To address your questions:

1. **Why doesn't `component-store` support actions like in the global store?**
   The primary purpose of `component-store` is to manage local component state, which typically doesn't require the same level of complexity as managing global state. Instead of actions, `component-store` uses methods to update state directly, which simplifies the state management process for local components.

2. **Updating a component variable when a certain service action occurs using `component-store` without actions:**
   You can achieve this by subscribing to the service in your component and updating the component variable accordingly. Here's a simplified example:

   ```typescript
   import { Component } from '@angular/core';
   import { DataService } from './data.service';

   @Component({
     selector: 'app-example',
     template: `
       <div>{{ data }}</div>
     `,
   })
   export class ExampleComponent {
     data: any;

     constructor(private dataService: DataService) {
       this.dataService.getData().subscribe((result) => {
         this.data = result;
       });
     }
   }
   ```

3. **Using actions in `component-store` and potential issues:**
   Using actions in `component-store` should not cause any inherent problems like memory leakage or data leakage. However, it's essential to use actions appropriately and manage subscriptions to avoid potential memory leaks. Make sure to unsubscribe from observables when the component is destroyed to prevent memory leaks.

Here's an example of how you can use `component-store` with actions:

```typescript
import { Injectable } from '@angular/core';
import { ComponentStore } from '@ngrx/component-store';
import { DataService } from './data.service';

@Injectable()
export class ExampleComponentStore extends ComponentStore<any> {
  constructor(private dataService: DataService) {
    super({});

    this.loadData();
  }

  readonly loadData = this.effect((trigger$) =>
    trigger$.pipe(
      switchMap(() => this.dataService.getData()),
      tap((data) => {
        this.patchState({ data });
      })
    )
  );
}
```

In this example, `loadData` is an effect that listens for trigger events (e.g., component initialization) and fetches data from the `DataService`. Once the data is retrieved, it updates the state using `patchState`.

Remember to handle error cases and cleanup subscriptions appropriately in your code to ensure optimal performance and stability.

**Comment by timdeschryver** [comment]
Hi, we're trying to keep GitHub issues for bug reports and feature requests.
I also noticed you created the discussion https://github.com/ngrx/platform/discussions/4220 for the same questions, that's why I'm closing this issue.

**Comment by joaomarcosjova** [comment]
> Hi, we're trying to keep GitHub issues for bug reports and feature requests. I also noticed you created the discussion #4220 for the same questions, that's why I'm closing this issue.

oh I see, have a good day

**Comment by vaidehi-cell** [comment]
> The `@ngrx/component-store` package provides a state management solution specifically designed for managing local component state within Angular applications. It's optimized for managing component-level state without the need for creating a full-fledged NgRx store.
> 
> To address your questions:
> 
> 1. **Why doesn't `component-store` support actions like in the global store?**
>    The primary purpose of `component-store` is to manage local component state, which typically doesn't require the same level of complexity as managing global state. Instead of actions, `component-store` uses methods to update state directly, which simplifies the state management process for local components.
> 2. **Updating a component variable when a certain service action occurs using `component-store` without actions:**
>    You can achieve this by subscribing to the service in your component and updating the component variable accordingly. Here's a simplified example:
>    ```ts
>    import { Component } from '@angular/core';
>    import { DataService } from './data.service';
>    
>    @Component({
>      selector: 'app-example',
>      template: `
>        <div>{{ data }}</div>
>      `,
>    })
>    export class ExampleComponent {
>      data: any;
>    
>      constructor(private dataService: DataService) {
>        this.dataService.getData().subscribe((result) => {
>          this.data = result;
>        });
>      }
>    }
>    ```
> 3. **Using actions in `component-store` and potential issues:**
>    Using actions in `component-store` should not cause any inherent problems like memory leakage or data leakage. However, it's essential to use actions appropriately and manage subscriptions to avoid potential memory leaks. Make sure to unsubscribe from observables when the component is destroyed to prevent memory leaks.
> 
> Here's an example of how you can use `component-store` with actions:
> 
> ```ts
> import { Injectable } from '@angular/core';
> import { ComponentStore } from '@ngrx/component-store';
> import { DataService } from './data.service';
> 
> @Injectable()
> export class ExampleComponentStore extends ComponentStore<any> {
>   constructor(private dataService: DataService) {
>     super({});
> 
>     this.loadData();
>   }
> 
>   readonly loadData = this.effect((trigger$) =>
>     trigger$.pipe(
>       switchMap(() => this.dataService.getData()),
>       tap((data) => {
>         this.patchState({ data });
>       })
>     )
>   );
> }
> ```
> 
> In this example, `loadData` is an effect that listens for trigger events (e.g., component initialization) and fetches data from the `DataService`. Once the data is retrieved, it updates the state using `patchState`.
> 
> Remember to handle error cases and cleanup subscriptions appropriately in your code to ensure optimal performance and stability.

@joaomarcosjova Thanks for the reply. I had a doubt, Could you explain how are actions used in the example you showed as a response to third question?

**Comment by vaidehi-cell** [comment]
> Hi, we're trying to keep GitHub issues for bug reports and feature requests. I also noticed you created the discussion #4220 for the same questions, that's why I'm closing this issue.

Got it.

**Comment by joaomarcosjova** [comment]
> > The `@ngrx/component-store` package provides a state management solution specifically designed for managing local component state within Angular applications. It's optimized for managing component-level state without the need for creating a full-fledged NgRx store.
> > To address your questions:
> > 
> > 1. **Why doesn't `component-store` support actions like in the global store?**
> >    The primary purpose of `component-store` is to manage local component state, which typically doesn't require the same level of complexity as managing global state. Instead of actions, `component-store` uses methods to update state directly, which simplifies the state management process for local components.
> > 2. **Updating a component variable when a certain service action occurs using `component-store` without actions:**
> >    You can achieve this by subscribing to the service in your component and updating the component variable accordingly. Here's a simplified example:
> >    ```ts
> >    import { Component } from '@angular/core';
> >    import { DataService } from './data.service';
> >    
> >    @Component({
> >      selector: 'app-example',
> >      template: `
> >        <div>{{ data }}</div>
> >      `,
> >    })
> >    export class ExampleComponent {
> >      data: any;
> >    
> >      constructor(private dataService: DataService) {
> >        this.dataService.getData().subscribe((result) => {
> >          this.data = result;
> >        });
> >      }
> >    }
> >    ```
> > 3. **Using actions in `component-store` and potential issues:**
> >    Using actions in `component-store` should not cause any inherent problems like memory leakage or data leakage. However, it's essential to use actions appropriately and manage subscriptions to avoid potential memory leaks. Make sure to unsubscribe from observables when the component is destroyed to prevent memory leaks.
> > 
> > Here's an example of how you can use `component-store` with actions:
> > ```ts
> > import { Injectable } from '@angular/core';
> > import { ComponentStore } from '@ngrx/component-store';
> > import { DataService } from './data.service';
> > 
> > @Injectable()
> > export class ExampleComponentStore extends ComponentStore<any> {
> >   constructor(private dataService: DataService) {
> >     super({});
> > 
> >     this.loadData();
> >   }
> > 
> >   readonly loadData = this.effect((trigger$) =>
> >     trigger$.pipe(
> >       switchMap(() => this.dataService.getData()),
> >       tap((data) => {
> >         this.patchState({ data });
> >       })
> >     )
> >   );
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In this example, `loadData` is an effect that listens for trigger events (e.g., component initialization) and fetches data from the `DataService`. Once the data is retrieved, it updates the state using `patchState`.
> > Remember to handle error cases and cleanup subscriptions appropriately in your code to ensure optimal performance and stability.
> 
> @joaomarcosjova Thanks for the reply. I had a doubt, Could you explain how are actions used in the example you showed as a response to third question?

Certainly! In the example provided, actions are used within the context of the `@ngrx/component-store` package to handle asynchronous data fetching and state management. Here's a breakdown of how actions are used in the example:

1. **Defining an Effect**: In the `ExampleComponentStore` class, there's a method called `loadData`, which represents an effect. An effect is a function that listens for trigger events and performs side effects, such as making HTTP requests or interacting with services.

```typescript
readonly loadData = this.effect((trigger$) =>
  trigger$.pipe(
    switchMap(() => this.dataService.getData()),
    tap((data) => {
      this.patchState({ data });
    })
  )
);
```

2. **Triggering the Effect**: The `loadData` effect is triggered by events emitted from the `trigger$` observable. In this case, the effect is triggered when the component is initialized or when a specific trigger condition is met.

3. **Fetching Data**: Within the effect, there's a call to `this.dataService.getData()`, which is responsible for fetching data asynchronously. This could involve making an HTTP request to a backend API or retrieving data from some other source.

4. **Updating State with Actions**: Once the data is fetched successfully, the `tap` operator is used to perform a side effect. In this case, the `data` retrieved from the service is passed to the `patchState` method. This method is an action provided by `@ngrx/component-store` that updates the component's state.

```typescript
tap((data) => {
  this.patchState({ data });
})
```

5. **Using Patch State**: The `patchState` method accepts an object representing the partial state that needs to be updated. In this example, it updates the `data` property of the component's state with the newly fetched data.

By encapsulating the asynchronous data fetching logic within an effect and using actions like `patchState` to update the component's state, developers can ensure a clear and structured approach to managing state in Angular applications using `@ngrx/component-store`. This pattern promotes better separation of concerns and facilitates easier testing and maintenance of the codebase.
