### ISSUE TITLE
ngRx 17 causing breaking unit tests - multiple issues

### ISSUE THREAD

**Issue by CodeLiftSleep** [ngrx/platform#4237]
### Which @ngrx/* package(s) are the source of the bug?

effects, router-store, store-devtools, store

### Minimal reproduction of the bug/regression with instructions

So with ngRx 17, I am getting the following 2 errors while running unit tests that all pass using ngRx 16(even in Angular 17 using --force). All other packages upgrade fine and do not cause issues, I have basically gone through and proven the issue is 100% caused by when I upgrade to ngRx 17(even tho it technically may not be the cause of it, it only happens when I upgrade to ngRx 17) 
ngRx 17 causes multiple failed unit tests with: 

**"TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, ReadableStream, Array, AsyncIterable, or Iterable."**

and then another error that seems to be related to the unit test suite itself(karma) since it doesn't happen on any specific unit test but rather once they finish:

**"An error was thrown in afterAll  error properties: Object({ longStack: 'TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, ReadableStream, Array, AsyncIterable, or Iterable."**

Just gives a bunch of karma_webpack stack traces...

I am not the only one experiencing these issues either based on google searches I have found regarding this.

### Expected behavior

unit tests pass as they have every version up until ngRx 17.  These have not changed other than to address a few issues over the various upgrades that prevent them from even running, but always end up working fine once they do.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx 17
Angular 17
Node 21.9.0
Chrome/ChromeHeadless

### Other information

unsure which module is the cause of this...these are what I have installed
   "@ngrx/effects": "^17.1.0",
    "@ngrx/router-store": "^17.1.0",
    "@ngrx/store": "^17.1.0",
"@ngrx/store-devtools": "^17.1.0",

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by markostanimirovic** [comment]
Hi @CodeLiftSleep,

Can you provide a repo with reproduction?

**Comment by markostanimirovic** [comment]
Just a note that bug reports without reproduction via Stackblitz or GitHub repo will be closed. For more info, check our [contribution guidelines](https://github.com/ngrx/platform/blob/main/CONTRIBUTING.md#submitting-bug-reports).
