### ISSUE TITLE
docs: Reusing `extraSelectors` in the `createFeature`

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#4244]
Add an example to the docs at https://ngrx.io/guide/store/feature-creators about reusing extra selectors.

You can define `extraSelectors` factory in the following way:

```ts
export const counterFeature = createFeature({
  name: 'counter',
  reducer: createReducer({ count: 0 }),
  // 👇
  extraSelectors({ selectCount }) {
    const selectCountPlus1 = createSelector(
      selectCount,
      (count) => count + 1
    );
    const selectCountPlus2 = createSelector(
      // 👇
      selectCountPlus1,
      (count) => count + 1
    );

    return { selectCountPlus1, selectCountPlus2 };
  },
});
```

_Originally posted by @markostanimirovic in https://github.com/ngrx/platform/discussions/3774#discussioncomment-4934409_

**Comment by mathisvester** [comment]
Would like to give this one a try. I submitted a PR with an example which is based on the content of the documentation. 

Haven't figured it out yet how to format the file automatically because prettier seems to be disabled for this directory. Is there another way to do so?
