### ISSUE TITLE
@ngrx/component-store: Add migration schematic for `tapResponse` operator

### ISSUE THREAD

**Issue by markostanimirovic** [ngrx/platform#4261]
### Which @ngrx/* package(s) are relevant/related to the feature request?

component-store

### Information

Before:

```ts
import { tapResponse } from '@ngrx/component-store';
```

After:

```ts
import { tapResponse } from '@ngrx/operators';
```

The schematic should also add `@ngrx/operators` package to `package.json` => `dependencies` if it's not already installed.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by rainerhahnekamp** [comment]
As in #4262: I'd like to work on that one.
