### ISSUE TITLE
@ngrx/effects: Add migration schematic for `concatLatestFrom` operator

### ISSUE THREAD

**Issue by markostanimirovic** [ngrx/platform#4262]
### Which @ngrx/* package(s) are relevant/related to the feature request?

effects

### Information

Before:

```ts
import { concatLatestFrom } from '@ngrx/effects';
```

After:

```ts
import { concatLatestFrom } from '@ngrx/operators';
```

The schematic should also add `@ngrx/operators` package to `package.json` => `dependencies` if it's not already installed.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by rainerhahnekamp** [comment]
If no one's interested, I'd like to take that one. I have some experience in writing schematics (see https://github.com/rainerhahnekamp/sam4sc)

**Comment by rainerhahnekamp** [comment]
@markostanimirovic and @timdeschryver. Thanks as well. I'd create then a schematic for the component store as well. See #4261
