### ISSUE TITLE
Use of rxMethod in service or component without signalStore

### ISSUE THREAD

**Issue by sokolej79** [ngrx/platform#4264]
### Which @ngrx/* package(s) are the source of the bug?

signals

### Minimal reproduction of the bug/regression with instructions

If we use rxMethod in service or component without signal store and listen for input changes in rxMethod onInit or in constructor with service, will be any memmory leak or it will automaticlly unsubscribe rxMethod when component or service is destroyed?
Do we need takeUntilDestroyed in rxMethod?
Is it valid approach to use rxMethod without  signalStore?

### Expected behavior

```
Sample scenario:
  private readonly user = toSignal(this.authService.user$);
  private readonly record = computed(() => this.viewState()?.record);

  private readonly actionsParams = computed(() => ({
    user: this.user(),
    record: this.record(),
  }));

  private readonly getActions = rxMethod<{
    user: User | null | undefined;
    record: DevItem | null | undefined;
  }>(
    pipe(
      filter((s) => !!s.user?.id && !!s.record?.id),
      switchMap((p) =>
        this.actionsService.getFormActions(p).pipe(
          tap((actions) => this.actions.set(actions)),
          retry({ count: 1, delay: 600 }),
          catchError((err) => {
            console.error('Get actions error', err);
            this.actions.set([]);
            return EMPTY;
          }),
        ),
      ),
     // takeUntilDestroyed(this.destroyRef) // !!! do i need this?
    ),
  );

// listen actions
  ngOnInit(): void {
    this.getActions(this.actionsParams); // will listen signal actionsParams change and load action on every params change
  }
```

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

Angular 17.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by markostanimirovic** [comment]
`rxMethod` is a standalone API and can be used without SignalStore. There is no need to use `takeUntilDestroyed` with `rxMethod` because cleanup will automatically happen on service/store/component destroy.

Read docs for more info: https://ngrx.io/guide/signals/rxjs-integration

---

Issues are used for bugs/feature requests. If you have any further questions, feel free to start a GitHub discussion or join our [Discord server](https://discord.gg/ngrx).
