### ISSUE TITLE
ngrx required Typescript v2.4 is not compatible with Angular 4

### ISSUE THREAD

**Issue by krismeister** [ngrx/platform#427]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X ] Documentation issue or request
</code></pre>

## What is the current behavior?
The current ngrx documentation specifies Typescript 2.4 as a dependancy. I believe this is a mistake as Angular 4 is not recommended with Typescript 2.4: https://github.com/angular/angular/issues/19287 .

Using Angular 4.4.3 project to typescript 2.4 I receive the following warning:
```
@angular/compiler-cli@4.4.3 requires typescript@'>=2.1.0 <2.4.0' but 2.4.2 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.

Please run the following command to install a compatible version of TypeScript.

    npm install typescript@'>=2.1.0 <2.4.0'
```

## Expected behavior:
For ngrx to require to the same typescript version as supported by angular.

## Minimal reproduction of the problem with instructions:
I don't have a great repo for this. I'm attempting to integrate ngrx 4 into a largish project and the observers are not behaving as expected.

## Other information:
Does everyone ignore this message? or does a certain angular compiler not give the warning above? In which case the documentation should mention it.

**Comment by brandonroberts** [comment]
This isn't an issue with ngrx as it is compatible with TS 2.4 which we use to build this project and the example app that goes along with it. Please provide a reproduction.

**Comment by krismeister** [comment]
The issue I had earlier was developer error. ngrx appears to work with typescript v2.3.5 fine.
