### ISSUE TITLE
@ngrx/signals: ability to save entity class instance on updateEntity()

### ISSUE THREAD

**Issue by xSirrioNx** [ngrx/platform#4270]
### Which @ngrx/* package(s) are relevant/related to the feature request?

signals

### Information

For example, we have store with entities that are instances of class `SomeClass`
```typescript
class SomeClass {
  id: number = 0;
  name: string = '';
  
  constructor(id: number, name: string = '') {
    this.id = id;
    this.name = name;
  }
}
const someStore = signalStore( withEntities({ entity: type<SomeClass>() }) )

patchState(someStore, addEntities([new SomeClass(1), new SomeClass(2)])
```

Now i wants to update entity with `id: 2` to change it's name
```typescript
patchState(someStore, updateEntity({ id: 2, { changes: { name: 'someName' }}}))
```

At this point we have in collection mixed entities:
```typescript
const instance1 = someStore.entityMap()[1];
const instance2 = someStore.entityMap()[2];

console.log(instance1 instanceof SomeClass); // true
console.log(instance2 instanceof SomeClass); // false
```

This is beacuse of updateEntity use simple destruction of object by spread operator (`newState = {...oldState, ...partialNewState}`) and we have simple object instead of class instance

I suggest to add additional not required option to updateEntity / updateEntities config, something like this

```typescript
updateEntity(
  {id, changes},
  {
    collection?: '',
    entityClass?: SomeClass // link to some class
  }
)
```

### Describe any alternatives/workarounds you're currently using

As alternative we can manually desstruct class and create new, then use `setEntity` instead of `updateEntity`, but it looks like   excess boilerplate

```typescript
const changedClassInstance = new SomeClass({...oldClassInstance, ...partialChanges});
patchState(someStore, setEntity(changedClassInstance));
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by brandonroberts** [comment]
Entities are meant to operate on Plain JavaScript Objects by design, so if you should map them to classes when consuming them if this is desired.
