### ISSUE TITLE
Cannot generate feature inside module with schematics

### ISSUE THREAD

**Issue by LosD** [ngrx/platform#4281]
### Which @ngrx/* package(s) are the source of the bug?

schematics

### Minimal reproduction of the bug/regression with instructions

- Create new Angular project: `ng new ngrxtest`
- Add ngrx packages:
  - `ng add @ngrx/store@latest --skip-confirmation`
  - `ng add @ngrx/effects@latest --skip-confirmation`
  - `ng add @ngrx/entity@latest --skip-confirmation`
  - `ng add @ngrx/schematics@latest --skip-confirmation`
- Create User module: `ng generate module User --flat false`
- (try to) Add feature: `ng generate feature user/User -m user.module.ts --group`

Result:
`Specified module path /src/app/user.module.ts does not exist`

### Expected behavior

Feature created inside module.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

Ngrx: 17.1.1
Angular: 17.2.1
Node: 18.19.1
Browser: Seems N/A, but I'm using Chrome 122

### Other information

Module and feature added exactly as in https://ngrx.io/guide/schematics/feature

I tried adding user/ in front of the module (`ng generate feature user/User -m user/user.module.ts --group`, but that made it add too many paths:
`Specified module path /src/app/user/user/user.module.ts does not exist`

Then I tried removing user from the feature path: `ng generate feature User -m user/user.module.ts --group`
That makes the command succeed.... But it generates the action, reducer and effect folder in the root app instead of the module. I guess that's not the intention?

Not sure if relevant, but I'm reproducing this on a Windows machine with Git bash. I originally saw this issue, or at least something very similar, on my Linux desktop at work in a proper bash shell. Unfortunately I'm not back there until April 2nd.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by olivierschmid** [comment]
Same here with version 16.3.0.
As workaround you can generate the feature without passing the module path/name. You will then promted to enter the module path/name - this still works

**Comment by timdeschryver** [comment]
Thanks for raising this issue and adding the reproductions.
This appears to be a problem with the effects schematics.


As a workaround you can provide the `path`:

```
npx ng generate feature User --module user.module.ts --group --path src/app/user
```
