### ISSUE TITLE
Signal Store with Angular SSR initiate store in every injected component

### ISSUE THREAD

**Issue by alexcibotari** [ngrx/platform#4284]
### Which @ngrx/* package(s) are the source of the bug?

signals

### Minimal reproduction of the bug/regression with instructions

1. Create an Angular SSR Project 
2. Create a Signal Store with 
````ts 
const TextStore = signalStore(
  { providedIn: 'root' },
  withState({text: 'init'}),
  withMethods( state => ({
     changeText: (text: string) => {
        patchState(state, { text});
      },
}))
}
````
5. add console.log in onInit and onDestory Store Hook
6. Create two different components: Header and Footer
7. Inject the Signal Sotre in both components
8. Render the components
9. The Sotre is initialized twice, and I have two different instances of Store, check the logs

Logs
````log
AppComponent: browser
app.component.ts:22 AppComponent: angular-ssr
core.mjs:29749 Angular is running in development mode.
cart.store.ts:107 onInit {items: Array(0)}
cart.component.ts:24 CartComponent effect []
cart.store.ts:107 onInit {items: Array(0)}
shopping-cart.component.ts:50 ShoppingCartComponent effect []
````

### Expected behavior

I expect to have only one signal Store to keep the application State

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

"@ngrx/signals": "^17.1.1",
  "@ngrx/operators": "^17.1.1",
Angular 17.3.x
Windows 11
Chrome

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by markostanimirovic** [comment]
Hi @alexcibotari,

Can you check if you accidentally added `CartStore` to the `providers` array of `CartComponent` and/or `ShoppingCartComponent`?

The best would be if you could provide a GitHub repo / StackBlitz playground with a reproduction.

**Comment by thomas-sol** [comment]
Hi @alexcibotari,
how did you solve your issue?
I am running into the same behavior.

**Comment by rainerhahnekamp** [comment]
@thomas-sol, as Marko said, check if your SignalStore doesn't also show up in a `providers` of `@Component`.

If no, please provide a reproducible example and reopen this issue.
