### ISSUE TITLE
SignalStore Methods code snipped has probably a flaw

### ISSUE THREAD

**Issue by ValentinBossi** [ngrx/platform#4287]
### Information

I looks like the code snipped
```
      pipe(
        debounceTime(300),
        //distinctUntilChanged(), <-- for demo excluded
        tap(() => patchState(store, { isLoading: true })),
        switchMap((query) => {
          return booksService.getByQuery(query).pipe(
            tapResponse({
              next: (books) => patchState(store, { books }),
              error: console.error,
              finalize: () => patchState(store, { isLoading: false }),
            })
          );
        }),
```
from the docs https://github.com/ngrx/platform/blob/092076c20caa698000e1a952f3b3bd4abf69a161/projects/ngrx.io/content/guide/signals/signal-store/index.md#L308 does not behave as intended.

The behaviour is different (as expected) when `patchState` is moved away from `tap` down to `switchMap` before the bookService is called.
At least thats my plain manual testing observation. Klicking rappidly then again slowly and again rapidly but still the `debounceTime` in mind. It does not switch back to `true` as expected (it looks like some klicks are just swallowed. only waiting for a couple of seconds helps, until everything works again). See my https://stackblitz.com/edit/stackblitz-starters-d6fl83?file=src%2FcounterStore.ts
compared to https://stackblitz.com/edit/afkdej?devtoolsheight=50&file=index.ts which behaves as expected.

### Documentation page

https://github.com/ngrx/platform/blob/092076c20caa698000e1a952f3b3bd4abf69a161/projects/ngrx.io/content/guide/signals/signal-store/index.md

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by timdeschryver** [comment]
Hi, I don't know if I understand the question.

> It does not switch back to true as expected (it looks like some klicks are just swallowed. only waiting for a couple of seconds helps, until everything works again)

This is the behavior of `debounceTime`: "The timeout duration in milliseconds (or the time unit determined internally by the optional scheduler) for the window of time required to wait for emission silence before emitting the most recent source value."

Moving the logic in the tap to switchMap should not affect this behavior.

**Comment by ValentinBossi** [comment]
Hi @timdeschryver thanks for checking this issue!
i have made a gif which shows it better than my words:
![watch_signal](https://github.com/ngrx/platform/assets/19373754/4a080237-eb4d-477f-83bb-bcd73bf63435)

in case A (using patchState in tap) im able to hold isLoading=false. that should not be possible if im correct (at least i was not able to do it in case B). in case B (using patchState in switchMap) what is possible, if im correct, is to hold isLoading=true if im always in the time constraint of which is given by debounceTime(300)&delay(2000).

maybe im doing it not really the same way in both cases and everthing is ok or i misunderstand something.
anyway thanks for checking!

**Comment by markostanimirovic** [comment]
Hi @ValentinBossi,

Feel free to create a PR to fix the example. There are two options:

1) Fix that you mentioned.
2) Or:

```ts
      pipe(
        debounceTime(300),
        distinctUntilChanged(),
        tap(() => patchState(store, { isLoading: true })),
        switchMap((query) => {
          return booksService.getByQuery(query).pipe(
            tapResponse({
              next: (books) => patchState(store, { books, isLoading: false }),
              error: (err) => {
                patchState(store, { isLoading: false });
                console.error(err);
              },
            })
          );
        }),
      )
```

**Comment by ValentinBossi** [comment]
hi @markostanimirovic
thanks for your input!
i try to understand why finalize should not be used in this case.
the only thing i see is that both next (response of service) and finalize (of operator completes) set the isLoading to false, which could make problems.

**Comment by ValentinBossi** [comment]
just for the record:
`finalize` (and`complete`) should not be used in this case, cause `switchMap` calls `unsubscribe` on the "service" which triggers `finalize` (and `complete`) in `tapResponse`. this sets `loading ` to `false` which is not the desired behaviour.
