### ISSUE TITLE
Losing state on browser reload

### ISSUE THREAD

**Issue by vediga** [ngrx/platform#433]
It appears that the whole state is lost after I reload the browser. Is there any way to persist state across browser reloads?

**Comment by roopkt** [comment]
@vediga  use browser's local storage or index db to persist data locally.

**Comment by vediga** [comment]
@roopkt How do we do that, I could not find any documentation?

**Comment by roopkt** [comment]
I believe in example app they have already used index db to persist data across browsers. Please go through the  https://github.com/ngrx/platform/blob/master/example-app/README.md
and check their sample app. 
" @ngrx/db - RxJS powered IndexedDB for Angular apps "

**Comment by vediga** [comment]
I just checked the live example app looks like it doesn't persist state across browser reloads
https://ngrx.github.io/platform/example-app/#/login

**Comment by roopkt** [comment]
I am not sure in their read me (  https://github.com/ngrx/platform/blob/master/example-app/README.md) they say " This application utilizes @ngrx/db to persist the collection across sessions; "

**Comment by brandonroberts** [comment]
The mentioned solutions above should work. Use browser storage

**Comment by aravindfz** [comment]
@rupeshtiwari your link throws 404

**Comment by pratikthakare777** [comment]
Apart from this is there any solution ?
Cause this one is potentially insecure for classified data..
