### ISSUE TITLE
PSA: Angular v18 and NgRx v18

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#4352]
### Which @ngrx/* package(s) are relevant/related to the feature request?

store

### Information

For those looking to upgrade to NgRx v18 along with Angular v18, just wanted to post some general notes as we go through this each release cycle.

We're still working on getting the release out.

- NgRx v17 still works with Angular v18.
- Until then, you may need to install using the legacy peer deps option with `npm` `npm i --legacy-peer-deps`.
- We won't be bumping the NgRx v17 `package.json` to go past Angular v17 package versions. Our stance has been to keep each major  release of NgRx aligned with each major release of Angular.

As this project is maintained by open source contributors in their free time, we try to work at a sustainable pace. You can support us by [sponsoring the project](https://github.com/sponsors/ngrx) or leveling up your team [through one of our workshops](https://ngrx.io/workshops).

We will have the release out as soon as its ready.

Thanks in advance,

The NgRx Team

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by jits** [comment]
Thank you @brandonroberts — this should save many "not compatible with Angular v18!!!" queries.

Is there a list of the remaining bits that need doing for NgRx v18, to make it over the line? (Perhaps folks can help contribute to this progress).

**Comment by serhiisol** [comment]
In the meanwhile you can use the following config in the package.json:
```json
  "overrides": {
    "@ngrx/signals": {
      ".": "^17.2.0",
      "@angular/core": "^18.0.0"
    },
    "@ngrx/store-devtools": {
      ".": "^17.2.0",
      "@angular/core": "^18.0.0"
    }
  }
```

**Comment by brandonroberts** [comment]
> In the meanwhile you can use the following config in the package.json:
> 
> ```json
>   "overrides": {
>     "@ngrx/signals": {
>       ".": "^17.2.0",
>       "@angular/core": "^18.0.0"
>     },
>     "@ngrx/store-devtools": {
>       ".": "^17.2.0",
>       "@angular/core": "^18.0.0"
>     }
>   }
> ```

What is this?! 

TIL 😅

**Comment by pumano** [comment]
would love to see support eslint flat config / eslint 9+ for @ngrx/eslint-plugin

**Comment by timdeschryver** [comment]
> would love to see support eslint flat config / eslint 9+ for @ngrx/eslint-plugin

We're currently looking at angular-eslint to support this (https://github.com/angular-eslint/angular-eslint/issues/1755). I'd like to keep our version/config in sync with it.

**Comment by friedhelm-youniverse** [comment]
EsLint seem to be ready. https://github.com/angular-eslint/angular-eslint/releases/tag/v18.0.0

**Comment by geforcemcdoodle** [comment]
How is the solution `ng add @ngrx/store@next` to be valued?

**Comment by pmathulan** [comment]
I just installed it with `ng add @ngrx/signals@18.0.0-beta.1`

**Comment by Yassinmoh** [comment]
I use Angular 18 and this command solve my problem :
`ng add @ngrx/store@^18.0.0-beta.1 --no-minimal --force`

**Comment by remymoro** [comment]
merci

**Comment by brandonroberts** [comment]
NgRx 18.0.0 has been published to npm on `latest`

https://dev.to/ngrx/announcing-ngrx-18-ngrx-signals-is-almost-stable-eslint-v9-support-new-logo-and-redesign-workshops-and-more-17n2

**Comment by ilFortu** [comment]
> NgRx 18.0.0 has been published to npm on `latest`
> 
> https://dev.to/ngrx/announcing-ngrx-18-ngrx-signals-is-almost-stable-eslint-v9-support-new-logo-and-redesign-workshops-and-more-17n2

Hi @brandonroberts,
On npm, I see as last version 18.0.0-rc.1
https://www.npmjs.com/package/@ngrx/signals?activeTab=versions

**Comment by timdeschryver** [comment]
@ilFortu see https://github.com/ngrx/platform/issues/4394

**Comment by bttb** [comment]
Since @ngrx/signals is still on 17.x.x, the command 

`ng add @ngrx/signals@latest`

(taken from [NgRx - installation](https://ngrx.io/guide/signals/install) fails, even with the recommended overrides in package.json.

**Comment by brandonroberts** [comment]
> Since @ngrx/signals is still on 17.x.x, the command
> 
> `ng add @ngrx/signals@latest`
> 
> (taken from [NgRx - installation](https://ngrx.io/guide/signals/install)) fails, even with the recommended overrides in package.json.

As mentioned in the blog post, `@ngrx/signals` hasn't gotten its final 18.0.0 release yet, so `ng add @ngrx/signals@next` is still the recommended approach until then.

**Comment by reduckted** [comment]
@brandonroberts The confusion comes from the blog post saying that `latest` should be used: 

> To get started with @ngrx/signals, install the package via one of the commands below and follow the @ngrx/signals Guide.
> 
> ```
> npm install @ngrx/signals
> ```
>
> You can also use the ng add command:
>
> ```
> ng add @ngrx/signals@latest
> ```

**Comment by brandonroberts** [comment]
> @brandonroberts The confusion comes from the blog post saying that `latest` should be used:
> 
> > To get started with @ngrx/signals, install the package via one of the commands below and follow the @ngrx/signals Guide.
> > ```
> > npm install @ngrx/signals
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can also use the ng add command:
> > ```
> > ng add @ngrx/signals@latest
> > ```



> @brandonroberts The confusion comes from the blog post saying that `latest` should be used:
> 
> > To get started with @ngrx/signals, install the package via one of the commands below and follow the @ngrx/signals Guide.
> > ```
> > npm install @ngrx/signals
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can also use the ng add command:
> > ```
> > ng add @ngrx/signals@latest
> > ```

@reduckted I see. Later on the in the blog post if you're updating, its stated there. @timdeschryver will you update the `ng add` command?

**Comment by timdeschryver** [comment]
@brandonroberts it's updated.

**Comment by msmallest** [comment]
I was a bit confused seeing the blog post referenced, so for people reading this issue, I think this is it: https://dev.to/ngrx/announcing-ngrx-18-ngrx-signals-is-almost-stable-eslint-v9-support-new-logo-and-redesign-workshops-and-more-17n2

Relevant takeaway from this issue that is reflected in the article

```shell
# We're waiting to release @ngrx/signals@18.0.0 
# Currently, you can use release candidate with Angular 18 apps
ng add @ngrx/signals@next
```

Installing it now and very excited to try it out, thank you to the team for providing this workaround for the moment.
