### ISSUE TITLE
Remove effects/concatLatestFrom docs 

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#4356]
### Information

The content of https://ngrx.io/guide/effects/operators#concatlatestfrom can be removed.
The new location can be found at https://ngrx.io/api/operators/concatLatestFrom. 

Ideally we also add a note on the new page that refers to the pre-18 documentation at https://v17.ngrx.io/guide/effects/operators#concatlatestfrom.

### Documentation page

https://ngrx.io/guide/effects/operators

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by va-stefanek** [comment]
The given link - https://v17.ngrx.io/guide/effects/operators#concatlatestfrom is not working.

**Comment by timdeschryver** [comment]
> The given link - https://v17.ngrx.io/guide/effects/operators#concatlatestfrom is not working.

We have to setup the v17 docs first in order for it to work.

**Comment by brandonroberts** [comment]
The link now works correctly https://v17.ngrx.io/guide/effects/operators#concatlatestfrom

**Comment by timdeschryver** [comment]
Thanks @brandonroberts !
