### ISSUE TITLE
ngrx.io dns is down

### ISSUE THREAD

**Issue by almamlaka** [ngrx/platform#4362]
### Information

![image](https://github.com/ngrx/platform/assets/59602921/0baacbff-bd03-4d68-9ff7-98322506fecb)
<img width="1312" alt="image" src="https://github.com/ngrx/platform/assets/59602921/4c81c956-1e89-4b86-a8ab-efb5071934cc">

### Documentation page

https://ngrx.io

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by almamlaka** [comment]
https://intodns.com/ngrx.io

**Comment by timdeschryver** [comment]
If you need access to the docs see https://ngrx-io.netlify.app/ until we resolve this issue.

**Comment by brandonroberts** [comment]
Thanks @almamlaka. The docs are back up now
