### ISSUE TITLE
QUESTION: Passing entire store in feature component

### ISSUE THREAD

**Issue by petrovic-ivan** [ngrx/platform#437]
What is best practice to pass state which needs to be shared through all app to into feature components?

My app is not super large but it will manipulate with a lot of data. Let say that I have app state in following structure:

```
export interface AppStore {
    featureA: any;
    featureB: any;
    featureC: any;
    shared: any;
}
```

No let say that I want to pass `shared` state and `featureA` state in `componentA`. Is it OK to pass like this:

`constructor(private store: Store<fromReducers.AppStore>)`

Now I am passing entire app state. Is it OK to always pass entire app state where I need different states or I need to organize `AppState` differently?

**Comment by brandonroberts** [comment]
This is where selectors come into play. You're injecting the Store which has the entire state available to you anywhere, but you use selectors to only select the slice of state you need to use or pass down. You'd then pass those Observables to your components through inputs or subscribe as needed.

```ts
featureA$ = this.store.select(state => state.featureA);
shared$ = this.store.select(state => state.shared);

constructor(private store: Store<fromReducers.AppStore>) {}
```

**Comment by petrovic-ivan** [comment]
Thanks. I can achieve with selectors what I want and it works perfectly. My concern is related how to properly organize store. I was thinking about two solutions: 

- One solution is to create two stores: features store and shared store. Then register in application level both stores and inject in a place where I need. Example if I want to use shared data in feature I will do like this: ` constructor(private feature: Store<fromFeatureReducers.FeatureState>, private shared: Store<fromSharedReducers.SharedState>)`

- Another creating one app store and use in entire application. Here is example: ` constructor(private feature: Store<fromFeatureReducers.AppState>)`. This solution has shared data as the slice of state.

Is this preference only, or I can have any benefits of splitting store in multiple modules and using the specific module in place where I need?
