### ISSUE TITLE
Support Angular4+

### ISSUE THREAD

**Issue by sumigoma** [ngrx/platform#439]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

Installing with any of the latest Angular5 betas results in the following warning.
```
npm WARN @ngrx/router-store@4.0.4 requires a peer of @angular/common@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngrx/router-store@4.0.4 requires a peer of @angular/core@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngrx/router-store@4.0.4 requires a peer of @angular/router@^4.0.0 but none is installed. You must install peer dependencies yourself.
```
This is due to the peerDependencies listing
```
    "@angular/common": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/router": "^4.0.0",
```
Could we have something along the lines of `"@angular/common": ">=4.0.0-beta <5.0.0",` assuming there are no issues with the latest ng5 beta?

N.B. I understand this is a warning and not prohibitive.

## Expected behavior:

No warnings.

**Comment by Fiontan** [comment]
This would be useful, although probably not the priority which means I have used the latest ngrx store with the latest angular, latest material etc- just requires some manual messing about with node_modules directories and addition of required typescript and rxjs libs. Not pretty but it eventually works.

**Comment by Fiontan** [comment]
IS there an opportunity here to align things to anular 5 release schedule? It might cover a few other issues e.g. universal support/state transfer etc....?
