### ISSUE TITLE
`@ngrx/signals/entity`: Replace `idKey` with `selectId`

### ISSUE THREAD

**Issue by markostanimirovic** [ngrx/platform#4392]
### Which @ngrx/* package(s) are relevant/related to the feature request?

signals

### Information

To allow defining entity identifier from multiple properties, but also for consistency with `@ngrx/entity`, `idKey` will be replaced with `selectId`.

Before:

```ts
const TodosStore = signalStore(
  withEntities<Todo>(),
  withMethods((store) => ({
    addTodo(todo: Todo): void {
      patchState(store, addEntity(todo, { idKey: '_id' }));
    },
  })
);
```

After:

```ts
const selectId = (todo: Todo) => todo._id;

const TodosStore = signalStore(
  withEntities<Todo>(),
  withMethods((store) => ({
    addTodo(todo: Todo): void {
      patchState(store, addEntity(todo, { selectId }));
    },
  })
);
```

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by jeffschulzusc** [comment]
i think this should be in the breaking changes list for 17/18 :)

**Comment by markostanimirovic** [comment]
> i think this should be in the breaking changes list for 17/18 :)

This change happened when `@ngrx/signals` was in the developer preview - before v18.0.

**Comment by jeffschulzusc** [comment]
i was thinking about 
https://ngrx.io/guide/migration/v18
would it make sense to mention it here ?
either way, thanks, it was a needed change
:)

**Comment by jeffschulzusc** [comment]
oh, i see what u mean about it was in preview ... understood
