### ISSUE TITLE
`@ngrx/signals` v18.0.0 Release

### ISSUE THREAD

**Issue by danielsogl** [ngrx/platform#4394]
### Which @ngrx/* package(s) are the source of the bug?

signals

### Minimal reproduction of the bug/regression with instructions

Can't install v18 of the signals package because it is not released on npm.

### Expected behavior

v18 of the signals package should be available through npm.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

v18

### Other information

See npm version log https://www.npmjs.com/package/@ngrx/signals?activeTab=versions

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by markostanimirovic** [comment]
Hi @danielsogl,

I didn't fail. `@ngrx/signals@18.0.0` is still not released. Currently, you can use release candidate with Angular 18 apps - `18.0.0-rc.x` (`@ngrx/signals@next`)

I'll keep this issue open for better visibility.

By the way, in v18.0, the developer preview flag will be removed from the `@ngrx/signals` package.

**Comment by rainerhahnekamp** [comment]
@markostanimirovic could you please update the article on dev.to as well and mention that the right command is `ng update @ngrx/signals@next`?

I think many of us might be unsure about the `next` and stick to 17 (getting version conflicts with Angular 18).

**Comment by markostanimirovic** [comment]
> @markostanimirovic could you please update the article on dev.to as well and mention that the right command is `ng update @ngrx/signals@next`?
> 
> I think many of us might be unsure about the `next` and stick to 17 (getting version conflicts with Angular 18).

cc @timdeschryver

**Comment by timdeschryver** [comment]
It's updated 👍

**Comment by rainerhahnekamp** [comment]
@timdeschryver isn't `@latest` still 17.2?

**Comment by pmathulan** [comment]
Still, ngrx signal released version is 17.2.0

**Comment by pumano** [comment]
same here @ngrx/signals 17.2.0 - no 18.0.0 available

**Comment by rainerhahnekamp** [comment]
@pmathulan @pumano: you need to install `@ngrx/signals@next`

**Comment by rainerhahnekamp** [comment]
@timdeschryver:  I think one last update of the article is required:

<img width="793" alt="Screenshot 2024-06-20 at 19 40 11" src="https://github.com/ngrx/platform/assets/5721205/1217b1d8-b5f3-4194-baf7-d43621493452">

**Comment by salztorte** [comment]
Is there a planned release Date for signals 18?

Yes, i know there is a Release Candidate, but my lead does not want dependencies to rc.

**Comment by kwood-gmr** [comment]
I would also note that web site's documentation includes items that are only in the 18 release

**Comment by JDavid21051** [comment]
> @timdeschryver: I think one last update of the article is required:
> 
> <img alt="Screenshot 2024-06-20 at 19 40 11" width="793" src="https://private-user-images.githubusercontent.com/5721205/341511023-1217b1d8-b5f3-4194-baf7-d43621493452.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNjAwNzUsIm5iZiI6MTcyMTA1OTc3NSwicGF0aCI6Ii81NzIxMjA1LzM0MTUxMTAyMy0xMjE3YjFkOC1iNWYzLTQxOTQtYmFmNy1kNDM2MjE0OTM0NTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTVUMTYwOTM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTQ0ZjliZTkyMDQ5ZGE1MmYyNzg1MGZhYTM5ZjI5ZGVmZjhmOTNmMjk1Y2RlOTBmMTg1YWY2YTViMDc5OWJmNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JQUq-BdRzvW1xmdP7QqkgpAfPqVvmwlS5ppjd3bWM9c">

This worked for me
```
"@ngrx/signals": "^18.0.0-rc.2",
```

is there a date for stable version 18?. it would be very useful. 
Thank you very much

**Comment by markostanimirovic** [comment]
> Is there a planned release Date for signals 18?

`@ngrx/signals` v18.0.0 will most likely be ready by the end of July.

**Comment by markostanimirovic** [comment]
`@ngrx/signals@18.0.0` is released! 🚀

**Comment by aahunt-cisco** [comment]
Still am seeing the error as it expecting NX 18.0.1 and so `nx migrate latest` fails

<img width="1186" alt="image" src="https://github.com/user-attachments/assets/b80d602a-07a9-44f4-9864-1bf86e8ad3b6">
