### ISSUE TITLE
`@ngrx/effects` and `@ngrx/component-store` depends on old beta version of `@ngrx/operators`

### ISSUE THREAD

**Issue by emqi** [ngrx/platform#4413]
### Which @ngrx/* package(s) are the source of the bug?

component-store, effects

### Minimal reproduction of the bug/regression with instructions

There seems to be a mostly harmless but odd "issue" with `@ngrx/effects` and `@ngrx/component-store` packages where even the latest v18 releases depends on the old `17.0.0-beta.0` version of `@ngrx/operators`. That dependency is also specified via exact version so even though newer versions are available, that old one will be installed and used.

![image](https://github.com/ngrx/platform/assets/6454798/a8d454f4-a285-483c-8615-fc405c86cb8e)

https://github.com/ngrx/platform/blob/c9c646c7a1b5123d263a0b0df49d3049bafb3a56/modules/component-store/package.json#L47
https://github.com/ngrx/platform/blob/c9c646c7a1b5123d263a0b0df49d3049bafb3a56/modules/component-store/package.json#L47

### Expected behavior

`@ngrx/operators` not to be a `-beta` release and to match the base package version 😀

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

@ngrx/component-store: >=17.0.0
@ngrx/effects: >=17.0.0

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by brandonroberts** [comment]
Thanks @emqi. This has been resolved in the `18.0.1` release
