### ISSUE TITLE
No matching export in "node_modules/@ngrx/component-store/fesm2022/ngrx-component-store.mjs" for import "tapResponse"

### ISSUE THREAD

**Issue by dragonflypl** [ngrx/platform#4414]
### Which @ngrx/* package(s) are the source of the bug?

component-store

### Minimal reproduction of the bug/regression with instructions

After installing latest 18 version of component store into Angular 18 project after migration, I get this compilation error:

> No matching export in "node_modules/@ngrx/component-store/fesm2022/ngrx-component-store.mjs" for import "tapResponse"

when importing `tapResponse`

```
import { tapResponse } from '@ngrx/component-store';
```

### Expected behavior

Import should work 

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

Angular@18
Node@20

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by rainerhahnekamp** [comment]
@dragonflypl `tapResponse` has been moved to '@ngrx/operators' as of version 18. The migration script should have updated your import statement. You can do it manually by replacing it with

`import { tapResponse } from '@ngrx/component-store';`

It would be great if you could let us know the imports of that file. Maybe an unknown issue with the migration.

**Comment by markostanimirovic** [comment]
Thanks @rainerhahnekamp!

@dragonflypl to run the migration schematic you should use `ng update` instead of updating dependencies manually.
