### ISSUE TITLE
RFC: Tracking Signal Changes

### ISSUE THREAD

**Issue by rainerhahnekamp** [ngrx/platform#4416]
## Problem

Miscellaneous extensions such as DevTools, local storage sync, and undo/redo are constrained due to the glitch-free effect of Signals. This issue has already been raised in:
- [angular/angular#56155 (comment)](https://github.com/angular/angular/issues/56155#issuecomment-2198332809)
- [angular/angular#53703](https://github.com/angular/angular/issues/53703)

It appears that no official mid-term solution will be provided.

## Proposed Solution

The Signal Store's `patchState` function offers the potential for a workaround. 

`patchState` is the sole function capable of updating the state and is fully controlled by ngrx/signals. It could track its calls and provide necessary information to any SignalStore feature that requires it.

Ideally, this functionality should be incorporated into the core (see [angular/angular#53703](https://github.com/angular/angular/issues/53703)). Implementing `patchState` shouldn't be too complex and could be seen as low-hanging fruit.

If there is interest, I am willing to develop a prototype.

---

## Example

```typescript
type StateChangeCallback<State> = (prev: State, current: State, diff: Partial<State>) => void;

// Using it in a feature
const withDevTools = (name: string, stateChangeCallback: StateChangeCallback<Record<string, unknown>>) => {
  // ...
}

// Using it in SignalStore
signalStore(
  withMethods((store, stateChangeCallback) => {
    // ...
  }),
  withHooks((store, stateChangeCallback) => {
    // ...
  });
)
```

The `signalStore` factory, as described in issue [#4340](https://github.com/angular/angular/issues/4340), would work well in combination with `withDevTools` from the example.

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by markostanimirovic** [comment]
Maybe we should consider a different API design choice because:

- We cannot track `signalState` changes in the same way - inconsistency.
- This feature is needed for library authors and rarely for application devs. Therefore, I don't think it should be an integral part of the base SignalStore features.
- It's not tree-shakeable.
- Introducing SignalStore APIs as additional SignalStore feature arguments will lead to:

Bad DX:

```ts
withHooks((_, _, someSignalStoreAPI) => ({
  /* ... */
}))
```

Breaking changes:

```ts
withHooks((store, service = inject(Service) /* compilation error */) => ({
  /* ... */
}))
```

I'd apply the same design principle we already have for standalone state helpers (`patchState` and `getState`):

```ts
watchState(store, (state) => {
  console.log(state);
});
```

**Comment by rainerhahnekamp** [comment]
Sure, if `watchState` is the better design and aligns more to the existing style, I'm happy with it. What matters to me is is that this feature does exist. 👍

**Comment by jdegand** [comment]
I'd suggest you check out the [SignalStory](https://zuriscript.github.io/signalstory/docs/prolog) for inspiration.  The library has state snapshots, immutability, and other things you can pull from.

**Comment by brandonroberts** [comment]
Thanks @jdegand, looks interesting. Let's stay on topic here. Thanks

**Comment by brandonroberts** [comment]
I like the `watchState` concept also. On the surface, it feels like a lightweight `Effect` that can listen to all state updates and perform some task based on them.

I think it could open up lots of possibilities.

**Comment by jits** [comment]
Excellent idea to have this `watchState` function!

Is it worth now deprecating (then removing) the `getState` function? (Seems redundant and less useful, now).

**Comment by markostanimirovic** [comment]
I think we should keep the `getState` function. It's still useful:

- When we want to get the SignalStore's state snapshot.
- If we don't want to watch the state changes synchronously, but have glitch-free behavior, `getState` can be used together with `effect`.

**Comment by rainerhahnekamp** [comment]
Thanks @markostanimirovic. Time for me to update the devtools :)
