### ISSUE TITLE
Does not refer to the right sourceMap

### ISSUE THREAD

**Issue by varghesep** [ngrx/platform#442]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
The bundle files refer a ```dist``` folder which does not exist in the ```node_modules``` folder for example: ```//# sourceMappingURL=./dist/store-devtools/bundles/store-devtools.umd.min.js.map```

## Expected behavior:
The ```sourceMappingURL``` should refer the map file in the bundles folder.

## Minimal reproduction of the problem with instructions:
1. Run the command ```npm install @ngrx/core @ngrx/store@2.2.3 --save```
2. Check the ```node_modules\@ngrx``` folder.

**Comment by brandonroberts** [comment]
This repo is for issues related to 4.x
