### ISSUE TITLE
How to install entity module with npm

### ISSUE THREAD

**Issue by SergioArrighi** [ngrx/platform#444]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X ] Documentation issue or request
</code></pre>

## What is the current behavior?

When I execute npm install I get 404 not found

## Expected behavior:

I understood that the cause is that the module is not yet published officially.
But being new to node I cannot figure out how to install this module.
Thanks and best regards

**Comment by TheRedD0t** [comment]
> It's not published yet but will be soon. Use the nightly builds for now
> 
> `npm install github:ngrx/entity-builds`

( #425)

@brandonroberts, can be closed. And maybe it's useful to add a hint to the entity documentation as long as it's not official released, to prevent further install issues.

**Comment by SergioArrighi** [comment]
Thanks a lot, really kind and sorry for basic question :)
Keep up the awesome job!

**Comment by SergioArrighi** [comment]
Still I get this error though
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, stat 'C:\Users\********\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-676ab875\ngrx\entity.es5.js'
Probably something related to my environment and I'm running under windows.

**Comment by TheRedD0t** [comment]
I just tried and it works fine for me. Try to clear the cache and install again.

**Comment by SergioArrighi** [comment]
I run 
npm cache clean --force
and then
npm install github:ngrx/entity-builds
But I still get the error.
I notice that in my file system I have
...AppData\Roaming\npm-cache\_cacache\tmp\git-clone-211e37a9\@ngrx\entity.es5.js
While in the error message
C:\Users\sarrighi\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-211e37a9\ngrx\entity.es5.js

With no @ before ngrx folder.
Could this be the cause?

**Comment by TheRedD0t** [comment]
Try to install with `npm install https://github.com/ngrx/entity-builds.git` or give yarn a try.

**Comment by SergioArrighi** [comment]
Actually the error is
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sarrighi\AppData\Roaming\npm-cache\_logs\2017-10-03T14_24_16_647Z-debug.log

Seems to be a common error when there are corrupted packages in dependencies.
Had no luck. I will keep on trying :D

**Comment by SergioArrighi** [comment]
Hello,
sorry to reopen this one but I believe I found the issue.
In fact I forked the repo you gave me and simply renamed folder @ngrx to ngrx (without @) than executing npm install <my_github_user>/entity-builds I had the module installed correctly and no npm errors.
Not sure if you guys will want to do something about it but it is a conflict your project has with npm (latest version).
Regards

**Comment by brandonroberts** [comment]
It will be released when ready. If you need further support on installing the nightly builds, use the https://gitter.im/ngrx/platform support channel

**Comment by SergioArrighi** [comment]
Thanks for the super helpful hints and kind support :S
