### ISSUE TITLE
RFC: Allow defining private SignalStore members

### ISSUE THREAD

**Issue by markostanimirovic** [ngrx/platform#4443]
### Which @ngrx/* package(s) are relevant/related to the feature request?

signals

### Information

Provide the ability to define private SignalStore members by using the `_` prefix:

```ts
export const CounterStore = signalStore(
  withState({
    count1: 0,
    // 👇 private state slice
    _count2: 0,
  }),
  withComputed(({ count1, _count2 }) => ({
    // 👇 private computed signal
    _doubleCount1: computed(() => count1() * 2),
    doubleCount2: computed(() => _count2() * 2),
  })),
  withMethods((store) => ({
    increment1(): void {
      patchState(store, { count1: store.count1() + 1 });
    },
    // 👇 private method
    _increment2(): void {
      patchState(store, { _count2: store._count2() + 1 });
    },
  })),
);
```

All state slices, computed signals, and methods with the `_` prefix are not accessible from the outside:

```ts
const store = inject(CounterStore);

store.count1(); // ✅
store._count2(); // ❌

store._doubleCount1(); // ❌
store.doubleCount2(); // ✅

store.increment1(); // ✅
store._increment2(); // ❌
```

**Note:** Only root-level state slices can be defined as private.

Similar to private class fields in TypeScript, private SignalStore members will be excluded from the public store instance only at the type level:

```ts
(store as any)._increment2(); // works
```

## Updating private state slices when the state is unprotected

Even if the state is unprotected from external modifications, compilation error will be thrown if private state slices are updated from the outside:

```ts
const CounterStore = signalStore(
  { protectedState: false },
  withState({ count1: 0, _count2: 0 }),
);

const store = inject(CounterStore);
patchState(store, { _count2: 10 }); // ❌ compilation error
```

## Private members in custom SignalStore features

If a private member is defined in a custom SignalStore feature, it will be accessible in the store that uses it:

```ts
const withFoo = () => signalStoreFeature(withState({ _foo: 'bar' }));

const Store = signalStore(
  withFoo(),
  withComputed(({ _foo }) => ({
    bar: computed(() => _foo() + 'bar'),
  }))
);
```

To limit the visibility of custom store feature members, it's necessary to specify the return type explicitly:

```ts
export function withCount(): SignalStoreFeature<
  EmptyFeatureResult,
  { state: { count2: number }; computed: {}; methods: {} }
> {
  return signalStoreFeature(withState({ count1: 0, count2: 0 }));
}
```

The `count1` property won't be visible in the store that uses the `withCount` feature.

Another option is to use symbols as keys:

```ts
const FOO = Symbol('FOO');

export function withFoo() {
  return signalStoreFeature(
    withMethods({ [FOO]: () => {} })
  );
}
```

The `FOO` method will be visible in the store that uses the `withFoo` custom feature but it won't be accessible if the `FOO` symbol is not exported.

## Private entity collections

The `withEntities` feature will not allow specifying which entity properties are private or not. However, it will be possible to define all entity properties as private using a collection name with the `_` prefix. Then, public entity properties (state slices and computed signals) can be reexported with custom names:

```ts
const todoConfig = entityConfig({
  entity: type<Todo>(),
  // 👇 private collection
  collection: '_todo',
});

const TodosStore = signalStore(
  withEntities(todoConfig),
  withComputed(({ _todoEntities }) => ({
    // 👇 exposing entity array publicly
    todos: _todoEntities,
  }))
);

@Component({
  /* ... */
  template: `
    <h1>Todos</h1>
    <ngrx-todo-list [todos]="store.todos()" />
  `,
  providers: [TodosStore],
})
class TodosComponent {
  readonly store = inject(TodosStore);
}
```

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by jits** [comment]
As an alternative to the proposed naming-based approach, how about enabling a scenario where you can encapsulate private state/methods in a _separate_ module-level SignalStore and then instantiate and access this in the exported store?

I think this fits in to a more functional, as well as "composition over inheritance", approach. As well as being something _standard_, rather than adding new semantics.

Some pseudocode:

```ts
// store.ts

// Only accessible within this module file.
const InternalStore = signalStore(…);

// Some way way to instantiate / inject this internal store, either here, or within the `Store` definition.
const internal = giveMeAnInstanceOfTheInternalStore();

export const Store = signalStore(
  […]
  // Access state and methods from `internal`, within this SignalStore definition.
);
```

Note: we can already use an internal (and thus private) `SignalState` instance right now, so it would be great to be able to do this within a `SignalStore` instance.

**Comment by markostanimirovic** [comment]
Hi @jits,

The suggested idea can only work for root-level stores.

**Comment by jits** [comment]
Hey @markostanimirovic — yeah, fair enough (I figured that might be the case).

Amazing turnaround on implementing this private fields/methods approach 🎉 I can see this being very useful, especially for hiding the entity state internals (as you've suggested).
