### ISSUE TITLE
RFC: Limit direct state / computed / methods access outside a SignalStore

### ISSUE THREAD

**Issue by mauriziocescon** [ngrx/platform#4446]
### Which @ngrx/* package(s) are relevant/related to the feature request?

signals

### Information 

With the recent introduction of `protectedState` in https://github.com/ngrx/platform/issues/4405, the encapsulation of `signalStore` has massively improved (thanks a lot for that!). 

However, I think there might be some extra room for improvements with the potential addition of "access limitation" to state / computeds / methods from outside the store. Here is a typical example: 

``` typescript
/**
 * In this case, you probably don't want to have _params and _loadItems callable from consumers 
 * cause they are just internal implementation:
 * 
 * - _params internal way of saving several props affecting the list of items, 
 * - _loadItems called several times will produce a bug (several http requests). 
 */

interface State {
  _params: { textSearch: string };

  items: { id: string }[];
  loading: boolean;
  error: string | undefined;
}

export const ItemsStore = signalStore(
  { providedIn: 'root' },
  // ...
  withComputed(({ _params }) => ({
    // ...
    textSearch: computed(() => _params.textSearch()),
  })),
  withMethods((store, itemsService = inject(ItemsService)) => ({
    // ...
    _loadItems: rxMethod<{ textSearch: string }>( /** ... **/),
  })),
  withHooks({
    onInit(store): void {
      store._loadItems(store._params);
    },
  })
);
```
Full example: https://stackblitz.com/edit/stackblitz-starters-oll7h1

This is like having `private` methods / computeds / stateSlices in a regular class-based angular provider. The reason for having such feature is to better encapsulate the internal implementation from the rest and therefore avoid mistakes for consumers. 

One might say the provided example could be refactored in order to avoid the specific problems. But this is just one potential case (can think about others) and in big enterprise applications the lack of such encapsulation can potentially end up with bugs. 

### Describe any alternatives/workarounds you're currently using

As of today, there are 2 alternatives: 

- **facade**: using a facade on top of a signalStore can provide the missing encapsulation layer. But considering a signalStore is just a provider, it sounds a bit a strange (compared to the regular ngrx/store). 

- **regular ng-service + ngrx utils**: another possibility is simply to define a regular angular service and take advantage of the great ngrx utils (something like [SignalState in a Service](https://ngrx.io/guide/signals/signal-state#example-2-signalstate-in-a-service)). This works fine, but on the other hand it means opting out of signalStore. 

### Suggestions

In https://github.com/ngrx/platform/pull/4210#issuecomment-1966810494, it has been mentioned some sort of convention as a possible way to improve the situation. Assuming it is still valid, here is how I see it (https://github.com/ngrx/platform/pull/4309#issuecomment-2240306100): 

- introduce a configurable or standard prefix indicating something is private (like `_` above), 
- anything prefixed not available outside of the store (ts interface) with `protectedState: true` (flag affecting both patchability and availability),
- I'd consider deprecating `protectedState: false` if it makes everything easier (I personally don't see any use case for such feature), 
- consider `custom store features` as internal implementation (so anything prefixed still available), 
- not affecting entities. 

In general, I'm not particularly in favour of such approach... just providing feedback in case it's the easiest / better way to achieve the goal. 

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by jits** [comment]
This likely duplicates https://github.com/ngrx/platform/issues/4443

**Comment by mauriziocescon** [comment]
Ah indeed, Marko created a ticket out of the discussion. Closing it then!
