### ISSUE TITLE
store,select("state").subscribe() return undefined subscription

### ISSUE THREAD

**Issue by giridharprakash** [ngrx/platform#445]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

let adminState = this.store.select("admin").subscribe(a => {
       adminState.unsubscribe();
       if (a.fileTypes)
       {
        //login here
       }
   });
## Expected behavior:

adminState should have subscription object instead of undefined

## Version of affected browser(s),operating system(s), npm, node and ngrx:
"@ngrx/store": "^4.0.3",
"@ngrx/effects": "^4.0.5",
"rxjs": "5.4.3",
"@angular/common": "4.4.4",
"ionic-angular": "3.7.1"

**Comment by brandonroberts** [comment]
This is most likely a bug in the way your state is set up. Please use the chat room for support. https://gitter.im/ngrx/platform
