### ISSUE TITLE
Add Linkedin Link to Footer

### ISSUE THREAD

**Issue by markostanimirovic** [ngrx/platform#4452]
### Information

Add the link to the NgRx profile on LinkedIn (https://linkedin.com/company/ngrx) to the footer below the "Twitter" link.

![ngrx-footer](https://github.com/user-attachments/assets/bda0a338-f251-43c5-baab-a15ddacbe30b)

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by iamisam** [comment]
Hey @markostanimirovic I am recently getting started with open source contribution and would like to work on this issue. Could you assign it to me?

**Comment by markostanimirovic** [comment]
@iamisam Sure! Feel free to create a PR.
