### ISSUE TITLE
@ngrx/router-store triggers unexpected ROUTER_CANCEL action if store is modified by guard .

### ISSUE THREAD

**Issue by majo44** [ngrx/platform#446]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
If the store is asynchronously modified by route guard, during the transition StoreRouterConnectingModule is executing navigateByUrl on router, because the url set in state by StoreRouterConnectingModule  (taken from NavigationStart event) is different than router.url value (which contains url from before of transition). This cause cancellation of previous navigation, and next try to execute the navigation (for same url), and again and again, until the guard will not return true synchronously.   

Please look at code  https://github.com/ngrx/platform/blob/master/modules/router-store/src/router_store_module.ts#L209

## Expected behavior:
StoreRouterConnectingModule  should not trigger navigateByUrl if state is modified by guard.

## Minimal reproduction of the problem with instructions:
Please look at: http://plnkr.co/edit/SbecXWSzFMnSRA9JFQ0i

## Version of affected browser(s),operating system(s), npm, node and ngrx:
latest

**Comment by brandonroberts** [comment]
Can you make a small repro?

**Comment by majo44** [comment]
Sample added.
http://plnkr.co/edit/SbecXWSzFMnSRA9JFQ0i

**Comment by brandonroberts** [comment]
This issue has already been fixed in master and will be in the next release. https://github.com/ngrx/platform/pull/355

**Comment by soyuka** [comment]
When will it be released? Thanks.

**Comment by aasmm7x** [comment]
I keep getting this error even with new master.

**Comment by demirtasg** [comment]
this issue is still not resolved

**Comment by pfeileon** [comment]
I'm refactoring an app from excessive resolver-use to NgRx and get unexpected navigation cancelled events, as well, even though the resolvers themselves don't even inject the store. Since I'll make all resolvers non-blocking and use them as a hook to dispatch actions more or less declaratively via the route config, it won't be an issue for me, but there's definitely still something wrong.
