### ISSUE TITLE
@ngrx/effects: Update examples to standalone APIs

### ISSUE THREAD

**Issue by markostanimirovic** [ngrx/platform#4468]
### Information

Standalone APIs have been stable since Angular v16, and we should update the `@ngrx/effects` documentation to use standalone APIs by default, and reference previous versions of the docs for module-based apps.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by AdrianRomanski** [comment]
I can give It a try :)

**Comment by markostanimirovic** [comment]
Hi @AdrianRomanski,

Are you still interested in working on this issue? If not, let us know so someone else can take it.

**Comment by AdrianRomanski** [comment]
@markostanimirovic  hello, Yes sorry i somehow Lost your first mention.
I will start working on It at The weekend
