### ISSUE TITLE
IDE errors for takeWhile on store.select()

### ISSUE THREAD

**Issue by axtho** [ngrx/platform#447]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
Currently, this method `this._store.select(app.getShowDrawer).takeWhile(() => this._alive).subscribe(..)` produces an IDE error of` "TS2339:Property 'takeWhile' does not exist on type 'Store<any>'"`.

AFAIK the methods run properly still. Previously this wasn't an issue.

## Expected behavior:
No IDE errors.

## Minimal reproduction of the problem with instructions:
http://plnkr.co/edit/teHXMxv6DdWor8akrAxO?p=preview

## Version of affected browser(s),operating system(s), npm, node and ngrx:
├─ @ngrx/effects@4.0.5
├─ @ngrx/router-store@4.0.4
├─ @ngrx/store-devtools@4.0.0
├─ @ngrx/store@4.0.3

Node: 8.5.0
RxJS: 5.4.3
Angular 4.4.4
Typescript: 2.5.3

## Other information:
The plunker produces browser errors 

> TypeError: this.counter.takeWhile is not a function

**Comment by MikeSaprykin** [comment]
@axtho Consider importing takeWhile operator directly in this file from rxjs
like this
```import 'rxjs/add/operator/takeWhile';```

**Comment by axtho** [comment]
@MikeSaprykin thanks, that helped. But why is this necessary now? I thought we'd all get away from  importing the operators this way (no to pollute the user space)?

**Comment by MikeSaprykin** [comment]
@axtho np :-) 
I believe it's done for optimizing purpose, as you're not importing operators you don't need, only the ones you use directly, thus others are not included in your final bundle.
You can avoid this by importing whole rxjs lib in some of your files, but that will pull all the stuff, which you probably don't need for your app.

Another option - you can import all operators you use in a separate file and import in somewhere in main.ts or app.component.ts ( or any other root file ), and you'll have all those operators imported. That will help you not to pollute user space ;-)

**Comment by axtho** [comment]
@MikeSaprykin thanks. I'll keep those in mind ;)
