### ISSUE TITLE
@ngrx/store-devtools: Update examples to standalone APIs

### ISSUE THREAD

**Issue by markostanimirovic** [ngrx/platform#4470]
### Information

Standalone APIs have been stable since Angular v16, and we should update the `@ngrx/store-devtools` documentation to use standalone APIs by default, and reference previous versions of the docs for module-based apps.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by sheikalthaf** [comment]
I can take this

**Comment by markostanimirovic** [comment]
Hi @sheikalthaf,

Do you still plan to work on this issue?

**Comment by sheikalthaf** [comment]
@markostanimirovic yes, I'll raise a PR soon.
