### ISSUE TITLE
Support mocking `selectSignal` in unit tests

### ISSUE THREAD

**Issue by karsenkeith** [ngrx/platform#4473]
### Which @ngrx/* package(s) are relevant/related to the feature request?

signals, store

### Information

I was reading through the NgRx Store documentation trying to follow the Testing examples (https://ngrx.io/guide/store/testing) for mocking selectors, but it seems this doesn't work when using `selectSignal`. It would be amazing if the same mocking functionality was available for both `select` and `selectSignal` in unit tests.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by markostanimirovic** [comment]
I just tested and `overrideSelector` works as expected with `selectSignal`:

```ts
it('works', () => {
  const mockValue = 20;
  mockStore.overrideSelector(selector, mockValue);

  expect(mockStore.selectSignal(selector)()).toBe(mockValue); // ✅ 
});
```
