### ISSUE TITLE
New Signals rule @ngrx/prefer-protected-state

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#4474]
### Which @ngrx/* package(s) are relevant/related to the feature request?

signals

### Information

As a best practice we recommend and encourage devs to use protected state.
But currently there's nothing to enforce this.

That's why I propose a new ESLint rule `@ngrx/prefer-protected-state`, which will detect and warn devs for unprotected states. 

By default this will be turned on (as other rules), teams can always opt-out of this behavior by configuring their ESLint rules (at a global level), or for specific scenarios by using a comment.

```ts
// GOOD ✅
const Store = signalStore(
  { protectedState: true },
);
```

```ts
// BAD ❌
const Store = signalStore(
  { protectedState: false },
    ~~~~~~~~~~~~~~~~~~~~~ [error]
);
```

### Describe any alternatives/workarounds you're currently using

 Devs need to be aware of this and catch these through pull requests.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by rainerhahnekamp** [comment]
Since I come from the global store, I am all in for such a rule. 👍

**Comment by NgDaddy** [comment]
Hi guys, @timdeschryver are you going to implment this? I could take this one if you all @markostanimirovic @rainerhahnekamp  @timdeschryver are ok with that.

**Comment by timdeschryver** [comment]
You can go ahead with the implementation @NgDaddy

**Comment by NgDaddy** [comment]
Ok @timdeschryver, I am on it

**Comment by NgDaddy** [comment]
Hi, could you please do CR guys @markostanimirovic @rainerhahnekamp @timdeschryver ? I guess it is ready but not 100% sure this is what you have been expecting @timdeschryver 😃

**Comment by NgDaddy** [comment]
@timdeschryver could you look at that PR #4488 ? 🤔
