### ISSUE TITLE
Support for Angular 4.4.3+, deprecated MaterialModule and changes to md-input-container

### ISSUE THREAD

**Issue by danielhdz56** [ngrx/platform#448]
## I'm submitting a...

<pre><code>
[] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

MaterialModule has been deprecated, causing a compiling error.
Consider creating a "Material" module within their application (e.g., FooMaterialModule) that imports only the set of components actually used in the application.

## Expected behavior:

No compiling error caused in:
- core.module.ts
- auth.module.ts,
- app/books/components/index.ts
- app/books/books.module.ts

## Minimal reproduction of the problem with instructions:

> To replace MaterialModule, users can create their own "Material" module within their application (e.g., GmailMaterialModule) that imports only the set of components actually used in the application.
[https://github.com/angular/material2/blob/master/CHANGELOG.md#materialmodule](url)

## Other information:
Updates on md-input-container:
- md-input-container renamed to md-form-field 
- input: Inputs have a width of 200px by default (similar to native input elements). The width can be overridden by via the mat-form-field css class. 

**In book-search.ts**
```
md-form-field {
    width: 300px;
}
```
**instead of**
```
input {
    width: 300px;
}
```

**Comment by brandonroberts** [comment]
Our dependencies are currently locked, so this isn't necessarily a bug. Would accept a PR with these changes though.

**Comment by izifortune** [comment]
I can take this one

**Comment by izifortune** [comment]
Made some progress. All the components are updated now have to go through the unit tests

**Comment by izifortune** [comment]
#482
