### ISSUE TITLE
Typings: Signals inside a DeepSignal of a type with optional properties are marked as optional.

### ISSUE THREAD

**Issue by fmaximus** [ngrx/platform#4496]
### Which @ngrx/* package(s) are the source of the bug?

signals

### Minimal reproduction of the bug/regression with instructions

https://stackblitz.com/edit/github-cbzri9?file=src%2Fmain.ts

See added optional score property in the Quiz type.

### Expected behavior

No compilation errors. A state object with optional properties should result in a DeepSignal where all properties are always present, but the signal value can be undefined.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

@ngrx/signals: 18.0.2

### Other information

Fix: add -? to the keys in DeepSignal, or surround with Required

```typescript
export type DeepSignal<T> = Signal<T> & (IsKnownRecord<T> extends true ? Readonly<{
    [K in keyof T]-?: IsKnownRecord<T[K]> extends true ? DeepSignal<T[K]> : Signal<T[K]>;
}> : unknown);
```

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by paweltwardziak** [comment]
@fmaximus I think it is not as easy as this 
```TS
export type DeepSignal<T> = Signal<T> & (IsKnownRecord<T> extends true ? Readonly<{
    [K in keyof T]-?: IsKnownRecord<T[K]> extends true ? DeepSignal<T[K]> : Signal<T[K]>;
}> : unknown);
```
It is because an deep signal implementation
```TS
export function toDeepSignal<T>(signal: Signal<T>): DeepSignal<T> {
  const value = untracked(() => signal());
  if (!isRecord(value)) {
    return signal as DeepSignal<T>;
  }

  return new Proxy(signal, {
    get(target: any, prop) {
      if (!(prop in value)) {
        return target[prop];
      }

      if (!isSignal(target[prop])) {
        Object.defineProperty(target, prop, {
          value: computed(() => target()[prop]),
          configurable: true,
        });
      }

      return toDeepSignal(target[prop]);
    },
  });
}
```
relies on default properties thus if you just change the type, the runtime error will still be there.

```TS
export function withState<State extends object>(
  stateOrFactory: State | (() => State)
): SignalStoreFeature<
  SignalStoreFeatureResult,
  { state: State; computed: {}; methods: {} }
> {
  return (store) => {
    const state =
      typeof stateOrFactory === 'function' ? stateOrFactory() : stateOrFactory;
    const stateKeys = Object.keys(state);

    assertUniqueStoreMembers(store, stateKeys);

    store[STATE_SOURCE].update((currentState) => ({
      ...currentState,
      ...state,
    }));

    const stateSignals = stateKeys.reduce((acc, key) => {
      const sliceSignal = computed(
        () => (store[STATE_SOURCE]() as Record<string, unknown>)[key]
      );
      return { ...acc, [key]: toDeepSignal(sliceSignal) };
    }, {} as SignalsDictionary);

    return {
      ...store,
      stateSignals: { ...store.stateSignals, ...stateSignals },
    } as InnerSignalStore<State>;
  };
}
```

I assume this is by design and I all optional properties should be initializated with `void 0` value I guess.

@rainerhahnekamp @markostanimirovic @timdeschryver correct me if I am wrong.

**Comment by rainerhahnekamp** [comment]
I'd be careful. One would have to verify if that might bite back somewhere else.

@fmaximus What speaks against having a union type like this?

```typescript
export interface State {
  id: number;
  title: string | undefined;
};

const initialState: State = {
  id: 1,
  title: 'Quiz'
}

signalStore(withState(initialState));
```

**Comment by markostanimirovic** [comment]
This is intended behavior. Deep signals are generated based on the initial state keys so there is no way to generate a signal if an optional state property is not passed.

As Rainer mentioned, use `| undefined` instead.
