### ISSUE TITLE
How to unit test selector in ngOnInit?

### ISSUE THREAD

**Issue by daBishMan** [ngrx/platform#450]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## What is the current behavior?

I am not sure how to unit test a selector in the ngOnInit of a component.
## Minimal reproduction of the problem with instructions:

below is the component i am trying to test, one of many.  
`
export class SocialSourcesComponent implements OnInit {
   selectedProfileSource$: Observable<string>;

   constructor(private store: Store<filters.State>) {   }

   ngOnInit() {
      this.selectedProfileSource$ = this.store.select(profileSourceSelector);
   }
}
`

## Version of affected browser(s),operating system(s), npm, node and ngrx:
npm -v 5.3.0
node -v 8.4.0
angular -v 4.4.3
"@ngrx/effects": "^4.0.2",
"@ngrx/router-store": "^4.0.2",
"@ngrx/store": "^4.0.2",
"@ngrx/store-devtools": "^4.0.0",

**Comment by MikeSaprykin** [comment]
@daBishMan Well, the main question you need to ask yourself - what do you really want to test?
* ngOnInit ( which should be trusted to framework ) ?
* selector function? ( then, probably you'd better test it in some other place, as the logic of selector is not in component )
* selectedProfileSource$  property of component? ( I wouldn't do this, as I mock the Store in most of cases )

Probably, you don't need to test ngOnInit function itself, as you can trust that Angular has tests for lifecycle methods.

If you want to test, that selector function is returning a slice of state, which you expecting,
you can test the selector function itself, which you pass in createSelector function somewhere in reducers tests. ( That's what I'm doing most of the time )
Something like this:

---
I don't know exact context so consider below stuff as a mock:
consider you has a selector function:
```
export const profileSourceSelector = createSelector(profileStateSelector, profileSourceSelectorFn)
```
So you can test profileSourceSelectorFn that it returns expected slice of state:
```
it('should return initialProfileState.profileSource on profileSourceSelectorFn', () => {
    expect(profileSourceSelectorFn(initialProfileState))
      .toEqual(initialProfileState.profileSource);
  });
```

If you want to test that selectedProfileSource$ is expected slice of state, after store.select(selector) personally I don't do it.
I actually mock Store provider in tests of components and I don't care what is returned in select function. I mock the data, if I need to use it. But mostly, this data is used in template with | async pipe - and I don't test the template at all.

---

That's my Personal opinion and experience with testing ngrx projects. Would be great to hear other people thoughts :-)

**Comment by brandonroberts** [comment]
The testing example in the docs covers your scenario. You don't need to mock the `Store` . You can provide your test setup with some `initialState` or dispatch and action that populates the data needed by your selector.

https://github.com/ngrx/platform/blob/master/docs/store/testing.md

**Comment by daBishMan** [comment]
I am not 100% sure the documentation covers my example, or I am completely missing something. 
take this selector I am trying to test that this selectors returns the right slice of data from state.
`
export const profileSourceSelector =
   createSelector(getFiltersState, (filtersState) => filtersState.searchParams.profileSource);
`
I don't see or understand how https://github.com/ngrx/platform/blob/master/docs/store/testing.md shows how to test it, again this can be user error and limited understanding.

**Comment by MikeSaprykin** [comment]
@daBishMan, well basically selector is a function, which receives the object and returns some keys out of it.
You can test it easily in a test file, next to file, in which you define the selector.
( if in reducer, I would do it in reducer.spec.ts, if in a separate selectors file - then in selectors.spec.ts file )

You can test it like this, for example:

const mockState = {
  filtersState: {
    searchParams: {
      profileSource: 'result'
    }
  }
}

it('should return result with profileSourceSelector', () => {
  expect(profileSourceSelector(mockState).toEqual('result')
}

I'm from mobile, so sorry, no code formatting here :-)

Also, personally I don't test function composed with createSelector function. I mostly move selector functions like: 

(filtersState) => filtersState.searchParams.profileSource 

to a separate helper function and test only them.

**Comment by MikeSaprykin** [comment]
@daBishMan all you need to test in selector functions, as for me, that they return any value from the object, which has keys expected by selector function.

**Comment by brandonroberts** [comment]
@daBishMan Correct. There isn't any specific documentation on testing selectors. We can add that, but its also something you would get for free when testing your components that use these selectors. If you mock out your Store then you would need to test them separately.

**Comment by daBishMan** [comment]
thanks @MikeSaprykin and @brandonroberts for your feedback.

**Comment by cold-gin** [comment]
> 
> 
> The testing example in the docs covers your scenario. You don't need to mock the `Store` . You can provide your test setup with some `initialState` or dispatch and action that populates the data needed by your selector.
> 
> https://github.com/ngrx/platform/blob/master/docs/store/testing.md

@brandonroberts Thank you for this link. But one scenario that is extremely difficult to mock is when you use a selector inside of an effect (especially more than ONE selector). The selector can be unit tested individually as you have shown, but really if one wants to just *override* the selector within an effect to return a mock so that the rest of the logic inside of an effect can proceed to be tested, that is very difficult. It seems with efffects you do not mock the store because you need the store mechanisms to trigger the effect to run. But then the only way to override a selector is to wrap it, and I found when I wrapped the selector and injected the store within that wrapper service, I then had to stub the wrapper service, as spyOn did not work on the wrapper when the real Store was injected into it. You might say store.pipe could be spied on, but that does not seem to work when the real Store is not stubbed. Ad also spying on store,pipe would not work if I have more than one selector involved within the effect.

I do see some fix requests for ngrx 8 listed here on GitHub for a MockStore. I am just bringing up these points to describe the difficulty of overriding a selector, specifically within the context of unit testing an effect. Thanks.

**Comment by timdeschryver** [comment]
@cold-gin `MockStore` was added in NgRx 7.
