### ISSUE TITLE
Add documentation for the ESLint rule signal-state-no-arrays-at-root-level

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#4501]
### Information

The rule `signal-state-no-arrays-at-root-level` should be documented at https://github.com/ngrx/platform/blob/main/projects/ngrx.io/content/guide/eslint-plugin/rules/signal-state-no-arrays-at-root-level.md.

It should also contain one or more examples showcasing some "bad" and "good" snippets.
For some examples we can take a look at the test cases at https://github.com/ngrx/platform/blob/main/modules/eslint-plugin/spec/rules/signals/with-state-no-arrays-at-root-level.spec.ts.

### Documentation page

https://ngrx.io/guide/eslint-plugin/rules/signal-state-no-arrays-at-root-level

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by paweltwardziak** [comment]
@timdeschryver I can pick it if you want :)
