### ISSUE TITLE
Add documentation for the ESLint rule signal-store-feature-should-use-generic-type

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#4502]
### Information

The rule `signal-store-feature-should-use-generic-type` should be documented at https://github.com/ngrx/platform/blob/main/projects/ngrx.io/content/guide/eslint-plugin/rules/signal-store-feature-should-use-generic-type.md.

It should also contain one or more examples showcasing some "bad" and "good" snippets.
For some examples we can take a look at the test cases at https://github.com/ngrx/platform/blob/main/modules/eslint-plugin/spec/rules/signals/signal-store-feature-should-use-generic-type.spec.ts

### Documentation page

https://ngrx.io/guide/eslint-plugin/rules/signal-store-feature-should-use-generic-type

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by paweltwardziak** [comment]
@timdeschryver if you ok with that, I can make it same way I made it there https://github.com/ngrx/platform/blob/main/projects/ngrx.io/content/guide/eslint-plugin/rules/prefer-protected-state.md

**Comment by timdeschryver** [comment]
That would be awesome @paweltwardziak !

**Comment by paweltwardziak** [comment]
O @timdeschryver, on it

**Comment by paweltwardziak** [comment]
@timdeschryver  Sorry for the delay, I've been a bit busy these past few days. Tomorrow I will raise my PR 👍

**Comment by paweltwardziak** [comment]
@timdeschryver see #4515  I've updated prefer-protected-state.md in that PR as well - I am not sure whether or not this is something acceptable to mix a little PR responibilities. Let me knwo - I can split it into two commits :)

**Comment by timdeschryver** [comment]
> @timdeschryver see #4515 I've updated prefer-protected-state.md in that PR as well - I am not sure whether or not this is something acceptable to mix a little PR responibilities. Let me knwo - I can split it into two commits :)

For this case it's fine. 😉
