### ISSUE TITLE
@ngrx/signals: withProperties feature

### ISSUE THREAD

**Issue by guillerot** [ngrx/platform#4503]
### Which @ngrx/* package(s) are relevant/related to the feature request?

signals

### Information

I would like to be able to add properties to a SignalStore.
Neither a signal nor a method

```ts
const MyStore = signalStore(
  withProperties(() => ({
    foo: new Foo(),
    bar: new Bar(),
  })),
  withMethods((store) => ({
    playFoo: () => store.foo.play(),
    stopBar: () => store.bar.stop(),
  }))
);

const store = inject(MyStore);
const foo = store.foo;
```

### Describe any alternatives/workarounds you're currently using

```ts
const MyStore = signalStore(
  withMethods((store) => {
    const foo = new Foo();
    const bar = new Bar();
    return {
      foo: () => foo,
      bar: () => bar,
    }; 
  }),
  withMethods((store) => ({
    playFoo: () => store.foo().play(),
    stopBar: () => store.bar().stop(),
  }))
);

const store = inject(MyStore);
const foo = store.foo();
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by rainerhahnekamp** [comment]
We also see a demand for such a feature. Stay tuned

**Comment by markostanimirovic** [comment]
Just in time! 😅 Yesterday we discussed this feature at the team meeting.

I created the RFC on this topic with more details: https://github.com/ngrx/platform/issues/4504

I'm going to close this issue in favor of it.

**Comment by guillerot** [comment]
That's awesome.
Bravo and thanks for this (future) feature 👏
