### ISSUE TITLE
@ngrx/router-store - please trigger ROUTER_SUCCESS (or _ENG)  Action

### ISSUE THREAD

**Issue by majo44** [ngrx/platform#452]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
Currently module is triggering actions on navigation start, cancel and failure. But there  is no any action triggered if transition successfully ends.

## Expected behavior:
The use case where I want to use such event is solution for solving fast click problem. 
Let imagine the search results page where we have the pagination. Ech pagination link is connected with route which contains guard. Such guard is responsible for load results for particular page. For fast click between the pages we will have the behavior that UI will repaint few times and flicker with not relevant data (for the routes which was cancelled). Unfortunately angular router is triggering cancel event after all guards and resolvers are resolved. For solve this problem we can apply some simple pattern, the loading action can load data to the some temp spot in store. And reducer can copy that spot to the main place in state (which can be observed by the ui) on routerEnd event.  

Currently I triggers simply this action by self but if I'm using router-storage, this will be nice to have such action in place.

Example code:
```typescript

// state declaration
export interface ResultsState {
    readonly results?: Array<string>;
    readonly page?: number;
    readonly tmp?: ResultsState;
}

// reducer
export function resultsReducer(state: ResultsState, action: Action): ResultsState {
    switch (action.type) {
        case RESULTS_LOADED_ACTION_TYPE: {
            // After load result we will store it in tmp spot
            return Object.assign({}, state, {tmp: action.payload});
        }
        case 'ROUTER_CANCEL': {
            // If routing is cancelled we will clear tmp
            return Object.assign({}, state, {tmp: {}});
        }
        case 'ROUTER_END': {
            // If routing ends, we will copy tmp to main store
            return Object.assign({}, state, state.tmp, {tmp: {}});
        }
        default: {
            return state || {};
        }
    }
}

// route guard
export class ResultsCanActivate implements CanActivate {

    constructor(
        private store: Store<ResultsState>) {
    }

    canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<boolean> {
        let params: {id: string} = route.params as any;
        // Checking is results loaded already.
        return this.hasResultsInStore(params.page)
            .switchMap(has => {
                if (has) {
                    // if is, we can navigate to page
                    return of(true);
                } else {
                    // if not we dispatch action for load results
                    this.store.dispatch(loadResultAction(params.page));
                    // and observing is loaded (to temporary spot)
                    return this.store.select('tmp', 'page')
                        .filter(page => page === params.page)
                        .map(page => true);
                }
            });
    }

     // Checking is results loaded already.
    private hasResultsInStore(page: number): Observable<boolean> {
        return this.store
            .select('page')
            .map(p => p === page)
            .take(1);
    }
}

```

**Comment by fxck** [comment]
dupe of https://github.com/ngrx/platform/issues/314 I think

**Comment by majo44** [comment]
Indeed
