### ISSUE TITLE
component-store and effects depend on the previous version of operators

### ISSUE THREAD

**Issue by P4** [ngrx/platform#4524]
### Which @ngrx/* package(s) are the source of the bug?

component-store, effects

### Minimal reproduction of the bug/regression with instructions

1. Add the following NgRx packages to package.json:
```json
"dependencies": {
  "@ngrx/store": "18.0.2",
  "@ngrx/component-store": "18.0.2",
  "@ngrx/effects": "18.0.2",
  "@ngrx/operators": "18.0.2",
}
```
2. Run `npm install`
3. Run `npm ls @ngrx/operators`

The `operators` package is installed 3 times, component store and effects depend on their own copy of the previous patch version 18.0.1
```
├─┬ @ngrx/component-store@18.0.2
│ └── @ngrx/operators@18.0.1
├─┬ @ngrx/effects@18.0.2
│ └── @ngrx/operators@18.0.1
└── @ngrx/operators@18.0.2
```

### Expected behavior

Since all `@ngrx` packages are released and `ng update`d together, `effects`, `component-store` and their `operators` dependency should all be the same version, i.e. 18.0.2

Otherwise one may end up with three copies of `operators` in the final bundle, which is not ideal

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx: 18.0.2
Angular: 18.1.0
Node: 18.20.2

### Other information

package.json for installed `@ngrx/effects` and `@ngrx/component-store` contains the following:

```json
  "dependencies": {
    "@ngrx/operators": "18.0.1",
    "tslib": "^2.0.0"
  },
```

I'm guessing something the version didn't get bumped during release.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by P4** [comment]
Looking at cb3f6deeb21887a288162f0cf15545b26e24a849 it seems only the versions in `peerDependencies` got bumped, but since `@ngrx/operators` is a normal dependency, it was skipped

**Comment by timdeschryver** [comment]
Good catch, thanks for reporting this.
