### ISSUE TITLE
ngrx/signals: Add Store generic type

### ISSUE THREAD

**Issue by Pizzicato** [ngrx/platform#4547]
### Which @ngrx/* package(s) are relevant/related to the feature request?

signals

### Information

I run in a situation in which I need the store type inside of the store declaration, so I cannot use `InstanceType<typeof MyStore>` as this requires the instance to have been already created.

I created a [stackblitz](https://stackblitz.com/edit/github-crxqjl?file=src%2Fstore.ts) with a minimal store to picture the issue, but I think this could potentially happen in many other situations.

Could you please create a generic type for a Store that doesn't require the store instance to have been previously created?

Note: check this [discussion](https://github.com/ngrx/platform/discussions/4140) for further details.

### Describe any alternatives/workarounds you're currently using

I'm just using `any` for the store type.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by timdeschryver** [comment]
You can use `WritableStateSource` for this case.
The example in the stackblitz can be updated to:

```ts
const asyncSearch = (searchService: SearchService, store: WritableStateSource<{ example: boolean }>) =>
  rxMethod<string>(tap((query) => patchState(store, { example: true })));

// This could just return a regular function instead of using rxMethod, but it makes typings consistent compared to the asyncSearch method.
const syncSearch = (store: WritableStateSource<{ example: boolean }>) =>
  rxMethod<string>(tap((query) => patchState(store, { example: true })));

```

**Comment by alejandrocoding** [comment]
Hello! are these public apis in 17.X version? or available only on 18.x?
