### ISSUE TITLE
add support for plain eslint 9 flat config without tseslint helper

### ISSUE THREAD

**Issue by pumano** [ngrx/platform#4550]
### Which @ngrx/* package(s) are relevant/related to the feature request?

eslint-plugin

### Information

currently we have:

```ts
const tseslint = require("typescript-eslint");
const ngrx = require("@ngrx/eslint-plugin/v9");

module.exports = tseslint.config({
  files: ["**/*.ts"],
  extends: [
    // 👇 Use all rules at once
    ...ngrx.configs.all,
    // 👇 Or only import the rules for a specific package
    ...ngrx.configs.store,
    ...ngrx.configs.effects,
    ...ngrx.configs.componentStore,
    ...ngrx.configs.operators,
    ...ngrx.configs.signals,
  ],
  rules: {
    // 👇 Configure specific rules
    "@ngrx/with-state-no-arrays-at-root-level": "warn",
  },
});
```

but it need  tseslint wrapper for working because field "extends" does not exist in plain flat config.

Please add example / or provide support for plain eslint v9 flat config support

### Describe any alternatives/workarounds you're currently using

not working
```ts
const ngrx = require("@ngrx/eslint-plugin/v9");

module.exports = [
{
  files: ["**/*.ts"],
 // extends not working here because it's legacy
  extends: [
    // 👇 Use all rules at once
    ...ngrx.configs.all,
  ],
  rules: {
    // 👇 Configure specific rules
    "@ngrx/with-state-no-arrays-at-root-level": "warn",
  },
});
```

looks like I need to use something like:

```ts
const ngrx = require("@ngrx/eslint-plugin/v9");

module.exports = [

{
  ...ngrx.configs.all,
  // then override config rules with 'warn'
  files: ["**/*.ts"],
  rules: {
    // 👇 Configure specific rules
    "@ngrx/with-state-no-arrays-at-root-level": "warn",
  },
});
```

but it's not working (multiple errors while trying to load rules)

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by dobripet** [comment]
I got same issue, approach from docs does not work.

**Comment by rainerhahnekamp** [comment]
@pumano, @dobripet, just to be clear on this. The issue is that a dependency is required which is missing in our package.json?

If yes, ESLint expects that certain dependencies are already installed and that it is not necessary to explicitly add them to the package.json: https://typescript-eslint.io/developers/eslint-plugins/#package-dependencies

**Comment by dobripet** [comment]
@rainerhahnekamp 

there is no issue for me, I was just blind. In docs is typescript-eslint config used to setup and I had the same setup as @pumano. I even got working the second approach he mentions wtih dependencies fixed.

**Comment by timdeschryver** [comment]
@pumano the NgRx ESLint package does require you to install typescript-eslint, which is why it's added a a peer dependency https://github.com/ngrx/platform/blob/ca1b2748845432778da20db95acfb9c19e5da368/modules/eslint-plugin/package.json#L49. I don't see that we'll make this optional in the near future. We can make this more clear in the docs.

@dobripet can you run the timing option https://eslint.org/docs/latest/extend/stats to detect if/which rule takes that long?

**Comment by pumano** [comment]
Problem only in 
```js
module.exports = tseslint.config({
```

Plain eslint config not contain It, only plain array of configs. And tseslint config contains extends while plain not. It's looks like your example is like compat

**Comment by pumano** [comment]
looks like my fault. So I close issue

**Comment by thengstermanndev** [comment]
@pumano Currently i'm facing the same issue. We are also using the plain flat config file. Did you find any solution for this in order to get rid of the flat compat stunt?

**Comment by pumano** [comment]
@thengstermanndev I just store config in different file:

```
module.exports = tseslint.config([
  {
    files: ['**/*.ts'],
    extends: [
      // 👇 Use all rules at once
      ...ngrx.configs.all,
      // 👇 Or only import the rules for a specific package
      ...ngrx.configs.store,
      ...ngrx.configs.effects,
      ...ngrx.configs.componentStore,
      ...ngrx.configs.operators,
      ...ngrx.configs.signals,
    ],
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: { project: ['./tsconfig.*?.json'] },
    },
    rules: {
      // 👇 Configure specific rules
   }
 }
]);

and then import it in eslint config:

```
// ngrx
...companyName.configs.ngrx,
```

**Comment by thengstermanndev** [comment]
I see... Thanks for the quick response 🙂
