### ISSUE TITLE
Document patchState freeze behavior in dev mode 

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#4551]
### Information

Document the new behavior added in https://github.com/ngrx/platform/pull/4526

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by rainerhahnekamp** [comment]
I'll take that one

**Comment by markostanimirovic** [comment]
Solved in https://github.com/ngrx/platform/pull/4595
