### ISSUE TITLE
Signal Store in Native Federation Angular

### ISSUE THREAD

**Issue by NavyJot** [ngrx/platform#4552]
### Which @ngrx/* package(s) are the source of the bug?

signals

### Minimal reproduction of the bug/regression with instructions

In Native Federation Approach for micro-frontend in angular, I tried adding signal store in shared library to maintain state but unable to use store from library to host application.

![image](https://github.com/user-attachments/assets/312efefa-957c-4096-a177-ffcb6b2816ba)

### Expected behavior

We should be able to access store in MFEs.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NGRX -  Signal Store - 18
Angular 18

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by markostanimirovic** [comment]
Hi @NavyJot,

Please provide a reproduction via the GitHub repo or StackBlitz playground. This is required when reporting a bug.

**Comment by markostanimirovic** [comment]
I'm going to close this issue. Feel free to reopen it with provided reproduction via StackBlitz playground or GitHub repo.
