### ISSUE TITLE
Schematics should set `standalone` to true

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#4563]
### Which @ngrx/* package(s) are relevant/related to the feature request?

schematics

### Information

The component schematics should switch the default from the `standalone` config from `false` to `true`.
This can be done by adding a default value in the `schema.json` files.

```diff
    "standalone": {
      "description": "Whether the generated component is standalone.",
      "type": "boolean",
+     "default": true
    },
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by tanmaytare** [comment]
please assign me ,  I would be willing to submit a PR to fix this issue

**Comment by timdeschryver** [comment]
@tanmaytare thank you.
Because I see a PR attached to this issue, I want to mention that the PR should be made to ngrx/platform and not your fork.
