### ISSUE TITLE
RFC: `method` - `rxMethod` without RxJS

### ISSUE THREAD

**Issue by rainerhahnekamp** [ngrx/platform#4581]
### Which @ngrx/* package(s) are relevant/related to the feature request?

signals

## Problem

With Angular introducing `resource` and `rxResource` for handling asynchronous tasks, SignalStore could benefit from a similar feature—a standalone `rxMethod` that operates **without a dependency to RxJS**: `method`.

## Proposed Solution

The `method` function, defined as `function method<Type>(consumer: (value: T | Signal<T>) => void)`, would provide a straightforward way to process Signal changes independently of RxJS.

```typescript
const UserStore = signalStore(
  withState({selectedId: 0}),
  withMethods(store => ({
    setSelectedId: method<number>(selectedId => patchState(store, {selectedId}))
  }))
)

class UserComponent {
    userId = input.required<number>();
    userStore = inject(UserStore);
    
    constructor() {
      this.userStore.setSelectedId(this.userId);
    }
}
```

## Differences to native `effect()`

It might be tempting to see `method` as a simple `effect`:

```typescript
const UserStore = signalStore(
    // ...
    withMethods(store => ({
      setSelectedId(value: Signal<number>) {
        effect(() => {
          const selectedId = value()
          patchState(store, { selectedId });
        });
      }
    }))
)
```

However, `method` offers three distinctive advantages over `effect`:

1. **Flexible Parameter**: The parameter can also be a simple number, not just a Signal.
2. **No Injection Context Required**: Unlike an `effect`, which requires an injection context or an `Injector`, `method` can be used directly in an event listener without passing an `Injector`.
3. **Explicit Tracking**: Only the Signal of the parameter is tracked, while other Signals within the consumer function (like `anotherSignal()` in the example) are not tracked. For example:

   ```typescript
   method<number>(value => patchState(store, { counter: value + anotherSignal() }));

## Discussion

However, the name `method` may not clearly convey its purpose, so a more descriptive alternative is worth considering. Possible options include `signalMethod`.

### Describe any alternatives/workarounds you're currently using

Devs could go with a normal `effect()`. This would limit the use case of `method` to only Signals as inputs. 

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by aboudard** [comment]
First, great improvement !
Even if `method` would be in my opinion clear enough, I feel very uncomfortable with it, mostly because it just looks like native language element (method of a class).
So that would be my humble contribution, everything except `method`.
Reflecting `rxMethod`, `signalMethod` would be nice.

**Comment by rainerhahnekamp** [comment]
@aboudard 

>  looks like native language element (method of a class).

Exactly, I don't have the best feeling about the name either.

**Comment by Tiime-LcsGa** [comment]
I may have missed something so what would be the difference/benefit over this?
```ts
const UserStore = signalStore(
  withState({selectedId: 0}),
  withMethods(store => ({
    setSelectedId: (selectedId: number) => patchState(store, {selectedId})
  }))
)

class UserComponent {
    userId = input.required<number>();
    userStore = inject(UserStore);
    
    constructor() {
      this.userStore.setSelectedId(this.userId);
    }
}
```

**Comment by LcsGa** [comment]
> > EDIT: If I'm correct, the difference would be with `effect` right? But then, wouldn't these use cases be handled by the incoming events, with `withReducer` and `withEffects` ?
> 
> Yeah, I might be wrong but your example would not be triggered again when the userId would change, right ?

Okay I think I understand now! Is the goal triggering the method without calling the method?
Isn't it deflecting the `withMethod` feature?
Since `events` are coming in `@ngrx/signals` wouldn't it be their goal to handle these use cases?

**Comment by rainerhahnekamp** [comment]
@Tiime-LcsGa, your example would throw a compilation error because you are passing a `Signal` as parameter to a function that accepts only `number`. `method`/`signalMethod` would fix that.

It is not a SignalStore feature. So not in the same group as `withMethod` or `withReducer`, etc. It is a utility function

**Comment by LcsGa** [comment]
> @Tiime-LcsGa, your example would throw a compilation error because you are passing a `Signal` as parameter to a function that accepts only `number`. `method`/`signalMethod` would fix that.
> 
> It is not a SignalStore feature. So not in the same group as `withMethod` or `withReducer`, etc. It is a utility function

I missed the fact that `userId` is a signal... 😅
I see what you mean when you're saying that it's a utility function but why wouldn't you do this instead?
```ts
const UserStore = signalStore(
  withState({selectedId: 0}),
  withMethods(store => ({
    setSelectedId: (selectedId: number) => patchState(store, {selectedId})
  }))
)

class UserComponent {
    userId = input.required<number>();
    userStore = inject(UserStore);
    
    constructor() {
      effect(() => this.userStore.setSelectedId(this.userId()));
    }
}
```
What are the benefits of this utility function?
I mean, Iwouldn't mind having `method`/`signalMethod` at all, but I feel like it is a little """"hacky"""" (an `effect` running under the hood)

**Comment by rainerhahnekamp** [comment]
@LcsGa you can now check out the PR and especially the tests where you can see its usage. You'll see that there is no `withMethods` involved.

**Comment by LcsGa** [comment]
Okay I get it now! I don't know why but as I read the first message you wrote there, I thought it was only usable in `withMethods`... It's a great addition then!! 👌🏼

**Comment by LcsGa** [comment]
I just read the implementation of `rxMethod`. Wouldn't it be better to improve it by adding an overload to be able to also pass in a basic function (like your solution) instead of an operator?
The reason why I ask is because I saw that the returned function of `rxMethod` can either be called with a basic value, a signal or an observable which is the main purpose (with a signal) of your solution.

**Comment by rainerhahnekamp** [comment]
Well, looks like I didn't describe it enough in the RFC:

> With Angular introducing resource and rxResource for handling asynchronous tasks, SignalStore could benefit from a similar feature—a standalone rxMethod that operates without a dependency to RxJS: method.

With `rxMethod` you have a dependence to RxJS. Angular is going RxJS-optional. `signalMethod`is the "`rxMethod` without RxJS".

**Comment by LcsGa** [comment]
> Well, looks like I didn't describe it enough in the RFC:
> 
> > With Angular introducing resource and rxResource for handling asynchronous tasks, SignalStore could benefit from a similar feature—a standalone rxMethod that operates without a dependency to RxJS: method.
> 
> With `rxMethod` you have a dependence to RxJS. Angular is going RxJS-optional. `signalMethod`is the "`rxMethod` without RxJS".

Okay I get everything now! 👌🏼
