### ISSUE TITLE
Add migration schematic for renaming `rxMethod.unsubscribe` to `destroy`.

### ISSUE THREAD

**Issue by markostanimirovic** [ngrx/platform#4585]
### Which @ngrx/* package(s) are relevant/related to the feature request?

signals

### Information

The migration schematic should rename `rxMethod.unsubscribe` to `destroy`.

Before:

```ts
const logNumber = rxMethod<number>(tap(console.log));
const numRef = logNumber(interval(1_000));

numRef.unsubscribe();
logNumber.unsubscribe();
```

After:

```ts
const logNumber = rxMethod<number>(tap(console.log));
const numRef = logNumber(interval(1_000));

numRef.destroy();
logNumber.destroy();
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by tanmaytare** [comment]
I would be willing to submit a PR to fix this issue ,please assign me

**Comment by timdeschryver** [comment]
Thanks @tanmaytare

**Comment by timdeschryver** [comment]
@tanmaytare We want to mention that it could be that this won't be possible with our current schematics setup.
It would be great of course if we're able to do this, but we wanted to give you a heads-up so you're aware of it and don't spend too much of your time into this issue.

**Comment by markostanimirovic** [comment]
I'm going to close this issue because it's not possible to implement this migration schematic.
