### ISSUE TITLE
Remove data example app

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#4586]
### Which @ngrx/* package(s) are relevant/related to the feature request?

data

### Information

Because `@ngrx/data` is in maintenance mode and we don't really do much with the data example app, we can safely remove it.
This makes it less time-consuming to upgrade to latest versions (e.g. migrating to standalone). 

Therefore, https://github.com/ngrx/platform/tree/main/projects/data-example-app (and the corresponding NX project) can be removed.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by pawel-twardziak** [comment]
No sure if there is anything else is to be done despite the removal, is there?
