### ISSUE TITLE
fix issues when having @typescript-eslint/typedef set in error

### ISSUE THREAD

**Issue by rmartinezcba** [ngrx/platform#4587]
### Which @ngrx/* package(s) are the source of the bug?

store

### Minimal reproduction of the bug/regression with instructions

Basically when using this library over a project that contains `eslint` and having the following rule for `typedef` 
```
"@typescript-eslint/typedef": [
		"error",
					{
						"parameter": true,
						"arrowParameter": true,
						"propertyDeclaration": true,
						"variableDeclaration": true,
						"memberVariableDeclaration": true,
						"objectDestructuring": false,
						"arrayDestructuring": true
					}
],
```
Then you are forced to disable this `eslint` wherever you define a store, otherwise you get a compile error as follows:

`Module not found: Error: Package path ./src/state-signal is not exported from package .../node_modules/@ngrx/signals`

Ultimately this happens because `STATE_SIGNAL` is not exported as I understand. After adding all suggested typedefs to the arguments of the different functions `signalStore`, `withComputed`, `withMethods`, `withHooks`, etc I see no way to avoid having to import this constant which causes this error. I've seen other posts related to this but no workaround helped.

If I start setting these as `unknown` I end up getting

`Argument of type 'unknown' is not assignable to parameter of type 'StateSignal<object>'. Property '[STATE_SIGNAL]' is missing in type '{}' but required in type 'StateSignal<object>'.ts(2345)`

Is there a way this lib can be used with such strict ts config?

### Expected behavior

 `STATE_SIGNAL` should be properly imported, or other typedefs should be exposed so this library can be used and configured using strict type checking

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

Node 18.19
Angular 17.3.7
@ngrx/signals 17.2.0

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by timdeschryver** [comment]
This should be resolved in NgRx 18.0.2.
If that's not the case, feel free to reopen this issue.
