### ISSUE TITLE
Error on Nightly builds

### ISSUE THREAD

**Issue by wizardnet972** [ngrx/platform#459]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
```
(node:19504) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, stat 'C:\Users\user1\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-c49fe60e\ngrx\store.es5.js'
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2017-10-07T11_57_12_667Z-debug.log
```

## Expected behavior:

The package should be installed.

## Minimal reproduction of the problem with instructions:
npm install github:ngrx/store-builds

## Version of affected browser(s),operating system(s), npm, node and ngrx:
windows 10
npm - 5.4.2
node v6.11.0
ngrx - builds

## Other information:
yarn works fine.
npm I got an error.
I did those before:
```
λ npm cache clean
λ npm cache verify
```

**Comment by brandonroberts** [comment]
This is not an ngrx issue. See the error message: `This is an error with npm itself.`
