### ISSUE TITLE
storedevtools logging to console omitted

### ISSUE THREAD

**Issue by nhhockeyplayer** [ngrx/platform#4598]
### Which @ngrx/* package(s) are the source of the bug?

store-devtools

### Minimal reproduction of the bug/regression with instructions

providing a repo with MFE hosts and remotes
all have options liveReload=true
NgRX setup in bootstrap.ts
devtools refuses to log

the repo for this is https://github.com/nhhockeyplayer/meanstacknh

to reproduce execute the following:

1. npm install 
2. nx run-many --all --target=build
3. nx serve ui-host --devRemotes=ui-auth,ui-nav,ui-dashboard

### Expected behavior

devtools should be logging and it refuses to cooperate and log

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

nx report

 NX   Report complete - copy this into the issue template

Node           : 22.9.0
OS             : darwin-x64
Native Target  : x86_64-macos
npm            : 10.9.0

nx (global)        : 20.0.0
nx                 : 20.1.2
@nx/js             : 20.1.2
@nx/jest           : 20.1.2
@nx/eslint         : 20.1.2
@nx/workspace      : 20.1.2
@nx/angular        : 20.1.2
@nx/cypress        : 20.1.2
@nx/devkit         : 20.1.2
@nx/esbuild        : 20.1.2
@nx/eslint-plugin  : 20.1.2
@nx/express        : 20.1.2
@nx/nest           : 20.1.2
@nx/node           : 20.1.2
@nx/playwright     : 20.1.2
@nx/vite           : 20.1.2
@nx/web            : 20.1.2
@nx/webpack        : 20.1.2
nx-cloud           : 19.1.0
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/cypress/plugin
@nx/eslint/plugin
@nx/playwright/plugin
---------------------------------------
Community plugins:
@compodoc/compodoc               : 1.1.26
@fortawesome/angular-fontawesome : 0.15.0
@ionic/angular                   : 6.7.5
@jsverse/transloco               : 7.5.0
@ngrx/component                  : 18.0.2
@ngrx/component-store            : 18.0.2
@ngrx/effects                    : 18.0.2
@ngrx/entity                     : 18.0.2
@ngrx/operators                  : 18.0.2
@ngrx/router-store               : 18.0.2
@ngrx/schematics                 : 18.0.2
@ngrx/store                      : 18.0.2
@ngrx/store-devtools             : 18.0.2
apollo-angular                   : 7.2.1

### Other information

if you would like access to my repo please request access

I have done NgRX in the field at 7 previous consulting projects and have had no issues getting devtools logger going but its become more difficult each time (each project where I have to redo it and it takes longer every time some project had to go weeks and months without it wondering why its become cracking a safe) and now its gotten impossible

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by nhhockeyplayer** [comment]
would enjoy a response on this
every repo on github sporting examples of devtools is broken and does not work
nothing works on github thats coded to storedevtools logging state including route serializers
whoever is responsible for this open source code needs to own up and resolve this for the consultants in the field
this issue has been knowing and nagging for months and now years
please offer your best
step up or step down
thanks for all your help

**Comment by nhhockeyplayer** [comment]
theres no info on what was substituted deprecated or replaced
all we get is the redux tab in chrome browser

the genius who took this valuable internal angular state logging out of the chrome console is obviously not a in the trench field consultant and knows nothing about what value having that state and route serializer info directly in the console with debugging code abilities **at our fingertips simultaneously** provides

someone please offer a status on the what and why

then we would like a higher authority to step in and put the original design back in place so field consultants can do their job with precision and ease

is this some react bias so the react developers can have a chance to catch up?
angular has taken a huge hit with regard to altering itself to accomodate the javascript/react community when its been obviously clear for years and years that javascript is utterly unfit for any commercial development, yet the alterations occurred destroying the original design with javascript creator over classes patterns so the javascripters can know-what-they-are-doing because they have no clue about any real object oriented design

and its wrong
leave the original masterpiece design alone and in place as-is as it was designed and stop the surgery

PUT IT BACK !!!!!!

**Comment by nhhockeyplayer** [comment]
heres a typical use model
maybe this team is responsible for the impact to an elegant should-not-even-be-touched masterpiece on first release

and coding like this is atrocious

unfathomable

but this is what they like and need

https://github.com/zalmoxisus/redux-devtools-extension#usage

**Comment by timdeschryver** [comment]
@nhhockeyplayer it isn't clear to me what this issue is about.
Can you recap:

- what are you trying to do
- what's the current behavior
- what's the expected behavior (what log do you expect and where should it log?)

A reproduction will also help us to investigate the problem.

**Comment by nhhockeyplayer** [comment]
> @nhhockeyplayer it isn't clear to me what this issue is about. Can you recap:
> 
> * what are you trying to do
> * what's the current behavior
> * what's the expected behavior (what log do you expect and where should it log?)
> 
> A reproduction will also help us to investigate the problem.
thanks friend,

theres alot of chatter about NgRX
in the early days competition
the ngrx team whipped off this done once done right pattern overnight before the switz redux facebook gang could even get theirs off the ground and with klunky complicated atrocisous javascript... look at the redux extension page. I faint when I go there and very disimpressed. The akita euro folks chymed in trying to bump NgRX off the map with their propaganda saying theres no need for NgRX when the only diff is Akita is the same thing without effects.
in short theres alot of confusion on NgRX and publications on pros cons good bad when its really moot.
NgRX is the purest most beautiful framework ever released. Innumerable uses and features.

For me its fit for modeling de-coupled use-cases of any kind. Caches collections/instances everything immutable like it should be and it is also reactive by nature dispatches can precipitate other dispatches to the back end for a virtual reactive live app.

Im an NgRX practitioner and helped model the actions in its infancy.

Who doesn't use it is foolish its a cure all for the largest projects and its saved me in the worst asynchronous tangles.

Cut to the short... StoreDevtools was also one of the best logging mechanisms ever where we can see the complete internals of the app and the router in action, in the chrome console where debugging is right there at our fingertips.

Somehow someone omitted it completely and has deemed NgRX StoreDevtools np-more for the chrome console.

No matter how much I try it wont log anymore. And someone secretly omitted it. Theres no news about this either.

And with all the react/redux corruption infiltration to the best frameworks to accomodate their mess Im feeling this is the same infiltration to squeeze NgRX off the table so react/redux can own their spot when their stuff is not even fit to read.

someone omitted StoreDevtools from logging NgRX and CustomRouteSeralizer to the chrome console.

I cannot imagine taking on any large scale project without StoreDevtools.

But it seems only the few choose this diamond grade framework and nobody cares.

When are they going to put it back. Its obvious some react biased javascipter did this. And its sad. These are not professional grade developers making decisions like this that affect the planet.

Can someone put back the StoreDevtools back to logging in the chrome console? I dont care about that redux extension its a disaster just trying to use it and only fits someone who is NOT NgRX centric.

I prefer the raw data of instances/collections & the internal state of the router visible on the same window like it was originally designed.

The react redux folks could omit state and censor anything internally with their extension maybe thats what this is all about.

This is bad practice and the developers should be complaining about this if they had any sense for true NgRX. 

Maybe Im the only one

**Comment by nhhockeyplayer** [comment]
> * what are you trying to do
log my router and ngrx state using storedevtools
> * what's the current behavior
the chrome browser console is blank... quiet... no logging of any kind coming from storedevtools
> * what's the expected behavior (what log do you expect and where should it log?)
storedevtools should be logging everything to the console in development mode I have implemented NgRX at every project since 2017 and used storedevtools on every one successfully.
all router state and NgRX store state dispatches instances collections payloads... invaluable internals get logged to the chrome browser console but its quiet logging nothing anymore and someone thought this okay and just to use the react/redux extension when that thing has nothing to do with NgRX they are against NgRX because NgRX beat their design hands down overnight before the could even get their released and its been a nightmare for that team ever since redux will never outperform NgRX.

NgX is adopted and sponsored by @nrwl/nx too in everything they develop which speaks volumes.

Only the best coders use NgRX

its turnkey and high velocity results in precision modeled use-cases completely de-coupled and asynchronously thread safe

too many good things to list about NgRX

its the first thing I use 

theres no need of anyone silently omitting the storedevtools logger from this framework and a crime

**Comment by timdeschryver** [comment]
The DevTools works as expected with the Redux DevTools plugin.
If this isn't the case please provide a reproduction.

![image](https://github.com/user-attachments/assets/74eb14c5-325a-47d7-b55e-f3da65ccce18)

**Comment by nhhockeyplayer** [comment]
> The DevTools works as expected with the Redux DevTools plugin. If this isn't the case please provide a reproduction.

well your completely avoiding me and defaulting to whats occurred with no conscience

NgRX was originally designed with console logging of state and router to the browser console not some special interest censorship extension

and you close me out shut down with no meaningful response

and given the sentiment of the redux people and past history I cited I remain correct and this is a disgrace for NgRX

an utter disgrace

all power to you and your redux... its not NgRX and never will be

**Comment by nhhockeyplayer** [comment]
why would you close this ticket before getting an answer

see these irresponsible political decisions have already been done and theres real reason for them

but no one is talking

its okay I write bug free code 99%

I wont be relying on your redux its an insult to NgRX and the real developers that write bulletproof code

thanks for all your generosity for carving out a gem from NgRX...
NOT

**Comment by nhhockeyplayer** [comment]
so this is a case study on how outside money and power takes over a pure perfect framework or maybe just peculiar javascripters that cant do object oriented designs
and pollutes it with their own flaws

the moment I saw PROPS I knew right off the bat... the javascripters have their hands on NgRX and now they are ruining it because they only know javascript cryptic short cuts and nothing about real readable understandable and I will cite moreso natural-world patterns and have to resort to making NgRX look like redux which I find a disaster sorry

and it will only get worse with more javascript short cuts

reminder: javascript is 100% unfit for commercial development, migrating a javascripter and their mind set and habits is very difficult and costly to do it dont work and I have seen project after project get taken down some to chapt-11 because of the hip scripter ego

NgRX should not suffer another line of code change to accomodate such substandard practice

and I re-iterate my request 
REVERT storedevtools back to its original pure design to log to the browser console 
(no one is using redux and neither am I just you)

PUT IT BACK
