### ISSUE TITLE
Shouldn't Effect receive actions as modified by meta-reducers?

### ISSUE THREAD

**Issue by GiuseppePiscopo** [ngrx/platform#460]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
Application has a meta-reducer as well as an effect. Meta-reducer modifies somehow the current action before passing that down to the chain. Effect receives original, un-modified action, as if meta-reducer never ran.

## Expected behavior:
Effect should receive the action as modified by meta-reducer.

## Minimal reproduction of the problem with instructions:

[This plunker](https://embed.plnkr.co/0rE5s83qe3vnyPccMFuY/) shows the issue as a tiny demo (sorry, did not notice you had already your plunker to start with).

* Open dev console to see messages. 
* Button click sends an action. 
* Meta-reducer catches that and adds a prefix to the text. 
* The effect logs to console the received action. It should be `EFFECT: [Caught by Meta] hello` and instead it shows `EFFECT: hello`.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
At least since ngrx 4.0.0, effects 4.0.4

## Other information:
One important note: if meta-reducer creates a new action and passes that along, without touching the original one, the issue is visible.  
If instead meta-reducer mutates the input action and passes that along, effects *senses* the changes. But this breaks during development when using ngrx-store-freeze, as that library (rightly) forbids changing action payload.

**Comment by brandonroberts** [comment]
This is working as designed. New state is produced from the current _dispatched_ action and the current state, not the resulting action from the composed reducer.
