### ISSUE TITLE
@ngrx/signals: Add migration schematic for props

### ISSUE THREAD

**Issue by markostanimirovic** [ngrx/platform#4608]
### Which @ngrx/* package(s) are relevant/related to the feature request?

signals

### Information

Add migration schematic for `@ngrx/signals` package that covers breaking changes made in this PR: https://github.com/ngrx/platform/pull/4607

1) `EntityComputed` and `NamedEntityComputed` should be renamed to `EntityProps` and `NamedEntityProps`:

```diff
- import { EntityComputed, NamedEntityComputed } from '@ngrx/signals/entities';
+ import { EntityProps, NamedEntityProps } from '@ngrx/signals/entities';
``` 

2) `computed` should be renamed to `props` in `signalStoreFeature` config:

```diff
// 2.a
export function withMyFeature() {
  return signalStoreFeature(
-    { computed: type<{ num: Signal<number> }>() },
+    { props: type<{ num: Signal<number> }>() },
    // ...
  );
}

// 2.b
export function withMyFeature() {
  return signalStoreFeature(
-    type<{ computed: { num: Signal<number> } }>(),
+    type<{ props: { num: Signal<number> } }>(),
    // ...
  );
}
```

3) `computed` should be renamed to `props` in `SignalStoreFeature` generic arguments:

```diff
export function withMyFeature(): SignalStoreFeature<
-  { state: {}, computed: { num1: Signal<number> }, methods: {} },
-  { state: {}, computed: { num2: Signal<number> }, methods: {} },
+  { state: {}, props: { num1: Signal<number> }, methods: {} },
+  { state: {}, props: { num2: Signal<number> }, methods: {} },
\> {
  // ...
}
```

### Describe any alternatives/workarounds you're currently using

_

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by rainerhahnekamp** [comment]
If no one takes this by Saturday, I’ll work on it.

**Comment by PrajaktaB27** [comment]
Hello! I was taking a look at this issue and couldn't replicate it, looks like it's been resolved in the recently merged pr #4607?

**Comment by timdeschryver** [comment]
@PrajaktaB27 #4607 has implemented `props`, this issue is to create a schematic to automatically migrate/update our user's codebase.

**Comment by rainerhahnekamp** [comment]
Alright, then I'd like to take that one
