### ISSUE TITLE
ngrx selectors not not surviving initialization select/pipe/subscribe

### ISSUE THREAD

**Issue by nhhockeyplayer** [ngrx/platform#4610]
### Which @ngrx/* package(s) are the source of the bug?

store

### Minimal reproduction of the bug/regression with instructions

plz ask for collaboration to get into repo
https://github.com/nhhockeyplayer/meanstacknh
its a simple root state
selectors for root-state, app-state, layout-state modeled

selectors modeled to the max

produces undefined crash when accessing root-state 'root' during initialization with select/subscribe

it appears selectors have a gaping hole in them during initialization and so we have to guess when to launch access to a store? unless I am mistaken this logic should be graceful. 

how to launch and reproduce

the repo just renders an app.component that dispatches an action... thats it

- execute ${PROJECT-ROOT}/.clean.zsh

or

- npm i
- nx run-many --all --target=build
- nx run ui-host:serve-all

### Expected behavior

there should not be a crash when accessing NgRX root subscripting into the root state after selectors have been appropriately modeled

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

nx report

 NX   Report complete - copy this into the issue template

Node           : 22.9.0
OS             : darwin-x64
Native Target  : x86_64-macos
npm            : 10.9.0

nx (global)        : 20.0.0
nx                 : 20.1.4
@nx/js             : 20.1.4
@nx/jest           : 20.1.4
@nx/eslint         : 20.1.4
@nx/workspace      : 20.1.4
@nx/angular        : 20.1.4
@nx/cypress        : 20.1.4
@nx/devkit         : 20.1.4
@nx/esbuild        : 20.1.4
@nx/eslint-plugin  : 20.1.4
@nx/express        : 20.1.4
@nx/nest           : 20.1.4
@nx/node           : 20.1.4
@nx/playwright     : 20.1.4
@nx/vite           : 20.1.4
@nx/web            : 20.1.4
@nx/webpack        : 20.1.4
nx-cloud           : 19.1.0
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/cypress/plugin
@nx/eslint/plugin
@nx/playwright/plugin
---------------------------------------
Community plugins:
@compodoc/compodoc               : 1.1.26
@fortawesome/angular-fontawesome : 0.15.0
@ionic/angular                   : 6.7.5
@jsverse/transloco               : 7.5.0
@ngrx/component                  : 18.0.2
@ngrx/component-store            : 18.0.2
@ngrx/effects                    : 18.0.2
@ngrx/entity                     : 18.0.2
@ngrx/operators                  : 18.0.2
@ngrx/router-store               : 18.0.2
@ngrx/schematics                 : 18.0.2
@ngrx/store                      : 18.0.2
@ngrx/store-devtools             : 18.0.2
apollo-angular                   : 8.0.0

### Other information

this is similar to the ngrx-standalone-workshop but simpler yet it takes NgRX further with microfrontend/mfe and graphql.

all logic for this crash is isolated to app.component to test out selector integrity

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by nhhockeyplayer** [comment]
if you comment out lines 143-148 of app.component.ts it works fine no crash

```
    ngAfterViewInit() {
        this.store.pipe(
            select(selectAppLoaded)
        )
            .pipe(
                map((payload) => payload)
            )
            .subscribe((payload) => {
                this.notificationService.info('ApplicationLoaded state ===> ' + payload);
            });

```

if those lines of code are enabled and uncommented, theres no reason why there is a crash when accessing or there should be some fault tolerance within the selector functions

here is the error log

```
ERROR 
TypeError: Cannot read properties of undefined (reading 'root') at http://localhost:4200/apps_ui-host_src_bootstrap_ts.js:360:116 at http://localhost:4200/default-node_modules_ngrx_store_fesm2022_ngrx-store_mjs.js:962:24 at memoized (http://localhost:4200/default-node_modules_ngrx_store_fesm2022_ngrx-store_mjs.js:838:33) at defaultStateFn (http://localhost:4200/default-node_modules_ngrx_store_fesm2022_ngrx-store_mjs.js:866:39) at http://localhost:4200/default-node_modules_ngrx_store_fesm2022_ngrx-store_mjs.js:965:30 at memoized (http://localhost:4200/default-node_modules_ngrx_store_fesm2022_ngrx-store_mjs.js:838:33) at http://localhost:4200/default-node_modules_ngrx_store_fesm2022_ngrx-store_mjs.js:865:38 at Array.map (<anonymous>) at defaultStateFn (http://localhost:4200/default-node_modules_ngrx_store_fesm2022_ngrx-store_mjs.js:865:28) at http://localhost:4200/default-node_modules_ngrx_store_fesm2022_ngrx-store_mjs.js:965:30 {stack: "TypeError: Cannot read properties of undefined (re…ules_ngrx_store_fesm2022_ngrx-store_mjs.js:965:30", message: "Cannot read properties of undefined (reading 'root')"}

```

**Comment by brandonroberts** [comment]
Running zsh commands seems a little suspect. Provide a GitHub repo that doesn't need special authentication.

**Comment by nhhockeyplayer** [comment]
> Running zsh commands seems a little suspect. Provide a GitHub repo that doesn't need special authentication.

thanks friend...
I gave this a try
provideRouter(appRoutes, **withEnabledBlockingInitialNavigation()**),

still occurs
if I get time I will try to carve up a repo but right now unable to short term 
its a sizable repo but stands as a great test against nx/angular/ngrx

you and coly010 have admin rights to download packages and the repo itself

Im sure this will shake out

**Comment by rainerhahnekamp** [comment]
@nhhockeyplayer, please use the provided stackblitz. we try to avoid using private repos.
