### ISSUE TITLE
User Rate Limit Exceeded in Example App

### ISSUE THREAD

**Issue by MarkTiedemann** [ngrx/platform#466]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[X] Documentation issue or request
</code></pre>

## What is the current behavior?

Wanted to check out the example app. After querying for 3 books, surprisingly, it didn't show any books anymore. As it turns out, the example app does not handle `403 Forbidden` responses (such as the one below) very well.

```json
{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "userRateLimitExceededUnreg",
    "message": "User Rate Limit Exceeded. Please sign up",
    "extendedHelp": "https://code.google.com/apis/console"
   }
  ],
  "code": 403,
  "message": "User Rate Limit Exceeded. Please sign up"
 }
}
```

## Expected behavior:

I would expect the app to give some sort of feedback that a rate limit was reached, instead of simply showing no books. I would expect the documentation of the example app to contain some sort of notice that rate limiting may apply.

**Comment by phillipzada** [comment]
@MikeRyanDev @brandonroberts thoughts on mocking the service using mockbackend to avoid this issue? Happy to submit a PR

**Comment by brandonroberts** [comment]
I don't think the service should be mocked. Instead, create a new action such as `SearchError` that is dispatched when the API call fails, store an error message in the state and display it on the page.

**Comment by peterbsmith2** [comment]
I'm working on a PR
