### ISSUE TITLE
Question: How to access Store from Effect?

### ISSUE THREAD

**Issue by Szpadel** [ngrx/platform#467]
## I'm submitting a...

<pre><code>
[x] Documentation issue or request
</code></pre>

How to access Feature store from Effect?
I have feature module, with store created by using `Store.forFeature` and effect initialized by `Effect.forFeature`.
I can import store in effect constructor , but I also need `featureSelector` (from `createFeatureSelector`)
and this is usually created in the same file where feature ngModule is created and this create circular dependency.
Ugly workaround for this is to create second feature selector in effect file.
Then there is another issue is that store starts emitting state changes when it is initialized, this causes that is receives updates that doesn't contain required feature.
Therefore another workaround is needed: `.filter(s => !!s)` after `.select`.

It there any better way to use state inside effects? Or respond to state changes by emitting Action?

**Comment by phillipzada** [comment]
Hi @Szpadel, Have you tried the withLatestFrom operator?

```
import 'rxjs/add/operator/withLatestFrom';
...

    @Effect()
    save$: Observable<Action> = this.actions$
        .ofType(role.ActionTypes.SAVE)
        .withLatestFrom(this.store$)
        .switchMap(([action, storeState]) => {
```

**Comment by Szpadel** [comment]
Yes I tried this also, but this doesn't solve anything, because you still need to somehow import store selector.
Also with this solution (after applying first workaround) I had issues with unit testing. (store isn't emitting any state in this case) not sure why yet.

**Comment by phillipzada** [comment]
keep in mind a select fires whenever the state changes. and in relation to testing u need to mock the store and manually fire the changes to start the actions, refer to the platform example app.

can u provide some sample code of what you are trying to do?

**Comment by brandonroberts** [comment]
@Szpadel if you need to get latest state within an effect, use a selector. If you need further assistance, please use the support channel https://gitter.im/ngrx/platform

**Comment by swargoletCts** [comment]
@brandonroberts  Can you please provide an example of using a selector within an effect.  I had a pretty in-depth conversation on gitter about it but we couldn't come to a good conclusion on the best approach.  Using withLatestFrom(this.store.select(fromRoot.getData)), produced some unwanted side-effects.  

Ended up changing to the following but unsure if it is the preferred approach:  
```
   ...
    .switchMap(() => {
      return this.store$.select(fromRoot.getData)
        .take(1)
        .map((data) => ...)
    })
```

**Comment by nasreddineskandrani** [comment]
i was in the gitter discussion, this is a stackblitz of the case @swargoletCts is presenting
https://stackblitz.com/edit/ngrx-seed-qxznej?file=src%2Fapp%2Ftest%2Ftest.effect.ts

in the file ./test/test.effect you can toggle the 2 effects to see the 2 different outputs with the `withLatestFrom` and the `switchMap` + `take(1)` solution.

**Comment by nasreddineskandrani** [comment]
I didn't write test or do a PR since it's experimental. You can check this custom selector `selectStoreForEffect` in the example link below (this apply not only for effects but also components).
https://stackblitz.com/edit/ngrx-proper-multi-select-from-store?file=src%2Fapp%2Ftest%2Ftest.effect.ts

**Comment by nasreddineskandrani** [comment]
just to give a status. I am not able to type the generik `selectStoreForEffect ` without variadik type in typescript or redo what is done for `withLatestFrom` in rxjs :(

**Comment by brandonroberts** [comment]
@nasreddineskandrani Option 2 would be the way to do it. I don't see us adding a custom selector the API for this use case. We could add a section to the doc on selecting state inside effects which has had an open issue already for a while.

**Comment by swargoletCts** [comment]
I'm also curious how to use take(1) with option 1.   
Once a solution is determined, it would be very good to update the documentation as all the answers I see around the web for getting data from the store involves using withLatestFrom by itself, which as shown, can have adverse side effects.

**Comment by chrisj-skinner** [comment]
I found using Option 1 worked nicely but using

`map(([a, b]) => console.log('in effect', b))`

instead of

`tap(([a, b]) => console.log('in effect', b))`

I was going around in circles with this one. `take(1)` seams only applicable to Option 2 but also a nice solution

**Comment by swargoletCts** [comment]
@chrisj-skinner The console.log statements are there just to convey what is going on in each example.  In example 1, when the effect is initialized (not called), it is setting up and maintaining an active subscription to the selector.  So, if you have a selector with a lot of complex logic in which input parameters to that selector change often, you wouldn't want an active subscription to it as then the logic would run quite often.  Instead, you only want to access the selector when absolutely necessary, such as after a certain action runs.  

In example 2, the selector is in a switchMap and also using take(1).  That way, when an action such as  'testActions.ActionTypes.Test' is dispatched, the effect will call the selector at that time, get the latest value from it and unsubscribe, thus, only executing the selector logic once when needed.  

The whole reason for this discussion, is to hopefully have @brandonroberts clarify what is the best approach here to use a selector in an effect while ensuring that we don't have unnecessary selector logic execution.   And then once a good solution is found, updating the documentation to reflect it.

**Comment by skyzito** [comment]
Hey Guys , wasup! 

I Create one effect in my project to communicate with a service passing a parameter. 
I Did that with this solution : 

`loadCollectionReports$: Observable<Action> = this.actions$
        .ofType(CollectionActionTypes.LOAD_REPORTS)
	.withLatestFrom(this.store, (action, state) => state.companies)
	.switchMap((state) => {
			const companyId = state.companies.selectedCompanyId;
			return this.api.loadReports(companyId).pipe(
				toArray(),
				map((reports: Report) => {
					const reportsArray = reports[0].data.getReports;
					reportsArray.map((item, index) => item.id = index);
					return new LoadReportsSuccess(reportsArray);
		}),
		catchError(error => of(new LoadReportsFail(error)))
	);
});`

This is the best solution ?

**Comment by mjh5153** [comment]
Know this is an issue from 2 years ago and withLatestFrom worked for me. Wondering why we wouldn't use forkJoin though as we only care about the last value and the observables only emit one value?

**Comment by dalu** [comment]
Is this the state of the art right now or have there been any improvements meanwhile?

**Comment by alex-okrushko** [comment]
> Is this the state of the art right now or have there been any improvements or new insights meanwhile?

```ts
    withLatestFrom(this.store.select(fooSelector))
```

@dalu Does that work for you?

**Comment by PuffPastry** [comment]
This solution does not work very well for router store. I get a lot of state is not defined errors.

**Comment by nasreddineskandrani** [comment]
@PuffPastry can you share a stackblitz with an example of the issues "state is not defined errors." ?
