### ISSUE TITLE
Pattern to combat Component re-rendering - Based on Selector Observable updates

### ISSUE THREAD

**Issue by hyndsite** [ngrx/platform#469]
Question (not a bug)
How to deal with re-rendering due to updates to store state provided by selectors?

**Overview**
Store -> data is flatten and dispersed as slices of the store

I have a tree of stateless child components of a parent stateful component that uses selectors to acquire a collection of data 

`{ 
   some_data {
       more_data_1 {
          more_data_2 {}
       }
   }
}`

The stateful component passes as an @Input() prop on the first child the data, which in turn passes a portion of the data to other child components, which continues on down through a number of nested components.

**Problems**:
We use a true unidirectional flow of data - and push all changes to application state to the store which flows back down to the parent (stateful) components subscription to the returned observable provided by the selector.

Because changes to the state trigger the subscription to the selector observable, triggering an update to the @Input properties on child components, finally resulting in a re-rendering.

It doesn't matter about the ChangeDetection strategy, because as long as I am passing the data via @Input props, it triggers a re-rendering.

How is the community handling this type of setup? to Stop the re-rendering process or have more control over it?

**Comment by phillipzada** [comment]
Hi @hyndsite, in your container which use the selector, have you tried using the distinctUntilChanged operator?

**Comment by hyndsite** [comment]
@phillipzada no I haven't.  I'll have to check it out.

This partially might be an architectural issue - but if my selector is grabbing a number of pieces of different slices of the state from the store, and a child component receives as input a part of that state, and changes a value of a property, which is sent to the parent container who first that off as an action w/ payload.  The end result is that the child component receives as an update to that data as input.  Which finally, in turn, causes a re-rendering.

Almost as if - you should be making the changes to the actually received data, and when receiving an update, if it hasn't actually changed (as the child component) it doesn't re-render.

**Comment by phillipzada** [comment]
can u provide sample of ur selector plz?

**Comment by hyndsite** [comment]
`  getSelectedPageWithSectionsAndQuestions() {

    return Observable.combineLatest(this.getSelectedPageWithSections(), this.getQuestions(),
      (pageWithSections, selectQuestions) => {

        const sectionsWithQuestions = pageWithSections.sections.map(section => {
          const questions: IQuestion[] = [];

          selectQuestions.forEach(item => {

            const question: IQuestion = item;
            if (question.sectionId === section.id) {
              questions.push(question);
            }
          });

          return {
            section, questions
          };
        });

        return {
          page: pageWithSections.page,
          sectionsWithQuestions
        };
      });
  }`

So, `sectionsWithQuestions` is an object that contains sections and questions object collections.  These are provided to child components which will make changes and propagate -> store -> parent container -> triggering this selector subscriptions to fire.

**Comment by phillipzada** [comment]
that looks like your problem. have tried writing it using **createFeatureSelector** ? see example app

provide all ur selector code (from the feature state) and i can guide u futher

**Comment by hyndsite** [comment]
Thanks @phillipzada  
So below are all the selector code:

--- Question Selector ----
`private selectResult$ = this.store.select(state => state.present.questions.result);
  private selectEntities$ = this.store.select(state => state.present.questions.entities);`

`get() {
    return zip(this.selectResult$, this.selectEntities$,
      (result, entities) => result.map(id => entities[id]));
  }`
---------------


---- Page Selector ----
` private selectResult$ = this.store.select(state => state.present.pages.result);
  private selectEntities$ = this.store.select(state => state.present.pages.entities);
  private selectSelected$ = this.store.select(state => state.present.pages.selectedId);`

`  getSelected() {
    return this.selectSelected$.withLatestFrom(this.get(),
      (selectedPageId, pages) => {
        return pages.find(page => page.id === selectedPageId);
      });
  }`

---- Aggregator Selectors ----
` getSelectedPage() {
    return this.pageSelector.getSelected();
  }`


` getQuestions() {
    return this.questionSelector.get();
  }`

` getSelectedPageWithSections() {
    return Observable.combineLatest(this.getSelectedPage(),
      this.getSections(),
      (page, sections) => {
        let pageSections: ISection[] = [];

        sections.forEach (item => {
          const section = item;
          if (item.pageId === page.id) {
            pageSections = [...pageSections, section];
          }
        });

        return {
          page,
          sections: pageSections
        };
      });
  }`

` getSelectedPageWithSectionsAndQuestions() {

return Observable.combineLatest(this.getSelectedPageWithSections(), this.getQuestions(),
  (pageWithSections, selectQuestions) => {

    const sectionsWithQuestions = pageWithSections.sections.map(section => {
      const questions: IQuestion[] = [];

      selectQuestions.forEach(item => {

        const question: IQuestion = item;
        if (question.sectionId === section.id) {
          questions.push(question);
        }
      });

      return {
        section, questions
      };
    });

    return {
      page: pageWithSections.page,
      sectionsWithQuestions
    };
  });
}`

**Comment by phillipzada** [comment]
Hey mate,

So I created a rough sample based on the info provided, which could resolve your issue. The selectors only fire when the sub-state in the pipeline has been updated/touched. Remember with selectors its all about chaining what you need. If you need to use mapped data on a regular basis, i.e. in a selector, then I suggest you add that mapping as a hash-map in your state.

Note: I used any only for the models for the sake of this example.

// **pages.reducer.ts**
```

export interface State {
    result: any;
    entities: { [id: string]: any };
    selectedId: any;
}

export const initialState: State = {
    result: null,
    entities: {},
    selectedId: null
};


export function reducer(state: State = initialState, action: any): State {

    switch (action.type) {
        case '[Pages] SET':
            return {
                ...state,
                ...action.payload
            };

        default:
            return state;
    }
}


export const getResults = (state: State) => state.result;
export const getEntities = (state: State) => state.entities;
export const getSelectedId = (state: State) => state.selectedId;
```
// **questions.reducer.ts**
```

export interface State {
    result: any;
    entities: { [id: string]: any };
}

export const initialState: State = {
    result: null,
    entities: {}
};


export function reducer(state: State = initialState, action: any): State {

    switch (action.type) {
        case '[Questions] SET':
            return {
                ...state,
                ...action.payload
            };

        default:
            return state;
    }
}


export const getResults = (state: State) => state.result;
export const getEntities = (state: State) => state.entities;
```
// **sections.reducer.ts**
```

export interface State {
    sections: any[];
}

export const initialState: State = {
    sections: []
};


export function reducer(state: State = initialState, action: any): State {

    switch (action.type) {
        case '[Sections] SET':
            return {
                ...state,
                ...action.payload
            };

        default:
            return state;
    }
}


export const getSections = (state: State) => state.sections;
```
// **present.state.ts**
```
import { createFeatureSelector, createSelector } from '@ngrx/store';
import { values } from 'lodash';
import * as fromPages from './pages.reducer';
import * as fromQuestions from './questions.reducer';
import * as fromRoot from './root.state';
import * as fromSections from './sections.reducer';

export const PRESENT_FEATURENAME = 'present';

export interface PresentState {
    pages: fromPages.State;
    questions: fromQuestions.State;
    sections: fromSections.State;
}

export interface State extends fromRoot.State {
    present: PresentState;
}

export const reducers = {
    pages: fromPages.reducer,
    questions: fromQuestions.reducer,
    sections: fromSections.reducer
};


// Top Level Selectors
export const selectPresentState = createFeatureSelector<PresentState>(PRESENT_FEATURENAME);
export const selectPagesState = createSelector(selectPresentState, (state: PresentState) => state.pages);
export const selectQuestionsState = createSelector(selectPresentState, (state: PresentState) => state.questions);
export const selectSectionsState = createSelector(selectPresentState, (state: PresentState) => state.sections);

// Questions Selectors
export const selectQuestionResults = createSelector(selectQuestionsState, fromQuestions.getResults);
export const selectQuestionEntities = createSelector(selectQuestionsState, fromQuestions.getEntities);

export const getQuestions = createSelector(selectQuestionResults, selectQuestionEntities,
    (results, entities) => results.map(result => entities[results]));

// Page Selectors
export const selectPageResults = createSelector(selectPagesState, fromPages.getResults);
export const selectPageEntities = createSelector(selectPagesState, fromPages.getEntities);
export const selectPageSelectedId = createSelector(selectPagesState, fromPages.getSelectedId);

export const selectSelectedPage = createSelector(selectPageEntities, selectPageSelectedId,
    (entities, selectedId) => entities[selectedId]);

// Selection Selectors
export const selectSelections = createSelector(selectSectionsState, fromSections.getSections);

// Aggregator Selectors
export const getSelectedPageWithSections = createSelector(selectSelectedPage, selectSelections,
    (selectedPage, sections) => {

        let pageSections: any[] = [];

        // Strongly suggest rework your state so you can does this simply and optimised, i.e. hashmap during reducer firing
        sections.forEach(item => {
            const section = item;
            if (item.pageId === selectedPage.id) {
                pageSections = [...pageSections, section];
            }
        });

        return {
            page: selectedPage,
            sections: pageSections
        };

    });

export const getSelectedPageWithSectionsAndQuestions = createSelector(getSelectedPageWithSections, getQuestions,
    (pageWithSections, questions) => {

        // Strongly suggest rework your state so you can does this simply and optimised, i.e. hashmap during reducer firing
        const sectionsWithQuestions = pageWithSections.sections.map(section => {
            const _questions: any[] = [];

            questions.forEach(item => {

                const question = item;
                if (question.sectionId === section.id) {
                    questions.push(question);
                }
            });

            return {
                section, questions
            };
        });

        return {
            page: pageWithSections.page,
            sectionsWithQuestions
        };

    });
```

**Comment by brandonroberts** [comment]
Thanks @PhillipZada!
