### ISSUE TITLE
Add a tag for each entity-build

### ISSUE THREAD

**Issue by Abrissirba** [ngrx/platform#470]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
If you add entity-builds to your package.json file and use the new package-lock.json a checksum is added to the lock file. This checksum is changed on every commit to entity-builds/master which then prevents npm install and makes it difficult use in a team with multiple developers. This would be solved by adding tags for each build.

**Comment by brandonroberts** [comment]
The official build will be tagged once released.

**Comment by Abrissirba** [comment]
Thanks, solved until then by creating a fork
