### ISSUE TITLE
Example App Fails miserably

### ISSUE THREAD

**Issue by TaylorZaneKirk** [ngrx/platform#471]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ x ] Documentation issue or request
</code></pre>

## What is the current behavior?

Build/serve fails while trying to run the example app. (Obviously the Angular Material update which deprecated a lot of stuff was a part of this, but also...) The example-app directly calls for @ngrx/entity import. Why? Why would you do this, developers? That import isn't even out, from everything I've read. And you know that! It's your import!! I tried to use the nightly builds and NPM errored out, so maybe its partially NPM's fault. But most of the blame is on the developers in this repo, and their sub par documentation.

Honestly, NGRX is so nice sounding when simply discussing the theory, but unfortunately the devs have made it almost impossible for someone trying to pick it up in its "current" state to be able to really learn how to use it well. And they don't help matters out when your EXAMPLE app, MEANT FOR LEARNING, cannot be easily approached.

The ReadMe of the example app doesn't even say that router-store is required. The ReadMe only calls for router.

It's so confusing to me; how the "product" (ngrx itself) is so well-done and thought out, but all the documentation to learn how to use this product are just Lazy. It's incredibly disappointing.

## Expected behavior:

Have the Example App be an example of how to work with the CURRENT state and build of NGRX. A reflection of what is CURRENTLY available to the general public AT THIS MOMENT, so as to avoid confusion and frustration on the part of the person trying to learn.

## Minimal reproduction of the problem with instructions:

1. Simply try to follow the example app and its documentation verbatim.
2. Watch the errors begin to stack up.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
Using Chrome on Windows 10
Latest ngrx

**Comment by bmayen** [comment]
Official releases are tagged. Use an official, tagged version. 

This is an open source work in progress. Using unreleased code which is still in active development and complaining in caps that the devs are doing lazy work contributes nothing to this community.

**Comment by TaylorZaneKirk** [comment]
@bmayen 
Admittedly, after having some lunch and unwinding a bit, you're absolutely right. It wasn't my intention to call the devs lazy (I was only referring to the documentation) but that is the general tone that reading this post seems to communicate. I do still believe documentation efforts on the part of operating ngrx as whole could be improved, but I could have said that in a more helpful and professional manner.

Closing now.

**Comment by bmayen** [comment]
I agree that I would love to see more and deeper documentation. All in good time, I'm sure :)

**Comment by bmayen** [comment]
FWIW, the example app itself is thoroughly documented. If you want to work on the bleeding edge, I suggest creating your own test app and following along with the code from the example app. You don't necessarily need to be able to build and run it if you can build and run your own attempts. I'm doing exactly this as we speak.

**Comment by bmayen** [comment]
@TaylorZaneKirk, actually, I just pulled down latest and it compiles and runs fne. I did have to set upstream to origin/master, so maybe that's the issue for you?
