### ISSUE TITLE
Can not install entity-builds

### ISSUE THREAD

**Issue by xipheCom** [ngrx/platform#472]
## I'm submitting a...

<pre><code>
[X] Bug report  
</code></pre>

## What is the current behavior?

<pre><code>
npm install github:ngrx/entity-builds
</code></pre>

gives the following error

(node:1412) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, stat '/home/[user]/.npm/_cacache/tmp/git-clone-da37a064/ngrx/entity.es5.js'

## Expected behavior:

Should install smoothly.

## Minimal reproduction of the problem with instructions:
<pre><code>
npm install github:ngrx/entity-builds
</code></pre>

## Version of affected browser(s),operating system(s), npm, node and ngrx:

Debian Stretch, 
node 8.4
npm 5.4.2

## Other information:

As far as I found out the error occurs because npm awaits entity.es5.js in folder "ngrx". But if I open the path I can find only /home/[user]/.npm/_cacache/tmp/git-clone-da37a064/@ngrx/entity.es5.js'. Look at the additional "@"-Sign in ngrx.

I have tried npm cache clean -f and npm cache verify, also deleted some temporary folders from npm.

**Comment by xipheCom** [comment]
+ No error with yarn

**Comment by brandonroberts** [comment]
This is not an ngrx issue but an error with npm itself.

**Comment by xipheCom** [comment]
But why i can find everything in .../@ngrx/... and npm will try .../ngrx/... What says npm to use the folder ngrx instead @ngrx? Other packages with @ like @angular/... installs well
