### ISSUE TITLE
Add file loader into the app configuration

### ISSUE THREAD

**Issue by cmontois** [ngrx/platform#474]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ X ] Documentation issue or request
</code></pre>

## What is the current behavior?

It's not very an issue coming from your repository, i'm just struggling with a configuration issue, but I think you can help me :
I have a player inside my Angular4 project build with your repo, but the problem is that this player is in React and I want to import it in one of my Angular file.
```
ERROR in ./showhow-admin/app/player/react/renderReactTree.js
Module parse failed: /var/www/html/js-projects/showhowadmin/node_modules/source-map-loader/index.js!/var/www/html/js-projects/showhowadmin/showhow-admin/app/player/react/renderReactTree.js Unexpected token (12:4)
You may need an appropriate loader to handle this file type.
| export function renderReactTree(store) {
|   const root = (
|     <Provider {...{store}}>
|       <ConnectedApp/>
|     </Provider>
 @ ./showhow-admin/app/player/react/index.js 1:0-49
 @ ./showhow-admin/app/player/player.module.ts
 @ ./showhow-admin/app/guides/components/guide-detail.ts
 @ ./showhow-admin/app/guides/components/index.ts
 @ ./showhow-admin/app/guides/guides.module.ts
 @ ./showhow-admin async
 @ ./~/@angular/core/@angular/core.es5.js
 @ ./showhow-admin/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./showhow-admin/main.ts
```
So It appears I need to add a special loader for react file, well I get that, but where shall I add this ?
When I added webpack to the dependencies in order to put this loader in webpack.config.js. 
The example:start script failed during the webpack compilation.

So If you have any Idea of how to do that, would be very appreciated, It's probably just a configuration things, but I am pretty new to Javascript apps so I don't truly know how to do this 

Project Structure:

example-app
-> auth
-> core
-> guides
-> **player**
-> reducers
-> shared

I shall maybe change the place of the folder to put it outside of the example app ?

## Expected behavior:
I want my app to be able to read my React js files and so to compile

## Version of affected browser(s),operating system(s), npm, node and ngrx:
node => v8.6.0
npm => 5.4.2

**Comment by NexiR** [comment]
I added the allowJs in the tsconfig.json file (I think I just need to add a react files loader but I m not truly sure How & Where

**Comment by brandonroberts** [comment]
The Angular CLI support channel is better suited for your issue. https://gitter.im/angular/angular-cli
