### ISSUE TITLE
rootReducer not called

### ISSUE THREAD

**Issue by broweratcognitecdotcom** [ngrx/platform#475]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## What is the current behavior?

I am using StoreModule.forFeature() in my feature modules. My rootReducer:

export function rootReducer(state: any = { }, action: Action): any {
  switch (action.type) {
    case RootActionsService.SET_ROOT_STATE:
      let actionWithPayload = action as ActionWithPayload;
      return actionWithPayload.payload;
    default:
      return state;
  }
}

I am importing it like this:

StoreModule.forRoot(rootReducer)

I dispatch RootActionsService.SET_ROOT_STATE via a service function:

setRootState(state: any) {
  this.store.dispatch(createAction(RootActionsService.SET_ROOT_STATE, state));
}

When this happens, I see my feature reducers called which aptly disregard the action as it not meant for them.

But my rootReducer never gets called. Why?
## Expected behavior:

The rootReducer needs to be called.

**Comment by brandonroberts** [comment]
Passing a function as the root reducer is not supported this way. You need to provide a map of reducers that are composed into the root state.

**Comment by broweratcognitecdotcom** [comment]
I guess I followed an old tutorial. Strange how there is no compilation error, and no errors in the console in this configuration.
