### ISSUE TITLE
Shared state with feature stores

### ISSUE THREAD

**Issue by philjones88** [ngrx/platform#486]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## What is the current behavior?

I'm struggling to find documentation or anything in the example app that demonstrates how to have feature stores but a "shared" store for common state.

I'm migrating an app from v2 and we have "layout" splice of state that I hoped to put into some form of "shared" store that could be used across all the feature stores.

The link here 404's

https://github.com/ngrx/platform/blob/master/docs/store/api.md#feature-module-state-composition

## Expected behavior:

A documented way to achieve the above, ideally built into the example app to show how it's done in a full application.

**Comment by sandangel** [comment]
you should have interface for the state of feature store extends interface state of shared store.

**Comment by philjones88** [comment]
@sandangel do you have a code example?

Ideally I'd like to access the "shared" state via store inside feature module components.

**Comment by sandangel** [comment]
‘export interface FeatureState extends SharedState {....}’ then in feature component inject Store<FeatureState>. i on mobile and i can not give you an example, hope you can figure it out

**Comment by philjones88** [comment]
I think I got it, it compiles.

Next challenge is it seems to be running all effects with `.withLatestFrom(...store code here...)` on page init rather than when the action happens.
