### ISSUE TITLE
Importing `EffectsModule.forRoot([MyEffects])` makes Http service undefined

### ISSUE THREAD

**Issue by trumbitta** [ngrx/platform#489]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
The `Http` service disappears (becomes `undefined`) from my application when I add `EffectsModule.forRoot([MyEffects])` to my `AppModule`.

## Expected behavior:
The `Http` service doesn't disappear.

## Minimal reproduction of the problem with instructions:
Using `@ngrx/effects` v4.0.5 with Angular v4.4.4.

When I import `EffectsModule` in `app.module.ts`, the Http service becomes undefined.

Some code:

```ts
    // app.module.ts
    import { BrowserModule, Title } from '@angular/platform-browser';
    ...
    import { HttpModule, Http } from '@angular/http';
    ...
    import { EffectsModule } from '@ngrx/effects';
    import { AuthenticationModule } from './authentication/authentication.module';
    import { MyEffects } from './myEffects.ts'
    ...

    @NgModule({
      declarations: [
        AppComponent
      ],
      imports: [
        BrowserModule,
        HttpModule,
        ...
        AuthenticationModule,
        StoreModule.forRoot(reducers),
        EffectsModule.forRoot([MyEffects])
      ]
      ...
    })
    export class AppModule { }
```

**Please note that `MyEffects` isn't related in any way to the authentication feature.**

When I use the first thing I can use in my app, the sign in button, I call AuthenticationService.signIn, which in turn calls its http instance `this.http.post(...`

And `this.http` is undefined (got an error message, looked into it via debugger, and found it undefined - `this` is not undefined and has a `http` property which is undefined)

If I comment out `EffectsModule.forRoot([MyEffects])`, the http service "reappears" and the sign in works.

**Please note that `MyEffects` isn't related in any way to the authentication feature.**

## Version of affected browser(s),operating system(s), npm, node and ngrx:

Chrome latest, ngrx/effects 4.0.5

**Comment by roopkt** [comment]
@trumbitta seems to be angular setup issue. Can you share any sample app. Because it works for me. I have many api calls in effect for root as well.

**Comment by trumbitta** [comment]
hi @roopkt , thanks, I tried to reproduce the problem and noticed that on StackBlitz I was using Angular 4.4.5 instead of 4.4.4 and I couldn't reproduce the problem.

I then updated locally to 4.4.5 and the problem was gone!

**Comment by roopkt** [comment]
Excellent ! @trumbitta

**Comment by brandonroberts** [comment]
👍

**Comment by joewoodhouse** [comment]
I seem to have got this again with angular5, anyone else?

**Comment by trumbitta** [comment]
@joewoodhouse for me everything's fine with `5.0.0`

**Comment by jameskentTX** [comment]
Angular 5.2.0, ngrx 4.1.1
I can't use HttpClient in effects of AppModule. Adding "private http: HttpClient" to effects constructor generates error and application crashes. If I remove http from constructor everything works ok.

**Comment by imranbutt-java** [comment]
<img width="506" alt="screen shot 2018-01-16 at 9 06 02 pm" src="https://user-images.githubusercontent.com/4415622/34998537-272133e4-fb01-11e7-8b3f-05754cfee5d9.png">

ng --version

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.6.1
Node: 8.9.3
OS: darwin x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.1
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.1
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0

and I can't import HttpModule.
