### ISSUE TITLE
Add support for actionSanitiser in @ngrx/store-devtools

### ISSUE THREAD

**Issue by aboyton** [ngrx/platform#494]
## I'm submitting a...

<pre><code>
[ ] Regression (a behaviour that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behaviour?
`redux-devtools-extension` has support for having an `actionSanitizer` (see https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#actionsanitizer--statesanitizer).

## Expected behaviour:
I'd like be able to use this with @ngrx/store-devtools if possible, but I can't seem to work out how this can be done.

**Comment by roopkt** [comment]
@brandonroberts  I checked in the support for both state and action sanitizer. Not sure how to create pull request.
