### ISSUE TITLE
ngrx v4 upgrade causes AOT issue

### ISSUE THREAD

**Issue by mickymots** [ngrx/platform#502]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

ng build --prod results in the following error

Error: SyntaxError: Unexpected token: (devtoolextension)

## Expected behavior:

ng build --prod run successfully

## Version of affected browser(s),operating system(s), npm, node and ngrx:
N/A
## Other information:
This error occurs only where the Feature store has been used

**Comment by brandonroberts** [comment]
Please provide a reproduction of the issue with more information
