### ISSUE TITLE
Should we use root state in feature module?

### ISSUE THREAD

**Issue by HWouters** [ngrx/platform#503]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

Thank you for providing the very useful example app! I have a question though about the use of the root state in a feature module. For example the auth module has the following code in its reducer file.
<pre><code>
import * as fromRoot from '../../reducers';

...

export interface State extends fromRoot.State { 
    auth: AuthState;
}
</code></pre>

My problem is the auth module is using a class (State) from the app module, but I would like to have my feature modules independent. Can you comment on this? Are there other ways of doing this?

**Comment by brandonroberts** [comment]
You're only extending the root interface to get the type information when creating selectors. You can completely separate your feature state, but you won't have the interface information from the root feature state unless you redefine the interface.
