### ISSUE TITLE
@ngrx/entity@4.1.0 not published?

### ISSUE THREAD

**Issue by bmayen** [ngrx/platform#505]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

npm info @ngrx/entity

npm ERR! code E404
npm ERR! 404 Not found : @ngrx/entity
npm ERR! 404
npm ERR! 404  '@ngrx/entity' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

## Expected behavior:

Expecting to see @ngrx/entity published with platform 4.1.0 release

**Comment by MikeRyanDev** [comment]
Sorry, was published as a private package by mistake. It should work now.

**Comment by bmayen** [comment]
verified 🎉
