### ISSUE TITLE
subscribe works fine but async in template gives [object Object] 

### ISSUE THREAD

**Issue by ysfjwd** [ngrx/platform#506]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
I am trying to get the observable of a custom type

```ts
export interface ConfigurationState {
  outlet_id: number;
  api_key: string;
}
```

in my component

```ts
@Component({
  selector: 'retail-root',
  templateUrl: './root.component.html',
  styleUrls: ['./root.component.scss']
})
export class RootComponent implements OnInit {
  public config$: Observable<ConfigurationState>;

  constructor(private store: Store<fromRoot.State>) {
    this.config$ = this.store.select(fromRoot.getConfigState);
    this.config$.subscribe(data => console.log(data));
   }

  ngOnInit() {
    console.log(this.config$);
    this.store.dispatch(new configActions.GetConfig());
  }

}
```

when i do

```html
{{ config$ | async }}
```

it gives me ```[object Object] ``` but if do subscribe, ```this.config$.subscribe(data => console.log(data));``` i get my object correct in console.

Something wrong with my setup?

## Expected behavior:

I should be able to get the object correctly in template.

## Version of affected browser(s),operating system(s), npm, node and ngrx:

browser: Chrome, Electron
OS: osx siera
npm: 5.4.2
node: 8.7.0
ngrx:

**Comment by fxck** [comment]
try `{{ config$ | async | json }}`

**Comment by ysfjwd** [comment]
oh great ... just a quick question.

if i do, ```{{ config$.outlet_id  }}``` i  don't get anything.

**Comment by fxck** [comment]
that's not how it works

```
{{ (config$ | async)?.outlet_id }}
```

and also none of these have anything to do with ngrx but rather with general knowledge of angular, would be best to ask on gitter.im/angular/angular

**Comment by ysfjwd** [comment]
sorry my bad. and thankyou for quick responses. sorry to bother. didn't mean to offend.
