### ISSUE TITLE
effects started shipping generated angular code with absolute paths

### ISSUE THREAD

**Issue by alexeagle** [ngrx/platform#510]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

Since 2.0.1, effects has started shipping these files:
https://unpkg.com/@ngrx/effects@2.0.4/src/effects.ngsummary.json
they have absolute paths from your machines.

I don't think this breaks most angular users, as they run `ngc` with an option that overwrites these files. However, when run under bazel we don't overwrite the files so user gets an error like 'cannot find type from /User/robertbt/some/path/effects.d.ts'

## Expected behavior:

Libraries should ship only with `metadata.json` files, not `ngsummary.json` files.

**Comment by MikeRyanDev** [comment]
We'll release a patch for 2.x that should address this.

**Comment by brandonroberts** [comment]
Patch released as `2.0.5`
