### ISSUE TITLE
Nighty build - TypeError

### ISSUE THREAD

**Issue by flauc** [ngrx/platform#52]
When ever I try introducing an effect in main `AppModule`  like this: 
```
EffectsModule.forRoot([
  LoginEffects
]),
```
I get the following error (even if the effect is completely empty): 
```
TypeError: Cannot read property 'lift' of undefined
 at observeOn...
 at new State...
```
This is on Chrome, my node version is 7.7.3 and npm 4.1.2.
Any help is greatly appreciated.

**Comment by fxck** [comment]
https://github.com/ReactiveX/rxjs/issues/2539#issuecomment-312234113

**Comment by flauc** [comment]
Thank you very much @fxck you saved me from a lot of digging 👍

**Comment by flauc** [comment]
I'm no longer convinced this is the same error. I've went through all the suggestion and looks like nothing helps. Also the error message is a bit different. It looks like `this` is not defined here: 

```js
function observeOn(scheduler, delay) {
    if (delay === void 0) { delay = 0; }
    return this.lift(new ObserveOnOperator(scheduler, delay));
}
```

This is from ngrx/effects

**Comment by axtho** [comment]
what TS version are you running?

**Comment by flauc** [comment]
2.4.1 but I tried with 2.3.4 and a few others as well. Looks like this pull request just fixed it. Will try now.

https://github.com/ReactiveX/rxjs/pull/2715

**Comment by axtho** [comment]
@flauc did that work for you?

**Comment by flauc** [comment]
Nop, I'm hoping tomorrow a fix for rxjs might come out.

**Comment by flauc** [comment]
That fixed it.

**Comment by vdsabev** [comment]
I just got this error today and was struggling to find a fix for about an hour.

I was trying to combine 2 observables, like so:
```ts
    @Effect()
    private setProfileCards$ = combineLatest(
        this.actions$.ofType(SELECT_DECK),
        this.config.config$.pipe(select('deck-cards')),
        (action: SelectDeck, cards: Card[]) => {
            ...
        },
    );
```

It was failing because of the most ridiculous of reasons...I was importing:
```ts
import { combineLatest } from 'rxjs/operators/combineLatest'; // Wrong!
```

Instead of:
```ts
import { combineLatest } from 'rxjs/observable/combineLatest'; // Correct
```

First time using RxJS, you can have a laugh 😆
Hopefully this helps someone else!
