### ISSUE TITLE
DevTools Error: @ngrx/store": 4.1.0 @angular:4.4.5

### ISSUE THREAD

**Issue by Max-Lev** [ngrx/platform#523]
error in devtools.d.ts(1,10) =>node_modules/@ngrx/store/store"' has no exported member 'Dispatcher'.
error in devtools.d.ts(1,22) =>node_modules/@ngrx/store/store"' has no exported member 'Reducer'.

There is an error with DevTools: module tries to import  { Dispatcher, Reducer } from '@ngrx/store';
inside of devtools.d.ts file.

**Comment by brandonroberts** [comment]
You're using the wrong version of store-devtools. You should be using `4.0.0` instead of `2.x`. If you need further assistance, use the support channel https://gitter.im/ngrx/platform
