### ISSUE TITLE
createSelector type error with selectIds from .adapter.getSelectors()

### ISSUE THREAD

**Issue by herkulano** [ngrx/platform#525]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

Adding a selector with `selectIds` from `.adapter.getSelectors()` throws a type error.

Using the `example-app`:
```js
export const {
  selectIds: getBookIds,
  selectEntities: getBookEntities,
  selectAll: getAllBooks,
  selectTotal: getTotalBooks
} = fromBooks.adapter.getSelectors(getBookEntitiesState)

const selectTest = createSelector(
  getBookIds,
  getBookEntities,
  (ids, entities) => {
    return { ids, entities }
  }
)
```

Error:
```
/platform-master/example-app/app/books/reducers/index.ts (97,3): Argument of type '((state: object) => number[]) | ((state: object) => string[])' is not assignable to parameter of type 'Selector<object, number[]>'.
  Type '(state: object) => string[]' is not assignable to type 'Selector<object, number[]>'.
    Type 'string[]' is not assignable to type 'number[]'.
      Type 'string' is not assignable to type 'number'.
```

## Version of affected browser(s),operating system(s), npm, node and ngrx:
@ngrx/entity 4.1.0

**Comment by brandonroberts** [comment]
Did you change the interface type for the `Book` to `number`?

**Comment by herkulano** [comment]
@brandonroberts no, the `example-app` is untouched except for the above code.

**Comment by herkulano** [comment]
@brandonroberts 

https://github.com/ngrx/platform/blob/f50690fc0f67a42c5614ed42b41ecb5f54a48d83/modules/entity/src/models.ts#L68-L84
The code below resolves the issue:
```ts
export type EntitySelectors<T, V> = {
  selectEntities: (state: V) => Dictionary<T>;
  selectAll: (state: V) => T[];
  selectTotal: (state: V) => number;
  selectIds: (state: V) => string[] | number[];
};
```

**Comment by goelinsights** [comment]
For anyone else who gets a type error: "Cannot invoke an expression whose type lacks a call signature", the union in the selectIds type that was changed in #533  is I believe the issue.

`export interface EntityState<T> {
  ids: string[] | number[];
  ...
}
`
I got this trying to check if the id exists in a guard.
`    return this._store.pipe(
      select(getProductIds),
      map(productIds => productIds.filter(productId => productId === id)),`

Current workaround is to escape the type for getProductIds:
`select(<any>getProductIds)`

@brandonroberts do you have a better suggestion for getting access to Array commands without triggering the type error?
