### ISSUE TITLE
Type definitions for select are wrong

### ISSUE THREAD

**Issue by aboyton** [ngrx/platform#528]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

In `platform/modules/store/src/store.ts` the type definitions for `select` all specify that they will return a value, but if you have a store that's indexed by identifiers you might not find a value.

So if the store is of type
```ts
type Store = {
  [id: string]: User;
};
```
then
```ts
const user: User = select('1');
```
even though `select('1')` could return `undefined`.

The docs and the code for `pluck` both show that it returns `undefined` if the item is not found ( http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-pluck, or https://github.com/ReactiveX/rxjs/blob/master/src/operators/pluck.ts)

## Expected behavior:

The type of `select` should be
```ts
select<a extends keyof T>(key: a): Store<T[a] | undefined>;
```
(and the same for the other overloads).

## Version of affected browser(s),operating system(s), npm, node and ngrx:
`ngrx`: either the tip of master or the latest release (4.1.0).

**Comment by brandonroberts** [comment]
This would be a breaking change. You already receive an error if you act on an undefined return. Closing for now.

**Comment by aboyton** [comment]
What do you mean you "You already receive an error if you act on an undefined return"? Do you mean you get a runtime error? That's exactly what I'm wanting to avoid, I'd like this to be picked up at compile time not runtime.

I completely agree that this would be a breaking change, programs that presently compile (but could fail at runtime) would no longer compile.

A you suggesting though the current definition is type correct or that you don't want to fix this now?
