### ISSUE TITLE
NgRx Store Devtools 4.0.0 +  Apollo-Angular Monitors/Displays only Apollo Actions

### ISSUE THREAD

**Issue by Max-Lev** [ngrx/platform#529]
"@ngrx/store-devtools": "^4.0.0",
"apollo-client": "^1.9.3",
"@angular/core": "^4.4.5".

Dev tools monitors only Apollo Requests and do not display Actions that lead to this requests:
Paging Action => Apollo Request displays only graphQL.

**Comment by brandonroberts** [comment]
Please provide a reproduction of this issue

**Comment by Max-Lev** [comment]
Found it: needed to change dev-tools options.
Tnx.
