### ISSUE TITLE
extend router state docs with router as single source of truth

### ISSUE THREAD

**Issue by axtho** [ngrx/platform#531]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## Expected behavior:
There are a number of sources out there that suggest to make the router the single source of truth, i.e. the dispatcher of actions. There is a [nice example](https://github.com/vsavkin/state_management_ngrx4/blob/master/clientapp/src/app/model.ts) out there.

If this a proper way of doing this like rehydration (etc), then  it would be helpful to have a section on this in the router-state docs, because the setup is quite a bit different from the example app.

**Comment by brandonroberts** [comment]
Making the router the source is one way to build your app on top of ngrx, but we do not recommend one convention over another.
