### ISSUE TITLE
"TypeError: Cannot convert undefined or null to object"

### ISSUE THREAD

**Issue by L0Y4L** [ngrx/platform#532]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
 "TypeError: 
![bug](https://user-images.githubusercontent.com/32991599/32143870-a7245998-bcb0-11e7-9c4d-8f343e63a814.png)
"TypeError: Can not convert undefined or null to object"

## Expected behavior:
 It should run fine on cmd..

**Comment by brandonroberts** [comment]
This is not a bug in ngrx
