### ISSUE TITLE
No documentation on how to get time travel debugging working with ngrx/router-store

### ISSUE THREAD

**Issue by sdebaun** [ngrx/platform#536]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
</code></pre>

I have been trying to get time travel debugging working with ngrx/router-store and have had no success.  The documentation doesn't add any clarity.  Are there any example applications that have time travel debugging for route changes?

I will submit a doc PR if someone can actually show me what I need to do to get this (@#)% working. <3

**Comment by sdebaun** [comment]
omg.  i love you.

why is that?  is that a magic state name that the extension looks for?

i had the reducer mounted as `{router: routerReducer}`, i think i saw an example from the 2.x version of router-store that had that.

**Comment by brandonroberts** [comment]
That's the default. There is a feature in master that lets you configure the key https://github.com/ngrx/platform/pull/417

**Comment by juanlizarazo** [comment]
I run into this as well. Until that feature is released, you can either use the default routerReducer or the nightly build:

`npm install github:ngrx/router-store-builds` OR `yarn add github:ngrx/router-store-builds`
Then 
`StoreRouterConnectingModule.forRoot( { stateKey: "router" })`

**Comment by mogusbi** [comment]
Does time travel work at all? I've tried implementing it on my own app and gave the example app on the repo a go and I couldn't get it to work at all

**Comment by fredgate** [comment]
Time travel debugging does not work when module is imported using forRoot method passing an option object.
I created a issue #573 for that. You can see it for more details and to have a workaround. I also prepare a pull request to fix this bug.

**Comment by brandonroberts** [comment]
Closed via #575
