### ISSUE TITLE
ngrx/router-store crashes Chrome Redux DevTools Extension

### ISSUE THREAD

**Issue by jongunter** [ngrx/platform#537]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
1. Open Redux DevTools
2. Dispatch some non-router action. Everything works normally.
3. Navigate to a route by clicking a [routerLink]
4. Redux DevTools compleley freezes and stops working. ngrx is still working and there are no error messages printed in the console.

## Expected behavior:
Redux DexTools should not freeze

## Minimal reproduction of the problem with instructions:
See above for repro steps.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
Chrome Version 62.0.3202.75 (Official Build) (64-bit)
ngrx/router-store 4.1.0
ngrx/store 4.0.3
Angular 4.2.4

**Comment by jongunter** [comment]
Ooops...didn't notice that section...thanks.

**Comment by nijat12** [comment]
I implemented the serializer but still DevTool Crashes.

Angular: 6.1.10
ngrx/store: 6.1.0
ngrx/router-store: 6.1.0
Chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by msorens** [comment]
Update: The URL mentioned by @aitboudad is now at https://github.com/ngrx/platform/blob/master/projects/ngrx.io/content/guide/router-store/configuration.md#custom-router-state-serializer
