### ISSUE TITLE
Spying on selectors to fake store-relations in effects fails

### ISSUE THREAD

**Issue by TekSiDoT** [ngrx/platform#539]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
Spying on selectors to fake store-relations during testing of store-dependent effects causes `Error: <spyOn> : getRecordingState is not declared writable or has no setter`

## Expected behavior:
This bug is a direct result from upgrading to latest versions of several dependencies:
Angular 4.4.5 -> 5.0.0 final
Angular/cli -> 1.4.8
Typescript 2.4.0 -> 2.6.1
Ngrx 4.0.3 -> 4.1.0

## Minimal reproduction of the problem with instructions:
Current plunkr does not provide the latest environments to reproduce.

## Other information:

Example code:

In .spec: 
```
        spyOn(StoreFunctions, 'getRecordingState').and.callFake(function () {
            const state: IRecordingState = {
                ...initialRecordingState,
                configSetState: 'pending'
            };
            return state;
        });
```

selector creation:
```
       export interface IAppState {
           recording: fromRecordingState.IRecordingState;
       };

       export const initialAppState: IAppState = {
           recording: fromRecordingState.initialRecordingState,
       };

       export const AppReducer: ActionReducerMap<IAppState> = {
           recording: fromRecordingReducer.reducer,
       };

        export const getRecording = (state: IAppState) => state.recording;
        export const getRecordingState: any = createSelector(getRecording, (state: fromRecordingState.IRecordingState) => state);
```

**Comment by brandonroberts** [comment]
This doesn't seem like a bug in Store. Provide a reproduction of the issue

**Comment by ryanquinn3** [comment]
@TekSiDoT I use the following code to solve this problem.

```ts
export function ensureObjectIsMockable<T extends Object, K extends keyof T>(target: T, property: K) {
  Object.defineProperty(target, property, { writable: true, value: target[property] });
}
```

so in your case
```ts
ensureObjectIsMockable(StoreFunctions, 'getRecordingState');
//your specs

**Comment by TekSiDoT** [comment]
@ryanquinn3 that works wonderfully, do you have any indication what changed the previous behavior?

**Comment by ryanquinn3** [comment]
I'm not actually sure. I have been using reselect for my selectors for some time and couldn't write tests without that hack. I'm pretty sure ngrx has a very similar implementation.
