### ISSUE TITLE
Feature Modules Fractal State & Preloading Modules

### ISSUE THREAD

**Issue by Kaffiend** [ngrx/platform#54]
Just curious and I'm still trying some things out for how i want to structure my state, I plan to have a few Large Modules comprised of several smaller modules within each and I'm wanting to introduce feature state and reducers lazily, and some eager modules with root state. Does changing the angular preloading strategy for instance to `PreloadAllModules` effect state composition when using the `forFeature` module loading of state?

**Comment by brandonroberts** [comment]
Yes it does. If your feature module is preloaded, it's feature   state will be loaded along with it. If you want more control over loading state you can inject the `ReducerManager` which has methods to add/remove reducers.
