### ISSUE TITLE
ActionReducerMap incorrect type with Typescript 2.6+ with option``--strictFunctionTypes`` 

### ISSUE THREAD

**Issue by kilian-ito** [ngrx/platform#540]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
The type `ActionReducerMap` considers that `V extends Action` is the same for every `T` types in the the action reducer map.

## Expected behavior:
`V` types should be independent. ActionReducerMap should have the following prototype :
```typescript
export declare type ActionReducerMap<T, V extends Action = Action> = {
    [p in keyof T]: ActionReducer<T[p], V[p]>;
};
```

## Minimal reproduction of the problem with instructions:
```typescript
class Action1 extends Action {
  public fieldA1: string;
}

class Action2 extends Action {
  public fieldA2: number;
}

function reducer1(state: State, action: Action1) {
  ...
}

function reducer2(state: State, action: Action2) {
  ...
}

combineReducers({reducer1, reducer2});  // <-- Error:  is not assignable to parameter of type ...

```

## Version of affected browser(s),operating system(s), npm, node and ngrx:
Typescript 2.6+ with option``--strictFunctionTypes``
NodeJs 6.10.x+
NgRx 4.1.0

**Comment by sfabriece** [comment]
@kilian-ito did you find out why this is problem? I'm facing a similar challenge.
