### ISSUE TITLE
Question: ngrx entity support for single object state

### ISSUE THREAD

**Issue by jbeckton** [ngrx/platform#542]
Looking at ngrx entity for the first time and want to add it to my project but it seems like it is built around collections being stored in the store. I have a layout state that is basically a single object and each property defines something in my apps layout state, like whether the side bar is open or closed. 

Does anyone have some examples of ngrx entity being used in this way?

**Comment by brandonroberts** [comment]
You don't need entity in that scenario. You would use a reducer to manage the layout state.
