### ISSUE TITLE
Best project structure for normalized model and related entities

### ISSUE THREAD

**Issue by aboglioli** [ngrx/platform#545]
It would be awesome to have more relations between entities in the `example-app`.

I follow the project structure shown in `example-app` but I'm having troubles for a big app with multiple relations between entities.

*book* and *collection* are in `app/books` folder. But, what would be the best solution for *product*, *productType* and *order*? (for example)

Should each one have its own folder with *containers*, *components*, *actions*, *reduces*, etc? How could I relate entities with `createSelector` or `combineLatest` from rxjs/Observable if they are in separated folders?

Considering that each one will have a page (container) and components for editing data.

**Comment by brandonroberts** [comment]
Support questions should be on stackoverflow or the support channel at https://gitter.im/ngrx/platform
