### ISSUE TITLE
Add an example usage of @ngrx/entity to example-app

### ISSUE THREAD

**Issue by changalberto** [ngrx/platform#547]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[x] Documentation issue or request
</code></pre>

Can you guys add an example of @ngrx/entity usage into the example-app to demo best practice?

Thanks!

**Comment by tja4472** [comment]
Have you seen?
https://github.com/ngrx/platform/blob/master/example-app/app/books/reducers/books.ts
```typescript
import { createSelector } from '@ngrx/store';
import { createEntityAdapter, EntityAdapter, EntityState } from '@ngrx/entity';
import { Book } from '../models/book';
import * as book from '../actions/book';
import * as collection from '../actions/collection';

/**
 * @ngrx/entity provides a predefined interface for handling
 * a structured dictionary of records. This interface
 * includes an array of ids, and a dictionary of the provided
 * model type by id. This interface is extended to include
 * any additional interface properties.
 */
export interface State extends EntityState<Book> {
  selectedBookId: string | null;
}
```

**Comment by changalberto** [comment]
@tja4472 Don't know how I missed that...  I must've been blind... Thanks for pointing that out!
