### ISSUE TITLE
[Support] TypeError: Cannot read property of undefined when read data from store

### ISSUE THREAD

**Issue by ngohungphuc** [ngrx/platform#548]
I get error when trying to access data from the store. Here is my code

index.ts
```
export interface AuthState {
  errorMsg: string;
  loggedIn: boolean;
}

const selectAuthModule = createFeatureSelector<AuthState>('authModule');

export const selectAuthStatusState = createSelector(
    selectAuthModule,
    (state: AuthState) => state.loggedIn
);

```
reducer
```
export const initialState: AuthState = {
  loggedIn: false,
  errorMsg: null
};

export function authReducer(state = initialState, action: BaseAction) {
  switch (action.type) {
    case LOGIN:
      return {
        ...state,
        user: action.payload
      };
    case LOGIN_SUCCESS:
      return {
        ...state,
        loggedIn: true,
        tokenInfo: action.payload,
      };
    case TOKEN_EXPIRE:
      return {
        ...state,
        tokenInfo: action.payload,
      };
    case LOGIN_FAIL:
      return {
        ...state,
        errorMsg: action.payload,
      };
    default:
      return state;
  }
}

export const getLoginState = (state: AuthState) => state.loggedIn;
```

I get the error TypeError: Cannot read property 'loggedIn' of undefined
 when the code run to this.store.select in AuthGuard and the error is in this line 
(state: AuthState) => state.loggedIn of index.ts

```
export class AuthGuard implements CanActivate {
  constructor(private store: Store<fromAuth.AuthState>) {
  }

  canActivate(): Observable<boolean> {
    return this.store
      .select(fromAuth.selectAuthStatusState)
      .map(authed => {
        if (!authed) {
          this.store.dispatch(new Auth.Redirect());
          return false;
        }
        return true;
      })
      .take(1);
  }
}

```

The following code can be found [at here](https://github.com/ngohungphuc/online-training/blob/master/OnlineTraining/OnlineTraining.FE/src/app/account/store/index.ts)

**Comment by jotatoledo** [comment]
Dont use the issue tracker for support questions. Ask for help in SO or gitter

**Comment by brandonroberts** [comment]
The gitter channel is https://gitter.im/ngrx/platform

**Comment by vegeta03** [comment]
Hi @ngohungphuc ,
did you find the solution the above problem, i am facing similar issue.

Thanks

**Comment by ngohungphuc** [comment]
@vegeta03 you can check my code in https://github.com/ngohungphuc/online-training/blob/master/OnlineTraining/OnlineTraining.FE/src/app/account/store/index.ts

**Comment by vegeta03** [comment]
@ngohungphuc thank you.

**Comment by FabianGosebrink** [comment]
What was the solution then? I am facing the same issue right now. Having a store in a feature module works as expected. Having it in the app module (`forRoot(...)`) is giving me the error `Cannot read property of undefined`

**Comment by ngohungphuc** [comment]
@FabianGosebrink read my index.ts file in the link above basically i have to create feature selector then 
createselector then wrap createfeatureselector inside of createselector
```
export const selectAuthState = createFeatureSelector<AuthState>('authModule');

export const selectAuthStatusState = createSelector(
  selectAuthState,
  fromAuth.getLoginState
);
```

**Comment by FabianGosebrink** [comment]
I think the difference is that you are in a feature state as I am trying to get selectors working on the root state. Am I right?

**Comment by kstack-au** [comment]
> I think the difference is that you are in a feature state as I am trying to get selectors working on the root state. Am I right?
> 
> Got it working now but I don't know if this is correct. However, it works now. I am not using a `createFeatureSelector(...)` now to get a piece of the top-level-state.

what did you do to get this to work for root state?

**Comment by binarybotany** [comment]
```ts
// something.selector.ts 
const somethingFeatureKey = 'something'; // Should match with what you pass to .forRoot 

const selectSomething = createFeatureSelector<SomethingState>(somethingFeatureKey);

app.module.ts
// ... 
StoreModule.forRoot({ 
  something: /* <-- makes sure this matches with the feature key above, also casing */ somethingReducer,
}).
```
