### ISSUE TITLE
Angular 5 - StaticInjectorError[ActionsSubject]: Function/Class not supported

### ISSUE THREAD

**Issue by pierre-hilt** [ngrx/platform#549]
## I'm submitting a...

<pre><code>
[ x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

I am injecting StoreModule.forRoot(reducers, {metaReducers}).providers into platform providers.

```
let providers: StaticProvider = StoreModule.forRoot(reducers, {metaReducers}).providers;
providers = providers.concat(StoreDevtoolsModule.instrument().providers);

platformBrowserDynamic(providers).bootstrapModule(AppDemoModule);
```

After migration to angular 5, I have an error in the console:
StaticInjectorError[ActionsSubject]: Function/Class not supported

## Expected behavior:

Application should start without error.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
@ngrx 4.1.0
@angular 5.0.0

**Comment by MattiJarvinen-BA** [comment]
As listed on [Angular 5 changelog](https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes)
> platformXXXX() no longer accepts providers which depend on reflection. Specifically the method signature went from Provider[] to StaticProvider[].
>
> Example: Before:
> ```typescript
> [
>  MyClass,
>  {provide: ClassA, useClass: SubClassA}
> ]
> ```
> After:
> ```typescript
> [
>   {provide: MyClass, deps: [Dep1,...]},
>   {provide: ClassA, useClass: SubClassA, deps: [Dep1,...]}
> ]
> ```
> NOTE: This only applies to platform creation and providers for the JIT compiler. It does not apply to @Component or @NgModule provides declarations.
> 
> Benchpress note: Previously Benchpress also supported reflective provides, which now require static providers.

Reply if this change fixes it.

**Comment by voznik** [comment]
hello
I have similar error after upgrate from 4.3.2 to 5.0.0 & ngrx@4.1.0
```
Unhandled Promise rejection: StaticInjectorError[Store]: 
  StaticInjectorError[Store]: 
    NullInjectorError: No provider for Store! ; Zone: <root> ; Task: Promise.then ; Value: Error: StaticInjectorError[Store]: 
```
how can I debug this error? where to look? :confused:

**Comment by MattiJarvinen-BA** [comment]
@voznik why you don't set Store as a constructor parameter and use Injector?

There was something about decorators and dynamic functions when I tried to run unit:tests with Angular5 against ngrx monorepo, (basicly dependency hell ensued, codelyzer, zonejs, rxjs, typescript had to be upgraded thus breaking tests since jasmine had to be upgraded....) and then run out of time to use for that.

Try this if you just need to get it working.
```typescript
import * as fromRoot from '../reducers';
export class BookExistsGuard implements CanActivate {
  constructor(
    private store: Store<fromRoot.State>,
    private service: BookService,
    private router: Router
  ) { }
// ....
}
```

**Comment by pierre-hilt** [comment]
OK I think I found the problem.

in [StoreModule providers](https://github.com/ngrx/platform/blob/2afb792060f496262b77ec64ea39088bef2c409e/modules/store/src/store_module.ts#L136) you add [ACTIONS_SUBJECT_PROVIDERS](https://github.com/ngrx/platform/blob/1bbd5bfa1e646eb42a34e8c9d1904f15f9173ed6/modules/store/src/actions_subject.ts#L35). But this provider is not following StaticProvider syntax.

This should be:

```
export const ACTIONS_SUBJECT_PROVIDERS: Provider[] = [{provide:ActionsSubject, deps:[]}];
```

Am I guessing right?

**Comment by MattiJarvinen-BA** [comment]
If only I had time to look into #553 with Angular 5.

**Comment by Reboog711** [comment]
In case this helps someone:

I was experiencing a similar error on a project that was not using the Angular CLI.  I believe the problem went away when I upgraded the version of TypeScript to 2.4.0, as is documented in the Angular 5 release notes.

**Comment by jjorbas** [comment]
In my experience,

I had the same problem with a service, and I noted that I forgot to declare 

providers: [ ServiceName ]

in the @component section of the ts file

**Comment by maksimbykov** [comment]
If you passing some custom class instance into component constructor it may produce the same problem.  It is because of DI, rather you can declare a property in the component class. At least I had that problem.

**Comment by lakhanpujeri** [comment]
![myerror](https://user-images.githubusercontent.com/36784919/36887770-b1c7ed8c-1e18-11e8-86d7-78cc478a0a0b.PNG)
Can any one help me please

**Comment by gilbertmpanga12** [comment]
@lakhanpujeri instead of injecting your service in constructor ,use a property instead thanks @maksimbykov

**Comment by straiforos** [comment]
Hello All,
I ran into this error: ```Error: StaticInjectorError(DynamicTestModule)[FiltersComponent -> Store]: 
  StaticInjectorError(Platform: core)[FiltersComponent -> Store]: 
    NullInjectorError: No provider for Store!```
I Imported the following: 
import { Store } from '@ngrx/store';
import { StoreModule } from '@ngrx/store';

I added the store module in imports as : ``` imports: [StoreModule.forRoot({}),............```
I added the store service to the providers : providers: [Store].

I have not seen this error when I add this and it works as expected as far as I can tell. Hope this helps!

**Comment by spraju92** [comment]
@straiforos  Which file you are imported above things?

**Comment by MehdiRahimiN** [comment]
> @lakhanpujeri instead of injecting your service in constructor ,use a property instead thanks @maksimbykov

It solves my problem but when i use property , returns undefined why? :|
