### ISSUE TITLE
Must npm install twice in order to install @ngrx/store-devtools

### ISSUE THREAD

**Issue by chrisekelley** [ngrx/platform#55]
We are having issues with package versions of `@ngrx/store and @ngrx/store-devtools`.

Here are our current versions from package.json:

````
    "@ngrx/core": "^1.2.0",
    "@ngrx/store": "^2.2.2",
    "@ngrx/store-devtools": "^3.2.4",
````

When we do an `npm install` on our code, @ngrx/store-devtools does not get installed.
When we do a second `npm install` it is installed.

I'm currently on npm 5.0.3 (node v6.9.4, via brew). It does not provide any error messages about this issue; however, earlier today, when I was on npm 3.10.10, I got the following message after npm install:

````
├── @ngrx/store-devtools@3.2.4
├─┬ ngrx@2.0.1
│ └─┬ fs-extra@0.30.0
│   └── klaw@1.3.1


npm WARN @ngrx/store-devtools@3.2.4 requires a peer of @ngrx/store@^2.0.0 but none was installed.

````

Can you please recommend any fixed versions of @ngrx/core, store, and store-devtools or other work-arounds?

**Comment by bfricka** [comment]
This `ngrx` package is really weird. On `postinstall` it clears out the `node_modules/@ngrx` directory and replaces its contents with its own bundled modules. I haven't read through the code yet, but I'm going to glance at it to make sure it's not malware.

Either way, get rid of that package.

**Comment by t-p-l-k** [comment]
@chrisekelley @bfricka https://www.npmjs.com/package/ngrx seems quite sketchy and the publisher has lots of similar packages like `ng2release` and `ts-types`. Maybe he just publishes them for himself to keep dependency list small, idk.

**Comment by rjsteinert** [comment]
@t-p-l-k @bfricka Wow! Thanks guys. So... ?
![screen shot 2017-07-05 at 6 57 20 pm](https://user-images.githubusercontent.com/156575/27888508-587e4b2a-61b4-11e7-91a6-15a4da7cd3d9.png)

**Comment by bfricka** [comment]
I reported the offending package to npm, since it probably violates their terms for being a duplicate hosted or spam package. Not sure what else to do, unfortunately

**Comment by t-p-l-k** [comment]
@bfricka check out other packages published by kpaxian ([link](https://www.npmjs.com/~kpaxian)). There're a lot more like this one. Not sure if it's against policy.
@k-paxian, can you clarify, please?

**Comment by k-paxian** [comment]
Lots of my packages are done specific for my organisation. Main purpose is to overcome "Artifactory encoded slash" issue specific to scoped dependencies only. Which is resolved as of now but im not able to delete those packages its against the rules, noone is able to completely delete a npm package those days. Sorry guys for you to trap on this stuff.

**Comment by bfricka** [comment]
@k-paxian Thanks for the response. Perhaps your org should look at something like [veradaccio](https://github.com/verdaccio/verdaccio) to solve these sorts of problems? Anyways, OP, I think the issue is solved and this can be closed.

**Comment by k-paxian** [comment]
@bfricka perhaps, npm shouldnt create the scoped packages slashing ussue first? Your proposal is suitable for org with few coworkers. And with all that orgs having thousands of employys and tons of burocracy its just not feaseble at all.

**Comment by chrisekelley** [comment]
@bfricka @t-p-l-k @k-paxian Thanks a lot for your help! We removed the ngrx package from package.json (and package-lock.json), committed, ran 'git clean -xfd' to ensure all was clean, and npm install did what was expected - @ngrx/store-devtools were successfully installed.

**Comment by rjsteinert** [comment]
> Sorry guys for you to trap on this stuff.

@k-paxian No worries man! I hope NPM can help the community out with this and unpublish those packages. Then perhaps NGRX could publish a package under that name and all it would do is warn "THIS IS NOT THE NGRX PACKAGE, USE @ngrx/..."
