### ISSUE TITLE
App based on Example app fails to compile after upgrade to Ng5/Cli1.5

### ISSUE THREAD

**Issue by heinschulie** [ngrx/platform#552]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

Firstly - thanks to the whole team for the NGRX project. It's incredible work. I have a project built on top of the Example App template that has been running smoothly in both Jit and Aot modes up until I upgraded to Ng5 and Cli1.5 (I was previously on Ng4 and the prior version of the Cli). I now get this error when trying to build/serve in either mode:

`Error: Error: /Users/iodigital/Documents/Code/propertyselector/modules/store/src/store_module.ts:89:1: Error encountered in metadata generated for exported symbol 'StoreModule': 
 /Users/iodigital/Documents/Code/propertyselector/modules/store/src/store_module.ts:214:32: Metadata collected contains an error that will be reported at runtime: Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function.`

I'm not sure if there is something obvious I am doing or not doing, but I thought I would post my issue here as there are probably a bunch of people using the Example app as a template and busy transitioning to the newer versions of framework and cli. 

## Expected behavior:

For the app to compile and build. 

## Minimal reproduction of the problem with instructions:
In an attempt to reproduce the issue for reference here I cloned the Example App again and tried to build it without any modification, encountering a different error to the one above! I don't want to confuse the issue here but I will paste that error below in the "other info" section. 

The error above references code in the store module - which I necessarily left untouched - so I am left a little stumped. 

I realize this is all a little muddled so I am happy to try help or provide more context, but that is the scenario as I am experiencing it. 

## Version of affected browser(s),operating system(s), npm, node and ngrx:
*, macOS Sierria 10.12.6, npm 5.5.1,  node v9, all latest versions of store, effects, router-store, store-devtools and entity. 

## Other information:

Error when building freshly downloaded Example app... 

`Error: Command failed: "/Users/iodigital/Documents/Code/ngrx-example/node_modules/.bin/ngc" -p ./modules/codegen/tsconfig-build.json
Error at /Users/iodigital/Documents/Code/ngrx-example/modules/codegen/src/metadata/get-properties.ts:6:3: Type 'TypeElement[]' is not assignable to type 'PropertySignature[]'.
  Type 'TypeElement' is not assignable to type 'PropertySignature'.
    Types of property 'kind' are incompatible.
      Type 'SyntaxKind' is not assignable to type 'SyntaxKind.PropertySignature | SyntaxKind.JSDocRecordMember'.
Error at /Users/iodigital/Documents/Code/ngrx-example/modules/codegen/src/collect-metadata.ts:23:38: Argument of type 'Statement' is not assignable to parameter of type 'InterfaceDeclaration'.
  Types of property 'kind' are incompatible.
    Type 'SyntaxKind' is not assignable to type 'SyntaxKind.InterfaceDeclaration'.`

**Comment by MattiJarvinen-BA** [comment]
Related to decorator https://github.com/angular/angular/issues/19698#issuecomment-338340211

Using an temporary const in store_module helped to overcome that when I tried to run unit tests, you could check tsconfig.json has `angularCompilerOptions.strictMetadataEmit=false`
