### ISSUE TITLE
No exported member 'OpaqueToken'

### ISSUE THREAD

**Issue by cyberbeast** [ngrx/platform#554]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
Getting an error as follows:
```
ERROR in node_modules/@ngrx/store/src/ng2.d.ts(1,10): error TS2305: Module '"/Users/../../../node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.
```

I upgraded angular4.4.6 to 5.0.0rc and ngrx from 2.4.* to 4.* and have been experiencing this error since.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
```

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.5.0
Node: 7.7.1
OS: darwin x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cdk: 2.0.0-beta.12
@angular/cli: 1.5.0
@angular/flex-layout: 2.0.0-beta.10-4905443
@angular/material: 2.0.0-beta.12
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.2
typescript: 2.6.1
webpack: 3.8.1
```

**Comment by cyberbeast** [comment]
There is another issue which solves this that was closed 22 hours ago. Discussions on that issue helped me fix the error I was having and so I am closing this issue.

**Comment by tiagomms** [comment]
@cyberbeast i am having the some problem. Can you redirect to the issue which solved this problem?

**Comment by gbrigens** [comment]
I am getting the same problem too where is the link to the fix?

**Comment by whooguyy** [comment]
From what I have seen, it is a library issue. When I upgraded from 4 to 5, I had to update a few/most of my libraries and these errors went away.

**Comment by Dhaneshmonds** [comment]
I am Getting the same error when I moved to angular 5.

**Comment by thoughtpalette** [comment]
A link to the discussion would've been amazing here @cyberbeast

**Comment by cyberbeast** [comment]
My issue was mainly due to errors in not following the migration guide in the documentation on the ngrx/platform git repo. The migration guide is very thorough about how to go about solving the issues. I am afraid the inline link to the specific issue number did not work while I typed my concluding thoughts on this issue. I apologize for that. You can find the migration guide [here](https://github.com/ngrx/platform/blob/master/MIGRATION.md)
