### ISSUE TITLE
Store.select -> Reducing function ->opened Subscriber

### ISSUE THREAD

**Issue by AntoniBertel** [ngrx/platform#557]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
<code>
this.store.select(getCountriesStatus).filter(n => false).take(1).subscribe(n => console.log );
</code></br>
returns opened Subscriber</br>
by the way </br>
<code>
Observable.of(1).filter(n => false).take(1).subscribe(n => console.log(n) );
</code></br>
or</br>
<code>
Subject.of(1).filter(n => false).take(1).subscribe(n => console.log(n))
</code>

returns closed Subscriber 

## Expected behavior:
<code>
this.store.select(getCountriesStatus).filter(n => false).take(1).subscribe(n => console.log );
</code>
returns closed Subscriber 

## Version of affected browser(s),operating system(s), npm, node and ngrx:
-    "@ngrx/core": "^1.2.0",
-   "@ngrx/effects": "^2.0.2",
-   "@ngrx/router-store": "^1.2.5",
-   "@ngrx/store": "^2.2.1"

**Comment by brandonroberts** [comment]
This repository is for ngrx 4.x, which is the latest version actively being maintained.

**Comment by AntoniBertel** [comment]
Summary:

It's OK, just keep in mind that take(1) will not close your stream (infinite or not) in cases such this.
