### ISSUE TITLE
Add documentation for Effect with state dependency

### ISSUE THREAD

**Issue by MattiJarvinen-BA** [ngrx/platform#560]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## What is the current behavior?

Currently Effect documentation doesn't contain example for handling state dependent effects. Since I'm not really sure where this should even be put in 4.X documentation I just leave it here.

## Expected behavior:

Adding this example would have value
```ts
...
import 'rxjs/add/operator/withLatestFrom';
...
class SomeEffects {
@Effect() refreshResultsWhenInBrowseMode$ = this.actions$
    .ofType(SearchActions.CHANGE_MODE, SearchActions.CLEAR_SEARCH)
    .withLatestFrom(this.state$)
    .filter(([action, state]) => state.search.mode === SearchMode.BROWSE)
    .map(([action, state]) => state.search.query)
    .map(query => this.searchActions.search(query));

constructor(private actions$: Actions,
            private state$: Store<AppState>) { }
}
```
Quoted from https://github.com/ngrx/effects/issues/49#issuecomment-248994416

**Comment by timdeschryver** [comment]
Closing this in favor of https://github.com/ngrx/platform/issues/1383.
