### ISSUE TITLE
this.debounce in example app's book effects is undefined

### ISSUE THREAD

**Issue by ericwang1120** [ngrx/platform#563]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

this.debounce in example app is not working

## Expected behavior:

this.debounce in example app should work

## Minimal reproduction of the problem with instructions:

1. Open 'browse books' page in example app
2. In chrome, press F12 to see the network, keep typing in words quicklly in the 'Find a Book' input. Request will be sent on every click although the debounce time is set to be 300.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
Chrome 62
Win7
ngrx4

## Other information:
Can be fix. In books/effects/book.ts, line 41
```
.debounceTime(this.debounce ? this.debounce : 300, this.scheduler || async)
```

**Comment by brandonroberts** [comment]
Closed via #576
