### ISSUE TITLE
filter is not a function after upgrading to angular 5

### ISSUE THREAD

**Issue by anakinjay** [ngrx/platform#564]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

attempting to filter on this.actions$ results in the following error:
 **this.actions$.filter is not a function** 

## Expected behavior:

action$.filter should be available to use in the effect

## Minimal reproduction of the problem with instructions:

```javascript
import { Effect, Actions, toPayload } from '@ngrx/effects';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { Store, Action } from '@ngrx/store';

@Injectable()
export class PromiseEffects {
  actionType;

  @Effect()
  promise$: Observable<Action> = this.actions$
   .filter(a => {
      const b = Object(a);
      if (b.payload) {
        return b.payload.constructor.name === 'ZoneAwarePromise';
      } else {
        return false;
      }
    })
    .map(x => {
      const y = Object(x);

      this.actionType = x.type;
      y.payload.then(this.handleFulfill, this.handleReject);

      return { type: this.actionType + '_PENDING' };
    });


  constructor(private actions$: Actions, private store$: Store<any>) { }

  handleReject = reason => {
    this.store$.dispatch({
      type: this.actionType + '_REJECTED',
      payload: reason
    });
  }

  handleFulfill = successValue => {
    this.store$.dispatch({
      type: this.actionType + '_FULFILLED',
      payload: successValue.data
    });
  }
}
```

## Version of affected browser(s),operating system(s), npm, node and ngrx:
node 8.1.3
npm 5.5.1
ngrx 4.1.1

## Other information:
This effect scans the payload of all actions for a promise, and if found hooks in pending, rejected, or fulfilled action dispatches.  It has worked wonderfully for dozens of projects, but after upgrading to angular 5 it has stopped working.

Seems like filter is no longer accessible from the Actions object type but I can't seem to figure out why or what would cause that.

Not sure if related, but I also upgrade NGRX from 4.0.2 to 4.1.1 at the same time.

**Comment by anakinjay** [comment]
Here's some more info:
Previously with Angular 4:
![gitbookviewerng](https://user-images.githubusercontent.com/1062577/32790284-06dfc8c2-c92c-11e7-8d27-1b2e576da108.jpg)

you can see filter is defined.

After upgrading to Angular 5:
![ng_widget_starter](https://user-images.githubusercontent.com/1062577/32790298-11eb863e-c92c-11e7-9903-9b3c96ebb263.jpg)

filter is now undefined.

**Comment by brandonroberts** [comment]
This is not a bug in ngrx. We don't patch any operators on the Observable prototype to prevent side events, so you must explicitly add your own operators that you use. More than likely, the Observable was being patched from somewhere else.

**Comment by anakinjay** [comment]
ok, sorry about that then, thank you!

**Comment by anakinjay** [comment]
In case anyone stumbles across this in the future, I had to add the functions to the NGRX Effects Actions prototype to get it to work:

import { filter } from 'rxjs/operator/filter';
import { map } from 'rxjs/operator/map';
Object.assign(Actions.prototype, {  map, filter });


That solves the issue.

**Comment by brandonroberts** [comment]
I would not recommend doing this. If you're using RxJS 5.5 or greater, you should use the new `pipe` syntax.

```ts
import { filter } from 'rxjs/operators';

  this.actions.pipe(filter(() => boolean));
```

Otherwise, you need to import the operators

```ts
import 'rxjs/add/operator/filter';
```

**Comment by anakinjay** [comment]
thank you so much @brandonroberts !  using pipe works perfectly and feels a lot safer.  Thanks again!!

**Comment by madhundle** [comment]
I am now getting this error with NgRx 17.2.0 and Angular 17.3.0.  The above solutions did not work. Does anyone have recent solutions?

`this.store.map is not a function`

`  this.isLoading$ = this.store.map(state => state.ui.isLoading);`

**Comment by rainerhahnekamp** [comment]
@madhundle `map,` and `filter` might have been available in the year 2017, but even then, it was not recommended anymore. 

It looks like you are using the wrong method. Should be `select` instead: 

```
this.isLoading$ = this.store.select(state => state.ui.isLoading);
```

From which version did you upgrade?
