### ISSUE TITLE
can not load lazy load module with canLoad() return store state prop.

### ISSUE THREAD

**Issue by sandangel** [ngrx/platform#565]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

I'm trying to guard a lazy module with canLoad depending on user have logged in or not.
```ts
@Injectable()
export class AuthGuard implements CanActivate, CanActivateChild, CanLoad {
  canLoad(route: Route): boolean | Observable<boolean> | Promise<boolean> {
    return this.store.select(selectIsAuthenticated).pipe(
       tap(isAuthenticated => {
         console.log(isAuthenticated);
       })
    );
  constructor(private store: Store<AppState>) {}
}
```
Although isAuthenticated is true, app still can not be able to load the lazy module. 
After click a link which will navigate to lazy load module, all other routes become unreachable too.
There is no error log in the browser console.

Note: After change to canActivate, it work as expected.

## Expected behavior:

Can load lazy module when isAuthenticated is true.

## Minimal reproduction of the problem with instructions:

https://angular-pu2u2j.stackblitz.io/hello

Navigate to Home, and Hello, there is no problem. Click con lazy, console will log false.
Then navigate to Home, click on Login button, console will log '12345' ( example auth token ),
and isAuthenticated turn to true.
Then click on Lazy again. console will log true, but Lazy component not show up.
Then click on Home, Home will be unreachable too.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
ngrx all 4.1.1

angular all 5.0.1
typescript 2.6.1
node 9.2.0, 8.9.2; npm 5.5.1
chrome 62, firefox 47
ubuntu 16.04

**Comment by brandonroberts** [comment]
This is not a bug in ngrx. All the Angular Router guards must resolve a boolean value. If providing an Observable, it must complete in order for the guard to continue.

```ts
@Injectable()
export class AuthGuard implements CanLoad {
  canLoad(): boolean | Observable<boolean> {
    return this.store.select(selectIsAuthenticated).pipe(tap(isAuth => {
      console.log(isAuth)
      return isAuth;
    }), take(1))
  }

  constructor(private store: Store<AppState>) {}
}
```

**Comment by sandangel** [comment]
@brandonroberts my silly mistake, sorry for that.
