### ISSUE TITLE
Automating selector creation?

### ISSUE THREAD

**Issue by hudibrian** [ngrx/platform#566]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

(If there is a way to automate the creating of selectors and I just couldn't find it in my searches then please just say so!)

Currently there is no way that I can find to automate the creation of selectors so that the user doesn't have to go and manually create selectors for the properties of his or her state.  When creating selectors there is a fairly common pattern being followed, and I believe it could be mostly removed from being a manual process given a little bit of effort.  This would then decrease *some* of the boilerplate code complaints I have seen floating around this library.

If there is some reason why it is not possible, or there is an argument as to why not to do it please let me know.  Otherwise, I would be happy to looking in to implementing and creating a pull request at some point in my spare time if it is something that could be helpful?

**Comment by deftomat** [comment]
@hudibrian Do you have any examples of these _common_ selectors? 

Examples could quite help as we probably don't know what do you exactly mean.

For example, a lot of selectors in our apps are quite different. The only selectors with a common pattern are specific to our app or are just a very simple functions like `(state) => state.users`.

Also, there is no reducers factory, so I'm not sure how to automatically create a selectors for them.

Feel free to describe your idea a little bit more 😉

**Comment by brandonroberts** [comment]
Selectors are easy enough to create using generators without expanding the API. Using `@ngrx/entity` provides a set of common selectors for entity collections.
