### ISSUE TITLE
release() method of MemoizedSelector not being called

### ISSUE THREAD

**Issue by swseverance** [ngrx/platform#569]
The function returned by `createSelector()` appears to have a `release()` method. The method is called explicitly in the selector.spec.ts unit tests. However, outside of the unit tests I cannot find anywhere in the source code where `release()` is actually being invoked. Am I mistaken? What is the motivation behind the method? Thanks

https://github.com/ngrx/platform/blob/2f6a0357bdfff60d2bc5c558563538d68aeb61e0/modules/store/src/selector.ts#L211

**Comment by brandonroberts** [comment]
Selectors are memoized by default. The `release` method allows you to reset a memoized selector if its a large dataset you no longer want to keep in memory. It just needs documentation to be added.
