### ISSUE TITLE
example-app's router state not updated to reflect proper URL after redirects

### ISSUE THREAD

**Issue by gssjr** [ngrx/platform#572]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

If I enter a URL that will cause a redirect, the routerReducer.state reflects the entered URL and does not get updated to the URL to which I was redirected.

## Expected behavior:

The routerReducer state reflects the actual URL in the browser.

## Minimal reproduction of the problem with instructions:

1) Fresh start, logged out
2) Navigate to /books/find (routerReducer.state.url is "/books/find"
3) [Auth] Login Redirect
4) routerReducer.state.url is still "/books/find"

## Version of affected browser(s),operating system(s), npm, node and ngrx:
latest

**Comment by PachowStudios** [comment]
Also having this issue. This basically prevents us from using route guards that can redirect.

**Comment by brandonroberts** [comment]
I don't think this is a bug. The `[Auth] Login Redirect` action does alter the `routerReducer.state.url`, it only triggers the effect to start the navigation. The `/login` url is reflected in the `ROUTER_NAVIGATION` action dispatched after.
