### ISSUE TITLE
StoreRouterConnectingModule.forRoot does not support config object

### ISSUE THREAD

**Issue by fredgate** [ngrx/platform#573]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
When I add StoreRouterConnectingModule of ngrx/router-store in my module using forRoot method instead of direct type, the options passed to the function as an object are ignored. If I pass the options as a function factory, the options are used correctly.
The interest of using the forRoot method instead of the class directly, is to change the name of the router state in the store. But actually it does not work, and so the time travel debugging in developper tools does not change URL and components are not replaced in the router outlet.

## Expected behavior:
The state key passed in the config options should be used, so the time travel debugging should work in developer tools.

## Minimal reproduction of the problem with instructions:

```
import * as fromRouter from '@ngrx/router-store';
export const reducers = {
    routes: fromRouter.routerReducer,
    ...
};
```
```
@NgModule({
  ...
  imports: [
    ...
    StoreRouterConnectingModule.forRoot({stateKey: 'routes'})    // KO
    StoreRouterConnectingModule.forRoot(() => <StoreRouterConfig>{stateKey: 'routes'})    // OK
  ]
  ...
})
```

## Version of affected browser(s),operating system(s), npm, node and ngrx:
ngrx 4.1.1

## Other information:
I located the problem, and I am preparing a pull request.

**Comment by brandonroberts** [comment]
Closed via #575
