### ISSUE TITLE
What about documentation? I have seen wiki page "Home / Welcome to the ngRx wiki", but it is empty.

### ISSUE THREAD

**Issue by AlexanderIgorovych** [ngrx/platform#578]
I am new to ngrx, that is why I count on documentation. I have seen demo app, from one point of view it is well commented, but from another point of view it does not provide basic description of the components (with few different examples). 
I will gladly create documentation, and will keep it in sync with latest version but I need your help to figure out all the aspects of the ngrx (step by step).
I will be much easier to create documentation because I am newcomer in this tool, and a lot of developers are newcomers too.
Let's do it together, I will describe my experience step-by-step (with diagrams) but I need your support.

P.S. don't get me wrong.

**Comment by brandonroberts** [comment]
@AlexanderIgorovych each package in the readme links to it's documentation. 

https://github.com/ngrx/platform/blob/master/README.md
