### ISSUE TITLE
Update only visible components

### ISSUE THREAD

**Issue by monica7l** [ngrx/platform#579]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
</code></pre>

## What is the current behavior?
I'm using ngrx/store. 
I have a store which is being updated and this affects several components that are subscribed to this store.
Not all these components are visible at a certain time. However, they all get updated as soon as the store get updated. 

## Expected behavior:
Is there a way to avoid this so the listening components will only get updated when they become visible?

## Minimal reproduction of the problem with instructions:
`this.store.select(AppState => AppState.ex).subscribe(ex => this.update(ex));
`
The method `update(ex)` is called anytime `store` is being updated. 

What is the best practice to avoid updating when the component is not visible but to trigger the update if it becomes visible again?

## Version of affected browser(s),operating system(s), npm, node and ngrx:
ngrx.store 4.1.1
node 6.0.60

**Comment by brandonroberts** [comment]
Each selection from state is called with `distinctUntilChanged`, so it only emits if the reference changes. You should check how your reducers are updating the state. If you need further assistance, use the support channel. https://gitter.im/ngrx/platform
