### ISSUE TITLE
Extend Actions

### ISSUE THREAD

**Issue by lidoravitan** [ngrx/platform#582]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

I found that create actions as pure object is unsuitable for big scale project, what I'm recommend is to write actions as class/service, then you can extend(you can use service inject and extend once) repeat actions.

then you have base action class, you can extend the action class with context. and you do not repeat your self, .and I  don't need to  explain the extend benefits.

example: Todos Application, first section for home tasks, second section for school tasks.
they both have add task, remove task, update task but the context is different
sure it's only simple example but in big scale application you will found your self write repeat actions.

sample code:

```
export class TodosActionTypes {
    
    GET_ALL_TODOS_REQUEST = `[${this.context}] GET ALL TODOS REQUEST`;
    GET_ALL_TODOS_COMPLETE = `[${this.context}] GET ALL TODOS COMPLETE`;

    constructor(public context) {}
    
    public getAllTodosRequestAction(): Action {
        return new CreateAction(this.GET_ALL_TODOS_REQUEST);
    }

    public getAllTodosRequestComplete(payload: Todo[]): Action {
        return new CreateAction(this.GET_ALL_TODOS_COMPLETE, payload);
    }

}

```
then i write simple util for craete action

```
export class CreateAction implements Action {
    constructor(public type, private payload?) {
    }
}
```
I'd love to know what you think about this paradigm or implementation.
And of course if you have ways to improve it. Or there is a better solution.

**Comment by brandonroberts** [comment]
The example app that shows common practices uses classes that extend actions already. Neither option is technically incorrect as you can use POJOs with typed action creator functions and achieve the same result. Thanks for the suggestion!

**Comment by JhonePartooo** [comment]
I think you don't understand me, Typed action creator is way to typed your actions, but you can't change the context for actions, you can do it manually like this:
```

function addTodo(payload, context) {
   return {
       type: `${context} add task`,
       payload: payload
   }
} 
```
but you dont wnat to pass the context every time. 
you can change the context with typed action creator?
