### ISSUE TITLE
Feature request:  action creators to reduce boilerplate

### ISSUE THREAD

**Issue by jaufgang** [ngrx/platform#584]
There is a fairly new library called ts-action that does a really good job of reducing boilerplate code for creating and consuming actions.  

see: https://github.com/cartant/ts-action 
and https://github.com/cartant/ts-action-operators

I know there are other action creator libraries out there, but as far as I know, this one seems to have a unique key innovation.  The creator function attaches the action name as a _static_  `.type` property to the action type. So when you create actions like this:
```typescript
export Foo = action("FOO", payload<{ foo: number }>());
export Bar = action("BAR", payload<{ bar: number }>());
```
you can use them in reducers using this syntax:  

```typescript
function fooBarReducer(state: State = initialState, action: typeof All): State {
  switch (action.type) {
  case Foo.type:
    return { ...state, foo: action.payload.foo };
  case Bar.type:
    return { ...state, bar: action.payload.bar };
  default:
    return state;
  }
}
```

This is very elegant because you don't need to export the action names as strings or enums, you just export each action type and that's it.

In the [blog post "Introducing @ngrx/entity"](https://medium.com/ngrx/introducing-ngrx-entity-598176456e15), it was stated 

> One of the most consistent complaints about building apps with NgRx is the amount of boilerplate developers have to write. The challenge when trying to solve the boilerplate issue is that the required explicitness is essential to get the full benefits out of the architecture. We think that by developing targeted libraries we can help reduce some of this boilerplate while retaining all of the benefits that NgRx provides.

I think this solution accomplishes this goal as well, would make NgRx easier for beginners to understand, and I would like to suggest adding this feature or something similar based on the same idea.  It would gain more uptake and become an accepted usage if it were part of theNgRx platform rather than a 3rd party library. I at least wanted to bring it to the attention of the NgRx team for your consideration.

**Comment by brandonroberts** [comment]
I think learning how actions are created from scratch gives you a better understanding of using NgRx, and if you want to implement a pattern such as this library, that's fine. It's not something we are going to add to the API at this time.
