### ISSUE TITLE
Update live app to map to example app code

### ISSUE THREAD

**Issue by goelinsights** [ngrx/platform#585]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
</code></pre>

## What is the current behavior?
Live app shows state with root level state elements:
- search
- books
- collection
- state
- router

Example app when generated shows different state elements with BookState elements one level down vs in the root:
- layout
- routerReducer
- auth
- books
 -- books
 -- search
 -- collection

## Expected behavior:
state as seen in dev-tools is the same.

## Minimal reproduction of the problem with instructions:
looked at live version at: http://ngrx.github.io/example-app/#/book/find

and generated the example app using Quick Start instructions from: https://github.com/ngrx/platform/blob/master/example-app/README.md

## Other information:
ngrx/platform 4.1.1

**Comment by goelinsights** [comment]
Spent a fair bit of time trying to figure out why my lazy loaded state was being injected a level down.  

Is this just the way it is or can it be pulled back up, as we see in the live app, where the 3 injected elements from BookState are pulled into the State at the first level without 'book' being the parent of BookState?

**Comment by brandonroberts** [comment]
The example app for 4.x is located at http://ngrx.github.io/platform/example-app
