### ISSUE TITLE
I have a design question for you. Would it not have been better to make actions of type Action<T>? 

### ISSUE THREAD

**Issue by egervari** [ngrx/platform#587]
This would really cut down on the amount of new types, and would make it easier to upgrade older applications on Ngrx 2.2 for example (like mine, which is 150,000 lines of code). Was there a reason this wasn't considered?

I think not having a `payload` on the Action makes it really awkward in reducers as well. Some of the actions for that reducer won't have payloads at all, or maybe you want to have better variable names that are not named `payload` since it's now possible to do that. In both cases, you must cast `action`, like below:

```
case LoginActionTypes.AUTHENTICATE_FAILURE:
      const authenticateFailure = action as AuthenticateFailure;
      
      return {
        ...state,
        isLoading: false,
        loadingError: authenticateFailure.error
      };
```

This seems really clunky.. the cast is more boilerplate, and it would probably occur 200-300 times in my application... maybe more. I wonder if it wouldn't just be better to put `payload` back into Action to remove all of these casts. This change would also remove custom action types, in the style of the ones in your examples:

```
export type LoginActions =
  SetDestination |
  TogglePasswordVisibility |
  Authenticate |
  AuthenticateSuccess |
  AuthenticateFailure;
```

In my case, I would have had 50+ types like this in my app, and all of that code could disappear if all Actions had a payload of type T. And since you have to cast in your reducers anyway in the payload-less Action model, the suggestion to group actions into a type like this seems unnecessary and waste of code. I mean if you have to cast, there's no need for this. The only way to benefit from these action types is to name every payload `payload`, and ensure every constructor has one, even if it doesn't require it. And if that's the case, then really you might as well just add it back into the Action class, because it's the same thing, but a lot more manual work.

The Action classes would also become a lot cleaner:

```
export class Authenticate extends Action<LoginForm> {
  public readonly type = LoginActionTypes.AUTHENTICATE;
}

export class AuthenticateFailure extends Action<Error> {
  public readonly type = LoginActionTypes.AUTHENTICATE_FAILURE;
}
```

or even simpler... just getting red of the Action subclasses altogether:

```
const myAction = new Action<LoginForm>(LoginActionTypes.AUTHENTICATE, loginForm);
```

This approach would actually remove all of the required custom action classes while still being type safe. Also, in your `*.actions.ts`, you would only have to code 1 export instead of 2+N exports (such as a collection of action type strings, individual action classes, and the actions type). That's a lot of time savings for the application coder, which should be the goal of any framework - remove as much code from the application as possible and get people coding productively and correctly as fast as possible.

If Ngrx was reworked to no longer require type strings and it relied on the name of the type instead, then I can definitely see the benefits of using Action classes - it would be less work - but as is, I'm missing the benefits to the current design in 4.x.

I think this suggestion and all of the consequences of implementing it would drastically reduce user code. I don't even see a downside to it. There's already a sizable code commitment to adding redux/ngrx to your application compared to the a services-only approach, so all of this new code in Ngrx 4.x just makes the library even more daunting and time-consuming to implement. Is there any reason why user code has to be this clunky? What is the payoff/benefit?

I realize I can make my own Action type, like `MyCustomAction` that includes a `payload`, but if that was the best practice, then I feel that the example apps/best practices shown on this github project would be problematic for newcomers and lead them to doing the wrong things, and that's not a good outcome in my opinion :(

Thanks for listening,
Katie

**Comment by jinder** [comment]
Why do you need to cast your actions? If you use a type discriminator, TypeScript will automatically narrow the type.  Just make sure your action has the readonly prefix on type.

**Comment by MikeRyanDev** [comment]
This was a conscious decision in NgRx 4 to try and push developers to use discriminated union types in reducer statements. Unfortunately, one of the headaches of discriminated unions is the amount of boilerplate required to implement in a sizable codebase (it sounds like we work on similarly large projects).

As @jinder mentioned if your string constants' types are flowing as string literals and the `type` property of your action classes are marked as `readonly` then you shouldn't need to manually cast actions in your reducer statements. 

Also note that we are actively working on building better tooling that won't require classes at all in future versions of NgRx. See the [@ngrx/codegen proposal here](https://paper.dropbox.com/doc/ngrxcodegen-Proposal-DhD934mmHfqTljpntnqJ3)
