### ISSUE TITLE
Question about example-app

### ISSUE THREAD

**Issue by TylerHelmuth** [ngrx/platform#591]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

I have a simple question.  In the example-app, what is the purpose of this code in books module's index reducer?

```
export interface State extends fromRoot.State {
  'books': BooksState;
}
```

**Comment by brandonroberts** [comment]
Support questions should be asked on stackoverflow or in the gitter channel https://gitter.im/ngrx/platform
