### ISSUE TITLE
example-app: Update actions types to use enum instead of const

### ISSUE THREAD

**Issue by BeastCode** [ngrx/platform#597]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
Actions types are currently declared as const.

## Expected behavior:
Suggestion, update example app to use enum instead of const for actions types

## Minimal reproduction of the problem with instructions:

Current:
export const OPEN_SIDENAV = '[Layout] Open Sidenav';
export const CLOSE_SIDENAV = '[Layout] Close Sidenav';

Suggestion:
export enum LayoutActionTypes {
  OpenSidenav = '[Layout] Open Sidenav',
  CloseSidenav = '[Layout] Close Sidenav',
}

## Other information:

I would like to help document best practices and conventions for NgRX code and turn the standards into code snippets for Angular.

**Comment by jotatoledo** [comment]
I remember that this was the implemented approach on the old ngrx/store example and afterwards got refactored. Maybe check the reason for it in thw repo

**Comment by BeastCode** [comment]
One difference between the old commit and my pr is that I’m using String Enums, which became available in TS2.4: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-4.html

**Comment by brandonroberts** [comment]
Fixed via #598
