### ISSUE TITLE
When returning a Class instance from selector, it gets updated erroneously

### ISSUE THREAD

**Issue by mxchange** [ngrx/platform#599]
## I'm submitting a...
<pre><code>
[ ] Regression
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

Selector subcription/stream update gets triggered when state hasn't changed.

#### When I return a `Class` instance from a selector
```typescript
export const getItem =
  createSelector(getItemState, state => new Item(state.item));
```
(Whether or not I use `super()` or don't pass any data (`new Item()`) makes no difference.)

And then dispatch some action on the reducer that is related to `getItemState`, (let's say `UPDATE_ITEM`) it causes to trigger the selector update (I'm assuming `.next()` in steam) each time the reducer is iterated (so also on `UPDATE_ITEM_DONE`)

#### But when I don't initialize a new Item:
```typescript
export const getItem =
  createSelector(getItemState, state => state.item);
```
It doesn't trigger an update, like expected, because the state hasn't changed.

To add to that:
#### if the reducer's state that is returned for either action is 
```typescript
return {
   ...state
}
```
The issue occurs (so it triggers even when there is no change in state).

#### But when I do:
```typescript
return state;
```
It doesn't

Or, when I just remove the actions `UPDATE_ITEM` and `UPDATE_ITEM_DONE` from the reducer entirely, it doesn't occur.

So to summarize:

### With class:
- UPDATE_ITEM 
- itemState$ subscription updated
- UPDATE_ITEM_DONE returns state
- itemState$ subscription updated

### Without class, or without spread operator
- UPDATE_ITEM 
- UPDATE_ITEM_DONE

So there's a combination of using a Class in the selector, and returning it with a spread operator that seems to be causing the issue. 
Whether this is related to `ngrx-store` or the typescript compilation (where the spread operator is taking the object apart and rebuilds it). I'm not sure how the `createSelector` works, and if this is expected behaviour.

## Things I've tried which didn't help
- diff the `itemState$` with lodash `_.isEqual` says `true`...
- tried selecting the state first then initialising with class, and the other way around (with 2 separate selectors)
- return `new Item(...state.item)`

## Expected behavior:

If I return a Class it should not trigger the next value in the store's stream, since nothing has actually changed.

## Minimal reproduction of the problem with instructions:

Returning a `new Class()` from a selector like above should be sufficient to reproduce.
And then see the different in how many time the `itemState$` from `getItemState` would update in each case, if at all.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
ngrx 4.0.0~4.1.1
angular 4.3.6
typescript 2.4.2
rxjs 5.5.2

**Comment by brandonroberts** [comment]
This is expected behavior. When using selectors, they already are returned with `distinctUntilChanged`, and returning a new object with the spread operator is returning a new reference, which triggers a change. I believe the same applies since you're returning a new instance of the `Item` instead of selecting that item instance from the store. Selectors don't fire unless the arguments change, so if your item reference hasn't changes, you should still get the same instance of Item.

What you could test is selecting the item from state and map it to a new instance of `Item`. If you need further support, use the https://gitter.im/ngrx/platform

**Comment by Shanedestiny383** [comment]
https://fadein2.github.io/mobile-application77/ I confronted that challenge and figured out an answer
