### ISSUE TITLE
@ngrx example application

### ISSUE THREAD

**Issue by joelmuskwe** [ngrx/platform#600]
I followed the steps but when i run i get these error messages:

**my enviroment is as follows:
npm -v: 5.5.1
node -v: v8.1.2
yarn -v: 0.24.6**

ERROR in example-app/app/app.module.ts(8,29): error TS2307: Cannot find module '@ngrx/store'.
example-app/app/app.module.ts(9,31): error TS2307: Cannot find module '@ngrx/effects'.
example-app/app/app.module.ts(14,8): error TS2307: Cannot find module '@ngrx/router-store'.
example-app/app/app.module.ts(15,37): error TS2307: Cannot find module '@ngrx/store-devtools'.
example-app/app/auth/actions/auth.ts(1,24): error TS2307: Cannot find module '@ngrx/store'.
example-app/app/auth/auth.module.ts(5,29): error TS2307: Cannot find module '@ngrx/store'.
example-app/app/auth/auth.module.ts(6,31): error TS2307: Cannot find module '@ngrx/effects'.
example-app/app/auth/containers/login-page.component.ts(2,23): error TS2307: Cannot find module '@ngrx/store'.
example-app/app/auth/effects/auth.effects.ts(8,33): error TS2307: Cannot find module '@ngrx/effects'.
example-app/app/auth/reducers/index.ts(1,55): error TS2307: Cannot find module '@ngrx/store'.
example-app/app/auth/services/auth-guard.service.ts(5,23): error TS2307: Cannot find module '@ngrx/store'.
example-app/app/auth/services/auth-guard.service.ts(11,14): error TS2420: Class 'AuthGuard' incorrectly implements interface 'CanActivate'.
  Types of property 'canActivate' are incompatible.
    Type '() => Observable<boolean>' is not assignable to type '(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) => boolean | Promise<boolean> | Obser...'.
      Type 'Observable<boolean>' is not assignable to type 'boolean | Promise<boolean> | Observable<boolean>'.
        Type 'Observable<boolean>' is not assignable to type 'Observable<boolean>'. Two different types with this name exist, but they are unrelated.
          Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.
example-app/app/books/actions/book.ts(1,24): error TS2307: Cannot find module '@ngrx/store'.
example-app/app/books/actions/collection.ts(1,24): error TS2307: Cannot find module '@ngrx/store'.
example-app/app/books/books.module.ts(4,29): error TS2307: Cannot find module '@ngrx/store'.
example-app/app/books/books.module.ts(5,31): error TS2307: Cannot find module '@ngrx/effects'.
example-app/app/books/containers/collection-page.ts(3,23): error TS2307: Cannot find module '@ngrx/store'.
example-app/app/books/containers/find-book-page.ts(3,23): error TS2307: Cannot find module '@ngrx/store'.
example-app/app/books/containers/selected-book-page.ts(2,23): error TS2307: Cannot find module '@ngrx/store'.
example-app/app/books/containers/view-book-page.ts(5,23): error TS2307: Cannot find module '@ngrx/store'.
example-app/app/books/containers/view-book-page.ts(33,8): error TS2339: Property 'map' does not exist on type 'Observable<Params>'.
example-app/app/books/effects/book.ts(8,33): error TS2307: Cannot find module '@ngrx/effects'.
example-app/app/books/effects/book.ts(9,24): error TS2307: Cannot find module '@ngrx/store'.
example-app/app/books/effects/collection.ts(7,24): error TS2307: Cannot find module '@ngrx/store'.
example-app/app/books/effects/collection.ts(8,33): error TS2307: Cannot find module '@ngrx/effects'.
example-app/app/books/guards/book-exists.ts(9,23): error TS2307: Cannot find module '@ngrx/store'.
example-app/app/books/guards/book-exists.ts(24,14): error TS2420: Class 'BookExistsGuard' incorrectly implements interface 'CanActivate'.
  Types of property 'canActivate' are incompatible.
    Type '(route: ActivatedRouteSnapshot) => Observable<boolean>' is not assignable to type '(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) => boolean | Promise<boolean> | Obser...'.
      Type 'Observable<boolean>' is not assignable to type 'boolean | Promise<boolean> | Observable<boolean>'.
        Type 'Observable<boolean>' is not assignable to type 'Observable<boolean>'. Two different types with this name exist, but they are unrelated.
example-app/app/books/reducers/books.ts(1,32): error TS2307: Cannot find module '@ngrx/store'.
example-app/app/books/reducers/books.ts(2,65): error TS2307: Cannot find module '@ngrx/entity'.
example-app/app/books/reducers/index.ts(1,55): error TS2307: Cannot find module '@ngrx/store'.
example-app/app/core/actions/layout.ts(1,24): error TS2307: Cannot find module '@ngrx/store'.
example-app/app/core/containers/app.ts(4,23): error TS2307: Cannot find module '@ngrx/store'.
example-app/app/core/services/google-books.ts(16,8): error TS2339: Property 'map' does not exist on type 'Observable<{ items: Book[]; }>'.
example-app/app/core/services/google-books.ts(20,5): error TS90010: Type 'Observable<Book>' is not assignable to type 'Observable<Book>'. Two different types with this name exist, but they are unrelated.
  Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.
example-app/app/reducers/index.ts(7,8): error TS2307: Cannot find module '@ngrx/store'.
example-app/app/reducers/index.ts(10,29): error TS2307: Cannot find module '@ngrx/router-store'.
example-app/app/shared/utils.ts(1,39): error TS2307: Cannot find module '@ngrx/router-store'.
node_modules/ngrx-store-freeze/src/index.d.ts(1,39): error TS2307: Cannot find module '@ngrx/store'.

webpack: Failed to compile.

**Comment by brandonroberts** [comment]
Check the `engines` in the `package.json`. It will provide you the correct version you need to run the project.
