### ISSUE TITLE
action-/stateSanitizer configuration does not make it into the extension.

### ISSUE THREAD

**Issue by timblakely** [ngrx/platform#604]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

`actionSanitizer` and `stateSanitizer`, if specified in the config, are not called.

## Other information:

#544 added support for `actionSanitizer` and `stateSanitizer`, but unfortunately they never make it into the extension. `StoreDevtools` uses `notify` to send updates to the extension, which in turn calls `devtoolsExtension.send` with `null, state, this.config, this.instanceId`. The config object does have the state-/actionSanitizers properties, but the `sendMessage` function in the extension [does not reference them nor passes the config into the extension](https://github.com/zalmoxisus/redux-devtools-extension/blob/58f6bd3c0d2fcb0ed831d7761d3db3c6030f415e/src/app/api/index.js#L84), and are subsequently ignored.

**Comment by timblakely** [comment]
Note: This also blocks the ability to dispatch an `Action` whose payload is/contains an `ActivatedRoute` while using `@ngrx/store-devtools` (or any other payload with circular references).

**Comment by roopkt** [comment]
Hi @timblakely 
I will start working on this issue.

**Comment by roopkt** [comment]
Hi @brandonroberts  I just committed the fix and tested it. Action/State sanitizers are getting called now.

**Comment by kgkma** [comment]
Hey @timblakely! I've also created #795 to address this.

> Note: This also blocks the ability to dispatch an Action whose payload is/contains an ActivatedRoute while using @ngrx/store-devtools (or any other payload with circular references).

I'm not sure how to test that this problem is resolved, but please feel free to try it out.

**Comment by roopkt** [comment]
Hi @kgkma I think you are correct. The way you did the fix makes more sense.

**Comment by brandonroberts** [comment]
Fixed via #795
