### ISSUE TITLE
ActionReducer returning compile error

### ISSUE THREAD

**Issue by subramn** [ngrx/platform#608]
Hi,

When i try to map the counterreducer in ActionReducerMap getting the following error , not sure what mistake i am making.

ERROR in [at-loader] ./src/app/store/counter-reducer.ts:20:14
    TS2322: Type '{ counter: (state: ApplicationState | undefined, action: AddAction) => ApplicationState; }' is not assignable to type 'ActionReducerMap<ApplicationState, Action>'.
  Types of property 'counter' are incompatible.
    Type '(state: ApplicationState | undefined, action: AddAction) => ApplicationState' is not assignable to type 'ActionReducer<number, Action>'.
      Types of parameters 'state' and 'state' are incompatible.
        Type 'number | undefined' is not assignable to type 'ApplicationState | undefined'.
          Type 'number' is not assignable to type 'ApplicationState | undefined'.

Code:

export interface ApplicationState {
    counter: number;
}

export const initialApplicationState: ApplicationState = {
    counter: 0
}

export function counterReducer(state: ApplicationState = initialApplicationState,
    action: AppActions) {
    console.log('Action came in! ' + action.payLoad);

    return state;
}

export const reducers: ActionReducerMap<ApplicationState> = {
    counter: counterReducer
}

**Comment by brandonroberts** [comment]
Support questions should be handled in the gitter channel https://gitter.im/ngrx/platform
