### ISSUE TITLE
synchronization with external database

### ISSUE THREAD

**Issue by alessandrov** [ngrx/platform#610]
First of all sorry if this is not the right place or way to ask.

We are willing to use this library in production, before doing that i would like to make sure that a (well tested) module **to synchronize ngrx/db with an external database** is available.

At the moment we are planning to use PouchDB to achieve that goal.

Any suggestion/information is welcome.

Thanks all.

**Comment by brandonroberts** [comment]
These type of questions should be handled in the gitter channel. https://gitter.im/ngrx/platform or on stackoverflow
