### ISSUE TITLE
Example app error 

### ISSUE THREAD

**Issue by ridj87** [ngrx/platform#612]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

Getting this when following installation instructions for the example app
 Argument of type '{ name: string; }' is not assignable to parameter of type 'StoreDevtoolsOptions'.   Object literal may only specify known properties, and 'name' does not exist in type 'StoreDevtoolsOptions'.

## Expected behavior:

To be able to build

## Minimal reproduction of the problem with instructions:

followed installations of example-app instructions

## Version of affected browser(s),operating system(s), npm, node and ngrx:

Angular CLI: 1.5.0
Node: 8.9.1
OS: win32 x64
Angular: 5.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cdk: 2.0.0-beta.12
@angular/cli: 1.5.0
@angular/material: 2.0.0-beta.12
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.2
typescript: 2.4.2
webpack: 3.8.1

**Comment by brandonroberts** [comment]
This is not a bug with the example app. Please provide more details about your environment.
