### ISSUE TITLE
Contradictional statements Victor Savkin - Branden Roberts

### ISSUE THREAD

**Issue by guygit** [ngrx/platform#614]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
</code></pre>

## What is the current behavior?

Victor Savkin states in his article (https://blog.nrwl.io/using-ngrx-4-to-manage-state-in-angular-applications-64e7a1f84b7b) that the router should be treated as a "Source of Truth".
Furthermore he states, that with his proposed approach it is possible to use the usual Resolvers and Guards.

Branden Roberts however, states in this Issue "https://github.com/ngrx/platform/issues/358"
that "Using resolvers with ngrx is considered an antipattern .."

At first sight, this seems to be a contradiction.

In addition I have seen here in the issue lists several comments requesting an explicit router event indicating that a certain route has eventually being entered (and was not cancelled in between)

Worst however, meanwhile articles popping up such as https://medium.com/@m3po22/stop-using-ngrx-effects-for-that-a6ccfe186399
stating "Is ngrx/effects really the best way to handle this?"

## Expected behavior:

Having unambiguoes concepts how things are supposed to be done for the most common scenarios
such as routing with/without resolvers and guards.
Also since "navigating to .." cannot be considered as an atomic operation, how does Navigation cancelling/erroring relate to all this?

Easiest would probably be - to have a StateChart one can easily see how this is supposed to work?

**Comment by brandonroberts** [comment]
Thanks for your concern @guygit. Both statements are true. You _should_ use the router as a source of truth if you want to build your application in that style, and using resolvers with ngrx is an _anti-pattern_. The NgRx platform it is flexible enough to be used in different scenarios and we don't need to force an opinion on you as a developer.
