### ISSUE TITLE
router-store causes console errors when built in prod mode (angular-cli@1.5.4, angular@5.0.3)

### ISSUE THREAD

**Issue by nate-summercook** [ngrx/platform#615]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
We're using Angular 5 with angular-cli and @ngrx with the router-store. Everything works fine until we try to run the app in prod mode `--environment=prod`. The prod build runs without errors but as soon as we start the app in the browser, this is what we encounter:
<pre><code>
zone.js:690 Unhandled Promise rejection: Cannot add property _resolvedData, object is not extensible ; Zone: angular ; Task: Promise.then ; Value: TypeError: Cannot add property _resolvedData, object is not extensible
    at MapSubscriber.eval [as project] (router.js:3848)
    at MapSubscriber._next (map.js:79)
    at MapSubscriber.Subscriber.next (Subscriber.js:91)
    at ScalarObservable._subscribe (ScalarObservable.js:51)
    at ScalarObservable.Observable._trySubscribe (Observable.js:172)
    at ScalarObservable.Observable.subscribe (Observable.js:160)
    at MapOperator.call (map.js:57)
    at Observable.subscribe (Observable.js:157)
    at subscribeToResult (subscribeToResult.js:23)
    at MergeMapSubscriber._innerSub (mergeMap.js:138) TypeError: Cannot add property _resolvedData, object is not extensible
    at MapSubscriber.eval [as project] (webpack-internal:///../../../router/esm5/router.js:3930:34)
    at MapSubscriber._next (webpack-internal:///../../../../rxjs/_esm5/operators/map.js:82:35)
    at MapSubscriber.Subscriber.next (webpack-internal:///../../../../rxjs/_esm5/Subscriber.js:96:18)
    at ScalarObservable._subscribe (webpack-internal:///../../../../rxjs/_esm5/observable/ScalarObservable.js:53:24)
    at ScalarObservable.Observable._trySubscribe (webpack-internal:///../../../../rxjs/_esm5/Observable.js:177:25)
    at ScalarObservable.Observable.subscribe (webpack-internal:///../../../../rxjs/_esm5/Observable.js:165:65)
    at MapOperator.call (webpack-internal:///../../../../rxjs/_esm5/operators/map.js:60:23)
    at Observable.subscribe (webpack-internal:///../../../../rxjs/_esm5/Observable.js:162:22)
    at subscribeToResult (webpack-internal:///../../../../rxjs/_esm5/util/subscribeToResult.js:32:27)
    at MergeMapSubscriber._innerSub (webpack-internal:///../../../../rxjs/_esm5/operators/mergeMap.js:143:108)
</code></pre>

## Expected behavior:
No errors in the console. ;)

## Minimal reproduction of the problem with instructions:

1. Create an app with angular-cli@1.5.4
2. Add ngrx and the router-store and add them to the App Module
3. Serve the page with `--environment=prod`

I looked also at the example-app that you have here and it seems quite outdated. Angular 4 and also older versions of @ngrx are used there.

(Plnkr not possible because it has to be reproduced with angular-cli & --environment=prod)

## Version of affected browser(s),operating system(s), npm, node and ngrx:
My system: Chrome, Windows 7
<pre><code>
node: 8.7.0
npm: 5.4.2
+-- @angular/animations@5.0.3
+-- @angular/cli@1.5.4
+-- @angular/common@5.0.3
+-- @angular/compiler@5.0.3
+-- @angular/compiler-cli@5.0.3
+-- @angular/core@5.0.3
+-- @angular/forms@5.0.3
+-- @angular/http@5.0.3
+-- @angular/language-service@5.0.3
+-- @angular/platform-browser@5.0.3
+-- @angular/platform-browser-dynamic@5.0.3
+-- @angular/router@5.0.3
+-- @ngrx/core@1.2.0
+-- @ngrx/effects@4.1.1
+-- @ngrx/router-store@4.1.1
+-- @ngrx/store@4.1.1
+-- @ngrx/store-devtools@4.1.1
+-- @ngx-translate/core@8.0.0
+-- @ngx-translate/http-loader@2.0.0
+-- @types/jasmine@2.5.45
+-- @types/node@6.0.92
+-- bootstrap-sass@3.3.7
+-- codelyzer@3.2.2
+-- core-js@2.5.1
+-- intl@1.2.5
+-- jasmine-core@2.8.0
+-- jasmine-spec-reporter@4.2.1
+-- karma@1.7.1
+-- karma-chrome-launcher@2.2.0
+-- karma-cli@1.0.1
+-- karma-coverage-istanbul-reporter@1.3.0
+-- karma-jasmine@1.1.0
+-- karma-jasmine-html-reporter@0.2.2
+-- karma-phantomjs-launcher@1.0.4
+-- lodash@4.17.4
+-- moment@2.19.2
+-- ng-dynamic-component@2.0.3
+-- ngrx-store-freeze@0.2.0
+-- ngx-bootstrap@2.0.0-beta.9
+-- ngx-toastr@6.5.0
+-- node-sass@4.5.3
+-- protractor@5.2.0
+-- rxjs@5.5.2
+-- stacktrace-js@2.0.0
+-- ts-node@3.3.0
+-- tslib@1.8.0
+-- tslint@5.8.0
+-- typescript@2.4.2
`-- zone.js@0.8.18
</code></pre>

## Other information:
--

**Comment by brandonroberts** [comment]
Please provide a reproduction of this issue.

**Comment by nate-summercook** [comment]
I tried reproducing the issue with your example-app, but as I said it's very outdated and doesn't even showcase the latest ngrx version...
I suggest just getting the example-app up to date which you probably have to do anyway and I'm sure you'll get the same error when you run it in prod mode.

**Comment by brandonroberts** [comment]
The example app for V4 is in this repository, so maybe you're referring to the old one...

**Comment by nate-summercook** [comment]
Oh ok, indeed looked in the wrong place... Trying it now...

**Comment by nate-summercook** [comment]
Ok here we go:
1. Check out the ngrx codebase
2. For example in `example-app/app/books/effects/book.ts`, add a simple `@Effect` that reacts to `ROUTER_NAVIGATION`:
<pre><code>
@Effect() routeChange$: Observable<Action> = this.actions$.ofType(ROUTER_NAVIGATION)
    .map((action: RouterNavigationAction) => action.payload)
    .do(console.log);
</code></pre>
3. Run example:start script `yarn run example:start` --> Everything's just fine.
4. In package.json add -prod flag to the example:start script, run again --> Error in the browser console.

**Comment by brandonroberts** [comment]
@nate-summercook that example produces an error without the `-prod` flag because it doesn't map to another action and you aren't using `@Effect({ dispatch: false })`.

**Comment by nate-summercook** [comment]
Found the problem on our side. It's described in the router-store documentation:

> Additionally, the router state snapshot is a mutable object, which can cause issues when developing with [store freeze](https://github.com/brandonroberts/ngrx-store-freeze) to prevent direct state mutations. This can be avoided by using a custom serializer.

Had to create a custom serializer because we use store-freeze. Sorry about this, can be closed.

**Comment by killstealing** [comment]
Hi.Could you tell me how you resolved this problem?

**Comment by sylvaingirardbe** [comment]
@killstealing the ngrx example app has a CustomRouterStateSerializer, which could solve your problem. Check out that code and see how it works.

HTH
