### ISSUE TITLE
from typescript import system to angular module providers for actions and selectors

### ISSUE THREAD

**Issue by techla** [ngrx/platform#618]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
the import / export of selectors and actions of a feature module is currently based on the typescript import / export system.

## Expected behavior:
But importing / exporting them via the injector (declared as providers so as to be part of the Anuglar import / export system) isn't the way to go (as we do for regular API services) ?

**Comment by brandonroberts** [comment]
There's nothing preventing you from registering your selectors through DI without this library explicitly providing an API for you. At a minimum you can put your selectors in a service.
