### ISSUE TITLE
--prod no such file package.json

### ISSUE THREAD

**Issue by ychost** [ngrx/platform#619]
Unhandled rejection Error: ENOENT: no such file or directory, open 'C:\Users\ychost\Desktop\ng5-admin\node_modules\_@ngrx_store@4.1.1@@ngrx\package.json'

angular: 5.0.3
angular/cli:1.5.5
ngrx: 4.1.1
node: 6.11
os: windows 10

**Comment by brandonroberts** [comment]
Check the `engines` in the `package.json`
