### ISSUE TITLE
Plunker and new issue template

### ISSUE THREAD

**Issue by axtho** [ngrx/platform#62]
There should be an issue template for new issues (as in https://github.com/angular/material2/issues/new, or in issue #61).

Additionally it would be helpful to have a Plunker with the nightly builds and some sort of easy test case and everything included (store, effects, router-store, devTools, db).

**Comment by robwormald** [comment]
Sounds good to me, want to build it? cc @filearts is i think there's some cool stuff to be done here with plunker templates
