### ISSUE TITLE
Dispatching Go throws an error when using relativeTo

### ISSUE THREAD

**Issue by alvipeo** [ngrx/platform#621]
I was trying to use what's provided here https://github.com/ngrx/platform/blob/master/docs/router-store/api.md#navigation-actions. So I have a simple dispatch:

          () => this.store.dispatch(
            new Go({
              path: ["../"],
              extras: { relativeTo: this.route }
            })
          )

and I get the following error from store-devtools:
>> TypeError: Cannot read property 'players' of undefined

but this error is gone if I just use `router.navigate`:

          () => this.router.navigate(["../"], { relativeTo: this.route })

My idea is this is a problem with store-devtools or `ActivatedRoute` serialization, or ... something else. I don't know. But seems like a bug.

BTW, I don't see much advantage in using Navigation Actions. Am I missing something?

---

the whole error from dev tools:

index.ts:51 state undefined
index.ts:52 action {type: "@ngrx/store/init"}
index.ts:51 state {layout: {…}, routerReducer: undefined, users: {…}}
index.ts:52 action {type: "@ngrx/effects/init"}
core.js:3565 Angular is running in the development mode. Call enableProdMode() to enable the production mode.
index.ts:51 state {layout: {…}, routerReducer: undefined, users: {…}}
index.ts:52 action {type: "ROUTER_NAVIGATION", payload: {…}}
index.ts:51 state {layout: {…}, routerReducer: {…}, users: {…}}
index.ts:52 action LoadRegistrations {type: "[Registrations] Load All"}
index.ts:51 state {layout: {…}, routerReducer: {…}, users: {…}}
index.ts:52 action ShowGlobalInProgressAction {payload: true, type: "[Global] Show In Progress Global"}
index.ts:51 state undefined
index.ts:52 action {type: "@ngrx/store/init"}
index.ts:51 state {layout: {…}, routerReducer: undefined, users: {…}}
index.ts:52 action {type: "@ngrx/effects/init"}
index.ts:51 state {layout: {…}, routerReducer: undefined, users: {…}}
index.ts:52 action {type: "ROUTER_NAVIGATION", payload: {…}}
index.ts:51 state {layout: {…}, routerReducer: {…}, users: {…}}
index.ts:52 action LoadRegistrations {type: "[Registrations] Load All"}
index.ts:51 state {layout: {…}, routerReducer: {…}, users: {…}}
index.ts:52 action ShowGlobalInProgressAction {payload: true, type: "[Global] Show In Progress Global"}
index.ts:51 state undefined
index.ts:52 action {type: "@ngrx/store/init"}
index.ts:51 state {layout: {…}, routerReducer: undefined, users: {…}, clients: {…}}
index.ts:52 action {type: "@ngrx/effects/init"}
index.ts:51 state {layout: {…}, routerReducer: undefined, users: {…}, clients: {…}}
index.ts:52 action {type: "ROUTER_NAVIGATION", payload: {…}}
index.ts:51 state {layout: {…}, routerReducer: {…}, users: {…}, clients: {…}}
index.ts:52 action LoadRegistrations {type: "[Registrations] Load All"}
index.ts:51 state {layout: {…}, routerReducer: {…}, users: {…}, clients: {…}}
index.ts:52 action ShowGlobalInProgressAction {payload: true, type: "[Global] Show In Progress Global"}
index.ts:51 state {layout: {…}, routerReducer: {…}, users: {…}, clients: {…}}
index.ts:52 action LoadRegistrationsSuccess {payload: Array(0), type: "[Registrations] Load All Success"}
index.ts:51 state {layout: {…}, routerReducer: {…}, users: {…}, clients: {…}}
index.ts:52 action ShowGlobalInProgressAction {payload: false, type: "[Global] Show In Progress Global"}
index.ts:51 state {layout: {…}, routerReducer: {…}, users: {…}, clients: {…}}
index.ts:52 action {type: "ROUTER_NAVIGATION", payload: {…}}
index.ts:51 state {layout: {…}, routerReducer: {…}, users: {…}, clients: {…}}
index.ts:52 action LoadClients {type: "[Clients] Load All"}
index.ts:51 state {layout: {…}, routerReducer: {…}, users: {…}, clients: {…}}
index.ts:52 action ShowGlobalInProgressAction {payload: true, type: "[Global] Show In Progress Global"}
index.ts:51 state {layout: {…}, routerReducer: {…}, users: {…}, clients: {…}}
index.ts:52 action LoadClientsSuccess {payload: Array(2), type: "[Clients] Load Success"}
index.ts:51 state {layout: {…}, routerReducer: {…}, users: {…}, clients: {…}}
index.ts:52 action ShowGlobalInProgressAction {payload: false, type: "[Global] Show In Progress Global"}
index.ts:51 state {layout: {…}, routerReducer: {…}, users: {…}, clients: {…}}
index.ts:52 action {type: "ROUTER_NAVIGATION", payload: {…}}
index.ts:51 state {layout: {…}, routerReducer: {…}, users: {…}, clients: {…}}
index.ts:52 action ViewClientAction {payload: "d23643ba-9599-45d8-aa8d-5a6e0913fd57", type: "[Clients] View Client"}
index.ts:51 state {layout: {…}, routerReducer: {…}, users: {…}, clients: {…}}
index.ts:52 action {type: "ROUTER_NAVIGATION", payload: {…}}
index.ts:51 state {layout: {…}, routerReducer: {…}, users: {…}, clients: {…}}
index.ts:52 action LoadClientAndSequences {payload: Guid, type: "[Client Sequences] Load Client and Sequences"}
index.ts:51 state {layout: {…}, routerReducer: {…}, users: {…}, clients: {…}}
index.ts:52 action ShowGlobalInProgressAction {payload: true, type: "[Global] Show In Progress Global"}
index.ts:51 state {layout: {…}, routerReducer: {…}, users: {…}, clients: {…}}
index.ts:52 action LoadSequencesSuccess {payload: {…}, type: "[Client Sequences] Load Success"}
index.ts:51 state {layout: {…}, routerReducer: {…}, users: {…}, clients: {…}}
index.ts:52 action ShowGlobalInProgressAction {payload: false, type: "[Global] Show In Progress Global"}
index.ts:51 state {layout: {…}, routerReducer: {…}, users: {…}, clients: {…}}
index.ts:52 action {type: "ROUTER_NAVIGATION", payload: {…}}
index.ts:51 state {layout: {…}, routerReducer: {…}, users: {…}, clients: {…}}
index.ts:52 action SaveSequence {payload: {…}, type: "[Client Sequences] Save sequence"}
index.ts:51 state {layout: {…}, routerReducer: {…}, users: {…}, clients: {…}}
index.ts:52 action ShowGlobalInProgressAction {payload: true, type: "[Global] Show In Progress Global"}
index.ts:51 state {layout: {…}, routerReducer: {…}, users: {…}, clients: {…}}
index.ts:52 action SaveSequenceSuccess {payload: {…}, type: "[Client Sequences] Save success"}
index.ts:51 state {layout: {…}, routerReducer: {…}, users: {…}, clients: {…}}
index.ts:52 action ShowMessageDialogAction {payload: MessageDialogSetup, type: "[Global] Show Message Dialog"}
index.ts:51 state {layout: {…}, routerReducer: {…}, users: {…}, clients: {…}}
index.ts:52 action ShowGlobalInProgressAction {payload: false, type: "[Global] Show In Progress Global"}
index.ts:51 state {layout: {…}, routerReducer: {…}, users: {…}, clients: {…}}
index.ts:52 action MessageDialogClosedAction {payload: {…}, type: "[Global] Message Dialog Closed"}
index.ts:51 state {layout: {…}, routerReducer: {…}, users: {…}, clients: {…}}
index.ts:52 action Go {payload: {…}, type: "[Router] Go"}
store-devtools.es5.js:270 TypeError: Cannot read property 'players' of undefined
    at Object.get [as players] (browser.js:5677)
    at eval (index.js:10)
    at Array.forEach (<anonymous>)
    at deepFreeze (index.js:7)
    at eval (index.js:13)
    at Array.forEach (<anonymous>)
    at deepFreeze (index.js:7)
    at eval (index.js:13)
    at Array.forEach (<anonymous>)
    at deepFreeze (index.js:7)
computeNextEntry @ store-devtools.es5.js:270
recomputeStates @ store-devtools.es5.js:305
(anonymous) @ store-devtools.es5.js:500
StoreDevtools.applyOperators.state @ store-devtools.es5.js:565
ScanSubscriber._tryNext @ scan.js:114
ScanSubscriber._next @ scan.js:107
Subscriber.next @ Subscriber.js:91
WithLatestFromSubscriber._next @ withLatestFrom.js:116
Subscriber.next @ Subscriber.js:91
Notification.observe @ Notification.js:32
ObserveOnSubscriber.dispatch @ observeOn.js:95
AsyncAction._execute @ AsyncAction.js:119
QueueAction.execute @ QueueAction.js:37
AsyncScheduler.flush @ AsyncScheduler.js:38
QueueAction.schedule @ QueueAction.js:31
Scheduler.schedule @ Scheduler.js:46
ObserveOnSubscriber.scheduleMessage @ observeOn.js:99
ObserveOnSubscriber._next @ observeOn.js:102
Subscriber.next @ Subscriber.js:91
MergeMapSubscriber.notifyNext @ mergeMap.js:151
InnerSubscriber._next @ InnerSubscriber.js:25
Subscriber.next @ Subscriber.js:91
MapSubscriber._next @ map.js:85
Subscriber.next @ Subscriber.js:91
MergeMapSubscriber.notifyNext @ mergeMap.js:151
InnerSubscriber._next @ InnerSubscriber.js:25
Subscriber.next @ Subscriber.js:91
SkipSubscriber._next @ skip.js:47
Subscriber.next @ Subscriber.js:91
Subject.next @ Subject.js:56
BehaviorSubject.next @ BehaviorSubject.js:46
ActionsSubject.next @ store.es5.js:126
Store.dispatch @ store.es5.js:402
(anonymous) @ messageDialog.ts:43
SafeSubscriber.__tryOrUnsub @ Subscriber.js:239
SafeSubscriber.next @ Subscriber.js:186
Subscriber._next @ Subscriber.js:127
Subscriber.next @ Subscriber.js:91
MapSubscriber._next @ map.js:85
Subscriber.next @ Subscriber.js:91
Subject.next @ Subject.js:56
(anonymous) @ dialog.es5.js:380
SafeSubscriber.__tryOrUnsub @ Subscriber.js:239
SafeSubscriber.next @ Subscriber.js:186
Subscriber._next @ Subscriber.js:127
Subscriber.next @ Subscriber.js:91
TakeSubscriber._next @ take.js:83
Subscriber.next @ Subscriber.js:91
FilterSubscriber._next @ filter.js:90
Subscriber.next @ Subscriber.js:91
schedulerFn @ core.js:4223
SafeSubscriber.__tryOrUnsub @ Subscriber.js:239
SafeSubscriber.next @ Subscriber.js:186
Subscriber._next @ Subscriber.js:127
Subscriber.next @ Subscriber.js:91
Subject.next @ Subject.js:56
EventEmitter.emit @ core.js:4203
MatDialogContainer._onAnimationDone @ dialog.es5.js:259
(anonymous) @ index.d.ts.MatDialogContainer.html:1
handleEvent @ core.js:13256
callWithDebugContext @ core.js:14741
debugHandleEvent @ core.js:14328
dispatchEvent @ core.js:9705
(anonymous) @ core.js:10319
(anonymous) @ animations.js:340
ZoneDelegate.invoke @ zone.js:392
onInvoke @ core.js:4630
ZoneDelegate.invoke @ zone.js:391
Zone.run @ zone.js:142
NgZone.run @ core.js:4447
AnimationRendererFactory.scheduleListenerCallback @ animations.js:340
(anonymous) @ animations.js:727
(anonymous) @ browser.js:99
(anonymous) @ browser.js:99
(anonymous) @ browser.js:5735
WebAnimationsPlayer._onFinish @ browser.js:5735
(anonymous) @ browser.js:5788
ZoneDelegate.invokeTask @ zone.js:425
Zone.runTask @ zone.js:192
ZoneTask.invokeTask @ zone.js:499
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
VM13669:2 [Deprecation] 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
derez @ VM13669:2
derez @ VM13669:2
derez @ VM13669:2
derez @ VM13669:2
derez @ VM13669:2
derez @ VM13669:2
derez @ VM13669:2
derez @ VM13669:2
derez @ VM13669:2
derez @ VM13669:2
derez @ VM13669:2
derez @ VM13669:2
derez @ VM13669:2
derez @ VM13669:2
derez @ VM13669:2
derez @ VM13669:2
derez @ VM13669:2
derez @ VM13669:2
derez @ VM13669:2
derez @ VM13669:2
derez @ VM13669:2
derez @ VM13669:2
derez @ VM13669:2
decycle @ VM13669:2
e.stringify @ VM13669:1
stringify @ VM13669:1
toContentScript @ VM13669:1
sendMessage @ VM13669:1
DevtoolsExtension.notify @ store-devtools.es5.js:184
StoreDevtools.applyOperators.state @ store-devtools.es5.js:566
ScanSubscriber._tryNext @ scan.js:114
ScanSubscriber._next @ scan.js:107
Subscriber.next @ Subscriber.js:91
WithLatestFromSubscriber._next @ withLatestFrom.js:116
Subscriber.next @ Subscriber.js:91
Notification.observe @ Notification.js:32
ObserveOnSubscriber.dispatch @ observeOn.js:95
AsyncAction._execute @ AsyncAction.js:119
QueueAction.execute @ QueueAction.js:37
AsyncScheduler.flush @ AsyncScheduler.js:38
QueueAction.schedule @ QueueAction.js:31
Scheduler.schedule @ Scheduler.js:46
ObserveOnSubscriber.scheduleMessage @ observeOn.js:99
ObserveOnSubscriber._next @ observeOn.js:102
Subscriber.next @ Subscriber.js:91
MergeMapSubscriber.notifyNext @ mergeMap.js:151
InnerSubscriber._next @ InnerSubscriber.js:25
Subscriber.next @ Subscriber.js:91
MapSubscriber._next @ map.js:85
Subscriber.next @ Subscriber.js:91
MergeMapSubscriber.notifyNext @ mergeMap.js:151
InnerSubscriber._next @ InnerSubscriber.js:25
Subscriber.next @ Subscriber.js:91
SkipSubscriber._next @ skip.js:47
Subscriber.next @ Subscriber.js:91
Subject.next @ Subject.js:56
BehaviorSubject.next @ BehaviorSubject.js:46
ActionsSubject.next @ store.es5.js:126
Store.dispatch @ store.es5.js:402
(anonymous) @ messageDialog.ts:43
SafeSubscriber.__tryOrUnsub @ Subscriber.js:239
SafeSubscriber.next @ Subscriber.js:186
Subscriber._next @ Subscriber.js:127
Subscriber.next @ Subscriber.js:91
MapSubscriber._next @ map.js:85
Subscriber.next @ Subscriber.js:91
Subject.next @ Subject.js:56
(anonymous) @ dialog.es5.js:380
SafeSubscriber.__tryOrUnsub @ Subscriber.js:239
SafeSubscriber.next @ Subscriber.js:186
Subscriber._next @ Subscriber.js:127
Subscriber.next @ Subscriber.js:91
TakeSubscriber._next @ take.js:83
Subscriber.next @ Subscriber.js:91
FilterSubscriber._next @ filter.js:90
Subscriber.next @ Subscriber.js:91
schedulerFn @ core.js:4223
SafeSubscriber.__tryOrUnsub @ Subscriber.js:239
SafeSubscriber.next @ Subscriber.js:186
Subscriber._next @ Subscriber.js:127
Subscriber.next @ Subscriber.js:91
Subject.next @ Subject.js:56
EventEmitter.emit @ core.js:4203
MatDialogContainer._onAnimationDone @ dialog.es5.js:259
(anonymous) @ index.d.ts.MatDialogContainer.html:1
handleEvent @ core.js:13256
callWithDebugContext @ core.js:14741
debugHandleEvent @ core.js:14328
dispatchEvent @ core.js:9705
(anonymous) @ core.js:10319
(anonymous) @ animations.js:340
ZoneDelegate.invoke @ zone.js:392
onInvoke @ core.js:4630
ZoneDelegate.invoke @ zone.js:391
Zone.run @ zone.js:142
NgZone.run @ core.js:4447
AnimationRendererFactory.scheduleListenerCallback @ animations.js:340
(anonymous) @ animations.js:727
(anonymous) @ browser.js:99
(anonymous) @ browser.js:99
(anonymous) @ browser.js:5735
WebAnimationsPlayer._onFinish @ browser.js:5735
(anonymous) @ browser.js:5788
ZoneDelegate.invokeTask @ zone.js:425
Zone.runTask @ zone.js:192
ZoneTask.invokeTask @ zone.js:499
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566

**Comment by brandonroberts** [comment]
Using navigation action is up to you. They were added to the migration document from users of router-store 2.x. If you're using `ngrx-store-freeze`, dispatching an action with the `ActivatedRoute` causes the same issues as it is a complex mutable object.

**Comment by alvipeo** [comment]
that's what I thought. thank you.
