### ISSUE TITLE
Type 'string' cannot be used to index type 'EffectsMetadata<T>'

### ISSUE THREAD

**Issue by alex-okrushko** [ngrx/platform#623]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

I'm syncing the latest ngrx into Google and I'm getting the build error: 

 metadata[propertyName] = { dispatch };
       ~~~~~~~~~~~~~~~~~~~~~~
third_party/javascript/ngrx/modules/effects/src/effects_metadata.ts(56,5): error TS2536: Type 'string' cannot be used to index type 'EffectsMetadata<T>'.

## Expected behavior:
<!-- Describe what the desired behavior would be. -->

I think it doesn't like the fact that propertyName cannot be narrowed down to keyof T.
The fix would be to use less fancy Indexable EffectsMetadata, e.g. this works:

```
export type EffectsMeta = {
  [key: string]:
    | undefined
    | {
        dispatch: boolean;
      }
};
```

The other option is to use ES6 Map altogether instead of Indexable.

Thoughts?

## Minimal reproduction of the problem with instructions:
<!--
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
http://plnkr.co/edit/tpl:757r6L
-->

## Version of affected browser(s),operating system(s), npm, node and ngrx:

## Other information:

**Comment by brandonroberts** [comment]
The first option seems reasonable to me. Is this error specific to closure compiler and how can we reproduce it?

**Comment by alex-okrushko** [comment]
@brandonroberts thanks for a quick reply.

I don't think it's about closure compiler. It's failing during "Compiling Angular templates (ngc)" in the project that is using ngrx v4.

Also, someone already discovered this exact issue (https://github.com/ngrx/platform/issues/518) which was also happening during ngc, but closed it assuming the fix was in uglify.

**Comment by brandonroberts** [comment]
@alex-okrushko is this still an issue?

**Comment by alex-okrushko** [comment]
yes it is. I've done Local Mod for now to get it into Google.
I can probably change it here as well sometime next week.
