### ISSUE TITLE
Maps/Sets can't be viewed in devtools

### ISSUE THREAD

**Issue by berwyn** [ngrx/platform#632]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

As noted in ngrx/store-devtools#64 and ngrx/store-devtools#67 using an ES2015 Set or Map works well enough in ngrx, but the devtools won't display the object instead showing an empty object (`{ }`) when it's first set, and omitting the object in diffs. Additionally, when looking at the graph of the store, the Set/Map will show up as a node, but have no associated value.

## Expected behavior:

Devtools should show that a Set/Map was used, and that it was updated as a result of an action.

## Minimal reproduction of the problem with instructions:

given:
```ts
StoreDevtoolsModule.instrument({ maxAge: 50 })
```
and
```ts
interface MyState {
    data: Map<string, Item>;
}
```
any reducer that updates this field will succeed, however this property will not be displayed correctly in the devtools, and will not exist in diffs.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
`yarn@1.0.1`
`node@7.10.1`
`@ngrx/store@4.1.1`
`@ngrx/effects@4.1.1`
`@ngrx/store-devtools@4.1.1`

## Other information:
Based on the other bugs, it seems that the devtools extension may have a `serialize` argument that may alleviate this, however passing this to ngrx doesn't seem to do anything different, so I'm unsure if there's work on the ngrx side to support this.

**Comment by brandonroberts** [comment]
The `serialize` option is already being passed to the Devtools as `false`. The extension itself does not show Map/Set unless you provide a toJSON patch. See https://github.com/zalmoxisus/redux-devtools-extension/issues/124

**Comment by vincenzovitale** [comment]
Thanks @berwyn , you saved the day! :)

**Comment by Maks-Yaremenko** [comment]
@berwyn Thank you, buddy!

**Comment by MaciejCaputa** [comment]
It looks like the `{Map, Set}#toJSON` method has been rejected by TC39 and removed from core-js in v3.0.0.
Shouldn't the extension handle displaying maps and sets itself?

**Comment by Zarepheth** [comment]
A manually implemented poly fill may also work: [Store-DevTools #64](https://github.com/ngrx/store-devtools/issues/64#issuecomment-314889392)

```typescript
if (environment.envName === 'dev') {
  (Map.prototype as any).toJSON = function () {
    return JSON.parse(JSON.stringify([...this]));
  };
}
```

**Comment by prewk** [comment]
Here's a simple one for Sets:

```ts
  (Set.prototype as any).toJSON = function() {
    return Array.from(this);
  };
```

**Comment by jdavault** [comment]
import { legacy_createStore as createStore, applyMiddleware } from "redux";
import reducers, { initialState } from "./reducers";
import thunkMiddleware from "redux-thunk";
import { composeWithDevTools } from "@redux-devtools/extension";

const composeEnhancers = composeWithDevTools({ serialize: true });

export const store = createStore(
  reducers,
  initialState,
  composeEnhancers(applyMiddleware(thunkMiddleware))
);

//WORKED FOR ME ....
