### ISSUE TITLE
runtime error after AOT compilation

### ISSUE THREAD

**Issue by phra** [ngrx/platform#637]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

if you compile your application with AOT you will get a runtime error not happening with the normal build.

## Expected behavior:

same execution flow as not AOT one.

## Version of affected browser(s),operating system(s), npm, node and ngrx:

```
╭─phra at kali in /home/phra/git/bloqmanager (build/aot ✚4)
╰─λ grep ngrx package.json                                                                                                                                      0 < 13:14:12
    "@ngrx/effects": "^4.1.1",
    "@ngrx/router-store": "^4.1.1",
    "@ngrx/store": "^4.1.1",
    "@ngrx/store-devtools": "^4.1.1",
    "ngrx-store-localstorage": "^0.3.0",
    "ngrx-store-logger": "^0.2.0",
```

## Other information:
![screenshot from 2017-12-08 13-13-20](https://user-images.githubusercontent.com/984628/33765613-f915b98a-dc19-11e7-934b-b25ff1cbff70.png)

**Comment by phra** [comment]
https://github.com/ngrx/platform/blob/master/docs/store/api.md#initial-state-and-ahead-of-time-aot-compilation

**Comment by phra** [comment]
ok i've updated my code following the wiki page linked above but i still get errors.. trying to debug further..

**Comment by phra** [comment]
i've managed to fix my project. closing this.

**Comment by dheeraja00** [comment]
@phra is it possible for you to paste your reducer & app.module code here, I am struggling to solve this issue

**Comment by phra** [comment]
@dheeraja00 you can follow the example app in this repo.
