### ISSUE TITLE
ngrx for communicating  ng1 and ng5 side-by-side applications 

### ISSUE THREAD

**Issue by dankrz** [ngrx/platform#639]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ x] Support request
</code></pre>

## Expected behavior:

Hello all,

I would like to ask if it possible to share on state between two separate apps one in ng1 and another in ng5. They are not connected with downgrade mechanism.

Best regard,
Krzysztof

**Comment by brandonroberts** [comment]
This isn't possible out of the box without the downgrade to link the apps. You'd have to create some synching mechanism between the two apps.

**Comment by alex-okrushko** [comment]
Having two separate apps doesn't make a lot of sense to me. You'd want eventually to have the whole app as Angular, right?

If they are connected via downgrade it's possible to use Store in angularjs. In fact, that's what we do for Firebase console.

here is an example (code that we have differs a bit, but general idea is the same):

```typescript
// store_service.ts
export class StoreService {
  static NG_NAME = 'storeService';

  private storePromise: ng.IPromise<Store<GlobalState>>;
  private resolveStorePromise: (store: Store<GlobalState>) => void;

  /**
   * @ngInject
   */
  constructor($q: ng.IQService) {
    this.storePromise = $q((resolve) => this.resolveStorePromise = resolve);
  }

  setStore(store: Store<GlobalState>) {
    this.resolveStorePromise(store);
  }

  /**
   * redirect dispatch to the store.
   */
  dispatch(action: Action) {
      this.storePromise.then(store => store.dispatch(action));
    }
 }
```

Wiring of the store service in angularjs:
```typescript
// store_module.ts
export const storeModule =
    angular
        .module('firebase.console.storemodule')
        .service(StoreService.NG_NAME, StoreService);
```

Now providing and setting the store in the Angular. This is the main module that is being downgraded into angularjs app (via `downgradeModule(AppModuleNgFactory)`)
```typescript
// app_module.ts

// we have it in a separate file.
export function firealertsServiceFactory(
    injector: ng.auto.IInjectorService, store: Store<GlobalState>) {
  const service = injector.get<StoreService>(StoreService.NG_NAME);
  service.setStore(store); // passing the store here.
  return service;
}

@NgModule({
  imports: [
    ... // our imports
  StoreModule.forRoot({}),
  ],
  providers: [{
    provide: StoreService,
    useFactory: storeServiceFactory,
    deps: ['$injector', Store]
  }],
})
export class AppModule {
  constructor() {}
  ngDoBootstrap() {}
}
```

**Comment by brandonroberts** [comment]
@alex-okrushko I agree that using the downgrade module is the best option
