### ISSUE TITLE
No exported member _initialStateFactory and _INITIAL_STATE in nightly-builds

### ISSUE THREAD

**Issue by axtho** [ngrx/platform#64]
#### Bug, feature request, or proposal:
BUG

#### What is the expected behavior?
Nightlies should compile

#### What is the current behavior?
running `ngc` produces this:

```
Error at /Applications/MAMP/htdocs/memberhive2/core/node_modules/@ngrx/store/store.d.ts:11:10: Module '"/Applications/MAMP/htdocs/memberhive2/core/node_modules/@ngrx/store/src/store_module"' has no exported member '_initialStateFactory'.
Error at /Applications/MAMP/htdocs/memberhive2/core/node_modules/@ngrx/store/store.d.ts:12:10: Module '"/Applications/MAMP/htdocs/memberhive2/core/node_modules/@ngrx/store/src/tokens"' has no exported member '_INITIAL_STATE'.
```

Looking at the source files there is indeed no function of that kind. 
What gives?

#### What are the steps to reproduce?
Pulling from nightlies and compiling any code with ngc.

#### Which versions of Angular, NGRX, OS, TypeScript, CLI, browsers are affected?
```
TS: 2.4.1
@angular/cli: 1.2.0
node: 8.1.3
os: darwin x64
@angular/animations: 4.2.6
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.2.6
@angular/compiler: 4.2.6
@angular/core: 4.2.6
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 4.2.6
@angular/http: 4.2.6
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.2.6
@angular/platform-browser-dynamic: 4.2.6
@angular/router: 4.2.6
@angular/cli: 1.2.0
@angular/compiler-cli: 4.2.6
@angular/platform-server: 4.2.6

```

#### Is there anything else we should know?
It was this last commit that did not include it properly: https://github.com/ngrx/store-builds/commit/b916d040c3790f102e2c2bbe0f56f54ae01d8d30

**Comment by SomilKumar** [comment]
Having the same issue with running ng-serve with the latest npm install of nightly builds.

**Comment by axtho** [comment]
you can get around it by pulling the nightly at the last commit, like so:
`"@ngrx/store": "github:ngrx/store-builds#745395b9775965e1bfcddaabece172f9f556d794",`

**Comment by SomilKumar** [comment]
@axtho thanks that did worked.

**Comment by strangesast** [comment]
You need TypeScript 2.4.x and RxJS 5.4.x (ngrx/effects#167, ngrx/store#439)
