### ISSUE TITLE
What are required workspace/cli updates, if libs are in separate repository  

### ISSUE THREAD

**Issue by netwobble** [ngrx/platform#640]
## I'm submitting a... Question

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X ] Feature request
[X ] Documentation issue or request
</code></pre>

## What is the current behavior?
We would like to have libs in separate repositories with different owners and then projects clone the lib to each project. 

The question is ... Once doing this, what configurations are necessary in the workspace to wire things up.

Example
Workspace 1
   - app 1
  - app 2
Libs
  - lib 1
  - lib 2 (from second repository)

Workspace 2 (maintained by separate team)
  - lib 2

## Other information:
Really just a question or documentation.

Cheers,

**Comment by brandonroberts** [comment]
I think you meant to open this issue over at https://github.com/nrwl/nx
