### ISSUE TITLE
Using store-devtools in "logOnly" mode in production

### ISSUE THREAD

**Issue by akrueger** [ngrx/platform#643]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ X ] Documentation issue or request
</code></pre>

My goal is to send error reports with a redux state history to my server as part of our logging service in production. I have no problem sending the current state at the time of the error, but what I'd really like is something that looks like the `state.json` object that the `redux-devtools-extension` allows you to download. With an object like that with a max age (say 5 to keep performance in a good spot), I could take the data from my server log and upload the state into the `redux-devtools-extension`; then replay the state back to see how users have managed to get into their error state. 

I don't need to use any of the features that can manipulate the state--JUMP, SKIP, PAUSE, COMMIT, etc--I'd want to avoid that completely in production. I have read about the extension's [production modes](https://github.com/zalmoxisus/redux-devtools-extension#14-using-in-production) that have `logOnly` as well as [this article](https://medium.com/@zalmoxis/using-redux-devtools-in-production-4c5b56c5600f).

I am not sure how this is best achieved in my Angular ngRx app. Is there a way for me to achieve this using `store-devtools`. Should I be using some other type of meta-reducer similar to the `enhancer`?

I saw the options for sanitizing actions and serializing state, but I'm more interested in a setting for `logOnly` and accessing the data in my error handling that could be read back into `redux-devtools-extension` for error analysis from our logs.

https://github.com/ngrx/store-devtools/issues/53#issuecomment-279043936 addresses use in production and seems to indicate that there is no `logOnly` option, but I didn't want to give up just on that assumption: 

> The devtools allow external users to look at and potentially manipulate the state of your application.

Thanks!

**Comment by akrueger** [comment]
Thanks a lot!

As a follow-up to this:

Is it possible to access the `liftedState` of @ngrx/store-devtools from the client application? This lifted state seems akin to the `state.json` object that is imported/exported by Redux Dev Tools. Since I want to log that at the point of an error, I'm trying to figure out the best way of accessing that at runtime when there is an error.

**Comment by brandonroberts** [comment]
@akrueger you can inject the `StoreDevtools` to access the `lifedState` property that is an Observable of the current lifted state.

**Comment by akrueger** [comment]
@brandonroberts Thanks, worked perfectly!

**Comment by akrueger** [comment]
I'm having some trouble figuring out the exact effects of including `logOnly: true`.

- What specifically is `logOnly` doing? I had assumed it was setting all features to false, but it doesn't appear to be true
- Even when I set all features to false, I still seem to be able to jump, skip, commit, etc

Below are my results of the Redux DevTools extension in development environment, production environment with logOnly, and production with logOnly and all features set to false:

Development environment:

![screen shot 2018-01-24 at 12 58 30](https://user-images.githubusercontent.com/1644520/35351538-cae695f4-0106-11e8-9635-3aabd8df8082.png)

<img width="959" alt="screen shot 2018-01-24 at 12 46 12" src="https://user-images.githubusercontent.com/1644520/35351519-bb6744ca-0106-11e8-9a8f-8f01c7cf7012.png">

Production with logOnly:

![screen shot 2018-01-24 at 12 58 30](https://user-images.githubusercontent.com/1644520/35351546-d1631420-0106-11e8-9725-b11987ed414e.png)

<img width="962" alt="screen shot 2018-01-24 at 12 46 27" src="https://user-images.githubusercontent.com/1644520/35351565-dc674cf6-0106-11e8-9347-12d3f8dcebf6.png">

Production with logOnly and all features set to false:

![screen shot 2018-01-24 at 12 58 06](https://user-images.githubusercontent.com/1644520/35351592-ea1d3982-0106-11e8-8390-0b368abe0350.png)

<img width="959" alt="screen shot 2018-01-24 at 12 52 47" src="https://user-images.githubusercontent.com/1644520/35351600-ef828cb0-0106-11e8-849d-32a1fba74c13.png">

Thanks!

**Comment by brandonroberts** [comment]
`logOnly` set the features to match these settings https://github.com/zalmoxisus/redux-devtools-extension/blob/master/npm-package/logOnly.js#L8

The `features` property is there only if you want to provide your own settings. Setting `features` to `false` enables all extension settings as documented here https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#features

**Comment by yfain** [comment]
I use this:
```
StoreDevtoolsModule.instrument({
  logOnly: environment.production
})
```
Supposedly, if the` logOnly` flag is true, your app will connect to the Redux DevTools extension in a log only mode, it'll have very little overhead as it shouldn't store the state data, but only log the action names that are happening during the runtime.

But in my experiments, I still see the state data in the ngrx DevTools panel, so what're the benefits of using `logOnly:true`?

**Comment by mtj8033** [comment]
Agreed this doesn't appear to be working properly, I can still execute all other actions atm
