### ISSUE TITLE
Typo in store-devtools README

### ISSUE THREAD

**Issue by RobertMonks** [ngrx/platform#647]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## What is the current behavior?
There is a typo in the ReadMe for the store-devtools

## Expected behavior:
Instead of it saying "the monitor function configuration that you what to hook," it should say "the monitor function configuration that you want to hook."  

## Minimal reproduction of the problem with instructions:
Go into the README.md file in the platform/docs/store-devtools folder to find the typo

**Comment by brandonroberts** [comment]
Thanks @RobertMonks. It would be great if could you open a PR to fix this.

**Comment by RobertMonks** [comment]
Okay, I will do that shortly.

**Comment by warapitiya** [comment]
@RobertMonks You have to create a fork from this repo and create a branch on it. And then put a PR to this repo. https://help.github.com/articles/working-with-forks/

**Comment by brandonroberts** [comment]
@RobertMonks sure. You can edit and create a pull request directly in Github. Just go here https://github.com/ngrx/platform/blob/master/docs/store-devtools/README.md and click the pencil icon to edit.

Down in the "Commit Changes" section, add a commit message and save the changes and it will fork for you, then you can create a pull request using that patch that will link back to this repo.

**Comment by RobertMonks** [comment]
@warapitiya @brandonroberts 
Thank you both for the information and tips to resolve this issue.  
Created PR for it: https://github.com/ngrx/platform/issues/647

**Comment by brandonroberts** [comment]
Fixed via #651
