### ISSUE TITLE
Add payload to Action interface

### ISSUE THREAD

**Issue by AhnpGit** [ngrx/platform#649]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
At the latest version of ngrx/store, there is no payload in Action interface

## Expected behavior:
It would be nice if payload is define in Action interface as optional attribute to be similar to Redux library.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
Operating system: Windows 10
npm: 5.6.0
node: 8.9.3
@ngrx/store: 4.1.1

**Comment by brandonroberts** [comment]
This issue has already been discussed at length and the Action interface will not have the payload.
