### ISSUE TITLE
Change detection issue with NaN value using select API

### ISSUE THREAD

**Issue by MonkeyMagiic** [ngrx/platform#650]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ x] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

Selector will fire for each notification if retrieved value is NaN, although this is the expected behavior of the distinctUntilChanged() in an application with frequent updates (in our case 300 updates a second) this can cause considerable performance impact. 

NaN !== NaN is a well known case and you can not compare previous and current values without the provided Number.isNaN or less trusted isNaN browser API. 

## Expected behavior:

When value retrieved by selector is NaN and previous retrieved value is NaN selector should not fire.

**Comment by randallmeeker** [comment]
seeing this too. Thanks for reporting @MonkeyMagiic This happens a lot when using router-store look for an ID

**Comment by robwormald** [comment]
As we're just using Rx's `distinctUntilChanged()` API directly, this should probably be reported to https://github.com/reactivex/rxjs ?
