### ISSUE TITLE
Model's getters and functions

### ISSUE THREAD

**Issue by wis-gss** [ngrx/platform#652]
Hi everyone.
I hope you can help me to clarify one moment of getting data from store.
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ x] Documentation issue or request
</code></pre>

I have a model like this:
<pre><code>
export class UserModel {
  title: string;
  firstName: string;
  lastName: string;
  constructor(data: any = {}) {
    this.title = data.title || 'Mr.';
    this.firstName = data.firstName || 'Robin';
    this.lastName = data.lastName || 'Smith'
  }
  
  get fullName: string {
    return this.title + ' ' + this.firstName + ' '  + this.lastName;
  }
}
</code></pre>

And when I try to get the `firstName` on view - everything is OK.
But I can't get `fullName`.

I try something like this:
<pre><code>
// It works
<p>{{ (user | async).fistName }}</p>
// It doesn't
<p>{{ (user | async).fullName }}</p> 
</code></pre>

Do you have any suggestions?

Best regards, Svyatoslav

**Comment by brandonroberts** [comment]
Support questions should be asked on stackoverflow or in the [gitter channel](https://gitter.im/ngrx/platform)
