### ISSUE TITLE
Entity Adapter updateOne strips getters / setters

### ISSUE THREAD

**Issue by randallmeeker** [ngrx/platform#657]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x?] Bug report  
[x?] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
Currently when using the entity adapter, `updateOne` will strip getters and setters.

## Expected behavior:
It should preserve the getters and setters on one or both of the objects being merged.

## Minimal reproduction of the problem with instructions:
https://stackblitz.com/edit/angular-x9wfbv
The example above sets up a store, loads test widgets, and then updates one with the adapter method and updates the second one without using the adapter to show desired behavior. 

## Version of affected browser(s),operating system(s), npm, node and ngrx:
@ngrx 4.1.1

**Comment by MikeRyanDev** [comment]
@ngrx/entities assumes that you are working with both serializable state and entities. Getters and setters cannot be serialized.
