### ISSUE TITLE
Error combineReducers with AOT

### ISSUE THREAD

**Issue by yamidvo** [ngrx/platform#659]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## What is the current behavior?
I have this error in AOT compilation:
`ERROR in src/app/app.module.ts(31,25): Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'combineReducers' was called in 'rootReducer'
    'rootReducer' calls 'combineReducers' at src/app/store/reducers/root.reducer.ts(20,16).`

## Minimal reproduction of the problem with instructions:
This is my root.reducer:
<pre><code>
import { ActionReducerMap, combineReducers } from '@ngrx/store';

import { storeTypesReducer as storeTypes } from './models/available/store-types.reducer';
import { currentStoreType } from './models/current-store-type.reducer';
import { storeZoneIdCollection } from './models/store-zone-id-collection.reducer';
import { storesReducer as stores } from './models/available/stores.reducer';
import { categories } from './models/categories.reducer';
import { paginatedStoresReducer as paginatedStores } from './models/available/paginated-stores.reducer';
import { userReducer as user } from './global/user.reducer';

const available = combineReducers({
  categories,
  storeTypes,
  storeZoneIdCollection,
  stores,
  paginatedStores
});

const models = combineReducers({
  currentStoreType,
  available
});

const global = combineReducers({
  user
});

const reducers: ActionReducerMap<any> = {
  models: models,
  global: global
};

export const rootReducer = reducers;
</code></pre>
## Version of affected browser(s),operating system(s), npm, node and ngrx:
@ngrx/core: 1.2.0,
@ngrx/effects: 4.1.1,
 @ngrx/store: 4.1.1,
@angular: 5.1.1

**Comment by brandonroberts** [comment]
You use a reducer token if you're generating reducers by calling a function. https://github.com/ngrx/platform/blob/master/docs/store/api.md#injecting-reducers
