### ISSUE TITLE
Many ngrx github issues deleted

### ISSUE THREAD

**Issue by nmai** [ngrx/platform#665]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ x] Documentation issue or request
</code></pre>

## What is the current behavior?

There are a lot of github issues being deleted. It has happened at least a dozen times so far - I'll search google for an ngrx-related problem I am having, several github issues are the top results and they look very promising, but I get a 404 page.

## Expected behavior:

Pretty sure the issues weren't deleted intentionally, probably something got renamed or migrated, but the end result is the same. With the current state of documentation (most of what you can find on the web is related to ngrx 2.0), devs need all the info they can get :)

## Minimal reproduction of the problem with instructions:

If you search for a phrase like "effectsmodule run" (I guess .run was removed in 4.0 because it gives me a not found error), you'll probably see some github issues as the top results. Check them out - they will be nonexistent.

**Comment by fxck** [comment]
It's probably because the issue section of store was closed. Which I think was not a good idea. Some good discussions were lost.

**Comment by nmai** [comment]
@fxck thanks for clarifying 👍 

we can close this issue anytime, just wanted to bring it to everyone's attention. I'm not sure if there's anything that can be done to recover the lost discussions, and eventually Google will purge those results if it hasn't already. 

there's still not exactly loads of documentation out there for ngrx (especially up-to-date info) so I think in the future we shouldn't be too quick to get rid of any resources that devs can use, even if it doesn't appear to be super relevant. great framework by the way- big thanks to the folks behind this project.
