### ISSUE TITLE
RouterStore navigates to url undefined

### ISSUE THREAD

**Issue by msterba** [ngrx/platform#668]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

The `RouterStateUrl` requires to have the property `url` in it. If it doesn't, `StoreRouterConnectingModule.navigateIfNeeded()` redirects to `undefined`.

In my minimal repro this results in an UrlParser error, the larger app which the minimal repo was derived from, just failed silently.

## Expected behavior:

Unless there is a use case where `redirectToUrl(undefined)` is a desired behaviour, navigateIfNeeded should throw or at least log a warning. Or at least the documentation could mention it. I thought RouterStateUrl could have the structure **I** need.

## Minimal reproduction of the problem with instructions:

I hope stackblitz apps are okay. https://stackblitz.com/edit/msterba-ngrx-devtools-vs-storemodule

## Version of affected browser(s),operating system(s), npm, node and ngrx:

The problem seems to be browser independent, tested on Chrome, Firefox and Brave (all latest)
Linux Ubuntu 17.10
node 9.2.1
npm 5.6.0
ngrx: 4.1.1

**Comment by brandonroberts** [comment]
The documentation states this explicitly here. https://github.com/ngrx/platform/blob/master/docs/router-store/api.md#custom-router-state-serializer

If you don't need the navigation based on state changes. Change the name of your router reducer key
