### ISSUE TITLE
Using withLatestFrom and dispatching multiple actions with forEach errors: cannot read property 'actionsObserver' of undefine

### ISSUE THREAD

**Issue by orangesoup** [ngrx/platform#669]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

I've been dispatching multiple actions like this before:

```ts
      [
        new x.X(this._query),
        new x.Y(this._query)
      ].forEach(this.store.dispatch);
```

Which worked just fine, until I've added `withLatestFrom` to the effects like this:

```ts
  @Effect()
  x$ = this.actions$
    .ofType(X)
    .pipe(
    withLatestFrom(this.state$),
    map(([action, state]: ([X, fromRoot.State])) => {
      return { query: action.payload, category: state.category.id };
    }),
    exhaustMap(req =>
      this.service
        .x(req)
        .pipe(
        map(resp => new xSuccess(resp)),
        catchError(err => of(new xFailure()))
        )
    )
    );

  @Effect()
  y$ = this.actions$
    .ofType(Y)
    .pipe(
    withLatestFrom(this.state$),
    map(([action, state]: ([Y, fromRoot.State])) => {
      return { query: action.payload, category: state.category.id };
    }),
    exhaustMap(req =>
      this.service
        .y(req)
        .pipe(
        map(resp => new ySuccess(resp)),
        catchError(err => of(new yFailure()))
        )
    )
    );
```

The error is: `ERROR TypeError: Cannot read property 'actionsObserver' of undefine`

Note that doing 2 separate dispatches of the same actions works just fine, it's only the forEach way that doesn't work.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
Latest.

I don't really have time to put together a demo now, but if it's needed I can do it a couple days later.

**Comment by brandonroberts** [comment]
Please provide a reproduction using stackblitz or plunker. Also, check the scope of the `forEach` if you expand the callback.

```ts
[action1, action2].forEach(action => this.store.dispatch(action));
```

**Comment by orangesoup** [comment]
@brandonroberts Yeah, sorry, my bad. Changing `forEach(this.store.dispatch)` to `forEach(action => this.store.dispatch(action))` works. Must've been tired.

**Comment by kdshop** [comment]
> Please provide a reproduction using stackblitz or plunker. Also, check the scope of the `forEach` if you expand the callback.
> 
> ```ts
> [action1, action2].forEach(action => this.store.dispatch(action));
> ```

https://github.com/ngrx/platform/issues/468#issuecomment-335797420
