### ISSUE TITLE
Entity: Update type should be provided from top level import.

### ISSUE THREAD

**Issue by sandangel** [ngrx/platform#670]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

Currently Update type for type checking updateMany and updateOne methods of entity adapter is only available in deep import `import {Update} from '@ngrx/entity/src/models'`
## Expected behavior:

It should be provided as top level import

```ts
      import {Update} from '@ngrx/entity';

      // ...
      const updates: Update[] = action.payload.map(item => ({id: item.unixTime, changes: item}));
      return {
        ...adapter.updateMany(updates, state),
        loading: false,
        loaded: true,
        errorMess: null,
      };

```

**Comment by brandonroberts** [comment]
Seems reasonable. Care to submit a PR?

**Comment by sandangel** [comment]
sure.

**Comment by shhdgit** [comment]
I think this #675  should release a version if docs is updated.
