### ISSUE TITLE
Entity: selectMap

### ISSUE THREAD

**Issue by undsoft** [ngrx/platform#673]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
</code></pre>

## Expected behavior:
Wouldn't it be better if selectEntities returned a Map? This way one could get both of the two worlds: guaranteed order and id keys.

**Comment by brandonroberts** [comment]
Order is guaranteed by the `ids` and if you want to create a Map from the entities you can do so in your composed selector.

**Comment by undsoft** [comment]
I understand that I can do it myself right now. This is why it's a feature request.
Whouldn't be easier to just have a map?

**Comment by brandonroberts** [comment]
Not necessarily. Currently, we're returning a dictionary of entities by id from the store, which is serializable out of the box. A Map isn't serializable, so we'd have to break the existing interface which isn't worth it in my opinion. If you want to use a map, compose a selector to create one.
