### ISSUE TITLE
Question: handle potential action types conflicts

### ISSUE THREAD

**Issue by sebastien-p** [ngrx/platform#676]
Hello,

First of all, thanks for the good work!

Now I have a question (full disclaimer: I'm relatively new to "Redux") about handling potential action types conflicts: because action types should be strings, why not allow them to not only be string literals but also `String` instances?

Reducers would work the same, Redux DevTools would work the same and we could make sure to have "unique" action types I guess.

I tried tricking TypeScript via type casting and the only thing that went wrong was because of this line: https://github.com/ngrx/platform/blob/95dd2dc2c870477572784044b0be46a2876ef43b/modules/effects/src/effect_notification.ts#L68

What do you think?

**Comment by brandonroberts** [comment]
Using a string instance would provide a `typeof` of `object`, which would go against the required type for the action type. Also this doesn't work will TypeScript enums for action types.
