### ISSUE TITLE
provideMockActions export missing in 5.x?

### ISSUE THREAD

**Issue by ryzy** [ngrx/platform#678]
## I'm submitting a...
<pre><code>
[x] Regression (worked in 4.x, stopped working in 5.x alpha (nightly build))
[x] Documentation issue or request
</code></pre>

## What is the current behavior?
Export of `provideMockActions` from `@ngrx/effects/testing` is missing.

## Expected behavior:
In 4.x version I can do:
```
import { provideMockActions } from '@ngrx/effects/testing';
```
and then use it to provide `Actions` in my unit tests.

## Minimal reproduction of the problem with instructions:
Following current Effects testing documentation from https://github.com/ngrx/platform/blob/master/docs/effects/testing.md and doing
```
import { provideMockActions } from '@ngrx/effects/testing';
```
...results with error `TS2305: Module '"/node_modules/@ngrx/effects/testing"' has no exported member 'provideMockActions'`.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
`ngrx/effects-builds` (currently 5.0.0-alpha.0).

## Other information:
I can see that the *example-app* in the master branch already has been adjusted and uses different approach, using `TestActions` and factory for it.

For someone coming from 4.x, at first glance it seems like a bit more boilerplate code but I see the benefits: more flexibility in terms of what actions are dispatched, marble testing etc.

I guess, going forward, that will be recommended approach going forward. If so, then this issue is about documentation update.

On the other side, we could still export `provideMockActions` (which still exists somewhere in `@ngrx/effects/testing/src/testing`) but mark it as deprecated. With it, users will have more smooth upgrade experience and have some more time to rewrite their tests.

What are your thoughts on that?

**Comment by MikeRyanDev** [comment]
This is definitely a regression. No intention of removing `provideMockActions`.

**Comment by ryzy** [comment]
Good :)

BTW maybe we should add the `TestActions` class to `@ngrx/effects/testing` as well? I see people use that same code, so we could reduce some boilerplate code?

**Comment by Manduro** [comment]
I believe this is a regression of https://github.com/ngrx/platform/commit/b7a554a814aa364039d4a551682950b221704a1f
