### ISSUE TITLE
ngrx/store is not being transpiled into es5

### ISSUE THREAD

**Issue by vagonpidarasov** [ngrx/platform#679]
## I'm submitting a...
<pre><code>
[x] Bug report 
</code></pre>

## What is the current behavior?
When ```ngtools/webpack``` loader is used to compile angular app, ngrx/store is not being transpiled into es5.

## Expected behavior:
When ```awesome-typescript-loader``` is used (dev build) ngrx/store is being transpiled into es5.

## Minimal reproduction of the problem with instructions:
Repo: https://github.com/vagonpidarasov/ngrx-platform-issues-679
* ```npm install```
* ```npm run dev``` runs webpack dev server at ```http://127.0.0.1:8080/```
* ```npm run build:dev``` builds dev version of the app using ```awesome-typescript``` loader
* ```npm run build:prod``` builds prod version of the app using ```ngtools/webpack``` loader

Steps to reproduce:
1. build dev and prod versions of the app
2. open ```dev/vendor.js``` file and search for ```'@ngrx/store/init'``` string, confirm that all es6/typescript was transpiled to es5
3. open ```prod/vendor.js``` file and search for ```'@ngrx/store/init'``` string, locate following es6 expression ```class ActionsSubject extends __WEBPACK_IMPORTED_MODULE_1_rxjs_BehaviorSubject__["BehaviorSubject"] {``` 

## Version of affected browser(s),operating system(s), npm, node and ngrx:
Chrome 61 / IE11, Windows 7 Enterprise, MACOS

```
"@ngrx/core": "1.2.0",
"@ngrx/store": "4.1.1",
"@ngtools/webpack": "1.9.3",
```

## Other information:  
Please suggest a workaround.

**Comment by vagonpidarasov** [comment]
Demo repo can be found here: https://github.com/vagonpidarasov/ngrx-platform-issues-679

**Comment by brandonroberts** [comment]
I believe this issue has already been fixed in master via #630

**Comment by vagonpidarasov** [comment]
And when do we expect new release?
The last version I was able to reproduce the issue with is [4.1.1](https://www.npmjs.com/package/@ngrx/store)

**Comment by woutderooms** [comment]
Is there any time indication when this will be released on npm? This is blocking for us at the moment.
