### ISSUE TITLE
@ngrx/router-store has no exported member RouterState

### ISSUE THREAD

**Issue by HermanMarvel** [ngrx/platform#680]
## I'm submitting a...

<pre><code>
[ X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
During typescript translation - exception about absent RouterState member in @ngrx/router-state

## Expected behavior:
In release 2.2.2 it used to work. I do realize that it is at least 2 major releases ago, but still what is current replacement for this? We had to upgrade TypeScript version due to Angular upgrade and that is why we were forced to update @ngrx version as well. 

## Minimal reproduction of the problem with instructions:

1. npm install @ngrx/router-store@latest 

2. import {RouterState } from '@ngrx/router-store';

## Version of affected browser(s),operating system(s), npm, node and ngrx:
Angular CLI: 1.6.2
Node: 8.7.0
OS: win32 x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cli: 1.6.2
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.2
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.5.3
webpack: 3.10.0

    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^4.1.1",
    "@ngrx/router-store": "^4.1.1",
    "@ngrx/store": "^4.1.1",
    "@ngrx/store-devtools": "^4.1.1",

**Comment by brandonroberts** [comment]
The changes to router-store are detailed in the migration guide. https://github.com/ngrx/platform/blob/master/MIGRATION.md#ngrxrouter-store
