### ISSUE TITLE
Unable to Set Root Store in Feature Module while Testing

### ISSUE THREAD

**Issue by bsankuratri** [ngrx/platform#690]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
When I'm trying to import root store which has user and router reducers the router state is undefined in component test but it works fine with application.

## Here is the imports into component test

<pre><code>
 beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [
        RouterTestingModule,
        StoreModule.forRoot({companies: combineReducers(fromStore.reducers), ...fromRootStore.reducers}),
        EffectsModule.forRoot([CompanyEffects, CollectionEffects]),
        StoreRouterConnectingModule
      ],
      providers: [
        CompanyService,
        ...fromCompanyGuards.guards,
        {provide: RouterStateSerializer, useClass: CustomSerializer}
      ],
      declarations: [ CompanySummaryComponent, CompanyHeaderComponent ]
    })
    .compileComponents();
  }));

</code></pre>

## Test:

<pre><code>
it('should create', () => {
    expect(component).toBeTruthy();
  });
</code></pre>

## My Component: 

<pre><code>
constructor(
    private store: Store<fromStore.State>,
    private rootStore: Store<fromRootStore.State>
    ) {

    this.actionsSubscription = this.store.select(fromRootStore.getRouterState)
      .pipe(map((routerState: fromRouter.RouterReducerState<fromRootStore.RouterStateUrl>) =>
        new company.Select(routerState.state.params.companyId)))
      .subscribe(store);

}

</code></pre>

## root store state: 

<pre><code>

export interface State {
  routerReducer: fromRouter.RouterReducerState<RouterStateUrl>;
  user: fromUserReducer.UserState;
}
</code></pre>

## Root Reducer:

<pre><code>
export const reducers: ActionReducerMap<State> = {
  routerReducer: fromRouter.routerReducer,
  user: fromUserReducer.reducer
};
</code></pre>

## selector for router reducer: 

<pre><code>
export const getRouterState = createFeatureSelector<
fromRouter.RouterReducerState<RouterStateUrl>
>('routerReducer');

</code></pre>

## I tried different combinations with importing store module in tests

<pre><code>
1) StoreModule.forRoot({companies: combineReducers(fromStore.reducers), ...fromRootStore.reducers}),

2) StoreModule.forRoot(combineReducers({companies: combineReducers(fromStore.reducers), ...fromRootStore.reducers})),

3) 1) StoreModule.forRoot(...companies: combineReducers(fromStore.reducers), ...fromRootStore.reducers),

</code></pre>

None of them were actually worked.

**Comment by brandonroberts** [comment]
Support questions should be asked on stackoverflow or in the [gitter channel](https://gitter.im/ngrx/platform)

**Comment by adrian-moisa** [comment]
Hi @bsankuratri, Have you managed to run the test. I have the exact same problem. When I try to run a complete instance of the state store using `TestBed` the webapi dependency is not instantiated properly. Instead of getting the instace, I get the constructor method (console logged it).
