### ISSUE TITLE
Action and ActionReducer Typedefs Appear Broken

### ISSUE THREAD

**Issue by josh-sachs** [ngrx/platform#693]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

https://github.com/ngrx/platform/blob/master/docs/entity/adapter.md#adapter-methods
Following the examples using Typescript 2.6.2, a type-check error occurs:

`reducers/index.ts`

```
export const reducers: ActionReducerMap<State> = {
  users: fromUser.reducer
};
```
The reducer function is not considered valid because it's signature doesn't accept a compatible Action argument.

`user.reducer.ts`

```
export function reducer(
  state = initialState,
  action: UserActions
): State { 
...
}
```

This is because the `UserActions` type is composed of `Action` implementations for which the `type` property is an `enum` as opposed to a `string`.

`@store/src/models.d.ts`

```
export interface Action {
    type: string;
}
```

There are two ways of coercing type-checking to work...

The first is to explicitly set each Action's `type` property to `string`, but this breaks type inferencing within the reducer function's switch statement.

`user.actions.ts`

```
export class LoadUsers implements Action {
  readonly type: string = UserActionTypes.LOAD_USERS;

  constructor(public payload: { users: User[] }) {}
}
```

The second is to modify the Action interface as such:

```
export interface Action {
    type: string | enum
}
```

I would propose updating the `Action` type definition to the following:

```
export interface Action {
    type: string | enum | const
}
```

I actually tried to work around the issue by using constant values as opposed to enums and it still wouldn't pass muster for the  constraints on ActionReducerMap.

```
export declare type ActionReducerMap<T, V extends Action = Action> = {
    [p in keyof T]: ActionReducer<T[p], V>;
};
```

## Expected behavior:

`Action` implementing `type` using an `enum` or `const` value should pass type-checking for `ActionReducerMap`

## Minimal reproduction of the problem with instructions:

```
import { Action, ActionReducerMap } from "@ngrx/store";

export interface UserState {
    Name: string;
};

const InitialState: UserState = { 
    Name: "Josh"
};

export enum UserActionTypes {
    SET_NAME = "[USER] Set Name",
};

export class SetUserName implements Action {
  readonly type = UserActionTypes.SET_NAME;

  constructor(public payload: { name: string }) { }
};

export type UserAction = SetUserName ;

export function UserReducer(state = InitialState, action: UserAction): State {
    switch(action.type) {
        case UserActionTypes.SET_NAME:
             return {...state, ...{ Name: action.payload }};
        default:
             return state;
    }
};

export interface State {
     User: UserState;
};

export const Reducers: ActionReducerMap<State> {
     User: UserReducer,
};
```

ActionReducerMap will not pass type checking.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
Typescript: 2.6.2
ngrx-platform: 4.1.1

**Comment by brandonroberts** [comment]
TypeScript 2.4.x is the officially supported target to build against currently. The build will be updated once a later version is supported.
