### ISSUE TITLE
Why is the documentation different from the version in npm?

### ISSUE THREAD

**Issue by safaldas** [ngrx/platform#705]
## I'm submitting an issue

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
</code></pre>

## What is the current behavior?
When using the example-app in platform to learn nothing works because I didnt know the master documentation is different version. Also if I checkout to the tag v4.1.1 the example-app code is not working. When is next version release? 
When importing the Authmodule to the appmodule why is there a forRoot method created?
I am getting `no provider for root` error

**Comment by MikeRyanDev** [comment]
That's our fault. We have been merging in code for v5.x eagerly to start producing alphas. This inadvertently included documentation changes. For now, docs for the latest stable release can be found here: https://github.com/ngrx/platform/tree/v4.1.1
