### ISSUE TITLE
[Effect] [ngrxOnRunEffects] take account of the current active action.

### ISSUE THREAD

**Issue by aitboudad** [ngrx/platform#707]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

when using `ngrxOnRunEffects` the resolved effect doesn't take account of the current active action (`LOGGED_IN`).

## Expected behavior:

in the below example I would expect that `getUsers$`  is being called once the effect is resolved.

## Minimal reproduction of the problem with instructions:

```ts
import 'rxjs/add/operator/do';
import 'rxjs/add/operator/exhaustMap';
import 'rxjs/add/operator/takeUntil';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import { Action } from '@ngrx/store';
import { Actions, Effect, OnRunEffects, EffectNotification } from '@ngrx/effects';

@Injectable()
export class UserEffects implements OnRunEffects {
  constructor(private actions$: Actions) {}

  @Effect() getUsers$: Observable<Action> = this.actions$
    .ofType('LOGGED_IN')
    .do(action => {
      console.log(action);
    });

  ngrxOnRunEffects(resolvedEffects$: Observable<EffectNotification>) {
    return this.actions$.ofType('LOGGED_IN')
      .exhaustMap(() => resolvedEffects$.takeUntil(this.actions$.ofType('LOGGED_OUT')));
  }
}
```

**Comment by MikeRyanDev** [comment]
That's not quite how that works. You've handled `LOGGED_IN` in `ngrxOnRunEffects` and so your `getusers$` doesn't have to listen to it.

**Comment by aitboudad** [comment]
any hint how it should be solved ?

**Comment by MikeRyanDev** [comment]
What are you trying to accomplish?

**Comment by aitboudad** [comment]
get list of users once the current user is logged

**Comment by MikeRyanDev** [comment]
Then instead of writing your effect like this:
```ts
@Effect() getUsers$ = this.actions$.ofType('LOGGED_IN')
  .mergeMap(action => this.usersService.getUsers())
```

You would write it like this:
```ts
@Effect() getUsers$ = this.usersService.getUsers()
```

That's because you've set it up in `ngrxOnRunEffects` to not start any of your effects until `'LOGGED_IN'` is dispatched.

**Comment by aitboudad** [comment]
didn't know we can register an effect without passing a type.
ahh it's work, thank you so much!
