### ISSUE TITLE
router-store docs contradict the blog of the router creator on RouteStateSnapshot immutability

### ISSUE THREAD

**Issue by prenderga-st** [ngrx/platform#708]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## What is the current behavior?

The [API documentation for router-store](https://github.com/ngrx/platform/blob/v4.1.1/docs/router-store/api.md#navigation-actions) says that "the router state snapshot is a mutable object." However, the [blog of the guy who created the router](https://vsavkin.com/angular-router-understanding-router-state-7b5b95a12eab) says that "RouteStateSnapshot is an immutable data structure."

Which document is correct, the router blog or the router-store docs?

Thank you!

## Minimal reproduction of the problem with instructions:

Compare the docs and blog referenced above.

**Comment by brandonroberts** [comment]
See https://github.com/angular/angular/pull/20289
