### ISSUE TITLE
Selector ie11 issues Expected: ':' / Expected identifier

### ISSUE THREAD

**Issue by phillipzada** [ngrx/platform#711]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

When using ie 11, the selector.js code is throwing an error **Expected ':'.** If you do a --prod build (or serve) the error is displayed as **Expected identifier**. and points to the selector eval code in the chunk.

## Expected behavior:

No error is thrown

## Minimal reproduction of the problem with instructions:

Use createSelector or createFeatureSelector in ie 11

## Version of affected browser(s),operating system(s), npm, node and ngrx:

```
Angular CLI: 1.6.3                                         
Node: 8.9.1                                                
OS: win32 x64                                              
Angular: 5.2.0                                             
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser               
... platform-browser-dynamic, router                       
                                                           
@angular/cli: 1.6.3                                        
@angular-devkit/build-optimizer: 0.0.36                    
@angular-devkit/core: 0.0.22                               
@angular-devkit/schematics: 0.0.42                         
@ngtools/json-schema: 1.1.0                                
@ngtools/webpack: 1.9.3                                    
@schematics/angular: 0.1.11                                
@schematics/schematics: 0.0.11                             
typescript: 2.6.2                                          
webpack-bundle-analyzer: 2.9.2                             
webpack: 3.10.0                                            
```

## Other information:
I found a workaround where if I copied the selectors.ts file from the repo and made my own copy of the file within my app, and updated all the import statements for createFeatureSelector and createSelector to the local version, it all works. I think there is an issue with typescript compiling. My project is set to es5 due to browser support requirements of the project.

Code I believe is the culprit
```
Object.defineProperty(e,"__esModule",{value:!0}),e.memoize=r,e.createSelector=function(...n){let e=n;if(Array.isArray(e[0])){const[n,...t]=e;e=[...n,...t]}const t=e.slice(0,e.length-1),i=e[e.length-1],l=t.filter(n=>n.release&&"function"==typeof n.release),u=r(function(...n){return i.apply(null,n)}),o=r(function(n){const e=t.map(e=>e(n));return u.memoized.apply(null,e)});return Object.assign(o.memoized,{release:function(){o.reset(),u.reset(),l.forEach(n=>n.release())},projector:u.memoized})},e.createFeatureSelector=function(n){const{memoized:e,reset:t}=r(function(e){return e[n]});return Object.assign(e,{release:t,projector:e})}},dkCM:function(n,e,t){"use strict";var r=t("6Xbx").__decorate,i=t("6Xbx").__metadata;
```

**Comment by brandonroberts** [comment]
@phillipzada Is this different than https://github.com/ngrx/platform/issues/682?

**Comment by phillipzada** [comment]
@brandonroberts please disregard, blond moment. The project was importing from **@ngrx/store/src/selector** rather than **@ngrx/store**
