### ISSUE TITLE
Question example app: Should pipe really be used for select and ofType?

### ISSUE THREAD

**Issue by martintro** [ngrx/platform#714]
I've been looking at the example app when migrating from the previous version of ngrx to 4.x.
When running the example app in this repository it works fine, but in my app I cannot find a way to import functions select or ofType.

Shouldn't both ofType and select be called outside pipe() like before?

**For example:**
**example-app/app/auth/effects/auth.effects.ts**
Like this instead of current code:
```
...
@Effect({ dispatch: false })
loginSuccess$ = this.actions$
  .ofType(AuthActionTypes.LoginSuccess)
  .pipe(tap(() => this.router.navigate(['/'])));
...
```

**example-app/app/auth/containers/login-page.component.ts**
Like this instead of current code:
```
...
pending$ = this.store.select(fromAuth.getLoginPagePending);
error$ = this.store.select(fromAuth.getLoginPageError);
...
```

**Comment by brandonroberts** [comment]
The example app and code reflects what will be in the next major release. Docs for the current release are here https://github.com/ngrx/platform/blob/v4.1.1/docs/store/README.md

**Comment by martintro** [comment]
I see, makes sense. Thanks!
