### ISSUE TITLE
How to update a subset of entities with ngrx-entity?

### ISSUE THREAD

**Issue by tilowestermann** [ngrx/platform#721]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## What is the current behavior?

I'm updating a set of entities using a HTTP Patch request to a remote backend. The response from the backend includes the updated entities only (i.e., not all entities).

I set up my reducer with an entity state adapter and use updateMany to update my entities:
```
case settings.SettingsActionTypes.UpdateSettingsSuccess: {
   return {
     ...state,
     ...adapter.updateMany(action.payload.map((category) => Object.assign({}, {id: category.name, changes: category})), state),
     loaded: true,
     loading: false,
   }
 }
```
While this updates the entities that received an update, it deletes all others that are not returned by the backend.

Is there a way to tell ngrx to only update entities that are included in the action.payload?

## Expected behavior:

Only changed entites will be updated, others will be left in place.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
ngrx 4.1.1

## Other information:
This question has been asked on StackOverflow before: https://stackoverflow.com/questions/48222655/how-to-update-a-subset-of-entities-with-ngrx-entity

**Comment by brandonroberts** [comment]
Entity does not do any destructive operations when updating your collection. Please add a reproduction using plunker or stackblitz if that's not the case.

**Comment by MattiJarvinen-BA** [comment]
Only destructive is `addAll`
```
  function addAllMutably(models: T[], state: R): DidMutate;
  function addAllMutably(models: any[], state: any): DidMutate {
    state.entities = {};
    state.ids = [];

    addManyMutably(models, state);

    return DidMutate.Both;
  }

````

**Comment by brandonroberts** [comment]
Closing as invalid

**Comment by amitcdubey** [comment]
hi brandonroberts 

below url for my store
https://stackblitz.com/edit/angular-mqjmzf

Hi am getting this error while am going to ngrx entity ....@ngrx/entity: The entity passed to the selectId implementation returned undefined. You should probably provide your own selectId implementation. The entity that was passed:
