### ISSUE TITLE
Question: Dispatching  action and using reducers across Features.

### ISSUE THREAD

**Issue by DamolAAkinleye** [ngrx/platform#722]
I currently have an app separated into different features. One for the dashboard and one for a Nav bar. They are both lazily loaded. 

However, I have run into a scenario where I need to get the number generated in the dashboard  feature into the Nav bar feature. Is there a way to use the store to communicate across lazily loaded features? Will I have to export all the actions into a shared feature and do the co-ordination from there. Any pointers to existing code will certainly help.

**Comment by brandonroberts** [comment]
Store already has access to all _loaded_ pieces of state. Selectors are resuable, so you would use your selector from the dashboard feature to provide it in the navbar feature. If you need further assistance, you can use the [gitter channel](https://gitter.im/ngrx/platform)
