### ISSUE TITLE
building multiple apps and deploying it as one.

### ISSUE THREAD

**Issue by a5hik** [ngrx/platform#725]
Question: How to run multiple apps together..

1. App1
2. App2

I need both App1 and App2 to work independently (can be built and deployed) 
I know this is possible with nx.

But,
.. I have a super app that loads both App1 and App2. 
Can routes operate this way between apps and the store?

Is this model doable with nx?

**Comment by brandonroberts** [comment]
Issues with Nx should be filed here https://github.com/nrwl/nx

**Comment by a5hik** [comment]
I think I have mistakenly posted here, sorry.
