### ISSUE TITLE
Roadmap information request

### ISSUE THREAD

**Issue by Stephane-Peyroutet** [ngrx/platform#726]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

Would it be possible to have a kind of roadmap for the NgRx project ?
I'm not asking for a specific schedule but something general and simple in the **Readme.md** would be nice to have like what is done in the [Material](https://github.com/angular/material2) project.
For example, I would guess 5.0.0 (at least rc.x or beta.x) is coming in a near future but do I assume Q1, Q2 or Q3 2018 ?

**Comment by RoopeHakulinen** [comment]
At least per [this](https://github.com/ngrx/platform/issues/325#issuecomment-324838650) the @ngrx/offline to help with offline-first approach has been on the table. In my opinion that is the most important thing to consider and would really like to hear the plans on that. If nothing comes up from the team I'm about to start to implement my own solution for that in few weeks.

**Comment by brandonroberts** [comment]
5.0.0 has been released to npm

**Comment by RoopeHakulinen** [comment]
I don't think that the release of 5.0.0 answers the question asked here about the future roadmap and thus the issue should be reopened and answered properly.

**Comment by Stephane-Peyroutet** [comment]
Yes, thank you @RoopeHakulinen.
My question was not when 5.0.0 will be released.
And, even if this is good news, the point is we didn't have any clue it was going to be released.
What about next months ? Do we just have to wait and see what happens ?
Or can we expect to have a kind of roadmap or planned stuff schedule ?
