### ISSUE TITLE
@ngrx/effects/effects"' has no exported member 'ofType'. in version 4 and 5

### ISSUE THREAD

**Issue by hoachan** [ngrx/platform#727]
## I'm submitting a bug 
Hi everyone, I'm editing ngrx-example with auth function. Now, I am having a bug as follow 
### I've installed the @ngrx/effects package v.5, and in the auth folder/ auth.effects.ts
ofType didn't work with following error message :  
 
<pre><code>
import { Effect, Actions, ofType} from '@ngrx/effects';
@Injectable()
export class AuthEffects {
  @Effect()
  login$ = this.actions$.pipe(
    ofType(AuthActionTypes.Login),
    map((action: Login) => action.payload),
    exhaustMap((auth: Authenticate) =>
      this.authService
        .login(auth)
        .pipe(
          map(user => new LoginSuccess({ user })),
          catchError(error => of(new LoginFailure(error)))
        )
    )
  );
</code></pre>

## With the current behavior 
 Module '"..../node_modules/@ngrx/effects/effects"' has no exported member 'ofType'.

## have anyone met the same situation? 
Please show me how to solve it . Thanks

**Comment by brandonroberts** [comment]
The `ofType` operator is only available through the nightly builds at the moment. So if you did a normal install, you won't get the latest.

**Comment by adrian-moisa** [comment]
Is `ofType` operator available?
