### ISSUE TITLE
Angular 5 effects not working with HttpClient

### ISSUE THREAD

**Issue by csutorasr** [ngrx/platform#729]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
If I inject the `HttpClient`, that should be used according to the Angular 5 docs, the effects stops working. With the `Http` from `'angular/http'` is working correctly. When I changed to `HttpClient` from `'angular/common/http'` it broke.

I try to load a script in the effect, but the `console.log` is not called at the begining of the effect.

## Expected behavior:
The HttpClient should work with the new http service.

## Minimal reproduction of the problem with instructions:
I tried to reproduce but i have failed. [Here is the working plunker](http://plnkr.co/edit/IixR3U6DjI8ZCByLxCcf?p=preview) In the plunker it is working somehow, maybe as a result of the SystemJS

## Version of affected browser(s),operating system(s), npm, node and ngrx:

Chrome latest, windows latest.
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.6.4
Node: 8.9.0
OS: win32 x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

@angular/cli: 1.6.4
@angular-devkit/build-optimizer: 0.0.38
@angular-devkit/core: 0.0.25
@angular-devkit/schematics: 0.0.48
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.4
@schematics/angular: 0.1.13
@schematics/schematics: 0.0.13
typescript: 2.6.2
webpack: 3.10.0
```

## Other information:

I have the latest version of everything.

**Comment by brandonroberts** [comment]
This is not a bug with ngrx. If you need further support, use the [gitter channel](https://gitter.im/ngrx/platform)

**Comment by csutorasr** [comment]
Sorry for the posting. I thought it has something connected with Ngrx as it couldn't loaded.

The real problem was the effect wanted to use the HttpClient, but an interceptor couldn't be loaded.
