### ISSUE TITLE
Unable to install @ngrx/router-store via npm

### ISSUE THREAD

**Issue by AClavijo** [ngrx/platform#730]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
Error when i tried to install @ngrx/router-store via npm:

npm i --save @ngrx/router-store@4.1.1

404 Not Found: @ngrx/router-store@4.1.1 

> http fetch GET 404 https://registry.npmjs.org/@ngrx%2frouter-store 1853ms 

## Expected behavior:
ngrx/router-store installed

## Minimal reproduction of the problem with instructions:

npm i --save @ngrx/router-store@4.1.1

## Version of affected browser(s),operating system(s), npm, node and ngrx:
2 info using npm@5.6.0                                                                                    
3 info using node@v8.0.0

## Other information:
I have the same behavior with the lastest.

**Comment by RoopeHakulinen** [comment]
Just ran the very same command (copy & pasted from above) in fresh npm project and it worked just fine. Also everything seems okay in the https://www.npmjs.com/package/@ngrx/router-store.

Probably you are behind some kind of proxy or then npm was having some issues.
