### ISSUE TITLE
No `select` found on import from '@ngrx/store'

### ISSUE THREAD

**Issue by Papish** [ngrx/platform#731]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ x ] Documentation issue or request
</code></pre>

## What is the current behavior?
Error while trying to import { select } from '@ngrx/store'

## Expected behavior:
Module `select` to be imported from '@ngrx/store'

## Minimal reproduction of the problem with instructions:
Using below code as per documentation to select from store but getting error stating no exported member `select`.
import { Store, select } from '@ngrx/store';

## Version of affected browser(s),operating system(s), npm, node and ngrx:
using "@ngrx/store": "^4.1.1" with latest angular/cli/npm/

**Comment by RoopeHakulinen** [comment]
The documentation is reflecting the current implementation of the `master` branch. That is for the upcoming version 5.0.0. You can find the correct documentation for 4.1.1 [here](https://github.com/ngrx/platform/blob/v4.1.1/docs/store/README.md). The link is also on the top of the README for each module.
