### ISSUE TITLE
TSLint rules for checking code-style and best practices

### ISSUE THREAD

**Issue by listepo-alterpost** [ngrx/platform#733]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

I think it has a right to life

**Comment by HideDev** [comment]
@brandonroberts what do you think?

**Comment by brandonroberts** [comment]
Not a bad idea, but we aren't going to dictate that here. What rules did you have in mind?

**Comment by MattiJarvinen-BA** [comment]
I'm not that familiar with what TSLint can and can't do. 

If possible:
- warn when using of instanceof in reducers (but how to limit that properly is totally another question)
- checks if actions are serializable
- check if reducers return values immutable

IMHO list of do's and do not's would be preferable. ( Especially those do not's with why. )

**Comment by brandonroberts** [comment]
Good ideas, but would be developed outside of this repo.
