### ISSUE TITLE
init called multiple times with lazy loaded modules

### ISSUE THREAD

**Issue by sylvaingirardbe** [ngrx/platform#740]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## What is the current behavior?
init is called per lazy loaded module

## Expected behavior:
it's only called once

## Minimal reproduction of the problem with instructions:
https://github.com/sylvaingirardbe/ngrx-lazy-loading
https://angular-jtprpf.stackblitz.io/

## Version of affected browser(s),operating system(s), npm, node and ngrx:
ngrx: 4.1.1
npm: 5.5.1
node: 9.2.0

## Other information:
I know this has been addressed multiple times and that the example app also uses lazy loading. Still, this very simple setup (which uses a lot of the components of the example app) causes init to be called twice, once for the AppModule and once for the lazy loaded Module1Module. Module2Module is not lazy loaded and plays nice.
Is anyone able to shine some sort of light on this behavior?

PS: I tried [SO](https://stackoverflow.com/questions/48317703/ngrx-store-init-called-multiple-times) first but that didn't get me any response...

**Comment by bmayen** [comment]
Are you using `preloadingStrategy: PreloadAllModules`?

**Comment by sylvaingirardbe** [comment]
Unless it's defaulting to that: no.

**Comment by brandonroberts** [comment]
This issue has already been fixed in master and is included in the `5.0.0` release
