### ISSUE TITLE
5.0.0 documentation problems

### ISSUE THREAD

**Issue by RoopeHakulinen** [ngrx/platform#742]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

 The docs for the modules have the link "Click here for documentation for the latest release (4.1.1)" which is now for the last version.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
5.0.0

**Comment by brandonroberts** [comment]
Care to submit a PR to remove those links from the README files?

**Comment by brandonroberts** [comment]
Fixed via https://github.com/ngrx/platform/commit/25d9a084f9a997cbbfbf924f41fe0cc2697be82e
