### ISSUE TITLE
lost reducer when aot

### ISSUE THREAD

**Issue by lishichao1002** [ngrx/platform#743]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

aot mode lost many reducers.

## Expected behavior:

same reducers with dev mode

## Version of affected browser(s),operating system(s), npm, node and ngrx:
```
   _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.6.5
Node: 6.9.5
OS: win32 x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.5
@angular/platform-server: 4.4.6
@angular-devkit/build-optimizer: 0.0.41
@angular-devkit/core: 0.0.28
@angular-devkit/schematics: 0.0.51
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.16
typescript: 2.5.3
webpack: 3.10.0
```

package.json
```
"dependencies": {
    "@angular/platform-server": "^4.2.4",
    "angular2-uuid": "^1.1.1",
    "ng-http-interceptor": "^3.1.1",
    "ngrx-store-logger": "^0.1.8",
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "@ngrx/store": "^5.0.0",
    "@ngrx/store-devtools": "^5.0.0",
     ...
  },
```

## Other information:

![image](https://user-images.githubusercontent.com/13584162/35320047-5f2ca7e2-011d-11e8-9b24-acc55fc3e1cc.png)
![image](https://user-images.githubusercontent.com/13584162/35320083-87c10d9c-011d-11e8-9573-47de674ffbab.png)
![image](https://user-images.githubusercontent.com/13584162/35320149-ca0dc08c-011d-11e8-8d78-9e47ede57fe1.png)
![image](https://user-images.githubusercontent.com/13584162/35320172-dc6dc650-011d-11e8-9968-36814fd53997.png)
![image](https://user-images.githubusercontent.com/13584162/35320218-f918929e-011d-11e8-879b-383a2cd6b75d.png)
![image](https://user-images.githubusercontent.com/13584162/35320230-09d0b06c-011e-11e8-89c1-22fbf0541212.png)

**Comment by lishichao1002** [comment]
The official demo 

![image](https://user-images.githubusercontent.com/13584162/35320587-42626b4a-011f-11e8-8404-c1cc2a431e85.png)

![image](https://user-images.githubusercontent.com/13584162/35320627-6b2ca310-011f-11e8-9a5a-1bb45ed4b768.png)

**Comment by Alex-Torres** [comment]
Experiencing the same problem.

**Comment by brandonroberts** [comment]
Is this after upgrading to 5.0.0 from 4.1.1?

**Comment by lishichao1002** [comment]
the plunker [ngrx 5.0.0 on jit mode](http://plnkr.co/edit/R6uPeuJxppKvLgMBxvUO?p=preview)
it works.

but not work on aot mode.

**Comment by brandonroberts** [comment]
This is more likely an AoT issue than with ngrx. If you're going to be manipulating the reducer map that way you need to use a token to inject your reducers: https://github.com/ngrx/platform/blob/master/docs/store/api.md#injecting-reducers
