### ISSUE TITLE
testing.js missing from @ngrx/effects in 5.0.0 release

### ISSUE THREAD

**Issue by doetk** [ngrx/platform#744]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
```
npm install @ngrx/effects
ls node_modules/@ngrx/effects/testing
```
Produces output:
`package.json  src  testing.d.ts  testing.metadata.json
`

## Expected behavior:
testing.js should be present in the @ngrx/effects module

## Minimal reproduction of the problem with instructions:
npm install lodash@5.0.0
Look for testing.js file in node_modules or try importing anything from @ngrx/effects/testing

## Version of affected browser(s),operating system(s), npm, node and ngrx:
ngrx version 5.0.0

## Other information:
N/A

**Comment by csutorasr** [comment]
Did you want to write lodash in the reproduction? (it is not affecting whether the problem occours)

**Comment by brandonroberts** [comment]
The `package.json` file points to the correct bundled file for `@ngrx/effects/testing`

**Comment by doetk** [comment]
Lodash was a mistake, bad copy and paste.

The package.json file in the @ngrx/effects/testing directory looks correct:
```
{
  "name": "@ngrx/effects/testing",
  "typings": "../testing.d.ts",
  "main": "../bundles/effects-testing.umd.js",
  "module": "../@ngrx/effects/testing.es5.js",
  "es2015": "../@ngrx/effects/testing.js"
}
```
...but only the testing.d.ts file exists. None of the JS files are present in the testing directory or its parent.

**Comment by doetk** [comment]
Ah, I see. The testing.js file doesn't sit alongside it's package JSON in the testing folder or root module, but rather in another directory:

``@ngrx/effects/@ngrx/effects``

Thanks.
