### ISSUE TITLE
[docs, opinionated] usage of .pipe in docs is pretty useless

### ISSUE THREAD

**Issue by ducin** [ngrx/platform#746]
Hi Guys,

Thanks for all your work with ngrx!

Referring to [this commit](https://github.com/ngrx/platform/commit/06aeac4f12e143a7af8703b859d7a3e87e5a621e), I think that introducing lettable operators were a mistake. I was reading through the [docs](https://github.com/ngrx/platform/blob/master/docs/effects/api.md#oftype) and found out that there is the new `.pipe` things in Rx which is used extensively in the docs now. The trouble is... it doesn't add *any* value. It only makes more things complicated, because instead of:

    stream.pipe(op1(cb1), op2(cb2))

you could just do

    stream.op1(cb1).op2(cb2)

and you've had that before... Pipe makes sense if you wanna reuse a sequence of operators that form bigger logic. And you would hardly ever have such need, while describing ngrx examples.

I guess you'd agree that a good documentation is an easy documentation. Rx `.pipe` is completely useless in this context - it only makes the knowledge entry level higher for readers. The abovementioned commit introduces some valuable changes, such as do->tap, angular updates, etc. Just the .pipe operator is useless, from my very personal and subjective point of view...

**Comment by MikeRyanDev** [comment]
Pipeable operators are going to be the default in rxjs v6 and the prototype operators (`rxjs/add/operator/foo`) are going to be deprecated. We're aligning with the long term mission of rxjs and making sure new users are doing things in a way that won't break on them in the future.
