### ISSUE TITLE
Issue with updateMany()

### ISSUE THREAD

**Issue by mcblum** [ngrx/platform#747]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ x ] Documentation issue or request
</code></pre>

## What is the current behavior?
Calling `adapter.updateMany` doesn't update the store. 

## Expected behavior:
It would update the store :)

## Minimal reproduction of the problem with instructions:
Maybe I'm missing something but I'm doing `return fieldAdapter.updateMany(action.fields, state);` in my reducer. I can see in the dev tools that `action.fields` is set and that it has new data, but the diff for the store shows no changes. The docs are a little unclear about `updateOne` and `updateMany`. I had to do something different to get `updateOne` to work (pass in `id` and `changes`) so I'm thinking it might be something like that.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
Mac, Chrome, Node 9.4, Ngrx 4.1.1

## Other information:
Thanks for your work on this! Truly amazing stuff.

Edit: Just so I'm not being dumb - if I pass an array of entities to `updateMany` that will work, right? It will scan them all and pluck whatever the `selectId` is set to for the key?

**Comment by brandonroberts** [comment]
Just passing an array of entities is not going to get updated that way. The signature for for `updateMany` is the same as `updateOne` except you pass an array of `id` and `changes` objects. The `Update` interface gives you the shape you should provide.

**Comment by mcblum** [comment]
Ah got it -- I can check that. @brandonroberts did I miss that in the docs somewhere? From what I saw it made it look like you could just pass the array. Secondarily, is that a design decision or something that you'd accept a PR for? If the user specifies a selectorId function to the adapter it would be possible to just provide an array, right?
