### ISSUE TITLE
Effects snapshot testing

### ISSUE THREAD

**Issue by jansivans** [ngrx/platform#752]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
</code></pre>

## What is the current behavior?
There are no desciption or example on how to use snapshot testing for effects.

## Expected behavior:
I am just curious if it is possible to use snapshot testing for effects now? Or some custom snapshot serializer needs to be written to do this?

**Comment by brandonroberts** [comment]
I don't know how much value you're going to get out of snapshots with effects. You still need something to assert against, otherwise your providing your own answer in the test if that makes sense.

**Comment by MikeRyanDev** [comment]
rx-sandbox allows you to get all of the messages for an observable in an array. Tools like Jest have native support for snapshot testing JavaScript arrays and objects, so I don't think there is anything we need to do here.
