### ISSUE TITLE
RFC: New Store method - selectAsync

### ISSUE THREAD

**Issue by bryanrideshark** [ngrx/platform#755]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Proposed implementation

````ts

Store<T> {

    selectAsync<K>(
        selectorFunc: (state: T, store?: Store<T>) => Observable<K>
    ): Observable<K> {
        return this.state$.switchMap((state) => selectorFunc(state, this)).distinctUntilChanged();
    }
}

````

## Motivations

Currently, Store is an elegant way to manage state in an application because of the singular direction when it comes to data flow. I always know that I am reading state when I call `select`, and modifying state when I call `dispatch`. CQRS for the win!

However, there are some times when you want to conditionally dispatch actions based on the state of data in the store. We frequently run into this problem at the office. I'll share an example component we use, `UserAvatarImg`. The idea is that you can just specify the Id of a user, and the size that you would like that image displayed in, and it will correctly display their image. This is used extensively throughout the app, in chat windows, search results, the users' own profile page, etc.

````ts

const isTruthy = <T>(v: T) => !!v;

@Component({
  selector: 'user-avatar-img',
  template: `
  <img [src]="imgSrc" />
  `
})
export class UserAvatarImgComponent implements OnInit, OnChanges {
  @Input()
  userId: string;

  @Input()
  size: number;

  public imgSrc: string;

  private userId$ = new BehaviorSubject<string>(undefined);
  private size$ = new BehaviorSubject<number>(undefined);

  constructor(
    public store: Store<{ userAvatars: { [userId: string]: {[size: number]: string} }>
  ) { }

  ngOnInit() {
    this.userId$
      .filter(isTruthy)
      .withLatestFrom(this.size$.filter(isTruthy))
      .switchMap(([userId, size]) => this.store.select(selectUserAvatarImgSrc(userId, size))
      .subscribe((imgSrc) => {
        this.imgSrc = imgSrc;
      });
  }

  ngOnChanges(changes: SimpleChanges) {
    const {
      userId,
      size
    } = changes;
    if (userId) {
      this.userId$.next(userId.currentValue);
    }
    if (size) {
      this.size$.next(size.currentValue);
    }
  }
}

// Generates a selector function to get an avatar from the store.
// In the real code, this is in a separate file.
function selectUserAvatarImgSrc(userId: string, size: number) {
  return function selectUserAvatarImg(state: { userAvatars: { [userId: string]: {[size: number]: string} } {
    const userImages = userAvatars ? userAvatars[userId] : null;
    const imageSrc = userImages ? userImages[size] || null : null;
    return imageSrc;
  }
}



````

This is a really elegant component as far as the visible API is concerned (you just say the person, and the size of the image, it takes care of the rest). 

Using the store for management of our data in this case, has one major drawback. We can only display what is currently in the store. To retrieve the data of additional users, currently we must modify the ngOnInit method:

````ts

ngOnInit() {
  this.userId$
    .filter(isTruthy)
    .withLatestFrom(this.size$.filter(isTruthy))
    .switchMap(([userId, size]) => this.store.select(selectUserAvatarImgSrc(userId, size))
    .subscribe((imgSrc) => {
      if (!imgSrc) {
        // Tell the store to fetch this data from the server or disk.
        this.store.dispatch({ type: 'FETCH_USER_AVATAR', payload: { userId: this.userId, size: this.size } });
      } else {
        this.imgSrc = imgSrc;
      }
    });
}

````

Now, this _works_. It's just not as pretty as the other example. We're mixing in the implementation details of how we retrieve data, with the declarative "I want to use this data". The way to resolve this is:

 - Modify all API resources so that they return avatar image sources (GraphQL is awesome, but you're not always able to convince your technical lead to do the upgrade).
 - Use a Service which wraps Store, and add a `getUserAvatarImgSrc$(userId: string, size: number): Observable<string>;` method which would do exactly as we have above
 - Use selectAsync

Here's how I would modify the component using `selectAsync`:

````ts

// Generates a selector function to get an avatar from the store.
// In the real code, this is in a separate file.
function selectUserAvatarImgSrc(userId: string, size: number) {
  return function selectUserAvatarImg(
      state: { userAvatars: { [userId: string]: {[size: number]: string} },
      store: Store<any>
    ): Observable<string> {
    return store.select((state) => {
        const userImages = userAvatars ? userAvatars[userId] : null;
        const imageSrc = userImages ? userImages[size] || null : null;
        return imageSrc;
    }).tap((imageSrc) => {
      if (!imageSrc) {
        store.dispatch({ type: 'FETCH_USER_AVATAR', payload: { userId, size } });
      }
    });
  }
}
ngOnInit() {
  this.userId$
    .filter(isTruthy)
    .withLatestFrom(this.size$.filter(isTruthy))
    .switchMap(([userId, size]) => this.store.selectAsync(selectUserAvatarImgSrc(userId, size))
    .subscribe((imgSrc) => {
        this.imgSrc = imgSrc;
    });
}

````

## Why not just use an Effect?

If there was an action dispatched every time someone called "select" on the store, I would not need to use this method. I could just wire it up with an effect. However, I don't see any way that you would be able to elegantly say "This data is being observed" through an action.

## Additional use cases:

In the definition I've proposed, store is optional for a reason. Imagine a selector function which automatically waits to emit data until certain conditions are met:

````ts

/**
 * Selects pigs only when they can fly.
 */
function selectPigsWhenTheyCanFly(state: { pigs: {[pigId: string]: Pig; }, pigsCanFly: boolean; }): Observable<{[pigId: string]: Pig; }> {

  if (state.pigsCanFly) {
    return Observable.of(state.pigs);    
  } else {
    return Observable.empty();
  }
}
````

**Comment by pscanlon1** [comment]
It seems that onInit you should be firing that action to an effect, and verify in the effect if the avatar already exists in the cache, otherwise load the data in the effect and the select method in your component picks it up.
If im understanding this correctly.

**Comment by bryanrideshark** [comment]
Absolutely, the `FETCH_USER_AVATAR` action absolutely should be acted upon by an Effect, which would do as you suggest (check local cache, exhaust all possibilities before actually making a network request). However, that's not my point. 

What I'm wanting, is the ability for the component to not even have to know about dispatching Actions. It should not be the responsibility of the components to know about how to fetch data from the network. They should be able to say "I need this data" - and allow other parts of the code to carry out that behavior.

The current architecture of `@ngrx/store` necessitates that I say "I need this data" twice - Once in the `store.select` function (where I pass in a function which selects the data I want) and again via an Action (where I say "hey, make sure this data exists!"). I would like to consolidate that down to a singular expression of "I need this data" - hence my proposal for `selectAsync`.

**Comment by pscanlon1** [comment]
Ah, I see what you mean.. In my current app, I was trying to follow the same type of pattern. I wrapped the store.select into separate service called a "slicer", for lack of a better term.. All my component does is subscribe to the observable function that the "slicer" returns.

What I did when I had some sort of metadata to add, was added a resolver to the route. For example.

if I am going to a page like . /:entityId/overview..

I would do a store action in the resolver that effects picked up and loaded entity data, or the reducers would react to the "selectedEntityId" property changing (as most of my data is keyed in this way)

**Comment by pscanlon1** [comment]
Meant to provide some code..

```
@Injectable()
export class EntityIdResolver implements Resolve<any> {
  constructor(private uiService: UiService) {}
 
  resolve(
    route: ActivatedRouteSnapshot,
    state: RouterStateSnapshot
  ): Observable<any>|Promise<any>|any {
    const sub = new Subject<any>();
    this.uiService.selectEntity(+route.params.id);
    return sub.next();
  }
}
```

uiService...
```
selectEntity(entity_id) {
    this.store.dispatch(new EntitySelectedAction({entity_id: +entity_id}));
  }
```
example of a reducer that updates based on entityId changing.
```
export const getEntityBankCashEntries = createSelector(fromUi.getSelectedEntityId, getBankCashEntries,
  (entityId, cashEntries) => {
    return cashEntries[entityId];
  });
```
I also have effects that react to this property changing..
```
@Effect()
  public onEntitySelected = this.actions$
    .ofType(UIActionsTypes.ENTITY_SELECTED)
    .map((action: UiActions.EntitySelectedAction) => action.payload)
```

Seems like you have this down.. but I just wanted to share what I'm doing as the solution to what seems to be a similar use case.. Maybe I can learn something or look at it in a different way!

**Comment by brandonroberts** [comment]
@bryanrideshark I'd consider this an anti-pattern, as now your selectors are introducing side effects which should be handled with `@ngrx/effects`. 

If you don't want your component to dispatch an action to check/fetch this data, you should use Effects combined with the router navigation cycle to listen for when it routes to that component, handle the fetching/checking in effects and push the data into the store. Your selectors still behave as normal and remain pure selector functions.

**Comment by pscanlon1** [comment]
How do you hook up your router events into effects?

**Comment by bryanrideshark** [comment]
@brandonroberts, can we find another way of doing side-effects than simply `@ngrx/effects`? Effectively, `@ngrx/store` is Redux, `@ngrx/effects` is Redux-Observable - but Redux also has different ways to do side effects (Redux Saga, Redux Thunk). 

My team is asking me repeatedly "Can't we just use a service"? And I keep responding "No, do you really want 4 services in your component just to get data? Testing is going to be harder that way, let's just keep using the Store". But I see their point. Consider this code:

````ts

ngOnInit() {
  this.userId$
    .filter(isTruthy)
    .withLatestFrom(this.size$.filter(isTruthy))
    .switchMap(([userId, size]) => this.userAvatarService.getAvatarImgSrc$(userId, size))
    .subscribe((imgSrc) => {
        this.imgSrc = imgSrc;
    });
}
````

It's much more attractive to jr. developers, as they no longer have to think about dispatching actions etc, they don't have to care about how it works, they can just access the data they need.


I suppose I could do as you suggest, and dispatch actions in ngOnChange:

````ts

ngOnChange(changes: SimpleChanges) {
    const {
        userId,
        size
    } = changes;
    if (userId || size) {
        this.store.dispatch({type: 'USER_AVATAR_IMG_REQUIRED', payload: {userId: this.userId, size: this.size} });
    }
}
````

and then have an Effect do the fetching. It's not awful, but it would be really nice to be able to do things as I described in my proposal on occasion.

Can we find another way to introduce side-effects to the application other than Effects? Something with less boilerplate?
