### ISSUE TITLE
NgRx Schematics - Documentation Idea: Put example Blueprints section output in the documents

### ISSUE THREAD

**Issue by goelinsights** [ngrx/platform#758]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## What is the current behavior?

Documentation of examples highlights the command line input and options to work

![2018-01-27_12-48-44](https://user-images.githubusercontent.com/2880781/35476170-73b7aa32-0360-11e8-9e51-6677320b3a2c.jpg)
## Expected behavior:

Documentation would add what the scaffolding creates with an example, ie. for the actions example of 
`ng generate action User --spec`
```
user.action.ts

export enum UserActionTypes {
  UserAction = '[User] Action'
}

export class User implements Action {
  readonly type = UserActionTypes.UserAction;
}

export type UserActions = User;
```
+ user.action.spec.ts

## Minimal reproduction of the problem with instructions:

Visited Blueprints => Action section of @ngrx/schematics https://github.com/ngrx/platform/blob/master/docs/schematics/action.md#examples

## Other information:
Love the new library!  Super excited to use it.

Happy to do the work as a pull request - just want to make sure it's something you'd accept.

**Comment by brandonroberts** [comment]
I think this output would be a little too verbose for the documentation. The intent is that Its easy enough to copy the command and run it and see the results.

**Comment by goelinsights** [comment]
That’s fair. Would a link to the github src file be better?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by brandonroberts** [comment]
I feel the same way about linking to the blueprint source. Its not a "clean" file as its mixed with some schematics syntax and template code. There are examples of actions, effects and reducers in the documentation already.

**Comment by brandonroberts** [comment]
Closing as non-actionable.
