### ISSUE TITLE
ngrx transpiles into invalid ES5 code

### ISSUE THREAD

**Issue by davidanaya** [ngrx/platform#759]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
I'm using a standard Ionic 3 project with ngrx, so that's webpack for bundling.

When I do a build of the project and I check the vendor.js file (where all the libraries used should be transpiled into js) I find this

```
function createSelector(...input) {
    let /** @type {?} */ args = input;
    if (Array.isArray(args[0])) {
        const [head, ...tail] = args;
        args = [...head, ...tail];
    }
```

In my tsconfig.json file I set my target as ES5, so I would expect that last line to be transpiled into something without the spread operator.

Am I missing something? This could fail in browsers with no ES6 support.

## Expected behavior:

I would expect that last line to be transpiled into something like ```args  = head.concat(tail)``` .

## Minimal reproduction of the problem with instructions:

Just add ngrx to an angular project and generate a build.

**Comment by creat-or** [comment]
I have a similar problem. My Ionic just shows a blank page. The console errors at a line of combineReducers
```
function combineReducers(reducers, initialState = {}) {
```
with the error
> Uncaught SyntaxError: Unexpected token =

I'm not sure if this is a ngrx problem or an ionic/webpack misconfiguration, though...

**Comment by creat-or** [comment]
Hi @davidanaya, 
I just got it to work. I did 2 things, but I'm not sure which one was the solution (I think it's the second one):

1. I updated the ngrx libs to 5.0.1 (from 4.1.1)
1. Due to automatic imports with Visual Studio Code, I got some import statements deeper than documented. I think this could also lead to the problem. To illustrate what I mean, here is a diff:
```diff
-import { ActionReducer } from '@ngrx/store/src/models';
-import { combineReducers } from '@ngrx/store/src/utils';
-import { createFeatureSelector } from '@ngrx/store';
+import { ActionReducer, combineReducers, createFeatureSelector } from '@ngrx/store';
```
So I guess importing `combineReducer` from `@ngrx/store/src/utils` is handled differently than importing it from `@ngrx/store`.

Hope that helps you, too!

**Comment by brandonroberts** [comment]
@creat-or that is correct. You should not use deep imports

**Comment by davidanaya** [comment]
Ey @creat-or thanks for sharing, I actually think that updating to 5.0.1 fixed the problem.

But to me version 4.1.1 has a problem in there as the generated code is not ES5 compliant and that causes the app to break in some android phones with the native browser.

It's easy to check, if you go to the node_modules/@ngrx/store/src/selector.js you will see things like this

```
if (Array.isArray(args[0])) {
        const [head, ...tail] = args;
        args = [...head, ...tail];
    }
```

I was not using deep imports in any case. I still need to go and check if migrating to 5.0.1 fixes the issue for me.

**Comment by MikeRyanDev** [comment]
There are different build artifacts published in an NgRx package. ES2015 was one of those artifacts in NgRx 4 and deep import paths may have caused these artifacts to be bundled in your application.

The `main` entry in `package.json` correctly points to bundled ES5, see here: https://github.com/ngrx/store-builds/blob/master/bundles/store.umd.js#L580

We no longer ship ES2015 source files with NgRx 5 but you should still avoid deep import paths.
