### ISSUE TITLE
naming conventions folders/files/components example-app, project structure

### ISSUE THREAD

**Issue by NilsNaegele** [ngrx/platform#767]
There is duplicate naming convention in this project, that is confusing. I think that in the Angular Styleguide there are some guidelines on how to name the files/folders and the components. Some documentation would also be a good idea. This is not a project conducive to adoption of this technology. May this be the goal?

It seems that a lot of code is implemented for some basic functionality. Maybe another sample app would be a good thing.

Look at the Angular documentation. Tour of Heroes Tutorial for inspiration. This would be a good sample app, in terms of code quality, adherence to our Styleguide and documentation.

It seems that Angular Redux is easier to understand and work with.

For starters I want one store, reducers and actions and not this confusing mess. This is my second stab at this project. And I am pro Angular: 100%.

**Comment by brandonroberts** [comment]
This project isn't meant to be a one-for-one implementation of the style guide. If you think using Angular Redux is better for you, feel free to use it.

**Comment by NilsNaegele** [comment]
On Production Apps I have used Angular Redux instead of this one. Wonder why?
These are just some suggestions on what can be improved.

**Comment by brandonroberts** [comment]
:+1:

**Comment by NilsNaegele** [comment]
"ngrx-store-freeze": "^0.2.1", where is the @ prefix? be consistent. This is also in the Angular Styleguide.
Either all modules have an @ prefix or none.

**Comment by MikeRyanDev** [comment]
ngrx-store-freeze is not maintained by the NgRx team and will not be published with the `@` prefix.
