### ISSUE TITLE
Get value from store without subscription

### ISSUE THREAD

**Issue by dalibor983** [ngrx/platform#769]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
</code></pre>

## What is the current behavior?

Currently the only way to get some value from the store is to create subscription (subscribe to observable and listening for store changes).

In general this way is good for components because there is onDestroy event where you can unsubscribe from observing.

Sometimes we need feature to retrieve current value from store without subscribing e.g. in some methods in services. There is a way to create subscription in service constructor but there is no way to unsubscribe from it because service does not have nothing similar to onDestroy like components. This may be the problem when service lives in lazy loading modules. What will happen if module is destroyed or instantiated multiple times. 

## Expected behavior:

To have feature to pickup current value from store without subscription.

## Other information:

Is there any way to get value from store without subscription?

**Comment by jotatoledo** [comment]
Services can implement OnDestroy...

**Comment by dalibor983** [comment]
@jotatoledo I think that `@Injectable()` does not have life-cycles event. Pleas gave me some link to documentation for that.

**Comment by dalibor983** [comment]
@jotatoledo You are right. I found in angular IPA that `OnDestroy` and `OnInit` can be applied to providers.

**Comment by dalibor983** [comment]
@jotatoledo It will be nice that we can pick up current state of something from store without subscribing.

In some situation we only wont the current value and we do not need to listen for changes.
