### ISSUE TITLE
Missing changelog, migration updates

### ISSUE THREAD

**Issue by LosD** [ngrx/platform#772]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## What is the current behavior?

No easy way to see changes from 4.x to 5.x, or how to safely update
## Expected behavior:

I would expect release procedures that includes keeping the changelog up to date.

**Comment by magnattic** [comment]
Really confusing, I just found out there is a ngrx 5 release. I'd like to keep up to date, but couldn't find any info about the changes, especially breaking ones.

**Comment by brandonroberts** [comment]
There is only one breaking change in the `5.0.0` release and that was to remove the deprecated `toPayload` function in `@ngrx/effects`. The changelogs reflect that change. This change was meant to be incremental, with us adding pipeable operators, schematics and bumping the minimum RxJS dependency. We did a "soft launch" to get the release out and will follow up with an official post soon.

**Comment by LosD** [comment]
Ohhhh... My bad. The main changelog is a linking file! Just saw that it hadn't been updated in 6 months.
