### ISSUE TITLE
Dispatching updateone and updatemany actions - help please

### ISSUE THREAD

**Issue by sergiobrr** [ngrx/platform#776]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
</code></pre>

## What is the current behavior?

I get an error trying to  dipatch an update action: Argument of type '{ company: { id: string | number; changes: Company; }; }' is not assignable to parameter of type '{ company: Update<Company>; }'.
## Expected behavior:

I'd like to  know how to dispatch an action updateOne and UpdateMany using adapters

## Version of affected browser(s),operating system(s), npm, node and ngrx:
"@ngrx/entity": "^5.0.1",
## Other information:
Could you please provide an example of entity updateOne and UpdateMany action dispatch?
Sorry for the noob question but i have the action defined as:
```
export class PatchOneSuccess implements Action {
	readonly type = PATCHONE_SUCCESS;

	constructor(public payload: {company: Update<Company>}) {}
} 
```
now i'd like to dispatch the action in effects.ts after success patching on the backend, how shlould dispatch it?

```
@Effect()
	patchOne$ = this.actions$.ofType(Company.PATCHONE)
		.map((action: Company.PatchOne) => action.payload)
		.switchMap(patching => this.companyService.patchOne(patching)
			.map((response: Model) => new Company.PatchOneSuccess(???????}))
			.catch(error => of(new Company.PatchOneFailure(error))));

```
Thanks a lot in advance for the great job

**Comment by brandonroberts** [comment]
Support questions should be asked on stackoverflow or in the [gitter channel](https://gitter.im/ngrx/platform)
