### ISSUE TITLE
@ngrx/schmatics should offer an entities flag when generating a feature?

### ISSUE THREAD

**Issue by matthewharwood** [ngrx/platform#779]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
Pretty common that you will want entities with a generate feature --group.  Currently, This isn't possible

## Expected behavior:
The goal is to get a directory structure that looks like the example-app Which currently isn't possible solely from schematics (you'll have to move some files around).  Generating a feature with the --group flag but it doesn't offer an --entity flag which would be ideal.

## Minimal reproduction of the problem with instructions:
`npx ng g module User --flat false`
`npx ng g feature user/User -m user.module.ts --group --collection=@ngrx/schematics`
`npx ng g container user/containers/Master --collection=@ngrx/schematics`
`npx ng g entity user/User --collection=@ngrx/schematics -m app.module.ts -r ../reducers/index.ts`
Then I have to move the files created by entity to the feature directories made with --group.

**Comment by rijine** [comment]
@brandonroberts @MikeRyanDev how to generate entity without creating model file ?
--model false kind of experience?
