### ISSUE TITLE
 Property 'forRoot' does not exist on type 'typeof StoreModule'

### ISSUE THREAD

**Issue by anakinjay** [ngrx/platform#784]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Feature request
[ X ] Documentation issue or request
</code></pre>

## What is the current behavior?

Not sure if this is a bug, or a documentation issue, but been using ngrx for a long time, started up a new project today the same as always and got this error.

Attempting to do: StoreModule.forRoot(reducers) produces the error:
**Property 'forRoot' does not exist on type 'typeof StoreModule'**

I've seen a few blog posts suggesting I try ForFeature instead but it produces pretty much the same error: **Property 'forFeature' does not exist on type 'typeof StoreModule'**

I've seen something else say just drop it all together and just use StoreModule.. but then I don't understand how to pass the reducers into it.

I tried looking at the example app: https://github.com/ngrx/platform/blob/master/example-app/app/app.module.ts but it's still using forRoot.

## Expected behavior:

should compile without errors

## Minimal reproduction of the problem with instructions:
attempt to load StoreModule with .forRoot in an angular module.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
node: 8.9
npm: 5.6
"@ngrx/core": "^1.2.0",
"@ngrx/effects": "^2.0.3",
"@ngrx/store": "^2.2.2",

**Comment by MikeRyanDev** [comment]
Your dependencies are out of date. You have listed NgRx v2.0.0 but the latest release is v5.0.0

**Comment by anakinjay** [comment]
I upgraded them to 5 and I'm still seeing the same error:

error TS2339: Property 'forRoot' does not exist on type 'typeof StoreModule'.

**Comment by andermev** [comment]
I have the same error, therefore I have used 'provideStore' instead of 'forRoot'.

**Comment by nivle** [comment]
> I have the same error, therefore I have used 'provideStore' instead of 'forRoot'.

makes sense

![image](https://user-images.githubusercontent.com/16451772/50406148-66b89980-07c0-11e9-8648-e8e7a666610e.png)

**Comment by initplatform** [comment]
if you just do `npm i ngrx` it will install version 2.0.1
you need to do `npm i ngrx/store`

**Comment by brandonroberts** [comment]
Yes, you would install using `@ngrx/store`. For more installation instructions, see the installation page https://ngrx.io/guide/store/install
