### ISSUE TITLE
How to handle if project does not have root level reducer

### ISSUE THREAD

**Issue by changLiuUNSW** [ngrx/platform#785]
In the example-app, it has root reducers like layout and router.
https://github.com/ngrx/platform/blob/master/example-app/app/reducers/index.ts#L32

However in my project, I do not have layout reducer and also I do not use @ngrx/router-store.

Just want to know how to handle it in this case ?

**Comment by brandonroberts** [comment]
Just provide with an empty object. 

```ts
StoreModule.forRoot({})
```
