### ISSUE TITLE
combine loading states at the root level

### ISSUE THREAD

**Issue by MurhafSousli** [ngrx/platform#804]
## I'm submitting a...
<pre><code>[x] Question</code></pre>

Hi, I would like to lock user actions and start a loading bar whenever a loading state is true in my state

## What is the current behavior?
Each sub-state has its own loading property which cannot be handled at once
```ts
this.store.pipe(
   select(fromPost.getLoading),
   tap((loading: boolean) => loading ? this.progressbar.start() : this.progressbar.complete())
).subscribe();
```

## Expected behavior:
A single loading state at the root level

```ts
this.store.pipe(
   select(fromRoot.getLoading),
   tap((loading: boolean) => loading ? this.progressbar.start() : this.progressbar.complete())
).subscribe();
```

I tried the following but I couldn't get it to work

in **app/reducers.index**
```ts
export const getLoading = createSelector(
  combineLatest(
    select(fromPost.getLoading),
    select(fromCollection.getLoading)
  ),
  map(([postLoading, collectionLoading]) => postLoading && collectionLoading)
);
```
How can I create a selector that combines loading states knowing that `fromPost` and `fromCollection` reducers are defined in lazy modules?

Thanks!

**Comment by brandonroberts** [comment]
Support questions should be asked on stackoverflow or the [gitter channel](https://gitter.im/ngrx/platform).
