### ISSUE TITLE
webpack@3.11.0 introduces compilation error

### ISSUE THREAD

**Issue by leachryanb** [ngrx/platform#806]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

```
@ngrx/effects/@ngrx/effects.js
@ngrx/store-devtools.js 
Error: No module factory available for dependency type: ContextElementDependency
    at Compilation.addModuleDependencies (/Users/163372/dev/monarch-dashboard/node_modules/@angular/cli/node_modules/webpack/lib/Compilation.js:215:21)
```
## Expected behavior:

Should build normally

## Minimal reproduction of the problem with instructions:

*STEPS TO REPRODUCE* 
1. Install webpack@3.11.0 in any project using ngrx
1. Try to build
3. Get errors

## Version of affected browser(s),operating system(s), npm, node and ngrx:
```
  npm: '5.6.0',
  node: '8.9.1',
...
├── @ngrx/effects@5.0.1
├── @ngrx/store@5.0.0
├── @ngrx/store-devtools@5.0.1
├── rxjs@5.5.6
├── webpack@3.11.0

```

**Comment by brandonroberts** [comment]
Provide more information with a reproduction of the issue.
