### ISSUE TITLE
Type Property Validation

### ISSUE THREAD

**Issue by amcdnl** [ngrx/platform#812]
## Issue
I'd like the ability to do type inference in a action factory rather than have to specify a type, however, ngrx has validation requiring a type which doesn't seem to necessarily required.

Code reference:

```javascript
    ActionsSubject.prototype.next = function (action) {
        if (typeof action === 'undefined') {
            throw new TypeError("Actions must be objects");
        }
        else if (typeof action.type === 'undefined') {
            throw new TypeError("Actions must have a type property");
        }
        _super.prototype.next.call(this, action);
    };
```

My implementation:

```javascript
class MyAction {}

switch(action.prototype.name) {
    'MyAction': do something
}
```

**Comment by MikeRyanDev** [comment]
Allowing types to be optional would break a core principle of NgRx and Redux: Actions should be serializable in both directions. Consider how this would work if you were receiving a stream of actions over a websocket connection or if you were building a PWA that stores actions in local storage when offline (hint: it wouldn't work).

**Comment by MikeRyanDev** [comment]
@amcdnl We are going to be introducing more "default" runtime checks into NgRx 6 (serialization and immutability). There will be a way to opt out of them at the root level with something we are calling "strict runtime checks". We don't see a reason why we couldn't make this another strict runtime check that could be disabled. Is this something you still want?

**Comment by amcdnl** [comment]
That’s clever. Ya I think third party libs could benefit from this.
