### ISSUE TITLE
Is not assignable

### ISSUE THREAD

**Issue by juniur** [ngrx/platform#815]
dear guys,
please, can you verify what are  these messages?

Inside ngrx/platform/example-app/app/reducers/index.ts
export const reducers: ActionReducerMap<State> = {
  layout: fromLayout.reducer,
  router: fromRouter.routerReducer,
};
error message:
Initializer type {layout: (state: State, action: LayoutActions) => State} is not assignable to variable type ActionReducerMap<State>

Initializer type {layout: (state: State, action: LayoutActions) => State, router: <T>(state: RouterReducerState<T>, action: RouterAction<any, T>) => RouterReducerState<T>} is not assignable to variable type ActionReducerMap<State>

export const metaReducers: MetaReducer<State>[] = !environment.production
  ? [logger, storeFreeze]
  : [];
error message:
Initializer type (((reducer: ActionReducer<State>) => ActionReducer<State>) | <T, V extends Action>(reducer: ActionReducer<T, V extends Action>) => ActionReducer<T, V extends Action>)[] | any[] is not assignable to variable type MetaReducer<State>[]

thank you.

**Comment by sandangel** [comment]
see #709

**Comment by juniur** [comment]
thanks, but it doesn't solve the issue.

**Comment by brandonroberts** [comment]
Closing as duplicate of #709
