### ISSUE TITLE
Store DevTools features (Jump, Skip, Test) not responding to config settings

### ISSUE THREAD

**Issue by akrueger** [ngrx/platform#819]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

With the following store-devtools config:

1. I am able to use Jump and Skip when they are set to false
2. Test generation tab doesn't show up even when set to true

```
StoreDevtoolsModule.instrument({
      name: 'Store DevTools Test',
      logOnly: true,
      maxAge: 25,
      features: {
        pause: false, // start/pause recording of dispatched actions
        lock: false, // lock/unlock dispatching actions and side effects    
        persist: false, // persist states on page reloading
        export: false, // export history of actions in a file
        import: false, // import history of actions from a file
        jump: false, // jump back and forth (time travelling)
        skip: false, // skip (cancel) actions
        reorder: false, // drag and drop actions in the history list 
        dispatch: false, // dispatch custom actions or action creators
        test: true // generate tests for the selected actions
      }
    })
```

## Expected behavior:

1. Jump and Skip are disabled when set to `false`
2. The Test generation tab is available when set to `true`

## Minimal reproduction of the problem with instructions:
https://angular-eaone9.stackblitz.io

## Version of affected browser(s),operating system(s), npm, node and ngrx:
macOS: `10.12.6`
Chrome: `64.0.3282.167`
Chrome Redux DevTools: `2.15.1`
Yarn: `1.3.2`
Node: `8.9.4`
ngRx: `5.1.0`

**Comment by dummdidumm** [comment]
Two things I found:
1. In your config, you set "logOnly" to true. This overwrites the features and only sets "pause" "export" and "test" to true (according to ngrx source code).
2. Even if I remove the "logOnly" option it does not work. Ngrx passes the features config through to the redux dev tools chrome extension but the extension does not seem to interpret them correctly. This looks to me like a bug on the chrome extension's side. For example, if I disable jump, the time travel bar disappears, but the possibility to jump does not go away.

-> This does not seem like a bug on ngrx's side to me.

**Comment by akrueger** [comment]
@dummdidumm I've seen these features work with React, so it seems the extension does have the ability to utilize them. I'm not sure if the API isn't correct, ngRx isn't passing something to the API correctl, or something else.

**Comment by dummdidumm** [comment]
I did some digging inside redux devtools and I think it is indeed a bug on their side. I created [this issue](https://github.com/zalmoxisus/remotedev-app/issues/40). If it gets fixed the test tab should appear.

**Comment by brandonroberts** [comment]
This issue should be fixed. Reopen if its not the case.
