### ISSUE TITLE
ngrx material icons

### ISSUE THREAD

**Issue by Kaffiend** [ngrx/platform#82]
Issued a request over at the material design vscode icons repository for the addition of ngrx icons. checkout [#92](https://github.com/PKief/vscode-material-icon-theme/issues/92) and comment if i missed something

@MikeRyanDev @brandonroberts @robwormald 
Suggested the github ngrx icon, if you guys are ok with its usage or have a better idea :smile: Thought i'd post an issue here to get some thoughts on the idea and ask about the image.

**Comment by bfricka** [comment]
Nice work

**Comment by Kaffiend** [comment]
the same request in another popular icon library can be tracked here [#1069](https://github.com/vscode-icons/vscode-icons/issues/1069)

**Comment by MikeRyanDev** [comment]
Thanks for passing this by us! We're OK with it, you have a good image 👍
