### ISSUE TITLE
Actions dispatched from a guard should be ignored when the time-travelling debugger is active

### ISSUE THREAD

**Issue by Alexislavie** [ngrx/platform#822]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

When using the time-travelling debugger, if the URL changes to a route which has a guard then this guard is executed and actions within the `canActivate()` method are dispatched.

When the time-travelling debugger is active, actions are dispatched from the guard and appear on the timeline.

## Expected behavior:

There should be a way to avoid this as:
- to ignore new actions dispatched when time-travelling the state, or
- adding the ability to test programmatically if the time-travelling debugger is active and decide not to dispatch a specific action then.

## Minimal reproduction of the problem with instructions:

I can not provide the code I'm working on as it is closed source.

Here is an abbreviated description of the architecture used...

Have a main module and a feature module.

<pre><code>
const routes: Routes = [
  { path: 'feature', loadChildren: '@modules/feature#FeatureModule' },
  { path: 'error/404', component: PageNotFoundContainerComponent },
  { path: '', redirectTo: 'home', pathMatch: 'full' },
  { path: '**', redirectTo: 'error/404' }
];

@NgModule({
  imports: [
    ...,
    RouterModule.forRoot(
      routes,
      { enableTracing: !environment.production }
    ),
    StoreModule.forRoot(reducers, {
      metaReducers: metaReducers
    }),
    StoreRouterConnectingModule.forRoot({
      stateKey: 'router'
    }),
    StoreDevtoolsModule.instrument({
      name: packageName,
      logOnly: environment.production,
      maxAge: 25
    }),
    EffectsModule.forRoot([RouterEffects]),
    ...
  ]
})
export class MainModule { }
</code></pre>

The feature module is responsible of managing todos object from a REST/JSON API.

<pre><code>
const routes: Routes = [
  {
    path: 'todos',
    component: TodosContainerComponent,
    canActivate: [
      TodosGuard
    ],
    runGuardsAndResolvers: 'paramsOrQueryParamsChange'
  },
  {
    path: '',
    redirectTo: '/error/404',
    pathMatch: 'full'
  }
];

@NgModule({
  declarations: [
    TodosContainerComponent,
  ],
  imports: [
    CommonModule,
    RouterModule.forChild(routes),
    StoreModule.forFeature('feature', reducers),
    EffectsModule.forFeature([
      TodosEffects
    ])
  ],
  providers: [
    TodosGuard
  ]
})
export class FeatureModule { }
</code></pre>

When navigating to `http://localhost:4200/feature/todos?page=0&size=20`, the `TodosGuard` guard `canActivate()` method dispatches a `[MyFeatureActionsGroup] Fetch Todos (Request)` with those queryParams as a payload. As an effect, the requested todos object are fetched by an HTTP service and the `[MyFeatureActionsGroup] Fetch Todos (Success)` action is triggered.
The guard then allow to navigate to the page and a container component displays the fetched todos from the ngrx store.

I use mainly the guard to check the URL queryParams and then prefetch the data.

Whenever the URL changes the guard is executed.

Below this line, I will try to resume the process of the bug I encounter.

**Initial sequence:**

- Navigate to `http://localhost:4200/feature/todos?page=0&size=20` in the browser address bar.
- A component trigger a router action to navigate to this URL:  `http://localhost:4200/feature/todos?page=1&size=20`.

<pre><code>
@ngrx/store/init
@ngrx/effects/init
@ngrx/store/update-reducers
ROUTER_NAVIGATION
[MyFeatureActionsGroup] Fetch Todos (Request)
[MyFeatureActionsGroup] Fetch Todos (Success)
[Router] Navigate
ROUTER_NAVIGATION
[MyFeatureActionsGroup] Fetch Todos (Request)
[MyFeatureActionsGroup] Fetch Todos (Success)
</code></pre>

**Then:**

With the time-traveller jump to the first `ROUTER_NAVIGATION` action and launch the replay.

**The sequence at the end looks like:**

<pre><code>
@ngrx/store/init
@ngrx/effects/init
@ngrx/store/update-reducers
ROUTER_NAVIGATION
[MyFeatureActionsGroup] Fetch Todos (Request)
[MyFeatureActionsGroup] Fetch Todos (Success)
[Router] Navigate
ROUTER_NAVIGATION
[MyFeatureActionsGroup] Fetch Todos (Request)
[MyFeatureActionsGroup] Fetch Todos (Success)
[MyFeatureActionsGroup] Fetch Todos (Request)
[MyFeatureActionsGroup] Fetch Todos (Success)
[MyFeatureActionsGroup] Fetch Todos (Request)
[MyFeatureActionsGroup] Fetch Todos (Success)
</code></pre>

As you can see, the guard as the URL changes is executed and dispatches again the `[MyFeatureActionsGroup] Fetch Todos (Request)` action.

The new actions generated are appended in the timeline and then played.

## Version of affected browser(s),operating system(s), npm, node and ngrx:

Tested on:

Windows: `7 Professional SP1 (build 7601)`
Node: `8.9.4`
npm: `5.6.0`
Yarn: `1.4.0`
@angular/{...}: `5.2.5`
@ngrx/core: `1.2.0`
@ngrx/{effects,schematics,store-devtools,store}: `5.1.0`
@ngrx/router-store: `5.0.1`
rxjs: `5.5.6`

Chrome: `64.0.3282.167`
Chrome Redux DevTools: `2.15.1`

Firefox: `58.0.2`
Firefox Redux DevTools: `2.15.1`

## Other information:

I have found interesting related issues, pull requests of my problem on GitHub:
- zalmoxisus/redux-devtools-extension#140
- gaearon/redux-devtools#167
- salsita/redux-side-effects#15

By the way, I can not pause the recording of events in the Redux DevTools window, neither persists them.
It does not do anything. This may be related to my need.

Thanks for your help.

**Comment by dummdidumm** [comment]
If #955 gets merged then you can use "lock" to avoid this issue.

**Comment by timdeschryver** [comment]
Closing this because https://github.com/ngrx/platform/pull/955 landed.
If this doesn't solve the problem, feel free to re-open the issue.
