### ISSUE TITLE
Make Example App compatible with StackBlitz

### ISSUE THREAD

**Issue by MurhafSousli** [ngrx/platform#827]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
</code></pre>

Can we have the ngrx example in a separate repo so we can play around with it using the Github stackblitz

https://stackblitz.com/github/ngrx/example-app

**Comment by brandonroberts** [comment]
That is the example app for 2.x, which is no longer being updated. There are some existing issues that won't allow us to use the latest version with stackblitz directly from the repo yet.

**Comment by MikeRyanDev** [comment]
Reopening. Sounds like you are asking if the current one can be made compatible.
