### ISSUE TITLE
system.js build failing due to "rxjs/operators" not found.

### ISSUE THREAD

**Issue by aamir1995** [ngrx/platform#842]
## I'm submitting a...

<pre><code>
[ x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

Production build failing with system.js due to `rxjs/operators` not found in `@ngrx/effects`, it was working fine in `@ngrx/effects 5.0.1` but stopped building now, it think this regression occurred due to https://github.com/ngrx/platform/commit/c8560e4 
![image](https://user-images.githubusercontent.com/10736453/36365927-9a08c26a-156d-11e8-9f00-6a7c2e587e8d.png)

## Expected behavior:

The project should build fine without above error.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
All.

**Comment by josh-sachs** [comment]
I think this issue is a dependency on rxjs 5.5.5+

**Comment by robwormald** [comment]
This is unrelated to NgRx. See for a config file using the new packages https://github.com/angular/angular/blob/master/integration/hello_world__systemjs_umd/src/systemjs.config.js#L36-L43
