### ISSUE TITLE
@ngrx/effects/testing has no exported member 'EffectsTestingModule' - Karma, Jasmine, Angurlar5

### ISSUE THREAD

**Issue by hetdev** [ngrx/platform#843]
I'm trying to code some test in an angular5 app, using @ngrx/effects 5.1.0, but when i'm trying to export the EffectsTestingModule and EffectsRunner from '@ngrx/effects/testing Karma can't importing.

Module '"PROJECT_PATH/@ngrx/effects/testing"' has no exported member 'EffectsTestingModule'.
Module '"PROJECT_PATH/@ngrx/effects/testing"' has no exported member 'EffectsRunner'.

`import { EffectsTestingModule, EffectsRunner } from '@ngrx/effects/testing';`

Anyone knows whats the problem or i'm missing installing something

**Comment by abdulhaq-e** [comment]
You're probably reading outdated docs. The current method for testing effecrs is documented here: https://github.com/ngrx/platform/blob/master/docs/effects/testing.md

What you are describing is the testing method used in ngrx v1 I think
