### ISSUE TITLE
Is there way to call the actions of feature modules from root module

### ISSUE THREAD

**Issue by vegeta03** [ngrx/platform#846]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ x] Support request
</code></pre>

I am trying to change the lazy loaded feature modules store to the initial state when logout action is called from the root module.

Thanks.

**Comment by brandonroberts** [comment]
Support requests should be asked on stackoverflow or in the [gitter channel](https://gitter.im/ngrx/platform)

**Comment by vegeta03** [comment]
found a solution from a comment from stackoverflow
https://stackoverflow.com/questions/48884973/ngrx-is-there-way-to-call-the-actions-of-feature-modules-from-root-module
