### ISSUE TITLE
NgRx action queue 

### ISSUE THREAD

**Issue by yukund** [ngrx/platform#847]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
</code></pre>

## Other information:

**Background :**
I would like to have an queue that includes an collection async Actions,  and only one action can be executed at a time (with corresponding effect/RESTservice call logic). Once the current action is resolved , we move the the next.
For example, we fire 10 actions in a particular order, so we can get them executed one by one in the same order.

**Question:**
Does NgRx support action queue? or what is the equivalent feature/library I should use? 
I would appreciate any suggestions/ideas.

**Comment by brandonroberts** [comment]
Support questions should be asked on stackoverflow or in the [gitter channel](https://gitter.im/ngrx/platform)
