### ISSUE TITLE
Question: Docs on Root State and Feature State

### ISSUE THREAD

**Issue by bhaidar** [ngrx/platform#850]
Hello,
If possible to point me to some resources online related to:
- Feature Stores
- Using Feature Store State defined in Module 1, using the State in Module 2
- Using Store State defined in Root app, using the State in Modules 1 and 2 (Shared State)

I am trying to organize/structure my new app, where I use a Feature Module per feature, and still analyzing whether I use a Store per Module, but then I might need to use a State defined in Module 1, use it in Module 2, etc. Also, I might define a shared State on the root app, use that State inside Modules 1 and 2.

Thanks
Bilal

**Comment by dummdidumm** [comment]
Module 1 should only use the state / actions of module 1 and the core/common/shared module, and not the state / actions of module 2. This also is true for services / components.

The example application organizes it like this:
Main reducer file, which declares the state visible for all modules: https://github.com/ngrx/platform/blob/master/example-app/app/reducers/index.ts
For each feature, a reducer file, which extends from that state and adds its part: https://github.com/ngrx/platform/blob/master/example-app/app/auth/reducers/index.ts ("export interface State extends fromRoot.State")
The components of that feature use that interface and the given selectors: https://github.com/ngrx/platform/blob/master/example-app/app/auth/containers/login-page.component.ts

That said, you get the whole state from the Store and select the substate you want from it via selectors.

**Comment by bhaidar** [comment]
@dummdidumm 
Thanks a lot for getting back to me. I never noticed the sample app btw, it looks helpful. I am going to go through it for sure.

Just to confirm my knowledge so far:
- The root module defines an "App" State with its own reducers (with 2 sub-states inside)
- Each module extends the "App" State interface by adding a new Feature State & sub-states with its own set of reducers.
- Each module configures the StoreModule for this specific Feature Module with the extended "App" State and its own reducers.
- The "createFeatureSelector" function would make use of the "App" State to return the specific Feature State we are requesting?

So by extending the State, the Store knows that I have new "properties" States and know what their reducers are without having to define them in the Root module?

However, I see no place in the feature modules where the "App" State is being queried or used.

Thanks
Bilal

**Comment by brandonroberts** [comment]
Support questions should be asked on stackoverflow or the [gitter channel](https://gitter.im/ngrx/platform).
