### ISSUE TITLE
RFC: Dev Tools support for persist, lock, pause

### ISSUE THREAD

**Issue by dummdidumm** [ngrx/platform#853]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
The redux dev tools extension has the following features which are not usable with ngrx at the moment:
- persist: If enabled, the state of the redux dev tools survive a full reload of the page. The persisted actions are fired against the initial state. This makes developing applications faster. Imagine you don't use HMR and have to fix something from the example application - every reload throws you back to the login page. With the persist feature, this would no longer be the case.
- lock/unlock: If locked, no new actions will get through to the reducer, the app is basically frozen. In combination with persist / HMR, this is a great developer experience when you want to focus on a specific feature with a specific number/order of actions.
- pause/unpause: If paused, the redux dev tools will not record the actions fired. The app will continue to work. Useful if you don't want to get spammed with lots of actions. When you unpause, the current state will be committed and recording is resumed.

Locking and pausing is explained in more details [here](https://medium.com/@zalmoxis/improve-your-development-workflow-with-redux-devtools-extension-f0379227ff83).

## Expected behavior:
Features also work with ngrx dev tools.

## Other information:
I'm willing to help with PRs.

**Comment by MikeRyanDev** [comment]
I'm down with these changes for NgRx 6. I don't know enough about Redux's devtools to help implement these. Would you be able to make these changes @dummdidumm?

**Comment by dummdidumm** [comment]
Sure, I'll look into it. The referenced PR is a first step to lay the groundwork for persist.
