### ISSUE TITLE
Add Entity Relationship Selectors to Entity

### ISSUE THREAD

**Issue by MikeRyanDev** [ngrx/platform#859]
Internally we have developed common patterns for creating selectors that help resolve entity relationships. We should consider making them generic and folding them into Entity.

**Comment by dsebastien** [comment]
Can you share more details about this?
It the idea to denormalize data when taking it out of the store using selectors?

**Comment by Nosfistis** [comment]
Are there any active plans for this? It's a cool major feature, and causing a lot of custom wiring which contradicts the ease of use @ngrx/data provides.

**Comment by satanTime** [comment]
Hi guys, I was struggling with the same issue and implemented a lib that tries to solve it: 
https://www.npmjs.com/package/ngrx-entity-relationship

let me know your thoughts.
