### ISSUE TITLE
Exporting a selector out of a library complains of Dictionary cannot be named

### ISSUE THREAD

**Issue by ymcnicoll** [ngrx/platform#865]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
When compiling a library using Ng-Packagr I get errors from un-exported types used by selectors. I dont get this error if using Reselect to create selectors.

Part of the issue is caused by Entity using un-exported Dictionary type for its entities. 

## Expected behavior:
Compiling without errors

## Minimal reproduction of the problem with instructions:

1. create a project following sample from ng-packagr.
2. create module withing the project with feature and selectors
3. build

**Comment by peterbsmith2** [comment]
@ymcnicoll would you provide a stackblitz or repo or similar example to reproduce then I can PR for you.
