### ISSUE TITLE
RFC: feat(entity) add selection option for entity

### ISSUE THREAD

**Issue by yairtawil** [ngrx/platform#869]
## I'm submitting a...
<pre><code>[x] Feature request
</code></pre>

## What is the current behavior?

No selection option
## Expected behavior:

Ability to select entities (multiple/single selection).

## Demo:
https://yairtawil.github.io/ngrx-entity-selection/

## Pull Request:
#863

**Comment by brandonroberts** [comment]
Comments left on PR
