### ISSUE TITLE
Unnecessary Angular Dependency?

### ISSUE THREAD

**Issue by josh-sachs** [ngrx/platform#870]
## I'm submitting a...

<pre><code>
[x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

Cannot build ngrx-platform without angular 5.

## Expected behavior:

It appears most modules should be framework agnostic, only ngrx/router and the example-app having an angular dependency.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
ngrx v5

## Other information:
The platform modules are distributed so that they can be cherry-picked based on required features.  I'm having a hard time finding code outside of the example-app and ngrx/router that imports from angular at all.

**Comment by brandonroberts** [comment]
ngrx is a set of reactive libraries built for Angular, so its not meant to be framework agnostic.

**Comment by josh-sachs** [comment]
sorry - they could be agnostic to the version of angular.  In general packages should require the lowest compatible dependency version.  I don't see an obviously compelling reason for forcing people to upgrade angular versions just for the sake of upgrading.

**Comment by MikeRyanDev** [comment]
@josh-sachs Ah, yes, that's a good point. We don't have the infrastructure in this repo to run our test suite against different versions of Angular. If someone made a pull request to add that then I would have no problem changing the dependency ranges on our packages.

**Comment by josh-sachs** [comment]
I can try and look into this at some point - but I think it is pretty light touch, I mean store, entities and core don't really seem contain anything angular specific outside of their ngModule declarations.
