### ISSUE TITLE
Entity Default Values

### ISSUE THREAD

**Issue by josh-sachs** [ngrx/platform#871]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[X] Documentation issue or request
</code></pre>

## What is the current behavior?

Prior to entities, when new data came down the pipe we might merge each entity with default values prior to insertion into state... 

`return { ...state, [data.Id]: { ...ENTITY_DEFAULT, data} };`

This would prevent fields on the entity from being put into state as `undefined`.

There doesn't seem to be a clean way to do this with entities.... looks like I have to compose an `Add` and `Update` within the reducer, and I can't leverage the cleaner `Upsert` methods.

```
  const list = action.payload;         
  state = Adapter.AddMany(list.map(x => ({ ...TEMPLATE_DEFAULT, ...x })), state);   
  return Adapter.UpdateMany(list.map(x => ({ id: x.Id, changes: x })), state);
```

## Expected behavior:

I would propose that a default representation of the entity be provided when the adapter is created...

```
const ENTITY_DEFAULT: Readonly<Widget> = {
  Id: null,
  Label: "Unnamed Widget",
};

const adapter = createEntityAdapter<Widget>({
    sortComparer: (a, b) => `${a.Label}|${a.Id}`.localeCompare(`${b.Label}|${b.Id}`),
    selectId: (x) => x.Id,
    entityDefault: ENTITY_DEFAULT,                                                                  
});
```

Internally, the adapter should merge any new/added entities with the defaults prior to insertion into the state.  The behavior during update operations would remain unchanged. 

## Version of affected browser(s),operating system(s), npm, node and ngrx:
ngrx-entity 5x

## Other information:
The idea here is that not all API endpoints always return a full representation of an entity.  For example, an abbreviated summary may be returned during a LIST operation, with the entire entity not being hydrated until a DETAIL operation is performed sometime in the future.  In this case, the entity should not exist in state with fields present in it's type/interface as `undefined`.

**Comment by brandonroberts** [comment]
Why can't you use the `Upsert` methods? I'd rather add an example of handling partial entities than add additional configuration to the API.

**Comment by josh-sachs** [comment]
When an entity is first inserted into its store, it needs to be merged with its default values.  When it subsequently updated, it should not be merged with its defaults. 

The recently added upsert method abstracts the logic away from the reducer around insert vs update, but it does not have any means by which to merge entity defaults when the resolved operation is an insert. 

Consider a common scenario, I have two API endpoints

```
List => EntitySummaryModel[]
Detail => EntityDetailModel
```

The corresponding reducer looks something like...

```
case EntityActionTypes.OnEntitiesListed: 
     const entities= action.payload.map(e => { ...ENTITY_DEFAULTS, ...e });
     return adapter.upsert(entities.map(e => { id: e.Id, changes: e }), state)

case: EntityActionTypes.OnEntityDetailed:
      return adapter.upsert({ id: action.payload.id, changes: action.payload }, state)
```

Any time the list reducer code runs, it will overwrite detail properties that are not also summary properties.  Instead, the list method has to check if an entity already exists and merge it as well prior to calling `upsert`... which defeats the point.  This is a trivial example, but gets much more complicated for entities for which properties are spread out across multiple API calls.

**Comment by josh-sachs** [comment]
bear in mind, this should absolutely be an optional configuration.  If a default isn't provided it would behave as it does now.  If a default is provided, `insert` and `upsert->insert` would merge entities with the defaults prior to insertion into the store.

**Comment by codefactorydevelopment** [comment]
@josh-sachs  Let me just try to understand...are you saying you're keeping only the list of entities in your state and then for details, you read it from that list:

```
State = {
listOfEntitiesFullRepresentation:FullEntityType[]
}
```

 or do you have your state something like:

```
State = {
listOfEntitiesCompactRepresentation:CompactEntityType[],
SelectedEntityDetailsFullRepresentation:FullEntityType
}
```

where for view/edit some entity you load full details from server on request?

**Comment by tdeschryver** [comment]
So if I understand this correctly, you don't want to have your loaded entities be overwritten with the default values? If that's the case, you could do
```
const entities = action.payload.map(e => { ...ENTITY_DEFAULTS, ...e, ...state.entities[e.Id] });
return adapter.upsertMany(entities , state)
```

**Comment by brandonroberts** [comment]
We won't be adding this to the API. You can achieve the same result with reusable functions that build up the default data.
