### ISSUE TITLE
ng generate feature erroneously creates actions outside the root folder

### ISSUE THREAD

**Issue by lanovoy** [ngrx/platform#873]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

Executing following command `$ ng generate feature User -m app.module.ts`
resulted in:
<pre><code>
  create <b>app/</b>user.actions.ts (222 bytes)  <-- <i>wrong location</i>
  create angularApp/app/user.reducer.ts (373 bytes)
  create angularApp/app/user.reducer.spec.ts (322 bytes)
  create angularApp/app/user.effects.ts (320 bytes)
  create angularApp/app/user.effects.spec.ts (588 bytes)
  update angularApp/app/app.module.ts (1690 bytes)
</code></pre>
## Expected behavior:

user.actions.ts are expected to be created inside the root folder (angularApp in our case):

`angularApp/app/user.actions.ts`

## Version of affected browser(s),operating system(s), npm, node and ngrx:

    "@ngrx/effects": "^5.1.0",
    "@ngrx/entity": "^5.1.0",
    "@ngrx/router-store": "^5.0.1",
    "@ngrx/store": "^5.1.0",
    "@ngrx/store-devtools": "^5.1.0",
    "@ngrx/schematics": "^5.1.0",

`$ ng --version

Angular CLI: 1.7.0
Node: 9.2.0
OS: win32 x64`

## Other information:

.angular-cli.json has root configured as 

`  "apps": [
    {
      "root": "angularApp",
...
`

**Comment by brandonroberts** [comment]
Can you provide a repo with a reproduction? I tested this against a clean CLI 1.7 project with no issues.

**Comment by lanovoy** [comment]
Hey Brandon,

Thanks for fast reply. Please try this branch here https://github.com/lanovoy/angular-starter/tree/test-ngrx-schema 

npm i
and then ng generate feature User -m app.module.ts

**Comment by lanovoy** [comment]
Couple files didn't get pushed properly for some reason. Now it should be good and reproducible with that branch. https://github.com/lanovoy/angular-starter/tree/test-ngrx-schema

**Comment by brandonroberts** [comment]
I still don't where your repo is configured to use a different root than `src`

**Comment by lanovoy** [comment]
Brandon,
It doesn't look like root matter at all. This repo uses default src root and it's reproducible just the same there...

**Comment by brandonroberts** [comment]
I see. I'll take a look this week

**Comment by lanovoy** [comment]
Thanks Brandon!
Easy copy-paste command for reproduction:
`git clone https://github.com/lanovoy/angular-starter.git && cd angular-starter && git checkout test-ngrx-schema && npm i && ng generate feature User -m app.module.ts`

**Comment by brandonroberts** [comment]
This is a dependency issue in your project. I removed the following from your package.json and let it install the versions in @angular/cli and it worked correctly.

```
    "@angular-devkit/core": "^0.4.3",
    "@angular-devkit/schematics": "^0.4.3",
```
