### ISSUE TITLE
Expanded information on meta reducers

### ISSUE THREAD

**Issue by oleosjo** [ngrx/platform#875]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[*] Documentation issue or request
</code></pre>

I have a reducer that handles the state of an image upload form in a component (upload queued, preview image, etc). That works fine if I'm on one page at a time. However, I need to be able to have any number of image upload components on the same page. So I need to have several "instances" of reducers, and actions, and effects for each image upload form, but use the same reducer, etc. Is there a pattern in which I can achieve this?

This article seems to be the closest solution I could find: https://hackernoon.com/ngrx-store-reuse-reducer-logic-b6c0449e695d. But that is older, and doesn't seem ideal. I want to find the NGRX 5 way of doing this.

I looked at the current meta reducers documentation, but there's only that one example of logging, and that doesn't cover actions. Maybe I'm not understanding. Any help would greatly be appreciated!

**Comment by MattiJarvinen-BA** [comment]
Without knowing much of your application, perhaps you could handle those uploads like entities?

```
"imageUploads": {
  "fieldName": {
     "queued": true,
     "preview": "https://..." // or "data:image/jpeg;base64,...",
     ....
   }
}
```

**Comment by brandonroberts** [comment]
Support questions should be asked on stackoverflow or the [gitter channel](https://gitter.im/ngrx/platform).
