### ISSUE TITLE
store pipe

### ISSUE THREAD

**Issue by juniur** [ngrx/platform#876]
## I'm submitting a...
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request

@ngrx/store

why using store.pipe(select(...)) instead of store.select?

can i request to have a documentation about this?

thanks,

juniur

**Comment by brandonroberts** [comment]
We are following convention introduced in RxJS 5.5 for better operator support. https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md

**Comment by onedotover** [comment]
Using combineLatest with select is now a little more verbose. Something about this doesn't feel right. Is this the recommended way to use pipes with something like combineLatest?

Before
```
combineLatest(
  store.select(selectItemA),
  store.select(selectItemB),
).subscribe(...)
```
After
```
combineLatest(
  store.pipe(select(selectItemA)),
  store.pipe(select(selectItemB)),
).subscribe(...)
```

**Comment by vkiperman** [comment]
I'm refactoring to make my selects piped. However my tests fail. The output says that the Action in the reducer is undefined. Anyone else come across anything similar?

**Comment by timdeschryver** [comment]
@vkiperman feel free to open up a new issue (with some code, or even better a reproduction) or hop into our [gitter channel](https://gitter.im/ngrx/platform).

**Comment by Max101** [comment]
@brandonroberts could you explain why is this "consistent" with RxJs and why does it need to be consistent? 
It makes no sense really to have this kind of consistency at the expense of cleaner code.
RxJs introduced pipes for one main purpose, tree-shaking. There is 99.9% no need for tree-shaking of the select method in NgRx. (There are other reasons yes for RxJs to do piping but they are not part of Rx) 
Is there an exact timeline on when this is planned to be completely removed?

**Comment by timdeschryver** [comment]
@Max101 we un-deprecated `select`, see #1382.
