### ISSUE TITLE
Return observable from `store.dispatch`

### ISSUE THREAD

**Issue by mxchange** [ngrx/platform#877]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
`store.dispatch` not returning observable

## Expected behavior:
I'd lik the observable in the `.dispatch()` method to be returned, in order to do a `.map` or `.catch` on it.

Not sure if it would be that simple, but in most redux libraries for react it does return something like a `Promise` so you can do `.then()`.

The alternative right now is to either listen to `actions$: Actions` or `actionSubject$: ActionSubject` and listen to a `DONE` or `FAILED` action. Or adding a callback to the action, which I'd like to avoid.

**Comment by jotatoledo** [comment]
Could you add some examples of any library that already does this?

**Comment by brandonroberts** [comment]
What value do you get in doing this? I feel like it gives you incentive to create too many subscriptions to manage, which is anti-pattern. Listening to the actions stream would be a better pattern to follow.

**Comment by mxchange** [comment]
@jotatoledo I think https://www.npmjs.com/package/redux-thunk does it.

@brandonroberts I agree that this should be used sparingly, but the difference is that you can have 2 of the same components that have their own follow-up after the dispatch, versus listening to the same generic action in 2 different components.

So having 2 instances of a component doing:
```
this.store.dispatch('UPLOAD_DOCUMENT');
... 
this.actions$.ofType('UPLOAD_DOCUMENT_DONE').subscribe((payload)=> {
    this.document = payload.document;
   // This triggers for either component instance, setting the document-response on both components
});
```
Versus:
```
this.store.dispatch(new UploadDocument(document)).map((payload) => {
   this.document = payload.document;
   // This should not trigger for other component instances
});
```

I still don't really like either, and possibly the solution for using the same generic action for 2 different instances would be to either not use redux at all, or doing something with a `meta` property like:

```
this.formId = 1;
this.store.dispatch(new UploadDocument(document, this.formId));
...
this.actions$.ofType('UPLOAD_DOCUMENT_DONE').subscribe((payload, meta)=> {
    if (meta !== this.formId) return;
    this.document = payload.document;
   // This should only set the document on the right instance.
});

```
Where the action is:

```
export class UploadDocument implements Action {
  readonly type = UPLOAD_DOCUMENT;
  readonly meta = FORM_ID;
  constructor (public payload: Error, public meta: number) {}
}
```
I don't like that one either because you'd have figure out a way to generate a unique id for these form components etc. and I feel it's overcomplicating it a lot.


The main problem is that setting the `this.document` isn't really doable from an effect, other than temporarily setting it to the store, but there's all kinds of functions and prototypes in there that I don't think belong in the store and are not serializable.
You could replace `this.document` with `this.dialog.close()` for another example where I don't know how else to achieve it other than having a `callback` or doing `.then` or `.map` after dispatch, _without having it break when using multiple instances of the component_..

**Comment by dummdidumm** [comment]
Regarding this.dialog.close(): If you have the dialog connected to ngrx aswell, you could do something like a callback, but passing the action that tells the state to close the dialog instead.

Action
```
export class DoSth implements Action {
   ...
   constructor (public sth, public callback: Action) {}
}
```

Component
`this.store.dispatch(new DoSth(someVariable, new CloseDialog(dialogId));`

Effect
```
this.actions
  .ofType('DoSth')
  ... // some api call. returns doSthAction
  .map((doSthAction) => doSth.Action.callback)
```

Generally I feel that these are situations where you really need to think twice about what and how much to put into ngrx/redux, and most of the time there is no solution that solves the problem without drawbacks.

**Comment by brandonroberts** [comment]
I still feel like this should be handled by subscribing to the actions stream. We want to keep the notions of dispatching and listening to actions separate from each other.

**Comment by MikeRyanDev** [comment]
For what it is worth, @vsavkin's talk about State Management Patterns introduces correlation IDs to make this straightforward: https://www.youtube.com/watch?v=vX2vG0o-rpM

**Comment by mpnewcomb** [comment]
This is my biggest hangup with the whole NGRX action pattern... it smells badly. I dispatch an action but have no direct way to know if it succeeded or failed. Furthermore, if the same action can be dispatched from multiple components they all have to monitor the success/failure and somehow magically determine if they were the one to dispatch that event so they can clean up...

**Comment by aFarkas** [comment]
By not allowing a feature that might be used incorrectly my code now is less maintainable and more error prone. well done!

**Comment by alex-okrushko** [comment]
@mxchange has the right suggestion:
> either not use redux at all

NgRx is not for all the cases and when you just need a result from a simple call, don't need to store it or share with any other components, then doing it via injected service is perfectly fine.

Otherwise it feels like trying to stretch the pattern to fit the needs that it's not designed for.

**Comment by aFarkas** [comment]
@alex-okrushko 

> NgRx is not for all the cases... Otherwise it feels like trying to stretch the pattern to fit the needs that it's not designed for.

You assume a lot here. It's probably the best example why to use a store for data. In my case it's about the user data that is coming from the user service and portions of this data are used by multiple components on every page. But some editing errors of the user data should only be displayed by the component that triggered the failed change-attempt. 

For me the solution is to not use effects to update the store. But coming from React/Redux where you have this feature it feels like a mistake.

**Comment by bohdanzhylavskyi** [comment]
:(
