### ISSUE TITLE
store should support falsey state

### ISSUE THREAD

**Issue by jbedard** [ngrx/platform#880]
## I'm submitting a...
<pre><code>[X] Bug report  
</code></pre>

## What is the current behavior?
Feature store/reducers with a falsey state fallback to the initial state. This might only be for feature and not root reducers?

See https://github.com/ngrx/platform/blob/7f49b9f413471306d614cd5eae8b4e8d7e41f611/modules/store/src/reducer_manager.ts#L46 where `state || initialState` is used.

## Expected behavior:
Any non-undefined state value should be considered "set" and not be reset to the `initialState`.

https://github.com/ngrx/platform/blob/7f49b9f413471306d614cd5eae8b4e8d7e41f611/modules/store/src/reducer_manager.ts#L46 should be changed to `(state !== undefined) ? state : initialState`

## Minimal reproduction of the problem with instructions:
Can create one if necessary...?

## Version of affected browser(s),operating system(s), npm, node and ngrx:
I'm using 5.x

## Other information:
As an example... in my case this feature-store represents the user session. An empty store value (`undefined`) means the session state is unknown (not fetched yet), a `null` value means no session exists and a `Session` object means the user is logged in. In this case the `null` value is being converted to `undefined`.

**Comment by jbedard** [comment]
Actually... should `initialState` be the initial state, or the default state? Is it correct that an `undefined` store value should always be converted to the `initialState` like the feature store does (in one case) today?

**Comment by brandonroberts** [comment]
Fixed via #886
