### ISSUE TITLE
[Feature Request] Schematic Store should generate an Angular barrel module

### ISSUE THREAD

**Issue by michaeljota** [ngrx/platform#881]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
Schematic store generates a Typescript barrel module. 

## Desired behavior:

Schematic Store could generate an Angular barrel module, following the Style Guide, and the current behavior that Router modules have. Currently new routers module, are Angular barrel modules importing the needed modules, with all the necessary configuration in the same file. 

Could generate something like this for root Store: 
```typescript
import { NgModule } from '@angular/core';
import {
  ActionReducer,
  ActionReducerMap,
  createFeatureSelector,
  createSelector,
  MetaReducer,
  StoreModule,
} from '@ngrx/store';
import { StoreDevtoolsModule } from '@ngrx/store-devtools';

import { environment } from './../environments/environment';

export class State {}

const reducers: ActionReducerMap<State> = {};

const metaReducers: MetaReducer<State>[] = !environment.production ? [] : [];

@NgModule({
  imports: [
    StoreModule.forRoot(reducers, { metaReducers, initialState: new State() }),
    !environment.production ? StoreDevtoolsModule.instrument() : [],
  ],
  declarations: [],
})
export class AppStoreModule {}
```

And something like this in a feat Store
```typescript
import { NgModule } from '@angular/core';
import {
  ActionReducer,
  ActionReducerMap,
  createFeatureSelector,
  createSelector,
  MetaReducer,
  StoreModule,
} from '@ngrx/store';

import { environment } from '../../environments/environment';

export class HeroesState {}

export const heroesReducers: ActionReducerMap<HeroesState> = {};

const metaReducers: MetaReducer<HeroesState>[] = !environment.production
  ? []
  : [];

@NgModule({
  imports: [
    StoreModule.forFeature('heroes', heroesReducers, {
      metaReducers,
      initialState: new HeroesState(),
    }),
  ],
  declarations: [],
})
export class HeroesStoreModule {}
```

This allow to find all the configuration related to the Store in a single file, and it does not overload with information, because all the declarations are about the Store.

Likewise, in the application module, is only needed one import, and any change regarding the Store, would only affect this file.

**Comment by brandonroberts** [comment]
This is not something we're going to implement as a standard.

**Comment by michaeljota** [comment]
But why? Angular is moving into this direction about importing modules that needs configuration. Maybe you could let this open and see the community reaction. You do have an open issue about reorganizing the example app to align the code into the current Angular Standard, and this is one of them.
