### ISSUE TITLE
RFC: Schematics: Extend from @schematics/angular

### ISSUE THREAD

**Issue by MichaelWarneke** [ngrx/platform#882]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

Some individual angular cli schematic generators are are listed in the collection.json.
This list has to be kept updated.

## Expected behavior:

Extend the ngrx schematics from @schematics/angular and not the individual generators.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
@ngrx/schematics 5.1.0

## Other information:
The angular devkit has been updated to allow extends.
https://github.com/angular/devkit/issues/34
I created a local branch with required changes and can pull if requested.
Changes:
- Updated Angular CLI to 1.7.2 (for the new "extends" scheme element) 
- Removed class, component, directive, enum, guard, interface, module, pipe and service from the collection.json
- Added "extends": ["@schematics/angular"] to the collection.json
- Implemented a test to check if ngrx schematics runs the extended angular schematics generator ( g class)

**Comment by brandonroberts** [comment]
Fixed via 0e17aad60ae4ff22d55be4643905005b6da952d1
