### ISSUE TITLE
Models not updating when the environment prod is false

### ISSUE THREAD

**Issue by gdmartinez93** [ngrx/platform#888]
## I'm submitting a...

<pre><code>
[X ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
When the environment prod is false, the models not work correctly. The first time, the models are working OK but next a submit that models is not updating. The "solution" is to activate the environment prod and with that works again.

Any idea for why that situation is happend?

## Expected behavior:
The models are updating with any change and not depend to the environment prod o dev.

## Minimal reproduction of the problem with instructions:
https://github.com/gdmartinez93/ngrx4-issue-888
http://subirimagen.me/uploads/20180304072450.gif

## Version of affected browser(s),operating system(s), npm, node and ngrx:
Angular CLI: 1.6.4
Node: 9.6.1
OS: linux x64

## Other information:
Sorry, i tagged wrong this issue, really is a Regression

**Comment by jotatoledo** [comment]
Your gif doesn't count as a minimal reproduction, it only shows the existence of an error.

**Comment by gdmartinez93** [comment]
Hi, is right i can't know the exactly steps for reproduce that behavior, but i created a repo https://github.com/gdmartinez93/ngrx4-issue-888 is a example login the credentials are an user 'test' and any password. This is a repo based on the example-app for the current ngrx version, you can try test make a failure login the first time the models are working but later not more.

**Comment by brandonroberts** [comment]
You shouldn't use `ngModel` in conjunction with store. Most likely the state was frozen and broken the model binding.
