### ISSUE TITLE
StoreDevtools with actionSanitizer does not compile with AOT/Prod

### ISSUE THREAD

**Issue by jmannau** [ngrx/platform#891]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

When adding either an actionSanitizer or stateSantizer to StoreDevtoolsModule and then compiling using --prod and error occurs.

## Expected behavior:

When using an actionSanitizer or stateSantizer, it should be possible to compile the app using production/AOT mode.

## Minimal reproduction of the problem with instructions:

1. Install https://github.com/jmannau/platform/tree/v5.1.0-storedevtool-actionsantizer-aot This has been updated to include a simple actionSanitizer (https://github.com/jmannau/platform/blob/v5.1.0-storedevtool-actionsantizer-aot/example-app/app/app.module.ts#L69)
2. start the example app using `yarn run example:start:aot`
3. The following compile error is thrown

```
ERROR in Error during template compile of 'AppModule'
  Function expressions are not supported in decorators in 'ɵ0'
    'ɵ0' contains the error at app/app.module.ts(69,24)
      Consider changing the function expression into an exported function.
```
## Version of affected browser(s),operating system(s), npm, node and ngrx:
@ngrx 5.1.0

## Other information:
None

**Comment by brandonroberts** [comment]
Your `actionSanitizer` should be an exported function. AoT doesn't support arrow functions.

```ts
export function actionSanitizer(action: Action) {
  return action;
}

@NgModule({
    StoreDevtoolsModule.instrument({
      name: 'NgRx Book Store DevTools',
      logOnly: environment.production,
      actionSanitizer: actionSanitizer,
    }),
```
