### ISSUE TITLE
Schematics: mix of plural vs singular file names

### ISSUE THREAD

**Issue by goelinsights** [ngrx/platform#894]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
Schematics generates files with a mix of plurals and singulars. (i.e., actions, effects, component, reducer, model)

## Expected behavior:
I'd expect that they'd all be singular based on existing CLI norms (component, model, etc). Trying to understand why some shouldn't be

## Minimal reproduction of the problem with instructions:
ng generate action ActionName

## Version of affected browser(s),operating system(s), npm, node and ngrx:
"@ngrx/schematics": "^5.1.0"

## Other information:
Sorry for being OCD, just seeing if I'm missing something as I'm trying to be consistent but used the singular in a big app and seeing a style conflict.

**Comment by brandonroberts** [comment]
The files represent what's being generated. A set of `actions`, a set of `effects`, a single `reducer`.
