### ISSUE TITLE
Store: Handling of @ngrx/store/update-reducers Action on Startup leads to strange behaviour for initialStates

### ISSUE THREAD

**Issue by tnobody** [ngrx/platform#906]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
I configure a object as an initialState for the store. Unfortunately some values are "overridden" on start-up of the store/app.

## Expected behavior:
All properties from the initial-state should remain untouched by any internal ngrx-action.

## Minimal reproduction of the problem with instructions:
I think my explanation was i bit poor sofar (sorry it's hard to explain this). I think an example will show the problem:

https://stackblitz.com/edit/angular-6wbjq4

In this example everything is fine. The initial state is produced by the initState() function in app/app.state.ts. 
<img width="1093" alt="screenshot 2018-03-12 18 02 05" src="https://user-images.githubusercontent.com/6229213/37298044-95599984-261f-11e8-9f8c-df97bae84c6c.png">

*BUT*:

Remove the key 'featureB' from this init state will "break" this behaviour. 

<img width="1145" alt="screenshot 2018-03-12 18 03 42" src="https://user-images.githubusercontent.com/6229213/37298101-bc6e51cc-261f-11e8-982d-a9eecb3f25b9.png">

It seems to be caused by the combination function: https://github.com/ngrx/platform/blob/9b02f79f1fc3b5e4d85bf0516108f93eed655126/modules/store/src/utils.ts#L29-L44

The function expects all possible state properties to be setted. If a property is not (in initialState) set the 'hasChanged' turns true and returns the nextState. This is some kind of an intermediated state (at least while the  ' @ngrx/store/update-reducers'-Action is fired).

## Version of affected browser(s),operating system(s), npm, node and ngrx:
@ngrx/store v 5.1 + 5.2

## Other information:

This is not directly linked to the problem but another finding that confused me.
After '@ngrx/store/update-reducers' is fired all reducers are applied, even if they were already applied previously:

![screenshot 2018-03-12 18 09 37](https://user-images.githubusercontent.com/6229213/37298452-9c199084-2620-11e8-91c0-cb727bbd7752.png)

**Comment by metaloha** [comment]
+1 We're seeing the repetition issue here as well on `feature` stores. The first feature will repeat 3 times, the second one repeats 4 times. Weird. In our case it's not causing any problems.

**Comment by johannesjo** [comment]
I'm experiencing the same thing with v6.1.0.
