### ISSUE TITLE
Initial state with property value "new Map()" missing from the state with aot build.

### ISSUE THREAD

**Issue by Ashwin2488** [ngrx/platform#910]
## I'm submitting a...

<pre><code>
[x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

I have a reducer with initial state set as following;
`export const initialState: State = {
  loaded: false,
  indexes: new Map()
};`

This works fine on running ng serve. The initial state of indexes is set to empty map in the store.
But, when I try to build this using ng build --prod and then run the application, the indexes property is missing from the initial state that is set in the store.
 
## Expected behavior:

The initial state of indexes should be set to empty map.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
 "@angular/common": "^5.2.7",
    "@angular/compiler": "^5.2.7",
    "@angular/core": "^5.2.7",
 "@ngrx/effects": "^5.1.0",
 "@ngrx/store": "^5.1.0",
 "typescript": "2.4.2",
 "@angular/cli": "^1.7.2",
    "@angular/compiler-cli": "^5.2.7",
node: 6.11.2
npm: 3.10.10

**Comment by tashoecraft** [comment]
@Ashwin2488 can you make a plunkr/stackblitz reproducing the issue

**Comment by Ashwin2488** [comment]
The issue was duet to the way initial state was provided. It needs to be a function as mentioned here for aot to inject dynamically.
https://github.com/ngrx/platform/blob/master/docs/store/api.md#initial-state

`export function getInitialState() {
  return { ...initialState, ...initialStateFromSomewhere };
}

@NgModule({
  imports: [
    StoreModule.forRoot(reducers, { initialState: getInitialState })
  ]
})`
