### ISSUE TITLE
respect the app prefix in schematics

### ISSUE THREAD

**Issue by Isigiel** [ngrx/platform#911]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

When generating a container, the component will be selected by 'app-component-name'.

## Expected behavior:

The selector should be 'prefix-component-name'.

## Minimal reproduction of the problem with instructions:

Set the prefix to something not _app_ and then generate a container

## Version of affected browser(s),operating system(s), npm, node and ngrx:
ngrx@5.2.0

**Comment by vitaliy-bobrov** [comment]
@Isigiel, seems that problem related to @angular-devkit/schematics package, as prefix option not passed to ngrx container schematic. But you can explicitly set the component prefix using `--prefix` (or `-p` alias) option for `ng g co ...`, example:
```
ng generate co --state=my-state --prefix=my-prefix
```

**Comment by czd** [comment]
@vitaliy-bobrov The workaround is fairly simple yes, but isn't expected behavior that the cli uses the prefix set for the application? How does the prefix get passed to the ngrx container? Is this a problem with other app specific variables?

**Comment by vitaliy-bobrov** [comment]
@czd, I've checked ng cli sources, and... they are passing prefix option only to a component or directive schematic, see https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/tasks/schematic-run.ts#L204. 

But you can specify defaults for ngrx/schematics in `.angular-cli.json` under `defaults.${schematicName}.${key}`, in case of `container` it should be `defaults.container.prefix`.

I'm going to create issue for ng CLI regarding that.

**Comment by brandonroberts** [comment]
This issue has been fixed upstream
