### ISSUE TITLE
Get old value after dispatch synchronous action

### ISSUE THREAD

**Issue by jinich** [ngrx/platform#913]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

Get old value after dispatch synchronous action

## Expected behavior:

Get only new value after dispatch action to update it

### Steps to reproduce:
**Initial state:**
```typescript
{
  items: [],
  selected: null
}
```

**Case 1:**
* `AppComponent` listen for changes from `items`
* Press Start will dispatch `LOAD_ALL` action to update `items = [1, 2, 3, 4, 5]`
* `AppComponent` was got notify and dispatch select item action to set `selected = 1`
* After dispatch this action, `AppComponent` select `selected ` state from store and subscribe to it to get it's value, i am expect to get only latest value of it (in this case is 1), but actually i got 2 value: null first and 1 second
* When debugging, i noticed that when dispatch `SELECT` action, the reducer was called after subscribe to `selected` state

**Case 2:** Same as case 1 but now i dispatch `SELECT` item action on the first time `AppComponent` got notify when subscribe to `items ` (remove `item.length > 0` check), i got only latest value is 1

Why we got different result in case 1 and case 2? Also, the behavior in case 1 is weird because `SELECT` is a synchronous  action, the reducer should be called before others
## Version of affected browser(s),operating system(s), npm, node and ngrx:
I use ngrx 5.2.0

**Comment by vitaliy-bobrov** [comment]
The problem that you're dispatching action in `select` subscription, you should use `Effect` to dispatch actions depending on state.

**Comment by venkateshparihar** [comment]
how to dispatch in effects??
