### ISSUE TITLE
Missing release notes

### ISSUE THREAD

**Issue by dhknudsen** [ngrx/platform#916]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## What is the current behavior?
When looking at the releases, there are no release notes that describe the content of the release or any possible breaking changes it introduce

## Expected behavior:
To have release notes added to all new releases that as a minimum just highlights possible deprecation/breaking changes.

**Comment by MikeRyanDev** [comment]
At the root of the repo there is a CHANGELOG.md that points to release notes for every package: https://github.com/ngrx/platform/blob/master/CHANGELOG.md
