### ISSUE TITLE
Schematics: Action type names - upper case

### ISSUE THREAD

**Issue by MichaelWarneke** [ngrx/platform#923]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

Schematics creates action type names like Load, Update, etc.

## Expected behavior:

In various previous examples and codegen code the action type names are always upper case like
LOAD_BOOKS_ACTION
UPDATE_BOOK_ACTION

## Other information:
It can be confusing when the action type names are the same as the action classes / interfaces names as created with schematics now. I know the example app has the same style. Just wondering if that's what you are going for in the future or do you want to have the action type names underscore / upper case to differ from class/interface names?
I prefer the the upper case style and created a modified fork which I can push if there is interest?
[my fork](https://github.com/MichaelWarneke/platform/tree/(schematics)-action-type-names-upper-case)

**Comment by brandonroberts** [comment]
Upper case action types made more sense when we were using constants. Now that we have switched to using enums that are already namespaced, the import lines are clearer.
