### ISSUE TITLE
[Store-DevTools] timestamp strange behaviour in ReduxDevTools Extension

### ISSUE THREAD

**Issue by MrClockOff** [ngrx/platform#924]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

1. Every state change will update timestamp on all previous events to current time in ReduxDevtools extension window. 
2. Timestamp is updating to current time also when user hover mouse over any state in state change event list in ReduxDevtools extension.  

## Expected behavior:

Every new event timestamp should start with + sign indicating how much time passed from previous state.

## Minimal reproduction of the problem with instructions:

Starting this default template is causing the described behaviour http://plnkr.co/edit/tpl:757r6L

## Version of affected browser(s),operating system(s), npm, node and ngrx:
Browsers: Chrome 65, Firefox 58
OS: OSX 10.13.2
npm: 5.6.0
node: 8.10.0
ngrx: 5.2.0

## Other information:
Please find the screenshots with highlighted issue:

![screen shot 2018-03-21 at 11 27 07](https://user-images.githubusercontent.com/22884089/37707717-00113d08-2cfc-11e8-81fb-bee41b4068b5.png)
![screen shot 2018-03-21 at 11 26 07](https://user-images.githubusercontent.com/22884089/37707722-03a92746-2cfc-11e8-9cda-f03f5f9fac0c.png)

**Comment by tdeschryver** [comment]
This is because the `timestamp` isn't set on the devtools action.

**Comment by MrClockOff** [comment]
@tdeschryver thank you for your reply. Could you please point me into the right example how should be the `timestamp` set on devtools action? 
I've followed all documents provided in this repo but for some reason I've missed this particular thing.

Thanks

**Comment by tdeschryver** [comment]
@MrClockOff This isn't your fault 😄
You can't set the timestamp yourself, it has to be set inside the store-devtools module.

**Comment by MrClockOff** [comment]
@tdeschryver Ah I see, thank you once again. I'll keep the ticket open then :)

**Comment by brandonroberts** [comment]
Fixed via df2411f40aefd7181b441f1a97e322f1c77d274f
