### ISSUE TITLE
Effects initialised without respecting APP_INITIALIZER

### ISSUE THREAD

**Issue by russelltrafford** [ngrx/platform#931]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
Using APP_INITIALIZER together with ngstore and effects does not work as expected. Effects are initialized before the promise via APP_INITIALIZER is completed. APP_INITIALIZER in this case is used to provide a at-runtime environment config via a get call to a JSON file.

Using code provided by @brandonroberts in #174 we can now semi-control when effects are run, except they are delayed by too much now, as the reducers are triggered before effects are loaded, and thus effects don't get triggered by said reducers.

More info and example code can be found in #174 which is now a Closed issue, however, problems remain, hence this ticket to more accurately address the specific issue.

## Expected behavior:
None of the components of the reactive store are initialized until APP_INITIALIZER's Promise code has successfully completed.

## Minimal reproduction of the problem with instructions:
Initial proposed fix code, which still shows the above issues can be seen at: https://github.com/ngrx/platform/issues/174#issuecomment-373853594

_Update:_ @paulwinner1995 provided the following repo with the issue reproduced:
https://github.com/paulwinner1995/effects-issue-example
Application fails on runtime, but if you comment out import of Effect module it works as expected.

**Comment by tmc101** [comment]
I spent most of today trying to work out why my services were being instantiated before my APP_INITIALIZER had a chance to load their configuration from the server.

In the end I found that the the effects where being instantiated _before_ the APP_INITIALIZER promise had resolved.

This was causing the services to be created and injected with an empty configuration.

It would be more intuitive if the everything (including effects) waited for the APP_INITIALIZERs to resolve - otherwise how do you initialize an app?

**Comment by russelltrafford** [comment]
yep, the effects no doubt use some of your regular services, which in turn triggers them to be initialized. Also note that variable declarations at the start of your classes will run too, so best to declare your variables empty, and then use a function called from your constructor (or elsewhere) to actually fill them with your data after APP_INITIALIZER completes. also be careful with `get` declarations in your class, because if anything calls those, they will also trigger, and thus mess up if your variables rely on data produced during the APP_INITIALIZER stage (i.e. run-time loaded config)

**Comment by russelltrafford** [comment]
Just put console.log or console.warn (adss stack traces) into loads of random constructors on services and components, and various functions in your store, and you'll soon see in the console if the order of things loaded is not as you were expecting.

**Comment by russelltrafford** [comment]
P.s. hate that Close and comment button!

**Comment by tmc101** [comment]
Yes - that's what I spent the day doing: adding console.log() calls to all of my constructors.

I'm amazed that is it so difficult to do something as simple as loading a config file before your application starts.

**Comment by russelltrafford** [comment]
I'm taking a little break from this issue and implementing the run-time config in one of our other apps that does not use the store (This should be easier....??). My colleague however is continuing to work on this and I'll join him once our other app has been converted without using the store. Lets see if we can figure this out.

Hopefully some others join the quest here...

**Comment by tmc101** [comment]
To summarize:

1. Angular provides the APP_INITIALIZER token to allow asynchronous tasks to be completed before the application starts.

2. There are numerous blogs and stackoverflow answers recommending that APP_INITIALIZER can be used to asynchronously load configuration data and add it to an injected ConfigService.
e.g. https://hackernoon.com/hook-into-angular-initialization-process-add41a6b7e

3. EffectModule.forRoot() causes the effects to be injected before the APP_INITIALIZER providers have run/resolved. Resulting in application services that are injected into effects classes being injected with an un-initialized ConfigService.

4. If the constructors of the services try to use values from the ConfigService the app will error.

5. Even if the Effects used the APP_INITIALIZER , we still can't guarantee that the asynchronous config would be read in time.

The only way I can see of being able to guarantee that an Angular app could be configured asynchronously would be for Angular to offer another unambiguous token e.g. APP_CONFIG, which would operate the same as APP_INITIALIZER, but block APP_INITIALIZER until all of the APP_CONFIG promises had resolved. But I'd be very happy if someone with more knowledge of Angular could tell me that I'm wrong.

In the meantime the only pragmatic approach I can think of is to not access, or cause to be accessed, the ConfigService in the constructors of your services. That would allow your APP_INITIALIZER a chance to populate the config information in your ConfigService before your app boostrapped.

So far this has only been a problem for me when using Effects - so having EffectsModule.runAfterBootstrap() back would be handy too.
 
Also: Thanks for ngrx - it is excellent.

**Comment by paulwinner1995** [comment]
+1 
Faced with same issue that @chrismellard has described. I have Configuration service that fetch base url to server during bootstrapping. So other services depend on this configuration. When I use such services with effects my application crashes, because url was not loaded before effect initialized.

**Comment by brandonroberts** [comment]
Will someone add a concrete reproduction of this issue? If using neither token works correctly, this would help us get the issue resolved or provide a workaround.

**Comment by paulwinner1995** [comment]
Hi @brandonroberts , 
I have made repository with reproduction of this issue https://github.com/paulwinner1995/effects-issue-example
Application fails on runtime, but if you comment out import of Effect module it works as expected.

**Comment by tdeschryver** [comment]
I think the problem might be that you're accessing the config in the ctor.
If you write your code like below, it does work.
```
getPosts(): Observable<Post[]> {
    return this.httpClient.get<Post[]>(
      `${this.configurationService.get("apiBaseUrl")}/posts`
    );
  }
```

**Comment by chrismellard** [comment]
@brandonroberts This fixed the issue for me. I think my previous endeavours at using this proposed method must have been flawed in some way.

**Comment by paulwinner1995** [comment]
Thanks a lot @brandonroberts , it helps me.

**Comment by russelltrafford** [comment]
Ah, maybe we shall have a go at that.

Our current solution if of interest to all, was to use a Subject Observable in addition to the APP_INITIALIZER.

And thus the app would do its bootloader init stuff as expected using APP_INITIALIZER, and for the ngStore code, when the config service was inevitable loaded before the environment stuff was ready, it would hit the config service constructor, which then uses the Obserable, and sits there waiting, and be forced to wait until the Observeable is given the OK by the env config service successfully getting the data back, originally triggered by APP INIT.

**Comment by russelltrafford** [comment]
Btw, @brandonroberts, provideBootstrapEffects() in the ngModule, if you do a production build / use AOT compiler with angular-cli, it complains that you should not have functions in the providers section of ngModule.

**Comment by paulwinner1995** [comment]
Hi @russelltrafford, Looks like in my case AOT compiler does't complain to function invocation on provider section. But I run production build with `ng build -prod -sm` command

**Comment by jaichandra** [comment]
Ran into the same issue today. The above solution by @brandonroberts did work. My Effects are in a feature module. So, had to pass an empty array to `EffectsModule.forFeature` and use `provideBootstrapEffects` instead:
```
@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    StoreModule.forFeature('foo', FooReducer),
    EffectsModule.forFeature([])
  ],
  providers: [provideBootstrapEffects([FooEffects])]
})
```

**Comment by jaichandra** [comment]
Ok. It works on the first feature module, but not in others. I guess thats because providers are added to the same root injector and the last module with `provideBootstrapEffects` is overriding all others.

**Comment by brandonroberts** [comment]
@jaichandra it could be tweaked some to add `multi: true` to the BOOTSTRAP_EFFECTS token, but then you have to flatten out the arrays of effects before registering them

**Comment by brandonroberts** [comment]
Closing as resolved with an example workaround

**Comment by rijine** [comment]
@brandonroberts tried to run https://github.com/brandonroberts/effects-issue-example 
Angular CLI: 6.1.5.
Effects are not getting invoked!

**Comment by ryanwong113** [comment]
I don't think the workaround works. My effects are not getting called..

**Comment by nheinbaugh** [comment]
We had to add a `ready` property to our config service that we are injecting. It feels gross and I look forward to ngrx honoring the app initializer.

Is there any ETA on this? Or any appetite to fix it (since there is a workaround)?

**Comment by nukec** [comment]
so this still not resolved? great.

**Comment by russelltrafford** [comment]
Wow this feels like years later and still not addressed? I've moved into a
new project with backbone.js now lol

**Comment by dellekappa** [comment]
@russelltrafford can you provide some details of your solution with Subject + APP_INITIALIZER?
Anyone found some alternative way to have an "all case working" solution?
A tried also to move all the effects and their dependecies in a module loaded lazily on the promise callback.
It works but anyway it forces the developer to keep in mind this issue and makes the app harder to configure.
Maybe there is a way to load some server side stuff before angular itself and then let angular load it synchronously?

**Comment by russelltrafford** [comment]
Sorry it was a long time ago and Im no longer at that company and project,
so don't have access to the code anymore. I gave a rough explanation at the
time, if there's specifics that I wrote that you have confusion about I'll
try and help if I remember.

**Comment by michael-lang** [comment]
Our workaround is to delay load of the application until the configuration is loaded within main.ts. We do this to toggle Rest API urls and OAuth client id settings between different deployed environments.

replace this:
`platformBrowserDynamic().bootstrapModule(AppModule)`

with this:
```
AppConfigService.loadConfig().then(() => {
  return platformBrowserDynamic().bootstrapModule(AppModule);
})
```

This means the code loading the configuration cannot rely on Angular's HttpClient.

```
import { Injectable } from '@angular/core';
import { AppConfig } from './app-config.models';

@Injectable({ providedIn: 'root' })
export class AppConfigService<T extends AppConfig = AppConfig> {
  static appConfig: AppConfig;

  constructor() { }

  static loadConfig(): Promise<void> {
    return new Promise((resolve, reject) => {
      const oReq = new XMLHttpRequest();
      oReq.addEventListener('load', (resp) => {
        if (oReq.status === 200) {
          try {
            AppConfigService.appConfig = JSON.parse(oReq.responseText);
          } catch (e) {
            reject(e);
          }
          resolve();
        } else {
          reject(oReq.statusText);
        }
      });
      oReq.open('GET', 'clientsettings.json');
      oReq.send();
    });
  }

  getConfig(): T {
    return AppConfigService.appConfig as T;
  }
}
```

A sample config:

```
export interface AppConfig {
  production: boolean;
}

export interface XyzAppConfig extends AppConfig {
  abcApi: string;
  abcClientId: string;
  restApiBase: string;
  foo: Bar;
}
```

You can still inject this config service into your other services that make HttpClient calls and use the config settings to set the correct url paths for the HttpClient requests.

```
  constructor(private http: HttpClient,
     private config: AppConfigService<XyzAppConfig>) { 
 }
```

**Comment by nukec** [comment]
There is no need of usage of APP_INITIALIZER here. Just use redux to load config.json in app.component.ts.  You dispatch action on init, and then effect should take care of loading config.json with httpclient, and dispatch another action which then stores config into state.

`this.store.dispatch(new LoadConfig());`

```
  @Effect()
  private loadConfig$: any = this.actions$.pipe(
    ofType(AppActionTypes.LoadConfig),
    mergeMap(() =>
      this.httpClient.get('assets/appsettings.json').pipe(
        map((response: AppConfig) => ({
          type: AppActionTypes.LoadConfigSuccess,
          payload: response
        })),
        catchError(() => of({ type: AppActionTypes.LoadConfigError }))
      )
    )
  );
```

that's it. you take care about payload assignation in reducer.

**Comment by michael-lang** [comment]
@nukec If you have multiple Effects that all depend on service configuration, this can get really tedious to copy this code around. It really is better to have the configuration loaded earlier.

**Comment by fwoelffel** [comment]
Thanks to @brandonroberts for his workaround. However, when `provideBootstrapEffects` was called multiple times, effects ended up shadowed and not all of them where injected.

Here is what we came up with:
```ts
import {APP_BOOTSTRAP_LISTENER, Type} from '@angular/core';
import {EffectSources} from '@ngrx/effects';

/**
 * See https://github.com/ngrx/platform/issues/931
 * This utility class is based on the workaround suggested by Brandon Roberts here https://github.com/brandonroberts/effects-issue-example
 * We had to refactor it and use dynamically generated injection tokens for the effects injection to avoid their shadowing when
 * EffectsBootstrapProvider.provide is called multiple times.
 */
export class EffectsBootstrapProvider {

  static provide (effects: Type<any>[]) {
    const EFFECTS_BOOTSTRAP = `__effects_bootstrap_${Math.random().toString(36)}`;
    return [
      effects,
      { provide: EFFECTS_BOOTSTRAP, deps: effects, useFactory: (...instances: any[]) => instances },
      {
        provide: APP_BOOTSTRAP_LISTENER,
        multi: true,
        useFactory: (_effects: Type<any>[], sources: EffectSources) => () => {
          _effects.forEach(effect => sources.addEffects(effect));
        },
        deps: [ EFFECTS_BOOTSTRAP, EffectSources ]
      }
    ];
  }

}
```

**Comment by darnautov** [comment]
> I've also created a fork of your example that uses the `bootstrapEffects` method mentioned in an earlier post that works without errors.
> 
> https://github.com/brandonroberts/effects-issue-example

I’ve faced an issue with this workaround. 
Based on docs all callbacks provided via APP_BOOTSTRAP_LISTENER will be called for every component that is bootstrapped. Hence root effects are registered after AppComponent initialized, so when I dispatch an action inside ngOnInit there is no effect yet.
Is there any way to register root effects after APP_INITIALIZER has been resolved and before AppComponent bootstrapped? 🤔

**Comment by darnautov** [comment]
I implemented ngrxOnInitEffects for effects, listen for init action and map to the action I was originally dispatching inside of ngOnInit of my AppComponent, but not sure it's a good idea.

**Comment by nukec** [comment]
I ended up loading config with root effects before feature effects are loaded.

**Comment by jasedwards** [comment]
The provideBootsrapEffects works fine for root effect but when used in a feature module the ngrxOnInitEffects is never called for that effect.    Is there any plan to have an actual solution built in for this?

**Comment by montella1507** [comment]
@brandonroberts  why is it closed? I think, ngrx is breaking "angular rules" :-(

**Comment by TheILPlace** [comment]
ngrx-data also breaks the rules, and runs before aPP_INITIALIZER finishes !
please re-open

**Comment by momoadeli** [comment]
Not sure why this issue was closed as it hasn't been resolved (even in #174 (comment). We are of course experiencing the same issue. However, I do have a couple of short questions (and I'm cognizant this is a regression)
1. Since the store ngrx store effects play a part in this, why not populate a store slice with configs and have services subscribe to them instead of injecting a service?
2. Speaking of services, the work-around @michael-lang provided seems like a good interim fix. I don't see any follow-up comments though. 

Thoughts?

**Comment by shprink** [comment]
@brandonroberts workaround worked for me => https://github.com/brandonroberts/effects-issue-example/blob/master/src/app/app.module.ts

It also works with AOT.

Thanks a lot

**Comment by Mysq** [comment]
This is *still* an problem in `8.6.0` version. Please reopen this issue.

**Comment by aravindfz** [comment]
@brandonroberts - can you please help us by fixing this?

**Comment by skined90** [comment]
Is there any fix for this?

**Comment by ihadabs** [comment]
> Angular CLI: 10.0.5
> Angular: 10.0.8

Any updates on this issue?

**Comment by fueg** [comment]
Thanks @michael-lang for the workaround! Worked nicely in my app.

**Comment by labeled** [comment]
Thank you @michael-lang for the suggestion. We are trying it out in our app now with a slight modification, we made it async and also had it provide the production flag as to help us support not determining environments during build times.
```
AppConfigService.loadConfig().then(async () => {
  if (AppConfigService.isProduction) {
    enableProdMode();
  }
  try {
    return platformBrowserDynamic().bootstrapModule(AppModule);
  } catch (err) {
    return console.error(err);
  }
});
```

**Comment by demirtasg** [comment]
> I've also created a fork of your example that uses the `bootstrapEffects` method mentioned in an earlier post that works without errors.
> 
> https://github.com/brandonroberts/effects-issue-example

this solved the problem for me. thanks

**Comment by joanferns00** [comment]
@brandonroberts  This worked for me! Thanks!

**Comment by naticaceres** [comment]
:( none of the workarounds work for me other than **michael-lang** 's 
but even his is cumbersome for my situation, as the project I am working on has 5 different apps, and the request of the appconfig needs to be repeated for each of their `main.ts` files, and remembered for any new app that requires the same mechanics.

**Brandon**'s looks nice, but it simply isn't clean enough for a large scale solution (my project has plenty of slices of the store, each living into their own libraries. it isn't maintainable to add to each of the libs with effects triggered during init a dependency to the `provideBootstrapEffects `and make devs remember it all the time for new effects)

isn't this a bug noisy enough for NGRX to reopen this issue?
from the looks of it, it definitely sounds like a tricky unexpected behavior.
when leveraging APP_INITIALIZER, [angular documentation states](
https://angular.io/api/core/APP_INITIALIZER#:~:text=you%20can%2C%20for%20example%2C%20create%20a%20factory%20function%20that%20loads%20language%20data%20or%20an%20external%20configuration%2C%20and%20provide%20that%20function%20to%20the%20app_initializer%20token.%20the%20function%20is%20executed%20during%20the%20application%20bootstrap%20process%2C%20and%20the%20needed%20data%20is%20available%20on%20startup.) _whatever promise or observable you pass into its provider function, will be executed during app bootstrap and the data will be available on startup_.

This is breaking Angular's own expected behavior, as it triggers literally everything else that effects need for DI, plus effect constructors before whatever we pass to the APP_INITIALIZER provider gets a chance to resolve.

I really appreciate all the effort from NGRX contributors and all the workarounds posted before me, but I whish this issue was reopened to at least allow for PRs to be created, or more discussion to be held looking for real solutions instead of hacks and workarounds (or at the very least some light to be shed explaining why this can't be solved in a better way).

**Comment by brandonroberts** [comment]
@naticaceres I would suggest opening a new GitHub discussion to document solutions for those who want to bootstrap effects with the App Initializer. We could also add a recipe page to the docs for it later.

**Comment by labeled** [comment]
@naticaceres I agree with you. We have 15 apps and each one has to do the same thing. We created custom app generators so that every app is generated with the correct setup. I did a lot of research on this issue and got the "working as intended" answer many times.

**Comment by zoechi** [comment]
Same here. I was surprised NgRx is initialized using `APP_INITIALIZER` and therefore it's not possible to load a config file before NgRx calls `ngrxOnInitEffects`.
https://offering.solutions/blog/articles/2021/11/11/loading-configuration-before-your-angular-app-starts/#using-the-fetch-api is probably the better approach then

**Comment by akiik** [comment]
Still a real issue, I used a workaround provided by @michael-lang, updated to the latest apis:
main.ts
```
EnvironmentConfigService.loadEnvironmentConfig().then(() =>
  platformBrowserDynamic().bootstrapModule(AppModule)
).catch(err => console.error(err));
```
environment-config.service.ts
```
@Injectable()
export class EnvironmentConfigService {

  static environmentConfig: EnvironmentConfig;

  static async loadEnvironmentConfig(): Promise<void> {
    EnvironmentConfigService.environmentConfig = await fetch(`/api/environment`)
      .then(response => {
        if (!response.ok) {
          throw new Error('Loading environment configuration failed');
        }
        return response.json();
      });
  }

  getEnvironmentConfig(): EnvironmentConfig {
    return EnvironmentConfigService.environmentConfig;
  }

```

**Comment by adisonch** [comment]
> Ok. It works on the first feature module, but not in others. I guess thats because providers are added to the same root injector and the last module with `provideBootstrapEffects` is overriding all others.

**Comment by carlokid** [comment]
> @jaichandra it could be tweaked some to add `multi: true` to the `BOOTSTRAP_EFFECTS` token, but then you have to flatten out the arrays of effects before registering them

@brandonroberts this doesn't seem to work. Could you have another look?

**Comment by carlokid** [comment]
> Ok. It works on the first feature module, but not in others. I guess thats because providers are added to the same root injector and the last module with `provideBootstrapEffects` is overriding all others.

@jaichandra have you figured this out somehow?

**Comment by yurakhomitsky** [comment]
This can be solved by moving effects to routing providers which were introduced along with standalone components

**Comment by divnych** [comment]
I used a workaround by defining a top-level componentless route that wraps around other app routes and registers effects, as follows:

```typescript
// app.routes.ts
export const routes: Routes = [
  {
    path: '',
    providers: [provideEffects(fooEffects, barEffects)],
    children: [
      // ... existing app routes
    ]
  }
];
```

**Comment by wall-street-dev** [comment]
We’ve been using the provided workaround for running NgRx effects after `APP_INITIALIZER `for a while.
It worked well when we only needed a single set of effects for things like authentication.
Recently, though, we had a new requirement:
We needed multiple effects—for authentication, feature access, and potentially more—to be registered and run after initialization.
With the original code, providing multiple effect modules didn’t work as expected: only the last effect set would win and actually execute!  

The fix was simple, switch the effect provider to use `multi: true`, so all of our post-initializer effects are respected.  

Here's the code in case someone has a similar requirement:

```

// Workaround for: https://github.com/ngrx/platform/issues/931

import { APP_BOOTSTRAP_LISTENER, Inject, InjectionToken, Type } from '@angular/core';
import { EffectSources } from '@ngrx/effects';

const BOOTSTRAP_EFFECTS = new InjectionToken<unknown>('Bootstrap Effects');

function bootstrapEffects<T>(effects: Type<T>[][], sources$: EffectSources) {
    return () => {
        effects.flat().forEach(effect => sources$.addEffects(effect));
    };
}

function createInstances<T>(...instances: T[]) {
    return instances;
}

export function provideBootstrapEffects<T>(effects: Type<T>[]) {
    return [
        effects,
        {
            provide: BOOTSTRAP_EFFECTS,
            multi: true,     // 🚩 important!
            deps: effects,
            useFactory: createInstances
        },
        {
            provide: APP_BOOTSTRAP_LISTENER,
            multi: true,
            useFactory: bootstrapEffects,
            deps: [[new Inject(BOOTSTRAP_EFFECTS)], EffectSources]
        }
    ];
}
```

Usage remains unchanged!
Now you can have many of these:
```
export function provideAppAccessState(): EnvironmentProviders {
    return makeEnvironmentProviders([provideState(APP_ACCESS_FEATURE_KEY, APP_ACCESS_REDUCER), provideBootstrapEffects([AppAccessEffects])]);
}
```

**Comment by talamaska** [comment]
How this approach would be made for functional effects and a standalone app?
