### ISSUE TITLE
ngrx/entity catch error on adapter collection methods

### ISSUE THREAD

**Issue by makbari** [ngrx/platform#934]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ X] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

I want to know if it is make sense to return catch error on entity adapter methods. 
I do not know if this is a feature request or it is already implemented. 

## Expected behavior:

For example, updateOne method, if there is no record match to the record, it returns error. 
(there is a possibility to use carchError on ngrx/effects, however i was wondering that if it is make sense to implement similar behavior for ngrx/entity)

**Comment by brandonroberts** [comment]
Reducers should not throw errors, so you should handle invalid data before it reaches the reducer.
