### ISSUE TITLE
Can the example-app be separated out from the platform as a standalone app? This is not an issue, just a suggestion to make it easier to understand how to build app using NgRx.

### ISSUE THREAD

**Issue by richcheng** [ngrx/platform#936]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

**Comment by brandonroberts** [comment]
The example app also serves as an integration check against what's in master. You can generate a clean CLI project, copy the contents of the`example-app` folder into the `src` folder, install the ngrx dependencies and run the app there. Here is a repo for reference: https://github.com/brandonroberts/ngrx-shiny-memory
