### ISSUE TITLE
[Store-DevTools] actionsBlacklist / actionsWhitelist

### ISSUE THREAD

**Issue by Wykks** [ngrx/platform#938]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
There is no way to filter out actions in Store-DevTools.

## Expected behavior:
Implement `actionsBlacklist` / `actionsWhitelist`
https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#actionsblacklist--actionswhitelist

I can try to implement this one, if you're ok with this.

**Comment by TobyBackstrom** [comment]
Yes, I'd like to see this, too. I've got some actions that come with a very high frequency and I need to filter them somehow to be able to use the devtools. I would guess this is a pretty common scenario in any app that displays "realtime data".

**Comment by nasreddineskandrani** [comment]
the `predicate` just below `actionsBlacklist` / `actionsWhitelist` is more useful as feature in my opinion (that can do the blacklisting or whitelisting).

@Wykks what do you think?

**Comment by Wykks** [comment]
Yup, you're right. I added `predicate` too
