### ISSUE TITLE
ReducerManagerDispatcher doesn't get actions when using the StoreDevtoolsModule

### ISSUE THREAD

**Issue by KevinVillela** [ngrx/platform#942]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
Using the StoreDevtoolsModule or any module that hooks into the extension functionality causes any ReducerManagerDispatcher to not receive any actions. A possibly related behavior is that you can only use 1 extension at a time.

## Expected behavior:
The ReducerManagerDispatcher receives actions.

## Minimal reproduction of the problem with instructions:
Create an app with a ReducerManagerDispatcher listening for actions, and then install the devtools module:

app_component.ts:
constructor(dispatcher: ReducerManagerDispatcher) {
  disptacher.subscribe(() => console.log('action!');
}

in module:
import {StoreDevtoolsModule} from '@ngrx/store-devtools';

StoreDevtoolsModule.instrument(),

## Version of affected browser(s),operating system(s), npm, node and ngrx:
Current version as of today

**Comment by brandonroberts** [comment]
If you're listening for actions, you inject `ActionsSubject` from `@ngrx/store`

**Comment by KevinVillela** [comment]
Thank you!
