### ISSUE TITLE
MetaReducer has inflexible type signature, doesn't support popular libraries such as undoredo-redux

### ISSUE THREAD

**Issue by alexjlockwood** [ngrx/platform#950]
The [undoredo-redux](https://github.com/omnidan/redux-undo) library exports a meta reducer with the following signature ([link](https://github.com/omnidan/redux-undo/blob/c2424454646de778b9e6b2cd3482ec1942b9a703/typings.d.ts#L78-L80)):

```ts
interface Undoable {
  <T>(reducer: Reducer<T>, options?: UndoableOptions): Reducer<StateWithHistory<T>>;
}
```

Note that the meta reducer takes a `Reducer<T>` as an argument and returns a `Reducer<StateWithHistory<T>>`.

With `@ngrx/store`, it is not possible to use a meta reducer like this. This is because `@ngrx/store` declares the `MetaReducer` type as follows ([link](https://github.com/ngrx/platform/blob/57633d2a8fc3de6f3f7e6ec38d8c9f83d0c86f73/modules/store/src/models.ts#L24-L26)):

```ts
type MetaReducer<T, V extends Action = Action> = (
  reducer: ActionReducer<T, V>
) => ActionReducer<T, V>;
```

Would it be possible to change this declaration so that we could use libraries like `undoredo-redux` with `@ngrx/store`? For example, something like this:

```ts
type MetaReducer<T, U, V extends Action = Action> = (
  reducer: ActionReducer<T, V>,
) => ActionReducer<U, V>;
```

If we want to avoid breaking existing code at all costs, I think we could move `U` to be the third generic argument and set its default value to `U = T`.

**Comment by timdeschryver** [comment]
Closing this issue, library owners can now use the `META_REDUCERS` token to provide a reducers. See https://github.com/ngrx/platform/pull/1970 for more info.
