### ISSUE TITLE
Document purpose of nextSearch$ + takeUntil

### ISSUE THREAD

**Issue by ravishivt** [ngrx/platform#959]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## What is the current behavior?

The example-app uses `nextSearch$` and `takeUntil` in [book.ts](https://github.com/ngrx/platform/blob/cb473c00475289509f0924321bb293d0ad1137ca/example-app/app/books/effects/book.ts#L52).  The logic is nonintuitive and there are a couple StackOverflow posts asking specifically what it does [1](https://stackoverflow.com/questions/42596635/why-takeuntil-is-necessary-in-this-ngrx-example) [2](https://stackoverflow.com/questions/41657400/why-use-takeuntil-over-take1-with-http-service).  Maybe I don't understand the answers given but they are contradictory and appear to be more or less guesses.  I still don't know the intended purpose is.  Doesn't `switchMap` eliminate the need for `takeUntil`?

## Expected behavior:

Given that the example-app is a reference for developers, a comment explaining what this piece of code does would help developers decide on whether they need to replicate it for their own effects.

**Comment by MattiJarvinen-BA** [comment]
SwitchMap switches and maps result to another observable thus eliminating the need for takeUntil. 

This is the correct explanation:

> To understand why takeUntil is used, it might help to make no assumptions about the implementation of searchBooks.
>
> The searchBooks service method returns an observable of Book[]. That observable does not necessarily have to complete; for instance, it could emit additional results if the database changes (this is what happens with Firebase's AngularFire2 observables). However, if take(1) is used, subsequent results will be ignored. If takeUntil is used, subsequent results will continue to effect actions until the next search is initiated.
>
> However, I don't think the takeUntil is essential, as the switchMap will take care of things (the inner observable will be unsubscribed, etc.).
>
> The author(s) of the example-app appear to have implemented the search effect in such a way that it is not dependent upon the implementation of the service.
> 
> With the simple, Http-based implementation of searchBooks, I cannot see why either take(1) or takeUntil would be required - as the observable will complete and the switchMap will ensure that SearchCompleteAction actions for stale searches are not emitted.
> - https://stackoverflow.com/a/41666748/1740331
