### ISSUE TITLE
would really appreciate some guidance migrating from Store 2.2.3

### ISSUE THREAD

**Issue by erikyuzwa** [ngrx/platform#961]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## What is the current behavior?
Migrating our use of Store from 2.2.x and need some guidance.

## Expected behavior:
Wanting to get latest Store humming along to finish our Angular5 upgrade.

## Minimal reproduction of the problem with instructions:
`store.replaceReducer(reducerfunc)` is non-existent in latest Store, and I didn't spot any recommendations in the changelog or comments (or anything) on migrating. Humble apologies if they are there somewhere and I just didn't notice.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
`store 2.2.3` / `store 5.2.0`

## Other information:

I'm just really learning about how reducers and store are working in general, so I am really N00b here. I was just hoping for a snippet of guidance on what I need to think about when migrating away from `replaceReducer()`. Thanks very much.

**Comment by tdeschryver** [comment]
You can go take a look at #165 for a similar question.

**Comment by erikyuzwa** [comment]
most excellent @tdeschryver - that does seem to be along the lines of what I'm missing. 🙇
