### ISSUE TITLE
Unknown property payload - plot twist

### ISSUE THREAD

**Issue by TeoTN** [ngrx/platform#962]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
My IDE (WebStorm) complains about unknown property `payload` in my project built on top of angular/cli but not when I copy-paste code to the `example-app` from this repository.

## Expected behavior:
Easily specify Action type so that it works. Not configuration-specific. Keep It Simple, Stupid.

## Minimal reproduction of the problem with instructions:
I've been trying following approach to implementing redux architecture (I'm writing off the top of my head, can't paste the actual code here):

**actions.ts**:
```
import { Action } from '@ngrx/store';

// Issue is present also when using enum
export const ACTION_1 = 'META::ACTION1'; 
export const ACTION_2 = 'META::ACTION2';

export class Action1 extends Action {
  readonly type = ACTION_1;
  constructor(payload: Model) {}
}

export class Action2 extends Action {
  readonly type = ACTION_2;
}

export class ActionsUnion = 
  Action1
  | Action2;
```

**reducers.ts**:
```
export const reducer = (state: MyState = initialState, action: ActionsUnion): MyState => {
  switch (action.type) {
    case ACTION_1: {
      return {
        ...state,
        key: action.payload, // IDE complains here <===========
      };
    }
    default:
      return state;
}
```

The most surprising part is that the code is 100% fine when copy-pasted into `example-app` from this repository. It seems like there was some configuration in the ngrx like `ignore-payload-in-action` set to true. My project is based on @angular/cli so there is nothing special included, lol.

Do you have any idea what could this be? Why actually `payload` was removed? Redux library (as configured in `react-scripts-ts`) has `AnyAction` type that allows `payload`, maybe that's valid solution?
Could anyone please provide me with **idiomatic** version of the code above?

## Version of affected browser(s),operating system(s), npm, node and ngrx:
node 8.x, ngrx@5.2.0

**Comment by TeoTN** [comment]
This might have been the ide...

**Comment by bossqone** [comment]
It think there is problem with constructor signature:
```
export class Action1 extends Action {
  readonly type = ACTION_1;
  constructor(payload: Model) {}
}
```
You should define it like: `constructor(public payload: Model) {}`. `public` keyword is important here, otherwise TypeScript won't be able to detect `payload` as class property. Plain `payload` without `public` is just a parameter of the constructor.
