### ISSUE TITLE
Improve StoreDevtoolsModule register API.

### ISSUE THREAD

**Issue by sandangel** [ngrx/platform#964]
## I'm submitting a...

<pre><code>
[x] Feature request
</code></pre>

## What is the current behavior?

Currently StoreDevtoolsModule is registered using this syntax:

```typescript
@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    AppRoutingModule,
    StoreModule.forRoot(reducers, { metaReducers }),
    EffectsModule.forRoot(effects),
    StoreRouterConnectingModule,
	// Is registered like this:
    !environment.production
      ? StoreDevtoolsModule.instrument({
          maxAge: 25
        })
      : []
  ],
  bootstrap: [AppComponent]
})
export class AppModule {}
```

## Expected behavior:

Is that we should provide a more intuitive API like ServiceWorkerModule?

```typescript
ServiceWorkerModule.register('/ngsw-worker.js', { enabled: environment.production })
```

We could provide a 'enabled' prop in StoreDevtoolsOptions and user could register this module in a more clean way like ServiceWorkerModule. This won't be a breaking change since user can still register it using old syntax.

## Suggest change:

We could change the instrument method to something like this:

```typescript
static instrument(options: StoreDevtoolsOptions = {enabled: true}): ModuleWithProviders {
    return {
      ngModule: StoreDevtoolsModule,
      providers: options.enabled === undefined || options.enabled ? [DevtoolsExtension, /* ... */] : []
    }
```

Then user could register StoreDevtoolsModule like:
```typescript
imports: [
	/* ... */
	StoreDevtoolsModule.instrument({
        maxAge: 25,
		enabled: !environment.production
    })
]
```

**Comment by dummdidumm** [comment]
While more ergonomic, I think this would prevent bundle size optimizers from removing the store devtools dependency from your production build.

**Comment by sandangel** [comment]
hi @dummdidumm, thanks for your comment. I think you are right. ServiceWorker is included in production build so that we can use that syntax. I'm going to close this issue now.
