### ISSUE TITLE
Feature Request: check if feature store is initialized or not

### ISSUE THREAD

**Issue by PoiScript** [ngrx/platform#969]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
If we try to select state from a lazy loading module which is not loaded yet, it will throw an error like:
```
TypeError: Cannot read property 'results' of undefined.
``` 

## Expected behavior:
ngrx can provide a method or something else to let us know this feature store is initialized and can be selected safely.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
```
@ngrx/store: 5.2.0
```

**Comment by dummdidumm** [comment]
If you have a feature store and rely on it in the same feature module, you should not have any problems. If you depend on that feature store from another feature module, then it would be better to move that state into shared/root store.

**Comment by nasreddineskandrani** [comment]
you lazy-loaded because you want to lightweight your `main.bundle.js` for fast initial boot and memory gain. `you will say ok! so what? :)`
If you do need a lazy-loaded state make it load before you try to add any action that requires it (it's not ngrx lib responsability), it's your app that should handle that.

Can you build an online example on stackblitz? if you want to show us the case. It ll be more easy to help since i don't visualize how you endup in this situation.

**Comment by PoiScript** [comment]
Well, I think my use case is quite easy to understand: I have two lazy-loading module, one for searching and one for displaying search result. If user navigate from search page to result page, no api request is made because the data is prefetched. If use visit the result page **directly**, make an api call.

The point is how to check if the search module is loaded, not how to make the search module loads before I select anything from it.


I solved it in a little tricky way:
```ts
export const selectResultById = (id: string) => ({ search }: State) =>
  search
    ? createSelector(
        resultStateAdapter.getSelectors().selectEntities,
        searchEntities => searchEntities[id],
      )(search.results)
    : null;
```

**Comment by nasreddineskandrani** [comment]
option1: you can create one module `search` put the 2 pages and your logic to do the search in it then you don't have to write the code for selector you describe in your previous comment.

option2: if you are open to change your design a little but you want to absolutely keep lazyloading so:
move the search logic to the second module 'result page' when a user do a search it ll be handle by the result page on load all the time. So your select with get `undefined` the first time. You can display a loading until you get your data.

hope this help!
Their is more cool solutions but that was my quick 2 cents.

**Comment by PoiScript** [comment]
@nasreddineskandrani Oh! Thanks for your detailed reply. But your solutions seem to make the problem more complicated... :( The two modules is independent and I just want to get some pisces of data between them safely. I don't want to break the whole structure in order to achieve this. I'm sorry but I still stick on my previous soluction.

**Comment by brandonroberts** [comment]
@PoiScript I don't see why you couldn't do this with a selector if you're set on keep the two areas isolated from each other. Create a feature selector in your result module that checks the presence of the search state.

```
export const selectSearchState  = createFeatureSelector('search');
export const isSearchLoaded = createSelector(selectSearchState, search => !!search);
```

Hope this helps. If you need further support, use the [gitter channel](https://gitter.im/ngrx/platform)
