### ISSUE TITLE
[Feature Request] Implement aggregate operator for aggregator pattern

### ISSUE THREAD

**Issue by evgeniyefimov** [ngrx/platform#974]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

Aggregator pattern requires a lot of boilerplate code.

## Expected behavior:

Add aggregate operator to reduce boilerplate code.
https://blog.nrwl.io/ngrx-patterns-and-techniques-f46126e2b1e5

**Comment by brandonroberts** [comment]
This is not a pattern we are going to include in the core APIs

**Comment by nhhockeyplayer** [comment]
so how do we make a contiguous set of actions synchronous ?

this is not synchronous

 switchMap((state: EStates) => [
     new myActions.Find(),
     new yourActions.Find(),
     new statesActions.ChangeSuccess(state)
 ]),

I find is strange the lead tech on this would do a series of presentation and article and the core omit the whole idea totally

is there a solution to this ?

**Comment by Brian611** [comment]
i dont understand why we dont have this feature as well.

**Comment by AdditionAddict** [comment]
> i dont understand why we dont have this feature as well.

I don’t understand the need for aggregator....just add as many actions into the `on` method in the reducer (or switch case fall though in earlier ngrx) as you need and similarly in the `ofType` method for effects. Example above isn’t using actions as intended... _unique events that are dispatched from components and services_, but as commands. 

See this talk on good action hygiene —> https://www.youtube.com/watch?v=22K-cftN-e0

Ask in the gutter channel if unsure.

**Comment by Brian611** [comment]
@AdditionAddict you seem to not understand the purpose of the aggregate pattern, it wouldn't have been created if it didn't solve a particular issue. 

Go through this presentation where Victor Savkin ex google developer who explains the usage.

https://youtu.be/FQ6fzkHvCEY?list=WL
