### ISSUE TITLE
NgRx router integration dispatches the navigation event before the preactivation phase (Guards and Resolvers) executes.

### ISSUE THREAD

**Issue by russoturisto** [ngrx/platform#975]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

Following the advice of vsavkin from nrwl/nx to open an issue here (couldn't find an open issue and I know the problem is still there in 5.2.0):

https://github.com/nrwl/nx/issues/258

## What is the current behavior?

"DataPersistence.navigation relies on the NgRx router integration. The integration dispatches the navigation event before the preactivation phase (Guards and Resolvers) executes."

## Expected behavior:

"NgRx router integration dispatches the navigation event AFTER the preactivation phase (Guards and Resolvers) executes.

## Minimal reproduction of the problem with instructions:

please see:
https://github.com/nrwl/nx/issues/258

## Version of affected browser(s),operating system(s), npm, node and ngrx:

5.2.0

## Other information:

We are stuck on 5.2.X due to customer commitments, is it possible to fix this in 5.2.X?

Thanks, :)

**Comment by bbaia** [comment]
Relates to #816

**Comment by dummdidumm** [comment]
Maybe we should think about enhancing the features of the router module in general.

One of the things that comes to my mind is to rework the actions that are dispatched and at what time they are dispatched:

- Navigation Request -> during first navigation lifecycle event.
- Navigation Done -> after last navigation lifecycle event but not if its an error or cancel.
- Navigation Error -> on error
- Navigation Cancel -> on cancel

**Comment by redjab** [comment]
Any response/update on this issue? I'm running into this recently, though with a slightly different scenario.
Imo, different actions should be dispatched depending on the router event, and only on NavigationEnd, NavigationError, and NavigationCancel should the params & queryParams in the router store gets updated, because only then you know for sure that these are going to be correct.

**Comment by brandonroberts** [comment]
Fixed via https://github.com/ngrx/platform/pull/1267
