### ISSUE TITLE
Does store-devtools have to use eval?

### ISSUE THREAD

**Issue by scriby** [ngrx/platform#977]
https://github.com/ngrx/platform/blob/cb473c00475289509f0924321bb293d0ad1137ca/modules/store-devtools/src/extension.ts#L179

We have some build rules at work which disallow evals. I was wondering if the eval used in store-devtools could use something else to deserialize such as JSON.parse. I wasn't able to see how the action string looks when testing locally (it always seems to be an object for me).

Thanks,

Chris

**Comment by MikeRyanDev** [comment]
Unfortunately not. We don't have control over how the Redux Devtools extension serializes actions that are dispatched back to the main thread.
