### ISSUE TITLE
Devtools slider overrides states

### ISSUE THREAD

**Issue by slavede** [ngrx/platform#981]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
When using slider old state is being mutated.
## Expected behavior:

Old state should not be changed when using slider

## Minimal reproduction of the problem with instructions:

First state change (orange getting true):
![image](https://user-images.githubusercontent.com/2838038/39049641-9335c92e-44a2-11e8-9afa-6b9cf702c933.png)

Second state change (pink getting true, orange is true from step 1)
![image](https://user-images.githubusercontent.com/2838038/39049648-9ce11082-44a2-11e8-8b42-6ed307204198.png)

Now, as soon as I start sliding, first state is being overriden and it remains that way even when I turn off slider.

![image](https://user-images.githubusercontent.com/2838038/39049671-b8332046-44a2-11e8-81a2-f5b5faf4cf61.png)

Shouldn't first state be the sam as first time I've seen it?

## Version of affected browser(s),operating system(s), npm, node and ngrx:
Chrome

λ ng --version

Angular CLI: 1.7.4
Node: 6.11.2
OS: win32 x64
Angular: 5.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0

## Other information:

Notice that time is updated in each action dispatched when using slider? Is that a feature or a bug.

**Comment by dummdidumm** [comment]
How does you reducer look like? Maybe you modify it in an impure way?

**Comment by slavede** [comment]
`   
      
    case (LightActions.TURN_ON_LIGHT): {
      const oldState = {...state};

      if (!oldState.colors[action.payload.color]) {
        oldState.litLights++;
      }
      oldState.colors[action.payload.color] = true;

      return oldState;
    }

    case (LightActions.TURN_OFF_LIGHT): {
      const oldState = {...state};
      if (oldState.colors[action.payload.color]) {
        oldState.litLights--;
      }

      oldState.colors[action.payload.color] = false;

      return oldState;
    }
`

**Comment by slavede** [comment]
Obviously my understanding of spread operator was wrong. Sorry for a bad bug report and thanks for the help
