### ISSUE TITLE
Inconsistent naming

### ISSUE THREAD

**Issue by martzcodes** [ngrx/platform#983]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## What is the current behavior?
I'm attempting to map out a step-by-step procedure for generating the example app and I've noticed there are a few filenames that are inconsistent:

```
login-form.component.ts
login-form.component.spec.ts
login-page.component.ts
login-page.component.spec.ts
auth.effects.ts
auth.effects.spec.ts
auth-guard.service.ts
auth-guard.service.spec.ts
auth.service.ts
```

## Expected behavior:
Everything else doesn't have the `.component|.effects|.service` parts of the names.

I also haven't found an easy way with angular-cli to rename files, I've been having to use a rename script to regex remove all of these names.  It would make it easier to reproduce if everything had their original file types in the names.

## Other information:
This isn't a huge deal, but I'm planning on writing up the step-by-step instructions to recreate the example app anyways, so maybe I can submit a PR for the instructions as part of the README and fix the file names while I'm at it?

**Comment by brandonroberts** [comment]
I think a good first step is just to submit a PR renaming the files.

**Comment by martzcodes** [comment]
@brandonroberts I think the question is... rename them to remove the component|effects|service etc to be inconsistent with angular-cli or add component|effects|service etc tot he files that don't have them to be consistent (I realize this way would add some redundant words to the file path)

**Comment by brandonroberts** [comment]
Add the `component|effects|service|etc` to be consistent with what the cli generates
