### ISSUE TITLE
ngrx/store throws run time error when using createFeatureSelector with a class

### ISSUE THREAD

**Issue by joshvito** [ngrx/platform#987]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

When the application bootstraps, it throws an error that `Uncaught TypeError: <CLASS> is not a constructor`.

## Expected behavior:

Expect the the Store/Application to start up without error.

## Minimal reproduction of the problem with instructions:
1. Create a js `<Class>` that extends an Immutable `Record`, that implements an `Interface`.
2. Use that class in defining a selector, e.g. `export const getClassThings = 
    createFeatureSelector<Class>('classSelectorThings');`
3. Use the selector in a provider in your angular application, e.g. 
```
/** provider.ts */

// this works 
this.things$ = this._store.select('classSelectorThings');

// this fails at runtime with the error
// this is one of the methods of ngrx i want to use !!
this.things$ = this._store.pipe(select(_RootReducer.getClassThings));
```

I have built a bare minimum [Plunker](https://plnkr.co/edit/oQb5327j6zNoNyfP2Ulu?p=preview) to show the error. You can see the error in the console when the plunk loads. In the case of application, the error prevents the app from loading.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
npm: 5.8.0
node: 8.10.0
angular: 5.2.10
ngrx: 5.2.0
immutable: 3.8.2
rxjs: 5.5.10
## Other information:
I've documented the problem a bit more extensively on SO at https://stackoverflow.com/questions/49134461/ngrx-store-throws-run-time-error-when-using-createfeatureselector-with-a-class#

**Comment by brandonroberts** [comment]
@joshvito I'm unable to see the error you described in the plunker. I pinned RxJS to 5.5.6 due to the latest release and the example starts up without any errors.

**Comment by joshvito** [comment]
@brandonroberts Here is the error.

**Comment by brandonroberts** [comment]
Here is a working plunker https://plnkr.co/edit/7q8Ripi4SSf0kJaS

**Comment by joshvito** [comment]
@brandonroberts here is the error shown in the plunker you shared

**Comment by tdeschryver** [comment]
@joshvito I think the error you're seeing is from plunker itself. Not from the angular app.

**Comment by joshvito** [comment]
I can reliably reproduce it with local code outside of Plunker. If you need me to set up a github repo with the bare minimum, I will.

**Comment by brandonroberts** [comment]
Yes, that would be ideal. Thanks

**Comment by joshvito** [comment]
ok, stay tuned.

**Comment by brandonroberts** [comment]
@tdeschryver no worries :+1:

@joshvito if that solves your issue, you can close this or I'll just close it within the next couple of days.

**Comment by joshvito** [comment]
@brandonroberts @tdeschryver Thanks to both of you. This definitely fixes the problem in the example I supplied. This also seems be the case for the problem in my actual app. Time for some refactoring. :)
