### ISSUE TITLE
Generate a changelog when publishing releases

### ISSUE THREAD

**Issue by MikeRyanDev** [ngrx/platform#99]
Use [Conventional Changelog](https://github.com/conventional-changelog/conventional-changelog) to generate a changelog when publishing packages.

**Comment by bfricka** [comment]
I was just going to open this issue! I'll look into taking care of this when I get a moment.

**Comment by chapati23** [comment]
Exactly what I was looking for :) is there _any_ overview of changes with v1.x/2.x other than the migration guide somewhere?

**Comment by Jefiozie** [comment]
@bfricka  If you don't find the time i'm also willing to help.
